
internal interface AEJLAOKEPFC
{
	// RVA: -1 Offset: -1 Slot: 0
	EDOHBJAPLPF_JsonData AEFEIKGDBMD(JNMFKOHFAFB_PublicStatus.KNHIPBADANI KDIFMECGNIC);

	// RVA: -1 Offset: -1 Slot: 1
	EDOHBJAPLPF_JsonData LPGBJBHFINB(JNMFKOHFAFB_PublicStatus.ONCMONJIPCD IDLHJIOMJBK);
}
