
// Namespace: 
public class AFEHLCGHAEE // TypeDefIndex: 8663
{
	// Fields
	public static string FAIOPNOJIBF; // 0x0
	public static string JIBNPJCIALH; // 0x4
	public static string JNPCEKKNEBF; // 0x8
	public static string KLKOINDHOHG; // 0xC
	public static string JMPEGAACBKA; // 0x10
	public static string ADCMNODJBGJ; // 0x14
	public static string MDIBIIHAAPN; // 0x18
	public static string CIGKEJEONGE; // 0x1C
	public static string CDOBCKMHAOK; // 0x20
	public static string ODNOJKHHEOP; // 0x24
	public static string MJBKGOJBPAD; // 0x28
	public static string LKIFDCEKDCK; // 0x2C
	public static string FFKMJNHFFFL; // 0x30
	public static string NCDPBLBDOCM; // 0x34
	public static string JBLAANIMKKH; // 0x38
	public static string ELLLLCLGECP; // 0x3C
	public static string ECHKEPABLIP; // 0x40
	public static string MDKELFPNCDB; // 0x44
	public static string LHKFKIKEJHN; // 0x48
	public static string DDAJLEKFCPH; // 0x4C
	public static string KFCIJBLDHOK; // 0x50
	public static string KFOCBNDNHDJ; // 0x54
	public static string AJAGMMHPBBC; // 0x58
	public static string EOCKBGONGEN; // 0x5C
	public static string FNLNIKFNHAM; // 0x60
	public static string GPCCCPHPDNL; // 0x64
	public static string CPBFAMJEODF; // 0x68
	public static string LDKEOMCNLBE; // 0x6C
	public static string MJMPANIBFED; // 0x70
	public static string NCDHKKCCGOD; // 0x74
	public static string MKANHLNEEGL; // 0x78
	public static string EMOLGEDEEJP; // 0x7C
	public static string ABFADMDAAKJ; // 0x80
	public static string EMHFDJEFIHG; // 0x84
	public static string EPKOHDLIKAN; // 0x88
	public static string FODKKJIDDKN; // 0x8C
	public static string NLFMKOJHAHJ; // 0x90
	public static string CNDDKMJAIBG; // 0x94
	public static string KAPMOPMDHJE; // 0x98
	public static string DJJGPACGEMM; // 0x9C
	public static string FCEJJEPFIPH; // 0xA0
	public static string LCAJFJMHHLG; // 0xA4
	public static string KMIDKGMIIBK; // 0xA8
	public static string GPPOJHNNINK; // 0xAC
	public static string PIJNJBJMFHL; // 0xB0
	public static string FEKOBIFJLAO; // 0xB4
	public static string NJCFGJPBOFO; // 0xB8
	public static string KFNDHKFLPPK; // 0xBC
	public static string LJNAKDMILMC; // 0xC0
	public static string FPOMEEJFBIG; // 0xC4
	public static string PLMHOKJIPJK; // 0xC8
	public static string DANMJLOBLIE; // 0xCC
	public static string OOIJCMLEAJP; // 0xD0
	public static string BIOGKIEECGN; // 0xD4
	public static string IIPIPIABGDG; // 0xD8
	public static string AIPJAKIFMPN; // 0xDC
	public static string DHDHHHOAIKF; // 0xE0
	public static string DIPKCALNIII; // 0xE4
	public static string LBMELIONKKB; // 0xE8
	public static string CEDLLCCONJP; // 0xEC
	public static string JGDNCEANEBB; // 0xF0
	public static string GLKOMLHCBEO; // 0xF4
	public static string EHODALENBEL; // 0xF8
	public static string EBIFBMEKEIL; // 0xFC
	public static string OLDAGCNLJOI; // 0x100
	public static string OHMCIEMIKCE; // 0x104
	public static string PINEFBCMNKP; // 0x108
	public static string FDFDHIFMOGE; // 0x10C
	public static string FHFONPEHLMN; // 0x110
	public static string FGKGELOJBJK; // 0x114
	public static string LFHILMNKGCB; // 0x118
	public static string JLNEMPJICEH; // 0x11C
	public static string JKONPJKILCH; // 0x120
	public static string BKIFLJAMJGG; // 0x124
	public static string DKOPDNHDLIA; // 0x128
	public static string PIJEEAOMMGA; // 0x12C
	public static string KACECFNECON; // 0x130
	public static string PIAOCCDBDHE; // 0x134
	public static string NPMIJMFMEKB; // 0x138
	public static string DEAENIIEPPA; // 0x13C
	public static string LHBNIAJDIGA; // 0x140
	public static string AOLLIMFKDAA; // 0x144
	public static string EIANMIIKPDH; // 0x148
	public static string DMFAMLPFNPO; // 0x14C
	public static string IIGDIHEALFE; // 0x150
	public static string JEDMLKOECHN; // 0x154
	public static string LBOIEJKNCGG; // 0x158
	public static string JLJJHDGEHLK; // 0x15C
	public static string JHOIMONJKLG; // 0x160
	public static string ICDIFNOADPK; // 0x164
	public static string PBJKGCLJFOE; // 0x168
	public static string NONBCCLGBAO; // 0x16C
	public static string JMOCLCGBNCP; // 0x170
	public static string MIMLMJGGNJH; // 0x174
	public static string NPHNBKNPEML; // 0x178
	public static string AJACFHJACGK; // 0x17C
	public static string CAFOACMKJKJ; // 0x180
	public static string AFFLGPAJMHC; // 0x184
	public static string IMJJCJPNHFJ; // 0x188
	public static string PLHJLBFGGGN; // 0x18C
	public static string MCHAINJKMEB; // 0x190
	public static string DKHIHHMOIKM; // 0x194
	public static string KCGJGPOFOCD; // 0x198
	public static string HEOLEHDFLJO; // 0x19C
	public static string EJPKFBHNDGI; // 0x1A0
	public static string CBACMMCDGEM; // 0x1A4
	public static string BPNPBJALGHM; // 0x1A8
	public static string JOMCOLHEBBI; // 0x1AC
	public static string JCAPANAALDF; // 0x1B0
	public static string HCAIJHCMAAC; // 0x1B4
	public static string KLNLADAPAME; // 0x1B8
	public static string LOLLNDMKPPH; // 0x1BC
	public static string KOHMHBGOFFI; // 0x1C0
	public static string ILLPEMPBDJG; // 0x1C4
	public static string JBKMAPLCBMO; // 0x1C8
	public static string BCANABIAIIP; // 0x1CC
	public static string PKLIPLFIDED; // 0x1D0
	public static string CFJKNAIOEAN; // 0x1D4
	public static string PNELHHHCFAI; // 0x1D8
	public static string FHBJOLPCAPN; // 0x1DC
	public static string KJGHLKIBGGD; // 0x1E0
	public static string OEGHFGCHIFA; // 0x1E4
	public static string AEMHPNJBFFD; // 0x1E8
	public static string FOILNHKHHDF; // 0x1EC
	public static string BIEPKMIADMM; // 0x1F0
	public static string KMFHHOANPFH; // 0x1F4
	public static string INAECNHELAM; // 0x1F8
	public static string HBHMAKNGKFK; // 0x1FC
	public static string AJKPKMHBHEF; // 0x200
	public static string FCBJFKGDINH; // 0x204
	public static string HECMDAIBGOM; // 0x208
	public static string LPEIACGJOFN; // 0x20C
	public static string NMICBJDPLOH; // 0x210
	public static string NHPDJADJNCL; // 0x214
	public static string COEBIDJMMCH; // 0x218
	public static string BEJFAOEGBLE; // 0x21C
	public static string HEOKKHAGEIE; // 0x220
	public static string LAMMILPNINO; // 0x224
	public static string GLMGHMCOMEC; // 0x228
	public static string HMFFHLPNMPH; // 0x22C
	public static string HEIPELEDAIK; // 0x230
	public static string OPCGCKFFEOO; // 0x234
	public static string IPFEKNMBEBI; // 0x238
	public static string DHIPGHBJLIL; // 0x23C
	public static string BMIJDLBGFNP; // 0x240
	public static string KGPJGLFLDBE; // 0x244
	public static string CHEAKMNHEAM; // 0x248
	public static string NNAACLEBIGE; // 0x24C
	public static string IPAAOFCGEAB; // 0x250
	public static string NIKCFOALFJC; // 0x254
	public static string DLDKPDCPHLN; // 0x258
	public static string DDBEJNGJIPF; // 0x25C
	public static string KLHFCNIDECB; // 0x260
	public static string AEBENOJEGOJ; // 0x264
	public static string ILJEIMNCKME; // 0x268
	public static string ODMJFHDIGLP; // 0x26C
	public static string PCMDFNHIEBE; // 0x270
	public static string EPBBNFDFLLD; // 0x274
	public static string EJKHAFIALGK; // 0x278
	public static string EGPADBNAOKP; // 0x27C
	public static string KPECMLFDLOI; // 0x280
	public static string IIMOOLKIOHC; // 0x284
	public static string FLNJLKKAFPB; // 0x288
	public static string EOKMNCPJMCO; // 0x28C
	public static string KGHBOICMCPP; // 0x290
	public static string PLALNIIBLOF; // 0x294
	public static string HJNNKCMLGFL; // 0x298
	public static string MMOJHIPAAIK; // 0x29C
	public static string MHKFDBLMOGF; // 0x2A0
	public static string FKIBPHGINAE; // 0x2A4
	public static string EHKJFNAABMC; // 0x2A8
	public static string PNAAOBECMPA; // 0x2AC
	public static string OEOIHIIIMCK; // 0x2B0
	public static string CBDOEDKIOJK; // 0x2B4
	public static string FDHHPHPCKOE; // 0x2B8
	public static string DOGDHKIEBJA; // 0x2BC
	public static string HDBEJBBPPBK; // 0x2C0
	public static string JPHOOKPHBLD; // 0x2C4
	public static string PDBPFJJCADD; // 0x2C8
	public static string EHDDADDKMFI; // 0x2CC
	public static string LJELGFAFGAB; // 0x2D0
	public static string MEPOLGBKLFD; // 0x2D4
	public static string JGEIIONMJMI; // 0x2D8
	public static string PAIIHEJIGKO; // 0x2DC
	public static string ILJODCEHHGH; // 0x2E0
	public static string ACABEFKBBEN; // 0x2E4
	public static string PAFFIBGPOJN; // 0x2E8
	public static string PNMKPKMDOND; // 0x2EC
	public static string JJPFFMADLLB; // 0x2F0
	public static string AICBBOHEIMG; // 0x2F4
	public static string JPDPFGFMKHK; // 0x2F8
	public static string JDHJEINPJLL; // 0x2FC
	public static string CCGECKBMBFM; // 0x300
	public static string LKNKFAPHLOH; // 0x304
	public static string NPPGKNGIFGK; // 0x308
	public static string JPFFIBCDCNJ; // 0x30C
	public static string DNBPICNPJNE; // 0x310
	public static string IBOGLMCNFBK; // 0x314
	public static string GIDKKHFHALL; // 0x318
	public static string DHMKKDEKJID; // 0x31C
	public static string GPHPNEGGGBG; // 0x320
	public static string EEDAHFGPNPH; // 0x324
	public static string NKIGFPJPALK; // 0x328
	public static string OANKLPBCKGN; // 0x32C
	public static string GPNPBHLLHDI; // 0x330
	public static string AIFCAAHMFBD; // 0x334
	public static string BBEPEDHIJED; // 0x338
	public static string HILOBIHECNN; // 0x33C
	public static string MKKGKKHABEK; // 0x340
	public static string JKPPKAHPPKH; // 0x344
	public static string EJDDPLLEGEF; // 0x348
	public static string MMPCPKODGKI; // 0x34C
	public static string FNAEGLFKDBI; // 0x350
	public static string MDADLCOCEBN; // 0x354
	public static string IPLCMPCDNJJ; // 0x358
	public static string AKOJJJLPCKA; // 0x35C
	public static string FEKLEAOHIFG; // 0x360
	public static string LOIIMNGCHBI; // 0x364
	public static string BGKIIFCGOLI; // 0x368
	public static string JCIBKDHKNFH; // 0x36C
	public static string JPFMJHLCMJL; // 0x370
	public static string FHGGNFABJBB; // 0x374
	public static string DLMDINBHGBG; // 0x378
	public static string IAPEBMMOLMM; // 0x37C
	public static string GNKMHCKFADN; // 0x380
	public static string ANAJIAENLNB; // 0x384
	public static string OCNINMIMHGC; // 0x388
	public static string EBCFHFIOHBN; // 0x38C
	public static string IKPIDCFOFEA; // 0x390
	public static string OFJFGMDBFPK; // 0x394
	public static string LHEIIHKDMPA; // 0x398
	public static string LPIKIBKFOJE; // 0x39C
	public static string JCHHIPOPNIN; // 0x3A0
	public static string JOBJHJCIMDN; // 0x3A4
	public static string EFHCKFKLJDK; // 0x3A8
	public static string PFDDNKEOKBF; // 0x3AC
	public static string PJFKNNNDMIA; // 0x3B0
	public static string EBDNICPAFLB; // 0x3B4
	public static string ADPPAIPFHML; // 0x3B8
	public static string JFMEKPDHJPP; // 0x3BC
	public static string HPPHKHBPFMJ; // 0x3C0
	public static string IFCJDGINBGF; // 0x3C4
	public static string CEBOHGGJBMN; // 0x3C8
	public static string PGOJILPILNG; // 0x3CC
	public static string EIDAEIIGKLB; // 0x3D0
	public static string FMGKFCHAOCF; // 0x3D4
	public static string KBNGOBEAHIC; // 0x3D8
	public static string MJBODMOLOBC; // 0x3DC
	public static string ADLGKMBIPCA; // 0x3E0
	public static string NEILEPPJKIN; // 0x3E4
	public static string EMDMJBBKMHJ; // 0x3E8
	public static string EJFAEKPGKNJ; // 0x3EC
	public static string NHBLDIPBHNF; // 0x3F0
	public static string GJMJHEPMLOA; // 0x3F4
	public static string NKFIIOGCDFM; // 0x3F8
	public static string KAKFEGGEKLB; // 0x3FC
	public static string PGPMMHGFIGH; // 0x400
	public static string JOIEHMBKJHI; // 0x404
	public static string IHBCBKDPBAJ; // 0x408
	public static string NMALAMICDGP; // 0x40C
	public static string IJHBIMNKOMC; // 0x410
	public static string DMEDKJPOLCH; // 0x414
	public static string LGPEAEHNAFJ; // 0x418
	public static string GDBAFBHIOAK; // 0x41C
	public static string GMECIBOJCFF; // 0x420
	public static string MBAMIOJNGBD; // 0x424
	public static string CFMBELIAJIB; // 0x428
	public static string LLGBAPAACLL; // 0x42C
	public static string NMHGCOLMPJA; // 0x430
	public static string DDGFCOPPBBN; // 0x434
	public static string LGADCGFMLLD; // 0x438
	public static string GEFHAMEJHKD; // 0x43C
	public static string PGPGPJNBIOH; // 0x440
	public static string MKBCAPPIKMM; // 0x444
	public static string MMEIOJKLCKK; // 0x448
	public static string LKHAAGIJEPG; // 0x44C
	public static string HPPOFOIJJMB; // 0x450
	public static string MFGHMHBADMC; // 0x454
	public static string PJPGBPACBFA; // 0x458
	public static string KBOLNIBLIND; // 0x45C
	public static string DIGMEFPEBBC; // 0x460
	public static string KNEDJFLCCLN; // 0x464
	public static string DJDFHJNNDGF; // 0x468
	public static string HANMDEBPBHG; // 0x46C
	public static string KIFJKGDBDBH; // 0x470
	public static string KKGPPDLFDKA; // 0x474
	public static string DIHMKEMHPHF; // 0x478
	public static string FBMPJABPOGN; // 0x47C
	public static string FMGNEKNBJFN; // 0x480
	public static string NANNGLGOFKH; // 0x484
	public static string JPHDGGNAKMO; // 0x488
	public static string BABAGPKAONA; // 0x48C
	public static string HBOIBKJEIAP; // 0x490
	public static string OIJLNFJALJP; // 0x494
	public static string BOGJDJLNAGH; // 0x498
	public static string BAOFEFFADPD; // 0x49C
	public static string BEPIOAIFCEC; // 0x4A0
	public static string CDMGDFLPPHN; // 0x4A4
	public static string DAHGIMDKPCP; // 0x4A8
	public static string GNHMCCLFBLB; // 0x4AC
	public static string NONMPJBNBNN; // 0x4B0
	public static string INDDJNMPONH; // 0x4B4
	public static string PMGMELIKALB; // 0x4B8
	public static string COIODGJDJEJ; // 0x4BC
	public static string IBAKPKKEDJM; // 0x4C0
	public static string OPLELHFKMEO; // 0x4C4
	public static string IEGHKKJJMHI; // 0x4C8
	public static string KAHOBGNOJDP; // 0x4CC
	public static string IOAKMAAFBAJ; // 0x4D0
	public static string MBJIFDBEDAC; // 0x4D4
	public static string EALOBDHOCHP; // 0x4D8
	public static string MOPDHAAPNAN; // 0x4DC
	public static string BGEMEKFIFNI; // 0x4E0
	public static string DOHKJELHMBD; // 0x4E4
	public static string MGHPJNNDCIG; // 0x4E8
	public static string NFHLDFJIBKI; // 0x4EC
	public static string BMOBAOCHNMO; // 0x4F0
	public static string HLCHKCJLEGK; // 0x4F4
	public static string LJEONGIBHGM; // 0x4F8
	public static string MOPBJIOCKML; // 0x4FC
	public static string CEEHDBKCHNJ; // 0x500
	public static string ENMGMCHECGE; // 0x504
	public static string FAENAMBEGMD; // 0x508
	public static string LGFFMGDBIAH; // 0x50C
	public static string HDEBAGHEIKD; // 0x510
	public static string IFILLPEKJFK; // 0x514
	public static string POOHGENNICD; // 0x518
	public static string DBNAGGGJDAB; // 0x51C
	public static string JGNBPFCJLKI; // 0x520
	public static string OKADDOIJGNB; // 0x524
	public static string JJCJCOANHBL; // 0x528
	public static string CNJCFCNLAMO; // 0x52C
	public static string PMACFHICGHG; // 0x530
	public static string EJOECKJNGPD; // 0x534
	public static string HKODBHPMLCP; // 0x538
	public static string JOJMKALFOKN; // 0x53C
	public static string DHGEFEAMAPJ; // 0x540
	public static string CDNKGPHFIHI; // 0x544
	public static string DMICCOMABCE; // 0x548
	public static string CHKKKFBBAAM; // 0x54C
	public static string OMOIGFMNFJB; // 0x550
	public static string GJODJNIHKKF; // 0x554
	public static string BEPCDMFIGJO; // 0x558
	public static string KDIDMAMLBLO; // 0x55C
	public static string CALPJOGCDGL; // 0x560
	public static string DFELEPDHLBF; // 0x564
	public static string BBCPDMKEHAK; // 0x568
	public static string PPFNGGCBJKC; // 0x56C
	public static string LOMHJBIJMOD; // 0x570
	public static string JGOHPDKCJKB; // 0x574
	public static string PJJFEAHIPGL; // 0x578
	public static string ADKJLADBKKK; // 0x57C
	public static string PBHBFBNFPJI; // 0x580
	public static string CMENIBCJJNF; // 0x584
	public static string NEMMJLNMEHB; // 0x588
	public static string NKGJOAEDCPH; // 0x58C
	public static string LCAINKFINEI; // 0x590
	public static string OMBOKLFEAFD; // 0x594
	public static string EBBJPBGHJOL; // 0x598
	public static string BDJMFDKLHPM; // 0x59C
	public static string ALMNMBDELDB; // 0x5A0
	public static string FJOLNJLLJEJ; // 0x5A4
	public static string LEJHEGIMCCL; // 0x5A8
	public static string FEDBLJNOCIH; // 0x5AC
	public static string CJCJBKIMLOB; // 0x5B0
	public static string LKCHLHEOHFF; // 0x5B4
	public static string JHFGJGEAGPH; // 0x5B8
	public static string FDBNFFNFOND; // 0x5BC
	public static string GFENIDOHDFP; // 0x5C0
	public static string EDKECALDABH; // 0x5C4
	public static string EGDEGGMPIGA; // 0x5C8
	public static string PMANOMLMICI; // 0x5CC
	public static string KGHAJGGMPKL; // 0x5D0
	public static string JGJPKLCCOIO; // 0x5D4
	public static string KNDKMLHAONN; // 0x5D8
	public static string IDLHJIOMJBK; // 0x5DC
	public static string LKMHPJKIFDN; // 0x5E0
	public static string CMIGGBMMBKK; // 0x5E4
	public static string NNMPGOAGEOL; // 0x5E8
	public static string FKCAECFAFCG; // 0x5EC
	public static string PHNBNCCDHNG; // 0x5F0
	public static string AGONOGEEGDL; // 0x5F4
	public static string GOPNIDNAFBP; // 0x5F8
	public static string DJEMDOCNBDB; // 0x5FC
	public static string HELBHEPKBJF; // 0x600
	public static string EFIMCLPAEEN; // 0x604
	public static string LDAHLLHCPGJ; // 0x608
	public static string HOPIMOECAFA; // 0x60C
	public static string LDALACBKEJN; // 0x610
	public static string HPGEGOONHGD; // 0x614
	public static string HGEDPFFCDBG; // 0x618
	public static string NGGGMCHJONH; // 0x61C
	public static string KLMPFGOCBHC; // 0x620
	public static string FNEIADJMHHO; // 0x624
	public static string OENPCNBFPDA; // 0x628
	public static string CMCKNKKCNDK; // 0x62C
	public static string CBIKELHFHCA; // 0x630
	public static string GIEBJDKLCDH; // 0x634
	public static string BDINKMHPCPK; // 0x638
	public static string LEMIEPGGAME; // 0x63C
	public static string KBAHNBKMFDL; // 0x640
	public static string PPAOHBBEPKK; // 0x644
	public static string JKPPLHLMPJC; // 0x648
	public static string EGBOHDFBAPB; // 0x64C
	public static string KMIPKHFODIK; // 0x650
	public static string DLCJLEBGBCI; // 0x654
	public static string LJGOOOMOMMA; // 0x658
	public static string HENOGPAINDF; // 0x65C
	public static string JBGEEPFKIGG; // 0x660
	public static string BEHEPILDEGG; // 0x664
	public static string EHGBICNIBKE; // 0x668
	public static string MIKCFEHGNJB; // 0x66C
	public static string BPFKIHKEDHA; // 0x670
	public static string POEGMFKLFJG; // 0x674
	public static string JKAMFMNGEBB; // 0x678
	public static string NPBEKONLDDI; // 0x67C
	public static string LKPHIGAFJKD; // 0x680
	public static string GKOAEJDMLED; // 0x684
	public static string ACBIPLOOEKI; // 0x688
	public static string CEBJHBFKILJ; // 0x68C
	public static string FOFGELKGMAH; // 0x690
	public static string OPFGFINHFCE; // 0x694
	public static string JPHMLLIBLGG; // 0x698
	public static string ABNMKJGNKFO; // 0x69C
	public static string NAJPNHKHKKA; // 0x6A0
	public static string MKNDAOHGOAK; // 0x6A4
	public static string BPDOLDOKJGG; // 0x6A8
	public static string PAGEGFKGCIC; // 0x6AC
	public static string HALGELBLEPE; // 0x6B0
	public static string LAALIAKBNIB; // 0x6B4
	public static string GGGFIKIHJCM; // 0x6B8
	public static string FDGBLNFGBPJ; // 0x6BC
	public static string BPLOEAHOPFI; // 0x6C0
	public static string GABEIDONLNE; // 0x6C4
	public static string MIODKKINJBD; // 0x6C8
	public static string JBFLEDKDFCO; // 0x6CC
	public static string CBOCBLLOMHE; // 0x6D0
	public static string MMOIFDEPIEP; // 0x6D4
	public static string GNBEKAELDMM; // 0x6D8
	public static string IKNALLJDAFH; // 0x6DC
	public static string OJGBNNIJNEM; // 0x6E0
	public static string FDMENECIKEL; // 0x6E4
	public static string FCBDGLEPGFJ; // 0x6E8
	public static string EKFHOJIGHHH; // 0x6EC
	public static string KOOEOKEDJDO; // 0x6F0
	public static string ACGHELNGNGK; // 0x6F4
	public static string FDCFPCMANBN; // 0x6F8
	public static string KOMKKBDABJP; // 0x6FC
	public static string LCJPKJMMIAP; // 0x700
	public static string PANKNKOIIJE; // 0x704
	public static string JJHDDBLNOHA; // 0x708
	public static string CHDDDCCHJJH; // 0x70C
	public static string AIHOJKFNEEN; // 0x710
	public static string AEJPNAKLKED; // 0x714
	public static string CCGDFHKBAKE; // 0x718
	public static string COGJONKKALB; // 0x71C
	public static string EMIJNAFJFJO; // 0x720
	public static string BEKFHEBCPEE; // 0x724
	public static string MKHBDJBODON; // 0x728
	public static string NKCGKLDPNOL; // 0x72C
	public static string LMOBPKIDIHF; // 0x730
	public static string LHMOAJAIJCO; // 0x734
	public static string HBMPOOCGNEN; // 0x738
	public static string OKECOPNBAGP; // 0x73C
	public static string DDMENKOHCGM; // 0x740
	public static string MBJJMIIFNLL; // 0x744
	public static string KKPADIFPHOK; // 0x748
	public static string CIOKHGPEEKE; // 0x74C
	public static string DOOGFEGEKLG; // 0x750
	public static string KCKBGALKNMA; // 0x754
	public static string BFHPKJEKJNN; // 0x758
	public static string NJDCEFLEPEG; // 0x75C
	public static string EIIDPKCBKEK; // 0x760
	public static string EPDPAHNLMKH; // 0x764
	public static string DFJLNPFJGDK; // 0x768
	public static string MIDCDCFCJJM; // 0x76C
	public static string LLHFLCGIMPB; // 0x770
	public static string HLLEEFLLFPD; // 0x774
	public static string ADKDHKMPMHP; // 0x778
	public static string AFKHNFBOMKI; // 0x77C
	public static string HHOCBLMEGGM; // 0x780
	public static string POBGGHEKLIB; // 0x784
	public static string NENOJMFOAOC; // 0x788
	public static string HIMIDIJIGJN; // 0x78C
	public static string POENMEGPHCG; // 0x790
	public static string GJEBPJHECIK; // 0x794
	public static string AKEFCAFBFKJ; // 0x798
	public static string DNDNFAAOOBA; // 0x79C
	public static string AJBPBEALBOB; // 0x7A0
	public static string MCPADDGDKGK; // 0x7A4
	public static string IAGNOJOCBPF; // 0x7A8
	public static string LIDBKCIMCKE; // 0x7AC
	public static string HBKBKHACHHI; // 0x7B0
	public static string AFPONJEJKCO; // 0x7B4
	public static string OJIMENABACH; // 0x7B8
	public static string LCFIHFMFICM; // 0x7BC
	public static string KHEBCAGHEIN; // 0x7C0
	public static string MFOCHEBHHNC; // 0x7C4
	public static string FJGCDPLCIAK; // 0x7C8
	public static string KNKPHBFGDHC; // 0x7CC
	public static string LNDEFMALKAN; // 0x7D0
	public static string ADGLNAGAGBK; // 0x7D4
	public static string GJDKHDLKONI; // 0x7D8
	public static string MIFLBHBPBNF; // 0x7DC
	public static string IIGPLLECFND; // 0x7E0
	public static string EAGOBOBJLAD; // 0x7E4
	public static string IJEKNCDIIAE; // 0x7E8
	public static string BMPFHHHCNJC; // 0x7EC
	public static string PBEKKMOPENN; // 0x7F0
	public static string MLGKDBJLNBM; // 0x7F4
	public static string NMNLJFIDFJE; // 0x7F8
	public static string FDBOPFEOENF; // 0x7FC
	public static string NAIMIHBNPPC; // 0x800
	public static string FBHMAIEDEGJ; // 0x804
	public static string IAGMJKNPIFD; // 0x808
	public static string GLHKICCPGKJ; // 0x80C
	public static string GPPGDDNHNLF; // 0x810
	public static string ADKIDBJCAJA; // 0x814
	public static string OMOBCBAEJGH; // 0x818
	public static string FEOKKEPAIBB; // 0x81C
	public static string CIAGPPFPMCL; // 0x820
	public static string MIMGPBHAJCO; // 0x824
	public static string OIMLBHPAMGD; // 0x828
	public static string BHFBDOGBOKL; // 0x82C
	public static string IFNLEKOILPM; // 0x830
	public static string AGBCJMMMLON; // 0x834
	public static string NBBLIKLDGKL; // 0x838
	public static string KLJGEHBKMMG; // 0x83C
	public static string KKAKGFJKMKL; // 0x840
	public static string NHPCKCOPKAM; // 0x844
	public static string GMLEMFDFKLG; // 0x848
	public static string ALDCIBEHAAG; // 0x84C
	public static string KLMIFEKNBLL; // 0x850
	public static string BGBKGFDLCME; // 0x854
	public static string CJEKGLGBIHF; // 0x858
	public static string JMAGFEENOED; // 0x85C
	public static string LNADEEECINK; // 0x860
	public static string KOHNLDKIKPC; // 0x864
	public static string HEBKEJBDCBH; // 0x868
	public static string OCLBNLOCOPC; // 0x86C
	public static string DLLLHFLGBAP; // 0x870
	public static string CJNNMLLEKEF; // 0x874
	public static string CALJIGKCAAH; // 0x878
	public static string MEFHDDNABLM; // 0x87C
	public static string MCGIGKFLHIL; // 0x880
	public static string LOJCJMGPMIG; // 0x884
	public static string COJJHFBKGML; // 0x888
	public static string ABFKGMFCAIL; // 0x88C
	public static string MOCFAHFOHPK; // 0x890
	public static string NLKEBAOBJCM; // 0x894
	public static string JOBKIDDLCPL; // 0x898
	public static string IKOFFIOMOME; // 0x89C
	public static string BDEOMEBFDFF; // 0x8A0
	public static string NJGNGFNKHAH; // 0x8A4
	public static string NLINIIGAEFN; // 0x8A8
	public static string NDFOAINJPIN; // 0x8AC
	public static string INJIPPBFMIG; // 0x8B0
	public static string ELBJIFCDJGO; // 0x8B4
	public static string KIOKIBGIHBM; // 0x8B8
	public static string NNCFCPEOODE; // 0x8BC
	public static string CMKKFCGBILD; // 0x8C0
	public static string PAMBKEPLBCC; // 0x8C4
	public static string KOOJOBAPBBE; // 0x8C8
	public static string LFBOCKNGLNK; // 0x8CC
	public static string AGNHPHEJKMK; // 0x8D0
	public static string HHGLNNHPIPE; // 0x8D4
	public static string OCGFKMHNEOF; // 0x8D8
	public static string CFHOMPIKIGK; // 0x8DC
	public static string KJMLLBDLKCG; // 0x8E0
	public static string IPEKDLNEOFI; // 0x8E4
	public static string NBPNNNBCGFG; // 0x8E8
	public static string PMGBOJCCFPI; // 0x8EC
	public static string IBOHALOCJDL; // 0x8F0
	public static string ILKEDIDGNLP; // 0x8F4
	public static string EEDDJLLIOBD; // 0x8F8
	public static string GPNOEFHGOJG; // 0x8FC
	public static string OOKGKIONGJF; // 0x900
	public static string PMKIBGEHGON; // 0x904
	public static string FBFLDFMFFOH; // 0x908
	public static string EMEGKEGFJBK; // 0x90C
	public static string NFIOKIBPJCJ; // 0x910
	public static string FEFDGBPFKBJ; // 0x914
	public static string NOAKONCNNPO; // 0x918
	public static string FIKLIDJBPBB; // 0x91C
	public static string CHIJNHKPIKP; // 0x920
	public static string HAAJGNCFNJM; // 0x924
	public static string PFJJFCPPNIN; // 0x928
	public static string NDDDBPKPMDK; // 0x92C
	public static string EIKFCGOFJHO; // 0x930
	public static string NGOONCOAOMI; // 0x934
	public static string LFNJMJBHGDA; // 0x938
	public static string DMJGDDEACMD; // 0x93C
	public static string JJLLJCEJENB; // 0x940
	public static string MLKFDMFDFCE; // 0x944
	public static string ECLAOLBGCDD; // 0x948
	public static string CAJKBDLCGOD; // 0x94C
	public static string IMEPEOAFIIB; // 0x950
	public static string PNIFJJPHLDH; // 0x954
	public static string ABLOIBMGLFD; // 0x958
	public static string KGMLFAFPOKP; // 0x95C
	public static string KOEAHHAHDNP; // 0x960
	public static string ICJEDACBMMF; // 0x964
	public static string JMEMGIPGGIK; // 0x968
	public static string BHLDDINNGFJ; // 0x96C
	public static string FHANAFNKIFC; // 0x970
	public static string IKCBPLIFBOJ; // 0x974
	public static string GLJINGPAEDM; // 0x978
	public static string ONOPACPKFPK; // 0x97C
	public static string JEENEHPOCFN; // 0x980
	public static string BLJOJBEKFAH; // 0x984
	public static string BEBJKJKBOGH; // 0x988
	public static string MOEDCMHBCHN; // 0x98C
	public static string COCEIPAKJKF; // 0x990
	public static string BKCJPIPJCCM; // 0x994
	public static string GJDNBENICPF; // 0x998
	public static string KHGJIGNHAGD; // 0x99C
	public static string IANDDEFHKAN; // 0x9A0
	public static string BIAPEOAOJNG; // 0x9A4
	public static string OJOHFHPAJDI; // 0x9A8
	public static string KBMDMEEMGLK; // 0x9AC
	public static string ILHOCHKPGAA; // 0x9B0
	public static string MINAGJOIGOP; // 0x9B4
	public static string FFMHJIJBKEN; // 0x9B8
	public static string JPILDOGJLDG; // 0x9BC
	public static string KBJAHKHGHAN; // 0x9C0
	public static string NNONCOCHGMD; // 0x9C4
	public static string NOHIMPJDOCK; // 0x9C8
	public static string AIFGNKMBFCD; // 0x9CC
	public static string POEPEIKKIEA; // 0x9D0
	public static string BDLNMOIOMHK; // 0x9D4
	public static string LHICAPGLBOF; // 0x9D8
	public static string PCBJHBCNNGD; // 0x9DC
	public static string IAFEEMCLNMC; // 0x9E0
	public static string DPHEHNKLHEI; // 0x9E4
	public static string OLKHBHLOKJI; // 0x9E8
	public static string PGLELFPNOPI; // 0x9EC
	public static string KNIFCANOHOC; // 0x9F0
	public static string BKEIOLFMMDH; // 0x9F4
	public static string NKMNFPMMJND; // 0x9F8
	public static string HMJPPJNLBCM; // 0x9FC
	public static string LNKKMBCDPHH; // 0xA00
	public static string FHCAFLCLGAA; // 0xA04
	public static string CIJOGNLMIKM; // 0xA08
	public static string JLPEGFAMKPK; // 0xA0C
	public static string JNLKJCDFFMM; // 0xA10
	public static string OGKKJJFAFHE; // 0xA14
	public static string EOODMBFCBCP; // 0xA18
	public static string PIGLAEFPNEK; // 0xA1C
	public static string OCAMDLMPBGA; // 0xA20
	public static string DMDLAIOJKPM; // 0xA24
	public static string HFEPDDFBDDA; // 0xA28
	public static string MHHNOKGNJFN; // 0xA2C
	public static string ALJIHHGHCOG; // 0xA30
	public static string LAKMJONILFH; // 0xA34
	public static string KBDOBONLNOJ; // 0xA38
	public static string DFOIEJOKDKJ; // 0xA3C
	public static string DNBFMLBNAEE; // 0xA40
	public static string AHJNPEAMCCH; // 0xA44
	public static string CPAGFPBNGBC; // 0xA48
	public static string DLAIGBEOGNN; // 0xA4C
	public static string FBAIDPHDEBA; // 0xA50
	public static string LLNDMKBBNIJ; // 0xA54
	public static string AGPKGMFOJHC; // 0xA58
	public static string EMBKPPHENAN; // 0xA5C
	public static string HLMLHOFHIOK; // 0xA60
	public static string DHMKKJNGDEN; // 0xA64
	public static string CCCHFLGBMAF; // 0xA68
	public static string KNJJPDDBKBA; // 0xA6C
	public static string KBFOIECIADN; // 0xA70
	public static string AHKBMJPFIMB; // 0xA74
	public static string CBBLAMDGOGK; // 0xA78
	public static string AKNELONELJK; // 0xA7C
	public static string HGDKJEDIHPG; // 0xA80
	public static string PGALIMGEPIB; // 0xA84
	public static string KHPFMNAKBKE; // 0xA88
	public static string ADAFEPKKBKP; // 0xA8C
	public static string EGPELMDJDCC; // 0xA90
	public static string GKHGCPODNEG; // 0xA94
	public static string HBODCMLFDOB; // 0xA98
	public static string FELIFAHDLON; // 0xA9C
	public static string NPHJIIHDEDD; // 0xAA0
	public static string MBINHJCEALB; // 0xAA4
	public static string PGCEGEJOOON; // 0xAA8
	public static string PLGFGIAHDHJ; // 0xAAC
	public static string PFNBMPCIIJJ; // 0xAB0
	public static string DLBLONNCCCE; // 0xAB4
	public static string HCFCNNPOJAE; // 0xAB8
	public static string LHAFADCJBME; // 0xABC
	public static string NKAKDIEKAGL; // 0xAC0
	public static string ACGLMKEBMDL; // 0xAC4
	public static string MOHDLLIJELH; // 0xAC8
	public static string CPGFPEDMDEH; // 0xACC
	public static string GELKOLABEIF; // 0xAD0
	public static string BCIDCCGECBG; // 0xAD4
	public static string JPJMMIAFCEO; // 0xAD8
	public static string HBJDJDKMNBF; // 0xADC
	public static string GOBMACPDDCL; // 0xAE0
	public static string MAFAIIHJAFG; // 0xAE4
	public static string JGGKJBCGKCC; // 0xAE8
	public static string BPEAIOBHMFD; // 0xAEC
	public static string FEIAGLJKPAI; // 0xAF0
	public static string MPFBADANFCC; // 0xAF4
	public static string JPBJOGBGKGA; // 0xAF8
	public static string HPGPJAPCKKF; // 0xAFC
	public static string GGLICPAANFE; // 0xB00
	public static string BFINGCJHOHI; // 0xB04
	public static string BMFEGOMNECF; // 0xB08
	public static string HIAIAJJPCDE; // 0xB0C
	public static string EAHPKPADCPL; // 0xB10
	public static string MHKCPJDNJKI; // 0xB14
	public static string PJDEOPMBGKJ; // 0xB18
	public static string LKHFPLMLHEN; // 0xB1C
	public static string FGCAJEAIABA; // 0xB20
	public static string NCLAPHIAIDM; // 0xB24
	public static string FANICHGKOML; // 0xB28
	public static string OCDBDAFJPBG; // 0xB2C
	public static string BCCOMAODPJI; // 0xB30
	public static string IDIDIJGPPIO; // 0xB34
	public static string APFOBLMCLAO; // 0xB38
	public static string BBEPLKNMICJ; // 0xB3C
	public static string ENJCKADOFBD; // 0xB40
	public static string DPOGAFBDEOH; // 0xB44
	public static string GBJFNGCDKPM; // 0xB48
	public static string EPMALNDIDJM; // 0xB4C
	public static string PNBJCNGCELE; // 0xB50
	public static string PNADPHDIBBN; // 0xB54
	public static string GAPHJJLNLKD; // 0xB58
	public static string EPEKGCONFFP; // 0xB5C
	public static string APJBBOHHFNE; // 0xB60
	public static string PIPCIMIALOO; // 0xB64
	public static string MNLAJEDKLCI; // 0xB68
	public static string JLEIHOEGMOP; // 0xB6C
	public static string HPBPDHPIBGN; // 0xB70
	public static string GOKJLBDJOLA; // 0xB74
	public static string IKMKEMAAGOH; // 0xB78
	public static string AEOEJNODHLC; // 0xB7C
	public static string HMFDJHEEGNN; // 0xB80
	public static string NJIDHLPGBFO; // 0xB84
	public static string NDFIEMPPMLF; // 0xB88

	// Methods

	// // RVA: 0x15BE3D8 Offset: 0x15BE3D8 VA: 0x15BE3D8
	// public static void BAFFAONJPCE() { }

	// // RVA: 0x15BE3DC Offset: 0x15BE3DC VA: 0x15BE3DC
	// public void .ctor() { }

	// // RVA: 0x15BE3E4 Offset: 0x15BE3E4 VA: 0x15BE3E4
	static AFEHLCGHAEE() 
	{ 
		KAPMOPMDHJE = "label";
		IDLHJIOMJBK = "data";
		NDFIEMPPMLF = "master";
	}
}
