
public class AKIIJBEJOEP
{
	public enum FABBEOMGNGL
	{
		HJNNKCMLGFL = 0,
		CCAPCGPIIPF = 1,
		HEFPAOLDHCK = 2,
	}

	public int FBGGEFFJJHB; // 0x8
	public string JOPOPMLFINI; // 0xC
	public string FEMMDNIELFC_Desc; // 0x10
	public string BGBJPGEIEDE_DescBalloon; // 0x14
	public int PPEGAKEIEGM_Enabled; // 0x18
	public int LMPPENOILPF; // 0x1C
	private int EHOIENNDEDH_IdCrypted; // 0x20
	private int NOFECLGOLAI_TypeCrypted; // 0x24
	private int NNDGELGIMAO_GroupCrypted; // 0x28
	private int DKOFFHFCPDD_TargetMusicTypeCrypted; // 0x2C
	private int JENDIADABGI_TargetMusicConditionIdCrypted; // 0x30
	private int NDKPNCJOENP_TargetDifficultyTypeCrypted; // 0x34
	private int GJMDLGLJBPL_TargetUnitTypeCrypted; // 0x38
	private int MFPNDLIJGDJ_TargetUnitConditionIdCrypted; // 0x3C
	private int AKCLJCCJBFH_TargetUnitConditionValueCrypted; // 0x40
	private int IBNOFNCOMKJ_ClearTypeCrypted; // 0x44
	private int EPIKHLFNFAP_ClearConditionIdCrypted; // 0x48
	private int BHDGLAFMNAO_ClearConditionValueCrypted; // 0x4C
	private int LDFJEIIOOBN_ClearCountCrypted; // 0x50
	private int PIMKKONMBOG_ItemIdCrypted; // 0x54
	private int ALJGJMBFKHE_ItemCountCrypted; // 0x58
	private int BNAJLJKHDCI_SltCrypted; // 0x5C
	private int HJCLFCILHEF_Slt2Crypted; // 0x60
	private int AHEDPADANKO_NextMusicCrypted; // 0x64
	private int NDNGNHDOEIK_Crypted; // 0x68
	private int DCEMPEFPKAO_Crypted; // 0x6C
	private int NPJBDKAFIBH_Crypted; // 0x70
	private int IGHKAPIJPLF_Crypted; // 0x74
	private int IOAGHJGBNLC_Crypted; // 0x78
	private int HHPFFPINGAA_Crypted; // 0x7C
	private long IBCNABKLHHH_StartCrypted; // 0x80
	private long MABPKDKBJAG_EndCrypted; // 0x88
	private int DICBCOFLFGC_Crypted; // 0x90
	private const int JHHLBIHEPDJ_True = 59;
	private const int DFMOPCKCCHF_False = 249;

	public int PPFNGGCBJKC_Id { get { return FBGGEFFJJHB ^ EHOIENNDEDH_IdCrypted; } set { EHOIENNDEDH_IdCrypted = value ^ FBGGEFFJJHB; } } //0xCD7520 DEMEPMAEJOO 0xCD2FBC HIGKAIDMOKN
	public int GBJFNGCDKPM_Type { get { return FBGGEFFJJHB ^ NOFECLGOLAI_TypeCrypted; } set { NOFECLGOLAI_TypeCrypted = value ^ FBGGEFFJJHB; } } //0xCD7530 CEJJMKODOGK 0xCD2FCC HOHCEBMMACI
	public bool PPCFIHMDMLM { get { return (FBGGEFFJJHB ^ NOFECLGOLAI_TypeCrypted) == 2; } } //0xCD7540 FEIHHNDGFPE
	public int KGICDMIJGDF_Group { get { return FBGGEFFJJHB ^ NNDGELGIMAO_GroupCrypted; } set { NNDGELGIMAO_GroupCrypted = value ^ FBGGEFFJJHB; } } //0xCD755C ENACPBCEBLF 0xCD2FDC KPCDPMGBPAG
	public int HMOJCCPIPBP_TargetMusicType { get { return FBGGEFFJJHB ^ DKOFFHFCPDD_TargetMusicTypeCrypted; } set { DKOFFHFCPDD_TargetMusicTypeCrypted = value ^ FBGGEFFJJHB; } } //0xCD756C ANNDMDFNGKG 0xCD2FEC LGCPDDPGCAB
	public int HBJJCDIMOPO_TargetMusicConditionId { get { return FBGGEFFJJHB ^ JENDIADABGI_TargetMusicConditionIdCrypted; } set { JENDIADABGI_TargetMusicConditionIdCrypted = value ^ FBGGEFFJJHB; } } //0xCD757C LMNFMFHKMGC 0xCD2FFC JEPGGJBCNFG
	public int DGMIADAEGAI_TargetDifficultyType { get { return FBGGEFFJJHB ^ NDKPNCJOENP_TargetDifficultyTypeCrypted; } set { NDKPNCJOENP_TargetDifficultyTypeCrypted = value ^ FBGGEFFJJHB; } } //0xCD758C OFCCCAPENJD 0xCD3B68 JKAKHHPGBGC
	public int NAPODHGLKAJ_TargetUnitType { get { return FBGGEFFJJHB ^ GJMDLGLJBPL_TargetUnitTypeCrypted; } set { GJMDLGLJBPL_TargetUnitTypeCrypted = value ^ FBGGEFFJJHB; } } //0xCD759C OEAAIHDECNF 0xCD300C LPNMLAIIEEL
	public int FHILEEHDDKN_TargetUnitConditionId { get { return FBGGEFFJJHB ^ MFPNDLIJGDJ_TargetUnitConditionIdCrypted; } set { MFPNDLIJGDJ_TargetUnitConditionIdCrypted = value ^ FBGGEFFJJHB; } } //0xCD75AC KAFJMKPGKNB 0xCD301C CADLPKFBHIP
	public int FAHLEOKHBGH_TargetUnitConditionValue { get { return FBGGEFFJJHB ^ AKCLJCCJBFH_TargetUnitConditionValueCrypted; } set { AKCLJCCJBFH_TargetUnitConditionValueCrypted = value ^ FBGGEFFJJHB; } } //0xCD75BC KJDOEOEKHDM 0xCD302C JFEHNBIDHEO
	public int HDAMBOOCIAA_ClearType { get { return FBGGEFFJJHB ^ IBNOFNCOMKJ_ClearTypeCrypted; } set { IBNOFNCOMKJ_ClearTypeCrypted = value ^ FBGGEFFJJHB; } } //0xCD75CC EEKMIBBDJCL 0xCD303C AHGIIJPDMME
	public int DEIEONIILLJ_ClearConditionId { get { return FBGGEFFJJHB ^ EPIKHLFNFAP_ClearConditionIdCrypted; } set { EPIKHLFNFAP_ClearConditionIdCrypted = value ^ FBGGEFFJJHB; } } //0xCD75DC ANGEBMGIDKL 0xCD304C AGGCCDKEPIP
	public int JJECMJFDEEP_ClearConditionValue { get { return FBGGEFFJJHB ^ BHDGLAFMNAO_ClearConditionValueCrypted; } set { BHDGLAFMNAO_ClearConditionValueCrypted = value ^ FBGGEFFJJHB; } } //0xCD75EC KNDJAKPNOIJ 0xCD305C DGEIJFDODFH
	public int GLDIGCJNOBO_ClearCount { get { return FBGGEFFJJHB ^ LDFJEIIOOBN_ClearCountCrypted; } set { LDFJEIIOOBN_ClearCountCrypted = value ^ FBGGEFFJJHB; } } //0xCD75FC IMNEEMEJKOF 0xCD306C CKLFFMEMKKB
	public int KABNKDJJKCN_NextMusic { get { return FBGGEFFJJHB ^ AHEDPADANKO_NextMusicCrypted; } set { AHEDPADANKO_NextMusicCrypted = value ^ FBGGEFFJJHB; } } //0xCD760C BAHELMHGCDO 0xCD307C KBAGGGMCPAK
	public int OOLNFBFBONH { get { return FBGGEFFJJHB ^ NDNGNHDOEIK_Crypted; } set { NDNGNHDOEIK_Crypted = value ^ FBGGEFFJJHB; } } //0xCD761C KLAKFEBLLCJ 0xCD308C IMDBOHNLGLA
	public int JAFIPGKNCAA { get { return FBGGEFFJJHB ^ DCEMPEFPKAO_Crypted; } set { DCEMPEFPKAO_Crypted = value ^ FBGGEFFJJHB; } } //0xCD762C AOBIAEANBEJ 0xCD309C PCFMNGCMEOB
	public int JJALDEPKCIJ { get { return FBGGEFFJJHB ^ NPJBDKAFIBH_Crypted; } set { NPJBDKAFIBH_Crypted = value ^ FBGGEFFJJHB; } } //0xCD763C HCJNOHDMHBH 0xCD30AC BDJDMCEHJCB
	public int HJNLDPMJFLB { get { return FBGGEFFJJHB ^ IGHKAPIJPLF_Crypted; } set { IGHKAPIJPLF_Crypted = value ^ FBGGEFFJJHB; } } //0xCD764C AEDCHEABECD 0xCD30BC KDCDLMCPNJL
	public int KIJAPOFAGPN_ItemId { get { return FBGGEFFJJHB ^ PIMKKONMBOG_ItemIdCrypted; } set { PIMKKONMBOG_ItemIdCrypted = value ^ FBGGEFFJJHB; } } //0xCD76CC GCKKKIDNACI 0xCD30CC OGBLMPODGBG
	public int JDLJPNMLFID_ItemCount { get { return FBGGEFFJJHB ^ ALJGJMBFKHE_ItemCountCrypted; } set { ALJGJMBFKHE_ItemCountCrypted = value ^ FBGGEFFJJHB; } } //0xCD76DC BGIBDHCFJMN 0xCD30DC NDNEDCNDOGJ
	public int IKJAAKEINHC_Slt { get { return FBGGEFFJJHB ^ BNAJLJKHDCI_SltCrypted; } set { BNAJLJKHDCI_SltCrypted = value ^ FBGGEFFJJHB; } } //0xCD76EC OHHGMCIDKAG 0xCD30EC GAOCMDHJKPD
	public int HPAOAKMKCMA_Slt2 { get { return FBGGEFFJJHB ^ HJCLFCILHEF_Slt2Crypted; } set { HJCLFCILHEF_Slt2Crypted = value ^ FBGGEFFJJHB; } } //0xCD76FC PEKGEADKHHH 0xCD30FC AMDPGPOKCCO
	public int HHIBBHFHENH_NextStepId { get { return FBGGEFFJJHB ^ IOAGHJGBNLC_Crypted; } set { IOAGHJGBNLC_Crypted = value ^ FBGGEFFJJHB; } } //0xCD770C MEHBABCCHOO 0xCD310C FBCMDNCLBDC
	public int EILKGEADKGH { get { return FBGGEFFJJHB ^ HHPFFPINGAA_Crypted; } set { HHPFFPINGAA_Crypted = value ^ FBGGEFFJJHB; } } //0xCD771C NPDDACIHBKD 0xCD311C BJJMCKHBPNH
	public long KJBGCLPMLCG_Start { get { return FBGGEFFJJHB ^ IBCNABKLHHH_StartCrypted; } set { IBCNABKLHHH_StartCrypted = value ^ FBGGEFFJJHB; } } //0xCD772C IDLJOCDJJOC 0xCD312C ODIEKGPKOAC
	public long GJFPFFBAKGK_End { get { return FBGGEFFJJHB ^ MABPKDKBJAG_EndCrypted; } set { MABPKDKBJAG_EndCrypted = value ^ FBGGEFFJJHB; } } //0xCD7744 KPBMCJKFEGN 0xCD3140 IEFCDGKGICA
	public bool PJPDOCNJNGJ { get { return DICBCOFLFGC_Crypted == JHHLBIHEPDJ_True; } set { DICBCOFLFGC_Crypted = value ? JHHLBIHEPDJ_True : DFMOPCKCCHF_False; } } //0xCD775C MBEBLALDBHJ 0xCD3154 ENPODKCLKMC

	//// RVA: 0xCD2ECC Offset: 0xCD2ECC VA: 0xCD2ECC
	public void LHPDDGIJKNB(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG)
	{
		this.JOPOPMLFINI = JOPOPMLFINI;
		FBGGEFFJJHB = KNEFBLHBDBG;
		GBJFNGCDKPM_Type = 0;
		KGICDMIJGDF_Group = 0;
		HMOJCCPIPBP_TargetMusicType = 0;
		HBJJCDIMOPO_TargetMusicConditionId = 0;
		NAPODHGLKAJ_TargetUnitType = 0;
		FHILEEHDDKN_TargetUnitConditionId = 0;
		FAHLEOKHBGH_TargetUnitConditionValue = 0;
		HDAMBOOCIAA_ClearType = 0;
		GLDIGCJNOBO_ClearCount = 0;
		KIJAPOFAGPN_ItemId = 0;
		JDLJPNMLFID_ItemCount = 0;
		IKJAAKEINHC_Slt = 0;
		HPAOAKMKCMA_Slt2 = 0;
		KABNKDJJKCN_NextMusic = 0;
		OOLNFBFBONH = 0;
		JAFIPGKNCAA = 0;
		JJALDEPKCIJ = 0;
		HJNLDPMJFLB = 0;
		HHIBBHFHENH_NextStepId = 0;
		EILKGEADKGH = 0;
		KJBGCLPMLCG_Start = 0;
		GJFPFFBAKGK_End = 0;
		BGBJPGEIEDE_DescBalloon = "";
		FEMMDNIELFC_Desc = "";
		PPFNGGCBJKC_Id = PPFNGGCBJKC;
		PPEGAKEIEGM_Enabled = 0;
		DEIEONIILLJ_ClearConditionId = 0;
		JJECMJFDEEP_ClearConditionValue = 0;
		LMPPENOILPF = 0;
		PJPDOCNJNGJ = false;
	}

	//// RVA: 0xCD3184 Offset: 0xCD3184 VA: 0xCD3184
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDOHBJAPLPF IDLHJIOMJBK) { }

	//// RVA: 0xCD3B78 Offset: 0xCD3B78 VA: 0xCD3B78
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HMNJADGBKFA JMHECKKKMLK) { }

	//// RVA: 0xCD40B8 Offset: 0xCD40B8 VA: 0xCD40B8
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HGHOHICGBEP JMHECKKKMLK) { }

	//// RVA: 0xCD4570 Offset: 0xCD4570 VA: 0xCD4570
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDHLNJNFNDN JMHECKKKMLK) { }

	//// RVA: 0xCD4AB0 Offset: 0xCD4AB0 VA: 0xCD4AB0
	public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, OPHFFGFJIBJ JMHECKKKMLK)
	{
		LHPDDGIJKNB(JOPOPMLFINI, PPFNGGCBJKC, KNEFBLHBDBG);
		JGHDNNFHEHC data = JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1];
		FEMMDNIELFC_Desc = DatabaseTextConverter.TranslateEventMissionDesc(JOPOPMLFINI, PPFNGGCBJKC, data.FEMMDNIELFC);
		BGBJPGEIEDE_DescBalloon = DatabaseTextConverter.TranslateEventMissionDesc2(JOPOPMLFINI, PPFNGGCBJKC, data.BGBJPGEIEDE);
		PPFNGGCBJKC_Id = (int)data.PPFNGGCBJKC;
		GBJFNGCDKPM_Type = (int)data.GBJFNGCDKPM;
		PPEGAKEIEGM_Enabled = (int)data.PLALNIIBLOF;
		HMOJCCPIPBP_TargetMusicType = (int)data.BDKFOMGCOOE;
		HBJJCDIMOPO_TargetMusicConditionId = (int)data.PJGIAKGGHPF;
		DGMIADAEGAI_TargetDifficultyType = (int)data.MMCBOJHFDEF;
		NAPODHGLKAJ_TargetUnitType = (int)data.JBECECBFFBF;
		FHILEEHDDKN_TargetUnitConditionId = (int)data.LDOMFAMFGLM;
		FAHLEOKHBGH_TargetUnitConditionValue = (int)data.BMDGADMKOIH;
		HDAMBOOCIAA_ClearType = (int)data.AIIEBILNLGO;
		DEIEONIILLJ_ClearConditionId = (int)data.JOGDEMBADLO;
		JJECMJFDEEP_ClearConditionValue = (int)data.GMJBANCDOJK;
		HJNLDPMJFLB = 0;
		GLDIGCJNOBO_ClearCount = (int)data.AIEOAMKDHJC;
		KABNKDJJKCN_NextMusic = 0;
		OOLNFBFBONH = 0;
		JAFIPGKNCAA = 0;
		JJALDEPKCIJ = 0;
		KIJAPOFAGPN_ItemId = (int)data.GLCLFMGPMAN;
		JDLJPNMLFID_ItemCount = (int)data.MBJIFDBEDAC;
		IKJAAKEINHC_Slt = (int)data.JJHPDDPKBHF;
		HPAOAKMKCMA_Slt2 =(int)data.KOACGMPOIGN;
		LMPPENOILPF = (int)data.ADCKKAFCIAC;
		HHIBBHFHENH_NextStepId = (int)data.HLOBFDBFINJ;
		EILKGEADKGH = (int)data.FPOMEEJFBIG;
		KJBGCLPMLCG_Start = data.FNEIADJMHHO;
		GJFPFFBAKGK_End = data.EICJBAEDMNM;
		PJPDOCNJNGJ = data.HJAFPEBIBOP != 0;
	}

	//// RVA: 0xCD4FF0 Offset: 0xCD4FF0 VA: 0xCD4FF0
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, ANCFFLNKINL JMHECKKKMLK) { }

	//// RVA: 0xCD5520 Offset: 0xCD5520 VA: 0xCD5520
	public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, OLLJFONKEKO JMHECKKKMLK)
	{
		LHPDDGIJKNB(JOPOPMLFINI, PPFNGGCBJKC, KNEFBLHBDBG);
		FEMMDNIELFC_Desc = DatabaseTextConverter.TranslateEventMissionDesc(JOPOPMLFINI, PPFNGGCBJKC, JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FEMMDNIELFC);
		BGBJPGEIEDE_DescBalloon = DatabaseTextConverter.TranslateEventMissionDesc2(JOPOPMLFINI, PPFNGGCBJKC, JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BGBJPGEIEDE);
		PPFNGGCBJKC_Id = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PPFNGGCBJKC;
		GBJFNGCDKPM_Type = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GBJFNGCDKPM;
		PPEGAKEIEGM_Enabled = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PLALNIIBLOF;
		HMOJCCPIPBP_TargetMusicType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BDKFOMGCOOE;
		HBJJCDIMOPO_TargetMusicConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PJGIAKGGHPF;
		DGMIADAEGAI_TargetDifficultyType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].MMCBOJHFDEF;
		NAPODHGLKAJ_TargetUnitType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JBECECBFFBF;
		FHILEEHDDKN_TargetUnitConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].LDOMFAMFGLM;
		FAHLEOKHBGH_TargetUnitConditionValue = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BMDGADMKOIH;
		HDAMBOOCIAA_ClearType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].AIIEBILNLGO;
		DEIEONIILLJ_ClearConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JOGDEMBADLO;
		JJECMJFDEEP_ClearConditionValue = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GMJBANCDOJK;
		GLDIGCJNOBO_ClearCount = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].AIEOAMKDHJC;
		KABNKDJJKCN_NextMusic = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].CMPNCNFICGG;
		OOLNFBFBONH = 0;
		JAFIPGKNCAA = 0;
		JJALDEPKCIJ = 0;
		HJNLDPMJFLB = 0;
		KIJAPOFAGPN_ItemId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GLCLFMGPMAN;
		JDLJPNMLFID_ItemCount = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].MBJIFDBEDAC;
		IKJAAKEINHC_Slt = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JJHPDDPKBHF;
		HPAOAKMKCMA_Slt2 = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].KOACGMPOIGN;
		LMPPENOILPF = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].ADCKKAFCIAC;
		HHIBBHFHENH_NextStepId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].HLOBFDBFINJ;
		EILKGEADKGH = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FPOMEEJFBIG;
		KJBGCLPMLCG_Start = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FNEIADJMHHO;
		GJFPFFBAKGK_End = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].EICJBAEDMNM;
		PJPDOCNJNGJ = false;
	}

	//// RVA: 0xCD5A5C Offset: 0xCD5A5C VA: 0xCD5A5C
	public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, FOKPKJFHNLO JMHECKKKMLK)
	{
		LHPDDGIJKNB(JOPOPMLFINI, PPFNGGCBJKC, KNEFBLHBDBG);
		FEMMDNIELFC_Desc = DatabaseTextConverter.TranslateEventMissionDesc(JOPOPMLFINI, PPFNGGCBJKC, JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FEMMDNIELFC);
		BGBJPGEIEDE_DescBalloon = DatabaseTextConverter.TranslateEventMissionDesc2(JOPOPMLFINI, PPFNGGCBJKC, JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BGBJPGEIEDE);
		PPFNGGCBJKC_Id = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PPFNGGCBJKC;
		GBJFNGCDKPM_Type = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GBJFNGCDKPM;
		PPEGAKEIEGM_Enabled = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PLALNIIBLOF;
		HMOJCCPIPBP_TargetMusicType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BDKFOMGCOOE;
		HBJJCDIMOPO_TargetMusicConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].PJGIAKGGHPF;
		DGMIADAEGAI_TargetDifficultyType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].MMCBOJHFDEF;
		NAPODHGLKAJ_TargetUnitType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JBECECBFFBF;
		FHILEEHDDKN_TargetUnitConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].LDOMFAMFGLM;
		FAHLEOKHBGH_TargetUnitConditionValue = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].BMDGADMKOIH;
		HDAMBOOCIAA_ClearType = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].AIIEBILNLGO;
		DEIEONIILLJ_ClearConditionId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JOGDEMBADLO;
		JJECMJFDEEP_ClearConditionValue = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GMJBANCDOJK;
		GLDIGCJNOBO_ClearCount = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].AIEOAMKDHJC;
		KABNKDJJKCN_NextMusic = 0;
		OOLNFBFBONH = 0;
		JAFIPGKNCAA = 0;
		JJALDEPKCIJ = 0;
		HJNLDPMJFLB = 0;
		KIJAPOFAGPN_ItemId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].GLCLFMGPMAN;
		JDLJPNMLFID_ItemCount = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].MBJIFDBEDAC;
		IKJAAKEINHC_Slt = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].JJHPDDPKBHF;
		HPAOAKMKCMA_Slt2 = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].KOACGMPOIGN;
		LMPPENOILPF = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].ADCKKAFCIAC;
		HHIBBHFHENH_NextStepId = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].HLOBFDBFINJ;
		EILKGEADKGH = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FPOMEEJFBIG;
		KJBGCLPMLCG_Start = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].FNEIADJMHHO;
		GJFPFFBAKGK_End = (int)JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].EICJBAEDMNM;
		PJPDOCNJNGJ = JMHECKKKMLK.MDDOGIAFDEI[PPFNGGCBJKC - 1].HJAFPEBIBOP != 0;
	}

	//// RVA: 0xCD5F9C Offset: 0xCD5F9C VA: 0xCD5F9C
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, NPAJGBIFLHB JMHECKKKMLK) { }

	//// RVA: 0xCD64A0 Offset: 0xCD64A0 VA: 0xCD64A0
	//public void FDKFKPGFHNE(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, NPAJGBIFLHB JMHECKKKMLK) { }

	//// RVA: 0xCD6614 Offset: 0xCD6614 VA: 0xCD6614
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, MAGFOKIIPPD JMHECKKKMLK) { }

	//// RVA: 0xCD6B18 Offset: 0xCD6B18 VA: 0xCD6B18
	//public void IFMHPIGMJBC(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDOHBJAPLPF IDLHJIOMJBK) { }

	//// RVA: 0xCD7024 Offset: 0xCD7024 VA: 0xCD7024
	//public void IFMHPIGMJBC(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HGHOHICGBEP JMHECKKKMLK) { }

	//// RVA: 0xCD7304 Offset: 0xCD7304 VA: 0xCD7304
	//public void FDKFKPGFHNE(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDHLNJNFNDN JMHECKKKMLK) { }

	//// RVA: 0xCD765C Offset: 0xCD765C VA: 0xCD765C
	public int GONJEDOAPFJ(int OIPCCBHIKIA)
	{
		if (OIPCCBHIKIA == 0)
			return HDAMBOOCIAA_ClearType;
		else
			return OOLNFBFBONH;
	}

	//// RVA: 0xCD7678 Offset: 0xCD7678 VA: 0xCD7678
	public int KJFKPGABANO(int OIPCCBHIKIA)
	{
		if(OIPCCBHIKIA == 0)
			return DEIEONIILLJ_ClearConditionId;
		else
			return JAFIPGKNCAA;
	}

	//// RVA: 0xCD7694 Offset: 0xCD7694 VA: 0xCD7694
	public int GHCDDKIBJGK(int OIPCCBHIKIA)
	{
		if(OIPCCBHIKIA == 0)
			return JJECMJFDEEP_ClearConditionValue;
		else
			return JJALDEPKCIJ;
	}

	//// RVA: 0xCD76B0 Offset: 0xCD76B0 VA: 0xCD76B0
	//public int OKJENADDBMC(int OIPCCBHIKIA) { }

	//// RVA: 0xCD7770 Offset: 0xCD7770 VA: 0xCD7770
	//public bool OFKCGMNFGKB(long LKCCMBEOLLA) { }

	//// RVA: 0xCD77DC Offset: 0xCD77DC VA: 0xCD77DC
	//public uint CAOGDCBPBAN() { }
}
