
public class AKIIJBEJOEP
{
	public enum FABBEOMGNGL
	{
		HJNNKCMLGFL = 0,
		CCAPCGPIIPF = 1,
		HEFPAOLDHCK = 2,
	}

	public int FBGGEFFJJHB; // 0x8
	public string JOPOPMLFINI; // 0xC
	public string FEMMDNIELFC; // 0x10
	public string BGBJPGEIEDE; // 0x14
	public int PPEGAKEIEGM; // 0x18
	public int LMPPENOILPF; // 0x1C
	private int EHOIENNDEDH; // 0x20
	private int NOFECLGOLAI; // 0x24
	private int NNDGELGIMAO; // 0x28
	private int DKOFFHFCPDD; // 0x2C
	private int JENDIADABGI; // 0x30
	private int NDKPNCJOENP; // 0x34
	private int GJMDLGLJBPL; // 0x38
	private int MFPNDLIJGDJ; // 0x3C
	private int AKCLJCCJBFH; // 0x40
	private int IBNOFNCOMKJ; // 0x44
	private int EPIKHLFNFAP; // 0x48
	private int BHDGLAFMNAO; // 0x4C
	private int LDFJEIIOOBN; // 0x50
	private int PIMKKONMBOG; // 0x54
	private int ALJGJMBFKHE; // 0x58
	private int BNAJLJKHDCI; // 0x5C
	private int HJCLFCILHEF; // 0x60
	private int AHEDPADANKO; // 0x64
	private int NDNGNHDOEIK; // 0x68
	private int DCEMPEFPKAO; // 0x6C
	private int NPJBDKAFIBH; // 0x70
	private int IGHKAPIJPLF; // 0x74
	private int IOAGHJGBNLC; // 0x78
	private int HHPFFPINGAA; // 0x7C
	private long IBCNABKLHHH; // 0x80
	private long MABPKDKBJAG; // 0x88
	private int DICBCOFLFGC; // 0x90
	private const int JHHLBIHEPDJ = 59;
	private const int DFMOPCKCCHF = 249;

	//public int PPFNGGCBJKC { get; set; } 0xCD7520 DEMEPMAEJOO 0xCD2FBC HIGKAIDMOKN
	//public int GBJFNGCDKPM { get; set; } 0xCD7530 CEJJMKODOGK 0xCD2FCC HOHCEBMMACI
	//public bool PPCFIHMDMLM { get; } 0xCD7540 FEIHHNDGFPE
	//public int KGICDMIJGDF { get; set; } 0xCD755C ENACPBCEBLF 0xCD2FDC KPCDPMGBPAG
	//public int HMOJCCPIPBP { get; set; } 0xCD756C ANNDMDFNGKG 0xCD2FEC LGCPDDPGCAB
	//public int HBJJCDIMOPO { get; set; } 0xCD757C LMNFMFHKMGC 0xCD2FFC JEPGGJBCNFG
	//public int DGMIADAEGAI { get; set; } 0xCD758C OFCCCAPENJD 0xCD3B68 JKAKHHPGBGC
	//public int NAPODHGLKAJ { get; set; } 0xCD759C OEAAIHDECNF 0xCD300C LPNMLAIIEEL
	//public int FHILEEHDDKN { get; set; } 0xCD75AC KAFJMKPGKNB 0xCD301C CADLPKFBHIP
	//public int FAHLEOKHBGH { get; set; } 0xCD75BC KJDOEOEKHDM 0xCD302C JFEHNBIDHEO
	//public int HDAMBOOCIAA { get; set; } 0xCD75CC EEKMIBBDJCL 0xCD303C AHGIIJPDMME
	//public int DEIEONIILLJ { get; set; } 0xCD75DC ANGEBMGIDKL 0xCD304C AGGCCDKEPIP
	//public int JJECMJFDEEP { get; set; } 0xCD75EC KNDJAKPNOIJ 0xCD305C DGEIJFDODFH
	//public int GLDIGCJNOBO { get; set; } 0xCD75FC IMNEEMEJKOF 0xCD306C CKLFFMEMKKB
	//public int KABNKDJJKCN { get; set; } 0xCD760C BAHELMHGCDO 0xCD307C KBAGGGMCPAK
	//public int OOLNFBFBONH { get; set; } 0xCD761C KLAKFEBLLCJ 0xCD308C IMDBOHNLGLA
	//public int JAFIPGKNCAA { get; set; } 0xCD762C AOBIAEANBEJ 0xCD309C PCFMNGCMEOB
	//public int JJALDEPKCIJ { get; set; } 0xCD763C HCJNOHDMHBH 0xCD30AC BDJDMCEHJCB
	//public int HJNLDPMJFLB { get; set; } 0xCD764C AEDCHEABECD 0xCD30BC KDCDLMCPNJL
	//public int KIJAPOFAGPN { get; set; } 0xCD76CC GCKKKIDNACI 0xCD30CC OGBLMPODGBG
	//public int JDLJPNMLFID { get; set; } 0xCD76DC BGIBDHCFJMN 0xCD30DC NDNEDCNDOGJ
	//public int IKJAAKEINHC { get; set; } 0xCD76EC OHHGMCIDKAG 0xCD30EC GAOCMDHJKPD
	//public int HPAOAKMKCMA { get; set; } 0xCD76FC PEKGEADKHHH 0xCD30FC AMDPGPOKCCO
	//public int HHIBBHFHENH { get; set; } 0xCD770C MEHBABCCHOO 0xCD310C FBCMDNCLBDC
	//public int EILKGEADKGH { get; set; } 0xCD771C NPDDACIHBKD 0xCD311C BJJMCKHBPNH
	//public long KJBGCLPMLCG { get; set; } 0xCD772C IDLJOCDJJOC 0xCD312C ODIEKGPKOAC
	//public long GJFPFFBAKGK { get; set; } 0xCD7744 KPBMCJKFEGN 0xCD3140 IEFCDGKGICA
	//public bool PJPDOCNJNGJ { get; set; } 0xCD775C MBEBLALDBHJ 0xCD3154 ENPODKCLKMC

	//// RVA: 0xCD2ECC Offset: 0xCD2ECC VA: 0xCD2ECC
	//public void LHPDDGIJKNB(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG) { }

	//// RVA: 0xCD3184 Offset: 0xCD3184 VA: 0xCD3184
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDOHBJAPLPF IDLHJIOMJBK) { }

	//// RVA: 0xCD3B78 Offset: 0xCD3B78 VA: 0xCD3B78
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HMNJADGBKFA JMHECKKKMLK) { }

	//// RVA: 0xCD40B8 Offset: 0xCD40B8 VA: 0xCD40B8
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HGHOHICGBEP JMHECKKKMLK) { }

	//// RVA: 0xCD4570 Offset: 0xCD4570 VA: 0xCD4570
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDHLNJNFNDN JMHECKKKMLK) { }

	//// RVA: 0xCD4AB0 Offset: 0xCD4AB0 VA: 0xCD4AB0
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, OPHFFGFJIBJ JMHECKKKMLK) { }

	//// RVA: 0xCD4FF0 Offset: 0xCD4FF0 VA: 0xCD4FF0
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, ANCFFLNKINL JMHECKKKMLK) { }

	//// RVA: 0xCD5520 Offset: 0xCD5520 VA: 0xCD5520
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, OLLJFONKEKO JMHECKKKMLK) { }

	//// RVA: 0xCD5A5C Offset: 0xCD5A5C VA: 0xCD5A5C
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, FOKPKJFHNLO JMHECKKKMLK) { }

	//// RVA: 0xCD5F9C Offset: 0xCD5F9C VA: 0xCD5F9C
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, NPAJGBIFLHB JMHECKKKMLK) { }

	//// RVA: 0xCD64A0 Offset: 0xCD64A0 VA: 0xCD64A0
	//public void FDKFKPGFHNE(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, NPAJGBIFLHB JMHECKKKMLK) { }

	//// RVA: 0xCD6614 Offset: 0xCD6614 VA: 0xCD6614
	//public void KHEKNNFCAOI(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, MAGFOKIIPPD JMHECKKKMLK) { }

	//// RVA: 0xCD6B18 Offset: 0xCD6B18 VA: 0xCD6B18
	//public void IFMHPIGMJBC(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDOHBJAPLPF IDLHJIOMJBK) { }

	//// RVA: 0xCD7024 Offset: 0xCD7024 VA: 0xCD7024
	//public void IFMHPIGMJBC(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, HGHOHICGBEP JMHECKKKMLK) { }

	//// RVA: 0xCD7304 Offset: 0xCD7304 VA: 0xCD7304
	//public void FDKFKPGFHNE(string JOPOPMLFINI, int PPFNGGCBJKC, int KNEFBLHBDBG, EDHLNJNFNDN JMHECKKKMLK) { }

	//// RVA: 0xCD765C Offset: 0xCD765C VA: 0xCD765C
	//public int GONJEDOAPFJ(int OIPCCBHIKIA) { }

	//// RVA: 0xCD7678 Offset: 0xCD7678 VA: 0xCD7678
	//public int KJFKPGABANO(int OIPCCBHIKIA) { }

	//// RVA: 0xCD7694 Offset: 0xCD7694 VA: 0xCD7694
	//public int GHCDDKIBJGK(int OIPCCBHIKIA) { }

	//// RVA: 0xCD76B0 Offset: 0xCD76B0 VA: 0xCD76B0
	//public int OKJENADDBMC(int OIPCCBHIKIA) { }

	//// RVA: 0xCD7770 Offset: 0xCD7770 VA: 0xCD7770
	//public bool OFKCGMNFGKB(long LKCCMBEOLLA) { }

	//// RVA: 0xCD77DC Offset: 0xCD77DC VA: 0xCD77DC
	//public uint CAOGDCBPBAN() { }
}
