
public class BHBONAHFKHD
{
	public EDOHBJAPLPF_JsonData MGPEIGDOMPH { get; private set; } // 0x8 DOBHNBKICMJ DNGMMHKPCFH NFDOJJOFOJD

	// RVA: 0xC7D068 Offset: 0xC7D068 VA: 0xC7D068
	public BHBONAHFKHD()
	{
		LHPDDGIJKNB();
	}

	//// RVA: 0xC7D088 Offset: 0xC7D088 VA: 0xC7D088
	public void LHPDDGIJKNB()
	{
		MGPEIGDOMPH = new EDOHBJAPLPF_JsonData();
		MGPEIGDOMPH.LAJDIPCJCPO_SetJsonType(JFBMDLGBPEN_JsonType.JKMLKAMHJIF_Object);
	}

	//// RVA: 0xC7D118 Offset: 0xC7D118 VA: 0xC7D118
	//private void BNFBKGHBHHN(string JIKKNHIAEKG, EDOHBJAPLPF OBHAFLMHAKG) { }

	//// RVA: 0xC7D270 Offset: 0xC7D270 VA: 0xC7D270
	//public void ANIJHEBLMGB(string JIKKNHIAEKG, string ALGBKNAAEKO, EDOHBJAPLPF JBGEEPFKIGG) { }

	//// RVA: 0xC7D430 Offset: 0xC7D430 VA: 0xC7D430
	//public void ANIJHEBLMGB(string JIKKNHIAEKG, string ALGBKNAAEKO, bool JBGEEPFKIGG) { }

	//// RVA: 0xC7D600 Offset: 0xC7D600 VA: 0xC7D600
	//public void ANIJHEBLMGB(string JIKKNHIAEKG, string ALGBKNAAEKO, int JBGEEPFKIGG) { }

	//// RVA: 0xC7D7D0 Offset: 0xC7D7D0 VA: 0xC7D7D0
	//public void ANIJHEBLMGB(string JIKKNHIAEKG, string ALGBKNAAEKO, string JBGEEPFKIGG) { }

	//// RVA: 0xC7D9A0 Offset: 0xC7D9A0 VA: 0xC7D9A0
	//public void OJCJPCHFPGO(string JIKKNHIAEKG, string ALGBKNAAEKO) { }

	//// RVA: 0xC7DB18 Offset: 0xC7DB18 VA: 0xC7DB18
	//public void OJLJAHAGBLK(string JIKKNHIAEKG, string ALGBKNAAEKO, EDOHBJAPLPF_JsonData JBGEEPFKIGG)

	//// RVA: 0xC7DCD8 Offset: 0xC7DCD8 VA: 0xC7DCD8
	//public void OJLJAHAGBLK(string JIKKNHIAEKG, string ALGBKNAAEKO, bool JBGEEPFKIGG)

	//// RVA: 0xC7DEA8 Offset: 0xC7DEA8 VA: 0xC7DEA8
	//public void OJLJAHAGBLK(string JIKKNHIAEKG, string ALGBKNAAEKO, int JBGEEPFKIGG)

	//// RVA: 0xC7E078 Offset: 0xC7E078 VA: 0xC7E078
	//public void OJLJAHAGBLK(string JIKKNHIAEKG, string ALGBKNAAEKO, string JBGEEPFKIGG)

	//// RVA: 0xC7E248 Offset: 0xC7E248 VA: 0xC7E248
	//public void AKBLDNCONGK(string JIKKNHIAEKG, string NHPCKCOPKAM, string ALGBKNAAEKO) { }

	//// RVA: 0xC7E418 Offset: 0xC7E418 VA: 0xC7E418
	//public void ODDIHGPONFL(string JIKKNHIAEKG, string NHPCKCOPKAM, string ALGBKNAAEKO) { }

	//// RVA: 0xC7E5E8 Offset: 0xC7E5E8 VA: 0xC7E5E8
	//public void KCCCOEMPPEA(string JIKKNHIAEKG, string ALGBKNAAEKO, EDOHBJAPLPF JBGEEPFKIGG) { }

	//// RVA: 0xC7E7A8 Offset: 0xC7E7A8 VA: 0xC7E7A8
	//public void FHPBAKLNKOL(string JIKKNHIAEKG, string ALGBKNAAEKO, bool JBGEEPFKIGG) { }

	//// RVA: 0xC7E978 Offset: 0xC7E978 VA: 0xC7E978
	//public void FHPBAKLNKOL(string JIKKNHIAEKG, string ALGBKNAAEKO, int JBGEEPFKIGG) { }

	//// RVA: 0xC7EB48 Offset: 0xC7EB48 VA: 0xC7EB48
	//public void FHPBAKLNKOL(string JIKKNHIAEKG, string ALGBKNAAEKO, string JBGEEPFKIGG) { }

	//// RVA: 0xC7ED18 Offset: 0xC7ED18 VA: 0xC7ED18
	//public void OPBAJJIJENO() { }
}
