
using System.ComponentModel;
using UnityEngine;
using XeSys;

public class BLHNHKMMPAD
{
	public int FBGGEFFJJHB; // 0x8
	public int[] MJNMPAKBNKB_Nr = new int[5]; // 0xC
	public int CJAOMKLHFJL_Crypted; // 0x10
	public int CPCKPCJBDEL_Crypted; // 0x14
	public int DMPDIMGFEBL_Crypted; // 0x18
	public int AOFGNAJLLPD_Crypted; // 0x1C
	public int BJHHOBEMBJG_Crypted; // 0x20
	public int LEHJBFPLJPL_Crypted; // 0x24
	public int ENEKCBCOKNM_Crypted; // 0x28
	public int MHGDDPCAGAJ_Crypted; // 0x2C
	public int GIELAFNPOCG_Crypted; // 0x30
	public int GHJIBEMCKLA_Crypted; // 0x34
	public int JKJDDGGNEAB_Crypted; // 0x38
	public int NBOLDNMPJFG_Crypted; // 0x3C
	public int BNPKALPLIJH_Crypted; // 0x40
	public int BCKCCHGMPBG_Crypted; // 0x44
	public int ONHKDPEAJOI_Crypted; // 0x48
	public int EOPEEENMHEN_Crypted; // 0x4C
	public int ADOIPHGJHBC_Crypted; // 0x50
	public long KLAPHOKNEDG_Crypted; // 0x58
	public int KPLDLGGMOMH_Crypted; // 0x60
	public int HIJDFKKMONB_Crypted; // 0x64
	public int LPNGJDDEJJD_Crypted; // 0x68
	public int GFPNAILCPLG_Crypted; // 0x6C

	public int GOIKCKHMBDL_F { get { return CJAOMKLHFJL_Crypted ^ FBGGEFFJJHB; } set { CJAOMKLHFJL_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF49C BPGCGEDHBEH 0x19BF4AC ICPMFBIDFFO
	public int AKNELONELJK_Df { get { return CPCKPCJBDEL_Crypted ^ FBGGEFFJJHB; } set { CPCKPCJBDEL_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF4BC BPPILHGDABB 0x19BF4CC PMMIIHKEGCI
	public int MIKICCLPDJA_L6 { get { return DMPDIMGFEBL_Crypted ^ FBGGEFFJJHB; } set { DMPDIMGFEBL_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF4DC CCFIANIJCJI 0x19BF4EC BFDODBCKDMK
	public int DIPKCALNIII_Dv { get { return AOFGNAJLLPD_Crypted ^ FBGGEFFJJHB; } set { AOFGNAJLLPD_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF4FC EOGPBFIDAPF 0x19BF50C JDNCGPBAFMB
	public int BEEAIAAJOHD_Cs { get { return BJHHOBEMBJG_Crypted ^ FBGGEFFJJHB; } set { BJHHOBEMBJG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF51C DIIBIOEMHAI 0x19BF52C JIHEDMEFKAF
	public int AFNIOJHODAG_CsCol { get { return LEHJBFPLJPL_Crypted ^ FBGGEFFJJHB; } set { LEHJBFPLJPL_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF53C OCABHAPHAMH 0x19BF54C DIAIECJEGDG
	public int HEBKEJBDCBH_Dl { get { return ENEKCBCOKNM_Crypted ^ FBGGEFFJJHB; } set { ENEKCBCOKNM_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF55C OMOHEDILHMF 0x19BF56C FCGDHINFKHC
	public int GLILAGLJLEP_S { get { return MHGDDPCAGAJ_Crypted ^ FBGGEFFJJHB; } set { MHGDDPCAGAJ_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF57C HGPGPALMELF 0x19BF58C ECHLNFNJFFO
	public int ECOLMPLOPFM_Sl { get { return GIELAFNPOCG_Crypted ^ FBGGEFFJJHB; } set { GIELAFNPOCG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF59C BFLCGLBAFOE 0x19BF5AC NJGKCLHFDIB
	public int CFCIMKOHLIG_M { get { return GHJIBEMCKLA_Crypted ^ FBGGEFFJJHB; } set { GHJIBEMCKLA_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF5BC AJNACFGNOAA 0x19BF5CC LCGAFCPHDKA
	public int IPPNCOHEEOD_Av { get { return EOPEEENMHEN_Crypted ^ FBGGEFFJJHB; } set { EOPEEENMHEN_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF5DC BNFNPCNAGAF 0x19BF5EC GEMDEGDPJPK
	public int KNIFCANOHOC_Sc { get { return NBOLDNMPJFG_Crypted ^ FBGGEFFJJHB; } set { NBOLDNMPJFG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF5FC EOJEPLIPOMJ 0x19BF60C AEEMBPAEAAI
	public int OFJHABJNGOD_Se { get { return BNPKALPLIJH_Crypted ^ FBGGEFFJJHB; } set { BNPKALPLIJH_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF61C NDBFELIIICL 0x19BF62C BIJLJDDDMLL
	public int NLKEBAOBJCM_Cb { get { return BCKCCHGMPBG_Crypted ^ FBGGEFFJJHB; } set { BCKCCHGMPBG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF63C AECNKGBNKHH 0x19BF64C ECHLKFHOJFP
	public int LAMCCNAKIOJ_Cr { get { return ONHKDPEAJOI_Crypted ^ FBGGEFFJJHB; } set { ONHKDPEAJOI_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF65C IHEENNFAAAJ 0x19BF66C ODPFIDLANCG
	public int BDLNMOIOMHK_To { get { return JKJDDGGNEAB_Crypted ^ FBGGEFFJJHB; } set { JKJDDGGNEAB_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF67C MKMAKAEDMBG 0x19BF68C GIJPLHEDIKD
	public long BEBJKJKBOGH_D { get { return KLAPHOKNEDG_Crypted ^ FBGGEFFJJHB; } set { KLAPHOKNEDG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF69C DIAPHCJBPFD 0x19BF6B4 IHAIKPNEEJE
	public int NHLGACIHDAH_Ex { get { return ADOIPHGJHBC_Crypted ^ FBGGEFFJJHB; } set { ADOIPHGJHBC_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF6C8 MDCFGFPHGKO 0x19BF6D8 KJOPHNJJCOB
	public int EDJMDDAGCEJ_S1 { get { return KPLDLGGMOMH_Crypted ^ FBGGEFFJJHB; } set { KPLDLGGMOMH_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF6E8 BCMKDNCFOJO 0x19BF6F8 DDIAEKOKDIE
	public int HEFPAIOLBAG_S2 { get { return HIJDFKKMONB_Crypted ^ FBGGEFFJJHB; } set { HIJDFKKMONB_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF708 EAGPNJEBOCP 0x19BF718 LLIGHINHLOL
	public int ENNCJKLIGKE_Lu { get { return LPNGJDDEJJD_Crypted ^ FBGGEFFJJHB; } set { LPNGJDDEJJD_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF728 CIGNNFNAAAN 0x19BF738 DOLNOHODMEI
	public int PALEGNNHIKH_Lf { get { return GFPNAILCPLG_Crypted ^ FBGGEFFJJHB; } set { GFPNAILCPLG_Crypted = value ^ FBGGEFFJJHB; } } //0x19BF748 MALPONGOPKO 0x19BF758 BHAFNMAEHOH

	// // RVA: 0x19BF768 Offset: 0x19BF768 VA: 0x19BF768 Slot: 4
	public virtual void LHPDDGIJKNB()
    {
        FBGGEFFJJHB = (int)NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime() * 0x1d32 + 13;
        BEBJKJKBOGH_D = 0;
        OFJHABJNGOD_Se = 0;
        NLKEBAOBJCM_Cb = 0;
        LAMCCNAKIOJ_Cr = 0;
        IPPNCOHEEOD_Av = 0;
        NHLGACIHDAH_Ex = 0;
        GOIKCKHMBDL_F = 0;
        AKNELONELJK_Df = 0;
        MIKICCLPDJA_L6 = 0;
        DIPKCALNIII_Dv = 0;
        BEEAIAAJOHD_Cs = 0;
        AFNIOJHODAG_CsCol = 0;
        HEBKEJBDCBH_Dl = 0;
        GLILAGLJLEP_S = 0;
        ECOLMPLOPFM_Sl = 0;
        CFCIMKOHLIG_M = 0;
        BDLNMOIOMHK_To = 0;
        KNIFCANOHOC_Sc = 0;
        EDJMDDAGCEJ_S1 = 0;
        HEFPAIOLBAG_S2 = 0;
        ENNCJKLIGKE_Lu = 0;
        PALEGNNHIKH_Lf = 0;
        for(int i = 0; i < MJNMPAKBNKB_Nr.Length; i++)
        {
            MJNMPAKBNKB_Nr[i] = 0;
        }
    }

	// // RVA: 0x19BF904 Offset: 0x19BF904 VA: 0x19BF904 Slot: 5
	public virtual bool AGBOGBEOFME(BLHNHKMMPAD OIKJFMGEICL)
	{
		if(GOIKCKHMBDL_F != OIKJFMGEICL.GOIKCKHMBDL_F)
			return false;
		if(AKNELONELJK_Df != OIKJFMGEICL.AKNELONELJK_Df)
			return false;
		if(BEBJKJKBOGH_D != OIKJFMGEICL.BEBJKJKBOGH_D)
			return false;
		if(MIKICCLPDJA_L6 != OIKJFMGEICL.MIKICCLPDJA_L6)
			return false;
		if(DIPKCALNIII_Dv != OIKJFMGEICL.DIPKCALNIII_Dv)
			return false;
		if(BEEAIAAJOHD_Cs != OIKJFMGEICL.BEEAIAAJOHD_Cs)
			return false;
		if(AFNIOJHODAG_CsCol != OIKJFMGEICL.AFNIOJHODAG_CsCol)
			return false;
		if(HEBKEJBDCBH_Dl != OIKJFMGEICL.HEBKEJBDCBH_Dl)
			return false;
		if(GLILAGLJLEP_S != OIKJFMGEICL.GLILAGLJLEP_S)
			return false;
		if(ECOLMPLOPFM_Sl != OIKJFMGEICL.ECOLMPLOPFM_Sl)
			return false;
		if(CFCIMKOHLIG_M != OIKJFMGEICL.CFCIMKOHLIG_M)
			return false;
		if(IPPNCOHEEOD_Av != OIKJFMGEICL.IPPNCOHEEOD_Av)
			return false;
		if(KNIFCANOHOC_Sc != OIKJFMGEICL.KNIFCANOHOC_Sc)
			return false;
		if(OFJHABJNGOD_Se != OIKJFMGEICL.OFJHABJNGOD_Se)
			return false;
		if(BDLNMOIOMHK_To != OIKJFMGEICL.BDLNMOIOMHK_To)
			return false;
		if(NLKEBAOBJCM_Cb != OIKJFMGEICL.NLKEBAOBJCM_Cb)
			return false;
		if(LAMCCNAKIOJ_Cr != OIKJFMGEICL.LAMCCNAKIOJ_Cr)
			return false;
		if(NHLGACIHDAH_Ex != OIKJFMGEICL.NHLGACIHDAH_Ex)
			return false;
		if(ENNCJKLIGKE_Lu != OIKJFMGEICL.ENNCJKLIGKE_Lu)
			return false;
		if(PALEGNNHIKH_Lf != OIKJFMGEICL.PALEGNNHIKH_Lf)
			return false;
		if(EDJMDDAGCEJ_S1 != OIKJFMGEICL.EDJMDDAGCEJ_S1)
			return false;
		if(HEFPAIOLBAG_S2 != OIKJFMGEICL.HEFPAIOLBAG_S2)
			return false;
		for(int i = 0; i < MJNMPAKBNKB_Nr.Length; i++)
		{
			if(MJNMPAKBNKB_Nr[i] != OIKJFMGEICL.MJNMPAKBNKB_Nr[i])
				return false;
		}
		return true;
	}

	// // RVA: 0x19BFEA0 Offset: 0x19BFEA0 VA: 0x19BFEA0 Slot: 6
	public virtual void ODDIHGPONFL(BLHNHKMMPAD OIKJFMGEICL)
	{
		GOIKCKHMBDL_F = OIKJFMGEICL.GOIKCKHMBDL_F;
		AKNELONELJK_Df = OIKJFMGEICL.AKNELONELJK_Df;
		MIKICCLPDJA_L6 = OIKJFMGEICL.MIKICCLPDJA_L6;
		DIPKCALNIII_Dv = OIKJFMGEICL.DIPKCALNIII_Dv;
		BEEAIAAJOHD_Cs = OIKJFMGEICL.BEEAIAAJOHD_Cs;
		AFNIOJHODAG_CsCol = OIKJFMGEICL.AFNIOJHODAG_CsCol;
		HEBKEJBDCBH_Dl = OIKJFMGEICL.HEBKEJBDCBH_Dl;
		GLILAGLJLEP_S = OIKJFMGEICL.GLILAGLJLEP_S;
		ECOLMPLOPFM_Sl = OIKJFMGEICL.ECOLMPLOPFM_Sl;
		IPPNCOHEEOD_Av = OIKJFMGEICL.IPPNCOHEEOD_Av;
		KNIFCANOHOC_Sc = OIKJFMGEICL.KNIFCANOHOC_Sc;
		OFJHABJNGOD_Se = OIKJFMGEICL.OFJHABJNGOD_Se;
		BEBJKJKBOGH_D = OIKJFMGEICL.BEBJKJKBOGH_D;
		NLKEBAOBJCM_Cb = OIKJFMGEICL.NLKEBAOBJCM_Cb;
		LAMCCNAKIOJ_Cr = OIKJFMGEICL.LAMCCNAKIOJ_Cr;
		BDLNMOIOMHK_To = OIKJFMGEICL.BDLNMOIOMHK_To;
		NHLGACIHDAH_Ex = OIKJFMGEICL.NHLGACIHDAH_Ex;
		ENNCJKLIGKE_Lu = OIKJFMGEICL.ENNCJKLIGKE_Lu;
		PALEGNNHIKH_Lf = OIKJFMGEICL.PALEGNNHIKH_Lf;
		EDJMDDAGCEJ_S1 = OIKJFMGEICL.EDJMDDAGCEJ_S1;
		HEFPAIOLBAG_S2 = OIKJFMGEICL.HEFPAIOLBAG_S2;
		for(int i = 0; i < MJNMPAKBNKB_Nr.Length; i++)
		{
			MJNMPAKBNKB_Nr[i] = OIKJFMGEICL.MJNMPAKBNKB_Nr[i];
		}
		GOIKCKHMBDL_F = OIKJFMGEICL.GOIKCKHMBDL_F;
		GOIKCKHMBDL_F = OIKJFMGEICL.GOIKCKHMBDL_F;
		GOIKCKHMBDL_F = OIKJFMGEICL.GOIKCKHMBDL_F;
		GOIKCKHMBDL_F = OIKJFMGEICL.GOIKCKHMBDL_F;
	}

	// // RVA: 0x19C039C Offset: 0x19C039C VA: 0x19C039C
	public EDOHBJAPLPF_JsonData NOJCMGAFAAC()
	{
		EDOHBJAPLPF_JsonData res = new EDOHBJAPLPF_JsonData();
		res["f"] = GOIKCKHMBDL_F;
		res["df"] = AKNELONELJK_Df;
		res["dv"] = DIPKCALNIII_Dv;
		res["cs"] = BEEAIAAJOHD_Cs;
		res["cs_col"] = AFNIOJHODAG_CsCol;
		res["dl"] = HEBKEJBDCBH_Dl;
		res["s"] = GLILAGLJLEP_S;
		res["sl"] = ECOLMPLOPFM_Sl;
		res["m"] = CFCIMKOHLIG_M;
		res["av"] = IPPNCOHEEOD_Av;
		res["cb"] = NLKEBAOBJCM_Cb;
		res["cr"] = LAMCCNAKIOJ_Cr;
		res["to"] = BDLNMOIOMHK_To;
		res["sc"] = KNIFCANOHOC_Sc;
		res["d"] = BEBJKJKBOGH_D;
		res["ex"] = NHLGACIHDAH_Ex;
		res["lu"] = ENNCJKLIGKE_Lu;
		res["lf"] = PALEGNNHIKH_Lf;
		res["s1"] = EDJMDDAGCEJ_S1;
		res["s2"] = HEFPAIOLBAG_S2;
		res["l6"] = MIKICCLPDJA_L6;
		res["se"] = OFJHABJNGOD_Se;
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		data.LAJDIPCJCPO_SetJsonType(JFBMDLGBPEN_JsonType.BDHGEFMCJDF_Array);
		for(int i = 0; i < 5; i++)
		{
			data.Add(MJNMPAKBNKB_Nr[i]);
		}
		res["nr"] = data;
		return res;
	}

	// // RVA: 0x19C0B6C Offset: 0x19C0B6C VA: 0x19C0B6C
	public void IIEMACPEEBJ(OKGLGHCBCJP_Database LKMHPJKIFDN, EDOHBJAPLPF_JsonData OBHAFLMHAKG, ref bool NGJDHLGMHMH)
	{
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("f"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("df"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("dv"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("cs"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("dl"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("s"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("sl"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("m"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("av"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("cb"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("cr"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("to"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("sc"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("d"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("ex"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("lu"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("lf"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("kr"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("s1"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("s2"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("l6"))
			NGJDHLGMHMH = true;
		if(!OBHAFLMHAKG.BBAJPINMOEP_Contains("se"))
			NGJDHLGMHMH = true;
		LHPDDGIJKNB();
		GOIKCKHMBDL_F = JsonUtil.GetInt(OBHAFLMHAKG, "f", 0);
		AKNELONELJK_Df = JsonUtil.GetInt(OBHAFLMHAKG, "df", 0);
		DIPKCALNIII_Dv = JsonUtil.GetInt(OBHAFLMHAKG, "dv", 0);
		BEEAIAAJOHD_Cs = JsonUtil.GetInt(OBHAFLMHAKG, "cs", 0);
		AFNIOJHODAG_CsCol = JsonUtil.GetInt(OBHAFLMHAKG, "cs_col", 0);
		HEBKEJBDCBH_Dl = JsonUtil.GetInt(OBHAFLMHAKG, "dl", 0);
		GLILAGLJLEP_S = JsonUtil.GetInt(OBHAFLMHAKG, "s", 0);
		ECOLMPLOPFM_Sl = JsonUtil.GetInt(OBHAFLMHAKG, "sl", 0);
		CFCIMKOHLIG_M = JsonUtil.GetInt(OBHAFLMHAKG, "m", 0);
		IPPNCOHEEOD_Av = JsonUtil.GetInt(OBHAFLMHAKG, "av", 0);
		NLKEBAOBJCM_Cb = JsonUtil.GetInt(OBHAFLMHAKG, "cb", 0);
		LAMCCNAKIOJ_Cr = JsonUtil.GetInt(OBHAFLMHAKG, "cr", 0);
		BDLNMOIOMHK_To = JsonUtil.GetInt(OBHAFLMHAKG, "to", 0);
		KNIFCANOHOC_Sc = JsonUtil.GetInt(OBHAFLMHAKG, "sc", 0);
		BEBJKJKBOGH_D = JsonUtil.GetLong(OBHAFLMHAKG, "d", 0);
		NHLGACIHDAH_Ex = JsonUtil.GetInt(OBHAFLMHAKG, "ex", 0);
		ENNCJKLIGKE_Lu = JsonUtil.GetInt(OBHAFLMHAKG, "lu", 0);
		PALEGNNHIKH_Lf = JsonUtil.GetInt(OBHAFLMHAKG, "lf", 0);
		EDJMDDAGCEJ_S1 = JsonUtil.GetInt(OBHAFLMHAKG, "s1", 0);
		HEFPAIOLBAG_S2 = JsonUtil.GetInt(OBHAFLMHAKG, "s2", 0);
		MIKICCLPDJA_L6 = JsonUtil.GetInt(OBHAFLMHAKG, "l6", 0);
		OFJHABJNGOD_Se = JsonUtil.GetInt(OBHAFLMHAKG, "se", 0);
		if(OFJHABJNGOD_Se < 0)
		{
			AKNELONELJK_Df = 0;
		}
		if(OFJHABJNGOD_Se > 4)
		{
			AKNELONELJK_Df = 4;
		}
		MIKICCLPDJA_L6 = 0;
		if(LKMHPJKIFDN.MGFMPKLLGHE_Diva.BEEGJHCDHJB_IsDivaAvaiable(DIPKCALNIII_Dv))
		{
			if(!LKMHPJKIFDN.MFPNGNMFEAL_Costume.OEMKAFGPOCE_IsCostumeAvaiable(BEEAIAAJOHD_Cs, DIPKCALNIII_Dv))
			{
				BEEAIAAJOHD_Cs = 0;
				AFNIOJHODAG_CsCol = 0;
			}
		}
		else
		{
			DIPKCALNIII_Dv = 1;
			BEEAIAAJOHD_Cs = 0;
			AFNIOJHODAG_CsCol = 0;
		}
		if(!LKMHPJKIFDN.ECNHDEHADGL_Scene.FGNJBMPDBLO_IsSceneValid(GLILAGLJLEP_S))
		{
			GLILAGLJLEP_S = 0;
			ECOLMPLOPFM_Sl = 0;
			CFCIMKOHLIG_M = 0;
		}
		IPPNCOHEEOD_Av = Mathf.Clamp(IPPNCOHEEOD_Av, 0, 99999999);
		if(OBHAFLMHAKG.BBAJPINMOEP_Contains("nr"))
		{
			EDOHBJAPLPF_JsonData data = OBHAFLMHAKG["nr"];
			for(int i = 0; i < 5; i++)
			{
				MJNMPAKBNKB_Nr[i] = (int)data[i];
				MJNMPAKBNKB_Nr[i] = Mathf.Clamp(MJNMPAKBNKB_Nr[i], 0, 9999);
			}
		}
		else
		{
			NGJDHLGMHMH = true;
		}
	}
}
