
public class BOPFPIHGJMD
{
	public enum ADMNKELOLPN
	{
		HJNNKCMLGFL = 0,
		CCAPCGPIIPF = 1,
		NBHIECDDJHH = 2,
		HFPIACELNLL = 3,
		HIIPBAMPCEM = 4,
		GEJGMBBCFEE = 5,
	}

    public enum JFHCHOILMEL
    {
        HJNNKCMLGFL_0 = 0,
        MLFOEICOGAP = 1,
        GNHENCIPDFK = 2,
    }
	
	public enum CMBJEEGFODD
	{
		HJNNKCMLGFL = 0,
		DPNBNKOOJHI = 1,
		ELCJGBEKIKD = 2,
		PIICPBCIHKN = 4,
		CDFJPMPHNJM = 8,
		JPFLFLFFEDD = 16,
		HIJBHIFABFC = 32,
	}
	
	public enum DBNJDPHLLHI
	{
		HJNNKCMLGFL = 0,
		CELJMOGCFCK = 1,
		OEMJLNBLENB = 2,
		FDKLFCEMHBP = 3,
		GNDAGINBJAG = 4,
		DCGPNEBJNIN = 5,
		JHDPHEILCBH = 6,
		NAGPNFFEBOF = 7,
		AIGCGFJOEGK = 8,
		KGEDHOOIJOI = 9,
		LKFPALJBJFM = 10,
		KMCGPEACGEE = 11,
	}
	
	public enum AHIOHONIGDH
	{
		HJNNKCMLGFL = 0,
		HOOPCKAOMGG = 1,
		GLICCOKGLPF = 2,
		IHCCBHDNHPC = 4,
		DBPDLIPKFAL = 8,
		GDEJFFFHFGP = 16,
	}
	
	public enum LGEIPIHHNPH
	{
		HJNNKCMLGFL = 0,
		HOOPCKAOMGG = 1,
		GLICCOKGLPF = 2,
		IHCCBHDNHPC = 3,
		DBPDLIPKFAL = 4,
		CFBJGAGBJEN = 5,
		GDEJFFFHFGP = 6,
		LCBPJOKNKPL = 7,
		AEFCOHJBLPO = 8,
	}
	
	public enum HDHDOOLPBEO
	{
		HJNNKCMLGFL = 0,
		CCDOBDNDPIL = 1,
		LJJODKKOOFD = 2,
		MOADAEHPFPA = 3,
	}

    public enum LEIPFJHOFPC
    {
        HJNNKCMLGFL = 0,
        NBDBAFGEEGA = 1,
        GLFGNEILACA = 2,
        GEJGMBBCFEE = 3,
    }
	
	public enum LBGOHNCBMDG
	{
		HJNNKCMLGFL = 0,
		KHBGFKPCOMI = 1,
		GIFEEFPDPBD = 2,
	}
	
	public enum AGGLEGJDLGF
	{
		HJNNKCMLGFL = 0,
		JPAODAPCJGG = 1,
		NLGNJNJBLEJ = 2,
	}
	
	public enum GNGGLPCONLM
	{
		HJNNKCMLGFL = 0,
		OCKIDPJNNBP_1 = 1,
		HHPBNBIEGHK = 2,
		BCMLFJPLKAM = 4,
		MGPHIBLKNMO = 8,
	}

	public enum MLBMHDCCGHI
	{
		HJNNKCMLGFL_0 = 0,
		HEFPAOLDHCK = 1,
		FDOOAJLGFAE = 2,
		FMLPIOFBCMA = 3,
		GENEIBGNMPH_4 = 4,
		GEJGMBBCFEE = 5,
	}
	public enum PDLKAKEABDP
	{
		EILIAPKFCEO_0 = 0,
		HFKNIAGOFKC_1 = 1,
		LGJIPMIHAKC_2 = 2,
		GHGLPOGHBBL_3 = 3,
	}
	
	public enum FDDGIANLNAD
	{
		BCMLFJPLKAM = 1,
		DMHGLBIOLLL = 2,
	}

	public enum IGHPDAGKIKO
	{
		FLFIICJKPKF = 0,
		EBAPFCDNMGD = 1,
		LGOIJAPMEBG = 2,
		FJGFAPKLLCL = 3,
		CADDNFIKDLG_4 = 4,
		GEJGMBBCFEE = 5,
	}
	
	public enum FPKMKLDDCNL
	{
		HJNNKCMLGFL = 0,
		HNOJIKHAPHA_1 = 1,
		HCBFMFONIOE = 2,
		KHLPAOENONH = 3,
	}
	
	public enum DLDOEOEFJKA
	{
		CCAPCGPIIPF_0 = 0,
		PLFJBGJMMDP_1 = 1,
		CCDOBDNDPIL_2 = 2,
		LJJODKKOOFD_3 = 3,
		MOADAEHPFPA_4 = 4,
	}
	
	public enum MGPIJGMDLOM
	{
		INIMBLOHIEF = 0,
		FMHLGHDKJBC = 1,
		JIOPJDJBLFK = 2,
		HJNNKCMLGFL = 3,
	}
	
	public enum HBJMIJIOCAM
	{
		FMHLGHDKJBC = 0,
		JIOPJDJBLFK = 1,
	}
	
	public enum CJDCPBACOLH
	{
		HFFNOFJBCAB = 0,
		LOAJGGDKOIH = 1,
		GAEONADENEJ = 2,
		CCAPCGPIIPF = 3,
	}

	public const int PHJLOHLFJBL = 1000;
	public const int PPGIAEJBHJP = 3;
	public const int BLJMNLACDMD = 3;
	public const int NPOPEFOHLGM = 3;
	public const int KPECCHDJLBK = 20;
	public const int GCCOCKNNEEK = 7;
	public const int NMAFKJNLOIK = 5;
	public const int KDNMNLCMDEF = 3;
	public const int AKCPFDEIHMJ = 0;
	public const int PIEBKBMBMCG = 9;
	public const int CDMNGLDLMFB = 5;
	public const int ACOFKGALJDD = 6;
	public const int PJIOAJAJPJI = 4;
	public const int OBKDAIIPMOB = 3;
	public const int LDEDNDHDJKP = 88;
}
