
[System.Obsolete("Use BPOJMOOIIFI_PlayerLevelData", true)]
public class BPOJMOOIIFI { }
public class BPOJMOOIIFI_PlayerLevelData
{
	private JJOPEDJCCJK_Exp FMPEMFPLPDA_DbExp; // 0x8
	public int FDNEEPFGPLH; // 0xC
	public bool LDHOOPGDBJC; // 0x10
	public int ALBCEALLGJG_Exp; // 0x14
	public int APIIHFJGEAO_Level; // 0x18
	public bool BKKNOOFHMMG; // 0x1C
	public int GIEHGPCHKPF_MaxStamina; // 0x20
	public int EDCAHIECMCE_MaxFriend; // 0x24
	public int GLAJCLEAKJJ_Exp2; // 0x28
	public int IANDPFDFAKP_Level2; // 0x2C
	public bool DMJCCEACFOG; // 0x30
	public int JCMCBGMEKJG; // 0x34
	public int EPNALMONMHB; // 0x38
	public int OFILPHEMLCB_MaxFriend2; // 0x3C
	public int OJBGOOBBMFP; // 0x40

	// RVA: 0x18F01EC Offset: 0x18F01EC VA: 0x18F01EC
	//public int NDFGMMKGBAA(int CIEOBFIIPLD) { }

	// RVA: 0x18F0220 Offset: 0x18F0220 VA: 0x18F0220
	public void KHEKNNFCAOI()
	{
		FMPEMFPLPDA_DbExp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.FMPEMFPLPDA_Exp;
		PEBFNABDJDI_System dbSystem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.GDEKCOOBLMA_System;
		BBHNACPENDM_ServerSaveData serverSave = CIOECGOMILE.HHCJCDFCLOB.MNJHBCIIHED_PrevServerData;
		ALBCEALLGJG_Exp = serverSave.KCCLEHLLOFG_Common.EOHDMCMHBKJ_Exp;
		APIIHFJGEAO_Level = serverSave.KCCLEHLLOFG_Common.KIECDDFNCAN_Level;
		GIEHGPCHKPF_MaxStamina = FMPEMFPLPDA_DbExp.HPEOBAEGHKC_GetStaminaGainForLevel(APIIHFJGEAO_Level);
		EDCAHIECMCE_MaxFriend = FMPEMFPLPDA_DbExp.PCJACJANGCA_GetFriendForLevel(APIIHFJGEAO_Level);
		BKKNOOFHMMG = dbSystem.NGHKJOEDLIP.PIAMMJNADJH_Plv <= APIIHFJGEAO_Level;
		GLAJCLEAKJJ_Exp2 = serverSave.KCCLEHLLOFG_Common.EOHDMCMHBKJ_Exp;
		IANDPFDFAKP_Level2 = serverSave.KCCLEHLLOFG_Common.KIECDDFNCAN_Level;
		JCMCBGMEKJG = CIOECGOMILE.HHCJCDFCLOB.BPLOEAHOPFI.DCBENCMNOGO;
		EPNALMONMHB = CIOECGOMILE.HHCJCDFCLOB.BPLOEAHOPFI.DCLKMNGMIKC();
		OFILPHEMLCB_MaxFriend2 = FMPEMFPLPDA_DbExp.PCJACJANGCA_GetFriendForLevel(IANDPFDFAKP_Level2);
		DMJCCEACFOG = dbSystem.NGHKJOEDLIP.PIAMMJNADJH_Plv <= IANDPFDFAKP_Level2;
		LDHOOPGDBJC = APIIHFJGEAO_Level < IANDPFDFAKP_Level2;
		FDNEEPFGPLH = JGEOBNENMAH.HHCJCDFCLOB.FOIPBBCHBIB;
		OJBGOOBBMFP = JGEOBNENMAH.HHCJCDFCLOB.HBAJPMDOMPL;
	}
}
