
[System.Obsolete("Use BPOJMOOIIFI_PlayerLevelData", true)]
public class BPOJMOOIIFI { }
public class BPOJMOOIIFI_PlayerLevelData
{
	private JJOPEDJCCJK_Exp FMPEMFPLPDA_DbExp; // 0x8
	public int FDNEEPFGPLH_GainExp; // 0xC
	public bool LDHOOPGDBJC_IsLevelUp; // 0x10
	public int ALBCEALLGJG_PrevExp; // 0x14
	public int APIIHFJGEAO_PrevLevel; // 0x18
	public bool BKKNOOFHMMG_WasMaxLevel; // 0x1C
	public int GIEHGPCHKPF_PrevMaxStamina; // 0x20
	public int EDCAHIECMCE_PrevMaxFriend; // 0x24
	public int GLAJCLEAKJJ_Exp; // 0x28
	public int IANDPFDFAKP_Level; // 0x2C
	public bool DMJCCEACFOG_IsMaxLevel; // 0x30
	public int JCMCBGMEKJG_MaxStamina; // 0x34
	public int EPNALMONMHB_CurrentStamina; // 0x38
	public int OFILPHEMLCB_MaxFriend; // 0x3C
	public int OJBGOOBBMFP; // 0x40

	// RVA: 0x18F01EC Offset: 0x18F01EC VA: 0x18F01EC
	//public int NDFGMMKGBAA(int CIEOBFIIPLD) { }

	// RVA: 0x18F0220 Offset: 0x18F0220 VA: 0x18F0220
	public void KHEKNNFCAOI()
	{
		FMPEMFPLPDA_DbExp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.FMPEMFPLPDA_Exp;
		PEBFNABDJDI_System dbSystem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.GDEKCOOBLMA_System;
		BBHNACPENDM_ServerSaveData serverSave = CIOECGOMILE.HHCJCDFCLOB.MNJHBCIIHED_PrevServerData;
		ALBCEALLGJG_PrevExp = serverSave.KCCLEHLLOFG_Common.EOHDMCMHBKJ_Exp;
		APIIHFJGEAO_PrevLevel = serverSave.KCCLEHLLOFG_Common.KIECDDFNCAN_Level;
		GIEHGPCHKPF_PrevMaxStamina = FMPEMFPLPDA_DbExp.HPEOBAEGHKC_GetStaminaGainForLevel(APIIHFJGEAO_PrevLevel);
		EDCAHIECMCE_PrevMaxFriend = FMPEMFPLPDA_DbExp.PCJACJANGCA_GetFriendForLevel(APIIHFJGEAO_PrevLevel);
		BKKNOOFHMMG_WasMaxLevel = dbSystem.NGHKJOEDLIP.PIAMMJNADJH_PlayerMaxLevel <= APIIHFJGEAO_PrevLevel;
		serverSave = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave;
		GLAJCLEAKJJ_Exp = serverSave.KCCLEHLLOFG_Common.EOHDMCMHBKJ_Exp;
		IANDPFDFAKP_Level = serverSave.KCCLEHLLOFG_Common.KIECDDFNCAN_Level;
		JCMCBGMEKJG_MaxStamina = CIOECGOMILE.HHCJCDFCLOB.BPLOEAHOPFI_StaminaUpdater.DCBENCMNOGO_MaxStamina;
		EPNALMONMHB_CurrentStamina = CIOECGOMILE.HHCJCDFCLOB.BPLOEAHOPFI_StaminaUpdater.DCLKMNGMIKC_GetCurrent();
		OFILPHEMLCB_MaxFriend = FMPEMFPLPDA_DbExp.PCJACJANGCA_GetFriendForLevel(IANDPFDFAKP_Level);
		DMJCCEACFOG_IsMaxLevel = dbSystem.NGHKJOEDLIP.PIAMMJNADJH_PlayerMaxLevel <= IANDPFDFAKP_Level;
		LDHOOPGDBJC_IsLevelUp = APIIHFJGEAO_PrevLevel < IANDPFDFAKP_Level;
		FDNEEPFGPLH_GainExp = JGEOBNENMAH.HHCJCDFCLOB.FOIPBBCHBIB;
		OJBGOOBBMFP = JGEOBNENMAH.HHCJCDFCLOB.HBAJPMDOMPL;
	}
}
