
using XeApp.Game.Common;
using System.Collections.Generic;

public static class CMMKCEPBIHI
{
    public enum NOJENDEDECD
    {
        HNGJDMNPMNP = 0,
        KBHGPMNGALJ = 1,
        AJIDOFDBIDL = 2,
        NLAGKLDCBAG = 3,
        GJDKJOHIEFF = 4,
        BMMPEPDFICC = 5,
        CPJOGHCLENG = 6,
        NKPLJNILBFP = 7,
        GGOOOIKELDH = 8,
        OPCNHIMPGCE = 9,
        AEFCOHJBLPO = 10,
    }

	private const int IMNILJDBFDL = 30;
	private const int NPMLACIOKJE = 1;
	private static StatusData GCECPDEOIIN = new StatusData(); // 0x0
	// private static Comparison<GCIJNCFDNON>[] MOGECDOLPPL = new Comparison<GCIJNCFDNON>[3] {
    //     (GCIJNCFDNON HKICMNAACDA, GCIJNCFDNON BNKHBCBJBKI) => {
    //         0x175A31C
    //     },
    //     (GCIJNCFDNON HKICMNAACDA, GCIJNCFDNON BNKHBCBJBKI) => {
    //         0x175A39C
    //     },
    //     (GCIJNCFDNON HKICMNAACDA, GCIJNCFDNON BNKHBCBJBKI) => {
    //         0x175A41C
    //     }
    // }; // 0x4
	// private static Func<StatusData, int>[] HDLKMMHKOKE = new Func<StatusData, int>[3] {
    //     (StatusData IBDJFHFIIHN) => {
    //         0x175A49C
    //     },
    //     (StatusData IBDJFHFIIHN) => {
    //         0x175A4C0
    //     },
    //     (StatusData IBDJFHFIIHN) => {
    //         0x175A4E4
    //     }
    // }; // 0x8
	// private static Action<StatusData, int>[] HOBOLJEFDFF = new Action<StatusData, int>[3] {
    //     (StatusData IBDJFHFIIHN, int OHDPMGMGJBI) => {
    //         0x175A508
    //     },
    //     (StatusData IBDJFHFIIHN, int OHDPMGMGJBI) => {
    //         0x175A54C
    //     },
    //     (StatusData IBDJFHFIIHN, int OHDPMGMGJBI) => {
    //         0x175A54C
    //     }
    // }; // 0xC
	private static int[] OOPMCKOCEFM = new int[10]; // 0x10
	private static float[] LKBGHCIKIOA = new float[5]; // 0x14
	private static int[] HCEPBDBHILM = new int[10] { 100, 100, 100, 90, 100, 100, 90, 90, 90, 90 }; // 0x18
	private static string[] DALGMKEOFLN = new string[8] {"score_gauge_e", "score_gauge_n", "score_gauge_h", "score_gauge_vh", 
        "score_gauge_ex", "score_gauge_h+", "score_gauge_vh+", "score_gauge_ex+"}; // 0x1C
	private static StatusData FLOHCPIIHEH = new StatusData(); // 0x20
	// private static AEKDNMPPOJN OMPNCHBNEPF = new AEKDNMPPOJN(); // 0x24
	private static LimitOverStatusData MEMCOJHNEIP = new LimitOverStatusData(); // 0x28
	private static List<int> AONMBIEIBCD = new List<int>(); // 0x2C
	private static List<int> FOMKBDKKODO = new List<int>(); // 0x30
	private static int AFBHKBGLMHG = 245; // 0x34
	private static List<int> DNJCAKPKNDP = new List<int>(); // 0x38

	public static ResultScoreRank.Type KHCOOPDAGOE { get; set; } // 0x3C
	public static float FDLECNKJCGG { get; set; } // 0x40

	// // RVA: 0x1085914 Offset: 0x1085914 VA: 0x1085914
	// public static void DIDENKKDJKI(ref AEGLGBOGDHH HBODCMLFDOB, JLKEOGLJNOD MLAFAACKKBG, DFKGGBMFFGB AHEFHIMGIBI, EEDKAACNBBG KKHIDFKKFJE, EAJCBFGKKFA PCEGKKLKFNO, EJKBKMBJMGL KDOLMBEAGCI) { }

	// // RVA: 0x1085B98 Offset: 0x1085B98 VA: 0x1085B98
	public static void AECDJDIJJKD(ref EDMIONMCICN HBODCMLFDOB, FFHPBEPOMAK DGCJCAHIAPP, JLKEOGLJNOD MLAFAACKKBG, DFKGGBMFFGB AHEFHIMGIBI, EEDKAACNBBG KKHIDFKKFJE, EAJCBFGKKFA PCEGKKLKFNO, EJKBKMBJMGL KDOLMBEAGCI)
	{
		TodoLogger.Log(0, "AECDJDIJJKD");
	}

	// // RVA: 0x1087134 Offset: 0x1087134 VA: 0x1087134
	// public static void NIPJMNDBCNF(ref EDMIONMCICN HBODCMLFDOB, JLKEOGLJNOD MLAFAACKKBG, EAJCBFGKKFA PCEGKKLKFNO, DFKGGBMFFGB AHEFHIMGIBI, EEDKAACNBBG KKHIDFKKFJE, EJKBKMBJMGL KDOLMBEAGCI) { }

	// // RVA: 0x1087C58 Offset: 0x1087C58 VA: 0x1087C58
	// private static void AECDJDIJJKD(ref EDMIONMCICN HBODCMLFDOB, FFHPBEPOMAK DGCJCAHIAPP, List<GCIJNCFDNON> OPIBAPEGCLA, EEDKAACNBBG KKHIDFKKFJE, JNKEEAOKNCI.MKGJHBAKMBD GJLFANGDGCL, ref HPODBOHGGDH CHMOEPNAJOO, int ABBDKBOIBCG, JLKEOGLJNOD MLAFAACKKBG) { }

	// // RVA: 0x1087F7C Offset: 0x1087F7C VA: 0x1087F7C
	// private static void AECDJDIJJKD(ref EDMIONMCICN HBODCMLFDOB, FFHPBEPOMAK DGCJCAHIAPP, GCIJNCFDNON AFBMEMCHJCL, GCIJNCFDNON HAPFNHPFBGD, GCIJNCFDNON JEBHFJEJAKJ, EEDKAACNBBG KKHIDFKKFJE, JNKEEAOKNCI.MKGJHBAKMBD GJLFANGDGCL, ref HPODBOHGGDH CHMOEPNAJOO, int ABBDKBOIBCG, JLKEOGLJNOD MLAFAACKKBG) { }

	// // RVA: 0x1087F6C Offset: 0x1087F6C VA: 0x1087F6C
	// private static void DALDDNMEMJE(ref EDMIONMCICN HBODCMLFDOB) { }

	// // RVA: 0x10890F4 Offset: 0x10890F4 VA: 0x10890F4
	// private static void LBBNJAGGCBB(ref EDMIONMCICN HBODCMLFDOB, StatusData BALBKJFMDFN) { }

	// // RVA: 0x1089190 Offset: 0x1089190 VA: 0x1089190
	// private static void MEICPKJFJOA(ref EDMIONMCICN HBODCMLFDOB, StatusData BALBKJFMDFN) { }

	// // RVA: 0x108897C Offset: 0x108897C VA: 0x108897C
	// private static KFCIIMBBNCD KDDDDMMMBHE(JNKEEAOKNCI FOFADHAENKC, int BFGNMDGOEID, JNKEEAOKNCI.MKGJHBAKMBD GJLFANGDGCL) { }

	// // RVA: 0x1088AC0 Offset: 0x1088AC0 VA: 0x1088AC0
	// private static bool FNIEADNMMIA(CenterSkillCondition.Type FKDOMKHHOCD, EEDKAACNBBG KKHIDFKKFJE, SeriesAttr.Type AIHCEGFANAM = 0) { }

	// // RVA: 0x1088C18 Offset: 0x1088C18 VA: 0x1088C18
	// private static bool FLPKCFDANMK(FFHPBEPOMAK FDBOPFEOENF, CenterSkillTarget.Type GJLFANGDGCL, int ABBDKBOIBCG) { }

	// // RVA: 0x108922C Offset: 0x108922C VA: 0x108922C
	// private static bool FJHLLHFGICG(GCIJNCFDNON COIODGJDJEJ, CenterSkillTarget.Type GJLFANGDGCL, int ABBDKBOIBCG, int HBMFKPPOPMK) { }

	// // RVA: 0x1088D0C Offset: 0x1088D0C VA: 0x1088D0C
	// private static void KDOFDLIMHJG(ref StatusData BALBKJFMDFN, StatusData JLJGCBOHJID, JNKEEAOKNCI.MKGJHBAKMBD GJLFANGDGCL, int PGLJHBODOHN, int CIEOBFIIPLD, JLKEOGLJNOD MLAFAACKKBG) { }

	// // RVA: 0x10896DC Offset: 0x10896DC VA: 0x10896DC
	// private static void CHJHPJHNCEB(ref StatusData BALBKJFMDFN, StatusData JLJGCBOHJID, byte INDDJNMPONH, float NANNGLGOFKH) { }

	// // RVA: 0x1087F4C Offset: 0x1087F4C VA: 0x1087F4C
	public static bool OJNOJNEKBKH(int LNGOBGPDBAG, int GMPOGAFIAEF)
    {
        return GMPOGAFIAEF == 4 || GMPOGAFIAEF == LNGOBGPDBAG;
    }

	// // RVA: 0x10868E8 Offset: 0x10868E8 VA: 0x10868E8
	// private static void NJNBELLEGCN(ref CFHDKAFLNEP HBODCMLFDOB, JLKEOGLJNOD MLAFAACKKBG, DFKGGBMFFGB AHEFHIMGIBI, EEDKAACNBBG KKHIDFKKFJE, EAJCBFGKKFA PCEGKKLKFNO, EJKBKMBJMGL KDOLMBEAGCI) { }

	// // RVA: 0x1089E00 Offset: 0x1089E00 VA: 0x1089E00
	// public static void NJNBELLEGCN(ref CFHDKAFLNEP HBODCMLFDOB, int[,] EDAJDLJHBKP, List<List<GCIJNCFDNON>> OPIBAPEGCLA, DFKGGBMFFGB AHEFHIMGIBI, JLKEOGLJNOD MLAFAACKKBG, EEDKAACNBBG KKHIDFKKFJE, EAJCBFGKKFA PCEGKKLKFNO, EJKBKMBJMGL KDOLMBEAGCI) { }

	// // RVA: 0x108BAF0 Offset: 0x108BAF0 VA: 0x108BAF0
	// private static void MHPBLAEDJOC(ref StatusData BALBKJFMDFN, GCIJNCFDNON COIODGJDJEJ, EEDKAACNBBG KKHIDFKKFJE, int ENMAEBJGEKL, int CNLIAMIIJID, JLKEOGLJNOD MLAFAACKKBG) { }

	// // RVA: 0x1089374 Offset: 0x1089374 VA: 0x1089374
	// public static int FPJIKEFIJOL(int NCNFMHDKAPN, JLKEOGLJNOD CDCKLJAJBDO) { }

	// [CompilerGeneratedAttribute] // RVA: 0x740684 Offset: 0x740684 VA: 0x740684
	// // RVA: 0x108BEB8 Offset: 0x108BEB8 VA: 0x108BEB8
	// public static ResultScoreRank.Type CKNLMMGELDF() { }

	// [CompilerGeneratedAttribute] // RVA: 0x740694 Offset: 0x740694 VA: 0x740694
	// // RVA: 0x108BF44 Offset: 0x108BF44 VA: 0x108BF44
	// private static void GEENHBHNFIC(ResultScoreRank.Type NANNGLGOFKH) { }

	// [CompilerGeneratedAttribute] // RVA: 0x7406A4 Offset: 0x7406A4 VA: 0x7406A4
	// // RVA: 0x108BFD4 Offset: 0x108BFD4 VA: 0x108BFD4
	// public static float IGEHABMEOHD() { }

	// [CompilerGeneratedAttribute] // RVA: 0x7406B4 Offset: 0x7406B4 VA: 0x7406B4
	// // RVA: 0x108C060 Offset: 0x108C060 VA: 0x108C060
	// private static void FOLIPOFKIJA(float NANNGLGOFKH) { }

	// // RVA: 0x108C0FC Offset: 0x108C0FC VA: 0x108C0FC
	// public static int NDNOLJACLLC(CMMKCEPBIHI.NOJENDEDECD HLANCDFJFIA) { }

	// // RVA: 0x108C1C0 Offset: 0x108C1C0 VA: 0x108C1C0
	// public static int EPNPGMCGJKB(Difficulty.Type AKNELONELJK, bool NGKGFBLFEGH) { }

	// // RVA: 0x108C2EC Offset: 0x108C2EC VA: 0x108C2EC
	// public static float GPCKPNJGANO(ResultScoreRank.Type FJOLNJLLJEJ) { }

	// // RVA: 0x108C3B0 Offset: 0x108C3B0 VA: 0x108C3B0
	// public static void EFCNOOFFMIL(DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, EJKBKMBJMGL BGJGFPPDNEP, Difficulty.Type AKNELONELJK, bool PDLCNDBOMAN, bool CMEOKJMCEBH) { }

	// // RVA: 0x108C488 Offset: 0x108C488 VA: 0x108C488
	// public static void EFCNOOFFMIL(DFKGGBMFFGB DJLNOAMJECI, JLKEOGLJNOD HJJNDDPGIML, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, EJKBKMBJMGL BGJGFPPDNEP, Difficulty.Type AKNELONELJK, bool PDLCNDBOMAN) { }

	// // RVA: 0x1092B60 Offset: 0x1092B60 VA: 0x1092B60
	// public static void BKBMHJBFDOG() { }

	// // RVA: 0x108D788 Offset: 0x108D788 VA: 0x108D788
	// private static int CBILJEAECKP(DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EJKBKMBJMGL BGJGFPPDNEP, EEDKAACNBBG GMFMMDAKENC, Difficulty.Type AKNELONELJK, bool GBNOALJPOBM, int BAKLKJLPLOJ, int DHIPGHBJLIL, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x108E2F8 Offset: 0x108E2F8 VA: 0x108E2F8
	// private static int CHCGGEPAAOE(DFKGGBMFFGB AHEFHIMGIBI, EEDKAACNBBG KKHIDFKKFJE, EAJCBFGKKFA PCEGKKLKFNO, EJKBKMBJMGL KDOLMBEAGCI, int DHIPGHBJLIL, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x108E584 Offset: 0x108E584 VA: 0x108E584
	// private static int DONJDICAMJB(DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, EJKBKMBJMGL BGJGFPPDNEP, ref CFHDKAFLNEP LNMECJDKFDN, int DHIPGHBJLIL, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x108E93C Offset: 0x108E93C VA: 0x108E93C
	// private static int DBHEBCCLIJG(ref EDMIONMCICN HBODCMLFDOB, DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, EJKBKMBJMGL BGJGFPPDNEP, ref CFHDKAFLNEP LNMECJDKFDN, int DHIPGHBJLIL, bool CCPIGKONMMH, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x108DEA8 Offset: 0x108DEA8 VA: 0x108DEA8
	// private static int MHIKPDIJKJO(DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, EJKBKMBJMGL BGJGFPPDNEP, ref CFHDKAFLNEP HBODCMLFDOB, int DHIPGHBJLIL, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1092FB8 Offset: 0x1092FB8 VA: 0x1092FB8
	// private static int FILPDDHMKEJ(GCIJNCFDNON LAPAEBEIAFK, EEDKAACNBBG GMFMMDAKENC, FFHPBEPOMAK JCFNFJJKPAM) { }

	// // RVA: 0x1093268 Offset: 0x1093268 VA: 0x1093268
	// private static int OPGMFCHDEDF(int KPIIIEGGPIB, GCIJNCFDNON COIODGJDJEJ, int FLKGCONIFEE, int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, bool KIFJKGDBDBH, JLKEOGLJNOD HEDKFICAPIJ, FFHPBEPOMAK NENDFGDMJDN) { }

	// // RVA: 0x108F96C Offset: 0x108F96C VA: 0x108F96C
	// private static int LKGBAIANMLE(int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, bool HGEKDNNJAAC, bool OOOGNIPJMDE, bool OHLCKPIMMFH, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1092720 Offset: 0x1092720 VA: 0x1092720
	// private static int NGCOIOANNPA(int FLKGCONIFEE, int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x10908A8 Offset: 0x10908A8 VA: 0x10908A8
	// private static int BPPIFIAGLBI(int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1090E60 Offset: 0x1090E60 VA: 0x1090E60
	// private static int CBIIKLGPILB(int KHDDPKHPJID, EEDKAACNBBG GMFMMDAKENC, DFKGGBMFFGB DJLNOAMJECI, Difficulty.Type AKNELONELJK, KLBKPANJCPL POMOLHBFAPM, bool GBNOALJPOBM, int BAKLKJLPLOJ, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x10915F0 Offset: 0x10915F0 VA: 0x10915F0
	// private static int OPKNHONFIOG(int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, bool HGEKDNNJAAC, bool OOOGNIPJMDE, bool OHLCKPIMMFH, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1094624 Offset: 0x1094624 VA: 0x1094624
	// private static void HHOKCLBEOHI(LimitOverStatusData CMCKNKKCNDK, GCIJNCFDNON PNLOINMCCKH, EEDKAACNBBG KKHIDFKKFJE) { }

	// // RVA: 0x10939D4 Offset: 0x10939D4 VA: 0x10939D4
	// private static int IGDGGMIMLDN(int NKGHBKFMFCI, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, SkillBuffEffect.Type MCJEIDPDMLF, int NEJBNCHLMNJ, KLBKPANJCPL POMOLHBFAPM, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1093FD0 Offset: 0x1093FD0 VA: 0x1093FD0
	// private static int CPPANAJNEDJ(int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, SkillBuffEffect.Type MCJEIDPDMLF, int NKGHBKFMFCI, SkillDuration.Type FPMFEKIPFPI, int PHAGNOHBMCM, SkillTrigger.Type BAAFOOKFDLL, int LFGFBMJNBKN, KLBKPANJCPL POMOLHBFAPM, bool HGEKDNNJAAC, bool OOOGNIPJMDE, bool OHLCKPIMMFH) { }

	// // RVA: 0x109435C Offset: 0x109435C VA: 0x109435C
	// private static int MCKHJBNJFJH(int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, SkillBuffEffect.Type MCJEIDPDMLF, int NKGHBKFMFCI, SkillDuration.Type FPMFEKIPFPI, int PHAGNOHBMCM, SkillTrigger.Type BAAFOOKFDLL, int LFGFBMJNBKN, KLBKPANJCPL POMOLHBFAPM, bool HGEKDNNJAAC, bool OHLCKPIMMFH) { }

	// // RVA: 0x1093E5C Offset: 0x1093E5C VA: 0x1093E5C
	// private static int MEAHJKCBGFE(int FLKGCONIFEE, int KHDDPKHPJID, DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, SkillBuffEffect.Type MCJEIDPDMLF, int NKGHBKFMFCI, SkillDuration.Type FPMFEKIPFPI, int PHAGNOHBMCM, SkillTrigger.Type BAAFOOKFDLL, int LFGFBMJNBKN, int JLDDHNFKGHL, KLBKPANJCPL POMOLHBFAPM, bool KIFJKGDBDBH = False) { }

	// // RVA: 0x108EE08 Offset: 0x108EE08 VA: 0x108EE08
	// private static bool MODGPFEPLIP(ref EDMIONMCICN HBODCMLFDOB, DFKGGBMFFGB DJLNOAMJECI, EAJCBFGKKFA ALOBLKOHIKD, EEDKAACNBBG GMFMMDAKENC, KLBKPANJCPL POMOLHBFAPM, Difficulty.Type AKNELONELJK, bool GIKLNODJKFK, out bool HGEKDNNJAAC, out bool OHLCKPIMMFH, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x10947B0 Offset: 0x10947B0 VA: 0x10947B0
	// private static float BEFDPKNGHPO(float EGIGDODCJOG, int LKCCMBEOLLA, int DCBENCMNOGO, float GKHEOELGCAP, float IHEACEHPHKP, float JDIKNJEJCNN, int NNFBAIJKCCP, float GLDFMGNCOGM, int EDGIJNGLBDE) { }

	// // RVA: 0x1094918 Offset: 0x1094918 VA: 0x1094918
	// private static bool PKLPIDIBHMN(DFKGGBMFFGB DJLNOAMJECI, EEDKAACNBBG GMFMMDAKENC, Difficulty.Type AKNELONELJK, bool GIKLNODJKFK, int EDGIJNGLBDE, float PGEDGKMCFLB, out bool HGEKDNNJAAC, JLKEOGLJNOD HEDKFICAPIJ) { }

	// // RVA: 0x1095364 Offset: 0x1095364 VA: 0x1095364
	// private static int OEEDGPGEPFH(float ALOGOPNMLJI, float EDGBEFKOGMN, float IFMEDLKMHIG, int LGGLNFIKCKF, int CKFNNECHOGG, float PBIFADDFADF, float KOMJMBBPMML, int EDGIJNGLBDE, out int GBMNIAOLBEB) { }

	// // RVA: 0x10956D0 Offset: 0x10956D0 VA: 0x10956D0
	// private static float FDIIFOOLDGM(float EDGBEFKOGMN, float IFMEDLKMHIG, float KOMJMBBPMML, out int GBMNIAOLBEB) { }

	// // RVA: 0x1093648 Offset: 0x1093648 VA: 0x1093648
	// private static int CKNDJNOFFGP(PPGHMBNIAEC KMHPOGKCHHK, int AOGDKBPNGCI, int GBMHFDKCFGB, FFHPBEPOMAK HIDAJBOHJKH) { }

	// // RVA: 0x109477C Offset: 0x109477C VA: 0x109477C
	// private static bool BBIBJKIKBPO(SkillBuffEffect.Type LFAFFMFOFEG) { }
}
