
using System.Collections.Generic;
using UnityEngine;

public class CNNIKANJMNG
{
	public static CNNIKANJMNG HHCJCDFCLOB; // 0x0
	private string CDHPNAJNNFN; // 0x8
	private int JLIIKLHGBJH; // 0xC
	private bool EBJDDBPFNPB; // 0x10
	//private List<CHPIKCFKJOA> ICJOJOPKNBK = new List<CHPIKCFKJOA>(50); // 0x14
	private int MLPLGFLKKLI = 10; // 0x18
	private int AOPELJFAMCL = 1; // 0x1C

	// RVA: 0x175D098 Offset: 0x175D098 VA: 0x175D098
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
	}

	//// RVA: 0x175D0FC Offset: 0x175D0FC VA: 0x175D0FC
	//public void FAMFKPBPIAA(string DEPGBBJMFED, int HHNFHJCAPJO, bool PFFJNEFNAMI, int CJHEHIMLGGL, int LHJCOPMMIGO, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//[IteratorStateMachineAttribute] // RVA: 0x6BA4E4 Offset: 0x6BA4E4 VA: 0x6BA4E4
	//// RVA: 0x175D1EC Offset: 0x175D1EC VA: 0x175D1EC
	//private IEnumerator BHBKPEOMNJH_RankingPlayerList(string DEPGBBJMFED, int HHNFHJCAPJO, bool PFFJNEFNAMI, int CJHEHIMLGGL, int LHJCOPMMIGO, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0x175D354 Offset: 0x175D354 VA: 0x175D354
	//private void BJKCAKJHMPC(int CJHEHIMLGGL, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0x175D630 Offset: 0x175D630 VA: 0x175D630
	public void JPNACOLKHLB(int CJHEHIMLGGL, int NEFEFHBHFFF, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG)
	{
		TodoLogger.Log(0, "JPNACOLKHLB");
	}

	//[IteratorStateMachineAttribute] // RVA: 0x6BA55C Offset: 0x6BA55C VA: 0x6BA55C
	//// RVA: 0x175D6A4 Offset: 0x175D6A4 VA: 0x175D6A4
	//private IEnumerator ACAJCMEIJCH_AddRankingPlayerListSecond(int CJHEHIMLGGL, int NEFEFHBHFFF, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0x175D7D4 Offset: 0x175D7D4 VA: 0x175D7D4
	//private void FGEIGGNCGGD(List<int> HMDAFLDJLIK, int CJHEHIMLGGL, int NEFEFHBHFFF, List<OBGBKHKMDNF> NFMMAELFANG, LIOLBKLMMIK KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0x175DC44 Offset: 0x175DC44 VA: 0x175DC44
	//private IBIGBMDANNM APGCNBONNPE(string DEPGBBJMFED, int HHNFHJCAPJO) { }

	//// RVA: 0x175DEAC Offset: 0x175DEAC VA: 0x175DEAC
	//private int IKJBJNJLMKH(BBHNACPENDM AHEFHIMGIBI, string DEPGBBJMFED, int HHNFHJCAPJO) { }

	//// RVA: 0x175DF28 Offset: 0x175DF28 VA: 0x175DF28
	//private double LEIMLIFCHCD(BBHNACPENDM AHEFHIMGIBI, string DEPGBBJMFED, int HHNFHJCAPJO) { }
}
