
public class CNPDMOGIBEN
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int FNEIADJMHHO { get; set; } // 0x10 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public int KOMKKBDABJP { get; set; } // 0x14 JPPMFGFLNGH MOMCBDJIGKO NECMHGINPDE
	public string KOHNLDKIKPC { get; set; } // 0x18 EAMJMDBMNKI KLCNELOBOGM ILNHCICNFHF
	public string BPFBAHCDJFJ { get; set; } // 0x1C BCJILIKDOAD CBFEAHBKODM KJLAKHNLPCG
}
