
public class DKFJADMCNPI
{
	public enum PBIBFAHJOKC
	{
		HEFKAMJNFFO = 0,
		MAFLOGHFHOP = 1,
		IPFBEMAOMCF = 2,
		AFEAALBOEGO = 3,
		LHAFCFABHAP = 4,
		IMPOKJGGPNO = 5,
		FDEKNOCEFNM = 6,
		LLCBPJBBAIM = 7,
		GEJGMBBCFEE = 8,
	}

	public enum NLKCMNHOBAI
	{
		HJNNKCMLGFL_0 = 0,
		CLJMJHDGPOC_1 = 1,
		IBGNFEOLKDP = 2,
		KENMCJCIGIB_3 = 3,
		LFLMBPJJEEG_4 = 4,
		BCMLFJPLKAM = 5,
		EGFEFGJLKLA = 6,
		HOOJOFACOEK = 7,
		DAOKJMHHKGP = 8,
		NGDJIJOIPIB = 9,
		EHEDFAMGLDP_10 = 10,
		KJAFDMGNBPO_11 = 11,
		CLJHDIKFECG_12 = 12,
		OBNEIGIFMFD_13 = 13,
		DOEHLCLBCNN_14 = 14,
		GJPEANBALKF = 15,
	}

	public const int ELIOGKCBPHB = 8;
	public const int APELNKCCILJ = 10;
	public const int DLFABFMPJNJ = 9;
	public const int EBOJECFBKPL = 9;
	public const int IKNHNABNAFJ = 20;
	public const int AHGEDPCCKDE = 3;
}
