
using XeApp.Game.Common;

public class ECEPJHGMGBJ : IBJAKJJICBC
{
	public int LPALNMHPDKK { get; set; } // 0xDC CDKILGMPLCF KFHBJBLOGGO GLJHANHAFMN
	public int HKIAHOEEMLC { get; set; } // 0xE0 JCKPLOPNIIB PLOGONAKOPF HMAMEJKDGAA
	public Difficulty.Type AKNELONELJK { get; set; } // 0xE4 MDCMMICBKFN BPPILHGDABB PMMIIHKEGCI
	public int FJOLNJLLJEJ { get; set; } // 0xE8 BLIGJGPCOKP EAKAGHDPEMI GHECCGBGCBI
	public bool LFGNLKKFOCD { get; set; } // 0xEC JPINIEEOCME PAIHMADGJKE ICADLJCGFIN

	//// RVA: 0x1502C90 Offset: 0x1502C90 VA: 0x1502C90
	//public void KHEKNNFCAOI(int GHBPLHBNMBK) { }
}
