using System.Collections.Generic;
using XeApp.Game;

public class EEMGHIINEHN
{
	public enum LMPEOKPFKCA
	{
		HONJMAFKFMA = 0,
		EKKJBJDFHFN = 1,
		DEPNDHEKPNC = 2,
		KMBLOGHDEMI = 3,
		AEFCOHJBLPO_4_Num = 4,
	}

	public class OPANFJDIEGH
	{
		public GCIJNCFDNON_SceneInfo[] JOHLGBDOLNO_AssistScenes = new GCIJNCFDNON_SceneInfo[4]; // 0x8
		public string JCJNKBKMJFK_Name; // 0xC

		// RVA: 0x1C4A128 Offset: 0x1C4A128 VA: 0x1C4A128
		public OPANFJDIEGH()
		{
			for(int i = 0; i < JOHLGBDOLNO_AssistScenes.Length; i++)
			{
				JOHLGBDOLNO_AssistScenes[i] = new GCIJNCFDNON_SceneInfo();
			}
		}

		// RVA: 0x1C4B364 Offset: 0x1C4B364 VA: 0x1C4B364
		public void LDHHJFHGGMA(BBHNACPENDM_ServerSaveData _LDEGEHAEALK_ServerData)
		{
			JNMFKOHFAFB_PublicStatus.ONCMONJIPCD assist = _LDEGEHAEALK_ServerData.MHEAEGMIKIE_PublicStatus.MGMFOJPNDGA_AssistData;
			for(int i = 0; i < JOHLGBDOLNO_AssistScenes.Length; i++)
			{
				if(assist.JOHLGBDOLNO_AssistScenes[i].PPFNGGCBJKC_id > 0)
				{
					JOHLGBDOLNO_AssistScenes[i].KHEKNNFCAOI_Init(assist.JOHLGBDOLNO_AssistScenes[i].PPFNGGCBJKC_id,
						assist.JOHLGBDOLNO_AssistScenes[i].PDNIFBEGMHC_Mb,
						assist.JOHLGBDOLNO_AssistScenes[i].EMOJHJGHJLN_Sb,
						assist.JOHLGBDOLNO_AssistScenes[i].JPIPENJGGDD_NumBoard, 1,
						assist.JOHLGBDOLNO_AssistScenes[i].MJBODMOLOBC_luck, false, 0, 
						assist.JOHLGBDOLNO_AssistScenes[i].DMNIMMGGJJJ_Leaf);
				}
			}
			JCJNKBKMJFK_Name = assist.JCJNKBKMJFK_Name;
		}
	}

	private List<OPANFJDIEGH> NPDOIBMDEGK = new List<OPANFJDIEGH>(); // 0x8

	//// RVA: 0x1C49D40 Offset: 0x1C49D40 VA: 0x1C49D40
	private void AODCGBBHKDJ(BBHNACPENDM_ServerSaveData _LDEGEHAEALK_ServerData, int _IGNIIEBMFIN_Page/* = 0*/)
	{
		JNMFKOHFAFB_PublicStatus.ONCMONJIPCD saveAssistPlate = _LDEGEHAEALK_ServerData.IGNHLKEMJND_AssistPlate.LDIINNKMLLO[_IGNIIEBMFIN_Page];
		OPANFJDIEGH data = new OPANFJDIEGH();
		for(int i = 0; i < saveAssistPlate.JOHLGBDOLNO_AssistScenes.Length; i++)
		{
			if(saveAssistPlate.JOHLGBDOLNO_AssistScenes[i].PPFNGGCBJKC_id > 0)
			{
				MMPBPOIFDAF_Scene.PMKOFEIONEG saveScene = _LDEGEHAEALK_ServerData.PNLOINMCCKH_Scene.OPIBAPEGCLA_Scenes[saveAssistPlate.JOHLGBDOLNO_AssistScenes[i].PPFNGGCBJKC_id - 1];
				data.JOHLGBDOLNO_AssistScenes[i].KHEKNNFCAOI_Init(saveScene.PPFNGGCBJKC_id, saveScene.PDNIFBEGMHC_Mb, saveScene.EMOJHJGHJLN_Sb, saveScene.JPIPENJGGDD_NumBoard, 1, saveScene.MJBODMOLOBC_luck, saveScene.LHMOAJAIJCO_is_new, 0, saveScene.DMNIMMGGJJJ_Leaf);
			}
		}
		data.JCJNKBKMJFK_Name = saveAssistPlate.JCJNKBKMJFK_Name;
		NPDOIBMDEGK.Add(data);
	}

	//// RVA: 0x1C4A250 Offset: 0x1C4A250 VA: 0x1C4A250
	public void KHEKNNFCAOI_Init()
	{
		NPDOIBMDEGK.Clear();
		for(int i = 0; i < 5; i++)
		{
			AODCGBBHKDJ(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData, i);
		}
	}

	//// RVA: 0x1C4A348 Offset: 0x1C4A348 VA: 0x1C4A348
	public void CLFGOPNDGNL_SetScene(GCIJNCFDNON_SceneInfo _IFGEJDMMAHE_Info, int _IGNIIEBMFIN_Page, int IMJIADPJJMM)
	{
		if (CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData != null)
		{
			NPDOIBMDEGK[_IGNIIEBMFIN_Page].JOHLGBDOLNO_AssistScenes[IMJIADPJJMM].KHEKNNFCAOI_Init(_IFGEJDMMAHE_Info.BCCHOBPJJKE_SceneId, _IFGEJDMMAHE_Info.KBOLNIBLIND_unlock, _IFGEJDMMAHE_Info.ODKMKEHJOCK_Sb, _IFGEJDMMAHE_Info.JPIPENJGGDD_NumBoard, _IFGEJDMMAHE_Info.IELENGDJPHF_Ulk, _IFGEJDMMAHE_Info.MJBODMOLOBC_luck, false, 0, _IFGEJDMMAHE_Info.MKHFCGPJPFI_LimitOverCount);
			CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.LDIINNKMLLO[_IGNIIEBMFIN_Page].JOHLGBDOLNO_AssistScenes[IMJIADPJJMM].DOMFHDPMCCO_Init(_IFGEJDMMAHE_Info.BCCHOBPJJKE_SceneId, _IFGEJDMMAHE_Info.KBOLNIBLIND_unlock, _IFGEJDMMAHE_Info.ODKMKEHJOCK_Sb, _IFGEJDMMAHE_Info.MJBODMOLOBC_luck, _IFGEJDMMAHE_Info.JPIPENJGGDD_NumBoard, _IFGEJDMMAHE_Info.MKHFCGPJPFI_LimitOverCount);
		}
	}

	//// RVA: 0x1C4A6FC Offset: 0x1C4A6FC VA: 0x1C4A6FC
	public void IONKIJLHJDP()
	{
		GCIJNCFDNON_SceneInfo scene = new GCIJNCFDNON_SceneInfo();
		KHEKNNFCAOI_Init();
		for(int i = 0; i < NPDOIBMDEGK.Count; i++)
		{
			for(int j = 0; j < NPDOIBMDEGK[i].JOHLGBDOLNO_AssistScenes.Length; j++)
			{
				if(NPDOIBMDEGK[i].JOHLGBDOLNO_AssistScenes[j].BCCHOBPJJKE_SceneId > 0)
				{
					CLFGOPNDGNL_SetScene(GameManager.Instance.ViewPlayerData.OPIBAPEGCLA_Scenes[NPDOIBMDEGK[i].JOHLGBDOLNO_AssistScenes[j].BCCHOBPJJKE_SceneId - 1], i, j);
				}
			}
		}
		AIMMBGFMFOD(ILHBCOMKHOO());
	}

	//// RVA: 0x1C4AC78 Offset: 0x1C4AC78 VA: 0x1C4AC78
	public void NODLMHKAGFD_RemoveScene(int _IGNIIEBMFIN_Page, int IMJIADPJJMM)
	{
		if (CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData == null)
			return;
		NPDOIBMDEGK[_IGNIIEBMFIN_Page].JOHLGBDOLNO_AssistScenes[IMJIADPJJMM] = new GCIJNCFDNON_SceneInfo();
		CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.LDIINNKMLLO[_IGNIIEBMFIN_Page].JOHLGBDOLNO_AssistScenes[IMJIADPJJMM].KMBPACJNEOF_Reset();
	}

	//// RVA: 0x1C4AEB8 Offset: 0x1C4AEB8 VA: 0x1C4AEB8
	public void EGENJDLKEJP(int _IGNIIEBMFIN_Page, string JAOODKBNALI)
	{
		CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.LDIINNKMLLO[_IGNIIEBMFIN_Page].JCJNKBKMJFK_Name = JAOODKBNALI;
	}

	//// RVA: 0x1C4AAF4 Offset: 0x1C4AAF4 VA: 0x1C4AAF4
	public void AIMMBGFMFOD(int _IGNIIEBMFIN_Page)
	{
		JNMFKOHFAFB_PublicStatus.ONCMONJIPCD data = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.LDIINNKMLLO[_IGNIIEBMFIN_Page];
		CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.MHEAEGMIKIE_PublicStatus.MGMFOJPNDGA_AssistData.DOMFHDPMCCO_Init(data.JOHLGBDOLNO_AssistScenes, data.JCJNKBKMJFK_Name);
	}

	//// RVA: 0x1C4AFCC Offset: 0x1C4AFCC VA: 0x1C4AFCC
	public void CEIOGBFIDKI_SetPage(int _IGNIIEBMFIN_Page)
	{
		CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.HODDNKENKHD_Page = _IGNIIEBMFIN_Page;
	}

	//// RVA: 0x1C4B0A0 Offset: 0x1C4B0A0 VA: 0x1C4B0A0
	public OPANFJDIEGH IOKHHOCMNKA(int _IGNIIEBMFIN_Page)
	{
		return NPDOIBMDEGK[_IGNIIEBMFIN_Page];
	}

	//// RVA: 0x1C4B120 Offset: 0x1C4B120 VA: 0x1C4B120
	//public EEMGHIINEHN.OPANFJDIEGH IOKHHOCMNKA() { }

	//// RVA: 0x1C4B204 Offset: 0x1C4B204 VA: 0x1C4B204
	public GCIJNCFDNON_SceneInfo ELBLMMPEKPH_GetAssistScene(int _IGNIIEBMFIN_Page, int IMJIADPJJMM)
	{
		return NPDOIBMDEGK[_IGNIIEBMFIN_Page].JOHLGBDOLNO_AssistScenes[IMJIADPJJMM];
	}

	//// RVA: 0x1C4AA20 Offset: 0x1C4AA20 VA: 0x1C4AA20
	public int ILHBCOMKHOO()
	{
		return CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.IGNHLKEMJND_AssistPlate.HODDNKENKHD_Page;
	}
}
