
using UnityEngine;

public class EJGJAFBLHHM
{
	private static string AMIFBFDPOGL = "base"; // 0x4
	private int PPOJCDCCFNI; // 0x8
	public string IPLCMPCDNJJ = ""; // 0xC
	public long FFDEBPDJOIJ; // 0x10

	public static EJGJAFBLHHM HHCJCDFCLOB { get; set; } // 0x0 LGMPACEDIJF NKACBOEHELJ OKPMHKNCNAL

	//// RVA: 0x12EE308 Offset: 0x12EE308 VA: 0x12EE308
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
	}

	//// RVA: 0x12EE388 Offset: 0x12EE388 VA: 0x12EE388
	//public void POOALAKNIHE(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG) { }

	//// RVA: 0x12EE6D0 Offset: 0x12EE6D0 VA: 0x12EE6D0
	//public void GAHFKKPLIHH() { }

	//// RVA: 0x12EEB9C Offset: 0x12EEB9C VA: 0x12EEB9C
	//public void AFOLPGDADKI(int JHNBJJKKGAK, string IPLCMPCDNJJ, IMCBBOAFION BHFHGFKBOHH, IMCBBOAFION NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG) { }
}
