using System.Collections.Generic;

public class EJHPIMANJFP
{
	private const int NKDJBEMDJHB = 259200;
	private bool OCNNKKPBDLL; // 0xC
	public long ECFNAOCFKKN; // 0x10

	public static EJHPIMANJFP HHCJCDFCLOB { get; private set; } // 0x0 LGMPACEDIJF NKACBOEHELJ OKPMHKNCNAL
	public List<LGDNAJACFHI> MHKCPJDNJKI { get; private set; } // 0x8 CPMNDNELDME DFAHGPEFPOO IOMCCGAKKCP

	// // RVA: 0x12EFA68 Offset: 0x12EFA68 VA: 0x12EFA68
	public EJHPIMANJFP()
	{
		MHKCPJDNJKI = new List<LGDNAJACFHI>();
	}

	// // RVA: 0x12EFAF4 Offset: 0x12EFAF4 VA: 0x12EFAF4
	public void IJBGPAENLJA()
	{
		HHCJCDFCLOB = this;
	}

	// // RVA: 0x12EFB58 Offset: 0x12EFB58 VA: 0x12EFB58
	// private bool AIJFDCIDDLO(SakashoErrorId PPFNGGCBJKC) { }

	// // RVA: 0x12EFB84 Offset: 0x12EFB84 VA: 0x12EFB84
	public void LILDGEPCPPG(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP GBHILNDNNDF, DJBHIFLHJLK MOBEEPPKFLG, bool MBGCBCOPOLA, bool FBBNPFFEJBN)
	{
		UnityEngine.Debug.LogError("TODO AHGFMJOAEPM_Coroutine_GetProductList");
		BHFHGFKBOHH();
	}

	// [IteratorStateMachineAttribute] // RVA: 0x6B9050 Offset: 0x6B9050 VA: 0x6B9050
	// // RVA: 0x12EFD3C Offset: 0x12EFD3C VA: 0x12EFD3C
	// private IEnumerator AHGFMJOAEPM_Coroutine_GetProductList(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x12EFE30 Offset: 0x12EFE30 VA: 0x12EFE30
	// private bool ALBOGEHBBAH(List<KBPDNHOKEKD> BBKDLIPKADG) { }
}
