
public class EPIFHEDDJAE
{
	public enum NGEDJNHECKN
	{
		HJNNKCMLGFL_0_None = 0,
		MGJDKBFHDML = 1,
		FJFMLFPJKNB_2 = 2,
	}

	public enum JAOBCBKBKJJ
	{
		HJNNKCMLGFL_0_None = 0,
		FMHLGHDKJBC_1_Atk = 1,
		JIOPJDJBLFK_2_Hit = 2,
		FIFJJFPHOEM = 3,
	}

	public enum JFEIHHBGFPF_AbilityCondition
	{
		HJNNKCMLGFL_0_None = 0,
		KLHDILNPGBB = 1,
		JEEDNIBFAEL = 2,
		KNMIMAAFAEB = 3,
		CIFHKBNKGKJ = 4,
		FANOODOOCFP = 5,
		PPNNBADDNKB_11 = 11,
		FHBJEIEPABF_12 = 12,
	}

	public const int IOGIPEHCGLF = 4;
}
