
using System.Collections.Generic;

public class FDDIIKBJNNA
{
	public List<GAKAAIHLFKI> NPKPBDIDBBG = new List<GAKAAIHLFKI>(); // 0x8
	public List<FHFEHOBCIIP> KHCACDIKJLG = new List<FHFEHOBCIIP>(); // 0xC

	// // RVA: 0xFC8280 Offset: 0xFC8280 VA: 0xFC8280
	public void KHEKNNFCAOI(bool DENGEJFHAFA, bool IAHLNPMFJMH = false, int BBDLLIEOLCB = -1)
	{
		//IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OMGFKMANMAB_Sns;
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		JALKJCLEPJN();
		NNIIGAECOHO();
		OPBFFEMJBFH(time, DENGEJFHAFA, IAHLNPMFJMH, BBDLLIEOLCB);
	}

	// // RVA: 0xFCA83C Offset: 0xFCA83C VA: 0xFCA83C
	public void KHEKNNFCAOI(int AIPLIEMLHGC)
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		HNEJELAAION(time, AIPLIEMLHGC);
	}

	// // RVA: 0xFCAFC8 Offset: 0xFCAFC8 VA: 0xFCAFC8
	// public void JCHLONCMPAJ() { }

	// // RVA: 0xFC8418 Offset: 0xFC8418 VA: 0xFC8418
	public void JALKJCLEPJN()
	{
		BOKMNHAFJHF_Sns snsDb = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OMGFKMANMAB_Sns;
		KHCACDIKJLG.Clear();
		for(int i = 0; i < snsDb.KHCACDIKJLG.Count; i++)
		{
			if(snsDb.KHCACDIKJLG[i].PPEGAKEIEGM_Enabled == 2)
			{
				FHFEHOBCIIP data = new FHFEHOBCIIP();
				data.IDELKEKDIFD = snsDb.KHCACDIKJLG[i].IDELKEKDIFD;
				data.EAHPLCJMPHD = snsDb.KHCACDIKJLG[i].EAHPLCJMPHD;
				data.OPFGFINHFCE = snsDb.KHCACDIKJLG[i].OPFGFINHFCE;
				data.HAPAFECPFEK = snsDb.KHCACDIKJLG[i].HAPAFECPFEK;
				KHCACDIKJLG.Add(data);
			}
		}
	}

	// // RVA: 0xFC86B8 Offset: 0xFC86B8 VA: 0xFC86B8
	public void NNIIGAECOHO()
	{
		BOKMNHAFJHF_Sns snsDb = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OMGFKMANMAB_Sns;
		NPKPBDIDBBG.Clear();
		for(int i = 0; i < snsDb.NPKPBDIDBBG_Room.Count; i++)
		{
			if(snsDb.NPKPBDIDBBG_Room[i].PPEGAKEIEGM_Enabled == 2 && snsDb.NPKPBDIDBBG_Room[i].MALFHCHNEFN_Room > 0)
			{
				GAKAAIHLFKI data = new GAKAAIHLFKI();
				data.MALFHCHNEFN = snsDb.NPKPBDIDBBG_Room[i].MALFHCHNEFN_Room;
				data.JBOECJOONLP = 0;
				data.OPFGFINHFCE = snsDb.NPKPBDIDBBG_Room[i].OPFGFINHFCE_Name;
				data.IJEKNCDIIAE = 0;
				data.IHCEJBAEEDO = snsDb.NPKPBDIDBBG_Room[i].PKOKDPHHLCG;
				NPKPBDIDBBG.Add(data);
			}
		}
	}

	// // RVA: 0xFCA93C Offset: 0xFCA93C VA: 0xFCA93C
	public void HNEJELAAION(long JHNMKKNEENE, int AIPLIEMLHGC)
	{
		TodoLogger.LogError(0, "HNEJELAAION");
	}

	// // RVA: 0xFC8A6C Offset: 0xFC8A6C VA: 0xFC8A6C
	public void OPBFFEMJBFH(long JHNMKKNEENE, bool DENGEJFHAFA, bool IAHLNPMFJMH, int BBDLLIEOLCB = -1)
	{
		TodoLogger.LogError(0, "OPBFFEMJBFH");
	}

	// // RVA: 0xFCB060 Offset: 0xFCB060 VA: 0xFCB060
	// public static bool MCCBDKEAMDK(FDDIIKBJNNA ANJGLKIGLAN, bool LODIBNOGMBE = False) { }

	// // RVA: 0xFCB520 Offset: 0xFCB520 VA: 0xFCB520
	// public static void FLKIIDJEJJM(FDDIIKBJNNA ANJGLKIGLAN) { }
}
