
public class FENCAJJBLBH
{
    public enum EIAPDOGALDK
    {
        HJNNKCMLGFL = 0,
        CPMDJEDFJLA = 1,
        IAOMGLELLBC = 2,
        AIEOCNLGLEE = 3,
        PNLBHBFOECC = 4
    }
	
	public FENCAJJBLBH.EIAPDOGALDK KGICDMIJGDF; // 0x8
	public ulong JNMJBPDFHEB; // 0x10
	public int OIPCCBHIKIA; // 0x18
	public string ODLOKEHMAGF; // 0x1C

	// RVA: 0x14DC0F8 Offset: 0x14DC0F8 VA: 0x14DC0F8
	public FENCAJJBLBH(FENCAJJBLBH.EIAPDOGALDK IPMOPFOMBIO, ulong FJKGJFJLCGL, int IOPHIHFOOEP, string AAGOAECLFFK)
    {
        KGICDMIJGDF = IPMOPFOMBIO;
        JNMJBPDFHEB = FJKGJFJLCGL;
        OIPCCBHIKIA = IOPHIHFOOEP;
        ODLOKEHMAGF = AAGOAECLFFK;
    }
}

