using System.Collections.Generic;
using System.Text;
using XeApp.Game.Common;
using XeSys;

public class FFHPBEPOMAK
{
	public class CLKBDNBMJCO
	{
		private const int FBGGEFFJJHB = 1561969535;
		private int IJNIDKLFABD; // 0x8
		private int JHKNDAGGOMG; // 0xC
		private int KLDFJGOKIKC; // 0x10
		private int CNKBEJHMHCP; // 0x14
		private int LMFEACDAOBG; // 0x18
		private int KCHNHFLJIDD; // 0x1C

		// public int KAMIJDBFGDB { get; set; } 0x14E4A68 0x14E4A7C
		// public int BPEFIIEPJBM { get; set; } 0x14E4A90 0x14E4AA4
		// public int DNFEEOODOBF { get; set; } 0x14E4AB8 0x14E4ACC
		// public int EMGLOGKKGKJ { get; set; } 0x14E4AE0 0x14E4AF4
		// public int FKHKMNEHBOJ { get; set; } 0x14E4B08 0x14E4B1C
		// public int PHOFGCKGIIA { get; set; } 0x14E4B30 0x14E4B44

		// // RVA: 0x14DF200 Offset: 0x14DF200 VA: 0x14DF200
		public void KHEKNNFCAOI(int AHHJLDLAPAN)
		{
			DEKKMGAFJCG_Diva.MNNLOBDPCCH_DivaInfo a = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN - 1];
			IJNIDKLFABD = a.MMCEMJILMJI_EvSoLevel ^ FBGGEFFJJHB;
			JHKNDAGGOMG = a.HDPANGMKKCP_EvVoLevel ^ FBGGEFFJJHB;
			KLDFJGOKIKC = a.FFMLBEEBHDD_EvChLevel ^ FBGGEFFJJHB;
		}

		// // RVA: 0x14E02F0 Offset: 0x14E02F0 VA: 0x14E02F0
		public int PNOKIEEILJN()
		{
			return IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OAINIGNLJKC_Diva2.LENIIENHJJK[IJNIDKLFABD ^ FBGGEFFJJHB].MKMIEGPOKGG;
		}

		// // RVA: 0x14E045C Offset: 0x14E045C VA: 0x14E045C
		public int LCDIGPJJJGI()
		{
			return IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OAINIGNLJKC_Diva2.LENIIENHJJK[JHKNDAGGOMG ^ FBGGEFFJJHB].MELGGCAIONF;
		}

		// // RVA: 0x14E05C8 Offset: 0x14E05C8 VA: 0x14E05C8
		public int KDKCMCBLEMG()
		{
			return IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OAINIGNLJKC_Diva2.LENIIENHJJK[KLDFJGOKIKC ^ FBGGEFFJJHB].LDLHPACIIAB;
		}

		// // RVA: 0x14E4B58 Offset: 0x14E4B58 VA: 0x14E4B58
		// public int PJCKMKEJCEL() { }
	}

	private bool BNFDBPPOAOE; // 0x8
	private bool EEBBAGGJOGH; // 0x9
	public int AHHJLDLAPAN_DivaId; // 0xC
	public int CIEOBFIIPLD_Level; // 0x10
	public int AIHCEGFANAM; // 0x14
	public string OPFGFINHFCE_DivaName; // 0x18
	public bool FJODMPGPDDD; // 0x28
	public bool IPJMPBANBPP; // 0x29
	public byte[] FFKMEFKOBHO; // 0x2C
	public List<byte[]> FGBKIPNGGJM = new List<byte[]>(); // 0x30
	public byte[] PFCJIKGENEH; // 0x34
	public List<byte[]> GDJPNDKMKPG = new List<byte[]>(); // 0x38
	public int AICGALGPFMO; // 0x3C
	public List<int> HHKFOOFPOJL = new List<int>(); // 0x40
	public bool JLKPGDEKPEO_IsHave; // 0x58
	public bool CPGDEPMPMFK; // 0x59
	public bool MBFADDHOEOK_IsNew; // 0x5A
	public CKFGMNAIBNG FFKMJNHFFFL_Costume = new CKFGMNAIBNG(); // 0x5C
	public CKFGMNAIBNG EGAFMGDFFCH = new CKFGMNAIBNG(); // 0x60
	private BBHNACPENDM_ServerSaveData LDEGEHAEALK; // 0x78
	// public static DisplayType[] HBBPOMBJJNG = new DisplayType[8] { 0, 1, 2, 3, 7, 8, 9, 10 }; // 0x0

	public StatusData JLJGCBOHJID_Status { get; private set; } = new StatusData(); // 0x1C MHGEJIKLJOP CKAOBJJCOFO MKFJBBFNFPD
	public StatusData CMCKNKKCNDK_EquippedStatus { get; private set; } = new StatusData(); // 0x20 CLCJNFNMNBH CNKGOPKANGF CHJGGLFGALP
	public List<int> DJICAKGOGFO_SubSceneIds { get; private set; } // 0x24 GIOHLILFNGF HFNMIBKHCPA OOEOBODDEBH
	public int FGFIBOBAPIA_SceneId { get; private set; } // 0x44 HIFDNPNIAAH DEDCNFGKGEH JINCEPHFFBN
	public int JPIDIENBGKH_CostumeId { get; private set; } // 0x48 CPCGNLOMIJL PHLLMIGCPCB BLBNMENMCIF
	public int EKFONBFDAAP_ColorId { get; private set; } // 0x4C GDOPIDINPAJ EIIGMAIDCAG BLGOCKHBMIG
	public int KIIMFCFMMDN_HomeCostumeId { get; private set; } // 0x50 NBEBILCKAIH GBBCNBOMGIH GAAGDLPJGKN
	public int JFFLFIMIMOI_HomeColorId { get; private set; } // 0x54 BENJFMIAAIP EPDJMLMLHIG FJBIDEJJHOD
	public int KELFCMEOPPM_EpisodeId { get; private set; } // 0x64 LOEOGJLMNME AHJNJHDELBE PJLFKEOLFMK
	public List<int> PKLPGBKKFOL { get; private set; } // 0x68 IOKGPGPGGPL ODHMENNBBML JLIFOJJIDIG
	public List<int> HMBECPGHPOE { get; private set; } // 0x6C BAMGHOCFIIG HDJMNMAPPAJ GBMDLJBJILK
	public List<int> FOHEIOLPAOG { get; private set; } // 0x70 IEPHLHPLBGB BEFACAKCODI HMAHEFFHNIO
	public FFHPBEPOMAK.CLKBDNBMJCO IHANGGCHPAL { get; private set; } = new FFHPBEPOMAK.CLKBDNBMJCO(); // 0x74 DCLILLHDINA NIBJBLCDIHD MBAKEDKIJDG

	// RVA: 0x14DE1BC Offset: 0x14DE1BC VA: 0x14DE1BC
	public void LEHDLBJJBNC()
	{
		TodoLogger.Log(0, "LEHDLBJJBNC");
	}

	// RVA: 0x14DE4E0 Offset: 0x14DE4E0 VA: 0x14DE4E0
	public void KHEKNNFCAOI(int AHHJLDLAPAN_DivaId, BBHNACPENDM_ServerSaveData NIMOGBDCMLJ, bool OJEBNBLHPNP = false)
	{
		BNFDBPPOAOE = true;
		EEBBAGGJOGH = false;
		if(NIMOGBDCMLJ == null)
		{
			LDEGEHAEALK = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave;
			this.AHHJLDLAPAN_DivaId = AHHJLDLAPAN_DivaId;
		}
		else
		{
			LDEGEHAEALK = NIMOGBDCMLJ;
			this.AHHJLDLAPAN_DivaId = AHHJLDLAPAN_DivaId;
		}
		PKLPGBKKFOL = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].ANAJIAENLNB_Levels;
		HMBECPGHPOE = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].LKIFDCEKDCK_Exps;
		FOHEIOLPAOG = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].KBOLNIBLIND_Unlocks;
		FJODMPGPDDD = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].CPGFPEDMDEH != 0 || RuntimeSettings.CurrentSettings.ForceDivaUnlock;
		IPJMPBANBPP = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MGFMPKLLGHE_Diva.CDENCMNHNGA[AHHJLDLAPAN_DivaId - 1].PPEGAKEIEGM == 2;
		CIEOBFIIPLD_Level = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].OKMELNIIMMO();
		AIHCEGFANAM = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MGFMPKLLGHE_Diva.CDENCMNHNGA[AHHJLDLAPAN_DivaId - 1].AIHCEGFANAM;
		OPFGFINHFCE_DivaName = EJOJNFDHDHN_GetName(AHHJLDLAPAN_DivaId);
		DJICAKGOGFO_SubSceneIds = new List<int>();
		for(int i = 0; i < LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].JCHHIPOPNIN; i++)
		{
			int val = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].EBDNICPAFLB_SSlot[i];
			DJICAKGOGFO_SubSceneIds.Add(val);
			if(val == 0)
			{
				FGBKIPNGGJM.Add(null);
				GDJPNDKMKPG.Add(null);
				HHKFOOFPOJL.Add(0);
			}
			else
			{
				FGBKIPNGGJM.Add(LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[val].PDNIFBEGMHC_Mb);
				GDJPNDKMKPG.Add(LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[val].EMOJHJGHJLN);
				HHKFOOFPOJL.Add(LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[val].JPIPENJGGDD_Mlt);
			}
		}
		FGFIBOBAPIA_SceneId = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].PIGLAEFPNEK_MSlot;
		if(FGFIBOBAPIA_SceneId != 0)
		{
			FFKMEFKOBHO = LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[FGFIBOBAPIA_SceneId].PDNIFBEGMHC_Mb;
			PFCJIKGENEH = LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[FGFIBOBAPIA_SceneId].EMOJHJGHJLN;
			AICGALGPFMO = LDEGEHAEALK.PNLOINMCCKH_Scene.OPIBAPEGCLA[FGFIBOBAPIA_SceneId].JPIPENJGGDD_Mlt;
		}
		JPIDIENBGKH_CostumeId = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].BEEAIAAJOHD_CostumeId;
		EKFONBFDAAP_ColorId = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].AFNIOJHODAG_CostumeColorId;
		FFKMJNHFFFL_Costume.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, JPIDIENBGKH_CostumeId, LDEGEHAEALK, OJEBNBLHPNP);
		KIIMFCFMMDN_HomeCostumeId = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].HPJMPINPKEP_HomeCostumeId;
		JFFLFIMIMOI_HomeColorId = LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].KKEPMONFGEI_HomeCostumeColorId;
		EGAFMGDFFCH.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].HPJMPINPKEP_HomeCostumeId, 
			LDEGEHAEALK, OJEBNBLHPNP);
		if(true/*JPIDIENBGKH == 0*/)
		{
			KELFCMEOPPM_EpisodeId = 0;
			MBFADDHOEOK_IsNew = false;
			JLKPGDEKPEO_IsHave = false;
			CPGDEPMPMFK = false;
		}
		else
		{
			TodoLogger.Log(0, "episode info");
			//KELFCMEOPPM = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MOLEPBNJAGE_Episode
			//L.280
		}
		IHANGGCHPAL.KHEKNNFCAOI(AHHJLDLAPAN_DivaId);
		HCDGELDHFHB();

	}

	// RVA: 0x14DFA1C Offset: 0x14DFA1C VA: 0x14DFA1C
	public void KHEKNNFCAOI(int AHHJLDLAPAN_DivaId, int PAOGPLDOMMI_Level, int PDEEMMEHDPK_CostumeId, int KOHAAFNNBOE_ColorId, GCIJNCFDNON AFBMEMCHJCL_MainScene, List<GCIJNCFDNON> HDJOHAJPGBA_SubScene, bool LGNOCBFCAAK = false)
	{
		EEBBAGGJOGH = LGNOCBFCAAK;
		BNFDBPPOAOE = false;
		this.AHHJLDLAPAN_DivaId = AHHJLDLAPAN_DivaId;
		CIEOBFIIPLD_Level = PAOGPLDOMMI_Level;
		BJPLLEBHAGO d = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MGFMPKLLGHE_Diva.CDENCMNHNGA[AHHJLDLAPAN_DivaId-1];
		AIHCEGFANAM = d.AIHCEGFANAM;
		JPIDIENBGKH_CostumeId = PDEEMMEHDPK_CostumeId;
		EKFONBFDAAP_ColorId = KOHAAFNNBOE_ColorId;
		if(!LGNOCBFCAAK)
		{
			FFKMJNHFFFL_Costume.KHEKNNFCAOI(AHHJLDLAPAN_DivaId,PDEEMMEHDPK_CostumeId,0,false);
		}
		else
		{
			FFKMJNHFFFL_Costume.KHEKNNFCAOI(AHHJLDLAPAN_DivaId,PDEEMMEHDPK_CostumeId,CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave,false);
		}
		FJODMPGPDDD = false;
		IPJMPBANBPP = d.PPEGAKEIEGM == 2;
		OPFGFINHFCE_DivaName = EJOJNFDHDHN_GetName(AHHJLDLAPAN_DivaId);
		if(HDJOHAJPGBA_SubScene != null)
		{
			DJICAKGOGFO_SubSceneIds = new List<int>();
			for(int i = 0; i < HDJOHAJPGBA_SubScene.Count; i++)
			{
				if(HDJOHAJPGBA_SubScene[i] == null)
				{
					DJICAKGOGFO_SubSceneIds.Add(0);
					FGBKIPNGGJM.Add(null);
					GDJPNDKMKPG.Add(null);
					HHKFOOFPOJL.Add(0);
				}
				else
				{
					if(HDJOHAJPGBA_SubScene[i].BCCHOBPJJKE_SceneId == 0)
					{
						DJICAKGOGFO_SubSceneIds.Add(0);
						FGBKIPNGGJM.Add(null);
						GDJPNDKMKPG.Add(null);
						HHKFOOFPOJL.Add(0);
					}
					else
					{
						DJICAKGOGFO_SubSceneIds.Add(HDJOHAJPGBA_SubScene[i].BCCHOBPJJKE_SceneId);
						FGBKIPNGGJM.Add(HDJOHAJPGBA_SubScene[i].KBOLNIBLIND);
						GDJPNDKMKPG.Add(HDJOHAJPGBA_SubScene[i].ODKMKEHJOCK);
						HHKFOOFPOJL.Add(HDJOHAJPGBA_SubScene[i].JPIPENJGGDD);
					}
				}
			}
		}
		if(AFBMEMCHJCL_MainScene == null || AFBMEMCHJCL_MainScene.BCCHOBPJJKE_SceneId == 0)
		{
			AICGALGPFMO = 0;
			FFKMEFKOBHO = null;
			FGFIBOBAPIA_SceneId = 0;
			PFCJIKGENEH = null;
		}
		else
		{
			AICGALGPFMO = AFBMEMCHJCL_MainScene.JPIPENJGGDD;
			FGFIBOBAPIA_SceneId = AFBMEMCHJCL_MainScene.BCCHOBPJJKE_SceneId;
			FFKMEFKOBHO = AFBMEMCHJCL_MainScene.KBOLNIBLIND;
			PFCJIKGENEH = AFBMEMCHJCL_MainScene.ODKMKEHJOCK;
		}
		IHANGGCHPAL.KHEKNNFCAOI(AHHJLDLAPAN_DivaId);
		HCDGELDHFHB();
	}

	// // RVA: 0x14DF0BC Offset: 0x14DF0BC VA: 0x14DF0BC
	public static string EJOJNFDHDHN_GetName(int MCDINKAKFGG)
	{
		StringBuilder str = new StringBuilder(32);
		MessageBank bank = MessageManager.Instance.GetBank("master");
		str.SetFormat("diva_{0:D2}", MCDINKAKFGG);
		return bank.GetMessageByLabel(str.ToString());
	}

	// // RVA: 0x14E01A4 Offset: 0x14E01A4 VA: 0x14E01A4
	// public StatusData FDFPMGHGBNN() { }

	// // RVA: 0x14DF39C Offset: 0x14DF39C VA: 0x14DF39C
	public void HCDGELDHFHB()
	{
		BJPLLEBHAGO a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MGFMPKLLGHE_Diva.CDENCMNHNGA[AHHJLDLAPAN_DivaId - 1];
		JLJGCBOHJID_Status.soul = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].PFJCOCPKABN_Soul;
		JLJGCBOHJID_Status.vocal = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].JFJDLEMNKFE_Vocal;
		JLJGCBOHJID_Status.charm = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].GDOLPGBLMEA_Charm;
		JLJGCBOHJID_Status.life = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].HFIDCMNFBJG_Life;
		JLJGCBOHJID_Status.fold = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].ONDFNOOICLE_Fold;
		JLJGCBOHJID_Status.support = a.CMCKNKKCNDK[CIEOBFIIPLD_Level].HCFOMFDPGEC_Support;
		JLJGCBOHJID_Status.soul += IHANGGCHPAL.PNOKIEEILJN();
		JLJGCBOHJID_Status.vocal += IHANGGCHPAL.LCDIGPJJJGI();
		JLJGCBOHJID_Status.charm += IHANGGCHPAL.KDKCMCBLEMG();
		if(EEBBAGGJOGH || BNFDBPPOAOE)
		{
			JLJGCBOHJID_Status.Add(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.BEKHNNCGIEL_Costume.NNIKNCGNDHK(AHHJLDLAPAN_DivaId));
		}
		CMCKNKKCNDK_EquippedStatus.Copy(JLJGCBOHJID_Status);
		if(FGFIBOBAPIA_SceneId != 0)
		{
			CMCKNKKCNDK_EquippedStatus.Add(GCIJNCFDNON.JPCAIAAOOLN(FGFIBOBAPIA_SceneId, FFKMEFKOBHO, PFCJIKGENEH, AICGALGPFMO, 0));
		}
		if(DJICAKGOGFO_SubSceneIds != null)
		{
			for(int i = 0; i < DJICAKGOGFO_SubSceneIds.Count; i++)
			{
				if(DJICAKGOGFO_SubSceneIds[i] != 0)
				{
					CMCKNKKCNDK_EquippedStatus.Add(GCIJNCFDNON.JPCAIAAOOLN(DJICAKGOGFO_SubSceneIds[i], FGBKIPNGGJM[i], GDJPNDKMKPG[i], HHKFOOFPOJL[i], 0));
				}
			}
		}
	}

	// // RVA: 0x14E0734 Offset: 0x14E0734 VA: 0x14E0734
	public void ELHBGKLLOIO()
	{
		JLJGCBOHJID_Status.Clear();
		CMCKNKKCNDK_EquippedStatus.Copy(JLJGCBOHJID_Status);
		if(FGFIBOBAPIA_SceneId != 0)
		{
			CMCKNKKCNDK_EquippedStatus.Add(GCIJNCFDNON.JPCAIAAOOLN(FGFIBOBAPIA_SceneId, FFKMEFKOBHO, PFCJIKGENEH, AICGALGPFMO, 0));
		}
		if(DJICAKGOGFO_SubSceneIds != null)
		{
			for(int i = 0; i < DJICAKGOGFO_SubSceneIds.Count; i++)
			{
				if(DJICAKGOGFO_SubSceneIds[i] != 0)
				{
					CMCKNKKCNDK_EquippedStatus.Add(GCIJNCFDNON.JPCAIAAOOLN(DJICAKGOGFO_SubSceneIds[i], FGBKIPNGGJM[i], GDJPNDKMKPG[i], HHKFOOFPOJL[i], 0));
				}
			}
		}
	}

	// // RVA: 0x14E09E8 Offset: 0x14E09E8 VA: 0x14E09E8
	// public bool OKDIEDCGODF(int BCCHOBPJJKE, bool ILBBPPMLLFM, KDMCFCBMAOI BBEBHGEHMMI, BLHOMPPGBMI NGMPDMCBNJB) { }

	// // RVA: 0x14E0D08 Offset: 0x14E0D08 VA: 0x14E0D08
	// public bool MNBNLONEDPF(bool ILBBPPMLLFM) { }

	// // RVA: 0x14E0E34 Offset: 0x14E0E34 VA: 0x14E0E34
	// public bool IFFMDJHENHB(int IMJIADPJJMM, int BCCHOBPJJKE, bool ILBBPPMLLFM, KDMCFCBMAOI BBEBHGEHMMI, BLHOMPPGBMI NGMPDMCBNJB) { }

	// // RVA: 0x14E13AC Offset: 0x14E13AC VA: 0x14E13AC
	// public bool BCEJOOCGBFG(int IMJIADPJJMM, bool ILBBPPMLLFM) { }

	// // RVA: 0x14E168C Offset: 0x14E168C VA: 0x14E168C
	// public void GFHOGBPOJDN(int PIHCLIPPNPB, int GFBJMMNGHAA, int FKCLAAAECLO, KDMCFCBMAOI BBEBHGEHMMI) { }

	// // RVA: 0x14E1758 Offset: 0x14E1758 VA: 0x14E1758
	public void HOOJOFACOEK_SetCostume(int PDEEMMEHDPK, int HEHKNMCDBJJ, bool MNGIDJDFBFD = false, bool OJEBNBLHPNP = false)
	{
		JPIDIENBGKH_CostumeId = PDEEMMEHDPK;
		EKFONBFDAAP_ColorId = HEHKNMCDBJJ;
		if(!BNFDBPPOAOE)
		{
			FFKMJNHFFFL_Costume.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, PDEEMMEHDPK, 0, OJEBNBLHPNP);
		}
		else
		{
			FFKMJNHFFFL_Costume.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, PDEEMMEHDPK, LDEGEHAEALK, OJEBNBLHPNP);
		}
		if(BNFDBPPOAOE && MNGIDJDFBFD)
		{
			if(JPIDIENBGKH_CostumeId == 0)
			{
				JLKPGDEKPEO_IsHave = true;
				KELFCMEOPPM_EpisodeId = 0;
				MBFADDHOEOK_IsNew = false;
			}
			else
			{
				if(FFKMJNHFFFL_Costume.DAJGPBLEEOB_PrismCostumeId == 1)
				{
					KELFCMEOPPM_EpisodeId = 0;
					MBFADDHOEOK_IsNew = false;
					JLKPGDEKPEO_IsHave = false; // ?? not sure
					CPGDEPMPMFK = true;
				}
				else
				{
					KELFCMEOPPM_EpisodeId = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MOLEPBNJAGE_Episode.NNFJBBFBIEN(JPIDIENBGKH_CostumeId);
					JLKPGDEKPEO_IsHave = LDEGEHAEALK.BEKHNNCGIEL_Costume.FABAGMLEKIB[JPIDIENBGKH_CostumeId - 1].CGKAEMGLHNK_Possessed();
					MBFADDHOEOK_IsNew = LDEGEHAEALK.BEKHNNCGIEL_Costume.FABAGMLEKIB[JPIDIENBGKH_CostumeId - 1].CADENLBDAEB_IsNew;
					CPGDEPMPMFK = false;
					if(KELFCMEOPPM_EpisodeId != 0)
					{
						if(LDEGEHAEALK.NGHJPEIKLJL_Episode.BBAJKJPKOHD_EpisodeList[KELFCMEOPPM_EpisodeId - 1].BEBJKJKBOGH_Date != 0)
						{
							CPGDEPMPMFK = true;
						}
					}
				}
			}
		}
		if (!BNFDBPPOAOE || MNGIDJDFBFD)
			return;
		LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].BEEAIAAJOHD_CostumeId = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.LBDOLHGDIEB(AHHJLDLAPAN_DivaId, PDEEMMEHDPK).JPIDIENBGKH_CostumeId;
		LDEGEHAEALK.DGCJCAHIAPP_Diva.NBIGLBMHEDC_DivaList[AHHJLDLAPAN_DivaId - 1].AFNIOJHODAG_CostumeColorId = HEHKNMCDBJJ;
	}

	// // RVA: 0x14E1C7C Offset: 0x14E1C7C VA: 0x14E1C7C
	public void JEIGPGNJJCP_SetCostumeColor(int HEHKNMCDBJJ)
	{
		EKFONBFDAAP_ColorId = HEHKNMCDBJJ;
	}

	// // RVA: 0x14E1C84 Offset: 0x14E1C84 VA: 0x14E1C84
	public void JFIPEKCDKLG(int PDEEMMEHDPK, int HEHKNMCDBJJ, bool OJEBNBLHPNP = false)
	{
		KIIMFCFMMDN_HomeCostumeId = PDEEMMEHDPK;
		JFFLFIMIMOI_HomeColorId = HEHKNMCDBJJ;
		if(!BNFDBPPOAOE)
		{
			EGAFMGDFFCH.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, PDEEMMEHDPK, 0, OJEBNBLHPNP);
		}
		else
		{
			EGAFMGDFFCH.KHEKNNFCAOI(AHHJLDLAPAN_DivaId, PDEEMMEHDPK, LDEGEHAEALK, OJEBNBLHPNP);
		}
	}

	// // RVA: 0x14E1D28 Offset: 0x14E1D28 VA: 0x14E1D28
	public void OPDBFHFKKJN(int PDEEMMEHDPK, int HEHKNMCDBJJ, bool OJEBNBLHPNP = false)
	{
		TodoLogger.Log(0, "OPDBFHFKKJN");
	}

	// // RVA: 0x14E1F38 Offset: 0x14E1F38 VA: 0x14E1F38
	// public void HFMDICFNFNO(int HEHKNMCDBJJ) { }

	// // RVA: 0x14E1F40 Offset: 0x14E1F40 VA: 0x14E1F40
	// public int EOJIGHEFIAA() { }

	// // RVA: 0x14E2058 Offset: 0x14E2058 VA: 0x14E2058
	// public int LHGJHJLGPBE() { }

	// // RVA: 0x14E2154 Offset: 0x14E2154 VA: 0x14E2154
	// public void ODFBCANBLIJ(GCIJNCFDNON PNLOINMCCKH) { }

	// // RVA: 0x14E2194 Offset: 0x14E2194 VA: 0x14E2194
	// public void GOEDGNGDMCN(GCIJNCFDNON PNLOINMCCKH, int IMJIADPJJMM) { }

	// // RVA: 0x14E239C Offset: 0x14E239C VA: 0x14E239C
	// public void CJBBDBGDFKJ(GCIJNCFDNON PNLOINMCCKH, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x14E23DC Offset: 0x14E23DC VA: 0x14E23DC
	// public void GIGDKIHBDHB(GCIJNCFDNON PNLOINMCCKH, int IMJIADPJJMM, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x14E2564 Offset: 0x14E2564 VA: 0x14E2564
	// public static int PFAGNJEPBCB(int AHHJLDLAPAN, int JPIDIENBGKH) { }

	// // RVA: 0x14E2810 Offset: 0x14E2810 VA: 0x14E2810
	public static List<FFHPBEPOMAK> DNAIGDHCILM_GetCostumeList(int AHHJLDLAPAN, bool OJEBNBLHPNP = false)
	{
		List<FFHPBEPOMAK> res = new List<FFHPBEPOMAK>();
		for (int i = 0; i < IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.CDENCMNHNGA.Count; i++)
		{
			LCLCCHLDNHJ_Costume.ILODJKFJJDO cosInfo = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.CDENCMNHNGA[i];
			int costumeId = cosInfo.JPIDIENBGKH_CostumeId;
			if (cosInfo.AHHJLDLAPAN_PrismDivaId == AHHJLDLAPAN)
			{
				if(cosInfo.PPEGAKEIEGM == 2)
				{
					if(cosInfo.DAJGPBLEEOB_PrismCostumeModelId == 1 || OJEBNBLHPNP)
					{
						//LAB_014e2d4c
						FFHPBEPOMAK data = new FFHPBEPOMAK();
						data.KHEKNNFCAOI(AHHJLDLAPAN, CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave, false);
						data.HOOJOFACOEK_SetCostume(cosInfo.JPIDIENBGKH_CostumeId, 0, true, OJEBNBLHPNP);
						data.JFIPEKCDKLG(cosInfo.JPIDIENBGKH_CostumeId, 0, OJEBNBLHPNP);
						res.Add(data);
					}
					else
					{
						var a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MOLEPBNJAGE_Episode.NNFJBBFBIEN(costumeId);
						if (a == 0)
						{
							if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.BEKHNNCGIEL_Costume.FABAGMLEKIB[costumeId - 1].CGKAEMGLHNK_Possessed())
							{
								FFHPBEPOMAK data = new FFHPBEPOMAK();
								data.KHEKNNFCAOI(AHHJLDLAPAN, CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave, false);
								data.HOOJOFACOEK_SetCostume(cosInfo.JPIDIENBGKH_CostumeId, 0, true, OJEBNBLHPNP);
								data.JFIPEKCDKLG(cosInfo.JPIDIENBGKH_CostumeId, 0, OJEBNBLHPNP);
								res.Add(data);
							}
						}
						else
						{
							if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.NGHJPEIKLJL_Episode.BBAJKJPKOHD_EpisodeList[a - 1].BEBJKJKBOGH_Date != 0 || RuntimeSettings.CurrentSettings.ForceCardsUnlock)
							{
								FFHPBEPOMAK data = new FFHPBEPOMAK();
								data.KHEKNNFCAOI(AHHJLDLAPAN, CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave, false);
								data.HOOJOFACOEK_SetCostume(cosInfo.JPIDIENBGKH_CostumeId, 0, true, OJEBNBLHPNP);
								data.JFIPEKCDKLG(cosInfo.JPIDIENBGKH_CostumeId, 0, OJEBNBLHPNP);
								res.Add(data);
							}
						}
					}
				}
			}
		}
		return res;
	}

	// // RVA: 0x14E2F68 Offset: 0x14E2F68 VA: 0x14E2F68
	public static List<FFHPBEPOMAK> OOJFGDKBOHK(int AHHJLDLAPAN, bool OJEBNBLHPNP = false)
	{
		TodoLogger.Log(0, "OOJFGDKBOHK");
		return new List<FFHPBEPOMAK>();
	}
}
