
public class FKAFHLIDAFD
{
	internal FENCAJJBLBH DCLNIAMEGLA; // 0x18

	public BBHNACPENDM_ServerSaveData AHEFHIMGIBI { get; internal set; } // 0x8 LCHHPGMCKJD GNMGJMDJEGI LGLGNHAMNIK
	internal BBHNACPENDM_ServerSaveData CCNKAKCBBDJ { get; set; } // 0xC MOMIOKHCMKH GHMKOMEKBFO KKOICOJPENH
	public BBHNACPENDM_ServerSaveData FMFKHDPKLOC { get; internal set; } // 0x10 FDDDKGAMLLB AAMOPGKKGEI OBEALILDFEM
	public bool KONHMOLMOCI { get; internal set; }  // 0x14 DEDJLABCBOH MDEMPMONBLE NAALAEJIEAI
	public bool LNAHEIEIBOI { get; internal set; }  // 0x15 INBPPDMFOAD FHEAKKHAAPF GOEIEJFPLOG
	public bool BLCDJDJJBHC { get; internal set; }  // 0x16 BPLABMJENOI AAIACPOJKKO DNLNBFEHCKD
	// public bool BBIOBFPCLOO { get; } 0x1187B54 BBBBKCIJNMG

	// RVA: 0x1187B64 Offset: 0x1187B64 VA: 0x1187B64
	// public void BELHFJNAEKB() { }
}
