
using XeApp.Game.Common;

public class GHLGEECLCMH
{
	private HighScoreRating JPJHBJAHPFP; // 0x8
	private HighScoreRating HOHNHJEFCBF; // 0xC
	//private NGJOPPIGCPM.DFJMELLLNLH HBLFKGAKHHN; // 0x30
	private int MIIAIBIGKOD; // 0x34

	public HighScoreRatingRank.Type LLNHMMBFPMA { get; private set; } // 0x10 EFILGAFDFOD FBMPLMNOLFC KBAOHMCAJIO
	public HighScoreRatingRank.Type KIPEPDKGCCG { get; private set; } // 0x14 BIPJDKCFNDG DJGIJDDLPHF DCFMFAIALPI
	public int[] HFEFAGMKPKH { get; private set; } // 0x18 EHFBONAPFCH PMNEAFIPGHP DJJFKLLPCKN
	public int[] OJFCIAJEJCI { get; private set; } // 0x1C BAFGCPMCDKK JLOGGGCCJCF LPFALOBBHNB
	public int ADKDHKMPMHP { get; private set; } // 0x20 HIELAPGGNEJ KCLKBHDMAFH GOLECEILPOI
	public int KNLMOBHBPII { get; private set; } // 0x24 JCAMCJFIIJC PPLCLFCEPOE EBKLGFBLBIM
	public int ECMFBEHEGEH { get; private set; } // 0x28 KJPIHNEFHEI AGKBCAKNDHM MLODJGBOBHB
	public int DEMOACDDPHM { get; private set; } // 0x2C KANPJCGBDMA LKNGGMNKPHD CEJAPKKCLEA

	//// RVA: 0xAA5D24 Offset: 0xAA5D24 VA: 0xAA5D24
	//public void KHEKNNFCAOI(IBIGBMDANNM NIMOGBDCMLJ) { }

	//// RVA: 0xAA5FC4 Offset: 0xAA5FC4 VA: 0xAA5FC4
	//public void KHEKNNFCAOI(int KBPEBJHBIPP, JDDGGJCGOPA AIMLPJOGPID, JDDGGJCGOPA JMODMCLMIJL) { }

	//// RVA: 0xAA6014 Offset: 0xAA6014 VA: 0xAA6014
	public void KHEKNNFCAOI(JDDGGJCGOPA AIMLPJOGPID, JDDGGJCGOPA JMODMCLMIJL)
	{
		TodoLogger.Log(0, "GHLGEECLCMH KHEKNNFCAOI");
	}

	//// RVA: 0xAA63B8 Offset: 0xAA63B8 VA: 0xAA63B8
	//public NGJOPPIGCPM.DFJMELLLNLH AGKAOEEFAAH() { }

	//// RVA: 0xAA63C0 Offset: 0xAA63C0 VA: 0xAA63C0
	//public int LGPGIGPHJJB() { }

	//// RVA: 0xAA63C8 Offset: 0xAA63C8 VA: 0xAA63C8
	//public List<HighScoreRating.UtaGradeData> IEPGAGBLHBN() { }

	//// RVA: 0xAA63F4 Offset: 0xAA63F4 VA: 0xAA63F4
	//public HighScoreRating.UtaGradeData CMANMLGFJMM() { }

	//// RVA: 0xAA6420 Offset: 0xAA6420 VA: 0xAA6420
	//public List<ECEPJHGMGBJ> BGMPAMNAKHN(int FJFCNGNGIBN = 0) { }

	//// RVA: 0xAA6C20 Offset: 0xAA6C20 VA: 0xAA6C20
	//public void GLAHMLIFAPB(int KIMIHIBGONK, int FJFCNGNGIBN = 0) { }
}
