using System.Collections.Generic;
using UnityEngine;

public class GNGMCIAIKMA
{
	public const sbyte HKKJGAJPNIL = 29;
	public const sbyte FKHFJOKHNAK = 63;
	private const short EAPCKKPCPII = 90;
	public static int FBGGEFFJJHB; // 0x0
	public static long BBEGLBMOBOF; // 0x8
	private int ILGOKEAIBBA; // 0x8
	private int NPNDCNDCDPC; // 0xC
	private int PFJENHEKCAO; // 0x10
	private int ELNEJEEKOEI; // 0x14
	private int IDKOMEFBCBD; // 0x18
	public int DKFOMHOJBGD; // 0x1C
	public List<long> GEAHCCJPOCN = new List<long>(); // 0x20
	private readonly sbyte[,] LMEHCADEKLN = new sbyte[3, 8] {
		{ 0x5b, 0x58, 0x59, 0x5e, 0x5f, 0x5c, 0x5d, 0x52},
		{ 0x53, 0x5b, 0x5e, 0x5d, 0x58, 0x5f, 0x52, 0x59}, 
		{ 0x5c, 0x53, 0x5b, 0x5f, 0x53, 0x59, 0x5f, 0x5d}
	}; // 0x24
	// public List<GNGMCIAIKMA.DFABPMMMIIB> CEHNIJPOEAF = new List<GNGMCIAIKMA.DFABPMMMIIB>(); // 0x28

	public static GNGMCIAIKMA HHCJCDFCLOB { get; private set; } // 0x10 GNGMCIAIKMA OKPMHKNCNAL
	// public int PMPKHBAJAFA { get; set; } // OAKEIKFELFC 0xAB8FE4  MBHILIEPJOO 0xAB9050
	// public int MALACFEDHDE { get; set; } //  KIMKKEOMPDL 0xAB90C0 PGILHFKNKEN 0xAB912C
	// private int HHKAGEAMHOE { get; set; } // DGNHFHGNDOF 0xAB919C  HDADMLNHJMN 0xAB9208
	// private int EEOPPDBICBN { get; set; } // GDODEJOPENB 0xAB9278 JIJIGMCJHBC 0xAB92E4
	// private int CEGHDFHLFPO { get; set; } // CDJABHMPLKM 0xAB9354  EIHJCGDLLPF 0xAB93C0

	// // RVA: 0xAB9430 Offset: 0xAB9430 VA: 0xAB9430
	// public int DDHNADFGKDF(int GJKPJMGPCEJ, int IKPIDCFOFEA) { }

	// // RVA: 0xAB9524 Offset: 0xAB9524 VA: 0xAB9524
	// public int[] EOPMDFOCAKJ(int GJKPJMGPCEJ) { }

	// // RVA: 0xAB9640 Offset: 0xAB9640 VA: 0xAB9640
	public GNGMCIAIKMA() 
	{ 
		FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
		BBEGLBMOBOF = ~FBGGEFFJJHB; // not sure
		ILGOKEAIBBA = FBGGEFFJJHB;
		NPNDCNDCDPC = FBGGEFFJJHB;
		PFJENHEKCAO = FBGGEFFJJHB;
		ELNEJEEKOEI = FBGGEFFJJHB;
		IDKOMEFBCBD = FBGGEFFJJHB;
	}

	// // RVA: 0xAB9974 Offset: 0xAB9974 VA: 0xAB9974
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
	}

	// // RVA: 0xAB99D8 Offset: 0xAB99D8 VA: 0xAB99D8
	// public bool GBCPDBJEDHL() { }

	// // RVA: 0xAB9AD0 Offset: 0xAB9AD0 VA: 0xAB9AD0
	// public bool GBCPDBJEDHL(long JHNMKKNEENE) { }

	// // RVA: 0xABA38C Offset: 0xABA38C VA: 0xABA38C
	// public bool NJBPNCDPGNO(int APFDNBGMMMM) { }

	// // RVA: 0xABA480 Offset: 0xABA480 VA: 0xABA480
	// public int AMIBPGONGFE(long JHNMKKNEENE, bool HLCDBGGEHPD) { }

	// // RVA: 0xABA5FC Offset: 0xABA5FC VA: 0xABA5FC
	// public void KGABKGKGNCA(int APFDNBGMMMM, bool BCGLDMKODLC) { }

	// // RVA: 0xABA788 Offset: 0xABA788 VA: 0xABA788
	// public int MIGJIALJLOF() { }

	// // RVA: 0xABA8C0 Offset: 0xABA8C0 VA: 0xABA8C0
	// public int FIAHJAMFNPD() { }

	// // RVA: 0xABA9F8 Offset: 0xABA9F8 VA: 0xABA9F8
	// public int GEAMLAKKMLI() { }

	// // RVA: 0xABAB30 Offset: 0xABAB30 VA: 0xABAB30
	// public bool DKMLDEDKPBA(int PLALNIIBLOF) { }

	// // RVA: 0xAB9E7C Offset: 0xAB9E7C VA: 0xAB9E7C
	// public List<int> CNADOFDDNLO(long JHNMKKNEENE) { }

	// // RVA: 0xABAB40 Offset: 0xABAB40 VA: 0xABAB40
	// public List<int> CNADOFDDNLO() { }

	// // RVA: 0xABAC38 Offset: 0xABAC38 VA: 0xABAC38
	// public bool MHNAINBNLHH(int APFDNBGMMMM) { }

	// // RVA: 0xABAD3C Offset: 0xABAD3C VA: 0xABAD3C
	// public bool DHPLHALIDHH(int APFDNBGMMMM) { }

	// // RVA: 0xABAE3C Offset: 0xABAE3C VA: 0xABAE3C
	// public bool DHPLHALIDHH(int APFDNBGMMMM, long JHNMKKNEENE) { }

	// // RVA: 0xABAFF4 Offset: 0xABAFF4 VA: 0xABAFF4
	// public bool KJNFBLAMJOH(int APFDNBGMMMM) { }

	// // RVA: 0xABAFC4 Offset: 0xABAFC4 VA: 0xABAFC4
	// public long GKDBBGIEPLC(int APFDNBGMMMM) { }

	// // RVA: 0xABAFFC Offset: 0xABAFFC VA: 0xABAFFC
	// public long DBEDJLOAILN(int APFDNBGMMMM) { }

	// // RVA: 0xABB2F4 Offset: 0xABB2F4 VA: 0xABB2F4
	// public int CBMJAPJKBNL(int PPFNGGCBJKC) { }

	// // RVA: 0xABB300 Offset: 0xABB300 VA: 0xABB300
	// public int LILBEIBCCKF(int EKANGPODCEP) { }

	// // RVA: 0xABB30C Offset: 0xABB30C VA: 0xABB30C
	// public bool DJGFICMNGGP(int APFDNBGMMMM) { }

	// // RVA: 0xABB380 Offset: 0xABB380 VA: 0xABB380
	// public int MGAHOPFMKHB() { }

	// // RVA: 0xABB3EC Offset: 0xABB3EC VA: 0xABB3EC
	// public bool NJELIKPFBEH(int AMCCOGJACPK) { }

	// // RVA: 0xABB460 Offset: 0xABB460 VA: 0xABB460
	// public int EAIJHJPKBFA(int APFDNBGMMMM) { }

	// // RVA: 0xABB4D4 Offset: 0xABB4D4 VA: 0xABB4D4
	// public int EHFLAKIFPOO(int APFDNBGMMMM) { }

	// // RVA: 0xABB674 Offset: 0xABB674 VA: 0xABB674
	// public bool IDKFAMEFCPD(int APFDNBGMMMM) { }

	// // RVA: 0xAB9C00 Offset: 0xAB9C00 VA: 0xAB9C00
	// public JKICPBIIHNE FJLIDJJAGOM() { }

	// // RVA: 0xABAEB8 Offset: 0xABAEB8 VA: 0xABAEB8
	// public JKICPBIIHNE.HNOGDJFJGPM EBEDAPJFHCE(int APFDNBGMMMM) { }

	// // RVA: 0xABB868 Offset: 0xABB868 VA: 0xABB868
	// public NFMHCLHEMHB PDMHKENDJHI() { }

	// // RVA: 0xABA634 Offset: 0xABA634 VA: 0xABA634
	// public NFMHCLHEMHB.CCGKCGJKADC MENDFPNPAAO(int PPFNGGCBJKC) { }

	// // RVA: 0xABB91C Offset: 0xABB91C VA: 0xABB91C
	// public NFMHCLHEMHB.CCGKCGJKADC MENDFPNPAAO(BBHNACPENDM AHEFHIMGIBI, int PPFNGGCBJKC) { }

	// // RVA: 0xABBA8C Offset: 0xABBA8C VA: 0xABBA8C
	// public bool BHFGBNNEMLI(int APFDNBGMMMM) { }

	// // RVA: 0xABBB00 Offset: 0xABBB00 VA: 0xABBB00
	// public int CGOIJPBINCF(int APFDNBGMMMM, bool BAFFAONJPCE) { }

	// // RVA: 0xABBC58 Offset: 0xABBC58 VA: 0xABBC58
	// public int JBEDFJHAAFP(int APFDNBGMMMM, bool BAFFAONJPCE) { }

	// // RVA: 0xABBDB0 Offset: 0xABBDB0 VA: 0xABBDB0
	// public int NIGPFNIIDII(int APFDNBGMMMM) { }

	// // RVA: 0xABBE78 Offset: 0xABBE78 VA: 0xABBE78
	// public JKICPBIIHNE.MKOCCBABHAH LAIDKMDLOPA(int APFDNBGMMMM, int EIHOBHDKCDB) { }

	// // RVA: 0xABBFE8 Offset: 0xABBFE8 VA: 0xABBFE8
	// public int DAIDHMMOGEI(int APFDNBGMMMM, int EIHOBHDKCDB) { }

	// // RVA: 0xABC00C Offset: 0xABC00C VA: 0xABC00C
	// public int KBIIEPNCLAD(int APFDNBGMMMM, int EIHOBHDKCDB) { }

	// // RVA: 0xABC030 Offset: 0xABC030 VA: 0xABC030
	// public List<JKICPBIIHNE.IEGCPLCLOHF> LABNDEFMAHI(int APFDNBGMMMM, int AMCCOGJACPK) { }

	// // RVA: 0xABC254 Offset: 0xABC254 VA: 0xABC254
	// public bool OIEBCNPOMIB(int APFDNBGMMMM, int AMCCOGJACPK, int EIHOBHDKCDB) { }

	// // RVA: 0xABC3B8 Offset: 0xABC3B8 VA: 0xABC3B8
	// public bool JJMANIALKBF(int APFDNBGMMMM, int EIHOBHDKCDB) { }

	// // RVA: 0xABC480 Offset: 0xABC480 VA: 0xABC480
	// public bool JIKFDBMMAIE(int APFDNBGMMMM) { }

	// // RVA: 0xABC520 Offset: 0xABC520 VA: 0xABC520
	// public List<int> ICNOKENCCJK(int APFDNBGMMMM, bool CADENLBDAEB, bool GNKMHCKFADN) { }

	// // RVA: 0xABC6F0 Offset: 0xABC6F0 VA: 0xABC6F0
	// public List<int> OAHPJJCHIPF(int APFDNBGMMMM) { }

	// // RVA: 0xABC83C Offset: 0xABC83C VA: 0xABC83C
	// public List<int> NCCCEBGHCOL(int APFDNBGMMMM) { }

	// // RVA: 0xABC978 Offset: 0xABC978 VA: 0xABC978
	// public List<int> BPGMPJHPKND(int APFDNBGMMMM) { }

	// // RVA: 0xABCB0C Offset: 0xABCB0C VA: 0xABCB0C
	// public List<int> PFDGKPCCGMG(int APFDNBGMMMM, bool CADENLBDAEB, bool JFPPDKHEEHN) { }

	// // RVA: 0xABCDE0 Offset: 0xABCDE0 VA: 0xABCDE0
	// public void DKKLLHMHBEA(int APFDNBGMMMM, List<int> GJKPJMGPCEJ, long JHNMKKNEENE) { }

	// // RVA: 0xABCEF8 Offset: 0xABCEF8 VA: 0xABCEF8
	// public List<int> OJPMBMOAFHM(int APFDNBGMMMM) { }

	// // RVA: 0xABD0A0 Offset: 0xABD0A0 VA: 0xABD0A0
	// public List<JKICPBIIHNE.IEGCPLCLOHF> AOIADBHHJAJ(int APFDNBGMMMM, int AMCCOGJACPK, int CPKMLLNADLJ, int AHHJLDLAPAN) { }

	// // RVA: 0xABDC04 Offset: 0xABDC04 VA: 0xABDC04
	// public List<int> PDLKHLJFLHJ(int APFDNBGMMMM) { }

	// // RVA: 0xABDD84 Offset: 0xABDD84 VA: 0xABDD84
	// public List<int> OHDKDNGIFJC(int APFDNBGMMMM, int AMCCOGJACPK, int CPKMLLNADLJ, int AHHJLDLAPAN) { }

	// // RVA: 0xABDF74 Offset: 0xABDF74 VA: 0xABDF74
	// public int MLCGJAJCFDP(int APFDNBGMMMM, int PGGAIDEJGEC, int AMCCOGJACPK = 0) { }

	// // RVA: 0xAB9CB4 Offset: 0xAB9CB4 VA: 0xAB9CB4
	// public bool KIAAOBFJCHP(long JHNMKKNEENE) { }

	// // RVA: 0xABE1E8 Offset: 0xABE1E8 VA: 0xABE1E8
	// public bool HLNJABHOBKL() { }

	// // RVA: 0xABB770 Offset: 0xABB770 VA: 0xABB770
	// public GNGMCIAIKMA.DFABPMMMIIB GLJKKGFPEPA(int APFDNBGMMMM) { }

	// // RVA: 0xABE2E0 Offset: 0xABE2E0 VA: 0xABE2E0
	// public void GJENEJOANEL(int APFDNBGMMMM, DKFJADMCNPI.NLKCMNHOBAI INDDJNMPONH, int PPFNGGCBJKC, int HMFFHLPNMPH, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD) { }

	// // RVA: 0xABE998 Offset: 0xABE998 VA: 0xABE998
	// public void GJENEJOANEL(BBHNACPENDM AHEFHIMGIBI, int APFDNBGMMMM, DKFJADMCNPI.NLKCMNHOBAI INDDJNMPONH, int PPFNGGCBJKC, int HMFFHLPNMPH) { }

	// // RVA: 0xABE6F4 Offset: 0xABE6F4 VA: 0xABE6F4
	// private void GJENEJOANEL(NFMHCLHEMHB.CCGKCGJKADC NHLBKJCPLBL, DKFJADMCNPI.NLKCMNHOBAI INDDJNMPONH, int PPFNGGCBJKC, int HMFFHLPNMPH) { }

	// // RVA: 0xABEA14 Offset: 0xABEA14 VA: 0xABEA14
	// public void GJENEJOANEL(DKFJADMCNPI.NLKCMNHOBAI INDDJNMPONH, int OIPCCBHIKIA, int HMFFHLPNMPH, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD) { }

	// // RVA: 0xABEB0C Offset: 0xABEB0C VA: 0xABEB0C
	// public void GJENEJOANEL(BBHNACPENDM AHEFHIMGIBI, DKFJADMCNPI.NLKCMNHOBAI INDDJNMPONH, int OIPCCBHIKIA, int HMFFHLPNMPH) { }

	// // RVA: 0xABEBF4 Offset: 0xABEBF4 VA: 0xABEBF4
	// public int GOIAHBFBKPF(int APFDNBGMMMM, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, JKICPBIIHNE.IEGCPLCLOHF KOGBMDOONFA, OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, int HMFFHLPNMPH) { }

	// // RVA: 0xAC0900 Offset: 0xAC0900 VA: 0xAC0900
	// public bool FGHOILFCCKC(JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, JKICPBIIHNE.IEGCPLCLOHF KOGBMDOONFA, OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, long JHNMKKNEENE) { }

	// // RVA: 0xAC108C Offset: 0xAC108C VA: 0xAC108C
	public bool HEFIKPAHCIA(JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, long JHNMKKNEENE = -1)
    {
        UnityEngine.Debug.LogError("TODO");
        return false;
    }

	// // RVA: 0xAC1228 Offset: 0xAC1228 VA: 0xAC1228
	// public bool HEFIKPAHCIA(int APFDNBGMMMM, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, long JHNMKKNEENE = -1) { }

	// // RVA: 0xAC1BB8 Offset: 0xAC1BB8 VA: 0xAC1BB8
	// public void FBHHEBDDIMO(int APFDNBGMMMM, bool NLNNKIKIPBJ) { }

	// // RVA: 0xAC1BF0 Offset: 0xAC1BF0 VA: 0xAC1BF0
	// public List<JJPEIELNEJB.JLHHGLANHGE> HNBJHJENFGL(JJPEIELNEJB.OMMBBPKFLNH KOGBMDOONFA, List<int> FFLGNFIAFFE) { }

	// // RVA: 0xAC21E4 Offset: 0xAC21E4 VA: 0xAC21E4
	// public void CPIICACGNBH(JKNGJFOBADP JANMJPOKLFL, BBHNACPENDM LDEGEHAEALK, int KIJAPOFAGPN, int HMFFHLPNMPH, int APFDNBGMMMM) { }

	// // RVA: 0xAC234C Offset: 0xAC234C VA: 0xAC234C
	// public bool NJJLNPOCKFO(int APFDNBGMMMM) { }

	// // RVA: 0xAC257C Offset: 0xAC257C VA: 0xAC257C
	// public int OBOGIOGEBPK(int APFDNBGMMMM, FKMOKDCJFEN.ADCPCCNCOMD CMCKNKKCNDK) { }

	// // RVA: 0xAC26A8 Offset: 0xAC26A8 VA: 0xAC26A8
	// public int OBOGIOGEBPK(FKMOKDCJFEN.ADCPCCNCOMD CMCKNKKCNDK) { }

	// // RVA: 0xAC2790 Offset: 0xAC2790 VA: 0xAC2790
	// public void MNMCNPLIEFM(int APFDNBGMMMM, bool NLNNKIKIPBJ) { }

	// // RVA: 0xAC27DC Offset: 0xAC27DC VA: 0xAC27DC
	// public bool DOEGBMNNFKH(int APFDNBGMMMM) { }

	// // RVA: 0xAC2828 Offset: 0xAC2828 VA: 0xAC2828
	// public bool EAJLHMIMAPE(int APFDNBGMMMM) { }
}
