
using System.Collections.Generic;
using XeApp.Game.Common;

public class HEFCLPGPMLK
{
	public class AAOPGOGGMID
	{
		public int PPFNGGCBJKC; // 0x8
		public string IJOLPDKFLPO; // 0xC
		public int KINFGHHNFCF; // 0x10
		public int NONBCCLGBAO; // 0x14
		public BOPFPIHGJMD.LGEIPIHHNPH DFMOGBOPLEF; // 0x18
		public int CIEOBFIIPLD; // 0x1C
		public int NBLBJCLIDNN; // 0x20
		public bool NBHEBLNHOJO; // 0x24
		public int BIEGNEGKLDE; // 0x28
		public List<int> AHNKDJLBLNM = new List<int>(); // 0x2C
		public List<int> PCPPHNINBBC = new List<int>(); // 0x30
		public BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG; // 0x34
		public BOPFPIHGJMD.ADMNKELOLPN CGKPIIFCCLD; // 0x38
		public BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK; // 0x3C
		public long KINJOEIAHFK; // 0x40
		public long PCCFAKEOBIC; // 0x48
		public long JGAMLEMMJCJ; // 0x50
		public long GCDPPCDBPDD; // 0x58
		public long LOAEGNGKFNF; // 0x60
		public int IMPNNOLLMBK; // 0x68
		public bool CADENLBDAEB; // 0x6C
		public bool OHOGIHMFEIJ; // 0x6D
		public int MNPEAHNONAI; // 0x70
		public int KPFHAMNOIAG; // 0x74
		public int AHHJLDLAPAN; // 0x78
		public BOPFPIHGJMD.HDHDOOLPBEO HBJEDMOMAEE; // 0x7C

		//// RVA: 0x1747F3C Offset: 0x1747F3C VA: 0x1747F3C
		//public OfferSelectContent.OrderButtonState MJKJGDOIAGO() { }
	}

	public class ANKPCIEKPAH
	{
		public int LLOBHDMHJIG; // 0x8
		public int LABKKJAGDFN; // 0xC
		public int KINFGHHNFCF; // 0x10
		public int NONBCCLGBAO; // 0x14
		public int JMHKMDFNAIN; // 0x18
		public SeriesAttr.Type CPKMLLNADLJ; // 0x1C
		public int PFGJJLGLPAC; // 0x20
		public string PMKFOEIFBLB; // 0x24
		public string PNIEAEHKGMJ; // 0x28
		public int CNLIAMIIJID; // 0x2C
		public bool LPDDOLAIODN; // 0x30
		public int HOJHKJBBOLM; // 0x34
		public int CKJPPJHNBBN; // 0x38
		public int KFFEFIPMOLD; // 0x3C
	}

	public class DNNODDKHJBJ : IComparer<AAOPGOGGMID>
	{
		private int AAFGNHHCILA = -1; // 0x8
		private int OJDPFLDPODB = -1; // 0xC

		// RVA: 0x1745D74 Offset: 0x1745D74 VA: 0x1745D74
		public DNNODDKHJBJ(bool DACKJBKIDOM = false)
		{
			AAFGNHHCILA = DACKJBKIDOM ? -1 : 1;
			OJDPFLDPODB = DACKJBKIDOM ? 1 : -1;
		}

		// RVA: 0x1747F80 Offset: 0x1747F80 VA: 0x1747F80 Slot: 4
		public int Compare(AAOPGOGGMID HKICMNAACDA, AAOPGOGGMID BNKHBCBJBKI)
		{
			if(HKICMNAACDA.CIEOBFIIPLD == BNKHBCBJBKI.CIEOBFIIPLD)
			{
				if(HKICMNAACDA.JGAMLEMMJCJ == BNKHBCBJBKI.JGAMLEMMJCJ)
				{
					if(HKICMNAACDA.NONBCCLGBAO == BNKHBCBJBKI.NONBCCLGBAO)
					{
						if (HKICMNAACDA.PPFNGGCBJKC == BNKHBCBJBKI.PPFNGGCBJKC)
							return 0;
						if (HKICMNAACDA.PPFNGGCBJKC <= BNKHBCBJBKI.PPFNGGCBJKC)
							return OJDPFLDPODB;
					}
					else if(HKICMNAACDA.NONBCCLGBAO <= BNKHBCBJBKI.NONBCCLGBAO)
						return OJDPFLDPODB;
				}
				else if (HKICMNAACDA.JGAMLEMMJCJ <= BNKHBCBJBKI.JGAMLEMMJCJ)
					return OJDPFLDPODB;
			}
			else
			{
				if (HKICMNAACDA.CIEOBFIIPLD <= BNKHBCBJBKI.CIEOBFIIPLD)
					return OJDPFLDPODB;
			}
			return AAFGNHHCILA;
		}
	}

	public List<AAOPGOGGMID> CAGIOJAAGGP; // 0x8
	public List<AAOPGOGGMID> KPMDLOBOEEM; // 0xC
	public List<AAOPGOGGMID> NLKBPLNCPGG; // 0x10
	public List<AAOPGOGGMID> PJEOEOHGMMA; // 0x14
	public List<ANKPCIEKPAH> MDNHCIKGEAE; // 0x18

	// RVA: 0x17439B0 Offset: 0x17439B0 VA: 0x17439B0
	public void EMAEAEAKDLJ()
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		if(KDHGBOOECKC.HHCJCDFCLOB != null)
		{
			KDHGBOOECKC.HHCJCDFCLOB.HKDGKDNIGDD();
			KDHGBOOECKC.HHCJCDFCLOB.JPNPPIHOJFC(time);
			CAGIOJAAGGP = IOCBIDHIIAE(time);
			KPMDLOBOEEM = GCHFJGGNEAM(time);
			NLKBPLNCPGG = CICAACFCNDC(time);
			PJEOEOHGMMA = JNJOOCCFBLF(time);
		}
	}

	//// RVA: 0x17453CC Offset: 0x17453CC VA: 0x17453CC
	//public HEFCLPGPMLK.AAOPGOGGMID HHPEMLOLJIH() { }

	//// RVA: 0x17456B8 Offset: 0x17456B8 VA: 0x17456B8
	//public List<HEFCLPGPMLK.AAOPGOGGMID> PDFOBMKIKKJ(BOPFPIHGJMD.MLBMHDCCGHI INDDJNMPONH, bool CILNIPJEECH = False, bool GJAFIADJFHH = False) { }

	//// RVA: 0x17457A4 Offset: 0x17457A4 VA: 0x17457A4
	//public List<HEFCLPGPMLK.AAOPGOGGMID> OEMBGNHHONF(List<HEFCLPGPMLK.AAOPGOGGMID> NNDGIAEFMOG, bool DACKJBKIDOM = False) { }

	//// RVA: 0x1745DB4 Offset: 0x1745DB4 VA: 0x1745DB4
	//public void KJODFBIBFFO(BBHNACPENDM LDEGEHAEALK, ref HEFCLPGPMLK.AAOPGOGGMID IDLHJIOMJBK, int FGHGMHPNEMG, int MLDPDLPHJPM, long JHNMKKNEENE) { }

	//// RVA: 0x1743B28 Offset: 0x1743B28 VA: 0x1743B28
	public List<AAOPGOGGMID> IOCBIDHIIAE(long JHNMKKNEENE)
	{
		List<AAOPGOGGMID> res = new List<AAOPGOGGMID>();
		if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
		{
			if(KDHGBOOECKC.HHCJCDFCLOB != null)
			{
				List<LGHIPHEDCNC_Offer.LHDLCLNBPLB>  l1 = KDHGBOOECKC.HHCJCDFCLOB.MIMNFDFLFFA(JHNMKKNEENE);
				for(int i = 0; i < l1.Count; i++)
				{
					AAOPGOGGMID data = new AAOPGOGGMID();
					data.PPFNGGCBJKC = l1[i].PPFNGGCBJKC;
					data.IJOLPDKFLPO = KDHGBOOECKC.HHCJCDFCLOB.GEGAJLNPMEC(l1[i].GBJFNGCDKPM, l1[i].PPFNGGCBJKC);
					data.DFMOGBOPLEF = KDHGBOOECKC.HHCJCDFCLOB.MDNPDBIPKLB(l1[i].CPKMLLNADLJ, l1[i].JBHBGOIMALD);
					data.KINFGHHNFCF = l1[i].FCBJFKGDINH;
					data.NONBCCLGBAO = l1[i].NONBCCLGBAO;
					data.FGHGMHPNEMG = (BOPFPIHGJMD.MLBMHDCCGHI)l1[i].GBJFNGCDKPM;
					data.CGKPIIFCCLD = (BOPFPIHGJMD.ADMNKELOLPN)l1[i].CECKOCLEABH;
					data.CIEOBFIIPLD = l1[i].GOKJLBDJOLA;
					data.NBLBJCLIDNN = l1[i].GOKJLBDJOLA;
					data.NBHEBLNHOJO = false;
					data.AHHJLDLAPAN = 0;
					data.BIEGNEGKLDE = l1[i].BBMBLOABEOK;
					for(int j = 0; j < l1[i].AGMPIKBJPPB(); j++)
					{
						data.AHNKDJLBLNM.Add(l1[i].GNLAKGANAPG(j));
						data.PCPPHNINBBC.Add(l1[i].FALLJIODMBC(j));
					}
					data.KPFHAMNOIAG = 5;
					data.HBJEDMOMAEE = 0;
					data.JGAMLEMMJCJ = l1[i].AIIOIKGMOBD * 60;
					data.IMPNNOLLMBK = (int)data.JGAMLEMMJCJ;
					data.OHOGIHMFEIJ = l1[i].LJNAKDMILMC > 0;
					KJODFBIBFFO(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave, ref data, l1[i].GBJFNGCDKPM, l1[i].PPFNGGCBJKC, JHNMKKNEENE);
					res.Add(data);
				}
				return OEMBGNHHONF(res, KDHGBOOECKC.HHCJCDFCLOB.LBKNBKPBAPJ());
			}
		}
		return res;
	}

	//// RVA: 0x1744144 Offset: 0x1744144 VA: 0x1744144
	//public List<HEFCLPGPMLK.AAOPGOGGMID> GCHFJGGNEAM(long JHNMKKNEENE) { }

	//// RVA: 0x1744750 Offset: 0x1744750 VA: 0x1744750
	//public List<HEFCLPGPMLK.AAOPGOGGMID> CICAACFCNDC(long JHNMKKNEENE) { }

	//// RVA: 0x1744DCC Offset: 0x1744DCC VA: 0x1744DCC
	//public List<HEFCLPGPMLK.AAOPGOGGMID> JNJOOCCFBLF(long JHNMKKNEENE) { }

	//// RVA: 0x17460DC Offset: 0x17460DC VA: 0x17460DC
	//public void CFMHAGBNNKA() { }

	//// RVA: 0x17460F4 Offset: 0x17460F4 VA: 0x17460F4
	//public List<HEFCLPGPMLK.ANKPCIEKPAH> AANFIKBAJPI() { }

	//// RVA: 0x1746A04 Offset: 0x1746A04 VA: 0x1746A04
	//public List<HEFCLPGPMLK.ANKPCIEKPAH> PMFIOHGEPPD(int PPFNGGCBJKC, bool LIFPCFFJEOA = False) { }

	//// RVA: 0x1746E08 Offset: 0x1746E08 VA: 0x1746E08
	//private int AIJJCLLJOKH(List<HEFCLPGPMLK.ANKPCIEKPAH> NNDGIAEFMOG) { }

	//// RVA: 0x1746708 Offset: 0x1746708 VA: 0x1746708
	//public int LHFJMGDOBEK(int FODKKJIDDKN) { }

	//// RVA: 0x174689C Offset: 0x174689C VA: 0x174689C
	//public int NAEMOCCOGAA(int PPFNGGCBJKC, int FODKKJIDDKN) { }

	//// RVA: 0x1746FC0 Offset: 0x1746FC0 VA: 0x1746FC0
	//public bool JBHBEKJHLFE(int PPFNGGCBJKC, int ADPPAIPFHML, int FODKKJIDDKN) { }

	//// RVA: 0x174718C Offset: 0x174718C VA: 0x174718C
	//public string NPMKEEANPBE(int PPFNGGCBJKC) { }

	//// RVA: 0x17472D8 Offset: 0x17472D8 VA: 0x17472D8
	//public bool PFEMFIICBCE(int PPFNGGCBJKC, string OPFGFINHFCE) { }

	//// RVA: 0x174741C Offset: 0x174741C VA: 0x174741C
	//public bool NAIBONEPAOJ(int OIOECMEEFKJ) { }

	//// RVA: 0x1747664 Offset: 0x1747664 VA: 0x1747664
	//public bool JHBMCGABHMD(int FODKKJIDDKN) { }

	//// RVA: 0x1747688 Offset: 0x1747688 VA: 0x1747688
	//public List<int> LOEDABGEMFJ(int CPKMLLNADLJ) { }

	//// RVA: 0x174784C Offset: 0x174784C VA: 0x174784C
	//public int LLMEKDNIOEF(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	//// RVA: 0x17478C0 Offset: 0x17478C0 VA: 0x17478C0
	//public HEFCLPGPMLK.ANKPCIEKPAH FFGHIOAOABE(int PPFNGGCBJKC) { }

	// RVA: 0x1747A48 Offset: 0x1747A48 VA: 0x1747A48
	public int NCAPNMMJCLF()
	{
		int res = 0;
		if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
		{
			if(KDHGBOOECKC.HHCJCDFCLOB != null)
			{
				List<KDHGBOOECKC.NOCAJFGHDPC> l1 = KDHGBOOECKC.HHCJCDFCLOB.NBIJDMOOILH();
				List<OCMJNBIFJNM_Offer.JPOHOLBBFGP> l2 = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.DAEJHMCMFJD_Offer.FOFLMHELILC;
				for(int i = 0; i < l1.Count; i++)
				{
					OCMJNBIFJNM_Offer.JPOHOLBBFGP save = l2[l1[i].OIPCCBHIKIA_Index];
					if(save.EALOBDHOCHP_Stat == 2 || save.EALOBDHOCHP_Stat == 3)
					{
						if (save.OIOECMEEFKJ_VFp > 0)
							res++;
					}
				}
			}
		}
		return res;
	}

	// RVA: 0x1747C58 Offset: 0x1747C58 VA: 0x1747C58
	public int JGFHJPGJJHP()
	{
		if (KDHGBOOECKC.HHCJCDFCLOB != null)
			return KDHGBOOECKC.HHCJCDFCLOB.JGFHJPGJJHP();
		return 0;
	}

	//// RVA: 0x1747C80 Offset: 0x1747C80 VA: 0x1747C80
	//public string OMPLNLDPOFN(int OIOECMEEFKJ) { }

	// RVA: 0x1747D00 Offset: 0x1747D00 VA: 0x1747D00
	public string BEGJBMHBGPL()
	{
		if(KDHGBOOECKC.HHCJCDFCLOB != null)
		{
			string str = KDHGBOOECKC.HHCJCDFCLOB.JIMBMBEEMHI();
			KDHGBOOECKC.HHCJCDFCLOB.PANKGNBPFEL(0);
			KDHGBOOECKC.HHCJCDFCLOB.BFJFAIIAMMO(2, true);
			return str;
		}
		return "";
	}

	// RVA: 0x1747DA4 Offset: 0x1747DA4 VA: 0x1747DA4
	public bool OHILPCDFKCH()
	{
		if (KDHGBOOECKC.HHCJCDFCLOB != null)
			return KDHGBOOECKC.HHCJCDFCLOB.OHILPCDFKCH();
		return false;
	}

	//// RVA: 0x1747DCC Offset: 0x1747DCC VA: 0x1747DCC
	//public int ECBHIIOABCK() { }

	//// RVA: 0x1747DF4 Offset: 0x1747DF4 VA: 0x1747DF4
	//public int PDGOLEJBNMM(BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK) { }
}
