using FlatBuffers;


public class IAIDGBJGDBH
{
	// public CCNNJMCKOGH EOACHAJJLHB { get; set; } // 0x8 ABHGFDJHAPO NKIGALDEEOA JEEMNBLJMOG
	// public CAEJOAOPJCJ[] POEOOJPBOJC { get; set; } // 0xC ENMIKFEDBDB GNCCEOKGKKE GENHEFPAIHO
	// public KHCOEKAINPK[] KPDMCJELMCI { get; set; } // 0x10 NCMJPPALBKH BNLKAIGKGIB LHPCNDOPPMF
	// public NNAAOAAGGCE[] NELGGEGAJPH { get; set; } // 0x14 FONBGKPLGJN ABEJIHHNBMJ HKIMBDOFNJN
	// public FNLNOMGDCIJ[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	// public FIHADIALPIL[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	// public EOMJDOOGLIC[] GJOBPIOOEHD { get; set; } // 0x20 BGBFGBNBBGL LLACDANLENK HLHGABNJNNM

	// // RVA: 0x120DA20 Offset: 0x120DA20 VA: 0x120DA20
	public static IAIDGBJGDBH HEGEKFMJNCC(byte[] NIODCJLINJN)
    {
        ByteBuffer reader = new ByteBuffer(NIODCJLINJN); // this
        DHFKAKFHFOL d = DHFKAKFHFOL.GetRootAsDHFKAKFHFOL(reader); // this00
        IAIDGBJGDBH self = new IAIDGBJGDBH(); // this01
        //CCNNJMCKOGH c = new CCNNJMCKOGH(); // pcVar1
        UnityEngine.Debug.LogError("TODO");
		return null;
    }
}
