public class IBIGBMDANNM
{
	public enum LJJOIIAEICI
	{
		CCAPCGPIIPF = 0,
		HEEJBCDDOJJ = 1,
		BGHNFBANAMN = 2,
		FCDDHHKAGEP = 3,
	}
	
	public long AJECHDLMKOE_LastLogin; // 0x10
	public long DHIFKMEFABP; // 0x18
	public LJJOIIAEICI LHMDABPNDDH; // 0x28
	public BBHNACPENDM_ServerSaveData AHEFHIMGIBI; // 0x2C
	public bool ONAFFLLLBHE; // 0x30
	public int FJOLNJLLJEJ; // 0x34
	public long KNIFCANOHOC; // 0x38
	public double HMLEDBJDCAF; // 0x40

	public int MLPEHNBNOGD { get; set; } // 0x8 OCNCGDJNBIH LJALJLIIODH MKBAMFJNCDK
	//public int ADFIHAPELAN { get; set; } 0x121255C NBALCMLLJGJ 0x12125A8 CPMNIMFDFAM
	public string LBODHBDOMGK { get { return AHEFHIMGIBI.JHFIPCIHJNL_Base.OPFGFINHFCE_Cont; } set { AHEFHIMGIBI.JHFIPCIHJNL_Base.OPFGFINHFCE_Cont = value; } }// 0x12125FC JLFIGDAGIEB 0x1212648 KMHENDLDBEA
	public string LFKJNMFFCLH { get; set; } // 0x20 JDLEEBJKOIL LMGFMDMOCIC KKODLMIGNIG
	//public int PDJEMLMOEPF { get; set; } 0x12126AC OICEHMGFBOG 0x12126F8 GIAENPIECFL
	//public int FCKJJGIMPPI { get; set; } 0x121274C KHAEBKHHDDH 0x1212798 FODBHLHKHFI
	//public int NOEAJIJIIHK { get; set; } 0x12127EC IKHEOMAMDGP 0x1212838 MMLGLIOAOBA
	//public bool CADENLBDAEB { get; } 0x121288C KJGFPPLHLAB
	public int NEILEPPJKIN { get; set; } // 0x24 MBBNGAAAJKL 0x12128A0 CPCOJHKJPAG 0x12128A8 JOPFPEAKGOH

	//// RVA: 0x12128B0 Offset: 0x12128B0 VA: 0x12128B0
	//public string LDBPEIMINJB() { }

	//// RVA: 0x1212D10 Offset: 0x1212D10 VA: 0x1212D10 Slot: 4
	//public virtual bool EDEDFDDIOKO(int PPFNGGCBJKC, long IFNLEKOILPM, bool MLEHCBKPNGK, List<string> OHNJJIMGKGK, EDOHBJAPLPF IDLHJIOMJBK) { }

	//// RVA: 0x1212DEC Offset: 0x1212DEC VA: 0x1212DEC Slot: 5
	//protected virtual bool NLENMNMCJCJ(int PPFNGGCBJKC, long IFNLEKOILPM, bool MLEHCBKPNGK, List<string> OHNJJIMGKGK, EDOHBJAPLPF IDLHJIOMJBK, BBHNACPENDM AHEFHIMGIBI) { }

	//// RVA: -1 Offset: -1
	//public static FriendPlayerDataClass HEGEKFMJNCC<FriendPlayerDataClass>(int PPFNGGCBJKC, long IFNLEKOILPM, bool MLEHCBKPNGK, List<string> OHNJJIMGKGK, EDOHBJAPLPF IDLHJIOMJBK) { }
	///* GenericInstMethod :
	//|
	//|-RVA: 0x2B62220 Offset: 0x2B62220 VA: 0x2B62220
	//|-IBIGBMDANNM.HEGEKFMJNCC<IBIGBMDANNM>
	//|-IBIGBMDANNM.HEGEKFMJNCC<IFICNCAHIGI>
	//|-IBIGBMDANNM.HEGEKFMJNCC<NKOBMDPHNGP.ELKMKCNPDFO>
	//|-IBIGBMDANNM.HEGEKFMJNCC<object>
	//*/

	//// RVA: 0x1212F94 Offset: 0x1212F94 VA: 0x1212F94
	//public void ILEBOIGEGEH() { }
}
