
using XeSys;

public class IEIGOPLPJGI
{
	public int PFGJJLGLPAC_PilotId; // 0x8
	public string OPFGFINHFCE; // 0xC
	public int AIHCEGFANAM; // 0x10
	public int CHIMPKJDCPP; // 0x14

	// // RVA: 0x11ED364 Offset: 0x11ED364 VA: 0x11ED364
	public void KHEKNNFCAOI_Init(int PFGJJLGLPAC)
	{
		PFGJJLGLPAC_PilotId = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OBGGLAKOHKP.GCINIJEMHFK[PFGJJLGLPAC].PFGJJLGLPAC;
		AIHCEGFANAM = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OBGGLAKOHKP.GCINIJEMHFK[PFGJJLGLPAC].AIHCEGFANAM;
		CHIMPKJDCPP = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OBGGLAKOHKP.GCINIJEMHFK[PFGJJLGLPAC].CHIMPKJDCPP;
		OPFGFINHFCE = MessageManager.Instance.GetMessage("master", "plt_nm_" + PFGJJLGLPAC.ToString("D4"));
	}
}
