
using System.Collections.Generic;

public class IHGHHPPDPEO
{
	private IOEKHJBOMDH_DecoStamp GOHGFAGAKOO; // 0x8

	// RVA: 0x11FBA04 Offset: 0x11FBA04 VA: 0x11FBA04
	public IHGHHPPDPEO()
	{
		GOHGFAGAKOO = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.FJPOELGFPBP_DecoStamp;
	}

	//// RVA: 0x11FBAD4 Offset: 0x11FBAD4 VA: 0x11FBAD4
	public List<IOEKHJBOMDH_DecoStamp.PAFLFMFEOJD> GMCKCMFKPOB()
	{
		return GOHGFAGAKOO.GNKJGECHLNE_CustomList;
	}

	//// RVA: 0x11FBAF8 Offset: 0x11FBAF8 VA: 0x11FBAF8
	public void JCHLONCMPAJ()
	{
		for(int i = 0; i < GOHGFAGAKOO.GNKJGECHLNE_CustomList.Count; i++)
		{
			GOHGFAGAKOO.GNKJGECHLNE_CustomList[i].LHPDDGIJKNB_Reset(0);
		}
	}

	//// RVA: 0x11FBC00 Offset: 0x11FBC00 VA: 0x11FBC00
	public void ANIJHEBLMGB(int _OIPCCBHIKIA_index, int _GNKMHCKFADN_stamp, int _HELBHEPKBJF_serif)
	{
		if (!MALJLHJOPLD_IsIndexValid(_OIPCCBHIKIA_index))
			return;
		GOHGFAGAKOO.GNKJGECHLNE_CustomList[_OIPCCBHIKIA_index].CNOHJPEHHCH_StampId = _GNKMHCKFADN_stamp;
		GOHGFAGAKOO.GNKJGECHLNE_CustomList[_OIPCCBHIKIA_index].JBOCHIJAMFD_SerifId = _HELBHEPKBJF_serif;
	}

	//// RVA: 0x11FBDB0 Offset: 0x11FBDB0 VA: 0x11FBDB0
	//public void ANIJHEBLMGB(int ECEOBKOFJHK, int EMMDEKDEKGO) { }

	//// RVA: 0x11FBF40 Offset: 0x11FBF40 VA: 0x11FBF40
	//public void OJCJPCHFPGO(int _OIPCCBHIKIA_index) { }

	//// RVA: 0x11FC038 Offset: 0x11FC038 VA: 0x11FC038
	//public void LIOJACECPEI(int LGOPCGPCLCO, int MHAEMMMHFLB) { }

	//// RVA: 0x11FC1E0 Offset: 0x11FC1E0 VA: 0x11FC1E0
	public void HJMKBCFJOOH(IMCBBOAFION _BHFHGFKBOHH_OnSuccess, DJBHIFLHJLK _MOBEEPPKFLG_OnFail)
	{
		CIOECGOMILE.HHCJCDFCLOB.AIKJMHBDABF_SavePlayerData(_BHFHGFKBOHH_OnSuccess, _MOBEEPPKFLG_OnFail, null);
	}

	//// RVA: 0x11FBD00 Offset: 0x11FBD00 VA: 0x11FBD00
	private bool MALJLHJOPLD_IsIndexValid(int _OIPCCBHIKIA_index)
	{
		if (_OIPCCBHIKIA_index < 0)
			return false;
		return _OIPCCBHIKIA_index < GOHGFAGAKOO.GNKJGECHLNE_CustomList.Count;
	}
}
