
using XeApp.Game.Common;

public class IIMBAOGHCIG
{
	public enum BEFNGAHBLEN
	{
		HJNNKCMLGFL = 0,
		JJGHKIBKFFJ = 1,
	}

	public BadgeConstant.ID BEEIIJJKDBH; // 0x8
	public string BHANMJKCCBC; // 0xC

	//// RVA: 0x1204B5C Offset: 0x1204B5C VA: 0x1204B5C
	public void FBANBDCOEJL(bool CADENLBDAEB)
	{
		if(HNNHJGJCFIL() != BEFNGAHBLEN.JJGHKIBKFFJ/*1*/)
		{
			BEEIIJJKDBH = CADENLBDAEB ? BadgeConstant.ID.New : BadgeConstant.ID.None;
			return;
		}
		BEEIIJJKDBH = BadgeConstant.ID.Label;
		BHANMJKCCBC = KDHGBOOECKC.HHCJCDFCLOB.JIDINGHMOJF();
	}

	//// RVA: 0x1204BC0 Offset: 0x1204BC0 VA: 0x1204BC0
	private BEFNGAHBLEN HNNHJGJCFIL()
	{
		if(!KDHGBOOECKC.HHCJCDFCLOB.CCPNBHCKNDC())
		{
			if(!KDHGBOOECKC.HHCJCDFCLOB.LOCAIBNPKDL_IsPlayerLevelOk())
			{
				return BEFNGAHBLEN.JJGHKIBKFFJ/*1*/;
			}
			return BEFNGAHBLEN.HJNNKCMLGFL/*0*/;
		}
		return BEFNGAHBLEN.JJGHKIBKFFJ/*1*/;
	}
}
