
public class IKCGAJKCPFN
{
	public int FBGGEFFJJHB; // 0x8
	public int EOONNJAMAMJ_StatCrypted2; // 0xC
	public int EHOIENNDEDH_IdCrypted; // 0x10
	public int HLMAFFLCCKD_CountCrypted; // 0x14
	public int INNAAKJONMJ_StatCrypted; // 0x18
	public int IMKEAJDJANE_CountCrypted2; // 0x1C
	public int BJMDLOCLCEN_Crypted; // 0x20
	public long BEBJKJKBOGH_Date; // 0x28
	public bool CADENLBDAEB_IsNew; // 0x30

	public int PPFNGGCBJKC_Id { get { return FBGGEFFJJHB ^ EHOIENNDEDH_IdCrypted; } set { EHOIENNDEDH_IdCrypted = value ^ FBGGEFFJJHB; } } //0x8DBB88 DEMEPMAEJOO 0x8DBB98 HIGKAIDMOKN
	public int EALOBDHOCHP_Stat { get { return FBGGEFFJJHB ^ INNAAKJONMJ_StatCrypted; } set { INNAAKJONMJ_StatCrypted = value ^ FBGGEFFJJHB; EOONNJAMAMJ_StatCrypted2 = INNAAKJONMJ_StatCrypted; } } //0x8DBBA8 KLDFNIEJBFE 0x8DBBB8 GJLLJFLGMCN
	public int HMFFHLPNMPH_Count { get { return FBGGEFFJJHB ^ HLMAFFLCCKD_CountCrypted; } set { HLMAFFLCCKD_CountCrypted = value ^ FBGGEFFJJHB; IMKEAJDJANE_CountCrypted2 = HLMAFFLCCKD_CountCrypted; } } //0x8DBBCC NJOGDDPICKG 0x8DBBDC NBBGMMBICNA
	public int JIOMCDGKIAF { get { return FBGGEFFJJHB ^ BJMDLOCLCEN_Crypted; } set { BJMDLOCLCEN_Crypted = value ^ FBGGEFFJJHB; } } //0x8DBBF0 DJHPCCHENCM 0x8DBC00 CJEGJOKIJPO

	//// RVA: 0x8DBC10 Offset: 0x8DBC10 VA: 0x8DBC10
	public void LHPDDGIJKNB(int PPFNGGCBJKC, int KNEFBLHBDBG)
	{
		BEBJKJKBOGH_Date = 0;
		FBGGEFFJJHB = KNEFBLHBDBG;
		EALOBDHOCHP_Stat = 0;
		this.PPFNGGCBJKC_Id = PPFNGGCBJKC;
		HMFFHLPNMPH_Count = 0;
		CADENLBDAEB_IsNew = true;
	}

	//// RVA: 0x8DBC44 Offset: 0x8DBC44 VA: 0x8DBC44
	public bool AGBOGBEOFME(IKCGAJKCPFN OIKJFMGEICL)
	{
		if (CADENLBDAEB_IsNew != OIKJFMGEICL.CADENLBDAEB_IsNew ||
			PPFNGGCBJKC_Id != OIKJFMGEICL.PPFNGGCBJKC_Id ||
			EALOBDHOCHP_Stat != OIKJFMGEICL.EALOBDHOCHP_Stat ||
			HMFFHLPNMPH_Count != OIKJFMGEICL.HMFFHLPNMPH_Count ||
			BEBJKJKBOGH_Date != OIKJFMGEICL.BEBJKJKBOGH_Date
			)
			return false;
		return true;
	}

	//// RVA: 0x8DBDBC Offset: 0x8DBDBC VA: 0x8DBDBC
	public void ODDIHGPONFL(IKCGAJKCPFN OIKJFMGEICL)
	{
		PPFNGGCBJKC_Id = OIKJFMGEICL.PPFNGGCBJKC_Id;
		EALOBDHOCHP_Stat = OIKJFMGEICL.EALOBDHOCHP_Stat;
		HMFFHLPNMPH_Count = OIKJFMGEICL.HMFFHLPNMPH_Count;
		BEBJKJKBOGH_Date = OIKJFMGEICL.BEBJKJKBOGH_Date;
		CADENLBDAEB_IsNew = OIKJFMGEICL.CADENLBDAEB_IsNew;
	}

	//// RVA: 0x8DBEA8 Offset: 0x8DBEA8 VA: 0x8DBEA8
	//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, IKCGAJKCPFN OHMCIEMIKCE, bool EFOEPDLNLJG) { }

	//// RVA: 0x8DCB60 Offset: 0x8DCB60 VA: 0x8DCB60
	public EDOHBJAPLPF_JsonData NOJCMGAFAAC()
	{
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		data["id"] = PPFNGGCBJKC_Id;
		data["stat"] = EALOBDHOCHP_Stat;
		data["count"] = HMFFHLPNMPH_Count;
		data["date"] = BEBJKJKBOGH_Date;
		data[AFEHLCGHAEE_Strings.KLJGEHBKMMG_new] = CADENLBDAEB_IsNew ? 1 : 0;
		return data;
	}
}
