using System.Text;
using UnityEngine;

public class ILCCJNDFFOB
{
	// public ILCCJNDFFOB.GOIOAIDCKDD HFGPPPOINDJ; // 0x8
	private const int LBBLKAEDGHE = 10;
	private StringBuilder JBBHNIACMFJ = new StringBuilder(256); // 0xC
	private StringBuilder NNNAKNFEPCF = new StringBuilder(64); // 0x10
	private long BMOBAOCHNMO; // 0x18
	private static string[] LDLBGFMFMDG = new string[6] { "enemy_info_id1", 
                                                            "enemy_info_id2", 
                                                            "enemy_info_id3", 
                                                            "enemy_info_id4",
                                                            "enemy_info_id5",
                                                            "enemy_info_id6"}; // 0x4
	private static string[] JGDKLDDPNAB = new string[6] { "enemy_info_1",
                                                            "enemy_info_2",
                                                            "enemy_info_3",
                                                            "enemy_info_4",
                                                            "enemy_info_5",
                                                            "enemy_info_6"}; // 0x8

	public static ILCCJNDFFOB HHCJCDFCLOB { get; set; } // 0x0 LGMPACEDIJF NKACBOEHELJ 0x8F3D90 OKPMHKNCNAL 0x8F3E1C

	// // RVA: 0x8F3EAC Offset: 0x8F3EAC VA: 0x8F3EAC
	public void IJBGPAENLJA()
    {
        HHCJCDFCLOB = this;
    }

	// // RVA: 0x8F3F2C Offset: 0x8F3F2C VA: 0x8F3F2C
	// private string AOKAECCKGFC(DateTime EBBCCKCMBMC) { }

	// // RVA: 0x8F4100 Offset: 0x8F4100 VA: 0x8F4100
	// private string BGLHDAKDPMJ(DateTime EBBCCKCMBMC) { }

	// // RVA: 0x8F4400 Offset: 0x8F4400 VA: 0x8F4400
	// private string COPGJHJGHJG(long KPBJHHHMOJE) { }

	// // RVA: 0x8F44CC Offset: 0x8F44CC VA: 0x8F44CC
	private void FLBFCCIEPNC(EDOHBJAPLPF_JsonData IDLHJIOMJBK, long JCNNBEEHFLE)
	{
		UnityEngine.Debug.LogWarning("TODO ILCCJNDFFOB.FLBFCCIEPNC");
	}

	// // RVA: 0x8F4AB8 Offset: 0x8F4AB8 VA: 0x8F4AB8
	// private void BAHPICOFGFH(EDOHBJAPLPF_JsonData IDLHJIOMJBK, JBECFDNKPFD MFCGAKOAGFE) { }

	// // RVA: 0x8F509C Offset: 0x8F509C VA: 0x8F509C
	private static void DEGEPBNNOAF(OAGBCBBHMPF.KJDNDEDOIOO KAPMOPMDHJE, EDOHBJAPLPF_JsonData IDLHJIOMJBK, bool FOIGCFNFPOB = false)
	{
		JDDGPJDKHNE.HHCJCDFCLOB.CLHLFPDNFNM((int)KAPMOPMDHJE,IDLHJIOMJBK,FOIGCFNFPOB);
	}

	// // RVA: 0x8F50E4 Offset: 0x8F50E4 VA: 0x8F50E4
	// public void JONAMONAHOB(int ADPPAIPFHML, int FKIBPHGINAE, LGDNAJACFHI MEANCEOIMGE) { }

	// // RVA: 0x8F5B88 Offset: 0x8F5B88 VA: 0x8F5B88
	// public void KMEONFIEFHN(int ADPPAIPFHML, int FKIBPHGINAE, FHPFLAGNCAF MEANCEOIMGE) { }

	// // RVA: 0x8F602C Offset: 0x8F602C VA: 0x8F602C
	// public void PMFGEJJDMCK(int PPFNGGCBJKC, int INDDJNMPONH, string FPGMBHJNGIK, int ADPPAIPFHML, int JLPEGFAMKPK) { }

	// // RVA: 0x8F63AC Offset: 0x8F63AC VA: 0x8F63AC
	// public void ALABPEPENHH(OAGBCBBHMPF.OGBCFNIKAFI LGADCGFMLLD, long GCLPIJNJFAE) { }

	// // RVA: 0x8F6A44 Offset: 0x8F6A44 VA: 0x8F6A44
	// public EDOHBJAPLPF_JsonData LECBAPOGJAG(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP) { }

	// // RVA: 0x8FACB0 Offset: 0x8FACB0 VA: 0x8FACB0
	// public void FKODKMNGCEH(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP) { }

	// // RVA: 0x8FAE00 Offset: 0x8FAE00 VA: 0x8FAE00
	// public EDOHBJAPLPF_JsonData MKMJILJPOGC(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN) { }

	// // RVA: 0x8FC960 Offset: 0x8FC960 VA: 0x8FC960
	// public void IMJLLLNHICJ(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN) { }

	// // RVA: 0x8FD4B0 Offset: 0x8FD4B0 VA: 0x8FD4B0
	// public void KHMDGNKEFOD(string CHJGGLFGALP, int EIANMIIKPDH, bool NMJBGABMEDK = False, bool CMEOKJMCEBH = False, int AHHJLDLAPAN = 1) { }

	// // RVA: 0x8FE158 Offset: 0x8FE158 VA: 0x8FE158
	// public void JNBKOAKJDAL(int HHGMPEEGFMA, int HMFFHLPNMPH, int IIGPLLECFND, int KJMLLBDLKCG, List<int> IHBECLGCIJI, BBHNACPENDM LDEGEHAEALK, IAPIDHGIEED OMOEKOCNICP, IAPIDHGIEED ONNIHHLHLDP, PFIJNPCEOIL IFFKECJOPIB) { }

	// // RVA: 0x8FF43C Offset: 0x8FF43C VA: 0x8FF43C
	// public void JNBKOAKJDAL(int HHGMPEEGFMA, int HMFFHLPNMPH, int IIGPLLECFND, int KJMLLBDLKCG, List<ANGEDJODMKO> HBHMAKNGKFK, BBHNACPENDM LDEGEHAEALK, IAPIDHGIEED OMOEKOCNICP, IAPIDHGIEED ONNIHHLHLDP, PFIJNPCEOIL IFFKECJOPIB) { }

	// // RVA: 0x8FF5B8 Offset: 0x8FF5B8 VA: 0x8FF5B8
	// public void JNBKOAKJDAL(int HHGMPEEGFMA, int HMFFHLPNMPH, int IIGPLLECFND, int KJMLLBDLKCG, List<MFDJIFIIPJD> HBHMAKNGKFK, BBHNACPENDM LDEGEHAEALK, IAPIDHGIEED OMOEKOCNICP, IAPIDHGIEED ONNIHHLHLDP, PFIJNPCEOIL IFFKECJOPIB) { }

	// // RVA: 0x8FF734 Offset: 0x8FF734 VA: 0x8FF734
	// public void NNAPCDMAAJM(int BCCHOBPJJKE, int JPIPENJGGDD, int MMEIOJKLCKK, int PNMKPKMDOND, List<int> GFFAJFPIEKD, List<int> GHINHKOOBKI, int NEMMJLNMEHB, List<int> FHHIONFFABP) { }

	// // RVA: 0x900300 Offset: 0x900300 VA: 0x900300
	// public void JAHALBMOANH(int JJBGOIMEIPF, OAGBCBBHMPF.COIIJOEKBDH LHEIIHKDMPA, string NPBEKONLDDI, int ADPPAIPFHML, int FBAIDPHDEBA, int LIDBKCIMCKE) { }

	// // RVA: 0x900900 Offset: 0x900900 VA: 0x900900
	// public void OJOLFJGNEMO(int OLDAGCNLJOI_Progress, int DLAEJOBELBH_Id) { }

	// // RVA: 0x900DA8 Offset: 0x900DA8 VA: 0x900DA8
	// public void DBIDGHMFLIC(int AHHJLDLAPAN, int IGCLCOMCHHB, int IBKAENIBBIL, int DPJCPEIPAPN, int EKPGGDOOLFM) { }

	// // RVA: 0x9011B4 Offset: 0x9011B4 VA: 0x9011B4
	// public void CJCJNKOPIKB(int AHHJLDLAPAN, int IGCLCOMCHHB, int IBKAENIBBIL, int DPJCPEIPAPN, int EKPGGDOOLFM) { }

	// // RVA: 0x900DE0 Offset: 0x900DE0 VA: 0x900DE0
	// private void DBIDGHMFLIC(OAGBCBBHMPF.KJDNDEDOIOO INDDJNMPONH, int AHHJLDLAPAN, int IGCLCOMCHHB, int IBKAENIBBIL, int DPJCPEIPAPN, int EKPGGDOOLFM) { }

	// // RVA: 0x9011EC Offset: 0x9011EC VA: 0x9011EC
	// public void GCCAFBHKAEG(int JOMGCCBFKEF) { }

	// // RVA: 0x9016DC Offset: 0x9016DC VA: 0x9016DC
	// public void MOCDNABNBAO(int JOMGCCBFKEF) { }

	// // RVA: 0x901E50 Offset: 0x901E50 VA: 0x901E50
	// public void APAJMNOBNLL(IKDICBBFBMI MOHDLLIJELH, int JOMGCCBFKEF) { }

	// // RVA: 0x902248 Offset: 0x902248 VA: 0x902248
	// public void JHAPELNFEOM(int APFDNBGMMMM, int JOMGCCBFKEF, string FEMMDNIELFC) { }

	// // RVA: 0x9025E0 Offset: 0x9025E0 VA: 0x9025E0
	// public void EAEHILOBHDA(int DLAEJOBELBH_Id, string NEDBBJDAFBH) { }

	// // RVA: 0x9028C8 Offset: 0x9028C8 VA: 0x9028C8
	// public void AOPBBHMIEPB(int BMPFHHHCNJC) { }

	// // RVA: 0x902EF8 Offset: 0x902EF8 VA: 0x902EF8
	// public void MNFOJMBPHEN(int LJEONGIBHGM, int JOBJHJCIMDN, int ADKIDBJCAJA, int HLJBAHBLBPL, int DKHKDNNIPCA) { }

	// // RVA: 0x9036DC Offset: 0x9036DC VA: 0x9036DC
	// public void EEPIDKPPLJI(int AFNCFEMDJNP, int FDMAECAPKDF) { }

	// // RVA: 0x9039C4 Offset: 0x9039C4 VA: 0x9039C4
	// public void JOLBIMMKGIP(int JPNBLCBOCLN, int NAJPNHKHKKA, int HBNIMMAEKHJ, int JGGKJBCGKCC) { }

	// // RVA: 0x903D7C Offset: 0x903D7C VA: 0x903D7C
	// public void HGOGFPOCKFA(int JPNBLCBOCLN, int NAJPNHKHKKA, int HBNIMMAEKHJ) { }

	// // RVA: 0x904060 Offset: 0x904060 VA: 0x904060
	// public void BBDKHAMANCB(int GDEJFKCMNAC, int FCJLPINNDKN, int KJDKJGGHHIF, int LGADCGFMLLD, string DNKNECIGGMO, int FEGJGLAHEOI = 0, int KNKCLDMLGIH = 0) { }

	// // RVA: 0x904668 Offset: 0x904668 VA: 0x904668
	// public void AMBIOHGPBNH(string IPBHCLIHAPG, int ADPPAIPFHML) { }

	// // RVA: 0x904950 Offset: 0x904950 VA: 0x904950
	// public void PNMJDKOLGEG(int DMOAGOOHEND) { }

	// // RVA: 0x904954 Offset: 0x904954 VA: 0x904954
	// public void EBLJKIOEELA(int AHHJLDLAPAN, int CIEOBFIIPLD, int LKIFDCEKDCK) { }

	// // RVA: 0x904958 Offset: 0x904958 VA: 0x904958
	// public void PGHFPIMIOKE(int ICPDDMIBEIL, int MKNKJMFILFB) { }

	// // RVA: 0x904C40 Offset: 0x904C40 VA: 0x904C40
	// public void COBCMOAAAFF(int APGKOJKNNGP) { }

	// // RVA: 0x904EDC Offset: 0x904EDC VA: 0x904EDC
	// public void CMBKHLDBIEC(int DIPKCALNIII, string LDBIGOBMFMD, int CLKJBCJMILI) { }

	// // RVA: 0x905210 Offset: 0x905210 VA: 0x905210
	// public void FLBCPKHGLPE(int APJBBOHHFNE, int MKNKJMFILFB, int MNHBMILFDBG, int ECEKFEFOFNI, string JKJDGDLAIME) { }

	// // RVA: 0x905750 Offset: 0x905750 VA: 0x905750
	// public void MLNHHIIDJAO(MBLFHJJEHLH.CGBKENNCMMC PEPCJDIECJP) { }

	// // RVA: 0x905F20 Offset: 0x905F20 VA: 0x905F20
	// public void NNFGBBCHLPC(int PGIIDPEGGPI, string HEIPELEDAIK, long ICPDDMIBEIL, long MKNKJMFILFB, long DOOGFEGEKLG, bool CMIGGBMMBKK) { }

	// // RVA: 0x905F24 Offset: 0x905F24 VA: 0x905F24
	// public void GIBLHFKIMDA(IKDICBBFBMI MOHDLLIJELH) { }

	// // RVA: 0x906284 Offset: 0x906284 VA: 0x906284
	// public void GBABEMFLPBA(string MDADLCOCEBN, int CCHFKKINLHB, int DAOBEIMNFLH, MHAPMOLCPKM MOHDLLIJELH) { }

	// // RVA: 0x906660 Offset: 0x906660 VA: 0x906660
	// public void MFIIOABPKAO(string MDADLCOCEBN, MHAPMOLCPKM MOHDLLIJELH) { }

	// // RVA: 0x906DD8 Offset: 0x906DD8 VA: 0x906DD8
	// public void EPABCLLAJDP(string MDADLCOCEBN, MHAPMOLCPKM MOHDLLIJELH, int PFDFGDPLLCK) { }

	// // RVA: 0x907500 Offset: 0x907500 VA: 0x907500
	// public void LKOICKMAADB(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, MHAPMOLCPKM MOHDLLIJELH) { }

	// // RVA: 0x907FA4 Offset: 0x907FA4 VA: 0x907FA4
	// public void EEGOAEADLDP(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, MHAPMOLCPKM MOHDLLIJELH) { }

	// // RVA: 0x9089A4 Offset: 0x9089A4 VA: 0x9089A4
	// public void JMAJBHENDPF(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, IKDICBBFBMI MOHDLLIJELH) { }

	// // RVA: 0x908E44 Offset: 0x908E44 VA: 0x908E44
	// public void NJKBAICBOIN(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, IKDICBBFBMI MOHDLLIJELH) { }

	// // RVA: 0x90941C Offset: 0x90941C VA: 0x90941C
	// public string MECOCJPMMDO(HAEDCCLHEMN.DJJHCPAKJKJ BIGMHOMLMAG) { }

	// // RVA: 0x909B38 Offset: 0x909B38 VA: 0x909B38
	// public void HHGEPDNBGAI(HAEDCCLHEMN MOHDLLIJELH, int[] PAHGOCGBINJ, int[] BEGOPJOCMAF) { }

	// // RVA: 0x90A79C Offset: 0x90A79C VA: 0x90A79C
	// public void PMHLIBHEBBB(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, HAEDCCLHEMN MOHDLLIJELH) { }

	// // RVA: 0x90AC64 Offset: 0x90AC64 VA: 0x90AC64
	// public void FEIOPIIEIKB(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, HAEDCCLHEMN MOHDLLIJELH) { }

	// // RVA: 0x90BF58 Offset: 0x90BF58 VA: 0x90BF58
	// public void EAGAKGNNINL(int OPKCNBFBBKP, string OPFGFINHFCE, string HJLDBEJOMIO) { }

	// // RVA: 0x907BF4 Offset: 0x907BF4 VA: 0x907BF4
	// private void HADLOAPLCAF(EDOHBJAPLPF_JsonData IDLHJIOMJBK, JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, IKDICBBFBMI MOHDLLIJELH) { }

	// // RVA: 0x90C240 Offset: 0x90C240 VA: 0x90C240
	public void NJEIHFPKOMG(int HBODCMLFDOB, int EJJNDLJIIIF, string EFBLONMFDCB)
	{
		EDOHBJAPLPF_JsonData json = new EDOHBJAPLPF_JsonData();
		FLBFCCIEPNC(json, JDDGPJDKHNE.HHCJCDFCLOB.KPKAKIIAFFB());
		json["result"] = HBODCMLFDOB;
		json["error_code"] = EJJNDLJIIIF;
		json["parse_result"] = EFBLONMFDCB;
		json["system_memory_size"] = SystemInfo.systemMemorySize;
		json["graphic_device_name"] = SystemInfo.graphicsDeviceName;
		json["processor_type"] = SystemInfo.processorType;
		DEGEPBNNOAF(OAGBCBBHMPF.KJDNDEDOIOO.NJEIHFPKOMG/*36*/, json, false);
	}

	// // RVA: 0x90C664 Offset: 0x90C664 VA: 0x90C664
	// public void EEOLHMGNJGO(int JGJPKLCCOIO, int OBLKLLDGOEJ, int MJBODMOLOBC, int GLCLFMGPMAN, int LJKMKCOAICL, int PFDFGDPLLCK, int EDKMIKFEEJI, int LCKLPIDPDIE) { }

	// // RVA: 0x90CBA4 Offset: 0x90CBA4 VA: 0x90CBA4
	// public void JNHOIANJAOP(KPJHLACKGJF MOHDLLIJELH) { }

	// // RVA: 0x90D72C Offset: 0x90D72C VA: 0x90D72C
	// public void HPFKEJGCDKN(KPJHLACKGJF MOHDLLIJELH) { }

	// // RVA: 0x90DADC Offset: 0x90DADC VA: 0x90DADC
	// public void FJIGNIDBFMM(KPJHLACKGJF MOHDLLIJELH) { }

	// // RVA: 0x90DFBC Offset: 0x90DFBC VA: 0x90DFBC
	// public void NIPOGLOEMCN(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, KPJHLACKGJF MOHDLLIJELH) { }

	// // RVA: 0x90E690 Offset: 0x90E690 VA: 0x90E690
	// public void FEMJIFOMOCL(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, KPJHLACKGJF MOHDLLIJELH) { }

	// // RVA: 0x90F0FC Offset: 0x90F0FC VA: 0x90F0FC
	// public void IENGPDCDMBM(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int JPLMIPNGKEA, int AIMGOGFLILF) { }

	// // RVA: 0x910540 Offset: 0x910540 VA: 0x910540
	// public void GDHNBIIOKMF(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN) { }

	// // RVA: 0x910ECC Offset: 0x910ECC VA: 0x910ECC
	// public void GADJDBJLIGC(int LKNCHJCLLFN, string OJBLOEBPHIE, string GGPGIALKGFG) { }

	// // RVA: 0x911200 Offset: 0x911200 VA: 0x911200
	// public void DBNECDJCNOI(int DLLJMINACDN, string GEGCFOCMEKD, int FNNGLNPIKOL, int DJJGPACGEMM, int IPJBPBDCCPF, int HABCGPMKBJK, int PEKOLGMLJAL, int BGHCIAOANCF, int GJNAOBBAPOF, int FFBPGKHIKGD, int KMFLNILNPJD, int JPLLMKIDNBM, int HMFDJHEEGNN, long DECPPKAAHFA, int NFBLLKHBMEK, string DJPBDDBNMLN) { }

	// // RVA: 0x911BA4 Offset: 0x911BA4 VA: 0x911BA4
	// public void CBKENDJIBDM(string JKJDGDLAIME, int LKNCHJCLLFN, int KAAENFOCPLN, int[] OCJACPIJCBL, int[] POEMOGPOGPN, int BBNEDFIJFEN, int GGPDPDMODPL, int[] KJEHAHAKGDE, int[] OKIMFNNDGGP, int FEFHFFGBOEM) { }

	// // RVA: 0x91251C Offset: 0x91251C VA: 0x91251C
	// public void LIPHGGFEJFJ(int IMMDGJAOPCD, int HMFFHLPNMPH, int EIILNOEOICO, int COJALPJKKDL, int JGGKJBCGKCC, int KJMLLBDLKCG, int GDAGHLJDKGK, CHHECNJBMLA MOHDLLIJELH) { }

	// // RVA: 0x912DAC Offset: 0x912DAC VA: 0x912DAC
	// public void LCDPEMIFNKJ(int GLCLFMGPMAN, int MBJIFDBEDAC) { }

	// // RVA: 0x913094 Offset: 0x913094 VA: 0x913094
	// public void ICAHGJMMGLM(string KMDDJIEPNMF) { }

	// // RVA: 0x913330 Offset: 0x913330 VA: 0x913330
	// public void BGJDJBOCLEA(string KMDDJIEPNMF, int HBODCMLFDOB, string OHLHAIIBLBI) { }

	// // RVA: 0x913664 Offset: 0x913664 VA: 0x913664
	// public void ILLBGAFIBDE(string KMDDJIEPNMF, int FJABGCFCPMH, string INAMDCCEBOH, string FNOBKBIFBJG, bool NDODFAPMMEB) { }

	// // RVA: 0x913A60 Offset: 0x913A60 VA: 0x913A60
	// public void KIFPDEFNEPB(string KMDDJIEPNMF, int FJABGCFCPMH, string INAMDCCEBOH, string FNOBKBIFBJG) { }

	// // RVA: 0x913DE0 Offset: 0x913DE0 VA: 0x913DE0
	// public void PHLHLIDCNNN(string KMDDJIEPNMF, int FJABGCFCPMH, string INAMDCCEBOH, string FNOBKBIFBJG) { }

	// // RVA: 0x914160 Offset: 0x914160 VA: 0x914160
	// public void DNNLEIKNHKL(int DIPKCALNIII, int NHCCINMHEAB, int GOKMANFHFPC, int HHAMIAPINGE, int MJKGDEOKFNK, int NCMCPNPOLEB, string JKJDGDLAIME, int CMJHOGBIOKM, int ADIFCNPMKJH, int DMMKFOLEGKO, int PMJKECBJBGP) { }

	// // RVA: 0x914720 Offset: 0x914720 VA: 0x914720
	// public void CDNFJBAJAMM(CANAFALMGLI MOHDLLIJELH, int JBEFLJENKAC) { }

	// // RVA: 0x914ABC Offset: 0x914ABC VA: 0x914ABC
	// public void BLDDKDNOCFA(CANAFALMGLI MOHDLLIJELH, string EBAMGNMELPO, string HBODCMLFDOB) { }

	// // RVA: 0x914E50 Offset: 0x914E50 VA: 0x914E50
	// public void DADNPOJNIBL(IKDICBBFBMI MOHDLLIJELH) { }

	// // RVA: 0x91514C Offset: 0x91514C VA: 0x91514C
	// public void LIIJEGOIKDP(int FMJECOKINMO, OAGBCBBHMPF.DKAMMIHBINF JKJDGDLAIME) { }

	// // RVA: 0x9154B4 Offset: 0x9154B4 VA: 0x9154B4
	// public void BKLNHBHDDEJ(string INDDJNMPONH) { }

	// // RVA: 0x915750 Offset: 0x915750 VA: 0x915750
	// public void DAGHKCKEJPA(BOPFPIHGJMD.MLBMHDCCGHI ODMEBOKPNAF, int AAKPLIFKIJK) { }

	// // RVA: 0x915A38 Offset: 0x915A38 VA: 0x915A38
	// public void OEGCKACJMPM(BOPFPIHGJMD.MLBMHDCCGHI ODMEBOKPNAF, int AAKPLIFKIJK) { }

	// // RVA: 0x9162E0 Offset: 0x9162E0 VA: 0x9162E0
	// public void ONPIDKLOPIP(BOPFPIHGJMD.MLBMHDCCGHI ODMEBOKPNAF, int AAKPLIFKIJK, int KMPBAKBKEGH) { }

	// // RVA: 0x916A08 Offset: 0x916A08 VA: 0x916A08
	// public void BABLKKLEPGD(int BEEAIAAJOHD, int MMEIOJKLCKK, int PNMKPKMDOND, int FCJLPINNDKN, int KJDKJGGHHIF, int GLCLFMGPMAN, int CLLKANEGGBJ, int NEMMJLNMEHB) { }

	// // RVA: 0x916F48 Offset: 0x916F48 VA: 0x916F48
	// public void PLEKHHPMELF(int GOIKCKHMBDL, int JGGKJBCGKCC, int MKNKJMFILFB) { }

	// // RVA: 0x91727C Offset: 0x91727C VA: 0x91727C
	// public void LPKDNOINDPE(long CBJBEGPLJDO, long LPHAOMAKKNF, long FDAEDIPOONF, long PCHNPJFFJJM, long CPFDDHIEODD, long LCNMPBBDGPJ, long BMHKJPHNCIJ, long KMJCPOGCJDG, long PPKCOLEJLLG, long BGOLKLJBAHD, OAGBCBBHMPF.NALHDBIKFJO GAFIOALKHIM, OAGBCBBHMPF.NALHDBIKFJO PMKOEGJAEDN, string EEMFGMEEBDC, string NJFKGJKINAG, int IHJMMPHPHEM, string EJJNDLJIIIF) { }

	// // RVA: 0x917AB4 Offset: 0x917AB4 VA: 0x917AB4
	// public void FJBCAHAFLNO() { }

	// // RVA: 0x917CD8 Offset: 0x917CD8 VA: 0x917CD8
	// public void FDFMKBGPALI(BOPFPIHGJMD.MLBMHDCCGHI ODMEBOKPNAF, int AAKPLIFKIJK, int GLCLFMGPMAN, int CLLKANEGGBJ, int PJIOJCFCFOK, int BIKHKIGMEMA) { }

	// // RVA: 0x9181C4 Offset: 0x9181C4 VA: 0x9181C4
	// public void PHCLHGPCFNL(NKOBMDPHNGP MOHDLLIJELH, int OIDBPKAKOJA, int MEBHCFJCKFE, string FMGBPEHHJEA, int CJHEHIMLGGL, int AHGJCJFOMIP, string AMMJLEOFFDO) { }

	// // RVA: 0x918694 Offset: 0x918694 VA: 0x918694
	// public void NJMBKGKPCKL() { }

	// // RVA: 0x918698 Offset: 0x918698 VA: 0x918698
	// public void PEBDGCDNPDM(NKOBMDPHNGP MOHDLLIJELH, string INDDJNMPONH) { }

	// // RVA: 0x9189E0 Offset: 0x9189E0 VA: 0x9189E0
	// public void LHCHBHPHLCP() { }

	// // RVA: 0x9189E4 Offset: 0x9189E4 VA: 0x9189E4
	// public void OOBKCHBNAOF() { }

	// // RVA: 0x9189E8 Offset: 0x9189E8 VA: 0x9189E8
	// private void HBOONEFDMJL(EDOHBJAPLPF_JsonData IDLHJIOMJBK, PKNOKJNLPOE.MJFMOPMOFDJ GJFJLEOGFLD) { }

	// // RVA: 0x919268 Offset: 0x919268 VA: 0x919268
	// public void LOGBJCFCJND(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, PKNOKJNLPOE MOHDLLIJELH) { }

	// // RVA: 0x919FE4 Offset: 0x919FE4 VA: 0x919FE4
	// public void FIPDFLHPNDO(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, PKNOKJNLPOE MOHDLLIJELH) { }

	// // RVA: 0x91A6B0 Offset: 0x91A6B0 VA: 0x91A6B0
	// public void KCCMKAEPGPE(PKNOKJNLPOE MOHDLLIJELH, int JGGKJBCGKCC, int KJMLLBDLKCG, int NMANGFCHCFB) { }

	// // RVA: 0x91ABC4 Offset: 0x91ABC4 VA: 0x91ABC4
	// public void ONMOONKHHLO(PKNOKJNLPOE MOHDLLIJELH, PKNOKJNLPOE.MJFMOPMOFDJ GJFJLEOGFLD) { }

	// // RVA: 0x91B040 Offset: 0x91B040 VA: 0x91B040
	// public void BACAKFPEMAF(PKNOKJNLPOE MOHDLLIJELH, bool PJJLOFMLOMN, bool MCMPOEHAIHP, List<PKNOKJNLPOE.ECICDAPCMJG> MOCDACANBIG) { }

	// // RVA: 0x91B758 Offset: 0x91B758 VA: 0x91B758
	// public void ICDCMLKMEHI(int APJBBOHHFNE, int MKNKJMFILFB, int GLCLFMGPMAN, int ECEKFEFOFNI, string JKJDGDLAIME) { }

	// // RVA: 0x91BB28 Offset: 0x91BB28 VA: 0x91BB28
	// public void EEHEMNBJPAP(PKNOKJNLPOE MOHDLLIJELH, JLOGEHCIBEJ.JJAFLOEBLDH CFLEMFADGLG, int AFFGGBLNPFJ, int EENFAGBJHPP, SakashoRaidbossEffectData NKDGDKKEPOO, JPPCMHKHAGC.ODNJNIICCLB HFBEDHKIBJA, string MDADLCOCEBN) { }

	// // RVA: 0x91C368 Offset: 0x91C368 VA: 0x91C368
	// public void HONFKODFAPA(PKNOKJNLPOE MOHDLLIJELH, PKNOKJNLPOE.MJFMOPMOFDJ GJFJLEOGFLD, PKNOKJNLPOE.KJJDLBFDGDM KONJMFICNJJ) { }

	// // RVA: 0x91CF90 Offset: 0x91CF90 VA: 0x91CF90
	// public void DNJGGCJPIMC(JGEOBNENMAH.EDHCNKBMLGI OMNOFMEBLAD, string MDADLCOCEBN, int KALCJMLIAOK, int CBHACAOCJGP, MANPIONIGNO MOHDLLIJELH) { }

	// // RVA: 0x91D638 Offset: 0x91D638 VA: 0x91D638
	// public void HPNIJDCPCNC(CPHJGFLEFNF IJAOGPFKDBP, JGEOBNENMAH.HAJIFNABIFF OMNOFMEBLAD, string MDADLCOCEBN, MANPIONIGNO MOHDLLIJELH) { }

	// // RVA: 0x91E404 Offset: 0x91E404 VA: 0x91E404
	// public void HJGEAHELBPE(MANPIONIGNO MOHDLLIJELH, int GLCLFMGPMAN, int ECEKFEFOFNI, int NLIMHCILPFE) { }

	// // RVA: 0x91E7E4 Offset: 0x91E7E4 VA: 0x91E7E4
	// public void DAHHMMNABFI() { }

	// // RVA: 0x91E7E8 Offset: 0x91E7E8 VA: 0x91E7E8
	// public void NBBGDNAHAGH() { }

	// // RVA: 0x91E7EC Offset: 0x91E7EC VA: 0x91E7EC
	// public void FJIPPAPEBID(int IPJBPBDCCPF, int HABCGPMKBJK, int PEKOLGMLJAL, int BGHCIAOANCF, int GJNAOBBAPOF, int FFBPGKHIKGD, int KMFLNILNPJD, int JPLLMKIDNBM, int HMFDJHEEGNN, long DECPPKAAHFA) { }

	// // RVA: 0x91F36C Offset: 0x91F36C VA: 0x91F36C
	// public void HEKBPBPLPJL(int NPMIJMFMEKB, int BEPIOAIFCEC) { }

	// // RVA: 0x91F708 Offset: 0x91F708 VA: 0x91F708
	// public void CLGHLKLHEAK(string INDDJNMPONH, int HHFIMKIKJBC) { }

	// // RVA: 0x91F9A4 Offset: 0x91F9A4 VA: 0x91F9A4
	// public void PFBIHCIFFKM(int HHFIMKIKJBC, bool MLEHCBKPNGK, bool FMNNBGOFBPB, int GLCLFMGPMAN = 0) { }

	// // RVA: 0x91FD94 Offset: 0x91FD94 VA: 0x91FD94
	// public void CEFIPAIKAKN(List<int> GMFMGJNPNKA, List<int> GNGFCCBHLPO) { }

	// // RVA: 0x920200 Offset: 0x920200 VA: 0x920200
	// public void JCJCJPCHNEN(int NPMIJMFMEKB, int BEPIOAIFCEC, int MFOCDHGOODC, bool MLEHCBKPNGK) { }

	// // RVA: 0x920614 Offset: 0x920614 VA: 0x920614
	// public void LHCHBHPHLCP(int AOPIMHHPPMG) { }

	// // RVA: 0x9208B0 Offset: 0x9208B0 VA: 0x9208B0
	// public void MIDMMEHCCFA(int NJHLKOFIDJN, int OLCAOJEHGMO, bool GNKGNCLBKLB) { }

	// // RVA: 0x920C1C Offset: 0x920C1C VA: 0x920C1C
	// public void AGFMBNBIHGB(int NJHLKOFIDJN, KDKFHGHGFEK DJKKEABCKLH, Vector3 NDFOAINJPIN) { }

	// // RVA: 0x920C90 Offset: 0x920C90 VA: 0x920C90
	// public void KBKIDKDDOJN(int NJHLKOFIDJN, int GOPGOJDEPML) { }

	// // RVA: 0x920D30 Offset: 0x920D30 VA: 0x920D30
	// public void EPINKLEJAGD(int NJHLKOFIDJN, KDKFHGHGFEK DJKKEABCKLH, Vector3 NDFOAINJPIN) { }

	// // RVA: 0x920DA4 Offset: 0x920DA4 VA: 0x920DA4
	// public void INHBHAMMBEH(int NJHLKOFIDJN, int GOPGOJDEPML) { }

	// // RVA: 0x920E44 Offset: 0x920E44 VA: 0x920E44
	// public void NOMCHDMPFFE(int DDCKAKGKCIB, int CJAGGLPJOMD, int JPNCPIINMPC) { }

	// // RVA: 0x921178 Offset: 0x921178 VA: 0x921178
	// public void CHMEOKEKABD(IECJNEHIEKO ADKIDBJCAJA) { }

	// // RVA: 0x92172C Offset: 0x92172C VA: 0x92172C
	// public void ELDCONNMDGN(int FODKKJIDDKN, int MJKGDEOKFNK, int NCMCPNPOLEB, int MPIJPMELIDO, int NHPFGLJJMJJ, int IKBIIBDNNAL, int LHDHBPOLEGB) { }

	// // RVA: 0x921C2C Offset: 0x921C2C VA: 0x921C2C
	// public void MINOEGPNBIH(int IJIEMJFAJKL, int GGJLPODCHIO, int JGGKJBCGKCC, int PJIOJCFCFOK, string INDDJNMPONH, string GNOOPLDMLBE) { }

	// // RVA: 0x92204C Offset: 0x92204C VA: 0x92204C
	// public void OMLMHKGCJPH(int IKPIDCFOFEA, string ADKIDBJCAJA, int FDGBLNFGBPJ, int HPPHKHBPFMJ) { }

	// // RVA: 0x9223CC Offset: 0x9223CC VA: 0x9223CC
	// public void HNOKBPNGOEF() { }

	// // RVA: 0x9225F0 Offset: 0x9225F0 VA: 0x9225F0
	// public void BOIIMIEPMLG(string INDDJNMPONH, int PPFNGGCBJKC, string KIFBPEGOEDL) { }

	// // RVA: 0x9225F4 Offset: 0x9225F4 VA: 0x9225F4
	// public void NBCACPPAAMC(int CHCPNKMNDOP, int KBMAMKCAIGD, int IGCLCOMCHHB, int IBKAENIBBIL, int DPJCPEIPAPN, int EKPGGDOOLFM) { }

	// // RVA: 0x922A14 Offset: 0x922A14 VA: 0x922A14
	// public void BBIBBNHCPPJ(int LKFPHAIMKMA, int HGBMBIBAEGG, int JBOMAOOPGAA, int HPBLCCLGFHH, int AICIPAHGLOE, int FOILMFGFFNH, int DLDODLGIOMC, int CNKFPJCGNFE, int EEJFLMKCCGN) { }
}
