
public class JBHCLFDBPKP // TypeDefIndex: 9600
{
	public string OPFGFINHFCE; // 0x8
	public IKMBBPDBECA KACECFNECON; // 0xC
	//public List<OEJEEHMMPBK> BMFEGOMNECF; // 0x10

	// RVA: 0x1420D2C Offset: 0x1420D2C VA: 0x1420D2C
	//public void KHEKNNFCAOI(EDOHBJAPLPF IDLHJIOMJBK, bool ENDFGMBBBEE) { }
}
