
public class JGIHJPPECBB
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int BEBJKJKBOGH { get; set; } // 0x10 MCIJNMKFMDB DIAPHCJBPFD IHAIKPNEEJE
	public int IJEKNCDIIAE { get; set; } // 0x14 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
