
using System.Collections.Generic;

public class JKNGJFOBADP
{
	public class GPPAIFNBHDP
	{
		public int BCCHOBPJJKE_SceneId; // 0x8
		public int INDDJNMPONH; // 0xC
		public int JKGFBFPIMGA_BaseRarity; // 0x10
		public int MPGNHFDGOBO_PrevRarity; // 0x14
		public int HNNAODKJGPD_NextRarity; // 0x18
		public int JPIPENJGGDD_NumBoard; // 0x1C
		public int FELBNCPBGMJ; // 0x20
		public int OCMIGHELJDP; // 0x24
		public bool OGPKHGEMLMP; // 0x28
		public bool OLGCDLJFMDH_Sngl; // 0x29
	}

	public class OILCOECKMOO
	{
		public int KELFCMEOPPM_Ep; // 0x8
		public int DNBFMLBNAEE; // 0xC
	}

	public int CIKCPLCPKAO; // 0x8
	public int PJIPCABDHCI; // 0xC
	public List<int> HAPENODDGOC = new List<int>(27); // 0x10
	public List<int> JLCNBOKABJL = new List<int>(3); // 0x14
	public int INOAGFJHBBH; // 0x18
	public int LNOEDPPJAHC; // 0x1C
	public int JIDELBDMKJM; // 0x20
	public long HHOBAFKAKJK; // 0x28
	public bool MPHIICNDGDH; // 0x30
	public int EPPFEAIMFOE_ItemCount; // 0x34
	public List<int> PPBHHLGPMBK = new List<int>(3); // 0x38
	public List<int> IONINNDIAFO = new List<int>(3); // 0x3C
	public int JNEMAOPELPE; // 0x40
	public int CNONCDLNIED; // 0x44
	public int HLEMBNOMOGM; // 0x48
	public int IKBLCEFCGDE; // 0x4C
	public int PJBJCBEMEEC; // 0x50
	public int OBCINIPHGGH; // 0x54
	public int IECOFJEJNON; // 0x58
	public int IHIJFEHOBOB; // 0x5C
	public int AAIAJEGOIHL; // 0x60
	public EKLNMHFCAOI.FKGCBLHOOCL_Category KJOGOABBMNN; // 0x64
	public bool OMGJFMMJPJD; // 0x65
	public List<MFDJIFIIPJD> HBHMAKNGKFK_Items = new List<MFDJIFIIPJD>(100); // 0x68
	public List<GPPAIFNBHDP> FIGHNFKAMGI = new List<GPPAIFNBHDP>(); // 0x6C
	public List<int> NNDMIOEKKMM = new List<int>(); // 0x70
	public List<OILCOECKMOO> FJKAMPIMFLP = new List<OILCOECKMOO>(); // 0x74
	public OAGBCBBHMPF.COIIJOEKBDH LHEIIHKDMPA; // 0x78
	public string NPBEKONLDDI = ""; // 0x7C

	//// RVA: 0x1469C68 Offset: 0x1469C68 VA: 0x1469C68
	public void FEGDNPIEKJC(OAGBCBBHMPF.COIIJOEKBDH EILCNJNKDAI, string PPFNGGCBJKC)
	{
		LHEIIHKDMPA = EILCNJNKDAI;
		NPBEKONLDDI = PPFNGGCBJKC;
	}

	//// RVA: 0x1469C78 Offset: 0x1469C78 VA: 0x1469C78
	public void NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category INDDJNMPONH, int MHFBCINOJEE, int ADPPAIPFHML, int FBAIDPHDEBA, int LIDBKCIMCKE)
	{
		ILCCJNDFFOB.HHCJCDFCLOB.JAHALBMOANH(EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(INDDJNMPONH, MHFBCINOJEE), LHEIIHKDMPA, NPBEKONLDDI, ADPPAIPFHML, FBAIDPHDEBA, LIDBKCIMCKE);
	}

	//// RVA: 0x1469D94 Offset: 0x1469D94 VA: 0x1469D94
	public void JCHLONCMPAJ()
	{
		CIKCPLCPKAO = 0;
		PJIPCABDHCI = 0;
		HAPENODDGOC.Clear();
		for(int i = 0; i < 27; i++)
		{
			HAPENODDGOC.Add(0);
		}
		JLCNBOKABJL.Clear();
		for (int i = 0; i < 3; i++)
		{
			JLCNBOKABJL.Add(0);
		}
		HHOBAFKAKJK = 0;
		INOAGFJHBBH = 0;
		LNOEDPPJAHC = 0;
		JIDELBDMKJM = 0;
		MPHIICNDGDH = false;
		EPPFEAIMFOE_ItemCount = 0;
		JNEMAOPELPE = 0;
		CNONCDLNIED = 0;
		IONINNDIAFO.Clear();
		PPBHHLGPMBK.Clear();
		for (int i = 0; i < 3; i++)
		{
			IONINNDIAFO.Add(0);
			PPBHHLGPMBK.Add(0);
		}
		IECOFJEJNON = 0;
		HLEMBNOMOGM = 0;
		IKBLCEFCGDE = 0;
		PJBJCBEMEEC = 0;
		OBCINIPHGGH = 0;
		HBHMAKNGKFK_Items.Clear();
		FIGHNFKAMGI.Clear();
		NNDMIOEKKMM.Clear();
		FJKAMPIMFLP.Clear();
		OMGJFMMJPJD = false;
	}

	//// RVA: 0x146A074 Offset: 0x146A074 VA: 0x146A074
	public void CPIICACGNBH_AddItem(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int KIJAPOFAGPN, int HMFFHLPNMPH, OOOOCFAFGCP KACECFNECON, int ONMCOJPNBAO = 0)
	{
		CPIICACGNBH(AHEFHIMGIBI, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(KIJAPOFAGPN), EKLNMHFCAOI.DEACAHNLMNI_getItemId(KIJAPOFAGPN), HMFFHLPNMPH, KACECFNECON, ONMCOJPNBAO);
	}

	//// RVA: 0x146A140 Offset: 0x146A140 VA: 0x146A140
	public void CPIICACGNBH(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category HHACNFODNEF, int MHFBCINOJEE, int HMFFHLPNMPH, OOOOCFAFGCP KACECFNECON, int ONMCOJPNBAO = 0)
	{
		EPPFEAIMFOE_ItemCount++;
		MFDJIFIIPJD data = new MFDJIFIIPJD();
		data.KHEKNNFCAOI(HHACNFODNEF, MHFBCINOJEE, HMFFHLPNMPH);
		data.KACECFNECON = KACECFNECON;
		HBHMAKNGKFK_Items.Add(data);
		IHIJFEHOBOB = MHFBCINOJEE;
		AAIAJEGOIHL = HMFFHLPNMPH;
		KJOGOABBMNN = HHACNFODNEF;
		switch(HHACNFODNEF)
		{
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJDEOPMBGKJ_PaidVC:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OBHECJMAEIO_GachaTicket:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IBBDMIFICCN_BonusVC:
				NGEPPDAOIBN(HHACNFODNEF, MHFBCINOJEE, HMFFHLPNMPH, 0, 0);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit:
				BOBHHEOBAJF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene:
				IKFHPLBCMHN(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH, ONMCOJPNBAO);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_Costume:
				DPFKEPHOBKL(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_Valkyrie:
				GAFDHKHLNBA(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem:
				ICHGJENIAMF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem:
				GFNNJKJGEGA(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MNCJMDDAFJB_EmblemItem:
				HPBIMHODDAP(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.EMOLGEDEEJP_EventItem:
				KNBGNFDFEON(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket:
				CHKDGBJDBEF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GIMBFBNKPNO_CompoItem:
				PKEBBIAIHEK(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KNHFAHFCCBK_SnsItem:
				OAOJFIOACEL(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem:
				PGMIPBPEDDD(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket:
				NFDOJPCKFAK(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal:
				JNABIIIMOPE(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.LLFAAOHPMIC_EventGachaTicket:
				IFDDILLJLFO(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem:
				LCIPJMMEMPI(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem:
				IAFODMHCKNH(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem:
				NKJHEGBDMHJ(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem:
				EALJGONPDJD(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_LimitedItem:
				NGIHAOOFEPG(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem:
				NOGNCLIGIMG(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GPMKJNDHDCP_DecoItemBg:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OKPAJOALDCG_DecoItemObj:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MCKHJLHKMJD_DecoItemChara:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ICIMCGOJEMD_StampItemSerif:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.BMMBLLOKNPF_DecoItemSp:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OOMMOOIIPJE_DecoItemPoster:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GGEFMAAOMFH_StampItemChara:
				FLFGJFDBEAB(AHEFHIMGIBI, HHACNFODNEF, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem:
				IJGFIAGIINJ(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CFLFPPDMFAE_RaidItem:
				ACODICAMEGB(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem:
				PCJFOILKCOP(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem:
				JHDCJPEPDIC(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg:
				DBHOKBOGDNB(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
				break;
		}
	}

	//// RVA: 0x146FF9C Offset: 0x146FF9C VA: 0x146FF9C
	public bool HMDCGPGGOBA_IsAddItemOverflow(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category HHACNFODNEF, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		switch(HHACNFODNEF)
		{
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit:
				return PBOGGAGPECG(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_Costume:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_Valkyrie:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg:
				return true;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem:
				return ALBIIKAIILG(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem:
				return BKLKPGCDMBE(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket:
				return KMNEKFLHAMN(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GIMBFBNKPNO_CompoItem:
				return FODKDOCADJI(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem:
				return LDCIPFEAOAD(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket:
				return MFNLHPELAOF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal:
				return EJPHHJFMAPE(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.LLFAAOHPMIC_EventGachaTicket:
				return EJKKIHJDOKF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem:
				return POCBGCBPBGD(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem:
				return EBFPNOMLJCN(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem:
				return EHMCNIGGPNO(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem:
				return GJGFKFFPLAB(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_LimitedItem:
				return PIHDONDGHMH(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem:
				return DAHPCLHIAKP(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem:
				return OHNDBOLGLFF(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CFLFPPDMFAE_RaidItem:
				return BGBJMNELGLC(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem:
				return BDFAHPBDGPJ(AHEFHIMGIBI, MHFBCINOJEE, HMFFHLPNMPH);
		}
		return false;
	}

	//// RVA: 0x1471CE0 Offset: 0x1471CE0 VA: 0x1471CE0
	//private void NNJGNMFMAKN(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x1471CE4 Offset: 0x1471CE4 VA: 0x1471CE4
	//private bool GHJAHGPACPI(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146A5DC Offset: 0x146A5DC VA: 0x146A5DC
	private void BOBHHEOBAJF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		int idx = 0;
		if (MHFBCINOJEE - 1 > 0)
			idx = MHFBCINOJEE - 1;
		int a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NMJEDFNPIPL_UcItem.CDENCMNHNGA[idx].JBGEEPFKIGG_Val;
		a *= HMFFHLPNMPH;
		if (a + AHEFHIMGIBI.KCCLEHLLOFG_Common.NFHLDFJIBKI_HaveUc > 99999999)
			MPHIICNDGDH = true;
		AHEFHIMGIBI.KCCLEHLLOFG_Common.ENEMPFLFEHP_AddUc(a);
		CIKCPLCPKAO += a;
		AHEFHIMGIBI.OEKEIGFAIGN_Counter.BDLNMOIOMHK_Total.EJJAPFPJLHP_AddUc(a);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit, idx + 1, a, AHEFHIMGIBI.KCCLEHLLOFG_Common.NFHLDFJIBKI_HaveUc, 0);
	}

	//// RVA: 0x1470158 Offset: 0x1470158 VA: 0x1470158
	private bool PBOGGAGPECG(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if (MHFBCINOJEE > 0)
			MHFBCINOJEE--;
		DGDIEDDPNNG_UcItem.FCPCMPLGJNP dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NMJEDFNPIPL_UcItem.CDENCMNHNGA[MHFBCINOJEE];
		return AHEFHIMGIBI.KCCLEHLLOFG_Common.NFHLDFJIBKI_HaveUc + dbItem.JBGEEPFKIGG_Val * HMFFHLPNMPH > 99999999;
	}

	//// RVA: 0x146A878 Offset: 0x146A878 VA: 0x146A878
	private void IKFHPLBCMHN(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH, int ONMCOJPNBAO = 0)
	{
		MLIBEPGADJH_Scene.KKLDOOJBJMN dbScene = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.CDENCMNHNGA_SceneList[MHFBCINOJEE - 1];
        MMPBPOIFDAF_Scene.PMKOFEIONEG saveScene = AHEFHIMGIBI.PNLOINMCCKH_Scene.OPIBAPEGCLA[MHFBCINOJEE - 1];
		int rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE);
		int mlt = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.HNMMJINNHII_Game.GENHLFPKOEE(rarity, dbScene.MCCIFLKCNKO_Feed);
		HLEMBNOMOGM = 0;
		IKBLCEFCGDE = 0;
		PJBJCBEMEEC = 0;
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		if(!saveScene.OFNNNEMCJNN())
		{
			if(dbScene.KELFCMEOPPM_Ep != 0)
			{
				bool b = false;
				for(int i = 0; i < FJKAMPIMFLP.Count; i++)
				{
					b |= FJKAMPIMFLP[i].KELFCMEOPPM_Ep == dbScene.KELFCMEOPPM_Ep;
				}
				if(!b)
				{
					OILCOECKMOO data = new OILCOECKMOO();
					data.KELFCMEOPPM_Ep = dbScene.KELFCMEOPPM_Ep;
					data.DNBFMLBNAEE = PIGBBNDPPJC.GMDHJBGLBEI(dbScene.KELFCMEOPPM_Ep, AHEFHIMGIBI);
					FJKAMPIMFLP.Add(data);
				}
				OCLHKHAMDHF_Episode.JEHNEEBBDBO_EpisodeInfo saveEp = AHEFHIMGIBI.NGHJPEIKLJL_Episode.BBAJKJPKOHD_EpisodeList[dbScene.KELFCMEOPPM_Ep - 1];
				if(saveEp.BEBJKJKBOGH_Date == 0)
				{
					NNDMIOEKKMM.Add(dbScene.KELFCMEOPPM_Ep);
					saveEp.LHMOAJAIJCO_IsNew = true;
					saveEp.BEBJKJKBOGH_Date = time;
				}
			}
			bool b2 = AHEFHIMGIBI.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture);
			int maxPoster = 50;
			if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database != null && 
				IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem != null)
			{
				maxPoster = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.LPJLEHAJADA("poster_have_max", 50);
			}
			for(int i = 0; i < HMFFHLPNMPH; i++)
			{
				HLEMBNOMOGM = MHFBCINOJEE;
				PJIPCABDHCI++;
				bool b3 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.FDIOFBGJKNO(MHFBCINOJEE) && b2;
				if(b3)
				{
					int e = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.KBEGPJEBFMA(MHFBCINOJEE);
					if(AHEFHIMGIBI.KCCLEHLLOFG_Common.FCBBIEPBDBA(e))
					{
						AHEFHIMGIBI.KCCLEHLLOFG_Common.HHCMHDKKFNF_SetPstVer(e);
					}
				}
				if(!saveScene.IHIAFIHAAPO_Unlocked)
				{
					if(!dbScene.FBJDHLGODPP_Sngl)
					{
						saveScene.DDLEICINOHK_Unlock(time, ONMCOJPNBAO);
						IKBLCEFCGDE = 0;
						PJBJCBEMEEC = 0;
						GPPAIFNBHDP data = new GPPAIFNBHDP();
						data.BCCHOBPJJKE_SceneId = MHFBCINOJEE;
						data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
						data.INDDJNMPONH = 1;
						data.JKGFBFPIMGA_BaseRarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_BaseRarity;
						data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_BaseRarity;
						data.OGPKHGEMLMP = b3;
						FIGHNFKAMGI.Add(data);
						//joined_r0x0146b3fc;
						if(b3)
						{
							//LAB_0146b66c
							saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_Mlt);
						}
					}
					else
					{
						saveScene.DJNPIJPHKKJ(time, ONMCOJPNBAO);
						IKBLCEFCGDE = 0;
						GPPAIFNBHDP data = new GPPAIFNBHDP();
						data.BCCHOBPJJKE_SceneId = MHFBCINOJEE;
						data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
						data.INDDJNMPONH = 1;
						data.JKGFBFPIMGA_BaseRarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_BaseRarity + 1;
						data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_BaseRarity + 1;
						data.OGPKHGEMLMP = b3;
						PJBJCBEMEEC = saveScene.JPIPENJGGDD_Mlt;
						data.JPIPENJGGDD_NumBoard = PJBJCBEMEEC;
						FIGHNFKAMGI.Add(data);
						if(b3)
						{
							//LAB_0146b66c;
							saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_Mlt);
						}
					}
				}
				else
				{
					GPPAIFNBHDP data = new GPPAIFNBHDP();
					data.BCCHOBPJJKE_SceneId = MHFBCINOJEE;
					data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
					if(saveScene.JPIPENJGGDD_Mlt == 0)
					{
						data.INDDJNMPONH = 3;
						data.JPIPENJGGDD_NumBoard = saveScene.JPIPENJGGDD_Mlt;
						data.JKGFBFPIMGA_BaseRarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_BaseRarity;
					}
					else
					{
						data.INDDJNMPONH = 4;
						data.JPIPENJGGDD_NumBoard = saveScene.JPIPENJGGDD_Mlt;
						data.JKGFBFPIMGA_BaseRarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_BaseRarity + 1;
					}
					data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_BaseRarity + 1;
					b3 = b3 && saveScene.JPIPENJGGDD_Mlt < maxPoster;
					data.OGPKHGEMLMP = b3;
					FIGHNFKAMGI.Add(data);
					saveScene.JPIPENJGGDD_Mlt++;
					saveScene.BEBJKJKBOGH_Date = time;
					dbScene.AGOEDLNOHND(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.JEMMMJEJLNL_Board, saveScene.EMOJHJGHJLN_Sb, saveScene.JPIPENJGGDD_Mlt, mlt);
					PJBJCBEMEEC = saveScene.JPIPENJGGDD_Mlt;
					IKBLCEFCGDE = saveScene.MJBODMOLOBC_Luck;
					//joined_r0x0146b3fc
					if(b3)
					{
						//LAB_0146b66c
						saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_Mlt);
					}
				}
			}
			if(GNGMCIAIKMA.HHCJCDFCLOB != null)
			{
				GNGMCIAIKMA.HHCJCDFCLOB.GJENEJOANEL(AHEFHIMGIBI, DKFJADMCNPI.NLKCMNHOBAI.NGDJIJOIPIB/*9*/, 0, HMFFHLPNMPH);
				GNGMCIAIKMA.HHCJCDFCLOB.HEFIKPAHCIA_IsBingoValid(null, -1);
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE, HMFFHLPNMPH, saveScene.JPIPENJGGDD_Mlt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, MHFBCINOJEE));
		}
	}

	//// RVA: 0x14702EC Offset: 0x14702EC VA: 0x14702EC
	//private bool LOOAENCCAPL(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146BF3C Offset: 0x146BF3C VA: 0x146BF3C
	private void ICHGJENIAMF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		EGOLBAPFHHD_Common.OFAPDOKONML growItem = AHEFHIMGIBI.KCCLEHLLOFG_Common.KBMDMEEMGLK_GrowItem[MHFBCINOJEE - 1];
		int cnt = growItem.BFINGCJHOHI_Cnt;
		if(cnt + HMFFHLPNMPH < 100000)
		{
			growItem.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
		}
		else
		{
			growItem.BFINGCJHOHI_Cnt = 99999;
			MPHIICNDGDH = true;
		}
		HAPENODDGOC[MHFBCINOJEE - 1] += HMFFHLPNMPH;
		INOAGFJHBBH += HMFFHLPNMPH;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, MHFBCINOJEE, HMFFHLPNMPH, growItem.BFINGCJHOHI_Cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, MHFBCINOJEE));
	}

	//// RVA: 0x1470304 Offset: 0x1470304 VA: 0x1470304
	private bool ALBIIKAIILG(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		return 99999 < HMFFHLPNMPH + AHEFHIMGIBI.KCCLEHLLOFG_Common.KBMDMEEMGLK_GrowItem[MHFBCINOJEE - 1].BFINGCJHOHI_Cnt;
	}

	//// RVA: 0x146B7F8 Offset: 0x146B7F8 VA: 0x146B7F8
	private void DPFKEPHOBKL(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
        EBFLJMOCLNA_Costume.ILFJDCICIKN cos = AHEFHIMGIBI.BEKHNNCGIEL_Costume.FABAGMLEKIB_List[MHFBCINOJEE - 1];
		if(!cos.CGKAEMGLHNK_Possessed())
		{
			cos.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			cos.CADENLBDAEB_IsNew = true;
			AHEFHIMGIBI.BEKHNNCGIEL_Costume.BJGLMIDBKKB(MHFBCINOJEE);
			if(AHEFHIMGIBI.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.JAHFLLONDCN(MHFBCINOJEE, 0))
				{
					int a1 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.FLFLMHDEBOL(MHFBCINOJEE);
					if(AHEFHIMGIBI.KCCLEHLLOFG_Common.HOGBPAGEJKO(a1))
					{
						AHEFHIMGIBI.KCCLEHLLOFG_Common.GCCOOJJHIAM_SetTrsVer(a1);
					}
				}
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_Costume, MHFBCINOJEE, HMFFHLPNMPH, 1, 0);
		}
    }

	//// RVA: 0x14702F4 Offset: 0x14702F4 VA: 0x14702F4
	//private bool FAGJNOGABJB(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146BBBC Offset: 0x146BBBC VA: 0x146BBBC
	private void GAFDHKHLNBA(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
        OIGEIIGKMNH_Valkyrie.HLNPGNNPCGO_ValkyrieInfo valk = AHEFHIMGIBI.JJFFBDLIOCF_Valkyrie.CNGNBKNBKGI_ValkList[MHFBCINOJEE - 1];
        if (!valk.FJODMPGPDDD)
		{
			valk.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			valk.CADENLBDAEB_New = true;
			if(AHEFHIMGIBI.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PEOALFEGNDH_Valkyrie.AAACOMKNJJJ(MHFBCINOJEE))
				{
					int a1 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PEOALFEGNDH_Valkyrie.MGKNLBJCJCK(MHFBCINOJEE);
					if(AHEFHIMGIBI.KCCLEHLLOFG_Common.CDDLPADLJNG(a1))
					{
						AHEFHIMGIBI.KCCLEHLLOFG_Common.HKAMGHBKNBH_SetDvfVer(a1);
					}
				}
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_Valkyrie, MHFBCINOJEE, HMFFHLPNMPH, 1, 0);
		}
	}

	//// RVA: 0x14702FC Offset: 0x14702FC VA: 0x14702FC
	//private bool HGALJPLIKNE(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146C220 Offset: 0x146C220 VA: 0x146C220
	private void GFNNJKJGEGA(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		KIICLPJJBNL_EpiItem.NKGPGMOHAFM dbEp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NEGGMILDEEF_EpiItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.AMCANGCIBEG saveCommon = AHEFHIMGIBI.KCCLEHLLOFG_Common.GJODJNIHKKF_EpiItem[dbEp.PPFNGGCBJKC_Id - 1];
		if(saveCommon.BFINGCJHOHI_Cnt + HMFFHLPNMPH < 10000)
		{
			saveCommon.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
		}
		else
		{
			saveCommon.BFINGCJHOHI_Cnt = 9999;
			MPHIICNDGDH = true;
		}
		JLCNBOKABJL[dbEp.PPFNGGCBJKC_Id - 1] += HMFFHLPNMPH;
		LNOEDPPJAHC = 0;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem, MHFBCINOJEE, HMFFHLPNMPH, saveCommon.BFINGCJHOHI_Cnt, 0);
	}

	//// RVA: 0x1470404 Offset: 0x1470404 VA: 0x1470404
	private bool BKLKPGCDMBE(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		KIICLPJJBNL_EpiItem.NKGPGMOHAFM dbEp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NEGGMILDEEF_EpiItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.AMCANGCIBEG saveEp = AHEFHIMGIBI.KCCLEHLLOFG_Common.GJODJNIHKKF_EpiItem[dbEp.PPFNGGCBJKC_Id - 1];
		return HMFFHLPNMPH + saveEp.BFINGCJHOHI_Cnt > 9999;
	}

	//// RVA: 0x146C554 Offset: 0x146C554 VA: 0x146C554
	private void KNBGNFDFEON(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		HGLPLKKBBOL_EventItem.JMCDEDCMCJE dbEvItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.DHOFNBMPBAG_EventItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_Counting_6, false);
		if(ev != null)
		{
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.EMOLGEDEEJP_EventItem, MHFBCINOJEE, HMFFHLPNMPH, 0, dbEvItem.EKLIPGELKCL_Rar);
			PPBHHLGPMBK[dbEvItem.EKLIPGELKCL_Rar - 1] = MHFBCINOJEE;
			IONINNDIAFO[dbEvItem.EKLIPGELKCL_Rar - 1] += HMFFHLPNMPH;
			JNEMAOPELPE += dbEvItem.JBGEEPFKIGG_Val * HMFFHLPNMPH;
			CNONCDLNIED += HMFFHLPNMPH;
		}
	}

	//// RVA: 0x146C830 Offset: 0x146C830 VA: 0x146C830
	private void CHKDGBJDBEF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		ABBOEIPOBLJ_EventTicket.CBDACMFFHJC dbEv = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KHPOJKHKLEM_EventTicket.CDENCMNHNGA[MHFBCINOJEE - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_Counting_6, false);
		if(ev != null)
		{
			ev.HPENJEOAMBK_SetTicket(EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket, MHFBCINOJEE), HMFFHLPNMPH, AHEFHIMGIBI);
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket, MHFBCINOJEE, HMFFHLPNMPH, ev.AELBIEDNPGB_GetTicketCount(AHEFHIMGIBI), 1);
			if(ev.HIDHLFCBIDE_EventType == OHCAABOMEOF.KGOGMKMBCPP_EventType.AOPKACCDKPA_EventCollection)
			{
				TodoLogger.LogError(TodoLogger.EventCollection_1, "Event");
			}
			else if(ev.HIDHLFCBIDE_EventType == OHCAABOMEOF.KGOGMKMBCPP_EventType.BNECMLPHAGJ_EventGoDiva)
			{
				AHEFHIMGIBI.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty++;
				if(AHEFHIMGIBI.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty <= 999999999)
					return;
				AHEFHIMGIBI.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty = 0;
			}
			else
			{
				return;
			}
		}
		else
		{
			if(AHEFHIMGIBI.MBAHCFLBDHN_EventCollection == null)
				return;
		}
		AHEFHIMGIBI.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty++;
		if(AHEFHIMGIBI.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty <= 999999999)
			return;
		AHEFHIMGIBI.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty = 0;
	}

	//// RVA: 0x14705D8 Offset: 0x14705D8 VA: 0x14705D8
	private bool KMNEKFLHAMN(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		ABBOEIPOBLJ_EventTicket.CBDACMFFHJC dbEv = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KHPOJKHKLEM_EventTicket.CDENCMNHNGA[MHFBCINOJEE - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_Counting_6, false);
		if(ev != null)
		{
			return ev.AELBIEDNPGB_GetTicketCount(null) + HMFFHLPNMPH > 9999;
		}
		return false;
	}

	//// RVA: 0x1470774 Offset: 0x1470774 VA: 0x1470774
	//private bool KBDCEEDMKGD(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146CC48 Offset: 0x146CC48 VA: 0x146CC48
	private void HPBIMHODDAP(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		IHGBPAJMJFK_Emblem.AKJPPHFGEFG_EmblemInfo embl = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBNBNAFGMDE_Emblem.CDENCMNHNGA_EmblemList[MHFBCINOJEE - 1];
		JGGLDGNKELI_Emblem.AAHAAJEJNLJ saveEblm = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.OFAJDLJBMEM_Emblem.MDKOHOCONKE[MHFBCINOJEE - 1];
		if(MHFBCINOJEE < 2)
			return;
		for(int i = 0; i < HMFFHLPNMPH; i++)
		{
			if(!saveEblm.FJODMPGPDDD_Unlocked)
			{
				saveEblm.FHCAFLCLGAA_Cnt = 0;
				saveEblm.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			}
			else
			{
				if(saveEblm.FHCAFLCLGAA_Cnt < 99)
				{
					saveEblm.FHCAFLCLGAA_Cnt++;
				}
			}
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MNCJMDDAFJB_EmblemItem, MHFBCINOJEE, HMFFHLPNMPH, saveEblm.FHCAFLCLGAA_Cnt + 1, 0);
		ILCCJNDFFOB.HHCJCDFCLOB.COBCMOAAAFF(MHFBCINOJEE);
	}

	//// RVA: 0x147077C Offset: 0x147077C VA: 0x147077C
	public bool FODKDOCADJI(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		HHPEMHHCKBE_Compo.MLMDKHBFOJM dbCompo = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ALFKMKICDPP_Compo.CDENCMNHNGA[MHFBCINOJEE - 1];
		for(int i = 0; i < dbCompo.JCJGGHGIKIJ(); i++)
		{
			int id = dbCompo.CBLLFCGEJAI(i);
			if(HMDCGPGGOBA_IsAddItemOverflow(AHEFHIMGIBI, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(id), EKLNMHFCAOI.DEACAHNLMNI_getItemId(id), HMFFHLPNMPH * dbCompo.HBJMCLGKLBA(i)))
				return true;
		}
		return false;
	}

	//// RVA: 0x146CFFC Offset: 0x146CFFC VA: 0x146CFFC
	public void PKEBBIAIHEK(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
        HHPEMHHCKBE_Compo.MLMDKHBFOJM dbData = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ALFKMKICDPP_Compo.CDENCMNHNGA[MHFBCINOJEE - 1];
		for(int i = 0; i < dbData.JCJGGHGIKIJ(); i++)
		{
			int fullItemId = dbData.CBLLFCGEJAI(i);
            EKLNMHFCAOI.FKGCBLHOOCL_Category itemCat = EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(fullItemId);
			int itemId = EKLNMHFCAOI.DEACAHNLMNI_getItemId(fullItemId);
			if(itemCat == EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem)
			{
				ICHGJENIAMF(AHEFHIMGIBI, itemId, dbData.HBJMCLGKLBA(i) * HMFFHLPNMPH);
			}
        }
    }

	//// RVA: 0x146D200 Offset: 0x146D200 VA: 0x146D200
	private void OAOJFIOACEL(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		BOKMNHAFJHF_Sns.KEIGMAOCJHK_Talk dbSns = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OMGFKMANMAB_Sns.CDENCMNHNGA_Talks[MHFBCINOJEE - 1];
        DDEMMEPBOIA_Sns.EFIFBJGKPJF saveSns = AHEFHIMGIBI.FLHMJHBOBEA_Sns.HAJEJPFGILG[MHFBCINOJEE - 1];
		saveSns.PMKJFKJFDOC_Itm = 1;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.KNHFAHFCCBK_SnsItem, MHFBCINOJEE, HMFFHLPNMPH, 1, 1);
	}

	//// RVA: 0x146D3CC Offset: 0x146D3CC VA: 0x146D3CC
	private void PGMIPBPEDDD(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		List<EGOLBAPFHHD_Common.FKLHGOGJOHH> l = AHEFHIMGIBI.KCCLEHLLOFG_Common.KFEBOFKAHAJ_EngItem;
		JKDKODAPGBJ_EnergyItem.GFGCCICHBHK enItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KOPOGNLKAEN_EnergyItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.FKLHGOGJOHH saveEn = l[MHFBCINOJEE - 1];
		if(enItem.DOOGFEGEKLG_Max < saveEn.BFINGCJHOHI_Cnt + HMFFHLPNMPH)
		{
			saveEn.BFINGCJHOHI_Cnt = enItem.DOOGFEGEKLG_Max;
			saveEn.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			MPHIICNDGDH = true;
		}
		else
		{
			saveEn.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			saveEn.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem, MHFBCINOJEE, HMFFHLPNMPH, saveEn.BFINGCJHOHI_Cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem, MHFBCINOJEE));
	}

	//// RVA: 0x147099C Offset: 0x147099C VA: 0x147099C
	private bool LDCIPFEAOAD(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		JKDKODAPGBJ_EnergyItem.GFGCCICHBHK item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KOPOGNLKAEN_EnergyItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.FKLHGOGJOHH saveItem = AHEFHIMGIBI.KCCLEHLLOFG_Common.KFEBOFKAHAJ_EngItem[MHFBCINOJEE - 1];
		return item.DOOGFEGEKLG_Max < HMFFHLPNMPH + saveItem.BFINGCJHOHI_Cnt;
	}

	//// RVA: 0x146DADC Offset: 0x146DADC VA: 0x146DADC
	private void JNABIIIMOPE(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		HHFFOACILKG_Medal.HCFJGDFMHOJ dbMedal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ICICKEBMEFA_Medal.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.GLBBNDKGEOC saveMedal = AHEFHIMGIBI.KCCLEHLLOFG_Common.MHKJEBNOPIM_Medal[MHFBCINOJEE - 1];
		int cnt = saveMedal.BFINGCJHOHI_Cnt;
		if(cnt + HMFFHLPNMPH < 100000000)
		{
			saveMedal.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			saveMedal.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
			if(dbMedal.IBAKPKKEDJM_Month > 0 && dbMedal.IBAKPKKEDJM_Month < 13)
			{
				AHEFHIMGIBI.OEKEIGFAIGN_Counter.BDLNMOIOMHK_Total.KPNLMLPFKMJ_AddMedal(HMFFHLPNMPH);
			}
		}
		else
		{
			saveMedal.BFINGCJHOHI_Cnt = 99999999;
			saveMedal.BEBJKJKBOGH_Date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			MPHIICNDGDH = true;
		}
		if(GNGMCIAIKMA.HHCJCDFCLOB != null)
		{
			GNGMCIAIKMA.HHCJCDFCLOB.GJENEJOANEL(DKFJADMCNPI.NLKCMNHOBAI.EHEDFAMGLDP_10, 0, HMFFHLPNMPH, null);
			GNGMCIAIKMA.HHCJCDFCLOB.HEFIKPAHCIA_IsBingoValid(null, -1);
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal, MHFBCINOJEE, HMFFHLPNMPH, saveMedal.BFINGCJHOHI_Cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal, MHFBCINOJEE));
	}

	//// RVA: 0x1470BD8 Offset: 0x1470BD8 VA: 0x1470BD8
	private bool EJPHHJFMAPE(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		HHFFOACILKG_Medal.HCFJGDFMHOJ dbMedal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ICICKEBMEFA_Medal.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.GLBBNDKGEOC saveMedal = AHEFHIMGIBI.KCCLEHLLOFG_Common.MHKJEBNOPIM_Medal[MHFBCINOJEE - 1];
		return HMFFHLPNMPH + saveMedal.BFINGCJHOHI_Cnt > 99999999;
	}

	//// RVA: 0x146D918 Offset: 0x146D918 VA: 0x146D918
	private void NFDOJPCKFAK(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(AHEFHIMGIBI.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket + HMFFHLPNMPH < 10000)
		{
			AHEFHIMGIBI.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket += HMFFHLPNMPH;
		}
		else
		{
			AHEFHIMGIBI.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket = 9999;
			MPHIICNDGDH = true;
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket, MHFBCINOJEE, HMFFHLPNMPH, AHEFHIMGIBI.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket, MHFBCINOJEE));
	}

	//// RVA: 0x1470B70 Offset: 0x1470B70 VA: 0x1470B70
	private bool MFNLHPELAOF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		return HMFFHLPNMPH + AHEFHIMGIBI.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket > 9999;
	}

	//// RVA: 0x146E0F4 Offset: 0x146E0F4 VA: 0x146E0F4
	private void IFDDILLJLFO(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		JNGINLMOJKH_EventGachaTicket.JDNAAGCHCOH dbEvGacha = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NKOKFIMNCJM_EventGachaTicket.CDENCMNHNGA[MHFBCINOJEE - 1];
		if(AHEFHIMGIBI.MMAIJOCPJHP_EventBoxGacha != null)
		{
			TodoLogger.LogError(TodoLogger.EventBoxGacha_8, "Event gacha");
		}
	}

	//// RVA: 0x1470D90 Offset: 0x1470D90 VA: 0x1470D90
	private bool EJKKIHJDOKF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		JNGINLMOJKH_EventGachaTicket.JDNAAGCHCOH dbEvGacha = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NKOKFIMNCJM_EventGachaTicket.CDENCMNHNGA[MHFBCINOJEE - 1];
		if(AHEFHIMGIBI.MMAIJOCPJHP_EventBoxGacha != null)
		{
			TodoLogger.LogError(TodoLogger.EventBoxGacha_8, "Event gacha");
		}
		return false;
	}

	//// RVA: 0x146E3C0 Offset: 0x146E3C0 VA: 0x146E3C0
	private void LCIPJMMEMPI(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(MHFBCINOJEE > 0)
		{
			EGOLBAPFHHD_Common.DEEGPPKGGLK d = AHEFHIMGIBI.KCCLEHLLOFG_Common.DHJFHILPKLB_IntimacyPresent[MHFBCINOJEE - 1];
			if(d.BFINGCJHOHI_Cnt + HMFFHLPNMPH < 10000)
				d.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
			else
			{
				d.BFINGCJHOHI_Cnt = 9999;
				MPHIICNDGDH = true;
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem, MHFBCINOJEE, HMFFHLPNMPH, d.BFINGCJHOHI_Cnt, 0);
		}
	}

	//// RVA: 0x1470FA0 Offset: 0x1470FA0 VA: 0x1470FA0
	private bool POCBGCBPBGD(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(MHFBCINOJEE < 1)
			return false;
		return HMFFHLPNMPH + AHEFHIMGIBI.KCCLEHLLOFG_Common.DHJFHILPKLB_IntimacyPresent[MHFBCINOJEE - 1].BFINGCJHOHI_Cnt > 9999;
	}

	//// RVA: 0x146E648 Offset: 0x146E648 VA: 0x146E648
	private void IAFODMHCKNH(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(MHFBCINOJEE == 13)
		{
			JHDCJPEPDIC(AHEFHIMGIBI, 1, HMFFHLPNMPH);
		}
		else
		{
			PPNFHHPJOKK_SpItem.JBBIPIAABOJ item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OOEPHOEFBNL_SpItem.CDENCMNHNGA[MHFBCINOJEE - 1];
			EGOLBAPFHHD_Common.KPMNLAHNDAI saveItem = AHEFHIMGIBI.KCCLEHLLOFG_Common.BBFIGEOBOMB_SpItem[MHFBCINOJEE - 1];
			if(saveItem != null)
			{
				if(saveItem.BFINGCJHOHI_Cnt + HMFFHLPNMPH > item.DOOGFEGEKLG_Max)
				{
					saveItem.BFINGCJHOHI_Cnt = item.DOOGFEGEKLG_Max;
				}
				else
				{
					saveItem.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
				}
				if(MHFBCINOJEE == 8)
				{
					AHEFHIMGIBI.OEKEIGFAIGN_Counter.BDLNMOIOMHK_Total.FNLAFLEEAHC(HMFFHLPNMPH);
				}
				NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem, MHFBCINOJEE, HMFFHLPNMPH, saveItem.BFINGCJHOHI_Cnt, 0);
			}
		}
	}

	//// RVA: 0x14710A4 Offset: 0x14710A4 VA: 0x14710A4
	private bool EBFPNOMLJCN(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(MHFBCINOJEE == 13)
		{
			return BDFAHPBDGPJ(AHEFHIMGIBI, 1, HMFFHLPNMPH);
		}
		else
		{
			PPNFHHPJOKK_SpItem.JBBIPIAABOJ item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OOEPHOEFBNL_SpItem.CDENCMNHNGA[MHFBCINOJEE - 1];
			EGOLBAPFHHD_Common.KPMNLAHNDAI saveItem = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.KCCLEHLLOFG_Common.BBFIGEOBOMB_SpItem[MHFBCINOJEE - 1];
			if(saveItem == null)
				return false;
			return item.DOOGFEGEKLG_Max < HMFFHLPNMPH + saveItem.BFINGCJHOHI_Cnt;
		}
	}

	//// RVA: 0x146E8FC Offset: 0x146E8FC VA: 0x146E8FC
	private void NKJHEGBDMHJ(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		EGOLBAPFHHD_Common.PGENIOHDCDI d = AHEFHIMGIBI.KCCLEHLLOFG_Common.EFBKCNNFIPJ(MHFBCINOJEE);
		if(d != null)
		{
			if (d.BFINGCJHOHI_Cnt + HMFFHLPNMPH < 10000)
				d.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
			else
				d.BFINGCJHOHI_Cnt = 9999;
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem, MHFBCINOJEE, HMFFHLPNMPH, d.BFINGCJHOHI_Cnt, 0);
		}
	}

	//// RVA: 0x1471294 Offset: 0x1471294 VA: 0x1471294
	private bool EHMCNIGGPNO(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.GOGFKAECFIP_CosItem.EEOADCECNOM_GetItemById(MHFBCINOJEE);
		EGOLBAPFHHD_Common.PGENIOHDCDI p = AHEFHIMGIBI.KCCLEHLLOFG_Common.EFBKCNNFIPJ(MHFBCINOJEE);
		if(p != null)
		{
			return HMFFHLPNMPH + p.BFINGCJHOHI_Cnt > 9999;
		}
		return false;
	}

	//// RVA: 0x146EAAC Offset: 0x146EAAC VA: 0x146EAAC
	private void EALJGONPDJD(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		for(int i = 0; i < HMFFHLPNMPH; i++)
		{
			AHEFHIMGIBI.DPNKPPBEAGJ_RareUpItem.APIEKGBMBPA(time, false);
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem, MHFBCINOJEE, HMFFHLPNMPH, AHEFHIMGIBI.DPNKPPBEAGJ_RareUpItem.LDLCGGACHGA(time), 0);
	}

	//// RVA: 0x14713EC Offset: 0x14713EC VA: 0x14713EC
	private bool GJGFKFFPLAB(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
		return AHEFHIMGIBI.DPNKPPBEAGJ_RareUpItem.LDLCGGACHGA(time) + HMFFHLPNMPH > 9;
	}

	//// RVA: 0x146EC38 Offset: 0x146EC38 VA: 0x146EC38
	private void NGIHAOOFEPG(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		EGLOKAEIHCB_LimitedItem.DEOCBHAGEEH d = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.IHPFCIJKFIC_LimitedItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		if(AHEFHIMGIBI.AFHFIPLOKMN_LimitedItem != null)
		{
			long t = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			for(int i = 0; i < HMFFHLPNMPH; i++)
			{
				AHEFHIMGIBI.AFHFIPLOKMN_LimitedItem.CPIICACGNBH(MHFBCINOJEE, t);
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_LimitedItem, MHFBCINOJEE, HMFFHLPNMPH, AHEFHIMGIBI.AFHFIPLOKMN_LimitedItem.HPPKOGKNKMH(MHFBCINOJEE, t), 0);
		}
	}

	//// RVA: 0x1471538 Offset: 0x1471538 VA: 0x1471538
	private bool PIHDONDGHMH(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		EGLOKAEIHCB_LimitedItem.DEOCBHAGEEH dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.IHPFCIJKFIC_LimitedItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		if(AHEFHIMGIBI.AFHFIPLOKMN_LimitedItem != null)
		{
			long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			return HMFFHLPNMPH + AHEFHIMGIBI.AFHFIPLOKMN_LimitedItem.HPPKOGKNKMH(MHFBCINOJEE, time) > dbItem.DOOGFEGEKLG_Max;
		}
		return false;
	}

	//// RVA: 0x146FA7C Offset: 0x146FA7C VA: 0x146FA7C
	private void JHDCJPEPDIC(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem != null)
		{
			long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime();
			JHAAHJNEBOG_LimitedCompoItem.AOBHKONKIPF dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MBAGKLJDKMH_LimitedCompoItem.OCMMLAOEPIG[MHFBCINOJEE - 1];
			int b = AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.OPCIHPEIFFE(dbItem.PENIOLJHIPK);
			int a = AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(dbItem.PENIOLJHIPK, time);
			if(b < a + HMFFHLPNMPH)
				HMFFHLPNMPH = b - a;
			if(HMFFHLPNMPH > 0)
			{
				for(int i = 0; i < HMFFHLPNMPH; i++)
				{
					AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.CPIICACGNBH(MHFBCINOJEE, time, false);
				}
				int c = AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(MHFBCINOJEE, time);
				NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem, MHFBCINOJEE,HMFFHLPNMPH, c, 0);
			}
		}
	}

	//// RVA: 0x1471B74 Offset: 0x1471B74 VA: 0x1471B74
	private bool BDFAHPBDGPJ(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		if(AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem == null)
			return false;
		else
		{
			return AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.OPCIHPEIFFE(MHFBCINOJEE) < HMFFHLPNMPH + AHEFHIMGIBI.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(MHFBCINOJEE, NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime());
		}
	}

	//// RVA: 0x146EE80 Offset: 0x146EE80 VA: 0x146EE80
	private void NOGNCLIGIMG(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		AHEFHIMGIBI.HMMNDKHKEBC_MonthlyPass.DGIBOADNFOI(HMFFHLPNMPH);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem, MHFBCINOJEE, HMFFHLPNMPH, AHEFHIMGIBI.HMMNDKHKEBC_MonthlyPass.JAMCDEDFHHK_HotenCnt, 0);
	}

	//// RVA: 0x1471764 Offset: 0x1471764 VA: 0x1471764
	private bool DAHPCLHIAKP(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		return AHEFHIMGIBI.HMMNDKHKEBC_MonthlyPass.JAMCDEDFHHK_HotenCnt + HMFFHLPNMPH > 99;
	}

	//// RVA: 0x146F254 Offset: 0x146F254 VA: 0x146F254
	private void IJGFIAGIINJ(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		EGOLBAPFHHD_Common.GHOADMJCPFK d = AHEFHIMGIBI.KCCLEHLLOFG_Common.MJAIFKFOPPI_ValItem[MHFBCINOJEE - 1];
		if(d != null)
		{
			if (d.BFINGCJHOHI_Cnt + HMFFHLPNMPH < 100000)
				d.BFINGCJHOHI_Cnt += HMFFHLPNMPH;
			else
				d.BFINGCJHOHI_Cnt = 99999;
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem, MHFBCINOJEE, HMFFHLPNMPH, d.BFINGCJHOHI_Cnt, 0);
		}
	}

	//// RVA: 0x146F73C Offset: 0x146F73C VA: 0x146F73C
	private void ACODICAMEGB(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		NKOBMDPHNGP_EventRaidLobby ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.OEGDCBLNNFF(OHCAABOMEOF.KGOGMKMBCPP_EventType.MCGPGMGEPHG_EventRaidLobby, KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_Counting_6) as NKOBMDPHNGP_EventRaidLobby;
		if(ev != null)
		{
			TodoLogger.LogError(TodoLogger.EventRaid_11_13, "Event Raid");
		}
		AHEFHIMGIBI.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty++;
		if(AHEFHIMGIBI.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty > 1000000000)
		{
			AHEFHIMGIBI.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty = 0;
		}
	}

	//// RVA: 0x1471974 Offset: 0x1471974 VA: 0x1471974
	private bool BGBJMNELGLC(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		NKOBMDPHNGP_EventRaidLobby ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.OEGDCBLNNFF(OHCAABOMEOF.KGOGMKMBCPP_EventType.MCGPGMGEPHG_EventRaidLobby, KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_Counting_6) as NKOBMDPHNGP_EventRaidLobby;
		if(ev != null)
		{
			TodoLogger.LogError(TodoLogger.EventRaid_11_13, "Event Raid");
		}
		return false;
	}

	//// RVA: 0x14717C8 Offset: 0x14717C8 VA: 0x14717C8
	private bool OHNDBOLGLFF(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		INDEPDKCJDD_ValItem.NHJLDENJKBE dbVal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.FBGKBGNIHGC_ValItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		EGOLBAPFHHD_Common.GHOADMJCPFK saveVal = AHEFHIMGIBI.KCCLEHLLOFG_Common.MJAIFKFOPPI_ValItem[MHFBCINOJEE - 1];
		if(saveVal != null)
		{
			return HMFFHLPNMPH + saveVal.BFINGCJHOHI_Cnt > 99999;
		}
		return false;
	}

	//// RVA: 0x1471CFC Offset: 0x1471CFC VA: 0x1471CFC
	//private bool IJPBEIHHBHB(BBHNACPENDM AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL HHACNFODNEF, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x146EF3C Offset: 0x146EF3C VA: 0x146EF3C
	private void FLFGJFDBEAB(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category HHACNFODNEF, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		int num = EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, HHACNFODNEF, MHFBCINOJEE, null);
		int max = EKLNMHFCAOI.AFEONHCADEL_GetMaxAllowed(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, HHACNFODNEF, MHFBCINOJEE, null);
		int cnt = num + HMFFHLPNMPH;
		if(max < cnt)
			cnt  = max;
		EKLNMHFCAOI.DPHGFMEPOCA_SetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, HHACNFODNEF, MHFBCINOJEE, cnt, null);
		if(HHACNFODNEF == EKLNMHFCAOI.FKGCBLHOOCL_Category.BMMBLLOKNPF_DecoItemSp)
		{
			if(AHEFHIMGIBI.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				int a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.CHMNDNFMAGA(MHFBCINOJEE);
				if(a > -1)
				{
					if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.KCCLEHLLOFG_Common.GAFDKEENNJO(a))
					{
						CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.KCCLEHLLOFG_Common.JAHBNIMDNHJ_DMasVer(a);
					}
				}
			}
		}
		else if(HHACNFODNEF == EKLNMHFCAOI.FKGCBLHOOCL_Category.MCKHJLHKMJD_DecoItemChara)
		{
			IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.KDFMGDNOMHE(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, MHFBCINOJEE);
		}
		NGEPPDAOIBN(HHACNFODNEF, MHFBCINOJEE, HMFFHLPNMPH, cnt, 0);
	}

	//// RVA: 0x146F450 Offset: 0x146F450 VA: 0x146F450
	private void PCJFOILKCOP(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		int num = EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, MHFBCINOJEE, null);
		int max = EKLNMHFCAOI.AFEONHCADEL_GetMaxAllowed(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, MHFBCINOJEE, null);
		int cnt = num + HMFFHLPNMPH;
		if(cnt > max)
			cnt = max;
		EKLNMHFCAOI.DPHGFMEPOCA_SetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, AHEFHIMGIBI, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, MHFBCINOJEE, cnt, null);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, MHFBCINOJEE, HMFFHLPNMPH, cnt, 0);
        BBLECJKKKLA_DecoSetItem.GJBPBKNHLHC_DecoSetItemInfo dbSet = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MJALLIOHKEJ_DecoSetItem.CDENCMNHNGA[MHFBCINOJEE - 1];
		for(int i = 0; i < dbSet.JJBNDDDGEAN_GetNumItems(); i++)
		{
			FLFGJFDBEAB(AHEFHIMGIBI, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(dbSet.FKNBLDPIPMC_GetItemCode(i)), EKLNMHFCAOI.DEACAHNLMNI_getItemId(dbSet.FKNBLDPIPMC_GetItemCode(i)), HMFFHLPNMPH * dbSet.NKOHMLHLJGL(i));
		}
    }

	//// RVA: 0x146FDB8 Offset: 0x146FDB8 VA: 0x146FDB8
	private void DBHOKBOGDNB(BBHNACPENDM_ServerSaveData AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH)
	{
		ALJHJDHNFFB_HomeBg.ADLLAFIDFAM dbBg = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PFEKKPABPKL_HomeBg.CDENCMNHNGA[MHFBCINOJEE - 1];
		CGFNKMNBNBN.DPMCLJMIBDK(AHEFHIMGIBI, MHFBCINOJEE, NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL.KMEFBNBFJHI_GetServerTime());
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg, MHFBCINOJEE, HMFFHLPNMPH, 1, 0);
	}

	//// RVA: 0x1471CD8 Offset: 0x1471CD8 VA: 0x1471CD8
	//private bool POKLFKEFCLM(BBHNACPENDM AHEFHIMGIBI, int MHFBCINOJEE, int HMFFHLPNMPH) { }

	//// RVA: 0x1471E30 Offset: 0x1471E30 VA: 0x1471E30
	public static string JKOAGEAPJHI(int KIJAPOFAGPN, int HMFFHLPNMPH)
	{
		return JKOAGEAPJHI(EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(KIJAPOFAGPN), EKLNMHFCAOI.DEACAHNLMNI_getItemId(KIJAPOFAGPN), HMFFHLPNMPH);
	}

	//// RVA: 0x1471ED8 Offset: 0x1471ED8 VA: 0x1471ED8
	public static string JKOAGEAPJHI(EKLNMHFCAOI.FKGCBLHOOCL_Category INDDJNMPONH, int JBGEEPFKIGG, int HMFFHLPNMPH)
	{
		return EKLNMHFCAOI.INCKKODFJAP_GetItemName(INDDJNMPONH, JBGEEPFKIGG) + JpStringLiterals.StringLiteral_12037 + HMFFHLPNMPH + EKLNMHFCAOI.NDBLEADIDLA(INDDJNMPONH, JBGEEPFKIGG);
	}

	//// RVA: 0x1471FCC Offset: 0x1471FCC VA: 0x1471FCC
	public static string JKOAGEAPJHI(int KIJAPOFAGPN, int HMFFHLPNMPH, int OEBOKCMFMHG)
	{
		EKLNMHFCAOI.FKGCBLHOOCL_Category cat = EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(KIJAPOFAGPN);
		int id = EKLNMHFCAOI.DEACAHNLMNI_getItemId(KIJAPOFAGPN);
		return KJFKHPMPLBC(EKLNMHFCAOI.INCKKODFJAP_GetItemName(cat, id), OEBOKCMFMHG) + JpStringLiterals.StringLiteral_12037 + HMFFHLPNMPH.ToString() + EKLNMHFCAOI.NDBLEADIDLA(cat, id);
	}

	//// RVA: 0x14720E8 Offset: 0x14720E8 VA: 0x14720E8
	public static string KJFKHPMPLBC(string OPFGFINHFCE, int OEBOKCMFMHG)
	{
		if (OPFGFINHFCE.Length < OEBOKCMFMHG)
			return OPFGFINHFCE;
		return OPFGFINHFCE.Substring(0, OEBOKCMFMHG - 1) + JpStringLiterals.StringLiteral_12038;
	}

	//// RVA: 0x147219C Offset: 0x147219C VA: 0x147219C
	public string OLAICLNDMFF()
	{
		return JKOAGEAPJHI(KJOGOABBMNN, IHIJFEHOBOB, AAIAJEGOIHL);
	}
}
