
using System.Collections.Generic;
using UnityEngine;

public class JKNGJFOBADP
{
	public class GPPAIFNBHDP
	{
		public int BCCHOBPJJKE_SceneId; // 0x8
		public int INDDJNMPONH_type; // 0xC
		public int JKGFBFPIMGA_Rarity; // 0x10
		public int MPGNHFDGOBO_PrevRarity; // 0x14
		public int HNNAODKJGPD_NextRarity; // 0x18
		public int JPIPENJGGDD_NumBoard; // 0x1C
		public int FELBNCPBGMJ; // 0x20
		public int OCMIGHELJDP; // 0x24
		public bool OGPKHGEMLMP; // 0x28
		public bool OLGCDLJFMDH_Sngl; // 0x29
	}

	public class OILCOECKMOO
	{
		public int KELFCMEOPPM_EpisodeId; // 0x8
		public int DNBFMLBNAEE_point; // 0xC
	}

	public int CIKCPLCPKAO; // 0x8
	public int PJIPCABDHCI; // 0xC
	public List<int> HAPENODDGOC = new List<int>(27); // 0x10
	public List<int> JLCNBOKABJL = new List<int>(3); // 0x14
	public int INOAGFJHBBH; // 0x18
	public int LNOEDPPJAHC; // 0x1C
	public int JIDELBDMKJM; // 0x20
	public long HHOBAFKAKJK; // 0x28
	public bool MPHIICNDGDH; // 0x30
	public int EPPFEAIMFOE_ItemCount; // 0x34
	public List<int> PPBHHLGPMBK = new List<int>(3); // 0x38
	public List<int> IONINNDIAFO = new List<int>(3); // 0x3C
	public int JNEMAOPELPE; // 0x40
	public int CNONCDLNIED; // 0x44
	public int HLEMBNOMOGM; // 0x48
	public int IKBLCEFCGDE_LastLuck; // 0x4C
	public int PJBJCBEMEEC; // 0x50
	public int OBCINIPHGGH; // 0x54
	public int IECOFJEJNON; // 0x58
	public int IHIJFEHOBOB; // 0x5C
	public int AAIAJEGOIHL; // 0x60
	public EKLNMHFCAOI.FKGCBLHOOCL_Category KJOGOABBMNN; // 0x64
	public bool OMGJFMMJPJD; // 0x65
	public List<MFDJIFIIPJD> HBHMAKNGKFK_items = new List<MFDJIFIIPJD>(100); // 0x68
	public List<GPPAIFNBHDP> FIGHNFKAMGI = new List<GPPAIFNBHDP>(); // 0x6C
	public List<int> NNDMIOEKKMM_NewEpisode = new List<int>(); // 0x70
	public List<OILCOECKMOO> FJKAMPIMFLP = new List<OILCOECKMOO>(); // 0x74
	public OAGBCBBHMPF.COIIJOEKBDH LHEIIHKDMPA_route_type; // 0x78
	public string NPBEKONLDDI_route_id = ""; // 0x7C

	//// RVA: 0x1469C68 Offset: 0x1469C68 VA: 0x1469C68
	public void FEGDNPIEKJC(OAGBCBBHMPF.COIIJOEKBDH EILCNJNKDAI, string _PPFNGGCBJKC_id)
	{
		LHEIIHKDMPA_route_type = EILCNJNKDAI;
		NPBEKONLDDI_route_id = _PPFNGGCBJKC_id;
	}

	//// RVA: 0x1469C78 Offset: 0x1469C78 VA: 0x1469C78
	public void NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category _INDDJNMPONH_type, int _MHFBCINOJEE_Num, int _ADPPAIPFHML_num, int _FBAIDPHDEBA_num_af, int _LIDBKCIMCKE_rarity)
	{
		ILCCJNDFFOB.HHCJCDFCLOB.JAHALBMOANH(EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(_INDDJNMPONH_type, _MHFBCINOJEE_Num), LHEIIHKDMPA_route_type, NPBEKONLDDI_route_id, _ADPPAIPFHML_num, _FBAIDPHDEBA_num_af, _LIDBKCIMCKE_rarity);
	}

	//// RVA: 0x1469D94 Offset: 0x1469D94 VA: 0x1469D94
	public void JCHLONCMPAJ_Clear()
	{
		CIKCPLCPKAO = 0;
		PJIPCABDHCI = 0;
		HAPENODDGOC.Clear();
		for(int i = 0; i < 27; i++)
		{
			HAPENODDGOC.Add(0);
		}
		JLCNBOKABJL.Clear();
		for (int i = 0; i < 3; i++)
		{
			JLCNBOKABJL.Add(0);
		}
		HHOBAFKAKJK = 0;
		INOAGFJHBBH = 0;
		LNOEDPPJAHC = 0;
		JIDELBDMKJM = 0;
		MPHIICNDGDH = false;
		EPPFEAIMFOE_ItemCount = 0;
		JNEMAOPELPE = 0;
		CNONCDLNIED = 0;
		IONINNDIAFO.Clear();
		PPBHHLGPMBK.Clear();
		for (int i = 0; i < 3; i++)
		{
			IONINNDIAFO.Add(0);
			PPBHHLGPMBK.Add(0);
		}
		IECOFJEJNON = 0;
		HLEMBNOMOGM = 0;
		IKBLCEFCGDE_LastLuck = 0;
		PJBJCBEMEEC = 0;
		OBCINIPHGGH = 0;
		HBHMAKNGKFK_items.Clear();
		FIGHNFKAMGI.Clear();
		NNDMIOEKKMM_NewEpisode.Clear();
		FJKAMPIMFLP.Clear();
		OMGJFMMJPJD = false;
	}

	//// RVA: 0x146A074 Offset: 0x146A074 VA: 0x146A074
	public void CPIICACGNBH_AddItem(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _KIJAPOFAGPN_ItemId, int _HMFFHLPNMPH_count, OOOOCFAFGCP _KACECFNECON_extra, int ONMCOJPNBAO/* = 0*/)
	{
		CPIICACGNBH_AddItem(_AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(_KIJAPOFAGPN_ItemId), EKLNMHFCAOI.DEACAHNLMNI_getItemId(_KIJAPOFAGPN_ItemId), _HMFFHLPNMPH_count, _KACECFNECON_extra, ONMCOJPNBAO);
	}

	//// RVA: 0x146A140 Offset: 0x146A140 VA: 0x146A140
	public void CPIICACGNBH_AddItem(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category _HHACNFODNEF_ItemCategory, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count, OOOOCFAFGCP _KACECFNECON_extra, int ONMCOJPNBAO/* = 0*/)
	{
		EPPFEAIMFOE_ItemCount++;
		MFDJIFIIPJD data = new MFDJIFIIPJD();
		data.KHEKNNFCAOI_Init(_HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
		data.KACECFNECON_extra = _KACECFNECON_extra;
		HBHMAKNGKFK_items.Add(data);
		IHIJFEHOBOB = _MHFBCINOJEE_Num;
		AAIAJEGOIHL = _HMFFHLPNMPH_count;
		KJOGOABBMNN = _HHACNFODNEF_ItemCategory;
		switch(_HHACNFODNEF_ItemCategory)
		{
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJDEOPMBGKJ_PaidVC:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OBHECJMAEIO_GachaTicket:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IBBDMIFICCN_BonusVC:
				NGEPPDAOIBN(_HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 0, 0);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit:
				BOBHHEOBAJF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene:
				IKFHPLBCMHN(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, ONMCOJPNBAO);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_5_Costume:
				DPFKEPHOBKL(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_6_Valkyrie:
				GAFDHKHLNBA(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem:
				ICHGJENIAMF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem:
				GFNNJKJGEGA(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MNCJMDDAFJB_EmblemItem:
				HPBIMHODDAP(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.EMOLGEDEEJP_EventItem:
				KNBGNFDFEON(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket:
				CHKDGBJDBEF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GIMBFBNKPNO_CompoItem:
				PKEBBIAIHEK(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KNHFAHFCCBK_SnsItem:
				OAOJFIOACEL(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem:
				PGMIPBPEDDD(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket:
				NFDOJPCKFAK(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal:
				JNABIIIMOPE(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.LLFAAOHPMIC_EventGachaTicket:
				IFDDILLJLFO(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem:
				LCIPJMMEMPI(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem:
				IAFODMHCKNH(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem:
				NKJHEGBDMHJ(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem:
				EALJGONPDJD(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_24_LimitedItem:
				NGIHAOOFEPG(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem:
				NOGNCLIGIMG(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GPMKJNDHDCP_DecoItemBg:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OKPAJOALDCG_DecoItemObj:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MCKHJLHKMJD_DecoItemChara:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ICIMCGOJEMD_StampItemSerif:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.BMMBLLOKNPF_DecoItemSp:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.OOMMOOIIPJE_DecoItemPoster:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GGEFMAAOMFH_StampItemChara:
				FLFGJFDBEAB(_AHEFHIMGIBI_PlayerData, _HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem:
				IJGFIAGIINJ(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CFLFPPDMFAE_RaidItem:
				ACODICAMEGB(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem:
				PCJFOILKCOP(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem:
				JHDCJPEPDIC(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg:
				DBHOKBOGDNB(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
				break;
		}
	}

	//// RVA: 0x146FF9C Offset: 0x146FF9C VA: 0x146FF9C
	public bool HMDCGPGGOBA_IsAddItemOverflow(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category _HHACNFODNEF_ItemCategory, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		switch(_HHACNFODNEF_ItemCategory)
		{
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit:
				return PBOGGAGPECG(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_5_Costume:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_6_Valkyrie:
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg:
				return true;
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem:
				return ALBIIKAIILG(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem:
				return BKLKPGCDMBE(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket:
				return KMNEKFLHAMN(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.GIMBFBNKPNO_CompoItem:
				return FODKDOCADJI(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem:
				return LDCIPFEAOAD(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket:
				return MFNLHPELAOF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal:
				return EJPHHJFMAPE(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.LLFAAOHPMIC_EventGachaTicket:
				return EJKKIHJDOKF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem:
				return POCBGCBPBGD(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem:
				return EBFPNOMLJCN(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem:
				return EHMCNIGGPNO(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem:
				return GJGFKFFPLAB(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_24_LimitedItem:
				return PIHDONDGHMH(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem:
				return DAHPCLHIAKP(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem:
				return OHNDBOLGLFF(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CFLFPPDMFAE_RaidItem:
				return BGBJMNELGLC(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
			case EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem:
				return BDFAHPBDGPJ(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count);
		}
		return false;
	}

	//// RVA: 0x1471CE0 Offset: 0x1471CE0 VA: 0x1471CE0
	//private void NNJGNMFMAKN(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x1471CE4 Offset: 0x1471CE4 VA: 0x1471CE4
	//private bool GHJAHGPACPI(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146A5DC Offset: 0x146A5DC VA: 0x146A5DC
	private void BOBHHEOBAJF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		int idx = 0;
		if (_MHFBCINOJEE_Num - 1 > 0)
			idx = _MHFBCINOJEE_Num - 1;
		int a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NMJEDFNPIPL_UcItem.CDENCMNHNGA_table[idx].JBGEEPFKIGG_val;
		a *= _HMFFHLPNMPH_count;
		if (a + _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.NFHLDFJIBKI_have_uc > 99999999)
			MPHIICNDGDH = true;
		_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.ENEMPFLFEHP_AddUc(a);
		CIKCPLCPKAO += a;
		_AHEFHIMGIBI_PlayerData.OEKEIGFAIGN_Counter.BDLNMOIOMHK_total.EJJAPFPJLHP_AddUc(a);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ACGHELNGNGK_UnionCredit, idx + 1, a, _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.NFHLDFJIBKI_have_uc, 0);
	}

	//// RVA: 0x1470158 Offset: 0x1470158 VA: 0x1470158
	private bool PBOGGAGPECG(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if (_MHFBCINOJEE_Num > 0)
			_MHFBCINOJEE_Num--;
		DGDIEDDPNNG_UcItem.FCPCMPLGJNP dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NMJEDFNPIPL_UcItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num];
		return _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.NFHLDFJIBKI_have_uc + dbItem.JBGEEPFKIGG_val * _HMFFHLPNMPH_count > 99999999;
	}

	//// RVA: 0x146A878 Offset: 0x146A878 VA: 0x146A878
	private void IKFHPLBCMHN(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count, int ONMCOJPNBAO/* = 0*/)
	{
		MLIBEPGADJH_Scene.KKLDOOJBJMN dbScene = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
        MMPBPOIFDAF_Scene.PMKOFEIONEG saveScene = _AHEFHIMGIBI_PlayerData.PNLOINMCCKH_Scene.OPIBAPEGCLA_Scenes[_MHFBCINOJEE_Num - 1];
		int rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num);
		int mlt = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.HNMMJINNHII_Game.GENHLFPKOEE(rarity, dbScene.MCCIFLKCNKO_Feed);
		HLEMBNOMOGM = 0;
		IKBLCEFCGDE_LastLuck = 0;
		PJBJCBEMEEC = 0;
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
		if(!saveScene.OFNNNEMCJNN())
		{
			if(dbScene.KELFCMEOPPM_EpisodeId != 0)
			{
				bool b = false;
				for(int i = 0; i < FJKAMPIMFLP.Count; i++)
				{
					b |= FJKAMPIMFLP[i].KELFCMEOPPM_EpisodeId == dbScene.KELFCMEOPPM_EpisodeId;
				}
				if(!b)
				{
					OILCOECKMOO data = new OILCOECKMOO();
					data.KELFCMEOPPM_EpisodeId = dbScene.KELFCMEOPPM_EpisodeId;
					data.DNBFMLBNAEE_point = PIGBBNDPPJC.GMDHJBGLBEI(dbScene.KELFCMEOPPM_EpisodeId, _AHEFHIMGIBI_PlayerData);
					FJKAMPIMFLP.Add(data);
				}
				OCLHKHAMDHF_Episode.JEHNEEBBDBO_EpisodeInfo saveEp = _AHEFHIMGIBI_PlayerData.NGHJPEIKLJL_Episode.BBAJKJPKOHD_EpisodeList[dbScene.KELFCMEOPPM_EpisodeId - 1];
				if(saveEp.BEBJKJKBOGH_date == 0)
				{
					NNDMIOEKKMM_NewEpisode.Add(dbScene.KELFCMEOPPM_EpisodeId);
					saveEp.LHMOAJAIJCO_is_new = true;
					saveEp.BEBJKJKBOGH_date = time;
				}
			}
			bool b2 = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture);
			int maxPoster = 50;
			if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database != null && 
				IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem != null)
			{
				maxPoster = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.LPJLEHAJADA_GetIntParam("poster_have_max", 50);
			}
			for(int i = 0; i < _HMFFHLPNMPH_count; i++)
			{
				HLEMBNOMOGM = _MHFBCINOJEE_Num;
				PJIPCABDHCI++;
				bool b3 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.FDIOFBGJKNO(_MHFBCINOJEE_Num) && b2;
				if(b3)
				{
					int e = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ECNHDEHADGL_Scene.KBEGPJEBFMA(_MHFBCINOJEE_Num);
					if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.FCBBIEPBDBA(e))
					{
						_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.HHCMHDKKFNF_SetPstVer(e);
					}
				}
				if(!saveScene.IHIAFIHAAPO_Unlocked)
				{
					if(!dbScene.FBJDHLGODPP_Sngl)
					{
						saveScene.DDLEICINOHK_Unlock(time, ONMCOJPNBAO);
						IKBLCEFCGDE_LastLuck = 0;
						PJBJCBEMEEC = 0;
						GPPAIFNBHDP data = new GPPAIFNBHDP();
						data.BCCHOBPJJKE_SceneId = _MHFBCINOJEE_Num;
						data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
						data.INDDJNMPONH_type = 1;
						data.JKGFBFPIMGA_Rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_Rarity;
						data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_Rarity;
						data.OGPKHGEMLMP = b3;
						FIGHNFKAMGI.Add(data);
						//joined_r0x0146b3fc;
						if(b3)
						{
							//LAB_0146b66c
							saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_NumBoard);
						}
					}
					else
					{
						saveScene.DJNPIJPHKKJ(time, ONMCOJPNBAO);
						IKBLCEFCGDE_LastLuck = 0;
						GPPAIFNBHDP data = new GPPAIFNBHDP();
						data.BCCHOBPJJKE_SceneId = _MHFBCINOJEE_Num;
						data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
						data.INDDJNMPONH_type = 1;
						data.JKGFBFPIMGA_Rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_Rarity + 1;
						data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_Rarity + 1;
						data.OGPKHGEMLMP = b3;
						PJBJCBEMEEC = saveScene.JPIPENJGGDD_NumBoard;
						data.JPIPENJGGDD_NumBoard = PJBJCBEMEEC;
						FIGHNFKAMGI.Add(data);
						if(b3)
						{
							//LAB_0146b66c;
							saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_NumBoard);
						}
					}
				}
				else
				{
					GPPAIFNBHDP data = new GPPAIFNBHDP();
					data.BCCHOBPJJKE_SceneId = _MHFBCINOJEE_Num;
					data.OLGCDLJFMDH_Sngl = dbScene.FBJDHLGODPP_Sngl;
					if(saveScene.JPIPENJGGDD_NumBoard == 0)
					{
						data.INDDJNMPONH_type = 3;
						data.JPIPENJGGDD_NumBoard = saveScene.JPIPENJGGDD_NumBoard;
						data.JKGFBFPIMGA_Rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_Rarity;
					}
					else
					{
						data.INDDJNMPONH_type = 4;
						data.JPIPENJGGDD_NumBoard = saveScene.JPIPENJGGDD_NumBoard;
						data.JKGFBFPIMGA_Rarity = EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num);
						data.MPGNHFDGOBO_PrevRarity = data.JKGFBFPIMGA_Rarity + 1;
					}
					data.HNNAODKJGPD_NextRarity = data.JKGFBFPIMGA_Rarity + 1;
					b3 = b3 && saveScene.JPIPENJGGDD_NumBoard < maxPoster;
					data.OGPKHGEMLMP = b3;
					FIGHNFKAMGI.Add(data);
					saveScene.JPIPENJGGDD_NumBoard++;
					saveScene.BEBJKJKBOGH_date = time;
					dbScene.AGOEDLNOHND(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.JEMMMJEJLNL_Board, saveScene.EMOJHJGHJLN_Sb, saveScene.JPIPENJGGDD_NumBoard, mlt);
					PJBJCBEMEEC = saveScene.JPIPENJGGDD_NumBoard;
					IKBLCEFCGDE_LastLuck = saveScene.MJBODMOLOBC_luck;
					//joined_r0x0146b3fc
					if(b3)
					{
						//LAB_0146b66c
						saveScene.OEBOPKCCEEO(saveScene.JPIPENJGGDD_NumBoard);
					}
				}
			}
			if(GNGMCIAIKMA.HHCJCDFCLOB != null)
			{
				GNGMCIAIKMA.HHCJCDFCLOB.GJENEJOANEL(_AHEFHIMGIBI_PlayerData, DKFJADMCNPI.NLKCMNHOBAI.NGDJIJOIPIB/*9*/, 0, _HMFFHLPNMPH_count);
				GNGMCIAIKMA.HHCJCDFCLOB.HEFIKPAHCIA_UpdateMission(null, -1);
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveScene.JPIPENJGGDD_NumBoard, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.MHKFDBLMOGF_Scene, _MHFBCINOJEE_Num));
		}
	}

	//// RVA: 0x14702EC Offset: 0x14702EC VA: 0x14702EC
	//private bool LOOAENCCAPL(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146BF3C Offset: 0x146BF3C VA: 0x146BF3C
	private void ICHGJENIAMF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		EGOLBAPFHHD_Common.OFAPDOKONML growItem = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.KBMDMEEMGLK_grow_item[_MHFBCINOJEE_Num - 1];
		int cnt = growItem.BFINGCJHOHI_cnt;
		if(cnt + _HMFFHLPNMPH_count < 100000)
		{
			growItem.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
		}
		else
		{
			growItem.BFINGCJHOHI_cnt = 99999;
			MPHIICNDGDH = true;
		}
		HAPENODDGOC[_MHFBCINOJEE_Num - 1] += _HMFFHLPNMPH_count;
		INOAGFJHBBH += _HMFFHLPNMPH_count;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, growItem.BFINGCJHOHI_cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, _MHFBCINOJEE_Num));
	}

	//// RVA: 0x1470304 Offset: 0x1470304 VA: 0x1470304
	private bool ALBIIKAIILG(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		return 99999 < _HMFFHLPNMPH_count + _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.KBMDMEEMGLK_grow_item[_MHFBCINOJEE_Num - 1].BFINGCJHOHI_cnt;
	}

	//// RVA: 0x146B7F8 Offset: 0x146B7F8 VA: 0x146B7F8
	private void DPFKEPHOBKL(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
        EBFLJMOCLNA_Costume.ILFJDCICIKN cos = _AHEFHIMGIBI_PlayerData.BEKHNNCGIEL_Costume.FABAGMLEKIB_CostumeList[_MHFBCINOJEE_Num - 1];
		if(!cos.FJODMPGPDDD_Unlocked)
		{
			cos.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			cos.CADENLBDAEB_IsNew = true;
			_AHEFHIMGIBI_PlayerData.BEKHNNCGIEL_Costume.BJGLMIDBKKB(_MHFBCINOJEE_Num);
			if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.JAHFLLONDCN(_MHFBCINOJEE_Num, 0))
				{
					int a1 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MFPNGNMFEAL_Costume.FLFLMHDEBOL(_MHFBCINOJEE_Num);
					if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.HOGBPAGEJKO(a1))
					{
						_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GCCOOJJHIAM_SetTrsVer(a1);
					}
				}
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.KBHGPMNGALJ_5_Costume, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 1, 0);
		}
    }

	//// RVA: 0x14702F4 Offset: 0x14702F4 VA: 0x14702F4
	//private bool FAGJNOGABJB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146BBBC Offset: 0x146BBBC VA: 0x146BBBC
	private void GAFDHKHLNBA(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
        OIGEIIGKMNH_Valkyrie.HLNPGNNPCGO_ValkyrieInfo valk = _AHEFHIMGIBI_PlayerData.JJFFBDLIOCF_Valkyrie.CNGNBKNBKGI_ValkList[_MHFBCINOJEE_Num - 1];
        if (!valk.FJODMPGPDDD_Unlocked)
		{
			valk.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			valk.CADENLBDAEB_IsNew = true;
			if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PEOALFEGNDH_Valkyrie.AAACOMKNJJJ(_MHFBCINOJEE_Num))
				{
					int a1 = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PEOALFEGNDH_Valkyrie.MGKNLBJCJCK(_MHFBCINOJEE_Num);
					if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.CDDLPADLJNG(a1))
					{
						_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.HKAMGHBKNBH_SetDvfVer(a1);
					}
				}
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.PFIOMNHDHCO_6_Valkyrie, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 1, 0);
		}
	}

	//// RVA: 0x14702FC Offset: 0x14702FC VA: 0x14702FC
	//private bool HGALJPLIKNE(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146C220 Offset: 0x146C220 VA: 0x146C220
	private void GFNNJKJGEGA(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		KIICLPJJBNL_EpiItem.NKGPGMOHAFM dbEp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NEGGMILDEEF_EpiItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.AMCANGCIBEG saveCommon = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GJODJNIHKKF_epi_item[dbEp.PPFNGGCBJKC_id - 1];
		if(saveCommon.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count < 10000)
		{
			saveCommon.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
		}
		else
		{
			saveCommon.BFINGCJHOHI_cnt = 9999;
			MPHIICNDGDH = true;
		}
		JLCNBOKABJL[dbEp.PPFNGGCBJKC_id - 1] += _HMFFHLPNMPH_count;
		LNOEDPPJAHC = 0;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MEDAKGBKIMO_EpisodeItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveCommon.BFINGCJHOHI_cnt, 0);
	}

	//// RVA: 0x1470404 Offset: 0x1470404 VA: 0x1470404
	private bool BKLKPGCDMBE(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		KIICLPJJBNL_EpiItem.NKGPGMOHAFM dbEp = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NEGGMILDEEF_EpiItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.AMCANGCIBEG saveEp = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GJODJNIHKKF_epi_item[dbEp.PPFNGGCBJKC_id - 1];
		return _HMFFHLPNMPH_count + saveEp.BFINGCJHOHI_cnt > 9999;
	}

	//// RVA: 0x146C554 Offset: 0x146C554 VA: 0x146C554
	private void KNBGNFDFEON(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		HGLPLKKBBOL_EventItem.JMCDEDCMCJE dbEvItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.DHOFNBMPBAG_EventItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_6_Counting, false);
		if(ev != null)
		{
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.EMOLGEDEEJP_EventItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 0, dbEvItem.EKLIPGELKCL_Rarity);
			PPBHHLGPMBK[dbEvItem.EKLIPGELKCL_Rarity - 1] = _MHFBCINOJEE_Num;
			IONINNDIAFO[dbEvItem.EKLIPGELKCL_Rarity - 1] += _HMFFHLPNMPH_count;
			JNEMAOPELPE += dbEvItem.JBGEEPFKIGG_val * _HMFFHLPNMPH_count;
			CNONCDLNIED += _HMFFHLPNMPH_count;
		}
	}

	//// RVA: 0x146C830 Offset: 0x146C830 VA: 0x146C830
	private void CHKDGBJDBEF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		ABBOEIPOBLJ_EventTicket.CBDACMFFHJC dbEv = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KHPOJKHKLEM_EventTicket.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_6_Counting, false);
		if(ev != null)
		{
			ev.HPENJEOAMBK_SetTicket(EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket, _MHFBCINOJEE_Num), _HMFFHLPNMPH_count, _AHEFHIMGIBI_PlayerData);
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CLMIJKACELE_EventTicket, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, ev.AELBIEDNPGB_GetTicketCount(_AHEFHIMGIBI_PlayerData), 1);
			if(ev.HIDHLFCBIDE_EventType == OHCAABOMEOF.KGOGMKMBCPP_EventType.AOPKACCDKPA_EventCollection)
			{
				;
			}
			else if(ev.HIDHLFCBIDE_EventType == OHCAABOMEOF.KGOGMKMBCPP_EventType.BNECMLPHAGJ_EventGoDiva)
			{
				_AHEFHIMGIBI_PlayerData.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty++;
				if(_AHEFHIMGIBI_PlayerData.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty <= 999999999)
					return;
				_AHEFHIMGIBI_PlayerData.JMPNGBGNCFO_EventGoDiva.AFNJCFEKFDD_Dirty = 0;
			}
			else
			{
				return;
			}
		}
		else
		{
			if(_AHEFHIMGIBI_PlayerData.MBAHCFLBDHN_EventCollection == null)
				return;
		}
		_AHEFHIMGIBI_PlayerData.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty++;
		if(_AHEFHIMGIBI_PlayerData.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty <= 999999999)
			return;
		_AHEFHIMGIBI_PlayerData.MBAHCFLBDHN_EventCollection.AFNJCFEKFDD_Dirty = 0;
	}

	//// RVA: 0x14705D8 Offset: 0x14705D8 VA: 0x14705D8
	private bool KMNEKFLHAMN(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		ABBOEIPOBLJ_EventTicket.CBDACMFFHJC dbEv = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KHPOJKHKLEM_EventTicket.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		IKDICBBFBMI_EventBase ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.MKBJOOAILBB_GetEventByStatus(KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_6_Counting, false);
		if(ev != null)
		{
			return ev.AELBIEDNPGB_GetTicketCount(null) + _HMFFHLPNMPH_count > 9999;
		}
		return false;
	}

	//// RVA: 0x1470774 Offset: 0x1470774 VA: 0x1470774
	//private bool KBDCEEDMKGD(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146CC48 Offset: 0x146CC48 VA: 0x146CC48
	private void HPBIMHODDAP(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		IHGBPAJMJFK_Emblem.AKJPPHFGEFG_EmblemInfo embl = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBNBNAFGMDE_Emblem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		JGGLDGNKELI_Emblem.AAHAAJEJNLJ saveEblm = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.OFAJDLJBMEM_Emblem.MDKOHOCONKE[_MHFBCINOJEE_Num - 1];
		if(_MHFBCINOJEE_Num < 2)
			return;
		for(int i = 0; i < _HMFFHLPNMPH_count; i++)
		{
			if(!saveEblm.FJODMPGPDDD_Unlocked)
			{
				saveEblm.FHCAFLCLGAA_em_cnt = 0;
				saveEblm.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			}
			else
			{
				if(saveEblm.FHCAFLCLGAA_em_cnt < 99)
				{
					saveEblm.FHCAFLCLGAA_em_cnt++;
				}
			}
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MNCJMDDAFJB_EmblemItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveEblm.FHCAFLCLGAA_em_cnt + 1, 0);
		ILCCJNDFFOB.HHCJCDFCLOB.COBCMOAAAFF(_MHFBCINOJEE_Num);
	}

	//// RVA: 0x147077C Offset: 0x147077C VA: 0x147077C
	public bool FODKDOCADJI(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		HHPEMHHCKBE_Compo.MLMDKHBFOJM dbCompo = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ALFKMKICDPP_Compo.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		for(int i = 0; i < dbCompo.JCJGGHGIKIJ(); i++)
		{
			int id = dbCompo.CBLLFCGEJAI(i);
			if(HMDCGPGGOBA_IsAddItemOverflow(_AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(id), EKLNMHFCAOI.DEACAHNLMNI_getItemId(id), _HMFFHLPNMPH_count * dbCompo.HBJMCLGKLBA(i)))
				return true;
		}
		return false;
	}

	//// RVA: 0x146CFFC Offset: 0x146CFFC VA: 0x146CFFC
	public void PKEBBIAIHEK(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
        HHPEMHHCKBE_Compo.MLMDKHBFOJM dbData = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ALFKMKICDPP_Compo.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		for(int i = 0; i < dbData.JCJGGHGIKIJ(); i++)
		{
			int fullItemId = dbData.CBLLFCGEJAI(i);
            EKLNMHFCAOI.FKGCBLHOOCL_Category itemCat = EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(fullItemId);
			int itemId = EKLNMHFCAOI.DEACAHNLMNI_getItemId(fullItemId);
			if(itemCat == EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem)
			{
				ICHGJENIAMF(_AHEFHIMGIBI_PlayerData, itemId, dbData.HBJMCLGKLBA(i) * _HMFFHLPNMPH_count);
			}
        }
    }

	//// RVA: 0x146D200 Offset: 0x146D200 VA: 0x146D200
	private void OAOJFIOACEL(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		BOKMNHAFJHF_Sns.KEIGMAOCJHK_Talk dbSns = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OMGFKMANMAB_Sns.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
        DDEMMEPBOIA_Sns.EFIFBJGKPJF saveSns = _AHEFHIMGIBI_PlayerData.FLHMJHBOBEA_Sns.HAJEJPFGILG[_MHFBCINOJEE_Num - 1];
		saveSns.PMKJFKJFDOC_Itm = 1;
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.KNHFAHFCCBK_SnsItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 1, 1);
	}

	//// RVA: 0x146D3CC Offset: 0x146D3CC VA: 0x146D3CC
	private void PGMIPBPEDDD(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		List<EGOLBAPFHHD_Common.FKLHGOGJOHH> l = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.KFEBOFKAHAJ_EngItem;
		JKDKODAPGBJ_EnergyItem.GFGCCICHBHK enItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KOPOGNLKAEN_EnergyItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.FKLHGOGJOHH saveEn = l[_MHFBCINOJEE_Num - 1];
		if(enItem.DOOGFEGEKLG_max < saveEn.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count)
		{
			saveEn.BFINGCJHOHI_cnt = enItem.DOOGFEGEKLG_max;
			saveEn.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			MPHIICNDGDH = true;
		}
		else
		{
			saveEn.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			saveEn.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveEn.BFINGCJHOHI_cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.DMMIIBCMCFG_EnergyItem, _MHFBCINOJEE_Num));
	}

	//// RVA: 0x147099C Offset: 0x147099C VA: 0x147099C
	private bool LDCIPFEAOAD(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		JKDKODAPGBJ_EnergyItem.GFGCCICHBHK item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.KOPOGNLKAEN_EnergyItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.FKLHGOGJOHH saveItem = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.KFEBOFKAHAJ_EngItem[_MHFBCINOJEE_Num - 1];
		return item.DOOGFEGEKLG_max < _HMFFHLPNMPH_count + saveItem.BFINGCJHOHI_cnt;
	}

	//// RVA: 0x146DADC Offset: 0x146DADC VA: 0x146DADC
	private void JNABIIIMOPE(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		HHFFOACILKG_Medal.HCFJGDFMHOJ dbMedal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ICICKEBMEFA_Medal.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.GLBBNDKGEOC saveMedal = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.MHKJEBNOPIM_Medal[_MHFBCINOJEE_Num - 1];
		int cnt = saveMedal.BFINGCJHOHI_cnt;
		if(cnt + _HMFFHLPNMPH_count < 100000000)
		{
			saveMedal.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			saveMedal.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
			if(dbMedal.IBAKPKKEDJM_month > 0 && dbMedal.IBAKPKKEDJM_month < 13)
			{
				_AHEFHIMGIBI_PlayerData.OEKEIGFAIGN_Counter.BDLNMOIOMHK_total.KPNLMLPFKMJ_AddMedal(_HMFFHLPNMPH_count);
			}
		}
		else
		{
			saveMedal.BFINGCJHOHI_cnt = 99999999;
			saveMedal.BEBJKJKBOGH_date = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			MPHIICNDGDH = true;
		}
		if(GNGMCIAIKMA.HHCJCDFCLOB != null)
		{
			GNGMCIAIKMA.HHCJCDFCLOB.GJENEJOANEL(DKFJADMCNPI.NLKCMNHOBAI.EHEDFAMGLDP_10, 0, _HMFFHLPNMPH_count, null);
			GNGMCIAIKMA.HHCJCDFCLOB.HEFIKPAHCIA_UpdateMission(null, -1);
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveMedal.BFINGCJHOHI_cnt, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.ADCAAALBAIF_Medal, _MHFBCINOJEE_Num));
	}

	//// RVA: 0x1470BD8 Offset: 0x1470BD8 VA: 0x1470BD8
	private bool EJPHHJFMAPE(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		HHFFOACILKG_Medal.HCFJGDFMHOJ dbMedal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ICICKEBMEFA_Medal.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.GLBBNDKGEOC saveMedal = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.MHKJEBNOPIM_Medal[_MHFBCINOJEE_Num - 1];
		return _HMFFHLPNMPH_count + saveMedal.BFINGCJHOHI_cnt > 99999999;
	}

	//// RVA: 0x146D918 Offset: 0x146D918 VA: 0x146D918
	private void NFDOJPCKFAK(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket + _HMFFHLPNMPH_count < 10000)
		{
			_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket += _HMFFHLPNMPH_count;
		}
		else
		{
			_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket = 9999;
			MPHIICNDGDH = true;
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket, EKLNMHFCAOI.FABCKNDLPDH_GetItemRarity(EKLNMHFCAOI.FKGCBLHOOCL_Category.IGIFMNJADEC_MvTicket, _MHFBCINOJEE_Num));
	}

	//// RVA: 0x1470B70 Offset: 0x1470B70 VA: 0x1470B70
	private bool MFNLHPELAOF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		return _HMFFHLPNMPH_count + _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GKKDNOFMJJN_NumTicket > 9999;
	}

	//// RVA: 0x146E0F4 Offset: 0x146E0F4 VA: 0x146E0F4
	private void IFDDILLJLFO(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		JNGINLMOJKH_EventGachaTicket.JDNAAGCHCOH dbEvGacha = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NKOKFIMNCJM_EventGachaTicket.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		if(_AHEFHIMGIBI_PlayerData.MMAIJOCPJHP_EventBoxGacha != null)
		{
            ALIPBIMCAPN_EventBoxGacha.GLNFOMDKJJH d = _AHEFHIMGIBI_PlayerData.MMAIJOCPJHP_EventBoxGacha.FBCJICEPLED[dbEvGacha.EJPKFBHNDGI_ev_no - 1];
			if(dbEvGacha.DOOGFEGEKLG_max < d.BGCOKABBHNC_GachaTicketCnt + _HMFFHLPNMPH_count)
			{
				d.BGCOKABBHNC_GachaTicketCnt = dbEvGacha.DOOGFEGEKLG_max;
			}
			else
			{
				d.BGCOKABBHNC_GachaTicketCnt += _HMFFHLPNMPH_count;
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.LLFAAOHPMIC_EventGachaTicket, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, d.BGCOKABBHNC_GachaTicketCnt, 0);
        }
	}

	//// RVA: 0x1470D90 Offset: 0x1470D90 VA: 0x1470D90
	private bool EJKKIHJDOKF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		JNGINLMOJKH_EventGachaTicket.JDNAAGCHCOH dbEvGacha = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.NKOKFIMNCJM_EventGachaTicket.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		if(_AHEFHIMGIBI_PlayerData.MMAIJOCPJHP_EventBoxGacha != null)
		{
			return dbEvGacha.DOOGFEGEKLG_max < _AHEFHIMGIBI_PlayerData.MMAIJOCPJHP_EventBoxGacha.FBCJICEPLED[dbEvGacha.EJPKFBHNDGI_ev_no - 1].BGCOKABBHNC_GachaTicketCnt + _HMFFHLPNMPH_count;
		}
		return false;
	}

	//// RVA: 0x146E3C0 Offset: 0x146E3C0 VA: 0x146E3C0
	private void LCIPJMMEMPI(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_MHFBCINOJEE_Num > 0)
		{
			EGOLBAPFHHD_Common.DEEGPPKGGLK d = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.DHJFHILPKLB_IntimacyPresent[_MHFBCINOJEE_Num - 1];
			if(d.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count < 10000)
				d.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
			else
			{
				d.BFINGCJHOHI_cnt = 9999;
				MPHIICNDGDH = true;
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DLBHNNOHLMM_PresentItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, d.BFINGCJHOHI_cnt, 0);
		}
	}

	//// RVA: 0x1470FA0 Offset: 0x1470FA0 VA: 0x1470FA0
	private bool POCBGCBPBGD(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_MHFBCINOJEE_Num < 1)
			return false;
		return _HMFFHLPNMPH_count + _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.DHJFHILPKLB_IntimacyPresent[_MHFBCINOJEE_Num - 1].BFINGCJHOHI_cnt > 9999;
	}

	//// RVA: 0x146E648 Offset: 0x146E648 VA: 0x146E648
	private void IAFODMHCKNH(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_MHFBCINOJEE_Num == 13)
		{
			JHDCJPEPDIC(_AHEFHIMGIBI_PlayerData, 1, _HMFFHLPNMPH_count);
		}
		else
		{
			PPNFHHPJOKK_SpItem.JBBIPIAABOJ item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OOEPHOEFBNL_SpItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
			EGOLBAPFHHD_Common.KPMNLAHNDAI saveItem = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.BBFIGEOBOMB_SpItem[_MHFBCINOJEE_Num - 1];
			if(saveItem != null)
			{
				if(saveItem.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count > item.DOOGFEGEKLG_max)
				{
					saveItem.BFINGCJHOHI_cnt = item.DOOGFEGEKLG_max;
				}
				else
				{
					saveItem.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
				}
				if(_MHFBCINOJEE_Num == 8)
				{
					_AHEFHIMGIBI_PlayerData.OEKEIGFAIGN_Counter.BDLNMOIOMHK_total.FNLAFLEEAHC(_HMFFHLPNMPH_count);
				}
				NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.FMIIHMHKJDI_SpItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, saveItem.BFINGCJHOHI_cnt, 0);
			}
		}
	}

	//// RVA: 0x14710A4 Offset: 0x14710A4 VA: 0x14710A4
	private bool EBFPNOMLJCN(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_MHFBCINOJEE_Num == 13)
		{
			return BDFAHPBDGPJ(_AHEFHIMGIBI_PlayerData, 1, _HMFFHLPNMPH_count);
		}
		else
		{
			PPNFHHPJOKK_SpItem.JBBIPIAABOJ item = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.OOEPHOEFBNL_SpItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
			EGOLBAPFHHD_Common.KPMNLAHNDAI saveItem = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.BBFIGEOBOMB_SpItem[_MHFBCINOJEE_Num - 1];
			if(saveItem == null)
				return false;
			return item.DOOGFEGEKLG_max < _HMFFHLPNMPH_count + saveItem.BFINGCJHOHI_cnt;
		}
	}

	//// RVA: 0x146E8FC Offset: 0x146E8FC VA: 0x146E8FC
	private void NKJHEGBDMHJ(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		EGOLBAPFHHD_Common.PGENIOHDCDI d = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.EFBKCNNFIPJ(_MHFBCINOJEE_Num);
		if(d != null)
		{
			if (d.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count < 10000)
				d.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
			else
				d.BFINGCJHOHI_cnt = 9999;
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.NEIIGCODGBA_CostumeItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, d.BFINGCJHOHI_cnt, 0);
		}
	}

	//// RVA: 0x1471294 Offset: 0x1471294 VA: 0x1471294
	private bool EHMCNIGGPNO(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.GOGFKAECFIP_CosItem.EEOADCECNOM_GetCostume(_MHFBCINOJEE_Num);
		EGOLBAPFHHD_Common.PGENIOHDCDI p = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.EFBKCNNFIPJ(_MHFBCINOJEE_Num);
		if(p != null)
		{
			return _HMFFHLPNMPH_count + p.BFINGCJHOHI_cnt > 9999;
		}
		return false;
	}

	//// RVA: 0x146EAAC Offset: 0x146EAAC VA: 0x146EAAC
	private void EALJGONPDJD(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
		for(int i = 0; i < _HMFFHLPNMPH_count; i++)
		{
			_AHEFHIMGIBI_PlayerData.DPNKPPBEAGJ_RareUpItem.APIEKGBMBPA(time, false);
		}
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CIOGEKJNMBB_RareUpItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, _AHEFHIMGIBI_PlayerData.DPNKPPBEAGJ_RareUpItem.LDLCGGACHGA(time), 0);
	}

	//// RVA: 0x14713EC Offset: 0x14713EC VA: 0x14713EC
	private bool GJGFKFFPLAB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
		return _AHEFHIMGIBI_PlayerData.DPNKPPBEAGJ_RareUpItem.LDLCGGACHGA(time) + _HMFFHLPNMPH_count > 9;
	}

	//// RVA: 0x146EC38 Offset: 0x146EC38 VA: 0x146EC38
	private void NGIHAOOFEPG(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		EGLOKAEIHCB_LimitedItem.DEOCBHAGEEH d = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.IHPFCIJKFIC_LimitedItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		if(_AHEFHIMGIBI_PlayerData.AFHFIPLOKMN_LimitedItem != null)
		{
			long t = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			for(int i = 0; i < _HMFFHLPNMPH_count; i++)
			{
				_AHEFHIMGIBI_PlayerData.AFHFIPLOKMN_LimitedItem.CPIICACGNBH_AddItem(_MHFBCINOJEE_Num, t, false);
			}
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.DLOPEFGOAPD_24_LimitedItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, _AHEFHIMGIBI_PlayerData.AFHFIPLOKMN_LimitedItem.HPPKOGKNKMH(_MHFBCINOJEE_Num, t), 0);
		}
	}

	//// RVA: 0x1471538 Offset: 0x1471538 VA: 0x1471538
	private bool PIHDONDGHMH(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		EGLOKAEIHCB_LimitedItem.DEOCBHAGEEH dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.IHPFCIJKFIC_LimitedItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		if(_AHEFHIMGIBI_PlayerData.AFHFIPLOKMN_LimitedItem != null)
		{
			long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			return _HMFFHLPNMPH_count + _AHEFHIMGIBI_PlayerData.AFHFIPLOKMN_LimitedItem.HPPKOGKNKMH(_MHFBCINOJEE_Num, time) > dbItem.DOOGFEGEKLG_max;
		}
		return false;
	}

	//// RVA: 0x146FA7C Offset: 0x146FA7C VA: 0x146FA7C
	private void JHDCJPEPDIC(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem != null)
		{
			long time = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime();
			JHAAHJNEBOG_LimitedCompoItem.AOBHKONKIPF dbItem = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MBAGKLJDKMH_LimitedCompoItem.OCMMLAOEPIG[_MHFBCINOJEE_Num - 1];
			int b = _AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.OPCIHPEIFFE(dbItem.PENIOLJHIPK);
			int a = _AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(dbItem.PENIOLJHIPK, time);
			if(b < a + _HMFFHLPNMPH_count)
				_HMFFHLPNMPH_count = b - a;
			if(_HMFFHLPNMPH_count > 0)
			{
				for(int i = 0; i < _HMFFHLPNMPH_count; i++)
				{
					_AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.CPIICACGNBH_AddItem(_MHFBCINOJEE_Num, time, false);
				}
				int c = _AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(_MHFBCINOJEE_Num, time);
				NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CKCPFLDGILD_LimitedCompoItem, _MHFBCINOJEE_Num,_HMFFHLPNMPH_count, c, 0);
			}
		}
	}

	//// RVA: 0x1471B74 Offset: 0x1471B74 VA: 0x1471B74
	private bool BDFAHPBDGPJ(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		if(_AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem == null)
			return false;
		else
		{
			return _AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.OPCIHPEIFFE(_MHFBCINOJEE_Num) < _HMFFHLPNMPH_count + _AHEFHIMGIBI_PlayerData.GJCOJBDOOJG_LimitedCompoItem.HPPKOGKNKMH(_MHFBCINOJEE_Num, NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime());
		}
	}

	//// RVA: 0x146EE80 Offset: 0x146EE80 VA: 0x146EE80
	private void NOGNCLIGIMG(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		_AHEFHIMGIBI_PlayerData.HMMNDKHKEBC_MonthlyPass.DGIBOADNFOI(_HMFFHLPNMPH_count);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.PJCJEOECLBK_MonthlyPassItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, _AHEFHIMGIBI_PlayerData.HMMNDKHKEBC_MonthlyPass.JAMCDEDFHHK_HotenCnt, 0);
	}

	//// RVA: 0x1471764 Offset: 0x1471764 VA: 0x1471764
	private bool DAHPCLHIAKP(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		return _AHEFHIMGIBI_PlayerData.HMMNDKHKEBC_MonthlyPass.JAMCDEDFHHK_HotenCnt + _HMFFHLPNMPH_count > 99;
	}

	//// RVA: 0x146F254 Offset: 0x146F254 VA: 0x146F254
	private void IJGFIAGIINJ(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		EGOLBAPFHHD_Common.GHOADMJCPFK d = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.MJAIFKFOPPI_ValItem[_MHFBCINOJEE_Num - 1];
		if(d != null)
		{
			if (d.BFINGCJHOHI_cnt + _HMFFHLPNMPH_count < 100000)
				d.BFINGCJHOHI_cnt += _HMFFHLPNMPH_count;
			else
				d.BFINGCJHOHI_cnt = 99999;
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.MABCLBNIOFA_ValkyrieItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, d.BFINGCJHOHI_cnt, 0);
		}
	}

	//// RVA: 0x146F73C Offset: 0x146F73C VA: 0x146F73C
	private void ACODICAMEGB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		NKOBMDPHNGP_EventRaidLobby ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.OEGDCBLNNFF(OHCAABOMEOF.KGOGMKMBCPP_EventType.MCGPGMGEPHG_EventRaidLobby, KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_6_Counting) as NKOBMDPHNGP_EventRaidLobby;
		if(ev != null)
		{
			NKBOMKGFGIO_EventRaidItem.PDPBHLDICEJ it = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ONOJBMDKBLE_EventRaidItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
			int num = Mathf.Clamp(ev.EHGKMLPCDBM_GetItemCount((XeApp.Game.Common.RaidItemConstants.Type) _MHFBCINOJEE_Num, _AHEFHIMGIBI_PlayerData) + _HMFFHLPNMPH_count, 0, it.DOOGFEGEKLG_max);
			ev.NCBELAFIPDN_SetItemCount((XeApp.Game.Common.RaidItemConstants.Type) _MHFBCINOJEE_Num, num, _AHEFHIMGIBI_PlayerData);
			NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.CFLFPPDMFAE_RaidItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, num, it.EKLIPGELKCL_Rarity);
		}
		_AHEFHIMGIBI_PlayerData.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty++;
		if(_AHEFHIMGIBI_PlayerData.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty > 1000000000)
		{
			_AHEFHIMGIBI_PlayerData.FHLMCCPCEAI_SaveHash.AFNJCFEKFDD_Dirty = 0;
		}
	}

	//// RVA: 0x1471974 Offset: 0x1471974 VA: 0x1471974
	private bool BGBJMNELGLC(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		NKOBMDPHNGP_EventRaidLobby ev = JEPBIIJDGEF_EventInfo.HHCJCDFCLOB.OEGDCBLNNFF(OHCAABOMEOF.KGOGMKMBCPP_EventType.MCGPGMGEPHG_EventRaidLobby, KGCNCBOKCBA.GNENJEHKMHD_EventStatus.EMAMLLFAOJI_6_Counting) as NKOBMDPHNGP_EventRaidLobby;
		if(ev != null)
		{
			NKBOMKGFGIO_EventRaidItem.PDPBHLDICEJ it = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.ONOJBMDKBLE_EventRaidItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
			return it.DOOGFEGEKLG_max < ev.EHGKMLPCDBM_GetItemCount((XeApp.Game.Common.RaidItemConstants.Type) _MHFBCINOJEE_Num, _AHEFHIMGIBI_PlayerData);
		}
		return false;
	}

	//// RVA: 0x14717C8 Offset: 0x14717C8 VA: 0x14717C8
	private bool OHNDBOLGLFF(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		INDEPDKCJDD_ValItem.NHJLDENJKBE dbVal = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.FBGKBGNIHGC_ValItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		EGOLBAPFHHD_Common.GHOADMJCPFK saveVal = _AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.MJAIFKFOPPI_ValItem[_MHFBCINOJEE_Num - 1];
		if(saveVal != null)
		{
			return _HMFFHLPNMPH_count + saveVal.BFINGCJHOHI_cnt > 99999;
		}
		return false;
	}

	//// RVA: 0x1471CFC Offset: 0x1471CFC VA: 0x1471CFC
	//private bool IJPBEIHHBHB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category _HHACNFODNEF_ItemCategory, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x146EF3C Offset: 0x146EF3C VA: 0x146EF3C
	private void FLFGJFDBEAB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category _HHACNFODNEF_ItemCategory, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		int num = EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, _HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, null);
		int max = EKLNMHFCAOI.AFEONHCADEL_GetMaxAllowed(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, _HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, null);
		int cnt = num + _HMFFHLPNMPH_count;
		if(max < cnt)
			cnt  = max;
		EKLNMHFCAOI.DPHGFMEPOCA_SetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, _HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, cnt, null);
		if(_HHACNFODNEF_ItemCategory == EKLNMHFCAOI.FKGCBLHOOCL_Category.BMMBLLOKNPF_DecoItemSp)
		{
			if(_AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.ADKJDHPEAJH(XeApp.Game.Common.GPFlagConstant.ID.IsDecolture))
			{
				int a = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.CHMNDNFMAGA(_MHFBCINOJEE_Num);
				if(a > -1)
				{
					if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.GAFDKEENNJO(a))
					{
						CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData.KCCLEHLLOFG_Common.JAHBNIMDNHJ_DMasVer(a);
					}
				}
			}
		}
		else if(_HHACNFODNEF_ItemCategory == EKLNMHFCAOI.FKGCBLHOOCL_Category.MCKHJLHKMJD_DecoItemChara)
		{
			IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EPAHOAKPAJJ_DecoItem.KDFMGDNOMHE(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num);
		}
		NGEPPDAOIBN(_HHACNFODNEF_ItemCategory, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, cnt, 0);
	}

	//// RVA: 0x146F450 Offset: 0x146F450 VA: 0x146F450
	private void PCJFOILKCOP(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		int num = EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, _MHFBCINOJEE_Num, null);
		int max = EKLNMHFCAOI.AFEONHCADEL_GetMaxAllowed(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, _MHFBCINOJEE_Num, null);
		int cnt = num + _HMFFHLPNMPH_count;
		if(cnt > max)
			cnt = max;
		EKLNMHFCAOI.DPHGFMEPOCA_SetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, _AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, _MHFBCINOJEE_Num, cnt, null);
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.ICJOEDJECAP_DecoSetItem, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, cnt, 0);
        BBLECJKKKLA_DecoSetItem.GJBPBKNHLHC_DecoSetItemInfo dbSet = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.MJALLIOHKEJ_DecoSetItem.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		for(int i = 0; i < dbSet.JJBNDDDGEAN_GetNumItems(); i++)
		{
			FLFGJFDBEAB(_AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(dbSet.FKNBLDPIPMC_GetItemCode(i)), EKLNMHFCAOI.DEACAHNLMNI_getItemId(dbSet.FKNBLDPIPMC_GetItemCode(i)), _HMFFHLPNMPH_count * dbSet.NKOHMLHLJGL_GetItemCount(i));
		}
    }

	//// RVA: 0x146FDB8 Offset: 0x146FDB8 VA: 0x146FDB8
	private void DBHOKBOGDNB(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count)
	{
		ALJHJDHNFFB_HomeBg.ADLLAFIDFAM dbBg = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.PFEKKPABPKL_HomeBg.CDENCMNHNGA_table[_MHFBCINOJEE_Num - 1];
		CGFNKMNBNBN.DPMCLJMIBDK(_AHEFHIMGIBI_PlayerData, _MHFBCINOJEE_Num, NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.FJDBNGEPKHL_Time.KMEFBNBFJHI_GetServerTime());
		NGEPPDAOIBN(EKLNMHFCAOI.FKGCBLHOOCL_Category.HGDPIAFBCGA_HomeBg, _MHFBCINOJEE_Num, _HMFFHLPNMPH_count, 1, 0);
	}

	//// RVA: 0x1471CD8 Offset: 0x1471CD8 VA: 0x1471CD8
	//private bool POKLFKEFCLM(BBHNACPENDM_ServerSaveData _AHEFHIMGIBI_PlayerData, int _MHFBCINOJEE_Num, int _HMFFHLPNMPH_count) { }

	//// RVA: 0x1471E30 Offset: 0x1471E30 VA: 0x1471E30
	public static string JKOAGEAPJHI(int _KIJAPOFAGPN_ItemId, int _HMFFHLPNMPH_count)
	{
		return JKOAGEAPJHI(EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(_KIJAPOFAGPN_ItemId), EKLNMHFCAOI.DEACAHNLMNI_getItemId(_KIJAPOFAGPN_ItemId), _HMFFHLPNMPH_count);
	}

	//// RVA: 0x1471ED8 Offset: 0x1471ED8 VA: 0x1471ED8
	public static string JKOAGEAPJHI(EKLNMHFCAOI.FKGCBLHOOCL_Category _INDDJNMPONH_type, int _JBGEEPFKIGG_val, int _HMFFHLPNMPH_count)
	{
		return EKLNMHFCAOI.INCKKODFJAP_GetItemName(_INDDJNMPONH_type, _JBGEEPFKIGG_val) + JpStringLiterals.StringLiteral_12037 + _HMFFHLPNMPH_count + EKLNMHFCAOI.NDBLEADIDLA(_INDDJNMPONH_type, _JBGEEPFKIGG_val);
	}

	//// RVA: 0x1471FCC Offset: 0x1471FCC VA: 0x1471FCC
	public static string JKOAGEAPJHI(int _KIJAPOFAGPN_ItemId, int _HMFFHLPNMPH_count, int OEBOKCMFMHG)
	{
		EKLNMHFCAOI.FKGCBLHOOCL_Category cat = EKLNMHFCAOI.BKHFLDMOGBD_GetItemCategory(_KIJAPOFAGPN_ItemId);
		int id = EKLNMHFCAOI.DEACAHNLMNI_getItemId(_KIJAPOFAGPN_ItemId);
		return KJFKHPMPLBC(EKLNMHFCAOI.INCKKODFJAP_GetItemName(cat, id), OEBOKCMFMHG) + JpStringLiterals.StringLiteral_12037 + _HMFFHLPNMPH_count.ToString() + EKLNMHFCAOI.NDBLEADIDLA(cat, id);
	}

	//// RVA: 0x14720E8 Offset: 0x14720E8 VA: 0x14720E8
	public static string KJFKHPMPLBC(string _OPFGFINHFCE_name, int OEBOKCMFMHG)
	{
		if (_OPFGFINHFCE_name.Length < OEBOKCMFMHG)
			return _OPFGFINHFCE_name;
		return _OPFGFINHFCE_name.Substring(0, OEBOKCMFMHG - 1) + JpStringLiterals.StringLiteral_12038;
	}

	//// RVA: 0x147219C Offset: 0x147219C VA: 0x147219C
	public string OLAICLNDMFF()
	{
		return JKOAGEAPJHI(KJOGOABBMNN, IHIJFEHOBOB, AAIAJEGOIHL);
	}
}
