
public class JOCIAMDFJHH
{
	private DAJBODHMLAB_DecoPublicSet HINDIMKCNFG; // 0x8
	private AHHPBMBBCFM_DecoPrivateSet AGLPDMEEOGC; // 0xC

	// RVA: 0x1BA2930 Offset: 0x1BA2930 VA: 0x1BA2930
	public JOCIAMDFJHH(DAJBODHMLAB_DecoPublicSet HINDIMKCNFG, AHHPBMBBCFM_DecoPrivateSet AGLPDMEEOGC)
	{
		this.HINDIMKCNFG = HINDIMKCNFG;
		this.AGLPDMEEOGC = AGLPDMEEOGC;
	}

	//// RVA: 0x1BA2958 Offset: 0x1BA2958 VA: 0x1BA2958
	public void HGDIEHFFLMO_LoadFromSlot(int IOPHIHFOOEP)
	{
		HINDIMKCNFG.LJMCPFACDGJ.BMGGKONLFIC_Copy(AGLPDMEEOGC.JBJHCJFOICD_SetArr[IOPHIHFOOEP]);
	}

	//// RVA: 0x1BA2A48 Offset: 0x1BA2A48 VA: 0x1BA2A48
	public void DKHCCBIOBPH_SaveToSlot(int KIDHLGLFFBJ)
	{
		if (KIDHLGLFFBJ < 0 || KIDHLGLFFBJ > 5)
			return;
		AGLPDMEEOGC.JBJHCJFOICD_SetArr[KIDHLGLFFBJ].BMGGKONLFIC_Copy(HINDIMKCNFG.LJMCPFACDGJ);
	}

	//// RVA: 0x1BA2B20 Offset: 0x1BA2B20 VA: 0x1BA2B20
	public void INBANHBGIFC_ResetSet(int KIDHLGLFFBJ)
	{
		if (KIDHLGLFFBJ < 0 || KIDHLGLFFBJ > 5)
			return;
		AGLPDMEEOGC.JBJHCJFOICD_SetArr[KIDHLGLFFBJ].KMBPACJNEOF_Reset();
	}

	//// RVA: 0x1BA2BDC Offset: 0x1BA2BDC VA: 0x1BA2BDC
	public void APOIDBODGGB_RenameSlot(int KIDHLGLFFBJ, string _OPFGFINHFCE_name)
	{
		if (KIDHLGLFFBJ < 0 || KIDHLGLFFBJ > 5)
			return;
		AGLPDMEEOGC.JBJHCJFOICD_SetArr[KIDHLGLFFBJ].CPOONLHIMKC_DecoRoomName = _OPFGFINHFCE_name;
	}

	//// RVA: 0x1BA2CA0 Offset: 0x1BA2CA0 VA: 0x1BA2CA0
	//public List<DAJBODHMLAB_DecoPublicSet.MMLACIFMNBN> JPPOALLHLKA() { }

	//// RVA: 0x1BA2A30 Offset: 0x1BA2A30 VA: 0x1BA2A30
	//private bool LMEKFGOFLBC(int IOPHIHFOOEP) { }
}
