using System.Collections;
using UnityEngine;
using System.Collections.Generic;
using System.Text;
using System;

public class KDHGBOOECKC
{
	public class NKMCJCAJIGD
	{
		private int ICPJNJLHKPB; // 0x8
		private int KDPLFFJOLFI; // 0xC

		// public int MLDPDLPHJPM { get; set; } 0xE7481C EJEKNOACOFD 0xE74830 DBBHJDGJOCA
		// public BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG { get; set; } 0xE74844 PCFFCOKAHBD 0xE74858 JBCALBBCBLF

		// RVA: 0xE74874 Offset: 0xE74874 VA: 0xE74874
		public void LHPDDGIJKNB()
		{
			ICPJNJLHKPB = 0x7138b4a5;
			KDPLFFJOLFI = 0x7138b4a5;
		}
	}

	public class JLLOKCFPOFH
	{
		private int EAJCFBCHIFB; // 0x8
		private int CNABOLBIBMH; // 0xC

		// public int EKLIPGELKCL { get; set; } 0xE72090 OEEHBGECGKL 0xE73D00 GHLMHLJJBIG
		// public int EGDEGGMPIGA { get; set; } 0xE720A4 ECJJIGCGIIO 0xE73D14 AAMILKDNEML

		// RVA: 0xE73D30 Offset: 0xE73D30 VA: 0xE73D30
		public void LHPDDGIJKNB()
		{
			EAJCFBCHIFB = 0x7138b4a5;
			CNABOLBIBMH = 0x7138b4a5;
		}
	}

	public class IBAOKNMIBCL
	{
		private int EHOIENNDEDH; // 0x8
		private int IFEHKNJONPL; // 0xC
		private int DGBAEDJPAMA; // 0x10
		private int MKENMKMJFKP; // 0x14

		// public int PPFNGGCBJKC { get; set; } 0xE720CC DEMEPMAEJOO 0xE720E0 HIGKAIDMOKN
		// public int BFINGCJHOHI { get; set; } 0xE720B8 LFMCLIDAPHB 0xE724B4 EDAEPDGGFJJ
		// public int DKHIHHMOIKM { get; set; } 0xE72DB4 OCOHLFAFINM 0xE72DA0 DPEOFJJLPML
		// public BOPFPIHGJMD.CJDCPBACOLH INDDJNMPONH { get; set; } 0xE72D8C GHAILOLPHPF 0xE73CC0 BACGOKIGMBC

		// RVA: 0xE73CD8 Offset: 0xE73CD8 VA: 0xE73CD8
		public void LHPDDGIJKNB()
		{
			EHOIENNDEDH = 0x7138b4a5;
			IFEHKNJONPL = 0x7138b4a5;
			DGBAEDJPAMA = 0x7138b4a5;
			MKENMKMJFKP = 0x7138b4a6;
		}

		// RVA: 0xE7295C Offset: 0xE7295C VA: 0xE7295C
		// public void ODDIHGPONFL(KDHGBOOECKC.IBAOKNMIBCL GPBJHKLFCEP) { }
	}

	public class CBJJINJDFDC
	{
		public List<KDHGBOOECKC.IBAOKNMIBCL> BHKKEJJMMDD; // 0x8
		public List<KDHGBOOECKC.IBAOKNMIBCL> ENEHOPNDNAF; // 0xC
		public List<KDHGBOOECKC.IBAOKNMIBCL> AJPLGEHPPGN; // 0x10
		public int OKDOMNJHGNF; // 0x14
		public int MFNCONLNBPB; // 0x18
		public int OOEFNNNFOLF; // 0x1C
		public bool KKBAGBFOPIJ; // 0x20
		public int FLIEFMMPKHF; // 0x24
		public int CMMNABJIKOH; // 0x28
		public bool JLDJAOCIIIG; // 0x2C

		// // RVA: 0xE716D8 Offset: 0xE716D8 VA: 0xE716D8
		// public KDHGBOOECKC.CBJJINJDFDC FKDIMODKKJD(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

		// // RVA: 0xE720F4 Offset: 0xE720F4 VA: 0xE720F4
		// public void CDNFIAKLGLH(ref List<KDHGBOOECKC.IBAOKNMIBCL> FFKPGLNBMNL, List<KDHGBOOECKC.IBAOKNMIBCL> PEGBLDOPIPM, bool AJBPBOECIMB) { }

		// // RVA: 0xE724C8 Offset: 0xE724C8 VA: 0xE724C8
		// public List<KDHGBOOECKC.IBAOKNMIBCL> CDNFIAKLGLH() { }

		// // RVA: 0xE72564 Offset: 0xE72564 VA: 0xE72564
		// public List<KDHGBOOECKC.IBAOKNMIBCL> JEMAJJIPHGA(long JHNMKKNEENE) { }

		// // RVA: 0xE729E0 Offset: 0xE729E0 VA: 0xE729E0
		// public List<KDHGBOOECKC.IBAOKNMIBCL> KBEMAMHADOO(List<KDHGBOOECKC.IBAOKNMIBCL> APMMCLKENBI, List<KDHGBOOECKC.IBAOKNMIBCL> HJAGDFOMEPM) { }

		// // RVA: 0xE72C54 Offset: 0xE72C54 VA: 0xE72C54
		// public List<KDHGBOOECKC.IBAOKNMIBCL> JEMJKEPLPAA(int KGMACNGGCNB, BOPFPIHGJMD.CJDCPBACOLH HHACNFODNEF) { }

		// // RVA: 0xE72DC8 Offset: 0xE72DC8 VA: 0xE72DC8
		// public int JLHACGNEFPJ(List<KDHGBOOECKC.IBAOKNMIBCL> NNDGIAEFMOG) { }

		// // RVA: 0xE7304C Offset: 0xE7304C VA: 0xE7304C
		// private void OIBNJADJHHG(JKNGJFOBADP JANMJPOKLFL, BBHNACPENDM LDEGEHAEALK, int KIJAPOFAGPN, int HMFFHLPNMPH, BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

		// // RVA: 0xE73264 Offset: 0xE73264 VA: 0xE73264
		// public bool BOAOOEIIAHG(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, List<KDHGBOOECKC.IBAOKNMIBCL> NNDGIAEFMOG) { }

		// // RVA: 0xE7349C Offset: 0xE7349C VA: 0xE7349C
		// public bool BOAOOEIIAHG(JKNGJFOBADP JANMJPOKLFL, BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, List<KDHGBOOECKC.IBAOKNMIBCL> NNDGIAEFMOG) { }
	}

	public class GBAGPIKOGAN_DivaOfferInfo
	{
		public int AHHJLDLAPAN_DivaId; // 0x8
		public int MLDPDLPHJPM_OfferId; // 0xC
		public string MBALOBPODGA_DivaName; // 0x10
		public string PGOGHFDBIBA_OfferName; // 0x14
		public string PNOBKANLFHA_OfferText; // 0x18
		public BOPFPIHGJMD.LEIPFJHOFPC OAFPGJLCNFM_Cond; // 0x1C
		public int KFEMFDFPCGO_Level0; // 0x20
		public int CIEOBFIIPLD_Level; // 0x24
		public bool NBHEBLNHOJO_IsMaxLevel; // 0x28

		// RVA: 0xE73938 Offset: 0xE73938 VA: 0xE73938
		public void LHPDDGIJKNB()
		{
			MLDPDLPHJPM_OfferId = 0;
			AHHJLDLAPAN_DivaId = 0;
			PGOGHFDBIBA_OfferName = "";
			MBALOBPODGA_DivaName = "";
			PNOBKANLFHA_OfferText = "";
			CIEOBFIIPLD_Level = 0;
			KFEMFDFPCGO_Level0 = 0;
			OAFPGJLCNFM_Cond = BOPFPIHGJMD.LEIPFJHOFPC.HJNNKCMLGFL/*0*/;
		}

		// // RVA: 0xE739BC Offset: 0xE739BC VA: 0xE739BC
		public void ODDIHGPONFL(GBAGPIKOGAN_DivaOfferInfo GPBJHKLFCEP)
		{
			AHHJLDLAPAN_DivaId = GPBJHKLFCEP.AHHJLDLAPAN_DivaId;
			MLDPDLPHJPM_OfferId = GPBJHKLFCEP.MLDPDLPHJPM_OfferId;
			MBALOBPODGA_DivaName = GPBJHKLFCEP.MBALOBPODGA_DivaName;
			PGOGHFDBIBA_OfferName = GPBJHKLFCEP.PGOGHFDBIBA_OfferName;
			PNOBKANLFHA_OfferText = GPBJHKLFCEP.PNOBKANLFHA_OfferText;
			OAFPGJLCNFM_Cond = GPBJHKLFCEP.OAFPGJLCNFM_Cond;
			KFEMFDFPCGO_Level0 = GPBJHKLFCEP.KFEMFDFPCGO_Level0;
			CIEOBFIIPLD_Level = GPBJHKLFCEP.CIEOBFIIPLD_Level;
			NBHEBLNHOJO_IsMaxLevel = GPBJHKLFCEP.NBHEBLNHOJO_IsMaxLevel;
		}

		// // RVA: 0xE73ACC Offset: 0xE73ACC VA: 0xE73ACC
		public bool AGBOGBEOFME(GBAGPIKOGAN_DivaOfferInfo OIKJFMGEICL)
		{
			return AHHJLDLAPAN_DivaId == OIKJFMGEICL.AHHJLDLAPAN_DivaId &&
				MLDPDLPHJPM_OfferId == OIKJFMGEICL.MLDPDLPHJPM_OfferId &&
				MBALOBPODGA_DivaName == OIKJFMGEICL.MBALOBPODGA_DivaName &&
				PGOGHFDBIBA_OfferName == OIKJFMGEICL.PGOGHFDBIBA_OfferName &&
				PNOBKANLFHA_OfferText == OIKJFMGEICL.PNOBKANLFHA_OfferText &&
				NBHEBLNHOJO_IsMaxLevel == OIKJFMGEICL.NBHEBLNHOJO_IsMaxLevel &&
				OAFPGJLCNFM_Cond == OIKJFMGEICL.OAFPGJLCNFM_Cond &&
				KFEMFDFPCGO_Level0 == OIKJFMGEICL.KFEMFDFPCGO_Level0 &&
				CIEOBFIIPLD_Level == OIKJFMGEICL.CIEOBFIIPLD_Level;
		}
	}
	public enum LEIPFJHOFPC
	{
		HJNNKCMLGFL = 0,
		NBDBAFGEEGA = 1,
		GLFGNEILACA = 2,
		GEJGMBBCFEE = 3,
	}

	public class LKBMNFAOOII
	{
		//public BOPFPIHGJMD.AGGLEGJDLGF HHACNFODNEF; // 0x8
		public int AICGFEIBKFL; // 0xC
		public int ADPPAIPFHML; // 0x10
		public int DOOGFEGEKLG; // 0x14
	}

	public class PGCENGCEJGB
	{
		public int PPFNGGCBJKC; // 0x8
		public int MKPJBDFDHOL; // 0xC
		//public BOPFPIHGJMD.MGPIJGMDLOM LHMDABPNDDH; // 0x10
	}

	public class BOBLBPGKIOH
	{
		//public BOPFPIHGJMD.MGPIJGMDLOM[] LHMDABPNDDH = new BOPFPIHGJMD.MGPIJGMDLOM[2]; // 0x8
		public int[] LNADJDFHHAI = new int[2]; // 0xC

		// RVA: 0xE71568 Offset: 0xE71568 VA: 0xE71568
		//public void BAFFAONJPCE() { }
	}

	public class JNHGHDKLDEM
	{
		public int FMHLGHDKJBC; // 0x8
		public int JIOPJDJBLFK; // 0xC
		//public KDHGBOOECKC.BOBLBPGKIOH[] NNDGIAEFMOG = new KDHGBOOECKC.BOBLBPGKIOH[3]; // 0x10

		//// RVA: 0xE73D44 Offset: 0xE73D44 VA: 0xE73D44
		//public void BAFFAONJPCE() { }

		//// RVA: 0xE73E98 Offset: 0xE73E98 VA: 0xE73E98
		//public KDHGBOOECKC.JNHGHDKLDEM JGJOAFJPIIH(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }
	}

	private class BADCBAILPID
	{
		public int FGHGMHPNEMG_Type; // 0x8
		public int MLDPDLPHJPM_OfferId; // 0xC
		public string GCFBAJONKHA = ""; // 0x10
	}

	public class NOCAJFGHDPC
	{
		public BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG_Type; // 0x8
		public int MLDPDLPHJPM_OfferId; // 0xC
		public int OIPCCBHIKIA_Index; // 0x10
	}


	private const int ENOBDCFHELD = 1899541669;
	private long GBOGLEDPFIO; // 0x8
	private long AIHOHDONCND; // 0x10
	private long HCHNGGAMGAD; // 0x18
	private BOPFPIHGJMD.JFHCHOILMEL GINJHBLEALE; // 0x20
	private int LHNLHFKDPKI; // 0x24
	private int CEFEHEAANKC; // 0x28
	private int EHMLAAHLNMN; // 0x2C
	private int JFFFPPPPNGK; // 0x30
	// private BOPFPIHGJMD.GNGGLPCONLM DGCOECIKEGA; // 0x34
	private long LJPLPIOJCNK; // 0x38
	// private BOPFPIHGJMD.MLBMHDCCGHI HMPKMCKANBG; // 0x40
	private int JNIGHEHKAHG; // 0x44
	private bool LONBOKLFGMI; // 0x48
	private List<NOCAJFGHDPC> JGPJCOCHJFJ; // 0x4C
	private const int LOKDKGIBOMF = 604800;
	private string[] JPJADDADKDA = new string[5] { JpStringLiterals.StringLiteral_12148, JpStringLiterals.StringLiteral_12149, JpStringLiterals.StringLiteral_12150, JpStringLiterals.StringLiteral_12151, JpStringLiterals.StringLiteral_12152 }; // 0x64

	public static KDHGBOOECKC HHCJCDFCLOB { get; private set; } // 0x0 LGMPACEDIJF NKACBOEHELJ OKPMHKNCNAL
	public KDHGBOOECKC.NKMCJCAJIGD NKMMJACCHEH { get; private set; } // 0x50 HFADJHMDDMB LJJDDFEFJNC GLBKBOAABOM
	public KDHGBOOECKC.JLLOKCFPOFH KPNGLBDMEBF { get; private set; } // 0x54 CENBJJIGEDL EMIGDHPEGDI LCMCCEKLAHP
	public KDHGBOOECKC.GBAGPIKOGAN_DivaOfferInfo IOCBOGFFHFE { get; private set; } // 0x58 GJJFCABOCII CAACODBAKMO OMPFOHNINBC
	public KDHGBOOECKC.GBAGPIKOGAN_DivaOfferInfo EHEEIIHLHHB { get; private set; } // 0x5C EFLOOGGNBAA DCBJPNFEAGP KEKPDABLCGD
	public KDHGBOOECKC.CBJJINJDFDC NGHMGNMNNEP { get; private set; } // 0x60 DJGNEFOADCE PNBNEBNMCJA EGJIKLMEBNF

	// // RVA: 0x1026FE4 Offset: 0x1026FE4 VA: 0x1026FE4
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
		NKMMJACCHEH = new KDHGBOOECKC.NKMCJCAJIGD();
		NKMMJACCHEH.LHPDDGIJKNB();
		KPNGLBDMEBF = new KDHGBOOECKC.JLLOKCFPOFH();
		KPNGLBDMEBF.LHPDDGIJKNB();
		IOCBOGFFHFE = new KDHGBOOECKC.GBAGPIKOGAN_DivaOfferInfo();
		IOCBOGFFHFE.LHPDDGIJKNB();
		EHEEIIHLHHB = new KDHGBOOECKC.GBAGPIKOGAN_DivaOfferInfo();
		EHEEIIHLHHB.LHPDDGIJKNB();
		JFFFPPPPNGK = 0;
		LONBOKLFGMI = false;
		GINJHBLEALE = BOPFPIHGJMD.JFHCHOILMEL.HJNNKCMLGFL/*0*/;
		LHNLHFKDPKI = 0;
		CEFEHEAANKC = 0;
		EHMLAAHLNMN = 0;
		NGHMGNMNNEP = new KDHGBOOECKC.CBJJINJDFDC();
	}

	// // RVA: 0x10271C0 Offset: 0x10271C0 VA: 0x10271C0
	// public bool MDKADMHKOLN(OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, bool FAGEBAKNAOB = False, int KDLDOLENIDG = 0, int AHHJLDLAPAN = 0, long KOOEOKEDJDO = 0, bool AGELHLFEJNG = True) { }

	// // RVA: 0x1027FD0 Offset: 0x1027FD0 VA: 0x1027FD0
	// public bool NEGHCLNLFEM(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x1028060 Offset: 0x1028060 VA: 0x1028060
	// public List<LGHIPHEDCNC.LHDLCLNBPLB> IOCBIDHIIAE(int AHCDMDKCDFM, int GPABMPAPIEC, long JHNMKKNEENE, BOPFPIHGJMD.FPKMKLDDCNL LJHNOBJJBJA, BOPFPIHGJMD.DLDOEOEFJKA INDDJNMPONH, int BAOFEFFADPD, bool BPAOFBAIAIK) { }

	// // RVA: 0x1028660 Offset: 0x1028660 VA: 0x1028660
	// public int PEJKAKECJNI(int NNDBJGDFEEM, int DOOGFEGEKLG) { }

	// // RVA: 0x1028670 Offset: 0x1028670 VA: 0x1028670
	// public LGHIPHEDCNC.LHDLCLNBPLB MJMIABEOKOA(ref List<LGHIPHEDCNC.LHDLCLNBPLB> CLMLKNCOOHH) { }

	// // RVA: 0x10287D4 Offset: 0x10287D4 VA: 0x10287D4
	// public LGHIPHEDCNC.LHDLCLNBPLB GABIMDJLBAG(ref List<LGHIPHEDCNC.LHDLCLNBPLB> CLMLKNCOOHH) { }

	// // RVA: 0x1028A74 Offset: 0x1028A74 VA: 0x1028A74
	// public bool HNPIJCCBLIA(LGHIPHEDCNC.HEECIKHJOBM KIOFLAGHLGD, long JHNMKKNEENE, ref List<LGHIPHEDCNC.LHDLCLNBPLB> ELAOAOKEJHN) { }

	// // RVA: 0x10293B0 Offset: 0x10293B0 VA: 0x10293B0
	// public bool AJAAFLHLNKP(long JHNMKKNEENE, ref List<LGHIPHEDCNC.LHDLCLNBPLB> ELAOAOKEJHN) { }

	// // RVA: 0x1029574 Offset: 0x1029574 VA: 0x1029574
	// public List<OCMJNBIFJNM.JPOHOLBBFGP> ONEMGDCCPPM(BBHNACPENDM LDEGEHAEALK, BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK, BOPFPIHGJMD.CMBJEEGFODD IBADNKFPNPI) { }

	// // RVA: 0x102979C Offset: 0x102979C VA: 0x102979C
	// public bool FGFJMGLFNNF(long KGIBHAGPCGE, long JHNMKKNEENE, ref List<LGHIPHEDCNC.LHDLCLNBPLB> ELAOAOKEJHN) { }

	// // RVA: 0x10299FC Offset: 0x10299FC VA: 0x10299FC
	// public bool LNFMLNDHFHI(BBHNACPENDM LDEGEHAEALK, long JHNMKKNEENE, BOPFPIHGJMD.DLDOEOEFJKA NPFIFEIOGAM) { }

	// // RVA: 0x1029C7C Offset: 0x1029C7C VA: 0x1029C7C
	// public bool HDNBNNKHCPA(BOPFPIHGJMD.DLDOEOEFJKA FGHGMHPNEMG, long JHNMKKNEENE, ref List<LGHIPHEDCNC.LHDLCLNBPLB> ELAOAOKEJHN) { }

	// // RVA: 0x102A6E0 Offset: 0x102A6E0 VA: 0x102A6E0
	// private bool PEMMDEMCHAH() { }

	// // RVA: 0x102A774 Offset: 0x102A774 VA: 0x102A774
	// public bool DJMICICGLLG() { }

	// // RVA: 0x102A9F8 Offset: 0x102A9F8 VA: 0x102A9F8
	// private bool DCKHPFDIMFI(int PPMBFJJDCPP, long JHNMKKNEENE) { }

	// // RVA: 0x102AAE0 Offset: 0x102AAE0 VA: 0x102AAE0
	// public List<LGHIPHEDCNC.LHDLCLNBPLB> MIMNFDFLFFA(long JHNMKKNEENE) { }

	// // RVA: 0x102BFC0 Offset: 0x102BFC0 VA: 0x102BFC0
	// public int CBDOLLGCIKB(long EJFPCCIHIBG, long JHNMKKNEENE) { }

	// // RVA: 0x102BFE0 Offset: 0x102BFE0 VA: 0x102BFE0
	// public long OGIGEGAMNCI(long EJFPCCIHIBG, int DNFKINPBKJL) { }

	// // RVA: 0x102C000 Offset: 0x102C000 VA: 0x102C000
	// public List<LGHIPHEDCNC.BFEIHCJHHAJ> NHHLDEPNCNG(long JHNMKKNEENE) { }

	// // RVA: 0x102CB08 Offset: 0x102CB08 VA: 0x102CB08
	// public List<LGHIPHEDCNC.PDLENIHAMBC> OGIKEILKDEA() { }

	// // RVA: 0x102CED4 Offset: 0x102CED4 VA: 0x102CED4
	// public List<LGHIPHEDCNC.FCOBCHHKMOA> DNNAPBIGHJI() { }

	// // RVA: 0x102D6A0 Offset: 0x102D6A0 VA: 0x102D6A0
	// public bool PHNCOGEOBAD() { }

	// // RVA: 0x102D698 Offset: 0x102D698 VA: 0x102D698
	// public void OLNHMMHLAGF(bool OAFPGJLCNFM) { }

	// // RVA: 0x102D6A8 Offset: 0x102D6A8 VA: 0x102D6A8
	// public bool OHILPCDFKCH() { }

	// // RVA: 0x102D6EC Offset: 0x102D6EC VA: 0x102D6EC
	// public int ECBHIIOABCK() { }

	// // RVA: 0x102D84C Offset: 0x102D84C VA: 0x102D84C
	// public int PDGOLEJBNMM(BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK, bool PFCKDGKGBMM) { }

	// // RVA: 0x102A4B8 Offset: 0x102A4B8 VA: 0x102A4B8
	// public int MPPINCEGOJE(BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK, bool PFCKDGKGBMM) { }

	// // RVA: 0x102A290 Offset: 0x102A290 VA: 0x102A290
	// public int GOJDPOGJOLM(BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK, bool PFCKDGKGBMM) { }

	// // RVA: 0x102D870 Offset: 0x102D870 VA: 0x102D870
	// public int LJMOMAGLEGL(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK, bool PFCKDGKGBMM) { }

	// // RVA: 0x102DAA4 Offset: 0x102DAA4 VA: 0x102DAA4
	// public string GEGAJLNPMEC(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102DC74 Offset: 0x102DC74 VA: 0x102DC74
	// public BOPFPIHGJMD.AHIOHONIGDH EKAECAHFMKE(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102DC98 Offset: 0x102DC98 VA: 0x102DC98
	// public BOPFPIHGJMD.AHIOHONIGDH EKAECAHFMKE(LGHIPHEDCNC.NONCDAINJLD KOGBMDOONFA) { }

	// // RVA: 0x102DF48 Offset: 0x102DF48 VA: 0x102DF48
	// public BOPFPIHGJMD.ADMNKELOLPN KJGAJBOBIHK(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102DF6C Offset: 0x102DF6C VA: 0x102DF6C
	// public int LBDENPEGONA(int OIOECMEEFKJ, BOPFPIHGJMD.HBJMIJIOCAM DGGBOFDCOLG) { }

	// // RVA: 0x102E430 Offset: 0x102E430 VA: 0x102E430
	// public void JPHPEIFPKDL(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102E490 Offset: 0x102E490 VA: 0x102E490
	// public KDHGBOOECKC.NKMCJCAJIGD CNNICINEKBJ() { }

	// // RVA: 0x102E498 Offset: 0x102E498 VA: 0x102E498
	// public List<KDHGBOOECKC.NOCAJFGHDPC> NBIJDMOOILH() { }

	// // RVA: 0x10276C0 Offset: 0x10276C0 VA: 0x10276C0
	public List<NOCAJFGHDPC> BJIPLMJFAGH()
	{
		JGPJCOCHJFJ = new List<NOCAJFGHDPC>();
		if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
		{
			List<OCMJNBIFJNM_Offer.JPOHOLBBFGP> d = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.DAEJHMCMFJD_Offer.FOFLMHELILC;
			for(int i = 0; i < d.Count; i++)
			{
				if(!d[i].DFIGPDCBAPB_IsUnitialized())
				{
					NOCAJFGHDPC data = new NOCAJFGHDPC();
					data.OIPCCBHIKIA_Index = i;
					data.FGHGMHPNEMG_Type = (BOPFPIHGJMD.MLBMHDCCGHI)d[i].GBJFNGCDKPM_Type;
					data.MLDPDLPHJPM_OfferId = d[i].MLDPDLPHJPM_OfferId;
					JGPJCOCHJFJ.Add(data);
				}
			}
		}
		return JGPJCOCHJFJ;
	}

	// // RVA: 0x1027928 Offset: 0x1027928 VA: 0x1027928
	// public OCMJNBIFJNM.JPOHOLBBFGP BKJJKHIBIGP(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x1027C8C Offset: 0x1027C8C VA: 0x1027C8C
	// public LGHIPHEDCNC.NONCDAINJLD GKIOIHLDBGF(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102E4A0 Offset: 0x102E4A0 VA: 0x102E4A0
	// public bool CKBDHFNLLJE(BOPFPIHGJMD.AHIOHONIGDH AELKJEKCJND, SeriesAttr.Type LLNKADMJODG) { }

	// // RVA: 0x102E4FC Offset: 0x102E4FC VA: 0x102E4FC
	// public bool CKBDHFNLLJE(BOPFPIHGJMD.LGEIPIHHNPH DFMOGBOPLEF, SeriesAttr.Type LLNKADMJODG) { }

	// // RVA: 0x102E578 Offset: 0x102E578 VA: 0x102E578
	// public BOPFPIHGJMD.LGEIPIHHNPH MDNPDBIPKLB(BOPFPIHGJMD.AHIOHONIGDH AELKJEKCJND, int JBHBGOIMALD) { }

	// // RVA: 0x102E5F0 Offset: 0x102E5F0 VA: 0x102E5F0
	// public bool KGKEGICJHCB(int OIOECMEEFKJ, BOPFPIHGJMD.AHIOHONIGDH AELKJEKCJND) { }

	// // RVA: 0x102E8A8 Offset: 0x102E8A8 VA: 0x102E8A8
	// public bool NNGDHKMNDNK(OCMJNBIFJNM.JPOHOLBBFGP EILKGEADKGH, BOPFPIHGJMD.AHIOHONIGDH AELKJEKCJND) { }

	// // RVA: 0x102E950 Offset: 0x102E950 VA: 0x102E950
	// public bool NKHGLFOBOJD(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, int OIOECMEEFKJ, int MNCEBKHBBEF) { }

	// // RVA: 0x102EC00 Offset: 0x102EC00 VA: 0x102EC00
	// public long NPEFMNPOMMJ(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, int OIOECMEEFKJ, FKGMGBHBNOC.HPJOCKGKNCC MNCEBKHBBEF, bool FMCIBHOHDAH = True) { }

	// // RVA: 0x102F054 Offset: 0x102F054 VA: 0x102F054
	// public int KGLLKKCFDEL(FKGMGBHBNOC.HPJOCKGKNCC MNCEBKHBBEF, BOPFPIHGJMD.ADMNKELOLPN CGKPIIFCCLD, BOPFPIHGJMD.HBJMIJIOCAM DGGBOFDCOLG) { }

	// // RVA: 0x102F1F4 Offset: 0x102F1F4 VA: 0x102F1F4
	public bool JPNPPIHOJFC(long JHNMKKNEENE)
	{
		TodoLogger.Log(0, "JPNPPIHOJFC");
		return false;
	}

	// // RVA: 0x102F5A0 Offset: 0x102F5A0 VA: 0x102F5A0
	// public BOPFPIHGJMD.IGHPDAGKIKO KOGFFBBKOPB(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102F5C4 Offset: 0x102F5C4 VA: 0x102F5C4
	// public bool MOOJLBNGNOB(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK) { }

	// // RVA: 0x102F7F4 Offset: 0x102F7F4 VA: 0x102F7F4
	// public bool PGGLEDMJEHB(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, int BFINGCJHOHI) { }

	// // RVA: 0x102FAD0 Offset: 0x102FAD0 VA: 0x102FAD0
	// public int MJILMJNJGFH(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x102FAF4 Offset: 0x102FAF4 VA: 0x102FAF4
	public int DEAIKHLFFCL(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG = 0)
	{
		if(FGHGMHPNEMG < BOPFPIHGJMD.MLBMHDCCGHI.GEJGMBBCFEE/*5*/)
		{
			if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
			{
				if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.OEKEIGFAIGN_Counter != null)
				{
					if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.OEKEIGFAIGN_Counter.BDLNMOIOMHK_Total != null)
					{
						return CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.OEKEIGFAIGN_Counter.BDLNMOIOMHK_Total.GKOAPFJFKEJ_VOpC[(int)FGHGMHPNEMG];
					}
				}
			}
		}
		return 0;
	}

	// // RVA: 0x102FC68 Offset: 0x102FC68 VA: 0x102FC68
	// public int KGEOELDMHJF(int AHHJLDLAPAN) { }

	// // RVA: 0x102E920 Offset: 0x102E920 VA: 0x102E920
	// public bool KDLDEFCPBMD(int ADPPAIPFHML, int BDMLMGBLGPC) { }

	// // RVA: 0x102FDE0 Offset: 0x102FDE0 VA: 0x102FDE0
	// public int DOBEIMMEHJF(List<int> NNDGIAEFMOG) { }

	// // RVA: 0x102FFA0 Offset: 0x102FFA0 VA: 0x102FFA0
	// public KDHGBOOECKC.JLLOKCFPOFH DOBIMMEGLOB(int GOKJLBDJOLA, bool BCGLDMKODLC) { }

	// // RVA: 0x1030234 Offset: 0x1030234 VA: 0x1030234
	// public List<KDHGBOOECKC.IBAOKNMIBCL> FOACCNFAGCH(List<LGHIPHEDCNC.NACBCEDKEPF> NNDGIAEFMOG, BOPFPIHGJMD.CJDCPBACOLH HHACNFODNEF, int PPFNGGCBJKC, int BFINGCJHOHI) { }

	// // RVA: 0x10306F4 Offset: 0x10306F4 VA: 0x10306F4
	// public List<KDHGBOOECKC.IBAOKNMIBCL> NLAPKNDOEPL(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x10308CC Offset: 0x10308CC VA: 0x10308CC
	// public KDHGBOOECKC.IBAOKNMIBCL LEPDAMFKAJP(List<LGHIPHEDCNC.NACBCEDKEPF> NNDGIAEFMOG, int FCDMDDIHMPO) { }

	// // RVA: 0x1030A70 Offset: 0x1030A70 VA: 0x1030A70
	// public int PCGKAPBMIDM(int MLDPDLPHJPM) { }

	// [IteratorStateMachineAttribute] // RVA: 0x6B8CD0 Offset: 0x6B8CD0 VA: 0x6B8CD0
	// // RVA: 0x1030B70 Offset: 0x1030B70 VA: 0x1030B70
	// public IEnumerator FMGMIKPJNKG(float MINBFANDAPL, bool CNHLBGMNGOF = False, Action LFEELJFNMKL) { }

	// // RVA: 0x1030C38 Offset: 0x1030C38 VA: 0x1030C38
	// public int LHIOJHAOAOD() { }

	// // RVA: 0x102BE44 Offset: 0x102BE44 VA: 0x102BE44
	// public int BCACCAGCPCO() { }

	// // RVA: 0x1030D68 Offset: 0x1030D68 VA: 0x1030D68
	// public int MAPECPHBNGM(int AHHJLDLAPAN) { }

	// // RVA: 0x1030F40 Offset: 0x1030F40 VA: 0x1030F40
	// public int LHLMBJNFEGB(int AHHJLDLAPAN) { }

	// // RVA: 0x1031118 Offset: 0x1031118 VA: 0x1031118
	// public LGHIPHEDCNC.PDLENIHAMBC AGFFPFCADJK(int AHHJLDLAPAN, List<LGHIPHEDCNC.PDLENIHAMBC> ABKBDLNLJDI, List<OCMJNBIFJNM.JPOHOLBBFGP> OMABPKCJECB) { }

	// // RVA: 0x1031790 Offset: 0x1031790 VA: 0x1031790
	public BOPFPIHGJMD.LEIPFJHOFPC PANBPMDADAH(int BBIOMNCILMC, int AKNELONELJK)
	{
		TodoLogger.Log(0, "PANBPMDADAH");
		return new BOPFPIHGJMD.LEIPFJHOFPC();
	}

	// // RVA: 0x1027B20 Offset: 0x1027B20 VA: 0x1027B20
	// public bool FGDFFDELFIO(OCMJNBIFJNM.JPOHOLBBFGP EILKGEADKGH) { }

	// // RVA: 0x103308C Offset: 0x103308C VA: 0x103308C
	// public bool FGDFFDELFIO(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x10332E4 Offset: 0x10332E4 VA: 0x10332E4
	// public void NBBFDHNKGEO() { }

	// // RVA: 0x1032DB4 Offset: 0x1032DB4 VA: 0x1032DB4
	// public bool MGHPDFMDFCJ() { }

	// // RVA: 0x10334EC Offset: 0x10334EC VA: 0x10334EC
	// public int OHMPHEFJBGN() { }

	// // RVA: 0x10335D4 Offset: 0x10335D4 VA: 0x10335D4
	// public int JMGECJKIJJF() { }

	// // RVA: 0x10337A8 Offset: 0x10337A8 VA: 0x10337A8
	// public bool AHKAIKMNKJL() { }

	// // RVA: 0x1033940 Offset: 0x1033940 VA: 0x1033940
	// public bool BOGPKGKBCFM() { }

	// // RVA: 0x1033A20 Offset: 0x1033A20 VA: 0x1033A20
	// public LGHIPHEDCNC.GHLIDOPMMDB LAIKKACPBPB(int PPFNGGCBJKC) { }

	// // RVA: 0x1033B98 Offset: 0x1033B98 VA: 0x1033B98
	// public int JGFHJPGJJHP() { }

	// // RVA: 0x1033E30 Offset: 0x1033E30 VA: 0x1033E30
	// public bool OOOMMBCDOBO() { }

	// // RVA: 0x1033F2C Offset: 0x1033F2C VA: 0x1033F2C
	// public string OMPLNLDPOFN(int OIOECMEEFKJ) { }

	// // RVA: 0x1032EB4 Offset: 0x1032EB4 VA: 0x1032EB4
	// public int HFLNFKFGEJH(int AHHJLDLAPAN) { }

	// // RVA: 0x10340FC Offset: 0x10340FC VA: 0x10340FC
	// public int KPCKLKIGOID() { }

	// // RVA: 0x10341EC Offset: 0x10341EC VA: 0x10341EC
	// public int CKINCELGOEE(OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, int KIJAPOFAGPN) { }

	// // RVA: 0x10342B0 Offset: 0x10342B0 VA: 0x10342B0
	// public void CGBBDJBEFAM(OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, int KIJAPOFAGPN, int ADPPAIPFHML) { }

	// // RVA: 0x103437C Offset: 0x103437C VA: 0x103437C
	// public int CKINCELGOEE() { }

	// // RVA: 0x10344AC Offset: 0x10344AC VA: 0x10344AC
	// public int HJIJAOHCLOE(int ADPPAIPFHML) { }

	// // RVA: 0x1034604 Offset: 0x1034604 VA: 0x1034604
	// public KDHGBOOECKC.LKBMNFAOOII NNMPMKGBJFB(long KAMNCNDAAOK, BOPFPIHGJMD.AGGLEGJDLGF FLGECLFIGPL) { }

	// // RVA: 0x1034878 Offset: 0x1034878 VA: 0x1034878
	// public KDHGBOOECKC.LKBMNFAOOII NNMPMKGBJFB(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, BOPFPIHGJMD.AGGLEGJDLGF FLGECLFIGPL, long JHNMKKNEENE = -1) { }

	// // RVA: 0x10349F8 Offset: 0x10349F8 VA: 0x10349F8
	// public int PEBJPOPJAJJ() { }

	// // RVA: 0x1034B84 Offset: 0x1034B84 VA: 0x1034B84
	// public int BCJNPJKGNHF(int JBGEEPFKIGG) { }

	// // RVA: 0x1034DC0 Offset: 0x1034DC0 VA: 0x1034DC0
	public bool PCPECPFJMGC()
	{
		if(CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
		{
			CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.DAEJHMCMFJD_Offer.KPAJEAHFPFH_FastCmp = 0;
			return true;
		}
		return false;
	}

	// // RVA: 0x1034E9C Offset: 0x1034E9C VA: 0x1034E9C
	public bool IHGJNLNJPOK()
	{
		return CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave.DAEJHMCMFJD_Offer.EAINJDPLIAG_FastCmpDt != NKGJPJPHLIF.HHCJCDFCLOB.DHMLDAGGKCD;
	}

	// // RVA: 0x1034FD8 Offset: 0x1034FD8 VA: 0x1034FD8
	// public int EJBPEBIIMPG() { }

	// // RVA: 0x10350C0 Offset: 0x10350C0 VA: 0x10350C0
	// public bool LOCAIBNPKDL() { }

	// // RVA: 0x10351B0 Offset: 0x10351B0 VA: 0x10351B0
	// public bool NKEKPBALJGD() { }

	// // RVA: 0x1035330 Offset: 0x1035330 VA: 0x1035330
	// public TransitionUniqueId OOFNEPBLPEA() { }

	// // RVA: 0x1035360 Offset: 0x1035360 VA: 0x1035360
	// public bool GNJCAJKEOGB() { }

	// // RVA: 0x1035370 Offset: 0x1035370 VA: 0x1035370
	// public bool GNJCAJKEOGB(BOPFPIHGJMD.GNGGLPCONLM HBOHFOPMLBO) { }

	// // RVA: 0x1035380 Offset: 0x1035380 VA: 0x1035380
	// public void PANKGNBPFEL(BOPFPIHGJMD.GNGGLPCONLM HBOHFOPMLBO) { }

	// // RVA: 0x102BE34 Offset: 0x102BE34 VA: 0x102BE34
	// public void JLKENFELMPM(BOPFPIHGJMD.GNGGLPCONLM HBOHFOPMLBO) { }

	// // RVA: 0x102F590 Offset: 0x102F590 VA: 0x102F590
	// public void EGNCJPMPMDC(BOPFPIHGJMD.GNGGLPCONLM HBOHFOPMLBO) { }

	// // RVA: 0x1035388 Offset: 0x1035388 VA: 0x1035388
	public bool PPPLNJCFAID()
	{
		TodoLogger.Log(0, "PPPLNJCFAID");
		return false;
	}

	// // RVA: 0x1035CB8 Offset: 0x1035CB8 VA: 0x1035CB8
	// public bool CCPNBHCKNDC() { }

	// // RVA: 0x1035C7C Offset: 0x1035C7C VA: 0x1035C7C
	// private bool OJELEDJNCFO(long JHNMKKNEENE) { }

	// // RVA: 0x1035DD0 Offset: 0x1035DD0 VA: 0x1035DD0
	// private bool CCPNBHCKNDC(long JHNMKKNEENE, bool CGKINNALDGE) { }

	// // RVA: 0x10360A0 Offset: 0x10360A0 VA: 0x10360A0
	// public string JIMBMBEEMHI() { }

	// // RVA: 0x10362E0 Offset: 0x10362E0 VA: 0x10362E0
	// public bool NLDDHJGHHOD() { }

	// // RVA: 0x10362EC Offset: 0x10362EC VA: 0x10362EC
	// public long IILNIBNFOLG(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG) { }

	// // RVA: 0x1036320 Offset: 0x1036320 VA: 0x1036320
	// public string IJEFGJHHELK() { }

	// // RVA: 0x10363E4 Offset: 0x10363E4 VA: 0x10363E4
	// public string GOIOHEOGOFK(int OIOECMEEFKJ) { }

	// // RVA: 0x102EF84 Offset: 0x102EF84 VA: 0x102EF84
	// public string PBKNBDCABDM(OCMJNBIFJNM.JPOHOLBBFGP GJLFANGDGCL, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x1036554 Offset: 0x1036554 VA: 0x1036554
	// public string PBKNBDCABDM(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x1036574 Offset: 0x1036574 VA: 0x1036574
	// public string OHDGMEGGLDP(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x1036600 Offset: 0x1036600 VA: 0x1036600
	// public bool MPEEILDOBCJ(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x1036690 Offset: 0x1036690 VA: 0x1036690
	// public BOPFPIHGJMD.JFHCHOILMEL JAMKJBMGAGI() { }

	// // RVA: 0x1036698 Offset: 0x1036698 VA: 0x1036698
	// public BOPFPIHGJMD.JFHCHOILMEL HKDGKDNIGDD() { }

	// // RVA: 0x1036A7C Offset: 0x1036A7C VA: 0x1036A7C
	// public void EBJOGGIHHBA(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, bool FMLIHIEMBBH = False) { }

	// // RVA: 0x1036E04 Offset: 0x1036E04 VA: 0x1036E04
	// private bool CEHIEFPLPFM(BBHNACPENDM LNEAHKALBHN, OKGLGHCBCJP JLBMBKHBKBG, int MBBJMJAAODG, int ENHEJFPMPJH) { }

	// // RVA: 0x103701C Offset: 0x103701C VA: 0x103701C
	// public void EBJOGGIHHBA(JKNGJFOBADP JANMJPOKLFL, BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM, ref bool GHEHKJFGOIE) { }

	// // RVA: 0x1037620 Offset: 0x1037620 VA: 0x1037620
	// public KDHGBOOECKC.CBJJINJDFDC IKENGGJIJJO() { }

	// // RVA: 0x1037628 Offset: 0x1037628 VA: 0x1037628
	// public KDHGBOOECKC.PGCENGCEJGB OFJFGHEIMAH(BOPFPIHGJMD.DBNJDPHLLHI CIANOCNPIFF) { }

	// // RVA: 0x103780C Offset: 0x103780C VA: 0x103780C
	// public string JIDINGHMOJF() { }

	// // RVA: 0x1035B84 Offset: 0x1035B84 VA: 0x1035B84
	// public bool MGMIIAMOMGH(BOPFPIHGJMD.FDDGIANLNAD FIKCHOLCKNJ) { }

	// // RVA: 0x10331C4 Offset: 0x10331C4 VA: 0x10331C4
	// public void LPGIDDKBJFJ(BOPFPIHGJMD.FDDGIANLNAD FIKCHOLCKNJ, bool OGBEGDKPDGK) { }

	// // RVA: 0x1035A64 Offset: 0x1035A64 VA: 0x1035A64
	// public void BFJFAIIAMMO(BOPFPIHGJMD.FDDGIANLNAD FIKCHOLCKNJ, bool OGBEGDKPDGK) { }

	// // RVA: 0x1035868 Offset: 0x1035868 VA: 0x1035868
	// public bool OONMAICCONN() { }

	// // RVA: 0x10330A4 Offset: 0x10330A4 VA: 0x10330A4
	// public void LMAHFGBPGKF(KDHGBOOECKC.GBAGPIKOGAN KOGBMDOONFA, bool OGBEGDKPDGK) { }

	// // RVA: 0x103596C Offset: 0x103596C VA: 0x103596C
	// public void GHNMKNCNHAA(KDHGBOOECKC.GBAGPIKOGAN KOGBMDOONFA) { }

	// // RVA: 0x1037990 Offset: 0x1037990 VA: 0x1037990
	// public void CPDBAIILNPL(bool OGBEGDKPDGK) { }

	// // RVA: 0x1037AA8 Offset: 0x1037AA8 VA: 0x1037AA8
	// public void HJOLFCDAIGE(BOPFPIHGJMD.MLBMHDCCGHI CKEDODOIIPD) { }

	// // RVA: 0x1037AB0 Offset: 0x1037AB0 VA: 0x1037AB0
	// public BOPFPIHGJMD.MLBMHDCCGHI NPIJHJNCBGM() { }

	// // RVA: 0x1037AB8 Offset: 0x1037AB8 VA: 0x1037AB8
	// public int PICPOPFLEJH() { }

	// // RVA: 0x1037BBC Offset: 0x1037BBC VA: 0x1037BBC
	// public int EKODBMNLMKA() { }

	// // RVA: 0x1037CC0 Offset: 0x1037CC0 VA: 0x1037CC0
	// public void NCGGBBELDFI(bool OAFPGJLCNFM) { }

	// // RVA: 0x1037DF4 Offset: 0x1037DF4 VA: 0x1037DF4
	// public bool LBKNBKPBAPJ() { }

	// [IteratorStateMachineAttribute] // RVA: 0x6B8D48 Offset: 0x6B8D48 VA: 0x6B8D48
	// // RVA: 0x1037EDC Offset: 0x1037EDC VA: 0x1037EDC
	public IEnumerator CEHFPAGELLE_Coroutine_ReceiveVOP_UnreceivedAchivements(IMCBBOAFION BHFHGFKBOHH_OnSuccess, DJBHIFLHJLK MOBEEPPKFLG_OnError)
    {
		BBHNACPENDM_ServerSaveData MNKKMKJMFDB_ServerSave; // 0x20
		List<string> HLOHHJKCOIP; // 0x24
		int MAHHCPJIKHA_VopVcAchvtCnt; // 0x28

		//0xE70060
		MNKKMKJMFDB_ServerSave = CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave;
		if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database != null && MNKKMKJMFDB_ServerSave != null)
		{
			if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer.FFKIBJKEBNP[0].LJNAKDMILMC == 0)
			{
				if (BHFHGFKBOHH_OnSuccess != null)
					BHFHGFKBOHH_OnSuccess();
			}
			else
			{
				bool PLOOEECNHFB = false;
				bool NPNNPNAIONN = false;
				StringBuilder str = new StringBuilder(256);
				HLOHHJKCOIP = new List<string>();
				List<string> CLPMDJFKJBO = new List<string>();
				List<BADCBAILPID> FCLLKLPHPMP = new List<BADCBAILPID>();
				List<BADCBAILPID> ICKPEPLDFOG = new List<BADCBAILPID>();
				List<NOCAJFGHDPC> data = BJIPLMJFAGH();
				for (int i = 0; i < data.Count;  i++)
				{
					OCMJNBIFJNM_Offer.JPOHOLBBFGP d = MNKKMKJMFDB_ServerSave.DAEJHMCMFJD_Offer.FOFLMHELILC[data[i].OIPCCBHIKIA_Index];
					if (d.BFINGCJHOHI_Cnt > 0)
					{
						int val = 0;
						int offerId = d.MLDPDLPHJPM_OfferId;
						switch (d.GBJFNGCDKPM_Type)
						{
							case 1:
								val = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer.HOJPJAFDIAD[offerId - 1].LJNAKDMILMC;
								break;
							case 2:
								val = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer.FFKIBJKEBNP[offerId - 1].LJNAKDMILMC;
								break;
							case 3:
								val = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer.PMCDKBBHCJK[offerId - 1].LJNAKDMILMC;
								break;
							case 4:
								val = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer.OICGEEKOLOG[offerId - 1].LJNAKDMILMC;
								break;
							default:
								break;
						}
						if(val > 0)
						{
							str.Clear();
							str.AppendFormat("new_offer_clear_key_" + val.ToString("D4"), Array.Empty<object>());
							HLOHHJKCOIP.Add(str.ToString());
							BADCBAILPID data2 = new BADCBAILPID();
							data2.FGHGMHPNEMG_Type = d.GBJFNGCDKPM_Type;
							data2.MLDPDLPHJPM_OfferId = d.MLDPDLPHJPM_OfferId;
							data2.GCFBAJONKHA = str.ToString();
							FCLLKLPHPMP.Add(data2);
						}
					}
				}
				if(HLOHHJKCOIP.Count < 1)
				{
					if (BHFHGFKBOHH_OnSuccess != null)
						BHFHGFKBOHH_OnSuccess();
					MNKKMKJMFDB_ServerSave.DAEJHMCMFJD_Offer.KNIKMMKNOFA_ARcv = 3;
				}
				else
				{
					MAHHCPJIKHA_VopVcAchvtCnt = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.GDEKCOOBLMA_System.LPJLEHAJADA("vop_vc_achvment_get_count", 80);
					if(MAHHCPJIKHA_VopVcAchvtCnt != 0)
					{
						//LAB_00e712f4
						while(HLOHHJKCOIP.Count > 0)
						{
							List<string> strs = new List<string>();
							if(MAHHCPJIKHA_VopVcAchvtCnt < HLOHHJKCOIP.Count)
							{
								for(int i = 0; i < MAHHCPJIKHA_VopVcAchvtCnt; i++)
								{
									strs.Add(HLOHHJKCOIP[0]);
									HLOHHJKCOIP.RemoveAt(0);
								}
							}
							else
							{
								for(int i = 0; i < HLOHHJKCOIP.Count; i++)
								{
									strs.Add(HLOHHJKCOIP[i]);
								}
								HLOHHJKCOIP.Clear();
							}
							CLPMDJFKJBO.Clear();
							ICKPEPLDFOG.Clear();
							PLOOEECNHFB = false;
							NPNNPNAIONN = false;
							JGMEFHJCNHP_GetAchievementRecords req = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.IFFNCAFNEAG_AddRequest(new JGMEFHJCNHP_GetAchievementRecords());
							req.KMOBDLBKAAA = false;
							req.MIDAMHNABAJ = strs;
							CACGCMBKHDI_Request.HDHIKGLMOGF KDFFGLHBDLO = (CACGCMBKHDI_Request NHECPMNKEFK) =>
							{
								//0xE6F5F8
								JGMEFHJCNHP_GetAchievementRecords t = NHECPMNKEFK as JGMEFHJCNHP_GetAchievementRecords;
								TodoLogger.Log(0, "BHFHGFKBOHH_OnSuccess");
							};
							req.BHFHGFKBOHH_OnSuccess = KDFFGLHBDLO;
							CACGCMBKHDI_Request.HDHIKGLMOGF BAHANNNJCGC = (CACGCMBKHDI_Request NHECPMNKEFK) =>
							{
								//0xE6F9F8
								TodoLogger.Log(0, "MOBEEPPKFLG_OnFail");
							};
							req.MOBEEPPKFLG_OnFail = BAHANNNJCGC;
							//LAB_00e71020
							while (PLOOEECNHFB == false)
								yield return null;
							if(NPNNPNAIONN == false)
							{
								if(CLPMDJFKJBO.Count > 0)
								{
									PLOOEECNHFB = false;
									NPNNPNAIONN = false;
									FLONELKGABJ_ClaimAchievementPrizes req2 = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.IFFNCAFNEAG_AddRequest(new FLONELKGABJ_ClaimAchievementPrizes());
									req2.KMOBDLBKAAA = false;
									req2.MIDAMHNABAJ = CLPMDJFKJBO;
									CACGCMBKHDI_Request.HDHIKGLMOGF CMJMGEFNBDK = (CACGCMBKHDI_Request NHECPMNKEFK) =>
									{
										//0xE6FA04
										TodoLogger.Log(0, "BHFHGFKBOHH_OnSuccess");
									};
									req2.BHFHGFKBOHH_OnSuccess = CMJMGEFNBDK;
									CACGCMBKHDI_Request.HDHIKGLMOGF DMLJLPMBLCH = (CACGCMBKHDI_Request NHECPMNKEFK) =>
									{
										//0xE6FA10
										TodoLogger.Log(0, "MOBEEPPKFLG_OnFail");
									};
									req2.MOBEEPPKFLG_OnFail = DMLJLPMBLCH;
									while (PLOOEECNHFB == false)
										yield return null;
									if(NPNNPNAIONN)
									{
										if (MOBEEPPKFLG_OnError != null)
											MOBEEPPKFLG_OnError();
										yield break;
									}
									else
									{
										JKNGJFOBADP data2 = new JKNGJFOBADP();
										data2.JCHLONCMPAJ();
										for(int i = 0; i < ICKPEPLDFOG.Count; i++)
										{
											data2.OBCINIPHGGH = 0;
											data2.PJBJCBEMEEC = 0;
											data2.FEGDNPIEKJC(OAGBCBBHMPF.COIIJOEKBDH.JMLJADADEEF/*28*/, ICKPEPLDFOG[i].FGHGMHPNEMG_Type.ToString() + ":" + ICKPEPLDFOG[i].MLDPDLPHJPM_OfferId.ToString());
											data2.CPIICACGNBH(MNKKMKJMFDB_ServerSave, EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(EKLNMHFCAOI.FKGCBLHOOCL_Category.PJDEOPMBGKJ_PaidVC, 1), 5, null, 0);
										}
									}
								}
								// go LAB_00e712f4
							}
							else
							{
								if (MOBEEPPKFLG_OnError != null)
									MOBEEPPKFLG_OnError();
								yield break;
							}
						}
						MNKKMKJMFDB_ServerSave.DAEJHMCMFJD_Offer.KNIKMMKNOFA_ARcv = 3;
						if (BHFHGFKBOHH_OnSuccess != null)
							BHFHGFKBOHH_OnSuccess();
					}
				}
			}
		}
		else
		{
			if (MOBEEPPKFLG_OnError != null)
				MOBEEPPKFLG_OnError();
		}
	}
}
