
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using XeSys;

public class KEPNMGHABPI
{
    //[DefaultMemberAttribute("Item")] // RVA: 0x63D4EC Offset: 0x63D4EC VA: 0x63D4EC
    public class FKGOOHONBGI // TypeDefIndex: 10101
    {
        private Dictionary<string, KEPNMGHABPI> GCOJLMHEBNJ = new Dictionary<string, KEPNMGHABPI>(); // 0x8

        // public KEPNMGHABPI INIMBLOHIEF { get; }

        // RVA: 0x19FC68C Offset: 0x19FC68C VA: 0x19FC68C
        public KEPNMGHABPI GOAMILGNJIE(BNJJHPEGNAI.HCAJEKFFNBM PNOEDHCKCEJ)
        {
            string str = PNOEDHCKCEJ.KGICDMIJGDF + PNOEDHCKCEJ.ADCMNODJBGJ_Title;
            KEPNMGHABPI res = null;
            if(!GCOJLMHEBNJ.TryGetValue(str, out res))
            {
                res = new KEPNMGHABPI(PNOEDHCKCEJ);
                GCOJLMHEBNJ.Add(str, res);
            }
            return res;
        }
    }

    public class AELPHOILEBM
    {
        public const int GBBILKJEBCO = 30;
        public const int KHPDFDJOHNL = 30;
        public const int KJEEECMKAPE = 1;
        internal const int PKDODBPFHAO = 2;
        internal const int JHKAOFLAMLC = 1;
        public SakashoBbsThreadCriteria IPKCADIAAPG; // 0x8
        public int MLPLGFLKKLI; // 0xC
        public int IGNIIEBMFIN; // 0x10
        public string ADCMNODJBGJ_Title; // 0x14
        internal int DFJDDIGFGKJ; // 0x18
        internal int MLMHPBOKJCL; // 0x1C

        // RVA: 0x19F42A4 Offset: 0x19F42A4 VA: 0x19F42A4
        public AELPHOILEBM(KEPNMGHABPI PAKIOKPJOBF)
        {
            KHEKNNFCAOI(PAKIOKPJOBF);
        }

        // RVA: 0x19FC234 Offset: 0x19FC234 VA: 0x19FC234
        public void KHEKNNFCAOI(KEPNMGHABPI PAKIOKPJOBF)
        {
			IPKCADIAAPG = null;
			MLPLGFLKKLI = 30;
			IGNIIEBMFIN = 1;
			ADCMNODJBGJ_Title = PAKIOKPJOBF.OJAGHKJAJEJ.Title;
			DFJDDIGFGKJ = 2;
			MLMHPBOKJCL = 1;
		}
    }

    public class EIAMFNIAFGN
    {
        public const int GBBILKJEBCO = 30;
        public const int KHPDFDJOHNL = 30;
        public const int KJEEECMKAPE = 1;
        internal const int JHKAOFLAMLC = 0;
        public SakashoBbsCommentCriteria IPKCADIAAPG; // 0x8
        public int MLPLGFLKKLI; // 0xC
        public int IGNIIEBMFIN; // 0x10
        internal int MLMHPBOKJCL; // 0x14

        // RVA: 0x19F6654 Offset: 0x19F6654 VA: 0x19F6654
        public EIAMFNIAFGN()
        {
            KHEKNNFCAOI();
        }

        // RVA: 0x19FC608 Offset: 0x19FC608 VA: 0x19FC608
        public void KHEKNNFCAOI()
        {
			IPKCADIAAPG = new SakashoBbsCommentCriteria();
			MLPLGFLKKLI = 30;
			IGNIIEBMFIN = 1;
			MLMHPBOKJCL = 0;
		}
    }

    public class LNCLNAOPNKF
    {
        public int BOINIEAKFPL_Id { get; private set; } // 0x8 IOHKLFBFEIH KLEKIGODFHI IOINKEKIMID
        public string OODOEBCLCFI_ThreadGroup { get; private set; } // 0xC CLACFNHPEBC ECOAONNEHHO HAIPBFFCCBG
        public string ECAIHFNAAOM_Title { get; private set; } // 0x10 BMBEDMGFOCA OLLOMOEMAGL INAJMAIEKDG
        public JKHBHIGMJIC CCBEKGNDDBE { get; private set; } // 0x14 HCNCKGNGIII CNEPKBEMPPI CONDCLIAOOG
        // public bool AKGODCLMDMF { get; } 0x19F56C4 KNCKLGPKAGF

        // RVA: 0x19F92A4 Offset: 0x19F92A4 VA: 0x19F92A4
        public LNCLNAOPNKF(int BOINIEAKFPL, string OODOEBCLCFI, string ECAIHFNAAOM)
        {
			BOINIEAKFPL_Id = BOINIEAKFPL;
			OODOEBCLCFI_ThreadGroup = OODOEBCLCFI;
			ECAIHFNAAOM_Title = ECAIHFNAAOM;
		}

        // RVA: 0x19F7314 Offset: 0x19F7314 VA: 0x19F7314
        public LNCLNAOPNKF(JKHBHIGMJIC CCBEKGNDDBE)
		{
			BOINIEAKFPL_Id = CCBEKGNDDBE.LIBHMBKLMHF_Id;
			OODOEBCLCFI_ThreadGroup = CCBEKGNDDBE.BDJEICCDKHB_ThreadGroup;
			ECAIHFNAAOM_Title = CCBEKGNDDBE.ADCMNODJBGJ_Title;
			this.CCBEKGNDDBE = CCBEKGNDDBE;
		}
    }

    public class CAIPMAMHNJP
    {
        public LNCLNAOPNKF MENAGBMBJFJ { get; private set; } // 0x8 AFGKFAFHPBD NCADLAEHAKK AMKFLBDACAG
        // public int BOINIEAKFPL { get; } 0x19F6630 KLEKIGODFHI
        // public string ECAIHFNAAOM { get; } 0x19FC2F0 OLLOMOEMAGL
        public int OIPCCBHIKIA_Idx { get; private set; } // 0xC MPFBDIIBNBG HFCGOHDOHAP FOGFPKNLADC
        public BNAAJMBJFPG CCBEKGNDDBE { get; private set; } // 0x10 HCNCKGNGIII CNEPKBEMPPI CONDCLIAOOG
        // public bool ODIJEJPAJOG { get; } 0x19FC32C BDLBNABIFEC
        // public bool NEDCNFBIKBH { get; } 0x19FC35C BEPMIMNOMJP

        // // RVA: 0x19FC3C0 Offset: 0x19FC3C0 VA: 0x19FC3C0
        private CAIPMAMHNJP(LNCLNAOPNKF MENAGBMBJFJ, int OIPCCBHIKIA)
		{
			this.MENAGBMBJFJ = MENAGBMBJFJ;
			this.OIPCCBHIKIA_Idx = OIPCCBHIKIA;
		}

        // // RVA: 0x19F7E74 Offset: 0x19F7E74 VA: 0x19F7E74
        public CAIPMAMHNJP(LNCLNAOPNKF MENAGBMBJFJ, BNAAJMBJFPG CCBEKGNDDBE)
		{
			this.MENAGBMBJFJ = MENAGBMBJFJ;
			OIPCCBHIKIA_Idx = CCBEKGNDDBE.NPAHGHOHMHN_Idx;
			this.CCBEKGNDDBE = CCBEKGNDDBE;
		}

        // // RVA: 0x19FC3E8 Offset: 0x19FC3E8 VA: 0x19FC3E8
        public CAIPMAMHNJP(int BOINIEAKFPL, string KGICDMIJGDF, string ADCMNODJBGJ, BNAAJMBJFPG CCBEKGNDDBE)
		{
			MENAGBMBJFJ = new LNCLNAOPNKF(BOINIEAKFPL, KGICDMIJGDF, ADCMNODJBGJ);
			OIPCCBHIKIA_Idx = CCBEKGNDDBE.NPAHGHOHMHN_Idx;
			this.CCBEKGNDDBE = CCBEKGNDDBE;
		}
    }

    public delegate void DALALJLBNPL();

    private class GJJPNNCILLI
    {
        public LNCLNAOPNKF MENAGBMBJFJ; // 0x8
        public SakashoBbsCommentInfo HCAHCFGPJIF; // 0xC
        public DALALJLBNPL BHFHGFKBOHH; // 0x10
        public DJBHIFLHJLK MOBEEPPKFLG; // 0x14
        public DJBHIFLHJLK NKGHADCBGJO; // 0x18

        // // RVA: 0x19F7EB8 Offset: 0x19F7EB8 VA: 0x19F7EB8
        public GJJPNNCILLI(LNCLNAOPNKF MENAGBMBJFJ, SakashoBbsCommentInfo HCAHCFGPJIF, DALALJLBNPL BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, DJBHIFLHJLK NKGHADCBGJO)
		{
			this.MENAGBMBJFJ = MENAGBMBJFJ;
			this.HCAHCFGPJIF = HCAHCFGPJIF;
			this.BHFHGFKBOHH = BHFHGFKBOHH;
			this.MOBEEPPKFLG = MOBEEPPKFLG;
			this.NKGHADCBGJO = NKGHADCBGJO;
		}
    }

    private class DGGNPDDJNOO : IComparer<JKHBHIGMJIC>
    {
        // RVA: 0x19FC580 Offset: 0x19FC580 VA: 0x19FC580 Slot: 4
        public int Compare(JKHBHIGMJIC CIFFHLGLPMK, JKHBHIGMJIC OIKJFMGEICL)
		{
			return CIFFHLGLPMK.LIBHMBKLMHF_Id - OIKJFMGEICL.LIBHMBKLMHF_Id;
		}
    }

    private class ANNDCGIBEDA : IComparer<LNCLNAOPNKF>
    {
        // RVA: 0x19FC2A0 Offset: 0x19FC2A0 VA: 0x19FC2A0 Slot: 4
        public int Compare(LNCLNAOPNKF CIFFHLGLPMK, LNCLNAOPNKF OIKJFMGEICL)
        {
			return CIFFHLGLPMK.BOINIEAKFPL_Id - OIKJFMGEICL.BOINIEAKFPL_Id;
        }
    }

    private class HPDEJLPPKJE : IComparer<BNAAJMBJFPG>
    {
        // RVA: 0x19FC7E4 Offset: 0x19FC7E4 VA: 0x19FC7E4 Slot: 4
        public int Compare(BNAAJMBJFPG CIFFHLGLPMK, BNAAJMBJFPG OIKJFMGEICL)
		{
			return OIKJFMGEICL.NPAHGHOHMHN_Idx - CIFFHLGLPMK.NPAHGHOHMHN_Idx;
		}
    }

    // private class DIBEHLLPKAD : IComparer<BNAAJMBJFPG>
    // {
    //     // RVA: 0x19FC5C0 Offset: 0x19FC5C0 VA: 0x19FC5C0 Slot: 4
    //     public int Compare(BNAAJMBJFPG CIFFHLGLPMK, BNAAJMBJFPG OIKJFMGEICL) { }
    // }

    private class CGOJGMLAFOH : IComparer<CAIPMAMHNJP>
    {
        // RVA: 0x19FC498 Offset: 0x19FC498 VA: 0x19FC498 Slot: 4
        public int Compare(CAIPMAMHNJP CIFFHLGLPMK, CAIPMAMHNJP OIKJFMGEICL)
        {
			int res = OIKJFMGEICL.MENAGBMBJFJ.BOINIEAKFPL_Id - CIFFHLGLPMK.MENAGBMBJFJ.BOINIEAKFPL_Id;
			if(res == 0)
				res = OIKJFMGEICL.OIPCCBHIKIA_Idx - CIFFHLGLPMK.OIPCCBHIKIA_Idx;
			return res;
		}
    }

    private delegate void KCODNIFAICE(FPOEFNEPJDH_CreateBbsThread.OIPIPIHBJFM NFEAMMJIMPG);

    private class JKBGFAALHLL
    {
        public CAIPMAMHNJP HHJIGMPALKM; // 0x8
        public CAIPMAMHNJP CBPDHJAACAH; // 0xC
        public int FOEFBANLCIM; // 0x10
        public LNCLNAOPNKF PBLLHAMIBHA; // 0x14
        public int KIHNBLOPLNC; // 0x18
        public CAIPMAMHNJP OIMHHIFNGOI; // 0x1C

        // public bool DNJEMPANDNN { get; } 0x19F5CA4 EEHKLMFOEFK

        // // RVA: 0x19F5DAC Offset: 0x19F5DAC VA: 0x19F5DAC
        public void IPBDPLOKLLP()
		{
			KIHNBLOPLNC = 0;
			OIMHHIFNGOI = null;
			HHJIGMPALKM = null;
			CBPDHJAACAH = null;
			FOEFBANLCIM = 0;
			PBLLHAMIBHA = null;
		}
    }

	public const int KMOLPKLGFKD = 1;
	private static FKGOOHONBGI GHPCOLKAAFF; // 0x0
	private LNCLNAOPNKF LHKOLKACMPA; // 0x8
	private List<LNCLNAOPNKF> JKHNFFDFPEC; // 0xC
	private SakashoBbsThreadCriteria BIBOMJHJHMG; // 0x14
	private SakashoBbsThreadInfo OJAGHKJAJEJ; // 0x18
	private KCODNIFAICE EKKDNEFMCMO; // 0x1C
	private bool DCPNKOLMDKF; // 0x20
	private Queue<GJJPNNCILLI> HBPKDJCJELM; // 0x24
	private bool HBJNOPOKMCB; // 0x28
	private JKBGFAALHLL MLNOKNEECEO; // 0x2C
	private BNJJHPEGNAI.HCAJEKFFNBM EGJKCPAIFCM; // 0x30

	public static FKGOOHONBGI OGIFFNLIDIO { get {
        if(GHPCOLKAAFF == null)
            GHPCOLKAAFF = new FKGOOHONBGI();
        return GHPCOLKAAFF;
    } } //0x19F3BC8 IHHPMAEAFLJ
	public string OODOEBCLCFI_ThreadGroup { get; private set; } // 0x10 CLACFNHPEBC ECOAONNEHHO HAIPBFFCCBG
	private PJKLMCGEJMK CPHFEPHDJIB { get { return NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester; } } //0x19F3D04 JPEBBKJAMCK

	// // RVA: 0x19F3DA0 Offset: 0x19F3DA0 VA: 0x19F3DA0
	internal KEPNMGHABPI(BNJJHPEGNAI.HCAJEKFFNBM MENAGBMBJFJ)
    {
        JKHNFFDFPEC = new List<LNCLNAOPNKF>();
        HBPKDJCJELM = new Queue<GJJPNNCILLI>();
        MLNOKNEECEO = new JKBGFAALHLL();
        OODOEBCLCFI_ThreadGroup = MENAGBMBJFJ.KGICDMIJGDF;
        SakashoBbsThreadCriteria ctr = new SakashoBbsThreadCriteria();
        ctr.ThreadGroup = OODOEBCLCFI_ThreadGroup;
        ctr.ExcludeBlockedThreads = MENAGBMBJFJ.BDNDHFBNBLL_ExcludeBlockedThread;
        BIBOMJHJHMG = ctr;
        SakashoBbsThreadInfo inf = new SakashoBbsThreadInfo();
        inf.Title = MENAGBMBJFJ.ADCMNODJBGJ_Title;
        inf.ThreadGroup = OODOEBCLCFI_ThreadGroup;
        inf.Extra = MENAGBMBJFJ.KACECFNECON_Extra;
        inf.ExpireDays = MENAGBMBJFJ.EMGJJFKONHK_ExpireDays;
        inf.ApplyOwnerBlacklist = MENAGBMBJFJ.BDNDHFBNBLL_ExcludeBlockedThread ? 1 : 0;
        EGJKCPAIFCM = MENAGBMBJFJ;
        OJAGHKJAJEJ = inf;
    }

	// [ConditionalAttribute] // RVA: 0x6C2C30 Offset: 0x6C2C30 VA: 0x6C2C30
	// // RVA: 0x19F4098 Offset: 0x19F4098 VA: 0x19F4098
	// public void FKLIPCAKCCE(int HMFFHLPNMPH, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x19F409C Offset: 0x19F409C VA: 0x19F409C
    public void OMEFFONNMBC(int KPNKPGLPDHI, Action<LNCLNAOPNKF> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, SakashoBbsThreadCriteria IPKCADIAAPG)
    {
		AELPHOILEBM data = new AELPHOILEBM(this);
		if (IPKCADIAAPG == null)
			IPKCADIAAPG = BIBOMJHJHMG;
		data.IPKCADIAAPG = IPKCADIAAPG;
		data.MLPLGFLKKLI = 1;
		data.IGNIIEBMFIN = 1;
		data.MLMHPBOKJCL = 0;
		data.ADCMNODJBGJ_Title = OJAGHKJAJEJ.Title;
		HJCEIODJLOJ(KPNKPGLPDHI, data, (List<LNCLNAOPNKF> NMHGLNGACMI) =>
		{
			//0x19F8498
			data.MLPLGFLKKLI = 30;
			if(NMHGLNGACMI.IsEmpty())
			{
				Predicate<LNCLNAOPNKF> BAHANNNJCGC = (LNCLNAOPNKF OHMCIEMIKCE) =>
				{
					//0x19F8808
					return OHMCIEMIKCE.ECAIHFNAAOM_Title == data.ADCMNODJBGJ_Title;
				};
				Action<LNCLNAOPNKF> CMJMGEFNBDK = (LNCLNAOPNKF OHMCIEMIKCE) =>
				{
					//0x19F885C
					if(OHMCIEMIKCE != null)
					{
						if(OHMCIEMIKCE.CCBEKGNDDBE.OMMDEKMFBAF_CommentsCount != OHMCIEMIKCE.CCBEKGNDDBE.ADGNGHIJFFC_MaxComments)
						{
							LHKOLKACMPA = OHMCIEMIKCE;
							BHFHGFKBOHH(OHMCIEMIKCE);
							return;
						}
					}
					HJCEIODJLOJ(KPNKPGLPDHI, data, (List<LNCLNAOPNKF> JHOONHIHJNJ) =>
					{
						//0x19F89E0
						BHFHGFKBOHH(OMEFFONNMBC(KPNKPGLPDHI, JHOONHIHJNJ, true));
					}, MOBEEPPKFLG, false);
				};
				GBKJNMFNOJO(KPNKPGLPDHI, data, BAHANNNJCGC, CMJMGEFNBDK, MOBEEPPKFLG);
				return;
			}
			else
			{
				LNCLNAOPNKF d = OMEFFONNMBC(KPNKPGLPDHI, NMHGLNGACMI, true);
				if(d.CCBEKGNDDBE.OMMDEKMFBAF_CommentsCount == d.CCBEKGNDDBE.ADGNGHIJFFC_MaxComments)
				{
					Action<List<LNCLNAOPNKF>> DMLJLPMBLCH = (List<LNCLNAOPNKF> JHOONHIHJNJ) =>
					{
						//0x19F8758
						BHFHGFKBOHH(OMEFFONNMBC(KPNKPGLPDHI, JHOONHIHJNJ, true));
					};
					HJCEIODJLOJ(KPNKPGLPDHI, data, DMLJLPMBLCH, MOBEEPPKFLG, false);
					return;
				}
				BHFHGFKBOHH(d);
			}
		}, MOBEEPPKFLG, true);
	}

	// // RVA: 0x19F4470 Offset: 0x19F4470 VA: 0x19F4470
	public void FNKJBKJIKPC(int KPNKPGLPDHI, bool PAEAHCEJLKG, Action<List<LNCLNAOPNKF>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, KEPNMGHABPI.AELPHOILEBM NGHKJOEDLIP, SakashoBbsThreadCriteria IPKCADIAAPG)
	{
		if(NGHKJOEDLIP == null)
		{
			NGHKJOEDLIP = new AELPHOILEBM(this);
			if (IPKCADIAAPG == null)
				IPKCADIAAPG = BIBOMJHJHMG;
			NGHKJOEDLIP.IPKCADIAAPG = IPKCADIAAPG;
			NGHKJOEDLIP.ADCMNODJBGJ_Title = OJAGHKJAJEJ.Title;
		}
		OMBENJEDFLJ(KPNKPGLPDHI, NGHKJOEDLIP, new List<List<LNCLNAOPNKF>>(), BHFHGFKBOHH, MOBEEPPKFLG, PAEAHCEJLKG);
	}

	// // RVA: 0x19F4758 Offset: 0x19F4758 VA: 0x19F4758
	public void FNKJBKJIKPC(int KPNKPGLPDHI, Action<List<LNCLNAOPNKF>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, bool DJHLDMOPCOL)
	{
		AELPHOILEBM a = new AELPHOILEBM(this);
		a.IPKCADIAAPG = BIBOMJHJHMG;
		a.ADCMNODJBGJ_Title = null;
		if(!DJHLDMOPCOL)
		{
			a.ADCMNODJBGJ_Title = OJAGHKJAJEJ.Title;
		}
		FNKJBKJIKPC(KPNKPGLPDHI, false, BHFHGFKBOHH, MOBEEPPKFLG, a, null);
	}

	// // RVA: 0x19F42CC Offset: 0x19F42CC VA: 0x19F42CC
	public void HJCEIODJLOJ(int KPNKPGLPDHI, AELPHOILEBM NGHKJOEDLIP, Action<List<LNCLNAOPNKF>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, bool CBNPNMPLJPP = false)
	{
		OMBENJEDFLJ_GetThreads(KPNKPGLPDHI, NGHKJOEDLIP, (MMCLJMPEFEP_GetBbsThreads.CAMBPKCCBDO CHCEIJOJDHL) =>
		{
			//0x19F8A90
			ALNCDMPMEHP(KPNKPGLPDHI, LFAJKNNALBJ(), NGHKJOEDLIP, CHCEIJOJDHL.NMHGLNGACMI_Threads, BHFHGFKBOHH, MOBEEPPKFLG, CBNPNMPLJPP);
		}, MOBEEPPKFLG);
	}

	// // RVA: 0x19F4D08 Offset: 0x19F4D08 VA: 0x19F4D08
	// public void PCBGOOBFCPG(int BOINIEAKFPL, SakashoBbsThreadInfo KOGBMDOONFA, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x19F4EE8 Offset: 0x19F4EE8 VA: 0x19F4EE8
	// public void EBMBDKCCPOG(int BOINIEAKFPL, int EMGJJFKONHK, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x19F5260 Offset: 0x19F5260 VA: 0x19F5260
	// public void POFAKDOBFFN(int KPNKPGLPDHI, int BOINIEAKFPL, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x19F4F48 Offset: 0x19F4F48 VA: 0x19F4F48
	private SakashoBbsThreadInfo LFAJKNNALBJ()
	{
		SakashoBbsThreadInfo res = new SakashoBbsThreadInfo();
		if (!string.IsNullOrEmpty(OJAGHKJAJEJ.Title))
			res.Title = OJAGHKJAJEJ.Title;
		else
			res.Title = "none";
		res.Detail = OJAGHKJAJEJ.Detail;
		res.ThreadGroup = OJAGHKJAJEJ.ThreadGroup;
		res.MinCommentBytes = OJAGHKJAJEJ.MinCommentBytes;
		res.MaxCommentBytes = OJAGHKJAJEJ.MaxCommentBytes;
		res.MaxComments = OJAGHKJAJEJ.MaxComments;
		res.ExpireDays = OJAGHKJAJEJ.ExpireDays;
		res.Extra = OJAGHKJAJEJ.Extra;
		res.ApplyOwnerBlacklist = OJAGHKJAJEJ.ApplyOwnerBlacklist;
		return res;
	}

	// // RVA: 0x19F5424 Offset: 0x19F5424 VA: 0x19F5424
	// public SakashoBbsThreadInfo LFAJKNNALBJ(KEPNMGHABPI.LNCLNAOPNKF MENAGBMBJFJ) { }

	// // RVA: 0x19F56DC Offset: 0x19F56DC VA: 0x19F56DC
	public void HMOPLMHMNNP_GetComments(int KPNKPGLPDHI, int BOINIEAKFPL, EIAMFNIAFGN NGHKJOEDLIP, Action<NFIMGIABIOI_GetBbsThreadComments.CIIDLDOOKBB> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		if((KPNKPGLPDHI & 1) == 0)
		{
			NFIMGIABIOI_GetBbsThreadComments COJNCNGHIJC = CPHFEPHDJIB.IFFNCAFNEAG_AddRequest(new NFIMGIABIOI_GetBbsThreadComments());
			COJNCNGHIJC.BOINIEAKFPL_ThreadId = BOINIEAKFPL;
			COJNCNGHIJC.IPKCADIAAPG_Criteria = NGHKJOEDLIP.IPKCADIAAPG;
			COJNCNGHIJC.MLMHPBOKJCL_SortOrder = NGHKJOEDLIP.MLMHPBOKJCL;
			COJNCNGHIJC.IGNIIEBMFIN_Page = NGHKJOEDLIP.IGNIIEBMFIN;
			COJNCNGHIJC.MLPLGFLKKLI_Ipp = NGHKJOEDLIP.MLPLGFLKKLI;
			COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19F8C7C
				BHFHGFKBOHH(COJNCNGHIJC.NFEAMMJIMPG);
			};
			COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19F8BC0
				if (MOBEEPPKFLG != null)
					MOBEEPPKFLG();
			};
		}
		else
		{
			NFIMGIABIOI_GetBbsThreadComments COJNCNGHIJC = NKGJPJPHLIF.HHCJCDFCLOB.HKDHHMHHJOJ.IFFNCAFNEAG_AddRequest(new NFIMGIABIOI_GetBbsThreadComments());
			COJNCNGHIJC.BOINIEAKFPL_ThreadId = BOINIEAKFPL;
			COJNCNGHIJC.IPKCADIAAPG_Criteria = NGHKJOEDLIP.IPKCADIAAPG;
			COJNCNGHIJC.MLMHPBOKJCL_SortOrder = NGHKJOEDLIP.MLMHPBOKJCL;
			COJNCNGHIJC.IGNIIEBMFIN_Page = NGHKJOEDLIP.IGNIIEBMFIN;
			COJNCNGHIJC.MLPLGFLKKLI_Ipp = NGHKJOEDLIP.MLPLGFLKKLI;
			COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19F8BD4
				BHFHGFKBOHH(COJNCNGHIJC.NFEAMMJIMPG);
			};
			COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19F8BAC
				if (MOBEEPPKFLG != null)
					MOBEEPPKFLG();
			};
		}
	}

	// // RVA: 0x19F5B84 Offset: 0x19F5B84 VA: 0x19F5B84
	public bool JGGFDPHHKJD()
	{
		if(MLNOKNEECEO.FOEFBANLCIM < 1 && MLNOKNEECEO.HHJIGMPALKM == null)
		{
			if (MLNOKNEECEO.PBLLHAMIBHA == null && MLNOKNEECEO.CBPDHJAACAH == null)
				return true;
		}
		if(MLNOKNEECEO.CBPDHJAACAH != null)
		{
			if(MLNOKNEECEO.KIHNBLOPLNC == PKNGBAPOFHF(JKHNFFDFPEC).BOINIEAKFPL_Id)
			{
				if (MLNOKNEECEO.OIMHHIFNGOI == null)
					return false;
				return MLNOKNEECEO.OIMHHIFNGOI.OIPCCBHIKIA_Idx > 1;
			}
			return true;
		}
		return false;
	}

	// // RVA: 0x19F5D6C Offset: 0x19F5D6C VA: 0x19F5D6C
	public void IPBDPLOKLLP()
	{
		MLNOKNEECEO.IPBDPLOKLLP();
		LHKOLKACMPA = null;
	}

	// // RVA: 0x19F5DC8 Offset: 0x19F5DC8 VA: 0x19F5DC8
	public void EMHMAJDNEJB(int KPNKPGLPDHI, Action<List<CAIPMAMHNJP>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, int HMFFHLPNMPH = 30, SakashoBbsCommentCriteria EKALCDNBHBJ = null)
	{
		int POMLAOPLMNA = MLNOKNEECEO.FOEFBANLCIM;
		if(!(MLNOKNEECEO.FOEFBANLCIM < 1 && MLNOKNEECEO.HHJIGMPALKM == null && MLNOKNEECEO.PBLLHAMIBHA == null && MLNOKNEECEO.CBPDHJAACAH == null))
		{
			if (LHKOLKACMPA.BOINIEAKFPL_Id != MLNOKNEECEO.PBLLHAMIBHA.BOINIEAKFPL_Id)
			{
				for (int i = JKHNFFDFPEC.Count - 1; i > -1; i--)
				{
					if (JKHNFFDFPEC[i].BOINIEAKFPL_Id != MLNOKNEECEO.PBLLHAMIBHA.BOINIEAKFPL_Id)
					{
						if (JKHNFFDFPEC[i].BOINIEAKFPL_Id != MLNOKNEECEO.HHJIGMPALKM.MENAGBMBJFJ.BOINIEAKFPL_Id)
						{
							//LAB_019f6090
							if (JKHNFFDFPEC[i].CCBEKGNDDBE != null)
							{
								POMLAOPLMNA -= JKHNFFDFPEC[i].CCBEKGNDDBE.OMMDEKMFBAF_CommentsCount;
							}
						}
						else
						{
							POMLAOPLMNA -= MLNOKNEECEO.HHJIGMPALKM.OIPCCBHIKIA_Idx;
						}
						//joined_r0x019f5f7c
					}
				}
			}
			//LAB_019f60dc
		}
		{
			//LAB_019f60dc
			HMFFHLPNMPH = Mathf.Clamp(HMFFHLPNMPH, 1, 30);
			int page = 0;
			if (POMLAOPLMNA != 0)
				page = POMLAOPLMNA / HMFFHLPNMPH;
			POMLAOPLMNA -= HMFFHLPNMPH * page;
			EIAMFNIAFGN NGHKJOEDLIP = new EIAMFNIAFGN();
			NGHKJOEDLIP.KHEKNNFCAOI();
			if (EKALCDNBHBJ == null)
				EKALCDNBHBJ = new SakashoBbsCommentCriteria();
			NGHKJOEDLIP.IPKCADIAAPG = EKALCDNBHBJ;
			NGHKJOEDLIP.MLPLGFLKKLI = HMFFHLPNMPH;
			NGHKJOEDLIP.IGNIIEBMFIN = page;
			Action<List<LNCLNAOPNKF>> CCFKOHNLBHP = (List<LNCLNAOPNKF> NMHGLNGACMI) =>
			{
				//0x19F8D24
				OCKOIMLGLCF(KPNKPGLPDHI, new List<List<CAIPMAMHNJP>>(), POMLAOPLMNA, HMFFHLPNMPH, NMHGLNGACMI, NGHKJOEDLIP, BHFHGFKBOHH, MOBEEPPKFLG);
			};
			if(MLNOKNEECEO.FOEFBANLCIM < 1)
			{
				if(MLNOKNEECEO.HHJIGMPALKM == null && MLNOKNEECEO.PBLLHAMIBHA == null && MLNOKNEECEO.CBPDHJAACAH == null)
				{
					LNCLNAOPNKF FACJOMMDIPN = LHKOLKACMPA;
					OMEFFONNMBC(KPNKPGLPDHI, (LNCLNAOPNKF EOHFABJDJOH) =>
					{
						//0x19F8E00
						if(FACJOMMDIPN != null)
						{
							if(EOHFABJDJOH.BOINIEAKFPL_Id == FACJOMMDIPN.BOINIEAKFPL_Id)
							{
								if(!JKHNFFDFPEC.IsEmpty())
								{
									CCFKOHNLBHP(new List<LNCLNAOPNKF>(JKHNFFDFPEC));
									return;
								}
							}
						}
						FNKJBKJIKPC(KPNKPGLPDHI, true, CCFKOHNLBHP, MOBEEPPKFLG, null, null);
					}, MOBEEPPKFLG, null);
					return;
				}
			}
			List<LNCLNAOPNKF> l = new List<LNCLNAOPNKF>(JKHNFFDFPEC.Count);
			foreach(var k in JKHNFFDFPEC)
			{
				l.Add(k);
				if (MLNOKNEECEO.PBLLHAMIBHA.BOINIEAKFPL_Id == k.BOINIEAKFPL_Id)
					break;
			}
			CCFKOHNLBHP(l);
		}
	}

	// // RVA: 0x19F667C Offset: 0x19F667C VA: 0x19F667C
	public void IFFGEIMIKHH(int KPNKPGLPDHI, SakashoBbsCommentInfo KOGBMDOONFA, KEPNMGHABPI.DALALJLBNPL BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, DJBHIFLHJLK NKGHADCBGJO)
    {
        if(LHKOLKACMPA != null)
        {
            HLEABLHJPOI(KPNKPGLPDHI, LHKOLKACMPA, KOGBMDOONFA, BHFHGFKBOHH, MOBEEPPKFLG, NKGHADCBGJO);
        }
        else
        {
            OMEFFONNMBC(KPNKPGLPDHI, (LNCLNAOPNKF EOHFABJDJOH) =>
            {
                //0x19F9028
                HLEABLHJPOI(KPNKPGLPDHI, EOHFABJDJOH, KOGBMDOONFA, BHFHGFKBOHH, MOBEEPPKFLG, NKGHADCBGJO);
            }, MOBEEPPKFLG, null);
        }
    }

	// // RVA: 0x19F69C4 Offset: 0x19F69C4 VA: 0x19F69C4
	public void HCMMMCFFGCA_UpdateThreadComment(int KPNKPGLPDHI, int BOINIEAKFPL, int OIPCCBHIKIA, SakashoBbsCommentInfo KOGBMDOONFA, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		EKNLDDKJBEL_UpdateThreadComment req = CPHFEPHDJIB.IFFNCAFNEAG_AddRequest(new EKNLDDKJBEL_UpdateThreadComment());
		req.BOINIEAKFPL_ThreadId = BOINIEAKFPL;
		req.OJBGACKBOCA_CommentIdx = OIPCCBHIKIA;
		req.KOGBMDOONFA_Info = KOGBMDOONFA;
		req.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x19F907C
			BHFHGFKBOHH();
		};
		req.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x19F90A8
			if(MOBEEPPKFLG != null)	
				MOBEEPPKFLG();
		};
	}

	// // RVA: 0x19F6BBC Offset: 0x19F6BBC VA: 0x19F6BBC
	// public void NCLDLJLAEBK(int KPNKPGLPDHI, int BOINIEAKFPL, int OIPCCBHIKIA, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x19F6D9C Offset: 0x19F6D9C VA: 0x19F6D9C
	private void ALNCDMPMEHP(int KPNKPGLPDHI, SakashoBbsThreadInfo KOGBMDOONFA, AELPHOILEBM NGHKJOEDLIP, List<JKHBHIGMJIC> JCIBAFAILAG, Action<List<LNCLNAOPNKF>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, bool CBNPNMPLJPP = false)
	{
		if(!string.IsNullOrEmpty(NGHKJOEDLIP.ADCMNODJBGJ_Title))
		{
			JCIBAFAILAG.RemoveAll((JKHBHIGMJIC OHMCIEMIKCE) =>
			{
				//0x19F90FC
				return OHMCIEMIKCE.ADCMNODJBGJ_Title != NGHKJOEDLIP.ADCMNODJBGJ_Title;
			});
		}
		bool needCreate = JCIBAFAILAG.IsEmpty() && !CBNPNMPLJPP;
		if (!JCIBAFAILAG.IsEmpty() && !CBNPNMPLJPP)
		{
			JCIBAFAILAG.Sort(new DGGNPDDJNOO());
			needCreate = JCIBAFAILAG[JCIBAFAILAG.Count - 1].ADGNGHIJFFC_MaxComments <= JCIBAFAILAG[JCIBAFAILAG.Count - 1].OMMDEKMFBAF_CommentsCount;
		}
		int cnt = JCIBAFAILAG.Count;
		if (needCreate)
			cnt++;
		List<LNCLNAOPNKF> l = new List<LNCLNAOPNKF>(cnt);
		foreach(var k in JCIBAFAILAG)
		{
			l.Add(new LNCLNAOPNKF(k));
		}
		if(needCreate)
		{
			CDPCNICOHEH_CreateThread(KPNKPGLPDHI, KOGBMDOONFA, (FPOEFNEPJDH_CreateBbsThread.OIPIPIHBJFM CHCEIJOJDHL) =>
			{
				//0x19F9148
				LHKOLKACMPA = new LNCLNAOPNKF(CHCEIJOJDHL.LIBHMBKLMHF_ThreadId, KOGBMDOONFA.ThreadGroup, KOGBMDOONFA.Title);
				l.Add(LHKOLKACMPA);
				BHFHGFKBOHH(l);
			}, MOBEEPPKFLG);
		}
		else
		{
			BHFHGFKBOHH(l);
		}
	}

	// // RVA: 0x19F7614 Offset: 0x19F7614 VA: 0x19F7614
	private LNCLNAOPNKF OMEFFONNMBC(int KPNKPGLPDHI, List<LNCLNAOPNKF> NMHGLNGACMI, bool CILNIPJEECH = true)
    {
		if (CILNIPJEECH)
			LHKOLKACMPA = NMHGLNGACMI[NMHGLNGACMI.Count - 1];
		return NMHGLNGACMI[NMHGLNGACMI.Count - 1];
	}

	// // RVA: 0x19F5CE4 Offset: 0x19F5CE4 VA: 0x19F5CE4
	private LNCLNAOPNKF PKNGBAPOFHF(List<LNCLNAOPNKF> NMHGLNGACMI)
	{
		return NMHGLNGACMI[0];
	}

	// // RVA: 0x19F459C Offset: 0x19F459C VA: 0x19F459C
	private void OMBENJEDFLJ(int KPNKPGLPDHI, AELPHOILEBM NGHKJOEDLIP, List<List<LNCLNAOPNKF>> CHGLFGOKKJG, Action<List<LNCLNAOPNKF>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, bool PAEAHCEJLKG)
	{
		OMBENJEDFLJ_GetThreads(KPNKPGLPDHI, NGHKJOEDLIP, (MMCLJMPEFEP_GetBbsThreads.CAMBPKCCBDO CHCEIJOJDHL) =>
		{
			//0x19F92D4
			ALNCDMPMEHP(KPNKPGLPDHI, null, NGHKJOEDLIP, CHCEIJOJDHL.NMHGLNGACMI_Threads, (List<LNCLNAOPNKF> AIMLPJOGPID) =>
			{
				//0x19F989C
				CHGLFGOKKJG.Add(AIMLPJOGPID);
				if(CHCEIJOJDHL.MDIBIIHAAPN_NextPage > 0)
				{
					NGHKJOEDLIP.IGNIIEBMFIN = CHCEIJOJDHL.MDIBIIHAAPN_NextPage;
					OMBENJEDFLJ(KPNKPGLPDHI, NGHKJOEDLIP, CHGLFGOKKJG, BHFHGFKBOHH, MOBEEPPKFLG, PAEAHCEJLKG);
					return;
				}
				JKHNFFDFPEC = GAOPGAEHPEE(CHGLFGOKKJG, 1);
				JKHNFFDFPEC.Sort(new ANNDCGIBEDA());
				IMCBBOAFION CMJMGEFNBDK = () =>
				{
					//0x19F9434
					if(!JKHNFFDFPEC.IsEmpty())
					{
						LNCLNAOPNKF l = OMEFFONNMBC(KPNKPGLPDHI, JKHNFFDFPEC, false);
						if(l.CCBEKGNDDBE.OMMDEKMFBAF_CommentsCount < l.CCBEKGNDDBE.ADGNGHIJFFC_MaxComments)
						{
							BHFHGFKBOHH(new List<LNCLNAOPNKF>(JKHNFFDFPEC));
							return;
						}
					}
					if (PAEAHCEJLKG)
					{
						CDPCNICOHEH_CreateThread(KPNKPGLPDHI, LFAJKNNALBJ(), (FPOEFNEPJDH_CreateBbsThread.OIPIPIHBJFM OHMCIEMIKCE) =>
						{
							//0x19F96DC
							LNCLNAOPNKF l = new LNCLNAOPNKF(OHMCIEMIKCE.LIBHMBKLMHF_ThreadId, OJAGHKJAJEJ.ThreadGroup, OJAGHKJAJEJ.Title);
							JKHNFFDFPEC.Add(l);
							BHFHGFKBOHH(new List<LNCLNAOPNKF>(JKHNFFDFPEC));
						}, MOBEEPPKFLG);
						return;
					}
					BHFHGFKBOHH(new List<LNCLNAOPNKF>(JKHNFFDFPEC));
				};
				IEAMGJPEPMO(KPNKPGLPDHI, CMJMGEFNBDK, MOBEEPPKFLG);
			}, MOBEEPPKFLG, true);
		}, MOBEEPPKFLG);
	}

	// // RVA: 0x19F76EC Offset: 0x19F76EC VA: 0x19F76EC
	private void IEAMGJPEPMO(int KPNKPGLPDHI, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		//EGJKCPAIFCM.FGGKPMCKKGJ;
		BHFHGFKBOHH();
	}

	// // RVA: 0x19F77D8 Offset: 0x19F77D8 VA: 0x19F77D8
	private void GBKJNMFNOJO(int KPNKPGLPDHI, AELPHOILEBM NGHKJOEDLIP, Predicate<LNCLNAOPNKF> AFGNFIPIGHB, Action<LNCLNAOPNKF> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		OMBENJEDFLJ_GetThreads(KPNKPGLPDHI, NGHKJOEDLIP, (MMCLJMPEFEP_GetBbsThreads.CAMBPKCCBDO CHCEIJOJDHL) =>
		{
			//0x19F9CC4
			ALNCDMPMEHP(KPNKPGLPDHI, null, NGHKJOEDLIP, CHCEIJOJDHL.NMHGLNGACMI_Threads, (List<LNCLNAOPNKF> AIMLPJOGPID) =>
			{
				//0x19F9E24
				foreach(var k in AIMLPJOGPID)
				{
					if(AFGNFIPIGHB(k))
					{
						BHFHGFKBOHH(k);
						return;
					}
				}
				if (CHCEIJOJDHL.MDIBIIHAAPN_NextPage < 1)
				{
					BHFHGFKBOHH(null);
					return;
				}
				if (CHCEIJOJDHL != null)
				{
					NGHKJOEDLIP.IGNIIEBMFIN = CHCEIJOJDHL.MDIBIIHAAPN_NextPage;
					GBKJNMFNOJO(KPNKPGLPDHI, NGHKJOEDLIP, AFGNFIPIGHB, BHFHGFKBOHH, MOBEEPPKFLG);
					return;
				}
			}, MOBEEPPKFLG, true);
		}, MOBEEPPKFLG);
	}

	// // RVA: 0x19F4860 Offset: 0x19F4860 VA: 0x19F4860
	private void OMBENJEDFLJ_GetThreads(int KPNKPGLPDHI, AELPHOILEBM NGHKJOEDLIP, Action<MMCLJMPEFEP_GetBbsThreads.CAMBPKCCBDO> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		if((KPNKPGLPDHI & 1) == 0)
		{
			MMCLJMPEFEP_GetBbsThreads COJNCNGHIJC = CPHFEPHDJIB.IFFNCAFNEAG_AddRequest(new MMCLJMPEFEP_GetBbsThreads());
			COJNCNGHIJC.IPKCADIAAPG_Criteria = NGHKJOEDLIP.IPKCADIAAPG == null ? BIBOMJHJHMG : NGHKJOEDLIP.IPKCADIAAPG;
			COJNCNGHIJC.MLPLGFLKKLI_Ipp = NGHKJOEDLIP.MLPLGFLKKLI;
			COJNCNGHIJC.IGNIIEBMFIN_Page = NGHKJOEDLIP.IGNIIEBMFIN;
			COJNCNGHIJC.DFJDDIGFGKJ_SortKey = NGHKJOEDLIP.DFJDDIGFGKJ;
			COJNCNGHIJC.MLMHPBOKJCL_SortOrder = NGHKJOEDLIP.MLMHPBOKJCL;
			COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FA260
				BHFHGFKBOHH(COJNCNGHIJC.NFEAMMJIMPG);
			};
			COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FA1A4
				if (MOBEEPPKFLG != null)
					MOBEEPPKFLG();
			};
		}
		else
		{
			MMCLJMPEFEP_GetBbsThreads COJNCNGHIJC = NKGJPJPHLIF.HHCJCDFCLOB.HKDHHMHHJOJ.IFFNCAFNEAG_AddRequest(new MMCLJMPEFEP_GetBbsThreads());
			COJNCNGHIJC.IPKCADIAAPG_Criteria = NGHKJOEDLIP.IPKCADIAAPG == null ? BIBOMJHJHMG : NGHKJOEDLIP.IPKCADIAAPG;
			COJNCNGHIJC.MLPLGFLKKLI_Ipp = NGHKJOEDLIP.MLPLGFLKKLI;
			COJNCNGHIJC.IGNIIEBMFIN_Page = NGHKJOEDLIP.IGNIIEBMFIN;
			COJNCNGHIJC.DFJDDIGFGKJ_SortKey = NGHKJOEDLIP.DFJDDIGFGKJ;
			COJNCNGHIJC.MLMHPBOKJCL_SortOrder = NGHKJOEDLIP.MLMHPBOKJCL;
			COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FA1B8
				BHFHGFKBOHH(COJNCNGHIJC.NFEAMMJIMPG);
			};
			COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FA190
				if (MOBEEPPKFLG != null)
					MOBEEPPKFLG();
			};
		}
	}

	// // RVA: 0x19F7398 Offset: 0x19F7398 VA: 0x19F7398
	private void CDPCNICOHEH_CreateThread(int KPNKPGLPDHI, SakashoBbsThreadInfo KOGBMDOONFA, KCODNIFAICE BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		EKKDNEFMCMO += BHFHGFKBOHH;
		if(!DCPNKOLMDKF)
		{
			DCPNKOLMDKF = true;
			FPOEFNEPJDH_CreateBbsThread COJNCNGHIJC = CPHFEPHDJIB.IFFNCAFNEAG_AddRequest(new FPOEFNEPJDH_CreateBbsThread());
			COJNCNGHIJC.KOGBMDOONFA = KOGBMDOONFA;
			COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FA308
				DCPNKOLMDKF = false;
				EKKDNEFMCMO(COJNCNGHIJC.NFEAMMJIMPG);
				EKKDNEFMCMO = (FPOEFNEPJDH_CreateBbsThread.OIPIPIHBJFM OHMCIEMIKCE) =>
				{
					//0x19F8484
					return;
				};
			};
			COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
			{
				//0x19FACCC
				DCPNKOLMDKF = false;
				MOBEEPPKFLG();
			};
		}
	}

	// // RVA: 0x19F79A0 Offset: 0x19F79A0 VA: 0x19F79A0
	private void OCKOIMLGLCF(int KPNKPGLPDHI, List<List<CAIPMAMHNJP>> GHIHLNKPKGH, int POMLAOPLMNA, int HMFFHLPNMPH, List<KEPNMGHABPI.LNCLNAOPNKF> NMHGLNGACMI, KEPNMGHABPI.EIAMFNIAFGN NGHKJOEDLIP, Action<List<KEPNMGHABPI.CAIPMAMHNJP>> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG)
	{
		LNCLNAOPNKF GNAOMJEPCLO = OMEFFONNMBC(KPNKPGLPDHI, NMHGLNGACMI, false);
		HMOPLMHMNNP_GetComments(KPNKPGLPDHI, GNAOMJEPCLO.BOINIEAKFPL_Id, NGHKJOEDLIP, (NFIMGIABIOI_GetBbsThreadComments.CIIDLDOOKBB CHCEIJOJDHL) =>
		{
			//0x19FAD18
			LNCLNAOPNKF data = new LNCLNAOPNKF(CHCEIJOJDHL.OHJPNDKBFEC_Thread);
			List<CAIPMAMHNJP> l = FNPFFILDFEI(data, CHCEIJOJDHL.GLNIHJIDABD_Comments);
			if(MLNOKNEECEO.HHJIGMPALKM == null)
			{
				if(!l.IsEmpty())
				{
					MLNOKNEECEO.HHJIGMPALKM = l[0];
				}
			}
			else
			{
				if(GNAOMJEPCLO.BOINIEAKFPL_Id == MLNOKNEECEO.PBLLHAMIBHA.BOINIEAKFPL_Id)
				{
					if(MLNOKNEECEO.PBLLHAMIBHA.CCBEKGNDDBE != null)
					{
						POMLAOPLMNA = CHCEIJOJDHL.OHJPNDKBFEC_Thread.OMMDEKMFBAF_CommentsCount + POMLAOPLMNA - MLNOKNEECEO.PBLLHAMIBHA.CCBEKGNDDBE.OMMDEKMFBAF_CommentsCount;
					}
				}
			}
			int cnt = Mathf.Min(POMLAOPLMNA, l.Count);
			l.RemoveRange(0, cnt);
			if(HMFFHLPNMPH < l.Count)
			{
				l.RemoveRange(HMFFHLPNMPH, l.Count - HMFFHLPNMPH);
			}
			GHIHLNKPKGH.Add(l);
			MLNOKNEECEO.PBLLHAMIBHA = data;
			MLNOKNEECEO.KIHNBLOPLNC = data.BOINIEAKFPL_Id;
			MLNOKNEECEO.FOEFBANLCIM += l.Count;
			if(!l.IsEmpty())
			{
				MLNOKNEECEO.CBPDHJAACAH = l[l.Count - 1];
				MLNOKNEECEO.OIMHHIFNGOI = l[l.Count - 1];
			}
			else
			{
				MLNOKNEECEO.OIMHHIFNGOI = null;
			}
			if(HMFFHLPNMPH <= l.Count)
			{
				List<CAIPMAMHNJP> l2 = GAOPGAEHPEE<CAIPMAMHNJP>(GHIHLNKPKGH, 0);
				l2.Sort(new CGOJGMLAFOH());
				BHFHGFKBOHH(l2);
				return;
			}
			if(CHCEIJOJDHL.MDIBIIHAAPN_NextPage < 1)
			{
				if(NMHGLNGACMI.Count < 2)
				{
					List<CAIPMAMHNJP> l2 = GAOPGAEHPEE<CAIPMAMHNJP>(GHIHLNKPKGH, 0);
					l2.Sort(new CGOJGMLAFOH());
					BHFHGFKBOHH(l2);
					return;
				}
				NMHGLNGACMI.Remove(GNAOMJEPCLO);
				NGHKJOEDLIP.IGNIIEBMFIN = 1;
			}
			else
			{
				NGHKJOEDLIP.IGNIIEBMFIN = 1 + (NGHKJOEDLIP.IGNIIEBMFIN * NGHKJOEDLIP.MLPLGFLKKLI + POMLAOPLMNA) / NGHKJOEDLIP.MLPLGFLKKLI;
			}
			POMLAOPLMNA = 0;
			OCKOIMLGLCF(KPNKPGLPDHI, GHIHLNKPKGH, 0, Mathf.Max(HMFFHLPNMPH - l.Count, 0), NMHGLNGACMI, NGHKJOEDLIP, BHFHGFKBOHH, MOBEEPPKFLG);
		}, MOBEEPPKFLG);
	}

	// // RVA: 0x19F7C0C Offset: 0x19F7C0C VA: 0x19F7C0C
	private List<CAIPMAMHNJP> FNPFFILDFEI(LNCLNAOPNKF MENAGBMBJFJ, List<BNAAJMBJFPG> GLNIHJIDABD)
	{
		List<CAIPMAMHNJP> res = new List<CAIPMAMHNJP>(GLNIHJIDABD.Count);
		GLNIHJIDABD.Sort(new HPDEJLPPKJE());
		foreach(var k in GLNIHJIDABD)
		{
			res.Add(new CAIPMAMHNJP(MENAGBMBJFJ, k));
		}
		return res;
	}

	// // RVA: 0x19F68A0 Offset: 0x19F68A0 VA: 0x19F68A0
	private void HLEABLHJPOI(int KPNKPGLPDHI, LNCLNAOPNKF MENAGBMBJFJ, SakashoBbsCommentInfo KOGBMDOONFA, DALALJLBNPL BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, DJBHIFLHJLK NKGHADCBGJO)
    {
		GJJPNNCILLI g = new GJJPNNCILLI(MENAGBMBJFJ, KOGBMDOONFA, BHFHGFKBOHH, MOBEEPPKFLG, NKGHADCBGJO);
		HBPKDJCJELM.Enqueue(g);
		if (HBJNOPOKMCB)
			return;
		HBJNOPOKMCB = true;
		N.a.StartCoroutineWatched(HANCEBLBOPF_Co_DequeueComments(KPNKPGLPDHI));
	}

	// [IteratorStateMachineAttribute] // RVA: 0x6C2C64 Offset: 0x6C2C64 VA: 0x6C2C64
	// // RVA: 0x19F7EF8 Offset: 0x19F7EF8 VA: 0x19F7EF8
	private IEnumerator HANCEBLBOPF_Co_DequeueComments(int KPNKPGLPDHI)
	{
		//0x19FBE6C
		while(HBPKDJCJELM.Count > 0)
		{
			bool BEKAMBBOLBO = false;
			GJJPNNCILLI CKHEDJODNIP = HBPKDJCJELM.Dequeue();
			if (LHKOLKACMPA != null)
			{
				CKHEDJODNIP.MENAGBMBJFJ = LHKOLKACMPA;
			}
			BEJLIJGIGOL(KPNKPGLPDHI, CKHEDJODNIP.MENAGBMBJFJ, CKHEDJODNIP.HCAHCFGPJIF, () =>
			{
				//0x19FB6D8
				BEKAMBBOLBO = true;
				CKHEDJODNIP.BHFHGFKBOHH();
			}, () =>
			{
				//0x19FBB58
				BEKAMBBOLBO = true;
				CKHEDJODNIP.MOBEEPPKFLG();
			}, () =>
			{
				//0x19FBBA0
				BEKAMBBOLBO = true;
				CKHEDJODNIP.NKGHADCBGJO();
			});
			while (!BEKAMBBOLBO)
				yield return null;
			yield return null;
		}
		HBJNOPOKMCB = false;
	}

	// // RVA: 0x19F7FC0 Offset: 0x19F7FC0 VA: 0x19F7FC0
	private void BEJLIJGIGOL(int KPNKPGLPDHI, LNCLNAOPNKF MENAGBMBJFJ, SakashoBbsCommentInfo KOGBMDOONFA, DALALJLBNPL BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, DJBHIFLHJLK NKGHADCBGJO)
	{
		IECJNEHIEKO_CreateBbsComment COJNCNGHIJC = CPHFEPHDJIB.IFFNCAFNEAG_AddRequest(new IECJNEHIEKO_CreateBbsComment());
		AHAENNIFOAF.IANGEPFFHHM(MENAGBMBJFJ.OODOEBCLCFI_ThreadGroup, ref COJNCNGHIJC.JECLCENDGIH_ThreadType, ref COJNCNGHIJC.GFOIDCMEHGL_RoomUserId, ref COJNCNGHIJC.DNJLJMKKDNA_EventId, ref COJNCNGHIJC.MEBHCFJCKFE_LobbyId);
		COJNCNGHIJC.BDJEICCDKHB_ThreadGroup = MENAGBMBJFJ.OODOEBCLCFI_ThreadGroup;
		COJNCNGHIJC.BOINIEAKFPL_ThreadId = MENAGBMBJFJ.BOINIEAKFPL_Id;
		COJNCNGHIJC.KOGBMDOONFA_Info = KOGBMDOONFA;
		COJNCNGHIJC.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x19FBBE8
			BHFHGFKBOHH();
		};
		COJNCNGHIJC.NBFDEFGFLPJ = (SakashoErrorId CNAIDEAFAAM) =>
		{
			//0x19F8488
			return CNAIDEAFAAM == SakashoErrorId.MAX_COMMENTS_EXCEEDED;
		};
		COJNCNGHIJC.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x19FBC10
			if(COJNCNGHIJC.NPNNPNAIONN_IsError)
			{
				if(COJNCNGHIJC.CJMFJOMECKI_ErrorId == SakashoErrorId.MAX_COMMENTS_EXCEEDED)
				{
					OMEFFONNMBC(KPNKPGLPDHI, (LNCLNAOPNKF EOHFABJDJOH) =>
					{
						//0x19FBDFC
						BEJLIJGIGOL(KPNKPGLPDHI, EOHFABJDJOH, KOGBMDOONFA, BHFHGFKBOHH, MOBEEPPKFLG, NKGHADCBGJO);
					}, () =>
					{
						//0x19FBE54
						if (MOBEEPPKFLG != null)
							MOBEEPPKFLG();
					}, null);
					return;
				}
			}
			if(COJNCNGHIJC.NPNNPNAIONN_IsError)
			{
				if(COJNCNGHIJC.CJMFJOMECKI_ErrorId == SakashoErrorId.NG_WORD_INCLUDED)
				{
					if (NKGHADCBGJO != null)
						NKGHADCBGJO();
					return;
				}
			}
			if (MOBEEPPKFLG != null)
				MOBEEPPKFLG();
		};
	}

	// // RVA: -1 Offset: -1
	private List<T> GAOPGAEHPEE<T>(List<List<T>> EKGFBEFBLEG, int KPKBLPNEBOG = 0)
	{
		int cnt = 0;
		foreach(var d in EKGFBEFBLEG)
		{
			cnt += d.Count;
		}
		List<T> res = new List<T>(cnt + KPKBLPNEBOG);
		foreach (var d in EKGFBEFBLEG)
		{
			res.AddRange(d);
		}
		return res;
	}
	// /* GenericInstMethod :
	// |
	// |-RVA: 0x1A24BB4 Offset: 0x1A24BB4 VA: 0x1A24BB4
	// |-KEPNMGHABPI.GAOPGAEHPEE<KEPNMGHABPI.CAIPMAMHNJP>
	// |-KEPNMGHABPI.GAOPGAEHPEE<KEPNMGHABPI.LNCLNAOPNKF>
	// |-KEPNMGHABPI.GAOPGAEHPEE<object>
	// */

	// [ConditionalAttribute] // RVA: 0x6C2CDC Offset: 0x6C2CDC VA: 0x6C2CDC
	// // RVA: 0x19F8404 Offset: 0x19F8404 VA: 0x19F8404
	// private void GNGCAIPOOMC(object IPBHCLIHAPG, string DOKKMMFKLJI = "cyan") { }
}
