public class KGCNCBOKCBA
{
	public enum GNENJEHKMHD
	{
		HJNNKCMLGFL = 0,
		FFLKPBPBPEP = 1,
		NCJFJLPJMLI = 2,
		MINDIGBAJFG = 3,
		GDOPLACICFE = 4,
		MEAJLPAHINL = 5,
		EMAMLLFAOJI = 6,
		EIFKDKFAHPH = 7,
		DDEODFNANDO = 8,
		BCKENOKGLIJ = 9,
		HINPDNKNAHO = 10,
		DOAENCHBAEO = 11,
		KPMNPGKKFJG = 6,
		EBPGLJPNGEB = 6,
	}

}
