public class KGCNCBOKCBA
{
	public enum GNENJEHKMHD
	{
		HJNNKCMLGFL = 0,
		FFLKPBPBPEP_1 = 1,
		NCJFJLPJMLI_2 = 2,
		MINDIGBAJFG_3 = 3,
		GDOPLACICFE_4 = 4,
		MEAJLPAHINL_5 = 5,
		EMAMLLFAOJI_6 = 6,
		EIFKDKFAHPH_7 = 7,
		DDEODFNANDO_8 = 8,
		BCKENOKGLIJ_9 = 9,
		HINPDNKNAHO_10 = 10,
		DOAENCHBAEO_11 = 11,
		KPMNPGKKFJG = 6,
		EBPGLJPNGEB = 6,
	}

}
