public class KGCNCBOKCBA
{
	public enum GNENJEHKMHD
	{
		HJNNKCMLGFL = 0,
		FFLKPBPBPEP = 1,
		NCJFJLPJMLI = 2,
		MINDIGBAJFG = 3,
		GDOPLACICFE = 4,
		MEAJLPAHINL_5 = 5,
		EMAMLLFAOJI_6 = 6,
		EIFKDKFAHPH = 7,
		DDEODFNANDO = 8,
		BCKENOKGLIJ_9 = 9,
		HINPDNKNAHO_10 = 10,
		DOAENCHBAEO_11 = 11,
		KPMNPGKKFJG = 6,
		EBPGLJPNGEB = 6,
	}

}
