
using System.Collections.Generic;
using UnityEngine;
using XeApp.Game.Menu;

public class LAMCONGFONF
{
	public class OJFOLGKMBIG
	{
		public int FJOLNJLLJEJ; // 0x8
		public int DNBFMLBNAEE; // 0xC
		public bool BEKAMBBOLBO; // 0x10
	}

	public bool PLOOEECNHFB; // 0x8
	public bool NPNNPNAIONN; // 0x9
	public bool FKKDIDMGLMI; // 0xA
	public bool FLCLIHBOHCH = true; // 0xB
	public bool DPPIBCENJJJ; // 0xC
	public List<RankingListInfo> HGGPIBNLALJ = new List<RankingListInfo>(); // 0x10
	public List<RankingListInfo> BMKBAMFBAPJ = new List<RankingListInfo>(); // 0x14
	private OJFOLGKMBIG[] KIAFBCEKMEA = new OJFOLGKMBIG[10]; // 0x18
	private OJFOLGKMBIG[] CEPDOODGDEM = new OJFOLGKMBIG[10]; // 0x1C
	private EECOJKDJIFG[] AEJCLHOIDDD = new EECOJKDJIFG[10]; // 0x20

	public static LAMCONGFONF HHCJCDFCLOB { get; private set; } // 0x0 NKACBOEHELJ OKPMHKNCNAL

	//// RVA: 0xD907F8 Offset: 0xD907F8 VA: 0xD907F8
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
	}

	//// RVA: 0xD9085C Offset: 0xD9085C VA: 0xD9085C
	public bool ECKDEPDMHGP()
	{
		JPJGOECJFEE_EventGoDivaRanking dbGo = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking;
		if(dbGo != null)
		{
			for(int i = 0; i < dbGo.NGHKJOEDLIP.MPCAGEPEJJJ.Count; i++)
			{
				KIAFBCEKMEA[i] = new OJFOLGKMBIG();
				CEPDOODGDEM[i] = new OJFOLGKMBIG();
				string OCGFKMHNEOF = dbGo.NGHKJOEDLIP.MPCAGEPEJJJ[i];
				AEJCLHOIDDD[i] = KKLGENJKEBN.HHCJCDFCLOB.JPDPFGFMKHK.Find((EECOJKDJIFG PKLPKMLGFGK) => {
					//0xD92A98
					return PKLPKMLGFGK.OCGFKMHNEOF == OCGFKMHNEOF;
				});
				if(AEJCLHOIDDD[i] == null)
					return false;
			}
			return true;
		}
		return false;
	}

	//// RVA: 0xD90CA0 Offset: 0xD90CA0 VA: 0xD90CA0
	//public LAMCONGFONF.OJFOLGKMBIG CEPOFDBHIAC(int LHJCOPMMIGO, bool PFFJNEFNAMI = False) { }

	//// RVA: 0xD90CF4 Offset: 0xD90CF4 VA: 0xD90CF4
	//public List<int> IFHPGJGLPPF() { }

	//// RVA: 0xD90F38 Offset: 0xD90F38 VA: 0xD90F38
	//public void FAMFKPBPIAA(int LHJCOPMMIGO, bool PFFJNEFNAMI, int CJHEHIMLGGL, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0xD912B4 Offset: 0xD912B4 VA: 0xD912B4
	//public void JPNACOLKHLB(int CJHEHIMLGGL, int NEFEFHBHFFF, int KKGKLNDOCFI, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0xD914C0 Offset: 0xD914C0 VA: 0xD914C0
	//public void HDAMBNOFGAN(int LHJCOPMMIGO, bool PFFJNEFNAMI) { }

	//// RVA: 0xD9152C Offset: 0xD9152C VA: 0xD9152C
	//public void HEOKADCEAGL(int LHJCOPMMIGO, bool PFFJNEFNAMI, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0xD918D8 Offset: 0xD918D8 VA: 0xD918D8
	//public void AMKJFGLEJGE(int LHJCOPMMIGO, int ABLHIAEDJAI, long JHNMKKNEENE) { }

	//// RVA: 0xD91C8C Offset: 0xD91C8C VA: 0xD91C8C
	//public void FGMOMBKGCNF(int LHJCOPMMIGO, int ABLHIAEDJAI = 0, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK NIMPEHIECJH, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0xD91F48 Offset: 0xD91F48 VA: 0xD91F48
	//private void EJHFJGKPHCM(int NEFEFHBHFFF, List<IBIGBMDANNM> NNDGIAEFMOG, int KKGKLNDOCFI) { }

	//// RVA: 0xD92330 Offset: 0xD92330 VA: 0xD92330
	//private void CBDFJFCGKNK(int NEFEFHBHFFF, List<IBIGBMDANNM> NNDGIAEFMOG, int KKGKLNDOCFI) { }

	//// RVA: 0xD91244 Offset: 0xD91244 VA: 0xD91244
	//private EECOJKDJIFG DAKMIKNKHMF(int LHJCOPMMIGO) { }

	//// RVA: 0xD92718 Offset: 0xD92718 VA: 0xD92718
	//public static int BFKAHKBKBJE(int FJOLNJLLJEJ, long EAKFLINAPOG) { }
}
