
using System.Collections.Generic;
using UnityEngine;
using XeApp.Game.Menu;

public class LAMCONGFONF
{
	public class OJFOLGKMBIG
	{
		public int FJOLNJLLJEJ_Rank; // 0x8
		public int DNBFMLBNAEE_Score; // 0xC
		public bool BEKAMBBOLBO; // 0x10
	}

	public bool PLOOEECNHFB_IsDone; // 0x8
	public bool NPNNPNAIONN_IsError; // 0x9
	public bool FKKDIDMGLMI; // 0xA
	public bool FLCLIHBOHCH = true; // 0xB
	public bool DPPIBCENJJJ; // 0xC
	public List<RankingListInfo> HGGPIBNLALJ = new List<RankingListInfo>(); // 0x10
	public List<RankingListInfo> BMKBAMFBAPJ = new List<RankingListInfo>(); // 0x14
	private OJFOLGKMBIG[] KIAFBCEKMEA = new OJFOLGKMBIG[10]; // 0x18
	private OJFOLGKMBIG[] CEPDOODGDEM = new OJFOLGKMBIG[10]; // 0x1C
	private EECOJKDJIFG[] AEJCLHOIDDD = new EECOJKDJIFG[10]; // 0x20

	public static LAMCONGFONF HHCJCDFCLOB { get; private set; } // 0x0 NKACBOEHELJ OKPMHKNCNAL

	//// RVA: 0xD907F8 Offset: 0xD907F8 VA: 0xD907F8
	public void IJBGPAENLJA(MonoBehaviour DANMJLOBLIE)
	{
		HHCJCDFCLOB = this;
	}

	//// RVA: 0xD9085C Offset: 0xD9085C VA: 0xD9085C
	public bool ECKDEPDMHGP()
	{
		JPJGOECJFEE_EventGoDivaRanking dbGo = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking;
		if(dbGo != null)
		{
			for(int i = 0; i < dbGo.NGHKJOEDLIP.MPCAGEPEJJJ.Count; i++)
			{
				KIAFBCEKMEA[i] = new OJFOLGKMBIG();
				CEPDOODGDEM[i] = new OJFOLGKMBIG();
				string OCGFKMHNEOF = dbGo.NGHKJOEDLIP.MPCAGEPEJJJ[i];
				AEJCLHOIDDD[i] = KKLGENJKEBN.HHCJCDFCLOB.JPDPFGFMKHK.Find((EECOJKDJIFG PKLPKMLGFGK) => {
					//0xD92A98
					return PKLPKMLGFGK.OCGFKMHNEOF_NameForApi == OCGFKMHNEOF;
				});
				if(AEJCLHOIDDD[i] == null)
					return false;
			}
			return true;
		}
		return false;
	}

	//// RVA: 0xD90CA0 Offset: 0xD90CA0 VA: 0xD90CA0
	public OJFOLGKMBIG CEPOFDBHIAC(int LHJCOPMMIGO, bool PFFJNEFNAMI = false)
	{
		if (PFFJNEFNAMI)
			return CEPDOODGDEM[LHJCOPMMIGO];
		else
			return KIAFBCEKMEA[LHJCOPMMIGO];
	}

	//// RVA: 0xD90CF4 Offset: 0xD90CF4 VA: 0xD90CF4
	public List<int> IFHPGJGLPPF()
	{
		List<int> res = new List<int>();
		if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking != null)
		{
			res.AddRange(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking.NGHKJOEDLIP.JHPCPNJJHLI);
			res.Sort((int HKICMNAACDA, int BNKHBCBJBKI) =>
			{
				//0xD92A90
				return HKICMNAACDA - BNKHBCBJBKI;
			});
		}
		return res;
	}

	//// RVA: 0xD90F38 Offset: 0xD90F38 VA: 0xD90F38
	public void FAMFKPBPIAA(int LHJCOPMMIGO, bool PFFJNEFNAMI, int CJHEHIMLGGL, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG)
	{
		DPPIBCENJJJ = false;
		PLOOEECNHFB_IsDone = false;
		NPNNPNAIONN_IsError = false;
		EECOJKDJIFG e = DAKMIKNKHMF(LHJCOPMMIGO);
		if(e == null)
		{
			PLOOEECNHFB_IsDone = true;
			if (IDAEHNGOKAE != null)
				IDAEHNGOKAE();
		}
		else
		{
			OJFOLGKMBIG[] ONJBNDCMMNL;
			if (PFFJNEFNAMI)
				ONJBNDCMMNL = CEPDOODGDEM;
			else
				ONJBNDCMMNL = KIAFBCEKMEA;
			KKLGENJKEBN.HHCJCDFCLOB.FAMFKPBPIAA_GetRankingPlayerList(e.OCGFKMHNEOF_NameForApi, PFFJNEFNAMI, CJHEHIMLGGL, LHJCOPMMIGO, (int NEFEFHBHFFF, List<IBIGBMDANNM> MAGKKPOFJIM) =>
			{
				//0xD92ACC
				ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = true;
				HGGPIBNLALJ.Clear();
				if(MAGKKPOFJIM != null)
				{
					int ANKHNOGKHDD = NKGJPJPHLIF.HHCJCDFCLOB.CAFHLEFMMGD_GetPlayerId();
					IBIGBMDANNM d = MAGKKPOFJIM.Find((IBIGBMDANNM GHPLINIACBB) =>
					{
						//0xD93100
						return GHPLINIACBB.MLPEHNBNOGD_Id == ANKHNOGKHDD;
					});
					if(d != null)
					{
						ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = d.FJOLNJLLJEJ_Rank;
						ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = (int)d.KNIFCANOHOC_Score;
					}
					EJHFJGKPHCM(NEFEFHBHFFF, MAGKKPOFJIM, CJHEHIMLGGL);
				}
				PLOOEECNHFB_IsDone = true;
				if (KLMFJJCNBIP != null)
					KLMFJJCNBIP();
			}, () =>
			{
				//0xD92E70
				ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = false;
				PLOOEECNHFB_IsDone = true;
				if (IDAEHNGOKAE != null)
					IDAEHNGOKAE();
			}, () =>
			{
				//0xD92FAC
				ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
				ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = false;
				PLOOEECNHFB_IsDone = true;
				NPNNPNAIONN_IsError = true;
				if (JGKOLBLPMPG != null)
					JGKOLBLPMPG();
			}, true);
		}
	}

	//// RVA: 0xD912B4 Offset: 0xD912B4 VA: 0xD912B4
	public void JPNACOLKHLB(int CJHEHIMLGGL, int NEFEFHBHFFF, int KKGKLNDOCFI, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG)
	{
		TodoLogger.LogError(0, "JPNACOLKHLB");
	}

	//// RVA: 0xD914C0 Offset: 0xD914C0 VA: 0xD914C0
	public void HDAMBNOFGAN(int LHJCOPMMIGO, bool PFFJNEFNAMI)
	{
		if (PFFJNEFNAMI)
			CEPDOODGDEM[LHJCOPMMIGO].BEKAMBBOLBO = false;
		else
			KIAFBCEKMEA[LHJCOPMMIGO].BEKAMBBOLBO = false;
	}

	//// RVA: 0xD9152C Offset: 0xD9152C VA: 0xD9152C
	public void HEOKADCEAGL(int LHJCOPMMIGO, bool PFFJNEFNAMI, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK IDAEHNGOKAE, DJBHIFLHJLK JGKOLBLPMPG)
	{
		PLOOEECNHFB_IsDone = false;
		NPNNPNAIONN_IsError = false;
		EECOJKDJIFG e = DAKMIKNKHMF(LHJCOPMMIGO);
		if(e == null)
		{
			PLOOEECNHFB_IsDone = true;
			if (IDAEHNGOKAE != null)
				IDAEHNGOKAE();
		}
		else
		{
			OJFOLGKMBIG[] ONJBNDCMMNL;
			if (PFFJNEFNAMI)
				ONJBNDCMMNL = CEPDOODGDEM;
			else
				ONJBNDCMMNL = KIAFBCEKMEA;
			if(!ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO)
			{
				KKLGENJKEBN.HHCJCDFCLOB.HEOKADCEAGL_GetRanks(e.OCGFKMHNEOF_NameForApi, () =>
				{
					//0xD93350
					ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = (int)KKLGENJKEBN.HHCJCDFCLOB.LPPCNCMEDFA_Rank;
					ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = (int)KKLGENJKEBN.HHCJCDFCLOB.IPNEJCOFBIB_ScoreTrunc;
					ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = true;
					PLOOEECNHFB_IsDone = true;
					if (KLMFJJCNBIP != null)
						KLMFJJCNBIP();
				}, () =>
				{
					//0xD934C0
					ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = KKLGENJKEBN.HHCJCDFCLOB.CJMFJOMECKI_ErrorId == SakashoErrorId.RANKING_PLAYER_NOT_FOUND;
					PLOOEECNHFB_IsDone = true;
					if (IDAEHNGOKAE != null)
						IDAEHNGOKAE();
				}, () =>
				{
					//0xD93624
					ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = false;
					PLOOEECNHFB_IsDone = true;
					NPNNPNAIONN_IsError = true;
					if (JGKOLBLPMPG != null)
						JGKOLBLPMPG();
				}, () =>
				{
					//0xD93778
					ONJBNDCMMNL[LHJCOPMMIGO].FJOLNJLLJEJ_Rank = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].DNBFMLBNAEE_Score = 0;
					ONJBNDCMMNL[LHJCOPMMIGO].BEKAMBBOLBO = false;
					PLOOEECNHFB_IsDone = true;
					FKKDIDMGLMI = true;
				});
			}
			else
			{
				PLOOEECNHFB_IsDone = true;
				if (KLMFJJCNBIP != null)
					KLMFJJCNBIP();
			}
		}
	}

	//// RVA: 0xD918D8 Offset: 0xD918D8 VA: 0xD918D8
	public void AMKJFGLEJGE(int LHJCOPMMIGO, int ABLHIAEDJAI, long JHNMKKNEENE)
	{
		EECOJKDJIFG e = DAKMIKNKHMF(LHJCOPMMIGO);
		if(e != null)
		{
			if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking != null && IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.EFHMLHKODOD_EventGoDivaRanking.NGHKJOEDLIP != null)
			{
				TodoLogger.LogError(0, "AMKJFGLEJGE");
			}
		}
	}

	//// RVA: 0xD91C8C Offset: 0xD91C8C VA: 0xD91C8C
	//public void FGMOMBKGCNF(int LHJCOPMMIGO, int ABLHIAEDJAI = 0, IMCBBOAFION KLMFJJCNBIP, DJBHIFLHJLK NIMPEHIECJH, DJBHIFLHJLK JGKOLBLPMPG) { }

	//// RVA: 0xD91F48 Offset: 0xD91F48 VA: 0xD91F48
	private void EJHFJGKPHCM(int NEFEFHBHFFF, List<IBIGBMDANNM> NNDGIAEFMOG, int KKGKLNDOCFI)
	{
		if(NNDGIAEFMOG != null)
		{
			for(int i = 0; i < NNDGIAEFMOG.Count; i++)
			{
				RankingListInfo info = HGGPIBNLALJ.Find((RankingListInfo GHPLINIACBB) =>
				{
					//0xD93BB4
					return NNDGIAEFMOG[i].MLPEHNBNOGD_Id == GHPLINIACBB.friend.MLPEHNBNOGD_Id;
				});
				if(info == null)
				{
					if(NNDGIAEFMOG[i].FJOLNJLLJEJ_Rank >= KKGKLNDOCFI)
					{
						EAJCBFGKKFA_FriendInfo data = new EAJCBFGKKFA_FriendInfo();
						data.KHEKNNFCAOI(NNDGIAEFMOG[i]);
						HGGPIBNLALJ.Add(new RankingListInfo(i, true, data));
					}
				}
			}
		}
	}

	//// RVA: 0xD92330 Offset: 0xD92330 VA: 0xD92330
	//private void CBDFJFCGKNK(int NEFEFHBHFFF, List<IBIGBMDANNM> NNDGIAEFMOG, int KKGKLNDOCFI) { }

	//// RVA: 0xD91244 Offset: 0xD91244 VA: 0xD91244
	private EECOJKDJIFG DAKMIKNKHMF(int LHJCOPMMIGO)
	{
		if (AEJCLHOIDDD.Length <= LHJCOPMMIGO)
			return null;
		return AEJCLHOIDDD[LHJCOPMMIGO];
	}

	//// RVA: 0xD92718 Offset: 0xD92718 VA: 0xD92718
	//public static int BFKAHKBKBJE(int FJOLNJLLJEJ, long EAKFLINAPOG) { }
}
