
[System.Obsolete("Use MBMENEIFOJC_TwitterLinkage", true)]
public class MBMENEIFOJC { }
public class MBMENEIFOJC_TwitterLinkage : AILHMHMOKKA_BaseLinkage
{
	//// RVA: 0xA306B4 Offset: 0xA306B4 VA: 0xA306B4 Slot: 4
	public override void EMKKJILHOOB_GetLinkageStatus(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG)
	{
		JEDJNIKPFLH_IsLinked = false;
		DKIAFKAJMED_GetTwitterLinkageStatus req = NKGJPJPHLIF.HHCJCDFCLOB.IBLPICFDGOF_ServerRequester.IFFNCAFNEAG_AddRequest(new DKIAFKAJMED_GetTwitterLinkageStatus());
		req.ICDEFIIADDO_Timeout = 15;
		req.NBFDEFGFLPJ = DGLAMLJFEDB_CheckError;
		req.BHFHGFKBOHH_OnSuccess = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x130B038
			DKIAFKAJMED_GetTwitterLinkageStatus r = JIPCHHHLOMM as DKIAFKAJMED_GetTwitterLinkageStatus;
			JEDJNIKPFLH_IsLinked = r.NFEAMMJIMPG.MKHDOLLACEF_TwitterLinkage;
			BHFHGFKBOHH();
		};
		req.MOBEEPPKFLG_OnFail = (CACGCMBKHDI_Request JIPCHHHLOMM) =>
		{
			//0x130B210
			TodoLogger.Log(0, "MOBEEPPKFLG_OnFail");
		};
	}

	//// RVA: 0xA30948 Offset: 0xA30948 VA: 0xA30948 Slot: 5
	//public override void GGNBIHHFJMP(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG) { }

	//// RVA: 0xA30B88 Offset: 0xA30B88 VA: 0xA30B88 Slot: 6
	//public override void MOHPODEDIEK(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG) { }

	//// RVA: 0xA30DC8 Offset: 0xA30DC8 VA: 0xA30DC8 Slot: 7
	//public override void BMJMJCIKALP(IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP NIMPEHIECJH, DJBHIFLHJLK AOCANKOMKFG) { }
}
