
public class MHOILBOJFHL
{
	public enum KCAEDEHGAFO
	{
		GCCBFIFJHII_Information = 0,
		CCFMGBNHMNN_Inquiry = 1,
		FFIDPICMNKN = 2,
		LCNNIHGFBMP = 3,
		EHDHJCGOGGN = 4,
		BFKFPEDCFCL = 5,
		LCCLAEBKMLD_6 = 6,
		EMAOPPMGKBD = 7,
		GHDACOGLNLJ_Contract = 8,
		GOMOJLPBCAN = 9,
		JMIDCMFKPOE = 10,
		AEFCOHJBLPO = 11,
	}
}
