
using XeSys;

public class MKCJNKIEADB
{
	public int PPFNGGCBJKC_Id; // 0x8
	public string BPEAIOBHMFD_NameForApis; // 0xC
	public string OPFGFINHFCE_Name; // 0x10
	public string KLMPFGOCBHC_Desc; // 0x14
	public long MMPCPKODGKI_ResetAt; // 0x18
	public long KBFOIECIADN_OpenAt; // 0x20
	public long EGBOHDFBAPB_CloseAt; // 0x28
	public ANPGILOLNFK.CDOGFBNLIPG CKHOBDIKJFN_Type; // 0x30
	public int PJHKECDOALD = 100; // 0x34
	public bool DNEHFIFIHEM; // 0x38
	public int OENPCNBFPDA_BgId; // 0x3C

	// RVA: 0x19596F0 Offset: 0x19596F0 VA: 0x19596F0 Slot: 4
	public virtual void KHEKNNFCAOI(EDOHBJAPLPF_JsonData IDLHJIOMJBK)
	{
		PPFNGGCBJKC_Id = (int)IDLHJIOMJBK[AFEHLCGHAEE_Strings.PPFNGGCBJKC_Id];
		BPEAIOBHMFD_NameForApis = (string)IDLHJIOMJBK[AFEHLCGHAEE_Strings.BPEAIOBHMFD_name_for_apis];
		OPFGFINHFCE_Name = (string)IDLHJIOMJBK[AFEHLCGHAEE_Strings.OPFGFINHFCE_name];
		KLMPFGOCBHC_Desc = (string)IDLHJIOMJBK[AFEHLCGHAEE_Strings.KLMPFGOCBHC_description];
		MMPCPKODGKI_ResetAt = JsonUtil.GetLong(IDLHJIOMJBK, AFEHLCGHAEE_Strings.MMPCPKODGKI_reset_at);
		KBFOIECIADN_OpenAt = JsonUtil.GetLong(IDLHJIOMJBK, AFEHLCGHAEE_Strings.KBFOIECIADN_opened_at);
		EGBOHDFBAPB_CloseAt = JsonUtil.GetLong(IDLHJIOMJBK, AFEHLCGHAEE_Strings.EGBOHDFBAPB_closed_at);
		CKHOBDIKJFN_Type = ANPGILOLNFK.OLMFIANJBOB_GetType(BPEAIOBHMFD_NameForApis);
		OENPCNBFPDA_BgId = ANPGILOLNFK.AFMHNPCDAFI_GetBgId(BPEAIOBHMFD_NameForApis);
		PJHKECDOALD = ANPGILOLNFK.FENFHPPHCBE[(int)CKHOBDIKJFN_Type];
		DNEHFIFIHEM = CKHOBDIKJFN_Type == ANPGILOLNFK.CDOGFBNLIPG.PHABJLGFJNI_1 || (CKHOBDIKJFN_Type >= ANPGILOLNFK.CDOGFBNLIPG.LAOEGNLOJHC_5 && CKHOBDIKJFN_Type < ANPGILOLNFK.CDOGFBNLIPG.MKADAMIGMPO_7);
	}

	//// RVA: 0x19599DC Offset: 0x19599DC VA: 0x19599DC
	public bool ILOKENBBBAE(long BEBJKJKBOGH)
	{
		if(KBFOIECIADN_OpenAt == 0 || BEBJKJKBOGH >= KBFOIECIADN_OpenAt)
		{
			if(EGBOHDFBAPB_CloseAt == 0 || BEBJKJKBOGH < EGBOHDFBAPB_CloseAt)
			{
				return BEBJKJKBOGH >= MMPCPKODGKI_ResetAt;
			}
		}
		return false;
	}
}
