
public class MMNNAPPLHFM
{
	private const int FBGGEFFJJHB = 0x2541a98f;
	public int GKGHEKGGAIF = FBGGEFFJJHB; // 0x8
	public int HNFFLHBKNFC = FBGGEFFJJHB; // 0xC
	public int FBBDIKKJBKJ = FBGGEFFJJHB; // 0x10
	public IKMBBPDBECA KACECFNECON; // 0x14
	public string KLMPFGOCBHC; // 0x18
	public int JCHIEPIBLPC = FBGGEFFJJHB; // 0x1C
	public int GNIJJPKCKKO = FBGGEFFJJHB; // 0x20

	public int AGBCJMMMLON { get { return GKGHEKGGAIF ^ FBGGEFFJJHB; } set { GKGHEKGGAIF = value ^ FBGGEFFJJHB; } } //0x1967964 AOGDFNLPBNO 0x1967978 MPINCEJGHJN
	public int LCJPKJMMIAP { get { return HNFFLHBKNFC ^ FBGGEFFJJHB; } set { HNFFLHBKNFC = value ^ FBGGEFFJJHB; } } //0x196798C FIFCKLADNCP 0x19679A0 FEOGBLAIIOC
	public int FHBJOLPCAPN { get { return FBBDIKKJBKJ ^ FBGGEFFJJHB; } set { FBBDIKKJBKJ = value ^ FBGGEFFJJHB; } } //0x19679B4 LDCMGLDHHDH 0x19679C8 CMAELNMMLAI
	public int MFFNDOEPJFO { get { return JCHIEPIBLPC ^ FBGGEFFJJHB; } set { JCHIEPIBLPC = value ^ FBGGEFFJJHB; } } //0x19679DC JLMLOOIDLGP 0x19679F0 NHHCGFKNBEF
	public int EKOFPNGPCIP { get { return GNIJJPKCKKO ^ FBGGEFFJJHB; } set { GNIJJPKCKKO = value ^ FBGGEFFJJHB; } } //0x1967A04 EDOJECAIPGK 0x1967A18 PDEFJLLLCOI
	//public int HMFFHLPNMPH { get; } 0x1967A2C NJOGDDPICKG

	//// RVA: 0x1967A4C Offset: 0x1967A4C VA: 0x1967A4C
	//public void KHEKNNFCAOI(EDOHBJAPLPF IDLHJIOMJBK) { }
}
