
public class NKJOBGGCCNA
{
	public int NHJBJIGNLHI { get; set; } // 0x8 GPBBDENNDAJ CALOGMNCDCM IPPJIMDIGPK
	public string ADBOHBLBNDL { get; set; } // 0xC NPMGAJJELEL OPAPKEJLHCF GMJEJBHAAAL
	public string IOIMHJAOKOO { get; set; } // 0x10 GMLEDKKPBFJ HJMJGBCJBIN OLGHLLNJPKD
}
