
public class OAGBCBBHMPF
{
    public enum KJDNDEDOIOO_LogType
    {
        FNGAOJCJFJP_0_None = 0,
        JONAMONAHOB_1_Paid = 1,
        PMFGEJJDMCK_2_Consume = 2,
        ALABPEPENHH_3_Tutorial = 3,
        FKODKMNGCEH_4_StageStart = 4,
        IMJLLLNHICJ_5_StageEnd = 5,
        KHMDGNKEFOD_6_DeckChange = 6,
        JNBKOAKJDAL_7_Gacha = 7,
        NNAPCDMAAJM_8_Enhance = 8,
        JAHALBMOANH_9_GetItem = 9,
        OJOLFJGNEMO_10_MusicDownload = 10,
        DBIDGHMFLIC_11_Clothes = 11,
        IEEKNBEEMMM_12_Mission = 12,
        EAEHILOBHDA_13_View = 13,
        AOPBBHMIEPB_14_Story = 14,
        MNFOJMBPHEN_15_Friend = 15,
        JOLBIMMKGIP_16_OpenSns = 16,
        HGOGFPOCKFA_17_Sns = 17,
        BBDKHAMANCB_18_Episode = 18,
        AMBIOHGPBNH_19_Review = 19,
        EEPIDKPPLJI_20_Valkyrie = 20,
        PNMJDKOLGEG_21_Rankup = 21,
        EBLJKIOEELA_22_DivaLevelUp = 22,
        PGHFPIMIOKE_23_Emblem = 23,
        CMBKHLDBIEC_24_Voice = 24,
        FLBCPKHGLPE_25_Energy = 25,
        MLNHHIIDJAO_26_Anketo = 26,
        COBCMOAAAFF_27_EmblemGet = 27,
        GIBLHFKIMDA_28_EventEnd = 28,
        MFIIOABPKAO_29_MissionEventSelect = 29,
        EPABCLLAJDP_30_MissionEventReset = 30,
        FCIJOHCNLBB_31_MissionStageStart = 31,
        EEGOAEADLDP_32_MissionStageEnd = 32,
        JMAJBHENDPF_33_EventStageStart = 33,
        NJKBAICBOIN_34_EventStageEnd = 34,
        GBABEMFLPBA_35_MissionEventChange = 35,
        NJEIHFPKOMG_36_GameStartLoad = 36,
        HHGEPDNBGAI_37_BattleStageMatch = 37,
        PMHLIBHEBBB_38_BattleStageStart = 38,
        FEIOPIIEIKB_39_BattleStageEnd = 39,
        EAGAKGNNINL_40_Banner = 40,
        EEOLHMGNJGO_41_UnlockLimitOver = 41,
        LKOICKMAADB_42_MissionEventStart = 42,
        GHJEAPLGKHJ_43_MissionEventSelectLevel = 43,
        IGKMGFKKKHI_44_MissionEventSelectMusic = 44,
        IENGPDCDMBM_45_MvStageStart = 45,
        GDHNBIIOKMF_46_MvStageEnd = 46,
        GADJDBJLIGC_47_ViewMovie = 47,
        DBNECDJCNOI_48_ShopBuy = 48,
        CBKENDJIBDM_49_MvChange = 49,
        LIPHGGFEJFJ_50_EventBoxGacha = 50,
        LCDPEMIFNKJ_51_RemoveExpiredItem = 51,
        ICAHGJMMGLM_52_ArTitleStart = 52,
        BGJDJBOCLEA_53_ArSceneStart = 53,
        ILLBGAFIBDE_54_ArMarker = 54,
        KIFPDEFNEPB_55_ArPhoto = 55,
        PHLHLIDCNNN_56_ArShare = 56,
        DNNLEIKNHKL_57_DivaIntimacyExpAdd = 57,
        CDNFJBAJAMM_58_PresentCampaignEntry = 58,
        BLDDKDNOCFA_59_PresentCampaignResult = 59,
        DADNPOJNIBL_60_EventHome = 60,
        LIIJEGOIKDP_61_Adventure = 61,
        LPKDNOINDPE_62_SubscriptionUpdate = 62,
        BKLNHBHDDEJ_63_VopTransition = 63,
        DAGHKCKEJPA_64_VopAppearence = 64,
        OEGCKACJMPM_65_VopOrders = 65,
        ONPIDKLOPIP_66_VopResults = 66,
        BABLKKLEPGD_67_CostumeEnhance = 67,
        PLEKHHPMELF_68_HealItemConsume = 68,
        FJBCAHAFLNO_69_VopDivaTouch = 69,
        FDFMKBGPALI_70_VopFastComplete = 70,
        LOGBJCFCJND_71_RaidStageStart = 71,
        FIPDFLHPNDO_72_RaidStageEnd = 72,
        KCCMKAEPGPE_73_RaidBossEncounter = 73,
        PEBDGCDNPDM_74_LobbyTransition = 74,
        PHCLHGPCFNL_75_LobbySelectGroup = 75,
        HGNLDJNEGJM_76_BlockList = 76,
        ICDCMLKMEHI_77_HealAp = 77,
        CLGHLKLHEAK_78_DecoTransition = 78,
        ELDCONNMDGN_79_ValkyrieEnhance = 79,
        CIGPIPBPABC_80_FanRegister = 80,
        MINOEGPNBIH_81_McCharge = 81,
        EEHEMNBJPAP_82_RaidBossAttack = 82,
        FJIPPAPEBID_83_DecoBuy = 83,
        BOIIMIEPMLG_84_DecoLayoutSet = 84,
        HONFKODFAPA_85_RaidBossReward = 85,
        PFBIHCIFFKM_86_DecoVisit = 86,
        CEFIPAIKAKN_87_DecoItemCollection = 87,
        NOMCHDMPFFE_88_DecoItemLevelUp = 88,
        CHMEOKEKABD_89_Chat = 89,
        MIDMMEHCCFA_90_DecoItemSet = 90,
        OMLMHKGCJPH_91_DecoStampSave = 91,
        ONMOONKHHLO_92_RaidBossAppearence = 92,
        HNOKBPNGOEF_93_DecoSns = 93,
        LHCHBHPHLCP_94_LobbyVisit = 94,
        CJCJNKOPIKB_95_HomeCloths = 95,
        DNJGGCJPIMC_96_GoDivaEventStageStart = 96,
        HPNIJDCPCNC_97_GoDivaEventStageEnd = 97,
        HJGEAHELBPE_98_GoDivaEventUsedFeverItem = 98,
        NBCACPPAAMC_99_HomeDivaModify = 99,
        BBIBBNHCPPJ_100_HomeModify = 100,
    }
	
	public enum OGBCFNIKAFI_LoadStep
	{
		FKPEAGGKNLC_0_Start = 0,
		BABBMOJCMDM_1_PrologueStart = 1,
		MHFHGNFCEHJ_2_DL0 = 2, // 2 => 12 %
		NJLGGHGMLMN_3_DL10 = 3,
		DCFJPBCIBEI_4_DL20 = 4,
		KGDFCJPODAJ_5_DL30 = 5,
		BHNNPGACIDF_6_DL40 = 6,
		KCKOFDFGLFE_7_DL50 = 7,
		HIEPCGKPDEH_8_DL60 = 8,
		PHLKLILEPPA_9_DL70 = 9,
		EDLJLDPMKIF_10_DL80 = 10,
		CKKHFDJCHBC_11_DL90 = 11,
		ECPJHFJHHFP_12_DL100 = 12,
		FFPMNJAMFCP_13_Adventure1 = 13,
		JHMCNBGOOJF_14_TimingCheck = 14,
		EKEBEGIELBJ_15_TimingCheckRetry = 15,
		HIAAKPMJJGD_16_1stLive = 16,
		BMIDACPCELO_17_1stLievSkip = 17,
		HOIECIKEIHB_18_1stLiveEnd = 18,
		FEEJKNDAHFE_19_Adventure2 = 19,
		PHOGGPBMGAE_20_GachaList = 20,
		ECLDDCCEJJG_21_GachaStart = 21,
		KIBFDMGJFMO_22_GachaResult = 22,
		JKGGACIFBOM_23_StartUnitSetup = 23,
		HMJIFCKIGEC_24_EndUnitSetup = 24,
		NBFHAMJNMMG_25_2ndLive = 25,
		JAPPCJMLAMJ_26_2ndLiveSkip = 26,
		BJBDDPHJHFA_27_2ndLiveEnd = 27,
		CAMJGCCMANN_28_Adventure3 = 28,
		KLPNOJFFNGL_29_SNSStart = 29,
		KBMDDIHNCFI_30_SNSEnd = 30,
		KAEEOAPBOCI_31_NameEnter = 31,
		BKFDCMALJBF_32_NameEnterEnd = 32,
		CBMEJNCDJEG_33_DivaSelect = 33,
		FFFHCFBMHDD_34_DivaStart = 34,
		GFLDEDJAONB_35_ValkyrieStart = 35,
		NKJKAEHAFJO_36_MainDl0 = 36, // 36 => 46 %
		IDIINPAANKI_37_MainDL10 = 37,
		JDOHDMDGOEL_38_MainDL20 = 38,
		LALOFKILEHB_39_MainDL30 = 39,
		MGBMNPHKKHD_40_MainDL40 = 40,
		NHIGFHJEKOO_41_MainDL50 = 41,
		OKFOGBPEHON_42_MainDL60 = 42,
		CMLPNGAJOAP_43_MainDL70 = 43,
		IPLMCBFBFGB_44_MainDL80 = 44,
		GJOEAOEHPNE_45_MainDL90 = 45,
		KBHNAJGGEPE_46_MainDL100 = 46,
		CFHINEFGHPC_47_LoginBonus = 47,
		LGFGBNKFPGH_48_Home = 48,
		HDMADAHNLDN_49_Missions = 49,
		CGKOFIKBMMI_50_Last = 50,
	}

	public enum COIIJOEKBDH_InventoryAddType
	{
		IMJOELNOOMB_0_NormalDrop = 0,
		EDHFDPBEFKA_1_StoryDrop = 1,
		GBMFNHOFGOP_2_Purchase = 2,
		DOEHLCLBCNN_3_Gacha = 3,
		CNACJCAMCFB_4_Episode = 4,
		EMAFECNMGDA_5_LiveCompletion = 5,
		ICAPJDDJIEA_6_Present = 6,
		APJJPDJNOJB_7_NormalMission = 7,
		LEABABGFEGB_8_DailyMission = 8,
		MGEFPKOJKBL_9_EventPoint = 9,
		PCDOEIFMLHG_10_EventMision = 10,
		FBCINBIIABE_11_LoginBonus = 11,
		LIHFAAPBLOH_12_SNSMission = 12,
		NJCPDNAHPDP_13_DebutMission = 13,
		IGAJCMKNLDL_14_EventLoginBonus = 14,
		LJILBHPMPOG_15_Shop = 15,
		GMOLAHOIJHE_16_EventGacha = 16,
		HJGPNANNPNM_17_BonusAchatDevise = 17,
		NJCKHBPLDGL_18_ARTitle = 18,
		GHLEPCNBCNC_19_WelcomeGift = 19,
		ACNGACBALGM_20_IntimacyReward = 20,
		EAKANCJFFKF_21_MedalEventMission = 21,
		IOBDJDHJJFK_22_BalleEventClassReward = 22,
		JJGHKIBKFFJ_23_Offer = 23,
		NODLEHAGKMN_24_Offer1stReward = 24,
		LEHHJINPFHA_25_CostumeUpgrade = 25,
		KEFAKKJOACI_26_MonthlyPass = 26,
		KFFIFJIBHFM_27_MonthlyPassRebuy = 27,
		JMLJADADEEF_28_OfferStone = 28,
		DIDJLIPNCKO_29_Bingo = 29,
		PFPGFPLGANO_30_ValkyrieSkillUpgrade = 30,
		DOENIIJNHNJ_31_RaidBossDefeat = 31,
		HEKCMMMHFMA_32_RaidBossMVP = 32,
		ADJKNFCENEA_33_RaidBossFirst = 33,
		ENGODNEBGJD_34_Deco = 34,
		IOEGFJMNDBM_35_Medal = 35,
		JJNIMNEJPOF_36_Present = 36,
		JPPOGMHJKKJ_37_VisitItemSp = 37,
		PJPBCFKEGBC_38_RaidTutorial = 38,
		KGOOLKLPJIP_39_BonusAPRefill = 39,
		LLMGBJKCBHI_40_RareUpAutoConversion = 40,
		HNJIKEJADJL_41_LiveSkipTicketGet = 41,
		CDJJNKKIBJN_42_RareUpStarUse = 42,
		MIDINHNHGNP_43_SecretBoardUpgrade = 43,
		MDPHOJAPCCC_44_UtaRankReward = 44,
		EJPNJANOEEA_45_MonthlyPassSpLoginReward = 45,
	}

	public enum DKAMMIHBINF_AdventureSource
	{
		KJHABBHBFPD_0_Other = 0,
		DECFIFJACCL_1_EventStory = 1,
		DODPGHDOFIO_2_GachaBanner = 2,
		BPCPDNGLNGO_3_EventHome = 3,
		HEFPAOLDHCK_4_Daily = 4,
		FCMMKJLCFAB_5_SpecialButton = 5,
		IDINJDEBPKP_6_EventBanner = 6,
		IFEDIOFCOBC_7_EventBalloon = 7,
		KDDHGLNCFMF_8_SpecialEventHome = 8,
		PGNFDEIHHMD_9_HomeAuto = 9,
		EKJGOMKEJLK_10_Scene = 10, // AbilityBoard
	}

	public enum NALHDBIKFJO
	{
		HJNNKCMLGFL_0_None = 0,
		FKKEAHEAOMM_1_Valid = 1,
		EANGJBHNNHF_2_Expired = 2,
		KEFKPCMGHIJ_3_ServerError = 3,
		NGBOABGLAMM_4_Error = 4,
	}

	public static string[] IEPAJNPLHJI_EventId = new string[101] { "NONE", "PAID", "CONSUME", "TUTORIAL", "STAGE_START", "STAGE_END", "DECK_CH",
                                                            "GACHA", "ENHANCE", "GET_ITEM", "MUSIC_DL", "CLOTHES", "MISSION", "VIEW",
                                                            "STORY", "FRIEND", "OPEN_SNS", "SNS", "EPISODE", "REVIEW", "VALKYRIE", 
                                                            "RANK_UP", "DIVA_LEVELUP", "EMBLEM", "VOICE", "ENERGY", "ENQUETE", "EMBLEM_GET",
                                                            "EVENT_END", "MISSION_EVENT_SELECT", "MISSION_EVENT_RESET", "MISSION_STAGE_START",
                                                            "MISSION_STAGE_END", "EVENT_STAGE_START", "EVENT_STAGE_END", 
                                                            "MISSION_EVENT_CHANGE", "GAME_START_LOAD", "BATTLE_STAGE_MATCH",
                                                            "BATTLE_STAGE_START", "BATTLE_STAGE_END", "BANNER", "UNLOCK_LIMIT_OVER",
                                                            "MISSION_EVENT_START", "MISSION_EVENT_SELECT_LEVEL", "MISSION_EVENT_SELECT_MUSIC",
                                                            "MV_STAGE_START", "MV_STAGE_END", "VIEW_MOVIE", "SHOP_BUY", 
                                                            "MV_CHANGE", "EVENT_BOX_GACHA", "REMOVE_EXPIRED_ITEM", "AR_TITLE_START",
                                                            "AR_SCENE_START", "AR_MARKER", "AR_PHOTO", "AR_SHARE", "DIVA_INTIMACY_EXP_ADD",
                                                            "PRESENT_CAMPAIGN_ENTRY", "PRESENT_CAMPAIGN_RESULT", "EVENT_HOME",
                                                            "ADVENTURE", "SUBSCRIPTION_UPDATE", "VOP_TRANSITION", "VOP_APPEARENCE",
                                                            "VOP_ORDERS", "VOP_RESULTS", "COSTUME_ENHANCE", "HEALITEM_CONSUME",
                                                            "VOP_DIVA_TOUCH", "VOP_FAST_COMPELTE", "RAID_STAGE_START", "RAID_STAGE_END",
                                                            "RAID_BOSS_ENCOUNTER", "LOBBY_TRANSITION", "LOBBY_SELECT_GROUP", "BLOCKLIST",
                                                            "HEAL_AP", "DECO_TRANSITION", "VALKYRIE_ENHANCE", "FAN_REGISTER", "MC_CHARGE",
                                                            "RAID_BOSS_ATACK", "DECO_BUY", "DECO_LAYOUT_SET", "RAID_BOSS_REWARD",
                                                            "DECO_VISIT", "DECO_ITEM_COLLECTION", "DECO_ITEM_LEVELUP", "CHAT",
                                                            "DECO_ITEM_SET", "DECO_STAMP_SAVE", "RAID_BOSS_APPEARENCE", "DECO_SNS",
                                                            "LOBBY_VISIT", "HOME_CLOTHS", "GODIVA_EVENT_STAGE_START", "GODIVA_EVENT_STAGE_END",
                                                            "GODIVA_EVENT_USED_FEVERITEM", "HOME_DIVA_MODIFY", "HOME_MODIFY"}; // 0x0
	public static string[] KDIDJBOMHFO_LoadStepNames = new string[50] {
		JpStringLiterals.StringLiteral_11078,
		JpStringLiterals.StringLiteral_12839,
		JpStringLiterals.StringLiteral_12840,
		JpStringLiterals.StringLiteral_12841,
		JpStringLiterals.StringLiteral_12842,
		JpStringLiterals.StringLiteral_12843,
		JpStringLiterals.StringLiteral_12844,
		JpStringLiterals.StringLiteral_12845,
		JpStringLiterals.StringLiteral_12846,
		JpStringLiterals.StringLiteral_12847,
		JpStringLiterals.StringLiteral_12848,
		JpStringLiterals.StringLiteral_12849,
		JpStringLiterals.StringLiteral_12850,
		JpStringLiterals.StringLiteral_12851,
		JpStringLiterals.StringLiteral_12852,
        JpStringLiterals.StringLiteral_12853,
		JpStringLiterals.StringLiteral_12854,
		JpStringLiterals.StringLiteral_12855,
        JpStringLiterals.StringLiteral_12856,
		JpStringLiterals.StringLiteral_12857,
		JpStringLiterals.StringLiteral_12858,
        JpStringLiterals.StringLiteral_12859,
		JpStringLiterals.StringLiteral_12860,
		JpStringLiterals.StringLiteral_12861,
        JpStringLiterals.StringLiteral_12862, 
		JpStringLiterals.StringLiteral_12863,
		JpStringLiterals.StringLiteral_12864,
        JpStringLiterals.StringLiteral_12865, 
		JpStringLiterals.StringLiteral_12866,
		JpStringLiterals.StringLiteral_12867,
        JpStringLiterals.StringLiteral_12868, 
		JpStringLiterals.StringLiteral_12869,
		JpStringLiterals.StringLiteral_12870,
        JpStringLiterals.StringLiteral_12871, 
		JpStringLiterals.StringLiteral_12872,
		JpStringLiterals.StringLiteral_12873,
        JpStringLiterals.StringLiteral_12874, 
		JpStringLiterals.StringLiteral_12875,
		JpStringLiterals.StringLiteral_12876,
        JpStringLiterals.StringLiteral_12877, 
		JpStringLiterals.StringLiteral_12878,
		JpStringLiterals.StringLiteral_12879,
        JpStringLiterals.StringLiteral_12880, 
		JpStringLiterals.StringLiteral_12881,
		JpStringLiterals.StringLiteral_12882,
        JpStringLiterals.StringLiteral_12883, 
		JpStringLiterals.StringLiteral_12884,
		JpStringLiterals.StringLiteral_12885,
        JpStringLiterals.StringLiteral_12886, 
		JpStringLiterals.StringLiteral_12887 }; // 0x4
	public static string[] CINOEDJHDIE = new string[46] {
		JpStringLiterals.StringLiteral_12888,
		JpStringLiterals.StringLiteral_12889,
		JpStringLiterals.StringLiteral_12890,
        JpStringLiterals.StringLiteral_12891, 
		JpStringLiterals.StringLiteral_11079,
		JpStringLiterals.StringLiteral_12892,
        JpStringLiterals.StringLiteral_12893, 
		JpStringLiterals.StringLiteral_11219,
		JpStringLiterals.StringLiteral_11216,
        JpStringLiterals.StringLiteral_12894, 
		JpStringLiterals.StringLiteral_11220,
		JpStringLiterals.StringLiteral_12895,
        JpStringLiterals.StringLiteral_11217, 
		JpStringLiterals.StringLiteral_11218,
		JpStringLiterals.StringLiteral_12896,
        JpStringLiterals.StringLiteral_12897, 
		JpStringLiterals.StringLiteral_12898,
		JpStringLiterals.StringLiteral_12899,
        JpStringLiterals.StringLiteral_12900, 
		JpStringLiterals.StringLiteral_12901,
		JpStringLiterals.StringLiteral_12902,
        JpStringLiterals.StringLiteral_12903, 
		JpStringLiterals.StringLiteral_12904,
		JpStringLiterals.StringLiteral_12905,
        JpStringLiterals.StringLiteral_12906, 
		JpStringLiterals.StringLiteral_12907,
		JpStringLiterals.StringLiteral_12908,
        JpStringLiterals.StringLiteral_12909, 
		JpStringLiterals.StringLiteral_12910,
		JpStringLiterals.StringLiteral_11221,
        JpStringLiterals.StringLiteral_12911, 
		JpStringLiterals.StringLiteral_12912,
		JpStringLiterals.StringLiteral_12913,
        JpStringLiterals.StringLiteral_12914, 
		JpStringLiterals.StringLiteral_12915,
		JpStringLiterals.StringLiteral_12916,
        JpStringLiterals.StringLiteral_12917, 
		JpStringLiterals.StringLiteral_12918,
		JpStringLiterals.StringLiteral_12919,
        JpStringLiterals.StringLiteral_12920, 
		JpStringLiterals.StringLiteral_12921,
		JpStringLiterals.StringLiteral_12922,
        JpStringLiterals.StringLiteral_12923, 
		JpStringLiterals.StringLiteral_12924,
		JpStringLiterals.StringLiteral_12925,
        JpStringLiterals.StringLiteral_12926}; // 0x8
	public static string[] BHKNBCJGBDG = new string[11] {
		JpStringLiterals.StringLiteral_12927,
		JpStringLiterals.StringLiteral_12928,
		JpStringLiterals.StringLiteral_12929,
        JpStringLiterals.StringLiteral_12930, 
		JpStringLiterals.StringLiteral_12931,
		JpStringLiterals.StringLiteral_12932,
        JpStringLiterals.StringLiteral_12933, 
		JpStringLiterals.StringLiteral_12934,
		JpStringLiterals.StringLiteral_12935,
        JpStringLiterals.StringLiteral_12936, 
		JpStringLiterals.StringLiteral_12937}; // 0xC
	public static string[] GNIPLCBMPEG_RaidAttackType = new string[5] {
		JpStringLiterals.StringLiteral_10136,
		JpStringLiterals.StringLiteral_11431,
		JpStringLiterals.StringLiteral_11428,
		JpStringLiterals.StringLiteral_11429, 
		JpStringLiterals.StringLiteral_11430}; // 0x10
}
