
public class OAGBCBBHMPF
{
    public enum KJDNDEDOIOO
    {
        FNGAOJCJFJP = 0,
        JONAMONAHOB = 1,
        PMFGEJJDMCK = 2,
        ALABPEPENHH = 3,
        FKODKMNGCEH = 4,
        IMJLLLNHICJ = 5,
        KHMDGNKEFOD = 6,
        JNBKOAKJDAL = 7,
        NNAPCDMAAJM = 8,
        JAHALBMOANH = 9,
        OJOLFJGNEMO = 10,
        DBIDGHMFLIC = 11,
        IEEKNBEEMMM = 12,
        EAEHILOBHDA = 13,
        AOPBBHMIEPB = 14,
        MNFOJMBPHEN = 15,
        JOLBIMMKGIP = 16,
        HGOGFPOCKFA = 17,
        BBDKHAMANCB = 18,
        AMBIOHGPBNH = 19,
        EEPIDKPPLJI = 20,
        PNMJDKOLGEG = 21,
        EBLJKIOEELA = 22,
        PGHFPIMIOKE = 23,
        CMBKHLDBIEC = 24,
        FLBCPKHGLPE = 25,
        MLNHHIIDJAO = 26,
        COBCMOAAAFF = 27,
        GIBLHFKIMDA = 28,
        MFIIOABPKAO = 29,
        EPABCLLAJDP = 30,
        FCIJOHCNLBB = 31,
        EEGOAEADLDP = 32,
        JMAJBHENDPF = 33,
        NJKBAICBOIN = 34,
        GBABEMFLPBA = 35,
        NJEIHFPKOMG = 36,
        HHGEPDNBGAI = 37,
        PMHLIBHEBBB = 38,
        FEIOPIIEIKB = 39,
        EAGAKGNNINL = 40,
        EEOLHMGNJGO = 41,
        LKOICKMAADB = 42,
        GHJEAPLGKHJ = 43,
        IGKMGFKKKHI = 44,
        IENGPDCDMBM = 45,
        GDHNBIIOKMF = 46,
        GADJDBJLIGC = 47,
        DBNECDJCNOI = 48,
        CBKENDJIBDM = 49,
        LIPHGGFEJFJ = 50,
        LCDPEMIFNKJ = 51,
        ICAHGJMMGLM = 52,
        BGJDJBOCLEA = 53,
        ILLBGAFIBDE = 54,
        KIFPDEFNEPB = 55,
        PHLHLIDCNNN = 56,
        DNNLEIKNHKL = 57,
        CDNFJBAJAMM = 58,
        BLDDKDNOCFA = 59,
        DADNPOJNIBL = 60,
        LIIJEGOIKDP = 61,
        LPKDNOINDPE = 62,
        BKLNHBHDDEJ = 63,
        DAGHKCKEJPA = 64,
        OEGCKACJMPM = 65,
        ONPIDKLOPIP = 66,
        BABLKKLEPGD = 67,
        PLEKHHPMELF = 68,
        FJBCAHAFLNO = 69,
        FDFMKBGPALI = 70,
        LOGBJCFCJND = 71,
        FIPDFLHPNDO = 72,
        KCCMKAEPGPE = 73,
        PEBDGCDNPDM = 74,
        PHCLHGPCFNL = 75,
        HGNLDJNEGJM = 76,
        ICDCMLKMEHI = 77,
        CLGHLKLHEAK = 78,
        ELDCONNMDGN = 79,
        CIGPIPBPABC = 80,
        MINOEGPNBIH = 81,
        EEHEMNBJPAP = 82,
        FJIPPAPEBID = 83,
        BOIIMIEPMLG = 84,
        HONFKODFAPA = 85,
        PFBIHCIFFKM = 86,
        CEFIPAIKAKN = 87,
        NOMCHDMPFFE = 88,
        CHMEOKEKABD = 89,
        MIDMMEHCCFA = 90,
        OMLMHKGCJPH = 91,
        ONMOONKHHLO = 92,
        HNOKBPNGOEF = 93,
        LHCHBHPHLCP = 94,
        CJCJNKOPIKB = 95,
        DNJGGCJPIMC = 96,
        HPNIJDCPCNC = 97,
        HJGEAHELBPE = 98,
        NBCACPPAAMC = 99,
        BBIBBNHCPPJ = 100,
    }
	
	public enum OGBCFNIKAFI
	{
		FKPEAGGKNLC = 0,
		BABBMOJCMDM = 1,
		MHFHGNFCEHJ = 2,
		NJLGGHGMLMN = 3,
		DCFJPBCIBEI = 4,
		KGDFCJPODAJ = 5,
		BHNNPGACIDF = 6,
		KCKOFDFGLFE = 7,
		HIEPCGKPDEH = 8,
		PHLKLILEPPA = 9,
		EDLJLDPMKIF = 10,
		CKKHFDJCHBC = 11,
		ECPJHFJHHFP = 12,
		FFPMNJAMFCP = 13,
		JHMCNBGOOJF = 14,
		EKEBEGIELBJ = 15,
		HIAAKPMJJGD = 16,
		BMIDACPCELO = 17,
		HOIECIKEIHB = 18,
		FEEJKNDAHFE = 19,
		PHOGGPBMGAE = 20,
		ECLDDCCEJJG = 21,
		KIBFDMGJFMO = 22,
		JKGGACIFBOM = 23,
		HMJIFCKIGEC = 24,
		NBFHAMJNMMG = 25,
		JAPPCJMLAMJ = 26,
		BJBDDPHJHFA = 27,
		CAMJGCCMANN = 28,
		KLPNOJFFNGL = 29,
		KBMDDIHNCFI = 30,
		KAEEOAPBOCI = 31,
		BKFDCMALJBF = 32,
		CBMEJNCDJEG = 33,
		FFFHCFBMHDD = 34,
		GFLDEDJAONB = 35,
		NKJKAEHAFJO = 36,
		IDIINPAANKI = 37,
		JDOHDMDGOEL = 38,
		LALOFKILEHB = 39,
		MGBMNPHKKHD = 40,
		NHIGFHJEKOO = 41,
		OKFOGBPEHON = 42,
		CMLPNGAJOAP = 43,
		IPLMCBFBFGB = 44,
		GJOEAOEHPNE = 45,
		KBHNAJGGEPE = 46,
		CFHINEFGHPC = 47,
		LGFGBNKFPGH = 48,
		HDMADAHNLDN = 49,
		CGKOFIKBMMI = 50,
	}

	public enum COIIJOEKBDH
	{
		IMJOELNOOMB = 0,
		EDHFDPBEFKA = 1,
		GBMFNHOFGOP = 2,
		DOEHLCLBCNN = 3,
		CNACJCAMCFB = 4,
		EMAFECNMGDA = 5,
		ICAPJDDJIEA = 6,
		APJJPDJNOJB = 7,
		LEABABGFEGB = 8,
		MGEFPKOJKBL = 9,
		PCDOEIFMLHG = 10,
		FBCINBIIABE = 11,
		LIHFAAPBLOH = 12,
		NJCPDNAHPDP = 13,
		IGAJCMKNLDL = 14,
		LJILBHPMPOG = 15,
		GMOLAHOIJHE = 16,
		HJGPNANNPNM = 17,
		NJCKHBPLDGL = 18,
		GHLEPCNBCNC = 19,
		ACNGACBALGM = 20,
		EAKANCJFFKF = 21,
		IOBDJDHJJFK = 22,
		JJGHKIBKFFJ = 23,
		NODLEHAGKMN = 24,
		LEHHJINPFHA = 25,
		KEFAKKJOACI = 26,
		KFFIFJIBHFM = 27,
		JMLJADADEEF = 28,
		DIDJLIPNCKO = 29,
		PFPGFPLGANO = 30,
		DOENIIJNHNJ = 31,
		HEKCMMMHFMA = 32,
		ADJKNFCENEA = 33,
		ENGODNEBGJD = 34,
		IOEGFJMNDBM = 35,
		JJNIMNEJPOF = 36,
		JPPOGMHJKKJ = 37,
		PJPBCFKEGBC = 38,
		KGOOLKLPJIP = 39,
		LLMGBJKCBHI = 40,
		HNJIKEJADJL = 41,
		CDJJNKKIBJN = 42,
		MIDINHNHGNP = 43,
		MDPHOJAPCCC = 44,
		EJPNJANOEEA = 45,
	}

	public enum DKAMMIHBINF
	{
		KJHABBHBFPD = 0,
		DECFIFJACCL = 1,
		DODPGHDOFIO = 2,
		BPCPDNGLNGO = 3,
		HEFPAOLDHCK = 4,
		FCMMKJLCFAB = 5,
		IDINJDEBPKP = 6,
		IFEDIOFCOBC = 7,
		KDDHGLNCFMF = 8,
		PGNFDEIHHMD = 9,
		EKJGOMKEJLK = 10,
	}

	public enum NALHDBIKFJO
	{
		HJNNKCMLGFL = 0,
		FKKEAHEAOMM = 1,
		EANGJBHNNHF = 2,
		KEFKPCMGHIJ = 3,
		NGBOABGLAMM = 4,
	}

	public static string[] IEPAJNPLHJI_EventId = new string[101] { "NONE", "PAID", "CONSUME", "TUTORIAL", "STAGE_START", "STAGE_END", "DECK_CH",
                                                            "GACHA", "ENHANCE", "GET_ITEM", "MUSIC_DL", "CLOTHES", "MISSION", "VIEW",
                                                            "STORY", "FRIEND", "OPEN_SNS", "SNS", "EPISODE", "REVIEW", "VALKYRIE", 
                                                            "RANK_UP", "DIVA_LEVELUP", "EMBLEM", "VOICE", "ENERGY", "ENQUETE", "EMBLEM_GET",
                                                            "EVENT_END", "MISSION_EVENT_SELECT", "MISSION_EVENT_RESET", "MISSION_STAGE_START",
                                                            "MISSION_STAGE_END", "EVENT_STAGE_START", "EVENT_STAGE_END", 
                                                            "MISSION_EVENT_CHANGE", "GAME_START_LOAD", "BATTLE_STAGE_MATCH",
                                                            "BATTLE_STAGE_START", "BATTLE_STAGE_END", "BANNER", "UNLOCK_LIMIT_OVER",
                                                            "MISSION_EVENT_START", "MISSION_EVENT_SELECT_LEVEL", "MISSION_EVENT_SELECT_MUSIC",
                                                            "MV_STAGE_START", "MV_STAGE_END", "VIEW_MOVIE", "SHOP_BUY", 
                                                            "MV_CHANGE", "EVENT_BOX_GACHA", "REMOVE_EXPIRED_ITEM", "AR_TITLE_START",
                                                            "AR_SCENE_START", "AR_MARKER", "AR_PHOTO", "AR_SHARE", "DIVA_INTIMACY_EXP_ADD",
                                                            "PRESENT_CAMPAIGN_ENTRY", "PRESENT_CAMPAIGN_RESULT", "EVENT_HOME",
                                                            "ADVENTURE", "SUBSCRIPTION_UPDATE", "VOP_TRANSITION", "VOP_APPEARENCE",
                                                            "VOP_ORDERS", "VOP_RESULTS", "COSTUME_ENHANCE", "HEALITEM_CONSUME",
                                                            "VOP_DIVA_TOUCH", "VOP_FAST_COMPELTE", "RAID_STAGE_START", "RAID_STAGE_END",
                                                            "RAID_BOSS_ENCOUNTER", "LOBBY_TRANSITION", "LOBBY_SELECT_GROUP", "BLOCKLIST",
                                                            "HEAL_AP", "DECO_TRANSITION", "VALKYRIE_ENHANCE", "FAN_REGISTER", "MC_CHARGE",
                                                            "RAID_BOSS_ATACK", "DECO_BUY", "DECO_LAYOUT_SET", "RAID_BOSS_REWARD",
                                                            "DECO_VISIT", "DECO_ITEM_COLLECTION", "DECO_ITEM_LEVELUP", "CHAT",
                                                            "DECO_ITEM_SET", "DECO_STAMP_SAVE", "RAID_BOSS_APPEARENCE", "DECO_SNS",
                                                            "LOBBY_VISIT", "HOME_CLOTHS", "GODIVA_EVENT_STAGE_START", "GODIVA_EVENT_STAGE_END",
                                                            "GODIVA_EVENT_USED_FEVERITEM", "HOME_DIVA_MODIFY", "HOME_MODIFY"}; // 0x0
	public static string[] KDIDJBOMHFO = new string[50] {
		JpStringLiterals.StringLiteral_11078,
		JpStringLiterals.StringLiteral_12839,
		JpStringLiterals.StringLiteral_12840,
		JpStringLiterals.StringLiteral_12841,
		JpStringLiterals.StringLiteral_12842,
		JpStringLiterals.StringLiteral_12843,
		JpStringLiterals.StringLiteral_12844,
		JpStringLiterals.StringLiteral_12845,
		JpStringLiterals.StringLiteral_12846,
		JpStringLiterals.StringLiteral_12847,
		JpStringLiterals.StringLiteral_12848,
		JpStringLiterals.StringLiteral_12849,
		JpStringLiterals.StringLiteral_12850,
		JpStringLiterals.StringLiteral_12851,
		JpStringLiterals.StringLiteral_12852,
        JpStringLiterals.StringLiteral_12853,
		JpStringLiterals.StringLiteral_12854,
		JpStringLiterals.StringLiteral_12855,
        JpStringLiterals.StringLiteral_12856,
		JpStringLiterals.StringLiteral_12857,
		JpStringLiterals.StringLiteral_12858,
        JpStringLiterals.StringLiteral_12859,
		JpStringLiterals.StringLiteral_12860,
		JpStringLiterals.StringLiteral_12861,
        JpStringLiterals.StringLiteral_12862, 
		JpStringLiterals.StringLiteral_12863,
		JpStringLiterals.StringLiteral_12864,
        JpStringLiterals.StringLiteral_12865, 
		JpStringLiterals.StringLiteral_12866,
		JpStringLiterals.StringLiteral_12867,
        JpStringLiterals.StringLiteral_12868, 
		JpStringLiterals.StringLiteral_12869,
		JpStringLiterals.StringLiteral_12870,
        JpStringLiterals.StringLiteral_12871, 
		JpStringLiterals.StringLiteral_12872,
		JpStringLiterals.StringLiteral_12873,
        JpStringLiterals.StringLiteral_12874, 
		JpStringLiterals.StringLiteral_12875,
		JpStringLiterals.StringLiteral_12876,
        JpStringLiterals.StringLiteral_12877, 
		JpStringLiterals.StringLiteral_12878,
		JpStringLiterals.StringLiteral_12879,
        JpStringLiterals.StringLiteral_12880, 
		JpStringLiterals.StringLiteral_12881,
		JpStringLiterals.StringLiteral_12882,
        JpStringLiterals.StringLiteral_12883, 
		JpStringLiterals.StringLiteral_12884,
		JpStringLiterals.StringLiteral_12885,
        JpStringLiterals.StringLiteral_12886, 
		JpStringLiterals.StringLiteral_12887 }; // 0x4
	public static string[] CINOEDJHDIE = new string[46] {
		JpStringLiterals.StringLiteral_12888,
		JpStringLiterals.StringLiteral_12889,
		JpStringLiterals.StringLiteral_12890,
        JpStringLiterals.StringLiteral_12891, 
		JpStringLiterals.StringLiteral_11079,
		JpStringLiterals.StringLiteral_12892,
        JpStringLiterals.StringLiteral_12893, 
		JpStringLiterals.StringLiteral_11219,
		JpStringLiterals.StringLiteral_11216,
        JpStringLiterals.StringLiteral_12894, 
		JpStringLiterals.StringLiteral_11220,
		JpStringLiterals.StringLiteral_12895,
        JpStringLiterals.StringLiteral_11217, 
		JpStringLiterals.StringLiteral_11218,
		JpStringLiterals.StringLiteral_12896,
        JpStringLiterals.StringLiteral_12897, 
		JpStringLiterals.StringLiteral_12898,
		JpStringLiterals.StringLiteral_12899,
        JpStringLiterals.StringLiteral_12900, 
		JpStringLiterals.StringLiteral_12901,
		JpStringLiterals.StringLiteral_12902,
        JpStringLiterals.StringLiteral_12903, 
		JpStringLiterals.StringLiteral_12904,
		JpStringLiterals.StringLiteral_12905,
        JpStringLiterals.StringLiteral_12906, 
		JpStringLiterals.StringLiteral_12907,
		JpStringLiterals.StringLiteral_12908,
        JpStringLiterals.StringLiteral_12909, 
		JpStringLiterals.StringLiteral_12910,
		JpStringLiterals.StringLiteral_11221,
        JpStringLiterals.StringLiteral_12911, 
		JpStringLiterals.StringLiteral_12912,
		JpStringLiterals.StringLiteral_12913,
        JpStringLiterals.StringLiteral_12914, 
		JpStringLiterals.StringLiteral_12915,
		JpStringLiterals.StringLiteral_12916,
        JpStringLiterals.StringLiteral_12917, 
		JpStringLiterals.StringLiteral_12918,
		JpStringLiterals.StringLiteral_12919,
        JpStringLiterals.StringLiteral_12920, 
		JpStringLiterals.StringLiteral_12921,
		JpStringLiterals.StringLiteral_12922,
        JpStringLiterals.StringLiteral_12923, 
		JpStringLiterals.StringLiteral_12924,
		JpStringLiterals.StringLiteral_12925,
        JpStringLiterals.StringLiteral_12926}; // 0x8
	public static string[] BHKNBCJGBDG = new string[11] {
		JpStringLiterals.StringLiteral_12927,
		JpStringLiterals.StringLiteral_12928,
		JpStringLiterals.StringLiteral_12929,
        JpStringLiterals.StringLiteral_12930, 
		JpStringLiterals.StringLiteral_12931,
		JpStringLiterals.StringLiteral_12932,
        JpStringLiterals.StringLiteral_12933, 
		JpStringLiterals.StringLiteral_12934,
		JpStringLiterals.StringLiteral_12935,
        JpStringLiterals.StringLiteral_12936, 
		JpStringLiterals.StringLiteral_12937}; // 0xC
	public static string[] GNIPLCBMPEG = new string[5] {
		JpStringLiterals.StringLiteral_10136,
		JpStringLiterals.StringLiteral_11431,
		JpStringLiterals.StringLiteral_11428,
		JpStringLiterals.StringLiteral_11429, 
		JpStringLiterals.StringLiteral_11430}; // 0x10
}
