
public class OAGBCBBHMPF
{
    public enum KJDNDEDOIOO
    {
        FNGAOJCJFJP = 0,
        JONAMONAHOB_1 = 1,
        PMFGEJJDMCK = 2,
        ALABPEPENHH = 3,
        FKODKMNGCEH = 4,
        IMJLLLNHICJ = 5,
        KHMDGNKEFOD = 6,
        JNBKOAKJDAL_7 = 7,
        NNAPCDMAAJM = 8,
        JAHALBMOANH = 9,
        OJOLFJGNEMO = 10,
        DBIDGHMFLIC = 11,
        IEEKNBEEMMM_12 = 12,
        EAEHILOBHDA_13 = 13,
        AOPBBHMIEPB = 14,
        MNFOJMBPHEN_15 = 15,
        JOLBIMMKGIP = 16,
        HGOGFPOCKFA = 17,
        BBDKHAMANCB_18 = 18,
        AMBIOHGPBNH = 19,
        EEPIDKPPLJI_ValkyrieChange = 20,
        PNMJDKOLGEG = 21,
        EBLJKIOEELA = 22,
        PGHFPIMIOKE = 23,
        CMBKHLDBIEC = 24,
        FLBCPKHGLPE_25 = 25,
        MLNHHIIDJAO_Anketo = 26,
        COBCMOAAAFF_27 = 27,
        GIBLHFKIMDA_28 = 28,
        MFIIOABPKAO = 29,
        EPABCLLAJDP = 30,
        FCIJOHCNLBB = 31,
        EEGOAEADLDP = 32,
        JMAJBHENDPF = 33,
        NJKBAICBOIN = 34,
        GBABEMFLPBA = 35,
        NJEIHFPKOMG_ServerSaveLoadInfo = 36,
        HHGEPDNBGAI_37 = 37,
        PMHLIBHEBBB_38 = 38,
        FEIOPIIEIKB_39 = 39,
        EAGAKGNNINL_40 = 40,
        EEOLHMGNJGO_41 = 41,
        LKOICKMAADB = 42,
        GHJEAPLGKHJ = 43,
        IGKMGFKKKHI = 44,
        IENGPDCDMBM = 45,
        GDHNBIIOKMF = 46,
        GADJDBJLIGC_47 = 47,
        DBNECDJCNOI_48 = 48,
        CBKENDJIBDM = 49,
        LIPHGGFEJFJ = 50,
        LCDPEMIFNKJ_51 = 51,
        ICAHGJMMGLM_52 = 52,
        BGJDJBOCLEA_53 = 53,
        ILLBGAFIBDE_54 = 54,
        KIFPDEFNEPB_55 = 55,
        PHLHLIDCNNN_56 = 56,
        DNNLEIKNHKL_57 = 57,
        CDNFJBAJAMM = 58,
        BLDDKDNOCFA = 59,
        DADNPOJNIBL_60 = 60,
        LIIJEGOIKDP = 61,
        LPKDNOINDPE_62 = 62,
        BKLNHBHDDEJ_63 = 63,
        DAGHKCKEJPA_64 = 64,
        OEGCKACJMPM_65 = 65,
        ONPIDKLOPIP_66 = 66,
        BABLKKLEPGD_67 = 67,
        PLEKHHPMELF_68 = 68,
        FJBCAHAFLNO_69 = 69,
        FDFMKBGPALI_70 = 70,
        LOGBJCFCJND = 71,
        FIPDFLHPNDO = 72,
        KCCMKAEPGPE = 73,
        PEBDGCDNPDM = 74,
        PHCLHGPCFNL = 75,
        HGNLDJNEGJM_76 = 76,
        ICDCMLKMEHI = 77,
        CLGHLKLHEAK = 78,
        ELDCONNMDGN_79 = 79,
        CIGPIPBPABC_80 = 80,
        MINOEGPNBIH_81 = 81,
        EEHEMNBJPAP = 82,
        FJIPPAPEBID = 83,
        BOIIMIEPMLG = 84,
        HONFKODFAPA = 85,
        PFBIHCIFFKM_86 = 86,
        CEFIPAIKAKN_87 = 87,
        NOMCHDMPFFE_88 = 88,
        CHMEOKEKABD_89 = 89,
        MIDMMEHCCFA_90 = 90,
        OMLMHKGCJPH_91 = 91,
        ONMOONKHHLO = 92,
        HNOKBPNGOEF_93 = 93,
        LHCHBHPHLCP = 94,
        CJCJNKOPIKB = 95,
        DNJGGCJPIMC_96 = 96,
        HPNIJDCPCNC_97 = 97,
        HJGEAHELBPE_98 = 98,
        NBCACPPAAMC = 99,
        BBIBBNHCPPJ = 100,
    }
	
	public enum OGBCFNIKAFI
	{
		FKPEAGGKNLC_0 = 0,
		BABBMOJCMDM_1 = 1,
		MHFHGNFCEHJ = 2, // 2 => 12 %
		NJLGGHGMLMN = 3,
		DCFJPBCIBEI = 4,
		KGDFCJPODAJ = 5,
		BHNNPGACIDF = 6,
		KCKOFDFGLFE = 7,
		HIEPCGKPDEH = 8,
		PHLKLILEPPA = 9,
		EDLJLDPMKIF = 10,
		CKKHFDJCHBC = 11,
		ECPJHFJHHFP = 12,
		FFPMNJAMFCP_13 = 13,
		JHMCNBGOOJF_14 = 14,
		EKEBEGIELBJ_15 = 15,
		HIAAKPMJJGD_16 = 16,
		BMIDACPCELO_17 = 17,
		HOIECIKEIHB_18 = 18,
		FEEJKNDAHFE_19 = 19,
		PHOGGPBMGAE_20 = 20,
		ECLDDCCEJJG_21 = 21,
		KIBFDMGJFMO_22 = 22,
		JKGGACIFBOM_23 = 23,
		HMJIFCKIGEC = 24,
		NBFHAMJNMMG_25 = 25,
		JAPPCJMLAMJ_26 = 26,
		BJBDDPHJHFA_27 = 27,
		CAMJGCCMANN_28 = 28,
		KLPNOJFFNGL_29 = 29,
		KBMDDIHNCFI_30 = 30,
		KAEEOAPBOCI_31 = 31,
		BKFDCMALJBF_32 = 32,
		CBMEJNCDJEG = 33,
		FFFHCFBMHDD_34 = 34,
		GFLDEDJAONB_35 = 35,
		NKJKAEHAFJO = 36, // 36 => 46 %
		IDIINPAANKI = 37,
		JDOHDMDGOEL = 38,
		LALOFKILEHB = 39,
		MGBMNPHKKHD = 40,
		NHIGFHJEKOO = 41,
		OKFOGBPEHON = 42,
		CMLPNGAJOAP = 43,
		IPLMCBFBFGB = 44,
		GJOEAOEHPNE = 45,
		KBHNAJGGEPE = 46,
		CFHINEFGHPC_47 = 47,
		LGFGBNKFPGH_48 = 48,
		HDMADAHNLDN_49 = 49,
		CGKOFIKBMMI = 50,
	}

	public enum COIIJOEKBDH
	{
		IMJOELNOOMB_0 = 0,
		EDHFDPBEFKA = 1,
		GBMFNHOFGOP = 2,
		DOEHLCLBCNN_3 = 3,
		CNACJCAMCFB_4 = 4,
		EMAFECNMGDA = 5,
		ICAPJDDJIEA_6 = 6,
		APJJPDJNOJB_7 = 7,
		LEABABGFEGB_8 = 8,
		MGEFPKOJKBL_9 = 9,
		PCDOEIFMLHG_10 = 10,
		FBCINBIIABE_11 = 11,
		LIHFAAPBLOH_12 = 12,
		NJCPDNAHPDP_13 = 13,
		IGAJCMKNLDL_14 = 14,
		LJILBHPMPOG_15 = 15,
		GMOLAHOIJHE = 16,
		HJGPNANNPNM_17 = 17,
		NJCKHBPLDGL = 18,
		GHLEPCNBCNC = 19,
		ACNGACBALGM = 20,
		EAKANCJFFKF = 21,
		IOBDJDHJJFK_22 = 22,
		JJGHKIBKFFJ_23 = 23,
		NODLEHAGKMN_24 = 24,
		LEHHJINPFHA_25 = 25,
		KEFAKKJOACI = 26,
		KFFIFJIBHFM = 27,
		JMLJADADEEF_28 = 28,
		DIDJLIPNCKO_29 = 29,
		PFPGFPLGANO = 30,
		DOENIIJNHNJ = 31,
		HEKCMMMHFMA = 32,
		ADJKNFCENEA = 33,
		ENGODNEBGJD_34 = 34,
		IOEGFJMNDBM_35 = 35,
		JJNIMNEJPOF_36 = 36,
		JPPOGMHJKKJ_37 = 37,
		PJPBCFKEGBC = 38,
		KGOOLKLPJIP = 39,
		LLMGBJKCBHI_40 = 40,
		HNJIKEJADJL = 41,
		CDJJNKKIBJN = 42,
		MIDINHNHGNP_43 = 43,
		MDPHOJAPCCC = 44,
		EJPNJANOEEA = 45,
	}

	public enum DKAMMIHBINF
	{
		KJHABBHBFPD = 0,
		DECFIFJACCL = 1,
		DODPGHDOFIO_2 = 2,
		BPCPDNGLNGO = 3,
		HEFPAOLDHCK = 4,
		FCMMKJLCFAB = 5,
		IDINJDEBPKP_6 = 6,
		IFEDIOFCOBC_7 = 7,
		KDDHGLNCFMF = 8,
		PGNFDEIHHMD = 9,
		EKJGOMKEJLK = 10,
	}

	public enum NALHDBIKFJO
	{
		HJNNKCMLGFL_0 = 0,
		FKKEAHEAOMM_1 = 1,
		EANGJBHNNHF_2 = 2,
		KEFKPCMGHIJ_3 = 3,
		NGBOABGLAMM_4 = 4,
	}

	public static string[] IEPAJNPLHJI_EventId = new string[101] { "NONE", "PAID", "CONSUME", "TUTORIAL", "STAGE_START", "STAGE_END", "DECK_CH",
                                                            "GACHA", "ENHANCE", "GET_ITEM", "MUSIC_DL", "CLOTHES", "MISSION", "VIEW",
                                                            "STORY", "FRIEND", "OPEN_SNS", "SNS", "EPISODE", "REVIEW", "VALKYRIE", 
                                                            "RANK_UP", "DIVA_LEVELUP", "EMBLEM", "VOICE", "ENERGY", "ENQUETE", "EMBLEM_GET",
                                                            "EVENT_END", "MISSION_EVENT_SELECT", "MISSION_EVENT_RESET", "MISSION_STAGE_START",
                                                            "MISSION_STAGE_END", "EVENT_STAGE_START", "EVENT_STAGE_END", 
                                                            "MISSION_EVENT_CHANGE", "GAME_START_LOAD", "BATTLE_STAGE_MATCH",
                                                            "BATTLE_STAGE_START", "BATTLE_STAGE_END", "BANNER", "UNLOCK_LIMIT_OVER",
                                                            "MISSION_EVENT_START", "MISSION_EVENT_SELECT_LEVEL", "MISSION_EVENT_SELECT_MUSIC",
                                                            "MV_STAGE_START", "MV_STAGE_END", "VIEW_MOVIE", "SHOP_BUY", 
                                                            "MV_CHANGE", "EVENT_BOX_GACHA", "REMOVE_EXPIRED_ITEM", "AR_TITLE_START",
                                                            "AR_SCENE_START", "AR_MARKER", "AR_PHOTO", "AR_SHARE", "DIVA_INTIMACY_EXP_ADD",
                                                            "PRESENT_CAMPAIGN_ENTRY", "PRESENT_CAMPAIGN_RESULT", "EVENT_HOME",
                                                            "ADVENTURE", "SUBSCRIPTION_UPDATE", "VOP_TRANSITION", "VOP_APPEARENCE",
                                                            "VOP_ORDERS", "VOP_RESULTS", "COSTUME_ENHANCE", "HEALITEM_CONSUME",
                                                            "VOP_DIVA_TOUCH", "VOP_FAST_COMPELTE", "RAID_STAGE_START", "RAID_STAGE_END",
                                                            "RAID_BOSS_ENCOUNTER", "LOBBY_TRANSITION", "LOBBY_SELECT_GROUP", "BLOCKLIST",
                                                            "HEAL_AP", "DECO_TRANSITION", "VALKYRIE_ENHANCE", "FAN_REGISTER", "MC_CHARGE",
                                                            "RAID_BOSS_ATACK", "DECO_BUY", "DECO_LAYOUT_SET", "RAID_BOSS_REWARD",
                                                            "DECO_VISIT", "DECO_ITEM_COLLECTION", "DECO_ITEM_LEVELUP", "CHAT",
                                                            "DECO_ITEM_SET", "DECO_STAMP_SAVE", "RAID_BOSS_APPEARENCE", "DECO_SNS",
                                                            "LOBBY_VISIT", "HOME_CLOTHS", "GODIVA_EVENT_STAGE_START", "GODIVA_EVENT_STAGE_END",
                                                            "GODIVA_EVENT_USED_FEVERITEM", "HOME_DIVA_MODIFY", "HOME_MODIFY"}; // 0x0
	public static string[] KDIDJBOMHFO = new string[50] {
		JpStringLiterals.StringLiteral_11078,
		JpStringLiterals.StringLiteral_12839,
		JpStringLiterals.StringLiteral_12840,
		JpStringLiterals.StringLiteral_12841,
		JpStringLiterals.StringLiteral_12842,
		JpStringLiterals.StringLiteral_12843,
		JpStringLiterals.StringLiteral_12844,
		JpStringLiterals.StringLiteral_12845,
		JpStringLiterals.StringLiteral_12846,
		JpStringLiterals.StringLiteral_12847,
		JpStringLiterals.StringLiteral_12848,
		JpStringLiterals.StringLiteral_12849,
		JpStringLiterals.StringLiteral_12850,
		JpStringLiterals.StringLiteral_12851,
		JpStringLiterals.StringLiteral_12852,
        JpStringLiterals.StringLiteral_12853,
		JpStringLiterals.StringLiteral_12854,
		JpStringLiterals.StringLiteral_12855,
        JpStringLiterals.StringLiteral_12856,
		JpStringLiterals.StringLiteral_12857,
		JpStringLiterals.StringLiteral_12858,
        JpStringLiterals.StringLiteral_12859,
		JpStringLiterals.StringLiteral_12860,
		JpStringLiterals.StringLiteral_12861,
        JpStringLiterals.StringLiteral_12862, 
		JpStringLiterals.StringLiteral_12863,
		JpStringLiterals.StringLiteral_12864,
        JpStringLiterals.StringLiteral_12865, 
		JpStringLiterals.StringLiteral_12866,
		JpStringLiterals.StringLiteral_12867,
        JpStringLiterals.StringLiteral_12868, 
		JpStringLiterals.StringLiteral_12869,
		JpStringLiterals.StringLiteral_12870,
        JpStringLiterals.StringLiteral_12871, 
		JpStringLiterals.StringLiteral_12872,
		JpStringLiterals.StringLiteral_12873,
        JpStringLiterals.StringLiteral_12874, 
		JpStringLiterals.StringLiteral_12875,
		JpStringLiterals.StringLiteral_12876,
        JpStringLiterals.StringLiteral_12877, 
		JpStringLiterals.StringLiteral_12878,
		JpStringLiterals.StringLiteral_12879,
        JpStringLiterals.StringLiteral_12880, 
		JpStringLiterals.StringLiteral_12881,
		JpStringLiterals.StringLiteral_12882,
        JpStringLiterals.StringLiteral_12883, 
		JpStringLiterals.StringLiteral_12884,
		JpStringLiterals.StringLiteral_12885,
        JpStringLiterals.StringLiteral_12886, 
		JpStringLiterals.StringLiteral_12887 }; // 0x4
	public static string[] CINOEDJHDIE = new string[46] {
		JpStringLiterals.StringLiteral_12888,
		JpStringLiterals.StringLiteral_12889,
		JpStringLiterals.StringLiteral_12890,
        JpStringLiterals.StringLiteral_12891, 
		JpStringLiterals.StringLiteral_11079,
		JpStringLiterals.StringLiteral_12892,
        JpStringLiterals.StringLiteral_12893, 
		JpStringLiterals.StringLiteral_11219,
		JpStringLiterals.StringLiteral_11216,
        JpStringLiterals.StringLiteral_12894, 
		JpStringLiterals.StringLiteral_11220,
		JpStringLiterals.StringLiteral_12895,
        JpStringLiterals.StringLiteral_11217, 
		JpStringLiterals.StringLiteral_11218,
		JpStringLiterals.StringLiteral_12896,
        JpStringLiterals.StringLiteral_12897, 
		JpStringLiterals.StringLiteral_12898,
		JpStringLiterals.StringLiteral_12899,
        JpStringLiterals.StringLiteral_12900, 
		JpStringLiterals.StringLiteral_12901,
		JpStringLiterals.StringLiteral_12902,
        JpStringLiterals.StringLiteral_12903, 
		JpStringLiterals.StringLiteral_12904,
		JpStringLiterals.StringLiteral_12905,
        JpStringLiterals.StringLiteral_12906, 
		JpStringLiterals.StringLiteral_12907,
		JpStringLiterals.StringLiteral_12908,
        JpStringLiterals.StringLiteral_12909, 
		JpStringLiterals.StringLiteral_12910,
		JpStringLiterals.StringLiteral_11221,
        JpStringLiterals.StringLiteral_12911, 
		JpStringLiterals.StringLiteral_12912,
		JpStringLiterals.StringLiteral_12913,
        JpStringLiterals.StringLiteral_12914, 
		JpStringLiterals.StringLiteral_12915,
		JpStringLiterals.StringLiteral_12916,
        JpStringLiterals.StringLiteral_12917, 
		JpStringLiterals.StringLiteral_12918,
		JpStringLiterals.StringLiteral_12919,
        JpStringLiterals.StringLiteral_12920, 
		JpStringLiterals.StringLiteral_12921,
		JpStringLiterals.StringLiteral_12922,
        JpStringLiterals.StringLiteral_12923, 
		JpStringLiterals.StringLiteral_12924,
		JpStringLiterals.StringLiteral_12925,
        JpStringLiterals.StringLiteral_12926}; // 0x8
	public static string[] BHKNBCJGBDG = new string[11] {
		JpStringLiterals.StringLiteral_12927,
		JpStringLiterals.StringLiteral_12928,
		JpStringLiterals.StringLiteral_12929,
        JpStringLiterals.StringLiteral_12930, 
		JpStringLiterals.StringLiteral_12931,
		JpStringLiterals.StringLiteral_12932,
        JpStringLiterals.StringLiteral_12933, 
		JpStringLiterals.StringLiteral_12934,
		JpStringLiterals.StringLiteral_12935,
        JpStringLiterals.StringLiteral_12936, 
		JpStringLiterals.StringLiteral_12937}; // 0xC
	public static string[] GNIPLCBMPEG = new string[5] {
		JpStringLiterals.StringLiteral_10136,
		JpStringLiterals.StringLiteral_11431,
		JpStringLiterals.StringLiteral_11428,
		JpStringLiterals.StringLiteral_11429, 
		JpStringLiterals.StringLiteral_11430}; // 0x10
}
