
public class OAILDDLJFEE : AEJLAOKEPFC
{
	// RVA: 0x1CC5C6C Offset: 0x1CC5C6C VA: 0x1CC5C6C Slot: 5
	public EDOHBJAPLPF_JsonData LPGBJBHFINB(JNMFKOHFAFB_PublicStatus.ONCMONJIPCD _IDLHJIOMJBK_data)
	{
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		EDOHBJAPLPF_JsonData data2 = new EDOHBJAPLPF_JsonData();
		for(int i = 0; i < 4; i++)
		{
			data2.Add(AEFEIKGDBMD(_IDLHJIOMJBK_data.JOHLGBDOLNO_AssistScenes[i]));
		}
		data[AFEHLCGHAEE_Strings.COEBIDJMMCH_assist_name] = _IDLHJIOMJBK_data.JCJNKBKMJFK_Name;
		data[AFEHLCGHAEE_Strings.GGLICPAANFE_assist_data_list] = data2;
		return data;
	}

	// RVA: 0x1CC5E54 Offset: 0x1CC5E54 VA: 0x1CC5E54 Slot: 4
	public EDOHBJAPLPF_JsonData AEFEIKGDBMD(JNMFKOHFAFB_PublicStatus.KNHIPBADANI KDIFMECGNIC)
	{
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		data[AFEHLCGHAEE_Strings.PPFNGGCBJKC_id] = KDIFMECGNIC.PPFNGGCBJKC_id;
		data[AFEHLCGHAEE_Strings.ANAJIAENLNB_lv] = KDIFMECGNIC.ANAJIAENLNB_lv;
		data[AFEHLCGHAEE_Strings.MJBODMOLOBC_luck] = KDIFMECGNIC.MJBODMOLOBC_luck;
		data[AFEHLCGHAEE_Strings.ALMNMBDELDB_mlt] = KDIFMECGNIC.JPIPENJGGDD_NumBoard;
		data["leaf"] = KDIFMECGNIC.DMNIMMGGJJJ_Leaf;
		data[AFEHLCGHAEE_Strings.DANMJLOBLIE_mb] = CEDHHAGBIBA.EHNMFLADJKG_ByteArrayToString(KDIFMECGNIC.PDNIFBEGMHC_Mb);
		data[AFEHLCGHAEE_Strings.KOHNLDKIKPC_sb] = CEDHHAGBIBA.EHNMFLADJKG_ByteArrayToString(KDIFMECGNIC.EMOJHJGHJLN_Sb);
		return data;
	}
}
