
public class OAILDDLJFEE : AEJLAOKEPFC
{
	// RVA: 0x1CC5C6C Offset: 0x1CC5C6C VA: 0x1CC5C6C Slot: 5
	public EDOHBJAPLPF_JsonData LPGBJBHFINB(JNMFKOHFAFB_PublicStatus.ONCMONJIPCD IDLHJIOMJBK)
	{
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		EDOHBJAPLPF_JsonData data2 = new EDOHBJAPLPF_JsonData();
		for(int i = 0; i < 4; i++)
		{
			data2.Add(AEFEIKGDBMD(IDLHJIOMJBK.JOHLGBDOLNO_DataList[i]));
		}
		data[AFEHLCGHAEE_Strings.COEBIDJMMCH_assist_name] = IDLHJIOMJBK.JCJNKBKMJFK_Name;
		data[AFEHLCGHAEE_Strings.GGLICPAANFE_assist_data_list] = data2;
		return data;
	}

	// RVA: 0x1CC5E54 Offset: 0x1CC5E54 VA: 0x1CC5E54 Slot: 4
	public EDOHBJAPLPF_JsonData AEFEIKGDBMD(JNMFKOHFAFB_PublicStatus.KNHIPBADANI KDIFMECGNIC)
	{
		EDOHBJAPLPF_JsonData data = new EDOHBJAPLPF_JsonData();
		data[AFEHLCGHAEE_Strings.PPFNGGCBJKC_Id] = KDIFMECGNIC.PPFNGGCBJKC_Id;
		data[AFEHLCGHAEE_Strings.ANAJIAENLNB_lv] = KDIFMECGNIC.ANAJIAENLNB_Level;
		data[AFEHLCGHAEE_Strings.MJBODMOLOBC_luck] = KDIFMECGNIC.MJBODMOLOBC_Luck;
		data[AFEHLCGHAEE_Strings.ALMNMBDELDB_mlt] = KDIFMECGNIC.JPIPENJGGDD_Mlt;
		data["leaf"] = KDIFMECGNIC.DMNIMMGGJJJ_Leaf;
		data[AFEHLCGHAEE_Strings.DANMJLOBLIE_mb] = CEDHHAGBIBA.EHNMFLADJKG_ByteArrayToString(KDIFMECGNIC.PDNIFBEGMHC_Mb);
		data[AFEHLCGHAEE_Strings.KOHNLDKIKPC_sb] = CEDHHAGBIBA.EHNMFLADJKG_ByteArrayToString(KDIFMECGNIC.EMOJHJGHJLN_Sb);
		return data;
	}
}
