
public class PCKLFFNPPLF : BNKMBBKMBNC
{
	//// RVA: 0xCC0F50 Offset: 0xCC0F50 VA: 0xCC0F50 Slot: 4
	public void NCMOCCDGKBP(AFIFDLOAKGI GEFIGDIDKPH, MNDAMOGGJBJ JICEBIKLCPF)
	{
		int cnt = GEFIGDIDKPH.ENNLMALGDKN();
		for (int i = 0; i < cnt; i++)
		{
			int itemId = EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, GEFIGDIDKPH.HMHJMPKLGID(i));
			int a = GEFIGDIDKPH.EHCMOEACKFP(i);
			bool isNew = true;
			int existIdx = 0;
			for(int j = 0; j < JICEBIKLCPF.INLBMFMOHCI.Count; j++)
			{
				if (JICEBIKLCPF.INLBMFMOHCI[j].PPFNGGCBJKC_Id == itemId)
				{
					existIdx = j;
					isNew = false;
				}
			}
			if(isNew)
			{
				MNDAMOGGJBJ.JFJJNPJNBPI d = new MNDAMOGGJBJ.JFJJNPJNBPI();
				d.PPFNGGCBJKC_Id = itemId;
				d.HMFFHLPNMPH = a;
				JICEBIKLCPF.INLBMFMOHCI.Add(d);
			}
			else
			{
				JICEBIKLCPF.INLBMFMOHCI[existIdx] = new MNDAMOGGJBJ.JFJJNPJNBPI() { PPFNGGCBJKC_Id = itemId, HMFFHLPNMPH = JICEBIKLCPF.INLBMFMOHCI[existIdx].HMFFHLPNMPH + a };
			}
		}
		cnt = GEFIGDIDKPH.PKLGGJPPBAN();
		for(int i = 0; i < cnt; i++)
		{
			int itemId = GEFIGDIDKPH.DEPIOOMBGDG(i);
			int a = GEFIGDIDKPH.BAGAEINPFNJ(i);
			bool isNew = true;
			int existIndex = 0;
			for(int j = 0; j < JICEBIKLCPF.INLBMFMOHCI.Count; j++)
			{
				if (JICEBIKLCPF.INLBMFMOHCI[j].PPFNGGCBJKC_Id == itemId)
				{
					existIndex = j;
					isNew = false;
				}
			}
			if (isNew)
			{
				MNDAMOGGJBJ.JFJJNPJNBPI d = new MNDAMOGGJBJ.JFJJNPJNBPI();
				d.PPFNGGCBJKC_Id = itemId;
				d.HMFFHLPNMPH = a;
				JICEBIKLCPF.INLBMFMOHCI.Add(d);
			}
			else
			{
				JICEBIKLCPF.INLBMFMOHCI[existIndex] = new MNDAMOGGJBJ.JFJJNPJNBPI() { PPFNGGCBJKC_Id = itemId, HMFFHLPNMPH = JICEBIKLCPF.INLBMFMOHCI[existIndex].HMFFHLPNMPH + a };
			}
		}
		JICEBIKLCPF.INLBMFMOHCI.Sort((MNDAMOGGJBJ.JFJJNPJNBPI HKICMNAACDA, MNDAMOGGJBJ.JFJJNPJNBPI BNKHBCBJBKI) =>
		{
			//0xCC19CC
			return HKICMNAACDA.PPFNGGCBJKC_Id - BNKHBCBJBKI.PPFNGGCBJKC_Id;
		});
		JICEBIKLCPF.CMBGGPOFBOO += GEFIGDIDKPH.PBIHLJKLHGJ;
	}

	//// RVA: 0xCC1764 Offset: 0xCC1764 VA: 0xCC1764 Slot: 5
	public void NCMOCCDGKBP(MNDAMOGGJBJ JICEBIKLCPF, int KIJAPOFAGPN)
	{
		if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database != null && CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave != null)
		{
			MNDAMOGGJBJ.JFJJNPJNBPI j = new MNDAMOGGJBJ.JFJJNPJNBPI();
			j.MBFFGGFGPEN(KIJAPOFAGPN, EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_ServerSave, EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, EKLNMHFCAOI.DEACAHNLMNI_getItemId(KIJAPOFAGPN), null));
			JICEBIKLCPF.INLBMFMOHCI.Add(j);
		}
	}
}
