
public class PCKLFFNPPLF : BNKMBBKMBNC
{
	//// RVA: 0xCC0F50 Offset: 0xCC0F50 VA: 0xCC0F50 Slot: 4
	public void NCMOCCDGKBP(AFIFDLOAKGI GEFIGDIDKPH, MNDAMOGGJBJ JICEBIKLCPF)
	{
		int cnt = GEFIGDIDKPH.ENNLMALGDKN();
		for (int i = 0; i < cnt; i++)
		{
			int itemId = EKLNMHFCAOI.GJEEGMCBGGM_GetItemFullId(EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, GEFIGDIDKPH.HMHJMPKLGID(i));
			int a = GEFIGDIDKPH.EHCMOEACKFP(i);
			bool isNew = true;
			int existIdx = 0;
			for(int j = 0; j < JICEBIKLCPF.INLBMFMOHCI_CostItems.Count; j++)
			{
				if (JICEBIKLCPF.INLBMFMOHCI_CostItems[j].PPFNGGCBJKC_id == itemId)
				{
					existIdx = j;
					isNew = false;
				}
			}
			if(isNew)
			{
				MNDAMOGGJBJ.JFJJNPJNBPI d = new MNDAMOGGJBJ.JFJJNPJNBPI();
				d.PPFNGGCBJKC_id = itemId;
				d.HMFFHLPNMPH_count = a;
				JICEBIKLCPF.INLBMFMOHCI_CostItems.Add(d);
			}
			else
			{
				JICEBIKLCPF.INLBMFMOHCI_CostItems[existIdx] = new MNDAMOGGJBJ.JFJJNPJNBPI() { PPFNGGCBJKC_id = itemId, HMFFHLPNMPH_count = JICEBIKLCPF.INLBMFMOHCI_CostItems[existIdx].HMFFHLPNMPH_count + a };
			}
		}
		cnt = GEFIGDIDKPH.PKLGGJPPBAN();
		for(int i = 0; i < cnt; i++)
		{
			int itemId = GEFIGDIDKPH.DEPIOOMBGDG(i);
			int a = GEFIGDIDKPH.BAGAEINPFNJ(i);
			bool isNew = true;
			int existIndex = 0;
			for(int j = 0; j < JICEBIKLCPF.INLBMFMOHCI_CostItems.Count; j++)
			{
				if (JICEBIKLCPF.INLBMFMOHCI_CostItems[j].PPFNGGCBJKC_id == itemId)
				{
					existIndex = j;
					isNew = false;
				}
			}
			if (isNew)
			{
				MNDAMOGGJBJ.JFJJNPJNBPI d = new MNDAMOGGJBJ.JFJJNPJNBPI();
				d.PPFNGGCBJKC_id = itemId;
				d.HMFFHLPNMPH_count = a;
				JICEBIKLCPF.INLBMFMOHCI_CostItems.Add(d);
			}
			else
			{
				JICEBIKLCPF.INLBMFMOHCI_CostItems[existIndex] = new MNDAMOGGJBJ.JFJJNPJNBPI() { PPFNGGCBJKC_id = itemId, HMFFHLPNMPH_count = JICEBIKLCPF.INLBMFMOHCI_CostItems[existIndex].HMFFHLPNMPH_count + a };
			}
		}
		JICEBIKLCPF.INLBMFMOHCI_CostItems.Sort((MNDAMOGGJBJ.JFJJNPJNBPI _HKICMNAACDA_a, MNDAMOGGJBJ.JFJJNPJNBPI _BNKHBCBJBKI_b) =>
		{
			//0xCC19CC
			return _HKICMNAACDA_a.PPFNGGCBJKC_id - _BNKHBCBJBKI_b.PPFNGGCBJKC_id;
		});
		JICEBIKLCPF.CMBGGPOFBOO_UcCost += GEFIGDIDKPH.PBIHLJKLHGJ_UCNumber;
	}

	//// RVA: 0xCC1764 Offset: 0xCC1764 VA: 0xCC1764 Slot: 5
	public void NCMOCCDGKBP(MNDAMOGGJBJ JICEBIKLCPF, int _KIJAPOFAGPN_ItemId)
	{
		if(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database != null && CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData != null)
		{
			MNDAMOGGJBJ.JFJJNPJNBPI j = new MNDAMOGGJBJ.JFJJNPJNBPI();
			j.MBFFGGFGPEN(_KIJAPOFAGPN_ItemId, EKLNMHFCAOI.ALHCGDMEMID_GetNumItems(IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database, CIOECGOMILE.HHCJCDFCLOB.AHEFHIMGIBI_PlayerData, EKLNMHFCAOI.FKGCBLHOOCL_Category.HLCHKCJLEGK_GrowItem, EKLNMHFCAOI.DEACAHNLMNI_getItemId(_KIJAPOFAGPN_ItemId), null));
			JICEBIKLCPF.INLBMFMOHCI_CostItems.Add(j);
		}
	}
}
