using UnityEngine;
using System.Collections.Generic;

public class PIGBKEIAMPE
{
    public enum BEKLBBDMAIJ
    {
        HJNNKCMLGFL = 0,
        CCAPCGPIIPF = 1,
        MDKMGHFJCNE = 2,
        BJACNBJLCHJ = 3,
        INFDLLGDBAO = 4,
        ANLLGBEIBNF = 5,
        DBDFOJLHOAH = 6,
    }
    
    public class CDDNFEDGCGG
    {
        public int MLPEHNBNOGD; // 0x8
        public long ANDGMDJLDLO; // 0x10
    }

	public static bool AGBLJGDGMGH = false; // 0x0
	public static bool CBHJOLOBEOM = false; // 0x1
	public static bool LAGJJJEJKAM = false; // 0x2
	public static int AAPDNPBGOHN = 1; // 0x4
	public static int KDCAJOMCENG = 1; // 0x8
	public static int KHCFABMANLC = 10; // 0xC
	public const int MAAAHDFNPHC = 200;
	public const int DCBJGIMHMMJ = 30;
	public const int GKFANOADIEA = 50;
	public const int NDADCONKKJH = 30;
	public const int LJEAGBPNMDE = 30;
	public const int KCJEDOLEAOI = 1;
	public const int DBPCPFOFIHF = 6;
	public const int CCJOIDHGOKG = -1;
	public const int NCEBCHHHEIH = 50;
	public const string JBIFCINAJAJ = "fan_count";
	private long MBPPBKAKIBM; // 0x20
	private long AEGKFFCKLNL; // 0x30
	private long LCCEHNMDILJ; // 0x38
	private int DPLHEBFFOBA = 600; // 0x40
	private string PEHPMOBIOJF; // 0x58
	private string CCJEGGGJJPO; // 0x5C
	public static bool HPAFJEGOFHI = false; // 0x10
	public int NKLACAPLMHI; // 0x64
	public bool GJHIHNBANEC; // 0x68
	private long GBLOMHMEMIC; // 0x70
	private bool LNHFLJBGGJB; // 0x78
	private uint PMBEODGMMBB = 0x15ab17a1; // 0x7C
	private static string[] ANELGKCJBAA = new string[5] { "StringLiteral_13101", "StringLiteral_13102", "StringLiteral_13103",
                                                        "StringLiteral_13104", "StringLiteral_13105" }; // 0x14
	public static bool DDNKBFMAHIB = false; // 0x18

	public bool PLOOEECNHFB { get; private set; } // 0x8 MGFBAEDOIDD JFOKBBLFMLD EDBGNGILAKA
	public int AIIOKIHEPDP { get; private set; } // 0xC MOFMDCNBIMC EDJKOFKFJFB MPDLGJHEFEI
	public int JPEIBHJIHPI { get; private set; } // 0x10 BHDIHHLPFME FLLNLLNBOEM LFDFIALJEDB
	public int LIEOOJCODFH { get; private set; } // 0x14 ALMMJEIPEEG DFGOBOKMBPK HAEIMBPACOO
	public int JCOBBOMCENL { get; private set; } // 0x18 PAKABOCDKJD DJHDCPBHPFB AFHCLIDDBOK
	public bool BKEOKNIEHII { get; private set; } // 0x1C PCBJHOFEIPH GAOJGOFBFOJ OCLIONPHBJE
	public int PPCNLKHHMFK { get; private set; } // 0x28 ELCPJCPGLBE IBNLBJALAGM BNEBLCHLJGI
	public bool EMBDPGBMCBF { get; private set; } // 0x2C PLBPKJKHLIK CKILJINALAK PPKHDDFFMMJ
	public int NMOJPDCBGMK { get; private set; } // 0x44 DINIENCLHLC HLHCEMNIPAA KJBCNOAFKPF
	public PIGBKEIAMPE.BEKLBBDMAIJ EMJFHKHLHDB { get; private set; } // 0x48 DBCICDKJFAG AIAPBFFGEGM LMDJCGGLPKB
	public List<IBIGBMDANNM> BFDEHIANFOG { get; private set; } // 0x4C OJLMPOEKAGH BPLEGOEMMNC CHJHFOMDIMP
	// public List<int> AONMOEOHFGP { get; private set; } // 0x50 HAGFPDKGCEO FFDGLAPBKPI BGAMDNPFHFE
	public List<int> JFDPPPBMCBK { get; private set; } // 0x54 NGJJFKKFHEE PBEFGAEJEBH PCFHMNADHFD
	public List<PIGBKEIAMPE.CDDNFEDGCGG> KAMNNDELNHG { get; private set; } // 0x60 EGDOIJNLCLC OOAJNNIHLPH LGBIBHJJEKL
	// public int LMCNBGMCOCI { get; } ??

	// // RVA: 0x16D39A4 Offset: 0x16D39A4 VA: 0x16D39A4
	// public void MFKOGDNNKLP() { }

	// // RVA: 0x16D3FC0 Offset: 0x16D3FC0 VA: 0x16D3FC0
	// public void OKJJBFBDPDI() { }

	// // RVA: 0x16D463C Offset: 0x16D463C VA: 0x16D463C
	// private void NDBHHJGGFDF(int PPFNGGCBJKC) { }

	// // RVA: 0x16D4768 Offset: 0x16D4768 VA: 0x16D4768
	// public void OCGEPBECHGB() { }

	// // RVA: 0x16D47E8 Offset: 0x16D47E8 VA: 0x16D47E8
	// public int KKPENKOHLCO() { }

	// // RVA: 0x16D47F8 Offset: 0x16D47F8 VA: 0x16D47F8
	// private void IMLMNFGDFPE(CACGCMBKHDI ADKIDBJCAJA, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D4920 Offset: 0x16D4920 VA: 0x16D4920
	public PIGBKEIAMPE()
    {
        JCOBBOMCENL = 0;
        LIEOOJCODFH = 0;
        JPEIBHJIHPI = 0;
        LIEOOJCODFH = 0;
        AEGKFFCKLNL = 0;
        PLOOEECNHFB = false;
        MBPPBKAKIBM = 0;
        PPCNLKHHMFK = 0;
        EMBDPGBMCBF = false;
        NMOJPDCBGMK = 0;
        EMJFHKHLHDB = PIGBKEIAMPE.BEKLBBDMAIJ.HJNNKCMLGFL/*0*/;
        BFDEHIANFOG = new List<IBIGBMDANNM>(200);
        JFDPPPBMCBK = new List<int>(50);
        KAMNNDELNHG = new List<PIGBKEIAMPE.CDDNFEDGCGG>(20);
        PEHPMOBIOJF = Application.persistentDataPath + "/SaveData";
        CCJEGGGJJPO = Application.persistentDataPath + "/fca";
    }

	// // RVA: 0x16D4AAC Offset: 0x16D4AAC VA: 0x16D4AAC
	// public void HHDGOABFEPC(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x16D4E68 Offset: 0x16D4E68 VA: 0x16D4E68
	// public void PGPLAOGALHD(int ELEPHBOKIGK, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D5094 Offset: 0x16D5094 VA: 0x16D5094
	// public void PFJBNPIBFMO(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x16D54F4 Offset: 0x16D54F4 VA: 0x16D54F4
	// public void MEJHFCBFPED(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x16D58B4 Offset: 0x16D58B4 VA: 0x16D58B4
	// public void BMJANOADDCC(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG, bool FBBNPFFEJBN = False) { }

	// // RVA: 0x16D5B90 Offset: 0x16D5B90 VA: 0x16D5B90
	// public void KIOJKHJNNNJ(SakashoPlayerCriteria IPKCADIAAPG, SakashoPlayerData.SearchOrder EILKGEADKGH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D6084 Offset: 0x16D6084 VA: 0x16D6084
	// public int CDOBDJFJLPG() { }

	// // RVA: 0x16D61B0 Offset: 0x16D61B0 VA: 0x16D61B0
	// public void CHAILEPDOPJ(EMOLDNAEDMG JENNNPEFPGF, EMOLDNAEDMG PFDAJGNEBJM, EMOLDNAEDMG PDIMJPKFILN, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D6944 Offset: 0x16D6944 VA: 0x16D6944
	// public void NCEJOLLKDDF() { }

	// // RVA: 0x16D69D4 Offset: 0x16D69D4 VA: 0x16D69D4
	// private int HEPEDNJMCFA(int HKICMNAACDA, int BNKHBCBJBKI) { }

	// // RVA: 0x16D6A08 Offset: 0x16D6A08 VA: 0x16D6A08
	// private void DLPHPGJCAAF(List<IBIGBMDANNM> NNDGIAEFMOG) { }

	// // RVA: 0x16D6B60 Offset: 0x16D6B60 VA: 0x16D6B60
	// private void NPGOGNGOBOE(List<IBIGBMDANNM> DMKCJODMFDH, List<IBIGBMDANNM> PDKNONEKLPL, List<IBIGBMDANNM> NDBOEFNFOBC, int FDNKMHGFBDJ, int LJBEDHNNMAO) { }

	// // RVA: 0x16D6F30 Offset: 0x16D6F30 VA: 0x16D6F30
	// public void POEDEMPINCH(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D7244 Offset: 0x16D7244 VA: 0x16D7244
	// public void CKJHFFHFPLH(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D74F4 Offset: 0x16D74F4 VA: 0x16D74F4
	// public bool PDEACDHIJJJ(int MLPEHNBNOGD) { }

	// // RVA: 0x16D75B4 Offset: 0x16D75B4 VA: 0x16D75B4
	// public void GJODIMMDJHJ(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D7814 Offset: 0x16D7814 VA: 0x16D7814
	// public void IJGADKKPAGJ(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D7B14 Offset: 0x16D7B14 VA: 0x16D7B14
	// public void LJMOBJNEHPM(int FBNPCFPONBN, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D7F54 Offset: 0x16D7F54 VA: 0x16D7F54
	// private bool LBIDNNNIFBD(SakashoErrorId KLCMLLLIANB) { }

	// // RVA: 0x16D7F78 Offset: 0x16D7F78 VA: 0x16D7F78
	// private bool DENFAJIBOOO(string LIDBGALGECP, SakashoErrorId KLCMLLLIANB, IMCBBOAFION HIDFAIBOHCC) { }

	// // RVA: 0x16D82AC Offset: 0x16D82AC VA: 0x16D82AC
	// public void AOHLMBKILED(int HPFDEEDLBOA, string LIDBGALGECP, int OCJLKGDPOMH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D86DC Offset: 0x16D86DC VA: 0x16D86DC
	// public void ADOIKCJALGM(int HPFDEEDLBOA, string LIDBGALGECP, int OCJLKGDPOMH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D89C8 Offset: 0x16D89C8 VA: 0x16D89C8
	// public void CCBALBLFNDN(int HPFDEEDLBOA, string LIDBGALGECP, int OCJLKGDPOMH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D8CC4 Offset: 0x16D8CC4 VA: 0x16D8CC4
	// public void FFIBIAEJBNC(int HPFDEEDLBOA, string LIDBGALGECP, int OCJLKGDPOMH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D8FC8 Offset: 0x16D8FC8 VA: 0x16D8FC8
	// public void PBEDDFMFDKB(int HPFDEEDLBOA, string LIDBGALGECP, int OCJLKGDPOMH, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D92D0 Offset: 0x16D92D0 VA: 0x16D92D0
	// public void EICNBEKECJG(List<int> FAMHAPONILI, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D9538 Offset: 0x16D9538 VA: 0x16D9538
	// public void EICNBEKECJG(List<IBIGBMDANNM> AHEFHIMGIBI, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16D9714 Offset: 0x16D9714 VA: 0x16D9714
	// public static string MKILKPFAOIC(long BEBJKJKBOGH, long EABMEFOJHOJ) { }

	// // RVA: 0x16D9AB8 Offset: 0x16D9AB8 VA: 0x16D9AB8
	// public static SakashoPlayerCriteria NKNOLNNPGAC(BBHNACPENDM AHEFHIMGIBI) { }

	// // RVA: 0x16D9C04 Offset: 0x16D9C04 VA: 0x16D9C04
	// public static SakashoPlayerCriteria NKNOLNNPGAC(BBHNACPENDM AHEFHIMGIBI, int PPFNGGCBJKC) { }

	// // RVA: 0x16D9D54 Offset: 0x16D9D54 VA: 0x16D9D54
	// public static int DJHFILDBOFG() { }

	// // RVA: 0x16D9E44 Offset: 0x16D9E44 VA: 0x16D9E44
	// public static int GKDGOGCOGBK() { }

	// // RVA: 0x16D9F20 Offset: 0x16D9F20 VA: 0x16D9F20
	// public void EGLFECJOPPP(PIGBKEIAMPE.KIELKOCLIGG PIBLLGLCJEO, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// [IteratorStateMachineAttribute] // RVA: 0x6B6E98 Offset: 0x6B6E98 VA: 0x6B6E98
	// // RVA: 0x16D9F88 Offset: 0x16D9F88 VA: 0x16D9F88
	// private IEnumerator PJHEJPKCHHE(PIGBKEIAMPE.KIELKOCLIGG PIBLLGLCJEO, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x16DA05C Offset: 0x16DA05C VA: 0x16DA05C
	// public void CPEHDILBIJA(int FGHNNFGJKJE, SakashoPlayerCriteria IPKCADIAAPG, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// [IteratorStateMachineAttribute] // RVA: 0x6B6F10 Offset: 0x6B6F10 VA: 0x6B6F10
	// // RVA: 0x16DA0CC Offset: 0x16DA0CC VA: 0x16DA0CC
	// private IEnumerator DAEDHMHBPCI(int FGHNNFGJKJE, SakashoPlayerCriteria IPKCADIAAPG, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x16DA1B8 Offset: 0x16DA1B8 VA: 0x16DA1B8
	// public void EPKOLKBGOGA(List<int> FNLNHGBGHKF, List<int> EDPCFGCDEFE, IMCBBOAFION BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG, DJBHIFLHJLK DDMLOBICBHI) { }

	// // RVA: 0x16DABA4 Offset: 0x16DABA4 VA: 0x16DABA4
	// public void NDDIOKIKCNA(int MLPEHNBNOGD, Action<int> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x16DAE5C Offset: 0x16DAE5C VA: 0x16DAE5C
	// public void CCAOOIMEPAL(Action<int> BHFHGFKBOHH, DJBHIFLHJLK MOBEEPPKFLG) { }

	// // RVA: 0x16DAF20 Offset: 0x16DAF20 VA: 0x16DAF20
	// public void BCEAAAOLGEB() { }

	// // RVA: 0x16DAFA0 Offset: 0x16DAFA0 VA: 0x16DAFA0
	// public int OKDGKAHNBPP() { }

	// // RVA: 0x16DB090 Offset: 0x16DB090 VA: 0x16DB090
	// public void HMANIPMKKFK(int EHGBICNIBKE, IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP JEMKODBAOEP, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DB434 Offset: 0x16DB434 VA: 0x16DB434
	// public void CIBLHBAMIJO(int EHGBICNIBKE, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DB6FC Offset: 0x16DB6FC VA: 0x16DB6FC
	// public bool DIGEHCDEAON(int MLPEHNBNOGD) { }

	// // RVA: 0x16DB804 Offset: 0x16DB804 VA: 0x16DB804
	// public void DIGEHCDEAON(int MLPEHNBNOGD, IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP ADNFKFINOBO, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DBA70 Offset: 0x16DBA70 VA: 0x16DBA70
	// public void LJLKGPDFEAD(int HPFDEEDLBOA, IMCBBOAFION BHFHGFKBOHH, JFDNPFFOACP ADNFKFINOBO, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DBCDC Offset: 0x16DBCDC VA: 0x16DBCDC
	// public void EKIJICIBGOG(bool FBBNPFFEJBN, IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DBFFC Offset: 0x16DBFFC VA: 0x16DBFFC
	// public void EGFNFKJOMIM(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }

	// // RVA: 0x16DC14C Offset: 0x16DC14C VA: 0x16DC14C
	// private void JPALOIENDOP(IMCBBOAFION BHFHGFKBOHH, CACGCMBKHDI.HDHIKGLMOGF MOBEEPPKFLG, CACGCMBKHDI.HDHIKGLMOGF AOCANKOMKFG) { }
}