
public class PJADOKMABLA
{
	public AFICKGBLCKO[] KKFLAKPPPHL { get; set; } // 0x8 MOEKECBIILD DMEGLNCFKKH IDLCACEMKPK
	public CNPDMOGIBEN[] HONMNBAJPGL { get; set; } // 0xC KBAKPGIOKAA LDNJEPPPPGA NELOBFINFJH
	public CHOGPKAJDJN[] JDODPPDNNFK { get; set; } // 0x10 CGDOLHJEOBI NHIBBNMFLHJ LFKMDFGOCAB
	public NKJOBGGCCNA[] MLMGFOGCDMD { get; set; } // 0x14 DCCINJNILEL FDHOOMNIEAE OFEAAAAKFCC

	// // RVA: 0x92F49C Offset: 0x92F49C VA: 0x92F49C
	// public static PJADOKMABLA HEGEKFMJNCC(byte[] NIODCJLINJN) { }
}
