using System.Collections.Generic;

public class EPPOHFLMDBC
{
	public int FBGGEFFJJHB = 0x1a915b; // 0x8
	public int MBCPMFPKNBA; // 0xC
	public int DBJFLJIMONP; // 0x10
	public int NDKJOJLCJBI; // 0x14
	public int GLMAGOANCLM; // 0x18
	public int CHINMGJCEDH; // 0x1C
	public int EAJBBFLFDHI; // 0x20
	public int EHDLPKCCJIA; // 0x24

	public int ANAJIAENLNB { get { return FBGGEFFJJHB ^ MBCPMFPKNBA; } set { MBCPMFPKNBA = FBGGEFFJJHB ^ value; } } //0xFC14D4 MMOMNMBKHJF 0xFC14E4 FEHNFGPFINK
	// public int HFIDCMNFBJG { get; set; } 0xFC14F4 CMDOHPBAFCO 0xFC1504 BJBDGCMJNEO
	// public int PFJCOCPKABN { get; set; } 0xFC1514 EJPPLFNLAAO 0xFC1524 NEMMJEJENFD
	// public int JFJDLEMNKFE { get; set; } 0xFC1534 GCMPLDKECFM 0xFC1544 CEHKELOHIBD
	// public int GDOLPGBLMEA { get; set; } 0xFC1554 LEHDODJMICA 0xFC1564 IKPOCJDOOGA
	// public int ONDFNOOICLE { get; set; } 0xFC1574 OGGOHKCANFG 0xFC1584 BKMHMPEBNPE
	// public int HCFOMFDPGEC { get; set; } 0xFC1594 GGIDKCOMCJL 0xFC15A4 LAIHOHGICJD

	// // RVA: 0xFC15B4 Offset: 0xFC15B4 VA: 0xFC15B4
	public void DOMFHDPMCCO(int ANAJIAENLNB, int FBGGEFFJJHB, short JKPPKAHPPKH, short MKMIEGPOKGG, short MELGGCAIONF, short LDLHPACIIAB, short JNNDFGPMEDA, short IDOIMLGLPAB)
	{
		this.MBCPMFPKNBA = FBGGEFFJJHB ^ ANAJIAENLNB;
		this.FBGGEFFJJHB = FBGGEFFJJHB;
		this.DBJFLJIMONP = JKPPKAHPPKH ^ FBGGEFFJJHB;
		this.NDKJOJLCJBI = MKMIEGPOKGG ^ FBGGEFFJJHB;
		this.GLMAGOANCLM = MELGGCAIONF ^ FBGGEFFJJHB;
		this.CHINMGJCEDH = LDLHPACIIAB ^ FBGGEFFJJHB;
		this.EAJBBFLFDHI = JNNDFGPMEDA ^ FBGGEFFJJHB;
		this.EHDLPKCCJIA = IDOIMLGLPAB ^ FBGGEFFJJHB;
	}

	// // RVA: 0xFC160C Offset: 0xFC160C VA: 0xFC160C
	public void ANIJHEBLMGB(int INDDJNMPONH, short JBGEEPFKIGG)
	{
		switch(INDDJNMPONH)
		{
			case 1:
			DBJFLJIMONP = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ DBJFLJIMONP ) + JBGEEPFKIGG);
			break;
			case 2:
			NDKJOJLCJBI = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ NDKJOJLCJBI ) + JBGEEPFKIGG);
			break;
			case 3:
			GLMAGOANCLM = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ GLMAGOANCLM ) + JBGEEPFKIGG);
			break;
			case 4:
			CHINMGJCEDH = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ CHINMGJCEDH ) + JBGEEPFKIGG);
			break;
			case 5:
			EAJBBFLFDHI = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ EAJBBFLFDHI ) + JBGEEPFKIGG);
			break;
			case 6:
			EHDLPKCCJIA = FBGGEFFJJHB ^ (( FBGGEFFJJHB ^ EHDLPKCCJIA ) + JBGEEPFKIGG);
			break;
			default:
			break;
		}
	}

	// // RVA: 0xFC1698 Offset: 0xFC1698 VA: 0xFC1698
	public void ODDIHGPONFL(EPPOHFLMDBC GPBJHKLFCEP)
	{
		MBCPMFPKNBA = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.MBCPMFPKNBA ^ FBGGEFFJJHB;
		DBJFLJIMONP = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.DBJFLJIMONP ^ FBGGEFFJJHB;
		NDKJOJLCJBI = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.NDKJOJLCJBI ^ FBGGEFFJJHB;
		GLMAGOANCLM = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.GLMAGOANCLM ^ FBGGEFFJJHB;
		CHINMGJCEDH = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.CHINMGJCEDH ^ FBGGEFFJJHB;
		EAJBBFLFDHI = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.EAJBBFLFDHI ^ FBGGEFFJJHB;
		EHDLPKCCJIA = GPBJHKLFCEP.FBGGEFFJJHB ^ GPBJHKLFCEP.EHDLPKCCJIA ^ FBGGEFFJJHB;
	}

	// // RVA: 0xFC1800 Offset: 0xFC1800 VA: 0xFC1800
	// public uint CAOGDCBPBAN() { }
}

public class BJPLLEBHAGO
{
	public sbyte DOAJJALOKLI; // 0xD
	public sbyte PKNONBBKCCP; // 0xE
	public List<EPPOHFLMDBC> CMCKNKKCNDK = new List<EPPOHFLMDBC>(); // 0x14

	public sbyte AIHCEGFANAM { get; set; } // 0x8 FJOGAAMLJMA ANEJPLENMAL HEHDOGFEIOL
	public sbyte AHHJLDLAPAN { get; set; } // 0x9 AMALMGIALDF IPKDLMIDMHH IENNENMKEFO
	public sbyte IDDHKOEFJFB { get; set; }  // 0xA KEOMNKLLNFJ // ADCMNNJMGKO KOFCMDMLAHC 
	public sbyte FPMGHDKACOF { get; set; } // 0xB AJHJBOKOPAJ // ALJDJOFDKDJ FPFJHHIANFD
	public sbyte PPEGAKEIEGM { get; set; } // 0xC NEKLJCCBECB KPOEEPIMMJP NCIEAFEDPBH
	public ushort LIOGKHIGJKN { get; set; } // 0x10 DGLBKOGGKHO JNBPCHKDNMD MLPEHHGEEIB
	public ushort CMBCBNEODPD { get; set; } // 0x12 CLHDIBCIJBB EIMFDHBOECI OJMIHHIIBPI

	// // RVA: 0xC85E00 Offset: 0xC85E00 VA: 0xC85E00
	// public uint CAOGDCBPBAN() { }
}
