
using System.Collections.Generic;
using XeSys;

[System.Obsolete("Use DHOJHGODBAB_Quest", true)]
public class DHOJHGODBAB { }
public class DHOJHGODBAB_Quest : DIHHCBACKGG_DbSection
{
	public List<CNLPPCFJEID> BEGCHDHHEKC { get; private set; } // 0x20 FGGBICBDOEN DEBOJOHHPPB CFINEIEEJGN
	public List<CNLPPCFJEID> GPMKFMFEKLN { get; private set; } // 0x24 LKPJIEOOENM HDOHKBOJCDK CDNIDJPOHDJ
	public List<LCKMNLOLDPD> LFAAEPAAEMB { get; private set; } // 0x28 LGPNBHKGMEA CBMPDJKIIOF EFCJGLJJBNA

	// RVA: 0x1988E24 Offset: 0x1988E24 VA: 0x1988E24
	public DHOJHGODBAB_Quest()
	{
		JIKKNHIAEKG_BlockName = "";
		LNIMEIMBCMF = false;
		BEGCHDHHEKC = new List<CNLPPCFJEID>();
		GPMKFMFEKLN = new List<CNLPPCFJEID>();
		LFAAEPAAEMB = new List<LCKMNLOLDPD>();
		LMHMIIKCGPE = 67;
	}

	// RVA: 0x1988F64 Offset: 0x1988F64 VA: 0x1988F64 Slot: 8
	protected override void KMBPACJNEOF()
	{
		BEGCHDHHEKC.Clear();
		GPMKFMFEKLN.Clear();
		LFAAEPAAEMB.Clear();
		int t = (int)Utility.GetCurrentUnixTime();
		t *= 7;
		int v = t;
		for(int i = 1; i < 21; i++)
		{
			CNLPPCFJEID data = new CNLPPCFJEID();
			data.LHPDDGIJKNB(i, v);
			BEGCHDHHEKC.Add(data);
			v += 3;
		}
		for(int i = 0; i < 1700; i++)
		{
			CNLPPCFJEID data = new CNLPPCFJEID();
			data.LHPDDGIJKNB(i + 1, t);
			GPMKFMFEKLN.Add(data);
			t += 7;
		}
	}

	// RVA: 0x1989194 Offset: 0x1989194 VA: 0x1989194 Slot: 9
	public override bool IIEMACPEEBJ(byte[] DBBGALAPFGC)
	{
		TodoLogger.Log(TodoLogger.Database, "DHOJHGODBAB_Quest.IIEMACPEEBJ");
		return true;
	}

	//// RVA: 0x19891F4 Offset: 0x19891F4 VA: 0x19891F4
	//private bool EELEJILKBIM(GEDOHHLGKCG ENCJBKPHGAL) { }

	//// RVA: 0x1989628 Offset: 0x1989628 VA: 0x1989628
	//private bool GBNIHKOIMFO(GEDOHHLGKCG ENCJBKPHGAL) { }

	//// RVA: 0x1989B7C Offset: 0x1989B7C VA: 0x1989B7C
	//private bool IHJNKFOJPKM(GEDOHHLGKCG ENCJBKPHGAL) { }

	// RVA: 0x1989F28 Offset: 0x1989F28 VA: 0x1989F28 Slot: 11
	public override uint CAOGDCBPBAN()
	{
		TodoLogger.Log(TodoLogger.DbIntegrityCheck, "DHOJHGODBAB_Quest.CAOGDCBPBAN");
		return 0;
	}
}

public class CNLPPCFJEID
{
	public int FBGGEFFJJHB; // 0x8
	private int EHOIENNDEDH; // 0xC
	private int MKENMKMJFKP; // 0x10
	private int ICLBAMBDKNI; // 0x14
	private int NILLPINGIIP; // 0x18
	private int FKKHMCINELD; // 0x1C
	private int IOAGHJGBNLC; // 0x20
	private int APJGMOJDPAK; // 0x24
	private int HNEHIJCAOJM; // 0x28
	private long IBCNABKLHHH; // 0x30
	private long MABPKDKBJAG; // 0x38
	private int HHPFFPINGAA; // 0x40
	private int ELFADCBHPCD; // 0x44
	private int EGCMPELNLKP; // 0x48
	public bool OAPCHMHAJID; // 0x4C
	public int HDBFCIOCNPA; // 0x50

	//public int PPFNGGCBJKC { get; set; } 0x175CD9C DEMEPMAEJOO 0x175CCD4 HIGKAIDMOKN
	//public int INDDJNMPONH { get; set; } 0x175CDA8 GHAILOLPHPF 0x175CCE4 BACGOKIGMBC
	//public int CHOFDPDFPDC { get; set; } 0x175CDB8 IBCDKHDLOKG 0x175CCF4 ICHJGBKDCGM
	//public int FCDKJAKLGMB { get; set; } 0x175CDC8 IJPJEEOLPIG 0x175CDD8 EDECEGOKICK
	//public int HHIBBHFHENH { get; set; } 0x175CDE8 MEHBABCCHOO 0x175CD14 FBCMDNCLBDC
	//public int DEPGBBJMFED { get; set; } 0x175CDF8 FNMFOBJIIIC 0x175CD6C OBEDPJLBBEG
	//public int AKBHPFBDDOL { get; set; } 0x175CE08 ANBHKALCHDJ 0x175CD24 GDANPNDMDCC
	//public int EIHOBHDKCDB { get; set; } 0x175CE18 EALKEGPNHGK 0x175CD04 LNFEIPOKKNG
	//public int EILKGEADKGH { get; set; } 0x175CE28 NPDDACIHBKD 0x175CD34 BJJMCKHBPNH
	//public int LMPPENOILPF { get; set; } 0x175CE38 JAOMCMFJPDJ 0x175CD7C LINHGODPPMB
	//public long KJBGCLPMLCG { get; set; } 0x175CE48 IDLJOCDJJOC 0x175CD44 ODIEKGPKOAC
	//public long GJFPFFBAKGK { get; set; } 0x175CE60 KPBMCJKFEGN 0x175CD58 IEFCDGKGICA
	//public int EKANGPODCEP { get; set; } 0x175CE78 EBLAFEMDFGD 0x175CD8C AHEFELNFBDM

	//// RVA: 0x175CC78 Offset: 0x175CC78 VA: 0x175CC78
	public void LHPDDGIJKNB(int PPFNGGCBJKC, int KNEFBLHBDBG)
	{
		FBGGEFFJJHB = PPFNGGCBJKC * KNEFBLHBDBG * 11;
		OAPCHMHAJID = false;
		HHPFFPINGAA = FBGGEFFJJHB;
		ELFADCBHPCD = FBGGEFFJJHB;
		EGCMPELNLKP = FBGGEFFJJHB;
		EHOIENNDEDH = FBGGEFFJJHB ^ FBGGEFFJJHB;
		MKENMKMJFKP = FBGGEFFJJHB;
		ICLBAMBDKNI = FBGGEFFJJHB;
		FKKHMCINELD = FBGGEFFJJHB;
		IOAGHJGBNLC = FBGGEFFJJHB;
		APJGMOJDPAK = FBGGEFFJJHB;
		HNEHIJCAOJM = FBGGEFFJJHB;
		IBCNABKLHHH = FBGGEFFJJHB;
		MABPKDKBJAG = FBGGEFFJJHB;
	}

	//// RVA: 0x175CE88 Offset: 0x175CE88 VA: 0x175CE88
	//public uint CAOGDCBPBAN() { }
}

public class LCKMNLOLDPD
{
	public int FBGGEFFJJHB = 0x340f8ed5; // 0x8
	public int EHOIENNDEDH; // 0xC
	public int AHGCGHAAHOO; // 0x10
	public int HLMAFFLCCKD; // 0x14
	public int IPFBMBMNAGL; // 0x18
	public int OHDDANALELB; // 0x1C

	//public int PPFNGGCBJKC { get; set; } 0xD9A97C DEMEPMAEJOO 0xD9A98C HIGKAIDMOKN
	//public int GLCLFMGPMAN { get; set; } 0xD9A99C LNJAENEGDEL 0xD9A9AC JHIDBGCHOKL
	//public int HMFFHLPNMPH { get; set; } 0xD9A9BC NJOGDDPICKG 0xD9A9CC NBBGMMBICNA
	//public int BGFPPGPJONG { get; set; } 0xD9A9DC LBMNPGFFCJN 0xD9A9EC NDNCLLKIJHA
	//public int APNMKLJMPMD { get; set; } 0xD9A9FC ICCFOKKODOH 0xD9AA0C CBPDLNBEJAE

	//// RVA: 0xD9AA1C Offset: 0xD9AA1C VA: 0xD9AA1C
	//public uint CAOGDCBPBAN() { }
}
