using System.Collections.Generic;
using XeSys;

public class KOGHKIODHPA { }
public class KOGHKIODHPA_Board : DIHHCBACKGG
{
    public class ADPMJDMFEIK
    {
        public int FBGGEFFJJHB; // 0x8
        private KOGHKIODHPA NDFIEMPPMLF; // 0xC
        public DMPDJFAGCPN EEDDJLLIOBD; // 0x10
        private int EOGELFKOHLF; // 0x14
        private int PDDFMJANJPF; // 0x18
        private int OCJAOJJDCBP; // 0x1C
        private int OPLKJKAIFPF; // 0x20
        private int GALOFABOMPJ; // 0x24
        private int MFINGOBDNBH; // 0x28
        private int LBBHOJADFBO; // 0x2C
        private int KAFJPMJJPIL; // 0x30
        private int GKLNKCGBEPF; // 0x34
        private int EBPGCKLJPKA; // 0x38
        private int FMHEJDAADKH; // 0x3C
        private int KIANBOJPALC; // 0x40
        private int EBNKFLGEDDI; // 0x44
        public List<AFIFDLOAKGI> HBHMAKNGKFK; // 0x48
        private int APDKLPBBPAF; // 0x4C
        private int LKCIMIMDHPG; // 0x50
        private int EGFKEAGMECF; // 0x54
        private int HOLMBHBIPMM; // 0x58
        private int LGPJBMDMLJH; // 0x5C
        private int PKCPMLCGAPG; // 0x60

        // public int AOPBAOJIOGO { get; set; } HDLCEEHNBKN 0x11317C0 AGKAANFCJIP 0x11317D0
        // public int ILABPFOMEAG { get; set; } ICFAOLCLHIA 0x11317E0 LIJJLCOMANF 0x11317F0
        // public int JGJFIJOCPAG { get; set; } JAGNIHJLOMM 0x1131800 GAGFPHDHMMM 0x1131810
        // public int JPIPENJGGDD { get; set; } FBLKAMOKPPP 0x1131820 BEEPHNBJGLI 0x1131830
        // public int JPJNKNOJBMM { get; set; } PNLGBGONPND 0x1131840 BPMONMAGICM 0x1131850
        // public int CHCLMPKHHEP { get; set; } KCCBJPIDNAE 0x1131860 DKDKIIHCEIC 0x1131870
        // public int NGBNKKJNCMO { get; set; } ONCBPABLANF 0x112FEE4 JOHLGKCHOLN 0x1131880
        // public int NEDFDMNEOKO { get; set; } PGEFCCNDCBL 0x112FEC4 IPMGEHJELJL 0x1131890
        // public int PAMLNGINDDA { get; set; } LCCEEIOKPAA 0x112FED4 NIGONEJGPDE 0x11318A0
        // public int NHLHNOPEHEI { get; set; } FGMBDFCAEJO 0x11318B0 PAJBMCKJDEG 0x11318C0
        // public int BCEOCNGPPMN { get; set; } OAJMLBAMIHL 0x11318D0 GKMFFPGNJMM 0x11318E0
        // public int NFLPEKNOEFH { get; set; } IDNHDLLGFFB 0x11318F0 LFBGENBNHKC 0x1131900
        // public int HDDBOHKFEIF { get; set; } ALKGDGFNNGC 0x1131910 HFJEPAIIKPL 0x1131920
        // public int PFNNOEANAHE { get; set; } DCHAJEMDBHB 0x1131930 DDKPFFABOAP 0x1131940
        // public int PFGFNIHOOHE { get; set; } ELLNMCBFFIP 0x1131950 GJJEMLNICGI 0x1131960
        // public int HGNGPAFOFNG { get; set; } CIMGIKJHIDO 0x1131970 FPHKKGHEBNG 0x1131980
        // public int PLNJOOPGGIG { get; set; } OFLAKKFDGFD 0x1131990 PENEGEDLOBL 0x11319A0
        // public int JFFEGBIODOJ { get; set; } AENBCBOPEKE 0x11319B0 EMBGHHLLHEC 0x11319C0
        // public int AEBEPGKIOFM { get; set; } GCPLFDONNIM 0x11319D0 HLCCBPNDEOE 0x11319E0

        // // RVA: 0x112FBBC Offset: 0x112FBBC VA: 0x112FBBC
        public ADPMJDMFEIK()
		{
			LHPDDGIJKNB_Reset();
		}

        // // RVA: 0x11319F0 Offset: 0x11319F0 VA: 0x11319F0
        public void LHPDDGIJKNB_Reset()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			NDFIEMPPMLF = null;
			EEDDJLLIOBD = null;
			EBNKFLGEDDI = FBGGEFFJJHB;
			HBHMAKNGKFK = null;
			LGPJBMDMLJH = FBGGEFFJJHB;
			PKCPMLCGAPG = FBGGEFFJJHB;
			EOGELFKOHLF = 0;
			PDDFMJANJPF = 0;
			OCJAOJJDCBP = 0;
			OPLKJKAIFPF = 0;
			GALOFABOMPJ = 0;
			MFINGOBDNBH = 0;
			LBBHOJADFBO = 0;
			KAFJPMJJPIL = 0;
			GKLNKCGBEPF = 0;
			EBPGCKLJPKA = 0;
			FMHEJDAADKH = 0;
			KIANBOJPALC = 0;
			APDKLPBBPAF = 0;
			LKCIMIMDHPG = 0;
			EGFKEAGMECF = 0;
			HOLMBHBIPMM = 0;
		}

        // // RVA: 0x112FBDC Offset: 0x112FBDC VA: 0x112FBDC
        // public void KHEKNNFCAOI_Init(KOGHKIODHPA NDFIEMPPMLF, int AOPBAOJIOGO, int OIPCCBHIKIA, int JPIPENJGGDD, int JPJNKNOJBMM, int ILABPFOMEAG, int JGJFIJOCPAG) { }

        // // RVA: 0x1131AB4 Offset: 0x1131AB4 VA: 0x1131AB4
        // public List<AFIFDLOAKGI> NKBGIKPCLMI(bool ANKEMCJFFIO) { }

        // // RVA: 0x1131DB4 Offset: 0x1131DB4 VA: 0x1131DB4
        // public void OMKKILODDIC(byte[] ODKMKEHJOCK, int MBLGJDKKLPO = 0) { }
    }

	public List<AFIFDLOAKGI> PJADHDHKOEJ { get; private set; } // 0x20 PPFNCNJKAPF APNMMPMNLML NDIACKACKOI
	public List<DMPDJFAGCPN> KLEBDKALPBD_Layout { get; private set; } // 0x24 DMCGOAHMECN DJAFNIBLLLC EHCJBJLFBFF
	public List<DMPDJFAGCPN> OONHJNINFAD_Sub { get; private set; } // 0x28 MLDNBLDHOLH KGCKKJIENOE OGIACBCKLFI
	public List<DMPDJFAGCPN> GLEOCPPMAKK { get; private set; } // 0x2C JJOCGMGGFCH KGIGLDBCCJK IDBJLNPNOKK
	public List<NHINPDLLFIO> GJLBMELKHEM { get; private set; } // 0x30 LLHGFEAEMNA EPGHPHEGHIN HCFHCAJOHMJ

	// // RVA: 0x112F6A0 Offset: 0x112F6A0 VA: 0x112F6A0
	// public AFIFDLOAKGI DDGNLCJGFJF(int KIJAPOFAGPN) { }

	// // RVA: 0x112F730 Offset: 0x112F730 VA: 0x112F730
	// public DMPDJFAGCPN FDCDIHIIJJM(int BJNBBEMBMIK) { }

	// // RVA: 0x112F7DC Offset: 0x112F7DC VA: 0x112F7DC
	// public DMPDJFAGCPN GPKFGCFHDHH(int BJNBBEMBMIK, bool JEMMNNJIIJL = False) { }

	// // RVA: 0x112F898 Offset: 0x112F898 VA: 0x112F898
	// public AFIFDLOAKGI BHMFCIIGKCB(int BJNBBEMBMIK, int OIPCCBHIKIA) { }

	// // RVA: 0x112F990 Offset: 0x112F990 VA: 0x112F990
	// public AFIFDLOAKGI PBINAHNEFIK(int AOPBAOJIOGO, int OIPCCBHIKIA, int JPIPENJGGDD, int JPJNKNOJBMM, int ILABPFOMEAG, int JGJFIJOCPAG) { }

	// // RVA: 0x112FEF4 Offset: 0x112FEF4 VA: 0x112FEF4
	// public bool AKKIBDEENJH(int ILABPFOMEAG) { }

	// // RVA: 0x112FFE4 Offset: 0x112FFE4 VA: 0x112FFE4
	// public int NENHCPMDAGM(int JPIPENJGGDD, int AOPBAOJIOGO, int ILABPFOMEAG) { }

	// // RVA: 0x1130188 Offset: 0x1130188 VA: 0x1130188
	public KOGHKIODHPA_Board()
    {
		JIKKNHIAEKG = "";
		LNIMEIMBCMF = false;
		PJADHDHKOEJ = new List<AFIFDLOAKGI>(500);
		KLEBDKALPBD_Layout = new List<DMPDJFAGCPN>(1000);
		OONHJNINFAD_Sub = new List<DMPDJFAGCPN>(20);
		GLEOCPPMAKK = new List<DMPDJFAGCPN>(20);
		GJLBMELKHEM = new List<NHINPDLLFIO>(2);
		LMHMIIKCGPE = 7;
    }

	// // RVA: 0x1130328 Offset: 0x1130328 VA: 0x1130328 Slot: 8
	protected override void KMBPACJNEOF()
    {
		PJADHDHKOEJ.Clear();
		KLEBDKALPBD_Layout.Clear();
		OONHJNINFAD_Sub.Clear();
		GLEOCPPMAKK.Clear();
		GJLBMELKHEM.Clear();
    }

	// // RVA: 0x1130450 Offset: 0x1130450 VA: 0x1130450 Slot: 9
	public override bool IIEMACPEEBJ(byte[] DBBGALAPFGC)
    {
		GGNFFEBIPON parser = GGNFFEBIPON.HEGEKFMJNCC(DBBGALAPFGC);
		OFNALFONKFK(parser);
		HBHAHIHFLMH(KLEBDKALPBD_Layout, parser.EBMHHKNDDEN);
		HBHAHIHFLMH(OONHJNINFAD_Sub, GLEOCPPMAKK, parser.EABCJPHDKDC);
		DCMPGIJIBBB(parser);
		return true;
    }

	// // RVA: 0x1131120 Offset: 0x1131120 VA: 0x1131120 Slot: 10
	public override bool IIEMACPEEBJ(EDOHBJAPLPF_JsonData OILEIIEIBHP, int KAPMOPMDHJE)
	{
		TodoLogger.Log(100, "TODO");
		return true;
	}

	// // RVA: 0x113123C Offset: 0x113123C VA: 0x113123C
	// private bool OFNALFONKFK(EDOHBJAPLPF_JsonData OILEIIEIBHP, int KAPMOPMDHJE) { }

	// // RVA: 0x11304F4 Offset: 0x11304F4 VA: 0x11304F4
	private bool OFNALFONKFK(GGNFFEBIPON FOLMNOOIOFM)
	{
		long time = Utility.GetCurrentUnixTime();
		long key = time * 0xb5c17;
		CBKLHFDMLFO[] array = FOLMNOOIOFM.CNGFINPPJKG;
		for(int i = 0; i < array.Length; i++)
		{
			AFIFDLOAKGI data = new AFIFDLOAKGI();
			data.FBGGEFFJJHB = (int)key;
			data.MKPJBDFDHOL = (int)array[i].HEOLEHDFLJO;
			data.INDDJNMPONH = (int)array[i].GBJFNGCDKPM;
			data.MKNDAOHGOAK = (int)array[i].KMIDKGMIIBK;
			data.PBIHLJKLHGJ = (int)array[i].ACGLMKEBMDL;
			data.IGNCGOMDGKI = new List<int>();
			for(int j = 0; j < array[i].IFILLPEKJFK.Length; j++)
			{
				data.IGNCGOMDGKI.Add((int)(array[i].IFILLPEKJFK[j] ^ (data.FBGGEFFJJHB * (i + 2))));
			}
			data.IEILOCENAMF = new List<int>();
			for (int j = 0; j < array[i].BONFLFAPFDG.Length; j++)
			{
				data.IEILOCENAMF.Add((int)(array[i].BONFLFAPFDG[j] ^ (data.FBGGEFFJJHB * (i + 2))));
			}
			PJADHDHKOEJ.Add(data);
			key = key * 0xd + 7;
		}
		return true;
	}

	// // RVA: 0x1131244 Offset: 0x1131244 VA: 0x1131244
	// private bool HBHAHIHFLMH(List<DMPDJFAGCPN> NNDGIAEFMOG, string OPFGFINHFCE, EDOHBJAPLPF_JsonData OILEIIEIBHP, int KAPMOPMDHJE) { }

	// // RVA: 0x1130A00 Offset: 0x1130A00 VA: 0x1130A00
	private bool HBHAHIHFLMH(List<DMPDJFAGCPN> NNDGIAEFMOG, AOGBEJNPKFB[] EBMHHKNDDEN)
	{
		for(int i = 0; i < EBMHHKNDDEN.Length; i++)
		{
			DMPDJFAGCPN data = new DMPDJFAGCPN();
			data.KHEKNNFCAOI(EBMHHKNDDEN[i]);
			NNDGIAEFMOG.Add(data);
		}
		return true;
	}

	// // RVA: 0x1130B30 Offset: 0x1130B30 VA: 0x1130B30
	private bool HBHAHIHFLMH(List<DMPDJFAGCPN> NNDGIAEFMOG, List<DMPDJFAGCPN> FCCKCFEEOMN, MNFBFBKBJLB[] EBMHHKNDDEN)
	{
		for(int i = 0; i < EBMHHKNDDEN.Length; i++)
		{
			DMPDJFAGCPN data1 = new DMPDJFAGCPN();
			DMPDJFAGCPN data2 = new DMPDJFAGCPN();
			data1.KHEKNNFCAOI(EBMHHKNDDEN[i]);
			NNDGIAEFMOG.Add(data1);
			data2.MNKHDMMDPKG(EBMHHKNDDEN[i]);
			FCCKCFEEOMN.Add(data2);
		}
		return true;
	}

	// // RVA: 0x1131468 Offset: 0x1131468 VA: 0x1131468
	// private bool DCMPGIJIBBB(EDOHBJAPLPF_JsonData OILEIIEIBHP, int KAPMOPMDHJE) { }

	// // RVA: 0x1130CFC Offset: 0x1130CFC VA: 0x1130CFC
	private bool DCMPGIJIBBB(GGNFFEBIPON FOLMNOOIOFM)
	{
		BDEOFCEPFMN[] array = FOLMNOOIOFM.DBIEABIPELG;
		for(int i = 0; i < array.Length; i++)
		{
			NHINPDLLFIO data = new NHINPDLLFIO();
			data.PPFNGGCBJKC_Id = array[i].PPFNGGCBJKC;
			data.JPJNKNOJBMM = array[i].ALMNMBDELDB;
			data.JBGEEPFKIGG = array[i].JBGEEPFKIGG;
			data.PPEGAKEIEGM = JKAECBCNHAN(array[i].IJEKNCDIIAE, (int)array[i].PLALNIIBLOF, 0);
			data.GMDCKJBIOGL = new List<CEBFFLDKAEC>();
			for(int j = 0; j < array[i].JFJFMFNMPPF.Length; j++)
			{
				CEBFFLDKAEC data2 = new CEBFFLDKAEC();
				data2.DNJEJEANJGL = array[i].JFJFMFNMPPF[j];
				data.GMDCKJBIOGL.Add(data2);
			}
			GJLBMELKHEM.Add(data);
		}
		return true;
	}

	// // RVA: 0x1131470 Offset: 0x1131470 VA: 0x1131470 Slot: 11
	public override uint CAOGDCBPBAN()
	{
		TodoLogger.Log(100, "CAOGDCBPBAN");
		return 0;
	}
}

public class AFIFDLOAKGI
{
	public int FBGGEFFJJHB; // 0x8
	public int PIMKKONMBOG; // 0xC
	public int MKENMKMJFKP; // 0x10
	public int BOCMGOHDKDK; // 0x14
	public int DBCAOAIFOCJ; // 0x18
	public int OANJBGBHDPJ; // 0x1C
	public List<int> IGNCGOMDGKI; // 0x20
	public List<int> IEILOCENAMF; // 0x24

	public int KIJAPOFAGPN { get { return PIMKKONMBOG ^ FBGGEFFJJHB; } set { PIMKKONMBOG = value ^ FBGGEFFJJHB; } } //0x15C2A98 GCKKKIDNACI 0x15C2AA8 OGBLMPODGBG
	public int MKPJBDFDHOL { get { return BOCMGOHDKDK ^ FBGGEFFJJHB; } set { BOCMGOHDKDK = value ^ FBGGEFFJJHB; } } //0x15C2AB8 MIDKFOPDBEJ 0x15C2AC8 IBBBHHLGEPJ
	public int INDDJNMPONH { get { return MKENMKMJFKP ^ FBGGEFFJJHB; } set { MKENMKMJFKP = value ^ FBGGEFFJJHB; } } //0x15C2AD8 GHAILOLPHPF 0x15C2AE8 BACGOKIGMBC
	public int MKNDAOHGOAK { get { return DBCAOAIFOCJ ^ FBGGEFFJJHB; } set { DBCAOAIFOCJ = value ^ FBGGEFFJJHB; } } //0x15C2AF8 MGMCJMODMAN 0x15C2B08 LOBLFMFJDEC
	public int PBIHLJKLHGJ { get { return OANJBGBHDPJ ^ FBGGEFFJJHB; } set { OANJBGBHDPJ = value ^ FBGGEFFJJHB; } } //0x15C2B18 FNBANHKHHDK 0x15C2B28 KCMBEMCKBED

	// RVA: 0x15C2B38 Offset: 0x15C2B38 VA: 0x15C2B38
	public AFIFDLOAKGI()
	{
		FBGGEFFJJHB = 0x344f4d38;
		MKNDAOHGOAK = 0;
		PBIHLJKLHGJ = 0;
		KIJAPOFAGPN = 0;
		INDDJNMPONH = 0;
		MKPJBDFDHOL = 0;
	}

	// // RVA: 0x15C2B80 Offset: 0x15C2B80 VA: 0x15C2B80
	// public void ODDIHGPONFL(AFIFDLOAKGI GPBJHKLFCEP) { }

	// // RVA: 0x15C2CA8 Offset: 0x15C2CA8 VA: 0x15C2CA8
	// public int ENNLMALGDKN() { }

	// // RVA: 0x15C2D24 Offset: 0x15C2D24 VA: 0x15C2D24
	// public int HMHJMPKLGID(int IKPIDCFOFEA) { }

	// // RVA: 0x15C2DE8 Offset: 0x15C2DE8 VA: 0x15C2DE8
	// public int EHCMOEACKFP(int IKPIDCFOFEA) { }

	// // RVA: 0x15C2EB0 Offset: 0x15C2EB0 VA: 0x15C2EB0
	// public int PKLGGJPPBAN() { }

	// // RVA: 0x15C2F2C Offset: 0x15C2F2C VA: 0x15C2F2C
	// public int DEPIOOMBGDG(int IKPIDCFOFEA) { }

	// // RVA: 0x15C2FF0 Offset: 0x15C2FF0 VA: 0x15C2FF0
	// public int BAGAEINPFNJ(int IKPIDCFOFEA) { }

	// // RVA: 0x15C30B8 Offset: 0x15C30B8 VA: 0x15C30B8
	// public uint CAOGDCBPBAN() { }
}

public class NLNDLEEJOFD
{
	public short GHPLINIACBB; // 0x8
	public short PMBEODGMMBB; // 0xA
	public short JBGEEPFKIGG; // 0xC

	// RVA: 0x1CA8674 Offset: 0x1CA8674 VA: 0x1CA8674
	// public uint CAOGDCBPBAN() { }
}

public class DMPDJFAGCPN
{
	public int PPFNGGCBJKC_Id; // 0x8
	public List<NLNDLEEJOFD> PDKGMFHIFML_Pl; // 0xC
	public List<NLNDLEEJOFD> ADPJCNHAJPC_Rd; // 0x10

	// // RVA: 0x122C2B0 Offset: 0x122C2B0 VA: 0x122C2B0
	// public bool KHEKNNFCAOI(EDOHBJAPLPF_JsonData IDLHJIOMJBK) { }

	// // RVA: 0x122C934 Offset: 0x122C934 VA: 0x122C934
	public bool KHEKNNFCAOI(AOGBEJNPKFB IDLHJIOMJBK)
	{
		PPFNGGCBJKC_Id = (int)IDLHJIOMJBK.PPFNGGCBJKC;
		PDKGMFHIFML_Pl = new List<NLNDLEEJOFD>(IDLHJIOMJBK.CFMBELIAJIB.Length);
		for(int i = 0; i < IDLHJIOMJBK.CFMBELIAJIB.Length; i+=3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 2];
			PDKGMFHIFML_Pl.Add(data);
		}
		ADPJCNHAJPC_Rd = new List<NLNDLEEJOFD>(IDLHJIOMJBK.NJGNGFNKHAH.Length);
		for (int i = 0; i < IDLHJIOMJBK.NJGNGFNKHAH.Length; i += 3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 2];
			ADPJCNHAJPC_Rd.Add(data);
		}
		return true;
	}

	// // RVA: 0x122CCB4 Offset: 0x122CCB4 VA: 0x122CCB4
	public bool KHEKNNFCAOI(MNFBFBKBJLB IDLHJIOMJBK)
	{
		PPFNGGCBJKC_Id = (int)IDLHJIOMJBK.PPFNGGCBJKC;
		PDKGMFHIFML_Pl = new List<NLNDLEEJOFD>(IDLHJIOMJBK.CFMBELIAJIB.Length);
		for (int i = 0; i < IDLHJIOMJBK.CFMBELIAJIB.Length; i += 3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 2];
			PDKGMFHIFML_Pl.Add(data);
		}
		ADPJCNHAJPC_Rd = new List<NLNDLEEJOFD>(IDLHJIOMJBK.NJGNGFNKHAH.Length);
		for (int i = 0; i < IDLHJIOMJBK.NJGNGFNKHAH.Length; i += 3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 2];
			ADPJCNHAJPC_Rd.Add(data);
		}
		return true;
	}

	// // RVA: 0x122D034 Offset: 0x122D034 VA: 0x122D034
	public bool MNKHDMMDPKG(MNFBFBKBJLB IDLHJIOMJBK)
	{
		PPFNGGCBJKC_Id = (int)IDLHJIOMJBK.PPFNGGCBJKC;
		PDKGMFHIFML_Pl = new List<NLNDLEEJOFD>(IDLHJIOMJBK.CFMBELIAJIB.Length);
		for (int i = 0; i < IDLHJIOMJBK.CFMBELIAJIB.Length; i += 3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.CFMBELIAJIB[i + 2];
			PDKGMFHIFML_Pl.Add(data);
		}
		if(PDKGMFHIFML_Pl.Count > 1)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)(PDKGMFHIFML_Pl[PDKGMFHIFML_Pl.Count - 1].GHPLINIACBB + 2);
			data.PMBEODGMMBB = PDKGMFHIFML_Pl[PDKGMFHIFML_Pl.Count - 1].PMBEODGMMBB;
			data.JBGEEPFKIGG = PDKGMFHIFML_Pl[PDKGMFHIFML_Pl.Count - 1].JBGEEPFKIGG;
			PDKGMFHIFML_Pl[PDKGMFHIFML_Pl.Count - 1].JBGEEPFKIGG = -1;
			PDKGMFHIFML_Pl.Add(data);
		}
		ADPJCNHAJPC_Rd = new List<NLNDLEEJOFD>(IDLHJIOMJBK.NJGNGFNKHAH.Length);
		for (int i = 0; i < IDLHJIOMJBK.NJGNGFNKHAH.Length; i += 3)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i];
			data.PMBEODGMMBB = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 1];
			data.JBGEEPFKIGG = (short)IDLHJIOMJBK.NJGNGFNKHAH[i + 2];
			ADPJCNHAJPC_Rd.Add(data);
		}
		if(ADPJCNHAJPC_Rd.Count > 1)
		{
			NLNDLEEJOFD data = new NLNDLEEJOFD();
			data.GHPLINIACBB = (short)(ADPJCNHAJPC_Rd[ADPJCNHAJPC_Rd.Count - 1].GHPLINIACBB + 2);
			data.PMBEODGMMBB = ADPJCNHAJPC_Rd[ADPJCNHAJPC_Rd.Count - 1].PMBEODGMMBB;
			data.JBGEEPFKIGG = ADPJCNHAJPC_Rd[ADPJCNHAJPC_Rd.Count - 1].JBGEEPFKIGG;
			ADPJCNHAJPC_Rd.Add(data);
		}
		return true;
	}

	// // RVA: 0x122D60C Offset: 0x122D60C VA: 0x122D60C
	// public uint CAOGDCBPBAN() { }
}

public class NHINPDLLFIO
{
	public int FBGGEFFJJHB; // 0x8
	public int OIFAFKDMEEJ; // 0xC
	private int EHOIENNDEDH; // 0x10
	private int GALOFABOMPJ; // 0x14
	private int ICKOHEDLEFP; // 0x18
	public List<CEBFFLDKAEC> GMDCKJBIOGL; // 0x1C

	public int PPEGAKEIEGM { get { return OIFAFKDMEEJ ^ FBGGEFFJJHB; } set { OIFAFKDMEEJ = value ^ FBGGEFFJJHB; } } //0x1890F04 KPOEEPIMMJP 0x1890F14 NCIEAFEDPBH
	public int PPFNGGCBJKC_Id { get { return EHOIENNDEDH ^ FBGGEFFJJHB; } set { EHOIENNDEDH = value ^ FBGGEFFJJHB; } } //0x1890F24 DEMEPMAEJOO 0x1890F34 HIGKAIDMOKN
	public int JPJNKNOJBMM { get { return GALOFABOMPJ ^ FBGGEFFJJHB; } set { GALOFABOMPJ = value ^ FBGGEFFJJHB; } } //0x1890F44 PNLGBGONPND 0x1890F54 BPMONMAGICM
	public int JBGEEPFKIGG { get { return ICKOHEDLEFP ^ FBGGEFFJJHB; } set { ICKOHEDLEFP = value ^ FBGGEFFJJHB; } } //0x1890F64 OLOCMINKGON 0x1890F74 ABAFHIBFKCE

	// RVA: 0x1890F84 Offset: 0x1890F84 VA: 0x1890F84
	public NHINPDLLFIO()
	{
		ICKOHEDLEFP = LPDNKHAIOLH.CEIBAFOCNCA();
		GMDCKJBIOGL = null;
		FBGGEFFJJHB = 0;
		OIFAFKDMEEJ = 0;
		EHOIENNDEDH = 0;
		GALOFABOMPJ = 0;
	}

	// // RVA: 0x1891028 Offset: 0x1891028 VA: 0x1891028
	// public int JJMEIHLNPDI(int FJFCNGNGIBN, int JPIPENJGGDD) { }

	// // RVA: 0x1891130 Offset: 0x1891130 VA: 0x1891130
	// public uint CAOGDCBPBAN() { }
}
