using System.Collections.Generic;

public class NDBFKHKMMCE : DIHHCBACKGG
{
	public class EHLEEEBJLAM
	{
		private int FBGGEFFJJHB; // 0x8
		private long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int GNGNIKNNCNH; // 0x1C
		private int HNJHPNPFAAN; // 0x20
		private int BGALCJHAFPF; // 0x24
		private int IPAKEGGICML; // 0x28
		private int EAJCFBCHIFB; // 0x2C
		private int MMDBOPCEKCJ; // 0x30
		private int HJCJMAONOMH; // 0x34
		private int HAIFEBPOPEF; // 0x38
		private int JFLBJEOOAMH; // 0x3C

		// public int PPFNGGCBJKC_Id { get; set; } 0x1AE28F0 DEMEPMAEJOO 0x1AE1178 HIGKAIDMOKN
		// public int IJEKNCDIIAE { get; set; } 0x1AE2900 KJIMMIBDCIL 0x1AE1188 DMEGNOKIKCD
		// public int PLALNIIBLOF { get; set; } 0x1ADE084 JPCJNLHHIPE 0x1AE1198 JJFJNEJLBDG
		// public int FJFCNGNGIBN { get; set; } 0x1AE2910 OCNDKILHCJK 0x1AE11A8 NMEEPJEFADN
		// public int CPKMLLNADLJ { get; set; } 0x1AE2920 BJPJMGHCDNO 0x1AE11B8 BPKIOJBKNBP
		// public int EKLIPGELKCL { get; set; } 0x1AE2930 OEEHBGECGKL 0x1AE11C8 GHLMHLJJBIG
		// public int MLMCEBBDJOE { get; set; } 0x1AE2940 IGMHCODOFKG 0x1AE11F8 IIIGDLGGEGK
		// public int ODNILEDOAIP { get; set; } 0x1AE2950 GNKPMBBAJHI 0x1AE11E8 PPMACIMALAC
		// public int NPPGKNGIFGK { get; set; } 0x1AE2960 FLMDBAFHDNJ 0x1AE11D8 DIHIEJPOCOJ
		// public int EBIMFANOGBK { get; set; } 0x1AE2970 CLJNHJFLOPF 0x1ADEDEC PBOCBEONGKG

		// RVA: 0x1AE10C0 Offset: 0x1AE10C0 VA: 0x1AE10C0
		public EHLEEEBJLAM()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			HAIFEBPOPEF = FBGGEFFJJHB;
			JFLBJEOOAMH = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			EHOIENNDEDH = 0;
			GNGNIKNNCNH = 0;
			HNJHPNPFAAN = 0;
			BGALCJHAFPF = 0;
			IPAKEGGICML = 0;
			EAJCFBCHIFB = 0;
			MMDBOPCEKCJ = 0;
			HJCJMAONOMH = 0;
		}

		// RVA: 0x1AE1FC8 Offset: 0x1AE1FC8 VA: 0x1AE1FC8
		// public uint CAOGDCBPBAN() { }
	}

	public class NIBEBIGPKLA
	{
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int GNGNIKNNCNH; // 0x1C
		private int HNJHPNPFAAN; // 0x20
		private int NOFECLGOLAI; // 0x24
		private int BGALCJHAFPF; // 0x28
		private int IPAKEGGICML; // 0x2C
		private int EAJCFBCHIFB; // 0x30
		private int IGBOGLAJCAO; // 0x34
		private int ILEIBLFHMEI; // 0x38
		private int CFONNKENNJH; // 0x3C
		private int CCACGHNJNOF; // 0x40
		private int FMCEHHAICJE; // 0x44
		private int HJKNAPMLBFG; // 0x48
		private int HHPFFPINGAA; // 0x4C
		private int MMDBOPCEKCJ; // 0x50
		private int HJCJMAONOMH; // 0x54
		private int HAIFEBPOPEF; // 0x58
		private int GJFLAHAGDKG; // 0x5C
		private int JFLBJEOOAMH; // 0x60

		// public int PPFNGGCBJKC_Id { get; set; } 0x1AE2AD0 DEMEPMAEJOO 0x1AE12D4 HIGKAIDMOKN
		// public int IJEKNCDIIAE { get; set; } 0x1AE2838 KJIMMIBDCIL 0x1AE12E4 DMEGNOKIKCD
		// public int PLALNIIBLOF { get; set; } 0x1ADE648 JPCJNLHHIPE 0x1AE12F4 JJFJNEJLBDG
		// public int GBJFNGCDKPM { get; set; } 0x1AE2828 CEJJMKODOGK 0x1AE1304 HOHCEBMMACI
		// public int FJFCNGNGIBN { get; set; } 0x1AE2AE0 OCNDKILHCJK 0x1AE1314 NMEEPJEFADN
		// public int CPKMLLNADLJ { get; set; } 0x1AE2AF0 BJPJMGHCDNO 0x1AE1324 BPKIOJBKNBP
		// public int EKLIPGELKCL { get; set; } 0x1AE2B00 OEEHBGECGKL 0x1AE1334 GHLMHLJJBIG
		// public int FAKNMCIIAEM { get; set; } 0x1AE2B10 CGDPJCABPDB 0x1AE1344 JJFPNFCDNIC
		// public int KPECMLFDLOI { get; set; } 0x1AE2B20 ILFJIGDCGBK 0x1AE1354 DOGEFDDMBDM
		// public int NGILPOOLBCF { get; set; }	0x1AE2B30 EDGHLAHGBFN 0x1AE1364 LFCKFNLGFCN
		// public int JINEKNIBOFI { get; set; } 0x1AE2B40 LKDHAPEGCPH 0x1AE1374 PBPDONPMGNF
		// public int BHDHPCDLICO { get; set; } 0x1AE2B50 AHKMMIGMMHJ 0x1AE1384 CHFCMEBBCOG
		// public int CMMNFCJNIOO { get; set; } 0x1AE2B60 IPBHOIGBNEO 0x1AE1394 EACBGCGAKLO
		// public int EILKGEADKGH { get; set; } 0x1AE2B70 NPDDACIHBKD 0x1AE13A4 BJJMCKHBPNH
		// public int MLMCEBBDJOE { get; set; } 0x1AE2B80 IGMHCODOFKG 0x1AE13B4 IIIGDLGGEGK
		// public int ODNILEDOAIP { get; set; } 0x1AE2B90 GNKPMBBAJHI 0x1AE13C4 PPMACIMALAC
		// public int NPPGKNGIFGK { get; set; } 0x1AE2BA0 FLMDBAFHDNJ 0x1AE13D4 DIHIEJPOCOJ
		// public int KEJMJPHFFOJ { get; set; } 0x1AE2BB0 FMNMLNIALNE 0x1AE13E4 GBEPCBPOGDB
		// public int EBIMFANOGBK { get; set; } 0x1AE2BC0 CLJNHJFLOPF 0x1ADEDFC PBOCBEONGKG

		// RVA: 0x1AE1208 Offset: 0x1AE1208 VA: 0x1AE1208
		public NIBEBIGPKLA()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			HJCJMAONOMH = FBGGEFFJJHB;
			HHPFFPINGAA = FBGGEFFJJHB;
			JFLBJEOOAMH = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			EHOIENNDEDH = 0;
			GNGNIKNNCNH = 0;
			HNJHPNPFAAN = 0;
			NOFECLGOLAI = 0;
			BGALCJHAFPF = 0;
			IPAKEGGICML = 0;
			EAJCFBCHIFB = 0;
			IGBOGLAJCAO = 0;
			ILEIBLFHMEI = 0;
			CFONNKENNJH = 0;
			CCACGHNJNOF = 0;
			FMCEHHAICJE = 0;
			HJKNAPMLBFG = 0;
			MMDBOPCEKCJ = 0;
			HAIFEBPOPEF = 0;
			GJFLAHAGDKG = 0;
		}

		// RVA: 0x1AE2028 Offset: 0x1AE2028 VA: 0x1AE2028
		// public uint CAOGDCBPBAN() { }
	}

	public class FIDBAFHNGCF : NIBEBIGPKLA
	{
		private int HNNLOMMFHEN; // 0x64
		private int PIMKKONMBOG; // 0x68
		private int CGDIOPJFHHD; // 0x6C

		// public int DMEDKJPOLCH { get; set; } 0x1AE2980 IPKCKAAEEOE 0x1AE1438 JOGLLINFLJN
		// public int KIJAPOFAGPN { get; set; }  0x1AE2990 GCKKKIDNACI 0x1AE1418 OGBLMPODGBG
		// public int ADECCOKCCDH { get; set; } 0x1AE29A0 GCFCECGJAJF 0x1AE1428 GJBMKGFMOFF

		// RVA: 0x1AE13F4 Offset: 0x1AE13F4 VA: 0x1AE13F4
		public FIDBAFHNGCF()
		{
			HNNLOMMFHEN = FBGGEFFJJHB;
			PIMKKONMBOG = FBGGEFFJJHB;
			CGDIOPJFHHD = FBGGEFFJJHB;
		}

		// RVA: 0x1AE20F8 Offset: 0x1AE20F8 VA: 0x1AE20F8
		// public uint CAOGDCBPBAN() { }
	}

	public class PELPLGBMOII
	{
		private int FBGGEFFJJHB; // 0x8
		private long BBEGLBMOBOF; // 0x10
		public CEBFFLDKAEC[] IPGHEIAFCHE = new CEBFFLDKAEC[10]; // 0x18
		public CEBFFLDKAEC[] MILFOEODPDK = new CEBFFLDKAEC[10]; // 0x1C
		private int EHOIENNDEDH; // 0x20
		private int IBNLAGGBLDH; // 0x24

		// public int PPFNGGCBJKC_Id { get; set; } 0x1AE2C44 DEMEPMAEJOO 0x1AE16E8 HIGKAIDMOKN
		// public int AGHJAAMABPI { get; set; } 0x1AE2C54 IICGAHBLHFJ 0x1AE16F8 OJOFJPLDCNB

		// RVA: 0x1AE1448 Offset: 0x1AE1448 VA: 0x1AE1448
		public PELPLGBMOII()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			EHOIENNDEDH = FBGGEFFJJHB;
			IBNLAGGBLDH = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			for(int i = 0; i < 10; i++)
			{
				CEBFFLDKAEC data = new CEBFFLDKAEC();
				IPGHEIAFCHE[i] = data;
				data.DNJEJEANJGL = 0;

				data = new CEBFFLDKAEC();
				MILFOEODPDK[i] = data;
				data.DNJEJEANJGL = 0;
			}
		}

		// RVA: 0x1AE2130 Offset: 0x1AE2130 VA: 0x1AE2130
		// public uint CAOGDCBPBAN() { }
	}

	public class IEOEMNPLANK
	{
		private int FBGGEFFJJHB; // 0x8
		private long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int GNGNIKNNCNH; // 0x1C
		private int HNJHPNPFAAN; // 0x20
		private int IPAKEGGICML; // 0x24
		private int EAJCFBCHIFB; // 0x28
		private int MMDBOPCEKCJ; // 0x2C
		private int HJCJMAONOMH; // 0x30
		private int HAIFEBPOPEF; // 0x34
		private int GJFLAHAGDKG; // 0x38
		private int JFLBJEOOAMH; // 0x3C

		// public int PPFNGGCBJKC_Id { get; set; } 0x1AE2A40 DEMEPMAEJOO 0x1AE17C0 HIGKAIDMOKN
		// public int IJEKNCDIIAE { get; set; } 0x1AE2A50 KJIMMIBDCIL 0x1AE17D0 DMEGNOKIKCD
		// public int PLALNIIBLOF { get; set; } 0x1ADE658 JPCJNLHHIPE 0x1AE17E0 JJFJNEJLBDG
		// public int CPKMLLNADLJ { get; set; } 0x1AE2A60 BJPJMGHCDNO 0x1AE17F0 BPKIOJBKNBP
		// public int EKLIPGELKCL { get; set; } 0x1AE2A70 OEEHBGECGKL 0x1AE1800 GHLMHLJJBIG
		// public int MLMCEBBDJOE { get; set; } 0x1AE2A80 IGMHCODOFKG 0x1AE1810 IIIGDLGGEGK
		// public int ODNILEDOAIP { get; set; } 0x1AE2A90 GNKPMBBAJHI 0x1AE1820 PPMACIMALAC
		// public int NPPGKNGIFGK { get; set; } 0x1AE2AA0 FLMDBAFHDNJ 0x1AE1830 DIHIEJPOCOJ
		// public int KEJMJPHFFOJ { get; set; } 0x1AE2AB0 FMNMLNIALNE 0x1AE1840 GBEPCBPOGDB
		// public int EBIMFANOGBK { get; set; } 0x1AE2AC0 CLJNHJFLOPF 0x1ADEE1C PBOCBEONGKG

		// RVA: 0x1AE1708 Offset: 0x1AE1708 VA: 0x1AE1708
		public IEOEMNPLANK()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			GJFLAHAGDKG = FBGGEFFJJHB;
			JFLBJEOOAMH = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			EHOIENNDEDH = 0;
			HNJHPNPFAAN = 0;
			EAJCFBCHIFB = 0;
			HJCJMAONOMH = 0;
		}

		// RVA: 0x1AE2218 Offset: 0x1AE2218 VA: 0x1AE2218
		// public uint CAOGDCBPBAN() { }
	}

	public class CCHHGIJMLBN
	{
		private int FBGGEFFJJHB; // 0x8
		private long BBEGLBMOBOF; // 0x10
		public CEBFFLDKAEC[] KPIBEAHCGOB = new CEBFFLDKAEC[5]; // 0x18
		private int EHOIENNDEDH; // 0x1C
		private int GNGNIKNNCNH; // 0x20
		private int HNJHPNPFAAN; // 0x24
		private int KGKIDDDKOGL; // 0x28
		private int NOFECLGOLAI; // 0x2C
		private int IPAKEGGICML; // 0x30
		private int EAJCFBCHIFB; // 0x34
		private int MMDBOPCEKCJ; // 0x38
		private int HJCJMAONOMH; // 0x3C
		private int HAIFEBPOPEF; // 0x40
		private int JFLBJEOOAMH; // 0x44

		// public int PPFNGGCBJKC_Id { get; set; } 0x1AE2850 DEMEPMAEJOO 0x1AE1A14 HIGKAIDMOKN
		// public int IJEKNCDIIAE { get; set; } 0x1AE2860 KJIMMIBDCIL 0x1AE1A24 DMEGNOKIKCD
		// public int PLALNIIBLOF { get; set; } 0x1ADE638 JPCJNLHHIPE 0x1AE1A34 JJFJNEJLBDG
		// public int JBFLEDKDFCO { get; set; } 0x1AE2870 LIJMKJLDHGP 0x1AE1A44 NFNCLFPPADP
		// public int GBJFNGCDKPM { get; set; } 0x1AE2880 CEJJMKODOGK 0x1AE1A54 HOHCEBMMACI
		// public int CPKMLLNADLJ { get; set; } 0x1AE2890 BJPJMGHCDNO 0x1AE1A64 BPKIOJBKNBP
		// public int EKLIPGELKCL { get; set; } 0x1AE28A0 OEEHBGECGKL 0x1AE1A74 GHLMHLJJBIG
		// public int MLMCEBBDJOE { get; set; } 0x1AE28B0 IGMHCODOFKG 0x1AE1A84 IIIGDLGGEGK
		// public int ODNILEDOAIP { get; set; } 0x1AE28C0 GNKPMBBAJHI 0x1AE1A94 PPMACIMALAC
		// public int NPPGKNGIFGK { get; set; } 0x1AE28D0 FLMDBAFHDNJ 0x1AE1AA4 DIHIEJPOCOJ
		// public int EBIMFANOGBK { get; set; } 0x1AE28E0 CLJNHJFLOPF 0x1ADEE0C PBOCBEONGKG

		// RVA: 0x1AE1850 Offset: 0x1AE1850 VA: 0x1AE1850
		public CCHHGIJMLBN()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			HJCJMAONOMH = FBGGEFFJJHB;
			HAIFEBPOPEF = FBGGEFFJJHB;
			JFLBJEOOAMH = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			EHOIENNDEDH = 0;
			HNJHPNPFAAN = 0;
			NOFECLGOLAI = 0;
			EAJCFBCHIFB = 0;
			for(int i = 0; i < 5; i++)
			{
				CEBFFLDKAEC data = new CEBFFLDKAEC();
				KPIBEAHCGOB[i] = data;
				data.DNJEJEANJGL = 0;
			}
		}

		// RVA: 0x1AE2278 Offset: 0x1AE2278 VA: 0x1AE2278
		// public uint CAOGDCBPBAN() { }
	}

	public class NNCIBDMDEFE
	{
		private int FBGGEFFJJHB; // 0x8
		private long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int EMKPFNEJOAB; // 0x1C
		private long PCLNFCNIECH; // 0x20
		private long HHPIJHADAOB; // 0x28
		private int OIFAFKDMEEJ; // 0x30

		// public int MDLEEKBBEKD { get; set; } 0x1AE2BD0 ODPALPLOPNN 0x1AE1B68 FJJOKFJJHME
		// public int EFNKCPBALOP { get; set; } 0x1AE2BE0 HAIPHNPDPIP 0x1AE1B88 DBJFAEOKOEK
		// public long NMELNJNFMJF { get; set; } 0x1AE2BF0 KPCNKFFKELH 0x1AE1B98 BEMLPMCBHEA
		// public long IAJAOIEOPDP { get; set; } 0x1AE2C04 GEFNJEHLBAL 0x1AE1BB8 IGAAEBAFAHB
		// public int PPEGAKEIEGM { get; set; } 0x1AE1BD8 KPOEEPIMMJP 0x1AE1B78 NCIEAFEDPBH

		// RVA: 0x1AE1AB4 Offset: 0x1AE1AB4 VA: 0x1AE1AB4
		public NNCIBDMDEFE()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			EMKPFNEJOAB = FBGGEFFJJHB;
			BBEGLBMOBOF = -FBGGEFFJJHB;
			PCLNFCNIECH = FBGGEFFJJHB;
			HHPIJHADAOB = FBGGEFFJJHB;
		}

		// RVA: 0x1AE2C18 Offset: 0x1AE2C18 VA: 0x1AE2C18
		// public uint CAOGDCBPBAN() { }
	}

	// public const int NLDKJMCFECI = 200;
	// public const int LNNEEPBINDO = 6000;
	// public const int IKMLLLANDNO = 100;
	// public const int HEGFNNDPKJI = 50;
	// public const int NOMAGGDHCCC = 100;
	// public const int JGDONEBKCHM = 5;
	// public const int OKKOJBACFHH = 10;
	public List<NDBFKHKMMCE.EHLEEEBJLAM> GJLHEJPHEDA = new List<NDBFKHKMMCE.EHLEEEBJLAM>(); // 0x20
	public List<NDBFKHKMMCE.NIBEBIGPKLA> GHOLIPLDMPJ = new List<NDBFKHKMMCE.NIBEBIGPKLA>(); // 0x24
	public List<NDBFKHKMMCE.FIDBAFHNGCF> GMONECJCJFK = new List<NDBFKHKMMCE.FIDBAFHNGCF>(); // 0x28
	public List<NDBFKHKMMCE.PELPLGBMOII> ONODAPNHMPB = new List<NDBFKHKMMCE.PELPLGBMOII>(); // 0x2C
	public List<NDBFKHKMMCE.IEOEMNPLANK> COLIEKINOPB = new List<NDBFKHKMMCE.IEOEMNPLANK>(); // 0x30
	public List<NDBFKHKMMCE.CCHHGIJMLBN> KHCACDIKJLG = new List<NDBFKHKMMCE.CCHHGIJMLBN>(); // 0x34
	public List<NDBFKHKMMCE.NNCIBDMDEFE> JDMCHNFAOFO = new List<NDBFKHKMMCE.NNCIBDMDEFE>(); // 0x38

	public Dictionary<string, NNJFKLBPBNK> FJOEBCMGDMI { get; private set; } // 0x3C IHKPIFIBECO GAMGELHIHHI DDDEJIJGGBJ
	public Dictionary<string, CEBFFLDKAEC> OHJFBLFELNK { get; private set; } // 0x40 KLDCHOIPJGB AEMNOGNEBOJ DGKDBOAMNBB

	// // RVA: 0x1ADDEF8 Offset: 0x1ADDEF8 VA: 0x1ADDEF8
	// public bool KOPLBMLHKCD(int GLCLFMGPMAN) { }

	// // RVA: 0x1ADE094 Offset: 0x1ADE094 VA: 0x1ADE094
	// public bool FMGPOKFKPIJ(OKGLGHCBCJP NDFIEMPPMLF, int GLCLFMGPMAN) { }

	// // RVA: 0x1ADE668 Offset: 0x1ADE668 VA: 0x1ADE668
	// public string EFEGBHACJAL(string LJNAKDMILMC, string KKMJBMKHGNH) { }

	// // RVA: 0x1ADE74C Offset: 0x1ADE74C VA: 0x1ADE74C
	// public int LPJLEHAJADA(string LJNAKDMILMC, int KKMJBMKHGNH) { }

	// // RVA: 0x1ADE830 Offset: 0x1ADE830 VA: 0x1ADE830
	// public bool GMKNPOJDIPP(string LJNAKDMILMC, out int NANNGLGOFKH) { }

	// // RVA: 0x1ADE920 Offset: 0x1ADE920 VA: 0x1ADE920
	public void MFIAFCCJHOF(BBLECJKKKLA MJALLIOHKEJ)
	{
        UnityEngine.Debug.LogError("TODO  DB Init");
	}

	// // RVA: 0x1ADEE2C Offset: 0x1ADEE2C VA: 0x1ADEE2C
	public NDBFKHKMMCE()
    {
		JIKKNHIAEKG = "";
		OHJFBLFELNK = new Dictionary<string, CEBFFLDKAEC>();
		LNIMEIMBCMF = false;
		LMHMIIKCGPE = 13;
		FJOEBCMGDMI = new Dictionary<string, NNJFKLBPBNK>();
    }

	// // RVA: 0x1ADF0C0 Offset: 0x1ADF0C0 VA: 0x1ADF0C0 Slot: 8
	protected override void KMBPACJNEOF()
    {
		GJLHEJPHEDA.Clear();
		GHOLIPLDMPJ.Clear();
		GMONECJCJFK.Clear();
		ONODAPNHMPB.Clear();
		COLIEKINOPB.Clear();
		KHCACDIKJLG.Clear();
		JDMCHNFAOFO.Clear();
		OHJFBLFELNK.Clear();
		FJOEBCMGDMI.Clear();
    }

	// // RVA: 0x1ADF298 Offset: 0x1ADF298 VA: 0x1ADF298 Slot: 9
	public override bool IIEMACPEEBJ(byte[] DBBGALAPFGC)
    {
        UnityEngine.Debug.LogError("TODO Database Load");
		return true;
    }

	// // RVA: 0x1ADF5B4 Offset: 0x1ADF5B4 VA: 0x1ADF5B4
	// private bool MPPKBPADFBE(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1ADF91C Offset: 0x1ADF91C VA: 0x1ADF91C
	// private bool DGJJPDCFKKM(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1ADFE3C Offset: 0x1ADFE3C VA: 0x1ADFE3C
	// private bool FEEHPPNFAHP(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1AE0308 Offset: 0x1AE0308 VA: 0x1AE0308
	// private bool GPJFKMCOAAL(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1AE0638 Offset: 0x1AE0638 VA: 0x1AE0638
	// private bool GPNIEKBBIII(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1AE09A0 Offset: 0x1AE09A0 VA: 0x1AE09A0
	// private bool OGIAJJLNKNE(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1AE0E00 Offset: 0x1AE0E00 VA: 0x1AE0E00
	// private bool BFLDLDCDFIC(NLFIKMMPOAL AJLPJINDCBI) { }

	// // RVA: 0x1AE1BE8 Offset: 0x1AE1BE8 VA: 0x1AE1BE8 Slot: 10
	public override bool IIEMACPEEBJ(EDOHBJAPLPF_JsonData OILEIIEIBHP, int KAPMOPMDHJE)
	{
		UnityEngine.Debug.LogError("TODO");
		return true;
	}

	// // RVA: 0x1AE1BF0 Offset: 0x1AE1BF0 VA: 0x1AE1BF0 Slot: 11
	public override uint CAOGDCBPBAN()
	{
		UnityEngine.Debug.LogError("TODO CAOGDCBPBAN");
		return 0;
	}

	// // RVA: 0x1AE2358 Offset: 0x1AE2358 VA: 0x1AE2358
	// public int KDFMGDNOMHE(OKGLGHCBCJP LKMHPJKIFDN, BBHNACPENDM LDEGEHAEALK, int NCLLKNJBEKI) { }

	// // RVA: 0x1AE2738 Offset: 0x1AE2738 VA: 0x1AE2738
	// public int CHMNDNFMAGA(int BIEGNEGKLDE) { }
}
