using UnityEngine;
using System.Collections.Generic;

public class OKGLGHCBCJP_Database
{
	public enum BEOKNKGHFFE
	{
		LIIJEGOIKDP = 0,
		MLNHHIIDJAO = 1,
		PICOGHJNOJA = 2,
		DBBOBIHPDNA = 3,
		PEIFIFLMIIF = 4,
		JOMAMMACANH = 5,
		DHMPHBPODCI = 6,
		DGPIFKCLAGB = 7,
		EFHFNMAIEJG = 8,
		LOFOAIEMECN = 9,
		LHFCAMJHMLB = 10,
		BGMIHMDPDCM = 11,
		DBILOJAEIOO = 12,
		DLFGIKANBDK = 13,
		PLJHAFGEGEB = 14,
		DHMEFNNJANH = 15,
		CNENKCCMEFL = 16,
		ACGFJFNPLKB = 17,
		PKDKLHJLEFA = 18,
		PGHFPIMIOKE = 19,
		CNGPLGIMJBB = 20,
		JBFFIPCOGEC = 21,
		BBDKHAMANCB = 22,
		MIOOJINHHFO = 23,
		OBEAIJOHOAJ = 24,
		GCEPOPPDPOC = 25,
		EMOOIGBGHLG = 26,
		AEGNEIOAOKI = 27,
		KNNGKODFAGC = 28,
		AFGGHHOHILP = 29,
		EICBLKBKMKE = 30,
		FIKPHDFLIIM = 31,
		FNLCLINDJAF = 32,
		IEICONEHLFE = 33,
		CJLAEPKNNJE = 34,
		MPCNKNCKBAE = 35,
		COFHBPGDPML = 36,
		BHJGBPLKMBK = 37,
		AHDKIFOPEHM = 38,
		LLEDCLGDDCD = 39,
		ACNPHHGCHAF = 40,
		FEICGBHOIPB = 41,
		OAOKLHCDPON = 42,
		GGKFEJFMNGP = 43,
		LLHBBEMKIGD = 44,
		HJDJGMNAJFJ = 45,
		MBMNNEODFFP = 46,
		NLIBPDOHAPH = 47,
		JLGODHLEBMK = 48,
		OFAAHIINGFD = 49,
		OFGFNFAJHFE = 50,
		DCBIDPBJHOC = 51,
		BNCLLKEHEFH = 52,
		BDGKKLAAJJB = 53,
		CLKOFJKPPEP = 54,
		DCEHHGDDBPP = 55,
		PLNOKLOLJEP = 56,
		IJEIEHHAJNM = 57,
		DMKFEJGOELJ = 58,
		IEBPINPALBD = 59,
		CHNHFHCEKGN = 60,
		FCAJCEOCDFF = 61,
		IJOLIEAOOJC = 62,
		MDAEJLJPIHN = 63,
		OJAHCPGNPDB = 64,
		KGJMEGLKJDM = 65,
		LNBMDELKFHI = 66,
		FMHLCBNFAOC = 67,
		LCJACACCKFC = 68,
		BPOFGIDPMBF = 69,
		JPNKKKOHHLG = 70,
		ECHHEGJOHGI = 71,
		NLDGAHCIPAE = 72,
		MHGPKDOPEDJ = 73,
		AMGKNGLDHMG = 74,
		BKEKCFONNBG = 75,
		JLNNFLCLGBM = 76,
		MHNJLGONIPK = 77,
		FPFHPCDNIDN = 78,
		OJFINMGAFPG = 79,
		HJBCLCJIAMN = 80,
		JOMKJEEEGLM = 81,
		MGLIHABHABA = 82,
		JHIAPFBBCCJ = 83,
		FLANCIJMJHP = 84,
		BKGFKGIGJNL = 85,
		NLIJGKHKMII = 86,
		CLAMLDCILJO = 87,
		FONDIJMKCAJ = 88,
		KPBNAHEIJIC = 89,
		ECEDGCHFCEF = 90,
		HOBIIBFBMKJ = 91,
		CHOGKKCHBCJ = 92,
		JMJMNDKFOIF = 93,
		LNCIOFKDBHD = 94,
		GPEFCGBGIHD = 95,
		JFDOPKICHPJ = 96,
		HDJDAENLIBF = 97,
		KOALKJHIHFC = 98,
		KNMIJOPCJCH = 99,
		ELBGPMIFOHO = 100,
		ABANJLALLBK = 101,
		HGOGFPOCKFA = 102,
		LCEEHPPLHNC = 103,
		AOPBBHMIEPB = 104,
		HGFDKEMHGHK = 105,
		ACECCMLEDMO = 106,
		HDDBEGLGIDK = 107,
		EMHPGEHBKPG = 108,
		JJMBJBFKJHK = 109,
		EKLPMPHCIDL = 110,
		OPHNLHMINEO = 111,
		NPLKLHDPLEO = 112,
		EEPIDKPPLJI = 113,
		LJKEOODGGJF = 114,
		NPOPGPFPLOL = 115,
		AHKEJPLNAJK = 116,
		CGKOFIKBMMI = 117,

	}

	public delegate void BIFFPAKDHJJ();

	public static BEOKNKGHFFE[] GAAEFILMAED; // 0x0
	public static readonly string[] IJBLEJOKEFH; // 0x4
	public List<OKGLGHCBCJP_Database.BEOKNKGHFFE> NDLAAACJOLP = new List<OKGLGHCBCJP_Database.BEOKNKGHFFE>(); // 0x8
	public string[] IIILDINMAKI = new string[117]; // 0xC
	public long[] GJFPFFBAKGK = new long[117]; // 0x10

	// private List<DIHHCBACKGG> MGJKEJHEBPO; // 0x130
	//private static Dictionary<int, OKGLGHCBCJP.BIFFPAKDHJJ> BGEJFKHOMOC; // 0x8

	// public GPMHOAKFALE EFMAIKAHFEK { get; private set; } // 0x14 JLLBGAHIIBG LLCFMAELHEP IEBCIAFOBIN
	// public IPJBAPLFECP OILKBADFBOK { get; private set; } // 0x18 PMEPLHGCOPN ACKDFMAHCPG IKNMGMOEIBJ
	// public LFPJCEMANCK IELDDHJMFKN { get; private set; } // 0x1C POIPNMNLPII LDEGIHHDKIM OPKDGNFPLMJ
	// public JKICPBIIHNE FPOIPGFFAPE { get; private set; } // 0x20 IGDEDAEJHHE DGFJAPEKHFO GNMGEPPDCKA
	public KOGHKIODHPA JEMMMJEJLNL { get; private set; } // 0x24 JCNENMIJKJM LEOMPFKGIDH OJLDODJNICJ
	// public HHJHIFJIKAC NBKNAAPBFFL { get; private set; } // 0x28 DPLHDEEFDJM ADJIKEFIPJA JNIKDFJOHFA
	// public AIPOFGJGPKI NGCCGLLLDIB { get; private set; } // 0x2C AKMEDCJEFIM ONFFEFOLNJA KHNFCNCCAJE
	// public HHPEMHHCKBE ALFKMKICDPP { get; private set; } // 0x30 EGAMKFEHKOH OFKPEOKIBOP FBMPHCEEOGP
	// public PLPBJOFICEJ GOGFKAECFIP { get; private set; } // 0x34 MFAKBNOPMAL ONAJMJDFKII OKGBJKKKBJK
	public LCLCCHLDNHJ MFPNGNMFEAL { get; private set; } // 0x38 BNPFDJNHBIN BHOKMJJHOOK PCDDICJFIEI
	public NDBFKHKMMCE EPAHOAKPAJJ { get; private set; } // 0x3C LKAKMHGBHKJ JHPEPALKAMJ BHEAGEGHAJB
	// public JEPMHCPBIGD CIGBHCHOPEO { get; private set; } // 0x40 BONFHNBALOL GNIGMPDFEPP LFDFGOBDAMF
	// public GAEBMAEDNAN PJGDIJPCHAK { get; private set; } // 0x44 JCDPLJOOJLG CMDIEHHIFOK CMJFJNNDFJJ
	public BBLECJKKKLA MJALLIOHKEJ { get; private set; } // 0x48 ABEMGBAJEBL BABMGOIFCOH GIIEMCFFDBD
	// public NEGELNMPEPH BGKKOOGPEFD { get; private set; } // 0x4C AAPCGHFOHFC BALCOIHEDMF BKGBCKMOMGN
	// public IHFIAFDLAAK GAPONCJOKAC { get; private set; } // 0x50 NCNFBFCCPGG OJGMINMADBB NEPJLJDPKKN
	public HPBPIOPPDCB MGFMPKLLGHE { get; private set; } // 0x54 ONCMJNDIMPD // ODGINDHEIBJ GIFOPLEGJCI
	// public HMIJOOPHJLB OAINIGNLJKC { get; private set; } // 0x58 EFGHBGKGCDI KNBBENGMPJL MAPJOGCOBCF
	// public NBPHJDCOECH HGLIIPFLMFB { get; private set; } // 0x5C DNBKBMJEDFG GEHKLFKNGDK DAEJHNBAAHD
	// public IHGBPAJMJFK LBNBNAFGMDE { get; private set; } // 0x60 DOKBBBOMOIP AEKIOLPFPCO PMEOIDAFOLD
	// public MHDFCLCMDKO OPFBEAJJMJB { get; private set; } // 0x64 DMKMEHGHLAL EDGAJGHMGOK AIBFBDMGEAL
	// public JKDKODAPGBJ KOPOGNLKAEN { get; private set; } // 0x68 DACOHEDKLPD AEOJDBAPOEN PABHKGHLLLJ
	// public KIICLPJJBNL NEGGMILDEEF { get; private set; } // 0x6C EEAPHFKEOOP EPDABADJFBH CFGCGOGNBMM
	// public KMOGDEOKHPG MOLEPBNJAGE { get; private set; } // 0x70 PKELMNGHNJI GJAGLJAIAGC ECGGGFGFEOH
	// public JNGINLMOJKH NKOKFIMNCJM { get; private set; } // 0x74 OOLBNNCGINP CHGCEALBNFF BDBOOJDGKFP
	// public JPJGOECJFEE EFHMLHKODOD { get; private set; } // 0x78 KAOFKMKMDPH PAGHOGPONBK AODLPJLNDBK
	// public HGLPLKKBBOL DHOFNBMPBAG { get; private set; } // 0x7C HLPDMEMHECG ILMEKLNLPND HMDGNIKNDKM
	// public NKBOMKGFGIO ONOJBMDKBLE { get; private set; } // 0x80 OLLFECMFKIC JOKCENNIGCE IJCDMHJCMBO
	// public ABBOEIPOBLJ KHPOJKHKLEM { get; private set; } // 0x84 MOKKFOJJBOL GPOGPBKFNLJ DILCIJAHIOB
	// public DKCJADHKGAN CLLPBOPLICM { get; private set; } // 0x88 FNJBPMENMGD GFEDAIKEGGC AIDDOHHKJGG
	// public FBIOJHECAHB NBEMLGADAGK { get; private set; } // 0x8C DCKAOHBMJLM INDINPLHFPO CJBHGJLJBNJ
	// public JJOPEDJCCJK FMPEMFPLPDA { get; private set; } // 0x90 NFHAGPKJMCM JBOGJKMKPHB LJNHCFIIOBB
	// public BIHCALIAJII OINLLHOMEAK { get; private set; } // 0x94 NFNMMHLNOME ACMDICBGLLH AECOJNDBPPA
	// public PMDCIJMMNGK GKMAHADAAFI { get; private set; } // 0x98 CDPNLBODAFG MIOKEFPFJPL JCGBPLBDCED
	public LDDDBPNGGIN HNMMJINNHII { get; private set; } // 0x9C OEGOKKFEMLN // NNKOOANMMJN FDBLNEBHBKD
	// public KEEKEFEPKFN NKDGLGCAPEI { get; private set; } // 0xA0 OEBKCKBOHDC GKNAKMMFPJG FPNMNKOHIDL
	// public KCDJCKCKKFM LOJAMHAADBF { get; private set; } // 0xA4 PHJBEOHOPNK BEONJGJAHHA GKIMOCCMPNE
	// public ALJHJDHNFFB PFEKKPABPKL { get; private set; } // 0xA8 ODEEPLDCIDD CJNCHHCJDLG EJKAKGDGDOJ
	// public JJCJKALEIAC NFDHMGGLEPN { get; private set; } // 0xAC GGHPDLEFLAF KFBIAJPDFOL BLPBJMIOOHJ
	// public NPCCDMKJBMM MGIMEEEALPK { get; private set; } // 0xB0 IIGKAHAPDCK EMOJEAIPDCL KJJAAHMMPDD
	// public JKMLBONMAHD MLGEHCJPAFB { get; private set; } // 0xB4 DIOBCOIDGBL KLENJIKKNGL MCEKLAONFOO
	// public GJALOMELEHD KDIALKDKBGE { get; private set; } // 0xB8 AJILIAMLKCN OHOFMNKPACI AJNFIOMEBPE
	// public LLKLAKGKNLD HDGOHBFKKDM { get; private set; } // 0xBC GOCPJPDCIFF HNHCBNDJBIL OMHPACMOBMD
	// public EGLOKAEIHCB IHPFCIJKFIC { get; private set; } // 0xC0 DLCGGEGFOFM BKAPBBKJELI MINMKCJFHDG
	// public HHFFOACILKG ICICKEBMEFA { get; private set; } // 0xC4 BLEKIIHCAEL ECAMAOEFEJK IEOJCBOIKPN
	public KBCCGHLCFNO MEGJDBJCEOC { get; private set; } // 0xC8 LAJCNNENFPJ MIALNGOCOPJ NABHFEAEHFH
	public LPPGENBEECK_musicMaster IBPAFKKEKNK { get; private set; } // 0xCC CKFEJCIKLAE AHENIIKNNJF HMKLOBHNMMI
	// public GJAEGCMKMEK NEGKEEAFKHP { get; private set; } // 0xD0 NFCPFDJHNFE HEMDMBJABPN EJFOCHNEPKD
	// public LGHIPHEDCNC LBCMJGOOHLJ { get; private set; } // 0xD4 NAAKJHEPHGP NFGKMIAHJHD FMJANBICBME
	// public MPOEMCEBBJH OBGGLAKOHKP { get; private set; } // 0xD8 AHLBGPDJMCC PLOCKLBILGJ CFGIBLPKPOH
	// public MDACFBPPIHD LPFEHNJEJFB { get; private set; } // 0xDC HFOPPMPKKFL BCAGHHBCENF FKMAMMGADKI
	// public DHOJHGODBAB MHGPMMIDKMM { get; private set; } // 0xE0 HFKCBLFIKEC BODCNAFFNII JFGOKBPMCFL
	// public CKDOOBKOJBB KKIMFMKOHFH { get; private set; } // 0xE4 NFOFMEKFHEA AMANIEHMCLH OHKJEENNABM
	public MLIBEPGADJH ECNHDEHADGL { get; private set; } // 0xE8 IEIOOBGMFNI ACAKHGDFOPE MINEODNFCJG
	// public BKPAPCMJKHE IFLGCDGOLOP { get; private set; } // 0xEC LPLEPMGGDMC JPPGBAEFJHD NNMGMDJDAEB
	// public JNKEEAOKNCI FOFADHAENKC { get; private set; } // 0xF0 EMMJGCNLPIC AIKMDJIOIPO ODHIIKEDPDK
	// public BOKMNHAFJHF OMGFKMANMAB { get; private set; } // 0xF4 MFLNAPMHPKD IEFPCCJONCN FJJMCAEKDCM
	// public PPNFHHPJOKK OOEPHOEFBNL { get; private set; } // 0xF8 GEDHKEFKHEH HCAIIFDMGHF ELGOCAOHJBM
	// public LAEGMENIEDB OHCIFMDPAPD { get; private set; } // 0xFC OCCBGBFIPFH HLLFEGMBGLE IKHIJOGKIAL
	public PEBFNABDJDI GDEKCOOBLMA { get; private set; } // 0x100 PINEBDOIEIB LIJDDDCBNPL AAEDGCBNJAO
	// public BCKMELFCKKN KNMFNBEOGON { get; private set; } // 0x104 CLNAKEBEBIM HAAKPEOBDIO JNKAICHDNND
	public JOHKNBEFHHP ACPALDEELCL { get; private set; } // 0x108 MOHDEFAGJCD HCJMPMCLFAL OEBNPODPBGG
	// public DGDIEDDPNNG NMJEDFNPIPL { get; private set; } // 0x10C AIDFHJFIJJE BOGKAJBELIJ ONFDHFKPFHK
	// public DKJMDIFAKKD KCCDBKIOLDJ { get; private set; } // 0x110 NFOKONGDFNH MJBBGKMNMKH LFKKHMAFIBA
	// public INDEPDKCJDD FBGKBGNIHGC { get; private set; } // 0x114 MOPJLGOMNLJ BAGFGFIMNLH KPAEENCFPIH
	// public GKFMJAHKEMA DIAEPFPGPEP { get; private set; } // 0x118 BCDPCPEGMHC MOJPFJFKFPG IMCKGLCKPED
	// public JPIANKEOOMB PEOALFEGNDH { get; private set; } // 0x11C IOEEBHMLNFN HFDLJDHDCED MJFJKMCBIHC
	// public HGPEFPFODHO DCNNPEDOGOG { get; private set; } // 0x120 DGEJGGLIBPK DDMLBAIOIHC ADFIKFDMPAN
	// public ILLPGHGGKLL LINHIDCNAMG { get; private set; } // 0x124 CKMGPFOBCMH FAIKNJFGDIB MLLLCNLNJBI
	// public PJANOOPJIDE KIBMNCOLJNC { get; private set; } // 0x128 KNIHEPFNDKP FDIFJJONAEA MLKGAOGFOPI
	// public JHAAHJNEBOG MBAGKLJDKMH { get; private set; } // 0x12C HKMFFDNMOBN BDENFILNIID BHGPHONEKGL

	// // RVA: 0x149049C Offset: 0x149049C VA: 0x149049C
	// private static bool LIPIIKKIKOI(OKGLGHCBCJP.BEOKNKGHFFE[] NNDGIAEFMOG, OKGLGHCBCJP.BEOKNKGHFFE PPFNGGCBJKC) { }

	// // RVA: 0x1490508 Offset: 0x1490508 VA: 0x1490508
	// private static bool LIPIIKKIKOI(List<OKGLGHCBCJP.BEOKNKGHFFE> NNDGIAEFMOG, OKGLGHCBCJP.BEOKNKGHFFE PPFNGGCBJKC) { }

	// // RVA: 0x14905D0 Offset: 0x14905D0 VA: 0x14905D0
	public void LNAKMLCCEJG(List<OKGLGHCBCJP_Database.BEOKNKGHFFE> NNDGIAEFMOG, OKGLGHCBCJP_Database.BEOKNKGHFFE[] FCCKCFEEOMN)
	{
		UnityEngine.Debug.LogError("TODO");
	}

	// // RVA: 0x1490734 Offset: 0x1490734 VA: 0x1490734
	// private static string JEHFDJPOEFF(string HKICMNAACDA) { }

	// // RVA: 0x1490738 Offset: 0x1490738 VA: 0x1490738
	// private static bool FNHALBBECIM(OKGLGHCBCJP.BEOKNKGHFFE NEJBNCHLMNJ) { }

	// RVA: 0x1490C94 Offset: 0x1490C94 VA: 0x1490C94
	public OKGLGHCBCJP_Database()
	{
		UnityEngine.Debug.LogError("TODO");
		for(int i = 0; i < 117; i++)
		{
			IIILDINMAKI[i] = IJBLEJOKEFH[i];
			GJFPFFBAKGK[i] = 0;
		}
	}

	// RVA: 0x1490E98 Offset: 0x1490E98 VA: 0x1490E98
	public List<string> PKOJMBICNHH()
	{
		UnityEngine.Debug.LogError("TODO");
		return null;
	}

	// // RVA: 0x149101C Offset: 0x149101C VA: 0x149101C
	// public DIHHCBACKGG LBDOLHGDIEB(string OPFGFINHFCE) { }

	// // RVA: -1 Offset: -1
	// public T LBDOLHGDIEB<T>(string OPFGFINHFCE) { }
	// /* GenericInstMethod :
	// |
	// |-RVA: 0x1AB61C8 Offset: 0x1AB61C8 VA: 0x1AB61C8
	// |-OKGLGHCBCJP.LBDOLHGDIEB<object>
	// */

	// // RVA: 0x149111C Offset: 0x149111C VA: 0x149111C
	// public bool LGLJALBIIIB() { }

	// // RVA: 0x1491240 Offset: 0x1491240 VA: 0x1491240
	public List<OKGLGHCBCJP_Database.BEOKNKGHFFE> BPCKOIDILDK(List<GDIPLANPCEI> JOBKIDDLCPL, long JHNMKKNEENE)
	{
		UnityEngine.Debug.LogError("TODO");
		return null;
	}

	// // RVA: 0x1491860 Offset: 0x1491860 VA: 0x1491860
	// public void KHEKNNFCAOI() { }

	// // RVA: 0x1494278 Offset: 0x1494278 VA: 0x1494278
	public void KHEKNNFCAOI(List<OKGLGHCBCJP_Database.BEOKNKGHFFE> INBBCDGDMLC)
	{
		UnityEngine.Debug.LogError("TODO");
	}

	// // RVA: 0x14918F8 Offset: 0x14918F8 VA: 0x14918F8
	// public void KHEKNNFCAOI(OKGLGHCBCJP.BEOKNKGHFFE[] INBBCDGDMLC) { }

	// // RVA: 0x14942FC Offset: 0x14942FC VA: 0x14942FC
	// private DIHHCBACKGG MNMFKKKFDCL(OKGLGHCBCJP.BEOKNKGHFFE NEJBNCHLMNJ) { }

	// // RVA: 0x149494C Offset: 0x149494C VA: 0x149494C
	// public bool IIEMACPEEBJ(List<string> ANFNAHPIJDH, EDOHBJAPLPF AAEDAEHIONI) { }

	// // RVA: 0x1494FAC Offset: 0x1494FAC VA: 0x1494FAC
	public bool IIEMACPEEBJ(List<string> ANFNAHPIJDH, CBBJHPBGBAJ_Archive OCMCEKEKAPI)
	{
		UnityEngine.Debug.LogError("TODO");
		return false;
	}

	// // RVA: 0x1496334 Offset: 0x1496334 VA: 0x1496334
	// public bool ALKOAPJCNFD(long JHNMKKNEENE) { }

	// // RVA: 0x1496410 Offset: 0x1496410 VA: 0x1496410
	// public int PFAKPFKJJKA() { }

	// // RVA: 0x1496570 Offset: 0x1496570 VA: 0x1496570
	public void IDBDAPPJOND()
	{
		UnityEngine.Debug.LogError("TODO");
	}

	// RVA: 0x14966B4 Offset: 0x14966B4 VA: 0x14966B4
	static OKGLGHCBCJP_Database()
	{
		UnityEngine.Debug.LogError("TODO");
		GAAEFILMAED = new BEOKNKGHFFE[0x47]
		{
			BEOKNKGHFFE.LIIJEGOIKDP,
			BEOKNKGHFFE.MLNHHIIDJAO,
			BEOKNKGHFFE.PICOGHJNOJA,
			BEOKNKGHFFE.DBBOBIHPDNA,
			BEOKNKGHFFE.PEIFIFLMIIF,
			BEOKNKGHFFE.JOMAMMACANH,
			BEOKNKGHFFE.DHMPHBPODCI,
			BEOKNKGHFFE.DGPIFKCLAGB,
			BEOKNKGHFFE.EFHFNMAIEJG,
			BEOKNKGHFFE.LOFOAIEMECN,
			BEOKNKGHFFE.LHFCAMJHMLB,
			BEOKNKGHFFE.BGMIHMDPDCM,
			BEOKNKGHFFE.DBILOJAEIOO,
			BEOKNKGHFFE.DLFGIKANBDK,
			BEOKNKGHFFE.PLJHAFGEGEB,
			BEOKNKGHFFE.DHMEFNNJANH,
			BEOKNKGHFFE.CNENKCCMEFL,
			BEOKNKGHFFE.ACGFJFNPLKB,
			BEOKNKGHFFE.PKDKLHJLEFA,
			BEOKNKGHFFE.PGHFPIMIOKE,
			BEOKNKGHFFE.CNGPLGIMJBB,
			BEOKNKGHFFE.JBFFIPCOGEC,
			BEOKNKGHFFE.BBDKHAMANCB,
			BEOKNKGHFFE.MIOOJINHHFO,
			BEOKNKGHFFE.HJDJGMNAJFJ,
			BEOKNKGHFFE.OFAAHIINGFD,
			BEOKNKGHFFE.OFGFNFAJHFE,
			BEOKNKGHFFE.MDAEJLJPIHN,
			BEOKNKGHFFE.AMGKNGLDHMG,
			BEOKNKGHFFE.BKEKCFONNBG,
			BEOKNKGHFFE.JLNNFLCLGBM,
			BEOKNKGHFFE.MHNJLGONIPK,
			BEOKNKGHFFE.FPFHPCDNIDN,
			BEOKNKGHFFE.OJFINMGAFPG,
			BEOKNKGHFFE.HJBCLCJIAMN,
			BEOKNKGHFFE.JOMKJEEEGLM,
			BEOKNKGHFFE.MGLIHABHABA,
			BEOKNKGHFFE.JHIAPFBBCCJ,
			BEOKNKGHFFE.FLANCIJMJHP,
			BEOKNKGHFFE.BKGFKGIGJNL,
			BEOKNKGHFFE.NLIJGKHKMII,
			BEOKNKGHFFE.CLAMLDCILJO,
			BEOKNKGHFFE.FONDIJMKCAJ,
			BEOKNKGHFFE.KPBNAHEIJIC,
			BEOKNKGHFFE.ECEDGCHFCEF,
			BEOKNKGHFFE.HOBIIBFBMKJ,
			BEOKNKGHFFE.CHOGKKCHBCJ,
			BEOKNKGHFFE.JMJMNDKFOIF,
			BEOKNKGHFFE.LNCIOFKDBHD,
			BEOKNKGHFFE.GPEFCGBGIHD,
			BEOKNKGHFFE.JFDOPKICHPJ,
			BEOKNKGHFFE.HDJDAENLIBF,
			BEOKNKGHFFE.KOALKJHIHFC,
			BEOKNKGHFFE.KNMIJOPCJCH,
			BEOKNKGHFFE.ELBGPMIFOHO,
			BEOKNKGHFFE.ABANJLALLBK,
			BEOKNKGHFFE.HGOGFPOCKFA,
			BEOKNKGHFFE.LCEEHPPLHNC,
			BEOKNKGHFFE.AOPBBHMIEPB,
			BEOKNKGHFFE.HGFDKEMHGHK,
			BEOKNKGHFFE.ACECCMLEDMO,
			BEOKNKGHFFE.HDDBEGLGIDK,
			BEOKNKGHFFE.EMHPGEHBKPG,
			BEOKNKGHFFE.JJMBJBFKJHK,
			BEOKNKGHFFE.EKLPMPHCIDL,
			BEOKNKGHFFE.OPHNLHMINEO,
			BEOKNKGHFFE.NPLKLHDPLEO,
			BEOKNKGHFFE.EEPIDKPPLJI,
			BEOKNKGHFFE.LJKEOODGGJF,
			BEOKNKGHFFE.NPOPGPFPLOL,
			BEOKNKGHFFE.AHKEJPLNAJK
		};

		IJBLEJOKEFH = new string[0x75];
		int Idx = 0;
  		IJBLEJOKEFH[Idx++] = "adventure";
		IJBLEJOKEFH[Idx++] = "anketo";
		IJBLEJOKEFH[Idx++] = "asset";
		IJBLEJOKEFH[Idx++] = "bingo";
		IJBLEJOKEFH[Idx++] = "board";
		IJBLEJOKEFH[Idx++] = "bonus_vc";
		IJBLEJOKEFH[Idx++] = "campaign_diva";
		IJBLEJOKEFH[Idx++] = "compo";
		IJBLEJOKEFH[Idx++] = "cos_item";
		IJBLEJOKEFH[Idx++] = "costume";
		IJBLEJOKEFH[Idx++] = "deco_item";
		IJBLEJOKEFH[Idx++] = "deco_item_init";
		IJBLEJOKEFH[Idx++] = "deco_point";
		IJBLEJOKEFH[Idx++] = "deco_set_item";
		IJBLEJOKEFH[Idx++] = "deco_sp_setting";
		IJBLEJOKEFH[Idx++] = "deco_stamp";
		IJBLEJOKEFH[Idx++] = "diva";
		IJBLEJOKEFH[Idx++] = "diva2";
		IJBLEJOKEFH[Idx++] = "drop";
		IJBLEJOKEFH[Idx++] = "emblem";
		IJBLEJOKEFH[Idx++] = "enemy";
		IJBLEJOKEFH[Idx++] = "energy_item";
		IJBLEJOKEFH[Idx++] = "episode";
		IJBLEJOKEFH[Idx++] = "epi_item";
		IJBLEJOKEFH[Idx++] = "event_april_fool_a";
		IJBLEJOKEFH[Idx++] = "event_april_fool_b";
		IJBLEJOKEFH[Idx++] = "event_april_fool_c";
		IJBLEJOKEFH[Idx++] = "event_april_fool_d";
		IJBLEJOKEFH[Idx++] = "event_april_fool_e";
		IJBLEJOKEFH[Idx++] = "event_april_fool_f";
		IJBLEJOKEFH[Idx++] = "event_april_fool_g";
		IJBLEJOKEFH[Idx++] = "event_april_fool_h";
		IJBLEJOKEFH[Idx++] = "event_april_fool_i";
		IJBLEJOKEFH[Idx++] = "event_battle_a";
		IJBLEJOKEFH[Idx++] = "event_battle_b";
		IJBLEJOKEFH[Idx++] = "event_battle_c";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_a";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_b";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_c";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_d";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_e";
		IJBLEJOKEFH[Idx++] = "event_box_gacha_f";
		IJBLEJOKEFH[Idx++] = "event_collection_a";
		IJBLEJOKEFH[Idx++] = "event_collection_b";
		IJBLEJOKEFH[Idx++] = "event_collection_c";
		IJBLEJOKEFH[Idx++] = "event_gacha_ticket";
		IJBLEJOKEFH[Idx++] = "event_godiva_a";
		IJBLEJOKEFH[Idx++] = "event_godiva_b";
		IJBLEJOKEFH[Idx++] = "event_godiva_c";
		IJBLEJOKEFH[Idx++] = "event_godiva_ranking";
		IJBLEJOKEFH[Idx++] = "event_item";
		IJBLEJOKEFH[Idx++] = "event_mission_a";
		IJBLEJOKEFH[Idx++] = "event_mission_b";
		IJBLEJOKEFH[Idx++] = "event_mission_c";
		IJBLEJOKEFH[Idx++] = "event_present_campaign_a";
		IJBLEJOKEFH[Idx++] = "event_raid_a";
		IJBLEJOKEFH[Idx++] = "event_raid_b";
		IJBLEJOKEFH[Idx++] = "event_raid_c";
		IJBLEJOKEFH[Idx++] = "event_raid_d";
		IJBLEJOKEFH[Idx++] = "event_raidlobby_a";
		IJBLEJOKEFH[Idx++] = "event_raidlobby_b";
		IJBLEJOKEFH[Idx++] = "event_raidlobby_c";
		IJBLEJOKEFH[Idx++] = "event_raidlobby_d";
		IJBLEJOKEFH[Idx++] = "event_raid_item";
		IJBLEJOKEFH[Idx++] = "event_quest_a";
		IJBLEJOKEFH[Idx++] = "event_quest_b";
		IJBLEJOKEFH[Idx++] = "event_quest_c";
		IJBLEJOKEFH[Idx++] = "event_score_a";
		IJBLEJOKEFH[Idx++] = "event_score_b";
		IJBLEJOKEFH[Idx++] = "event_score_c";
		IJBLEJOKEFH[Idx++] = "event_score_d";
		IJBLEJOKEFH[Idx++] = "event_score_e";
		IJBLEJOKEFH[Idx++] = "event_score_f";
		IJBLEJOKEFH[Idx++] = "event_sp_a";
		IJBLEJOKEFH[Idx++] = "event_ticket";
		IJBLEJOKEFH[Idx++] = "event_weekday";
		IJBLEJOKEFH[Idx++] = "event_story";
		IJBLEJOKEFH[Idx++] = "exp";
		IJBLEJOKEFH[Idx++] = "gacha_limit";
		IJBLEJOKEFH[Idx++] = "gacha_ticket";
		IJBLEJOKEFH[Idx++] = "game";
		IJBLEJOKEFH[Idx++] = "grow_item";
		IJBLEJOKEFH[Idx++] = "help_browser";
		IJBLEJOKEFH[Idx++] = "home_bg";
		IJBLEJOKEFH[Idx++] = "home_pickup";
		IJBLEJOKEFH[Idx++] = "home_voice";
		IJBLEJOKEFH[Idx++] = "rich_banner";
		IJBLEJOKEFH[Idx++] = "intimacy";
		IJBLEJOKEFH[Idx++] = "limit_over";
		IJBLEJOKEFH[Idx++] = "limited_item";
		IJBLEJOKEFH[Idx++] = "medal";
		IJBLEJOKEFH[Idx++] = "monthly_pass";
		IJBLEJOKEFH[Idx++] = "music";
		IJBLEJOKEFH[Idx++] = "mv_ticket";
		IJBLEJOKEFH[Idx++] = "offer";
		IJBLEJOKEFH[Idx++] = "pilot";
		IJBLEJOKEFH[Idx++] = "present_item";
		IJBLEJOKEFH[Idx++] = "quest";
		IJBLEJOKEFH[Idx++] = "rareup_item";
		IJBLEJOKEFH[Idx++] = "scene";
		IJBLEJOKEFH[Idx++] = "shop";
		IJBLEJOKEFH[Idx++] = "skill";
		IJBLEJOKEFH[Idx++] = "sns";
		IJBLEJOKEFH[Idx++] = "sp_item";
		IJBLEJOKEFH[Idx++] = "story";
		IJBLEJOKEFH[Idx++] = "system";
		IJBLEJOKEFH[Idx++] = "tips";
		IJBLEJOKEFH[Idx++] = "title_banner";
		IJBLEJOKEFH[Idx++] = "tutorial_mini_adv";
		IJBLEJOKEFH[Idx++] = "tutorial_pict";
		IJBLEJOKEFH[Idx++] = "uc_item";
		IJBLEJOKEFH[Idx++] = "val_item";
		IJBLEJOKEFH[Idx++] = "val_skill";
		IJBLEJOKEFH[Idx++] = "valkyrie";
		IJBLEJOKEFH[Idx++] = "vc_item";
		IJBLEJOKEFH[Idx++] = "highscore_rating";
		IJBLEJOKEFH[Idx++] = "limited_compo_item";
  
		//BGEJFKHOMOC = new Dictionary<int, BIFFPAKDHJJ>();
		//BGEJFKHOMOC.Add(0, );
		//TODO
	}
	
}
