// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class AIAGNLHOHPF : Table {
  public static AIAGNLHOHPF GetRootAsAIAGNLHOHPF(ByteBuffer _bb) { return GetRootAsAIAGNLHOHPF(_bb, new AIAGNLHOHPF()); }
  public static AIAGNLHOHPF GetRootAsAIAGNLHOHPF(ByteBuffer _bb, AIAGNLHOHPF obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AIAGNLHOHPF __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public MKPHLDNDLDL GetKDNNKLCMJCE(int j) { return GetKDNNKLCMJCE(new MKPHLDNDLDL(), j); }
  public MKPHLDNDLDL GetKDNNKLCMJCE(MKPHLDNDLDL obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int KDNNKLCMJCELength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<AIAGNLHOHPF> CreateAIAGNLHOHPF(FlatBufferBuilder builder,
      VectorOffset KDNNKLCMJCEOffset = default(VectorOffset)) {
    builder.StartObject(1);
    AIAGNLHOHPF.AddKDNNKLCMJCE(builder, KDNNKLCMJCEOffset);
    return AIAGNLHOHPF.EndAIAGNLHOHPF(builder);
  }

  public static void StartAIAGNLHOHPF(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddKDNNKLCMJCE(FlatBufferBuilder builder, VectorOffset KDNNKLCMJCEOffset) { builder.AddOffset(0, KDNNKLCMJCEOffset.Value, 0); }
  public static VectorOffset CreateKDNNKLCMJCEVector(FlatBufferBuilder builder, Offset<MKPHLDNDLDL>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartKDNNKLCMJCEVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<AIAGNLHOHPF> EndAIAGNLHOHPF(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AIAGNLHOHPF>(o);
  }
};

