// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class BNKFBEGNEHA : Table {
  public static BNKFBEGNEHA GetRootAsBNKFBEGNEHA(ByteBuffer _bb) { return GetRootAsBNKFBEGNEHA(_bb, new BNKFBEGNEHA()); }
  public static BNKFBEGNEHA GetRootAsBNKFBEGNEHA(ByteBuffer _bb, BNKFBEGNEHA obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public BNKFBEGNEHA __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int CFLMCGOJJJD { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string IIDCFMHCPLJ { get { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIDCFMHCPLJBytes() { return __vector_as_arraysegment(8); }
  public int MAIJBDCJPNJ { get { int o = __offset(10); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int OFMGALJGDAO { get { int o = __offset(12); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int NJLJEKDBPCH { get { int o = __offset(14); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MAOAGDBDBIB { get { int o = __offset(16); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int JEEDFKICAKL { get { int o = __offset(18); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<BNKFBEGNEHA> CreateBNKFBEGNEHA(FlatBufferBuilder builder,
      int BBPHAPFBFHK = 0,
      int CFLMCGOJJJD = 0,
      StringOffset IIDCFMHCPLJOffset = default(StringOffset),
      int MAIJBDCJPNJ = 0,
      int OFMGALJGDAO = 0,
      int NJLJEKDBPCH = 0,
      int MAOAGDBDBIB = 0,
      int JEEDFKICAKL = 0) {
    builder.StartObject(8);
    BNKFBEGNEHA.AddJEEDFKICAKL(builder, JEEDFKICAKL);
    BNKFBEGNEHA.AddMAOAGDBDBIB(builder, MAOAGDBDBIB);
    BNKFBEGNEHA.AddNJLJEKDBPCH(builder, NJLJEKDBPCH);
    BNKFBEGNEHA.AddOFMGALJGDAO(builder, OFMGALJGDAO);
    BNKFBEGNEHA.AddMAIJBDCJPNJ(builder, MAIJBDCJPNJ);
    BNKFBEGNEHA.AddIIDCFMHCPLJ(builder, IIDCFMHCPLJOffset);
    BNKFBEGNEHA.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    BNKFBEGNEHA.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return BNKFBEGNEHA.EndBNKFBEGNEHA(builder);
  }

  public static void StartBNKFBEGNEHA(FlatBufferBuilder builder) { builder.StartObject(8); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, int BBPHAPFBFHK) { builder.AddInt(0, BBPHAPFBFHK, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, int CFLMCGOJJJD) { builder.AddInt(1, CFLMCGOJJJD, 0); }
  public static void AddIIDCFMHCPLJ(FlatBufferBuilder builder, StringOffset IIDCFMHCPLJOffset) { builder.AddOffset(2, IIDCFMHCPLJOffset.Value, 0); }
  public static void AddMAIJBDCJPNJ(FlatBufferBuilder builder, int MAIJBDCJPNJ) { builder.AddInt(3, MAIJBDCJPNJ, 0); }
  public static void AddOFMGALJGDAO(FlatBufferBuilder builder, int OFMGALJGDAO) { builder.AddInt(4, OFMGALJGDAO, 0); }
  public static void AddNJLJEKDBPCH(FlatBufferBuilder builder, int NJLJEKDBPCH) { builder.AddInt(5, NJLJEKDBPCH, 0); }
  public static void AddMAOAGDBDBIB(FlatBufferBuilder builder, int MAOAGDBDBIB) { builder.AddInt(6, MAOAGDBDBIB, 0); }
  public static void AddJEEDFKICAKL(FlatBufferBuilder builder, int JEEDFKICAKL) { builder.AddInt(7, JEEDFKICAKL, 0); }
  public static Offset<BNKFBEGNEHA> EndBNKFBEGNEHA(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BNKFBEGNEHA>(o);
  }
};

