// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class BPDPIFOLPDM : Table {
  public static BPDPIFOLPDM GetRootAsBPDPIFOLPDM(ByteBuffer _bb) { return GetRootAsBPDPIFOLPDM(_bb, new BPDPIFOLPDM()); }
  public static BPDPIFOLPDM GetRootAsBPDPIFOLPDM(ByteBuffer _bb, BPDPIFOLPDM obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public BPDPIFOLPDM __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DDMBKEJNPJK { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JLBMBKHBKBG { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint EHIBOEAILLI { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CFLMCGOJJJD { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int OFMGALJGDAO { get { int o = __offset(14); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int OILFLMOBFJM { get { int o = __offset(16); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int KBGHNCHBLHN { get { int o = __offset(18); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int DAEBPADJEOK { get { int o = __offset(20); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int JMADKJNCBCO { get { int o = __offset(22); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int DIGHIPFGPAP { get { int o = __offset(24); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GNPNCHPOGNL { get { int o = __offset(26); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int CODDJJEBDNG { get { int o = __offset(28); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetPGEKHEFEBOC(int j) { int o = __offset(30); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int PGEKHEFEBOCLength { get { int o = __offset(30); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetPGEKHEFEBOCBytes() { return __vector_as_arraysegment(30); }
  public int GetIIFJDHKAMED(int j) { int o = __offset(32); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int IIFJDHKAMEDLength { get { int o = __offset(32); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetIIFJDHKAMEDBytes() { return __vector_as_arraysegment(32); }
  public int GetFCDHEJINFPH(int j) { int o = __offset(34); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int FCDHEJINFPHLength { get { int o = __offset(34); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetFCDHEJINFPHBytes() { return __vector_as_arraysegment(34); }
  public int MFKMAPAOPLN { get { int o = __offset(36); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<BPDPIFOLPDM> CreateBPDPIFOLPDM(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint DDMBKEJNPJK = 0,
      uint JLBMBKHBKBG = 0,
      uint EHIBOEAILLI = 0,
      uint CFLMCGOJJJD = 0,
      int OFMGALJGDAO = 0,
      int OILFLMOBFJM = 0,
      int KBGHNCHBLHN = 0,
      int DAEBPADJEOK = 0,
      int JMADKJNCBCO = 0,
      int DIGHIPFGPAP = 0,
      int GNPNCHPOGNL = 0,
      int CODDJJEBDNG = 0,
      VectorOffset PGEKHEFEBOCOffset = default(VectorOffset),
      VectorOffset IIFJDHKAMEDOffset = default(VectorOffset),
      VectorOffset FCDHEJINFPHOffset = default(VectorOffset),
      int MFKMAPAOPLN = 0) {
    builder.StartObject(17);
    BPDPIFOLPDM.AddMFKMAPAOPLN(builder, MFKMAPAOPLN);
    BPDPIFOLPDM.AddFCDHEJINFPH(builder, FCDHEJINFPHOffset);
    BPDPIFOLPDM.AddIIFJDHKAMED(builder, IIFJDHKAMEDOffset);
    BPDPIFOLPDM.AddPGEKHEFEBOC(builder, PGEKHEFEBOCOffset);
    BPDPIFOLPDM.AddCODDJJEBDNG(builder, CODDJJEBDNG);
    BPDPIFOLPDM.AddGNPNCHPOGNL(builder, GNPNCHPOGNL);
    BPDPIFOLPDM.AddDIGHIPFGPAP(builder, DIGHIPFGPAP);
    BPDPIFOLPDM.AddJMADKJNCBCO(builder, JMADKJNCBCO);
    BPDPIFOLPDM.AddDAEBPADJEOK(builder, DAEBPADJEOK);
    BPDPIFOLPDM.AddKBGHNCHBLHN(builder, KBGHNCHBLHN);
    BPDPIFOLPDM.AddOILFLMOBFJM(builder, OILFLMOBFJM);
    BPDPIFOLPDM.AddOFMGALJGDAO(builder, OFMGALJGDAO);
    BPDPIFOLPDM.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    BPDPIFOLPDM.AddEHIBOEAILLI(builder, EHIBOEAILLI);
    BPDPIFOLPDM.AddJLBMBKHBKBG(builder, JLBMBKHBKBG);
    BPDPIFOLPDM.AddDDMBKEJNPJK(builder, DDMBKEJNPJK);
    BPDPIFOLPDM.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return BPDPIFOLPDM.EndBPDPIFOLPDM(builder);
  }

  public static void StartBPDPIFOLPDM(FlatBufferBuilder builder) { builder.StartObject(17); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddDDMBKEJNPJK(FlatBufferBuilder builder, uint DDMBKEJNPJK) { builder.AddUint(1, DDMBKEJNPJK, 0); }
  public static void AddJLBMBKHBKBG(FlatBufferBuilder builder, uint JLBMBKHBKBG) { builder.AddUint(2, JLBMBKHBKBG, 0); }
  public static void AddEHIBOEAILLI(FlatBufferBuilder builder, uint EHIBOEAILLI) { builder.AddUint(3, EHIBOEAILLI, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, uint CFLMCGOJJJD) { builder.AddUint(4, CFLMCGOJJJD, 0); }
  public static void AddOFMGALJGDAO(FlatBufferBuilder builder, int OFMGALJGDAO) { builder.AddInt(5, OFMGALJGDAO, 0); }
  public static void AddOILFLMOBFJM(FlatBufferBuilder builder, int OILFLMOBFJM) { builder.AddInt(6, OILFLMOBFJM, 0); }
  public static void AddKBGHNCHBLHN(FlatBufferBuilder builder, int KBGHNCHBLHN) { builder.AddInt(7, KBGHNCHBLHN, 0); }
  public static void AddDAEBPADJEOK(FlatBufferBuilder builder, int DAEBPADJEOK) { builder.AddInt(8, DAEBPADJEOK, 0); }
  public static void AddJMADKJNCBCO(FlatBufferBuilder builder, int JMADKJNCBCO) { builder.AddInt(9, JMADKJNCBCO, 0); }
  public static void AddDIGHIPFGPAP(FlatBufferBuilder builder, int DIGHIPFGPAP) { builder.AddInt(10, DIGHIPFGPAP, 0); }
  public static void AddGNPNCHPOGNL(FlatBufferBuilder builder, int GNPNCHPOGNL) { builder.AddInt(11, GNPNCHPOGNL, 0); }
  public static void AddCODDJJEBDNG(FlatBufferBuilder builder, int CODDJJEBDNG) { builder.AddInt(12, CODDJJEBDNG, 0); }
  public static void AddPGEKHEFEBOC(FlatBufferBuilder builder, VectorOffset PGEKHEFEBOCOffset) { builder.AddOffset(13, PGEKHEFEBOCOffset.Value, 0); }
  public static VectorOffset CreatePGEKHEFEBOCVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartPGEKHEFEBOCVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddIIFJDHKAMED(FlatBufferBuilder builder, VectorOffset IIFJDHKAMEDOffset) { builder.AddOffset(14, IIFJDHKAMEDOffset.Value, 0); }
  public static VectorOffset CreateIIFJDHKAMEDVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartIIFJDHKAMEDVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFCDHEJINFPH(FlatBufferBuilder builder, VectorOffset FCDHEJINFPHOffset) { builder.AddOffset(15, FCDHEJINFPHOffset.Value, 0); }
  public static VectorOffset CreateFCDHEJINFPHVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartFCDHEJINFPHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMFKMAPAOPLN(FlatBufferBuilder builder, int MFKMAPAOPLN) { builder.AddInt(16, MFKMAPAOPLN, 0); }
  public static Offset<BPDPIFOLPDM> EndBPDPIFOLPDM(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BPDPIFOLPDM>(o);
  }
};

