// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class CIJEJAKKDMB : Table {
  public static CIJEJAKKDMB GetRootAsCIJEJAKKDMB(ByteBuffer _bb) { return GetRootAsCIJEJAKKDMB(_bb, new CIJEJAKKDMB()); }
  public static CIJEJAKKDMB GetRootAsCIJEJAKKDMB(ByteBuffer _bb, CIJEJAKKDMB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CIJEJAKKDMB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CFLMCGOJJJD { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KJFEBMBHKOC { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int IBDFJIDNDJH { get { int o = __offset(10); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GLIIHLOLPEF { get { int o = __offset(12); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int KMEODDMBHHE { get { int o = __offset(14); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<CIJEJAKKDMB> CreateCIJEJAKKDMB(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint CFLMCGOJJJD = 0,
      uint KJFEBMBHKOC = 0,
      int IBDFJIDNDJH = 0,
      int GLIIHLOLPEF = 0,
      int KMEODDMBHHE = 0) {
    builder.StartObject(6);
    CIJEJAKKDMB.AddKMEODDMBHHE(builder, KMEODDMBHHE);
    CIJEJAKKDMB.AddGLIIHLOLPEF(builder, GLIIHLOLPEF);
    CIJEJAKKDMB.AddIBDFJIDNDJH(builder, IBDFJIDNDJH);
    CIJEJAKKDMB.AddKJFEBMBHKOC(builder, KJFEBMBHKOC);
    CIJEJAKKDMB.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    CIJEJAKKDMB.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return CIJEJAKKDMB.EndCIJEJAKKDMB(builder);
  }

  public static void StartCIJEJAKKDMB(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, uint CFLMCGOJJJD) { builder.AddUint(1, CFLMCGOJJJD, 0); }
  public static void AddKJFEBMBHKOC(FlatBufferBuilder builder, uint KJFEBMBHKOC) { builder.AddUint(2, KJFEBMBHKOC, 0); }
  public static void AddIBDFJIDNDJH(FlatBufferBuilder builder, int IBDFJIDNDJH) { builder.AddInt(3, IBDFJIDNDJH, 0); }
  public static void AddGLIIHLOLPEF(FlatBufferBuilder builder, int GLIIHLOLPEF) { builder.AddInt(4, GLIIHLOLPEF, 0); }
  public static void AddKMEODDMBHHE(FlatBufferBuilder builder, int KMEODDMBHHE) { builder.AddInt(5, KMEODDMBHHE, 0); }
  public static Offset<CIJEJAKKDMB> EndCIJEJAKKDMB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CIJEJAKKDMB>(o);
  }
};

