// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class CJBNLNDKLKA : Table {
  public static CJBNLNDKLKA GetRootAsCJBNLNDKLKA(ByteBuffer _bb) { return GetRootAsCJBNLNDKLKA(_bb, new CJBNLNDKLKA()); }
  public static CJBNLNDKLKA GetRootAsCJBNLNDKLKA(ByteBuffer _bb, CJBNLNDKLKA obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CJBNLNDKLKA __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint MBBJMJAAODG { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int CFCGMIMJKLE { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int OFGPIPFIPKB { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public uint LHABMCKNLFG { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AIIPAPCLGGO { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ACHLKLEIOJJ { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint GGIDBEGABBO { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<CJBNLNDKLKA> CreateCJBNLNDKLKA(FlatBufferBuilder builder,
      uint MBBJMJAAODG = 0,
      int CFCGMIMJKLE = 0,
      int OFGPIPFIPKB = 0,
      uint LHABMCKNLFG = 0,
      uint AIIPAPCLGGO = 0,
      uint ACHLKLEIOJJ = 0,
      uint GGIDBEGABBO = 0) {
    builder.StartObject(7);
    CJBNLNDKLKA.AddGGIDBEGABBO(builder, GGIDBEGABBO);
    CJBNLNDKLKA.AddACHLKLEIOJJ(builder, ACHLKLEIOJJ);
    CJBNLNDKLKA.AddAIIPAPCLGGO(builder, AIIPAPCLGGO);
    CJBNLNDKLKA.AddLHABMCKNLFG(builder, LHABMCKNLFG);
    CJBNLNDKLKA.AddOFGPIPFIPKB(builder, OFGPIPFIPKB);
    CJBNLNDKLKA.AddCFCGMIMJKLE(builder, CFCGMIMJKLE);
    CJBNLNDKLKA.AddMBBJMJAAODG(builder, MBBJMJAAODG);
    return CJBNLNDKLKA.EndCJBNLNDKLKA(builder);
  }

  public static void StartCJBNLNDKLKA(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddMBBJMJAAODG(FlatBufferBuilder builder, uint MBBJMJAAODG) { builder.AddUint(0, MBBJMJAAODG, 0); }
  public static void AddCFCGMIMJKLE(FlatBufferBuilder builder, int CFCGMIMJKLE) { builder.AddInt(1, CFCGMIMJKLE, 0); }
  public static void AddOFGPIPFIPKB(FlatBufferBuilder builder, int OFGPIPFIPKB) { builder.AddInt(2, OFGPIPFIPKB, 0); }
  public static void AddLHABMCKNLFG(FlatBufferBuilder builder, uint LHABMCKNLFG) { builder.AddUint(3, LHABMCKNLFG, 0); }
  public static void AddAIIPAPCLGGO(FlatBufferBuilder builder, uint AIIPAPCLGGO) { builder.AddUint(4, AIIPAPCLGGO, 0); }
  public static void AddACHLKLEIOJJ(FlatBufferBuilder builder, uint ACHLKLEIOJJ) { builder.AddUint(5, ACHLKLEIOJJ, 0); }
  public static void AddGGIDBEGABBO(FlatBufferBuilder builder, uint GGIDBEGABBO) { builder.AddUint(6, GGIDBEGABBO, 0); }
  public static Offset<CJBNLNDKLKA> EndCJBNLNDKLKA(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CJBNLNDKLKA>(o);
  }
};

