// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class CJMBCLHMFBF : Table {
  public static CJMBCLHMFBF GetRootAsCJMBCLHMFBF(ByteBuffer _bb) { return GetRootAsCJMBCLHMFBF(_bb, new CJMBCLHMFBF()); }
  public static CJMBCLHMFBF GetRootAsCJMBCLHMFBF(ByteBuffer _bb, CJMBCLHMFBF obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CJMBCLHMFBF __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public GFNMEMLEAFB GetBBPMPGIIHOL(int j) { return GetBBPMPGIIHOL(new GFNMEMLEAFB(), j); }
  public GFNMEMLEAFB GetBBPMPGIIHOL(GFNMEMLEAFB obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int BBPMPGIIHOLLength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<CJMBCLHMFBF> CreateCJMBCLHMFBF(FlatBufferBuilder builder,
      VectorOffset BBPMPGIIHOLOffset = default(VectorOffset)) {
    builder.StartObject(1);
    CJMBCLHMFBF.AddBBPMPGIIHOL(builder, BBPMPGIIHOLOffset);
    return CJMBCLHMFBF.EndCJMBCLHMFBF(builder);
  }

  public static void StartCJMBCLHMFBF(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddBBPMPGIIHOL(FlatBufferBuilder builder, VectorOffset BBPMPGIIHOLOffset) { builder.AddOffset(0, BBPMPGIIHOLOffset.Value, 0); }
  public static VectorOffset CreateBBPMPGIIHOLVector(FlatBufferBuilder builder, Offset<GFNMEMLEAFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartBBPMPGIIHOLVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CJMBCLHMFBF> EndCJMBCLHMFBF(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CJMBCLHMFBF>(o);
  }
};

