// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class CLBPBGIPFPP : Table {
  public static CLBPBGIPFPP GetRootAsCLBPBGIPFPP(ByteBuffer _bb) { return GetRootAsCLBPBGIPFPP(_bb, new CLBPBGIPFPP()); }
  public static CLBPBGIPFPP GetRootAsCLBPBGIPFPP(ByteBuffer _bb, CLBPBGIPFPP obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CLBPBGIPFPP __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CFLMCGOJJJD { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint IAPFGOHKAGE { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint HICGGFMNEMI { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint EFFICDBHCCH { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint FOHAACCBBOP { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int NJLJEKDBPCH { get { int o = __offset(16); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MAOAGDBDBIB { get { int o = __offset(18); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<CLBPBGIPFPP> CreateCLBPBGIPFPP(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint CFLMCGOJJJD = 0,
      uint IAPFGOHKAGE = 0,
      uint HICGGFMNEMI = 0,
      uint EFFICDBHCCH = 0,
      uint FOHAACCBBOP = 0,
      int NJLJEKDBPCH = 0,
      int MAOAGDBDBIB = 0) {
    builder.StartObject(8);
    CLBPBGIPFPP.AddMAOAGDBDBIB(builder, MAOAGDBDBIB);
    CLBPBGIPFPP.AddNJLJEKDBPCH(builder, NJLJEKDBPCH);
    CLBPBGIPFPP.AddFOHAACCBBOP(builder, FOHAACCBBOP);
    CLBPBGIPFPP.AddEFFICDBHCCH(builder, EFFICDBHCCH);
    CLBPBGIPFPP.AddHICGGFMNEMI(builder, HICGGFMNEMI);
    CLBPBGIPFPP.AddIAPFGOHKAGE(builder, IAPFGOHKAGE);
    CLBPBGIPFPP.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    CLBPBGIPFPP.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return CLBPBGIPFPP.EndCLBPBGIPFPP(builder);
  }

  public static void StartCLBPBGIPFPP(FlatBufferBuilder builder) { builder.StartObject(8); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, uint CFLMCGOJJJD) { builder.AddUint(1, CFLMCGOJJJD, 0); }
  public static void AddIAPFGOHKAGE(FlatBufferBuilder builder, uint IAPFGOHKAGE) { builder.AddUint(2, IAPFGOHKAGE, 0); }
  public static void AddHICGGFMNEMI(FlatBufferBuilder builder, uint HICGGFMNEMI) { builder.AddUint(3, HICGGFMNEMI, 0); }
  public static void AddEFFICDBHCCH(FlatBufferBuilder builder, uint EFFICDBHCCH) { builder.AddUint(4, EFFICDBHCCH, 0); }
  public static void AddFOHAACCBBOP(FlatBufferBuilder builder, uint FOHAACCBBOP) { builder.AddUint(5, FOHAACCBBOP, 0); }
  public static void AddNJLJEKDBPCH(FlatBufferBuilder builder, int NJLJEKDBPCH) { builder.AddInt(6, NJLJEKDBPCH, 0); }
  public static void AddMAOAGDBDBIB(FlatBufferBuilder builder, int MAOAGDBDBIB) { builder.AddInt(7, MAOAGDBDBIB, 0); }
  public static Offset<CLBPBGIPFPP> EndCLBPBGIPFPP(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CLBPBGIPFPP>(o);
  }
};

