// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class DBDMELPOPMH : Table {
  public static DBDMELPOPMH GetRootAsDBDMELPOPMH(ByteBuffer _bb) { return GetRootAsDBDMELPOPMH(_bb, new DBDMELPOPMH()); }
  public static DBDMELPOPMH GetRootAsDBDMELPOPMH(ByteBuffer _bb, DBDMELPOPMH obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public DBDMELPOPMH __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int AINFENANAKL { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int IHODOLMEGIL { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MDGINMBLOHO { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<DBDMELPOPMH> CreateDBDMELPOPMH(FlatBufferBuilder builder,
      int AINFENANAKL = 0,
      int IHODOLMEGIL = 0,
      int MDGINMBLOHO = 0) {
    builder.StartObject(3);
    DBDMELPOPMH.AddMDGINMBLOHO(builder, MDGINMBLOHO);
    DBDMELPOPMH.AddIHODOLMEGIL(builder, IHODOLMEGIL);
    DBDMELPOPMH.AddAINFENANAKL(builder, AINFENANAKL);
    return DBDMELPOPMH.EndDBDMELPOPMH(builder);
  }

  public static void StartDBDMELPOPMH(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddAINFENANAKL(FlatBufferBuilder builder, int AINFENANAKL) { builder.AddInt(0, AINFENANAKL, 0); }
  public static void AddIHODOLMEGIL(FlatBufferBuilder builder, int IHODOLMEGIL) { builder.AddInt(1, IHODOLMEGIL, 0); }
  public static void AddMDGINMBLOHO(FlatBufferBuilder builder, int MDGINMBLOHO) { builder.AddInt(2, MDGINMBLOHO, 0); }
  public static Offset<DBDMELPOPMH> EndDBDMELPOPMH(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DBDMELPOPMH>(o);
  }
};

