// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class DFHBOFFBKDB : Table {
  public static DFHBOFFBKDB GetRootAsDFHBOFFBKDB(ByteBuffer _bb) { return GetRootAsDFHBOFFBKDB(_bb, new DFHBOFFBKDB()); }
  public static DFHBOFFBKDB GetRootAsDFHBOFFBKDB(ByteBuffer _bb, DFHBOFFBKDB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public DFHBOFFBKDB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public JOGLEFDCEJI GetEJKKOPBPJBN(int j) { return GetEJKKOPBPJBN(new JOGLEFDCEJI(), j); }
  public JOGLEFDCEJI GetEJKKOPBPJBN(JOGLEFDCEJI obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int EJKKOPBPJBNLength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }
  public JIMFBCIKKKJ GetMDFKCCMFFFD(int j) { return GetMDFKCCMFFFD(new JIMFBCIKKKJ(), j); }
  public JIMFBCIKKKJ GetMDFKCCMFFFD(JIMFBCIKKKJ obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int MDFKCCMFFFDLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public OLMJGOPCIKK GetMHOEKDECGGN(int j) { return GetMHOEKDECGGN(new OLMJGOPCIKK(), j); }
  public OLMJGOPCIKK GetMHOEKDECGGN(OLMJGOPCIKK obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int MHOEKDECGGNLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public FFAOJIELJAC GetPCHLJEFOEFL(int j) { return GetPCHLJEFOEFL(new FFAOJIELJAC(), j); }
  public FFAOJIELJAC GetPCHLJEFOEFL(FFAOJIELJAC obj, int j) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int PCHLJEFOEFLLength { get { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; } }
  public CJLNKNELECA GetJKFLLEHIMLL(int j) { return GetJKFLLEHIMLL(new CJLNKNELECA(), j); }
  public CJLNKNELECA GetJKFLLEHIMLL(CJLNKNELECA obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int JKFLLEHIMLLLength { get { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; } }
  public NOAPHCIKEID GetNJJINHMIOHN(int j) { return GetNJJINHMIOHN(new NOAPHCIKEID(), j); }
  public NOAPHCIKEID GetNJJINHMIOHN(NOAPHCIKEID obj, int j) { int o = __offset(14); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int NJJINHMIOHNLength { get { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<DFHBOFFBKDB> CreateDFHBOFFBKDB(FlatBufferBuilder builder,
      VectorOffset EJKKOPBPJBNOffset = default(VectorOffset),
      VectorOffset MDFKCCMFFFDOffset = default(VectorOffset),
      VectorOffset MHOEKDECGGNOffset = default(VectorOffset),
      VectorOffset PCHLJEFOEFLOffset = default(VectorOffset),
      VectorOffset JKFLLEHIMLLOffset = default(VectorOffset),
      VectorOffset NJJINHMIOHNOffset = default(VectorOffset)) {
    builder.StartObject(6);
    DFHBOFFBKDB.AddNJJINHMIOHN(builder, NJJINHMIOHNOffset);
    DFHBOFFBKDB.AddJKFLLEHIMLL(builder, JKFLLEHIMLLOffset);
    DFHBOFFBKDB.AddPCHLJEFOEFL(builder, PCHLJEFOEFLOffset);
    DFHBOFFBKDB.AddMHOEKDECGGN(builder, MHOEKDECGGNOffset);
    DFHBOFFBKDB.AddMDFKCCMFFFD(builder, MDFKCCMFFFDOffset);
    DFHBOFFBKDB.AddEJKKOPBPJBN(builder, EJKKOPBPJBNOffset);
    return DFHBOFFBKDB.EndDFHBOFFBKDB(builder);
  }

  public static void StartDFHBOFFBKDB(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddEJKKOPBPJBN(FlatBufferBuilder builder, VectorOffset EJKKOPBPJBNOffset) { builder.AddOffset(0, EJKKOPBPJBNOffset.Value, 0); }
  public static VectorOffset CreateEJKKOPBPJBNVector(FlatBufferBuilder builder, Offset<JOGLEFDCEJI>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartEJKKOPBPJBNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMDFKCCMFFFD(FlatBufferBuilder builder, VectorOffset MDFKCCMFFFDOffset) { builder.AddOffset(1, MDFKCCMFFFDOffset.Value, 0); }
  public static VectorOffset CreateMDFKCCMFFFDVector(FlatBufferBuilder builder, Offset<JIMFBCIKKKJ>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMDFKCCMFFFDVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMHOEKDECGGN(FlatBufferBuilder builder, VectorOffset MHOEKDECGGNOffset) { builder.AddOffset(2, MHOEKDECGGNOffset.Value, 0); }
  public static VectorOffset CreateMHOEKDECGGNVector(FlatBufferBuilder builder, Offset<OLMJGOPCIKK>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMHOEKDECGGNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPCHLJEFOEFL(FlatBufferBuilder builder, VectorOffset PCHLJEFOEFLOffset) { builder.AddOffset(3, PCHLJEFOEFLOffset.Value, 0); }
  public static VectorOffset CreatePCHLJEFOEFLVector(FlatBufferBuilder builder, Offset<FFAOJIELJAC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartPCHLJEFOEFLVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddJKFLLEHIMLL(FlatBufferBuilder builder, VectorOffset JKFLLEHIMLLOffset) { builder.AddOffset(4, JKFLLEHIMLLOffset.Value, 0); }
  public static VectorOffset CreateJKFLLEHIMLLVector(FlatBufferBuilder builder, Offset<CJLNKNELECA>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartJKFLLEHIMLLVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddNJJINHMIOHN(FlatBufferBuilder builder, VectorOffset NJJINHMIOHNOffset) { builder.AddOffset(5, NJJINHMIOHNOffset.Value, 0); }
  public static VectorOffset CreateNJJINHMIOHNVector(FlatBufferBuilder builder, Offset<NOAPHCIKEID>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNJJINHMIOHNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<DFHBOFFBKDB> EndDFHBOFFBKDB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DFHBOFFBKDB>(o);
  }
};

