// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class DNHKFIKECGD : Table {
  public static DNHKFIKECGD GetRootAsDNHKFIKECGD(ByteBuffer _bb) { return GetRootAsDNHKFIKECGD(_bb, new DNHKFIKECGD()); }
  public static DNHKFIKECGD GetRootAsDNHKFIKECGD(ByteBuffer _bb, DNHKFIKECGD obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public DNHKFIKECGD __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint MJOCIHPPKNO { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int GetHFOJCEBNHCI(int j) { int o = __offset(6); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int HFOJCEBNHCILength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetHFOJCEBNHCIBytes() { return __vector_as_arraysegment(6); }

  public static Offset<DNHKFIKECGD> CreateDNHKFIKECGD(FlatBufferBuilder builder,
      uint MJOCIHPPKNO = 0,
      VectorOffset HFOJCEBNHCIOffset = default(VectorOffset)) {
    builder.StartObject(2);
    DNHKFIKECGD.AddHFOJCEBNHCI(builder, HFOJCEBNHCIOffset);
    DNHKFIKECGD.AddMJOCIHPPKNO(builder, MJOCIHPPKNO);
    return DNHKFIKECGD.EndDNHKFIKECGD(builder);
  }

  public static void StartDNHKFIKECGD(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMJOCIHPPKNO(FlatBufferBuilder builder, uint MJOCIHPPKNO) { builder.AddUint(0, MJOCIHPPKNO, 0); }
  public static void AddHFOJCEBNHCI(FlatBufferBuilder builder, VectorOffset HFOJCEBNHCIOffset) { builder.AddOffset(1, HFOJCEBNHCIOffset.Value, 0); }
  public static VectorOffset CreateHFOJCEBNHCIVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartHFOJCEBNHCIVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<DNHKFIKECGD> EndDNHKFIKECGD(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DNHKFIKECGD>(o);
  }
};

