// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class FELDPFHIOHB : Table {
  public static FELDPFHIOHB GetRootAsFELDPFHIOHB(ByteBuffer _bb) { return GetRootAsFELDPFHIOHB(_bb, new FELDPFHIOHB()); }
  public static FELDPFHIOHB GetRootAsFELDPFHIOHB(ByteBuffer _bb, FELDPFHIOHB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public FELDPFHIOHB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint CFDDADEOMJE { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KCDJCBMMALB { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JDDPFMAIEJK { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ALGLINABMBO { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint BBPHAPFBFHK { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint OPEDKFOOFMO { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CLGDAMPNKAA { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint GJEJFAJHBME { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JPNENGEPDED { get { int o = __offset(20); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JPBEMBKMEON { get { int o = __offset(22); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ALNLKFDILHL { get { int o = __offset(24); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint EHJPHAAHMEF { get { int o = __offset(26); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint FKICJENKKIC { get { int o = __offset(28); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint INBPHKHGIAM { get { int o = __offset(30); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint IMPIDEOCBKK { get { int o = __offset(32); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint EELICAHAECD { get { int o = __offset(34); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JKDAMKCJMLD { get { int o = __offset(36); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<FELDPFHIOHB> CreateFELDPFHIOHB(FlatBufferBuilder builder,
      uint CFDDADEOMJE = 0,
      uint KCDJCBMMALB = 0,
      uint JDDPFMAIEJK = 0,
      uint ALGLINABMBO = 0,
      uint BBPHAPFBFHK = 0,
      uint OPEDKFOOFMO = 0,
      uint CLGDAMPNKAA = 0,
      uint GJEJFAJHBME = 0,
      uint JPNENGEPDED = 0,
      uint JPBEMBKMEON = 0,
      uint ALNLKFDILHL = 0,
      uint EHJPHAAHMEF = 0,
      uint FKICJENKKIC = 0,
      uint INBPHKHGIAM = 0,
      uint IMPIDEOCBKK = 0,
      uint EELICAHAECD = 0,
      uint JKDAMKCJMLD = 0) {
    builder.StartObject(17);
    FELDPFHIOHB.AddJKDAMKCJMLD(builder, JKDAMKCJMLD);
    FELDPFHIOHB.AddEELICAHAECD(builder, EELICAHAECD);
    FELDPFHIOHB.AddIMPIDEOCBKK(builder, IMPIDEOCBKK);
    FELDPFHIOHB.AddINBPHKHGIAM(builder, INBPHKHGIAM);
    FELDPFHIOHB.AddFKICJENKKIC(builder, FKICJENKKIC);
    FELDPFHIOHB.AddEHJPHAAHMEF(builder, EHJPHAAHMEF);
    FELDPFHIOHB.AddALNLKFDILHL(builder, ALNLKFDILHL);
    FELDPFHIOHB.AddJPBEMBKMEON(builder, JPBEMBKMEON);
    FELDPFHIOHB.AddJPNENGEPDED(builder, JPNENGEPDED);
    FELDPFHIOHB.AddGJEJFAJHBME(builder, GJEJFAJHBME);
    FELDPFHIOHB.AddCLGDAMPNKAA(builder, CLGDAMPNKAA);
    FELDPFHIOHB.AddOPEDKFOOFMO(builder, OPEDKFOOFMO);
    FELDPFHIOHB.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    FELDPFHIOHB.AddALGLINABMBO(builder, ALGLINABMBO);
    FELDPFHIOHB.AddJDDPFMAIEJK(builder, JDDPFMAIEJK);
    FELDPFHIOHB.AddKCDJCBMMALB(builder, KCDJCBMMALB);
    FELDPFHIOHB.AddCFDDADEOMJE(builder, CFDDADEOMJE);
    return FELDPFHIOHB.EndFELDPFHIOHB(builder);
  }

  public static void StartFELDPFHIOHB(FlatBufferBuilder builder) { builder.StartObject(17); }
  public static void AddCFDDADEOMJE(FlatBufferBuilder builder, uint CFDDADEOMJE) { builder.AddUint(0, CFDDADEOMJE, 0); }
  public static void AddKCDJCBMMALB(FlatBufferBuilder builder, uint KCDJCBMMALB) { builder.AddUint(1, KCDJCBMMALB, 0); }
  public static void AddJDDPFMAIEJK(FlatBufferBuilder builder, uint JDDPFMAIEJK) { builder.AddUint(2, JDDPFMAIEJK, 0); }
  public static void AddALGLINABMBO(FlatBufferBuilder builder, uint ALGLINABMBO) { builder.AddUint(3, ALGLINABMBO, 0); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(4, BBPHAPFBFHK, 0); }
  public static void AddOPEDKFOOFMO(FlatBufferBuilder builder, uint OPEDKFOOFMO) { builder.AddUint(5, OPEDKFOOFMO, 0); }
  public static void AddCLGDAMPNKAA(FlatBufferBuilder builder, uint CLGDAMPNKAA) { builder.AddUint(6, CLGDAMPNKAA, 0); }
  public static void AddGJEJFAJHBME(FlatBufferBuilder builder, uint GJEJFAJHBME) { builder.AddUint(7, GJEJFAJHBME, 0); }
  public static void AddJPNENGEPDED(FlatBufferBuilder builder, uint JPNENGEPDED) { builder.AddUint(8, JPNENGEPDED, 0); }
  public static void AddJPBEMBKMEON(FlatBufferBuilder builder, uint JPBEMBKMEON) { builder.AddUint(9, JPBEMBKMEON, 0); }
  public static void AddALNLKFDILHL(FlatBufferBuilder builder, uint ALNLKFDILHL) { builder.AddUint(10, ALNLKFDILHL, 0); }
  public static void AddEHJPHAAHMEF(FlatBufferBuilder builder, uint EHJPHAAHMEF) { builder.AddUint(11, EHJPHAAHMEF, 0); }
  public static void AddFKICJENKKIC(FlatBufferBuilder builder, uint FKICJENKKIC) { builder.AddUint(12, FKICJENKKIC, 0); }
  public static void AddINBPHKHGIAM(FlatBufferBuilder builder, uint INBPHKHGIAM) { builder.AddUint(13, INBPHKHGIAM, 0); }
  public static void AddIMPIDEOCBKK(FlatBufferBuilder builder, uint IMPIDEOCBKK) { builder.AddUint(14, IMPIDEOCBKK, 0); }
  public static void AddEELICAHAECD(FlatBufferBuilder builder, uint EELICAHAECD) { builder.AddUint(15, EELICAHAECD, 0); }
  public static void AddJKDAMKCJMLD(FlatBufferBuilder builder, uint JKDAMKCJMLD) { builder.AddUint(16, JKDAMKCJMLD, 0); }
  public static Offset<FELDPFHIOHB> EndFELDPFHIOHB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FELDPFHIOHB>(o);
  }
};

