// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GDOALKDMNGG : Table {
  public static GDOALKDMNGG GetRootAsGDOALKDMNGG(ByteBuffer _bb) { return GetRootAsGDOALKDMNGG(_bb, new GDOALKDMNGG()); }
  public static GDOALKDMNGG GetRootAsGDOALKDMNGG(ByteBuffer _bb, GDOALKDMNGG obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GDOALKDMNGG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string IIDCFMHCPLJ { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIDCFMHCPLJBytes() { return __vector_as_arraysegment(4); }
  public uint MAIJBDCJPNJ { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint HEMLBADKAOA { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string MKDFHLALNAF { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetMKDFHLALNAFBytes() { return __vector_as_arraysegment(10); }
  public uint MCHOEAGDGJP { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LLJNABNBDMN { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DJHKCHMBGHC { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint BCKOLCDDIAG { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KPJEPCJKIJJ { get { int o = __offset(20); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LKIBIHGHEMA { get { int o = __offset(22); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ANELKJCGJJL { get { int o = __offset(24); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AEOKLKJAKHB { get { int o = __offset(26); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint OGBOPHDAMCI { get { int o = __offset(28); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint HGFJBAJCFNF { get { int o = __offset(30); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string HAEMDABJFJF { get { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetHAEMDABJFJFBytes() { return __vector_as_arraysegment(32); }
  public int BNOHOIBDHLP { get { int o = __offset(34); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string NNKLANONDOM { get { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNNKLANONDOMBytes() { return __vector_as_arraysegment(36); }
  public uint LENBJLOPKLE { get { int o = __offset(38); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string EMNAOOMCCGD { get { int o = __offset(40); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetEMNAOOMCCGDBytes() { return __vector_as_arraysegment(40); }
  public int ODMLFHELAJK { get { int o = __offset(42); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int JOIACOFCFAA { get { int o = __offset(44); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetCLEFGBLBDGJ(int j) { int o = __offset(46); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int CLEFGBLBDGJLength { get { int o = __offset(46); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCLEFGBLBDGJBytes() { return __vector_as_arraysegment(46); }
  public int MHPCFPIINFL { get { int o = __offset(48); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public uint JFNKDHPAEGD { get { int o = __offset(50); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KIPKMBIKLDO { get { int o = __offset(52); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<GDOALKDMNGG> CreateGDOALKDMNGG(FlatBufferBuilder builder,
      StringOffset IIDCFMHCPLJOffset = default(StringOffset),
      uint MAIJBDCJPNJ = 0,
      uint HEMLBADKAOA = 0,
      StringOffset MKDFHLALNAFOffset = default(StringOffset),
      uint MCHOEAGDGJP = 0,
      uint LLJNABNBDMN = 0,
      uint DJHKCHMBGHC = 0,
      uint BCKOLCDDIAG = 0,
      uint KPJEPCJKIJJ = 0,
      uint LKIBIHGHEMA = 0,
      uint ANELKJCGJJL = 0,
      uint AEOKLKJAKHB = 0,
      uint OGBOPHDAMCI = 0,
      uint HGFJBAJCFNF = 0,
      StringOffset HAEMDABJFJFOffset = default(StringOffset),
      int BNOHOIBDHLP = 0,
      StringOffset NNKLANONDOMOffset = default(StringOffset),
      uint LENBJLOPKLE = 0,
      StringOffset EMNAOOMCCGDOffset = default(StringOffset),
      int ODMLFHELAJK = 0,
      int JOIACOFCFAA = 0,
      VectorOffset CLEFGBLBDGJOffset = default(VectorOffset),
      int MHPCFPIINFL = 0,
      uint JFNKDHPAEGD = 0,
      uint KIPKMBIKLDO = 0) {
    builder.StartObject(25);
    GDOALKDMNGG.AddKIPKMBIKLDO(builder, KIPKMBIKLDO);
    GDOALKDMNGG.AddJFNKDHPAEGD(builder, JFNKDHPAEGD);
    GDOALKDMNGG.AddMHPCFPIINFL(builder, MHPCFPIINFL);
    GDOALKDMNGG.AddCLEFGBLBDGJ(builder, CLEFGBLBDGJOffset);
    GDOALKDMNGG.AddJOIACOFCFAA(builder, JOIACOFCFAA);
    GDOALKDMNGG.AddODMLFHELAJK(builder, ODMLFHELAJK);
    GDOALKDMNGG.AddEMNAOOMCCGD(builder, EMNAOOMCCGDOffset);
    GDOALKDMNGG.AddLENBJLOPKLE(builder, LENBJLOPKLE);
    GDOALKDMNGG.AddNNKLANONDOM(builder, NNKLANONDOMOffset);
    GDOALKDMNGG.AddBNOHOIBDHLP(builder, BNOHOIBDHLP);
    GDOALKDMNGG.AddHAEMDABJFJF(builder, HAEMDABJFJFOffset);
    GDOALKDMNGG.AddHGFJBAJCFNF(builder, HGFJBAJCFNF);
    GDOALKDMNGG.AddOGBOPHDAMCI(builder, OGBOPHDAMCI);
    GDOALKDMNGG.AddAEOKLKJAKHB(builder, AEOKLKJAKHB);
    GDOALKDMNGG.AddANELKJCGJJL(builder, ANELKJCGJJL);
    GDOALKDMNGG.AddLKIBIHGHEMA(builder, LKIBIHGHEMA);
    GDOALKDMNGG.AddKPJEPCJKIJJ(builder, KPJEPCJKIJJ);
    GDOALKDMNGG.AddBCKOLCDDIAG(builder, BCKOLCDDIAG);
    GDOALKDMNGG.AddDJHKCHMBGHC(builder, DJHKCHMBGHC);
    GDOALKDMNGG.AddLLJNABNBDMN(builder, LLJNABNBDMN);
    GDOALKDMNGG.AddMCHOEAGDGJP(builder, MCHOEAGDGJP);
    GDOALKDMNGG.AddMKDFHLALNAF(builder, MKDFHLALNAFOffset);
    GDOALKDMNGG.AddHEMLBADKAOA(builder, HEMLBADKAOA);
    GDOALKDMNGG.AddMAIJBDCJPNJ(builder, MAIJBDCJPNJ);
    GDOALKDMNGG.AddIIDCFMHCPLJ(builder, IIDCFMHCPLJOffset);
    return GDOALKDMNGG.EndGDOALKDMNGG(builder);
  }

  public static void StartGDOALKDMNGG(FlatBufferBuilder builder) { builder.StartObject(25); }
  public static void AddIIDCFMHCPLJ(FlatBufferBuilder builder, StringOffset IIDCFMHCPLJOffset) { builder.AddOffset(0, IIDCFMHCPLJOffset.Value, 0); }
  public static void AddMAIJBDCJPNJ(FlatBufferBuilder builder, uint MAIJBDCJPNJ) { builder.AddUint(1, MAIJBDCJPNJ, 0); }
  public static void AddHEMLBADKAOA(FlatBufferBuilder builder, uint HEMLBADKAOA) { builder.AddUint(2, HEMLBADKAOA, 0); }
  public static void AddMKDFHLALNAF(FlatBufferBuilder builder, StringOffset MKDFHLALNAFOffset) { builder.AddOffset(3, MKDFHLALNAFOffset.Value, 0); }
  public static void AddMCHOEAGDGJP(FlatBufferBuilder builder, uint MCHOEAGDGJP) { builder.AddUint(4, MCHOEAGDGJP, 0); }
  public static void AddLLJNABNBDMN(FlatBufferBuilder builder, uint LLJNABNBDMN) { builder.AddUint(5, LLJNABNBDMN, 0); }
  public static void AddDJHKCHMBGHC(FlatBufferBuilder builder, uint DJHKCHMBGHC) { builder.AddUint(6, DJHKCHMBGHC, 0); }
  public static void AddBCKOLCDDIAG(FlatBufferBuilder builder, uint BCKOLCDDIAG) { builder.AddUint(7, BCKOLCDDIAG, 0); }
  public static void AddKPJEPCJKIJJ(FlatBufferBuilder builder, uint KPJEPCJKIJJ) { builder.AddUint(8, KPJEPCJKIJJ, 0); }
  public static void AddLKIBIHGHEMA(FlatBufferBuilder builder, uint LKIBIHGHEMA) { builder.AddUint(9, LKIBIHGHEMA, 0); }
  public static void AddANELKJCGJJL(FlatBufferBuilder builder, uint ANELKJCGJJL) { builder.AddUint(10, ANELKJCGJJL, 0); }
  public static void AddAEOKLKJAKHB(FlatBufferBuilder builder, uint AEOKLKJAKHB) { builder.AddUint(11, AEOKLKJAKHB, 0); }
  public static void AddOGBOPHDAMCI(FlatBufferBuilder builder, uint OGBOPHDAMCI) { builder.AddUint(12, OGBOPHDAMCI, 0); }
  public static void AddHGFJBAJCFNF(FlatBufferBuilder builder, uint HGFJBAJCFNF) { builder.AddUint(13, HGFJBAJCFNF, 0); }
  public static void AddHAEMDABJFJF(FlatBufferBuilder builder, StringOffset HAEMDABJFJFOffset) { builder.AddOffset(14, HAEMDABJFJFOffset.Value, 0); }
  public static void AddBNOHOIBDHLP(FlatBufferBuilder builder, int BNOHOIBDHLP) { builder.AddInt(15, BNOHOIBDHLP, 0); }
  public static void AddNNKLANONDOM(FlatBufferBuilder builder, StringOffset NNKLANONDOMOffset) { builder.AddOffset(16, NNKLANONDOMOffset.Value, 0); }
  public static void AddLENBJLOPKLE(FlatBufferBuilder builder, uint LENBJLOPKLE) { builder.AddUint(17, LENBJLOPKLE, 0); }
  public static void AddEMNAOOMCCGD(FlatBufferBuilder builder, StringOffset EMNAOOMCCGDOffset) { builder.AddOffset(18, EMNAOOMCCGDOffset.Value, 0); }
  public static void AddODMLFHELAJK(FlatBufferBuilder builder, int ODMLFHELAJK) { builder.AddInt(19, ODMLFHELAJK, 0); }
  public static void AddJOIACOFCFAA(FlatBufferBuilder builder, int JOIACOFCFAA) { builder.AddInt(20, JOIACOFCFAA, 0); }
  public static void AddCLEFGBLBDGJ(FlatBufferBuilder builder, VectorOffset CLEFGBLBDGJOffset) { builder.AddOffset(21, CLEFGBLBDGJOffset.Value, 0); }
  public static VectorOffset CreateCLEFGBLBDGJVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCLEFGBLBDGJVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMHPCFPIINFL(FlatBufferBuilder builder, int MHPCFPIINFL) { builder.AddInt(22, MHPCFPIINFL, 0); }
  public static void AddJFNKDHPAEGD(FlatBufferBuilder builder, uint JFNKDHPAEGD) { builder.AddUint(23, JFNKDHPAEGD, 0); }
  public static void AddKIPKMBIKLDO(FlatBufferBuilder builder, uint KIPKMBIKLDO) { builder.AddUint(24, KIPKMBIKLDO, 0); }
  public static Offset<GDOALKDMNGG> EndGDOALKDMNGG(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GDOALKDMNGG>(o);
  }
};

