// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GHBCOHFGDMM : Table {
  public static GHBCOHFGDMM GetRootAsGHBCOHFGDMM(ByteBuffer _bb) { return GetRootAsGHBCOHFGDMM(_bb, new GHBCOHFGDMM()); }
  public static GHBCOHFGDMM GetRootAsGHBCOHFGDMM(ByteBuffer _bb, GHBCOHFGDMM obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GHBCOHFGDMM __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint NOAABMLLCEI { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LOIDCOGHAOJ { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DMEMJNAEDHP { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JEOALGELOHK { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int GetGNGJHKKAAIN(int j) { int o = __offset(12); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int GNGJHKKAAINLength { get { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetGNGJHKKAAINBytes() { return __vector_as_arraysegment(12); }

  public static Offset<GHBCOHFGDMM> CreateGHBCOHFGDMM(FlatBufferBuilder builder,
      uint NOAABMLLCEI = 0,
      uint LOIDCOGHAOJ = 0,
      uint DMEMJNAEDHP = 0,
      uint JEOALGELOHK = 0,
      VectorOffset GNGJHKKAAINOffset = default(VectorOffset)) {
    builder.StartObject(5);
    GHBCOHFGDMM.AddGNGJHKKAAIN(builder, GNGJHKKAAINOffset);
    GHBCOHFGDMM.AddJEOALGELOHK(builder, JEOALGELOHK);
    GHBCOHFGDMM.AddDMEMJNAEDHP(builder, DMEMJNAEDHP);
    GHBCOHFGDMM.AddLOIDCOGHAOJ(builder, LOIDCOGHAOJ);
    GHBCOHFGDMM.AddNOAABMLLCEI(builder, NOAABMLLCEI);
    return GHBCOHFGDMM.EndGHBCOHFGDMM(builder);
  }

  public static void StartGHBCOHFGDMM(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddNOAABMLLCEI(FlatBufferBuilder builder, uint NOAABMLLCEI) { builder.AddUint(0, NOAABMLLCEI, 0); }
  public static void AddLOIDCOGHAOJ(FlatBufferBuilder builder, uint LOIDCOGHAOJ) { builder.AddUint(1, LOIDCOGHAOJ, 0); }
  public static void AddDMEMJNAEDHP(FlatBufferBuilder builder, uint DMEMJNAEDHP) { builder.AddUint(2, DMEMJNAEDHP, 0); }
  public static void AddJEOALGELOHK(FlatBufferBuilder builder, uint JEOALGELOHK) { builder.AddUint(3, JEOALGELOHK, 0); }
  public static void AddGNGJHKKAAIN(FlatBufferBuilder builder, VectorOffset GNGJHKKAAINOffset) { builder.AddOffset(4, GNGJHKKAAINOffset.Value, 0); }
  public static VectorOffset CreateGNGJHKKAAINVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartGNGJHKKAAINVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GHBCOHFGDMM> EndGHBCOHFGDMM(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GHBCOHFGDMM>(o);
  }
};

