// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GJNHKIDNFJO : Table {
  public static GJNHKIDNFJO GetRootAsGJNHKIDNFJO(ByteBuffer _bb) { return GetRootAsGJNHKIDNFJO(_bb, new GJNHKIDNFJO()); }
  public static GJNHKIDNFJO GetRootAsGJNHKIDNFJO(ByteBuffer _bb, GJNHKIDNFJO obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GJNHKIDNFJO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int LLJMKBDBIGN { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetCLFGGLFAJKH(int j) { int o = __offset(6); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int CLFGGLFAJKHLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCLFGGLFAJKHBytes() { return __vector_as_arraysegment(6); }

  public static Offset<GJNHKIDNFJO> CreateGJNHKIDNFJO(FlatBufferBuilder builder,
      int LLJMKBDBIGN = 0,
      VectorOffset CLFGGLFAJKHOffset = default(VectorOffset)) {
    builder.StartObject(2);
    GJNHKIDNFJO.AddCLFGGLFAJKH(builder, CLFGGLFAJKHOffset);
    GJNHKIDNFJO.AddLLJMKBDBIGN(builder, LLJMKBDBIGN);
    return GJNHKIDNFJO.EndGJNHKIDNFJO(builder);
  }

  public static void StartGJNHKIDNFJO(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddLLJMKBDBIGN(FlatBufferBuilder builder, int LLJMKBDBIGN) { builder.AddInt(0, LLJMKBDBIGN, 0); }
  public static void AddCLFGGLFAJKH(FlatBufferBuilder builder, VectorOffset CLFGGLFAJKHOffset) { builder.AddOffset(1, CLFGGLFAJKHOffset.Value, 0); }
  public static VectorOffset CreateCLFGGLFAJKHVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCLFGGLFAJKHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GJNHKIDNFJO> EndGJNHKIDNFJO(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GJNHKIDNFJO>(o);
  }
};

