// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GMAHGBPDAPH : Table {
  public static GMAHGBPDAPH GetRootAsGMAHGBPDAPH(ByteBuffer _bb) { return GetRootAsGMAHGBPDAPH(_bb, new GMAHGBPDAPH()); }
  public static GMAHGBPDAPH GetRootAsGMAHGBPDAPH(ByteBuffer _bb, GMAHGBPDAPH obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GMAHGBPDAPH __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int CFLMCGOJJJD { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int OFMGALJGDAO { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public uint DPHNIALHDJK { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint HDGPONIHIBP { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint GFPLLOGJMHE { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint EJNIJBKBNGE { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DGMDFCHIBKD { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<GMAHGBPDAPH> CreateGMAHGBPDAPH(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      int CFLMCGOJJJD = 0,
      int OFMGALJGDAO = 0,
      uint DPHNIALHDJK = 0,
      uint HDGPONIHIBP = 0,
      uint GFPLLOGJMHE = 0,
      uint EJNIJBKBNGE = 0,
      uint DGMDFCHIBKD = 0) {
    builder.StartObject(8);
    GMAHGBPDAPH.AddDGMDFCHIBKD(builder, DGMDFCHIBKD);
    GMAHGBPDAPH.AddEJNIJBKBNGE(builder, EJNIJBKBNGE);
    GMAHGBPDAPH.AddGFPLLOGJMHE(builder, GFPLLOGJMHE);
    GMAHGBPDAPH.AddHDGPONIHIBP(builder, HDGPONIHIBP);
    GMAHGBPDAPH.AddDPHNIALHDJK(builder, DPHNIALHDJK);
    GMAHGBPDAPH.AddOFMGALJGDAO(builder, OFMGALJGDAO);
    GMAHGBPDAPH.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    GMAHGBPDAPH.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return GMAHGBPDAPH.EndGMAHGBPDAPH(builder);
  }

  public static void StartGMAHGBPDAPH(FlatBufferBuilder builder) { builder.StartObject(8); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, int CFLMCGOJJJD) { builder.AddInt(1, CFLMCGOJJJD, 0); }
  public static void AddOFMGALJGDAO(FlatBufferBuilder builder, int OFMGALJGDAO) { builder.AddInt(2, OFMGALJGDAO, 0); }
  public static void AddDPHNIALHDJK(FlatBufferBuilder builder, uint DPHNIALHDJK) { builder.AddUint(3, DPHNIALHDJK, 0); }
  public static void AddHDGPONIHIBP(FlatBufferBuilder builder, uint HDGPONIHIBP) { builder.AddUint(4, HDGPONIHIBP, 0); }
  public static void AddGFPLLOGJMHE(FlatBufferBuilder builder, uint GFPLLOGJMHE) { builder.AddUint(5, GFPLLOGJMHE, 0); }
  public static void AddEJNIJBKBNGE(FlatBufferBuilder builder, uint EJNIJBKBNGE) { builder.AddUint(6, EJNIJBKBNGE, 0); }
  public static void AddDGMDFCHIBKD(FlatBufferBuilder builder, uint DGMDFCHIBKD) { builder.AddUint(7, DGMDFCHIBKD, 0); }
  public static Offset<GMAHGBPDAPH> EndGMAHGBPDAPH(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GMAHGBPDAPH>(o);
  }
};

