// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GMCDKDCBFFK : Table {
  public static GMCDKDCBFFK GetRootAsGMCDKDCBFFK(ByteBuffer _bb) { return GetRootAsGMCDKDCBFFK(_bb, new GMCDKDCBFFK()); }
  public static GMCDKDCBFFK GetRootAsGMCDKDCBFFK(ByteBuffer _bb, GMCDKDCBFFK obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GMCDKDCBFFK __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint CIOGNKLHPDE { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint OBIIODKLNFO { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<GMCDKDCBFFK> CreateGMCDKDCBFFK(FlatBufferBuilder builder,
      uint CIOGNKLHPDE = 0,
      uint OBIIODKLNFO = 0) {
    builder.StartObject(2);
    GMCDKDCBFFK.AddOBIIODKLNFO(builder, OBIIODKLNFO);
    GMCDKDCBFFK.AddCIOGNKLHPDE(builder, CIOGNKLHPDE);
    return GMCDKDCBFFK.EndGMCDKDCBFFK(builder);
  }

  public static void StartGMCDKDCBFFK(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddCIOGNKLHPDE(FlatBufferBuilder builder, uint CIOGNKLHPDE) { builder.AddUint(0, CIOGNKLHPDE, 0); }
  public static void AddOBIIODKLNFO(FlatBufferBuilder builder, uint OBIIODKLNFO) { builder.AddUint(1, OBIIODKLNFO, 0); }
  public static Offset<GMCDKDCBFFK> EndGMCDKDCBFFK(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GMCDKDCBFFK>(o);
  }
};

