// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GMNMPFMGIBP : Table {
  public static GMNMPFMGIBP GetRootAsGMNMPFMGIBP(ByteBuffer _bb) { return GetRootAsGMNMPFMGIBP(_bb, new GMNMPFMGIBP()); }
  public static GMNMPFMGIBP GetRootAsGMNMPFMGIBP(ByteBuffer _bb, GMNMPFMGIBP obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GMNMPFMGIBP __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string IIDCFMHCPLJ { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIDCFMHCPLJBytes() { return __vector_as_arraysegment(4); }
  public string HAEJDOGGKPC { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetHAEJDOGGKPCBytes() { return __vector_as_arraysegment(6); }
  public uint MAIJBDCJPNJ { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string MKDFHLALNAF { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetMKDFHLALNAFBytes() { return __vector_as_arraysegment(10); }
  public uint MCHOEAGDGJP { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LLJNABNBDMN { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DEPHCHOBAJG { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DJHKCHMBGHC { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint BCKOLCDDIAG { get { int o = __offset(20); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LKIBIHGHEMA { get { int o = __offset(22); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ANELKJCGJJL { get { int o = __offset(24); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AEOKLKJAKHB { get { int o = __offset(26); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint OGBOPHDAMCI { get { int o = __offset(28); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint HGFJBAJCFNF { get { int o = __offset(30); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string HAEMDABJFJF { get { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetHAEMDABJFJFBytes() { return __vector_as_arraysegment(32); }
  public string PPCOEAIPHKA { get { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetPPCOEAIPHKABytes() { return __vector_as_arraysegment(34); }
  public int BNOHOIBDHLP { get { int o = __offset(36); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string NNKLANONDOM { get { int o = __offset(38); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNNKLANONDOMBytes() { return __vector_as_arraysegment(38); }
  public uint LENBJLOPKLE { get { int o = __offset(40); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int GetKNDBMPNNCGG(int j) { int o = __offset(42); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int KNDBMPNNCGGLength { get { int o = __offset(42); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetKNDBMPNNCGGBytes() { return __vector_as_arraysegment(42); }
  public string EMNAOOMCCGD { get { int o = __offset(44); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetEMNAOOMCCGDBytes() { return __vector_as_arraysegment(44); }
  public int ODMLFHELAJK { get { int o = __offset(46); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int JOIACOFCFAA { get { int o = __offset(48); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetCLEFGBLBDGJ(int j) { int o = __offset(50); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int CLEFGBLBDGJLength { get { int o = __offset(50); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCLEFGBLBDGJBytes() { return __vector_as_arraysegment(50); }
  public int KPCNGKDBMHA { get { int o = __offset(52); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<GMNMPFMGIBP> CreateGMNMPFMGIBP(FlatBufferBuilder builder,
      StringOffset IIDCFMHCPLJOffset = default(StringOffset),
      StringOffset HAEJDOGGKPCOffset = default(StringOffset),
      uint MAIJBDCJPNJ = 0,
      StringOffset MKDFHLALNAFOffset = default(StringOffset),
      uint MCHOEAGDGJP = 0,
      uint LLJNABNBDMN = 0,
      uint DEPHCHOBAJG = 0,
      uint DJHKCHMBGHC = 0,
      uint BCKOLCDDIAG = 0,
      uint LKIBIHGHEMA = 0,
      uint ANELKJCGJJL = 0,
      uint AEOKLKJAKHB = 0,
      uint OGBOPHDAMCI = 0,
      uint HGFJBAJCFNF = 0,
      StringOffset HAEMDABJFJFOffset = default(StringOffset),
      StringOffset PPCOEAIPHKAOffset = default(StringOffset),
      int BNOHOIBDHLP = 0,
      StringOffset NNKLANONDOMOffset = default(StringOffset),
      uint LENBJLOPKLE = 0,
      VectorOffset KNDBMPNNCGGOffset = default(VectorOffset),
      StringOffset EMNAOOMCCGDOffset = default(StringOffset),
      int ODMLFHELAJK = 0,
      int JOIACOFCFAA = 0,
      VectorOffset CLEFGBLBDGJOffset = default(VectorOffset),
      int KPCNGKDBMHA = 0) {
    builder.StartObject(25);
    GMNMPFMGIBP.AddKPCNGKDBMHA(builder, KPCNGKDBMHA);
    GMNMPFMGIBP.AddCLEFGBLBDGJ(builder, CLEFGBLBDGJOffset);
    GMNMPFMGIBP.AddJOIACOFCFAA(builder, JOIACOFCFAA);
    GMNMPFMGIBP.AddODMLFHELAJK(builder, ODMLFHELAJK);
    GMNMPFMGIBP.AddEMNAOOMCCGD(builder, EMNAOOMCCGDOffset);
    GMNMPFMGIBP.AddKNDBMPNNCGG(builder, KNDBMPNNCGGOffset);
    GMNMPFMGIBP.AddLENBJLOPKLE(builder, LENBJLOPKLE);
    GMNMPFMGIBP.AddNNKLANONDOM(builder, NNKLANONDOMOffset);
    GMNMPFMGIBP.AddBNOHOIBDHLP(builder, BNOHOIBDHLP);
    GMNMPFMGIBP.AddPPCOEAIPHKA(builder, PPCOEAIPHKAOffset);
    GMNMPFMGIBP.AddHAEMDABJFJF(builder, HAEMDABJFJFOffset);
    GMNMPFMGIBP.AddHGFJBAJCFNF(builder, HGFJBAJCFNF);
    GMNMPFMGIBP.AddOGBOPHDAMCI(builder, OGBOPHDAMCI);
    GMNMPFMGIBP.AddAEOKLKJAKHB(builder, AEOKLKJAKHB);
    GMNMPFMGIBP.AddANELKJCGJJL(builder, ANELKJCGJJL);
    GMNMPFMGIBP.AddLKIBIHGHEMA(builder, LKIBIHGHEMA);
    GMNMPFMGIBP.AddBCKOLCDDIAG(builder, BCKOLCDDIAG);
    GMNMPFMGIBP.AddDJHKCHMBGHC(builder, DJHKCHMBGHC);
    GMNMPFMGIBP.AddDEPHCHOBAJG(builder, DEPHCHOBAJG);
    GMNMPFMGIBP.AddLLJNABNBDMN(builder, LLJNABNBDMN);
    GMNMPFMGIBP.AddMCHOEAGDGJP(builder, MCHOEAGDGJP);
    GMNMPFMGIBP.AddMKDFHLALNAF(builder, MKDFHLALNAFOffset);
    GMNMPFMGIBP.AddMAIJBDCJPNJ(builder, MAIJBDCJPNJ);
    GMNMPFMGIBP.AddHAEJDOGGKPC(builder, HAEJDOGGKPCOffset);
    GMNMPFMGIBP.AddIIDCFMHCPLJ(builder, IIDCFMHCPLJOffset);
    return GMNMPFMGIBP.EndGMNMPFMGIBP(builder);
  }

  public static void StartGMNMPFMGIBP(FlatBufferBuilder builder) { builder.StartObject(25); }
  public static void AddIIDCFMHCPLJ(FlatBufferBuilder builder, StringOffset IIDCFMHCPLJOffset) { builder.AddOffset(0, IIDCFMHCPLJOffset.Value, 0); }
  public static void AddHAEJDOGGKPC(FlatBufferBuilder builder, StringOffset HAEJDOGGKPCOffset) { builder.AddOffset(1, HAEJDOGGKPCOffset.Value, 0); }
  public static void AddMAIJBDCJPNJ(FlatBufferBuilder builder, uint MAIJBDCJPNJ) { builder.AddUint(2, MAIJBDCJPNJ, 0); }
  public static void AddMKDFHLALNAF(FlatBufferBuilder builder, StringOffset MKDFHLALNAFOffset) { builder.AddOffset(3, MKDFHLALNAFOffset.Value, 0); }
  public static void AddMCHOEAGDGJP(FlatBufferBuilder builder, uint MCHOEAGDGJP) { builder.AddUint(4, MCHOEAGDGJP, 0); }
  public static void AddLLJNABNBDMN(FlatBufferBuilder builder, uint LLJNABNBDMN) { builder.AddUint(5, LLJNABNBDMN, 0); }
  public static void AddDEPHCHOBAJG(FlatBufferBuilder builder, uint DEPHCHOBAJG) { builder.AddUint(6, DEPHCHOBAJG, 0); }
  public static void AddDJHKCHMBGHC(FlatBufferBuilder builder, uint DJHKCHMBGHC) { builder.AddUint(7, DJHKCHMBGHC, 0); }
  public static void AddBCKOLCDDIAG(FlatBufferBuilder builder, uint BCKOLCDDIAG) { builder.AddUint(8, BCKOLCDDIAG, 0); }
  public static void AddLKIBIHGHEMA(FlatBufferBuilder builder, uint LKIBIHGHEMA) { builder.AddUint(9, LKIBIHGHEMA, 0); }
  public static void AddANELKJCGJJL(FlatBufferBuilder builder, uint ANELKJCGJJL) { builder.AddUint(10, ANELKJCGJJL, 0); }
  public static void AddAEOKLKJAKHB(FlatBufferBuilder builder, uint AEOKLKJAKHB) { builder.AddUint(11, AEOKLKJAKHB, 0); }
  public static void AddOGBOPHDAMCI(FlatBufferBuilder builder, uint OGBOPHDAMCI) { builder.AddUint(12, OGBOPHDAMCI, 0); }
  public static void AddHGFJBAJCFNF(FlatBufferBuilder builder, uint HGFJBAJCFNF) { builder.AddUint(13, HGFJBAJCFNF, 0); }
  public static void AddHAEMDABJFJF(FlatBufferBuilder builder, StringOffset HAEMDABJFJFOffset) { builder.AddOffset(14, HAEMDABJFJFOffset.Value, 0); }
  public static void AddPPCOEAIPHKA(FlatBufferBuilder builder, StringOffset PPCOEAIPHKAOffset) { builder.AddOffset(15, PPCOEAIPHKAOffset.Value, 0); }
  public static void AddBNOHOIBDHLP(FlatBufferBuilder builder, int BNOHOIBDHLP) { builder.AddInt(16, BNOHOIBDHLP, 0); }
  public static void AddNNKLANONDOM(FlatBufferBuilder builder, StringOffset NNKLANONDOMOffset) { builder.AddOffset(17, NNKLANONDOMOffset.Value, 0); }
  public static void AddLENBJLOPKLE(FlatBufferBuilder builder, uint LENBJLOPKLE) { builder.AddUint(18, LENBJLOPKLE, 0); }
  public static void AddKNDBMPNNCGG(FlatBufferBuilder builder, VectorOffset KNDBMPNNCGGOffset) { builder.AddOffset(19, KNDBMPNNCGGOffset.Value, 0); }
  public static VectorOffset CreateKNDBMPNNCGGVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartKNDBMPNNCGGVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEMNAOOMCCGD(FlatBufferBuilder builder, StringOffset EMNAOOMCCGDOffset) { builder.AddOffset(20, EMNAOOMCCGDOffset.Value, 0); }
  public static void AddODMLFHELAJK(FlatBufferBuilder builder, int ODMLFHELAJK) { builder.AddInt(21, ODMLFHELAJK, 0); }
  public static void AddJOIACOFCFAA(FlatBufferBuilder builder, int JOIACOFCFAA) { builder.AddInt(22, JOIACOFCFAA, 0); }
  public static void AddCLEFGBLBDGJ(FlatBufferBuilder builder, VectorOffset CLEFGBLBDGJOffset) { builder.AddOffset(23, CLEFGBLBDGJOffset.Value, 0); }
  public static VectorOffset CreateCLEFGBLBDGJVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCLEFGBLBDGJVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddKPCNGKDBMHA(FlatBufferBuilder builder, int KPCNGKDBMHA) { builder.AddInt(24, KPCNGKDBMHA, 0); }
  public static Offset<GMNMPFMGIBP> EndGMNMPFMGIBP(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GMNMPFMGIBP>(o);
  }
};

