// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HDAONNHPGDA : Table {
  public static HDAONNHPGDA GetRootAsHDAONNHPGDA(ByteBuffer _bb) { return GetRootAsHDAONNHPGDA(_bb, new HDAONNHPGDA()); }
  public static HDAONNHPGDA GetRootAsHDAONNHPGDA(ByteBuffer _bb, HDAONNHPGDA obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HDAONNHPGDA __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string AGOIMGHMGOH { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetAGOIMGHMGOHBytes() { return __vector_as_arraysegment(4); }
  public string KJFEBMBHKOC { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetKJFEBMBHKOCBytes() { return __vector_as_arraysegment(6); }

  public static Offset<HDAONNHPGDA> CreateHDAONNHPGDA(FlatBufferBuilder builder,
      StringOffset AGOIMGHMGOHOffset = default(StringOffset),
      StringOffset KJFEBMBHKOCOffset = default(StringOffset)) {
    builder.StartObject(2);
    HDAONNHPGDA.AddKJFEBMBHKOC(builder, KJFEBMBHKOCOffset);
    HDAONNHPGDA.AddAGOIMGHMGOH(builder, AGOIMGHMGOHOffset);
    return HDAONNHPGDA.EndHDAONNHPGDA(builder);
  }

  public static void StartHDAONNHPGDA(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAGOIMGHMGOH(FlatBufferBuilder builder, StringOffset AGOIMGHMGOHOffset) { builder.AddOffset(0, AGOIMGHMGOHOffset.Value, 0); }
  public static void AddKJFEBMBHKOC(FlatBufferBuilder builder, StringOffset KJFEBMBHKOCOffset) { builder.AddOffset(1, KJFEBMBHKOCOffset.Value, 0); }
  public static Offset<HDAONNHPGDA> EndHDAONNHPGDA(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HDAONNHPGDA>(o);
  }
};

