// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HDMBLGJMPMA : Table {
  public static HDMBLGJMPMA GetRootAsHDMBLGJMPMA(ByteBuffer _bb) { return GetRootAsHDMBLGJMPMA(_bb, new HDMBLGJMPMA()); }
  public static HDMBLGJMPMA GetRootAsHDMBLGJMPMA(ByteBuffer _bb, HDMBLGJMPMA obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HDMBLGJMPMA __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int FANPJEPOAFK { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int PENNDFJDJMP { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int CNOIMMHCCIH { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int IDHMEJECPBO { get { int o = __offset(10); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<HDMBLGJMPMA> CreateHDMBLGJMPMA(FlatBufferBuilder builder,
      int FANPJEPOAFK = 0,
      int PENNDFJDJMP = 0,
      int CNOIMMHCCIH = 0,
      int IDHMEJECPBO = 0) {
    builder.StartObject(4);
    HDMBLGJMPMA.AddIDHMEJECPBO(builder, IDHMEJECPBO);
    HDMBLGJMPMA.AddCNOIMMHCCIH(builder, CNOIMMHCCIH);
    HDMBLGJMPMA.AddPENNDFJDJMP(builder, PENNDFJDJMP);
    HDMBLGJMPMA.AddFANPJEPOAFK(builder, FANPJEPOAFK);
    return HDMBLGJMPMA.EndHDMBLGJMPMA(builder);
  }

  public static void StartHDMBLGJMPMA(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddFANPJEPOAFK(FlatBufferBuilder builder, int FANPJEPOAFK) { builder.AddInt(0, FANPJEPOAFK, 0); }
  public static void AddPENNDFJDJMP(FlatBufferBuilder builder, int PENNDFJDJMP) { builder.AddInt(1, PENNDFJDJMP, 0); }
  public static void AddCNOIMMHCCIH(FlatBufferBuilder builder, int CNOIMMHCCIH) { builder.AddInt(2, CNOIMMHCCIH, 0); }
  public static void AddIDHMEJECPBO(FlatBufferBuilder builder, int IDHMEJECPBO) { builder.AddInt(3, IDHMEJECPBO, 0); }
  public static Offset<HDMBLGJMPMA> EndHDMBLGJMPMA(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HDMBLGJMPMA>(o);
  }
};

