// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HGBICHMJHMI : Table {
  public static HGBICHMJHMI GetRootAsHGBICHMJHMI(ByteBuffer _bb) { return GetRootAsHGBICHMJHMI(_bb, new HGBICHMJHMI()); }
  public static HGBICHMJHMI GetRootAsHGBICHMJHMI(ByteBuffer _bb, HGBICHMJHMI obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HGBICHMJHMI __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string IIDCFMHCPLJ { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIDCFMHCPLJBytes() { return __vector_as_arraysegment(4); }
  public uint MAIJBDCJPNJ { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint MCHOEAGDGJP { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LLJNABNBDMN { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AEOKLKJAKHB { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint APJPCEEAANA { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KPMGJEELOEI { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int BNOHOIBDHLP { get { int o = __offset(18); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetCLEFGBLBDGJ(int j) { int o = __offset(20); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int CLEFGBLBDGJLength { get { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCLEFGBLBDGJBytes() { return __vector_as_arraysegment(20); }

  public static Offset<HGBICHMJHMI> CreateHGBICHMJHMI(FlatBufferBuilder builder,
      StringOffset IIDCFMHCPLJOffset = default(StringOffset),
      uint MAIJBDCJPNJ = 0,
      uint MCHOEAGDGJP = 0,
      uint LLJNABNBDMN = 0,
      uint AEOKLKJAKHB = 0,
      uint APJPCEEAANA = 0,
      uint KPMGJEELOEI = 0,
      int BNOHOIBDHLP = 0,
      VectorOffset CLEFGBLBDGJOffset = default(VectorOffset)) {
    builder.StartObject(9);
    HGBICHMJHMI.AddCLEFGBLBDGJ(builder, CLEFGBLBDGJOffset);
    HGBICHMJHMI.AddBNOHOIBDHLP(builder, BNOHOIBDHLP);
    HGBICHMJHMI.AddKPMGJEELOEI(builder, KPMGJEELOEI);
    HGBICHMJHMI.AddAPJPCEEAANA(builder, APJPCEEAANA);
    HGBICHMJHMI.AddAEOKLKJAKHB(builder, AEOKLKJAKHB);
    HGBICHMJHMI.AddLLJNABNBDMN(builder, LLJNABNBDMN);
    HGBICHMJHMI.AddMCHOEAGDGJP(builder, MCHOEAGDGJP);
    HGBICHMJHMI.AddMAIJBDCJPNJ(builder, MAIJBDCJPNJ);
    HGBICHMJHMI.AddIIDCFMHCPLJ(builder, IIDCFMHCPLJOffset);
    return HGBICHMJHMI.EndHGBICHMJHMI(builder);
  }

  public static void StartHGBICHMJHMI(FlatBufferBuilder builder) { builder.StartObject(9); }
  public static void AddIIDCFMHCPLJ(FlatBufferBuilder builder, StringOffset IIDCFMHCPLJOffset) { builder.AddOffset(0, IIDCFMHCPLJOffset.Value, 0); }
  public static void AddMAIJBDCJPNJ(FlatBufferBuilder builder, uint MAIJBDCJPNJ) { builder.AddUint(1, MAIJBDCJPNJ, 0); }
  public static void AddMCHOEAGDGJP(FlatBufferBuilder builder, uint MCHOEAGDGJP) { builder.AddUint(2, MCHOEAGDGJP, 0); }
  public static void AddLLJNABNBDMN(FlatBufferBuilder builder, uint LLJNABNBDMN) { builder.AddUint(3, LLJNABNBDMN, 0); }
  public static void AddAEOKLKJAKHB(FlatBufferBuilder builder, uint AEOKLKJAKHB) { builder.AddUint(4, AEOKLKJAKHB, 0); }
  public static void AddAPJPCEEAANA(FlatBufferBuilder builder, uint APJPCEEAANA) { builder.AddUint(5, APJPCEEAANA, 0); }
  public static void AddKPMGJEELOEI(FlatBufferBuilder builder, uint KPMGJEELOEI) { builder.AddUint(6, KPMGJEELOEI, 0); }
  public static void AddBNOHOIBDHLP(FlatBufferBuilder builder, int BNOHOIBDHLP) { builder.AddInt(7, BNOHOIBDHLP, 0); }
  public static void AddCLEFGBLBDGJ(FlatBufferBuilder builder, VectorOffset CLEFGBLBDGJOffset) { builder.AddOffset(8, CLEFGBLBDGJOffset.Value, 0); }
  public static VectorOffset CreateCLEFGBLBDGJVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCLEFGBLBDGJVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HGBICHMJHMI> EndHGBICHMJHMI(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HGBICHMJHMI>(o);
  }
};

