// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HJIPOJKELHB : Table {
  public static HJIPOJKELHB GetRootAsHJIPOJKELHB(ByteBuffer _bb) { return GetRootAsHJIPOJKELHB(_bb, new HJIPOJKELHB()); }
  public static HJIPOJKELHB GetRootAsHJIPOJKELHB(ByteBuffer _bb, HJIPOJKELHB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HJIPOJKELHB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int COPFAKAHEMN { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetCEPFOAEFOEA(int j) { int o = __offset(6); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int CEPFOAEFOEALength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCEPFOAEFOEABytes() { return __vector_as_arraysegment(6); }

  public static Offset<HJIPOJKELHB> CreateHJIPOJKELHB(FlatBufferBuilder builder,
      int COPFAKAHEMN = 0,
      VectorOffset CEPFOAEFOEAOffset = default(VectorOffset)) {
    builder.StartObject(2);
    HJIPOJKELHB.AddCEPFOAEFOEA(builder, CEPFOAEFOEAOffset);
    HJIPOJKELHB.AddCOPFAKAHEMN(builder, COPFAKAHEMN);
    return HJIPOJKELHB.EndHJIPOJKELHB(builder);
  }

  public static void StartHJIPOJKELHB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddCOPFAKAHEMN(FlatBufferBuilder builder, int COPFAKAHEMN) { builder.AddInt(0, COPFAKAHEMN, 0); }
  public static void AddCEPFOAEFOEA(FlatBufferBuilder builder, VectorOffset CEPFOAEFOEAOffset) { builder.AddOffset(1, CEPFOAEFOEAOffset.Value, 0); }
  public static VectorOffset CreateCEPFOAEFOEAVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCEPFOAEFOEAVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HJIPOJKELHB> EndHJIPOJKELHB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HJIPOJKELHB>(o);
  }
};

