// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HJOPMDDAIDF : Table {
  public static HJOPMDDAIDF GetRootAsHJOPMDDAIDF(ByteBuffer _bb) { return GetRootAsHJOPMDDAIDF(_bb, new HJOPMDDAIDF()); }
  public static HJOPMDDAIDF GetRootAsHJOPMDDAIDF(ByteBuffer _bb, HJOPMDDAIDF obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HJOPMDDAIDF __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public EPBCNHDGFCB OPBPOOKODJK { get { return GetOPBPOOKODJK(new EPBCNHDGFCB()); } }
  public EPBCNHDGFCB GetOPBPOOKODJK(EPBCNHDGFCB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public PAPIGFKKFAK GetKJFDCEGGPPH(int j) { return GetKJFDCEGGPPH(new PAPIGFKKFAK(), j); }
  public PAPIGFKKFAK GetKJFDCEGGPPH(PAPIGFKKFAK obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int KJFDCEGGPPHLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public DLDBBNOCCJD GetOIJINAJFMCB(int j) { return GetOIJINAJFMCB(new DLDBBNOCCJD(), j); }
  public DLDBBNOCCJD GetOIJINAJFMCB(DLDBBNOCCJD obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int OIJINAJFMCBLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public OFIGAJKJFPF GetLEDCBACGIDD(int j) { return GetLEDCBACGIDD(new OFIGAJKJFPF(), j); }
  public OFIGAJKJFPF GetLEDCBACGIDD(OFIGAJKJFPF obj, int j) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int LEDCBACGIDDLength { get { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; } }
  public BMAKMHEEFEF GetNJJINHMIOHN(int j) { return GetNJJINHMIOHN(new BMAKMHEEFEF(), j); }
  public BMAKMHEEFEF GetNJJINHMIOHN(BMAKMHEEFEF obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int NJJINHMIOHNLength { get { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; } }
  public PBJDMDHLPIP GetNPFBHGKLIOM(int j) { return GetNPFBHGKLIOM(new PBJDMDHLPIP(), j); }
  public PBJDMDHLPIP GetNPFBHGKLIOM(PBJDMDHLPIP obj, int j) { int o = __offset(14); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int NPFBHGKLIOMLength { get { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; } }
  public DEOAJNDLLLH GetFBAHAFKCMMH(int j) { return GetFBAHAFKCMMH(new DEOAJNDLLLH(), j); }
  public DEOAJNDLLLH GetFBAHAFKCMMH(DEOAJNDLLLH obj, int j) { int o = __offset(16); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int FBAHAFKCMMHLength { get { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; } }
  public HCNLBIAHFHK GetGGKDJGGAFKA(int j) { return GetGGKDJGGAFKA(new HCNLBIAHFHK(), j); }
  public HCNLBIAHFHK GetGGKDJGGAFKA(HCNLBIAHFHK obj, int j) { int o = __offset(18); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int GGKDJGGAFKALength { get { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; } }
  public CHOEGDGADLA GetHDNMEPFHLNF(int j) { return GetHDNMEPFHLNF(new CHOEGDGADLA(), j); }
  public CHOEGDGADLA GetHDNMEPFHLNF(CHOEGDGADLA obj, int j) { int o = __offset(20); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int HDNMEPFHLNFLength { get { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; } }
  public HCMLGJBONGC GetOLLJCDPOAAI(int j) { return GetOLLJCDPOAAI(new HCMLGJBONGC(), j); }
  public HCMLGJBONGC GetOLLJCDPOAAI(HCMLGJBONGC obj, int j) { int o = __offset(22); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int OLLJCDPOAAILength { get { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; } }
  public DCBENCFJMOC GetBHNBMLKMLGN(int j) { return GetBHNBMLKMLGN(new DCBENCFJMOC(), j); }
  public DCBENCFJMOC GetBHNBMLKMLGN(DCBENCFJMOC obj, int j) { int o = __offset(24); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int BHNBMLKMLGNLength { get { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<HJOPMDDAIDF> CreateHJOPMDDAIDF(FlatBufferBuilder builder,
      Offset<EPBCNHDGFCB> OPBPOOKODJKOffset = default(Offset<EPBCNHDGFCB>),
      VectorOffset KJFDCEGGPPHOffset = default(VectorOffset),
      VectorOffset OIJINAJFMCBOffset = default(VectorOffset),
      VectorOffset LEDCBACGIDDOffset = default(VectorOffset),
      VectorOffset NJJINHMIOHNOffset = default(VectorOffset),
      VectorOffset NPFBHGKLIOMOffset = default(VectorOffset),
      VectorOffset FBAHAFKCMMHOffset = default(VectorOffset),
      VectorOffset GGKDJGGAFKAOffset = default(VectorOffset),
      VectorOffset HDNMEPFHLNFOffset = default(VectorOffset),
      VectorOffset OLLJCDPOAAIOffset = default(VectorOffset),
      VectorOffset BHNBMLKMLGNOffset = default(VectorOffset)) {
    builder.StartObject(11);
    HJOPMDDAIDF.AddBHNBMLKMLGN(builder, BHNBMLKMLGNOffset);
    HJOPMDDAIDF.AddOLLJCDPOAAI(builder, OLLJCDPOAAIOffset);
    HJOPMDDAIDF.AddHDNMEPFHLNF(builder, HDNMEPFHLNFOffset);
    HJOPMDDAIDF.AddGGKDJGGAFKA(builder, GGKDJGGAFKAOffset);
    HJOPMDDAIDF.AddFBAHAFKCMMH(builder, FBAHAFKCMMHOffset);
    HJOPMDDAIDF.AddNPFBHGKLIOM(builder, NPFBHGKLIOMOffset);
    HJOPMDDAIDF.AddNJJINHMIOHN(builder, NJJINHMIOHNOffset);
    HJOPMDDAIDF.AddLEDCBACGIDD(builder, LEDCBACGIDDOffset);
    HJOPMDDAIDF.AddOIJINAJFMCB(builder, OIJINAJFMCBOffset);
    HJOPMDDAIDF.AddKJFDCEGGPPH(builder, KJFDCEGGPPHOffset);
    HJOPMDDAIDF.AddOPBPOOKODJK(builder, OPBPOOKODJKOffset);
    return HJOPMDDAIDF.EndHJOPMDDAIDF(builder);
  }

  public static void StartHJOPMDDAIDF(FlatBufferBuilder builder) { builder.StartObject(11); }
  public static void AddOPBPOOKODJK(FlatBufferBuilder builder, Offset<EPBCNHDGFCB> OPBPOOKODJKOffset) { builder.AddOffset(0, OPBPOOKODJKOffset.Value, 0); }
  public static void AddKJFDCEGGPPH(FlatBufferBuilder builder, VectorOffset KJFDCEGGPPHOffset) { builder.AddOffset(1, KJFDCEGGPPHOffset.Value, 0); }
  public static VectorOffset CreateKJFDCEGGPPHVector(FlatBufferBuilder builder, Offset<PAPIGFKKFAK>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartKJFDCEGGPPHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOIJINAJFMCB(FlatBufferBuilder builder, VectorOffset OIJINAJFMCBOffset) { builder.AddOffset(2, OIJINAJFMCBOffset.Value, 0); }
  public static VectorOffset CreateOIJINAJFMCBVector(FlatBufferBuilder builder, Offset<DLDBBNOCCJD>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartOIJINAJFMCBVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLEDCBACGIDD(FlatBufferBuilder builder, VectorOffset LEDCBACGIDDOffset) { builder.AddOffset(3, LEDCBACGIDDOffset.Value, 0); }
  public static VectorOffset CreateLEDCBACGIDDVector(FlatBufferBuilder builder, Offset<OFIGAJKJFPF>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartLEDCBACGIDDVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddNJJINHMIOHN(FlatBufferBuilder builder, VectorOffset NJJINHMIOHNOffset) { builder.AddOffset(4, NJJINHMIOHNOffset.Value, 0); }
  public static VectorOffset CreateNJJINHMIOHNVector(FlatBufferBuilder builder, Offset<BMAKMHEEFEF>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNJJINHMIOHNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddNPFBHGKLIOM(FlatBufferBuilder builder, VectorOffset NPFBHGKLIOMOffset) { builder.AddOffset(5, NPFBHGKLIOMOffset.Value, 0); }
  public static VectorOffset CreateNPFBHGKLIOMVector(FlatBufferBuilder builder, Offset<PBJDMDHLPIP>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNPFBHGKLIOMVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFBAHAFKCMMH(FlatBufferBuilder builder, VectorOffset FBAHAFKCMMHOffset) { builder.AddOffset(6, FBAHAFKCMMHOffset.Value, 0); }
  public static VectorOffset CreateFBAHAFKCMMHVector(FlatBufferBuilder builder, Offset<DEOAJNDLLLH>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartFBAHAFKCMMHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGGKDJGGAFKA(FlatBufferBuilder builder, VectorOffset GGKDJGGAFKAOffset) { builder.AddOffset(7, GGKDJGGAFKAOffset.Value, 0); }
  public static VectorOffset CreateGGKDJGGAFKAVector(FlatBufferBuilder builder, Offset<HCNLBIAHFHK>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartGGKDJGGAFKAVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHDNMEPFHLNF(FlatBufferBuilder builder, VectorOffset HDNMEPFHLNFOffset) { builder.AddOffset(8, HDNMEPFHLNFOffset.Value, 0); }
  public static VectorOffset CreateHDNMEPFHLNFVector(FlatBufferBuilder builder, Offset<CHOEGDGADLA>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartHDNMEPFHLNFVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOLLJCDPOAAI(FlatBufferBuilder builder, VectorOffset OLLJCDPOAAIOffset) { builder.AddOffset(9, OLLJCDPOAAIOffset.Value, 0); }
  public static VectorOffset CreateOLLJCDPOAAIVector(FlatBufferBuilder builder, Offset<HCMLGJBONGC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartOLLJCDPOAAIVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBHNBMLKMLGN(FlatBufferBuilder builder, VectorOffset BHNBMLKMLGNOffset) { builder.AddOffset(10, BHNBMLKMLGNOffset.Value, 0); }
  public static VectorOffset CreateBHNBMLKMLGNVector(FlatBufferBuilder builder, Offset<DCBENCFJMOC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartBHNBMLKMLGNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HJOPMDDAIDF> EndHJOPMDDAIDF(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HJOPMDDAIDF>(o);
  }
};

