// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class HMAOBLEJDAH : Table {
  public static HMAOBLEJDAH GetRootAsHMAOBLEJDAH(ByteBuffer _bb) { return GetRootAsHMAOBLEJDAH(_bb, new HMAOBLEJDAH()); }
  public static HMAOBLEJDAH GetRootAsHMAOBLEJDAH(ByteBuffer _bb, HMAOBLEJDAH obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public HMAOBLEJDAH __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint HLCDELCABOF { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ADCLAGBHDBC { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint OFLDIKGIPBL { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DLGFIIKAOJD { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CFLMCGOJJJD { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AMFPDKACLLL { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LNCMMHCDOJE { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint MJOCIHPPKNO { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint GetHOFPKKMIOAL(int j) { int o = __offset(20); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int HOFPKKMIOALLength { get { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetHOFPKKMIOALBytes() { return __vector_as_arraysegment(20); }
  public uint GetCPOGAPIBMHF(int j) { int o = __offset(22); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int CPOGAPIBMHFLength { get { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCPOGAPIBMHFBytes() { return __vector_as_arraysegment(22); }
  public uint GetGFFCGBEAKDP(int j) { int o = __offset(24); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int GFFCGBEAKDPLength { get { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetGFFCGBEAKDPBytes() { return __vector_as_arraysegment(24); }
  public uint GetNBOHLKPDNKA(int j) { int o = __offset(26); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int NBOHLKPDNKALength { get { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetNBOHLKPDNKABytes() { return __vector_as_arraysegment(26); }
  public uint GetDHHLJCLLPAF(int j) { int o = __offset(28); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int DHHLJCLLPAFLength { get { int o = __offset(28); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetDHHLJCLLPAFBytes() { return __vector_as_arraysegment(28); }
  public uint GetOHBEDDIGFKG(int j) { int o = __offset(30); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int OHBEDDIGFKGLength { get { int o = __offset(30); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetOHBEDDIGFKGBytes() { return __vector_as_arraysegment(30); }
  public uint GetDNHAKGCPLOG(int j) { int o = __offset(32); return o != 0 ? bb.GetUint(__vector(o) + j * 4) : (uint)0; }
  public int DNHAKGCPLOGLength { get { int o = __offset(32); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetDNHAKGCPLOGBytes() { return __vector_as_arraysegment(32); }

  public static Offset<HMAOBLEJDAH> CreateHMAOBLEJDAH(FlatBufferBuilder builder,
      uint HLCDELCABOF = 0,
      uint ADCLAGBHDBC = 0,
      uint OFLDIKGIPBL = 0,
      uint DLGFIIKAOJD = 0,
      uint CFLMCGOJJJD = 0,
      uint AMFPDKACLLL = 0,
      uint LNCMMHCDOJE = 0,
      uint MJOCIHPPKNO = 0,
      VectorOffset HOFPKKMIOALOffset = default(VectorOffset),
      VectorOffset CPOGAPIBMHFOffset = default(VectorOffset),
      VectorOffset GFFCGBEAKDPOffset = default(VectorOffset),
      VectorOffset NBOHLKPDNKAOffset = default(VectorOffset),
      VectorOffset DHHLJCLLPAFOffset = default(VectorOffset),
      VectorOffset OHBEDDIGFKGOffset = default(VectorOffset),
      VectorOffset DNHAKGCPLOGOffset = default(VectorOffset)) {
    builder.StartObject(15);
    HMAOBLEJDAH.AddDNHAKGCPLOG(builder, DNHAKGCPLOGOffset);
    HMAOBLEJDAH.AddOHBEDDIGFKG(builder, OHBEDDIGFKGOffset);
    HMAOBLEJDAH.AddDHHLJCLLPAF(builder, DHHLJCLLPAFOffset);
    HMAOBLEJDAH.AddNBOHLKPDNKA(builder, NBOHLKPDNKAOffset);
    HMAOBLEJDAH.AddGFFCGBEAKDP(builder, GFFCGBEAKDPOffset);
    HMAOBLEJDAH.AddCPOGAPIBMHF(builder, CPOGAPIBMHFOffset);
    HMAOBLEJDAH.AddHOFPKKMIOAL(builder, HOFPKKMIOALOffset);
    HMAOBLEJDAH.AddMJOCIHPPKNO(builder, MJOCIHPPKNO);
    HMAOBLEJDAH.AddLNCMMHCDOJE(builder, LNCMMHCDOJE);
    HMAOBLEJDAH.AddAMFPDKACLLL(builder, AMFPDKACLLL);
    HMAOBLEJDAH.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    HMAOBLEJDAH.AddDLGFIIKAOJD(builder, DLGFIIKAOJD);
    HMAOBLEJDAH.AddOFLDIKGIPBL(builder, OFLDIKGIPBL);
    HMAOBLEJDAH.AddADCLAGBHDBC(builder, ADCLAGBHDBC);
    HMAOBLEJDAH.AddHLCDELCABOF(builder, HLCDELCABOF);
    return HMAOBLEJDAH.EndHMAOBLEJDAH(builder);
  }

  public static void StartHMAOBLEJDAH(FlatBufferBuilder builder) { builder.StartObject(15); }
  public static void AddHLCDELCABOF(FlatBufferBuilder builder, uint HLCDELCABOF) { builder.AddUint(0, HLCDELCABOF, 0); }
  public static void AddADCLAGBHDBC(FlatBufferBuilder builder, uint ADCLAGBHDBC) { builder.AddUint(1, ADCLAGBHDBC, 0); }
  public static void AddOFLDIKGIPBL(FlatBufferBuilder builder, uint OFLDIKGIPBL) { builder.AddUint(2, OFLDIKGIPBL, 0); }
  public static void AddDLGFIIKAOJD(FlatBufferBuilder builder, uint DLGFIIKAOJD) { builder.AddUint(3, DLGFIIKAOJD, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, uint CFLMCGOJJJD) { builder.AddUint(4, CFLMCGOJJJD, 0); }
  public static void AddAMFPDKACLLL(FlatBufferBuilder builder, uint AMFPDKACLLL) { builder.AddUint(5, AMFPDKACLLL, 0); }
  public static void AddLNCMMHCDOJE(FlatBufferBuilder builder, uint LNCMMHCDOJE) { builder.AddUint(6, LNCMMHCDOJE, 0); }
  public static void AddMJOCIHPPKNO(FlatBufferBuilder builder, uint MJOCIHPPKNO) { builder.AddUint(7, MJOCIHPPKNO, 0); }
  public static void AddHOFPKKMIOAL(FlatBufferBuilder builder, VectorOffset HOFPKKMIOALOffset) { builder.AddOffset(8, HOFPKKMIOALOffset.Value, 0); }
  public static VectorOffset CreateHOFPKKMIOALVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartHOFPKKMIOALVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCPOGAPIBMHF(FlatBufferBuilder builder, VectorOffset CPOGAPIBMHFOffset) { builder.AddOffset(9, CPOGAPIBMHFOffset.Value, 0); }
  public static VectorOffset CreateCPOGAPIBMHFVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartCPOGAPIBMHFVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGFFCGBEAKDP(FlatBufferBuilder builder, VectorOffset GFFCGBEAKDPOffset) { builder.AddOffset(10, GFFCGBEAKDPOffset.Value, 0); }
  public static VectorOffset CreateGFFCGBEAKDPVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartGFFCGBEAKDPVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddNBOHLKPDNKA(FlatBufferBuilder builder, VectorOffset NBOHLKPDNKAOffset) { builder.AddOffset(11, NBOHLKPDNKAOffset.Value, 0); }
  public static VectorOffset CreateNBOHLKPDNKAVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartNBOHLKPDNKAVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDHHLJCLLPAF(FlatBufferBuilder builder, VectorOffset DHHLJCLLPAFOffset) { builder.AddOffset(12, DHHLJCLLPAFOffset.Value, 0); }
  public static VectorOffset CreateDHHLJCLLPAFVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartDHHLJCLLPAFVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOHBEDDIGFKG(FlatBufferBuilder builder, VectorOffset OHBEDDIGFKGOffset) { builder.AddOffset(13, OHBEDDIGFKGOffset.Value, 0); }
  public static VectorOffset CreateOHBEDDIGFKGVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartOHBEDDIGFKGVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDNHAKGCPLOG(FlatBufferBuilder builder, VectorOffset DNHAKGCPLOGOffset) { builder.AddOffset(14, DNHAKGCPLOGOffset.Value, 0); }
  public static VectorOffset CreateDNHAKGCPLOGVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static void StartDNHAKGCPLOGVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HMAOBLEJDAH> EndHMAOBLEJDAH(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HMAOBLEJDAH>(o);
  }
};

