// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class IABACDAGDAP : Table {
  public static IABACDAGDAP GetRootAsIABACDAGDAP(ByteBuffer _bb) { return GetRootAsIABACDAGDAP(_bb, new IABACDAGDAP()); }
  public static IABACDAGDAP GetRootAsIABACDAGDAP(ByteBuffer _bb, IABACDAGDAP obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IABACDAGDAP __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint GGJFACAIOBF { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LPJPOOHJKAE { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint PIFAMBCEMKL { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint COPFAKAHEMN { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string IMOOHKAFLPP { get { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIMOOHKAFLPPBytes() { return __vector_as_arraysegment(14); }

  public static Offset<IABACDAGDAP> CreateIABACDAGDAP(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint GGJFACAIOBF = 0,
      uint LPJPOOHJKAE = 0,
      uint PIFAMBCEMKL = 0,
      uint COPFAKAHEMN = 0,
      StringOffset IMOOHKAFLPPOffset = default(StringOffset)) {
    builder.StartObject(6);
    IABACDAGDAP.AddIMOOHKAFLPP(builder, IMOOHKAFLPPOffset);
    IABACDAGDAP.AddCOPFAKAHEMN(builder, COPFAKAHEMN);
    IABACDAGDAP.AddPIFAMBCEMKL(builder, PIFAMBCEMKL);
    IABACDAGDAP.AddLPJPOOHJKAE(builder, LPJPOOHJKAE);
    IABACDAGDAP.AddGGJFACAIOBF(builder, GGJFACAIOBF);
    IABACDAGDAP.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return IABACDAGDAP.EndIABACDAGDAP(builder);
  }

  public static void StartIABACDAGDAP(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddGGJFACAIOBF(FlatBufferBuilder builder, uint GGJFACAIOBF) { builder.AddUint(1, GGJFACAIOBF, 0); }
  public static void AddLPJPOOHJKAE(FlatBufferBuilder builder, uint LPJPOOHJKAE) { builder.AddUint(2, LPJPOOHJKAE, 0); }
  public static void AddPIFAMBCEMKL(FlatBufferBuilder builder, uint PIFAMBCEMKL) { builder.AddUint(3, PIFAMBCEMKL, 0); }
  public static void AddCOPFAKAHEMN(FlatBufferBuilder builder, uint COPFAKAHEMN) { builder.AddUint(4, COPFAKAHEMN, 0); }
  public static void AddIMOOHKAFLPP(FlatBufferBuilder builder, StringOffset IMOOHKAFLPPOffset) { builder.AddOffset(5, IMOOHKAFLPPOffset.Value, 0); }
  public static Offset<IABACDAGDAP> EndIABACDAGDAP(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IABACDAGDAP>(o);
  }
};

