// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class IDOIMCLBFJA : Table {
  public static IDOIMCLBFJA GetRootAsIDOIMCLBFJA(ByteBuffer _bb) { return GetRootAsIDOIMCLBFJA(_bb, new IDOIMCLBFJA()); }
  public static IDOIMCLBFJA GetRootAsIDOIMCLBFJA(ByteBuffer _bb, IDOIMCLBFJA obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IDOIMCLBFJA __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint JKDAMKCJMLD { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DJBJGNJAHHP { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<IDOIMCLBFJA> CreateIDOIMCLBFJA(FlatBufferBuilder builder,
      uint JKDAMKCJMLD = 0,
      uint DJBJGNJAHHP = 0) {
    builder.StartObject(2);
    IDOIMCLBFJA.AddDJBJGNJAHHP(builder, DJBJGNJAHHP);
    IDOIMCLBFJA.AddJKDAMKCJMLD(builder, JKDAMKCJMLD);
    return IDOIMCLBFJA.EndIDOIMCLBFJA(builder);
  }

  public static void StartIDOIMCLBFJA(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddJKDAMKCJMLD(FlatBufferBuilder builder, uint JKDAMKCJMLD) { builder.AddUint(0, JKDAMKCJMLD, 0); }
  public static void AddDJBJGNJAHHP(FlatBufferBuilder builder, uint DJBJGNJAHHP) { builder.AddUint(1, DJBJGNJAHHP, 0); }
  public static Offset<IDOIMCLBFJA> EndIDOIMCLBFJA(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IDOIMCLBFJA>(o);
  }
};

