// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class INOFLJPLFAN : Table {
  public static INOFLJPLFAN GetRootAsINOFLJPLFAN(ByteBuffer _bb) { return GetRootAsINOFLJPLFAN(_bb, new INOFLJPLFAN()); }
  public static INOFLJPLFAN GetRootAsINOFLJPLFAN(ByteBuffer _bb, INOFLJPLFAN obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public INOFLJPLFAN __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PAAOHNKLBAC { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MBBJMJAAODG { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int LFFMNLEJJMH { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int PAEGHLMNPNO { get { int o = __offset(10); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int ODBPKGJPLMD { get { int o = __offset(12); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<INOFLJPLFAN> CreateINOFLJPLFAN(FlatBufferBuilder builder,
      int PAAOHNKLBAC = 0,
      int MBBJMJAAODG = 0,
      int LFFMNLEJJMH = 0,
      int PAEGHLMNPNO = 0,
      int ODBPKGJPLMD = 0) {
    builder.StartObject(5);
    INOFLJPLFAN.AddODBPKGJPLMD(builder, ODBPKGJPLMD);
    INOFLJPLFAN.AddPAEGHLMNPNO(builder, PAEGHLMNPNO);
    INOFLJPLFAN.AddLFFMNLEJJMH(builder, LFFMNLEJJMH);
    INOFLJPLFAN.AddMBBJMJAAODG(builder, MBBJMJAAODG);
    INOFLJPLFAN.AddPAAOHNKLBAC(builder, PAAOHNKLBAC);
    return INOFLJPLFAN.EndINOFLJPLFAN(builder);
  }

  public static void StartINOFLJPLFAN(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddPAAOHNKLBAC(FlatBufferBuilder builder, int PAAOHNKLBAC) { builder.AddInt(0, PAAOHNKLBAC, 0); }
  public static void AddMBBJMJAAODG(FlatBufferBuilder builder, int MBBJMJAAODG) { builder.AddInt(1, MBBJMJAAODG, 0); }
  public static void AddLFFMNLEJJMH(FlatBufferBuilder builder, int LFFMNLEJJMH) { builder.AddInt(2, LFFMNLEJJMH, 0); }
  public static void AddPAEGHLMNPNO(FlatBufferBuilder builder, int PAEGHLMNPNO) { builder.AddInt(3, PAEGHLMNPNO, 0); }
  public static void AddODBPKGJPLMD(FlatBufferBuilder builder, int ODBPKGJPLMD) { builder.AddInt(4, ODBPKGJPLMD, 0); }
  public static Offset<INOFLJPLFAN> EndINOFLJPLFAN(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<INOFLJPLFAN>(o);
  }
};

