// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class IONNGNNIKOG : Table {
  public static IONNGNNIKOG GetRootAsIONNGNNIKOG(ByteBuffer _bb) { return GetRootAsIONNGNNIKOG(_bb, new IONNGNNIKOG()); }
  public static IONNGNNIKOG GetRootAsIONNGNNIKOG(ByteBuffer _bb, IONNGNNIKOG obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IONNGNNIKOG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int HFJLPAOGLEH { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string NNKLANONDOM { get { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNNKLANONDOMBytes() { return __vector_as_arraysegment(8); }
  public string EPHHJONMFBP { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetEPHHJONMFBPBytes() { return __vector_as_arraysegment(10); }
  public string IIGJOMDOEDO { get { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIGJOMDOEDOBytes() { return __vector_as_arraysegment(12); }
  public int NHMKEMIMBML { get { int o = __offset(14); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetBJBNCHAIOHH(int j) { int o = __offset(16); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int BJBNCHAIOHHLength { get { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetBJBNCHAIOHHBytes() { return __vector_as_arraysegment(16); }
  public int GetBNCIPLKECMC(int j) { int o = __offset(18); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int BNCIPLKECMCLength { get { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetBNCIPLKECMCBytes() { return __vector_as_arraysegment(18); }
  public int IBIAJNFJICN { get { int o = __offset(20); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<IONNGNNIKOG> CreateIONNGNNIKOG(FlatBufferBuilder builder,
      int BBPHAPFBFHK = 0,
      int HFJLPAOGLEH = 0,
      StringOffset NNKLANONDOMOffset = default(StringOffset),
      StringOffset EPHHJONMFBPOffset = default(StringOffset),
      StringOffset IIGJOMDOEDOOffset = default(StringOffset),
      int NHMKEMIMBML = 0,
      VectorOffset BJBNCHAIOHHOffset = default(VectorOffset),
      VectorOffset BNCIPLKECMCOffset = default(VectorOffset),
      int IBIAJNFJICN = 0) {
    builder.StartObject(9);
    IONNGNNIKOG.AddIBIAJNFJICN(builder, IBIAJNFJICN);
    IONNGNNIKOG.AddBNCIPLKECMC(builder, BNCIPLKECMCOffset);
    IONNGNNIKOG.AddBJBNCHAIOHH(builder, BJBNCHAIOHHOffset);
    IONNGNNIKOG.AddNHMKEMIMBML(builder, NHMKEMIMBML);
    IONNGNNIKOG.AddIIGJOMDOEDO(builder, IIGJOMDOEDOOffset);
    IONNGNNIKOG.AddEPHHJONMFBP(builder, EPHHJONMFBPOffset);
    IONNGNNIKOG.AddNNKLANONDOM(builder, NNKLANONDOMOffset);
    IONNGNNIKOG.AddHFJLPAOGLEH(builder, HFJLPAOGLEH);
    IONNGNNIKOG.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return IONNGNNIKOG.EndIONNGNNIKOG(builder);
  }

  public static void StartIONNGNNIKOG(FlatBufferBuilder builder) { builder.StartObject(9); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, int BBPHAPFBFHK) { builder.AddInt(0, BBPHAPFBFHK, 0); }
  public static void AddHFJLPAOGLEH(FlatBufferBuilder builder, int HFJLPAOGLEH) { builder.AddInt(1, HFJLPAOGLEH, 0); }
  public static void AddNNKLANONDOM(FlatBufferBuilder builder, StringOffset NNKLANONDOMOffset) { builder.AddOffset(2, NNKLANONDOMOffset.Value, 0); }
  public static void AddEPHHJONMFBP(FlatBufferBuilder builder, StringOffset EPHHJONMFBPOffset) { builder.AddOffset(3, EPHHJONMFBPOffset.Value, 0); }
  public static void AddIIGJOMDOEDO(FlatBufferBuilder builder, StringOffset IIGJOMDOEDOOffset) { builder.AddOffset(4, IIGJOMDOEDOOffset.Value, 0); }
  public static void AddNHMKEMIMBML(FlatBufferBuilder builder, int NHMKEMIMBML) { builder.AddInt(5, NHMKEMIMBML, 0); }
  public static void AddBJBNCHAIOHH(FlatBufferBuilder builder, VectorOffset BJBNCHAIOHHOffset) { builder.AddOffset(6, BJBNCHAIOHHOffset.Value, 0); }
  public static VectorOffset CreateBJBNCHAIOHHVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartBJBNCHAIOHHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBNCIPLKECMC(FlatBufferBuilder builder, VectorOffset BNCIPLKECMCOffset) { builder.AddOffset(7, BNCIPLKECMCOffset.Value, 0); }
  public static VectorOffset CreateBNCIPLKECMCVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartBNCIPLKECMCVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddIBIAJNFJICN(FlatBufferBuilder builder, int IBIAJNFJICN) { builder.AddInt(8, IBIAJNFJICN, 0); }
  public static Offset<IONNGNNIKOG> EndIONNGNNIKOG(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IONNGNNIKOG>(o);
  }
};

