// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class JOGLEFDCEJI : Table {
  public static JOGLEFDCEJI GetRootAsJOGLEFDCEJI(ByteBuffer _bb) { return GetRootAsJOGLEFDCEJI(_bb, new JOGLEFDCEJI()); }
  public static JOGLEFDCEJI GetRootAsJOGLEFDCEJI(ByteBuffer _bb, JOGLEFDCEJI obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public JOGLEFDCEJI __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int CKMMECCALPI { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int OFMGALJGDAO { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int CFLMCGOJJJD { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string CLGDAMPNKAA { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetCLGDAMPNKAABytes() { return __vector_as_arraysegment(10); }
  public int LPJPOOHJKAE { get { int o = __offset(12); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int NCADHENBLDB { get { int o = __offset(14); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int CLGHAEBNGCF { get { int o = __offset(16); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int KCCGHBAOJEN { get { int o = __offset(18); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int HAHMOLPJPCG { get { int o = __offset(20); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int NJLJEKDBPCH { get { int o = __offset(22); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MAOAGDBDBIB { get { int o = __offset(24); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int JAOFIDGEIGE { get { int o = __offset(26); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int BPMBFFDNMDD { get { int o = __offset(28); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<JOGLEFDCEJI> CreateJOGLEFDCEJI(FlatBufferBuilder builder,
      int CKMMECCALPI = 0,
      int OFMGALJGDAO = 0,
      int CFLMCGOJJJD = 0,
      StringOffset CLGDAMPNKAAOffset = default(StringOffset),
      int LPJPOOHJKAE = 0,
      int NCADHENBLDB = 0,
      int CLGHAEBNGCF = 0,
      int KCCGHBAOJEN = 0,
      int HAHMOLPJPCG = 0,
      int NJLJEKDBPCH = 0,
      int MAOAGDBDBIB = 0,
      int JAOFIDGEIGE = 0,
      int BPMBFFDNMDD = 0) {
    builder.StartObject(13);
    JOGLEFDCEJI.AddBPMBFFDNMDD(builder, BPMBFFDNMDD);
    JOGLEFDCEJI.AddJAOFIDGEIGE(builder, JAOFIDGEIGE);
    JOGLEFDCEJI.AddMAOAGDBDBIB(builder, MAOAGDBDBIB);
    JOGLEFDCEJI.AddNJLJEKDBPCH(builder, NJLJEKDBPCH);
    JOGLEFDCEJI.AddHAHMOLPJPCG(builder, HAHMOLPJPCG);
    JOGLEFDCEJI.AddKCCGHBAOJEN(builder, KCCGHBAOJEN);
    JOGLEFDCEJI.AddCLGHAEBNGCF(builder, CLGHAEBNGCF);
    JOGLEFDCEJI.AddNCADHENBLDB(builder, NCADHENBLDB);
    JOGLEFDCEJI.AddLPJPOOHJKAE(builder, LPJPOOHJKAE);
    JOGLEFDCEJI.AddCLGDAMPNKAA(builder, CLGDAMPNKAAOffset);
    JOGLEFDCEJI.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    JOGLEFDCEJI.AddOFMGALJGDAO(builder, OFMGALJGDAO);
    JOGLEFDCEJI.AddCKMMECCALPI(builder, CKMMECCALPI);
    return JOGLEFDCEJI.EndJOGLEFDCEJI(builder);
  }

  public static void StartJOGLEFDCEJI(FlatBufferBuilder builder) { builder.StartObject(13); }
  public static void AddCKMMECCALPI(FlatBufferBuilder builder, int CKMMECCALPI) { builder.AddInt(0, CKMMECCALPI, 0); }
  public static void AddOFMGALJGDAO(FlatBufferBuilder builder, int OFMGALJGDAO) { builder.AddInt(1, OFMGALJGDAO, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, int CFLMCGOJJJD) { builder.AddInt(2, CFLMCGOJJJD, 0); }
  public static void AddCLGDAMPNKAA(FlatBufferBuilder builder, StringOffset CLGDAMPNKAAOffset) { builder.AddOffset(3, CLGDAMPNKAAOffset.Value, 0); }
  public static void AddLPJPOOHJKAE(FlatBufferBuilder builder, int LPJPOOHJKAE) { builder.AddInt(4, LPJPOOHJKAE, 0); }
  public static void AddNCADHENBLDB(FlatBufferBuilder builder, int NCADHENBLDB) { builder.AddInt(5, NCADHENBLDB, 0); }
  public static void AddCLGHAEBNGCF(FlatBufferBuilder builder, int CLGHAEBNGCF) { builder.AddInt(6, CLGHAEBNGCF, 0); }
  public static void AddKCCGHBAOJEN(FlatBufferBuilder builder, int KCCGHBAOJEN) { builder.AddInt(7, KCCGHBAOJEN, 0); }
  public static void AddHAHMOLPJPCG(FlatBufferBuilder builder, int HAHMOLPJPCG) { builder.AddInt(8, HAHMOLPJPCG, 0); }
  public static void AddNJLJEKDBPCH(FlatBufferBuilder builder, int NJLJEKDBPCH) { builder.AddInt(9, NJLJEKDBPCH, 0); }
  public static void AddMAOAGDBDBIB(FlatBufferBuilder builder, int MAOAGDBDBIB) { builder.AddInt(10, MAOAGDBDBIB, 0); }
  public static void AddJAOFIDGEIGE(FlatBufferBuilder builder, int JAOFIDGEIGE) { builder.AddInt(11, JAOFIDGEIGE, 0); }
  public static void AddBPMBFFDNMDD(FlatBufferBuilder builder, int BPMBFFDNMDD) { builder.AddInt(12, BPMBFFDNMDD, 0); }
  public static Offset<JOGLEFDCEJI> EndJOGLEFDCEJI(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<JOGLEFDCEJI>(o);
  }
};

