// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class KEOGNGPEGMH : Table {
  public static KEOGNGPEGMH GetRootAsKEOGNGPEGMH(ByteBuffer _bb) { return GetRootAsKEOGNGPEGMH(_bb, new KEOGNGPEGMH()); }
  public static KEOGNGPEGMH GetRootAsKEOGNGPEGMH(ByteBuffer _bb, KEOGNGPEGMH obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public KEOGNGPEGMH __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint CFLMCGOJJJD { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint BKKAFNHOJFE { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string NNKLANONDOM { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNNKLANONDOMBytes() { return __vector_as_arraysegment(10); }
  public uint EFFICDBHCCH { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint FOHAACCBBOP { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<KEOGNGPEGMH> CreateKEOGNGPEGMH(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint CFLMCGOJJJD = 0,
      uint BKKAFNHOJFE = 0,
      StringOffset NNKLANONDOMOffset = default(StringOffset),
      uint EFFICDBHCCH = 0,
      uint FOHAACCBBOP = 0) {
    builder.StartObject(6);
    KEOGNGPEGMH.AddFOHAACCBBOP(builder, FOHAACCBBOP);
    KEOGNGPEGMH.AddEFFICDBHCCH(builder, EFFICDBHCCH);
    KEOGNGPEGMH.AddNNKLANONDOM(builder, NNKLANONDOMOffset);
    KEOGNGPEGMH.AddBKKAFNHOJFE(builder, BKKAFNHOJFE);
    KEOGNGPEGMH.AddCFLMCGOJJJD(builder, CFLMCGOJJJD);
    KEOGNGPEGMH.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return KEOGNGPEGMH.EndKEOGNGPEGMH(builder);
  }

  public static void StartKEOGNGPEGMH(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddCFLMCGOJJJD(FlatBufferBuilder builder, uint CFLMCGOJJJD) { builder.AddUint(1, CFLMCGOJJJD, 0); }
  public static void AddBKKAFNHOJFE(FlatBufferBuilder builder, uint BKKAFNHOJFE) { builder.AddUint(2, BKKAFNHOJFE, 0); }
  public static void AddNNKLANONDOM(FlatBufferBuilder builder, StringOffset NNKLANONDOMOffset) { builder.AddOffset(3, NNKLANONDOMOffset.Value, 0); }
  public static void AddEFFICDBHCCH(FlatBufferBuilder builder, uint EFFICDBHCCH) { builder.AddUint(4, EFFICDBHCCH, 0); }
  public static void AddFOHAACCBBOP(FlatBufferBuilder builder, uint FOHAACCBBOP) { builder.AddUint(5, FOHAACCBBOP, 0); }
  public static Offset<KEOGNGPEGMH> EndKEOGNGPEGMH(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<KEOGNGPEGMH>(o);
  }
};

