// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class LDLCKBMOFJC : Table {
  public static LDLCKBMOFJC GetRootAsLDLCKBMOFJC(ByteBuffer _bb) { return GetRootAsLDLCKBMOFJC(_bb, new LDLCKBMOFJC()); }
  public static LDLCKBMOFJC GetRootAsLDLCKBMOFJC(ByteBuffer _bb, LDLCKBMOFJC obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public LDLCKBMOFJC __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ILOKJEKGMOB GetHLBFAIIOKBI(int j) { return GetHLBFAIIOKBI(new ILOKJEKGMOB(), j); }
  public ILOKJEKGMOB GetHLBFAIIOKBI(ILOKJEKGMOB obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int HLBFAIIOKBILength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<LDLCKBMOFJC> CreateLDLCKBMOFJC(FlatBufferBuilder builder,
      VectorOffset HLBFAIIOKBIOffset = default(VectorOffset)) {
    builder.StartObject(1);
    LDLCKBMOFJC.AddHLBFAIIOKBI(builder, HLBFAIIOKBIOffset);
    return LDLCKBMOFJC.EndLDLCKBMOFJC(builder);
  }

  public static void StartLDLCKBMOFJC(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddHLBFAIIOKBI(FlatBufferBuilder builder, VectorOffset HLBFAIIOKBIOffset) { builder.AddOffset(0, HLBFAIIOKBIOffset.Value, 0); }
  public static VectorOffset CreateHLBFAIIOKBIVector(FlatBufferBuilder builder, Offset<ILOKJEKGMOB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartHLBFAIIOKBIVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<LDLCKBMOFJC> EndLDLCKBMOFJC(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LDLCKBMOFJC>(o);
  }
};

