// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class MCCEAMFIECM : Table {
  public static MCCEAMFIECM GetRootAsMCCEAMFIECM(ByteBuffer _bb) { return GetRootAsMCCEAMFIECM(_bb, new MCCEAMFIECM()); }
  public static MCCEAMFIECM GetRootAsMCCEAMFIECM(ByteBuffer _bb, MCCEAMFIECM obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public MCCEAMFIECM __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public APGJGCCJNJF OPBPOOKODJK { get { return GetOPBPOOKODJK(new APGJGCCJNJF()); } }
  public APGJGCCJNJF GetOPBPOOKODJK(APGJGCCJNJF obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public HFNALPGCIFB GetNJJINHMIOHN(int j) { return GetNJJINHMIOHN(new HFNALPGCIFB(), j); }
  public HFNALPGCIFB GetNJJINHMIOHN(HFNALPGCIFB obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int NJJINHMIOHNLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public CNOCBANEBIK GetNPFBHGKLIOM(int j) { return GetNPFBHGKLIOM(new CNOCBANEBIK(), j); }
  public CNOCBANEBIK GetNPFBHGKLIOM(CNOCBANEBIK obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int NPFBHGKLIOMLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public DMNHOBFBIJD GetFBAHAFKCMMH(int j) { return GetFBAHAFKCMMH(new DMNHOBFBIJD(), j); }
  public DMNHOBFBIJD GetFBAHAFKCMMH(DMNHOBFBIJD obj, int j) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int FBAHAFKCMMHLength { get { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<MCCEAMFIECM> CreateMCCEAMFIECM(FlatBufferBuilder builder,
      Offset<APGJGCCJNJF> OPBPOOKODJKOffset = default(Offset<APGJGCCJNJF>),
      VectorOffset NJJINHMIOHNOffset = default(VectorOffset),
      VectorOffset NPFBHGKLIOMOffset = default(VectorOffset),
      VectorOffset FBAHAFKCMMHOffset = default(VectorOffset)) {
    builder.StartObject(4);
    MCCEAMFIECM.AddFBAHAFKCMMH(builder, FBAHAFKCMMHOffset);
    MCCEAMFIECM.AddNPFBHGKLIOM(builder, NPFBHGKLIOMOffset);
    MCCEAMFIECM.AddNJJINHMIOHN(builder, NJJINHMIOHNOffset);
    MCCEAMFIECM.AddOPBPOOKODJK(builder, OPBPOOKODJKOffset);
    return MCCEAMFIECM.EndMCCEAMFIECM(builder);
  }

  public static void StartMCCEAMFIECM(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddOPBPOOKODJK(FlatBufferBuilder builder, Offset<APGJGCCJNJF> OPBPOOKODJKOffset) { builder.AddOffset(0, OPBPOOKODJKOffset.Value, 0); }
  public static void AddNJJINHMIOHN(FlatBufferBuilder builder, VectorOffset NJJINHMIOHNOffset) { builder.AddOffset(1, NJJINHMIOHNOffset.Value, 0); }
  public static VectorOffset CreateNJJINHMIOHNVector(FlatBufferBuilder builder, Offset<HFNALPGCIFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNJJINHMIOHNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddNPFBHGKLIOM(FlatBufferBuilder builder, VectorOffset NPFBHGKLIOMOffset) { builder.AddOffset(2, NPFBHGKLIOMOffset.Value, 0); }
  public static VectorOffset CreateNPFBHGKLIOMVector(FlatBufferBuilder builder, Offset<CNOCBANEBIK>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNPFBHGKLIOMVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFBAHAFKCMMH(FlatBufferBuilder builder, VectorOffset FBAHAFKCMMHOffset) { builder.AddOffset(3, FBAHAFKCMMHOffset.Value, 0); }
  public static VectorOffset CreateFBAHAFKCMMHVector(FlatBufferBuilder builder, Offset<DMNHOBFBIJD>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartFBAHAFKCMMHVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MCCEAMFIECM> EndMCCEAMFIECM(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MCCEAMFIECM>(o);
  }
};

