// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class MPAKIJAPJIC : Table {
  public static MPAKIJAPJIC GetRootAsMPAKIJAPJIC(ByteBuffer _bb) { return GetRootAsMPAKIJAPJIC(_bb, new MPAKIJAPJIC()); }
  public static MPAKIJAPJIC GetRootAsMPAKIJAPJIC(ByteBuffer _bb, MPAKIJAPJIC obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public MPAKIJAPJIC __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string IIDCFMHCPLJ { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIIDCFMHCPLJBytes() { return __vector_as_arraysegment(4); }
  public string HAEJDOGGKPC { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetHAEJDOGGKPCBytes() { return __vector_as_arraysegment(6); }
  public uint MAIJBDCJPNJ { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public string MKDFHLALNAF { get { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetMKDFHLALNAFBytes() { return __vector_as_arraysegment(10); }
  public string GetNLPMPPCENKD(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int NLPMPPCENKDLength { get { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; } }
  public uint LLJNABNBDMN { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint DJHKCHMBGHC { get { int o = __offset(16); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint BCKOLCDDIAG { get { int o = __offset(18); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint LKIBIHGHEMA { get { int o = __offset(20); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint ANELKJCGJJL { get { int o = __offset(22); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint AEOKLKJAKHB { get { int o = __offset(24); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public int GetKNDBMPNNCGG(int j) { int o = __offset(26); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int KNDBMPNNCGGLength { get { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetKNDBMPNNCGGBytes() { return __vector_as_arraysegment(26); }

  public static Offset<MPAKIJAPJIC> CreateMPAKIJAPJIC(FlatBufferBuilder builder,
      StringOffset IIDCFMHCPLJOffset = default(StringOffset),
      StringOffset HAEJDOGGKPCOffset = default(StringOffset),
      uint MAIJBDCJPNJ = 0,
      StringOffset MKDFHLALNAFOffset = default(StringOffset),
      VectorOffset NLPMPPCENKDOffset = default(VectorOffset),
      uint LLJNABNBDMN = 0,
      uint DJHKCHMBGHC = 0,
      uint BCKOLCDDIAG = 0,
      uint LKIBIHGHEMA = 0,
      uint ANELKJCGJJL = 0,
      uint AEOKLKJAKHB = 0,
      VectorOffset KNDBMPNNCGGOffset = default(VectorOffset)) {
    builder.StartObject(12);
    MPAKIJAPJIC.AddKNDBMPNNCGG(builder, KNDBMPNNCGGOffset);
    MPAKIJAPJIC.AddAEOKLKJAKHB(builder, AEOKLKJAKHB);
    MPAKIJAPJIC.AddANELKJCGJJL(builder, ANELKJCGJJL);
    MPAKIJAPJIC.AddLKIBIHGHEMA(builder, LKIBIHGHEMA);
    MPAKIJAPJIC.AddBCKOLCDDIAG(builder, BCKOLCDDIAG);
    MPAKIJAPJIC.AddDJHKCHMBGHC(builder, DJHKCHMBGHC);
    MPAKIJAPJIC.AddLLJNABNBDMN(builder, LLJNABNBDMN);
    MPAKIJAPJIC.AddNLPMPPCENKD(builder, NLPMPPCENKDOffset);
    MPAKIJAPJIC.AddMKDFHLALNAF(builder, MKDFHLALNAFOffset);
    MPAKIJAPJIC.AddMAIJBDCJPNJ(builder, MAIJBDCJPNJ);
    MPAKIJAPJIC.AddHAEJDOGGKPC(builder, HAEJDOGGKPCOffset);
    MPAKIJAPJIC.AddIIDCFMHCPLJ(builder, IIDCFMHCPLJOffset);
    return MPAKIJAPJIC.EndMPAKIJAPJIC(builder);
  }

  public static void StartMPAKIJAPJIC(FlatBufferBuilder builder) { builder.StartObject(12); }
  public static void AddIIDCFMHCPLJ(FlatBufferBuilder builder, StringOffset IIDCFMHCPLJOffset) { builder.AddOffset(0, IIDCFMHCPLJOffset.Value, 0); }
  public static void AddHAEJDOGGKPC(FlatBufferBuilder builder, StringOffset HAEJDOGGKPCOffset) { builder.AddOffset(1, HAEJDOGGKPCOffset.Value, 0); }
  public static void AddMAIJBDCJPNJ(FlatBufferBuilder builder, uint MAIJBDCJPNJ) { builder.AddUint(2, MAIJBDCJPNJ, 0); }
  public static void AddMKDFHLALNAF(FlatBufferBuilder builder, StringOffset MKDFHLALNAFOffset) { builder.AddOffset(3, MKDFHLALNAFOffset.Value, 0); }
  public static void AddNLPMPPCENKD(FlatBufferBuilder builder, VectorOffset NLPMPPCENKDOffset) { builder.AddOffset(4, NLPMPPCENKDOffset.Value, 0); }
  public static VectorOffset CreateNLPMPPCENKDVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNLPMPPCENKDVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLLJNABNBDMN(FlatBufferBuilder builder, uint LLJNABNBDMN) { builder.AddUint(5, LLJNABNBDMN, 0); }
  public static void AddDJHKCHMBGHC(FlatBufferBuilder builder, uint DJHKCHMBGHC) { builder.AddUint(6, DJHKCHMBGHC, 0); }
  public static void AddBCKOLCDDIAG(FlatBufferBuilder builder, uint BCKOLCDDIAG) { builder.AddUint(7, BCKOLCDDIAG, 0); }
  public static void AddLKIBIHGHEMA(FlatBufferBuilder builder, uint LKIBIHGHEMA) { builder.AddUint(8, LKIBIHGHEMA, 0); }
  public static void AddANELKJCGJJL(FlatBufferBuilder builder, uint ANELKJCGJJL) { builder.AddUint(9, ANELKJCGJJL, 0); }
  public static void AddAEOKLKJAKHB(FlatBufferBuilder builder, uint AEOKLKJAKHB) { builder.AddUint(10, AEOKLKJAKHB, 0); }
  public static void AddKNDBMPNNCGG(FlatBufferBuilder builder, VectorOffset KNDBMPNNCGGOffset) { builder.AddOffset(11, KNDBMPNNCGGOffset.Value, 0); }
  public static VectorOffset CreateKNDBMPNNCGGVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartKNDBMPNNCGGVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MPAKIJAPJIC> EndMPAKIJAPJIC(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MPAKIJAPJIC>(o);
  }
};

