// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class OJJCFKMBCCG : Table {
  public static OJJCFKMBCCG GetRootAsOJJCFKMBCCG(ByteBuffer _bb) { return GetRootAsOJJCFKMBCCG(_bb, new OJJCFKMBCCG()); }
  public static OJJCFKMBCCG GetRootAsOJJCFKMBCCG(ByteBuffer _bb, OJJCFKMBCCG obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public OJJCFKMBCCG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetHDALNHDJPLP(int j) { int o = __offset(6); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int HDALNHDJPLPLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetHDALNHDJPLPBytes() { return __vector_as_arraysegment(6); }
  public int GetLGMFAKNICMB(int j) { int o = __offset(8); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int LGMFAKNICMBLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetLGMFAKNICMBBytes() { return __vector_as_arraysegment(8); }
  public int GetLLPOHOGEHMG(int j) { int o = __offset(10); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int LLPOHOGEHMGLength { get { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetLLPOHOGEHMGBytes() { return __vector_as_arraysegment(10); }
  public int GetIEIMHJDMABN(int j) { int o = __offset(12); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int IEIMHJDMABNLength { get { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetIEIMHJDMABNBytes() { return __vector_as_arraysegment(12); }

  public static Offset<OJJCFKMBCCG> CreateOJJCFKMBCCG(FlatBufferBuilder builder,
      int BBPHAPFBFHK = 0,
      VectorOffset HDALNHDJPLPOffset = default(VectorOffset),
      VectorOffset LGMFAKNICMBOffset = default(VectorOffset),
      VectorOffset LLPOHOGEHMGOffset = default(VectorOffset),
      VectorOffset IEIMHJDMABNOffset = default(VectorOffset)) {
    builder.StartObject(5);
    OJJCFKMBCCG.AddIEIMHJDMABN(builder, IEIMHJDMABNOffset);
    OJJCFKMBCCG.AddLLPOHOGEHMG(builder, LLPOHOGEHMGOffset);
    OJJCFKMBCCG.AddLGMFAKNICMB(builder, LGMFAKNICMBOffset);
    OJJCFKMBCCG.AddHDALNHDJPLP(builder, HDALNHDJPLPOffset);
    OJJCFKMBCCG.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return OJJCFKMBCCG.EndOJJCFKMBCCG(builder);
  }

  public static void StartOJJCFKMBCCG(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, int BBPHAPFBFHK) { builder.AddInt(0, BBPHAPFBFHK, 0); }
  public static void AddHDALNHDJPLP(FlatBufferBuilder builder, VectorOffset HDALNHDJPLPOffset) { builder.AddOffset(1, HDALNHDJPLPOffset.Value, 0); }
  public static VectorOffset CreateHDALNHDJPLPVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartHDALNHDJPLPVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLGMFAKNICMB(FlatBufferBuilder builder, VectorOffset LGMFAKNICMBOffset) { builder.AddOffset(2, LGMFAKNICMBOffset.Value, 0); }
  public static VectorOffset CreateLGMFAKNICMBVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartLGMFAKNICMBVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLLPOHOGEHMG(FlatBufferBuilder builder, VectorOffset LLPOHOGEHMGOffset) { builder.AddOffset(3, LLPOHOGEHMGOffset.Value, 0); }
  public static VectorOffset CreateLLPOHOGEHMGVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartLLPOHOGEHMGVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddIEIMHJDMABN(FlatBufferBuilder builder, VectorOffset IEIMHJDMABNOffset) { builder.AddOffset(4, IEIMHJDMABNOffset.Value, 0); }
  public static VectorOffset CreateIEIMHJDMABNVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartIEIMHJDMABNVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<OJJCFKMBCCG> EndOJJCFKMBCCG(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<OJJCFKMBCCG>(o);
  }
};

