// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class PCGHGHNPJDO : Table {
  public static PCGHGHNPJDO GetRootAsPCGHGHNPJDO(ByteBuffer _bb) { return GetRootAsPCGHGHNPJDO(_bb, new PCGHGHNPJDO()); }
  public static PCGHGHNPJDO GetRootAsPCGHGHNPJDO(ByteBuffer _bb, PCGHGHNPJDO obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public PCGHGHNPJDO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public CNHFHECKIAI GetLMHJEEMBGIA(int j) { return GetLMHJEEMBGIA(new CNHFHECKIAI(), j); }
  public CNHFHECKIAI GetLMHJEEMBGIA(CNHFHECKIAI obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int LMHJEEMBGIALength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<PCGHGHNPJDO> CreatePCGHGHNPJDO(FlatBufferBuilder builder,
      VectorOffset LMHJEEMBGIAOffset = default(VectorOffset)) {
    builder.StartObject(1);
    PCGHGHNPJDO.AddLMHJEEMBGIA(builder, LMHJEEMBGIAOffset);
    return PCGHGHNPJDO.EndPCGHGHNPJDO(builder);
  }

  public static void StartPCGHGHNPJDO(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddLMHJEEMBGIA(FlatBufferBuilder builder, VectorOffset LMHJEEMBGIAOffset) { builder.AddOffset(0, LMHJEEMBGIAOffset.Value, 0); }
  public static VectorOffset CreateLMHJEEMBGIAVector(FlatBufferBuilder builder, Offset<CNHFHECKIAI>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartLMHJEEMBGIAVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PCGHGHNPJDO> EndPCGHGHNPJDO(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PCGHGHNPJDO>(o);
  }
};

