// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class PEGCLNAOLBG : Table {
  public static PEGCLNAOLBG GetRootAsPEGCLNAOLBG(ByteBuffer _bb) { return GetRootAsPEGCLNAOLBG(_bb, new PEGCLNAOLBG()); }
  public static PEGCLNAOLBG GetRootAsPEGCLNAOLBG(ByteBuffer _bb, PEGCLNAOLBG obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public PEGCLNAOLBG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint BBPHAPFBFHK { get { int o = __offset(4); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint MKLGLNCCAJF { get { int o = __offset(6); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint NPCAIBOAGGO { get { int o = __offset(8); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint KLMIFFAAGOD { get { int o = __offset(10); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint JINBBAJGKGI { get { int o = __offset(12); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }
  public uint MDAGNDELGJC { get { int o = __offset(14); return o != 0 ? bb.GetUint(o + bb_pos) : (uint)0; } }

  public static Offset<PEGCLNAOLBG> CreatePEGCLNAOLBG(FlatBufferBuilder builder,
      uint BBPHAPFBFHK = 0,
      uint MKLGLNCCAJF = 0,
      uint NPCAIBOAGGO = 0,
      uint KLMIFFAAGOD = 0,
      uint JINBBAJGKGI = 0,
      uint MDAGNDELGJC = 0) {
    builder.StartObject(6);
    PEGCLNAOLBG.AddMDAGNDELGJC(builder, MDAGNDELGJC);
    PEGCLNAOLBG.AddJINBBAJGKGI(builder, JINBBAJGKGI);
    PEGCLNAOLBG.AddKLMIFFAAGOD(builder, KLMIFFAAGOD);
    PEGCLNAOLBG.AddNPCAIBOAGGO(builder, NPCAIBOAGGO);
    PEGCLNAOLBG.AddMKLGLNCCAJF(builder, MKLGLNCCAJF);
    PEGCLNAOLBG.AddBBPHAPFBFHK(builder, BBPHAPFBFHK);
    return PEGCLNAOLBG.EndPEGCLNAOLBG(builder);
  }

  public static void StartPEGCLNAOLBG(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddBBPHAPFBFHK(FlatBufferBuilder builder, uint BBPHAPFBFHK) { builder.AddUint(0, BBPHAPFBFHK, 0); }
  public static void AddMKLGLNCCAJF(FlatBufferBuilder builder, uint MKLGLNCCAJF) { builder.AddUint(1, MKLGLNCCAJF, 0); }
  public static void AddNPCAIBOAGGO(FlatBufferBuilder builder, uint NPCAIBOAGGO) { builder.AddUint(2, NPCAIBOAGGO, 0); }
  public static void AddKLMIFFAAGOD(FlatBufferBuilder builder, uint KLMIFFAAGOD) { builder.AddUint(3, KLMIFFAAGOD, 0); }
  public static void AddJINBBAJGKGI(FlatBufferBuilder builder, uint JINBBAJGKGI) { builder.AddUint(4, JINBBAJGKGI, 0); }
  public static void AddMDAGNDELGJC(FlatBufferBuilder builder, uint MDAGNDELGJC) { builder.AddUint(5, MDAGNDELGJC, 0); }
  public static Offset<PEGCLNAOLBG> EndPEGCLNAOLBG(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PEGCLNAOLBG>(o);
  }
};

