
using System.Collections.Generic;

[System.Obsolete("Use IOEKHJBOMDH_DecoStamp", true)]
public class IOEKHJBOMDH { }
public class IOEKHJBOMDH_DecoStamp : KLFDBFMNLBL_ServerSaveBlock
{
	public class PAFLFMFEOJD
	{
		private int ENOBDCFHELD; // 0x8
		private int FCEJCHGLFGN; // 0xC
		private int LNMDNLFFIDI; // 0x10
		private int HBPDJCFJNED; // 0x14
		private int DOCJJLGDBMB; // 0x18
		private int MEMDPDCJNNA; // 0x1C

		public int CNOHJPEHHCH { get { return LNMDNLFFIDI ^ ENOBDCFHELD; } set { LNMDNLFFIDI = value ^ ENOBDCFHELD; HBPDJCFJNED = value ^ FCEJCHGLFGN; } } //0xA03F24 LFIBGCJBHOF 0xA047BC LEIBBHPBKOF
		public int JBOCHIJAMFD { get { return DOCJJLGDBMB ^ ENOBDCFHELD; } set { DOCJJLGDBMB = value ^ ENOBDCFHELD; MEMDPDCJNNA = value ^ FCEJCHGLFGN; } } //0xA03F34 AFHBJCEOOEI 0xA047D8 LCDHDMNKDKA
		//public bool IEDNAKOJNDE { get; } 0xA060F8 JCIMBGHEMOK

		// RVA: 0xA030EC Offset: 0xA030EC VA: 0xA030EC
		public PAFLFMFEOJD(int PPFNGGCBJKC = 0)
		{
			LHPDDGIJKNB(PPFNGGCBJKC);
		}

		//// RVA: 0xA06128 Offset: 0xA06128 VA: 0xA06128
		public void LHPDDGIJKNB(int PPFNGGCBJKC)
		{
			ENOBDCFHELD = LPDNKHAIOLH.CEIBAFOCNCA();
			FCEJCHGLFGN = LPDNKHAIOLH.CEIBAFOCNCA();
			CNOHJPEHHCH = PPFNGGCBJKC;
			JBOCHIJAMFD = 0;
		}

		//// RVA: 0xA05038 Offset: 0xA05038 VA: 0xA05038
		//public bool AGBOGBEOFME(IOEKHJBOMDH.PAFLFMFEOJD OIKJFMGEICL) { }

		//// RVA: 0xA04BBC Offset: 0xA04BBC VA: 0xA04BBC
		//public void ODDIHGPONFL(IOEKHJBOMDH.PAFLFMFEOJD OIKJFMGEICL) { }

		//// RVA: 0xA02CB0 Offset: 0xA02CB0 VA: 0xA02CB0
		//public FENCAJJBLBH PFAKPFKJJKA() { }

		//// RVA: 0xA05860 Offset: 0xA05860 VA: 0xA05860
		//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, IOEKHJBOMDH.PAFLFMFEOJD GJLFANGDGCL, bool EFOEPDLNLJG) { }
	}
 
	public class GFPPDCEPLCM
	{
		public int ENOBDCFHELD; // 0x8
		public int FCEJCHGLFGN; // 0xC
		private const sbyte JFOFMKBJBBE_False = 0x13;
		private const sbyte CNECJGKECHK_True = 0x57;
		private int EHOIENNDEDH; // 0x10
		public int INCHFKJOIEK; // 0x14
		private int IFEHKNJONPL; // 0x18
		public int ONFJFGFNGGD; // 0x1C
		private sbyte ACKPOCNHOOP; // 0x20
		public sbyte KCEAEOMJNFO; // 0x21

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ ENOBDCFHELD; } set { EHOIENNDEDH = value ^ ENOBDCFHELD; INCHFKJOIEK = value ^ FCEJCHGLFGN; } } //0xA03F70 DEMEPMAEJOO 0xA047F4 HIGKAIDMOKN
		public int BFINGCJHOHI { get { return IFEHKNJONPL ^ ENOBDCFHELD; } set { IFEHKNJONPL = value ^ ENOBDCFHELD; ONFJFGFNGGD = value ^ FCEJCHGLFGN; } } //0xA03F80 LFMCLIDAPHB 0xA04810 EDAEPDGGFJJ
		public bool CADENLBDAEB { get { return ACKPOCNHOOP == CNECJGKECHK_True; } set { ACKPOCNHOOP = value ? CNECJGKECHK_True : JFOFMKBJBBE_False; KCEAEOMJNFO = value ? JFOFMKBJBBE_False : CNECJGKECHK_True; } } //0xA03F90 KJGFPPLHLAB 0xA0482C ILJHLPMDHPO

		// RVA: 0xA03114 Offset: 0xA03114 VA: 0xA03114
		public GFPPDCEPLCM(int PPFNGGCBJKC = 0)
		{
			ENOBDCFHELD = LPDNKHAIOLH.CEIBAFOCNCA();
			FCEJCHGLFGN = LPDNKHAIOLH.CEIBAFOCNCA();
			LHPDDGIJKNB(PPFNGGCBJKC);
		}

		//// RVA: 0xA06074 Offset: 0xA06074 VA: 0xA06074
		public void LHPDDGIJKNB(int PPFNGGCBJKC = 0)
		{
			this.PPFNGGCBJKC = PPFNGGCBJKC;
			BFINGCJHOHI = 0;
			CADENLBDAEB = false;
		}

		//// RVA: 0xA04C38 Offset: 0xA04C38 VA: 0xA04C38
		//public IOEKHJBOMDH.GFPPDCEPLCM ODDIHGPONFL(IOEKHJBOMDH.GFPPDCEPLCM GPBJHKLFCEP) { }

		//// RVA: 0xA050A4 Offset: 0xA050A4 VA: 0xA050A4
		//public bool AGBOGBEOFME(IOEKHJBOMDH.GFPPDCEPLCM OIKJFMGEICL) { }

		//// RVA: 0xA03F44 Offset: 0xA03F44 VA: 0xA03F44
		//public bool DFIGPDCBAPB() { }

		//// RVA: 0xA05DB4 Offset: 0xA05DB4 VA: 0xA05DB4
		//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, IOEKHJBOMDH.GFPPDCEPLCM OHMCIEMIKCE, bool EFOEPDLNLJG) { }

		//// RVA: 0xA02DB0 Offset: 0xA02DB0 VA: 0xA02DB0
		//public FENCAJJBLBH PFAKPFKJJKA() { }

		//// RVA: 0xA06098 Offset: 0xA06098 VA: 0xA06098
		//public bool PPJAGFPBFHJ(int HMFFHLPNMPH) { }
	}

	private const int ECFEMKGFDCE = 3;
	private const string POFDDFCGEGP = "_";
	public const int EDFABKBBOFI = 1;
	public const int FJEDMPPIGAM = 30;
	public const int NNEODMHAPGP = 900;
	public const int BNGDHECNKFF = 400;
	public List<PAFLFMFEOJD> GNKJGECHLNE; // 0x24
	public List<GFPPDCEPLCM> FHBIIONKIDI; // 0x28
	public List<GFPPDCEPLCM> DMKMNGELNAE; // 0x2C

	// public override bool DMICHEJIAJL { get; }

	// // RVA: 0xA027AC Offset: 0xA027AC VA: 0xA027AC
	// public bool DDKEJHIGBGK(IHFIAFDLAAK GAPONCJOKAC, int PPFNGGCBJKC) { }

	// // RVA: 0xA028B0 Offset: 0xA028B0 VA: 0xA028B0
	// public bool HOAKPBBIGPK(IHFIAFDLAAK GAPONCJOKAC, int PPFNGGCBJKC) { }

	// // RVA: 0xA029B4 Offset: 0xA029B4 VA: 0xA029B4
	public IOEKHJBOMDH_DecoStamp()
	{
		GNKJGECHLNE = new List<PAFLFMFEOJD>(30);
		FHBIIONKIDI = new List<GFPPDCEPLCM>();
		DMKMNGELNAE = new List<GFPPDCEPLCM>();
		KMBPACJNEOF();
	}

	// // RVA: 0xA02AA4 Offset: 0xA02AA4 VA: 0xA02AA4 Slot: 11
	public override FENCAJJBLBH PFAKPFKJJKA()
	{
		TodoLogger.Log(0, "TODO");
		return null;
	}

	// // RVA: 0xA02EE4 Offset: 0xA02EE4 VA: 0xA02EE4 Slot: 4
	public override void KMBPACJNEOF()
	{
		GNKJGECHLNE.Clear();
		FHBIIONKIDI.Clear();
		DMKMNGELNAE.Clear();
		for(int i = 0; i < 30; i++)
		{
			GNKJGECHLNE.Add(new PAFLFMFEOJD());
		}
		for(int i = 0; i < 900; i++)
		{
			FHBIIONKIDI.Add(new GFPPDCEPLCM());
		}
		for (int i = 0; i < 400; i++)
		{
			DMKMNGELNAE.Add(new GFPPDCEPLCM());
		}
	}

	// // RVA: 0xA031DC Offset: 0xA031DC VA: 0xA031DC Slot: 5
	// public override void OKJPIBHMKMJ(EDOHBJAPLPF_JsonData OILEIIEIBHP, long MCKEOKFMLAH) { }

	// // RVA: 0xA03FA4 Offset: 0xA03FA4 VA: 0xA03FA4 Slot: 6
	public override bool IIEMACPEEBJ_Deserialize(EDOHBJAPLPF_JsonData OILEIIEIBHP)
	{
		TodoLogger.Log(0, "TODO");
		return true;
	}

	// // RVA: 0xA04884 Offset: 0xA04884 VA: 0xA04884 Slot: 7
	// public override void BMGGKONLFIC(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0xA04CE0 Offset: 0xA04CE0 VA: 0xA04CE0 Slot: 8
	// public override bool AGBOGBEOFME(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0xA0516C Offset: 0xA0516C VA: 0xA0516C Slot: 10
	// public override void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, KLFDBFMNLBL GJLFANGDGCL, long MCKEOKFMLAH) { }

	// // RVA: 0xA0606C Offset: 0xA0606C VA: 0xA0606C Slot: 9
	// public override bool NFKFOODCJJB() { }
}
