
using System.Collections.Generic;

[System.Obsolete("Use NFMHCLHEMHB_Bingo", true)]
public class NFMHCLHEMHB { }
public class NFMHCLHEMHB_Bingo : KLFDBFMNLBL_ServerSaveBlock
{
	public class CCGKCGJKADC
	{
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private long HMDBEHOHPGN; // 0x20
		private long OIPPKODMBFP; // 0x28
		private int COGALGDHDFE; // 0x30
		private int COELGGNMBCB; // 0x34
		public KKAJHLFMBKE AHCFGOGCJKI; // 0x38
		public List<OCLGCNPBNHE> AHJNPEAMCCH; // 0x3C
		public List<long> MIOBPGFAABN; // 0x40

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ FBGGEFFJJHB; } set { EHOIENNDEDH = value ^ FBGGEFFJJHB; } } //0x1AEC7E0 DEMEPMAEJOO 0x1AEE5C0 HIGKAIDMOKN
		public long KOOEOKEDJDO { get { return HMDBEHOHPGN ^ BBEGLBMOBOF; } set { HMDBEHOHPGN = value ^ BBEGLBMOBOF; } } //0x1AEC7F0 BABHKIGIOPO 0x1AEE5D0 PCOFGPBACAM
		public long EBDKHCLCOFL { get { return OIPPKODMBFP ^ BBEGLBMOBOF; } set { OIPPKODMBFP = value ^ BBEGLBMOBOF; } } //0x1AEC804 OGCBLPKOELF 0x1AEE5F0 HHKIKFCMBEB
		public int JNLKJCDFFMM { get { return COGALGDHDFE ^ FBGGEFFJJHB; } set { COGALGDHDFE = value ^ FBGGEFFJJHB; } } //0x1AEC81C JLGNODHICKN 0x1AEE604 DLEGLBAGJOI
		public int BJOHOIAKKFM { get { return COELGGNMBCB ^ FBGGEFFJJHB; } set { COELGGNMBCB = value ^ FBGGEFFJJHB; } } //0x1AEC82C HBIPFAPFKOM 0x1AEE614 GIMACKPNDBH

		//// RVA: 0x1AECABC Offset: 0x1AECABC VA: 0x1AECABC
		//public long MILJGLKJACG(int IOPHIHFOOEP) { }

		//// RVA: 0x1AF0BE0 Offset: 0x1AF0BE0 VA: 0x1AF0BE0
		//public bool IDOLNNPFDDH(int IOPHIHFOOEP, long MIKCFEHGNJB) { }

		// RVA: 0x1AEA708 Offset: 0x1AEA708 VA: 0x1AEA708
		public CCGKCGJKADC()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			BBEGLBMOBOF = ~FBGGEFFJJHB;
		}

		//// RVA: 0x1AEA7A4 Offset: 0x1AEA7A4 VA: 0x1AEA7A4
		public void KHEKNNFCAOI(int PPFNGGCBJKC)
		{
			this.PPFNGGCBJKC = PPFNGGCBJKC;
			KOOEOKEDJDO = 0;
			EBDKHCLCOFL = 0;
			JNLKJCDFFMM = 0;
			BJOHOIAKKFM = 0;
			AHCFGOGCJKI = new KKAJHLFMBKE();
			AHCFGOGCJKI.KHEKNNFCAOI(0);
			AHJNPEAMCCH = new List<OCLGCNPBNHE>();
			for(int i = 0; i < 20; i++)
			{
				OCLGCNPBNHE data = new OCLGCNPBNHE();
				data.KHEKNNFCAOI(i + 1);
				AHJNPEAMCCH.Add(data);
			}
			MIOBPGFAABN = new List<long>();
			for(int i = 0; i < 8; i++)
			{
				MIOBPGFAABN.Add(BBEGLBMOBOF);
			}
		}

		//// RVA: 0x1AF101C Offset: 0x1AF101C VA: 0x1AF101C
		//public void LHPDDGIJKNB() { }

		//// RVA: 0x1AF1024 Offset: 0x1AF1024 VA: 0x1AF1024
		//public bool CHFOOMPEABN() { }

		//// RVA: 0x1AEE974 Offset: 0x1AEE974 VA: 0x1AEE974
		//public void ODDIHGPONFL(NFMHCLHEMHB.CCGKCGJKADC GPBJHKLFCEP) { }

		//// RVA: 0x1AEED28 Offset: 0x1AEED28 VA: 0x1AEED28
		//public bool AGBOGBEOFME(NFMHCLHEMHB.CCGKCGJKADC OIKJFMGEICL) { }

		//// RVA: 0x1AEF238 Offset: 0x1AEF238 VA: 0x1AEF238
		//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, NFMHCLHEMHB.CCGKCGJKADC OHMCIEMIKCE, bool EFOEPDLNLJG) { }
	}
	
	public class FLLIDKFECHC
	{
		private const int MNHALNODIPI = 99999999;
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		public int[] DENIHAKEBCA = new int[5]; // 0x18
		public int[] IKJLNHDBGHI = new int[10]; // 0x1C
		public int[] NPBIKIMOKME = new int[11]; // 0x20
		public int[] MENIJIHIBDC = new int[11]; // 0x24
		public int[] FCAHJGHCHAL = new int[11]; // 0x28
		public int[] EFEJCLLLEJJ = new int[11]; // 0x2C
		public int[] LGHCJFCCGFI = new int[9]; // 0x30
		private int PGCLFDKEICG; // 0x34
		private int BGBHLBBAPLP; // 0x38
		private int MBHOFBCAHAA; // 0x3C
		private int OBMDMPKJPPN; // 0x40
		private int IIKHMOBNJIP; // 0x44
		private int BFJMFKNHNDF; // 0x48
		private int PGLEOCMDIHO; // 0x4C
		private int DONIGIGNCEK; // 0x50

		public int BOLCACJFJGG { get { return PGCLFDKEICG ^ FBGGEFFJJHB; } set { PGCLFDKEICG = value ^ FBGGEFFJJHB; } } //0x1AEC84C MFLNPFGCJEA 0x1AEE684 HIFCFHNDGLM
		public int ODJEADMLGFB { get { return BGBHLBBAPLP ^ FBGGEFFJJHB; } set { BGBHLBBAPLP = value ^ FBGGEFFJJHB; } } //0x1AEC85C LMCDMMNEPBB 0x1AEE694 OKLIBJNDABE
		public int FFMHGGHFNPJ { get { return MBHOFBCAHAA ^ FBGGEFFJJHB; } set { MBHOFBCAHAA = value ^ FBGGEFFJJHB; } } //0x1AEC86C HECFEOHMINM 0x1AEE6A4 LCICCKNOCDH
		public int GNNKOAILFOL { get { return OBMDMPKJPPN ^ FBGGEFFJJHB; } set { OBMDMPKJPPN = value ^ FBGGEFFJJHB; } } //0x1AEC87C FHEPJDMPLGB 0x1AEE6B4 OCHICNIKHLL
		public int NHPNPIBOHFB { get { return IIKHMOBNJIP ^ FBGGEFFJJHB; } set { IIKHMOBNJIP = value ^ FBGGEFFJJHB; } } //0x1AEC88C FILGNOJGLKI 0x1AEE6C4 EGALFOKNCCM
		public int GCEKFPECEAI { get { return BFJMFKNHNDF ^ FBGGEFFJJHB; } set { BFJMFKNHNDF = value ^ FBGGEFFJJHB; } } //0x1AEC89C FPJIMCLMBIA 0x1AEE6D4 HBDLAAGDFOE
		public int HJNEMKGIBGE { get { return PGLEOCMDIHO ^ FBGGEFFJJHB; } set { PGLEOCMDIHO = value ^ FBGGEFFJJHB; } } //0x1AEC8AC NLEACKBCHDA 0x1AEE6E4 EDLAINIBICO
		public int AIPKHFKODAH { get { return DONIGIGNCEK ^ FBGGEFFJJHB; } set { DONIGIGNCEK = value ^ FBGGEFFJJHB; } } //0x1AEC8BC JDCFGCHDOJE 0x1AEE6F4 FICCLMGIOLP

		// RVA: 0x1AF15F8 Offset: 0x1AF15F8 VA: 0x1AF15F8
		public FLLIDKFECHC()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			BBEGLBMOBOF = ~FBGGEFFJJHB;
		}

		//// RVA: 0x1AF1710 Offset: 0x1AF1710 VA: 0x1AF1710
		public void KHEKNNFCAOI()
		{
			HJNEMKGIBGE = 0;
			AIPKHFKODAH = 0;
			BOLCACJFJGG = 0;
			ODJEADMLGFB = 1;
			FFMHGGHFNPJ = 0;
			GNNKOAILFOL = 0;
			NHPNPIBOHFB = 0;
			GCEKFPECEAI = 0;
			for (int i = 0; i < 5; i++)
			{
				DENIHAKEBCA[i] = FBGGEFFJJHB;
			}
			for (int i = 0; i < 10; i++)
			{
				IKJLNHDBGHI[i] = FBGGEFFJJHB;
			}
			for (int i = 0; i < 11; i++)
			{
				NPBIKIMOKME[i] = FBGGEFFJJHB;
				MENIJIHIBDC[i] = FBGGEFFJJHB;
				FCAHJGHCHAL[i] = FBGGEFFJJHB;
				EFEJCLLLEJJ[i] = FBGGEFFJJHB;
			}
			for (int i = 0; i < LGHCJFCCGFI.Length; i++)
			{
				LGHCJFCCGFI[i] = FBGGEFFJJHB;
			}
		}

		//// RVA: 0x1AF1948 Offset: 0x1AF1948 VA: 0x1AF1948
		//public void ODDIHGPONFL(NFMHCLHEMHB.FLLIDKFECHC GPBJHKLFCEP) { }

		//// RVA: 0x1AF1E38 Offset: 0x1AF1E38 VA: 0x1AF1E38
		//public bool AGBOGBEOFME(NFMHCLHEMHB.FLLIDKFECHC OIKJFMGEICL) { }

		//// RVA: 0x1AF22E8 Offset: 0x1AF22E8 VA: 0x1AF22E8
		//public void AGNDGJOPIDL(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2314 Offset: 0x1AF2314 VA: 0x1AF2314
		//public void JLKOBAAEDAM(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2340 Offset: 0x1AF2340 VA: 0x1AF2340
		//public void CNEMNJOLIBE(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF236C Offset: 0x1AF236C VA: 0x1AF236C
		//public void EJDEINMOHOP(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2398 Offset: 0x1AF2398 VA: 0x1AF2398
		//public void BFAJMALBALG(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF23C4 Offset: 0x1AF23C4 VA: 0x1AF23C4
		//public void OAEMBFCMCHL(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF23F0 Offset: 0x1AF23F0 VA: 0x1AF23F0
		//public void HFOCJMOOMBB(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF241C Offset: 0x1AF241C VA: 0x1AF241C
		//public void PJPHOMJFDEH(int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2448 Offset: 0x1AF2448 VA: 0x1AF2448
		//public int INMNHOGDFPM(ref int[] PILEIPOLBOE, int OIPCCBHIKIA) { }

		//// RVA: 0x1AF24D0 Offset: 0x1AF24D0 VA: 0x1AF24D0
		//public void NMKOFGHHAEA(ref int[] PILEIPOLBOE, int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2554 Offset: 0x1AF2554 VA: 0x1AF2554
		//public void HNGEHGDDGAB(ref int[] PILEIPOLBOE, int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC8CC Offset: 0x1AEC8CC VA: 0x1AEC8CC
		//public int GNHALIDFACE(int FGHGMHPNEMG) { }

		//// RVA: 0x1AF094C Offset: 0x1AF094C VA: 0x1AF094C
		//public void NADMCFKICOE(int FGHGMHPNEMG, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2628 Offset: 0x1AF2628 VA: 0x1AF2628
		//public void KKHPAHICACE(int FGHGMHPNEMG, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC8D8 Offset: 0x1AEC8D8 VA: 0x1AEC8D8
		//public int EJNFMAAKCMH(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF09B4 Offset: 0x1AF09B4 VA: 0x1AF09B4
		//public void MPEEACOJILJ(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF264C Offset: 0x1AF264C VA: 0x1AF264C
		//public void NKOPNPPGPCD(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC8E4 Offset: 0x1AEC8E4 VA: 0x1AEC8E4
		//public int MLBJKMLMLEG(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF0A1C Offset: 0x1AF0A1C VA: 0x1AF0A1C
		//public void NDMPJNBKHPM(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2670 Offset: 0x1AF2670 VA: 0x1AF2670
		//public void APEIECMCGGH(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC8F0 Offset: 0x1AEC8F0 VA: 0x1AEC8F0
		//public int FGGFDPFMKAF(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF0A84 Offset: 0x1AF0A84 VA: 0x1AF0A84
		//public void FBJIMCNJPOB(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2694 Offset: 0x1AF2694 VA: 0x1AF2694
		//public void PDHLABPHFNB(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC8FC Offset: 0x1AEC8FC VA: 0x1AEC8FC
		//public int KGFLHCHAIGO(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF0AEC Offset: 0x1AF0AEC VA: 0x1AF0AEC
		//public void PODJFPCEDLM(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF26B8 Offset: 0x1AF26B8 VA: 0x1AF26B8
		//public void PCLBKGHNJPN(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC908 Offset: 0x1AEC908 VA: 0x1AEC908
		//public int IKKOANOJHLB(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF0B54 Offset: 0x1AF0B54 VA: 0x1AF0B54
		//public void PBEDBGMNGHB(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF26DC Offset: 0x1AF26DC VA: 0x1AF26DC
		//public void CCIDPHJEONL(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AEC914 Offset: 0x1AEC914 VA: 0x1AEC914
		//public int CDNJPNFGHOG(int OIPCCBHIKIA) { }

		//// RVA: 0x1AF0BBC Offset: 0x1AF0BBC VA: 0x1AF0BBC
		//public void CLOMILDLINH(int OIPCCBHIKIA, int HMFFHLPNMPH) { }

		//// RVA: 0x1AF2700 Offset: 0x1AF2700 VA: 0x1AF2700
		//public void MPOEJLFDAGJ(int OIPCCBHIKIA, int HMFFHLPNMPH) { }
	}

	public class KKAJHLFMBKE
	{
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int FKKHMCINELD; // 0x1C
		private int CGIGOFKGCII; // 0x20
		private int HNJNKCPDKAL; // 0x24
		private int DJENABHDIPP; // 0x28
		public FLLIDKFECHC JJKBBFEJFGO; // 0x2C
		public List<HKMBGGGMEKA> HDMADAHNLDN; // 0x30
		public List<long> OHMBCPHFDLD; // 0x34

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ FBGGEFFJJHB; } set { EHOIENNDEDH = value ^ FBGGEFFJJHB; } } //0x1AEA3DC DEMEPMAEJOO 0x1AEE62C HIGKAIDMOKN
		public int EIHOBHDKCDB { get { return FKKHMCINELD ^ FBGGEFFJJHB; } set { FKKHMCINELD = value ^ FBGGEFFJJHB; } } //0x1AEA40C EALKEGPNHGK 0x1AEE63C LNFEIPOKKNG
		public int AHHJLDLAPAN { get { return CGIGOFKGCII ^ FBGGEFFJJHB; } set { CGIGOFKGCII = value ^ FBGGEFFJJHB; } } //0x1AEA3EC IPKDLMIDMHH 0x1AEE64C IENNENMKEFO
		public int DAJGPBLEEOB { get { return HNJNKCPDKAL ^ FBGGEFFJJHB; } set { HNJNKCPDKAL = value ^ FBGGEFFJJHB; } } //0x1AEA3FC LHPKEPPBKPF 0x1AEE65C OIOEEEDODJA
		public int JBMGFNHBECN { get { return DJENABHDIPP ^ FBGGEFFJJHB; } set { DJENABHDIPP = value ^ FBGGEFFJJHB; } } //0x1AEC83C IJMJAGAPMCF 0x1AEE66C MKNANLMEHKA

		//// RVA: 0x1AEC984 Offset: 0x1AEC984 VA: 0x1AEC984
		//public long CPLKJBCBPNM(int IOPHIHFOOEP) { }

		//// RVA: 0x1AF081C Offset: 0x1AF081C VA: 0x1AF081C
		//public bool BMJGIEJPDLM(int IOPHIHFOOEP, long MIKCFEHGNJB) { }

		// RVA: 0x1AF0CCC Offset: 0x1AF0CCC VA: 0x1AF0CCC
		public KKAJHLFMBKE()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			BBEGLBMOBOF = ~FBGGEFFJJHB;
		}

		//// RVA: 0x1AF0D68 Offset: 0x1AF0D68 VA: 0x1AF0D68
		public void KHEKNNFCAOI(int PPFNGGCBJKC)
		{
			this.PPFNGGCBJKC = PPFNGGCBJKC;
			EIHOBHDKCDB = 0;
			AHHJLDLAPAN = 0;
			DAJGPBLEEOB = 0;
			JBMGFNHBECN = 0;
			JJKBBFEJFGO = new FLLIDKFECHC();
			JJKBBFEJFGO.KHEKNNFCAOI();
			HDMADAHNLDN = new List<HKMBGGGMEKA>(9);
			for(int i = 0; i < 9; i++)
			{
				HKMBGGGMEKA data = new HKMBGGGMEKA();
				data.KHEKNNFCAOI(i + 1);
				HDMADAHNLDN.Add(data);
			}
			OHMBCPHFDLD = new List<long>();
			for (int i = 0; i < 7; i++)
			{
				OHMBCPHFDLD.Add(BBEGLBMOBOF);
			}
		}

		//// RVA: 0x1AF109C Offset: 0x1AF109C VA: 0x1AF109C
		//public bool CHFOOMPEABN() { }

		//// RVA: 0x1AF2A10 Offset: 0x1AF2A10 VA: 0x1AF2A10
		//public bool DFIGPDCBAPB() { }

		//// RVA: 0x1AF10D0 Offset: 0x1AF10D0 VA: 0x1AF10D0
		//public void ODDIHGPONFL(NFMHCLHEMHB.KKAJHLFMBKE GPBJHKLFCEP) { }

		//// RVA: 0x1AF1378 Offset: 0x1AF1378 VA: 0x1AF1378
		//public bool AGBOGBEOFME(NFMHCLHEMHB.KKAJHLFMBKE OIKJFMGEICL) { }

		//// RVA: 0x1AF2A48 Offset: 0x1AF2A48 VA: 0x1AF2A48
		//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, NFMHCLHEMHB.KKAJHLFMBKE OHMCIEMIKCE, bool EFOEPDLNLJG) { }
	}

	public class HKMBGGGMEKA
	{
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private int IJLOECFBOAN; // 0x1C
		private int NLBLLLLBHOP; // 0x20
		private int HLMAFFLCCKD; // 0x24
		private long MIOBPGFAABN; // 0x28
		private int MCFFGKAOIHP; // 0x30

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ FBGGEFFJJHB; } set { EHOIENNDEDH = value ^ FBGGEFFJJHB; } } //0x1AEC920 DEMEPMAEJOO 0x1AEE704 HIGKAIDMOKN
		public int JOMGCCBFKEF { get { return IJLOECFBOAN ^ FBGGEFFJJHB; } set { IJLOECFBOAN = value ^ FBGGEFFJJHB; } } //0x1AEC930 GGFGMDFOFLG 0x1AEE714 JCJBHJOOIDP
		public int CMCKNKKCNDK { get { return NLBLLLLBHOP ^ FBGGEFFJJHB; } set { NLBLLLLBHOP = value ^ FBGGEFFJJHB; } } //0x1AEC940 CNKGOPKANGF 0x1AEE724 CHJGGLFGALP
		public int HMFFHLPNMPH { get { return HLMAFFLCCKD ^ FBGGEFFJJHB; } set { HLMAFFLCCKD = value ^ FBGGEFFJJHB; } } //0x1AEC950 NJOGDDPICKG 0x1AEE734 NBBGMMBICNA
		public long OPGPHAEMIDO { get { return MIOBPGFAABN ^ BBEGLBMOBOF; } set { MIOBPGFAABN = value ^ BBEGLBMOBOF; } } //0x1AEC960 HEBGPKBHPIB 0x1AEE744 JMKELOPNAGE
		public int CCKELABMHIO { get { return MCFFGKAOIHP ^ FBGGEFFJJHB; } set { MCFFGKAOIHP = value ^ FBGGEFFJJHB; } } //0x1AEC974 GGHKPKEGFLM 0x1AEE764 GCDJHHFGLLE

		// RVA: 0x1AF2724 Offset: 0x1AF2724 VA: 0x1AF2724
		public HKMBGGGMEKA()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			BBEGLBMOBOF = ~FBGGEFFJJHB;
		}

		//// RVA: 0x1AF27C0 Offset: 0x1AF27C0 VA: 0x1AF27C0
		public void KHEKNNFCAOI(int PPFNGGCBJKC)
		{
			this.PPFNGGCBJKC = PPFNGGCBJKC;
			JOMGCCBFKEF = 0;
			CMCKNKKCNDK = 0;
			HMFFHLPNMPH = 0;
			OPGPHAEMIDO = 0;
			CCKELABMHIO = 0;
		}

		//// RVA: 0x1AF27F0 Offset: 0x1AF27F0 VA: 0x1AF27F0
		//public void ODDIHGPONFL(NFMHCLHEMHB.HKMBGGGMEKA GPBJHKLFCEP) { }

		//// RVA: 0x1AF2924 Offset: 0x1AF2924 VA: 0x1AF2924
		//public bool AGBOGBEOFME(NFMHCLHEMHB.HKMBGGGMEKA OIKJFMGEICL) { }
	}

	public class OCLGCNPBNHE
	{
		public int FBGGEFFJJHB; // 0x8
		public long BBEGLBMOBOF; // 0x10
		private int EHOIENNDEDH; // 0x18
		private long EEDMPMBDGJN; // 0x20

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ FBGGEFFJJHB; } set { EHOIENNDEDH = value ^ FBGGEFFJJHB; } } //0x1AECA98 DEMEPMAEJOO 0x1AEE774 HIGKAIDMOKN
		public long MIKCFEHGNJB { get { return EEDMPMBDGJN ^ BBEGLBMOBOF; } set { EEDMPMBDGJN = value ^ BBEGLBMOBOF; } } //0x1AECAA8 PPCHCNBHAAG 0x1AEE784 DKKLANMGOIF

		// RVA: 0x1AF0F60 Offset: 0x1AF0F60 VA: 0x1AF0F60
		public OCLGCNPBNHE()
		{
			FBGGEFFJJHB = LPDNKHAIOLH.CEIBAFOCNCA();
			BBEGLBMOBOF = ~FBGGEFFJJHB;
		}

		//// RVA: 0x1AF0FFC Offset: 0x1AF0FFC VA: 0x1AF0FFC
		public void KHEKNNFCAOI(int PPFNGGCBJKC)
		{
			this.PPFNGGCBJKC = PPFNGGCBJKC;
			MIKCFEHGNJB = 0;
		}

		//// RVA: 0x1AECA64 Offset: 0x1AECA64 VA: 0x1AECA64
		//public bool DFIGPDCBAPB() { }
	}

	 private const int ECFEMKGFDCE = 2;
	 public static string POFDDFCGEGP = "_"; // 0x0

	 public List<CCGKCGJKADC> MPCJGPEBCCD { get; private set; } // 0x24 JIFCNLJLCFC IKJFFEHHGBA BBPFBLJNACB
	// public override bool DMICHEJIAJL { get; }

	// // RVA: 0x1AEA1B0 Offset: 0x1AEA1B0 VA: 0x1AEA1B0
	// public NFMHCLHEMHB.CCGKCGJKADC GCINIJEMHFK(int PPFNGGCBJKC) { }

	// // RVA: 0x1AEA23C Offset: 0x1AEA23C VA: 0x1AEA23C
	// public bool DFIGPDCBAPB(int PPFNGGCBJKC) { }

	// // RVA: 0x1AEA41C Offset: 0x1AEA41C VA: 0x1AEA41C
	// public NFMHCLHEMHB.CCGKCGJKADC EACEMMDIPFD() { }

	// // RVA: 0x1AEA574 Offset: 0x1AEA574 VA: 0x1AEA574
	public NFMHCLHEMHB_Bingo()
	{
		MPCJGPEBCCD = new List<CCGKCGJKADC>(10);
		KMBPACJNEOF();
	}

	// // RVA: 0x1AEA618 Offset: 0x1AEA618 VA: 0x1AEA618 Slot: 4
	public override void KMBPACJNEOF()
	{
		MPCJGPEBCCD.Clear();
		for(int i = 0; i < 10; i++)
		{
			CCGKCGJKADC data = new CCGKCGJKADC();
			data.KHEKNNFCAOI(i + 1);
			MPCJGPEBCCD.Add(data);
		}
	}

	// // RVA: 0x1AEA9A4 Offset: 0x1AEA9A4 VA: 0x1AEA9A4 Slot: 5
	// public override void OKJPIBHMKMJ(EDOHBJAPLPF_JsonData OILEIIEIBHP, long MCKEOKFMLAH) { }

	// // RVA: 0x1AECB9C Offset: 0x1AECB9C VA: 0x1AECB9C Slot: 6
	public override bool IIEMACPEEBJ_Deserialize(EDOHBJAPLPF_JsonData OILEIIEIBHP)
	{
		TodoLogger.Log(0, "TODO");
		return true;
	}

	// // RVA: 0x1AEE7A4 Offset: 0x1AEE7A4 VA: 0x1AEE7A4 Slot: 7
	// public override void BMGGKONLFIC(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0x1AEEAE0 Offset: 0x1AEEAE0 VA: 0x1AEEAE0 Slot: 8
	// public override bool AGBOGBEOFME(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0x1AEEE2C Offset: 0x1AEEE2C VA: 0x1AEEE2C Slot: 10
	// public override void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, KLFDBFMNLBL GJLFANGDGCL, long MCKEOKFMLAH) { }

	// // RVA: 0x1AF0698 Offset: 0x1AF0698 VA: 0x1AF0698 Slot: 9
	// public override bool NFKFOODCJJB() { }
}
