
using System.Collections.Generic;

[System.Obsolete("Use OCMJNBIFJNM_Offer", true)]
public class OCMJNBIFJNM { }
public class OCMJNBIFJNM_Offer : KLFDBFMNLBL_ServerSaveBlock
{
	public class JPOHOLBBFGP
	{
		private int EHOIENNDEDH; // 0x8
		private int ICPJNJLHKPB; // 0xC
		private int NOFECLGOLAI; // 0x10
		private int INNAAKJONMJ; // 0x14
		private int CNFEJDCFKPB; // 0x18
		private int EGFONKCBCKO; // 0x1C
		private long JAABPHOMCAP; // 0x20
		private long AIOMEDDAPKB; // 0x28
		private long HMDBEHOHPGN; // 0x30
		private int BJMDLOCLCEN; // 0x38
		private int MFHADBAGMCE; // 0x3C
		private int IFEHKNJONPL; // 0x40
		private int BIBOHDLOHOD; // 0x44
		private int DINFDLNMILH; // 0x48
		private int PGDEAJOOHJG; // 0x4C
		public int INCHFKJOIEK; // 0x50
		public int DCKFIBJANOG; // 0x54
		public int FECFOELPDCA; // 0x58
		public int EOONNJAMAMJ; // 0x5C
		public int GFKFDBNAMCH; // 0x60
		public int BJDNKECKFCO; // 0x64
		public long EMPBHKIFOAD; // 0x68
		public long FPFMLAEDCMG; // 0x70
		public long PBEIHONDFLH; // 0x78
		public int IGLJIECEOMG; // 0x80
		public int ONFJFGFNGGD; // 0x84
		public int AHMMIENMLLH; // 0x88
		public int LLLNINDDNFE; // 0x8C
		public int DDCAGHDNPEO; // 0x90

		public int PPFNGGCBJKC { get { return EHOIENNDEDH ^ ENOBDCFHELD; } set { EHOIENNDEDH = value ^ ENOBDCFHELD; INCHFKJOIEK = value ^ FCEJCHGLFGN; } } //0x1B3319C DEMEPMAEJOO 0x1B341FC HIGKAIDMOKN
		public int MLDPDLPHJPM { get { return ICPJNJLHKPB ^ ENOBDCFHELD; } set { ICPJNJLHKPB = value ^ ENOBDCFHELD; DCKFIBJANOG = value ^ FCEJCHGLFGN; } } //0x1B331B0 EJEKNOACOFD 0x1B34220 DBBHJDGJOCA
		public int GBJFNGCDKPM { get { return NOFECLGOLAI ^ ENOBDCFHELD; } set { NOFECLGOLAI = value ^ ENOBDCFHELD; FECFOELPDCA = value ^ FCEJCHGLFGN; } } //0x1B31930 CEJJMKODOGK 0x1B34244 HOHCEBMMACI
		public int EALOBDHOCHP { get { return INNAAKJONMJ ^ ENOBDCFHELD; } set { INNAAKJONMJ = value ^ ENOBDCFHELD; EOONNJAMAMJ = value ^ FCEJCHGLFGN; } } //0x1B31798 KLDFNIEJBFE 0x1B34268 GJLLJFLGMCN
		public int OIOECMEEFKJ { get { return CNFEJDCFKPB ^ ENOBDCFHELD; } set { CNFEJDCFKPB = value ^ ENOBDCFHELD; GFKFDBNAMCH = value ^ FCEJCHGLFGN; } } //0x1B331C4 NOHNJIIHJFA 0x1B3428C MMMGEECFJPJ
		public int MNCEBKHBBEF { get { return EGFONKCBCKO ^ ENOBDCFHELD; } set { EGFONKCBCKO = value ^ ENOBDCFHELD; BJDNKECKFCO = value ^ FCEJCHGLFGN; } } //0x1B331D8 EBLIADGGLGA 0x1B342B0 ELEONKNCLBC
		public long DFJLNPFJGDK { get { return JAABPHOMCAP ^ DAMPKGIGHIM; } set { JAABPHOMCAP = value ^ DAMPKGIGHIM; EMPBHKIFOAD = value ^ JJNNFNNELIH; } } //0x1B331EC NIBPLJHMJPP 0x1B342D4 LJHPCABPJHF
		public long NCDHKKCCGOD { get { return AIOMEDDAPKB ^ DAMPKGIGHIM; } set { AIOMEDDAPKB = value ^ DAMPKGIGHIM; FPFMLAEDCMG = value ^ JJNNFNNELIH; } } //0x1B33200 KIHJCBHEKAM 0x1B3430C MFNAKDJPPNL
		public long KOOEOKEDJDO { get { return HMDBEHOHPGN ^ DAMPKGIGHIM; } set { HMDBEHOHPGN = value ^ DAMPKGIGHIM; PBEIHONDFLH = value ^ JJNNFNNELIH; } } //0x1B33214 BABHKIGIOPO 0x1B34344 PCOFGPBACAM
		public int JIOMCDGKIAF { get { return BJMDLOCLCEN ^ ENOBDCFHELD; } set { BJMDLOCLCEN = value ^ ENOBDCFHELD; } } //0x1B37504 DJHPCCHENCM 0x1B37518 CJEGJOKIJPO
		public bool LHMOAJAIJCO { get { return MFHADBAGMCE == ENOBDCFHELD; } set { MFHADBAGMCE = value ? ENOBDCFHELD : FCEJCHGLFGN; IGLJIECEOMG = value ? FCEJCHGLFGN : ENOBDCFHELD; } } //0x1B33228 ECKLIIBFNGI 0x1B3437C BGNCBCKNKNK
		public int BFINGCJHOHI { get { return IFEHKNJONPL ^ ENOBDCFHELD; } set { IFEHKNJONPL = value ^ ENOBDCFHELD; ONFJFGFNGGD = value ^ FCEJCHGLFGN; } } //0x1B33244 LFMCLIDAPHB 0x1B343E4 EDAEPDGGFJJ
		public int PIBLLGLCJEO { get { return BIBOHDLOHOD ^ ENOBDCFHELD; } set { BIBOHDLOHOD = value ^ ENOBDCFHELD; AHMMIENMLLH = value ^ FCEJCHGLFGN; } } //0x1B33258 CMKMAGNMPGC 0x1B34408 CICCOMMMNHK
		public int NACGJGLGOHM { get { return DINFDLNMILH ^ ENOBDCFHELD; } set { DINFDLNMILH = value ^ ENOBDCFHELD; LLLNINDDNFE = value ^ FCEJCHGLFGN; } } //0x1B3326C BHBFAPJLGLH 0x1B3442C KGOGHLFFMPM
		public int JBPOABLNLHC { get { return PGDEAJOOHJG ^ ENOBDCFHELD; } set { PGDEAJOOHJG = value ^ ENOBDCFHELD; DDCAGHDNPEO = value ^ FCEJCHGLFGN; } } //0x1B33280 LJJNNMMNFLA 0x1B34450 MLCNJKIICLJ
		public string BDJMFDKLHPM { get; set; } // 0x94 EOBCNECIOMH GFMBGPMJPLJ ENAMMCHJBDE

		//// RVA: 0x1B3752C Offset: 0x1B3752C VA: 0x1B3752C
		//public bool DPMCPMJJGAA(BOPFPIHGJMD.CMBJEEGFODD LPJJLOIFCID) { }

		//// RVA: 0x1B37548 Offset: 0x1B37548 VA: 0x1B37548
		//public void HKFGCIOEMJE(BOPFPIHGJMD.CMBJEEGFODD LPJJLOIFCID) { }

		//// RVA: 0x1B37578 Offset: 0x1B37578 VA: 0x1B37578
		//public void BKMEPICADBC(BOPFPIHGJMD.CMBJEEGFODD LPJJLOIFCID) { }

		//// RVA: 0x1B375A8 Offset: 0x1B375A8 VA: 0x1B375A8
		//public void BKMEPICADBC() { }

		// RVA: 0x1B31F54 Offset: 0x1B31F54 VA: 0x1B31F54
		public JPOHOLBBFGP()
		{
			LHPDDGIJKNB(0);
			JIOMCDGKIAF = 0;
		}

		//// RVA: 0x1B313B0 Offset: 0x1B313B0 VA: 0x1B313B0
		public void LHPDDGIJKNB(int HBCEIBHJPFN = -1)
		{
			if(HBCEIBHJPFN > -1)
			{
				PPFNGGCBJKC = HBCEIBHJPFN;
			}
			KOOEOKEDJDO = 0;
			MNCEBKHBBEF = 0;
			MLDPDLPHJPM = 0;
			GBJFNGCDKPM = 0;
			EALOBDHOCHP = 0;
			OIOECMEEFKJ = 0;
			DFJLNPFJGDK = 0;
			NCDHKKCCGOD = 0;
			LHMOAJAIJCO = false;
			BFINGCJHOHI = 0;
			PIBLLGLCJEO = 0;
			NACGJGLGOHM = 0;
			JBPOABLNLHC = 0;
			BDJMFDKLHPM = "";
		}

		//// RVA: 0x1B348E0 Offset: 0x1B348E0 VA: 0x1B348E0
		//public void ODDIHGPONFL(OCMJNBIFJNM.JPOHOLBBFGP GPBJHKLFCEP) { }

		//// RVA: 0x1B35168 Offset: 0x1B35168 VA: 0x1B35168
		//public bool AGBOGBEOFME(OCMJNBIFJNM.JPOHOLBBFGP OIKJFMGEICL) { }

		//// RVA: 0x1B310E8 Offset: 0x1B310E8 VA: 0x1B310E8
		//public bool DFIGPDCBAPB() { }

		//// RVA: 0x1B366D8 Offset: 0x1B366D8 VA: 0x1B366D8
		//public void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, string JIKKNHIAEKG, string MJBACHKCIHA, int OIPCCBHIKIA, OCMJNBIFJNM.JPOHOLBBFGP OHMCIEMIKCE, bool EFOEPDLNLJG) { }
	}

	public class PMOECIDOLNA
	{
		private NNJFKLBPBNK_SecureString FINCFIGKHPA = new NNJFKLBPBNK_SecureString(); // 0x8
		private int[] EHOIENNDEDH = new int[3]; // 0xC

		public string OPFGFINHFCE { get { return FINCFIGKHPA.DNJEJEANJGL_Value; } set { FINCFIGKHPA.DNJEJEANJGL_Value = value; } } //0x1B334F0 DKJOHDGOIJE 0x1B34484 MJAMIGECMMF

		//// RVA: 0x1B3351C Offset: 0x1B3351C VA: 0x1B3351C
		//public int LBCCCKNANMJ(int IOPHIHFOOEP) { }

		//// RVA: 0x1B32050 Offset: 0x1B32050 VA: 0x1B32050
		public bool ODGFPJFJPFP(int IOPHIHFOOEP, int FODKKJIDDKN)
		{
			bool b = 99 < FODKKJIDDKN;
			bool b2 = FODKKJIDDKN == 100;
			bool res = false;
			if(FODKKJIDDKN < 101)
			{
				b = 1 < IOPHIHFOOEP;
				b2 = IOPHIHFOOEP == 2;
			}
			if(!b || b2)
			{
				EHOIENNDEDH[IOPHIHFOOEP] = FODKKJIDDKN ^ ENOBDCFHELD;
				res = true;
			}
			return res;
		}

		//// RVA: 0x1B3201C Offset: 0x1B3201C VA: 0x1B3201C
		public void LHPDDGIJKNB(string MHNBNPJMDGL = "")
		{
			OPFGFINHFCE = MHNBNPJMDGL;
			for (int i = 0; i < 3; i++)
			{
				ODGFPJFJPFP(i, 0);
			}
		}

		//// RVA: 0x1B34B78 Offset: 0x1B34B78 VA: 0x1B34B78
		//public void ODDIHGPONFL(OCMJNBIFJNM.PMOECIDOLNA GPBJHKLFCEP) { }

		//// RVA: 0x1B3558C Offset: 0x1B3558C VA: 0x1B3558C
		//public bool AGBOGBEOFME(OCMJNBIFJNM.PMOECIDOLNA OIKJFMGEICL) { }
	}

	private const int ECFEMKGFDCE = 2;
	private const int ENOBDCFHELD = 0x7549a513;
	private const int FCEJCHGLFGN = 0x715a9543;
	private const long DAMPKGIGHIM = 0x7549a513;
	private const long JJNNFNNELIH = 0x715a9543;
	private const string POFDDFCGEGP = "_";
	private long FELCCJLALLN = DAMPKGIGHIM; // 0x30
	public long KKMOKKKBJPH = JJNNFNNELIH; // 0x38
	private long DGDMMLKHKGB = DAMPKGIGHIM; // 0x40
	public long NNKEKAIINKG = JJNNFNNELIH; // 0x48
	private int KCIMAFPMDFF = ENOBDCFHELD; // 0x50
	public int PKDHAGEKMFJ = FCEJCHGLFGN; // 0x54
	private int PHMINEDNKIA = ENOBDCFHELD; // 0x58
	public int JMEMKJIPNIM = FCEJCHGLFGN; // 0x5C
	private int FJJIEMHHCEB = ENOBDCFHELD; // 0x60
	public int OBIBODJDAAH = FCEJCHGLFGN; // 0x64
	private int HIOJLJHFHJI; // 0x68
	public int LHKAJBLEOJP; // 0x6C
	private int ODGEECOIMLK; // 0x70
	public int FIFFBHDIOMI; // 0x74
	private int LOIHBJBPLCE; // 0x78
	private int NNDPDBJCELB; // 0x7C
	private int[] AELDPNJIOOC; // 0x80
	private int PGHGOOFMDMI; // 0x84

	public List<JPOHOLBBFGP> FOFLMHELILC { get; private set; } // 0x24 MODPKBBCNEP FEAKKIANKJD MIDJOPPIGLK
	public List<PMOECIDOLNA> NEGDGHKOFFF { get; private set; } // 0x28 NIHGMLEADCF MNFOOGHFKOL BBPKMGNNKDL
	public long LJPLPIOJCNK { get { return FELCCJLALLN ^ DAMPKGIGHIM; } set { FELCCJLALLN = value ^ DAMPKGIGHIM; KKMOKKKBJPH = value ^ JJNNFNNELIH; } } // AMACLCHBDGJ 0x1B30E24 MBPKGMBDKJA 0x1B30E38
	public long JKIFLFKFHPB { get { return DGDMMLKHKGB ^ DAMPKGIGHIM; } set { DGDMMLKHKGB = value ^ DAMPKGIGHIM; NNKEKAIINKG = value ^ JJNNFNNELIH; } } // GJOFKKKECDH 0x1B30E70 APKIIKHFKCK 0x1B30E88
	public int KPAJEAHFPFH { get { return KCIMAFPMDFF ^ ENOBDCFHELD; } set { KCIMAFPMDFF = value ^ ENOBDCFHELD; PKDHAGEKMFJ = value ^ FCEJCHGLFGN; } } // PHFCLOFLJPI 0x1B30EC0 AGPHKBANKCF 0x1B30ED4
	public int EAINJDPLIAG { get { return PHMINEDNKIA ^ ENOBDCFHELD; } set { PHMINEDNKIA = value ^ ENOBDCFHELD; JMEMKJIPNIM = value ^ FCEJCHGLFGN; } } // AMDBKOOCKJJ 0x1B30EF4 ILFOGMPFFGA 0x1B30F08
	public int JLFONLABECA { get { return FJJIEMHHCEB ^ ENOBDCFHELD; } set { FJJIEMHHCEB = value ^ ENOBDCFHELD; OBIBODJDAAH = value ^ FCEJCHGLFGN; } } // DADPKEBBAAP 0x1B30F28 IBNKKFGJAFN 0x1B30F3C
	public int JNIGHEHKAHG { get { return HIOJLJHFHJI ^ ENOBDCFHELD; } set { HIOJLJHFHJI = value ^ ENOBDCFHELD; LHKAJBLEOJP = value ^ FCEJCHGLFGN; } } // MOCAOPPMPDO 0x1B30FCC FNLOFIIKLLK 0x1B30FE0
	public int DFCFJMOLIOC { get { return ODGEECOIMLK ^ ENOBDCFHELD; } set { ODGEECOIMLK = value ^ ENOBDCFHELD; FIFFBHDIOMI = value ^ FCEJCHGLFGN; } } // EIINPPOFNOK 0x1B31000 LCHDFMFJNKI 0x1B31014
	public int GHKKEFGDIBC { get { return LOIHBJBPLCE ^ ENOBDCFHELD; } set { LOIHBJBPLCE = value ^ ENOBDCFHELD; } } // EDBPDAJBLKA 0x1B31944 IAGFEICDNLP 0x1B31958
	public int CHFMCFNEFEO { get { return NNDPDBJCELB ^ ENOBDCFHELD; } set { NNDPDBJCELB = value ^ ENOBDCFHELD; } } // IEPJFBCMFFB 0x1B3196C GJAMHFABMPF 0x1B31980
	public int KNIKMMKNOFA { get { return PGHGOOFMDMI ^ ENOBDCFHELD; } set { PGHGOOFMDMI = value ^ ENOBDCFHELD; } } // LKJJIINADLD 0x1B31A4C IHOKNBIAPLL 0x1B31A60
	// public override bool DMICHEJIAJL { get; } // ??

	// // RVA: 0x1B30F5C Offset: 0x1B30F5C VA: 0x1B30F5C
	// public bool MLBBKNLPBBD(BOPFPIHGJMD.PDLKAKEABDP COONLEFJBMP) { }

	// // RVA: 0x1B30F84 Offset: 0x1B30F84 VA: 0x1B30F84
	// public void ILMPHFPFLJE(BOPFPIHGJMD.PDLKAKEABDP COONLEFJBMP, bool OAFPGJLCNFM) { }

	// // RVA: 0x1B31034 Offset: 0x1B31034 VA: 0x1B31034
	// public OCMJNBIFJNM.JPOHOLBBFGP GCINIJEMHFK(int PPFNGGCBJKC) { }

	// // RVA: 0x1B310C8 Offset: 0x1B310C8 VA: 0x1B310C8
	// public bool DFIGPDCBAPB(int PPFNGGCBJKC) { }

	// // RVA: 0x1B3121C Offset: 0x1B3121C VA: 0x1B3121C
	// public OCMJNBIFJNM.JPOHOLBBFGP EACEMMDIPFD() { }

	// // RVA: 0x1B31374 Offset: 0x1B31374 VA: 0x1B31374
	// public OCMJNBIFJNM.JPOHOLBBFGP KHEKNNFCAOI_Init(int PPFNGGCBJKC) { }

	// // RVA: 0x1B314F8 Offset: 0x1B314F8 VA: 0x1B314F8
	// public OCMJNBIFJNM.JPOHOLBBFGP KLMOEMBHNCM(BOPFPIHGJMD.MLBMHDCCGHI FGHGMHPNEMG, int MLDPDLPHJPM) { }

	// // RVA: 0x1B31614 Offset: 0x1B31614 VA: 0x1B31614
	// public List<OCMJNBIFJNM.JPOHOLBBFGP> CCMINIGMJDM(BOPFPIHGJMD.IGHPDAGKIKO CMCKNKKCNDK) { }

	// // RVA: 0x1B317AC Offset: 0x1B317AC VA: 0x1B317AC
	// public List<OCMJNBIFJNM.JPOHOLBBFGP> DOFBNAIFFAN(BOPFPIHGJMD.MLBMHDCCGHI INDDJNMPONH) { }

	// // RVA: 0x1B31994 Offset: 0x1B31994 VA: 0x1B31994
	// public int MIPAIEGENEA(int IOPHIHFOOEP) { }

	// // RVA: 0x1B319F4 Offset: 0x1B319F4 VA: 0x1B319F4
	public void ALANKFMEIPK(int IOPHIHFOOEP, int JBGEEPFKIGG)
	{
		if(IOPHIHFOOEP > -1 && AELDPNJIOOC.Length > IOPHIHFOOEP)
		{
			AELDPNJIOOC[IOPHIHFOOEP] = JBGEEPFKIGG ^ ENOBDCFHELD;
		}
	}

	// // RVA: 0x1B31A78 Offset: 0x1B31A78 VA: 0x1B31A78
	public OCMJNBIFJNM_Offer()
	{
		FOFLMHELILC = new List<JPOHOLBBFGP>(1000);
		NEGDGHKOFFF = new List<PMOECIDOLNA>(5);
		AELDPNJIOOC = new int[10];
		KMBPACJNEOF();
	}

	// // RVA: 0x1B31BD0 Offset: 0x1B31BD0 VA: 0x1B31BD0 Slot: 4
	public override void KMBPACJNEOF()
	{
		FOFLMHELILC.Clear();
		NEGDGHKOFFF.Clear();
		for (int i = 0; i < 1000; i++)
		{
			JPOHOLBBFGP data = new JPOHOLBBFGP();
			data.LHPDDGIJKNB(i + 1);
			FOFLMHELILC.Add(data);
		}
		LGHIPHEDCNC_Offer offerDb = IMMAOANGPNK.HHCJCDFCLOB.NKEBMCIMJND_Database.LBCMJGOOHLJ_Offer;
		string defName = offerDb.EFEGBHACJAL("default_vf_platoon_name", JpStringLiterals.StringLiteral_12943);
		for(int i = 0; i < 5; i++)
		{
			PMOECIDOLNA data = new PMOECIDOLNA();
			data.LHPDDGIJKNB(defName);
			NEGDGHKOFFF.Add(data);
		}
		NEGDGHKOFFF[0].ODGFPJFJPFP(0, 1);
		KNIKMMKNOFA = 0;
		DFCFJMOLIOC = 0;
		GHKKEFGDIBC = 1;
		CHFMCFNEFEO = 1;
		LJPLPIOJCNK = 0;
		JKIFLFKFHPB = 0;
		KPAJEAHFPFH = 0;
		EAINJDPLIAG = 0;
		JLFONLABECA = 0;
		JNIGHEHKAHG = 0;
		for(int i = 0; i < AELDPNJIOOC.Length; i++)
		{
			ALANKFMEIPK(i, 2);
		}
	}

	// // RVA: 0x1B320C0 Offset: 0x1B320C0 VA: 0x1B320C0 Slot: 5
	// public override void OKJPIBHMKMJ(EDOHBJAPLPF_JsonData OILEIIEIBHP, long MCKEOKFMLAH) { }

	// // RVA: 0x1B3329C Offset: 0x1B3329C VA: 0x1B3329C
	// private EDOHBJAPLPF_JsonData BGGGENIANOD(OCMJNBIFJNM.PMOECIDOLNA FFOINHDALAM) { }

	// // RVA: 0x1B33580 Offset: 0x1B33580 VA: 0x1B33580 Slot: 6
	public override bool IIEMACPEEBJ_Deserialize(EDOHBJAPLPF_JsonData OILEIIEIBHP)
	{
		TodoLogger.Log(0, "TODO");
		return true;
	}

	// // RVA: 0x1B344B8 Offset: 0x1B344B8 VA: 0x1B344B8 Slot: 7
	// public override void BMGGKONLFIC(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0x1B34BEC Offset: 0x1B34BEC VA: 0x1B34BEC Slot: 8
	// public override bool AGBOGBEOFME(KLFDBFMNLBL GPBJHKLFCEP) { }

	// // RVA: 0x1B35630 Offset: 0x1B35630 VA: 0x1B35630 Slot: 10
	// public override void AGHKODFKOJI(BHBONAHFKHD JBBHNIACMFJ, KLFDBFMNLBL GJLFANGDGCL, long MCKEOKFMLAH) { }

	// // RVA: 0x1B36D84 Offset: 0x1B36D84 VA: 0x1B36D84 Slot: 11
	public override FENCAJJBLBH PFAKPFKJJKA()
	{
		TodoLogger.Log(0, "TODO");
		return null;
	}

	// // RVA: 0x1B373C0 Offset: 0x1B373C0 VA: 0x1B373C0 Slot: 9
	// public override bool NFKFOODCJJB() { }

	// [CompilerGeneratedAttribute] // RVA: 0x6BF220 Offset: 0x6BF220 VA: 0x6BF220
	// // RVA: 0x1B373C8 Offset: 0x1B373C8 VA: 0x1B373C8
	// private void <Deserialize>b__79_0(int OIPCCBHIKIA, int JBGEEPFKIGG) { }
}
