# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class AHCMKLEDILD(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAHCMKLEDILD(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AHCMKLEDILD()
        x.Init(buf, n + offset)
        return x

    # AHCMKLEDILD
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AHCMKLEDILD
    def DCEDMFDNAKH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # AHCMKLEDILD
    def OFMGALJGDAO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def AHCMKLEDILDStart(builder): builder.StartObject(2)
def AHCMKLEDILDAddDCEDMFDNAKH(builder, DCEDMFDNAKH): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(DCEDMFDNAKH), 0)
def AHCMKLEDILDAddOFMGALJGDAO(builder, OFMGALJGDAO): builder.PrependInt32Slot(1, OFMGALJGDAO, 0)
def AHCMKLEDILDEnd(builder): return builder.EndObject()
