# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class AMMFBOPDMFI(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAMMFBOPDMFI(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AMMFBOPDMFI()
        x.Init(buf, n + offset)
        return x

    # AMMFBOPDMFI
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AMMFBOPDMFI
    def JIHMDOCLAPK(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .EFOIDPJOBDM import EFOIDPJOBDM
            obj = EFOIDPJOBDM()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AMMFBOPDMFI
    def JIHMDOCLAPKLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AMMFBOPDMFIStart(builder): builder.StartObject(1)
def AMMFBOPDMFIAddJIHMDOCLAPK(builder, JIHMDOCLAPK): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(JIHMDOCLAPK), 0)
def AMMFBOPDMFIStartJIHMDOCLAPKVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AMMFBOPDMFIEnd(builder): return builder.EndObject()
