# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class BDHHMNFDCJO(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBDHHMNFDCJO(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BDHHMNFDCJO()
        x.Init(buf, n + offset)
        return x

    # BDHHMNFDCJO
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BDHHMNFDCJO
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BDHHMNFDCJO
    def DPFDOIIOICA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BDHHMNFDCJO
    def GEAIPAEKLNF(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BDHHMNFDCJO
    def JGILGOILJNK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BDHHMNFDCJOStart(builder): builder.StartObject(4)
def BDHHMNFDCJOAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependInt32Slot(0, BBPHAPFBFHK, 0)
def BDHHMNFDCJOAddDPFDOIIOICA(builder, DPFDOIIOICA): builder.PrependInt32Slot(1, DPFDOIIOICA, 0)
def BDHHMNFDCJOAddGEAIPAEKLNF(builder, GEAIPAEKLNF): builder.PrependInt32Slot(2, GEAIPAEKLNF, 0)
def BDHHMNFDCJOAddJGILGOILJNK(builder, JGILGOILJNK): builder.PrependInt32Slot(3, JGILGOILJNK, 0)
def BDHHMNFDCJOEnd(builder): return builder.EndObject()
