# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class BNKFBEGNEHA(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBNKFBEGNEHA(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BNKFBEGNEHA()
        x.Init(buf, n + offset)
        return x

    # BNKFBEGNEHA
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BNKFBEGNEHA
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def CFLMCGOJJJD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def IIDCFMHCPLJ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # BNKFBEGNEHA
    def MAIJBDCJPNJ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def OFMGALJGDAO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def NJLJEKDBPCH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def MAOAGDBDBIB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BNKFBEGNEHA
    def JEEDFKICAKL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BNKFBEGNEHAStart(builder): builder.StartObject(8)
def BNKFBEGNEHAAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependInt32Slot(0, BBPHAPFBFHK, 0)
def BNKFBEGNEHAAddCFLMCGOJJJD(builder, CFLMCGOJJJD): builder.PrependInt32Slot(1, CFLMCGOJJJD, 0)
def BNKFBEGNEHAAddIIDCFMHCPLJ(builder, IIDCFMHCPLJ): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(IIDCFMHCPLJ), 0)
def BNKFBEGNEHAAddMAIJBDCJPNJ(builder, MAIJBDCJPNJ): builder.PrependInt32Slot(3, MAIJBDCJPNJ, 0)
def BNKFBEGNEHAAddOFMGALJGDAO(builder, OFMGALJGDAO): builder.PrependInt32Slot(4, OFMGALJGDAO, 0)
def BNKFBEGNEHAAddNJLJEKDBPCH(builder, NJLJEKDBPCH): builder.PrependInt32Slot(5, NJLJEKDBPCH, 0)
def BNKFBEGNEHAAddMAOAGDBDBIB(builder, MAOAGDBDBIB): builder.PrependInt32Slot(6, MAOAGDBDBIB, 0)
def BNKFBEGNEHAAddJEEDFKICAKL(builder, JEEDFKICAKL): builder.PrependInt32Slot(7, JEEDFKICAKL, 0)
def BNKFBEGNEHAEnd(builder): return builder.EndObject()
