# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class BPAAICMLPOI(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBPAAICMLPOI(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BPAAICMLPOI()
        x.Init(buf, n + offset)
        return x

    # BPAAICMLPOI
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BPAAICMLPOI
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BPAAICMLPOI
    def LPJPOOHJKAE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BPAAICMLPOI
    def KJFEBMBHKOC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BPAAICMLPOI
    def LAIEPFCPDLK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BPAAICMLPOIStart(builder): builder.StartObject(4)
def BPAAICMLPOIAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependInt32Slot(0, BBPHAPFBFHK, 0)
def BPAAICMLPOIAddLPJPOOHJKAE(builder, LPJPOOHJKAE): builder.PrependInt32Slot(1, LPJPOOHJKAE, 0)
def BPAAICMLPOIAddKJFEBMBHKOC(builder, KJFEBMBHKOC): builder.PrependInt32Slot(2, KJFEBMBHKOC, 0)
def BPAAICMLPOIAddLAIEPFCPDLK(builder, LAIEPFCPDLK): builder.PrependInt32Slot(3, LAIEPFCPDLK, 0)
def BPAAICMLPOIEnd(builder): return builder.EndObject()
