# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class GAPIOFFIFKN(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGAPIOFFIFKN(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GAPIOFFIFKN()
        x.Init(buf, n + offset)
        return x

    # GAPIOFFIFKN
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GAPIOFFIFKN
    def KHFMFOFIFGG(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .EIICDPMENEH import EIICDPMENEH
            obj = EIICDPMENEH()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GAPIOFFIFKN
    def KHFMFOFIFGGLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GAPIOFFIFKNStart(builder): builder.StartObject(1)
def GAPIOFFIFKNAddKHFMFOFIFGG(builder, KHFMFOFIFGG): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(KHFMFOFIFGG), 0)
def GAPIOFFIFKNStartKHFMFOFIFGGVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GAPIOFFIFKNEnd(builder): return builder.EndObject()
