# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class GIGLCNHCNEN(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGIGLCNHCNEN(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GIGLCNHCNEN()
        x.Init(buf, n + offset)
        return x

    # GIGLCNHCNEN
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GIGLCNHCNEN
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GIGLCNHCNEN
    def CFLMCGOJJJD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GIGLCNHCNEN
    def IDHMHHMGAHM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GIGLCNHCNEN
    def NJLJEKDBPCH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GIGLCNHCNEN
    def MAOAGDBDBIB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def GIGLCNHCNENStart(builder): builder.StartObject(5)
def GIGLCNHCNENAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependUint32Slot(0, BBPHAPFBFHK, 0)
def GIGLCNHCNENAddCFLMCGOJJJD(builder, CFLMCGOJJJD): builder.PrependUint32Slot(1, CFLMCGOJJJD, 0)
def GIGLCNHCNENAddIDHMHHMGAHM(builder, IDHMHHMGAHM): builder.PrependUint32Slot(2, IDHMHHMGAHM, 0)
def GIGLCNHCNENAddNJLJEKDBPCH(builder, NJLJEKDBPCH): builder.PrependUint32Slot(3, NJLJEKDBPCH, 0)
def GIGLCNHCNENAddMAOAGDBDBIB(builder, MAOAGDBDBIB): builder.PrependUint32Slot(4, MAOAGDBDBIB, 0)
def GIGLCNHCNENEnd(builder): return builder.EndObject()
