# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class HKILNANKLLB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHKILNANKLLB(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HKILNANKLLB()
        x.Init(buf, n + offset)
        return x

    # HKILNANKLLB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HKILNANKLLB
    def JCEDIBCEFOJ(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .JJEDGMMFLNA import JJEDGMMFLNA
            obj = JJEDGMMFLNA()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HKILNANKLLB
    def JCEDIBCEFOJLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HKILNANKLLB
    def GFOJACKHEDC(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .CBMILEEGEPN import CBMILEEGEPN
            obj = CBMILEEGEPN()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HKILNANKLLB
    def GFOJACKHEDCLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def HKILNANKLLBStart(builder): builder.StartObject(2)
def HKILNANKLLBAddJCEDIBCEFOJ(builder, JCEDIBCEFOJ): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(JCEDIBCEFOJ), 0)
def HKILNANKLLBStartJCEDIBCEFOJVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def HKILNANKLLBAddGFOJACKHEDC(builder, GFOJACKHEDC): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(GFOJACKHEDC), 0)
def HKILNANKLLBStartGFOJACKHEDCVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def HKILNANKLLBEnd(builder): return builder.EndObject()
