# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class JLDCIOBACAL(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsJLDCIOBACAL(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JLDCIOBACAL()
        x.Init(buf, n + offset)
        return x

    # JLDCIOBACAL
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JLDCIOBACAL
    def HOENDPOGFIO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # JLDCIOBACAL
    def PBOCIEKNBCI(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # JLDCIOBACAL
    def IHLNKPCMGNE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # JLDCIOBACAL
    def KHLNIPBFCNK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def JLDCIOBACALStart(builder): builder.StartObject(4)
def JLDCIOBACALAddHOENDPOGFIO(builder, HOENDPOGFIO): builder.PrependUint32Slot(0, HOENDPOGFIO, 0)
def JLDCIOBACALAddPBOCIEKNBCI(builder, PBOCIEKNBCI): builder.PrependUint32Slot(1, PBOCIEKNBCI, 0)
def JLDCIOBACALAddIHLNKPCMGNE(builder, IHLNKPCMGNE): builder.PrependUint32Slot(2, IHLNKPCMGNE, 0)
def JLDCIOBACALAddKHLNIPBFCNK(builder, KHLNIPBFCNK): builder.PrependUint32Slot(3, KHLNIPBFCNK, 0)
def JLDCIOBACALEnd(builder): return builder.EndObject()
