# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class JMGNAIJPDBF(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsJMGNAIJPDBF(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JMGNAIJPDBF()
        x.Init(buf, n + offset)
        return x

    # JMGNAIJPDBF
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JMGNAIJPDBF
    def HDAGLLICBAO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # JMGNAIJPDBF
    def AJAPPNMNKJH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def JMGNAIJPDBFStart(builder): builder.StartObject(2)
def JMGNAIJPDBFAddHDAGLLICBAO(builder, HDAGLLICBAO): builder.PrependInt32Slot(0, HDAGLLICBAO, 0)
def JMGNAIJPDBFAddAJAPPNMNKJH(builder, AJAPPNMNKJH): builder.PrependInt32Slot(1, AJAPPNMNKJH, 0)
def JMGNAIJPDBFEnd(builder): return builder.EndObject()
