# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class KBACMNEFKPH(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKBACMNEFKPH(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KBACMNEFKPH()
        x.Init(buf, n + offset)
        return x

    # KBACMNEFKPH
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KBACMNEFKPH
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def CFLMCGOJJJD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def IAPFGOHKAGE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def HBMAMCJNDIH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def PMPNFFNPDPJ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def NJLJEKDBPCH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KBACMNEFKPH
    def MAOAGDBDBIB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def KBACMNEFKPHStart(builder): builder.StartObject(7)
def KBACMNEFKPHAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependUint32Slot(0, BBPHAPFBFHK, 0)
def KBACMNEFKPHAddCFLMCGOJJJD(builder, CFLMCGOJJJD): builder.PrependUint32Slot(1, CFLMCGOJJJD, 0)
def KBACMNEFKPHAddIAPFGOHKAGE(builder, IAPFGOHKAGE): builder.PrependUint32Slot(2, IAPFGOHKAGE, 0)
def KBACMNEFKPHAddHBMAMCJNDIH(builder, HBMAMCJNDIH): builder.PrependUint32Slot(3, HBMAMCJNDIH, 0)
def KBACMNEFKPHAddPMPNFFNPDPJ(builder, PMPNFFNPDPJ): builder.PrependUint32Slot(4, PMPNFFNPDPJ, 0)
def KBACMNEFKPHAddNJLJEKDBPCH(builder, NJLJEKDBPCH): builder.PrependUint32Slot(5, NJLJEKDBPCH, 0)
def KBACMNEFKPHAddMAOAGDBDBIB(builder, MAOAGDBDBIB): builder.PrependUint32Slot(6, MAOAGDBDBIB, 0)
def KBACMNEFKPHEnd(builder): return builder.EndObject()
