# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class KBKAEPDDIME(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKBKAEPDDIME(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KBKAEPDDIME()
        x.Init(buf, n + offset)
        return x

    # KBKAEPDDIME
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KBKAEPDDIME
    def NMOFFGFGFKA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # KBKAEPDDIME
    def BMICKLAGCCD(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # KBKAEPDDIME
    def BMICKLAGCCDLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def KBKAEPDDIMEStart(builder): builder.StartObject(2)
def KBKAEPDDIMEAddNMOFFGFGFKA(builder, NMOFFGFGFKA): builder.PrependInt32Slot(0, NMOFFGFGFKA, 0)
def KBKAEPDDIMEAddBMICKLAGCCD(builder, BMICKLAGCCD): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(BMICKLAGCCD), 0)
def KBKAEPDDIMEStartBMICKLAGCCDVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def KBKAEPDDIMEEnd(builder): return builder.EndObject()
