# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class LKEFGGDDBJK(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLKEFGGDDBJK(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LKEFGGDDBJK()
        x.Init(buf, n + offset)
        return x

    # LKEFGGDDBJK
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LKEFGGDDBJK
    def BBPHAPFBFHK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def CFLMCGOJJJD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def LPJPOOHJKAE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def AEAKMMJLLDK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def NNKLANONDOM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # LKEFGGDDBJK
    def JGAGKFPAAIB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # LKEFGGDDBJK
    def NMGIFIOPMIJ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def NFPKGHADCCP(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def PJCPCILBICH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def GAHFANCNFIH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def ANOHJLDOAAK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def GJJPLLHMMAF(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def AJHANMOKKDF(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def PBAJJGLCCDO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def MPMOLHBIKKG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def ENECIEOGIJC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def MBBJMJAAODG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def IMCFOKIBEMC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def OADMJNEOKLC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def EGCKDOIIACL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def GPBKFHCJEPD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def EBBBDFADIPN(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def GLIIHLOLPEF(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def KMEODDMBHHE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LKEFGGDDBJK
    def CFMIBDJFAMO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def LKEFGGDDBJKStart(builder): builder.StartObject(25)
def LKEFGGDDBJKAddBBPHAPFBFHK(builder, BBPHAPFBFHK): builder.PrependUint32Slot(0, BBPHAPFBFHK, 0)
def LKEFGGDDBJKAddCFLMCGOJJJD(builder, CFLMCGOJJJD): builder.PrependUint32Slot(1, CFLMCGOJJJD, 0)
def LKEFGGDDBJKAddLPJPOOHJKAE(builder, LPJPOOHJKAE): builder.PrependUint32Slot(2, LPJPOOHJKAE, 0)
def LKEFGGDDBJKAddAEAKMMJLLDK(builder, AEAKMMJLLDK): builder.PrependUint32Slot(3, AEAKMMJLLDK, 0)
def LKEFGGDDBJKAddNNKLANONDOM(builder, NNKLANONDOM): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(NNKLANONDOM), 0)
def LKEFGGDDBJKAddJGAGKFPAAIB(builder, JGAGKFPAAIB): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(JGAGKFPAAIB), 0)
def LKEFGGDDBJKAddNMGIFIOPMIJ(builder, NMGIFIOPMIJ): builder.PrependUint32Slot(6, NMGIFIOPMIJ, 0)
def LKEFGGDDBJKAddNFPKGHADCCP(builder, NFPKGHADCCP): builder.PrependUint32Slot(7, NFPKGHADCCP, 0)
def LKEFGGDDBJKAddPJCPCILBICH(builder, PJCPCILBICH): builder.PrependUint32Slot(8, PJCPCILBICH, 0)
def LKEFGGDDBJKAddGAHFANCNFIH(builder, GAHFANCNFIH): builder.PrependUint32Slot(9, GAHFANCNFIH, 0)
def LKEFGGDDBJKAddANOHJLDOAAK(builder, ANOHJLDOAAK): builder.PrependUint32Slot(10, ANOHJLDOAAK, 0)
def LKEFGGDDBJKAddGJJPLLHMMAF(builder, GJJPLLHMMAF): builder.PrependUint32Slot(11, GJJPLLHMMAF, 0)
def LKEFGGDDBJKAddAJHANMOKKDF(builder, AJHANMOKKDF): builder.PrependUint32Slot(12, AJHANMOKKDF, 0)
def LKEFGGDDBJKAddPBAJJGLCCDO(builder, PBAJJGLCCDO): builder.PrependUint32Slot(13, PBAJJGLCCDO, 0)
def LKEFGGDDBJKAddMPMOLHBIKKG(builder, MPMOLHBIKKG): builder.PrependUint32Slot(14, MPMOLHBIKKG, 0)
def LKEFGGDDBJKAddENECIEOGIJC(builder, ENECIEOGIJC): builder.PrependUint32Slot(15, ENECIEOGIJC, 0)
def LKEFGGDDBJKAddMBBJMJAAODG(builder, MBBJMJAAODG): builder.PrependUint32Slot(16, MBBJMJAAODG, 0)
def LKEFGGDDBJKAddIMCFOKIBEMC(builder, IMCFOKIBEMC): builder.PrependUint32Slot(17, IMCFOKIBEMC, 0)
def LKEFGGDDBJKAddOADMJNEOKLC(builder, OADMJNEOKLC): builder.PrependUint32Slot(18, OADMJNEOKLC, 0)
def LKEFGGDDBJKAddEGCKDOIIACL(builder, EGCKDOIIACL): builder.PrependUint32Slot(19, EGCKDOIIACL, 0)
def LKEFGGDDBJKAddGPBKFHCJEPD(builder, GPBKFHCJEPD): builder.PrependUint32Slot(20, GPBKFHCJEPD, 0)
def LKEFGGDDBJKAddEBBBDFADIPN(builder, EBBBDFADIPN): builder.PrependUint32Slot(21, EBBBDFADIPN, 0)
def LKEFGGDDBJKAddGLIIHLOLPEF(builder, GLIIHLOLPEF): builder.PrependUint32Slot(22, GLIIHLOLPEF, 0)
def LKEFGGDDBJKAddKMEODDMBHHE(builder, KMEODDMBHHE): builder.PrependUint32Slot(23, KMEODDMBHHE, 0)
def LKEFGGDDBJKAddCFMIBDJFAMO(builder, CFMIBDJFAMO): builder.PrependUint32Slot(24, CFMIBDJFAMO, 0)
def LKEFGGDDBJKEnd(builder): return builder.EndObject()
