# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class OALBFMECCIL(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOALBFMECCIL(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OALBFMECCIL()
        x.Init(buf, n + offset)
        return x

    # OALBFMECCIL
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OALBFMECCIL
    def BNCIPLKECMC(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OALBFMECCIL
    def BNCIPLKECMCLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OALBFMECCIL
    def NMEEJNHKPCN(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OALBFMECCIL
    def NMEEJNHKPCNLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OALBFMECCIL
    def CNOKDINCFAO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # OALBFMECCIL
    def NGGAJCBPGFI(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OALBFMECCIL
    def NGGAJCBPGFILength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def OALBFMECCILStart(builder): builder.StartObject(4)
def OALBFMECCILAddBNCIPLKECMC(builder, BNCIPLKECMC): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(BNCIPLKECMC), 0)
def OALBFMECCILStartBNCIPLKECMCVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OALBFMECCILAddNMEEJNHKPCN(builder, NMEEJNHKPCN): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(NMEEJNHKPCN), 0)
def OALBFMECCILStartNMEEJNHKPCNVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OALBFMECCILAddCNOKDINCFAO(builder, CNOKDINCFAO): builder.PrependUint32Slot(2, CNOKDINCFAO, 0)
def OALBFMECCILAddNGGAJCBPGFI(builder, NGGAJCBPGFI): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(NGGAJCBPGFI), 0)
def OALBFMECCILStartNGGAJCBPGFIVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OALBFMECCILEnd(builder): return builder.EndObject()
