# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class OLMJGOPCIKK(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOLMJGOPCIKK(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OLMJGOPCIKK()
        x.Init(buf, n + offset)
        return x

    # OLMJGOPCIKK
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OLMJGOPCIKK
    def PBMIJLINDCG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OLMJGOPCIKK
    def OFMGALJGDAO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OLMJGOPCIKK
    def CFLMCGOJJJD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OLMJGOPCIKK
    def HAHMOLPJPCG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OLMJGOPCIKK
    def NJLJEKDBPCH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OLMJGOPCIKK
    def MAOAGDBDBIB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def OLMJGOPCIKKStart(builder): builder.StartObject(6)
def OLMJGOPCIKKAddPBMIJLINDCG(builder, PBMIJLINDCG): builder.PrependInt32Slot(0, PBMIJLINDCG, 0)
def OLMJGOPCIKKAddOFMGALJGDAO(builder, OFMGALJGDAO): builder.PrependInt32Slot(1, OFMGALJGDAO, 0)
def OLMJGOPCIKKAddCFLMCGOJJJD(builder, CFLMCGOJJJD): builder.PrependInt32Slot(2, CFLMCGOJJJD, 0)
def OLMJGOPCIKKAddHAHMOLPJPCG(builder, HAHMOLPJPCG): builder.PrependInt32Slot(3, HAHMOLPJPCG, 0)
def OLMJGOPCIKKAddNJLJEKDBPCH(builder, NJLJEKDBPCH): builder.PrependInt32Slot(4, NJLJEKDBPCH, 0)
def OLMJGOPCIKKAddMAOAGDBDBIB(builder, MAOAGDBDBIB): builder.PrependInt32Slot(5, MAOAGDBDBIB, 0)
def OLMJGOPCIKKEnd(builder): return builder.EndObject()
