# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PLONLLOGMEJ(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPLONLLOGMEJ(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PLONLLOGMEJ()
        x.Init(buf, n + offset)
        return x

    # PLONLLOGMEJ
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PLONLLOGMEJ
    def JEEPKOLPINE(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .GEGKPJCPNJE import GEGKPJCPNJE
            obj = GEGKPJCPNJE()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PLONLLOGMEJ
    def JEEPKOLPINELength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PLONLLOGMEJStart(builder): builder.StartObject(1)
def PLONLLOGMEJAddJEEPKOLPINE(builder, JEEPKOLPINE): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(JEEPKOLPINE), 0)
def PLONLLOGMEJStartJEEPKOLPINEVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PLONLLOGMEJEnd(builder): return builder.EndObject()
