using FlatBuffers;
using System.Collections.Generic;

public class BJMFBPEMGCD
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0xC NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public uint HFNIHKOAMGC { get; set; } // 0x10 FHBGLLIFKHM ECGBAIBHGFP CGCGLFDKHPC
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO_SaveIdx { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x20 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x24 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint BCPHKGGOEKA { get; set; } // 0x28 CBOPOFLBNPP DDOJKPFODBM IFNDFDKBPLJ
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x2C HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x30 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x34 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JMJDLDEIFKE { get; set; } // 0x38 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO_DayGroup { get; set; } // 0x3C IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE_KeyPrefix { get; set; } // 0x40 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x44 HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public int MJBKGOJBPAD_item_type { get; set; } // 0x48 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public string FEMMDNIELFC_Desc { get; set; } // 0x4C GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint HKKNEAGCIEB_RankingSupport { get; set; } // 0x50 DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public string OMCAOJJGOGG_Lb { get; set; } // 0x54 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM_StartAdventureId { get; set; } // 0x58 AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP_EndAdventureId { get; set; } // 0x5C OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public uint OHGDNJLFDFF_Start { get; set; } // 0x60 HNLGNDHJIED NHBPNMFMHOC NAIJIAGADLK
	public uint PHKLJGNMFBL_End { get; set; } // 0x64 EPNCDMLKDAD HIAAMENBKEA NKBJDKIHPPB
}
public class GHAFLMIOHKM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MGLJCOMOGLO_BtnId { get; set; } // 0x14 CMPNGIIAKNF AEIJNJKLGOI LEOGMFOMAJK
	public uint PNDEAHGLJIC_BtnType { get; set; } // 0x18 OLOFFGLBEOL FCMJGJNLHJC PMDHFNCONCH
	public int LPDLBACJKIB_TransId { get; set; } // 0x1C NIMPPGDJGCA KJEJNNIKGJA FPPDFHIGMCE
	public uint PDBPFJJCADD_open_at { get; set; } // 0x20 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x24 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public uint GNOFNIOLPPC_ImgId { get; set; } // 0x28 DDHPPJFCHHM GFDJOOOJFOA BINBNBMIJLA
	public uint BOJCOPAALNC_EventId { get; set; } // 0x2C NMHBPGGBBEE PHFOCDMIEIO MBPAGIFEGHH
}
public class OMLNDNBOGBM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM_typ { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint KGICDMIJGDF_Group { get; set; } // 0x14 LHIOCOLMMNP ENACPBCEBLF KPCDPMGBPAG
	public uint FPOMEEJFBIG_odr { get; set; } // 0x18 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC_Desc { get; set; } // 0x1C GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE_DescBalloon { get; set; } // 0x20 PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x24 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x28 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x2C NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x30 CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x34 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x38 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x3C OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x40 PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x44 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x48 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x4C KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC_item_count { get; set; } // 0x50 HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ_Link { get; set; } // 0x54 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x58 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x5C LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x60 FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO_st { get; set; } // 0x64 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM_end { get; set; } // 0x68 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class KGBNJLAIFFN
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint BDEOMEBFDFF_gacha_id { get; set; } // 0x10 MKOMLOGPCFP OEIBDDGJBMK LELOPHJEIIM
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class PDKLCAEOOLD
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint BDEOMEBFDFF_gacha_id { get; set; } // 0x10 MKOMLOGPCFP OEIBDDGJBMK LELOPHJEIIM
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class JJBOBCDGNOP
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint DNJLJMKKDNA_EventId { get; set; } // 0x10 KCIFEAIAGDG DONEINFNFCP EPEBGHFNMKP
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class LADKNAIOJBK
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint OENPCNBFPDA_bg_id { get; set; } // 0x10 CFHILALNGHJ BNLALNCFJPB KPJBLJCKBLF
	public uint KGICDMIJGDF_Group { get; set; } // 0x14 LHIOCOLMMNP ENACPBCEBLF KPCDPMGBPAG
	public uint PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class PPAOPCHAFDP
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint[] ALMEBFDEGBG { get; set; } // 0x10 OGLDIHMAGPL HJGELAJENOB MKJEDBLAODP
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class LKDADIMPPHE
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NHONHLOEGEF
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class AGOFNEFMGJC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint BDEOMEBFDFF_gacha_id { get; set; } // 0x10 MKOMLOGPCFP OEIBDDGJBMK LELOPHJEIIM
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class OLMOJDOOIOM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint KDGJBBFKLGI_Chapter { get; set; } // 0x10 IILAMFIKKFH PDFJGOMGICB FDJKJDIECDK
	public uint OIAAFFHGBBD_AdvId { get; set; } // 0x14 JOJKCBIKOIO ENLDJCEIHCK GOMCJDMDDBG
	public uint PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
}
public class AHDABPFAHNL
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint PDBPFJJCADD_open_at { get; set; } // 0x10 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x14 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public uint EJBGHLOOLBC_HelpIds { get; set; } // 0x18 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
}
public class DIFGDAIFPKN
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint[] OPKCNBFBBKP_BannerId { get; set; } // 0x10 APMFBEDHBJB HCHAEEFCPMI ILIKNLGOJHE
	public uint[] BEBJKJKBOGH_date { get; set; } // 0x14 MCIJNMKFMDB DIAPHCJBPFD_get_date IHAIKPNEEJE
	public uint PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class JAJIKIPGDOK
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint OPKCNBFBBKP_BannerId { get; set; } // 0x10 APMFBEDHBJB HCHAEEFCPMI ILIKNLGOJHE
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class HPKKBOBEMMB
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint DNJLJMKKDNA_EventId { get; set; } // 0x10 KCIFEAIAGDG DONEINFNFCP EPEBGHFNMKP
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class KFKHGNCCMCH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint DNJLJMKKDNA_EventId { get; set; } // 0x10 KCIFEAIAGDG DONEINFNFCP EPEBGHFNMKP
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class MGJDMEPNMOD
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint BDEOMEBFDFF_gacha_id { get; set; } // 0x10 MKOMLOGPCFP OEIBDDGJBMK LELOPHJEIIM
	public uint PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class ELEEMMNLBEM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint PDBPFJJCADD_open_at { get; set; } // 0x10 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x14 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class ELOPBNCMDBH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint PDBPFJJCADD_open_at { get; set; } // 0x10 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x14 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class ANCFFLNKINL
{
	public BJMFBPEMGCD HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public GHAFLMIOHKM[] OPIDLGADBPE { get; set; } // 0xC HPFOIILOCJB FMGLABIHIHC KKMBPIAJLMH
	public OMLNDNBOGBM[] MDDOGIAFDEI { get; set; } // 0x10 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public KGBNJLAIFFN[] AFMPLCMMPHO { get; set; } // 0x14 CNBLFFPMPDG PFGHNPGKDPE OKAALDHJIFO
	public PDKLCAEOOLD[] IEMKMPDAJCM { get; set; } // 0x18 HADHOJEGEOJ AMODFGPBEHL OACHJDLJFML
	public JJBOBCDGNOP[] MHCBBBFJALG { get; set; } // 0x1C LANHLFNDBCB JONCCPABNHD OJKNHLJDEPB
	public LADKNAIOJBK[] KKENLPIJOBN { get; set; } // 0x20 LJANOAALGPA ABEHFDPOAFA JJICAOFNPCE
	public PPAOPCHAFDP[] BPFJNIGNLEJ { get; set; } // 0x24 FMDAIMFADKD KNBFDBNBJDG MMCNOAFFJLB
	public LKDADIMPPHE[] BHGDNGHDDAC { get; set; } // 0x28 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public NHONHLOEGEF[] MHGMDJNOLMI { get; set; } // 0x2C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public AGOFNEFMGJC[] OCCJOGGPJIB { get; set; } // 0x30 IIKNPOKGNAK ONEDKILDMIA BBLLNKENPGB
	public OLMOJDOOIOM[] HHIGONDIHDF { get; set; } // 0x34 CBCKIHPBHOK CBMDIFJNILM GANINPNOFMI
	public AHDABPFAHNL[] JHJNMGPFAKA { get; set; } // 0x38 PDBFFJCLHBF MPAAJJGAJLO DCBCCIOELLL
	public DIFGDAIFPKN[] BOBEIHMGCEC { get; set; } // 0x3C ALHFNEODBHM FLNCPCECKFC ODCMMEGDPMA
	public JAJIKIPGDOK[] DJEBGHFEOKG { get; set; } // 0x40 ALNKPDNAEMB JOJHJDPHGJE AALGFMNKNON
	public HPKKBOBEMMB[] PDIINOHFNGF { get; set; } // 0x44 OAAECLAOBKO MBEFEJHLNBD MLNMIEJCGOO
	public KFKHGNCCMCH[] EODGIMADEGI { get; set; } // 0x48 NNPIHLBNPHL GCLJDCIHJPD DHICKBANHCD
	public MGJDMEPNMOD[] OMLANIGCHDA { get; set; } // 0x4C HKHMIHGIMPM JFMHMEJIJDM AJOKJKHIDFB
	public ELEEMMNLBEM[] GFKENIPCEKK { get; set; } // 0x50 FHBJEMAKHLL EOHCMFHNBML IKGCNPGKFNA
	public ELOPBNCMDBH[] FEMIKAOHGPL { get; set; } // 0x54 KNPDBMFNKOO NKAONKEBADF DIJFHFIKLHF
	public static ANCFFLNKINL HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xD4EB8C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		KCMFPGDPCIG res_readData = KCMFPGDPCIG.GetRootAsKCMFPGDPCIG(buffer);
		ANCFFLNKINL res_data = new ANCFFLNKINL();

		LMAOEFHMHNN HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		BJMFBPEMGCD HMBHNLCFDIH_data = new BJMFBPEMGCD();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.HFNIHKOAMGC = HMBHNLCFDIH_readData.HEMLBADKAOA;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO_SaveIdx = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.BCPHKGGOEKA = HMBHNLCFDIH_readData.JFPEOBHPALH;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO_DayGroup = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE_KeyPrefix = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.MJBKGOJBPAD_item_type = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.FEMMDNIELFC_Desc = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKKNEAGCIEB_RankingSupport = HMBHNLCFDIH_readData.LENBJLOPKLE;
		HMBHNLCFDIH_data.OMCAOJJGOGG_Lb = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM_StartAdventureId = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP_EndAdventureId = HMBHNLCFDIH_readData.JOIACOFCFAA;
		HMBHNLCFDIH_data.OHGDNJLFDFF_Start = HMBHNLCFDIH_readData.JFNKDHPAEGD;
		HMBHNLCFDIH_data.PHKLJGNMFBL_End = HMBHNLCFDIH_readData.KIPKMBIKLDO;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<GHAFLMIOHKM> OPIDLGADBPE_list = new List<GHAFLMIOHKM>();
		for(int OPIDLGADBPE_idx = 0; OPIDLGADBPE_idx < res_readData.POKLHFPANOFLength; OPIDLGADBPE_idx++)
		{
			LNEJLNKGPNE OPIDLGADBPE_readData = res_readData.GetPOKLHFPANOF(OPIDLGADBPE_idx);
			GHAFLMIOHKM OPIDLGADBPE_data = new GHAFLMIOHKM();

			OPIDLGADBPE_data.PPFNGGCBJKC_id = OPIDLGADBPE_readData.BBPHAPFBFHK;
			OPIDLGADBPE_data.IJEKNCDIIAE_mver = OPIDLGADBPE_readData.OFMGALJGDAO;
			OPIDLGADBPE_data.PLALNIIBLOF_en = OPIDLGADBPE_readData.CFLMCGOJJJD;
			OPIDLGADBPE_data.MGLJCOMOGLO_BtnId = OPIDLGADBPE_readData.IAANELFBMJA;
			OPIDLGADBPE_data.PNDEAHGLJIC_BtnType = OPIDLGADBPE_readData.OEHNJJEPMJI;
			OPIDLGADBPE_data.LPDLBACJKIB_TransId = OPIDLGADBPE_readData.MEBNLBGNNPP;
			OPIDLGADBPE_data.PDBPFJJCADD_open_at = OPIDLGADBPE_readData.NJLJEKDBPCH;
			OPIDLGADBPE_data.FDBNFFNFOND_close_at = OPIDLGADBPE_readData.MAOAGDBDBIB;
			OPIDLGADBPE_data.GNOFNIOLPPC_ImgId = OPIDLGADBPE_readData.BBINGFKGFPB;
			OPIDLGADBPE_data.BOJCOPAALNC_EventId = OPIDLGADBPE_readData.JBCDDOFEDEP;
			OPIDLGADBPE_list.Add(OPIDLGADBPE_data);
		}
		res_data.OPIDLGADBPE = OPIDLGADBPE_list.ToArray();

		List<OMLNDNBOGBM> MDDOGIAFDEI_list = new List<OMLNDNBOGBM>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			NFMLBJAPPIO MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			OMLNDNBOGBM MDDOGIAFDEI_data = new OMLNDNBOGBM();

			MDDOGIAFDEI_data.PPFNGGCBJKC_id = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF_en = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM_typ = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.KGICDMIJGDF_Group = MDDOGIAFDEI_readData.PEGBGEGKCGA;
			MDDOGIAFDEI_data.FPOMEEJFBIG_odr = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC_Desc = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE_DescBalloon = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN_ItemId = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC_item_count = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ_Link = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO_st = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM_end = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<KGBNJLAIFFN> AFMPLCMMPHO_list = new List<KGBNJLAIFFN>();
		for(int AFMPLCMMPHO_idx = 0; AFMPLCMMPHO_idx < res_readData.NHANJELFBGJLength; AFMPLCMMPHO_idx++)
		{
			NCIJKPJKNNJ AFMPLCMMPHO_readData = res_readData.GetNHANJELFBGJ(AFMPLCMMPHO_idx);
			KGBNJLAIFFN AFMPLCMMPHO_data = new KGBNJLAIFFN();

			AFMPLCMMPHO_data.PPFNGGCBJKC_id = AFMPLCMMPHO_readData.BBPHAPFBFHK;
			AFMPLCMMPHO_data.PLALNIIBLOF_en = AFMPLCMMPHO_readData.CFLMCGOJJJD;
			AFMPLCMMPHO_data.BDEOMEBFDFF_gacha_id = AFMPLCMMPHO_readData.HHFEPINGMEI;
			AFMPLCMMPHO_data.PDBPFJJCADD_open_at = AFMPLCMMPHO_readData.NJLJEKDBPCH;
			AFMPLCMMPHO_data.FDBNFFNFOND_close_at = AFMPLCMMPHO_readData.MAOAGDBDBIB;
			AFMPLCMMPHO_list.Add(AFMPLCMMPHO_data);
		}
		res_data.AFMPLCMMPHO = AFMPLCMMPHO_list.ToArray();

		List<PDKLCAEOOLD> IEMKMPDAJCM_list = new List<PDKLCAEOOLD>();
		for(int IEMKMPDAJCM_idx = 0; IEMKMPDAJCM_idx < res_readData.NEBBOBFGPPCLength; IEMKMPDAJCM_idx++)
		{
			JBCLJHNMAEL IEMKMPDAJCM_readData = res_readData.GetNEBBOBFGPPC(IEMKMPDAJCM_idx);
			PDKLCAEOOLD IEMKMPDAJCM_data = new PDKLCAEOOLD();

			IEMKMPDAJCM_data.PPFNGGCBJKC_id = IEMKMPDAJCM_readData.BBPHAPFBFHK;
			IEMKMPDAJCM_data.PLALNIIBLOF_en = IEMKMPDAJCM_readData.CFLMCGOJJJD;
			IEMKMPDAJCM_data.BDEOMEBFDFF_gacha_id = IEMKMPDAJCM_readData.HHFEPINGMEI;
			IEMKMPDAJCM_data.PDBPFJJCADD_open_at = IEMKMPDAJCM_readData.NJLJEKDBPCH;
			IEMKMPDAJCM_data.FDBNFFNFOND_close_at = IEMKMPDAJCM_readData.MAOAGDBDBIB;
			IEMKMPDAJCM_list.Add(IEMKMPDAJCM_data);
		}
		res_data.IEMKMPDAJCM = IEMKMPDAJCM_list.ToArray();

		List<JJBOBCDGNOP> MHCBBBFJALG_list = new List<JJBOBCDGNOP>();
		for(int MHCBBBFJALG_idx = 0; MHCBBBFJALG_idx < res_readData.AFJJPJKCDCMLength; MHCBBBFJALG_idx++)
		{
			HCIHHMAFHBD MHCBBBFJALG_readData = res_readData.GetAFJJPJKCDCM(MHCBBBFJALG_idx);
			JJBOBCDGNOP MHCBBBFJALG_data = new JJBOBCDGNOP();

			MHCBBBFJALG_data.PPFNGGCBJKC_id = MHCBBBFJALG_readData.BBPHAPFBFHK;
			MHCBBBFJALG_data.PLALNIIBLOF_en = MHCBBBFJALG_readData.CFLMCGOJJJD;
			MHCBBBFJALG_data.DNJLJMKKDNA_EventId = MHCBBBFJALG_readData.IDHMHHMGAHM;
			MHCBBBFJALG_data.PDBPFJJCADD_open_at = MHCBBBFJALG_readData.NJLJEKDBPCH;
			MHCBBBFJALG_data.FDBNFFNFOND_close_at = MHCBBBFJALG_readData.MAOAGDBDBIB;
			MHCBBBFJALG_list.Add(MHCBBBFJALG_data);
		}
		res_data.MHCBBBFJALG = MHCBBBFJALG_list.ToArray();

		List<LADKNAIOJBK> KKENLPIJOBN_list = new List<LADKNAIOJBK>();
		for(int KKENLPIJOBN_idx = 0; KKENLPIJOBN_idx < res_readData.MPLCLCLBJPALength; KKENLPIJOBN_idx++)
		{
			MIICCHHAGJF KKENLPIJOBN_readData = res_readData.GetMPLCLCLBJPA(KKENLPIJOBN_idx);
			LADKNAIOJBK KKENLPIJOBN_data = new LADKNAIOJBK();

			KKENLPIJOBN_data.PPFNGGCBJKC_id = KKENLPIJOBN_readData.BBPHAPFBFHK;
			KKENLPIJOBN_data.PLALNIIBLOF_en = KKENLPIJOBN_readData.CFLMCGOJJJD;
			KKENLPIJOBN_data.OENPCNBFPDA_bg_id = KKENLPIJOBN_readData.MOMCBJDJDIA;
			KKENLPIJOBN_data.KGICDMIJGDF_Group = KKENLPIJOBN_readData.PEGBGEGKCGA;
			KKENLPIJOBN_data.PDBPFJJCADD_open_at = KKENLPIJOBN_readData.NJLJEKDBPCH;
			KKENLPIJOBN_data.FDBNFFNFOND_close_at = KKENLPIJOBN_readData.MAOAGDBDBIB;
			KKENLPIJOBN_list.Add(KKENLPIJOBN_data);
		}
		res_data.KKENLPIJOBN = KKENLPIJOBN_list.ToArray();

		List<PPAOPCHAFDP> BPFJNIGNLEJ_list = new List<PPAOPCHAFDP>();
		for(int BPFJNIGNLEJ_idx = 0; BPFJNIGNLEJ_idx < res_readData.DDLMFMGDBILLength; BPFJNIGNLEJ_idx++)
		{
			ECDHHNAFLCJ BPFJNIGNLEJ_readData = res_readData.GetDDLMFMGDBIL(BPFJNIGNLEJ_idx);
			PPAOPCHAFDP BPFJNIGNLEJ_data = new PPAOPCHAFDP();

			BPFJNIGNLEJ_data.PPFNGGCBJKC_id = BPFJNIGNLEJ_readData.BBPHAPFBFHK;
			BPFJNIGNLEJ_data.PLALNIIBLOF_en = BPFJNIGNLEJ_readData.CFLMCGOJJJD;
			List<uint> ALMEBFDEGBG_list = new List<uint>();
			for(int ALMEBFDEGBG_idx = 0; ALMEBFDEGBG_idx < BPFJNIGNLEJ_readData.NNCHHHGHAKJLength; ALMEBFDEGBG_idx++)
			{
				ALMEBFDEGBG_list.Add(BPFJNIGNLEJ_readData.GetNNCHHHGHAKJ(ALMEBFDEGBG_idx));
			}
			BPFJNIGNLEJ_data.ALMEBFDEGBG = ALMEBFDEGBG_list.ToArray();

			BPFJNIGNLEJ_data.PDBPFJJCADD_open_at = BPFJNIGNLEJ_readData.NJLJEKDBPCH;
			BPFJNIGNLEJ_data.FDBNFFNFOND_close_at = BPFJNIGNLEJ_readData.MAOAGDBDBIB;
			BPFJNIGNLEJ_list.Add(BPFJNIGNLEJ_data);
		}
		res_data.BPFJNIGNLEJ = BPFJNIGNLEJ_list.ToArray();

		List<LKDADIMPPHE> BHGDNGHDDAC_list = new List<LKDADIMPPHE>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			DNHBOHGLGHF BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			LKDADIMPPHE BHGDNGHDDAC_data = new LKDADIMPPHE();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<NHONHLOEGEF> MHGMDJNOLMI_list = new List<NHONHLOEGEF>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			EFEDOIIDFEC MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			NHONHLOEGEF MHGMDJNOLMI_data = new NHONHLOEGEF();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<AGOFNEFMGJC> OCCJOGGPJIB_list = new List<AGOFNEFMGJC>();
		for(int OCCJOGGPJIB_idx = 0; OCCJOGGPJIB_idx < res_readData.FHLMJLCFFFKLength; OCCJOGGPJIB_idx++)
		{
			GHKANHJNIJD OCCJOGGPJIB_readData = res_readData.GetFHLMJLCFFFK(OCCJOGGPJIB_idx);
			AGOFNEFMGJC OCCJOGGPJIB_data = new AGOFNEFMGJC();

			OCCJOGGPJIB_data.PPFNGGCBJKC_id = OCCJOGGPJIB_readData.BBPHAPFBFHK;
			OCCJOGGPJIB_data.PLALNIIBLOF_en = OCCJOGGPJIB_readData.CFLMCGOJJJD;
			OCCJOGGPJIB_data.BDEOMEBFDFF_gacha_id = OCCJOGGPJIB_readData.HHFEPINGMEI;
			OCCJOGGPJIB_data.PDBPFJJCADD_open_at = OCCJOGGPJIB_readData.NJLJEKDBPCH;
			OCCJOGGPJIB_data.FDBNFFNFOND_close_at = OCCJOGGPJIB_readData.MAOAGDBDBIB;
			OCCJOGGPJIB_list.Add(OCCJOGGPJIB_data);
		}
		res_data.OCCJOGGPJIB = OCCJOGGPJIB_list.ToArray();

		List<OLMOJDOOIOM> HHIGONDIHDF_list = new List<OLMOJDOOIOM>();
		for(int HHIGONDIHDF_idx = 0; HHIGONDIHDF_idx < res_readData.CJCGFACIGEGLength; HHIGONDIHDF_idx++)
		{
			LFNFJEBKHGL HHIGONDIHDF_readData = res_readData.GetCJCGFACIGEG(HHIGONDIHDF_idx);
			OLMOJDOOIOM HHIGONDIHDF_data = new OLMOJDOOIOM();

			HHIGONDIHDF_data.PPFNGGCBJKC_id = HHIGONDIHDF_readData.BBPHAPFBFHK;
			HHIGONDIHDF_data.PLALNIIBLOF_en = HHIGONDIHDF_readData.CFLMCGOJJJD;
			HHIGONDIHDF_data.KDGJBBFKLGI_Chapter = HHIGONDIHDF_readData.JBHNPKHLOBI;
			HHIGONDIHDF_data.OIAAFFHGBBD_AdvId = HHIGONDIHDF_readData.CEPBOFBJBKB;
			HHIGONDIHDF_data.PDBPFJJCADD_open_at = HHIGONDIHDF_readData.NJLJEKDBPCH;
			HHIGONDIHDF_list.Add(HHIGONDIHDF_data);
		}
		res_data.HHIGONDIHDF = HHIGONDIHDF_list.ToArray();

		List<AHDABPFAHNL> JHJNMGPFAKA_list = new List<AHDABPFAHNL>();
		for(int JHJNMGPFAKA_idx = 0; JHJNMGPFAKA_idx < res_readData.NCLHKEHIJJCLength; JHJNMGPFAKA_idx++)
		{
			MOFHLFIPPNP JHJNMGPFAKA_readData = res_readData.GetNCLHKEHIJJC(JHJNMGPFAKA_idx);
			AHDABPFAHNL JHJNMGPFAKA_data = new AHDABPFAHNL();

			JHJNMGPFAKA_data.PPFNGGCBJKC_id = JHJNMGPFAKA_readData.BBPHAPFBFHK;
			JHJNMGPFAKA_data.PLALNIIBLOF_en = JHJNMGPFAKA_readData.CFLMCGOJJJD;
			JHJNMGPFAKA_data.PDBPFJJCADD_open_at = JHJNMGPFAKA_readData.NJLJEKDBPCH;
			JHJNMGPFAKA_data.FDBNFFNFOND_close_at = JHJNMGPFAKA_readData.MAOAGDBDBIB;
			JHJNMGPFAKA_data.EJBGHLOOLBC_HelpIds = JHJNMGPFAKA_readData.FIABJKGEJFF;
			JHJNMGPFAKA_list.Add(JHJNMGPFAKA_data);
		}
		res_data.JHJNMGPFAKA = JHJNMGPFAKA_list.ToArray();

		List<DIFGDAIFPKN> BOBEIHMGCEC_list = new List<DIFGDAIFPKN>();
		for(int BOBEIHMGCEC_idx = 0; BOBEIHMGCEC_idx < res_readData.HLCDDAGIMLELength; BOBEIHMGCEC_idx++)
		{
			LHNCOEINPJB BOBEIHMGCEC_readData = res_readData.GetHLCDDAGIMLE(BOBEIHMGCEC_idx);
			DIFGDAIFPKN BOBEIHMGCEC_data = new DIFGDAIFPKN();

			BOBEIHMGCEC_data.PPFNGGCBJKC_id = BOBEIHMGCEC_readData.BBPHAPFBFHK;
			BOBEIHMGCEC_data.PLALNIIBLOF_en = BOBEIHMGCEC_readData.CFLMCGOJJJD;
			List<uint> OPKCNBFBBKP_list = new List<uint>();
			for(int OPKCNBFBBKP_idx = 0; OPKCNBFBBKP_idx < BOBEIHMGCEC_readData.GPELFPEHLMDLength; OPKCNBFBBKP_idx++)
			{
				OPKCNBFBBKP_list.Add(BOBEIHMGCEC_readData.GetGPELFPEHLMD(OPKCNBFBBKP_idx));
			}
			BOBEIHMGCEC_data.OPKCNBFBBKP_BannerId = OPKCNBFBBKP_list.ToArray();

			List<uint> BEBJKJKBOGH_list = new List<uint>();
			for(int BEBJKJKBOGH_idx = 0; BEBJKJKBOGH_idx < BOBEIHMGCEC_readData.EODLLIMCLLHLength; BEBJKJKBOGH_idx++)
			{
				BEBJKJKBOGH_list.Add(BOBEIHMGCEC_readData.GetEODLLIMCLLH(BEBJKJKBOGH_idx));
			}
			BOBEIHMGCEC_data.BEBJKJKBOGH_date = BEBJKJKBOGH_list.ToArray();

			BOBEIHMGCEC_data.PDBPFJJCADD_open_at = BOBEIHMGCEC_readData.NJLJEKDBPCH;
			BOBEIHMGCEC_data.FDBNFFNFOND_close_at = BOBEIHMGCEC_readData.MAOAGDBDBIB;
			BOBEIHMGCEC_list.Add(BOBEIHMGCEC_data);
		}
		res_data.BOBEIHMGCEC = BOBEIHMGCEC_list.ToArray();

		List<JAJIKIPGDOK> DJEBGHFEOKG_list = new List<JAJIKIPGDOK>();
		for(int DJEBGHFEOKG_idx = 0; DJEBGHFEOKG_idx < res_readData.NNIGHPIKHNJLength; DJEBGHFEOKG_idx++)
		{
			MKOEIFFJPKH DJEBGHFEOKG_readData = res_readData.GetNNIGHPIKHNJ(DJEBGHFEOKG_idx);
			JAJIKIPGDOK DJEBGHFEOKG_data = new JAJIKIPGDOK();

			DJEBGHFEOKG_data.PPFNGGCBJKC_id = DJEBGHFEOKG_readData.BBPHAPFBFHK;
			DJEBGHFEOKG_data.PLALNIIBLOF_en = DJEBGHFEOKG_readData.CFLMCGOJJJD;
			DJEBGHFEOKG_data.OPKCNBFBBKP_BannerId = DJEBGHFEOKG_readData.JOGGPOAOLOI;
			DJEBGHFEOKG_data.PDBPFJJCADD_open_at = DJEBGHFEOKG_readData.NJLJEKDBPCH;
			DJEBGHFEOKG_data.FDBNFFNFOND_close_at = DJEBGHFEOKG_readData.MAOAGDBDBIB;
			DJEBGHFEOKG_list.Add(DJEBGHFEOKG_data);
		}
		res_data.DJEBGHFEOKG = DJEBGHFEOKG_list.ToArray();

		List<HPKKBOBEMMB> PDIINOHFNGF_list = new List<HPKKBOBEMMB>();
		for(int PDIINOHFNGF_idx = 0; PDIINOHFNGF_idx < res_readData.IEGBGJGGNJILength; PDIINOHFNGF_idx++)
		{
			PKBJAHIOPOM PDIINOHFNGF_readData = res_readData.GetIEGBGJGGNJI(PDIINOHFNGF_idx);
			HPKKBOBEMMB PDIINOHFNGF_data = new HPKKBOBEMMB();

			PDIINOHFNGF_data.PPFNGGCBJKC_id = PDIINOHFNGF_readData.BBPHAPFBFHK;
			PDIINOHFNGF_data.PLALNIIBLOF_en = PDIINOHFNGF_readData.CFLMCGOJJJD;
			PDIINOHFNGF_data.DNJLJMKKDNA_EventId = PDIINOHFNGF_readData.IDHMHHMGAHM;
			PDIINOHFNGF_data.PDBPFJJCADD_open_at = PDIINOHFNGF_readData.NJLJEKDBPCH;
			PDIINOHFNGF_data.FDBNFFNFOND_close_at = PDIINOHFNGF_readData.MAOAGDBDBIB;
			PDIINOHFNGF_list.Add(PDIINOHFNGF_data);
		}
		res_data.PDIINOHFNGF = PDIINOHFNGF_list.ToArray();

		List<KFKHGNCCMCH> EODGIMADEGI_list = new List<KFKHGNCCMCH>();
		for(int EODGIMADEGI_idx = 0; EODGIMADEGI_idx < res_readData.KMDPJKDLAAHLength; EODGIMADEGI_idx++)
		{
			GIGLCNHCNEN EODGIMADEGI_readData = res_readData.GetKMDPJKDLAAH(EODGIMADEGI_idx);
			KFKHGNCCMCH EODGIMADEGI_data = new KFKHGNCCMCH();

			EODGIMADEGI_data.PPFNGGCBJKC_id = EODGIMADEGI_readData.BBPHAPFBFHK;
			EODGIMADEGI_data.PLALNIIBLOF_en = EODGIMADEGI_readData.CFLMCGOJJJD;
			EODGIMADEGI_data.DNJLJMKKDNA_EventId = EODGIMADEGI_readData.IDHMHHMGAHM;
			EODGIMADEGI_data.PDBPFJJCADD_open_at = EODGIMADEGI_readData.NJLJEKDBPCH;
			EODGIMADEGI_data.FDBNFFNFOND_close_at = EODGIMADEGI_readData.MAOAGDBDBIB;
			EODGIMADEGI_list.Add(EODGIMADEGI_data);
		}
		res_data.EODGIMADEGI = EODGIMADEGI_list.ToArray();

		List<MGJDMEPNMOD> OMLANIGCHDA_list = new List<MGJDMEPNMOD>();
		for(int OMLANIGCHDA_idx = 0; OMLANIGCHDA_idx < res_readData.PKKCHMEBNOKLength; OMLANIGCHDA_idx++)
		{
			ILCAGMDDGIO OMLANIGCHDA_readData = res_readData.GetPKKCHMEBNOK(OMLANIGCHDA_idx);
			MGJDMEPNMOD OMLANIGCHDA_data = new MGJDMEPNMOD();

			OMLANIGCHDA_data.PPFNGGCBJKC_id = OMLANIGCHDA_readData.BBPHAPFBFHK;
			OMLANIGCHDA_data.PLALNIIBLOF_en = OMLANIGCHDA_readData.CFLMCGOJJJD;
			OMLANIGCHDA_data.BDEOMEBFDFF_gacha_id = OMLANIGCHDA_readData.HHFEPINGMEI;
			OMLANIGCHDA_data.PDBPFJJCADD_open_at = OMLANIGCHDA_readData.NJLJEKDBPCH;
			OMLANIGCHDA_data.FDBNFFNFOND_close_at = OMLANIGCHDA_readData.MAOAGDBDBIB;
			OMLANIGCHDA_list.Add(OMLANIGCHDA_data);
		}
		res_data.OMLANIGCHDA = OMLANIGCHDA_list.ToArray();

		List<ELEEMMNLBEM> GFKENIPCEKK_list = new List<ELEEMMNLBEM>();
		for(int GFKENIPCEKK_idx = 0; GFKENIPCEKK_idx < res_readData.KCOMOLJANNELength; GFKENIPCEKK_idx++)
		{
			ELJJEFEIEIK GFKENIPCEKK_readData = res_readData.GetKCOMOLJANNE(GFKENIPCEKK_idx);
			ELEEMMNLBEM GFKENIPCEKK_data = new ELEEMMNLBEM();

			GFKENIPCEKK_data.PPFNGGCBJKC_id = GFKENIPCEKK_readData.BBPHAPFBFHK;
			GFKENIPCEKK_data.PLALNIIBLOF_en = GFKENIPCEKK_readData.CFLMCGOJJJD;
			GFKENIPCEKK_data.PDBPFJJCADD_open_at = GFKENIPCEKK_readData.NJLJEKDBPCH;
			GFKENIPCEKK_data.FDBNFFNFOND_close_at = GFKENIPCEKK_readData.MAOAGDBDBIB;
			GFKENIPCEKK_list.Add(GFKENIPCEKK_data);
		}
		res_data.GFKENIPCEKK = GFKENIPCEKK_list.ToArray();

		List<ELOPBNCMDBH> FEMIKAOHGPL_list = new List<ELOPBNCMDBH>();
		for(int FEMIKAOHGPL_idx = 0; FEMIKAOHGPL_idx < res_readData.PEJBPICDONNLength; FEMIKAOHGPL_idx++)
		{
			PGFKEJKOOJD FEMIKAOHGPL_readData = res_readData.GetPEJBPICDONN(FEMIKAOHGPL_idx);
			ELOPBNCMDBH FEMIKAOHGPL_data = new ELOPBNCMDBH();

			FEMIKAOHGPL_data.PPFNGGCBJKC_id = FEMIKAOHGPL_readData.BBPHAPFBFHK;
			FEMIKAOHGPL_data.PLALNIIBLOF_en = FEMIKAOHGPL_readData.CFLMCGOJJJD;
			FEMIKAOHGPL_data.PDBPFJJCADD_open_at = FEMIKAOHGPL_readData.NJLJEKDBPCH;
			FEMIKAOHGPL_data.FDBNFFNFOND_close_at = FEMIKAOHGPL_readData.MAOAGDBDBIB;
			FEMIKAOHGPL_list.Add(FEMIKAOHGPL_data);
		}
		res_data.FEMIKAOHGPL = FEMIKAOHGPL_list.ToArray();

		return res_data;
	}
}
