using FlatBuffers;
using System.Collections.Generic;

public class EIIBKGHEGFI
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FBFLDFMFFOH_rar { get; set; } // 0xC LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint JBGEEPFKIGG_val { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
}
public class BELBAJBINBO
{
	public EIIBKGHEGFI[] GMDKFCMGHIK { get; set; } // 0x8 POMGFCIPGKL EMAGPNNLPGJ FJEPAPLAIDL
	public static BELBAJBINBO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xC75CF8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		AIAGNLHOHPF res_readData = AIAGNLHOHPF.GetRootAsAIAGNLHOHPF(buffer);
		BELBAJBINBO res_data = new BELBAJBINBO();

		List<EIIBKGHEGFI> GMDKFCMGHIK_list = new List<EIIBKGHEGFI>();
		for(int GMDKFCMGHIK_idx = 0; GMDKFCMGHIK_idx < res_readData.KDNNKLCMJCELength; GMDKFCMGHIK_idx++)
		{
			MKPHLDNDLDL GMDKFCMGHIK_readData = res_readData.GetKDNNKLCMJCE(GMDKFCMGHIK_idx);
			EIIBKGHEGFI GMDKFCMGHIK_data = new EIIBKGHEGFI();

			GMDKFCMGHIK_data.PPFNGGCBJKC_id = GMDKFCMGHIK_readData.BBPHAPFBFHK;
			GMDKFCMGHIK_data.FBFLDFMFFOH_rar = GMDKFCMGHIK_readData.ODBPKGJPLMD;
			GMDKFCMGHIK_data.JBGEEPFKIGG_val = GMDKFCMGHIK_readData.KJFEBMBHKOC;
			GMDKFCMGHIK_data.GBJFNGCDKPM_typ = GMDKFCMGHIK_readData.LPJPOOHJKAE;
			GMDKFCMGHIK_list.Add(GMDKFCMGHIK_data);
		}
		res_data.GMDKFCMGHIK = GMDKFCMGHIK_list.ToArray();

		return res_data;
	}
}
