using FlatBuffers;
using System.Collections.Generic;

public class MMBIHLNLPHB
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND_close_at { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public int KNHOMNONOEB_AssetId { get; set; } // 0x1C EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
}
public class BENBFNLECGA
{
	public MMBIHLNLPHB[] KFKOALPLEGG { get; set; } // 0x8 FCMLCPIOBEN OEPJFJBDFIG BBGIPEJCKNE
	public static BENBFNLECGA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xC75FDC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		CJMBCLHMFBF res_readData = CJMBCLHMFBF.GetRootAsCJMBCLHMFBF(buffer);
		BENBFNLECGA res_data = new BENBFNLECGA();

		List<MMBIHLNLPHB> KFKOALPLEGG_list = new List<MMBIHLNLPHB>();
		for(int KFKOALPLEGG_idx = 0; KFKOALPLEGG_idx < res_readData.BBPMPGIIHOLLength; KFKOALPLEGG_idx++)
		{
			GFNMEMLEAFB KFKOALPLEGG_readData = res_readData.GetBBPMPGIIHOL(KFKOALPLEGG_idx);
			MMBIHLNLPHB KFKOALPLEGG_data = new MMBIHLNLPHB();

			KFKOALPLEGG_data.PPFNGGCBJKC_id = KFKOALPLEGG_readData.BBPHAPFBFHK;
			KFKOALPLEGG_data.IJEKNCDIIAE_mver = KFKOALPLEGG_readData.OFMGALJGDAO;
			KFKOALPLEGG_data.PLALNIIBLOF_en = KFKOALPLEGG_readData.CFLMCGOJJJD;
			KFKOALPLEGG_data.PDBPFJJCADD_open_at = KFKOALPLEGG_readData.NJLJEKDBPCH;
			KFKOALPLEGG_data.FDBNFFNFOND_close_at = KFKOALPLEGG_readData.MAOAGDBDBIB;
			KFKOALPLEGG_data.KNHOMNONOEB_AssetId = KFKOALPLEGG_readData.NCADHENBLDB;
			KFKOALPLEGG_list.Add(KFKOALPLEGG_data);
		}
		res_data.KFKOALPLEGG = KFKOALPLEGG_list.ToArray();

		return res_data;
	}
}
