using FlatBuffers;
using System.Collections.Generic;

public class BCCFAPDAFOE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int BCKCEEMNKCH { get; set; } // 0x14 HNOKIOCJCGC KMKCBONBHCN MMKFAENKJPK
	public int BDJMFDKLHPM { get; set; } // 0x18 EOBCNECIOMH GFMBGPMJPLJ ENAMMCHJBDE
	public int PDBPFJJCADD { get; set; } // 0x1C PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x20 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class MCCFOKHKJIC
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int BCKCEEMNKCH { get; set; } // 0x10 HNOKIOCJCGC KMKCBONBHCN MMKFAENKJPK
	public int PIDAAPMCAML { get; set; } // 0x14 FBMFEMGAJPD BHFHPNBGGBA ILHFKGPINNI
	public int OIAAFFHGBBD { get; set; } // 0x18 JOJKCBIKOIO ENLDJCEIHCK GOMCJDMDDBG
	public int ODNOJKHHEOP { get; set; } // 0x1C HHGINHPEICA NINNDNIDNGJ DEKDOBENELE
	public int DFMOIKJOCGH { get; set; } // 0x20 MFFLHOELPCE NFBPOLHEJIA DPCFHPDOKDN
}
public class BLOHGJIKLAK
{
	public BCCFAPDAFOE[] MLJNCEIFECL { get; set; } // 0x8 HCKJIAKFGCH GOEBFAEFFMB CHCLIHFFFPK
	public MCCFOKHKJIC[] FGAOKKECNIH { get; set; } // 0xC CALGMBGPKOL JBLDLHMDFCI EKEBNPNMBAE
	public static BLOHGJIKLAK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x19C2300
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		HKILNANKLLB res_readData = HKILNANKLLB.GetRootAsHKILNANKLLB(buffer);
		BLOHGJIKLAK res_data = new BLOHGJIKLAK();

		List<BCCFAPDAFOE> MLJNCEIFECL_list = new List<BCCFAPDAFOE>();
		for(int MLJNCEIFECL_idx = 0; MLJNCEIFECL_idx < res_readData.JCEDIBCEFOJLength; MLJNCEIFECL_idx++)
		{
			JJEDGMMFLNA MLJNCEIFECL_readData = res_readData.GetJCEDIBCEFOJ(MLJNCEIFECL_idx);
			BCCFAPDAFOE MLJNCEIFECL_data = new BCCFAPDAFOE();

			MLJNCEIFECL_data.PPFNGGCBJKC = MLJNCEIFECL_readData.BBPHAPFBFHK;
			MLJNCEIFECL_data.IJEKNCDIIAE = MLJNCEIFECL_readData.OFMGALJGDAO;
			MLJNCEIFECL_data.PLALNIIBLOF = MLJNCEIFECL_readData.CFLMCGOJJJD;
			MLJNCEIFECL_data.BCKCEEMNKCH = MLJNCEIFECL_readData.GKNBEHEMMFH;
			MLJNCEIFECL_data.BDJMFDKLHPM = MLJNCEIFECL_readData.MJOCIHPPKNO;
			MLJNCEIFECL_data.PDBPFJJCADD = MLJNCEIFECL_readData.NJLJEKDBPCH;
			MLJNCEIFECL_data.FDBNFFNFOND = MLJNCEIFECL_readData.MAOAGDBDBIB;
			MLJNCEIFECL_list.Add(MLJNCEIFECL_data);
		}
		res_data.MLJNCEIFECL = MLJNCEIFECL_list.ToArray();

		List<MCCFOKHKJIC> FGAOKKECNIH_list = new List<MCCFOKHKJIC>();
		for(int FGAOKKECNIH_idx = 0; FGAOKKECNIH_idx < res_readData.GFOJACKHEDCLength; FGAOKKECNIH_idx++)
		{
			CBMILEEGEPN FGAOKKECNIH_readData = res_readData.GetGFOJACKHEDC(FGAOKKECNIH_idx);
			MCCFOKHKJIC FGAOKKECNIH_data = new MCCFOKHKJIC();

			FGAOKKECNIH_data.PPFNGGCBJKC = FGAOKKECNIH_readData.BBPHAPFBFHK;
			FGAOKKECNIH_data.PLALNIIBLOF = FGAOKKECNIH_readData.CFLMCGOJJJD;
			FGAOKKECNIH_data.BCKCEEMNKCH = FGAOKKECNIH_readData.GKNBEHEMMFH;
			FGAOKKECNIH_data.PIDAAPMCAML = FGAOKKECNIH_readData.DNMMADEPEKH;
			FGAOKKECNIH_data.OIAAFFHGBBD = FGAOKKECNIH_readData.CEPBOFBJBKB;
			FGAOKKECNIH_data.ODNOJKHHEOP = FGAOKKECNIH_readData.IHPEJOJEPFM;
			FGAOKKECNIH_data.DFMOIKJOCGH = FGAOKKECNIH_readData.BBDGLCFCBFL;
			FGAOKKECNIH_list.Add(FGAOKKECNIH_data);
		}
		res_data.FGAOKKECNIH = FGAOKKECNIH_list.ToArray();

		return res_data;
	}
}
