using FlatBuffers;
using System.Collections.Generic;

public class NLDAADHODFI
{
	public uint CBBLAMDGOGK { get; set; } // COLDIHOBOAC 0x8 // MLAOHCFONJD GDFGAJNCLHC
	public uint DMEDKJPOLCH { get; set; } // JAEJJPMKMFI 0xC // IPKCKAAEEOE JOGLLINFLJN
	public uint LHKFKIKEJHN { get; set; } // JCODGBOLCIG 0x10 // JDEBEHKLHMM PAEOHIHJFCD
	public uint PLALNIIBLOF { get; set; } // DFMNDOMAPAB 0x14 // JPCJNLHHIPE JJFJNEJLBDG
	public uint EHDDADDKMFI { get; set; } // MCAKELLLNIO 0x18 // IFFJALDBDDI LMLHCMMIEJH
	public uint KLMIFEKNBLL { get; set; } // DGEFHELLNBP 0x1C // KLMLEPCKEHM NDNHEJFBNMC
	public uint FPOMEEJFBIG { get; set; } // PJKJIFMIFDJ 0x20 // OEEBAHNAPEC BEHAPLPPLNE
	public uint GPNOEFHGOJG { get; set; } // JHDENCIJCJC 0x24 // IMEDMCEEIMG ODOJGKNGNOP
	public uint PAIIHEJIGKO { get; set; } // LMEFJFFNMAN 0x28 // DABGLMPIDNI LOKOIJFDBDE
	public uint FCEJJEPFIPH { get; set; } // ACOJMMLFGOK 0x2C // LLLKCLJBPBL IBLEKPDKFDO
	public uint[] CFJKNAIOEAN { get; set; } // MPLOLLPCDIF 0x30 // PMBGOFMCPOM GALKNDCFHAK
	public uint[] BKEIOLFMMDH { get; set; } // CICHIFAEKHN 0x34 // JFEIGJLJJFM IAFNMHDEKEI
	public uint[] JGEIIONMJMI { get; set; } // MNBHJKIFPEI 0x38 // MJBNOHDIKBO JKJEOAHFDHA
	public uint[] CMENIBCJJNF { get; set; } // EAKLICNNONC 0x3C // MGNDABKMNLI PBAGALKJMLO
	public uint[] KMFHHOANPFH { get; set; } // FFDDMKIEILO 0x40 // BBIIBILMAIH EPKDJPIJDGF
	public uint[] EHODALENBEL { get; set; } // LFAOBBPOMKC 0x44 // IGMCHGEJIGP ELJJOANFNFJ
	public uint[] ALJIHHGHCOG { get; set; } // JBFFCGCNKKE 0x48 // JFIPBBGMNAJ IAOOONFGPED
	public uint NOHIMPJDOCK { get; set; } // GDEMMPHGLNC 0x4C // JJKDJDMENIO CNKEEPBJPBN
	public uint DFELEPDHLBF { get; set; } // GHBCOIBALLM 0x50 // IMHLDJFEBND PFKJHBKNHPE
	public uint CAJKBDLCGOD { get; set; } // PNMIDABPDKK 0x54 // DJOIJBBPJOL HDNHPFBIJBP
	public uint LHBNIAJDIGA { get; set; } // PCALIGAIMLB 0x58 // LOJCANBIELM MKEFHPLGHEI
	public int IJEKNCDIIAE { get; set; } // FAHNCMHNFCG 0x5C // KJIMMIBDCIL DMEGNOKIKCD
	public int JJMMJGANPFI { get; set; } // PJPPPIKIGBH 0x60 // NIHBJIJABNO FMLMAJKPEJK
	public int EIIOPABMJFJ { get; set; } // KIBBKMCPCCL 0x64 // CALLFCFIGGJ HHMJLJHOHFP
	public int HHGPOOBOKHP { get; set; } // NIAPLBDGELO 0x68 // ADIKJFICDNP JIHMDHIGOII
	public uint ECLGEFGJMAM { get; set; } // FKHJPKIJHFL 0x6C // ALEAEBNKAOJ PCHFEEIILPI
	public uint FABJJODPCIN { get; set; } // EJABAOCGIJE 0x70 // IALCNHENHEN KENFNCBHIII
	public uint CCHNGBLALEB { get; set; } // KBLAIPCFMNM 0x74 // NOLJHJBFDFN PELLKHGCMFM
	public uint[] BODBNFFIOJN { get; set; } // PKEPEMCBBFC 0x78 // AHODMNFNNDP NMICEEHBJEJ
	public uint[] KJLLNPFHEEL { get; set; } // PFINKCLGEMD 0x7C // MKMKGNMEDKJ DELNNOEEOJN
	public uint[] DOAFFAGEHOM { get; set; } // LMPKMEIDHNI 0x80 // HLPNBMOBLFL OGPCILCNKIJ
	public uint[] BIHJCIGKMBA { get; set; } // HJPKHOJAMFK 0x84 // IPBKPFHLAHF AKCPANPLNIH
	public uint[] OOBOCLOFPBF { get; set; } // MNMGMMGPFAJ 0x88 // NMCKJLAOHMJ AOHJEOOEPJJ
	public uint[] DKAIOCGKJLO { get; set; } // HAMFIBJCJBN 0x8C // NOFFGJPIAPK DJLOMOAPAIA
	public uint[] OIDAMEGDNOF { get; set; } // DLDAOGHLJDI 0x90 // ECMGMKMGHKM IMCEKAJFMPP
	public int OHDNJMJCGCJ { get; set; } // LIHNNEEFPGB 0x94 // FCMNDCLBMEJ PMEGPDCEHLG
	public uint PNIFJEENINF { get; set; } // MCIDBILLLEA 0x98 // FNFJBBMHOMN MHJCFGMFNAH
}
public class KEBPMGGPLIF
{
	public uint[] AIHOJKFNEEN { get; set; } // GGBFCEFNCFM 0x8 // BGFIPHMMOGA DHAIHODDOGM
	public uint FCEJJEPFIPH { get; set; } // ACOJMMLFGOK 0xC // LLLKCLJBPBL IBLEKPDKFDO
}
public class JPALGGIPGGN
{
	public uint JPHOOKPHBLD { get; set; } // ANIFMEEIAKJ 0x8 // CEPDDPGCMDH HAEEKJJEMNH
	public uint DPBBFBFJCKG { get; set; } // BAOKAACCAGA 0xC // NBPLAMGJAKL CMFDHLNGNJM
	public uint FNAEGLFKDBI { get; set; } // LBAHGOGILCP 0x10 // LOMBIDHJOPN DOJHNJILKPI
	public uint GJDKHDLKONI { get; set; } // NPNOKLNFINL 0x14 // PJBLCJCLGJL NEAEKFBNIFM
	public uint PPFNGGCBJKC { get; set; } // FDGEMCPHJCB 0x18 // DEMEPMAEJOO HIGKAIDMOKN
	public uint AOLLIMFKDAA { get; set; } // NFMGELLCAMN 0x1C // JOGECEHFINO PMCBBDHCEEN
	public uint IIPIPIABGDG { get; set; } // CPOHCOAOMDD 0x20 // DNKBBHGLGIA MDMELENNABM
	public uint JPFMJHLCMJL { get; set; } // PIJIPMOBEIJ 0x24 // LLFFAPHPGFJ PMGNHNIKHLE
	public uint PKLIPLFIDED { get; set; } // GENGBBBBLHE 0x28 // IJDJDFANCBN LEOMLLPLJCF
	public uint AJAGMMHPBBC { get; set; } // NOPDOLFJHOO 0x2C // OHEEPJAFPNG LIOHOBCLGFH
	public uint DHCBIMHIPHB { get; set; } // JPBLDLNHBPC 0x30 // GBNNILGHCNH NKBLLALANEJ
	public uint MGJJHHGDOFK { get; set; } // AAIPJDLBLGL 0x34 // MPKLLDLLLMH HJCPHKJDHPO
	public uint FEJADFIALKK { get; set; } // CHHLIGMLKMD 0x38 // GGOFCNMKBBB FICFFGENKHK
	public uint IKOFFIOMOME { get; set; } // JEKIOGNINII 0x3C // PAKMDLPHDDI GEKMPKHAPFL
	public uint FFKLLDKDEFP { get; set; } // CCDIOABNGLF 0x40 // CJELOLPLHOD DEJFFEEGPGP
	public uint MIDEDJKGOED { get; set; } // EOPPCADLNFB 0x44 // FMKCLMKGDBB OHKHLGDGNEO
	public uint LKIFDCEKDCK { get; set; } // IAHMAGLCEBN 0x48 // GOKMANFHFPC ICJKOKGFNLI
}
public class FMAFIIPNNEO
{
	public uint OLKHBHLOKJI { get; set; } // PLGFIADPEMH 0x8 // JENKDEPBBHF JADIPKGHKHF
	public uint HDBEJBBPPBK { get; set; } // AKJANANIGAL 0xC // MICJGHKJCDO EKFGNBKPCDB
	public uint HOPIMOECAFA { get; set; } // IJBIGIGKGOG 0x10 // DLLDHBJBDPA NMINHOBPIKF
	public uint ANAJIAENLNB { get; set; } // IKMILCFHBGA 0x14 // MMOMNMBKHJF FEHNFGPFINK
	public uint GKHGCPODNEG { get; set; } // IMINOAPPFJL 0x18 // COOCPECOAHF BCCHDOJCABC
	public uint PIPCIMIALOO { get; set; } // INBCDPNEACE 0x1C // KJNBPECGBJJ DMAJEBCFHHK
	public uint EJOECKJNGPD { get; set; } // HEGGKIADPIF 0x20 // ELOGHDKHOMC JPLHGJKPGIC
	public uint MOIECBABHNP { get; set; } // OCJIDOFIFNB 0x24 // CADCCIKGPCN OHOOAIFAFHA
	public uint GDHLEEJPNIJ { get; set; } // ENECHGKIJMG 0x28 // AKOAGECGNOA GJDHJNAHOAD
	public uint KKBPKNBLJCK { get; set; } // EGHMADGHMCC 0x2C // PJAHCMMDOEG JPIFCOODIMI
	public uint AMGHCNHIFFG { get; set; } // KIBNINMMKID 0x30 // IFHDDMHECKI FGJGJCMHPJN
	public uint AOLENLGEJED { get; set; } // EJFLGPLODCF 0x34 // GALCMHDNMEA FCCDJDLEIIO
	public uint EPEBHGHKMBE { get; set; } // KCPHLCBPOBO 0x38 // GAFCOIJIGPD PJIPCKIGANO
}
public class FBAFBKNKENO
{
	public uint CBBLAMDGOGK { get; set; } // COLDIHOBOAC 0x8 // MLAOHCFONJD GDFGAJNCLHC
	public uint DMEDKJPOLCH { get; set; } // JAEJJPMKMFI 0xC // IPKCKAAEEOE JOGLLINFLJN
	public uint GPNOEFHGOJG { get; set; } // JHDENCIJCJC 0x10 // IMEDMCEEIMG ODOJGKNGNOP
	public uint PAIIHEJIGKO { get; set; } // LMEFJFFNMAN 0x14 // DABGLMPIDNI LOKOIJFDBDE
	public uint PLALNIIBLOF { get; set; } // DFMNDOMAPAB 0x18 // JPCJNLHHIPE JJFJNEJLBDG
	public uint KLMIFEKNBLL { get; set; } // DGEFHELLNBP 0x1C // KLMLEPCKEHM NDNHEJFBNMC
	public uint NHBLDIPBHNF { get; set; } // HEJBEEJPNPG 0x20 // HOMBHFADDNG FIEMLIDBMID
	public uint BDJMFDKLHPM { get; set; } // EOBCNECIOMH 0x24 // GFMBGPMJPLJ ENAMMCHJBDE
	public uint[] CFJKNAIOEAN { get; set; } // MPLOLLPCDIF 0x28 // PMBGOFMCPOM GALKNDCFHAK
	public uint[] BKEIOLFMMDH { get; set; } // CICHIFAEKHN 0x2C // JFEIGJLJJFM IAFNMHDEKEI
	public uint[] JGEIIONMJMI { get; set; } // MNBHJKIFPEI 0x30 // MJBNOHDIKBO JKJEOAHFDHA
	public uint[] CMENIBCJJNF { get; set; } // EAKLICNNONC 0x34 // MGNDABKMNLI PBAGALKJMLO
	public uint[] KMFHHOANPFH { get; set; } // FFDDMKIEILO 0x38 // BBIIBILMAIH EPKDJPIJDGF
	public uint[] EHODALENBEL { get; set; } // LFAOBBPOMKC 0x3C // IGMCHGEJIGP ELJJOANFNFJ
	public uint[] ALJIHHGHCOG { get; set; } // JBFFCGCNKKE 0x40 // JFIPBBGMNAJ IAOOONFGPED
}
public class EODMBJMOHBC
{
	public int LBMELIONKKB { get; set; } // BMFCJPBAMID 0x8 // NMPEEOFKHNL AFIGMMIICAK
	public uint[] JBGEEPFKIGG { get; set; } // AHPLCJAKAOP 0xC // OLOCMINKGON ABAFHIBFKCE
}
public class INDENDCNNHJ
{
	public uint LJNAKDMILMC { get; set; } // KNJIHALCKLN 0x8 // LIIHHICIBKM OACJGKPBHIK
	public int[] JBKMAPLCBMO { get; set; } // BBIAACACCGF 0xC // MAKKLCAINGM ABCGENKFMIK
}
public class OIPFPLPMCMF
{
	public uint EIIOPABMJFJ { get; set; } // KIBBKMCPCCL 0x8 // CALLFCFIGGJ HHMJLJHOHFP
	public uint FODKKJIDDKN { get; set; } // LMELEDLFDKC 0xC // LCHMMCPCFDD DHMLIEPNLCG
	public uint NBMPGOJBPMD { get; set; } // HGOFDCCONPI 0x10 // MJGJHMPBOHJ NIPFCPPENPO
	public uint[] DIPKCALNIII { get; set; } // HLEPHANBMGN 0x14 // EOGPBFIDAPF JDNCGPBAFMB
	public uint[] BEEAIAAJOHD { get; set; } // JPEMECNHGLE 0x18 // DIIBIOEMHAI JIHEDMEFKAF
	public uint OOFEIPCLEKJ { get; set; } // NHPBEEPNJCG 0x1C // PJJOAOEDBJM KDKFEPCHBLF
	public uint EDDLJBLJJOE { get; set; } // BOJAGMIMLLL 0x20 // OGNFJEEJNCL EHMPKKABGJF
	public uint JIIOKINLOGM { get; set; } // IDIACENGDHD 0x24 // MONICLNMKGP OKHMKIOCBCP
	public uint MDKNFOIMCJB { get; set; } // CHFEPGGOFKN 0x28 // OHFJKIOMNJD KDOJLNGLJBB
	public uint OENPCNBFPDA { get; set; } // CFHILALNGHJ 0x2C // BNLALNCFJPB KPJBLJCKBLF
	public uint EGMIILFFHMI { get; set; } // PEAAOAHMECD 0x30 // CNHMMEIEBNL JEDADHONPII
	public uint HFMFGFHPBNB { get; set; } // EFHBLGLBJDO 0x34 // DMKLDLMPPIG CFAEAHHNOCG
	public uint ENAAKPKFBGN { get; set; } // BJILBIMJIOI 0x38 // FCIFCCKHAGA KJCBKMPJOGM
	public uint IHLDBMMOCHF { get; set; } // KPMPHMDAEMO 0x3C // PJGCOJDADDE AEMLHPPNGGP
}
public class NJBDNGAPLLI
{
	public uint EHDDADDKMFI { get; set; } // MCAKELLLNIO 0x8 // IFFJALDBDDI LMLHCMMIEJH
	public uint NKAKDIEKAGL { get; set; } // FIHIFKJINAB 0xC // IKCJMIMEJNF FBIHFHEPNPA
}
public class MDCGKDDENNG
{
	public uint KLMIFEKNBLL { get; set; } // DGEFHELLNBP 0x8 // KLMLEPCKEHM NDNHEJFBNMC
	public uint IJEKNCDIIAE { get; set; } // FAHNCMHNFCG 0xC // KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // DFMNDOMAPAB 0x10 // JPCJNLHHIPE JJFJNEJLBDG
	public uint[] DIPKCALNIII { get; set; } // HLEPHANBMGN 0x14 // EOGPBFIDAPF JDNCGPBAFMB
	public uint ELDPFJIDNAB { get; set; } // MODLAIEFPEM 0x18 // HIODIDCBCOG BDDHPKDJPKE
	public uint NDIJPKPDOMG { get; set; } // EOGNHLKODCH 0x1C // MIOAPDAGOMG AMHPPEEMDJG
}
public class BMHPFEELLNP
{
	public NLDAADHODFI[] HDDGLOAECEK { get; set; } // FFDJKIKFALM 0x8 // EGFNOLIPDJO NOBKFEHPAOL
	public KEBPMGGPLIF[] LNNNCEAAIAM { get; set; } // CEOGECAGOON 0xC // NNPKGOICGIK EEOBJPBHEHN
	public JPALGGIPGGN[] MDFFJJKBDFC { get; set; } // MLEEAALCDDB 0x10 // CGKHDMIDHGN MDIFADGJNNH
	public FMAFIIPNNEO[] DGEPOLGDKHA { get; set; } // CKKCGOJLNDG 0x14 // KGFIKAIHPEB EICOINGPPEL
	public FBAFBKNKENO[] DBINAHBHDOC { get; set; } // EGMPBHDEDGG 0x18 // JFGKFMLKHEL MBDDJLPGJEO
	public EODMBJMOHBC[] BJGDMLNFKKN { get; set; } // ICKECHLOMOA 0x1C // OIPKLAMEMPH JBNIKGCHPPI
	public INDENDCNNHJ[] CDKOBOHBJHM { get; set; } // IBICFAFPMFK 0x20 // CDEGGAJHBIK LANIBDGHFFP
	public OIPFPLPMCMF[] JNFKEOEGGLF { get; set; } // HFHBIPOJPJK 0x24 // DNAMALNANBC NHAHDADMKAE
	public NJBDNGAPLLI[] JEOOAMHEMJL { get; set; } // GGGJBGDBGEK 0x28 // FJHMMOHFBML LAGKKKDMJPH
	public MDCGKDDENNG[] BOECDBOLGJN { get; set; } // DLFELOOMEFF 0x2C // PFKFCHHAKLA FIOGMDLBIIG
	public static BMHPFEELLNP HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x19C3CC8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JKFNAKIBOCI res_readData = JKFNAKIBOCI.GetRootAsJKFNAKIBOCI(buffer);
		BMHPFEELLNP res_data = new BMHPFEELLNP();

		List<NLDAADHODFI> HDDGLOAECEK_list = new List<NLDAADHODFI>();
		for(int HDDGLOAECEK_idx = 0; HDDGLOAECEK_idx < res_readData.PMNLBNBKCDMLength; HDDGLOAECEK_idx++)
		{
			IGBINOLLPPB HDDGLOAECEK_readData = res_readData.GetPMNLBNBKCDM(HDDGLOAECEK_idx);
			NLDAADHODFI HDDGLOAECEK_data = new NLDAADHODFI();

			HDDGLOAECEK_data.CBBLAMDGOGK = HDDGLOAECEK_readData.HLCDELCABOF;
			HDDGLOAECEK_data.DMEDKJPOLCH = HDDGLOAECEK_readData.ADCLAGBHDBC;
			HDDGLOAECEK_data.LHKFKIKEJHN = HDDGLOAECEK_readData.EJCJCAMDFGF;
			HDDGLOAECEK_data.PLALNIIBLOF = HDDGLOAECEK_readData.CFLMCGOJJJD;
			HDDGLOAECEK_data.EHDDADDKMFI = HDDGLOAECEK_readData.NAJHJIHCOON;
			HDDGLOAECEK_data.KLMIFEKNBLL = HDDGLOAECEK_readData.AMFPDKACLLL;
			HDDGLOAECEK_data.FPOMEEJFBIG = HDDGLOAECEK_readData.AEAKMMJLLDK;
			HDDGLOAECEK_data.GPNOEFHGOJG = HDDGLOAECEK_readData.OFLDIKGIPBL;
			HDDGLOAECEK_data.PAIIHEJIGKO = HDDGLOAECEK_readData.DLGFIIKAOJD;
			HDDGLOAECEK_data.FCEJJEPFIPH = HDDGLOAECEK_readData.LNHODOPAJIL;
			List<uint> CFJKNAIOEAN_list = new List<uint>();
			for(int CFJKNAIOEAN_idx = 0; CFJKNAIOEAN_idx < HDDGLOAECEK_readData.HOFPKKMIOALLength; CFJKNAIOEAN_idx++)
			{
				CFJKNAIOEAN_list.Add(HDDGLOAECEK_readData.GetHOFPKKMIOAL(CFJKNAIOEAN_idx));
			}
			HDDGLOAECEK_data.CFJKNAIOEAN = CFJKNAIOEAN_list.ToArray();

			List<uint> BKEIOLFMMDH_list = new List<uint>();
			for(int BKEIOLFMMDH_idx = 0; BKEIOLFMMDH_idx < HDDGLOAECEK_readData.CPOGAPIBMHFLength; BKEIOLFMMDH_idx++)
			{
				BKEIOLFMMDH_list.Add(HDDGLOAECEK_readData.GetCPOGAPIBMHF(BKEIOLFMMDH_idx));
			}
			HDDGLOAECEK_data.BKEIOLFMMDH = BKEIOLFMMDH_list.ToArray();

			List<uint> JGEIIONMJMI_list = new List<uint>();
			for(int JGEIIONMJMI_idx = 0; JGEIIONMJMI_idx < HDDGLOAECEK_readData.GFFCGBEAKDPLength; JGEIIONMJMI_idx++)
			{
				JGEIIONMJMI_list.Add(HDDGLOAECEK_readData.GetGFFCGBEAKDP(JGEIIONMJMI_idx));
			}
			HDDGLOAECEK_data.JGEIIONMJMI = JGEIIONMJMI_list.ToArray();

			List<uint> CMENIBCJJNF_list = new List<uint>();
			for(int CMENIBCJJNF_idx = 0; CMENIBCJJNF_idx < HDDGLOAECEK_readData.NBOHLKPDNKALength; CMENIBCJJNF_idx++)
			{
				CMENIBCJJNF_list.Add(HDDGLOAECEK_readData.GetNBOHLKPDNKA(CMENIBCJJNF_idx));
			}
			HDDGLOAECEK_data.CMENIBCJJNF = CMENIBCJJNF_list.ToArray();

			List<uint> KMFHHOANPFH_list = new List<uint>();
			for(int KMFHHOANPFH_idx = 0; KMFHHOANPFH_idx < HDDGLOAECEK_readData.DHHLJCLLPAFLength; KMFHHOANPFH_idx++)
			{
				KMFHHOANPFH_list.Add(HDDGLOAECEK_readData.GetDHHLJCLLPAF(KMFHHOANPFH_idx));
			}
			HDDGLOAECEK_data.KMFHHOANPFH = KMFHHOANPFH_list.ToArray();

			List<uint> EHODALENBEL_list = new List<uint>();
			for(int EHODALENBEL_idx = 0; EHODALENBEL_idx < HDDGLOAECEK_readData.OHBEDDIGFKGLength; EHODALENBEL_idx++)
			{
				EHODALENBEL_list.Add(HDDGLOAECEK_readData.GetOHBEDDIGFKG(EHODALENBEL_idx));
			}
			HDDGLOAECEK_data.EHODALENBEL = EHODALENBEL_list.ToArray();

			List<uint> ALJIHHGHCOG_list = new List<uint>();
			for(int ALJIHHGHCOG_idx = 0; ALJIHHGHCOG_idx < HDDGLOAECEK_readData.DNHAKGCPLOGLength; ALJIHHGHCOG_idx++)
			{
				ALJIHHGHCOG_list.Add(HDDGLOAECEK_readData.GetDNHAKGCPLOG(ALJIHHGHCOG_idx));
			}
			HDDGLOAECEK_data.ALJIHHGHCOG = ALJIHHGHCOG_list.ToArray();

			HDDGLOAECEK_data.NOHIMPJDOCK = HDDGLOAECEK_readData.PLKKDJCPONF;
			HDDGLOAECEK_data.DFELEPDHLBF = HDDGLOAECEK_readData.KACDPANCECF;
			HDDGLOAECEK_data.CAJKBDLCGOD = HDDGLOAECEK_readData.MKCOKBLMLBH;
			HDDGLOAECEK_data.LHBNIAJDIGA = HDDGLOAECEK_readData.BDJNKDFFIKF;
			HDDGLOAECEK_data.IJEKNCDIIAE = HDDGLOAECEK_readData.OFMGALJGDAO;
			HDDGLOAECEK_data.JJMMJGANPFI = HDDGLOAECEK_readData.PFIBELFMLLM;
			HDDGLOAECEK_data.EIIOPABMJFJ = HDDGLOAECEK_readData.INCDOBNIIPH;
			HDDGLOAECEK_data.HHGPOOBOKHP = HDDGLOAECEK_readData.BBLLPBBJHDG;
			HDDGLOAECEK_data.ECLGEFGJMAM = HDDGLOAECEK_readData.HIDEDIMKGAI;
			HDDGLOAECEK_data.FABJJODPCIN = HDDGLOAECEK_readData.GGAGCGHLDAB;
			HDDGLOAECEK_data.CCHNGBLALEB = HDDGLOAECEK_readData.KAJAOOEGKBP;
			List<uint> BODBNFFIOJN_list = new List<uint>();
			for(int BODBNFFIOJN_idx = 0; BODBNFFIOJN_idx < HDDGLOAECEK_readData.HEJFHKLCDOCLength; BODBNFFIOJN_idx++)
			{
				BODBNFFIOJN_list.Add(HDDGLOAECEK_readData.GetHEJFHKLCDOC(BODBNFFIOJN_idx));
			}
			HDDGLOAECEK_data.BODBNFFIOJN = BODBNFFIOJN_list.ToArray();

			List<uint> KJLLNPFHEEL_list = new List<uint>();
			for(int KJLLNPFHEEL_idx = 0; KJLLNPFHEEL_idx < HDDGLOAECEK_readData.ONNPLNPMNIELength; KJLLNPFHEEL_idx++)
			{
				KJLLNPFHEEL_list.Add(HDDGLOAECEK_readData.GetONNPLNPMNIE(KJLLNPFHEEL_idx));
			}
			HDDGLOAECEK_data.KJLLNPFHEEL = KJLLNPFHEEL_list.ToArray();

			List<uint> DOAFFAGEHOM_list = new List<uint>();
			for(int DOAFFAGEHOM_idx = 0; DOAFFAGEHOM_idx < HDDGLOAECEK_readData.FCLPDBPKMGHLength; DOAFFAGEHOM_idx++)
			{
				DOAFFAGEHOM_list.Add(HDDGLOAECEK_readData.GetFCLPDBPKMGH(DOAFFAGEHOM_idx));
			}
			HDDGLOAECEK_data.DOAFFAGEHOM = DOAFFAGEHOM_list.ToArray();

			List<uint> BIHJCIGKMBA_list = new List<uint>();
			for(int BIHJCIGKMBA_idx = 0; BIHJCIGKMBA_idx < HDDGLOAECEK_readData.KLADDKGABODLength; BIHJCIGKMBA_idx++)
			{
				BIHJCIGKMBA_list.Add(HDDGLOAECEK_readData.GetKLADDKGABOD(BIHJCIGKMBA_idx));
			}
			HDDGLOAECEK_data.BIHJCIGKMBA = BIHJCIGKMBA_list.ToArray();

			List<uint> OOBOCLOFPBF_list = new List<uint>();
			for(int OOBOCLOFPBF_idx = 0; OOBOCLOFPBF_idx < HDDGLOAECEK_readData.FECBKKEGDKJLength; OOBOCLOFPBF_idx++)
			{
				OOBOCLOFPBF_list.Add(HDDGLOAECEK_readData.GetFECBKKEGDKJ(OOBOCLOFPBF_idx));
			}
			HDDGLOAECEK_data.OOBOCLOFPBF = OOBOCLOFPBF_list.ToArray();

			List<uint> DKAIOCGKJLO_list = new List<uint>();
			for(int DKAIOCGKJLO_idx = 0; DKAIOCGKJLO_idx < HDDGLOAECEK_readData.IJKGNDLDHODLength; DKAIOCGKJLO_idx++)
			{
				DKAIOCGKJLO_list.Add(HDDGLOAECEK_readData.GetIJKGNDLDHOD(DKAIOCGKJLO_idx));
			}
			HDDGLOAECEK_data.DKAIOCGKJLO = DKAIOCGKJLO_list.ToArray();

			List<uint> OIDAMEGDNOF_list = new List<uint>();
			for(int OIDAMEGDNOF_idx = 0; OIDAMEGDNOF_idx < HDDGLOAECEK_readData.ALBAAFNCALMLength; OIDAMEGDNOF_idx++)
			{
				OIDAMEGDNOF_list.Add(HDDGLOAECEK_readData.GetALBAAFNCALM(OIDAMEGDNOF_idx));
			}
			HDDGLOAECEK_data.OIDAMEGDNOF = OIDAMEGDNOF_list.ToArray();

			HDDGLOAECEK_data.OHDNJMJCGCJ = HDDGLOAECEK_readData.HBGBAPHAHOA;
			HDDGLOAECEK_data.PNIFJEENINF = HDDGLOAECEK_readData.DHIEDHMBKNB;
			HDDGLOAECEK_list.Add(HDDGLOAECEK_data);
		}
		res_data.HDDGLOAECEK = HDDGLOAECEK_list.ToArray();

		List<KEBPMGGPLIF> LNNNCEAAIAM_list = new List<KEBPMGGPLIF>();
		for(int LNNNCEAAIAM_idx = 0; LNNNCEAAIAM_idx < res_readData.IPFGDNLPHFALength; LNNNCEAAIAM_idx++)
		{
			CDCEKBNNJLL LNNNCEAAIAM_readData = res_readData.GetIPFGDNLPHFA(LNNNCEAAIAM_idx);
			KEBPMGGPLIF LNNNCEAAIAM_data = new KEBPMGGPLIF();

			List<uint> AIHOJKFNEEN_list = new List<uint>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < LNNNCEAAIAM_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(LNNNCEAAIAM_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			LNNNCEAAIAM_data.AIHOJKFNEEN = AIHOJKFNEEN_list.ToArray();

			LNNNCEAAIAM_data.FCEJJEPFIPH = LNNNCEAAIAM_readData.LNHODOPAJIL;
			LNNNCEAAIAM_list.Add(LNNNCEAAIAM_data);
		}
		res_data.LNNNCEAAIAM = LNNNCEAAIAM_list.ToArray();

		List<JPALGGIPGGN> MDFFJJKBDFC_list = new List<JPALGGIPGGN>();
		for(int MDFFJJKBDFC_idx = 0; MDFFJJKBDFC_idx < res_readData.CGHMONDBJAILength; MDFFJJKBDFC_idx++)
		{
			FELDPFHIOHB MDFFJJKBDFC_readData = res_readData.GetCGHMONDBJAI(MDFFJJKBDFC_idx);
			JPALGGIPGGN MDFFJJKBDFC_data = new JPALGGIPGGN();

			MDFFJJKBDFC_data.JPHOOKPHBLD = MDFFJJKBDFC_readData.CFDDADEOMJE;
			MDFFJJKBDFC_data.DPBBFBFJCKG = MDFFJJKBDFC_readData.KCDJCBMMALB;
			MDFFJJKBDFC_data.FNAEGLFKDBI = MDFFJJKBDFC_readData.JDDPFMAIEJK;
			MDFFJJKBDFC_data.GJDKHDLKONI = MDFFJJKBDFC_readData.ALGLINABMBO;
			MDFFJJKBDFC_data.PPFNGGCBJKC = MDFFJJKBDFC_readData.BBPHAPFBFHK;
			MDFFJJKBDFC_data.AOLLIMFKDAA = MDFFJJKBDFC_readData.OPEDKFOOFMO;
			MDFFJJKBDFC_data.IIPIPIABGDG = MDFFJJKBDFC_readData.CLGDAMPNKAA;
			MDFFJJKBDFC_data.JPFMJHLCMJL = MDFFJJKBDFC_readData.GJEJFAJHBME;
			MDFFJJKBDFC_data.PKLIPLFIDED = MDFFJJKBDFC_readData.JPNENGEPDED;
			MDFFJJKBDFC_data.AJAGMMHPBBC = MDFFJJKBDFC_readData.JPBEMBKMEON;
			MDFFJJKBDFC_data.DHCBIMHIPHB = MDFFJJKBDFC_readData.ALNLKFDILHL;
			MDFFJJKBDFC_data.MGJJHHGDOFK = MDFFJJKBDFC_readData.EHJPHAAHMEF;
			MDFFJJKBDFC_data.FEJADFIALKK = MDFFJJKBDFC_readData.FKICJENKKIC;
			MDFFJJKBDFC_data.IKOFFIOMOME = MDFFJJKBDFC_readData.INBPHKHGIAM;
			MDFFJJKBDFC_data.FFKLLDKDEFP = MDFFJJKBDFC_readData.IMPIDEOCBKK;
			MDFFJJKBDFC_data.MIDEDJKGOED = MDFFJJKBDFC_readData.EELICAHAECD;
			MDFFJJKBDFC_data.LKIFDCEKDCK = MDFFJJKBDFC_readData.JKDAMKCJMLD;
			MDFFJJKBDFC_list.Add(MDFFJJKBDFC_data);
		}
		res_data.MDFFJJKBDFC = MDFFJJKBDFC_list.ToArray();

		List<FMAFIIPNNEO> DGEPOLGDKHA_list = new List<FMAFIIPNNEO>();
		for(int DGEPOLGDKHA_idx = 0; DGEPOLGDKHA_idx < res_readData.GCHBPMOLDHOLength; DGEPOLGDKHA_idx++)
		{
			COJOFJEOJDI DGEPOLGDKHA_readData = res_readData.GetGCHBPMOLDHO(DGEPOLGDKHA_idx);
			FMAFIIPNNEO DGEPOLGDKHA_data = new FMAFIIPNNEO();

			DGEPOLGDKHA_data.OLKHBHLOKJI = DGEPOLGDKHA_readData.CIFKCEFLDDL;
			DGEPOLGDKHA_data.HDBEJBBPPBK = DGEPOLGDKHA_readData.DILIHLCAPFG;
			DGEPOLGDKHA_data.HOPIMOECAFA = DGEPOLGDKHA_readData.FJDKDEDMHNI;
			DGEPOLGDKHA_data.ANAJIAENLNB = DGEPOLGDKHA_readData.DLPCOLDNAKE;
			DGEPOLGDKHA_data.GKHGCPODNEG = DGEPOLGDKHA_readData.BJOOHLLPCFK;
			DGEPOLGDKHA_data.PIPCIMIALOO = DGEPOLGDKHA_readData.GKLHNNBMGKH;
			DGEPOLGDKHA_data.EJOECKJNGPD = DGEPOLGDKHA_readData.CNLOBDLMAAP;
			DGEPOLGDKHA_data.MOIECBABHNP = DGEPOLGDKHA_readData.NJHACADNBPI;
			DGEPOLGDKHA_data.GDHLEEJPNIJ = DGEPOLGDKHA_readData.OHAOECLAPEG;
			DGEPOLGDKHA_data.KKBPKNBLJCK = DGEPOLGDKHA_readData.JNAIKKGAEEE;
			DGEPOLGDKHA_data.AMGHCNHIFFG = DGEPOLGDKHA_readData.HEBOLJILFOE;
			DGEPOLGDKHA_data.AOLENLGEJED = DGEPOLGDKHA_readData.JDKJPDKIEOA;
			DGEPOLGDKHA_data.EPEBHGHKMBE = DGEPOLGDKHA_readData.EJHHKNOCLBN;
			DGEPOLGDKHA_list.Add(DGEPOLGDKHA_data);
		}
		res_data.DGEPOLGDKHA = DGEPOLGDKHA_list.ToArray();

		List<FBAFBKNKENO> DBINAHBHDOC_list = new List<FBAFBKNKENO>();
		for(int DBINAHBHDOC_idx = 0; DBINAHBHDOC_idx < res_readData.GPKPLHPBDJOLength; DBINAHBHDOC_idx++)
		{
			HMAOBLEJDAH DBINAHBHDOC_readData = res_readData.GetGPKPLHPBDJO(DBINAHBHDOC_idx);
			FBAFBKNKENO DBINAHBHDOC_data = new FBAFBKNKENO();

			DBINAHBHDOC_data.CBBLAMDGOGK = DBINAHBHDOC_readData.HLCDELCABOF;
			DBINAHBHDOC_data.DMEDKJPOLCH = DBINAHBHDOC_readData.ADCLAGBHDBC;
			DBINAHBHDOC_data.GPNOEFHGOJG = DBINAHBHDOC_readData.OFLDIKGIPBL;
			DBINAHBHDOC_data.PAIIHEJIGKO = DBINAHBHDOC_readData.DLGFIIKAOJD;
			DBINAHBHDOC_data.PLALNIIBLOF = DBINAHBHDOC_readData.CFLMCGOJJJD;
			DBINAHBHDOC_data.KLMIFEKNBLL = DBINAHBHDOC_readData.AMFPDKACLLL;
			DBINAHBHDOC_data.NHBLDIPBHNF = DBINAHBHDOC_readData.LNCMMHCDOJE;
			DBINAHBHDOC_data.BDJMFDKLHPM = DBINAHBHDOC_readData.MJOCIHPPKNO;
			List<uint> CFJKNAIOEAN_list = new List<uint>();
			for(int CFJKNAIOEAN_idx = 0; CFJKNAIOEAN_idx < DBINAHBHDOC_readData.HOFPKKMIOALLength; CFJKNAIOEAN_idx++)
			{
				CFJKNAIOEAN_list.Add(DBINAHBHDOC_readData.GetHOFPKKMIOAL(CFJKNAIOEAN_idx));
			}
			DBINAHBHDOC_data.CFJKNAIOEAN = CFJKNAIOEAN_list.ToArray();

			List<uint> BKEIOLFMMDH_list = new List<uint>();
			for(int BKEIOLFMMDH_idx = 0; BKEIOLFMMDH_idx < DBINAHBHDOC_readData.CPOGAPIBMHFLength; BKEIOLFMMDH_idx++)
			{
				BKEIOLFMMDH_list.Add(DBINAHBHDOC_readData.GetCPOGAPIBMHF(BKEIOLFMMDH_idx));
			}
			DBINAHBHDOC_data.BKEIOLFMMDH = BKEIOLFMMDH_list.ToArray();

			List<uint> JGEIIONMJMI_list = new List<uint>();
			for(int JGEIIONMJMI_idx = 0; JGEIIONMJMI_idx < DBINAHBHDOC_readData.GFFCGBEAKDPLength; JGEIIONMJMI_idx++)
			{
				JGEIIONMJMI_list.Add(DBINAHBHDOC_readData.GetGFFCGBEAKDP(JGEIIONMJMI_idx));
			}
			DBINAHBHDOC_data.JGEIIONMJMI = JGEIIONMJMI_list.ToArray();

			List<uint> CMENIBCJJNF_list = new List<uint>();
			for(int CMENIBCJJNF_idx = 0; CMENIBCJJNF_idx < DBINAHBHDOC_readData.NBOHLKPDNKALength; CMENIBCJJNF_idx++)
			{
				CMENIBCJJNF_list.Add(DBINAHBHDOC_readData.GetNBOHLKPDNKA(CMENIBCJJNF_idx));
			}
			DBINAHBHDOC_data.CMENIBCJJNF = CMENIBCJJNF_list.ToArray();

			List<uint> KMFHHOANPFH_list = new List<uint>();
			for(int KMFHHOANPFH_idx = 0; KMFHHOANPFH_idx < DBINAHBHDOC_readData.DHHLJCLLPAFLength; KMFHHOANPFH_idx++)
			{
				KMFHHOANPFH_list.Add(DBINAHBHDOC_readData.GetDHHLJCLLPAF(KMFHHOANPFH_idx));
			}
			DBINAHBHDOC_data.KMFHHOANPFH = KMFHHOANPFH_list.ToArray();

			List<uint> EHODALENBEL_list = new List<uint>();
			for(int EHODALENBEL_idx = 0; EHODALENBEL_idx < DBINAHBHDOC_readData.OHBEDDIGFKGLength; EHODALENBEL_idx++)
			{
				EHODALENBEL_list.Add(DBINAHBHDOC_readData.GetOHBEDDIGFKG(EHODALENBEL_idx));
			}
			DBINAHBHDOC_data.EHODALENBEL = EHODALENBEL_list.ToArray();

			List<uint> ALJIHHGHCOG_list = new List<uint>();
			for(int ALJIHHGHCOG_idx = 0; ALJIHHGHCOG_idx < DBINAHBHDOC_readData.DNHAKGCPLOGLength; ALJIHHGHCOG_idx++)
			{
				ALJIHHGHCOG_list.Add(DBINAHBHDOC_readData.GetDNHAKGCPLOG(ALJIHHGHCOG_idx));
			}
			DBINAHBHDOC_data.ALJIHHGHCOG = ALJIHHGHCOG_list.ToArray();

			DBINAHBHDOC_list.Add(DBINAHBHDOC_data);
		}
		res_data.DBINAHBHDOC = DBINAHBHDOC_list.ToArray();

		List<EODMBJMOHBC> BJGDMLNFKKN_list = new List<EODMBJMOHBC>();
		for(int BJGDMLNFKKN_idx = 0; BJGDMLNFKKN_idx < res_readData.PGLIDFOBMEFLength; BJGDMLNFKKN_idx++)
		{
			CGNIMFAHBJM BJGDMLNFKKN_readData = res_readData.GetPGLIDFOBMEF(BJGDMLNFKKN_idx);
			EODMBJMOHBC BJGDMLNFKKN_data = new EODMBJMOHBC();

			BJGDMLNFKKN_data.LBMELIONKKB = BJGDMLNFKKN_readData.NDJHFINEEGP;
			List<uint> JBGEEPFKIGG_list = new List<uint>();
			for(int JBGEEPFKIGG_idx = 0; JBGEEPFKIGG_idx < BJGDMLNFKKN_readData.CGKGLCKCAMCLength; JBGEEPFKIGG_idx++)
			{
				JBGEEPFKIGG_list.Add(BJGDMLNFKKN_readData.GetCGKGLCKCAMC(JBGEEPFKIGG_idx));
			}
			BJGDMLNFKKN_data.JBGEEPFKIGG = JBGEEPFKIGG_list.ToArray();

			BJGDMLNFKKN_list.Add(BJGDMLNFKKN_data);
		}
		res_data.BJGDMLNFKKN = BJGDMLNFKKN_list.ToArray();

		List<INDENDCNNHJ> CDKOBOHBJHM_list = new List<INDENDCNNHJ>();
		for(int CDKOBOHBJHM_idx = 0; CDKOBOHBJHM_idx < res_readData.ENMMCFBMAGJLength; CDKOBOHBJHM_idx++)
		{
			EKIPCOEPMIF CDKOBOHBJHM_readData = res_readData.GetENMMCFBMAGJ(CDKOBOHBJHM_idx);
			INDENDCNNHJ CDKOBOHBJHM_data = new INDENDCNNHJ();

			CDKOBOHBJHM_data.LJNAKDMILMC = CDKOBOHBJHM_readData.AGOIMGHMGOH;
			List<int> JBKMAPLCBMO_list = new List<int>();
			for(int JBKMAPLCBMO_idx = 0; JBKMAPLCBMO_idx < CDKOBOHBJHM_readData.AHLIHEFODLDLength; JBKMAPLCBMO_idx++)
			{
				JBKMAPLCBMO_list.Add(CDKOBOHBJHM_readData.GetAHLIHEFODLD(JBKMAPLCBMO_idx));
			}
			CDKOBOHBJHM_data.JBKMAPLCBMO = JBKMAPLCBMO_list.ToArray();

			CDKOBOHBJHM_list.Add(CDKOBOHBJHM_data);
		}
		res_data.CDKOBOHBJHM = CDKOBOHBJHM_list.ToArray();

		List<OIPFPLPMCMF> JNFKEOEGGLF_list = new List<OIPFPLPMCMF>();
		for(int JNFKEOEGGLF_idx = 0; JNFKEOEGGLF_idx < res_readData.GCANFKHNPMBLength; JNFKEOEGGLF_idx++)
		{
			BMALHADEABJ JNFKEOEGGLF_readData = res_readData.GetGCANFKHNPMB(JNFKEOEGGLF_idx);
			OIPFPLPMCMF JNFKEOEGGLF_data = new OIPFPLPMCMF();

			JNFKEOEGGLF_data.EIIOPABMJFJ = JNFKEOEGGLF_readData.INCDOBNIIPH;
			JNFKEOEGGLF_data.FODKKJIDDKN = JNFKEOEGGLF_readData.MDGOAMHIAMH;
			JNFKEOEGGLF_data.NBMPGOJBPMD = JNFKEOEGGLF_readData.DHJAFJKALCA;
			List<uint> DIPKCALNIII_list = new List<uint>();
			for(int DIPKCALNIII_idx = 0; DIPKCALNIII_idx < JNFKEOEGGLF_readData.LACEJFCOFHGLength; DIPKCALNIII_idx++)
			{
				DIPKCALNIII_list.Add(JNFKEOEGGLF_readData.GetLACEJFCOFHG(DIPKCALNIII_idx));
			}
			JNFKEOEGGLF_data.DIPKCALNIII = DIPKCALNIII_list.ToArray();

			List<uint> BEEAIAAJOHD_list = new List<uint>();
			for(int BEEAIAAJOHD_idx = 0; BEEAIAAJOHD_idx < JNFKEOEGGLF_readData.OFIKIJKPFAFLength; BEEAIAAJOHD_idx++)
			{
				BEEAIAAJOHD_list.Add(JNFKEOEGGLF_readData.GetOFIKIJKPFAF(BEEAIAAJOHD_idx));
			}
			JNFKEOEGGLF_data.BEEAIAAJOHD = BEEAIAAJOHD_list.ToArray();

			JNFKEOEGGLF_data.OOFEIPCLEKJ = JNFKEOEGGLF_readData.CHNBFNIKEBM;
			JNFKEOEGGLF_data.EDDLJBLJJOE = JNFKEOEGGLF_readData.APNAIGEPNEG;
			JNFKEOEGGLF_data.JIIOKINLOGM = JNFKEOEGGLF_readData.GILPCLPDGBI;
			JNFKEOEGGLF_data.MDKNFOIMCJB = JNFKEOEGGLF_readData.IFDJNKPLADH;
			JNFKEOEGGLF_data.OENPCNBFPDA = JNFKEOEGGLF_readData.MOMCBJDJDIA;
			JNFKEOEGGLF_data.EGMIILFFHMI = JNFKEOEGGLF_readData.EINBGKEKALF;
			JNFKEOEGGLF_data.HFMFGFHPBNB = JNFKEOEGGLF_readData.CLLDHAPABLI;
			JNFKEOEGGLF_data.ENAAKPKFBGN = JNFKEOEGGLF_readData.IJKMBFLJGJF;
			JNFKEOEGGLF_data.IHLDBMMOCHF = JNFKEOEGGLF_readData.EPGNGIDAFGH;
			JNFKEOEGGLF_list.Add(JNFKEOEGGLF_data);
		}
		res_data.JNFKEOEGGLF = JNFKEOEGGLF_list.ToArray();

		List<NJBDNGAPLLI> JEOOAMHEMJL_list = new List<NJBDNGAPLLI>();
		for(int JEOOAMHEMJL_idx = 0; JEOOAMHEMJL_idx < res_readData.CCBLOPIOPEGLength; JEOOAMHEMJL_idx++)
		{
			JDNHKBBPAOI JEOOAMHEMJL_readData = res_readData.GetCCBLOPIOPEG(JEOOAMHEMJL_idx);
			NJBDNGAPLLI JEOOAMHEMJL_data = new NJBDNGAPLLI();

			JEOOAMHEMJL_data.EHDDADDKMFI = JEOOAMHEMJL_readData.NAJHJIHCOON;
			JEOOAMHEMJL_data.NKAKDIEKAGL = JEOOAMHEMJL_readData.CBGDIIIBBAN;
			JEOOAMHEMJL_list.Add(JEOOAMHEMJL_data);
		}
		res_data.JEOOAMHEMJL = JEOOAMHEMJL_list.ToArray();

		List<MDCGKDDENNG> BOECDBOLGJN_list = new List<MDCGKDDENNG>();
		for(int BOECDBOLGJN_idx = 0; BOECDBOLGJN_idx < res_readData.CGPPMMAJNGNLength; BOECDBOLGJN_idx++)
		{
			JCFEECCNGIF BOECDBOLGJN_readData = res_readData.GetCGPPMMAJNGN(BOECDBOLGJN_idx);
			MDCGKDDENNG BOECDBOLGJN_data = new MDCGKDDENNG();

			BOECDBOLGJN_data.KLMIFEKNBLL = BOECDBOLGJN_readData.AMFPDKACLLL;
			BOECDBOLGJN_data.IJEKNCDIIAE = BOECDBOLGJN_readData.OFMGALJGDAO;
			BOECDBOLGJN_data.PLALNIIBLOF = BOECDBOLGJN_readData.CFLMCGOJJJD;
			List<uint> DIPKCALNIII_list = new List<uint>();
			for(int DIPKCALNIII_idx = 0; DIPKCALNIII_idx < BOECDBOLGJN_readData.LACEJFCOFHGLength; DIPKCALNIII_idx++)
			{
				DIPKCALNIII_list.Add(BOECDBOLGJN_readData.GetLACEJFCOFHG(DIPKCALNIII_idx));
			}
			BOECDBOLGJN_data.DIPKCALNIII = DIPKCALNIII_list.ToArray();

			BOECDBOLGJN_data.ELDPFJIDNAB = BOECDBOLGJN_readData.GHPIPMFBJHH;
			BOECDBOLGJN_data.NDIJPKPDOMG = BOECDBOLGJN_readData.EMFHICAOLOA;
			BOECDBOLGJN_list.Add(BOECDBOLGJN_data);
		}
		res_data.BOECDBOLGJN = BOECDBOLGJN_list.ToArray();

		return res_data;
	}
}
