using FlatBuffers;
using System.Collections.Generic;

public class LKCILPCIPBE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int[] JIMJHIDEHNM { get; set; } // 0xC CPFMBIINNNL HMLIMKEFHHD OPHOIBNLNLN
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int[] HANMDEBPBHG { get; set; } // 0x14 IMDBPCNAOOE EFGGIMOPNMG PNGGKPFDKMA
	public string[] IPBHCLIHAPG { get; set; } // 0x18 PGDNLLBNAFF CBMCOGPJADM BAIGLALPKDE
	public int IJEKNCDIIAE { get; set; } // 0x1C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int KNHABOOAAIP { get; set; } // 0x20 ADCPFMGAFHF KILMBMIGBOE NEDDEHCHIBE
	public string[] ADCMNODJBGJ { get; set; } // 0x24 PDOIKFFAKNG AJDDKABOOLK GHAHAGNIELN
	public int[] INANEEGAEEG { get; set; } // 0x28 CKPKJEJMACE GAEPJHACPBA FGPHIHOOEGP
	public int[] JOFAJDPOEOB { get; set; } // 0x2C HFBODPFCJDN IFMBJHJFFNF CHNGFDMJKBE
	public int DBHPPMPNCKF { get; set; } // 0x30 PLPJBFEDAOM JHLPDKDGDJB GBKBPCELENK
	public int BFCILBEICEN { get; set; } // 0x34 GFBFNCJOPAL NBIIHNECDLH HPFFECCGJCP
}
public class BOFIIKIJEPA
{
	public LKCILPCIPBE[] NBDMOIBEDFI { get; set; } // 0x8 PNNNALPPKAG EPIPNCALBIK AIDOPJFGDJI
	public static BOFIIKIJEPA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x19CCD6C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		PCIPKGNLLBO res_readData = PCIPKGNLLBO.GetRootAsPCIPKGNLLBO(buffer);
		BOFIIKIJEPA res_data = new BOFIIKIJEPA();

		List<LKCILPCIPBE> NBDMOIBEDFI_list = new List<LKCILPCIPBE>();
		for(int NBDMOIBEDFI_idx = 0; NBDMOIBEDFI_idx < res_readData.NGOGEEKMLKNLength; NBDMOIBEDFI_idx++)
		{
			NHPNFFMICJP NBDMOIBEDFI_readData = res_readData.GetNGOGEEKMLKN(NBDMOIBEDFI_idx);
			LKCILPCIPBE NBDMOIBEDFI_data = new LKCILPCIPBE();

			NBDMOIBEDFI_data.PPFNGGCBJKC = NBDMOIBEDFI_readData.BBPHAPFBFHK;
			List<int> JIMJHIDEHNM_list = new List<int>();
			for(int JIMJHIDEHNM_idx = 0; JIMJHIDEHNM_idx < NBDMOIBEDFI_readData.OFJEKBGFFPBLength; JIMJHIDEHNM_idx++)
			{
				JIMJHIDEHNM_list.Add(NBDMOIBEDFI_readData.GetOFJEKBGFFPB(JIMJHIDEHNM_idx));
			}
			NBDMOIBEDFI_data.JIMJHIDEHNM = JIMJHIDEHNM_list.ToArray();

			NBDMOIBEDFI_data.PLALNIIBLOF = NBDMOIBEDFI_readData.CFLMCGOJJJD;
			List<int> HANMDEBPBHG_list = new List<int>();
			for(int HANMDEBPBHG_idx = 0; HANMDEBPBHG_idx < NBDMOIBEDFI_readData.KNOOHMIHJNLLength; HANMDEBPBHG_idx++)
			{
				HANMDEBPBHG_list.Add(NBDMOIBEDFI_readData.GetKNOOHMIHJNL(HANMDEBPBHG_idx));
			}
			NBDMOIBEDFI_data.HANMDEBPBHG = HANMDEBPBHG_list.ToArray();

			List<string> IPBHCLIHAPG_list = new List<string>();
			for(int IPBHCLIHAPG_idx = 0; IPBHCLIHAPG_idx < NBDMOIBEDFI_readData.IKDLGFEPPDBLength; IPBHCLIHAPG_idx++)
			{
				IPBHCLIHAPG_list.Add(NBDMOIBEDFI_readData.GetIKDLGFEPPDB(IPBHCLIHAPG_idx));
			}
			NBDMOIBEDFI_data.IPBHCLIHAPG = IPBHCLIHAPG_list.ToArray();

			NBDMOIBEDFI_data.IJEKNCDIIAE = NBDMOIBEDFI_readData.OFMGALJGDAO;
			NBDMOIBEDFI_data.KNHABOOAAIP = NBDMOIBEDFI_readData.EECIECJDLGC;
			List<string> ADCMNODJBGJ_list = new List<string>();
			for(int ADCMNODJBGJ_idx = 0; ADCMNODJBGJ_idx < NBDMOIBEDFI_readData.CFBPBOLLPHHLength; ADCMNODJBGJ_idx++)
			{
				ADCMNODJBGJ_list.Add(NBDMOIBEDFI_readData.GetCFBPBOLLPHH(ADCMNODJBGJ_idx));
			}
			NBDMOIBEDFI_data.ADCMNODJBGJ = ADCMNODJBGJ_list.ToArray();

			List<int> INANEEGAEEG_list = new List<int>();
			for(int INANEEGAEEG_idx = 0; INANEEGAEEG_idx < NBDMOIBEDFI_readData.KMLACADFKINLength; INANEEGAEEG_idx++)
			{
				INANEEGAEEG_list.Add(NBDMOIBEDFI_readData.GetKMLACADFKIN(INANEEGAEEG_idx));
			}
			NBDMOIBEDFI_data.INANEEGAEEG = INANEEGAEEG_list.ToArray();

			List<int> JOFAJDPOEOB_list = new List<int>();
			for(int JOFAJDPOEOB_idx = 0; JOFAJDPOEOB_idx < NBDMOIBEDFI_readData.EGMHEAOKLNDLength; JOFAJDPOEOB_idx++)
			{
				JOFAJDPOEOB_list.Add(NBDMOIBEDFI_readData.GetEGMHEAOKLND(JOFAJDPOEOB_idx));
			}
			NBDMOIBEDFI_data.JOFAJDPOEOB = JOFAJDPOEOB_list.ToArray();

			NBDMOIBEDFI_data.DBHPPMPNCKF = NBDMOIBEDFI_readData.OILFLMOBFJM;
			NBDMOIBEDFI_data.BFCILBEICEN = NBDMOIBEDFI_readData.CMNENMNDDMO;
			NBDMOIBEDFI_list.Add(NBDMOIBEDFI_data);
		}
		res_data.NBDMOIBEDFI = NBDMOIBEDFI_list.ToArray();

		return res_data;
	}
}
