using FlatBuffers;
using System.Collections.Generic;

public class IHANOPGIKEO
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint EJPKFBHNDGI_ev_no { get; set; } // 0xC EMPIMMNPMJL BDKLEOCKELL JILBLBACAEL
	public uint GOBMACPDDCL_ev_id { get; set; } // 0x10 EKOLNCPJDPN ODBGFPGPPAC LIMKOCNLLPL
	public uint JBGEEPFKIGG_val { get; set; } // 0x14 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint DOOGFEGEKLG_max { get; set; } // 0x18 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public uint EMIJNAFJFJO_expir { get; set; } // 0x1C GBHMMAHHJGG GBGPKONOFGD KCFHLAFJJPJ
	public uint PLALNIIBLOF_en { get; set; } // 0x20 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x24 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
public class BOLCKDHHNDB
{
	public IHANOPGIKEO[] IIHHPGHEIIN { get; set; } // 0x8 AKOJOKBBNPK EICLLOMMNEL PCIILNEOKOP
	public static BOLCKDHHNDB HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x19CF110
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		ONCFNGIBLHO res_readData = ONCFNGIBLHO.GetRootAsONCFNGIBLHO(buffer);
		BOLCKDHHNDB res_data = new BOLCKDHHNDB();

		List<IHANOPGIKEO> IIHHPGHEIIN_list = new List<IHANOPGIKEO>();
		for(int IIHHPGHEIIN_idx = 0; IIHHPGHEIIN_idx < res_readData.KDGCIEMFIIMLength; IIHHPGHEIIN_idx++)
		{
			INFGGLDJAIF IIHHPGHEIIN_readData = res_readData.GetKDGCIEMFIIM(IIHHPGHEIIN_idx);
			IHANOPGIKEO IIHHPGHEIIN_data = new IHANOPGIKEO();

			IIHHPGHEIIN_data.PPFNGGCBJKC_id = IIHHPGHEIIN_readData.BBPHAPFBFHK;
			IIHHPGHEIIN_data.EJPKFBHNDGI_ev_no = IIHHPGHEIIN_readData.ONGGCPLNOFG;
			IIHHPGHEIIN_data.GOBMACPDDCL_ev_id = IIHHPGHEIIN_readData.BMACFCLAHFD;
			IIHHPGHEIIN_data.JBGEEPFKIGG_val = IIHHPGHEIIN_readData.KJFEBMBHKOC;
			IIHHPGHEIIN_data.DOOGFEGEKLG_max = IIHHPGHEIIN_readData.GEJGMBBCFEE;
			IIHHPGHEIIN_data.EMIJNAFJFJO_expir = IIHHPGHEIIN_readData.HHGNAFHNHEK;
			IIHHPGHEIIN_data.PLALNIIBLOF_en = IIHHPGHEIIN_readData.CFLMCGOJJJD;
			IIHHPGHEIIN_data.IJEKNCDIIAE_mver = IIHHPGHEIIN_readData.OFMGALJGDAO;
			IIHHPGHEIIN_list.Add(IIHHPGHEIIN_data);
		}
		res_data.IIHHPGHEIIN = IIHHPGHEIIN_list.ToArray();

		return res_data;
	}
}
