using FlatBuffers;
using System.Collections.Generic;

public class HMNCNMGCIMM
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD_RankingName { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public string[] MPCAGEPEJJJ_Key { get; set; } // 0x18 OINCEAPBAHC PLBHMKFJNPJ BCEIHFNLBIM
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x20 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x24 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x28 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x2C BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x30 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public int[] JHPCPNJJHLI_RankingThreshold { get; set; } // 0x34 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
}
public class KAGMCEBLHAI
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class KBHIGPCGLKH
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class CEGLELHPKBO
{
	public HMNCNMGCIMM HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public KAGMCEBLHAI[] BHGDNGHDDAC { get; set; } // 0xC JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public KBHIGPCGLKH[] MHGMDJNOLMI { get; set; } // 0x10 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static CEGLELHPKBO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x12B4F4C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		AIAIHLIBPLM res_readData = AIAIHLIBPLM.GetRootAsAIAIHLIBPLM(buffer);
		CEGLELHPKBO res_data = new CEGLELHPKBO();

		MPAKIJAPJIC HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		HMNCNMGCIMM HMBHNLCFDIH_data = new HMNCNMGCIMM();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD_RankingName = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		List<string> MPCAGEPEJJJ_list = new List<string>();
		for(int MPCAGEPEJJJ_idx = 0; MPCAGEPEJJJ_idx < HMBHNLCFDIH_readData.NLPMPPCENKDLength; MPCAGEPEJJJ_idx++)
		{
			MPCAGEPEJJJ_list.Add(HMBHNLCFDIH_readData.GetNLPMPPCENKD(MPCAGEPEJJJ_idx));
		}
		HMBHNLCFDIH_data.MPCAGEPEJJJ_Key = MPCAGEPEJJJ_list.ToArray();

		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI_RankingThreshold = JHPCPNJJHLI_list.ToArray();

		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<KAGMCEBLHAI> BHGDNGHDDAC_list = new List<KAGMCEBLHAI>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			DAIIOPHMNIM BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			KAGMCEBLHAI BHGDNGHDDAC_data = new KAGMCEBLHAI();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<KBHIGPCGLKH> MHGMDJNOLMI_list = new List<KBHIGPCGLKH>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			NNKOCPILBMP MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			KBHIGPCGLKH MHGMDJNOLMI_data = new KBHIGPCGLKH();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
