using FlatBuffers;
using System.Collections.Generic;

public class ADBHLCDDPHK
{
	public string OPFGFINHFCE { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint HPNOGLIFJOP { get; set; } // 0x20 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE { get; set; } // 0x24 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF { get; set; } // 0x28 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI { get; set; } // 0x2C BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH { get; set; } // 0x30 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JMJDLDEIFKE { get; set; } // 0x34 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO { get; set; } // 0x38 IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x3C AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public int[] EJBGHLOOLBC { get; set; } // 0x40 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
}
public class OEAFJBOBDHE
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NAABOMBLCMK
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class PDDHLCIJPOK
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int HMFFHLPNMPH { get; set; } // 0xC NKBFANLDLIL NJOGDDPICKG NBBGMMBICNA
	public string FEMMDNIELFC { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string MCNPILDHLEE { get; set; } // 0x14 MABNODDMLDE JLJJFLOEKDF HFBABDLDOGC
	public string OJHJLJLCKAC { get; set; } // 0x18 LNDPGHGEEFN JBJHIAENBBP MJCKEMJCGJI
	public int PNFGDBDNODC { get; set; } // 0x1C NHOJEHJEGJI PICLGMPHLKI KLKGPBGFMOP
	public int[] COCEIPAKJKF { get; set; } // 0x20 IJJHLKJKEMJ ANNLMIFAJJD IHBJBNPLFFA
	public int[] BFINGCJHOHI { get; set; } // 0x24 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public int KCGJGPOFOCD { get; set; } // 0x28 JANCADDFPKF CKFBDDKHAJO IPOBANBJJHB
}
public class POEILNNBDEE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KLCMKLPIDDJ { get; set; } // 0xC LBNFMGNGCDA FKGAMFACFKO MHLPBOBOFJA
	public int BAOFEFFADPD { get; set; } // 0x10 MNBJKHKHMCL KHNONKOPIPO LBJPPBMDOGE
	public int FKPEAGGKNLC { get; set; } // 0x14 KEJMMFJOGLF INKAILFPHPC JBHHCLEJMNL
	public int KOMKKBDABJP { get; set; } // 0x18 JPPMFGFLNGH MOMCBDJIGKO NECMHGINPDE
}
public class CEGMAIDIKLC
{
	public ADBHLCDDPHK HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public OEAFJBOBDHE[] BHGDNGHDDAC { get; set; } // 0xC JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public NAABOMBLCMK[] MHGMDJNOLMI { get; set; } // 0x10 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public PDDHLCIJPOK[] BNHMOENHDFB { get; set; } // 0x14 HGKKBJMAPNN NLKLLFOGFOM IPFIPKDJJIM
	public POEILNNBDEE[] MAHEBNDELHE { get; set; } // 0x18 KCFOCFGLPFA DDOJMMPHCBB FCJBMPGJIGL
	public static CEGMAIDIKLC HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x12B5AF4
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		EDNGOONFHEO res_readData = EDNGOONFHEO.GetRootAsEDNGOONFHEO(buffer);
		CEGMAIDIKLC res_data = new CEGMAIDIKLC();

		CLPHCGNHCGC HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		ADBHLCDDPHK HMBHNLCFDIH_data = new ADBHLCDDPHK();

		HMBHNLCFDIH_data.OPFGFINHFCE = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.HPNOGLIFJOP = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC = EJBGHLOOLBC_list.ToArray();

		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<OEAFJBOBDHE> BHGDNGHDDAC_list = new List<OEAFJBOBDHE>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			MBMMPMLDACB BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			OEAFJBOBDHE BHGDNGHDDAC_data = new OEAFJBOBDHE();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<NAABOMBLCMK> MHGMDJNOLMI_list = new List<NAABOMBLCMK>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			CLLJHAIJMHD MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			NAABOMBLCMK MHGMDJNOLMI_data = new NAABOMBLCMK();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<PDDHLCIJPOK> BNHMOENHDFB_list = new List<PDDHLCIJPOK>();
		for(int BNHMOENHDFB_idx = 0; BNHMOENHDFB_idx < res_readData.HHBHEKNMBHFLength; BNHMOENHDFB_idx++)
		{
			IONNGNNIKOG BNHMOENHDFB_readData = res_readData.GetHHBHEKNMBHF(BNHMOENHDFB_idx);
			PDDHLCIJPOK BNHMOENHDFB_data = new PDDHLCIJPOK();

			BNHMOENHDFB_data.PPFNGGCBJKC = BNHMOENHDFB_readData.BBPHAPFBFHK;
			BNHMOENHDFB_data.HMFFHLPNMPH = BNHMOENHDFB_readData.HFJLPAOGLEH;
			BNHMOENHDFB_data.FEMMDNIELFC = BNHMOENHDFB_readData.NNKLANONDOM;
			BNHMOENHDFB_data.MCNPILDHLEE = BNHMOENHDFB_readData.EPHHJONMFBP;
			BNHMOENHDFB_data.OJHJLJLCKAC = BNHMOENHDFB_readData.IIGJOMDOEDO;
			BNHMOENHDFB_data.PNFGDBDNODC = BNHMOENHDFB_readData.NHMKEMIMBML;
			List<int> COCEIPAKJKF_list = new List<int>();
			for(int COCEIPAKJKF_idx = 0; COCEIPAKJKF_idx < BNHMOENHDFB_readData.BJBNCHAIOHHLength; COCEIPAKJKF_idx++)
			{
				COCEIPAKJKF_list.Add(BNHMOENHDFB_readData.GetBJBNCHAIOHH(COCEIPAKJKF_idx));
			}
			BNHMOENHDFB_data.COCEIPAKJKF = COCEIPAKJKF_list.ToArray();

			List<int> BFINGCJHOHI_list = new List<int>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < BNHMOENHDFB_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(BNHMOENHDFB_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			BNHMOENHDFB_data.BFINGCJHOHI = BFINGCJHOHI_list.ToArray();

			BNHMOENHDFB_data.KCGJGPOFOCD = BNHMOENHDFB_readData.IBIAJNFJICN;
			BNHMOENHDFB_list.Add(BNHMOENHDFB_data);
		}
		res_data.BNHMOENHDFB = BNHMOENHDFB_list.ToArray();

		List<POEILNNBDEE> MAHEBNDELHE_list = new List<POEILNNBDEE>();
		for(int MAHEBNDELHE_idx = 0; MAHEBNDELHE_idx < res_readData.AAAINBAEOFDLength; MAHEBNDELHE_idx++)
		{
			PAEHJMNAOKB MAHEBNDELHE_readData = res_readData.GetAAAINBAEOFD(MAHEBNDELHE_idx);
			POEILNNBDEE MAHEBNDELHE_data = new POEILNNBDEE();

			MAHEBNDELHE_data.PPFNGGCBJKC = MAHEBNDELHE_readData.BBPHAPFBFHK;
			MAHEBNDELHE_data.KLCMKLPIDDJ = MAHEBNDELHE_readData.IALIGIAJJGP;
			MAHEBNDELHE_data.BAOFEFFADPD = MAHEBNDELHE_readData.FKGLOPMFMCP;
			MAHEBNDELHE_data.FKPEAGGKNLC = MAHEBNDELHE_readData.LAONNJLHPCF;
			MAHEBNDELHE_data.KOMKKBDABJP = MAHEBNDELHE_readData.BNDAHALMIPE;
			MAHEBNDELHE_list.Add(MAHEBNDELHE_data);
		}
		res_data.MAHEBNDELHE = MAHEBNDELHE_list.ToArray();

		return res_data;
	}
}
