using FlatBuffers;
using System.Collections.Generic;

public class DNNGNDOKKGA
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FBFLDFMFFOH { get; set; } // 0xC LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint DOOGFEGEKLG { get; set; } // 0x18 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
}
public class CHIHOOMFLNA
{
	public DNNGNDOKKGA[] KADBDHBKNMK { get; set; } // 0x8 OBKGMIFKBHP CGOCHNOHPGO PDJNADPCPCE
	public static CHIHOOMFLNA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x12C78B0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		AGKBCKADDKJ res_readData = AGKBCKADDKJ.GetRootAsAGKBCKADDKJ(buffer);
		CHIHOOMFLNA res_data = new CHIHOOMFLNA();

		List<DNNGNDOKKGA> KADBDHBKNMK_list = new List<DNNGNDOKKGA>();
		for(int KADBDHBKNMK_idx = 0; KADBDHBKNMK_idx < res_readData.AGCMBBANHPNLength; KADBDHBKNMK_idx++)
		{
			FKEPLHAEEBK KADBDHBKNMK_readData = res_readData.GetAGCMBBANHPN(KADBDHBKNMK_idx);
			DNNGNDOKKGA KADBDHBKNMK_data = new DNNGNDOKKGA();

			KADBDHBKNMK_data.PPFNGGCBJKC = KADBDHBKNMK_readData.BBPHAPFBFHK;
			KADBDHBKNMK_data.FBFLDFMFFOH = KADBDHBKNMK_readData.ODBPKGJPLMD;
			KADBDHBKNMK_data.JBGEEPFKIGG = KADBDHBKNMK_readData.KJFEBMBHKOC;
			KADBDHBKNMK_data.FPOMEEJFBIG = KADBDHBKNMK_readData.AEAKMMJLLDK;
			KADBDHBKNMK_data.DOOGFEGEKLG = KADBDHBKNMK_readData.GEJGMBBCFEE;
			KADBDHBKNMK_list.Add(KADBDHBKNMK_data);
		}
		res_data.KADBDHBKNMK = KADBDHBKNMK_list.ToArray();

		return res_data;
	}
}
