using FlatBuffers;
using System.Collections.Generic;

public class JBFGONALAMG
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int CBDOEDKIOJK_ev { get; set; } // 0x10 CENBLPHOLKK COMDLMJJFFN MJNJNAHIJCO
	public int MGPEOHKLOEP { get; set; } // 0x14 NIPOMPPPKNC AIMHKENDHJE CGBPBCBKICD
	public int LFAFFICDFMJ_Done { get; set; } // 0x18 JFPEKCBLODF ACFLKJFKHEM CNNAFLCILJD
	public int HANMDEBPBHG_pic { get; set; } // 0x1C IMDBPCNAOOE EFGGIMOPNMG PNGGKPFDKMA
	public string IPBHCLIHAPG_Msg { get; set; } // 0x20 PGDNLLBNAFF CBMCOGPJADM BAIGLALPKDE
	public string ADCMNODJBGJ_title { get; set; } // 0x24 PDOIKFFAKNG AJDDKABOOLK GHAHAGNIELN
	public int NHBLDIPBHNF_pg { get; set; } // 0x28 HEJBEEJPNPG HOMBHFADDNG FIEMLIDBMID
	public int GENGOHFLGLG { get; set; } // 0x2C ODDKKPMCKKF IHAADJGCAOC OHKAFBKODBF
	public int OAAMGLOGJNN { get; set; } // 0x30 NFPFLOEPMCP FEFFMEDIIAD LJKBOEIPEJK
	public int[] KPECMLFDLOI_pri { get; set; } // 0x34 CIGDCGJELBI ILFJIGDCGBK DOGEFDDMBDM
	public int HBDKKPIOFND { get; set; } // 0x38 OGKOJFHINBG ANFEBLIOIKL MHEGKAFIFEG
	public int PDMJBLLHICB { get; set; } // 0x3C ABHJIMGCKMN GOFNCLKNNCB IHOCNEBCIOB
	public int IJEKNCDIIAE_mver { get; set; } // 0x40 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
public class DGLENODDACE
{
	public JBFGONALAMG[] KCCHMPEPAII { get; set; } // 0x8 BAHLFKIMFPN BKKMAGLGBDH JONDKPCHJFL
	public static DGLENODDACE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1986248
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		BGECCLJCLID res_readData = BGECCLJCLID.GetRootAsBGECCLJCLID(buffer);
		DGLENODDACE res_data = new DGLENODDACE();

		List<JBFGONALAMG> KCCHMPEPAII_list = new List<JBFGONALAMG>();
		for(int KCCHMPEPAII_idx = 0; KCCHMPEPAII_idx < res_readData.GLOAIMAJLCMLength; KCCHMPEPAII_idx++)
		{
			HHBIKNLNLDF KCCHMPEPAII_readData = res_readData.GetGLOAIMAJLCM(KCCHMPEPAII_idx);
			JBFGONALAMG KCCHMPEPAII_data = new JBFGONALAMG();

			KCCHMPEPAII_data.PPFNGGCBJKC_id = KCCHMPEPAII_readData.BBPHAPFBFHK;
			KCCHMPEPAII_data.PLALNIIBLOF_en = KCCHMPEPAII_readData.CFLMCGOJJJD;
			KCCHMPEPAII_data.CBDOEDKIOJK_ev = KCCHMPEPAII_readData.AJBEKGHBAJO;
			KCCHMPEPAII_data.MGPEOHKLOEP = KCCHMPEPAII_readData.ALIHKGHHPMG;
			KCCHMPEPAII_data.LFAFFICDFMJ_Done = KCCHMPEPAII_readData.FCEKAHGHJHF;
			KCCHMPEPAII_data.HANMDEBPBHG_pic = KCCHMPEPAII_readData.BLJLFEDLAME;
			KCCHMPEPAII_data.IPBHCLIHAPG_Msg = KCCHMPEPAII_readData.IAHNDJDBCAJ;
			KCCHMPEPAII_data.ADCMNODJBGJ_title = KCCHMPEPAII_readData.AFJJKGBHFJP;
			KCCHMPEPAII_data.NHBLDIPBHNF_pg = KCCHMPEPAII_readData.LNCMMHCDOJE;
			KCCHMPEPAII_data.GENGOHFLGLG = KCCHMPEPAII_readData.CNEMDDAGABM;
			KCCHMPEPAII_data.OAAMGLOGJNN = KCCHMPEPAII_readData.NOGLKHEHLFA;
			List<int> KPECMLFDLOI_list = new List<int>();
			for(int KPECMLFDLOI_idx = 0; KPECMLFDLOI_idx < KCCHMPEPAII_readData.CLKFDBKPOPLLength; KPECMLFDLOI_idx++)
			{
				KPECMLFDLOI_list.Add(KCCHMPEPAII_readData.GetCLKFDBKPOPL(KPECMLFDLOI_idx));
			}
			KCCHMPEPAII_data.KPECMLFDLOI_pri = KPECMLFDLOI_list.ToArray();

			KCCHMPEPAII_data.HBDKKPIOFND = KCCHMPEPAII_readData.CPILHHGBKIH;
			KCCHMPEPAII_data.PDMJBLLHICB = KCCHMPEPAII_readData.OPBFBAKKDCI;
			KCCHMPEPAII_data.IJEKNCDIIAE_mver = KCCHMPEPAII_readData.OFMGALJGDAO;
			KCCHMPEPAII_list.Add(KCCHMPEPAII_data);
		}
		res_data.KCCHMPEPAII = KCCHMPEPAII_list.ToArray();

		return res_data;
	}
}
