using FlatBuffers;
using System.Collections.Generic;

public class LNFHEEBKPNL
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint FEFDGBPFKBJ_gid { get; set; } // 0x14 NBBEDGJCLDE BFIENFNOPIH INLGKGJPBCP
	public uint KOMKKBDABJP_end { get; set; } // 0x18 JPPMFGFLNGH MOMCBDJIGKO NECMHGINPDE
	public uint FOILNHKHHDF_pt { get; set; } // 0x1C LNNCNOIGMGM FOFBHPJDHFO LHPMDDKPJDP
	public uint[] CIOKHGPEEKE_sid { get; set; } // 0x20 BDJNNGOOPCO KICCFHPEGJC NNKLOCFCMOL
}
public class DNAMOAGODKD
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class MOGPEEGGGEC
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class DNKLFEPGGNC
{
	public LNFHEEBKPNL[] JFFLBNACFOH { get; set; } // 0x8 CGJILPEONDC IPLFONNHHCA JFHKHKPPHFN
	public DNAMOAGODKD[] BHGDNGHDDAC { get; set; } // 0xC JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public MOGPEEGGGEC[] MHGMDJNOLMI { get; set; } // 0x10 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static DNKLFEPGGNC HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1231FD8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		ACCMHHCLELG res_readData = ACCMHHCLELG.GetRootAsACCMHHCLELG(buffer);
		DNKLFEPGGNC res_data = new DNKLFEPGGNC();

		List<LNFHEEBKPNL> JFFLBNACFOH_list = new List<LNFHEEBKPNL>();
		for(int JFFLBNACFOH_idx = 0; JFFLBNACFOH_idx < res_readData.ODLAFHPCDECLength; JFFLBNACFOH_idx++)
		{
			JLIDEAHFDEA JFFLBNACFOH_readData = res_readData.GetODLAFHPCDEC(JFFLBNACFOH_idx);
			LNFHEEBKPNL JFFLBNACFOH_data = new LNFHEEBKPNL();

			JFFLBNACFOH_data.PPFNGGCBJKC_id = JFFLBNACFOH_readData.BBPHAPFBFHK;
			JFFLBNACFOH_data.IJEKNCDIIAE_mver = JFFLBNACFOH_readData.OFMGALJGDAO;
			JFFLBNACFOH_data.PLALNIIBLOF_en = JFFLBNACFOH_readData.CFLMCGOJJJD;
			JFFLBNACFOH_data.FEFDGBPFKBJ_gid = JFFLBNACFOH_readData.PBMIJLINDCG;
			JFFLBNACFOH_data.KOMKKBDABJP_end = JFFLBNACFOH_readData.BNDAHALMIPE;
			JFFLBNACFOH_data.FOILNHKHHDF_pt = JFFLBNACFOH_readData.HJNPKHJJDBB;
			List<uint> CIOKHGPEEKE_list = new List<uint>();
			for(int CIOKHGPEEKE_idx = 0; CIOKHGPEEKE_idx < JFFLBNACFOH_readData.PJLIIABPNFJLength; CIOKHGPEEKE_idx++)
			{
				CIOKHGPEEKE_list.Add(JFFLBNACFOH_readData.GetPJLIIABPNFJ(CIOKHGPEEKE_idx));
			}
			JFFLBNACFOH_data.CIOKHGPEEKE_sid = CIOKHGPEEKE_list.ToArray();

			JFFLBNACFOH_list.Add(JFFLBNACFOH_data);
		}
		res_data.JFFLBNACFOH = JFFLBNACFOH_list.ToArray();

		List<DNAMOAGODKD> BHGDNGHDDAC_list = new List<DNAMOAGODKD>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			CKMEIOAPABF BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			DNAMOAGODKD BHGDNGHDDAC_data = new DNAMOAGODKD();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<MOGPEEGGGEC> MHGMDJNOLMI_list = new List<MOGPEEGGGEC>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			BEHBIEJAFJL MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			MOGPEEGGGEC MHGMDJNOLMI_data = new MOGPEEGGGEC();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
