using FlatBuffers;
using System.Collections.Generic;

public class ILEKHFDFOEH
{
	public int CIOKHGPEEKE_sid { get; set; } // 0x8 BDJNNGOOPCO KICCFHPEGJC_get_sid NNKLOCFCMOL_set_sid
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public string IIPIPIABGDG_nam { get; set; } // 0x14 CPOHCOAOMDD DNKBBHGLGIA_get_nam MDMELENNABM_set_nam
	public int GBJFNGCDKPM_typ { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public int KNHOMNONOEB_AssetId { get; set; } // 0x1C EJNCFCPHDML NECFMEFKKPH_get_AssetId MHNEFLJACHA_set_AssetId
	public int IBAKPKKEDJM_month { get; set; } // 0x20 IDEJILEAOJM IJHAHFOOJKH_get_month LNKIOJGIKMB_set_month
	public int JPGALGPNJAI_VcId { get; set; } // 0x24 PDCNDDDLOJD GHFHDABMBCL_get_VcId AGNACDEALEO_set_VcId
	public int AHEFJKEICLM { get; set; } // 0x28 GPLOKHLAFBM KGAPLCDPPMF_get_ AHIGCACLOHF_set_
	public int PDBPFJJCADD_open_at { get; set; } // 0x2C PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public int FDBNFFNFOND_close_at { get; set; } // 0x30 INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
	public int GHNAPCBBEHH { get; set; } // 0x34 AMJIEFBCGLL MMECMKPAPHH_get_ KMOCJKFKEAC_set_
	public int EILKGEADKGH_Order { get; set; } // 0x38 PBIPJHCABED NPDDACIHBKD_get_Order BJJMCKHBPNH_set_Order
}
public class JPCFDBADANB
{
	public int MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int GHNAPCBBEHH { get; set; } // 0x14 AMJIEFBCGLL MMECMKPAPHH_get_ KMOCJKFKEAC_set_
	public int KMFLNILNPJD_Cnt { get; set; } // 0x18 BDNBFNKKEEL EJNACGPGJAI_get_Cnt PGAECLKCFEL_set_Cnt
	public int AHEFJKEICLM { get; set; } // 0x1C GPLOKHLAFBM KGAPLCDPPMF_get_ AHIGCACLOHF_set_
	public int PDBPFJJCADD_open_at { get; set; } // 0x20 PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public int FDBNFFNFOND_close_at { get; set; } // 0x24 INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
	public int EILKGEADKGH_Order { get; set; } // 0x28 PBIPJHCABED NPDDACIHBKD_get_Order BJJMCKHBPNH_set_Order
	public int JBFLEDKDFCO_cid { get; set; } // 0x2C JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public int DLCGAMHADEN_Label { get; set; } // 0x30 ANDDAFHKOPK BNGHEBJEOPL_get_Label PBMMAJFCPJL_set_Label
}
public class IPGOMEABJBG
{
	public int FEFDGBPFKBJ_gid { get; set; } // 0x8 NBBEDGJCLDE BFIENFNOPIH_get_gid INLGKGJPBCP_set_gid
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int AHEFJKEICLM { get; set; } // 0x14 GPLOKHLAFBM KGAPLCDPPMF_get_ AHIGCACLOHF_set_
	public int PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public int FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
}
public class KCAFKJHPMBD
{
	public int JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public int EENKMPGFAIC { get; set; } // 0xC GNADDGIBGPM HDCPOCMFMKH_get_ BGAONIOFMAN_set_
	public int NOMHGPEKHPF { get; set; } // 0x10 EAEEBLLJJKI HNDPHOOGDCC_get_ BEHMGKGCKHG_set_
	public int JKHDLPJHGBK { get; set; } // 0x14 EMJJGELNJLF BCABPKJPAHM_get_ DCMFMCDBBGC_set_
	public int NLIMHCILPFE_AfCount { get; set; } // 0x18 IOFDLJHJLBA FOFOIAHAOEN_get_AfCount OCKCIFAEHBL_set_AfCount
}
public class NHLGHMCNLML
{
	public int POFDDFCGEGP_Underscore { get; set; } // 0x8 PPPCLKHNCAN IMNKDCLKMEM_get_Underscore GKGJKCNDNLF_set_Underscore
	public int NNDBJGDFEEM_Min { get; set; } // 0xC CNDGBLDLDCC EHNOFMPHLFC_get_Min GCANPOPEKEE_set_Min
	public int DOOGFEGEKLG_max { get; set; } // 0x10 IKKMNBJGBJK AECMFIOFFJN_get_max NGOJJDOCIDG_set_max
	public int DMOPADCLBKD { get; set; } // 0x14 LJOCNKEHPKK GIMAABOHDFM_get_ JIKLBLIKEDM_set_
	public int GIPGIGDBFHL { get; set; } // 0x18 FOANNOHBIKD AGGIAGLPAEN_get_ FINGLHPGLAE_set_
}
public class OHFBGFGCHFF
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class EBLAAOGMLIJ
{
	public ILEKHFDFOEH[] IGEOPMBHHAM { get; set; } // 0x8 DLAFGEMIHNA JIECMBMPNJF_get_ CJLJJEHIBFP_set_
	public JPCFDBADANB[] LLACOLKBNOH { get; set; } // 0xC FOIACKEHFEG FGAOFLGACJP_get_ FDJBCLONELI_set_
	public IPGOMEABJBG[] HBKOMBJJBIG { get; set; } // 0x10 HNIKCGOILAG JMFHMJMGCDG_get_ AMBDFGBJHJO_set_
	public KCAFKJHPMBD[] FOGEDIJHNMB { get; set; } // 0x14 FPODBBLOMFM KCDPGHELLBL_get_ AEGNDGJIACD_set_
	public NHLGHMCNLML[] JPDDILNAKPH { get; set; } // 0x18 MFOPOPFKJLE FOLCFGPJMFB_get_ MBBAFPMFNJJ_set_
	public OHFBGFGCHFF[] BHGDNGHDDAC { get; set; } // 0x1C JHDNDHBDFFI CEHHJMMMCID_get_ EDOEOHENKDG_set_
	public static EBLAAOGMLIJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x14FE494
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		DFHBOFFBKDB res_readData_ = DFHBOFFBKDB.GetRootAsDFHBOFFBKDB(buffer);
		EBLAAOGMLIJ res_data_ = new EBLAAOGMLIJ();

		List<ILEKHFDFOEH> IGEOPMBHHAM_list_ = new List<ILEKHFDFOEH>();
		for(int IGEOPMBHHAM_idx_ = 0; IGEOPMBHHAM_idx_ < res_readData_.EJKKOPBPJBNLength; IGEOPMBHHAM_idx_++)
		{
			JOGLEFDCEJI IGEOPMBHHAM_readData_ = res_readData_.GetEJKKOPBPJBN(IGEOPMBHHAM_idx_);
			ILEKHFDFOEH IGEOPMBHHAM_data_ = new ILEKHFDFOEH();

			IGEOPMBHHAM_data_.CIOKHGPEEKE_sid = IGEOPMBHHAM_readData_.CKMMECCALPI/*_sid*/;
			IGEOPMBHHAM_data_.IJEKNCDIIAE_mver = IGEOPMBHHAM_readData_.OFMGALJGDAO/*_mver*/;
			IGEOPMBHHAM_data_.PLALNIIBLOF_en = IGEOPMBHHAM_readData_.CFLMCGOJJJD/*_en*/;
			IGEOPMBHHAM_data_.IIPIPIABGDG_nam = IGEOPMBHHAM_readData_.CLGDAMPNKAA/*_nam*/;
			IGEOPMBHHAM_data_.GBJFNGCDKPM_typ = IGEOPMBHHAM_readData_.LPJPOOHJKAE/*_typ*/;
			IGEOPMBHHAM_data_.KNHOMNONOEB_AssetId = IGEOPMBHHAM_readData_.NCADHENBLDB/*_AssetId*/;
			IGEOPMBHHAM_data_.IBAKPKKEDJM_month = IGEOPMBHHAM_readData_.CLGHAEBNGCF/*_month*/;
			IGEOPMBHHAM_data_.JPGALGPNJAI_VcId = IGEOPMBHHAM_readData_.KCCGHBAOJEN/*_VcId*/;
			IGEOPMBHHAM_data_.AHEFJKEICLM = IGEOPMBHHAM_readData_.HAHMOLPJPCG;
			IGEOPMBHHAM_data_.PDBPFJJCADD_open_at = IGEOPMBHHAM_readData_.NJLJEKDBPCH/*_open_at*/;
			IGEOPMBHHAM_data_.FDBNFFNFOND_close_at = IGEOPMBHHAM_readData_.MAOAGDBDBIB/*_close_at*/;
			IGEOPMBHHAM_data_.GHNAPCBBEHH = IGEOPMBHHAM_readData_.JAOFIDGEIGE;
			IGEOPMBHHAM_data_.EILKGEADKGH_Order = IGEOPMBHHAM_readData_.BPMBFFDNMDD/*_Order*/;
			IGEOPMBHHAM_list_.Add(IGEOPMBHHAM_data_);
		}
		res_data_.IGEOPMBHHAM = IGEOPMBHHAM_list_.ToArray();

		List<JPCFDBADANB> LLACOLKBNOH_list_ = new List<JPCFDBADANB>();
		for(int LLACOLKBNOH_idx_ = 0; LLACOLKBNOH_idx_ < res_readData_.MDFKCCMFFFDLength; LLACOLKBNOH_idx_++)
		{
			JIMFBCIKKKJ LLACOLKBNOH_readData_ = res_readData_.GetMDFKCCMFFFD(LLACOLKBNOH_idx_);
			JPCFDBADANB LLACOLKBNOH_data_ = new JPCFDBADANB();

			LLACOLKBNOH_data_.MJMPANIBFED_pid = LLACOLKBNOH_readData_.COPFAKAHEMN/*_pid*/;
			LLACOLKBNOH_data_.IJEKNCDIIAE_mver = LLACOLKBNOH_readData_.OFMGALJGDAO/*_mver*/;
			LLACOLKBNOH_data_.PLALNIIBLOF_en = LLACOLKBNOH_readData_.CFLMCGOJJJD/*_en*/;
			LLACOLKBNOH_data_.GHNAPCBBEHH = LLACOLKBNOH_readData_.JAOFIDGEIGE;
			LLACOLKBNOH_data_.KMFLNILNPJD_Cnt = LLACOLKBNOH_readData_.FHHFICHAABG/*_Cnt*/;
			LLACOLKBNOH_data_.AHEFJKEICLM = LLACOLKBNOH_readData_.HAHMOLPJPCG;
			LLACOLKBNOH_data_.PDBPFJJCADD_open_at = LLACOLKBNOH_readData_.NJLJEKDBPCH/*_open_at*/;
			LLACOLKBNOH_data_.FDBNFFNFOND_close_at = LLACOLKBNOH_readData_.MAOAGDBDBIB/*_close_at*/;
			LLACOLKBNOH_data_.EILKGEADKGH_Order = LLACOLKBNOH_readData_.BPMBFFDNMDD/*_Order*/;
			LLACOLKBNOH_data_.JBFLEDKDFCO_cid = LLACOLKBNOH_readData_.HOENDPOGFIO/*_cid*/;
			LLACOLKBNOH_data_.DLCGAMHADEN_Label = LLACOLKBNOH_readData_.PELKLPGCMFN/*_Label*/;
			LLACOLKBNOH_list_.Add(LLACOLKBNOH_data_);
		}
		res_data_.LLACOLKBNOH = LLACOLKBNOH_list_.ToArray();

		List<IPGOMEABJBG> HBKOMBJJBIG_list_ = new List<IPGOMEABJBG>();
		for(int HBKOMBJJBIG_idx_ = 0; HBKOMBJJBIG_idx_ < res_readData_.MHOEKDECGGNLength; HBKOMBJJBIG_idx_++)
		{
			OLMJGOPCIKK HBKOMBJJBIG_readData_ = res_readData_.GetMHOEKDECGGN(HBKOMBJJBIG_idx_);
			IPGOMEABJBG HBKOMBJJBIG_data_ = new IPGOMEABJBG();

			HBKOMBJJBIG_data_.FEFDGBPFKBJ_gid = HBKOMBJJBIG_readData_.PBMIJLINDCG/*_gid*/;
			HBKOMBJJBIG_data_.IJEKNCDIIAE_mver = HBKOMBJJBIG_readData_.OFMGALJGDAO/*_mver*/;
			HBKOMBJJBIG_data_.PLALNIIBLOF_en = HBKOMBJJBIG_readData_.CFLMCGOJJJD/*_en*/;
			HBKOMBJJBIG_data_.AHEFJKEICLM = HBKOMBJJBIG_readData_.HAHMOLPJPCG;
			HBKOMBJJBIG_data_.PDBPFJJCADD_open_at = HBKOMBJJBIG_readData_.NJLJEKDBPCH/*_open_at*/;
			HBKOMBJJBIG_data_.FDBNFFNFOND_close_at = HBKOMBJJBIG_readData_.MAOAGDBDBIB/*_close_at*/;
			HBKOMBJJBIG_list_.Add(HBKOMBJJBIG_data_);
		}
		res_data_.HBKOMBJJBIG = HBKOMBJJBIG_list_.ToArray();

		List<KCAFKJHPMBD> FOGEDIJHNMB_list_ = new List<KCAFKJHPMBD>();
		for(int FOGEDIJHNMB_idx_ = 0; FOGEDIJHNMB_idx_ < res_readData_.PCHLJEFOEFLLength; FOGEDIJHNMB_idx_++)
		{
			FFAOJIELJAC FOGEDIJHNMB_readData_ = res_readData_.GetPCHLJEFOEFL(FOGEDIJHNMB_idx_);
			KCAFKJHPMBD FOGEDIJHNMB_data_ = new KCAFKJHPMBD();

			FOGEDIJHNMB_data_.JBFLEDKDFCO_cid = FOGEDIJHNMB_readData_.HOENDPOGFIO/*_cid*/;
			FOGEDIJHNMB_data_.EENKMPGFAIC = FOGEDIJHNMB_readData_.IPIEGLDLJOL;
			FOGEDIJHNMB_data_.NOMHGPEKHPF = FOGEDIJHNMB_readData_.EABFGANHEEH;
			FOGEDIJHNMB_data_.JKHDLPJHGBK = FOGEDIJHNMB_readData_.FLCMINFEBOP;
			FOGEDIJHNMB_data_.NLIMHCILPFE_AfCount = FOGEDIJHNMB_readData_.OJLCLDJEPDL/*_AfCount*/;
			FOGEDIJHNMB_list_.Add(FOGEDIJHNMB_data_);
		}
		res_data_.FOGEDIJHNMB = FOGEDIJHNMB_list_.ToArray();

		List<NHLGHMCNLML> JPDDILNAKPH_list_ = new List<NHLGHMCNLML>();
		for(int JPDDILNAKPH_idx_ = 0; JPDDILNAKPH_idx_ < res_readData_.JKFLLEHIMLLLength; JPDDILNAKPH_idx_++)
		{
			CJLNKNELECA JPDDILNAKPH_readData_ = res_readData_.GetJKFLLEHIMLL(JPDDILNAKPH_idx_);
			NHLGHMCNLML JPDDILNAKPH_data_ = new NHLGHMCNLML();

			JPDDILNAKPH_data_.POFDDFCGEGP_Underscore = JPDDILNAKPH_readData_.ILGBFGPGNGL/*_Underscore*/;
			JPDDILNAKPH_data_.NNDBJGDFEEM_Min = JPDDILNAKPH_readData_.CCIHMCAPHCB/*_Min*/;
			JPDDILNAKPH_data_.DOOGFEGEKLG_max = JPDDILNAKPH_readData_.GEJGMBBCFEE/*_max*/;
			JPDDILNAKPH_data_.DMOPADCLBKD = JPDDILNAKPH_readData_.NOFLCNIGNEG;
			JPDDILNAKPH_data_.GIPGIGDBFHL = JPDDILNAKPH_readData_.PHOBAICLCKE;
			JPDDILNAKPH_list_.Add(JPDDILNAKPH_data_);
		}
		res_data_.JPDDILNAKPH = JPDDILNAKPH_list_.ToArray();

		List<OHFBGFGCHFF> BHGDNGHDDAC_list_ = new List<OHFBGFGCHFF>();
		for(int BHGDNGHDDAC_idx_ = 0; BHGDNGHDDAC_idx_ < res_readData_.NJJINHMIOHNLength; BHGDNGHDDAC_idx_++)
		{
			NOAPHCIKEID BHGDNGHDDAC_readData_ = res_readData_.GetNJJINHMIOHN(BHGDNGHDDAC_idx_);
			OHFBGFGCHFF BHGDNGHDDAC_data_ = new OHFBGFGCHFF();

			BHGDNGHDDAC_data_.LJNAKDMILMC_key = BHGDNGHDDAC_readData_.AGOIMGHMGOH/*_key*/;
			BHGDNGHDDAC_data_.JBGEEPFKIGG_val = BHGDNGHDDAC_readData_.KJFEBMBHKOC/*_val*/;
			BHGDNGHDDAC_list_.Add(BHGDNGHDDAC_data_);
		}
		res_data_.BHGDNGHDDAC = BHGDNGHDDAC_list_.ToArray();

		return res_data_;
	}
}
