using FlatBuffers;
using System.Collections.Generic;

public class ILEKHFDFOEH
{
	public int CIOKHGPEEKE { get; set; } // 0x8 BDJNNGOOPCO KICCFHPEGJC NNKLOCFCMOL
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string IIPIPIABGDG { get; set; } // 0x14 CPOHCOAOMDD DNKBBHGLGIA MDMELENNABM
	public int GBJFNGCDKPM { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int KNHOMNONOEB { get; set; } // 0x1C EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
	public int IBAKPKKEDJM { get; set; } // 0x20 IDEJILEAOJM IJHAHFOOJKH LNKIOJGIKMB
	public int JPGALGPNJAI { get; set; } // 0x24 PDCNDDDLOJD GHFHDABMBCL AGNACDEALEO
	public int AHEFJKEICLM { get; set; } // 0x28 GPLOKHLAFBM KGAPLCDPPMF AHIGCACLOHF
	public int PDBPFJJCADD { get; set; } // 0x2C PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x30 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public int GHNAPCBBEHH { get; set; } // 0x34 AMJIEFBCGLL MMECMKPAPHH KMOCJKFKEAC
	public int EILKGEADKGH { get; set; } // 0x38 PBIPJHCABED NPDDACIHBKD BJJMCKHBPNH
}
public class JPCFDBADANB
{
	public int MJMPANIBFED { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int GHNAPCBBEHH { get; set; } // 0x14 AMJIEFBCGLL MMECMKPAPHH KMOCJKFKEAC
	public int KMFLNILNPJD { get; set; } // 0x18 BDNBFNKKEEL EJNACGPGJAI PGAECLKCFEL
	public int AHEFJKEICLM { get; set; } // 0x1C GPLOKHLAFBM KGAPLCDPPMF AHIGCACLOHF
	public int PDBPFJJCADD { get; set; } // 0x20 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x24 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public int EILKGEADKGH { get; set; } // 0x28 PBIPJHCABED NPDDACIHBKD BJJMCKHBPNH
	public int JBFLEDKDFCO { get; set; } // 0x2C JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public int DLCGAMHADEN { get; set; } // 0x30 ANDDAFHKOPK BNGHEBJEOPL PBMMAJFCPJL
}
public class IPGOMEABJBG
{
	public int FEFDGBPFKBJ { get; set; } // 0x8 NBBEDGJCLDE BFIENFNOPIH INLGKGJPBCP
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int AHEFJKEICLM { get; set; } // 0x14 GPLOKHLAFBM KGAPLCDPPMF AHIGCACLOHF
	public int PDBPFJJCADD { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class KCAFKJHPMBD
{
	public int JBFLEDKDFCO { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public int EENKMPGFAIC { get; set; } // 0xC GNADDGIBGPM HDCPOCMFMKH BGAONIOFMAN
	public int NOMHGPEKHPF { get; set; } // 0x10 EAEEBLLJJKI HNDPHOOGDCC BEHMGKGCKHG
	public int JKHDLPJHGBK { get; set; } // 0x14 EMJJGELNJLF BCABPKJPAHM DCMFMCDBBGC
	public int NLIMHCILPFE { get; set; } // 0x18 IOFDLJHJLBA FOFOIAHAOEN OCKCIFAEHBL
}
public class NHLGHMCNLML
{
	public int POFDDFCGEGP { get; set; } // 0x8 PPPCLKHNCAN IMNKDCLKMEM GKGJKCNDNLF
	public int NNDBJGDFEEM { get; set; } // 0xC CNDGBLDLDCC EHNOFMPHLFC GCANPOPEKEE
	public int DOOGFEGEKLG { get; set; } // 0x10 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public int DMOPADCLBKD { get; set; } // 0x14 LJOCNKEHPKK GIMAABOHDFM JIKLBLIKEDM
	public int GIPGIGDBFHL { get; set; } // 0x18 FOANNOHBIKD AGGIAGLPAEN FINGLHPGLAE
}
public class OHFBGFGCHFF
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class EBLAAOGMLIJ
{
	public ILEKHFDFOEH[] IGEOPMBHHAM { get; set; } // 0x8 DLAFGEMIHNA JIECMBMPNJF CJLJJEHIBFP
	public JPCFDBADANB[] LLACOLKBNOH { get; set; } // 0xC FOIACKEHFEG FGAOFLGACJP FDJBCLONELI
	public IPGOMEABJBG[] HBKOMBJJBIG { get; set; } // 0x10 HNIKCGOILAG JMFHMJMGCDG AMBDFGBJHJO
	public KCAFKJHPMBD[] FOGEDIJHNMB { get; set; } // 0x14 FPODBBLOMFM KCDPGHELLBL AEGNDGJIACD
	public NHLGHMCNLML[] JPDDILNAKPH { get; set; } // 0x18 MFOPOPFKJLE FOLCFGPJMFB MBBAFPMFNJJ
	public OHFBGFGCHFF[] BHGDNGHDDAC { get; set; } // 0x1C JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public static EBLAAOGMLIJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x14FE494
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		DFHBOFFBKDB res_readData = DFHBOFFBKDB.GetRootAsDFHBOFFBKDB(buffer);
		EBLAAOGMLIJ res_data = new EBLAAOGMLIJ();

		List<ILEKHFDFOEH> IGEOPMBHHAM_list = new List<ILEKHFDFOEH>();
		for(int IGEOPMBHHAM_idx = 0; IGEOPMBHHAM_idx < res_readData.EJKKOPBPJBNLength; IGEOPMBHHAM_idx++)
		{
			JOGLEFDCEJI IGEOPMBHHAM_readData = res_readData.GetEJKKOPBPJBN(IGEOPMBHHAM_idx);
			ILEKHFDFOEH IGEOPMBHHAM_data = new ILEKHFDFOEH();

			IGEOPMBHHAM_data.CIOKHGPEEKE = IGEOPMBHHAM_readData.CKMMECCALPI;
			IGEOPMBHHAM_data.IJEKNCDIIAE = IGEOPMBHHAM_readData.OFMGALJGDAO;
			IGEOPMBHHAM_data.PLALNIIBLOF = IGEOPMBHHAM_readData.CFLMCGOJJJD;
			IGEOPMBHHAM_data.IIPIPIABGDG = IGEOPMBHHAM_readData.CLGDAMPNKAA;
			IGEOPMBHHAM_data.GBJFNGCDKPM = IGEOPMBHHAM_readData.LPJPOOHJKAE;
			IGEOPMBHHAM_data.KNHOMNONOEB = IGEOPMBHHAM_readData.NCADHENBLDB;
			IGEOPMBHHAM_data.IBAKPKKEDJM = IGEOPMBHHAM_readData.CLGHAEBNGCF;
			IGEOPMBHHAM_data.JPGALGPNJAI = IGEOPMBHHAM_readData.KCCGHBAOJEN;
			IGEOPMBHHAM_data.AHEFJKEICLM = IGEOPMBHHAM_readData.HAHMOLPJPCG;
			IGEOPMBHHAM_data.PDBPFJJCADD = IGEOPMBHHAM_readData.NJLJEKDBPCH;
			IGEOPMBHHAM_data.FDBNFFNFOND = IGEOPMBHHAM_readData.MAOAGDBDBIB;
			IGEOPMBHHAM_data.GHNAPCBBEHH = IGEOPMBHHAM_readData.JAOFIDGEIGE;
			IGEOPMBHHAM_data.EILKGEADKGH = IGEOPMBHHAM_readData.BPMBFFDNMDD;
			IGEOPMBHHAM_list.Add(IGEOPMBHHAM_data);
		}
		res_data.IGEOPMBHHAM = IGEOPMBHHAM_list.ToArray();

		List<JPCFDBADANB> LLACOLKBNOH_list = new List<JPCFDBADANB>();
		for(int LLACOLKBNOH_idx = 0; LLACOLKBNOH_idx < res_readData.MDFKCCMFFFDLength; LLACOLKBNOH_idx++)
		{
			JIMFBCIKKKJ LLACOLKBNOH_readData = res_readData.GetMDFKCCMFFFD(LLACOLKBNOH_idx);
			JPCFDBADANB LLACOLKBNOH_data = new JPCFDBADANB();

			LLACOLKBNOH_data.MJMPANIBFED = LLACOLKBNOH_readData.COPFAKAHEMN;
			LLACOLKBNOH_data.IJEKNCDIIAE = LLACOLKBNOH_readData.OFMGALJGDAO;
			LLACOLKBNOH_data.PLALNIIBLOF = LLACOLKBNOH_readData.CFLMCGOJJJD;
			LLACOLKBNOH_data.GHNAPCBBEHH = LLACOLKBNOH_readData.JAOFIDGEIGE;
			LLACOLKBNOH_data.KMFLNILNPJD = LLACOLKBNOH_readData.FHHFICHAABG;
			LLACOLKBNOH_data.AHEFJKEICLM = LLACOLKBNOH_readData.HAHMOLPJPCG;
			LLACOLKBNOH_data.PDBPFJJCADD = LLACOLKBNOH_readData.NJLJEKDBPCH;
			LLACOLKBNOH_data.FDBNFFNFOND = LLACOLKBNOH_readData.MAOAGDBDBIB;
			LLACOLKBNOH_data.EILKGEADKGH = LLACOLKBNOH_readData.BPMBFFDNMDD;
			LLACOLKBNOH_data.JBFLEDKDFCO = LLACOLKBNOH_readData.HOENDPOGFIO;
			LLACOLKBNOH_data.DLCGAMHADEN = LLACOLKBNOH_readData.PELKLPGCMFN;
			LLACOLKBNOH_list.Add(LLACOLKBNOH_data);
		}
		res_data.LLACOLKBNOH = LLACOLKBNOH_list.ToArray();

		List<IPGOMEABJBG> HBKOMBJJBIG_list = new List<IPGOMEABJBG>();
		for(int HBKOMBJJBIG_idx = 0; HBKOMBJJBIG_idx < res_readData.MHOEKDECGGNLength; HBKOMBJJBIG_idx++)
		{
			OLMJGOPCIKK HBKOMBJJBIG_readData = res_readData.GetMHOEKDECGGN(HBKOMBJJBIG_idx);
			IPGOMEABJBG HBKOMBJJBIG_data = new IPGOMEABJBG();

			HBKOMBJJBIG_data.FEFDGBPFKBJ = HBKOMBJJBIG_readData.PBMIJLINDCG;
			HBKOMBJJBIG_data.IJEKNCDIIAE = HBKOMBJJBIG_readData.OFMGALJGDAO;
			HBKOMBJJBIG_data.PLALNIIBLOF = HBKOMBJJBIG_readData.CFLMCGOJJJD;
			HBKOMBJJBIG_data.AHEFJKEICLM = HBKOMBJJBIG_readData.HAHMOLPJPCG;
			HBKOMBJJBIG_data.PDBPFJJCADD = HBKOMBJJBIG_readData.NJLJEKDBPCH;
			HBKOMBJJBIG_data.FDBNFFNFOND = HBKOMBJJBIG_readData.MAOAGDBDBIB;
			HBKOMBJJBIG_list.Add(HBKOMBJJBIG_data);
		}
		res_data.HBKOMBJJBIG = HBKOMBJJBIG_list.ToArray();

		List<KCAFKJHPMBD> FOGEDIJHNMB_list = new List<KCAFKJHPMBD>();
		for(int FOGEDIJHNMB_idx = 0; FOGEDIJHNMB_idx < res_readData.PCHLJEFOEFLLength; FOGEDIJHNMB_idx++)
		{
			FFAOJIELJAC FOGEDIJHNMB_readData = res_readData.GetPCHLJEFOEFL(FOGEDIJHNMB_idx);
			KCAFKJHPMBD FOGEDIJHNMB_data = new KCAFKJHPMBD();

			FOGEDIJHNMB_data.JBFLEDKDFCO = FOGEDIJHNMB_readData.HOENDPOGFIO;
			FOGEDIJHNMB_data.EENKMPGFAIC = FOGEDIJHNMB_readData.IPIEGLDLJOL;
			FOGEDIJHNMB_data.NOMHGPEKHPF = FOGEDIJHNMB_readData.EABFGANHEEH;
			FOGEDIJHNMB_data.JKHDLPJHGBK = FOGEDIJHNMB_readData.FLCMINFEBOP;
			FOGEDIJHNMB_data.NLIMHCILPFE = FOGEDIJHNMB_readData.OJLCLDJEPDL;
			FOGEDIJHNMB_list.Add(FOGEDIJHNMB_data);
		}
		res_data.FOGEDIJHNMB = FOGEDIJHNMB_list.ToArray();

		List<NHLGHMCNLML> JPDDILNAKPH_list = new List<NHLGHMCNLML>();
		for(int JPDDILNAKPH_idx = 0; JPDDILNAKPH_idx < res_readData.JKFLLEHIMLLLength; JPDDILNAKPH_idx++)
		{
			CJLNKNELECA JPDDILNAKPH_readData = res_readData.GetJKFLLEHIMLL(JPDDILNAKPH_idx);
			NHLGHMCNLML JPDDILNAKPH_data = new NHLGHMCNLML();

			JPDDILNAKPH_data.POFDDFCGEGP = JPDDILNAKPH_readData.ILGBFGPGNGL;
			JPDDILNAKPH_data.NNDBJGDFEEM = JPDDILNAKPH_readData.CCIHMCAPHCB;
			JPDDILNAKPH_data.DOOGFEGEKLG = JPDDILNAKPH_readData.GEJGMBBCFEE;
			JPDDILNAKPH_data.DMOPADCLBKD = JPDDILNAKPH_readData.NOFLCNIGNEG;
			JPDDILNAKPH_data.GIPGIGDBFHL = JPDDILNAKPH_readData.PHOBAICLCKE;
			JPDDILNAKPH_list.Add(JPDDILNAKPH_data);
		}
		res_data.JPDDILNAKPH = JPDDILNAKPH_list.ToArray();

		List<OHFBGFGCHFF> BHGDNGHDDAC_list = new List<OHFBGFGCHFF>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			NOAPHCIKEID BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			OHFBGFGCHFF BHGDNGHDDAC_data = new OHFBGFGCHFF();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		return res_data;
	}
}
