using FlatBuffers;
using System.Collections.Generic;

public class MPEFMPPMBGM
{
	public uint GLCLFMGPMAN { get; set; } // 0x8 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int FPLEBCKDCBE { get; set; } // 0xC BJHAJOOCEPM GMAGDACFGJF BNOJHOABBFC
	public int MDLMHEDHPHA { get; set; } // 0x10 NIBANBEBJBP HBELOEOGKNM APHNMFBNLBJ
	public uint NEGMFBPNJGK { get; set; } // 0x14 EKOPFGHKAEB AGBGLCMJIIL PDPBJNLLAID
	public uint DAPGDCPDCNA { get; set; } // 0x18 AIEPLCMPKAN GFAHOLGECII KJKCIHEDEBB
	public uint BEJGNPAAKNB { get; set; } // 0x1C MNDBPPIDDEG PPHPHCADCLJ BPMLEPPPCKP
	public uint OPAHFDJPFJO { get; set; } // 0x20 EIPKOACLOPK AFIMAHKLGJH OELIAPKHFKE
}
public class FFHDKFPLLEN
{
	public MPEFMPPMBGM[] HMPJFEFCGHI { get; set; } // 0x8 JDFLNCKOEIJ JIJDJPPJJKH PECPJANFJCM
	public static FFHDKFPLLEN HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x14DC914
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OJJJPOGDHKM res_readData = OJJJPOGDHKM.GetRootAsOJJJPOGDHKM(buffer);
		FFHDKFPLLEN res_data = new FFHDKFPLLEN();

		List<MPEFMPPMBGM> HMPJFEFCGHI_list = new List<MPEFMPPMBGM>();
		for(int HMPJFEFCGHI_idx = 0; HMPJFEFCGHI_idx < res_readData.BKJJHPCJDMJLength; HMPJFEFCGHI_idx++)
		{
			CJBNLNDKLKA HMPJFEFCGHI_readData = res_readData.GetBKJJHPCJDMJ(HMPJFEFCGHI_idx);
			MPEFMPPMBGM HMPJFEFCGHI_data = new MPEFMPPMBGM();

			HMPJFEFCGHI_data.GLCLFMGPMAN = HMPJFEFCGHI_readData.MBBJMJAAODG;
			HMPJFEFCGHI_data.FPLEBCKDCBE = HMPJFEFCGHI_readData.CFCGMIMJKLE;
			HMPJFEFCGHI_data.MDLMHEDHPHA = HMPJFEFCGHI_readData.OFGPIPFIPKB;
			HMPJFEFCGHI_data.NEGMFBPNJGK = HMPJFEFCGHI_readData.LHABMCKNLFG;
			HMPJFEFCGHI_data.DAPGDCPDCNA = HMPJFEFCGHI_readData.AIIPAPCLGGO;
			HMPJFEFCGHI_data.BEJGNPAAKNB = HMPJFEFCGHI_readData.ACHLKLEIOJJ;
			HMPJFEFCGHI_data.OPAHFDJPFJO = HMPJFEFCGHI_readData.GGIDBEGABBO;
			HMPJFEFCGHI_list.Add(HMPJFEFCGHI_data);
		}
		res_data.HMPJFEFCGHI = HMPJFEFCGHI_list.ToArray();

		return res_data;
	}
}
