using FlatBuffers;
using System.Collections.Generic;

public class PKDAOHIIJMM
{
	public uint DDMENKOHCGM_aid { get; set; } // 0x8 PFIGOIDGEDB NHEMDKLCIOG_get_aid NMEAJIJAGHD_set_aid
	public uint MIKCFEHGNJB_dt { get; set; } // 0xC HGBGPCILGLM PPCHCNBHAAG_get_dt DKKLANMGOIF_set_dt
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x10 JKDMAFHPKDJ DHOGDENEIOI_get_dv DBDFNFLGDFN_set_dv
	public uint HIMIDIJIGJN_et { get; set; } // 0x14 JJINNLAMGLL BHEAPFFMJOB_get_et KFAFHOOLEGI_set_et
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x18 CENBLPHOLKK COMDLMJJFFN_get_ev MJNJNAHIJCO_set_ev
	public uint LFOHDJJHLJE { get; set; } // 0x1C MENEEGHPGDC JCNLPBLGDMK_get_ EECCBENKDPG_set_
	public uint[] JMAGFEENOED_dv2 { get; set; } // 0x20 GLKLOAGDFDK GDPLEDJGNJO_get_dv2 GGLKCLOJNBP_set_dv2
	public uint NDIOEOHDMLJ { get; set; } // 0x24 CADLEMLEPEL NEMGKAJDGBO_get_ JONFEFDFDEN_set_
	public uint[] JNNFFAEFGOC { get; set; } // 0x28 KPKIGBKGLNG FGKCMNIMKND_get_ IPBHJDBFGNE_set_
	public uint PLMHOKJIPJK_lin { get; set; } // 0x2C CLFBLFMHBMG POGIHHKNLNH_get_lin BPBHIDPPLAJ_set_lin
	public uint INANEEGAEEG { get; set; } // 0x30 CKPKJEJMACE GAEPJHACPBA_get_ FGPHIHOOEGP_set_
	public uint HEOLEHDFLJO_ico { get; set; } // 0x34 EALEFNJMEPK OICOCHBFNAK_get_ico HGLFJJHECGH_set_ico
	public uint AOELPHMDDND { get; set; } // 0x38 JCLLKBKEIHP PFHADHPFLMP_get_ LJPGAFOEAMA_set_
	public uint KPECMLFDLOI_pri { get; set; } // 0x3C CIGDCGJELBI ILFJIGDCGBK_get_pri DOGEFDDMBDM_set_pri
	public uint GAMODHFMOMK { get; set; } // 0x40 ACHOGBEJIAH PLKDHENBGAF_get_ KIPFAMBAGBE_set_
}
public class OEBKKEFIOEB
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH_get_tgt MEHEHNALGIH_set_tgt
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF_get_v1 LFGKAMKBDGA_set_v1
	public int BBFKKANELFP_EffectType { get; set; } // 0x1C NOLHNEKFBOP OEGMCIENPLC_get_EffectType GBLBJCIFGEI_set_EffectType
}
public class DJJLEDFBIBI
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA_get_p1 NEPOGGCFLEE_set_p1
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM_get_p2 FGBBLCDLPMO_set_p2
	public uint INANEEGAEEG { get; set; } // 0x14 CKPKJEJMACE GAEPJHACPBA_get_ FGPHIHOOEGP_set_
}
public class GNDJHFAGJKB
{
	public uint BEKFHEBCPEE_lid { get; set; } // 0x8 CBMBNLGHCIJ HNFOPDCPENF_get_lid KGALEEINBDN_set_lid
	public int PFOIIAGCKON { get; set; } // 0xC LDIIIKODNIC IEGPJCFFFNK_get_ PAINBOCLHMO_set_
	public uint NNONCOCHGMD_tt { get; set; } // 0x10 JIFDIIFBIFD MNDPADEADII_get_tt BFLMOFGALBC_set_tt
	public uint[] MHHNOKGNJFN_tv { get; set; } // 0x14 MOFFLCMBILL KHGGAIEKNMF_get_tv GABNIBDEKBB_set_tv
	public uint MIKCFEHGNJB_dt { get; set; } // 0x18 HGBGPCILGLM PPCHCNBHAAG_get_dt DKKLANMGOIF_set_dt
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x1C JKDMAFHPKDJ DHOGDENEIOI_get_dv DBDFNFLGDFN_set_dv
	public uint HIMIDIJIGJN_et { get; set; } // 0x20 JJINNLAMGLL BHEAPFFMJOB_get_et KFAFHOOLEGI_set_et
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x24 CENBLPHOLKK COMDLMJJFFN_get_ev MJNJNAHIJCO_set_ev
	public uint IMLOHAOEKJE { get; set; } // 0x28 HGNBBCGNGEE LHFGMOKLEMB_get_ BIHJEDPNMJN_set_
	public uint LFOHDJJHLJE { get; set; } // 0x2C MENEEGHPGDC JCNLPBLGDMK_get_ EECCBENKDPG_set_
	public uint[] JMAGFEENOED_dv2 { get; set; } // 0x30 GLKLOAGDFDK GDPLEDJGNJO_get_dv2 GGLKCLOJNBP_set_dv2
	public uint NDIOEOHDMLJ { get; set; } // 0x34 CADLEMLEPEL NEMGKAJDGBO_get_ JONFEFDFDEN_set_
	public uint[] JNNFFAEFGOC { get; set; } // 0x38 KPKIGBKGLNG FGKCMNIMKND_get_ IPBHJDBFGNE_set_
	public uint IAAMCGAOFPK { get; set; } // 0x3C AGAKKAPGPHN JJLFDBNBMBK_get_ HINJBPONOEK_set_
	public uint PLMHOKJIPJK_lin { get; set; } // 0x40 CLFBLFMHBMG POGIHHKNLNH_get_lin BPBHIDPPLAJ_set_lin
	public uint INANEEGAEEG { get; set; } // 0x44 CKPKJEJMACE GAEPJHACPBA_get_ FGPHIHOOEGP_set_
	public uint HEOLEHDFLJO_ico { get; set; } // 0x48 EALEFNJMEPK OICOCHBFNAK_get_ico HGLFJJHECGH_set_ico
	public uint AOELPHMDDND { get; set; } // 0x4C JCLLKBKEIHP PFHADHPFLMP_get_ LJPGAFOEAMA_set_
	public uint KPECMLFDLOI_pri { get; set; } // 0x50 CIGDCGJELBI ILFJIGDCGBK_get_pri DOGEFDDMBDM_set_pri
	public int LECPFABMCHE { get; set; } // 0x54 EOHDPMJNOPE GGMHOOGFBML_get_ DKOIJNFHBMA_set_
	public int EHCACJFKHIC { get; set; } // 0x58 LJBECNGBAMP EEMJGMLLDDP_get_ LBBMABEOENN_set_
	public uint FCBDGLEPGFJ_mid { get; set; } // 0x5C EBFNFMCEGFP DJCPCJNBNOF_get_mid KEDAKKPAIFI_set_mid
	public uint BPBLHHFKBBG { get; set; } // 0x60 BLBKEKHBLHE EHAPCNBENHL_get_ ONAHJPGJCCM_set_
}
public class EBAOBOGMNPH
{
	public uint MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public uint ODMJFHDIGLP_cnd { get; set; } // 0xC DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint JHGHCMEBOOL { get; set; } // 0x10 HHKEABPOCDD BILEDOIKHHJ_get_ MLDMGBLAILG_set_
	public uint BEJMJAHGAFH { get; set; } // 0x14 GEDDOIEODJP EIEOJPGJMOI_get_ GJBJICHNIJF_set_
}
public class FAGNHJMBNCI
{
	public uint PFOIIAGCKON { get; set; } // 0x8 LDIIIKODNIC IEGPJCFFFNK_get_ PAINBOCLHMO_set_
	public uint AOPELJFAMCL_LiveSkillType { get; set; } // 0xC PIIIHFJNIAI CEDJPEMOPJH_get_LiveSkillType KBNMPGFOKNK_set_LiveSkillType
}
public class LIAMFMKIPFD
{
	public uint BEKFHEBCPEE_lid { get; set; } // 0x8 CBMBNLGHCIJ HNFOPDCPENF_get_lid KGALEEINBDN_set_lid
	public uint NNONCOCHGMD_tt { get; set; } // 0xC JIFDIIFBIFD MNDPADEADII_get_tt BFLMOFGALBC_set_tt
	public uint MHHNOKGNJFN_tv { get; set; } // 0x10 MOFFLCMBILL KHGGAIEKNMF_get_tv GABNIBDEKBB_set_tv
	public uint MIKCFEHGNJB_dt { get; set; } // 0x14 HGBGPCILGLM PPCHCNBHAAG_get_dt DKKLANMGOIF_set_dt
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x18 JKDMAFHPKDJ DHOGDENEIOI_get_dv DBDFNFLGDFN_set_dv
	public uint HIMIDIJIGJN_et { get; set; } // 0x1C JJINNLAMGLL BHEAPFFMJOB_get_et KFAFHOOLEGI_set_et
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x20 CENBLPHOLKK COMDLMJJFFN_get_ev MJNJNAHIJCO_set_ev
	public uint PLMHOKJIPJK_lin { get; set; } // 0x24 CLFBLFMHBMG POGIHHKNLNH_get_lin BPBHIDPPLAJ_set_lin
}
public class DLMMECOIPDO
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH_get_tgt MEHEHNALGIH_set_tgt
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF_get_v1 LFGKAMKBDGA_set_v1
}
public class OPNDNFJFFIO
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA_get_p1 NEPOGGCFLEE_set_p1
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM_get_p2 FGBBLCDLPMO_set_p2
}
public class BPEPDCHPBOC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII_get_ JKGDHHCCEGG_set_
	public uint JKOIOLGLNFO { get; set; } // 0x18 BHNGANDMNPO CGKFIJPLEDI_get_ BJPHIHHNBLO_set_
	public uint OGNCJAMBOCJ { get; set; } // 0x1C CBAFOFPOCNC IEBIBAOJLGF_get_ CHBONGIILFK_set_
	public uint NDIOEOHDMLJ { get; set; } // 0x20 CADLEMLEPEL NEMGKAJDGBO_get_ JONFEFDFDEN_set_
	public uint LFOHDJJHLJE { get; set; } // 0x24 MENEEGHPGDC JCNLPBLGDMK_get_ EECCBENKDPG_set_
}
public class CLFBIKKLDOH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII_get_ JKGDHHCCEGG_set_
	public uint EPIBJMFJNDC { get; set; } // 0x18 PEBOAPLBEGH NGNPLKDEPDD_get_ CCKKDOEJEBH_set_
	public uint GNPACBPKKCP { get; set; } // 0x1C AFFAKAMGMPJ KPPMJKOKHCK_get_ EBEAJCOEJCN_set_
	public uint GCFHEHAFHKO { get; set; } // 0x20 OOMALFFLAII ACFPNJKMLPJ_get_ HDFMGGFIGMC_set_
	public uint KLCMNKMONJJ { get; set; } // 0x24 FJAPPIMCJNA ECIPMKDEOGL_get_ DBLJLODDJKL_set_
	public uint CGNBOKANMAD { get; set; } // 0x28 KDIPNFEEEMG COLJIOBFIBG_get_ IBFCBCGIOKN_set_
	public uint JOKNHEBCHFB { get; set; } // 0x2C IDLHIPAMNGL HOGLCPPGHAL_get_ LIHFLPJODNH_set_
}
public class DCOKBIMIIMA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII_get_ JKGDHHCCEGG_set_
	public int PFOIIAGCKON { get; set; } // 0x18 LDIIIKODNIC IEGPJCFFFNK_get_ PAINBOCLHMO_set_
	public uint JKOIOLGLNFO { get; set; } // 0x1C BHNGANDMNPO CGKFIJPLEDI_get_ BJPHIHHNBLO_set_
	public uint OGNCJAMBOCJ { get; set; } // 0x20 CBAFOFPOCNC IEBIBAOJLGF_get_ CHBONGIILFK_set_
	public uint NDIOEOHDMLJ { get; set; } // 0x24 CADLEMLEPEL NEMGKAJDGBO_get_ JONFEFDFDEN_set_
	public uint LFOHDJJHLJE { get; set; } // 0x28 MENEEGHPGDC JCNLPBLGDMK_get_ EECCBENKDPG_set_
	public uint NNONCOCHGMD_tt { get; set; } // 0x2C JIFDIIFBIFD MNDPADEADII_get_tt BFLMOFGALBC_set_tt
	public uint FCBDGLEPGFJ_mid { get; set; } // 0x30 EBFNFMCEGFP DJCPCJNBNOF_get_mid KEDAKKPAIFI_set_mid
	public uint BPBLHHFKBBG { get; set; } // 0x34 BLBKEKHBLHE EHAPCNBENHL_get_ ONAHJPGJCCM_set_
	public uint OCAMDLMPBGA_dv { get; set; } // 0x38 JKDMAFHPKDJ DHOGDENEIOI_get_dv DBDFNFLGDFN_set_dv
}
public class OJEFFPDNEOP
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH_get_tgt MEHEHNALGIH_set_tgt
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF_get_v1 LFGKAMKBDGA_set_v1
}
public class MEDPEPOBHGD
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA_get_p1 NEPOGGCFLEE_set_p1
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM_get_p2 FGBBLCDLPMO_set_p2
}
public class DGMLKJPPPOC
{
	public int[] FDBOPFEOENF_diva { get; set; } // 0x8 DNDMMJJOAOE MJPHCAIKKJG_get_diva GHECGDMEBFF_set_diva
	public int[] DKEDLFLAKGC { get; set; } // 0xC FAGKBALGCOO HAJBHCEFBMD_get_ OCHFADBFANO_set_
}
public class OJEKDEDAIEP
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class NGKKAGAMMDF
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class MFGCKJCKFDM
{
	public uint MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public uint ODMJFHDIGLP_cnd { get; set; } // 0xC DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint JHGHCMEBOOL { get; set; } // 0x10 HHKEABPOCDD BILEDOIKHHJ_get_ MLDMGBLAILG_set_
	public uint BEJMJAHGAFH { get; set; } // 0x14 GEDDOIEODJP EIEOJPGJMOI_get_ GJBJICHNIJF_set_
}
public class GOIHGONJPNC
{
	public int[] NANNGLGOFKH_value { get; set; } // 0x8 AAMNNPBLAHF EDFAHCMGHKM_get_value BKPDFNKGNHA_set_value
	public int NNDBJGDFEEM_Min { get; set; } // 0xC CNDGBLDLDCC EHNOFMPHLFC_get_Min GCANPOPEKEE_set_Min
	public int FDBOPFEOENF_diva { get; set; } // 0x10 DNDMMJJOAOE MJPHCAIKKJG_get_diva GHECGDMEBFF_set_diva
}
public class HPCMDEIGDDH
{
	public int[] KCOHMHFBDKF_Value1 { get; set; } // 0x8 GGIAPJFCIDJ GKJCGDJOJFJ_get_Value1 MCIEMNJMCCM_set_Value1
	public int[] HLMMBNCIIAC_Value2 { get; set; } // 0xC MMPKJPEIHIC IEHAMGNNLFN_get_Value2 JIICFDMJKBA_set_Value2
	public int DOOGFEGEKLG_max { get; set; } // 0x10 IKKMNBJGBJK AECMFIOFFJN_get_max NGOJJDOCIDG_set_max
}
public class NLLCPFIHFFA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int[] LGFLNOJDHHC_Targets { get; set; } // 0xC EMCGKFLLCOG CKEEGLHCHKH_get_Targets GHJPJPFOAAI_set_Targets
}
public class FLHKDAGGLNK
{
	public PKDAOHIIJMM[] OKDCMAAIICE { get; set; } // 0x8 ALNDDEMHFAM KGDAHOAGJBD_get_ JBHEGCMJLHG_set_
	public OEBKKEFIOEB[] BHJHBOKODBH { get; set; } // 0xC KDAKNDENEBP KCGDIAGAOLL_get_ KPKGOHNPJBO_set_
	public DJJLEDFBIBI[] CAIFABNNKJB { get; set; } // 0x10 NPIMPAHOCHO KBPMJOKBNDD_get_ DEKAEGABCMP_set_
	public GNDJHFAGJKB[] GBOHIMFKPPI { get; set; } // 0x14 EOLPDOIGNDG GJJNBIBKEGJ_get_ KIAKJFMDJGJ_set_
	public EBAOBOGMNPH[] KIHBDEJJHJM { get; set; } // 0x18 JHHDDEOBFCE FGHDAOHHEJG_get_ JLNEFNPCFKP_set_
	public FAGNHJMBNCI[] NIIDELOIGDB { get; set; } // 0x1C EAPLAOGHPOB KKKPEEDFKLO_get_ BMCDIGGOODN_set_
	public LIAMFMKIPFD[] CLELJNJEGID { get; set; } // 0x20 IPECODADDCA GPAEFFCJEPI_get_ MMBFFCMPCCH_set_
	public DLMMECOIPDO[] JNJPNLDJJMI { get; set; } // 0x24 ABAJGLDPMEJ OMOAAHAOKNI_get_ EDLMPAODJAP_set_
	public OPNDNFJFFIO[] FMMKFANHGMJ { get; set; } // 0x28 IHMBKCMKJLB BAHOEAJGBBP_get_ FFAHBKOFACO_set_
	public BPEPDCHPBOC[] HGFOLPABILK { get; set; } // 0x2C JBHKOFMNABI IMDENCKCOBL_get_ JNOFHKHFBHC_set_
	public CLFBIKKLDOH[] BGOAGJLBECM { get; set; } // 0x30 LNCBDDEPPBE IABIBHBKFIG_get_ CEHDCFKDGJK_set_
	public DCOKBIMIIMA[] OOBEHBMMJAC { get; set; } // 0x34 EDHGCIILCNF NGNEBFOAHPK_get_ ICAJDKMMFMK_set_
	public OJEFFPDNEOP[] NAAHEIAJLDP { get; set; } // 0x38 FMIFLFJAEAB ADBPCFNGFBH_get_ DPODCHHMIGK_set_
	public MEDPEPOBHGD[] GCGNDMLDCML { get; set; } // 0x3C BHHNLHCDFNB MKLPHIEGIPA_get_ PFJDNCGCHFM_set_
	public DGMLKJPPPOC[] NAJGALLJIBP { get; set; } // 0x40 FLHHMJPHAFD NLGAEFHPFNA_get_ JDMMDAJDICO_set_
	public OJEKDEDAIEP[] BHGDNGHDDAC { get; set; } // 0x44 JHDNDHBDFFI CEHHJMMMCID_get_ EDOEOHENKDG_set_
	public NGKKAGAMMDF[] MHGMDJNOLMI { get; set; } // 0x48 JBFEKPIDNIC NFFJJGMEEOB_get_ BGEFBFOAMPK_set_
	public MFGCKJCKFDM[] CHKNAMIFECK { get; set; } // 0x4C CGFNHNGAOCJ JCLOBJNAKDI_get_ HNBGHBCDOHG_set_
	public GOIHGONJPNC[] FIMINKADAPC { get; set; } // 0x50 JBHLJBKBFJJ ENLEDOBFKLJ_get_ NBHJFMEPHOO_set_
	public HPCMDEIGDDH[] GDFFALAJFNP { get; set; } // 0x54 CNGOBDOLPIF FIBHOKGCFEE_get_ LHKICDHCEIJ_set_
	public NLLCPFIHFFA[] KBFEMKJBHBL { get; set; } // 0x58 JLAGPOJDACM DMIFMIKEHKE_get_ AHNGBJBPFLP_set_
	public static FLHKDAGGLNK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1193468
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		HPKOMBFEADM res_readData_ = HPKOMBFEADM.GetRootAsHPKOMBFEADM(buffer);
		FLHKDAGGLNK res_data_ = new FLHKDAGGLNK();

		List<PKDAOHIIJMM> OKDCMAAIICE_list_ = new List<PKDAOHIIJMM>();
		for(int OKDCMAAIICE_idx_ = 0; OKDCMAAIICE_idx_ < res_readData_.NOKJIDGJCABLength; OKDCMAAIICE_idx_++)
		{
			GAJADNFKMEE OKDCMAAIICE_readData_ = res_readData_.GetNOKJIDGJCAB(OKDCMAAIICE_idx_);
			PKDAOHIIJMM OKDCMAAIICE_data_ = new PKDAOHIIJMM();

			OKDCMAAIICE_data_.DDMENKOHCGM_aid = OKDCMAAIICE_readData_.KMBNCDICCAJ/*_aid*/;
			OKDCMAAIICE_data_.MIKCFEHGNJB_dt = OKDCMAAIICE_readData_.LMKLPPINLOK/*_dt*/;
			List<uint> OCAMDLMPBGA_list_ = new List<uint>();
			for(int OCAMDLMPBGA_idx_ = 0; OCAMDLMPBGA_idx_ < OKDCMAAIICE_readData_.LGJDLFJCCLKLength; OCAMDLMPBGA_idx_++)
			{
				OCAMDLMPBGA_list_.Add(OKDCMAAIICE_readData_.GetLGJDLFJCCLK(OCAMDLMPBGA_idx_));
			}
			OKDCMAAIICE_data_.OCAMDLMPBGA_dv = OCAMDLMPBGA_list_.ToArray();

			OKDCMAAIICE_data_.HIMIDIJIGJN_et = OKDCMAAIICE_readData_.LIGDKLEFBNM/*_et*/;
			List<uint> CBDOEDKIOJK_list_ = new List<uint>();
			for(int CBDOEDKIOJK_idx_ = 0; CBDOEDKIOJK_idx_ < OKDCMAAIICE_readData_.BMICKLAGCCDLength; CBDOEDKIOJK_idx_++)
			{
				CBDOEDKIOJK_list_.Add(OKDCMAAIICE_readData_.GetBMICKLAGCCD(CBDOEDKIOJK_idx_));
			}
			OKDCMAAIICE_data_.CBDOEDKIOJK_ev = CBDOEDKIOJK_list_.ToArray();

			OKDCMAAIICE_data_.LFOHDJJHLJE = OKDCMAAIICE_readData_.DGMDFCHIBKD;
			List<uint> JMAGFEENOED_list_ = new List<uint>();
			for(int JMAGFEENOED_idx_ = 0; JMAGFEENOED_idx_ < OKDCMAAIICE_readData_.DINDMDCKMCPLength; JMAGFEENOED_idx_++)
			{
				JMAGFEENOED_list_.Add(OKDCMAAIICE_readData_.GetDINDMDCKMCP(JMAGFEENOED_idx_));
			}
			OKDCMAAIICE_data_.JMAGFEENOED_dv2 = JMAGFEENOED_list_.ToArray();

			OKDCMAAIICE_data_.NDIOEOHDMLJ = OKDCMAAIICE_readData_.EJNIJBKBNGE;
			List<uint> JNNFFAEFGOC_list_ = new List<uint>();
			for(int JNNFFAEFGOC_idx_ = 0; JNNFFAEFGOC_idx_ < OKDCMAAIICE_readData_.EBDOOBOFLFMLength; JNNFFAEFGOC_idx_++)
			{
				JNNFFAEFGOC_list_.Add(OKDCMAAIICE_readData_.GetEBDOOBOFLFM(JNNFFAEFGOC_idx_));
			}
			OKDCMAAIICE_data_.JNNFFAEFGOC = JNNFFAEFGOC_list_.ToArray();

			OKDCMAAIICE_data_.PLMHOKJIPJK_lin = OKDCMAAIICE_readData_.FLNOLLMJOKE/*_lin*/;
			OKDCMAAIICE_data_.INANEEGAEEG = OKDCMAAIICE_readData_.KHLNIPBFCNK;
			OKDCMAAIICE_data_.HEOLEHDFLJO_ico = OKDCMAAIICE_readData_.EOHDEKFEONI/*_ico*/;
			OKDCMAAIICE_data_.AOELPHMDDND = OKDCMAAIICE_readData_.FHKGIFCFEPI;
			OKDCMAAIICE_data_.KPECMLFDLOI_pri = OKDCMAAIICE_readData_.DMEMJNAEDHP/*_pri*/;
			OKDCMAAIICE_data_.GAMODHFMOMK = OKDCMAAIICE_readData_.JKKAICPJBOK;
			OKDCMAAIICE_list_.Add(OKDCMAAIICE_data_);
		}
		res_data_.OKDCMAAIICE = OKDCMAAIICE_list_.ToArray();

		List<OEBKKEFIOEB> BHJHBOKODBH_list_ = new List<OEBKKEFIOEB>();
		for(int BHJHBOKODBH_idx_ = 0; BHJHBOKODBH_idx_ < res_readData_.OMLNOBDNJMHLength; BHJHBOKODBH_idx_++)
		{
			APGAHFFLAPA BHJHBOKODBH_readData_ = res_readData_.GetOMLNOBDNJMH(BHJHBOKODBH_idx_);
			OEBKKEFIOEB BHJHBOKODBH_data_ = new OEBKKEFIOEB();

			BHJHBOKODBH_data_.ODMJFHDIGLP_cnd = BHJHBOKODBH_readData_.NCIKNCJLFBI/*_cnd*/;
			BHJHBOKODBH_data_.MJMPANIBFED_pid = BHJHBOKODBH_readData_.COPFAKAHEMN/*_pid*/;
			BHJHBOKODBH_data_.AGNHPHEJKMK_tgt = BHJHBOKODBH_readData_.HLPHBGLMBIO/*_tgt*/;
			BHJHBOKODBH_data_.GBJFNGCDKPM_typ = BHJHBOKODBH_readData_.LPJPOOHJKAE/*_typ*/;
			List<uint> KFCIJBLDHOK_list_ = new List<uint>();
			for(int KFCIJBLDHOK_idx_ = 0; KFCIJBLDHOK_idx_ < BHJHBOKODBH_readData_.CHGIONDFIKPLength; KFCIJBLDHOK_idx_++)
			{
				KFCIJBLDHOK_list_.Add(BHJHBOKODBH_readData_.GetCHGIONDFIKP(KFCIJBLDHOK_idx_));
			}
			BHJHBOKODBH_data_.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list_.ToArray();

			BHJHBOKODBH_data_.BBFKKANELFP_EffectType = BHJHBOKODBH_readData_.MGHHDHFMOPF/*_EffectType*/;
			BHJHBOKODBH_list_.Add(BHJHBOKODBH_data_);
		}
		res_data_.BHJHBOKODBH = BHJHBOKODBH_list_.ToArray();

		List<DJJLEDFBIBI> CAIFABNNKJB_list_ = new List<DJJLEDFBIBI>();
		for(int CAIFABNNKJB_idx_ = 0; CAIFABNNKJB_idx_ < res_readData_.IPNICBONNJELength; CAIFABNNKJB_idx_++)
		{
			JLDCIOBACAL CAIFABNNKJB_readData_ = res_readData_.GetIPNICBONNJE(CAIFABNNKJB_idx_);
			DJJLEDFBIBI CAIFABNNKJB_data_ = new DJJLEDFBIBI();

			CAIFABNNKJB_data_.JBFLEDKDFCO_cid = CAIFABNNKJB_readData_.HOENDPOGFIO/*_cid*/;
			CAIFABNNKJB_data_.POOHGENNICD_p1 = CAIFABNNKJB_readData_.PBOCIEKNBCI/*_p1*/;
			CAIFABNNKJB_data_.LLGBAPAACLL_p2 = CAIFABNNKJB_readData_.IHLNKPCMGNE/*_p2*/;
			CAIFABNNKJB_data_.INANEEGAEEG = CAIFABNNKJB_readData_.KHLNIPBFCNK;
			CAIFABNNKJB_list_.Add(CAIFABNNKJB_data_);
		}
		res_data_.CAIFABNNKJB = CAIFABNNKJB_list_.ToArray();

		List<GNDJHFAGJKB> GBOHIMFKPPI_list_ = new List<GNDJHFAGJKB>();
		for(int GBOHIMFKPPI_idx_ = 0; GBOHIMFKPPI_idx_ < res_readData_.CADCONAACMALength; GBOHIMFKPPI_idx_++)
		{
			EMCHOIHFOHN GBOHIMFKPPI_readData_ = res_readData_.GetCADCONAACMA(GBOHIMFKPPI_idx_);
			GNDJHFAGJKB GBOHIMFKPPI_data_ = new GNDJHFAGJKB();

			GBOHIMFKPPI_data_.BEKFHEBCPEE_lid = GBOHIMFKPPI_readData_.IPCBHGGLEJA/*_lid*/;
			GBOHIMFKPPI_data_.PFOIIAGCKON = GBOHIMFKPPI_readData_.CIOGNKLHPDE;
			GBOHIMFKPPI_data_.NNONCOCHGMD_tt = GBOHIMFKPPI_readData_.NABLNBMACHL/*_tt*/;
			List<uint> MHHNOKGNJFN_list_ = new List<uint>();
			for(int MHHNOKGNJFN_idx_ = 0; MHHNOKGNJFN_idx_ < GBOHIMFKPPI_readData_.ENFCBLPNAFOLength; MHHNOKGNJFN_idx_++)
			{
				MHHNOKGNJFN_list_.Add(GBOHIMFKPPI_readData_.GetENFCBLPNAFO(MHHNOKGNJFN_idx_));
			}
			GBOHIMFKPPI_data_.MHHNOKGNJFN_tv = MHHNOKGNJFN_list_.ToArray();

			GBOHIMFKPPI_data_.MIKCFEHGNJB_dt = GBOHIMFKPPI_readData_.LMKLPPINLOK/*_dt*/;
			List<uint> OCAMDLMPBGA_list_ = new List<uint>();
			for(int OCAMDLMPBGA_idx_ = 0; OCAMDLMPBGA_idx_ < GBOHIMFKPPI_readData_.LGJDLFJCCLKLength; OCAMDLMPBGA_idx_++)
			{
				OCAMDLMPBGA_list_.Add(GBOHIMFKPPI_readData_.GetLGJDLFJCCLK(OCAMDLMPBGA_idx_));
			}
			GBOHIMFKPPI_data_.OCAMDLMPBGA_dv = OCAMDLMPBGA_list_.ToArray();

			GBOHIMFKPPI_data_.HIMIDIJIGJN_et = GBOHIMFKPPI_readData_.LIGDKLEFBNM/*_et*/;
			List<uint> CBDOEDKIOJK_list_ = new List<uint>();
			for(int CBDOEDKIOJK_idx_ = 0; CBDOEDKIOJK_idx_ < GBOHIMFKPPI_readData_.BMICKLAGCCDLength; CBDOEDKIOJK_idx_++)
			{
				CBDOEDKIOJK_list_.Add(GBOHIMFKPPI_readData_.GetBMICKLAGCCD(CBDOEDKIOJK_idx_));
			}
			GBOHIMFKPPI_data_.CBDOEDKIOJK_ev = CBDOEDKIOJK_list_.ToArray();

			GBOHIMFKPPI_data_.IMLOHAOEKJE = GBOHIMFKPPI_readData_.JKONGPGFPNN;
			GBOHIMFKPPI_data_.LFOHDJJHLJE = GBOHIMFKPPI_readData_.DGMDFCHIBKD;
			List<uint> JMAGFEENOED_list_ = new List<uint>();
			for(int JMAGFEENOED_idx_ = 0; JMAGFEENOED_idx_ < GBOHIMFKPPI_readData_.DINDMDCKMCPLength; JMAGFEENOED_idx_++)
			{
				JMAGFEENOED_list_.Add(GBOHIMFKPPI_readData_.GetDINDMDCKMCP(JMAGFEENOED_idx_));
			}
			GBOHIMFKPPI_data_.JMAGFEENOED_dv2 = JMAGFEENOED_list_.ToArray();

			GBOHIMFKPPI_data_.NDIOEOHDMLJ = GBOHIMFKPPI_readData_.EJNIJBKBNGE;
			List<uint> JNNFFAEFGOC_list_ = new List<uint>();
			for(int JNNFFAEFGOC_idx_ = 0; JNNFFAEFGOC_idx_ < GBOHIMFKPPI_readData_.EBDOOBOFLFMLength; JNNFFAEFGOC_idx_++)
			{
				JNNFFAEFGOC_list_.Add(GBOHIMFKPPI_readData_.GetEBDOOBOFLFM(JNNFFAEFGOC_idx_));
			}
			GBOHIMFKPPI_data_.JNNFFAEFGOC = JNNFFAEFGOC_list_.ToArray();

			GBOHIMFKPPI_data_.IAAMCGAOFPK = GBOHIMFKPPI_readData_.OBAOICIEFHO;
			GBOHIMFKPPI_data_.PLMHOKJIPJK_lin = GBOHIMFKPPI_readData_.FLNOLLMJOKE/*_lin*/;
			GBOHIMFKPPI_data_.INANEEGAEEG = GBOHIMFKPPI_readData_.KHLNIPBFCNK;
			GBOHIMFKPPI_data_.HEOLEHDFLJO_ico = GBOHIMFKPPI_readData_.EOHDEKFEONI/*_ico*/;
			GBOHIMFKPPI_data_.AOELPHMDDND = GBOHIMFKPPI_readData_.FHKGIFCFEPI;
			GBOHIMFKPPI_data_.KPECMLFDLOI_pri = GBOHIMFKPPI_readData_.DMEMJNAEDHP/*_pri*/;
			GBOHIMFKPPI_data_.LECPFABMCHE = GBOHIMFKPPI_readData_.MBBCOAFGCJL;
			GBOHIMFKPPI_data_.EHCACJFKHIC = GBOHIMFKPPI_readData_.AFIBPDNHCNC;
			GBOHIMFKPPI_data_.FCBDGLEPGFJ_mid = GBOHIMFKPPI_readData_.BKKAFNHOJFE/*_mid*/;
			GBOHIMFKPPI_data_.BPBLHHFKBBG = GBOHIMFKPPI_readData_.PGKFEHHDIBH;
			GBOHIMFKPPI_list_.Add(GBOHIMFKPPI_data_);
		}
		res_data_.GBOHIMFKPPI = GBOHIMFKPPI_list_.ToArray();

		List<EBAOBOGMNPH> KIHBDEJJHJM_list_ = new List<EBAOBOGMNPH>();
		for(int KIHBDEJJHJM_idx_ = 0; KIHBDEJJHJM_idx_ < res_readData_.IPKCKIGAGBBLength; KIHBDEJJHJM_idx_++)
		{
			IMGPAFDIMKP KIHBDEJJHJM_readData_ = res_readData_.GetIPKCKIGAGBB(KIHBDEJJHJM_idx_);
			EBAOBOGMNPH KIHBDEJJHJM_data_ = new EBAOBOGMNPH();

			KIHBDEJJHJM_data_.MJMPANIBFED_pid = KIHBDEJJHJM_readData_.COPFAKAHEMN/*_pid*/;
			KIHBDEJJHJM_data_.ODMJFHDIGLP_cnd = KIHBDEJJHJM_readData_.NCIKNCJLFBI/*_cnd*/;
			KIHBDEJJHJM_data_.JHGHCMEBOOL = KIHBDEJJHJM_readData_.EEEHIFGPKON;
			KIHBDEJJHJM_data_.BEJMJAHGAFH = KIHBDEJJHJM_readData_.ANDMOLFOEDG;
			KIHBDEJJHJM_list_.Add(KIHBDEJJHJM_data_);
		}
		res_data_.KIHBDEJJHJM = KIHBDEJJHJM_list_.ToArray();

		List<FAGNHJMBNCI> NIIDELOIGDB_list_ = new List<FAGNHJMBNCI>();
		for(int NIIDELOIGDB_idx_ = 0; NIIDELOIGDB_idx_ < res_readData_.FGPFMCLGMALLength; NIIDELOIGDB_idx_++)
		{
			GMCDKDCBFFK NIIDELOIGDB_readData_ = res_readData_.GetFGPFMCLGMAL(NIIDELOIGDB_idx_);
			FAGNHJMBNCI NIIDELOIGDB_data_ = new FAGNHJMBNCI();

			NIIDELOIGDB_data_.PFOIIAGCKON = NIIDELOIGDB_readData_.CIOGNKLHPDE;
			NIIDELOIGDB_data_.AOPELJFAMCL_LiveSkillType = NIIDELOIGDB_readData_.OBIIODKLNFO/*_LiveSkillType*/;
			NIIDELOIGDB_list_.Add(NIIDELOIGDB_data_);
		}
		res_data_.NIIDELOIGDB = NIIDELOIGDB_list_.ToArray();

		List<LIAMFMKIPFD> CLELJNJEGID_list_ = new List<LIAMFMKIPFD>();
		for(int CLELJNJEGID_idx_ = 0; CLELJNJEGID_idx_ < res_readData_.LCHKOHKKMPHLength; CLELJNJEGID_idx_++)
		{
			PKAMNOECHOM CLELJNJEGID_readData_ = res_readData_.GetLCHKOHKKMPH(CLELJNJEGID_idx_);
			LIAMFMKIPFD CLELJNJEGID_data_ = new LIAMFMKIPFD();

			CLELJNJEGID_data_.BEKFHEBCPEE_lid = CLELJNJEGID_readData_.IPCBHGGLEJA/*_lid*/;
			CLELJNJEGID_data_.NNONCOCHGMD_tt = CLELJNJEGID_readData_.NABLNBMACHL/*_tt*/;
			CLELJNJEGID_data_.MHHNOKGNJFN_tv = CLELJNJEGID_readData_.OPDBBGBMPMM/*_tv*/;
			CLELJNJEGID_data_.MIKCFEHGNJB_dt = CLELJNJEGID_readData_.LMKLPPINLOK/*_dt*/;
			List<uint> OCAMDLMPBGA_list_ = new List<uint>();
			for(int OCAMDLMPBGA_idx_ = 0; OCAMDLMPBGA_idx_ < CLELJNJEGID_readData_.LGJDLFJCCLKLength; OCAMDLMPBGA_idx_++)
			{
				OCAMDLMPBGA_list_.Add(CLELJNJEGID_readData_.GetLGJDLFJCCLK(OCAMDLMPBGA_idx_));
			}
			CLELJNJEGID_data_.OCAMDLMPBGA_dv = OCAMDLMPBGA_list_.ToArray();

			CLELJNJEGID_data_.HIMIDIJIGJN_et = CLELJNJEGID_readData_.LIGDKLEFBNM/*_et*/;
			List<uint> CBDOEDKIOJK_list_ = new List<uint>();
			for(int CBDOEDKIOJK_idx_ = 0; CBDOEDKIOJK_idx_ < CLELJNJEGID_readData_.BMICKLAGCCDLength; CBDOEDKIOJK_idx_++)
			{
				CBDOEDKIOJK_list_.Add(CLELJNJEGID_readData_.GetBMICKLAGCCD(CBDOEDKIOJK_idx_));
			}
			CLELJNJEGID_data_.CBDOEDKIOJK_ev = CBDOEDKIOJK_list_.ToArray();

			CLELJNJEGID_data_.PLMHOKJIPJK_lin = CLELJNJEGID_readData_.FLNOLLMJOKE/*_lin*/;
			CLELJNJEGID_list_.Add(CLELJNJEGID_data_);
		}
		res_data_.CLELJNJEGID = CLELJNJEGID_list_.ToArray();

		List<DLMMECOIPDO> JNJPNLDJJMI_list_ = new List<DLMMECOIPDO>();
		for(int JNJPNLDJJMI_idx_ = 0; JNJPNLDJJMI_idx_ < res_readData_.IIPLKGBCJMFLength; JNJPNLDJJMI_idx_++)
		{
			OENLOOBJABF JNJPNLDJJMI_readData_ = res_readData_.GetIIPLKGBCJMF(JNJPNLDJJMI_idx_);
			DLMMECOIPDO JNJPNLDJJMI_data_ = new DLMMECOIPDO();

			JNJPNLDJJMI_data_.ODMJFHDIGLP_cnd = JNJPNLDJJMI_readData_.NCIKNCJLFBI/*_cnd*/;
			JNJPNLDJJMI_data_.MJMPANIBFED_pid = JNJPNLDJJMI_readData_.COPFAKAHEMN/*_pid*/;
			JNJPNLDJJMI_data_.AGNHPHEJKMK_tgt = JNJPNLDJJMI_readData_.HLPHBGLMBIO/*_tgt*/;
			JNJPNLDJJMI_data_.GBJFNGCDKPM_typ = JNJPNLDJJMI_readData_.LPJPOOHJKAE/*_typ*/;
			List<uint> KFCIJBLDHOK_list_ = new List<uint>();
			for(int KFCIJBLDHOK_idx_ = 0; KFCIJBLDHOK_idx_ < JNJPNLDJJMI_readData_.CHGIONDFIKPLength; KFCIJBLDHOK_idx_++)
			{
				KFCIJBLDHOK_list_.Add(JNJPNLDJJMI_readData_.GetCHGIONDFIKP(KFCIJBLDHOK_idx_));
			}
			JNJPNLDJJMI_data_.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list_.ToArray();

			JNJPNLDJJMI_list_.Add(JNJPNLDJJMI_data_);
		}
		res_data_.JNJPNLDJJMI = JNJPNLDJJMI_list_.ToArray();

		List<OPNDNFJFFIO> FMMKFANHGMJ_list_ = new List<OPNDNFJFFIO>();
		for(int FMMKFANHGMJ_idx_ = 0; FMMKFANHGMJ_idx_ < res_readData_.KCPALOBNNJILength; FMMKFANHGMJ_idx_++)
		{
			DLDBCENIBOB FMMKFANHGMJ_readData_ = res_readData_.GetKCPALOBNNJI(FMMKFANHGMJ_idx_);
			OPNDNFJFFIO FMMKFANHGMJ_data_ = new OPNDNFJFFIO();

			FMMKFANHGMJ_data_.JBFLEDKDFCO_cid = FMMKFANHGMJ_readData_.HOENDPOGFIO/*_cid*/;
			FMMKFANHGMJ_data_.POOHGENNICD_p1 = FMMKFANHGMJ_readData_.PBOCIEKNBCI/*_p1*/;
			FMMKFANHGMJ_data_.LLGBAPAACLL_p2 = FMMKFANHGMJ_readData_.IHLNKPCMGNE/*_p2*/;
			FMMKFANHGMJ_list_.Add(FMMKFANHGMJ_data_);
		}
		res_data_.FMMKFANHGMJ = FMMKFANHGMJ_list_.ToArray();

		List<BPEPDCHPBOC> HGFOLPABILK_list_ = new List<BPEPDCHPBOC>();
		for(int HGFOLPABILK_idx_ = 0; HGFOLPABILK_idx_ < res_readData_.FOONGLJEAEGLength; HGFOLPABILK_idx_++)
		{
			GMAHGBPDAPH HGFOLPABILK_readData_ = res_readData_.GetFOONGLJEAEG(HGFOLPABILK_idx_);
			BPEPDCHPBOC HGFOLPABILK_data_ = new BPEPDCHPBOC();

			HGFOLPABILK_data_.PPFNGGCBJKC_id = HGFOLPABILK_readData_.BBPHAPFBFHK/*_id*/;
			HGFOLPABILK_data_.PLALNIIBLOF_en = HGFOLPABILK_readData_.CFLMCGOJJJD/*_en*/;
			HGFOLPABILK_data_.IJEKNCDIIAE_mver = HGFOLPABILK_readData_.OFMGALJGDAO/*_mver*/;
			HGFOLPABILK_data_.MKDDOJOADMF = HGFOLPABILK_readData_.DPHNIALHDJK;
			HGFOLPABILK_data_.JKOIOLGLNFO = HGFOLPABILK_readData_.HDGPONIHIBP;
			HGFOLPABILK_data_.OGNCJAMBOCJ = HGFOLPABILK_readData_.GFPLLOGJMHE;
			HGFOLPABILK_data_.NDIOEOHDMLJ = HGFOLPABILK_readData_.EJNIJBKBNGE;
			HGFOLPABILK_data_.LFOHDJJHLJE = HGFOLPABILK_readData_.DGMDFCHIBKD;
			HGFOLPABILK_list_.Add(HGFOLPABILK_data_);
		}
		res_data_.HGFOLPABILK = HGFOLPABILK_list_.ToArray();

		List<CLFBIKKLDOH> BGOAGJLBECM_list_ = new List<CLFBIKKLDOH>();
		for(int BGOAGJLBECM_idx_ = 0; BGOAGJLBECM_idx_ < res_readData_.DFDGMAIMKMKLength; BGOAGJLBECM_idx_++)
		{
			CCLAFODHKHA BGOAGJLBECM_readData_ = res_readData_.GetDFDGMAIMKMK(BGOAGJLBECM_idx_);
			CLFBIKKLDOH BGOAGJLBECM_data_ = new CLFBIKKLDOH();

			BGOAGJLBECM_data_.PPFNGGCBJKC_id = BGOAGJLBECM_readData_.BBPHAPFBFHK/*_id*/;
			BGOAGJLBECM_data_.PLALNIIBLOF_en = BGOAGJLBECM_readData_.CFLMCGOJJJD/*_en*/;
			BGOAGJLBECM_data_.IJEKNCDIIAE_mver = BGOAGJLBECM_readData_.OFMGALJGDAO/*_mver*/;
			BGOAGJLBECM_data_.MKDDOJOADMF = BGOAGJLBECM_readData_.DPHNIALHDJK;
			BGOAGJLBECM_data_.EPIBJMFJNDC = BGOAGJLBECM_readData_.LNAHNBCMHIE;
			BGOAGJLBECM_data_.GNPACBPKKCP = BGOAGJLBECM_readData_.NGNFMDIGEFK;
			BGOAGJLBECM_data_.GCFHEHAFHKO = BGOAGJLBECM_readData_.FBEBMENBOCL;
			BGOAGJLBECM_data_.KLCMNKMONJJ = BGOAGJLBECM_readData_.JEJAIHHMGCK;
			BGOAGJLBECM_data_.CGNBOKANMAD = BGOAGJLBECM_readData_.FHJJMPPPMIL;
			BGOAGJLBECM_data_.JOKNHEBCHFB = BGOAGJLBECM_readData_.AJFMHHBCNKB;
			BGOAGJLBECM_list_.Add(BGOAGJLBECM_data_);
		}
		res_data_.BGOAGJLBECM = BGOAGJLBECM_list_.ToArray();

		List<DCOKBIMIIMA> OOBEHBMMJAC_list_ = new List<DCOKBIMIIMA>();
		for(int OOBEHBMMJAC_idx_ = 0; OOBEHBMMJAC_idx_ < res_readData_.LPKLLIOACNFLength; OOBEHBMMJAC_idx_++)
		{
			KJLKDFAJFHC OOBEHBMMJAC_readData_ = res_readData_.GetLPKLLIOACNF(OOBEHBMMJAC_idx_);
			DCOKBIMIIMA OOBEHBMMJAC_data_ = new DCOKBIMIIMA();

			OOBEHBMMJAC_data_.PPFNGGCBJKC_id = OOBEHBMMJAC_readData_.BBPHAPFBFHK/*_id*/;
			OOBEHBMMJAC_data_.PLALNIIBLOF_en = OOBEHBMMJAC_readData_.CFLMCGOJJJD/*_en*/;
			OOBEHBMMJAC_data_.IJEKNCDIIAE_mver = OOBEHBMMJAC_readData_.OFMGALJGDAO/*_mver*/;
			OOBEHBMMJAC_data_.MKDDOJOADMF = OOBEHBMMJAC_readData_.DPHNIALHDJK;
			OOBEHBMMJAC_data_.PFOIIAGCKON = OOBEHBMMJAC_readData_.CIOGNKLHPDE;
			OOBEHBMMJAC_data_.JKOIOLGLNFO = OOBEHBMMJAC_readData_.HDGPONIHIBP;
			OOBEHBMMJAC_data_.OGNCJAMBOCJ = OOBEHBMMJAC_readData_.GFPLLOGJMHE;
			OOBEHBMMJAC_data_.NDIOEOHDMLJ = OOBEHBMMJAC_readData_.EJNIJBKBNGE;
			OOBEHBMMJAC_data_.LFOHDJJHLJE = OOBEHBMMJAC_readData_.DGMDFCHIBKD;
			OOBEHBMMJAC_data_.NNONCOCHGMD_tt = OOBEHBMMJAC_readData_.NABLNBMACHL/*_tt*/;
			OOBEHBMMJAC_data_.FCBDGLEPGFJ_mid = OOBEHBMMJAC_readData_.BKKAFNHOJFE/*_mid*/;
			OOBEHBMMJAC_data_.BPBLHHFKBBG = OOBEHBMMJAC_readData_.PGKFEHHDIBH;
			OOBEHBMMJAC_data_.OCAMDLMPBGA_dv = OOBEHBMMJAC_readData_.DDMBKEJNPJK/*_dv*/;
			OOBEHBMMJAC_list_.Add(OOBEHBMMJAC_data_);
		}
		res_data_.OOBEHBMMJAC = OOBEHBMMJAC_list_.ToArray();

		List<OJEFFPDNEOP> NAAHEIAJLDP_list_ = new List<OJEFFPDNEOP>();
		for(int NAAHEIAJLDP_idx_ = 0; NAAHEIAJLDP_idx_ < res_readData_.HCLJANFGCFHLength; NAAHEIAJLDP_idx_++)
		{
			LCFOJIDKGIN NAAHEIAJLDP_readData_ = res_readData_.GetHCLJANFGCFH(NAAHEIAJLDP_idx_);
			OJEFFPDNEOP NAAHEIAJLDP_data_ = new OJEFFPDNEOP();

			NAAHEIAJLDP_data_.ODMJFHDIGLP_cnd = NAAHEIAJLDP_readData_.NCIKNCJLFBI/*_cnd*/;
			NAAHEIAJLDP_data_.MJMPANIBFED_pid = NAAHEIAJLDP_readData_.COPFAKAHEMN/*_pid*/;
			NAAHEIAJLDP_data_.AGNHPHEJKMK_tgt = NAAHEIAJLDP_readData_.HLPHBGLMBIO/*_tgt*/;
			NAAHEIAJLDP_data_.GBJFNGCDKPM_typ = NAAHEIAJLDP_readData_.LPJPOOHJKAE/*_typ*/;
			List<uint> KFCIJBLDHOK_list_ = new List<uint>();
			for(int KFCIJBLDHOK_idx_ = 0; KFCIJBLDHOK_idx_ < NAAHEIAJLDP_readData_.CHGIONDFIKPLength; KFCIJBLDHOK_idx_++)
			{
				KFCIJBLDHOK_list_.Add(NAAHEIAJLDP_readData_.GetCHGIONDFIKP(KFCIJBLDHOK_idx_));
			}
			NAAHEIAJLDP_data_.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list_.ToArray();

			NAAHEIAJLDP_list_.Add(NAAHEIAJLDP_data_);
		}
		res_data_.NAAHEIAJLDP = NAAHEIAJLDP_list_.ToArray();

		List<MEDPEPOBHGD> GCGNDMLDCML_list_ = new List<MEDPEPOBHGD>();
		for(int GCGNDMLDCML_idx_ = 0; GCGNDMLDCML_idx_ < res_readData_.LGCEAMIIMJKLength; GCGNDMLDCML_idx_++)
		{
			AMFPOBCCLMN GCGNDMLDCML_readData_ = res_readData_.GetLGCEAMIIMJK(GCGNDMLDCML_idx_);
			MEDPEPOBHGD GCGNDMLDCML_data_ = new MEDPEPOBHGD();

			GCGNDMLDCML_data_.JBFLEDKDFCO_cid = GCGNDMLDCML_readData_.HOENDPOGFIO/*_cid*/;
			GCGNDMLDCML_data_.POOHGENNICD_p1 = GCGNDMLDCML_readData_.PBOCIEKNBCI/*_p1*/;
			GCGNDMLDCML_data_.LLGBAPAACLL_p2 = GCGNDMLDCML_readData_.IHLNKPCMGNE/*_p2*/;
			GCGNDMLDCML_list_.Add(GCGNDMLDCML_data_);
		}
		res_data_.GCGNDMLDCML = GCGNDMLDCML_list_.ToArray();

		List<DGMLKJPPPOC> NAJGALLJIBP_list_ = new List<DGMLKJPPPOC>();
		for(int NAJGALLJIBP_idx_ = 0; NAJGALLJIBP_idx_ < res_readData_.PAFOHOKPIGHLength; NAJGALLJIBP_idx_++)
		{
			IPIBGJJPKLO NAJGALLJIBP_readData_ = res_readData_.GetPAFOHOKPIGH(NAJGALLJIBP_idx_);
			DGMLKJPPPOC NAJGALLJIBP_data_ = new DGMLKJPPPOC();

			List<int> FDBOPFEOENF_list_ = new List<int>();
			for(int FDBOPFEOENF_idx_ = 0; FDBOPFEOENF_idx_ < NAJGALLJIBP_readData_.FOGBEEHMDJMLength; FDBOPFEOENF_idx_++)
			{
				FDBOPFEOENF_list_.Add(NAJGALLJIBP_readData_.GetFOGBEEHMDJM(FDBOPFEOENF_idx_));
			}
			NAJGALLJIBP_data_.FDBOPFEOENF_diva = FDBOPFEOENF_list_.ToArray();

			List<int> DKEDLFLAKGC_list_ = new List<int>();
			for(int DKEDLFLAKGC_idx_ = 0; DKEDLFLAKGC_idx_ < NAJGALLJIBP_readData_.BIMBNIBIMHALength; DKEDLFLAKGC_idx_++)
			{
				DKEDLFLAKGC_list_.Add(NAJGALLJIBP_readData_.GetBIMBNIBIMHA(DKEDLFLAKGC_idx_));
			}
			NAJGALLJIBP_data_.DKEDLFLAKGC = DKEDLFLAKGC_list_.ToArray();

			NAJGALLJIBP_list_.Add(NAJGALLJIBP_data_);
		}
		res_data_.NAJGALLJIBP = NAJGALLJIBP_list_.ToArray();

		List<OJEKDEDAIEP> BHGDNGHDDAC_list_ = new List<OJEKDEDAIEP>();
		for(int BHGDNGHDDAC_idx_ = 0; BHGDNGHDDAC_idx_ < res_readData_.NJJINHMIOHNLength; BHGDNGHDDAC_idx_++)
		{
			BANGFGHKPNP BHGDNGHDDAC_readData_ = res_readData_.GetNJJINHMIOHN(BHGDNGHDDAC_idx_);
			OJEKDEDAIEP BHGDNGHDDAC_data_ = new OJEKDEDAIEP();

			BHGDNGHDDAC_data_.LJNAKDMILMC_key = BHGDNGHDDAC_readData_.AGOIMGHMGOH/*_key*/;
			BHGDNGHDDAC_data_.JBGEEPFKIGG_val = BHGDNGHDDAC_readData_.KJFEBMBHKOC/*_val*/;
			BHGDNGHDDAC_list_.Add(BHGDNGHDDAC_data_);
		}
		res_data_.BHGDNGHDDAC = BHGDNGHDDAC_list_.ToArray();

		List<NGKKAGAMMDF> MHGMDJNOLMI_list_ = new List<NGKKAGAMMDF>();
		for(int MHGMDJNOLMI_idx_ = 0; MHGMDJNOLMI_idx_ < res_readData_.NPFBHGKLIOMLength; MHGMDJNOLMI_idx_++)
		{
			JEMGNNMPIAD MHGMDJNOLMI_readData_ = res_readData_.GetNPFBHGKLIOM(MHGMDJNOLMI_idx_);
			NGKKAGAMMDF MHGMDJNOLMI_data_ = new NGKKAGAMMDF();

			MHGMDJNOLMI_data_.LJNAKDMILMC_key = MHGMDJNOLMI_readData_.AGOIMGHMGOH/*_key*/;
			MHGMDJNOLMI_data_.JBGEEPFKIGG_val = MHGMDJNOLMI_readData_.KJFEBMBHKOC/*_val*/;
			MHGMDJNOLMI_list_.Add(MHGMDJNOLMI_data_);
		}
		res_data_.MHGMDJNOLMI = MHGMDJNOLMI_list_.ToArray();

		List<MFGCKJCKFDM> CHKNAMIFECK_list_ = new List<MFGCKJCKFDM>();
		for(int CHKNAMIFECK_idx_ = 0; CHKNAMIFECK_idx_ < res_readData_.PMKJKCPFLELLength; CHKNAMIFECK_idx_++)
		{
			KMMGHIGKELN CHKNAMIFECK_readData_ = res_readData_.GetPMKJKCPFLEL(CHKNAMIFECK_idx_);
			MFGCKJCKFDM CHKNAMIFECK_data_ = new MFGCKJCKFDM();

			CHKNAMIFECK_data_.MJMPANIBFED_pid = CHKNAMIFECK_readData_.COPFAKAHEMN/*_pid*/;
			CHKNAMIFECK_data_.ODMJFHDIGLP_cnd = CHKNAMIFECK_readData_.NCIKNCJLFBI/*_cnd*/;
			CHKNAMIFECK_data_.JHGHCMEBOOL = CHKNAMIFECK_readData_.EEEHIFGPKON;
			CHKNAMIFECK_data_.BEJMJAHGAFH = CHKNAMIFECK_readData_.ANDMOLFOEDG;
			CHKNAMIFECK_list_.Add(CHKNAMIFECK_data_);
		}
		res_data_.CHKNAMIFECK = CHKNAMIFECK_list_.ToArray();

		List<GOIHGONJPNC> FIMINKADAPC_list_ = new List<GOIHGONJPNC>();
		for(int FIMINKADAPC_idx_ = 0; FIMINKADAPC_idx_ < res_readData_.KFLDFHANEKKLength; FIMINKADAPC_idx_++)
		{
			OLKBCLJBFAA FIMINKADAPC_readData_ = res_readData_.GetKFLDFHANEKK(FIMINKADAPC_idx_);
			GOIHGONJPNC FIMINKADAPC_data_ = new GOIHGONJPNC();

			List<int> NANNGLGOFKH_list_ = new List<int>();
			for(int NANNGLGOFKH_idx_ = 0; NANNGLGOFKH_idx_ < FIMINKADAPC_readData_.KPONLGHOAMBLength; NANNGLGOFKH_idx_++)
			{
				NANNGLGOFKH_list_.Add(FIMINKADAPC_readData_.GetKPONLGHOAMB(NANNGLGOFKH_idx_));
			}
			FIMINKADAPC_data_.NANNGLGOFKH_value = NANNGLGOFKH_list_.ToArray();

			FIMINKADAPC_data_.NNDBJGDFEEM_Min = FIMINKADAPC_readData_.CCIHMCAPHCB/*_Min*/;
			FIMINKADAPC_data_.FDBOPFEOENF_diva = FIMINKADAPC_readData_.PIFAMBCEMKL/*_diva*/;
			FIMINKADAPC_list_.Add(FIMINKADAPC_data_);
		}
		res_data_.FIMINKADAPC = FIMINKADAPC_list_.ToArray();

		List<HPCMDEIGDDH> GDFFALAJFNP_list_ = new List<HPCMDEIGDDH>();
		for(int GDFFALAJFNP_idx_ = 0; GDFFALAJFNP_idx_ < res_readData_.AOONDLEGAAALength; GDFFALAJFNP_idx_++)
		{
			GAJBGNNNHCP GDFFALAJFNP_readData_ = res_readData_.GetAOONDLEGAAA(GDFFALAJFNP_idx_);
			HPCMDEIGDDH GDFFALAJFNP_data_ = new HPCMDEIGDDH();

			List<int> KCOHMHFBDKF_list_ = new List<int>();
			for(int KCOHMHFBDKF_idx_ = 0; KCOHMHFBDKF_idx_ < GDFFALAJFNP_readData_.PHGKBJDEJKILength; KCOHMHFBDKF_idx_++)
			{
				KCOHMHFBDKF_list_.Add(GDFFALAJFNP_readData_.GetPHGKBJDEJKI(KCOHMHFBDKF_idx_));
			}
			GDFFALAJFNP_data_.KCOHMHFBDKF_Value1 = KCOHMHFBDKF_list_.ToArray();

			List<int> HLMMBNCIIAC_list_ = new List<int>();
			for(int HLMMBNCIIAC_idx_ = 0; HLMMBNCIIAC_idx_ < GDFFALAJFNP_readData_.OOFMHMCDPEMLength; HLMMBNCIIAC_idx_++)
			{
				HLMMBNCIIAC_list_.Add(GDFFALAJFNP_readData_.GetOOFMHMCDPEM(HLMMBNCIIAC_idx_));
			}
			GDFFALAJFNP_data_.HLMMBNCIIAC_Value2 = HLMMBNCIIAC_list_.ToArray();

			GDFFALAJFNP_data_.DOOGFEGEKLG_max = GDFFALAJFNP_readData_.GEJGMBBCFEE/*_max*/;
			GDFFALAJFNP_list_.Add(GDFFALAJFNP_data_);
		}
		res_data_.GDFFALAJFNP = GDFFALAJFNP_list_.ToArray();

		List<NLLCPFIHFFA> KBFEMKJBHBL_list_ = new List<NLLCPFIHFFA>();
		for(int KBFEMKJBHBL_idx_ = 0; KBFEMKJBHBL_idx_ < res_readData_.BEINKIKDHCOLength; KBFEMKJBHBL_idx_++)
		{
			JIIFKJGKCNM KBFEMKJBHBL_readData_ = res_readData_.GetBEINKIKDHCO(KBFEMKJBHBL_idx_);
			NLLCPFIHFFA KBFEMKJBHBL_data_ = new NLLCPFIHFFA();

			KBFEMKJBHBL_data_.PPFNGGCBJKC_id = KBFEMKJBHBL_readData_.BBPHAPFBFHK/*_id*/;
			List<int> LGFLNOJDHHC_list_ = new List<int>();
			for(int LGFLNOJDHHC_idx_ = 0; LGFLNOJDHHC_idx_ < KBFEMKJBHBL_readData_.JNFHLJCMAAALength; LGFLNOJDHHC_idx_++)
			{
				LGFLNOJDHHC_list_.Add(KBFEMKJBHBL_readData_.GetJNFHLJCMAAA(LGFLNOJDHHC_idx_));
			}
			KBFEMKJBHBL_data_.LGFLNOJDHHC_Targets = LGFLNOJDHHC_list_.ToArray();

			KBFEMKJBHBL_list_.Add(KBFEMKJBHBL_data_);
		}
		res_data_.KBFEMKJBHBL = KBFEMKJBHBL_list_.ToArray();

		return res_data_;
	}
}
