using FlatBuffers;
using System.Collections.Generic;

public class PKDAOHIIJMM
{
	public uint DDMENKOHCGM_aid { get; set; } // 0x8 PFIGOIDGEDB NHEMDKLCIOG NMEAJIJAGHD
	public uint MIKCFEHGNJB_dt { get; set; } // 0xC HGBGPCILGLM PPCHCNBHAAG DKKLANMGOIF
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x10 JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
	public uint HIMIDIJIGJN_et { get; set; } // 0x14 JJINNLAMGLL BHEAPFFMJOB KFAFHOOLEGI
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x18 CENBLPHOLKK COMDLMJJFFN MJNJNAHIJCO
	public uint LFOHDJJHLJE { get; set; } // 0x1C MENEEGHPGDC JCNLPBLGDMK EECCBENKDPG
	public uint[] JMAGFEENOED_dv2 { get; set; } // 0x20 GLKLOAGDFDK GDPLEDJGNJO GGLKCLOJNBP
	public uint NDIOEOHDMLJ { get; set; } // 0x24 CADLEMLEPEL NEMGKAJDGBO JONFEFDFDEN
	public uint[] JNNFFAEFGOC { get; set; } // 0x28 KPKIGBKGLNG FGKCMNIMKND IPBHJDBFGNE
	public uint PLMHOKJIPJK_lin { get; set; } // 0x2C CLFBLFMHBMG POGIHHKNLNH BPBHIDPPLAJ
	public uint INANEEGAEEG { get; set; } // 0x30 CKPKJEJMACE GAEPJHACPBA FGPHIHOOEGP
	public uint HEOLEHDFLJO_ico { get; set; } // 0x34 EALEFNJMEPK OICOCHBFNAK HGLFJJHECGH
	public uint AOELPHMDDND { get; set; } // 0x38 JCLLKBKEIHP PFHADHPFLMP LJPGAFOEAMA
	public uint KPECMLFDLOI_pri { get; set; } // 0x3C CIGDCGJELBI ILFJIGDCGBK DOGEFDDMBDM
	public uint GAMODHFMOMK { get; set; } // 0x40 ACHOGBEJIAH PLKDHENBGAF KIPFAMBAGBE
}
public class OEBKKEFIOEB
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ KEOPEEKGMDO
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH MEHEHNALGIH
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int BBFKKANELFP_EffectType { get; set; } // 0x1C NOLHNEKFBOP OEGMCIENPLC GBLBJCIFGEI
}
public class DJJLEDFBIBI
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA NEPOGGCFLEE
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM FGBBLCDLPMO
	public uint INANEEGAEEG { get; set; } // 0x14 CKPKJEJMACE GAEPJHACPBA FGPHIHOOEGP
}
public class GNDJHFAGJKB
{
	public uint BEKFHEBCPEE_lid { get; set; } // 0x8 CBMBNLGHCIJ HNFOPDCPENF KGALEEINBDN
	public int PFOIIAGCKON { get; set; } // 0xC LDIIIKODNIC IEGPJCFFFNK PAINBOCLHMO
	public uint NNONCOCHGMD_tt { get; set; } // 0x10 JIFDIIFBIFD MNDPADEADII BFLMOFGALBC
	public uint[] MHHNOKGNJFN_tv { get; set; } // 0x14 MOFFLCMBILL KHGGAIEKNMF GABNIBDEKBB
	public uint MIKCFEHGNJB_dt { get; set; } // 0x18 HGBGPCILGLM PPCHCNBHAAG DKKLANMGOIF
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x1C JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
	public uint HIMIDIJIGJN_et { get; set; } // 0x20 JJINNLAMGLL BHEAPFFMJOB KFAFHOOLEGI
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x24 CENBLPHOLKK COMDLMJJFFN MJNJNAHIJCO
	public uint IMLOHAOEKJE { get; set; } // 0x28 HGNBBCGNGEE LHFGMOKLEMB BIHJEDPNMJN
	public uint LFOHDJJHLJE { get; set; } // 0x2C MENEEGHPGDC JCNLPBLGDMK EECCBENKDPG
	public uint[] JMAGFEENOED_dv2 { get; set; } // 0x30 GLKLOAGDFDK GDPLEDJGNJO GGLKCLOJNBP
	public uint NDIOEOHDMLJ { get; set; } // 0x34 CADLEMLEPEL NEMGKAJDGBO JONFEFDFDEN
	public uint[] JNNFFAEFGOC { get; set; } // 0x38 KPKIGBKGLNG FGKCMNIMKND IPBHJDBFGNE
	public uint IAAMCGAOFPK { get; set; } // 0x3C AGAKKAPGPHN JJLFDBNBMBK HINJBPONOEK
	public uint PLMHOKJIPJK_lin { get; set; } // 0x40 CLFBLFMHBMG POGIHHKNLNH BPBHIDPPLAJ
	public uint INANEEGAEEG { get; set; } // 0x44 CKPKJEJMACE GAEPJHACPBA FGPHIHOOEGP
	public uint HEOLEHDFLJO_ico { get; set; } // 0x48 EALEFNJMEPK OICOCHBFNAK HGLFJJHECGH
	public uint AOELPHMDDND { get; set; } // 0x4C JCLLKBKEIHP PFHADHPFLMP LJPGAFOEAMA
	public uint KPECMLFDLOI_pri { get; set; } // 0x50 CIGDCGJELBI ILFJIGDCGBK DOGEFDDMBDM
	public int LECPFABMCHE { get; set; } // 0x54 EOHDPMJNOPE GGMHOOGFBML DKOIJNFHBMA
	public int EHCACJFKHIC { get; set; } // 0x58 LJBECNGBAMP EEMJGMLLDDP LBBMABEOENN
	public uint FCBDGLEPGFJ_mid { get; set; } // 0x5C EBFNFMCEGFP DJCPCJNBNOF KEDAKKPAIFI
	public uint BPBLHHFKBBG { get; set; } // 0x60 BLBKEKHBLHE EHAPCNBENHL ONAHJPGJCCM
}
public class EBAOBOGMNPH
{
	public uint MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public uint ODMJFHDIGLP_cnd { get; set; } // 0xC DKHKAJOLLPE IEACLNIEABJ KEOPEEKGMDO
	public uint JHGHCMEBOOL { get; set; } // 0x10 HHKEABPOCDD BILEDOIKHHJ MLDMGBLAILG
	public uint BEJMJAHGAFH { get; set; } // 0x14 GEDDOIEODJP EIEOJPGJMOI GJBJICHNIJF
}
public class FAGNHJMBNCI
{
	public uint PFOIIAGCKON { get; set; } // 0x8 LDIIIKODNIC IEGPJCFFFNK PAINBOCLHMO
	public uint AOPELJFAMCL_LiveSkillType { get; set; } // 0xC PIIIHFJNIAI CEDJPEMOPJH KBNMPGFOKNK
}
public class LIAMFMKIPFD
{
	public uint BEKFHEBCPEE_lid { get; set; } // 0x8 CBMBNLGHCIJ HNFOPDCPENF KGALEEINBDN
	public uint NNONCOCHGMD_tt { get; set; } // 0xC JIFDIIFBIFD MNDPADEADII BFLMOFGALBC
	public uint MHHNOKGNJFN_tv { get; set; } // 0x10 MOFFLCMBILL KHGGAIEKNMF GABNIBDEKBB
	public uint MIKCFEHGNJB_dt { get; set; } // 0x14 HGBGPCILGLM PPCHCNBHAAG DKKLANMGOIF
	public uint[] OCAMDLMPBGA_dv { get; set; } // 0x18 JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
	public uint HIMIDIJIGJN_et { get; set; } // 0x1C JJINNLAMGLL BHEAPFFMJOB KFAFHOOLEGI
	public uint[] CBDOEDKIOJK_ev { get; set; } // 0x20 CENBLPHOLKK COMDLMJJFFN MJNJNAHIJCO
	public uint PLMHOKJIPJK_lin { get; set; } // 0x24 CLFBLFMHBMG POGIHHKNLNH BPBHIDPPLAJ
}
public class DLMMECOIPDO
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ KEOPEEKGMDO
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH MEHEHNALGIH
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
}
public class OPNDNFJFFIO
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA NEPOGGCFLEE
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM FGBBLCDLPMO
}
public class BPEPDCHPBOC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII JKGDHHCCEGG
	public uint JKOIOLGLNFO { get; set; } // 0x18 BHNGANDMNPO CGKFIJPLEDI BJPHIHHNBLO
	public uint OGNCJAMBOCJ { get; set; } // 0x1C CBAFOFPOCNC IEBIBAOJLGF CHBONGIILFK
	public uint NDIOEOHDMLJ { get; set; } // 0x20 CADLEMLEPEL NEMGKAJDGBO JONFEFDFDEN
	public uint LFOHDJJHLJE { get; set; } // 0x24 MENEEGHPGDC JCNLPBLGDMK EECCBENKDPG
}
public class CLFBIKKLDOH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII JKGDHHCCEGG
	public uint EPIBJMFJNDC { get; set; } // 0x18 PEBOAPLBEGH NGNPLKDEPDD CCKKDOEJEBH
	public uint GNPACBPKKCP { get; set; } // 0x1C AFFAKAMGMPJ KPPMJKOKHCK EBEAJCOEJCN
	public uint GCFHEHAFHKO { get; set; } // 0x20 OOMALFFLAII ACFPNJKMLPJ HDFMGGFIGMC
	public uint KLCMNKMONJJ { get; set; } // 0x24 FJAPPIMCJNA ECIPMKDEOGL DBLJLODDJKL
	public uint CGNBOKANMAD { get; set; } // 0x28 KDIPNFEEEMG COLJIOBFIBG IBFCBCGIOKN
	public uint JOKNHEBCHFB { get; set; } // 0x2C IDLHIPAMNGL HOGLCPPGHAL LIHFLPJODNH
}
public class DCOKBIMIIMA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint MKDDOJOADMF { get; set; } // 0x14 JCMNDDHDOID LBBFKLAKDII JKGDHHCCEGG
	public int PFOIIAGCKON { get; set; } // 0x18 LDIIIKODNIC IEGPJCFFFNK PAINBOCLHMO
	public uint JKOIOLGLNFO { get; set; } // 0x1C BHNGANDMNPO CGKFIJPLEDI BJPHIHHNBLO
	public uint OGNCJAMBOCJ { get; set; } // 0x20 CBAFOFPOCNC IEBIBAOJLGF CHBONGIILFK
	public uint NDIOEOHDMLJ { get; set; } // 0x24 CADLEMLEPEL NEMGKAJDGBO JONFEFDFDEN
	public uint LFOHDJJHLJE { get; set; } // 0x28 MENEEGHPGDC JCNLPBLGDMK EECCBENKDPG
	public uint NNONCOCHGMD_tt { get; set; } // 0x2C JIFDIIFBIFD MNDPADEADII BFLMOFGALBC
	public uint FCBDGLEPGFJ_mid { get; set; } // 0x30 EBFNFMCEGFP DJCPCJNBNOF KEDAKKPAIFI
	public uint BPBLHHFKBBG { get; set; } // 0x34 BLBKEKHBLHE EHAPCNBENHL ONAHJPGJCCM
	public uint OCAMDLMPBGA_dv { get; set; } // 0x38 JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
}
public class OJEFFPDNEOP
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ KEOPEEKGMDO
	public uint MJMPANIBFED_pid { get; set; } // 0xC GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public uint AGNHPHEJKMK_tgt { get; set; } // 0x10 BCKMGEBHABF MNJIGLFFJAH MEHEHNALGIH
	public uint GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint[] KFCIJBLDHOK_v1 { get; set; } // 0x18 JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
}
public class MEDPEPOBHGD
{
	public uint JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint POOHGENNICD_p1 { get; set; } // 0xC FDOJOMGKEHN ECKNJCLMPCA NEPOGGCFLEE
	public uint LLGBAPAACLL_p2 { get; set; } // 0x10 BJCPLKLPGJP CNAOBGOCLLM FGBBLCDLPMO
}
public class DGMLKJPPPOC
{
	public int[] FDBOPFEOENF_diva { get; set; } // 0x8 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public int[] DKEDLFLAKGC { get; set; } // 0xC FAGKBALGCOO HAJBHCEFBMD OCHFADBFANO
}
public class OJEKDEDAIEP
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NGKKAGAMMDF
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class MFGCKJCKFDM
{
	public uint MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public uint ODMJFHDIGLP_cnd { get; set; } // 0xC DKHKAJOLLPE IEACLNIEABJ KEOPEEKGMDO
	public uint JHGHCMEBOOL { get; set; } // 0x10 HHKEABPOCDD BILEDOIKHHJ MLDMGBLAILG
	public uint BEJMJAHGAFH { get; set; } // 0x14 GEDDOIEODJP EIEOJPGJMOI GJBJICHNIJF
}
public class GOIHGONJPNC
{
	public int[] NANNGLGOFKH_value { get; set; } // 0x8 AAMNNPBLAHF EDFAHCMGHKM BKPDFNKGNHA
	public int NNDBJGDFEEM_Min { get; set; } // 0xC CNDGBLDLDCC EHNOFMPHLFC GCANPOPEKEE
	public int FDBOPFEOENF_diva { get; set; } // 0x10 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
}
public class HPCMDEIGDDH
{
	public int[] KCOHMHFBDKF_Value1 { get; set; } // 0x8 GGIAPJFCIDJ GKJCGDJOJFJ MCIEMNJMCCM
	public int[] HLMMBNCIIAC_Value2 { get; set; } // 0xC MMPKJPEIHIC IEHAMGNNLFN JIICFDMJKBA
	public int DOOGFEGEKLG_max { get; set; } // 0x10 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
}
public class NLLCPFIHFFA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int[] LGFLNOJDHHC_Targets { get; set; } // 0xC EMCGKFLLCOG CKEEGLHCHKH GHJPJPFOAAI
}
public class FLHKDAGGLNK
{
	public PKDAOHIIJMM[] OKDCMAAIICE { get; set; } // 0x8 ALNDDEMHFAM KGDAHOAGJBD JBHEGCMJLHG
	public OEBKKEFIOEB[] BHJHBOKODBH { get; set; } // 0xC KDAKNDENEBP KCGDIAGAOLL KPKGOHNPJBO
	public DJJLEDFBIBI[] CAIFABNNKJB { get; set; } // 0x10 NPIMPAHOCHO KBPMJOKBNDD DEKAEGABCMP
	public GNDJHFAGJKB[] GBOHIMFKPPI { get; set; } // 0x14 EOLPDOIGNDG GJJNBIBKEGJ KIAKJFMDJGJ
	public EBAOBOGMNPH[] KIHBDEJJHJM { get; set; } // 0x18 JHHDDEOBFCE FGHDAOHHEJG JLNEFNPCFKP
	public FAGNHJMBNCI[] NIIDELOIGDB { get; set; } // 0x1C EAPLAOGHPOB KKKPEEDFKLO BMCDIGGOODN
	public LIAMFMKIPFD[] CLELJNJEGID { get; set; } // 0x20 IPECODADDCA GPAEFFCJEPI MMBFFCMPCCH
	public DLMMECOIPDO[] JNJPNLDJJMI { get; set; } // 0x24 ABAJGLDPMEJ OMOAAHAOKNI EDLMPAODJAP
	public OPNDNFJFFIO[] FMMKFANHGMJ { get; set; } // 0x28 IHMBKCMKJLB BAHOEAJGBBP FFAHBKOFACO
	public BPEPDCHPBOC[] HGFOLPABILK { get; set; } // 0x2C JBHKOFMNABI IMDENCKCOBL JNOFHKHFBHC
	public CLFBIKKLDOH[] BGOAGJLBECM { get; set; } // 0x30 LNCBDDEPPBE IABIBHBKFIG CEHDCFKDGJK
	public DCOKBIMIIMA[] OOBEHBMMJAC { get; set; } // 0x34 EDHGCIILCNF NGNEBFOAHPK ICAJDKMMFMK
	public OJEFFPDNEOP[] NAAHEIAJLDP { get; set; } // 0x38 FMIFLFJAEAB ADBPCFNGFBH DPODCHHMIGK
	public MEDPEPOBHGD[] GCGNDMLDCML { get; set; } // 0x3C BHHNLHCDFNB MKLPHIEGIPA PFJDNCGCHFM
	public DGMLKJPPPOC[] NAJGALLJIBP { get; set; } // 0x40 FLHHMJPHAFD NLGAEFHPFNA JDMMDAJDICO
	public OJEKDEDAIEP[] BHGDNGHDDAC { get; set; } // 0x44 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public NGKKAGAMMDF[] MHGMDJNOLMI { get; set; } // 0x48 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public MFGCKJCKFDM[] CHKNAMIFECK { get; set; } // 0x4C CGFNHNGAOCJ JCLOBJNAKDI HNBGHBCDOHG
	public GOIHGONJPNC[] FIMINKADAPC { get; set; } // 0x50 JBHLJBKBFJJ ENLEDOBFKLJ NBHJFMEPHOO
	public HPCMDEIGDDH[] GDFFALAJFNP { get; set; } // 0x54 CNGOBDOLPIF FIBHOKGCFEE LHKICDHCEIJ
	public NLLCPFIHFFA[] KBFEMKJBHBL { get; set; } // 0x58 JLAGPOJDACM DMIFMIKEHKE AHNGBJBPFLP
	public static FLHKDAGGLNK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1193468
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		HPKOMBFEADM res_readData = HPKOMBFEADM.GetRootAsHPKOMBFEADM(buffer);
		FLHKDAGGLNK res_data = new FLHKDAGGLNK();

		List<PKDAOHIIJMM> OKDCMAAIICE_list = new List<PKDAOHIIJMM>();
		for(int OKDCMAAIICE_idx = 0; OKDCMAAIICE_idx < res_readData.NOKJIDGJCABLength; OKDCMAAIICE_idx++)
		{
			GAJADNFKMEE OKDCMAAIICE_readData = res_readData.GetNOKJIDGJCAB(OKDCMAAIICE_idx);
			PKDAOHIIJMM OKDCMAAIICE_data = new PKDAOHIIJMM();

			OKDCMAAIICE_data.DDMENKOHCGM_aid = OKDCMAAIICE_readData.KMBNCDICCAJ;
			OKDCMAAIICE_data.MIKCFEHGNJB_dt = OKDCMAAIICE_readData.LMKLPPINLOK;
			List<uint> OCAMDLMPBGA_list = new List<uint>();
			for(int OCAMDLMPBGA_idx = 0; OCAMDLMPBGA_idx < OKDCMAAIICE_readData.LGJDLFJCCLKLength; OCAMDLMPBGA_idx++)
			{
				OCAMDLMPBGA_list.Add(OKDCMAAIICE_readData.GetLGJDLFJCCLK(OCAMDLMPBGA_idx));
			}
			OKDCMAAIICE_data.OCAMDLMPBGA_dv = OCAMDLMPBGA_list.ToArray();

			OKDCMAAIICE_data.HIMIDIJIGJN_et = OKDCMAAIICE_readData.LIGDKLEFBNM;
			List<uint> CBDOEDKIOJK_list = new List<uint>();
			for(int CBDOEDKIOJK_idx = 0; CBDOEDKIOJK_idx < OKDCMAAIICE_readData.BMICKLAGCCDLength; CBDOEDKIOJK_idx++)
			{
				CBDOEDKIOJK_list.Add(OKDCMAAIICE_readData.GetBMICKLAGCCD(CBDOEDKIOJK_idx));
			}
			OKDCMAAIICE_data.CBDOEDKIOJK_ev = CBDOEDKIOJK_list.ToArray();

			OKDCMAAIICE_data.LFOHDJJHLJE = OKDCMAAIICE_readData.DGMDFCHIBKD;
			List<uint> JMAGFEENOED_list = new List<uint>();
			for(int JMAGFEENOED_idx = 0; JMAGFEENOED_idx < OKDCMAAIICE_readData.DINDMDCKMCPLength; JMAGFEENOED_idx++)
			{
				JMAGFEENOED_list.Add(OKDCMAAIICE_readData.GetDINDMDCKMCP(JMAGFEENOED_idx));
			}
			OKDCMAAIICE_data.JMAGFEENOED_dv2 = JMAGFEENOED_list.ToArray();

			OKDCMAAIICE_data.NDIOEOHDMLJ = OKDCMAAIICE_readData.EJNIJBKBNGE;
			List<uint> JNNFFAEFGOC_list = new List<uint>();
			for(int JNNFFAEFGOC_idx = 0; JNNFFAEFGOC_idx < OKDCMAAIICE_readData.EBDOOBOFLFMLength; JNNFFAEFGOC_idx++)
			{
				JNNFFAEFGOC_list.Add(OKDCMAAIICE_readData.GetEBDOOBOFLFM(JNNFFAEFGOC_idx));
			}
			OKDCMAAIICE_data.JNNFFAEFGOC = JNNFFAEFGOC_list.ToArray();

			OKDCMAAIICE_data.PLMHOKJIPJK_lin = OKDCMAAIICE_readData.FLNOLLMJOKE;
			OKDCMAAIICE_data.INANEEGAEEG = OKDCMAAIICE_readData.KHLNIPBFCNK;
			OKDCMAAIICE_data.HEOLEHDFLJO_ico = OKDCMAAIICE_readData.EOHDEKFEONI;
			OKDCMAAIICE_data.AOELPHMDDND = OKDCMAAIICE_readData.FHKGIFCFEPI;
			OKDCMAAIICE_data.KPECMLFDLOI_pri = OKDCMAAIICE_readData.DMEMJNAEDHP;
			OKDCMAAIICE_data.GAMODHFMOMK = OKDCMAAIICE_readData.JKKAICPJBOK;
			OKDCMAAIICE_list.Add(OKDCMAAIICE_data);
		}
		res_data.OKDCMAAIICE = OKDCMAAIICE_list.ToArray();

		List<OEBKKEFIOEB> BHJHBOKODBH_list = new List<OEBKKEFIOEB>();
		for(int BHJHBOKODBH_idx = 0; BHJHBOKODBH_idx < res_readData.OMLNOBDNJMHLength; BHJHBOKODBH_idx++)
		{
			APGAHFFLAPA BHJHBOKODBH_readData = res_readData.GetOMLNOBDNJMH(BHJHBOKODBH_idx);
			OEBKKEFIOEB BHJHBOKODBH_data = new OEBKKEFIOEB();

			BHJHBOKODBH_data.ODMJFHDIGLP_cnd = BHJHBOKODBH_readData.NCIKNCJLFBI;
			BHJHBOKODBH_data.MJMPANIBFED_pid = BHJHBOKODBH_readData.COPFAKAHEMN;
			BHJHBOKODBH_data.AGNHPHEJKMK_tgt = BHJHBOKODBH_readData.HLPHBGLMBIO;
			BHJHBOKODBH_data.GBJFNGCDKPM_typ = BHJHBOKODBH_readData.LPJPOOHJKAE;
			List<uint> KFCIJBLDHOK_list = new List<uint>();
			for(int KFCIJBLDHOK_idx = 0; KFCIJBLDHOK_idx < BHJHBOKODBH_readData.CHGIONDFIKPLength; KFCIJBLDHOK_idx++)
			{
				KFCIJBLDHOK_list.Add(BHJHBOKODBH_readData.GetCHGIONDFIKP(KFCIJBLDHOK_idx));
			}
			BHJHBOKODBH_data.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list.ToArray();

			BHJHBOKODBH_data.BBFKKANELFP_EffectType = BHJHBOKODBH_readData.MGHHDHFMOPF;
			BHJHBOKODBH_list.Add(BHJHBOKODBH_data);
		}
		res_data.BHJHBOKODBH = BHJHBOKODBH_list.ToArray();

		List<DJJLEDFBIBI> CAIFABNNKJB_list = new List<DJJLEDFBIBI>();
		for(int CAIFABNNKJB_idx = 0; CAIFABNNKJB_idx < res_readData.IPNICBONNJELength; CAIFABNNKJB_idx++)
		{
			JLDCIOBACAL CAIFABNNKJB_readData = res_readData.GetIPNICBONNJE(CAIFABNNKJB_idx);
			DJJLEDFBIBI CAIFABNNKJB_data = new DJJLEDFBIBI();

			CAIFABNNKJB_data.JBFLEDKDFCO_cid = CAIFABNNKJB_readData.HOENDPOGFIO;
			CAIFABNNKJB_data.POOHGENNICD_p1 = CAIFABNNKJB_readData.PBOCIEKNBCI;
			CAIFABNNKJB_data.LLGBAPAACLL_p2 = CAIFABNNKJB_readData.IHLNKPCMGNE;
			CAIFABNNKJB_data.INANEEGAEEG = CAIFABNNKJB_readData.KHLNIPBFCNK;
			CAIFABNNKJB_list.Add(CAIFABNNKJB_data);
		}
		res_data.CAIFABNNKJB = CAIFABNNKJB_list.ToArray();

		List<GNDJHFAGJKB> GBOHIMFKPPI_list = new List<GNDJHFAGJKB>();
		for(int GBOHIMFKPPI_idx = 0; GBOHIMFKPPI_idx < res_readData.CADCONAACMALength; GBOHIMFKPPI_idx++)
		{
			EMCHOIHFOHN GBOHIMFKPPI_readData = res_readData.GetCADCONAACMA(GBOHIMFKPPI_idx);
			GNDJHFAGJKB GBOHIMFKPPI_data = new GNDJHFAGJKB();

			GBOHIMFKPPI_data.BEKFHEBCPEE_lid = GBOHIMFKPPI_readData.IPCBHGGLEJA;
			GBOHIMFKPPI_data.PFOIIAGCKON = GBOHIMFKPPI_readData.CIOGNKLHPDE;
			GBOHIMFKPPI_data.NNONCOCHGMD_tt = GBOHIMFKPPI_readData.NABLNBMACHL;
			List<uint> MHHNOKGNJFN_list = new List<uint>();
			for(int MHHNOKGNJFN_idx = 0; MHHNOKGNJFN_idx < GBOHIMFKPPI_readData.ENFCBLPNAFOLength; MHHNOKGNJFN_idx++)
			{
				MHHNOKGNJFN_list.Add(GBOHIMFKPPI_readData.GetENFCBLPNAFO(MHHNOKGNJFN_idx));
			}
			GBOHIMFKPPI_data.MHHNOKGNJFN_tv = MHHNOKGNJFN_list.ToArray();

			GBOHIMFKPPI_data.MIKCFEHGNJB_dt = GBOHIMFKPPI_readData.LMKLPPINLOK;
			List<uint> OCAMDLMPBGA_list = new List<uint>();
			for(int OCAMDLMPBGA_idx = 0; OCAMDLMPBGA_idx < GBOHIMFKPPI_readData.LGJDLFJCCLKLength; OCAMDLMPBGA_idx++)
			{
				OCAMDLMPBGA_list.Add(GBOHIMFKPPI_readData.GetLGJDLFJCCLK(OCAMDLMPBGA_idx));
			}
			GBOHIMFKPPI_data.OCAMDLMPBGA_dv = OCAMDLMPBGA_list.ToArray();

			GBOHIMFKPPI_data.HIMIDIJIGJN_et = GBOHIMFKPPI_readData.LIGDKLEFBNM;
			List<uint> CBDOEDKIOJK_list = new List<uint>();
			for(int CBDOEDKIOJK_idx = 0; CBDOEDKIOJK_idx < GBOHIMFKPPI_readData.BMICKLAGCCDLength; CBDOEDKIOJK_idx++)
			{
				CBDOEDKIOJK_list.Add(GBOHIMFKPPI_readData.GetBMICKLAGCCD(CBDOEDKIOJK_idx));
			}
			GBOHIMFKPPI_data.CBDOEDKIOJK_ev = CBDOEDKIOJK_list.ToArray();

			GBOHIMFKPPI_data.IMLOHAOEKJE = GBOHIMFKPPI_readData.JKONGPGFPNN;
			GBOHIMFKPPI_data.LFOHDJJHLJE = GBOHIMFKPPI_readData.DGMDFCHIBKD;
			List<uint> JMAGFEENOED_list = new List<uint>();
			for(int JMAGFEENOED_idx = 0; JMAGFEENOED_idx < GBOHIMFKPPI_readData.DINDMDCKMCPLength; JMAGFEENOED_idx++)
			{
				JMAGFEENOED_list.Add(GBOHIMFKPPI_readData.GetDINDMDCKMCP(JMAGFEENOED_idx));
			}
			GBOHIMFKPPI_data.JMAGFEENOED_dv2 = JMAGFEENOED_list.ToArray();

			GBOHIMFKPPI_data.NDIOEOHDMLJ = GBOHIMFKPPI_readData.EJNIJBKBNGE;
			List<uint> JNNFFAEFGOC_list = new List<uint>();
			for(int JNNFFAEFGOC_idx = 0; JNNFFAEFGOC_idx < GBOHIMFKPPI_readData.EBDOOBOFLFMLength; JNNFFAEFGOC_idx++)
			{
				JNNFFAEFGOC_list.Add(GBOHIMFKPPI_readData.GetEBDOOBOFLFM(JNNFFAEFGOC_idx));
			}
			GBOHIMFKPPI_data.JNNFFAEFGOC = JNNFFAEFGOC_list.ToArray();

			GBOHIMFKPPI_data.IAAMCGAOFPK = GBOHIMFKPPI_readData.OBAOICIEFHO;
			GBOHIMFKPPI_data.PLMHOKJIPJK_lin = GBOHIMFKPPI_readData.FLNOLLMJOKE;
			GBOHIMFKPPI_data.INANEEGAEEG = GBOHIMFKPPI_readData.KHLNIPBFCNK;
			GBOHIMFKPPI_data.HEOLEHDFLJO_ico = GBOHIMFKPPI_readData.EOHDEKFEONI;
			GBOHIMFKPPI_data.AOELPHMDDND = GBOHIMFKPPI_readData.FHKGIFCFEPI;
			GBOHIMFKPPI_data.KPECMLFDLOI_pri = GBOHIMFKPPI_readData.DMEMJNAEDHP;
			GBOHIMFKPPI_data.LECPFABMCHE = GBOHIMFKPPI_readData.MBBCOAFGCJL;
			GBOHIMFKPPI_data.EHCACJFKHIC = GBOHIMFKPPI_readData.AFIBPDNHCNC;
			GBOHIMFKPPI_data.FCBDGLEPGFJ_mid = GBOHIMFKPPI_readData.BKKAFNHOJFE;
			GBOHIMFKPPI_data.BPBLHHFKBBG = GBOHIMFKPPI_readData.PGKFEHHDIBH;
			GBOHIMFKPPI_list.Add(GBOHIMFKPPI_data);
		}
		res_data.GBOHIMFKPPI = GBOHIMFKPPI_list.ToArray();

		List<EBAOBOGMNPH> KIHBDEJJHJM_list = new List<EBAOBOGMNPH>();
		for(int KIHBDEJJHJM_idx = 0; KIHBDEJJHJM_idx < res_readData.IPKCKIGAGBBLength; KIHBDEJJHJM_idx++)
		{
			IMGPAFDIMKP KIHBDEJJHJM_readData = res_readData.GetIPKCKIGAGBB(KIHBDEJJHJM_idx);
			EBAOBOGMNPH KIHBDEJJHJM_data = new EBAOBOGMNPH();

			KIHBDEJJHJM_data.MJMPANIBFED_pid = KIHBDEJJHJM_readData.COPFAKAHEMN;
			KIHBDEJJHJM_data.ODMJFHDIGLP_cnd = KIHBDEJJHJM_readData.NCIKNCJLFBI;
			KIHBDEJJHJM_data.JHGHCMEBOOL = KIHBDEJJHJM_readData.EEEHIFGPKON;
			KIHBDEJJHJM_data.BEJMJAHGAFH = KIHBDEJJHJM_readData.ANDMOLFOEDG;
			KIHBDEJJHJM_list.Add(KIHBDEJJHJM_data);
		}
		res_data.KIHBDEJJHJM = KIHBDEJJHJM_list.ToArray();

		List<FAGNHJMBNCI> NIIDELOIGDB_list = new List<FAGNHJMBNCI>();
		for(int NIIDELOIGDB_idx = 0; NIIDELOIGDB_idx < res_readData.FGPFMCLGMALLength; NIIDELOIGDB_idx++)
		{
			GMCDKDCBFFK NIIDELOIGDB_readData = res_readData.GetFGPFMCLGMAL(NIIDELOIGDB_idx);
			FAGNHJMBNCI NIIDELOIGDB_data = new FAGNHJMBNCI();

			NIIDELOIGDB_data.PFOIIAGCKON = NIIDELOIGDB_readData.CIOGNKLHPDE;
			NIIDELOIGDB_data.AOPELJFAMCL_LiveSkillType = NIIDELOIGDB_readData.OBIIODKLNFO;
			NIIDELOIGDB_list.Add(NIIDELOIGDB_data);
		}
		res_data.NIIDELOIGDB = NIIDELOIGDB_list.ToArray();

		List<LIAMFMKIPFD> CLELJNJEGID_list = new List<LIAMFMKIPFD>();
		for(int CLELJNJEGID_idx = 0; CLELJNJEGID_idx < res_readData.LCHKOHKKMPHLength; CLELJNJEGID_idx++)
		{
			PKAMNOECHOM CLELJNJEGID_readData = res_readData.GetLCHKOHKKMPH(CLELJNJEGID_idx);
			LIAMFMKIPFD CLELJNJEGID_data = new LIAMFMKIPFD();

			CLELJNJEGID_data.BEKFHEBCPEE_lid = CLELJNJEGID_readData.IPCBHGGLEJA;
			CLELJNJEGID_data.NNONCOCHGMD_tt = CLELJNJEGID_readData.NABLNBMACHL;
			CLELJNJEGID_data.MHHNOKGNJFN_tv = CLELJNJEGID_readData.OPDBBGBMPMM;
			CLELJNJEGID_data.MIKCFEHGNJB_dt = CLELJNJEGID_readData.LMKLPPINLOK;
			List<uint> OCAMDLMPBGA_list = new List<uint>();
			for(int OCAMDLMPBGA_idx = 0; OCAMDLMPBGA_idx < CLELJNJEGID_readData.LGJDLFJCCLKLength; OCAMDLMPBGA_idx++)
			{
				OCAMDLMPBGA_list.Add(CLELJNJEGID_readData.GetLGJDLFJCCLK(OCAMDLMPBGA_idx));
			}
			CLELJNJEGID_data.OCAMDLMPBGA_dv = OCAMDLMPBGA_list.ToArray();

			CLELJNJEGID_data.HIMIDIJIGJN_et = CLELJNJEGID_readData.LIGDKLEFBNM;
			List<uint> CBDOEDKIOJK_list = new List<uint>();
			for(int CBDOEDKIOJK_idx = 0; CBDOEDKIOJK_idx < CLELJNJEGID_readData.BMICKLAGCCDLength; CBDOEDKIOJK_idx++)
			{
				CBDOEDKIOJK_list.Add(CLELJNJEGID_readData.GetBMICKLAGCCD(CBDOEDKIOJK_idx));
			}
			CLELJNJEGID_data.CBDOEDKIOJK_ev = CBDOEDKIOJK_list.ToArray();

			CLELJNJEGID_data.PLMHOKJIPJK_lin = CLELJNJEGID_readData.FLNOLLMJOKE;
			CLELJNJEGID_list.Add(CLELJNJEGID_data);
		}
		res_data.CLELJNJEGID = CLELJNJEGID_list.ToArray();

		List<DLMMECOIPDO> JNJPNLDJJMI_list = new List<DLMMECOIPDO>();
		for(int JNJPNLDJJMI_idx = 0; JNJPNLDJJMI_idx < res_readData.IIPLKGBCJMFLength; JNJPNLDJJMI_idx++)
		{
			OENLOOBJABF JNJPNLDJJMI_readData = res_readData.GetIIPLKGBCJMF(JNJPNLDJJMI_idx);
			DLMMECOIPDO JNJPNLDJJMI_data = new DLMMECOIPDO();

			JNJPNLDJJMI_data.ODMJFHDIGLP_cnd = JNJPNLDJJMI_readData.NCIKNCJLFBI;
			JNJPNLDJJMI_data.MJMPANIBFED_pid = JNJPNLDJJMI_readData.COPFAKAHEMN;
			JNJPNLDJJMI_data.AGNHPHEJKMK_tgt = JNJPNLDJJMI_readData.HLPHBGLMBIO;
			JNJPNLDJJMI_data.GBJFNGCDKPM_typ = JNJPNLDJJMI_readData.LPJPOOHJKAE;
			List<uint> KFCIJBLDHOK_list = new List<uint>();
			for(int KFCIJBLDHOK_idx = 0; KFCIJBLDHOK_idx < JNJPNLDJJMI_readData.CHGIONDFIKPLength; KFCIJBLDHOK_idx++)
			{
				KFCIJBLDHOK_list.Add(JNJPNLDJJMI_readData.GetCHGIONDFIKP(KFCIJBLDHOK_idx));
			}
			JNJPNLDJJMI_data.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list.ToArray();

			JNJPNLDJJMI_list.Add(JNJPNLDJJMI_data);
		}
		res_data.JNJPNLDJJMI = JNJPNLDJJMI_list.ToArray();

		List<OPNDNFJFFIO> FMMKFANHGMJ_list = new List<OPNDNFJFFIO>();
		for(int FMMKFANHGMJ_idx = 0; FMMKFANHGMJ_idx < res_readData.KCPALOBNNJILength; FMMKFANHGMJ_idx++)
		{
			DLDBCENIBOB FMMKFANHGMJ_readData = res_readData.GetKCPALOBNNJI(FMMKFANHGMJ_idx);
			OPNDNFJFFIO FMMKFANHGMJ_data = new OPNDNFJFFIO();

			FMMKFANHGMJ_data.JBFLEDKDFCO_cid = FMMKFANHGMJ_readData.HOENDPOGFIO;
			FMMKFANHGMJ_data.POOHGENNICD_p1 = FMMKFANHGMJ_readData.PBOCIEKNBCI;
			FMMKFANHGMJ_data.LLGBAPAACLL_p2 = FMMKFANHGMJ_readData.IHLNKPCMGNE;
			FMMKFANHGMJ_list.Add(FMMKFANHGMJ_data);
		}
		res_data.FMMKFANHGMJ = FMMKFANHGMJ_list.ToArray();

		List<BPEPDCHPBOC> HGFOLPABILK_list = new List<BPEPDCHPBOC>();
		for(int HGFOLPABILK_idx = 0; HGFOLPABILK_idx < res_readData.FOONGLJEAEGLength; HGFOLPABILK_idx++)
		{
			GMAHGBPDAPH HGFOLPABILK_readData = res_readData.GetFOONGLJEAEG(HGFOLPABILK_idx);
			BPEPDCHPBOC HGFOLPABILK_data = new BPEPDCHPBOC();

			HGFOLPABILK_data.PPFNGGCBJKC_id = HGFOLPABILK_readData.BBPHAPFBFHK;
			HGFOLPABILK_data.PLALNIIBLOF_en = HGFOLPABILK_readData.CFLMCGOJJJD;
			HGFOLPABILK_data.IJEKNCDIIAE_mver = HGFOLPABILK_readData.OFMGALJGDAO;
			HGFOLPABILK_data.MKDDOJOADMF = HGFOLPABILK_readData.DPHNIALHDJK;
			HGFOLPABILK_data.JKOIOLGLNFO = HGFOLPABILK_readData.HDGPONIHIBP;
			HGFOLPABILK_data.OGNCJAMBOCJ = HGFOLPABILK_readData.GFPLLOGJMHE;
			HGFOLPABILK_data.NDIOEOHDMLJ = HGFOLPABILK_readData.EJNIJBKBNGE;
			HGFOLPABILK_data.LFOHDJJHLJE = HGFOLPABILK_readData.DGMDFCHIBKD;
			HGFOLPABILK_list.Add(HGFOLPABILK_data);
		}
		res_data.HGFOLPABILK = HGFOLPABILK_list.ToArray();

		List<CLFBIKKLDOH> BGOAGJLBECM_list = new List<CLFBIKKLDOH>();
		for(int BGOAGJLBECM_idx = 0; BGOAGJLBECM_idx < res_readData.DFDGMAIMKMKLength; BGOAGJLBECM_idx++)
		{
			CCLAFODHKHA BGOAGJLBECM_readData = res_readData.GetDFDGMAIMKMK(BGOAGJLBECM_idx);
			CLFBIKKLDOH BGOAGJLBECM_data = new CLFBIKKLDOH();

			BGOAGJLBECM_data.PPFNGGCBJKC_id = BGOAGJLBECM_readData.BBPHAPFBFHK;
			BGOAGJLBECM_data.PLALNIIBLOF_en = BGOAGJLBECM_readData.CFLMCGOJJJD;
			BGOAGJLBECM_data.IJEKNCDIIAE_mver = BGOAGJLBECM_readData.OFMGALJGDAO;
			BGOAGJLBECM_data.MKDDOJOADMF = BGOAGJLBECM_readData.DPHNIALHDJK;
			BGOAGJLBECM_data.EPIBJMFJNDC = BGOAGJLBECM_readData.LNAHNBCMHIE;
			BGOAGJLBECM_data.GNPACBPKKCP = BGOAGJLBECM_readData.NGNFMDIGEFK;
			BGOAGJLBECM_data.GCFHEHAFHKO = BGOAGJLBECM_readData.FBEBMENBOCL;
			BGOAGJLBECM_data.KLCMNKMONJJ = BGOAGJLBECM_readData.JEJAIHHMGCK;
			BGOAGJLBECM_data.CGNBOKANMAD = BGOAGJLBECM_readData.FHJJMPPPMIL;
			BGOAGJLBECM_data.JOKNHEBCHFB = BGOAGJLBECM_readData.AJFMHHBCNKB;
			BGOAGJLBECM_list.Add(BGOAGJLBECM_data);
		}
		res_data.BGOAGJLBECM = BGOAGJLBECM_list.ToArray();

		List<DCOKBIMIIMA> OOBEHBMMJAC_list = new List<DCOKBIMIIMA>();
		for(int OOBEHBMMJAC_idx = 0; OOBEHBMMJAC_idx < res_readData.LPKLLIOACNFLength; OOBEHBMMJAC_idx++)
		{
			KJLKDFAJFHC OOBEHBMMJAC_readData = res_readData.GetLPKLLIOACNF(OOBEHBMMJAC_idx);
			DCOKBIMIIMA OOBEHBMMJAC_data = new DCOKBIMIIMA();

			OOBEHBMMJAC_data.PPFNGGCBJKC_id = OOBEHBMMJAC_readData.BBPHAPFBFHK;
			OOBEHBMMJAC_data.PLALNIIBLOF_en = OOBEHBMMJAC_readData.CFLMCGOJJJD;
			OOBEHBMMJAC_data.IJEKNCDIIAE_mver = OOBEHBMMJAC_readData.OFMGALJGDAO;
			OOBEHBMMJAC_data.MKDDOJOADMF = OOBEHBMMJAC_readData.DPHNIALHDJK;
			OOBEHBMMJAC_data.PFOIIAGCKON = OOBEHBMMJAC_readData.CIOGNKLHPDE;
			OOBEHBMMJAC_data.JKOIOLGLNFO = OOBEHBMMJAC_readData.HDGPONIHIBP;
			OOBEHBMMJAC_data.OGNCJAMBOCJ = OOBEHBMMJAC_readData.GFPLLOGJMHE;
			OOBEHBMMJAC_data.NDIOEOHDMLJ = OOBEHBMMJAC_readData.EJNIJBKBNGE;
			OOBEHBMMJAC_data.LFOHDJJHLJE = OOBEHBMMJAC_readData.DGMDFCHIBKD;
			OOBEHBMMJAC_data.NNONCOCHGMD_tt = OOBEHBMMJAC_readData.NABLNBMACHL;
			OOBEHBMMJAC_data.FCBDGLEPGFJ_mid = OOBEHBMMJAC_readData.BKKAFNHOJFE;
			OOBEHBMMJAC_data.BPBLHHFKBBG = OOBEHBMMJAC_readData.PGKFEHHDIBH;
			OOBEHBMMJAC_data.OCAMDLMPBGA_dv = OOBEHBMMJAC_readData.DDMBKEJNPJK;
			OOBEHBMMJAC_list.Add(OOBEHBMMJAC_data);
		}
		res_data.OOBEHBMMJAC = OOBEHBMMJAC_list.ToArray();

		List<OJEFFPDNEOP> NAAHEIAJLDP_list = new List<OJEFFPDNEOP>();
		for(int NAAHEIAJLDP_idx = 0; NAAHEIAJLDP_idx < res_readData.HCLJANFGCFHLength; NAAHEIAJLDP_idx++)
		{
			LCFOJIDKGIN NAAHEIAJLDP_readData = res_readData.GetHCLJANFGCFH(NAAHEIAJLDP_idx);
			OJEFFPDNEOP NAAHEIAJLDP_data = new OJEFFPDNEOP();

			NAAHEIAJLDP_data.ODMJFHDIGLP_cnd = NAAHEIAJLDP_readData.NCIKNCJLFBI;
			NAAHEIAJLDP_data.MJMPANIBFED_pid = NAAHEIAJLDP_readData.COPFAKAHEMN;
			NAAHEIAJLDP_data.AGNHPHEJKMK_tgt = NAAHEIAJLDP_readData.HLPHBGLMBIO;
			NAAHEIAJLDP_data.GBJFNGCDKPM_typ = NAAHEIAJLDP_readData.LPJPOOHJKAE;
			List<uint> KFCIJBLDHOK_list = new List<uint>();
			for(int KFCIJBLDHOK_idx = 0; KFCIJBLDHOK_idx < NAAHEIAJLDP_readData.CHGIONDFIKPLength; KFCIJBLDHOK_idx++)
			{
				KFCIJBLDHOK_list.Add(NAAHEIAJLDP_readData.GetCHGIONDFIKP(KFCIJBLDHOK_idx));
			}
			NAAHEIAJLDP_data.KFCIJBLDHOK_v1 = KFCIJBLDHOK_list.ToArray();

			NAAHEIAJLDP_list.Add(NAAHEIAJLDP_data);
		}
		res_data.NAAHEIAJLDP = NAAHEIAJLDP_list.ToArray();

		List<MEDPEPOBHGD> GCGNDMLDCML_list = new List<MEDPEPOBHGD>();
		for(int GCGNDMLDCML_idx = 0; GCGNDMLDCML_idx < res_readData.LGCEAMIIMJKLength; GCGNDMLDCML_idx++)
		{
			AMFPOBCCLMN GCGNDMLDCML_readData = res_readData.GetLGCEAMIIMJK(GCGNDMLDCML_idx);
			MEDPEPOBHGD GCGNDMLDCML_data = new MEDPEPOBHGD();

			GCGNDMLDCML_data.JBFLEDKDFCO_cid = GCGNDMLDCML_readData.HOENDPOGFIO;
			GCGNDMLDCML_data.POOHGENNICD_p1 = GCGNDMLDCML_readData.PBOCIEKNBCI;
			GCGNDMLDCML_data.LLGBAPAACLL_p2 = GCGNDMLDCML_readData.IHLNKPCMGNE;
			GCGNDMLDCML_list.Add(GCGNDMLDCML_data);
		}
		res_data.GCGNDMLDCML = GCGNDMLDCML_list.ToArray();

		List<DGMLKJPPPOC> NAJGALLJIBP_list = new List<DGMLKJPPPOC>();
		for(int NAJGALLJIBP_idx = 0; NAJGALLJIBP_idx < res_readData.PAFOHOKPIGHLength; NAJGALLJIBP_idx++)
		{
			IPIBGJJPKLO NAJGALLJIBP_readData = res_readData.GetPAFOHOKPIGH(NAJGALLJIBP_idx);
			DGMLKJPPPOC NAJGALLJIBP_data = new DGMLKJPPPOC();

			List<int> FDBOPFEOENF_list = new List<int>();
			for(int FDBOPFEOENF_idx = 0; FDBOPFEOENF_idx < NAJGALLJIBP_readData.FOGBEEHMDJMLength; FDBOPFEOENF_idx++)
			{
				FDBOPFEOENF_list.Add(NAJGALLJIBP_readData.GetFOGBEEHMDJM(FDBOPFEOENF_idx));
			}
			NAJGALLJIBP_data.FDBOPFEOENF_diva = FDBOPFEOENF_list.ToArray();

			List<int> DKEDLFLAKGC_list = new List<int>();
			for(int DKEDLFLAKGC_idx = 0; DKEDLFLAKGC_idx < NAJGALLJIBP_readData.BIMBNIBIMHALength; DKEDLFLAKGC_idx++)
			{
				DKEDLFLAKGC_list.Add(NAJGALLJIBP_readData.GetBIMBNIBIMHA(DKEDLFLAKGC_idx));
			}
			NAJGALLJIBP_data.DKEDLFLAKGC = DKEDLFLAKGC_list.ToArray();

			NAJGALLJIBP_list.Add(NAJGALLJIBP_data);
		}
		res_data.NAJGALLJIBP = NAJGALLJIBP_list.ToArray();

		List<OJEKDEDAIEP> BHGDNGHDDAC_list = new List<OJEKDEDAIEP>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			BANGFGHKPNP BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			OJEKDEDAIEP BHGDNGHDDAC_data = new OJEKDEDAIEP();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<NGKKAGAMMDF> MHGMDJNOLMI_list = new List<NGKKAGAMMDF>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			JEMGNNMPIAD MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			NGKKAGAMMDF MHGMDJNOLMI_data = new NGKKAGAMMDF();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<MFGCKJCKFDM> CHKNAMIFECK_list = new List<MFGCKJCKFDM>();
		for(int CHKNAMIFECK_idx = 0; CHKNAMIFECK_idx < res_readData.PMKJKCPFLELLength; CHKNAMIFECK_idx++)
		{
			KMMGHIGKELN CHKNAMIFECK_readData = res_readData.GetPMKJKCPFLEL(CHKNAMIFECK_idx);
			MFGCKJCKFDM CHKNAMIFECK_data = new MFGCKJCKFDM();

			CHKNAMIFECK_data.MJMPANIBFED_pid = CHKNAMIFECK_readData.COPFAKAHEMN;
			CHKNAMIFECK_data.ODMJFHDIGLP_cnd = CHKNAMIFECK_readData.NCIKNCJLFBI;
			CHKNAMIFECK_data.JHGHCMEBOOL = CHKNAMIFECK_readData.EEEHIFGPKON;
			CHKNAMIFECK_data.BEJMJAHGAFH = CHKNAMIFECK_readData.ANDMOLFOEDG;
			CHKNAMIFECK_list.Add(CHKNAMIFECK_data);
		}
		res_data.CHKNAMIFECK = CHKNAMIFECK_list.ToArray();

		List<GOIHGONJPNC> FIMINKADAPC_list = new List<GOIHGONJPNC>();
		for(int FIMINKADAPC_idx = 0; FIMINKADAPC_idx < res_readData.KFLDFHANEKKLength; FIMINKADAPC_idx++)
		{
			OLKBCLJBFAA FIMINKADAPC_readData = res_readData.GetKFLDFHANEKK(FIMINKADAPC_idx);
			GOIHGONJPNC FIMINKADAPC_data = new GOIHGONJPNC();

			List<int> NANNGLGOFKH_list = new List<int>();
			for(int NANNGLGOFKH_idx = 0; NANNGLGOFKH_idx < FIMINKADAPC_readData.KPONLGHOAMBLength; NANNGLGOFKH_idx++)
			{
				NANNGLGOFKH_list.Add(FIMINKADAPC_readData.GetKPONLGHOAMB(NANNGLGOFKH_idx));
			}
			FIMINKADAPC_data.NANNGLGOFKH_value = NANNGLGOFKH_list.ToArray();

			FIMINKADAPC_data.NNDBJGDFEEM_Min = FIMINKADAPC_readData.CCIHMCAPHCB;
			FIMINKADAPC_data.FDBOPFEOENF_diva = FIMINKADAPC_readData.PIFAMBCEMKL;
			FIMINKADAPC_list.Add(FIMINKADAPC_data);
		}
		res_data.FIMINKADAPC = FIMINKADAPC_list.ToArray();

		List<HPCMDEIGDDH> GDFFALAJFNP_list = new List<HPCMDEIGDDH>();
		for(int GDFFALAJFNP_idx = 0; GDFFALAJFNP_idx < res_readData.AOONDLEGAAALength; GDFFALAJFNP_idx++)
		{
			GAJBGNNNHCP GDFFALAJFNP_readData = res_readData.GetAOONDLEGAAA(GDFFALAJFNP_idx);
			HPCMDEIGDDH GDFFALAJFNP_data = new HPCMDEIGDDH();

			List<int> KCOHMHFBDKF_list = new List<int>();
			for(int KCOHMHFBDKF_idx = 0; KCOHMHFBDKF_idx < GDFFALAJFNP_readData.PHGKBJDEJKILength; KCOHMHFBDKF_idx++)
			{
				KCOHMHFBDKF_list.Add(GDFFALAJFNP_readData.GetPHGKBJDEJKI(KCOHMHFBDKF_idx));
			}
			GDFFALAJFNP_data.KCOHMHFBDKF_Value1 = KCOHMHFBDKF_list.ToArray();

			List<int> HLMMBNCIIAC_list = new List<int>();
			for(int HLMMBNCIIAC_idx = 0; HLMMBNCIIAC_idx < GDFFALAJFNP_readData.OOFMHMCDPEMLength; HLMMBNCIIAC_idx++)
			{
				HLMMBNCIIAC_list.Add(GDFFALAJFNP_readData.GetOOFMHMCDPEM(HLMMBNCIIAC_idx));
			}
			GDFFALAJFNP_data.HLMMBNCIIAC_Value2 = HLMMBNCIIAC_list.ToArray();

			GDFFALAJFNP_data.DOOGFEGEKLG_max = GDFFALAJFNP_readData.GEJGMBBCFEE;
			GDFFALAJFNP_list.Add(GDFFALAJFNP_data);
		}
		res_data.GDFFALAJFNP = GDFFALAJFNP_list.ToArray();

		List<NLLCPFIHFFA> KBFEMKJBHBL_list = new List<NLLCPFIHFFA>();
		for(int KBFEMKJBHBL_idx = 0; KBFEMKJBHBL_idx < res_readData.BEINKIKDHCOLength; KBFEMKJBHBL_idx++)
		{
			JIIFKJGKCNM KBFEMKJBHBL_readData = res_readData.GetBEINKIKDHCO(KBFEMKJBHBL_idx);
			NLLCPFIHFFA KBFEMKJBHBL_data = new NLLCPFIHFFA();

			KBFEMKJBHBL_data.PPFNGGCBJKC_id = KBFEMKJBHBL_readData.BBPHAPFBFHK;
			List<int> LGFLNOJDHHC_list = new List<int>();
			for(int LGFLNOJDHHC_idx = 0; LGFLNOJDHHC_idx < KBFEMKJBHBL_readData.JNFHLJCMAAALength; LGFLNOJDHHC_idx++)
			{
				LGFLNOJDHHC_list.Add(KBFEMKJBHBL_readData.GetJNFHLJCMAAA(LGFLNOJDHHC_idx));
			}
			KBFEMKJBHBL_data.LGFLNOJDHHC_Targets = LGFLNOJDHHC_list.ToArray();

			KBFEMKJBHBL_list.Add(KBFEMKJBHBL_data);
		}
		res_data.KBFEMKJBHBL = KBFEMKJBHBL_list.ToArray();

		return res_data;
	}
}
