using FlatBuffers;
using System.Collections.Generic;

public class LJBDGKFPGHH
{
	public string OPFGFINHFCE { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public uint HFNIHKOAMGC { get; set; } // 0x14 FHBGLLIFKHM ECGBAIBHGFP CGCGLFDKHPC
	public string OCGFKMHNEOF { get; set; } // 0x18 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public string[] MPCAGEPEJJJ { get; set; } // 0x1C OINCEAPBAHC PLBHMKFJNPJ BCEIHFNLBIM
	public uint MOEKELIIDEO { get; set; } // 0x20 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND { get; set; } // 0x24 JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint EHHFFKAFOMC { get; set; } // 0x28 MDCEFKJDJIJ EMIPFAAPLIB JHGMJLNGOGD
	public uint HPNOGLIFJOP { get; set; } // 0x2C LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE { get; set; } // 0x30 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF { get; set; } // 0x34 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI { get; set; } // 0x38 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH { get; set; } // 0x3C HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JBFDHOIKAIK { get; set; } // 0x40 HKLAIJDEMID GBNKCHLEGPH AAKNFOAHCCI
	public uint KHIKEGLBGAF { get; set; } // 0x44 OAPPFIGOMHO FAHFDEFDLMH OJJMIBDFGBG
	public uint DPJCFLKFEPN { get; set; } // 0x48 IPODKLGLHPC MEAAAGCCAPI GNMJKJHPIOG
	public uint[] EEOGPJJCKHH { get; set; } // 0x4C CPNKKFMLHFL BBBPKCMKJEF CDMJOOGMGNP
	public uint JMJDLDEIFKE { get; set; } // 0x50 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO { get; set; } // 0x54 IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x58 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x5C HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public int MJBKGOJBPAD { get; set; } // 0x60 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public uint MPKNCMEAMLO { get; set; } // 0x64 PCGLIOIAEPM JDFHGPLACGI NEFEJGOEIMM
	public uint AHKPNPNOAMO { get; set; } // 0x68 AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
	public string FEMMDNIELFC { get; set; } // 0x6C GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint HKKNEAGCIEB { get; set; } // 0x70 DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI { get; set; } // 0x74 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public string OMCAOJJGOGG { get; set; } // 0x78 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM { get; set; } // 0x7C AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP { get; set; } // 0x80 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC { get; set; } // 0x84 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int EKJFNHHKBPL { get; set; } // 0x88 BPPNFOAFCPE BONLIFKCIFO HBFFBCJHJAC
}
public class PODNPHFIDHP
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FOILNHKHHDF { get; set; } // 0xC LNNCNOIGMGM FOFBHPJDHFO LHPMDDKPJDP
	public int[] AIHOJKFNEEN { get; set; } // 0x10 GGBFCEFNCFM BGFIPHMMOGA DHAIHODDOGM
	public uint[] BFINGCJHOHI { get; set; } // 0x14 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public uint[] JJHPDDPKBHF { get; set; } // 0x18 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public int JOPPFEHKNFO { get; set; } // 0x1C LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
	public uint[] HJAFPEBIBOP { get; set; } // 0x20 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class AFEHHCKJJGB
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MPLGPBNJDJB { get; set; } // 0x10 GNKPHDHIMAC KADAEAOKJNE MBKFNLHPNPP
	public int PDBPFJJCADD { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class KIJLAHILELO
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
	public uint HJAFPEBIBOP { get; set; } // 0x68 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class EOBMLPFEJLM
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int PDBPFJJCADD { get; set; } // 0x10 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x14 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class DBLFDPNEFPM
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint LJELGFAFGAB { get; set; } // 0xC CJCOPPAFPKE APHFJDOOLCK KBEAJHMCGPM
	public uint KNEDJFLCCLN { get; set; } // 0x10 HJMKHFAHBIO DKJNGOIGJGH EOMMBJGKKJI
	public uint MBAMIOJNGBD { get; set; } // 0x14 PJHOHPBOIDJ NJBKAFBFJML IGAFGHBHMIF
}
public class GLABDNJIHCE
{
	public uint LKIFDCEKDCK { get; set; } // 0x8 IAHMAGLCEBN GOKMANFHFPC ICJKOKGFNLI
	public uint DKHIHHMOIKM { get; set; } // 0xC DDCGLGKFHPP OCOHLFAFINM DPEOFJJLPML
}
public class BIBCILCCAAD
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint ECLAOLBGCDD { get; set; } // 0xC GFELDHIDJDM DPILCBJHCPP BHCFGBAPKBF
	public uint OMCOIBDHOCF { get; set; } // 0x10 DOPEHLFODNP CFNIHNGBFCB OLFHCIKJJIF
	public uint JBGEEPFKIGG { get; set; } // 0x14 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class PLPBLFHKOGP
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int BEBJKJKBOGH { get; set; } // 0x14 MCIJNMKFMDB DIAPHCJBPFD IHAIKPNEEJE
	public int FNEIADJMHHO { get; set; } // 0x18 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public int EICJBAEDMNM { get; set; } // 0x1C GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class GHNFKHHNJFP
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class AEANCDLNPNA
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class LDJDFLHGBFG
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KFCIJBLDHOK { get; set; } // 0xC JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int JLEIHOEGMOP { get; set; } // 0x10 JLNAMGLBPME JJGFFGDDFPA LIIFHDMHLHP
}
public class NEEFDIIDPHK
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GBJFNGCDKPM { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int MAFAIIHJAFG { get; set; } // 0x14 FIINMMHBBJF LLNFMLKMFKB PCICDCAILIF
}
public class LCFFJMJPPFI
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PDBPFJJCADD { get; set; } // 0xC PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x10 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public string FEMMDNIELFC { get; set; } // 0x14 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
}
public class JGBFIHBFBDA
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int CNKFPJCGNFE { get; set; } // 0xC OGPCJNOKMAM GJBOGOFHGNP GJDGIDCMJMH
	public int GNFBMCGMCFO { get; set; } // 0x10 LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x14 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class KPHKMOFOFAO
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GNFBMCGMCFO { get; set; } // 0xC LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x10 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class CDPDAALCOAE
{
	public int KHPHAAMGMJP { get; set; } // 0x8 FHLAGLBMFHE ABFDDKBBPCH MHDOIIEMDEH
	public int OFIAENKCJME { get; set; } // 0xC NHHGGLNCELI KADLAKFANGA AIDAPNCEPOB
	public int[] JMLCLHHLJHM { get; set; } // 0x10 HCOPKKMMEAL KCJKEEAILGB EGEABIGCJJK
}
public class FOKPKJFHNLO
{
	public LJBDGKFPGHH HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public PODNPHFIDHP[] MCHFABAKPMH { get; set; } // 0xC BFBKDKPKLMM IPDEGCCJALP HHNBEKGDAPD
	public AFEHHCKJJGB[] GHIHAGAOPNC { get; set; } // 0x10 CNAPBHHKEPH OHCBAEGAKOH OIDPGMCLNBF
	public KIJLAHILELO[] MDDOGIAFDEI { get; set; } // 0x14 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public EOBMLPFEJLM[] DGBJMMJALMH { get; set; } // 0x18 MONCBBEAOEA EOGLPBGMBGJ APBHGLFNKDK
	public DBLFDPNEFPM[] MPPGCHJPPKM { get; set; } // 0x1C HDNDMADIBDH HIGNLBIIGFK HMCLNNKCIBA
	public GLABDNJIHCE[] EENKKKDBABF { get; set; } // 0x20 KEHABBAJMBG LKCKCMFGKED GLEBNICMKPE
	public BIBCILCCAAD[] DHDJOPFCOPP { get; set; } // 0x24 AFAKFPAFLLE OEFNBNONNDF GCEIGMLNIOL
	public PLPBLFHKOGP[] GICHIKNDMHE { get; set; } // 0x28 POAHGOPFCKM OHJKAOJEMAK EPNHIJPELNB
	public GHNFKHHNJFP[] BHGDNGHDDAC { get; set; } // 0x2C JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public AEANCDLNPNA[] MHGMDJNOLMI { get; set; } // 0x30 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public LDJDFLHGBFG[] KIEKMCKCMGD { get; set; } // 0x34 AHOFIJDMDAO EEMBMMJIHPE CDHPBECJGGO
	public NEEFDIIDPHK[] MHKNGJMEGFI { get; set; } // 0x38 DGMLFJKGMLO DJAALDIHICI ILMEEBDMNBJ
	public LCFFJMJPPFI[] IHNBOEPLJKE { get; set; } // 0x3C MMGGONDGLOL EMLHCNDOCCP GKPFNDEHLJD
	public JGBFIHBFBDA[] OLACFKILCFD { get; set; } // 0x40 ODAEGEAACIA KCGGGPCDEPK ANKJOEMLFCI
	public KPHKMOFOFAO[] MIOCOKLMLBD { get; set; } // 0x44 COILMDCEJLD MNIALHMNHFM OGLAMDPDFCD
	public CDPDAALCOAE[] IEJLJIHIDJC { get; set; } // 0x48 CDHGOELCBFB DGNNDIPELAP BFHEABPGGHO
	public static FOKPKJFHNLO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x13F56AC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		NMCBIDLKHED res_readData = NMCBIDLKHED.GetRootAsNMCBIDLKHED(buffer);
		FOKPKJFHNLO res_data = new FOKPKJFHNLO();

		NDELGBLMJJO HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		LJBDGKFPGHH HMBHNLCFDIH_data = new LJBDGKFPGHH();

		HMBHNLCFDIH_data.OPFGFINHFCE = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.HFNIHKOAMGC = HMBHNLCFDIH_readData.HEMLBADKAOA;
		HMBHNLCFDIH_data.OCGFKMHNEOF = HMBHNLCFDIH_readData.MKDFHLALNAF;
		List<string> MPCAGEPEJJJ_list = new List<string>();
		for(int MPCAGEPEJJJ_idx = 0; MPCAGEPEJJJ_idx < HMBHNLCFDIH_readData.NLPMPPCENKDLength; MPCAGEPEJJJ_idx++)
		{
			MPCAGEPEJJJ_list.Add(HMBHNLCFDIH_readData.GetNLPMPPCENKD(MPCAGEPEJJJ_idx));
		}
		HMBHNLCFDIH_data.MPCAGEPEJJJ = MPCAGEPEJJJ_list.ToArray();

		HMBHNLCFDIH_data.MOEKELIIDEO = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.EHHFFKAFOMC = HMBHNLCFDIH_readData.DEPHCHOBAJG;
		HMBHNLCFDIH_data.HPNOGLIFJOP = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JBFDHOIKAIK = HMBHNLCFDIH_readData.IDMMPIIIPLL;
		HMBHNLCFDIH_data.KHIKEGLBGAF = HMBHNLCFDIH_readData.HKPPDACCCOH;
		HMBHNLCFDIH_data.DPJCFLKFEPN = HMBHNLCFDIH_readData.NAMFJMCKFIF;
		List<uint> EEOGPJJCKHH_list = new List<uint>();
		for(int EEOGPJJCKHH_idx = 0; EEOGPJJCKHH_idx < HMBHNLCFDIH_readData.EBFEIMNOLHPLength; EEOGPJJCKHH_idx++)
		{
			EEOGPJJCKHH_list.Add(HMBHNLCFDIH_readData.GetEBFEIMNOLHP(EEOGPJJCKHH_idx));
		}
		HMBHNLCFDIH_data.EEOGPJJCKHH = EEOGPJJCKHH_list.ToArray();

		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.MJBKGOJBPAD = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.MPKNCMEAMLO = HMBHNLCFDIH_readData.ALNLBALBCJK;
		HMBHNLCFDIH_data.AHKPNPNOAMO = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		HMBHNLCFDIH_data.FEMMDNIELFC = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKKNEAGCIEB = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI = JHPCPNJJHLI_list.ToArray();

		HMBHNLCFDIH_data.OMCAOJJGOGG = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.EKJFNHHKBPL = HMBHNLCFDIH_readData.HFKHLKGAJEL;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<PODNPHFIDHP> MCHFABAKPMH_list = new List<PODNPHFIDHP>();
		for(int MCHFABAKPMH_idx = 0; MCHFABAKPMH_idx < res_readData.KJFDCEGGPPHLength; MCHFABAKPMH_idx++)
		{
			JPHCKOHCJKL MCHFABAKPMH_readData = res_readData.GetKJFDCEGGPPH(MCHFABAKPMH_idx);
			PODNPHFIDHP MCHFABAKPMH_data = new PODNPHFIDHP();

			MCHFABAKPMH_data.PPFNGGCBJKC = MCHFABAKPMH_readData.BBPHAPFBFHK;
			MCHFABAKPMH_data.FOILNHKHHDF = MCHFABAKPMH_readData.HJNPKHJJDBB;
			List<int> AIHOJKFNEEN_list = new List<int>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < MCHFABAKPMH_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(MCHFABAKPMH_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			MCHFABAKPMH_data.AIHOJKFNEEN = AIHOJKFNEEN_list.ToArray();

			List<uint> BFINGCJHOHI_list = new List<uint>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < MCHFABAKPMH_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(MCHFABAKPMH_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			MCHFABAKPMH_data.BFINGCJHOHI = BFINGCJHOHI_list.ToArray();

			List<uint> JJHPDDPKBHF_list = new List<uint>();
			for(int JJHPDDPKBHF_idx = 0; JJHPDDPKBHF_idx < MCHFABAKPMH_readData.OOJBHHPJONJLength; JJHPDDPKBHF_idx++)
			{
				JJHPDDPKBHF_list.Add(MCHFABAKPMH_readData.GetOOJBHHPJONJ(JJHPDDPKBHF_idx));
			}
			MCHFABAKPMH_data.JJHPDDPKBHF = JJHPDDPKBHF_list.ToArray();

			MCHFABAKPMH_data.JOPPFEHKNFO = MCHFABAKPMH_readData.ALPALMJMJJK;
			List<uint> HJAFPEBIBOP_list = new List<uint>();
			for(int HJAFPEBIBOP_idx = 0; HJAFPEBIBOP_idx < MCHFABAKPMH_readData.PODPGCKCBEOLength; HJAFPEBIBOP_idx++)
			{
				HJAFPEBIBOP_list.Add(MCHFABAKPMH_readData.GetPODPGCKCBEO(HJAFPEBIBOP_idx));
			}
			MCHFABAKPMH_data.HJAFPEBIBOP = HJAFPEBIBOP_list.ToArray();

			MCHFABAKPMH_list.Add(MCHFABAKPMH_data);
		}
		res_data.MCHFABAKPMH = MCHFABAKPMH_list.ToArray();

		List<AFEHHCKJJGB> GHIHAGAOPNC_list = new List<AFEHHCKJJGB>();
		for(int GHIHAGAOPNC_idx = 0; GHIHAGAOPNC_idx < res_readData.AJMKEFMPKHBLength; GHIHAGAOPNC_idx++)
		{
			MOEAENJLEGI GHIHAGAOPNC_readData = res_readData.GetAJMKEFMPKHB(GHIHAGAOPNC_idx);
			AFEHHCKJJGB GHIHAGAOPNC_data = new AFEHHCKJJGB();

			GHIHAGAOPNC_data.PPFNGGCBJKC = GHIHAGAOPNC_readData.BBPHAPFBFHK;
			GHIHAGAOPNC_data.PLALNIIBLOF = GHIHAGAOPNC_readData.CFLMCGOJJJD;
			GHIHAGAOPNC_data.MPLGPBNJDJB = GHIHAGAOPNC_readData.IAPFGOHKAGE;
			GHIHAGAOPNC_data.PDBPFJJCADD = GHIHAGAOPNC_readData.NJLJEKDBPCH;
			GHIHAGAOPNC_data.FDBNFFNFOND = GHIHAGAOPNC_readData.MAOAGDBDBIB;
			GHIHAGAOPNC_list.Add(GHIHAGAOPNC_data);
		}
		res_data.GHIHAGAOPNC = GHIHAGAOPNC_list.ToArray();

		List<KIJLAHILELO> MDDOGIAFDEI_list = new List<KIJLAHILELO>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			MINHCKEGNDL MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			KIJLAHILELO MDDOGIAFDEI_data = new KIJLAHILELO();

			MDDOGIAFDEI_data.PPFNGGCBJKC = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_data.HJAFPEBIBOP = MDDOGIAFDEI_readData.HBHEHJDPEBI;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<EOBMLPFEJLM> DGBJMMJALMH_list = new List<EOBMLPFEJLM>();
		for(int DGBJMMJALMH_idx = 0; DGBJMMJALMH_idx < res_readData.EMBEBHJKMNCLength; DGBJMMJALMH_idx++)
		{
			HLJHIMHEACC DGBJMMJALMH_readData = res_readData.GetEMBEBHJKMNC(DGBJMMJALMH_idx);
			EOBMLPFEJLM DGBJMMJALMH_data = new EOBMLPFEJLM();

			DGBJMMJALMH_data.PPFNGGCBJKC = DGBJMMJALMH_readData.BBPHAPFBFHK;
			DGBJMMJALMH_data.JBGEEPFKIGG = DGBJMMJALMH_readData.KJFEBMBHKOC;
			DGBJMMJALMH_data.PDBPFJJCADD = DGBJMMJALMH_readData.NJLJEKDBPCH;
			DGBJMMJALMH_data.FDBNFFNFOND = DGBJMMJALMH_readData.MAOAGDBDBIB;
			DGBJMMJALMH_list.Add(DGBJMMJALMH_data);
		}
		res_data.DGBJMMJALMH = DGBJMMJALMH_list.ToArray();

		List<DBLFDPNEFPM> MPPGCHJPPKM_list = new List<DBLFDPNEFPM>();
		for(int MPPGCHJPPKM_idx = 0; MPPGCHJPPKM_idx < res_readData.POCJDCJLODDLength; MPPGCHJPPKM_idx++)
		{
			KDDOEACKIHA MPPGCHJPPKM_readData = res_readData.GetPOCJDCJLODD(MPPGCHJPPKM_idx);
			DBLFDPNEFPM MPPGCHJPPKM_data = new DBLFDPNEFPM();

			MPPGCHJPPKM_data.PPFNGGCBJKC = MPPGCHJPPKM_readData.BBPHAPFBFHK;
			MPPGCHJPPKM_data.LJELGFAFGAB = MPPGCHJPPKM_readData.FHLKEIBOFNN;
			MPPGCHJPPKM_data.KNEDJFLCCLN = MPPGCHJPPKM_readData.EGEFMJCLNDM;
			MPPGCHJPPKM_data.MBAMIOJNGBD = MPPGCHJPPKM_readData.KDPKPOBKKMJ;
			MPPGCHJPPKM_list.Add(MPPGCHJPPKM_data);
		}
		res_data.MPPGCHJPPKM = MPPGCHJPPKM_list.ToArray();

		List<GLABDNJIHCE> EENKKKDBABF_list = new List<GLABDNJIHCE>();
		for(int EENKKKDBABF_idx = 0; EENKKKDBABF_idx < res_readData.LFKGJNLPMAELength; EENKKKDBABF_idx++)
		{
			IDOIMCLBFJA EENKKKDBABF_readData = res_readData.GetLFKGJNLPMAE(EENKKKDBABF_idx);
			GLABDNJIHCE EENKKKDBABF_data = new GLABDNJIHCE();

			EENKKKDBABF_data.LKIFDCEKDCK = EENKKKDBABF_readData.JKDAMKCJMLD;
			EENKKKDBABF_data.DKHIHHMOIKM = EENKKKDBABF_readData.DJBJGNJAHHP;
			EENKKKDBABF_list.Add(EENKKKDBABF_data);
		}
		res_data.EENKKKDBABF = EENKKKDBABF_list.ToArray();

		List<BIBCILCCAAD> DHDJOPFCOPP_list = new List<BIBCILCCAAD>();
		for(int DHDJOPFCOPP_idx = 0; DHDJOPFCOPP_idx < res_readData.FHJIGCFBFENLength; DHDJOPFCOPP_idx++)
		{
			JFGEKMJJBAO DHDJOPFCOPP_readData = res_readData.GetFHJIGCFBFEN(DHDJOPFCOPP_idx);
			BIBCILCCAAD DHDJOPFCOPP_data = new BIBCILCCAAD();

			DHDJOPFCOPP_data.PPFNGGCBJKC = DHDJOPFCOPP_readData.BBPHAPFBFHK;
			DHDJOPFCOPP_data.ECLAOLBGCDD = DHDJOPFCOPP_readData.AOLCNACKIBK;
			DHDJOPFCOPP_data.OMCOIBDHOCF = DHDJOPFCOPP_readData.AECGHGOLNKL;
			DHDJOPFCOPP_data.JBGEEPFKIGG = DHDJOPFCOPP_readData.KJFEBMBHKOC;
			DHDJOPFCOPP_list.Add(DHDJOPFCOPP_data);
		}
		res_data.DHDJOPFCOPP = DHDJOPFCOPP_list.ToArray();

		List<PLPBLFHKOGP> GICHIKNDMHE_list = new List<PLPBLFHKOGP>();
		for(int GICHIKNDMHE_idx = 0; GICHIKNDMHE_idx < res_readData.OOMKKGEMBMOLength; GICHIKNDMHE_idx++)
		{
			CIJEJAKKDMB GICHIKNDMHE_readData = res_readData.GetOOMKKGEMBMO(GICHIKNDMHE_idx);
			PLPBLFHKOGP GICHIKNDMHE_data = new PLPBLFHKOGP();

			GICHIKNDMHE_data.PPFNGGCBJKC = GICHIKNDMHE_readData.BBPHAPFBFHK;
			GICHIKNDMHE_data.PLALNIIBLOF = GICHIKNDMHE_readData.CFLMCGOJJJD;
			GICHIKNDMHE_data.JBGEEPFKIGG = GICHIKNDMHE_readData.KJFEBMBHKOC;
			GICHIKNDMHE_data.BEBJKJKBOGH = GICHIKNDMHE_readData.IBDFJIDNDJH;
			GICHIKNDMHE_data.FNEIADJMHHO = GICHIKNDMHE_readData.GLIIHLOLPEF;
			GICHIKNDMHE_data.EICJBAEDMNM = GICHIKNDMHE_readData.KMEODDMBHHE;
			GICHIKNDMHE_list.Add(GICHIKNDMHE_data);
		}
		res_data.GICHIKNDMHE = GICHIKNDMHE_list.ToArray();

		List<GHNFKHHNJFP> BHGDNGHDDAC_list = new List<GHNFKHHNJFP>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			HDMKPCIFCKM BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			GHNFKHHNJFP BHGDNGHDDAC_data = new GHNFKHHNJFP();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<AEANCDLNPNA> MHGMDJNOLMI_list = new List<AEANCDLNPNA>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			POCLCIIAOED MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			AEANCDLNPNA MHGMDJNOLMI_data = new AEANCDLNPNA();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<LDJDFLHGBFG> KIEKMCKCMGD_list = new List<LDJDFLHGBFG>();
		for(int KIEKMCKCMGD_idx = 0; KIEKMCKCMGD_idx < res_readData.FBAHAFKCMMHLength; KIEKMCKCMGD_idx++)
		{
			GIENJNNNCMN KIEKMCKCMGD_readData = res_readData.GetFBAHAFKCMMH(KIEKMCKCMGD_idx);
			LDJDFLHGBFG KIEKMCKCMGD_data = new LDJDFLHGBFG();

			KIEKMCKCMGD_data.PPFNGGCBJKC = KIEKMCKCMGD_readData.BBPHAPFBFHK;
			KIEKMCKCMGD_data.KFCIJBLDHOK = KIEKMCKCMGD_readData.MCJNHPMBPIJ;
			KIEKMCKCMGD_data.JLEIHOEGMOP = KIEKMCKCMGD_readData.MGJKFKDICGC;
			KIEKMCKCMGD_list.Add(KIEKMCKCMGD_data);
		}
		res_data.KIEKMCKCMGD = KIEKMCKCMGD_list.ToArray();

		List<NEEFDIIDPHK> MHKNGJMEGFI_list = new List<NEEFDIIDPHK>();
		for(int MHKNGJMEGFI_idx = 0; MHKNGJMEGFI_idx < res_readData.GGKDJGGAFKALength; MHKNGJMEGFI_idx++)
		{
			FNEOAPMLFFD MHKNGJMEGFI_readData = res_readData.GetGGKDJGGAFKA(MHKNGJMEGFI_idx);
			NEEFDIIDPHK MHKNGJMEGFI_data = new NEEFDIIDPHK();

			MHKNGJMEGFI_data.PPFNGGCBJKC = MHKNGJMEGFI_readData.BBPHAPFBFHK;
			MHKNGJMEGFI_data.GBJFNGCDKPM = MHKNGJMEGFI_readData.LPJPOOHJKAE;
			MHKNGJMEGFI_data.JBGEEPFKIGG = MHKNGJMEGFI_readData.KJFEBMBHKOC;
			MHKNGJMEGFI_data.MAFAIIHJAFG = MHKNGJMEGFI_readData.LAIEPFCPDLK;
			MHKNGJMEGFI_list.Add(MHKNGJMEGFI_data);
		}
		res_data.MHKNGJMEGFI = MHKNGJMEGFI_list.ToArray();

		List<LCFFJMJPPFI> IHNBOEPLJKE_list = new List<LCFFJMJPPFI>();
		for(int IHNBOEPLJKE_idx = 0; IHNBOEPLJKE_idx < res_readData.JHDOILHEBOGLength; IHNBOEPLJKE_idx++)
		{
			ICAMEMFMEPB IHNBOEPLJKE_readData = res_readData.GetJHDOILHEBOG(IHNBOEPLJKE_idx);
			LCFFJMJPPFI IHNBOEPLJKE_data = new LCFFJMJPPFI();

			IHNBOEPLJKE_data.PPFNGGCBJKC = IHNBOEPLJKE_readData.BBPHAPFBFHK;
			IHNBOEPLJKE_data.PDBPFJJCADD = IHNBOEPLJKE_readData.NJLJEKDBPCH;
			IHNBOEPLJKE_data.FDBNFFNFOND = IHNBOEPLJKE_readData.MAOAGDBDBIB;
			IHNBOEPLJKE_data.FEMMDNIELFC = IHNBOEPLJKE_readData.NNKLANONDOM;
			IHNBOEPLJKE_list.Add(IHNBOEPLJKE_data);
		}
		res_data.IHNBOEPLJKE = IHNBOEPLJKE_list.ToArray();

		List<JGBFIHBFBDA> OLACFKILCFD_list = new List<JGBFIHBFBDA>();
		for(int OLACFKILCFD_idx = 0; OLACFKILCFD_idx < res_readData.HDNMEPFHLNFLength; OLACFKILCFD_idx++)
		{
			EPOOCHGHFNI OLACFKILCFD_readData = res_readData.GetHDNMEPFHLNF(OLACFKILCFD_idx);
			JGBFIHBFBDA OLACFKILCFD_data = new JGBFIHBFBDA();

			OLACFKILCFD_data.PPFNGGCBJKC = OLACFKILCFD_readData.BBPHAPFBFHK;
			OLACFKILCFD_data.CNKFPJCGNFE = OLACFKILCFD_readData.DPFDOIIOICA;
			OLACFKILCFD_data.GNFBMCGMCFO = OLACFKILCFD_readData.GEAIPAEKLNF;
			OLACFKILCFD_data.BFFGFAMJAIG = OLACFKILCFD_readData.JGILGOILJNK;
			OLACFKILCFD_list.Add(OLACFKILCFD_data);
		}
		res_data.OLACFKILCFD = OLACFKILCFD_list.ToArray();

		List<KPHKMOFOFAO> MIOCOKLMLBD_list = new List<KPHKMOFOFAO>();
		for(int MIOCOKLMLBD_idx = 0; MIOCOKLMLBD_idx < res_readData.OLLJCDPOAAILength; MIOCOKLMLBD_idx++)
		{
			PCEMLBKHFFI MIOCOKLMLBD_readData = res_readData.GetOLLJCDPOAAI(MIOCOKLMLBD_idx);
			KPHKMOFOFAO MIOCOKLMLBD_data = new KPHKMOFOFAO();

			MIOCOKLMLBD_data.PPFNGGCBJKC = MIOCOKLMLBD_readData.BBPHAPFBFHK;
			MIOCOKLMLBD_data.GNFBMCGMCFO = MIOCOKLMLBD_readData.GEAIPAEKLNF;
			MIOCOKLMLBD_data.BFFGFAMJAIG = MIOCOKLMLBD_readData.JGILGOILJNK;
			MIOCOKLMLBD_list.Add(MIOCOKLMLBD_data);
		}
		res_data.MIOCOKLMLBD = MIOCOKLMLBD_list.ToArray();

		List<CDPDAALCOAE> IEJLJIHIDJC_list = new List<CDPDAALCOAE>();
		for(int IEJLJIHIDJC_idx = 0; IEJLJIHIDJC_idx < res_readData.BHNBMLKMLGNLength; IEJLJIHIDJC_idx++)
		{
			MANCFDNPDOD IEJLJIHIDJC_readData = res_readData.GetBHNBMLKMLGN(IEJLJIHIDJC_idx);
			CDPDAALCOAE IEJLJIHIDJC_data = new CDPDAALCOAE();

			IEJLJIHIDJC_data.KHPHAAMGMJP = IEJLJIHIDJC_readData.OEBLGFLPMNE;
			IEJLJIHIDJC_data.OFIAENKCJME = IEJLJIHIDJC_readData.BJELMJJFMBI;
			List<int> JMLCLHHLJHM_list = new List<int>();
			for(int JMLCLHHLJHM_idx = 0; JMLCLHHLJHM_idx < IEJLJIHIDJC_readData.IHNCJBFCAAILength; JMLCLHHLJHM_idx++)
			{
				JMLCLHHLJHM_list.Add(IEJLJIHIDJC_readData.GetIHNCJBFCAAI(JMLCLHHLJHM_idx));
			}
			IEJLJIHIDJC_data.JMLCLHHLJHM = JMLCLHHLJHM_list.ToArray();

			IEJLJIHIDJC_list.Add(IEJLJIHIDJC_data);
		}
		res_data.IEJLJIHIDJC = IEJLJIHIDJC_list.ToArray();

		return res_data;
	}
}
