using FlatBuffers;
using System.Collections.Generic;

public class EKMJAONFHDF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint MAPNDFCJFLJ { get; set; } // 0xC DLCEAFBCBGK IPFCNEIHNLJ CLNEANLIOFN
	public uint JBFLEDKDFCO_cid { get; set; } // 0x10 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint PMDLBHLNIDP { get; set; } // 0x14 KBPFPPBNJCC HNDKMDOPGNC NLFFKMHAAKB
	public uint JIMJHIDEHNM_ApCounter { get; set; } // 0x18 CPFMBIINNNL HMLIMKEFHHD OPHOIBNLNLN
	public uint JGOHPDKCJKB_rw { get; set; } // 0x1C HOBIJNCHJHA MJFPLENCCCP OKELMCNLMDD
	public uint FPOMEEJFBIG_odr { get; set; } // 0x20 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint FNEIADJMHHO_st { get; set; } // 0x24 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x28 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class GBGCDLGBMEF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint MAPNDFCJFLJ { get; set; } // 0xC DLCEAFBCBGK IPFCNEIHNLJ CLNEANLIOFN
	public uint JBFLEDKDFCO_cid { get; set; } // 0x10 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint PMDLBHLNIDP { get; set; } // 0x14 KBPFPPBNJCC HNDKMDOPGNC NLFFKMHAAKB
	public uint JGOHPDKCJKB_rw { get; set; } // 0x18 HOBIJNCHJHA MJFPLENCCCP OKELMCNLMDD
	public uint FPOMEEJFBIG_odr { get; set; } // 0x1C PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint HLOBFDBFINJ { get; set; } // 0x20 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint FPAODPEJDHB { get; set; } // 0x24 KHAOEBHIANF DGAPPBGPPCB CILLABKJOCP
	public uint FNEIADJMHHO_st { get; set; } // 0x28 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x2C GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
	public uint HPGNBPIBAOM_IsBeginner { get; set; } // 0x30 BMEHEHGDBEL CNGGNJIILPC KINBLEJIELP
	public uint DMEDKJPOLCH_cat { get; set; } // 0x34 JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint ADOJHHMMNIN { get; set; } // 0x38 MBEGALDJHLI FPPFNDNGOPD LPOGJAAFDIK
	public uint ADCKKAFCIAC { get; set; } // 0x3C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint IJEKNCDIIAE_mver { get; set; } // 0x40 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int JMMEGKGCIIL { get; set; } // 0x44 ILCNHAFCAGN JDPKCAGDCLJ DNFIBINDNJO
}
public class KLPHKNHEKPM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint CLDDAEMKHOG { get; set; } // 0xC ODGPJJABDIF EJIEKOADMON OEMHJFANMOB
	public uint PIMBMBIICMK { get; set; } // 0x10 FHPCDLALFLK MEFGFLKOEHP EELNDGENNFM
	public uint LJNAKDMILMC_key { get; set; } // 0x14 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public uint OILNNGPCLGD { get; set; } // 0x18 ICJMBLFPJIG BJADBAIJBPM KHKAIDMPANB
}
public class GEDOHHLGKCG
{
	public EKMJAONFHDF[] HGMBJPLPHJJ { get; set; } // 0x8 HFKHFEHLPLB EHBNJLJBJKP KBMNMMJNNDB
	public GBGCDLGBMEF[] MECOBEMIHDG { get; set; } // 0xC PEHGIAGKJMJ AONIABHNHHC DHGHGMBLBGM
	public KLPHKNHEKPM[] APHNKNGKKFC { get; set; } // 0x10 NKNDJILLFLC IGMIBBHAANI LBGEJOLEKPL
	public static GEDOHHLGKCG HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x16B7AEC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		EEBLKICOJPH res_readData = EEBLKICOJPH.GetRootAsEEBLKICOJPH(buffer);
		GEDOHHLGKCG res_data = new GEDOHHLGKCG();

		List<EKMJAONFHDF> HGMBJPLPHJJ_list = new List<EKMJAONFHDF>();
		for(int HGMBJPLPHJJ_idx = 0; HGMBJPLPHJJ_idx < res_readData.OFNGBGFMDDOLength; HGMBJPLPHJJ_idx++)
		{
			EECGFGECDBJ HGMBJPLPHJJ_readData = res_readData.GetOFNGBGFMDDO(HGMBJPLPHJJ_idx);
			EKMJAONFHDF HGMBJPLPHJJ_data = new EKMJAONFHDF();

			HGMBJPLPHJJ_data.PPFNGGCBJKC_id = HGMBJPLPHJJ_readData.BBPHAPFBFHK;
			HGMBJPLPHJJ_data.MAPNDFCJFLJ = HGMBJPLPHJJ_readData.FIDHINJIOAD;
			HGMBJPLPHJJ_data.JBFLEDKDFCO_cid = HGMBJPLPHJJ_readData.HOENDPOGFIO;
			HGMBJPLPHJJ_data.PMDLBHLNIDP = HGMBJPLPHJJ_readData.ECFLMBOLCAA;
			HGMBJPLPHJJ_data.JIMJHIDEHNM_ApCounter = HGMBJPLPHJJ_readData.MKLGLNCCAJF;
			HGMBJPLPHJJ_data.JGOHPDKCJKB_rw = HGMBJPLPHJJ_readData.DHFDNBDDLLO;
			HGMBJPLPHJJ_data.FPOMEEJFBIG_odr = HGMBJPLPHJJ_readData.AEAKMMJLLDK;
			HGMBJPLPHJJ_data.FNEIADJMHHO_st = HGMBJPLPHJJ_readData.GLIIHLOLPEF;
			HGMBJPLPHJJ_data.EICJBAEDMNM = HGMBJPLPHJJ_readData.KMEODDMBHHE;
			HGMBJPLPHJJ_list.Add(HGMBJPLPHJJ_data);
		}
		res_data.HGMBJPLPHJJ = HGMBJPLPHJJ_list.ToArray();

		List<GBGCDLGBMEF> MECOBEMIHDG_list = new List<GBGCDLGBMEF>();
		for(int MECOBEMIHDG_idx = 0; MECOBEMIHDG_idx < res_readData.FOBKBJEHOFGLength; MECOBEMIHDG_idx++)
		{
			NACHIDBHKDO MECOBEMIHDG_readData = res_readData.GetFOBKBJEHOFG(MECOBEMIHDG_idx);
			GBGCDLGBMEF MECOBEMIHDG_data = new GBGCDLGBMEF();

			MECOBEMIHDG_data.PPFNGGCBJKC_id = MECOBEMIHDG_readData.BBPHAPFBFHK;
			MECOBEMIHDG_data.MAPNDFCJFLJ = MECOBEMIHDG_readData.FIDHINJIOAD;
			MECOBEMIHDG_data.JBFLEDKDFCO_cid = MECOBEMIHDG_readData.HOENDPOGFIO;
			MECOBEMIHDG_data.PMDLBHLNIDP = MECOBEMIHDG_readData.ECFLMBOLCAA;
			MECOBEMIHDG_data.JGOHPDKCJKB_rw = MECOBEMIHDG_readData.DHFDNBDDLLO;
			MECOBEMIHDG_data.FPOMEEJFBIG_odr = MECOBEMIHDG_readData.AEAKMMJLLDK;
			MECOBEMIHDG_data.HLOBFDBFINJ = MECOBEMIHDG_readData.OADMJNEOKLC;
			MECOBEMIHDG_data.FPAODPEJDHB = MECOBEMIHDG_readData.MIBINPGCPPK;
			MECOBEMIHDG_data.FNEIADJMHHO_st = MECOBEMIHDG_readData.GLIIHLOLPEF;
			MECOBEMIHDG_data.EICJBAEDMNM = MECOBEMIHDG_readData.KMEODDMBHHE;
			MECOBEMIHDG_data.HPGNBPIBAOM_IsBeginner = MECOBEMIHDG_readData.JBAHJKKJPEG;
			MECOBEMIHDG_data.DMEDKJPOLCH_cat = MECOBEMIHDG_readData.ADCLAGBHDBC;
			MECOBEMIHDG_data.ADOJHHMMNIN = MECOBEMIHDG_readData.ECLKGKLMLBK;
			MECOBEMIHDG_data.ADCKKAFCIAC = MECOBEMIHDG_readData.EBBBDFADIPN;
			MECOBEMIHDG_data.IJEKNCDIIAE_mver = MECOBEMIHDG_readData.OFMGALJGDAO;
			MECOBEMIHDG_data.JMMEGKGCIIL = MECOBEMIHDG_readData.FKLNFLAFBDH;
			MECOBEMIHDG_list.Add(MECOBEMIHDG_data);
		}
		res_data.MECOBEMIHDG = MECOBEMIHDG_list.ToArray();

		List<KLPHKNHEKPM> APHNKNGKKFC_list = new List<KLPHKNHEKPM>();
		for(int APHNKNGKKFC_idx = 0; APHNKNGKKFC_idx < res_readData.ILBKJACHOHMLength; APHNKNGKKFC_idx++)
		{
			BPMNLCHMMIE APHNKNGKKFC_readData = res_readData.GetILBKJACHOHM(APHNKNGKKFC_idx);
			KLPHKNHEKPM APHNKNGKKFC_data = new KLPHKNHEKPM();

			APHNKNGKKFC_data.PPFNGGCBJKC_id = APHNKNGKKFC_readData.BBPHAPFBFHK;
			APHNKNGKKFC_data.CLDDAEMKHOG = APHNKNGKKFC_readData.BKEFGOKMFOB;
			APHNKNGKKFC_data.PIMBMBIICMK = APHNKNGKKFC_readData.DBLGMHOGODM;
			APHNKNGKKFC_data.LJNAKDMILMC_key = APHNKNGKKFC_readData.AGOIMGHMGOH;
			APHNKNGKKFC_data.OILNNGPCLGD = APHNKNGKKFC_readData.ICJLLMMABON;
			APHNKNGKKFC_list.Add(APHNKNGKKFC_data);
		}
		res_data.APHNKNGKKFC = APHNKNGKKFC_list.ToArray();

		return res_data;
	}
}
