using FlatBuffers;
using System.Collections.Generic;

public class CBKLHFDMLFO
{
	public uint PPFNGGCBJKC_Id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint HEOLEHDFLJO { get; set; } // 0xC EALEFNJMEPK OICOCHBFNAK HGLFJJHECGH
	public uint[] IFILLPEKJFK { get; set; } // 0x10 MHLFAGLLMGH LMFKMBOBFOG ENHLLDAKGJJ
	public uint GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint ACGLMKEBMDL { get; set; } // 0x18 EPENFLDKGJE ALOLFIJOOHG JDPCOMJIMHG
	public uint KMIDKGMIIBK { get; set; } // 0x1C EMKLEANANFF IJHDGOLKKDM KDBIHPAHGHA
	public uint[] BONFLFAPFDG { get; set; } // 0x20 HAFEFLMECIM ADMBEAAIBDL HLIHMAKBLMN
}
public class AOGBEJNPKFB
{
	public uint PPFNGGCBJKC_Id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int[] CFMBELIAJIB { get; set; } // 0xC MMJNKEGILKA AMOJHDKGHBP CIHDINOPNEM
	public int[] NJGNGFNKHAH { get; set; } // 0x10 LEONGAPBFML LILBBEIJFHD KIFDICGFJIE
}
public class MNFBFBKBJLB
{
	public uint PPFNGGCBJKC_Id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int[] CFMBELIAJIB { get; set; } // 0xC MMJNKEGILKA AMOJHDKGHBP CIHDINOPNEM
	public int[] NJGNGFNKHAH { get; set; } // 0x10 LEONGAPBFML LILBBEIJFHD KIFDICGFJIE
}
public class BDEOFCEPFMN
{
	public int PPFNGGCBJKC_Id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE { get; set; } // 0x10 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int ALMNMBDELDB { get; set; } // 0x14 PBNNMHBCMJH PMGKNCJIDIJ JCNDENOLLFK
	public int JBGEEPFKIGG { get; set; } // 0x18 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int[] JFJFMFNMPPF { get; set; } // 0x1C OIGALJDLLCA IKEJPGFHMOG CCEGLLNCOGM
}
public class GGNFFEBIPON
{
	public CBKLHFDMLFO[] CNGFINPPJKG { get; set; } // 0x8 NKLPKADLGEJ AMHJPMPAGGI CICLCACKBBJ
	public AOGBEJNPKFB[] EBMHHKNDDEN { get; set; } // 0xC EMKLLGFDNMG PDJCBBHHBIH HMPBEHHFEIH
	public MNFBFBKBJLB[] EABCJPHDKDC { get; set; } // 0x10 MCLMFFDJOLF NGAEPBJIAPF GLIAKALDNJL
	public BDEOFCEPFMN[] DBIEABIPELG { get; set; } // 0x14 BBNOMBNEHMC CFDIHDPGNJL FMLHAPHMCLB
	public static GGNFFEBIPON HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xAA3590
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		ANBBEHKIHLJ res_readData = ANBBEHKIHLJ.GetRootAsANBBEHKIHLJ(buffer);
		GGNFFEBIPON res_data = new GGNFFEBIPON();

		List<CBKLHFDMLFO> CNGFINPPJKG_list = new List<CBKLHFDMLFO>();
		for(int CNGFINPPJKG_idx = 0; CNGFINPPJKG_idx < res_readData.OAHBCGIOJFALength; CNGFINPPJKG_idx++)
		{
			EDGCKDLNLNN CNGFINPPJKG_readData = res_readData.GetOAHBCGIOJFA(CNGFINPPJKG_idx);
			CBKLHFDMLFO CNGFINPPJKG_data = new CBKLHFDMLFO();

			CNGFINPPJKG_data.PPFNGGCBJKC_Id = CNGFINPPJKG_readData.BBPHAPFBFHK;
			CNGFINPPJKG_data.HEOLEHDFLJO = CNGFINPPJKG_readData.EOHDEKFEONI;
			List<uint> IFILLPEKJFK_list = new List<uint>();
			for(int IFILLPEKJFK_idx = 0; IFILLPEKJFK_idx < CNGFINPPJKG_readData.PLPNKMFFPLELength; IFILLPEKJFK_idx++)
			{
				IFILLPEKJFK_list.Add(CNGFINPPJKG_readData.GetPLPNKMFFPLE(IFILLPEKJFK_idx));
			}
			CNGFINPPJKG_data.IFILLPEKJFK = IFILLPEKJFK_list.ToArray();

			CNGFINPPJKG_data.GBJFNGCDKPM = CNGFINPPJKG_readData.LPJPOOHJKAE;
			CNGFINPPJKG_data.ACGLMKEBMDL = CNGFINPPJKG_readData.PAEGHLMNPNO;
			CNGFINPPJKG_data.KMIDKGMIIBK = CNGFINPPJKG_readData.OPOLOJINLPI;
			List<uint> BONFLFAPFDG_list = new List<uint>();
			for(int BONFLFAPFDG_idx = 0; BONFLFAPFDG_idx < CNGFINPPJKG_readData.NMKAIHMOFNALength; BONFLFAPFDG_idx++)
			{
				BONFLFAPFDG_list.Add(CNGFINPPJKG_readData.GetNMKAIHMOFNA(BONFLFAPFDG_idx));
			}
			CNGFINPPJKG_data.BONFLFAPFDG = BONFLFAPFDG_list.ToArray();

			CNGFINPPJKG_list.Add(CNGFINPPJKG_data);
		}
		res_data.CNGFINPPJKG = CNGFINPPJKG_list.ToArray();

		List<AOGBEJNPKFB> EBMHHKNDDEN_list = new List<AOGBEJNPKFB>();
		for(int EBMHHKNDDEN_idx = 0; EBMHHKNDDEN_idx < res_readData.KOMCNJPMIHCLength; EBMHHKNDDEN_idx++)
		{
			LLGJODEDLOA EBMHHKNDDEN_readData = res_readData.GetKOMCNJPMIHC(EBMHHKNDDEN_idx);
			AOGBEJNPKFB EBMHHKNDDEN_data = new AOGBEJNPKFB();

			EBMHHKNDDEN_data.PPFNGGCBJKC_Id = EBMHHKNDDEN_readData.BBPHAPFBFHK;
			List<int> CFMBELIAJIB_list = new List<int>();
			for(int CFMBELIAJIB_idx = 0; CFMBELIAJIB_idx < EBMHHKNDDEN_readData.GAGNCJEKOLLLength; CFMBELIAJIB_idx++)
			{
				CFMBELIAJIB_list.Add(EBMHHKNDDEN_readData.GetGAGNCJEKOLL(CFMBELIAJIB_idx));
			}
			EBMHHKNDDEN_data.CFMBELIAJIB = CFMBELIAJIB_list.ToArray();

			List<int> NJGNGFNKHAH_list = new List<int>();
			for(int NJGNGFNKHAH_idx = 0; NJGNGFNKHAH_idx < EBMHHKNDDEN_readData.GPCCCOAHKAELength; NJGNGFNKHAH_idx++)
			{
				NJGNGFNKHAH_list.Add(EBMHHKNDDEN_readData.GetGPCCCOAHKAE(NJGNGFNKHAH_idx));
			}
			EBMHHKNDDEN_data.NJGNGFNKHAH = NJGNGFNKHAH_list.ToArray();

			EBMHHKNDDEN_list.Add(EBMHHKNDDEN_data);
		}
		res_data.EBMHHKNDDEN = EBMHHKNDDEN_list.ToArray();

		List<MNFBFBKBJLB> EABCJPHDKDC_list = new List<MNFBFBKBJLB>();
		for(int EABCJPHDKDC_idx = 0; EABCJPHDKDC_idx < res_readData.LCPGFAHAGPLLength; EABCJPHDKDC_idx++)
		{
			DJABNGNLIHM EABCJPHDKDC_readData = res_readData.GetLCPGFAHAGPL(EABCJPHDKDC_idx);
			MNFBFBKBJLB EABCJPHDKDC_data = new MNFBFBKBJLB();

			EABCJPHDKDC_data.PPFNGGCBJKC_Id = EABCJPHDKDC_readData.BBPHAPFBFHK;
			List<int> CFMBELIAJIB_list = new List<int>();
			for(int CFMBELIAJIB_idx = 0; CFMBELIAJIB_idx < EABCJPHDKDC_readData.GAGNCJEKOLLLength; CFMBELIAJIB_idx++)
			{
				CFMBELIAJIB_list.Add(EABCJPHDKDC_readData.GetGAGNCJEKOLL(CFMBELIAJIB_idx));
			}
			EABCJPHDKDC_data.CFMBELIAJIB = CFMBELIAJIB_list.ToArray();

			List<int> NJGNGFNKHAH_list = new List<int>();
			for(int NJGNGFNKHAH_idx = 0; NJGNGFNKHAH_idx < EABCJPHDKDC_readData.GPCCCOAHKAELength; NJGNGFNKHAH_idx++)
			{
				NJGNGFNKHAH_list.Add(EABCJPHDKDC_readData.GetGPCCCOAHKAE(NJGNGFNKHAH_idx));
			}
			EABCJPHDKDC_data.NJGNGFNKHAH = NJGNGFNKHAH_list.ToArray();

			EABCJPHDKDC_list.Add(EABCJPHDKDC_data);
		}
		res_data.EABCJPHDKDC = EABCJPHDKDC_list.ToArray();

		List<BDEOFCEPFMN> DBIEABIPELG_list = new List<BDEOFCEPFMN>();
		for(int DBIEABIPELG_idx = 0; DBIEABIPELG_idx < res_readData.HIHGBEKDKOLLength; DBIEABIPELG_idx++)
		{
			OHCNALAONKF DBIEABIPELG_readData = res_readData.GetHIHGBEKDKOL(DBIEABIPELG_idx);
			BDEOFCEPFMN DBIEABIPELG_data = new BDEOFCEPFMN();

			DBIEABIPELG_data.PPFNGGCBJKC_Id = DBIEABIPELG_readData.BBPHAPFBFHK;
			DBIEABIPELG_data.PLALNIIBLOF = DBIEABIPELG_readData.CFLMCGOJJJD;
			DBIEABIPELG_data.IJEKNCDIIAE = DBIEABIPELG_readData.OFMGALJGDAO;
			DBIEABIPELG_data.ALMNMBDELDB = DBIEABIPELG_readData.OFELCGCIOFJ;
			DBIEABIPELG_data.JBGEEPFKIGG = DBIEABIPELG_readData.KJFEBMBHKOC;
			List<int> JFJFMFNMPPF_list = new List<int>();
			for(int JFJFMFNMPPF_idx = 0; JFJFMFNMPPF_idx < DBIEABIPELG_readData.DAIPOIOKCAALength; JFJFMFNMPPF_idx++)
			{
				JFJFMFNMPPF_list.Add(DBIEABIPELG_readData.GetDAIPOIOKCAA(JFJFMFNMPPF_idx));
			}
			DBIEABIPELG_data.JFJFMFNMPPF = JFJFMFNMPPF_list.ToArray();

			DBIEABIPELG_list.Add(DBIEABIPELG_data);
		}
		res_data.DBIEABIPELG = DBIEABIPELG_list.ToArray();

		return res_data;
	}
}
