using FlatBuffers;
using System.Collections.Generic;

public class FDGGBBPGKFB
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int ADKDHKMPMHP { get; set; } // 0xC HIELAPGGNEJ KCLKBHDMAFH GOLECEILPOI
	public int JOPPFEHKNFO { get; set; } // 0x10 LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
	public int HDOEJDHGFLH { get; set; } // 0x14 LBHMFCIPOOA OEGAADKHDEB NCJCOKLLAIL
	public int DDLGKJOKGFJ { get; set; } // 0x18 CHOMMGHNCOE LOOIIPKGBDN EEFGDPLHGDM
	public string CHEHLCNHMII { get; set; } // 0x1C NNJDPFKJJOE PEHOFHPJDFK PEBKEBNMNEO
	public int[] GLCLFMGPMAN { get; set; } // 0x20 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int[] ADPPAIPFHML { get; set; } // 0x24 LONDDHLNFBL LJMLHOOPGEM PHNIOCPOBGO
	public uint LJNAKDMILMC { get; set; } // 0x28 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
}
public class BAAELIGJGIJ
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class MKHHOIJDCAH
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class GHFFJFCGDCB
{
	public FDGGBBPGKFB[] HEHPAMADHGC { get; set; } // 0x8 ELDDPACCPDB BGLEMGEDKIM HPKKCCEEGEK
	public BAAELIGJGIJ[] BHGDNGHDDAC { get; set; } // 0xC JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public MKHHOIJDCAH[] MHGMDJNOLMI { get; set; } // 0x10 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static GHFFJFCGDCB HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xAA4DF0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		KMANHBAOCLJ res_readData = KMANHBAOCLJ.GetRootAsKMANHBAOCLJ(buffer);
		GHFFJFCGDCB res_data = new GHFFJFCGDCB();

		List<FDGGBBPGKFB> HEHPAMADHGC_list = new List<FDGGBBPGKFB>();
		for(int HEHPAMADHGC_idx = 0; HEHPAMADHGC_idx < res_readData.PIIOHCJFHBDLength; HEHPAMADHGC_idx++)
		{
			OIGIKHKPIOF HEHPAMADHGC_readData = res_readData.GetPIIOHCJFHBD(HEHPAMADHGC_idx);
			FDGGBBPGKFB HEHPAMADHGC_data = new FDGGBBPGKFB();

			HEHPAMADHGC_data.PPFNGGCBJKC = HEHPAMADHGC_readData.BBPHAPFBFHK;
			HEHPAMADHGC_data.ADKDHKMPMHP = HEHPAMADHGC_readData.EKJDPPJFKOK;
			HEHPAMADHGC_data.JOPPFEHKNFO = HEHPAMADHGC_readData.ALPALMJMJJK;
			HEHPAMADHGC_data.HDOEJDHGFLH = HEHPAMADHGC_readData.MJGENHDKIFB;
			HEHPAMADHGC_data.DDLGKJOKGFJ = HEHPAMADHGC_readData.JFLHEINHLOC;
			HEHPAMADHGC_data.CHEHLCNHMII = HEHPAMADHGC_readData.GJBNEGIFCDG;
			List<int> GLCLFMGPMAN_list = new List<int>();
			for(int GLCLFMGPMAN_idx = 0; GLCLFMGPMAN_idx < HEHPAMADHGC_readData.AGPECCAGHFLLength; GLCLFMGPMAN_idx++)
			{
				GLCLFMGPMAN_list.Add(HEHPAMADHGC_readData.GetAGPECCAGHFL(GLCLFMGPMAN_idx));
			}
			HEHPAMADHGC_data.GLCLFMGPMAN = GLCLFMGPMAN_list.ToArray();

			List<int> ADPPAIPFHML_list = new List<int>();
			for(int ADPPAIPFHML_idx = 0; ADPPAIPFHML_idx < HEHPAMADHGC_readData.EKPDMIAPDKBLength; ADPPAIPFHML_idx++)
			{
				ADPPAIPFHML_list.Add(HEHPAMADHGC_readData.GetEKPDMIAPDKB(ADPPAIPFHML_idx));
			}
			HEHPAMADHGC_data.ADPPAIPFHML = ADPPAIPFHML_list.ToArray();

			HEHPAMADHGC_data.LJNAKDMILMC = HEHPAMADHGC_readData.AGOIMGHMGOH;
			HEHPAMADHGC_list.Add(HEHPAMADHGC_data);
		}
		res_data.HEHPAMADHGC = HEHPAMADHGC_list.ToArray();

		List<BAAELIGJGIJ> BHGDNGHDDAC_list = new List<BAAELIGJGIJ>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			HLDFFNGONFE BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			BAAELIGJGIJ BHGDNGHDDAC_data = new BAAELIGJGIJ();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<MKHHOIJDCAH> MHGMDJNOLMI_list = new List<MKHHOIJDCAH>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			OLDFIFPNMJO MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			MKHHOIJDCAH MHGMDJNOLMI_data = new MKHHOIJDCAH();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
