using FlatBuffers;
using System.Collections.Generic;

public class JMHHPHHACHH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x14 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint FBFLDFMFFOH_rar { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int EIGNPDFHIJA { get; set; } // 0x1C JIMIIFIJDON COAODPNEELA OHOPAKFBOGL
}
public class HDPPMMGCPFC
{
	public JMHHPHHACHH[] ECFMCPJIDJN { get; set; } // 0x8 CBOICJHEFAO IDEIHKDOEGB HHIPMDCOPPA
	public static HDPPMMGCPFC HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1743664
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		FJGGBKGOPEG res_readData = FJGGBKGOPEG.GetRootAsFJGGBKGOPEG(buffer);
		HDPPMMGCPFC res_data = new HDPPMMGCPFC();

		List<JMHHPHHACHH> ECFMCPJIDJN_list = new List<JMHHPHHACHH>();
		for(int ECFMCPJIDJN_idx = 0; ECFMCPJIDJN_idx < res_readData.HCAJMDDNOANLength; ECFMCPJIDJN_idx++)
		{
			LDJGKHHLNKN ECFMCPJIDJN_readData = res_readData.GetHCAJMDDNOAN(ECFMCPJIDJN_idx);
			JMHHPHHACHH ECFMCPJIDJN_data = new JMHHPHHACHH();

			ECFMCPJIDJN_data.PPFNGGCBJKC_id = ECFMCPJIDJN_readData.BBPHAPFBFHK;
			ECFMCPJIDJN_data.JBGEEPFKIGG_val = ECFMCPJIDJN_readData.KJFEBMBHKOC;
			ECFMCPJIDJN_data.PLALNIIBLOF_en = ECFMCPJIDJN_readData.CFLMCGOJJJD;
			ECFMCPJIDJN_data.IJEKNCDIIAE_mver = ECFMCPJIDJN_readData.OFMGALJGDAO;
			ECFMCPJIDJN_data.FBFLDFMFFOH_rar = ECFMCPJIDJN_readData.ODBPKGJPLMD;
			ECFMCPJIDJN_data.EIGNPDFHIJA = ECFMCPJIDJN_readData.GPBMFGDNLHL;
			ECFMCPJIDJN_list.Add(ECFMCPJIDJN_data);
		}
		res_data.ECFMCPJIDJN = ECFMCPJIDJN_list.ToArray();

		return res_data;
	}
}
