using FlatBuffers;
using System.Collections.Generic;

public class ECHMLLNAIHK
{
	public string OPFGFINHFCE { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint EHHFFKAFOMC { get; set; } // 0x20 MDCEFKJDJIJ EMIPFAAPLIB JHGMJLNGOGD
	public uint HPNOGLIFJOP { get; set; } // 0x24 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE { get; set; } // 0x28 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF { get; set; } // 0x2C HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI { get; set; } // 0x30 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH { get; set; } // 0x34 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint KHIKEGLBGAF { get; set; } // 0x38 OAPPFIGOMHO FAHFDEFDLMH OJJMIBDFGBG
	public uint DPJCFLKFEPN { get; set; } // 0x3C IPODKLGLHPC MEAAAGCCAPI GNMJKJHPIOG
	public uint[] EEOGPJJCKHH { get; set; } // 0x40 CPNKKFMLHFL BBBPKCMKJEF CDMJOOGMGNP
	public uint JMJDLDEIFKE { get; set; } // 0x44 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO { get; set; } // 0x48 IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x4C AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public int MJBKGOJBPAD { get; set; } // 0x50 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public string FEMMDNIELFC { get; set; } // 0x54 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public int JKFPADIAKCK { get; set; } // 0x58 DJMAJJIHFPL CENPFGJOAPN FKKHCFFICFH
	public uint HKKNEAGCIEB { get; set; } // 0x5C DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI { get; set; } // 0x60 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public int[] EPHAKDAPAHE { get; set; } // 0x64 CCIKGIINJPH MPHKFHJCOPG HLEJFIBNCBD
	public uint[] HIAMHLLHAON { get; set; } // 0x68 OFPOHJIDECK DJDNABNLAPN EFAGPEJEIAA
	public uint[] BKBEPOFJOJG { get; set; } // 0x6C HHLOICEKOFO DECBJJEPLPG INKLCACPHDG
	public string OMCAOJJGOGG { get; set; } // 0x70 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM { get; set; } // 0x74 AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP { get; set; } // 0x78 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC { get; set; } // 0x7C IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int AHKPNPNOAMO { get; set; } // 0x80 AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
	public int EKJFNHHKBPL { get; set; } // 0x84 BPPNFOAFCPE BONLIFKCIFO HBFFBCJHJAC
	public int[] HEABAENHIDE { get; set; } // 0x88 JHPFLNHMHHJ ILADNPDEPCO CBPOEIJLPEF
}
public class AHBGKGEOGMD
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FOILNHKHHDF { get; set; } // 0xC LNNCNOIGMGM FOFBHPJDHFO LHPMDDKPJDP
	public int[] AIHOJKFNEEN { get; set; } // 0x10 GGBFCEFNCFM BGFIPHMMOGA DHAIHODDOGM
	public uint[] BFINGCJHOHI { get; set; } // 0x14 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public uint[] JJHPDDPKBHF { get; set; } // 0x18 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public int JOPPFEHKNFO { get; set; } // 0x1C LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
}
public class MLIOEHFFKOL
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint BDKFOMGCOOE { get; set; } // 0x1C AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x20 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x24 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x28 CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x2C MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x30 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x34 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x38 PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x3C FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x40 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN { get; set; } // 0x44 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC { get; set; } // 0x48 HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ { get; set; } // 0x4C NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x50 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint ADCKKAFCIAC { get; set; } // 0x54 FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO { get; set; } // 0x58 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x5C GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class EIEAIKBBMCP
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string FEMMDNIELFC { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string DCOFJKBIOAH { get; set; } // 0x14 LFHINHLDCMI HBDCLKDHDHM GKBPJDDGPKI
	public int JONPKLHMOBL { get; set; } // 0x18 EDPHGGPAPJJ LDDGKJEDMED BEBCJJGHFDO
	public int MKNDAOHGOAK { get; set; } // 0x1C KMGMHIKCDIE MGMCJMODMAN LOBLFMFJDEC
	public int EIOFPIHABFC { get; set; } // 0x20 DOEKDKGOCDI OMKHICDNDND KGDECCPKPBN
	public int IAGDDKLKGJN { get; set; } // 0x24 GHNDJCCPNDE FDONNLBHBFI GMHDHJFLKKO
	public int BDKFOMGCOOE { get; set; } // 0x28 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public int PJGIAKGGHPF { get; set; } // 0x2C HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public int MMCBOJHFDEF { get; set; } // 0x30 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public int AIIEBILNLGO { get; set; } // 0x34 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public int JOGDEMBADLO { get; set; } // 0x38 PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public int GMJBANCDOJK { get; set; } // 0x3C FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public int AIEOAMKDHJC { get; set; } // 0x40 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public int GLCLFMGPMAN { get; set; } // 0x44 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int MBJIFDBEDAC { get; set; } // 0x48 HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
}
public class MAMENAIEHJO
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class JNKMFEONNGF
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class ALNCCFLCKFE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KFCIJBLDHOK { get; set; } // 0xC JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int JLEIHOEGMOP { get; set; } // 0x10 JLNAMGLBPME JJGFFGDDFPA LIIFHDMHLHP
}
public class NEDOEMIILFF
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GBJFNGCDKPM { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int MAFAIIHJAFG { get; set; } // 0x14 FIINMMHBBJF LLNFMLKMFKB PCICDCAILIF
}
public class MOBFFIKHKHM
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int CNKFPJCGNFE { get; set; } // 0xC OGPCJNOKMAM GJBOGOFHGNP GJDGIDCMJMH
	public int GNFBMCGMCFO { get; set; } // 0x10 LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x14 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class ECMPIGNKJOK
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GNFBMCGMCFO { get; set; } // 0xC LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x10 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class NIJKKLJAABL
{
	public int KHPHAAMGMJP { get; set; } // 0x8 FHLAGLBMFHE ABFDDKBBPCH MHDOIIEMDEH
	public int OFIAENKCJME { get; set; } // 0xC NHHGGLNCELI KADLAKFANGA AIDAPNCEPOB
	public int[] JMLCLHHLJHM { get; set; } // 0x10 HCOPKKMMEAL KCJKEEAILGB EGEABIGCJJK
}
public class HGHOHICGBEP
{
	public ECHMLLNAIHK HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public AHBGKGEOGMD[] MCHFABAKPMH { get; set; } // 0xC BFBKDKPKLMM IPDEGCCJALP HHNBEKGDAPD
	public MLIOEHFFKOL[] MDDOGIAFDEI { get; set; } // 0x10 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public EIEAIKBBMCP[] DGPHHJCPNOO { get; set; } // 0x14 NOFBKAPCNCJ FDCOKDMDELH LMPPHNCIKOF
	public MAMENAIEHJO[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public JNKMFEONNGF[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public ALNCCFLCKFE[] KIEKMCKCMGD { get; set; } // 0x20 AHOFIJDMDAO EEMBMMJIHPE CDHPBECJGGO
	public NEDOEMIILFF[] MHKNGJMEGFI { get; set; } // 0x24 DGMLFJKGMLO DJAALDIHICI ILMEEBDMNBJ
	public MOBFFIKHKHM[] OLACFKILCFD { get; set; } // 0x28 ODAEGEAACIA KCGGGPCDEPK ANKJOEMLFCI
	public ECMPIGNKJOK[] MIOCOKLMLBD { get; set; } // 0x2C COILMDCEJLD MNIALHMNHFM OGLAMDPDFCD
	public NIJKKLJAABL[] IEJLJIHIDJC { get; set; } // 0x30 CDHGOELCBFB DGNNDIPELAP BFHEABPGGHO
	public static HGHOHICGBEP HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x174D910
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		HJOPMDDAIDF res_readData = HJOPMDDAIDF.GetRootAsHJOPMDDAIDF(buffer);
		HGHOHICGBEP res_data = new HGHOHICGBEP();

		EPBCNHDGFCB HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		ECHMLLNAIHK HMBHNLCFDIH_data = new ECHMLLNAIHK();

		HMBHNLCFDIH_data.OPFGFINHFCE = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.EHHFFKAFOMC = HMBHNLCFDIH_readData.DEPHCHOBAJG;
		HMBHNLCFDIH_data.HPNOGLIFJOP = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.KHIKEGLBGAF = HMBHNLCFDIH_readData.HKPPDACCCOH;
		HMBHNLCFDIH_data.DPJCFLKFEPN = HMBHNLCFDIH_readData.NAMFJMCKFIF;
		List<uint> EEOGPJJCKHH_list = new List<uint>();
		for(int EEOGPJJCKHH_idx = 0; EEOGPJJCKHH_idx < HMBHNLCFDIH_readData.EBFEIMNOLHPLength; EEOGPJJCKHH_idx++)
		{
			EEOGPJJCKHH_list.Add(HMBHNLCFDIH_readData.GetEBFEIMNOLHP(EEOGPJJCKHH_idx));
		}
		HMBHNLCFDIH_data.EEOGPJJCKHH = EEOGPJJCKHH_list.ToArray();

		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.MJBKGOJBPAD = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.FEMMDNIELFC = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.JKFPADIAKCK = HMBHNLCFDIH_readData.KJPLOBLDNHJ;
		HMBHNLCFDIH_data.HKKNEAGCIEB = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI = JHPCPNJJHLI_list.ToArray();

		List<int> EPHAKDAPAHE_list = new List<int>();
		for(int EPHAKDAPAHE_idx = 0; EPHAKDAPAHE_idx < HMBHNLCFDIH_readData.JNBJODMLPMOLength; EPHAKDAPAHE_idx++)
		{
			EPHAKDAPAHE_list.Add(HMBHNLCFDIH_readData.GetJNBJODMLPMO(EPHAKDAPAHE_idx));
		}
		HMBHNLCFDIH_data.EPHAKDAPAHE = EPHAKDAPAHE_list.ToArray();

		List<uint> HIAMHLLHAON_list = new List<uint>();
		for(int HIAMHLLHAON_idx = 0; HIAMHLLHAON_idx < HMBHNLCFDIH_readData.JFKBEBPJGBHLength; HIAMHLLHAON_idx++)
		{
			HIAMHLLHAON_list.Add(HMBHNLCFDIH_readData.GetJFKBEBPJGBH(HIAMHLLHAON_idx));
		}
		HMBHNLCFDIH_data.HIAMHLLHAON = HIAMHLLHAON_list.ToArray();

		List<uint> BKBEPOFJOJG_list = new List<uint>();
		for(int BKBEPOFJOJG_idx = 0; BKBEPOFJOJG_idx < HMBHNLCFDIH_readData.BPBBMFCKGGPLength; BKBEPOFJOJG_idx++)
		{
			BKBEPOFJOJG_list.Add(HMBHNLCFDIH_readData.GetBPBBMFCKGGP(BKBEPOFJOJG_idx));
		}
		HMBHNLCFDIH_data.BKBEPOFJOJG = BKBEPOFJOJG_list.ToArray();

		HMBHNLCFDIH_data.OMCAOJJGOGG = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.AHKPNPNOAMO = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		HMBHNLCFDIH_data.EKJFNHHKBPL = HMBHNLCFDIH_readData.HFKHLKGAJEL;
		List<int> HEABAENHIDE_list = new List<int>();
		for(int HEABAENHIDE_idx = 0; HEABAENHIDE_idx < HMBHNLCFDIH_readData.LFDLHFLPCNCLength; HEABAENHIDE_idx++)
		{
			HEABAENHIDE_list.Add(HMBHNLCFDIH_readData.GetLFDLHFLPCNC(HEABAENHIDE_idx));
		}
		HMBHNLCFDIH_data.HEABAENHIDE = HEABAENHIDE_list.ToArray();

		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<AHBGKGEOGMD> MCHFABAKPMH_list = new List<AHBGKGEOGMD>();
		for(int MCHFABAKPMH_idx = 0; MCHFABAKPMH_idx < res_readData.KJFDCEGGPPHLength; MCHFABAKPMH_idx++)
		{
			PAPIGFKKFAK MCHFABAKPMH_readData = res_readData.GetKJFDCEGGPPH(MCHFABAKPMH_idx);
			AHBGKGEOGMD MCHFABAKPMH_data = new AHBGKGEOGMD();

			MCHFABAKPMH_data.PPFNGGCBJKC = MCHFABAKPMH_readData.BBPHAPFBFHK;
			MCHFABAKPMH_data.FOILNHKHHDF = MCHFABAKPMH_readData.HJNPKHJJDBB;
			List<int> AIHOJKFNEEN_list = new List<int>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < MCHFABAKPMH_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(MCHFABAKPMH_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			MCHFABAKPMH_data.AIHOJKFNEEN = AIHOJKFNEEN_list.ToArray();

			List<uint> BFINGCJHOHI_list = new List<uint>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < MCHFABAKPMH_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(MCHFABAKPMH_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			MCHFABAKPMH_data.BFINGCJHOHI = BFINGCJHOHI_list.ToArray();

			List<uint> JJHPDDPKBHF_list = new List<uint>();
			for(int JJHPDDPKBHF_idx = 0; JJHPDDPKBHF_idx < MCHFABAKPMH_readData.OOJBHHPJONJLength; JJHPDDPKBHF_idx++)
			{
				JJHPDDPKBHF_list.Add(MCHFABAKPMH_readData.GetOOJBHHPJONJ(JJHPDDPKBHF_idx));
			}
			MCHFABAKPMH_data.JJHPDDPKBHF = JJHPDDPKBHF_list.ToArray();

			MCHFABAKPMH_data.JOPPFEHKNFO = MCHFABAKPMH_readData.ALPALMJMJJK;
			MCHFABAKPMH_list.Add(MCHFABAKPMH_data);
		}
		res_data.MCHFABAKPMH = MCHFABAKPMH_list.ToArray();

		List<MLIOEHFFKOL> MDDOGIAFDEI_list = new List<MLIOEHFFKOL>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			DLDBBNOCCJD MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			MLIOEHFFKOL MDDOGIAFDEI_data = new MLIOEHFFKOL();

			MDDOGIAFDEI_data.PPFNGGCBJKC = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<EIEAIKBBMCP> DGPHHJCPNOO_list = new List<EIEAIKBBMCP>();
		for(int DGPHHJCPNOO_idx = 0; DGPHHJCPNOO_idx < res_readData.LEDCBACGIDDLength; DGPHHJCPNOO_idx++)
		{
			OFIGAJKJFPF DGPHHJCPNOO_readData = res_readData.GetLEDCBACGIDD(DGPHHJCPNOO_idx);
			EIEAIKBBMCP DGPHHJCPNOO_data = new EIEAIKBBMCP();

			DGPHHJCPNOO_data.PPFNGGCBJKC = DGPHHJCPNOO_readData.BBPHAPFBFHK;
			DGPHHJCPNOO_data.PLALNIIBLOF = DGPHHJCPNOO_readData.CFLMCGOJJJD;
			DGPHHJCPNOO_data.FEMMDNIELFC = DGPHHJCPNOO_readData.NNKLANONDOM;
			DGPHHJCPNOO_data.DCOFJKBIOAH = DGPHHJCPNOO_readData.HAOBOBNDAPL;
			DGPHHJCPNOO_data.JONPKLHMOBL = DGPHHJCPNOO_readData.HBOJKLFJGND;
			DGPHHJCPNOO_data.MKNDAOHGOAK = DGPHHJCPNOO_readData.AEHGIANDFOD;
			DGPHHJCPNOO_data.EIOFPIHABFC = DGPHHJCPNOO_readData.FEFAFHIGNMA;
			DGPHHJCPNOO_data.IAGDDKLKGJN = DGPHHJCPNOO_readData.FJIECABELGK;
			DGPHHJCPNOO_data.BDKFOMGCOOE = DGPHHJCPNOO_readData.NMGIFIOPMIJ;
			DGPHHJCPNOO_data.PJGIAKGGHPF = DGPHHJCPNOO_readData.NFPKGHADCCP;
			DGPHHJCPNOO_data.MMCBOJHFDEF = DGPHHJCPNOO_readData.PJCPCILBICH;
			DGPHHJCPNOO_data.AIIEBILNLGO = DGPHHJCPNOO_readData.AJHANMOKKDF;
			DGPHHJCPNOO_data.JOGDEMBADLO = DGPHHJCPNOO_readData.PBAJJGLCCDO;
			DGPHHJCPNOO_data.GMJBANCDOJK = DGPHHJCPNOO_readData.MPMOLHBIKKG;
			DGPHHJCPNOO_data.AIEOAMKDHJC = DGPHHJCPNOO_readData.ENECIEOGIJC;
			DGPHHJCPNOO_data.GLCLFMGPMAN = DGPHHJCPNOO_readData.MBBJMJAAODG;
			DGPHHJCPNOO_data.MBJIFDBEDAC = DGPHHJCPNOO_readData.IMCFOKIBEMC;
			DGPHHJCPNOO_list.Add(DGPHHJCPNOO_data);
		}
		res_data.DGPHHJCPNOO = DGPHHJCPNOO_list.ToArray();

		List<MAMENAIEHJO> BHGDNGHDDAC_list = new List<MAMENAIEHJO>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			BMAKMHEEFEF BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			MAMENAIEHJO BHGDNGHDDAC_data = new MAMENAIEHJO();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<JNKMFEONNGF> MHGMDJNOLMI_list = new List<JNKMFEONNGF>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			PBJDMDHLPIP MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			JNKMFEONNGF MHGMDJNOLMI_data = new JNKMFEONNGF();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<ALNCCFLCKFE> KIEKMCKCMGD_list = new List<ALNCCFLCKFE>();
		for(int KIEKMCKCMGD_idx = 0; KIEKMCKCMGD_idx < res_readData.FBAHAFKCMMHLength; KIEKMCKCMGD_idx++)
		{
			DEOAJNDLLLH KIEKMCKCMGD_readData = res_readData.GetFBAHAFKCMMH(KIEKMCKCMGD_idx);
			ALNCCFLCKFE KIEKMCKCMGD_data = new ALNCCFLCKFE();

			KIEKMCKCMGD_data.PPFNGGCBJKC = KIEKMCKCMGD_readData.BBPHAPFBFHK;
			KIEKMCKCMGD_data.KFCIJBLDHOK = KIEKMCKCMGD_readData.MCJNHPMBPIJ;
			KIEKMCKCMGD_data.JLEIHOEGMOP = KIEKMCKCMGD_readData.MGJKFKDICGC;
			KIEKMCKCMGD_list.Add(KIEKMCKCMGD_data);
		}
		res_data.KIEKMCKCMGD = KIEKMCKCMGD_list.ToArray();

		List<NEDOEMIILFF> MHKNGJMEGFI_list = new List<NEDOEMIILFF>();
		for(int MHKNGJMEGFI_idx = 0; MHKNGJMEGFI_idx < res_readData.GGKDJGGAFKALength; MHKNGJMEGFI_idx++)
		{
			HCNLBIAHFHK MHKNGJMEGFI_readData = res_readData.GetGGKDJGGAFKA(MHKNGJMEGFI_idx);
			NEDOEMIILFF MHKNGJMEGFI_data = new NEDOEMIILFF();

			MHKNGJMEGFI_data.PPFNGGCBJKC = MHKNGJMEGFI_readData.BBPHAPFBFHK;
			MHKNGJMEGFI_data.GBJFNGCDKPM = MHKNGJMEGFI_readData.LPJPOOHJKAE;
			MHKNGJMEGFI_data.JBGEEPFKIGG = MHKNGJMEGFI_readData.KJFEBMBHKOC;
			MHKNGJMEGFI_data.MAFAIIHJAFG = MHKNGJMEGFI_readData.LAIEPFCPDLK;
			MHKNGJMEGFI_list.Add(MHKNGJMEGFI_data);
		}
		res_data.MHKNGJMEGFI = MHKNGJMEGFI_list.ToArray();

		List<MOBFFIKHKHM> OLACFKILCFD_list = new List<MOBFFIKHKHM>();
		for(int OLACFKILCFD_idx = 0; OLACFKILCFD_idx < res_readData.HDNMEPFHLNFLength; OLACFKILCFD_idx++)
		{
			CHOEGDGADLA OLACFKILCFD_readData = res_readData.GetHDNMEPFHLNF(OLACFKILCFD_idx);
			MOBFFIKHKHM OLACFKILCFD_data = new MOBFFIKHKHM();

			OLACFKILCFD_data.PPFNGGCBJKC = OLACFKILCFD_readData.BBPHAPFBFHK;
			OLACFKILCFD_data.CNKFPJCGNFE = OLACFKILCFD_readData.DPFDOIIOICA;
			OLACFKILCFD_data.GNFBMCGMCFO = OLACFKILCFD_readData.GEAIPAEKLNF;
			OLACFKILCFD_data.BFFGFAMJAIG = OLACFKILCFD_readData.JGILGOILJNK;
			OLACFKILCFD_list.Add(OLACFKILCFD_data);
		}
		res_data.OLACFKILCFD = OLACFKILCFD_list.ToArray();

		List<ECMPIGNKJOK> MIOCOKLMLBD_list = new List<ECMPIGNKJOK>();
		for(int MIOCOKLMLBD_idx = 0; MIOCOKLMLBD_idx < res_readData.OLLJCDPOAAILength; MIOCOKLMLBD_idx++)
		{
			HCMLGJBONGC MIOCOKLMLBD_readData = res_readData.GetOLLJCDPOAAI(MIOCOKLMLBD_idx);
			ECMPIGNKJOK MIOCOKLMLBD_data = new ECMPIGNKJOK();

			MIOCOKLMLBD_data.PPFNGGCBJKC = MIOCOKLMLBD_readData.BBPHAPFBFHK;
			MIOCOKLMLBD_data.GNFBMCGMCFO = MIOCOKLMLBD_readData.GEAIPAEKLNF;
			MIOCOKLMLBD_data.BFFGFAMJAIG = MIOCOKLMLBD_readData.JGILGOILJNK;
			MIOCOKLMLBD_list.Add(MIOCOKLMLBD_data);
		}
		res_data.MIOCOKLMLBD = MIOCOKLMLBD_list.ToArray();

		List<NIJKKLJAABL> IEJLJIHIDJC_list = new List<NIJKKLJAABL>();
		for(int IEJLJIHIDJC_idx = 0; IEJLJIHIDJC_idx < res_readData.BHNBMLKMLGNLength; IEJLJIHIDJC_idx++)
		{
			DCBENCFJMOC IEJLJIHIDJC_readData = res_readData.GetBHNBMLKMLGN(IEJLJIHIDJC_idx);
			NIJKKLJAABL IEJLJIHIDJC_data = new NIJKKLJAABL();

			IEJLJIHIDJC_data.KHPHAAMGMJP = IEJLJIHIDJC_readData.OEBLGFLPMNE;
			IEJLJIHIDJC_data.OFIAENKCJME = IEJLJIHIDJC_readData.BJELMJJFMBI;
			List<int> JMLCLHHLJHM_list = new List<int>();
			for(int JMLCLHHLJHM_idx = 0; JMLCLHHLJHM_idx < IEJLJIHIDJC_readData.IHNCJBFCAAILength; JMLCLHHLJHM_idx++)
			{
				JMLCLHHLJHM_list.Add(IEJLJIHIDJC_readData.GetIHNCJBFCAAI(JMLCLHHLJHM_idx));
			}
			IEJLJIHIDJC_data.JMLCLHHLJHM = JMLCLHHLJHM_list.ToArray();

			IEJLJIHIDJC_list.Add(IEJLJIHIDJC_data);
		}
		res_data.IEJLJIHIDJC = IEJLJIHIDJC_list.ToArray();

		return res_data;
	}
}
