using FlatBuffers;
using System.Collections.Generic;

public class GGDEOLDOFMH
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int AGNHPHEJKMK { get; set; } // 0xC BCKMGEBHABF MNJIGLFFJAH MEHEHNALGIH
	public int EILKGEADKGH { get; set; } // 0x10 PBIPJHCABED NPDDACIHBKD BJJMCKHBPNH
	public int GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int PLALNIIBLOF { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string ADCMNODJBGJ { get; set; } // 0x1C PDOIKFFAKNG AJDDKABOOLK GHAHAGNIELN
	public string[] BNMCMNPPPCI { get; set; } // 0x20 OJDCFHIBPBH OJPIPIHODMK MHKOFEGPBMG
	public int EMNLOGDDOBC { get; set; } // 0x24 LKKBIIFHIJH LLPCDDPBCIF IANFOOFFAHD
	public int IICECOLFEEL { get; set; } // 0x28 GDCLPLLNMAP NPILABMMKMB AFPJONFBLEO
	public int IJEKNCDIIAE { get; set; } // 0x2C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int NNDBJGDFEEM { get; set; } // 0x30 CNDGBLDLDCC EHNOFMPHLFC GCANPOPEKEE
	public int DOOGFEGEKLG { get; set; } // 0x34 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public int LLNDMKBBNIJ { get; set; } // 0x38 BGOALFDCFBL OHMCGADLNCA KJNHDFEGEGE
}
public class HHHEIMGFICD
{
	public GGDEOLDOFMH[] EEMGLFBGGKN { get; set; } // 0x8 HECMJMBFELK JBBCGDLBBAA FANKGMKNGGK
	public static HHHEIMGFICD HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1759CA8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		EBDJIPDILLC res_readData = EBDJIPDILLC.GetRootAsEBDJIPDILLC(buffer);
		HHHEIMGFICD res_data = new HHHEIMGFICD();

		List<GGDEOLDOFMH> EEMGLFBGGKN_list = new List<GGDEOLDOFMH>();
		for(int EEMGLFBGGKN_idx = 0; EEMGLFBGGKN_idx < res_readData.BIDEEFOGFCGLength; EEMGLFBGGKN_idx++)
		{
			EJMDBHGILEI EEMGLFBGGKN_readData = res_readData.GetBIDEEFOGFCG(EEMGLFBGGKN_idx);
			GGDEOLDOFMH EEMGLFBGGKN_data = new GGDEOLDOFMH();

			EEMGLFBGGKN_data.PPFNGGCBJKC = EEMGLFBGGKN_readData.BBPHAPFBFHK;
			EEMGLFBGGKN_data.AGNHPHEJKMK = EEMGLFBGGKN_readData.HLPHBGLMBIO;
			EEMGLFBGGKN_data.EILKGEADKGH = EEMGLFBGGKN_readData.BPMBFFDNMDD;
			EEMGLFBGGKN_data.GBJFNGCDKPM = EEMGLFBGGKN_readData.LPJPOOHJKAE;
			EEMGLFBGGKN_data.PLALNIIBLOF = EEMGLFBGGKN_readData.CFLMCGOJJJD;
			EEMGLFBGGKN_data.ADCMNODJBGJ = EEMGLFBGGKN_readData.AFJJKGBHFJP;
			List<string> BNMCMNPPPCI_list = new List<string>();
			for(int BNMCMNPPPCI_idx = 0; BNMCMNPPPCI_idx < EEMGLFBGGKN_readData.NKCBBELDHOILength; BNMCMNPPPCI_idx++)
			{
				BNMCMNPPPCI_list.Add(EEMGLFBGGKN_readData.GetNKCBBELDHOI(BNMCMNPPPCI_idx));
			}
			EEMGLFBGGKN_data.BNMCMNPPPCI = BNMCMNPPPCI_list.ToArray();

			EEMGLFBGGKN_data.EMNLOGDDOBC = EEMGLFBGGKN_readData.PPGJPNONPDB;
			EEMGLFBGGKN_data.IICECOLFEEL = EEMGLFBGGKN_readData.COBFEKPMGIB;
			EEMGLFBGGKN_data.IJEKNCDIIAE = EEMGLFBGGKN_readData.OFMGALJGDAO;
			EEMGLFBGGKN_data.NNDBJGDFEEM = EEMGLFBGGKN_readData.CCIHMCAPHCB;
			EEMGLFBGGKN_data.DOOGFEGEKLG = EEMGLFBGGKN_readData.GEJGMBBCFEE;
			EEMGLFBGGKN_data.LLNDMKBBNIJ = EEMGLFBGGKN_readData.CNNEAFFOPAO;
			EEMGLFBGGKN_list.Add(EEMGLFBGGKN_data);
		}
		res_data.EEMGLFBGGKN = EEMGLFBGGKN_list.ToArray();

		return res_data;
	}
}
