using FlatBuffers;
using System.Collections.Generic;

public class LFFAKLJILCM
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD_RankingName { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public string IDGAEEJLGIK { get; set; } // 0x10 MJHNCPIAJCK HDLHFAFLMLD PICAFNJCKOI
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0x14 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public uint HFNIHKOAMGC { get; set; } // 0x18 FHBGLLIFKHM ECGBAIBHGFP CGCGLFDKHPC
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x1C FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public string OGMGLOFKKPA { get; set; } // 0x20 IAAEFKNBJMJ IDPAEJFBCMD JEIDAEPANEH
	public uint MOEKELIIDEO_SaveIdx { get; set; } // 0x24 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x28 JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint EHHFFKAFOMC { get; set; } // 0x2C MDCEFKJDJIJ EMIPFAAPLIB JHGMJLNGOGD
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x30 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x34 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x38 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x3C BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x40 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JBFDHOIKAIK_InventoryEndDate { get; set; } // 0x44 HKLAIJDEMID GBNKCHLEGPH AAKNFOAHCCI
	public uint KHIKEGLBGAF_RankingRewardScene { get; set; } // 0x48 OAPPFIGOMHO FAHFDEFDLMH OJJMIBDFGBG
	public uint DPJCFLKFEPN { get; set; } // 0x4C IPODKLGLHPC MEAAAGCCAPI GNMJKJHPIOG
	public uint[] EEOGPJJCKHH_Drops { get; set; } // 0x50 CPNKKFMLHFL BBBPKCMKJEF CDMJOOGMGNP
	public uint JMJDLDEIFKE { get; set; } // 0x54 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO_DayGroup { get; set; } // 0x58 IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE_KeyPrefix { get; set; } // 0x5C AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x60 HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public int MJBKGOJBPAD_item_type { get; set; } // 0x64 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public uint MPKNCMEAMLO { get; set; } // 0x68 PCGLIOIAEPM JDFHGPLACGI NEFEJGOEIMM
	public string KOHMHBGOFFI_free_music { get; set; } // 0x6C JLLIIMINNHM GLMMBMGFOMJ MPHABIGJJJH
	public uint AHKPNPNOAMO_ExtreamOpen { get; set; } // 0x70 AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
	public string FEMMDNIELFC_Desc { get; set; } // 0x74 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string HKEAFPNNAPC { get; set; } // 0x78 DFJAALEBDEA HBBEMBHDFKF DELEAPCEANK
	public string MCDPPHKEMJI { get; set; } // 0x7C CADCNPAEDII OBCNBGENDBE PAALJHPNIFG
	public string BJHHDGCOACI { get; set; } // 0x80 DFIBGNIMEBI MDPFAPFHCAI ADHLJBBAGNF
	public string JDDIOIMOFDE { get; set; } // 0x84 LLCBHGKCOGI DECDACJPOPI DEMONJBBJKN
	public uint[] DMDHPBNAPKI { get; set; } // 0x88 EKMNICNMONA EGOOPMEIAKM MMGCGEAJKEO
	public uint HKKNEAGCIEB_RankingSupport { get; set; } // 0x8C DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI_RankingThreshold { get; set; } // 0x90 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public int[] GHIKEPLBHHG { get; set; } // 0x94 IBFJDIMOKIC CKNNOBGPBFB JOOCBEAPKGA
	public string OMCAOJJGOGG_Lb { get; set; } // 0x98 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM_StartAdventureId { get; set; } // 0x9C AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP_EndAdventureId { get; set; } // 0xA0 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC_HelpIds { get; set; } // 0xA4 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int EKJFNHHKBPL { get; set; } // 0xA8 BPPNFOAFCPE BONLIFKCIFO HBFFBCJHJAC
}
public class MCFPAFGFPJC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FOILNHKHHDF_pt { get; set; } // 0xC LNNCNOIGMGM FOFBHPJDHFO LHPMDDKPJDP
	public int[] AIHOJKFNEEN_itm { get; set; } // 0x10 GGBFCEFNCFM BGFIPHMMOGA DHAIHODDOGM
	public uint[] BFINGCJHOHI_cnt { get; set; } // 0x14 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public uint[] JJHPDDPKBHF { get; set; } // 0x18 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public int JOPPFEHKNFO_Pickup { get; set; } // 0x1C LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
	public uint[] HJAFPEBIBOP_Limit { get; set; } // 0x20 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class ENAEMKEKAOE
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MPLGPBNJDJB_FreeMusicId { get; set; } // 0x10 GNKPHDHIMAC KADAEAOKJNE MBKFNLHPNPP
	public uint DKHIHHMOIKM_bns { get; set; } // 0x14 DDCGLGKFHPP OCOHLFAFINM DPEOFJJLPML
	public int PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class OFFLOKADBGI
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM_typ { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG_odr { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC_Desc { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE_DescBalloon { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC_item_count { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ_Link { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO_st { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM_end { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
	public uint HJAFPEBIBOP_Limit { get; set; } // 0x68 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class DPCNINPPGFC
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class KNLJCIJAAME
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class CBFHDJAILAO
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KFCIJBLDHOK_v1 { get; set; } // 0xC JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int JLEIHOEGMOP_v2 { get; set; } // 0x10 JLNAMGLBPME JJGFFGDDFPA LIIFHDMHLHP
}
public class KKDKCGPPEJD
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GBJFNGCDKPM_typ { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int JBGEEPFKIGG_val { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int MAFAIIHJAFG_spurt { get; set; } // 0x14 FIINMMHBBJF LLNFMLKMFKB PCICDCAILIF
}
public class CMLHFCEIABD
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PDBPFJJCADD_open_at { get; set; } // 0xC PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x10 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public string FEMMDNIELFC_Desc { get; set; } // 0x14 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
}
public class KPFPLABANJG
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int CNKFPJCGNFE_SceneId { get; set; } // 0xC OGPCJNOKMAM GJBOGOFHGNP GJDGIDCMJMH
	public int GNFBMCGMCFO_BonusBefore { get; set; } // 0x10 LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG_BonusAfter { get; set; } // 0x14 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class CNFAHCDJNKD
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GNFBMCGMCFO_BonusBefore { get; set; } // 0xC LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG_BonusAfter { get; set; } // 0x10 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class CFFKBKJMNNN
{
	public int KHPHAAMGMJP_EpId { get; set; } // 0x8 FHLAGLBMFHE ABFDDKBBPCH MHDOIIEMDEH
	public int OFIAENKCJME_BaseBonus { get; set; } // 0xC NHHGGLNCELI KADLAKFANGA AIDAPNCEPOB
	public int[] JMLCLHHLJHM { get; set; } // 0x10 HCOPKKMMEAL KCJKEEAILGB EGEABIGCJJK
}
public class HMNJADGBKFA
{
	public LFFAKLJILCM HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public MCFPAFGFPJC[] MCHFABAKPMH { get; set; } // 0xC BFBKDKPKLMM IPDEGCCJALP HHNBEKGDAPD
	public ENAEMKEKAOE[] GHIHAGAOPNC { get; set; } // 0x10 CNAPBHHKEPH OHCBAEGAKOH OIDPGMCLNBF
	public OFFLOKADBGI[] MDDOGIAFDEI { get; set; } // 0x14 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public DPCNINPPGFC[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public KNLJCIJAAME[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public CBFHDJAILAO[] KIEKMCKCMGD { get; set; } // 0x20 AHOFIJDMDAO EEMBMMJIHPE CDHPBECJGGO
	public KKDKCGPPEJD[] MHKNGJMEGFI { get; set; } // 0x24 DGMLFJKGMLO DJAALDIHICI ILMEEBDMNBJ
	public CMLHFCEIABD[] IHNBOEPLJKE { get; set; } // 0x28 MMGGONDGLOL EMLHCNDOCCP GKPFNDEHLJD
	public KPFPLABANJG[] OLACFKILCFD { get; set; } // 0x2C ODAEGEAACIA KCGGGPCDEPK ANKJOEMLFCI
	public CNFAHCDJNKD[] MIOCOKLMLBD { get; set; } // 0x30 COILMDCEJLD MNIALHMNHFM OGLAMDPDFCD
	public CFFKBKJMNNN[] IEJLJIHIDJC { get; set; } // 0x34 CDHGOELCBFB DGNNDIPELAP BFHEABPGGHO
	public static HMNJADGBKFA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x15F6C9C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		KBPJMHKBEAJ res_readData = KBPJMHKBEAJ.GetRootAsKBPJMHKBEAJ(buffer);
		HMNJADGBKFA res_data = new HMNJADGBKFA();

		EGJJJNCPNPD HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		LFFAKLJILCM HMBHNLCFDIH_data = new LFFAKLJILCM();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD_RankingName = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.IDGAEEJLGIK = HMBHNLCFDIH_readData.NNCGCDNLJEE;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.HFNIHKOAMGC = HMBHNLCFDIH_readData.HEMLBADKAOA;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.OGMGLOFKKPA = HMBHNLCFDIH_readData.LIBHMBEONKC;
		HMBHNLCFDIH_data.MOEKELIIDEO_SaveIdx = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.EHHFFKAFOMC = HMBHNLCFDIH_readData.DEPHCHOBAJG;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JBFDHOIKAIK_InventoryEndDate = HMBHNLCFDIH_readData.IDMMPIIIPLL;
		HMBHNLCFDIH_data.KHIKEGLBGAF_RankingRewardScene = HMBHNLCFDIH_readData.HKPPDACCCOH;
		HMBHNLCFDIH_data.DPJCFLKFEPN = HMBHNLCFDIH_readData.NAMFJMCKFIF;
		List<uint> EEOGPJJCKHH_list = new List<uint>();
		for(int EEOGPJJCKHH_idx = 0; EEOGPJJCKHH_idx < HMBHNLCFDIH_readData.EBFEIMNOLHPLength; EEOGPJJCKHH_idx++)
		{
			EEOGPJJCKHH_list.Add(HMBHNLCFDIH_readData.GetEBFEIMNOLHP(EEOGPJJCKHH_idx));
		}
		HMBHNLCFDIH_data.EEOGPJJCKHH_Drops = EEOGPJJCKHH_list.ToArray();

		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO_DayGroup = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE_KeyPrefix = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.MJBKGOJBPAD_item_type = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.MPKNCMEAMLO = HMBHNLCFDIH_readData.ALNLBALBCJK;
		HMBHNLCFDIH_data.KOHMHBGOFFI_free_music = HMBHNLCFDIH_readData.GPCEIBGOEGB;
		HMBHNLCFDIH_data.AHKPNPNOAMO_ExtreamOpen = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		HMBHNLCFDIH_data.FEMMDNIELFC_Desc = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKEAFPNNAPC = HMBHNLCFDIH_readData.IAOHBNNABEA;
		HMBHNLCFDIH_data.MCDPPHKEMJI = HMBHNLCFDIH_readData.GPGAAMAIPOA;
		HMBHNLCFDIH_data.BJHHDGCOACI = HMBHNLCFDIH_readData.CKPGPEBLNFH;
		HMBHNLCFDIH_data.JDDIOIMOFDE = HMBHNLCFDIH_readData.MCBLMLBNNJJ;
		List<uint> DMDHPBNAPKI_list = new List<uint>();
		for(int DMDHPBNAPKI_idx = 0; DMDHPBNAPKI_idx < HMBHNLCFDIH_readData.LCDPKHOIDJHLength; DMDHPBNAPKI_idx++)
		{
			DMDHPBNAPKI_list.Add(HMBHNLCFDIH_readData.GetLCDPKHOIDJH(DMDHPBNAPKI_idx));
		}
		HMBHNLCFDIH_data.DMDHPBNAPKI = DMDHPBNAPKI_list.ToArray();

		HMBHNLCFDIH_data.HKKNEAGCIEB_RankingSupport = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI_RankingThreshold = JHPCPNJJHLI_list.ToArray();

		List<int> GHIKEPLBHHG_list = new List<int>();
		for(int GHIKEPLBHHG_idx = 0; GHIKEPLBHHG_idx < HMBHNLCFDIH_readData.KMDIENAOMLHLength; GHIKEPLBHHG_idx++)
		{
			GHIKEPLBHHG_list.Add(HMBHNLCFDIH_readData.GetKMDIENAOMLH(GHIKEPLBHHG_idx));
		}
		HMBHNLCFDIH_data.GHIKEPLBHHG = GHIKEPLBHHG_list.ToArray();

		HMBHNLCFDIH_data.OMCAOJJGOGG_Lb = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM_StartAdventureId = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP_EndAdventureId = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC_HelpIds = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.EKJFNHHKBPL = HMBHNLCFDIH_readData.HFKHLKGAJEL;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<MCFPAFGFPJC> MCHFABAKPMH_list = new List<MCFPAFGFPJC>();
		for(int MCHFABAKPMH_idx = 0; MCHFABAKPMH_idx < res_readData.KJFDCEGGPPHLength; MCHFABAKPMH_idx++)
		{
			NKAGFIBDIJL MCHFABAKPMH_readData = res_readData.GetKJFDCEGGPPH(MCHFABAKPMH_idx);
			MCFPAFGFPJC MCHFABAKPMH_data = new MCFPAFGFPJC();

			MCHFABAKPMH_data.PPFNGGCBJKC_id = MCHFABAKPMH_readData.BBPHAPFBFHK;
			MCHFABAKPMH_data.FOILNHKHHDF_pt = MCHFABAKPMH_readData.HJNPKHJJDBB;
			List<int> AIHOJKFNEEN_list = new List<int>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < MCHFABAKPMH_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(MCHFABAKPMH_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			MCHFABAKPMH_data.AIHOJKFNEEN_itm = AIHOJKFNEEN_list.ToArray();

			List<uint> BFINGCJHOHI_list = new List<uint>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < MCHFABAKPMH_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(MCHFABAKPMH_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			MCHFABAKPMH_data.BFINGCJHOHI_cnt = BFINGCJHOHI_list.ToArray();

			List<uint> JJHPDDPKBHF_list = new List<uint>();
			for(int JJHPDDPKBHF_idx = 0; JJHPDDPKBHF_idx < MCHFABAKPMH_readData.OOJBHHPJONJLength; JJHPDDPKBHF_idx++)
			{
				JJHPDDPKBHF_list.Add(MCHFABAKPMH_readData.GetOOJBHHPJONJ(JJHPDDPKBHF_idx));
			}
			MCHFABAKPMH_data.JJHPDDPKBHF = JJHPDDPKBHF_list.ToArray();

			MCHFABAKPMH_data.JOPPFEHKNFO_Pickup = MCHFABAKPMH_readData.ALPALMJMJJK;
			List<uint> HJAFPEBIBOP_list = new List<uint>();
			for(int HJAFPEBIBOP_idx = 0; HJAFPEBIBOP_idx < MCHFABAKPMH_readData.PODPGCKCBEOLength; HJAFPEBIBOP_idx++)
			{
				HJAFPEBIBOP_list.Add(MCHFABAKPMH_readData.GetPODPGCKCBEO(HJAFPEBIBOP_idx));
			}
			MCHFABAKPMH_data.HJAFPEBIBOP_Limit = HJAFPEBIBOP_list.ToArray();

			MCHFABAKPMH_list.Add(MCHFABAKPMH_data);
		}
		res_data.MCHFABAKPMH = MCHFABAKPMH_list.ToArray();

		List<ENAEMKEKAOE> GHIHAGAOPNC_list = new List<ENAEMKEKAOE>();
		for(int GHIHAGAOPNC_idx = 0; GHIHAGAOPNC_idx < res_readData.AJMKEFMPKHBLength; GHIHAGAOPNC_idx++)
		{
			AEDNLIGLDLI GHIHAGAOPNC_readData = res_readData.GetAJMKEFMPKHB(GHIHAGAOPNC_idx);
			ENAEMKEKAOE GHIHAGAOPNC_data = new ENAEMKEKAOE();

			GHIHAGAOPNC_data.PPFNGGCBJKC_id = GHIHAGAOPNC_readData.BBPHAPFBFHK;
			GHIHAGAOPNC_data.PLALNIIBLOF_en = GHIHAGAOPNC_readData.CFLMCGOJJJD;
			GHIHAGAOPNC_data.MPLGPBNJDJB_FreeMusicId = GHIHAGAOPNC_readData.IAPFGOHKAGE;
			GHIHAGAOPNC_data.DKHIHHMOIKM_bns = GHIHAGAOPNC_readData.DJBJGNJAHHP;
			GHIHAGAOPNC_data.PDBPFJJCADD_open_at = GHIHAGAOPNC_readData.NJLJEKDBPCH;
			GHIHAGAOPNC_data.FDBNFFNFOND_close_at = GHIHAGAOPNC_readData.MAOAGDBDBIB;
			GHIHAGAOPNC_list.Add(GHIHAGAOPNC_data);
		}
		res_data.GHIHAGAOPNC = GHIHAGAOPNC_list.ToArray();

		List<OFFLOKADBGI> MDDOGIAFDEI_list = new List<OFFLOKADBGI>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			HNIEJMNIBMD MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			OFFLOKADBGI MDDOGIAFDEI_data = new OFFLOKADBGI();

			MDDOGIAFDEI_data.PPFNGGCBJKC_id = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF_en = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM_typ = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG_odr = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC_Desc = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE_DescBalloon = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN_ItemId = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC_item_count = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ_Link = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO_st = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM_end = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_data.HJAFPEBIBOP_Limit = MDDOGIAFDEI_readData.HBHEHJDPEBI;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<DPCNINPPGFC> BHGDNGHDDAC_list = new List<DPCNINPPGFC>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			MAAGLHIIMOK BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			DPCNINPPGFC BHGDNGHDDAC_data = new DPCNINPPGFC();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<KNLJCIJAAME> MHGMDJNOLMI_list = new List<KNLJCIJAAME>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			EKBIGBOIGPH MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			KNLJCIJAAME MHGMDJNOLMI_data = new KNLJCIJAAME();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<CBFHDJAILAO> KIEKMCKCMGD_list = new List<CBFHDJAILAO>();
		for(int KIEKMCKCMGD_idx = 0; KIEKMCKCMGD_idx < res_readData.FBAHAFKCMMHLength; KIEKMCKCMGD_idx++)
		{
			KAGKHJNAHHL KIEKMCKCMGD_readData = res_readData.GetFBAHAFKCMMH(KIEKMCKCMGD_idx);
			CBFHDJAILAO KIEKMCKCMGD_data = new CBFHDJAILAO();

			KIEKMCKCMGD_data.PPFNGGCBJKC_id = KIEKMCKCMGD_readData.BBPHAPFBFHK;
			KIEKMCKCMGD_data.KFCIJBLDHOK_v1 = KIEKMCKCMGD_readData.MCJNHPMBPIJ;
			KIEKMCKCMGD_data.JLEIHOEGMOP_v2 = KIEKMCKCMGD_readData.MGJKFKDICGC;
			KIEKMCKCMGD_list.Add(KIEKMCKCMGD_data);
		}
		res_data.KIEKMCKCMGD = KIEKMCKCMGD_list.ToArray();

		List<KKDKCGPPEJD> MHKNGJMEGFI_list = new List<KKDKCGPPEJD>();
		for(int MHKNGJMEGFI_idx = 0; MHKNGJMEGFI_idx < res_readData.GGKDJGGAFKALength; MHKNGJMEGFI_idx++)
		{
			EEBNFEADGDN MHKNGJMEGFI_readData = res_readData.GetGGKDJGGAFKA(MHKNGJMEGFI_idx);
			KKDKCGPPEJD MHKNGJMEGFI_data = new KKDKCGPPEJD();

			MHKNGJMEGFI_data.PPFNGGCBJKC_id = MHKNGJMEGFI_readData.BBPHAPFBFHK;
			MHKNGJMEGFI_data.GBJFNGCDKPM_typ = MHKNGJMEGFI_readData.LPJPOOHJKAE;
			MHKNGJMEGFI_data.JBGEEPFKIGG_val = MHKNGJMEGFI_readData.KJFEBMBHKOC;
			MHKNGJMEGFI_data.MAFAIIHJAFG_spurt = MHKNGJMEGFI_readData.LAIEPFCPDLK;
			MHKNGJMEGFI_list.Add(MHKNGJMEGFI_data);
		}
		res_data.MHKNGJMEGFI = MHKNGJMEGFI_list.ToArray();

		List<CMLHFCEIABD> IHNBOEPLJKE_list = new List<CMLHFCEIABD>();
		for(int IHNBOEPLJKE_idx = 0; IHNBOEPLJKE_idx < res_readData.JHDOILHEBOGLength; IHNBOEPLJKE_idx++)
		{
			PHLPHMPPNON IHNBOEPLJKE_readData = res_readData.GetJHDOILHEBOG(IHNBOEPLJKE_idx);
			CMLHFCEIABD IHNBOEPLJKE_data = new CMLHFCEIABD();

			IHNBOEPLJKE_data.PPFNGGCBJKC_id = IHNBOEPLJKE_readData.BBPHAPFBFHK;
			IHNBOEPLJKE_data.PDBPFJJCADD_open_at = IHNBOEPLJKE_readData.NJLJEKDBPCH;
			IHNBOEPLJKE_data.FDBNFFNFOND_close_at = IHNBOEPLJKE_readData.MAOAGDBDBIB;
			IHNBOEPLJKE_data.FEMMDNIELFC_Desc = IHNBOEPLJKE_readData.NNKLANONDOM;
			IHNBOEPLJKE_list.Add(IHNBOEPLJKE_data);
		}
		res_data.IHNBOEPLJKE = IHNBOEPLJKE_list.ToArray();

		List<KPFPLABANJG> OLACFKILCFD_list = new List<KPFPLABANJG>();
		for(int OLACFKILCFD_idx = 0; OLACFKILCFD_idx < res_readData.HDNMEPFHLNFLength; OLACFKILCFD_idx++)
		{
			DGPHIEINKFP OLACFKILCFD_readData = res_readData.GetHDNMEPFHLNF(OLACFKILCFD_idx);
			KPFPLABANJG OLACFKILCFD_data = new KPFPLABANJG();

			OLACFKILCFD_data.PPFNGGCBJKC_id = OLACFKILCFD_readData.BBPHAPFBFHK;
			OLACFKILCFD_data.CNKFPJCGNFE_SceneId = OLACFKILCFD_readData.DPFDOIIOICA;
			OLACFKILCFD_data.GNFBMCGMCFO_BonusBefore = OLACFKILCFD_readData.GEAIPAEKLNF;
			OLACFKILCFD_data.BFFGFAMJAIG_BonusAfter = OLACFKILCFD_readData.JGILGOILJNK;
			OLACFKILCFD_list.Add(OLACFKILCFD_data);
		}
		res_data.OLACFKILCFD = OLACFKILCFD_list.ToArray();

		List<CNFAHCDJNKD> MIOCOKLMLBD_list = new List<CNFAHCDJNKD>();
		for(int MIOCOKLMLBD_idx = 0; MIOCOKLMLBD_idx < res_readData.OLLJCDPOAAILength; MIOCOKLMLBD_idx++)
		{
			DMAHJEKCGNM MIOCOKLMLBD_readData = res_readData.GetOLLJCDPOAAI(MIOCOKLMLBD_idx);
			CNFAHCDJNKD MIOCOKLMLBD_data = new CNFAHCDJNKD();

			MIOCOKLMLBD_data.PPFNGGCBJKC_id = MIOCOKLMLBD_readData.BBPHAPFBFHK;
			MIOCOKLMLBD_data.GNFBMCGMCFO_BonusBefore = MIOCOKLMLBD_readData.GEAIPAEKLNF;
			MIOCOKLMLBD_data.BFFGFAMJAIG_BonusAfter = MIOCOKLMLBD_readData.JGILGOILJNK;
			MIOCOKLMLBD_list.Add(MIOCOKLMLBD_data);
		}
		res_data.MIOCOKLMLBD = MIOCOKLMLBD_list.ToArray();

		List<CFFKBKJMNNN> IEJLJIHIDJC_list = new List<CFFKBKJMNNN>();
		for(int IEJLJIHIDJC_idx = 0; IEJLJIHIDJC_idx < res_readData.BHNBMLKMLGNLength; IEJLJIHIDJC_idx++)
		{
			MAJJICHLHLP IEJLJIHIDJC_readData = res_readData.GetBHNBMLKMLGN(IEJLJIHIDJC_idx);
			CFFKBKJMNNN IEJLJIHIDJC_data = new CFFKBKJMNNN();

			IEJLJIHIDJC_data.KHPHAAMGMJP_EpId = IEJLJIHIDJC_readData.OEBLGFLPMNE;
			IEJLJIHIDJC_data.OFIAENKCJME_BaseBonus = IEJLJIHIDJC_readData.BJELMJJFMBI;
			List<int> JMLCLHHLJHM_list = new List<int>();
			for(int JMLCLHHLJHM_idx = 0; JMLCLHHLJHM_idx < IEJLJIHIDJC_readData.IHNCJBFCAAILength; JMLCLHHLJHM_idx++)
			{
				JMLCLHHLJHM_list.Add(IEJLJIHIDJC_readData.GetIHNCJBFCAAI(JMLCLHHLJHM_idx));
			}
			IEJLJIHIDJC_data.JMLCLHHLJHM = JMLCLHHLJHM_list.ToArray();

			IEJLJIHIDJC_list.Add(IEJLJIHIDJC_data);
		}
		res_data.IEJLJIHIDJC = IEJLJIHIDJC_list.ToArray();

		return res_data;
	}
}
