using FlatBuffers;
using System.Collections.Generic;

public class CCNNJMCKOGH
{
	public uint PFNBMPCIIJJ_heal_sec { get; set; } // 0x8 JPCAPPODBKL FHKONOMKGBN BLIGJALGJIK
	public int KBNGOBEAHIC_key_path { get; set; } // 0xC JDAOMCMILGK JKEJHFKAKDN OKFDFHNIILF
	public int KHGJIGNHAGD_retry_try_cnt { get; set; } // 0x10 OCFEDBBLLDD NLNDHIKBGOA OACFGDPBLCP
	public int JOIEHMBKJHI_retry_wait_ms { get; set; } // 0x14 LELAEJNBNLI LKFCFNJDCOD EAKKAOCBAMF
	public int PIJNJBJMFHL_plv { get; set; } // 0x18 FDEADNAIFEB DJIHFCAPEEG DNPADGOOKBA
	public uint KMNPFOPBDMA_RenameDay { get; set; } // 0x1C JKOLECDLNOM BKMILJONJDL PLJFDIKPMMH
	public uint[] JEDMLKOECHN_gacha_hour { get; set; } // 0x20 INEBMKHHGJD BONJKMBJIJE EMHDLMOJHDD
	public int JFDDEKJKGDC { get; set; } // 0x24 CKGACKACFOC LPAPFJLMHHF LLIJLKNLMJO
}
public class CAEJOAOPJCJ
{
	public string MKANHLNEEGL_filter { get; set; } // 0x8 FCAGKJALAAC KMICICLALGM BEMBDHHJDAH
	public uint LJNAKDMILMC_key { get; set; } // 0xC KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
}
public class KHCOEKAINPK
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string LJNAKDMILMC_key { get; set; } // 0xC KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int IKNALLJDAFH_ofs { get; set; } // 0x10 PFBNNKKDABO JAHEPHJPGBA MHODNPNIKEL
	public int NHPCKCOPKAM_from { get; set; } // 0x14 DNCPBMBLKLL GKJBCKDHCOE JJCALPLDOON
	public int PJFKNNNDMIA_to { get; set; } // 0x18 CBNKKOJHMNH HLKDJMHLHNL APDEHBODBOO
	public uint PLGFGIAHDHJ_fr { get; set; } // 0x1C NJMPLCGOCFJ HPEHCMDMKCG IENOPFCNHBP
	public uint DLAIGBEOGNN_ex { get; set; } // 0x20 ADEEDEMALFA KFHHLPALPDI PEPBOMHIJNH
	public uint MLPLGFLKKLI_Ipp { get; set; } // 0x24 OBLDCKNHGCD AEMHGPJHDIG AIEANAANLOO
	public uint ADPPAIPFHML_num { get; set; } // 0x28 LONDDHLNFBL LJMLHOOPGEM PHNIOCPOBGO
}
public class NNAAOAAGGCE
{
	public string PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string HJLDBEJOMIO { get; set; } // 0xC BNJJOAGLABF MDILFLMALPN KKDEJNIJBAB
}
public class FNLNOMGDCIJ
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class FIHADIALPIL
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class EOMJDOOGLIC
{
	public string GJCCGIFLKPD { get; set; } // 0x8 PKIFPNEFNMN ILCKANCKDNO IAONNNPLGHM
	public string BDCNFMMAEJJ { get; set; } // 0xC BGNPLLAOMKO BBGAEPHMCGI HOAHAGPOKOM
	public uint CJOKJFGDHLD { get; set; } // 0x10 LDIAKCPFJNC IAABIPMKOHK FLNMFNMEECC
}
public class IAIDGBJGDBH
{
	public CCNNJMCKOGH EOACHAJJLHB { get; set; } // 0x8 ABHGFDJHAPO NKIGALDEEOA JEEMNBLJMOG
	public CAEJOAOPJCJ[] POEOOJPBOJC { get; set; } // 0xC ENMIKFEDBDB GNCCEOKGKKE GENHEFPAIHO
	public KHCOEKAINPK[] KPDMCJELMCI { get; set; } // 0x10 NCMJPPALBKH BNLKAIGKGIB LHPCNDOPPMF
	public NNAAOAAGGCE[] NELGGEGAJPH { get; set; } // 0x14 FONBGKPLGJN ABEJIHHNBMJ HKIMBDOFNJN
	public FNLNOMGDCIJ[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public FIHADIALPIL[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public EOMJDOOGLIC[] GJOBPIOOEHD { get; set; } // 0x20 BGBFGBNBBGL LLACDANLENK HLHGABNJNNM
	public static IAIDGBJGDBH HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x120DA20
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		DHFKAKFHFOL res_readData = DHFKAKFHFOL.GetRootAsDHFKAKFHFOL(buffer);
		IAIDGBJGDBH res_data = new IAIDGBJGDBH();

		HGDLMDMAIHK EOACHAJJLHB_readData = res_readData.EIOJCBPLGPB;
		CCNNJMCKOGH EOACHAJJLHB_data = new CCNNJMCKOGH();

		EOACHAJJLHB_data.PFNBMPCIIJJ_heal_sec = EOACHAJJLHB_readData.ODHNEFLOILP;
		EOACHAJJLHB_data.KBNGOBEAHIC_key_path = EOACHAJJLHB_readData.ECEFNALDNGJ;
		EOACHAJJLHB_data.KHGJIGNHAGD_retry_try_cnt = EOACHAJJLHB_readData.DDCHBAJGIJL;
		EOACHAJJLHB_data.JOIEHMBKJHI_retry_wait_ms = EOACHAJJLHB_readData.PCIIMOPFEMG;
		EOACHAJJLHB_data.PIJNJBJMFHL_plv = EOACHAJJLHB_readData.GGKNGDGKMIJ;
		EOACHAJJLHB_data.KMNPFOPBDMA_RenameDay = EOACHAJJLHB_readData.ONCBLMJHMKB;
		List<uint> JEDMLKOECHN_list = new List<uint>();
		for(int JEDMLKOECHN_idx = 0; JEDMLKOECHN_idx < EOACHAJJLHB_readData.LGMELGKMCBLLength; JEDMLKOECHN_idx++)
		{
			JEDMLKOECHN_list.Add(EOACHAJJLHB_readData.GetLGMELGKMCBL(JEDMLKOECHN_idx));
		}
		EOACHAJJLHB_data.JEDMLKOECHN_gacha_hour = JEDMLKOECHN_list.ToArray();

		EOACHAJJLHB_data.JFDDEKJKGDC = EOACHAJJLHB_readData.DGGPEONPMKA;
		res_data.EOACHAJJLHB = EOACHAJJLHB_data;
		List<CAEJOAOPJCJ> POEOOJPBOJC_list = new List<CAEJOAOPJCJ>();
		for(int POEOOJPBOJC_idx = 0; POEOOJPBOJC_idx < res_readData.ENOAIJNIMECLength; POEOOJPBOJC_idx++)
		{
			BPAPHMKFBEF POEOOJPBOJC_readData = res_readData.GetENOAIJNIMEC(POEOOJPBOJC_idx);
			CAEJOAOPJCJ POEOOJPBOJC_data = new CAEJOAOPJCJ();

			POEOOJPBOJC_data.MKANHLNEEGL_filter = POEOOJPBOJC_readData.BMBEAHIAGBH;
			POEOOJPBOJC_data.LJNAKDMILMC_key = POEOOJPBOJC_readData.AGOIMGHMGOH;
			POEOOJPBOJC_list.Add(POEOOJPBOJC_data);
		}
		res_data.POEOOJPBOJC = POEOOJPBOJC_list.ToArray();

		List<KHCOEKAINPK> KPDMCJELMCI_list = new List<KHCOEKAINPK>();
		for(int KPDMCJELMCI_idx = 0; KPDMCJELMCI_idx < res_readData.EICOHLEBKLELength; KPDMCJELMCI_idx++)
		{
			BOPCBNDDJHD KPDMCJELMCI_readData = res_readData.GetEICOHLEBKLE(KPDMCJELMCI_idx);
			KHCOEKAINPK KPDMCJELMCI_data = new KHCOEKAINPK();

			KPDMCJELMCI_data.PPFNGGCBJKC_id = KPDMCJELMCI_readData.BBPHAPFBFHK;
			KPDMCJELMCI_data.LJNAKDMILMC_key = KPDMCJELMCI_readData.AGOIMGHMGOH;
			KPDMCJELMCI_data.IKNALLJDAFH_ofs = KPDMCJELMCI_readData.JPLNJKHPFCI;
			KPDMCJELMCI_data.NHPCKCOPKAM_from = KPDMCJELMCI_readData.HFEOJGNPDHI;
			KPDMCJELMCI_data.PJFKNNNDMIA_to = KPDMCJELMCI_readData.EBONAKOCJCL;
			KPDMCJELMCI_data.PLGFGIAHDHJ_fr = KPDMCJELMCI_readData.PJKMNDDCKIJ;
			KPDMCJELMCI_data.DLAIGBEOGNN_ex = KPDMCJELMCI_readData.EHIBOEAILLI;
			KPDMCJELMCI_data.MLPLGFLKKLI_Ipp = KPDMCJELMCI_readData.HCMOJIDKHHA;
			KPDMCJELMCI_data.ADPPAIPFHML_num = KPDMCJELMCI_readData.LFFMNLEJJMH;
			KPDMCJELMCI_list.Add(KPDMCJELMCI_data);
		}
		res_data.KPDMCJELMCI = KPDMCJELMCI_list.ToArray();

		List<NNAAOAAGGCE> NELGGEGAJPH_list = new List<NNAAOAAGGCE>();
		for(int NELGGEGAJPH_idx = 0; NELGGEGAJPH_idx < res_readData.JDIKIHGCOLBLength; NELGGEGAJPH_idx++)
		{
			GFDPDCODNPA NELGGEGAJPH_readData = res_readData.GetJDIKIHGCOLB(NELGGEGAJPH_idx);
			NNAAOAAGGCE NELGGEGAJPH_data = new NNAAOAAGGCE();

			NELGGEGAJPH_data.PPFNGGCBJKC_id = NELGGEGAJPH_readData.BBPHAPFBFHK;
			NELGGEGAJPH_data.HJLDBEJOMIO = NELGGEGAJPH_readData.JEAFIKCAKGD;
			NELGGEGAJPH_list.Add(NELGGEGAJPH_data);
		}
		res_data.NELGGEGAJPH = NELGGEGAJPH_list.ToArray();

		List<FNLNOMGDCIJ> BHGDNGHDDAC_list = new List<FNLNOMGDCIJ>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			BKOCGOPJMPI BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			FNLNOMGDCIJ BHGDNGHDDAC_data = new FNLNOMGDCIJ();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<FIHADIALPIL> MHGMDJNOLMI_list = new List<FIHADIALPIL>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			EBMOMBAFGEB MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			FIHADIALPIL MHGMDJNOLMI_data = new FIHADIALPIL();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<EOMJDOOGLIC> GJOBPIOOEHD_list = new List<EOMJDOOGLIC>();
		for(int GJOBPIOOEHD_idx = 0; GJOBPIOOEHD_idx < res_readData.CBMKDHMLKGELength; GJOBPIOOEHD_idx++)
		{
			BKAHCKIDMFJ GJOBPIOOEHD_readData = res_readData.GetCBMKDHMLKGE(GJOBPIOOEHD_idx);
			EOMJDOOGLIC GJOBPIOOEHD_data = new EOMJDOOGLIC();

			GJOBPIOOEHD_data.GJCCGIFLKPD = GJOBPIOOEHD_readData.BPLBMCHILPG;
			GJOBPIOOEHD_data.BDCNFMMAEJJ = GJOBPIOOEHD_readData.DNPMJEFJFCN;
			GJOBPIOOEHD_data.CJOKJFGDHLD = GJOBPIOOEHD_readData.NIBEHMBNEOM;
			GJOBPIOOEHD_list.Add(GJOBPIOOEHD_data);
		}
		res_data.GJOBPIOOEHD = GJOBPIOOEHD_list.ToArray();

		return res_data;
	}
}
