using FlatBuffers;
using System.Collections.Generic;

public class FGABLOBFLHC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public uint OCAMDLMPBGA_dv { get; set; } // 0xC JKDMAFHPKDJ DHOGDENEIOI_get_dv DBDFNFLGDFN_set_dv
	public uint LKMHPJKIFDN_md { get; set; } // 0x10 CJAAANEJOAK LAGBBLNKFFG_get_md OBHBLAIPBFO_set_md
	public uint DLAIGBEOGNN_ex { get; set; } // 0x14 ADEEDEMALFA KFHHLPALPDI_get_ex PEPBOMHIJNH_set_ex
	public uint PLALNIIBLOF_en { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int IJEKNCDIIAE_mver { get; set; } // 0x1C FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int DBHPPMPNCKF { get; set; } // 0x20 PLPJBFEDAOM JHLPDKDGDJB_get_ GBKBPCELENK_set_
	public int GMOOKMONMMD { get; set; } // 0x24 POEDEEAABOK LMNLEACGCGF_get_ BPCNCBENPAD_set_
	public int DOJAMIPOKBD { get; set; } // 0x28 FACHAGDIPHF OLENMLPLPCM_get_ PJPIGHFAABB_set_
	public int MDEBEGADHOH { get; set; } // 0x2C IEAMHLCNGDC GBGKHOKBPFM_get_ DKGHKHPDMAE_set_
	public int JILNNPKFKEK { get; set; } // 0x30 BLMIMJFOHLP FONALDEFKFK_get_ AAIAHAOEDLA_set_
	public int GOFFPLJKIIB { get; set; } // 0x34 OBAKBGAJPEI BBNJAOOJFGA_get_ NEDJCHBKINE_set_
	public int NFEJAAOAFPG { get; set; } // 0x38 PDCBJPFIIBO OGNOBILICJE_get_ FGHMAIMKBMJ_set_
	public int[] BFIFIDKOJGD { get; set; } // 0x3C PHJFHDJCLCJ DKPGPLFHGAI_get_ DAOGMNDELMD_set_
	public int[] AJNPNDIDJLD { get; set; } // 0x40 KNIHGKCAJHI HMNMPJPLKKD_get_ BHJDILEDECA_set_
	public int[] GMKDHMPGLFL { get; set; } // 0x44 NDKGBLDKBFH HHPAKPMAJIH_get_ EPAKHJPAPPO_set_
	public int JBPJAGOJMFA { get; set; } // 0x48 MODEJBAGAPB AGJGJBHCMPC_get_ KPJHEPNNLDN_set_
}
public class ECFLPFIJGGC
{
	public int MJMPANIBFED_pid { get; set; } // 0x8 GGAJJGLDIII LPHIIIAOHBE_get_pid POHHJDNBLOD_set_pid
	public int[] KIONHNAPIOM { get; set; } // 0xC NKBILNEOHPK BPFCMINAGBG_get_ MGCJOKCGKLA_set_
}
public class GPBHHNACMOP
{
	public int PGPGPJNBIOH_uid { get; set; } // 0x8 CAIBNHDMKJD CJEDGLPDJBN_get_uid EKJKPIKJLJJ_set_uid
	public int[] GNKAPBFMIDE { get; set; } // 0xC GCJBHIOODHI IAGIBIGJINB_get_ NFGBFKFKBOP_set_
}
public class OJHOANCOJIK
{
	public int CHOIMHCMAHG { get; set; } // 0x8 ALCEBFJAGJB APOIMEHLPBD_get_ HJFDHIEGGBH_set_
	public int[] IKKKOBGCPGN { get; set; } // 0xC HMKFJELDLHP HDKGHOPLJOP_get_ MCAGPNNLIJH_set_
	public int[] CHIFFONJIAD { get; set; } // 0x10 HLHDPIMMEPG MOKENIJJDAL_get_ AKJPOFAINEK_set_
}
public class JAELFHFCDDH
{
	public int AMCICCBMHJC { get; set; } // 0x8 LLBHIHBEOHD GPEPHKOOOEO_get_ CCFMEJMIFLP_set_
	public int HFIFHDCJFPM { get; set; } // 0xC IEABCLEADGN NGGOBDGMNKD_get_ NEDLOLPFJII_set_
}
public class IBCDCBLBJKE
{
	public FGABLOBFLHC[] MDFBOCBCGGE { get; set; } // 0x8 HPNCLJOBGMP PGEIBFCKNHN_get_ BDLAGBBJIHM_set_
	public ECFLPFIJGGC[] EIDOFLACDGH { get; set; } // 0xC BAHDNECPOIE IMOOMHJJEPF_get_ DNKNKOBFBMP_set_
	public GPBHHNACMOP[] HJPKLNPDDHN { get; set; } // 0x10 BPLAGEOJCMG OOMODFJKJLK_get_ JKIOMFFHMLK_set_
	public OJHOANCOJIK[] MMCDFGKCEPO { get; set; } // 0x14 DAEDGKFFPIJ BPOPLCMHLLL_get_ OJCCGHIJMMC_set_
	public JAELFHFCDDH[] ODKFBJEOCGB { get; set; } // 0x18 FDEEKNONDIP CEPIHAMNKIB_get_ AAPFDNEFHKD_set_
	public static IBCDCBLBJKE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1211238
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OGCAPIHPNLC res_readData_ = OGCAPIHPNLC.GetRootAsOGCAPIHPNLC(buffer);
		IBCDCBLBJKE res_data_ = new IBCDCBLBJKE();

		List<FGABLOBFLHC> MDFBOCBCGGE_list_ = new List<FGABLOBFLHC>();
		for(int MDFBOCBCGGE_idx_ = 0; MDFBOCBCGGE_idx_ < res_readData_.AMNNIENGDHILength; MDFBOCBCGGE_idx_++)
		{
			BPDPIFOLPDM MDFBOCBCGGE_readData_ = res_readData_.GetAMNNIENGDHI(MDFBOCBCGGE_idx_);
			FGABLOBFLHC MDFBOCBCGGE_data_ = new FGABLOBFLHC();

			MDFBOCBCGGE_data_.PPFNGGCBJKC_id = MDFBOCBCGGE_readData_.BBPHAPFBFHK/*_id*/;
			MDFBOCBCGGE_data_.OCAMDLMPBGA_dv = MDFBOCBCGGE_readData_.DDMBKEJNPJK/*_dv*/;
			MDFBOCBCGGE_data_.LKMHPJKIFDN_md = MDFBOCBCGGE_readData_.JLBMBKHBKBG/*_md*/;
			MDFBOCBCGGE_data_.DLAIGBEOGNN_ex = MDFBOCBCGGE_readData_.EHIBOEAILLI/*_ex*/;
			MDFBOCBCGGE_data_.PLALNIIBLOF_en = MDFBOCBCGGE_readData_.CFLMCGOJJJD/*_en*/;
			MDFBOCBCGGE_data_.IJEKNCDIIAE_mver = MDFBOCBCGGE_readData_.OFMGALJGDAO/*_mver*/;
			MDFBOCBCGGE_data_.DBHPPMPNCKF = MDFBOCBCGGE_readData_.OILFLMOBFJM;
			MDFBOCBCGGE_data_.GMOOKMONMMD = MDFBOCBCGGE_readData_.KBGHNCHBLHN;
			MDFBOCBCGGE_data_.DOJAMIPOKBD = MDFBOCBCGGE_readData_.DAEBPADJEOK;
			MDFBOCBCGGE_data_.MDEBEGADHOH = MDFBOCBCGGE_readData_.JMADKJNCBCO;
			MDFBOCBCGGE_data_.JILNNPKFKEK = MDFBOCBCGGE_readData_.DIGHIPFGPAP;
			MDFBOCBCGGE_data_.GOFFPLJKIIB = MDFBOCBCGGE_readData_.GNPNCHPOGNL;
			MDFBOCBCGGE_data_.NFEJAAOAFPG = MDFBOCBCGGE_readData_.CODDJJEBDNG;
			List<int> BFIFIDKOJGD_list_ = new List<int>();
			for(int BFIFIDKOJGD_idx_ = 0; BFIFIDKOJGD_idx_ < MDFBOCBCGGE_readData_.PGEKHEFEBOCLength; BFIFIDKOJGD_idx_++)
			{
				BFIFIDKOJGD_list_.Add(MDFBOCBCGGE_readData_.GetPGEKHEFEBOC(BFIFIDKOJGD_idx_));
			}
			MDFBOCBCGGE_data_.BFIFIDKOJGD = BFIFIDKOJGD_list_.ToArray();

			List<int> AJNPNDIDJLD_list_ = new List<int>();
			for(int AJNPNDIDJLD_idx_ = 0; AJNPNDIDJLD_idx_ < MDFBOCBCGGE_readData_.IIFJDHKAMEDLength; AJNPNDIDJLD_idx_++)
			{
				AJNPNDIDJLD_list_.Add(MDFBOCBCGGE_readData_.GetIIFJDHKAMED(AJNPNDIDJLD_idx_));
			}
			MDFBOCBCGGE_data_.AJNPNDIDJLD = AJNPNDIDJLD_list_.ToArray();

			List<int> GMKDHMPGLFL_list_ = new List<int>();
			for(int GMKDHMPGLFL_idx_ = 0; GMKDHMPGLFL_idx_ < MDFBOCBCGGE_readData_.FCDHEJINFPHLength; GMKDHMPGLFL_idx_++)
			{
				GMKDHMPGLFL_list_.Add(MDFBOCBCGGE_readData_.GetFCDHEJINFPH(GMKDHMPGLFL_idx_));
			}
			MDFBOCBCGGE_data_.GMKDHMPGLFL = GMKDHMPGLFL_list_.ToArray();

			MDFBOCBCGGE_data_.JBPJAGOJMFA = MDFBOCBCGGE_readData_.MFKMAPAOPLN;
			MDFBOCBCGGE_list_.Add(MDFBOCBCGGE_data_);
		}
		res_data_.MDFBOCBCGGE = MDFBOCBCGGE_list_.ToArray();

		List<ECFLPFIJGGC> EIDOFLACDGH_list_ = new List<ECFLPFIJGGC>();
		for(int EIDOFLACDGH_idx_ = 0; EIDOFLACDGH_idx_ < res_readData_.OAHKOBDODPGLength; EIDOFLACDGH_idx_++)
		{
			HJIPOJKELHB EIDOFLACDGH_readData_ = res_readData_.GetOAHKOBDODPG(EIDOFLACDGH_idx_);
			ECFLPFIJGGC EIDOFLACDGH_data_ = new ECFLPFIJGGC();

			EIDOFLACDGH_data_.MJMPANIBFED_pid = EIDOFLACDGH_readData_.COPFAKAHEMN/*_pid*/;
			List<int> KIONHNAPIOM_list_ = new List<int>();
			for(int KIONHNAPIOM_idx_ = 0; KIONHNAPIOM_idx_ < EIDOFLACDGH_readData_.CEPFOAEFOEALength; KIONHNAPIOM_idx_++)
			{
				KIONHNAPIOM_list_.Add(EIDOFLACDGH_readData_.GetCEPFOAEFOEA(KIONHNAPIOM_idx_));
			}
			EIDOFLACDGH_data_.KIONHNAPIOM = KIONHNAPIOM_list_.ToArray();

			EIDOFLACDGH_list_.Add(EIDOFLACDGH_data_);
		}
		res_data_.EIDOFLACDGH = EIDOFLACDGH_list_.ToArray();

		List<GPBHHNACMOP> HJPKLNPDDHN_list_ = new List<GPBHHNACMOP>();
		for(int HJPKLNPDDHN_idx_ = 0; HJPKLNPDDHN_idx_ < res_readData_.PMHBCDENHAILength; HJPKLNPDDHN_idx_++)
		{
			GJNHKIDNFJO HJPKLNPDDHN_readData_ = res_readData_.GetPMHBCDENHAI(HJPKLNPDDHN_idx_);
			GPBHHNACMOP HJPKLNPDDHN_data_ = new GPBHHNACMOP();

			HJPKLNPDDHN_data_.PGPGPJNBIOH_uid = HJPKLNPDDHN_readData_.LLJMKBDBIGN/*_uid*/;
			List<int> GNKAPBFMIDE_list_ = new List<int>();
			for(int GNKAPBFMIDE_idx_ = 0; GNKAPBFMIDE_idx_ < HJPKLNPDDHN_readData_.CLFGGLFAJKHLength; GNKAPBFMIDE_idx_++)
			{
				GNKAPBFMIDE_list_.Add(HJPKLNPDDHN_readData_.GetCLFGGLFAJKH(GNKAPBFMIDE_idx_));
			}
			HJPKLNPDDHN_data_.GNKAPBFMIDE = GNKAPBFMIDE_list_.ToArray();

			HJPKLNPDDHN_list_.Add(HJPKLNPDDHN_data_);
		}
		res_data_.HJPKLNPDDHN = HJPKLNPDDHN_list_.ToArray();

		List<OJHOANCOJIK> MMCDFGKCEPO_list_ = new List<OJHOANCOJIK>();
		for(int MMCDFGKCEPO_idx_ = 0; MMCDFGKCEPO_idx_ < res_readData_.DABMEKCEBEPLength; MMCDFGKCEPO_idx_++)
		{
			POLDFBLCDFN MMCDFGKCEPO_readData_ = res_readData_.GetDABMEKCEBEP(MMCDFGKCEPO_idx_);
			OJHOANCOJIK MMCDFGKCEPO_data_ = new OJHOANCOJIK();

			MMCDFGKCEPO_data_.CHOIMHCMAHG = MMCDFGKCEPO_readData_.DNIDLBOLLGH;
			List<int> IKKKOBGCPGN_list_ = new List<int>();
			for(int IKKKOBGCPGN_idx_ = 0; IKKKOBGCPGN_idx_ < MMCDFGKCEPO_readData_.KMKKKKNNFGBLength; IKKKOBGCPGN_idx_++)
			{
				IKKKOBGCPGN_list_.Add(MMCDFGKCEPO_readData_.GetKMKKKKNNFGB(IKKKOBGCPGN_idx_));
			}
			MMCDFGKCEPO_data_.IKKKOBGCPGN = IKKKOBGCPGN_list_.ToArray();

			List<int> CHIFFONJIAD_list_ = new List<int>();
			for(int CHIFFONJIAD_idx_ = 0; CHIFFONJIAD_idx_ < MMCDFGKCEPO_readData_.NDOLMCLBIBFLength; CHIFFONJIAD_idx_++)
			{
				CHIFFONJIAD_list_.Add(MMCDFGKCEPO_readData_.GetNDOLMCLBIBF(CHIFFONJIAD_idx_));
			}
			MMCDFGKCEPO_data_.CHIFFONJIAD = CHIFFONJIAD_list_.ToArray();

			MMCDFGKCEPO_list_.Add(MMCDFGKCEPO_data_);
		}
		res_data_.MMCDFGKCEPO = MMCDFGKCEPO_list_.ToArray();

		List<JAELFHFCDDH> ODKFBJEOCGB_list_ = new List<JAELFHFCDDH>();
		for(int ODKFBJEOCGB_idx_ = 0; ODKFBJEOCGB_idx_ < res_readData_.EPPNEJBPKMFLength; ODKFBJEOCGB_idx_++)
		{
			JMGNAIJPDBF ODKFBJEOCGB_readData_ = res_readData_.GetEPPNEJBPKMF(ODKFBJEOCGB_idx_);
			JAELFHFCDDH ODKFBJEOCGB_data_ = new JAELFHFCDDH();

			ODKFBJEOCGB_data_.AMCICCBMHJC = ODKFBJEOCGB_readData_.HDAGLLICBAO;
			ODKFBJEOCGB_data_.HFIFHDCJFPM = ODKFBJEOCGB_readData_.AJAPPNMNKJH;
			ODKFBJEOCGB_list_.Add(ODKFBJEOCGB_data_);
		}
		res_data_.ODKFBJEOCGB = ODKFBJEOCGB_list_.ToArray();

		return res_data_;
	}
}
