using FlatBuffers;
using System.Collections.Generic;

public class JGIHJPPECBB
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE_name { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int BEBJKJKBOGH_date { get; set; } // 0x10 MCIJNMKFMDB DIAPHCJBPFD_get_date IHAIKPNEEJE
	public int IJEKNCDIIAE_mver { get; set; } // 0x14 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
public class IDEELDJLDBN
{
	public JGIHJPPECBB[] MLOPDBGPLFI { get; set; } // 0x8 EGHMJKKFFBD LKEHBKLHHMP OCGNMNHBBPE
	public static IDEELDJLDBN HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x11EB4FC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JHCHMCIFCND res_readData = JHCHMCIFCND.GetRootAsJHCHMCIFCND(buffer);
		IDEELDJLDBN res_data = new IDEELDJLDBN();

		List<JGIHJPPECBB> MLOPDBGPLFI_list = new List<JGIHJPPECBB>();
		for(int MLOPDBGPLFI_idx = 0; MLOPDBGPLFI_idx < res_readData.MFLNKKKEGJHLength; MLOPDBGPLFI_idx++)
		{
			GGCGMFLDFMA MLOPDBGPLFI_readData = res_readData.GetMFLNKKKEGJH(MLOPDBGPLFI_idx);
			JGIHJPPECBB MLOPDBGPLFI_data = new JGIHJPPECBB();

			MLOPDBGPLFI_data.PPFNGGCBJKC_id = MLOPDBGPLFI_readData.BBPHAPFBFHK;
			MLOPDBGPLFI_data.OPFGFINHFCE_name = MLOPDBGPLFI_readData.IIDCFMHCPLJ;
			MLOPDBGPLFI_data.BEBJKJKBOGH_date = MLOPDBGPLFI_readData.IBDFJIDNDJH;
			MLOPDBGPLFI_data.IJEKNCDIIAE_mver = MLOPDBGPLFI_readData.OFMGALJGDAO;
			MLOPDBGPLFI_list.Add(MLOPDBGPLFI_data);
		}
		res_data.MLOPDBGPLFI = MLOPDBGPLFI_list.ToArray();

		return res_data;
	}
}
