using FlatBuffers;
using System.Collections.Generic;

public class DPGPEALHJOB
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public string OPFGFINHFCE_name { get; set; } // 0x10 LGIIAPHCLPN DKJOHDGOIJE_get_name MJAMIGECMMF_set_name
	public int OBGBAOLONDD_UniqueId { get; set; } // 0x14 NCOKDCMHMJF OLHPPFCEIIK_get_UniqueId EIHCOIFCELN_set_UniqueId
	public int IJEKNCDIIAE_mver { get; set; } // 0x18 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PDBPFJJCADD_open_at { get; set; } // 0x1C PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public int FDBNFFNFOND_close_at { get; set; } // 0x20 INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
	public int DIJHLDAIBCA { get; set; } // 0x24 GPNFFGDHJPG JDMOCKJPIOH_get_ KFJJFDLPEDE_set_
}
public class MEDIMPGIJHC
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE_get_name MJAMIGECMMF_set_name
	public int OCPIODNOHKL { get; set; } // 0xC BGADONLHPIN ODFBMPBJGHL_get_ NMJMOIKKFLL_set_
	public int EJBGHLOOLBC_HelpIds { get; set; } // 0x10 IPIFFFAPMBI EPDMCNHPMMH_get_HelpIds DNLNMDIBEML_set_HelpIds
	public int KDBLHOFCPIO { get; set; } // 0x14 MJGFCHGEHBB CIAMFNPKIMP_get_ OOAMEEBMEMD_set_
	public int KLHAFHMFFNK { get; set; } // 0x18 GMPFDMEFNMA HNOKLOPAIKE_get_ KLGPCGJIINL_set_
	public int BENBNKNPOAA { get; set; } // 0x1C PCLICMAPPAI HJJHIEOGIAL_get_ NPLCGEJFJLH_set_
}
public class KODOLHPAONC
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE_get_name MJAMIGECMMF_set_name
	public string HJLDBEJOMIO { get; set; } // 0xC BNJJOAGLABF MDILFLMALPN_get_ KKDEJNIJBAB_set_
}
public class CEFDJALCHBL
{
	public int OBGBAOLONDD_UniqueId { get; set; } // 0x8 NCOKDCMHMJF OLHPPFCEIIK_get_UniqueId EIHCOIFCELN_set_UniqueId
	public MEDIMPGIJHC[] EBEMOEPADJB { get; set; } // 0xC HGDDOFPEOOB HOCJMMAIKKG_get_ NGAAMODFBNP_set_
	public KODOLHPAONC[] OJMEIBNMLNP { get; set; } // 0x10 ENJDPPONPGF DMPIELBKMNB_get_ CFLFPNGJLDF_set_
}
public class IGDFIPKLHBA
{
	public DPGPEALHJOB[] FNOIEDBFLPH { get; set; } // 0x8 NGMOGGFBKGF HLKBCCMMLHG_get_ FNNFPHGNFPI_set_
	public CEFDJALCHBL[] NAPKJCKIPEF { get; set; } // 0xC FPEAHHBHNDD JHNNMMEJJMO_get_ DDDBLLONBLL_set_
	public static IGDFIPKLHBA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x11F434C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JAFMFLPLHEB res_readData_ = JAFMFLPLHEB.GetRootAsJAFMFLPLHEB(buffer);
		IGDFIPKLHBA res_data_ = new IGDFIPKLHBA();

		List<DPGPEALHJOB> FNOIEDBFLPH_list_ = new List<DPGPEALHJOB>();
		for(int FNOIEDBFLPH_idx_ = 0; FNOIEDBFLPH_idx_ < res_readData_.NBIPMJGGIMMLength; FNOIEDBFLPH_idx_++)
		{
			BNKFBEGNEHA FNOIEDBFLPH_readData_ = res_readData_.GetNBIPMJGGIMM(FNOIEDBFLPH_idx_);
			DPGPEALHJOB FNOIEDBFLPH_data_ = new DPGPEALHJOB();

			FNOIEDBFLPH_data_.PPFNGGCBJKC_id = FNOIEDBFLPH_readData_.BBPHAPFBFHK/*_id*/;
			FNOIEDBFLPH_data_.PLALNIIBLOF_en = FNOIEDBFLPH_readData_.CFLMCGOJJJD/*_en*/;
			FNOIEDBFLPH_data_.OPFGFINHFCE_name = FNOIEDBFLPH_readData_.IIDCFMHCPLJ/*_name*/;
			FNOIEDBFLPH_data_.OBGBAOLONDD_UniqueId = FNOIEDBFLPH_readData_.MAIJBDCJPNJ/*_UniqueId*/;
			FNOIEDBFLPH_data_.IJEKNCDIIAE_mver = FNOIEDBFLPH_readData_.OFMGALJGDAO/*_mver*/;
			FNOIEDBFLPH_data_.PDBPFJJCADD_open_at = FNOIEDBFLPH_readData_.NJLJEKDBPCH/*_open_at*/;
			FNOIEDBFLPH_data_.FDBNFFNFOND_close_at = FNOIEDBFLPH_readData_.MAOAGDBDBIB/*_close_at*/;
			FNOIEDBFLPH_data_.DIJHLDAIBCA = FNOIEDBFLPH_readData_.JEEDFKICAKL;
			FNOIEDBFLPH_list_.Add(FNOIEDBFLPH_data_);
		}
		res_data_.FNOIEDBFLPH = FNOIEDBFLPH_list_.ToArray();

		List<CEFDJALCHBL> NAPKJCKIPEF_list_ = new List<CEFDJALCHBL>();
		for(int NAPKJCKIPEF_idx_ = 0; NAPKJCKIPEF_idx_ < res_readData_.DGEFKIIOAIPLength; NAPKJCKIPEF_idx_++)
		{
			HHJALCFAKEC NAPKJCKIPEF_readData_ = res_readData_.GetDGEFKIIOAIP(NAPKJCKIPEF_idx_);
			CEFDJALCHBL NAPKJCKIPEF_data_ = new CEFDJALCHBL();

			NAPKJCKIPEF_data_.OBGBAOLONDD_UniqueId = NAPKJCKIPEF_readData_.MAIJBDCJPNJ/*_UniqueId*/;
			List<MEDIMPGIJHC> EBEMOEPADJB_list_ = new List<MEDIMPGIJHC>();
			for(int EBEMOEPADJB_idx_ = 0; EBEMOEPADJB_idx_ < NAPKJCKIPEF_readData_.PIDFEPBIHNELength; EBEMOEPADJB_idx_++)
			{
				OBEFECOGHGM EBEMOEPADJB_readData_ = NAPKJCKIPEF_readData_.GetPIDFEPBIHNE(EBEMOEPADJB_idx_);
				MEDIMPGIJHC EBEMOEPADJB_data_ = new MEDIMPGIJHC();

				EBEMOEPADJB_data_.OPFGFINHFCE_name = EBEMOEPADJB_readData_.IIDCFMHCPLJ/*_name*/;
				EBEMOEPADJB_data_.OCPIODNOHKL = EBEMOEPADJB_readData_.LENIKJONAFB;
				EBEMOEPADJB_data_.EJBGHLOOLBC_HelpIds = EBEMOEPADJB_readData_.FIABJKGEJFF/*_HelpIds*/;
				EBEMOEPADJB_data_.KDBLHOFCPIO = EBEMOEPADJB_readData_.ICOLJHNBDIA;
				EBEMOEPADJB_data_.KLHAFHMFFNK = EBEMOEPADJB_readData_.FFJIHOINOLL;
				EBEMOEPADJB_data_.BENBNKNPOAA = EBEMOEPADJB_readData_.KEPFKJDEGOO;
				EBEMOEPADJB_list_.Add(EBEMOEPADJB_data_);
			}
			NAPKJCKIPEF_data_.EBEMOEPADJB = EBEMOEPADJB_list_.ToArray();

			List<KODOLHPAONC> OJMEIBNMLNP_list_ = new List<KODOLHPAONC>();
			for(int OJMEIBNMLNP_idx_ = 0; OJMEIBNMLNP_idx_ < NAPKJCKIPEF_readData_.FKAGFJHPDBDLength; OJMEIBNMLNP_idx_++)
			{
				KPHKFKGKKNK OJMEIBNMLNP_readData_ = NAPKJCKIPEF_readData_.GetFKAGFJHPDBD(OJMEIBNMLNP_idx_);
				KODOLHPAONC OJMEIBNMLNP_data_ = new KODOLHPAONC();

				OJMEIBNMLNP_data_.OPFGFINHFCE_name = OJMEIBNMLNP_readData_.IIDCFMHCPLJ/*_name*/;
				OJMEIBNMLNP_data_.HJLDBEJOMIO = OJMEIBNMLNP_readData_.JEAFIKCAKGD;
				OJMEIBNMLNP_list_.Add(OJMEIBNMLNP_data_);
			}
			NAPKJCKIPEF_data_.OJMEIBNMLNP = OJMEIBNMLNP_list_.ToArray();

			NAPKJCKIPEF_list_.Add(NAPKJCKIPEF_data_);
		}
		res_data_.NAPKJCKIPEF = NAPKJCKIPEF_list_.ToArray();

		return res_data_;
	}
}
