using FlatBuffers;
using System.Collections.Generic;

public class LFHPPKNLGLJ
{
	public int IKPIDCFOFEA_no { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM_get_no PCJEHLGEJDH_set_no
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public string DNJLJMKKDNA_EventId { get; set; } // 0x10 KCIFEAIAGDG DONEINFNFCP_get_EventId EPEBGHFNMKP_set_EventId
	public string OFJIBKAOMKO { get; set; } // 0x14 ONMKNADCBMA EGNHPGFPKJE_get_ JCKJPIPKOIJ_set_
	public string AMLNJJHJEHE { get; set; } // 0x18 LNJBNNDNLBM EEMDDKKFHIB_get_ DCCGHBEMENJ_set_
	public string DJJAKCKDGMA { get; set; } // 0x1C AIHHCPGODML PPFHHPJFIJF_get_ PNNHLHCJNOI_set_
	public int LCCDKCPBJAK_BannerId { get; set; } // 0x20 PMGIJMMBBCM EJCGPCCMFOC_get_BannerId PIDILOOINOG_set_BannerId
	public int KIGNIOGKEGD { get; set; } // 0x24 DNEMODJAHOJ CEPNGDLACFP_get_ LFNFLHBNHPM_set_
	public int AKCAHAKHIPI { get; set; } // 0x28 CONCNPCHEJP FHOLAGIDMKG_get_ EELAKKAGOJP_set_
	public int LLAGMIDPGFP { get; set; } // 0x2C OCLGEKKBNEK CDDGMDHCKBC_get_ MMOBCDKCLJF_set_
}
public class FBPGKNMGGKF
{
	public int JLIPMPMDEHI { get; set; } // 0x8 FKGFBKDLGGL DMFGFPKLOPA_get_ DDAAAPGELEK_set_
	public int LOPHEKJBJKD { get; set; } // 0xC FOLHMCEMIAF KKMIBCFCNPN_get_ FMKAALCHCPL_set_
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
}
public class ABNJFHAAANG
{
	public int PLALNIIBLOF_en { get; set; } // 0x8 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int KBPENAAJPHN { get; set; } // 0xC IFPBJOECEFE EFEOOCHLDJD_get_ IENBKJHLOPB_set_
	public int AKKDBALDNAN { get; set; } // 0x10 FEPFIABDLOL HBEABGIBBNL_get_ BGLJCGIPIEG_set_
	public int OENPCNBFPDA_bg_id { get; set; } // 0x14 CFHILALNGHJ BNLALNCFJPB_get_bg_id KPJBLJCKBLF_set_bg_id
}
public class JGKIKCIOAJJ
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class NNGGJFPJHOJ
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class IINMAJAFDIF
{
	public LFHPPKNLGLJ[] GHGFEFIAIFC { get; set; } // 0x8 JAEHBIANMBH DKKBFCFGDAH_get_ EHJAEAPHIMD_set_
	public FBPGKNMGGKF[] GCKNBNMLCEF { get; set; } // 0xC BEKANALLJMG GHADEBOONHN_get_ HKMHLPCLEKL_set_
	public ABNJFHAAANG[] DEJCELHJKHN { get; set; } // 0x10 IAFBOMKPMBN OFKNJPOJKAG_get_ LKDHFMAGEJG_set_
	public JGKIKCIOAJJ[] BHGDNGHDDAC { get; set; } // 0x14 JHDNDHBDFFI CEHHJMMMCID_get_ EDOEOHENKDG_set_
	public NNGGJFPJHOJ[] MHGMDJNOLMI { get; set; } // 0x18 JBFEKPIDNIC NFFJJGMEEOB_get_ BGEFBFOAMPK_set_
	public static IINMAJAFDIF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x8D95E0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JJKEIOGAGKI res_readData_ = JJKEIOGAGKI.GetRootAsJJKEIOGAGKI(buffer);
		IINMAJAFDIF res_data_ = new IINMAJAFDIF();

		List<LFHPPKNLGLJ> GHGFEFIAIFC_list_ = new List<LFHPPKNLGLJ>();
		for(int GHGFEFIAIFC_idx_ = 0; GHGFEFIAIFC_idx_ < res_readData_.BBJIABHHCNNLength; GHGFEFIAIFC_idx_++)
		{
			AGFBIPOFDKC GHGFEFIAIFC_readData_ = res_readData_.GetBBJIABHHCNN(GHGFEFIAIFC_idx_);
			LFHPPKNLGLJ GHGFEFIAIFC_data_ = new LFHPPKNLGLJ();

			GHGFEFIAIFC_data_.IKPIDCFOFEA_no = GHGFEFIAIFC_readData_.CILHGCNPEFO/*_no*/;
			GHGFEFIAIFC_data_.PLALNIIBLOF_en = GHGFEFIAIFC_readData_.CFLMCGOJJJD/*_en*/;
			GHGFEFIAIFC_data_.DNJLJMKKDNA_EventId = GHGFEFIAIFC_readData_.IDHMHHMGAHM/*_EventId*/;
			GHGFEFIAIFC_data_.OFJIBKAOMKO = GHGFEFIAIFC_readData_.EKKCGKJJOFN;
			GHGFEFIAIFC_data_.AMLNJJHJEHE = GHGFEFIAIFC_readData_.OLFHCANIOKL;
			GHGFEFIAIFC_data_.DJJAKCKDGMA = GHGFEFIAIFC_readData_.ENOJILKGDPM;
			GHGFEFIAIFC_data_.LCCDKCPBJAK_BannerId = GHGFEFIAIFC_readData_.EOKIODCFLMP/*_BannerId*/;
			GHGFEFIAIFC_data_.KIGNIOGKEGD = GHGFEFIAIFC_readData_.CMHHLIAFHEB;
			GHGFEFIAIFC_data_.AKCAHAKHIPI = GHGFEFIAIFC_readData_.ADJFMDNEKEB;
			GHGFEFIAIFC_data_.LLAGMIDPGFP = GHGFEFIAIFC_readData_.HDJFOAJOFKC;
			GHGFEFIAIFC_list_.Add(GHGFEFIAIFC_data_);
		}
		res_data_.GHGFEFIAIFC = GHGFEFIAIFC_list_.ToArray();

		List<FBPGKNMGGKF> GCKNBNMLCEF_list_ = new List<FBPGKNMGGKF>();
		for(int GCKNBNMLCEF_idx_ = 0; GCKNBNMLCEF_idx_ < res_readData_.GMFHOALFGJCLength; GCKNBNMLCEF_idx_++)
		{
			PMEKDNKBNBI GCKNBNMLCEF_readData_ = res_readData_.GetGMFHOALFGJC(GCKNBNMLCEF_idx_);
			FBPGKNMGGKF GCKNBNMLCEF_data_ = new FBPGKNMGGKF();

			GCKNBNMLCEF_data_.JLIPMPMDEHI = GCKNBNMLCEF_readData_.APMIOOKCLFI;
			GCKNBNMLCEF_data_.LOPHEKJBJKD = GCKNBNMLCEF_readData_.EINIBCEFPPL;
			GCKNBNMLCEF_data_.PLALNIIBLOF_en = GCKNBNMLCEF_readData_.CFLMCGOJJJD/*_en*/;
			GCKNBNMLCEF_list_.Add(GCKNBNMLCEF_data_);
		}
		res_data_.GCKNBNMLCEF = GCKNBNMLCEF_list_.ToArray();

		List<ABNJFHAAANG> DEJCELHJKHN_list_ = new List<ABNJFHAAANG>();
		for(int DEJCELHJKHN_idx_ = 0; DEJCELHJKHN_idx_ < res_readData_.FLKKDMDCNDNLength; DEJCELHJKHN_idx_++)
		{
			FGEACEDNLAC DEJCELHJKHN_readData_ = res_readData_.GetFLKKDMDCNDN(DEJCELHJKHN_idx_);
			ABNJFHAAANG DEJCELHJKHN_data_ = new ABNJFHAAANG();

			DEJCELHJKHN_data_.PLALNIIBLOF_en = DEJCELHJKHN_readData_.CFLMCGOJJJD/*_en*/;
			DEJCELHJKHN_data_.KBPENAAJPHN = DEJCELHJKHN_readData_.CPICBLIGEPH;
			DEJCELHJKHN_data_.AKKDBALDNAN = DEJCELHJKHN_readData_.BKEMOEAJMHK;
			DEJCELHJKHN_data_.OENPCNBFPDA_bg_id = DEJCELHJKHN_readData_.MOMCBJDJDIA/*_bg_id*/;
			DEJCELHJKHN_list_.Add(DEJCELHJKHN_data_);
		}
		res_data_.DEJCELHJKHN = DEJCELHJKHN_list_.ToArray();

		List<JGKIKCIOAJJ> BHGDNGHDDAC_list_ = new List<JGKIKCIOAJJ>();
		for(int BHGDNGHDDAC_idx_ = 0; BHGDNGHDDAC_idx_ < res_readData_.NJJINHMIOHNLength; BHGDNGHDDAC_idx_++)
		{
			BOOHINDELKH BHGDNGHDDAC_readData_ = res_readData_.GetNJJINHMIOHN(BHGDNGHDDAC_idx_);
			JGKIKCIOAJJ BHGDNGHDDAC_data_ = new JGKIKCIOAJJ();

			BHGDNGHDDAC_data_.LJNAKDMILMC_key = BHGDNGHDDAC_readData_.AGOIMGHMGOH/*_key*/;
			BHGDNGHDDAC_data_.JBGEEPFKIGG_val = BHGDNGHDDAC_readData_.KJFEBMBHKOC/*_val*/;
			BHGDNGHDDAC_list_.Add(BHGDNGHDDAC_data_);
		}
		res_data_.BHGDNGHDDAC = BHGDNGHDDAC_list_.ToArray();

		List<NNGGJFPJHOJ> MHGMDJNOLMI_list_ = new List<NNGGJFPJHOJ>();
		for(int MHGMDJNOLMI_idx_ = 0; MHGMDJNOLMI_idx_ < res_readData_.NPFBHGKLIOMLength; MHGMDJNOLMI_idx_++)
		{
			EAJOKHIMIMD MHGMDJNOLMI_readData_ = res_readData_.GetNPFBHGKLIOM(MHGMDJNOLMI_idx_);
			NNGGJFPJHOJ MHGMDJNOLMI_data_ = new NNGGJFPJHOJ();

			MHGMDJNOLMI_data_.LJNAKDMILMC_key = MHGMDJNOLMI_readData_.AGOIMGHMGOH/*_key*/;
			MHGMDJNOLMI_data_.JBGEEPFKIGG_val = MHGMDJNOLMI_readData_.KJFEBMBHKOC/*_val*/;
			MHGMDJNOLMI_list_.Add(MHGMDJNOLMI_data_);
		}
		res_data_.MHGMDJNOLMI = MHGMDJNOLMI_list_.ToArray();

		return res_data_;
	}
}
