using FlatBuffers;
using System.Collections.Generic;

public class LFHPPKNLGLJ
{
	public int IKPIDCFOFEA { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM PCJEHLGEJDH
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string DNJLJMKKDNA { get; set; } // 0x10 KCIFEAIAGDG DONEINFNFCP EPEBGHFNMKP
	public string OFJIBKAOMKO { get; set; } // 0x14 ONMKNADCBMA EGNHPGFPKJE JCKJPIPKOIJ
	public string AMLNJJHJEHE { get; set; } // 0x18 LNJBNNDNLBM EEMDDKKFHIB DCCGHBEMENJ
	public string DJJAKCKDGMA { get; set; } // 0x1C AIHHCPGODML PPFHHPJFIJF PNNHLHCJNOI
	public int LCCDKCPBJAK { get; set; } // 0x20 PMGIJMMBBCM EJCGPCCMFOC PIDILOOINOG
	public int KIGNIOGKEGD { get; set; } // 0x24 DNEMODJAHOJ CEPNGDLACFP LFNFLHBNHPM
	public int AKCAHAKHIPI { get; set; } // 0x28 CONCNPCHEJP FHOLAGIDMKG EELAKKAGOJP
	public int LLAGMIDPGFP { get; set; } // 0x2C OCLGEKKBNEK CDDGMDHCKBC MMOBCDKCLJF
}
public class FBPGKNMGGKF
{
	public int JLIPMPMDEHI { get; set; } // 0x8 FKGFBKDLGGL DMFGFPKLOPA DDAAAPGELEK
	public int LOPHEKJBJKD { get; set; } // 0xC FOLHMCEMIAF KKMIBCFCNPN FMKAALCHCPL
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
}
public class ABNJFHAAANG
{
	public int PLALNIIBLOF { get; set; } // 0x8 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int KBPENAAJPHN { get; set; } // 0xC IFPBJOECEFE EFEOOCHLDJD IENBKJHLOPB
	public int AKKDBALDNAN { get; set; } // 0x10 FEPFIABDLOL HBEABGIBBNL BGLJCGIPIEG
	public int OENPCNBFPDA { get; set; } // 0x14 CFHILALNGHJ BNLALNCFJPB KPJBLJCKBLF
}
public class JGKIKCIOAJJ
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NNGGJFPJHOJ
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class IINMAJAFDIF
{
	public LFHPPKNLGLJ[] GHGFEFIAIFC { get; set; } // 0x8 JAEHBIANMBH DKKBFCFGDAH EHJAEAPHIMD
	public FBPGKNMGGKF[] GCKNBNMLCEF { get; set; } // 0xC BEKANALLJMG GHADEBOONHN HKMHLPCLEKL
	public ABNJFHAAANG[] DEJCELHJKHN { get; set; } // 0x10 IAFBOMKPMBN OFKNJPOJKAG LKDHFMAGEJG
	public JGKIKCIOAJJ[] BHGDNGHDDAC { get; set; } // 0x14 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public NNGGJFPJHOJ[] MHGMDJNOLMI { get; set; } // 0x18 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static IINMAJAFDIF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x8D95E0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JJKEIOGAGKI res_readData = JJKEIOGAGKI.GetRootAsJJKEIOGAGKI(buffer);
		IINMAJAFDIF res_data = new IINMAJAFDIF();

		List<LFHPPKNLGLJ> GHGFEFIAIFC_list = new List<LFHPPKNLGLJ>();
		for(int GHGFEFIAIFC_idx = 0; GHGFEFIAIFC_idx < res_readData.BBJIABHHCNNLength; GHGFEFIAIFC_idx++)
		{
			AGFBIPOFDKC GHGFEFIAIFC_readData = res_readData.GetBBJIABHHCNN(GHGFEFIAIFC_idx);
			LFHPPKNLGLJ GHGFEFIAIFC_data = new LFHPPKNLGLJ();

			GHGFEFIAIFC_data.IKPIDCFOFEA = GHGFEFIAIFC_readData.CILHGCNPEFO;
			GHGFEFIAIFC_data.PLALNIIBLOF = GHGFEFIAIFC_readData.CFLMCGOJJJD;
			GHGFEFIAIFC_data.DNJLJMKKDNA = GHGFEFIAIFC_readData.IDHMHHMGAHM;
			GHGFEFIAIFC_data.OFJIBKAOMKO = GHGFEFIAIFC_readData.EKKCGKJJOFN;
			GHGFEFIAIFC_data.AMLNJJHJEHE = GHGFEFIAIFC_readData.OLFHCANIOKL;
			GHGFEFIAIFC_data.DJJAKCKDGMA = GHGFEFIAIFC_readData.ENOJILKGDPM;
			GHGFEFIAIFC_data.LCCDKCPBJAK = GHGFEFIAIFC_readData.EOKIODCFLMP;
			GHGFEFIAIFC_data.KIGNIOGKEGD = GHGFEFIAIFC_readData.CMHHLIAFHEB;
			GHGFEFIAIFC_data.AKCAHAKHIPI = GHGFEFIAIFC_readData.ADJFMDNEKEB;
			GHGFEFIAIFC_data.LLAGMIDPGFP = GHGFEFIAIFC_readData.HDJFOAJOFKC;
			GHGFEFIAIFC_list.Add(GHGFEFIAIFC_data);
		}
		res_data.GHGFEFIAIFC = GHGFEFIAIFC_list.ToArray();

		List<FBPGKNMGGKF> GCKNBNMLCEF_list = new List<FBPGKNMGGKF>();
		for(int GCKNBNMLCEF_idx = 0; GCKNBNMLCEF_idx < res_readData.GMFHOALFGJCLength; GCKNBNMLCEF_idx++)
		{
			PMEKDNKBNBI GCKNBNMLCEF_readData = res_readData.GetGMFHOALFGJC(GCKNBNMLCEF_idx);
			FBPGKNMGGKF GCKNBNMLCEF_data = new FBPGKNMGGKF();

			GCKNBNMLCEF_data.JLIPMPMDEHI = GCKNBNMLCEF_readData.APMIOOKCLFI;
			GCKNBNMLCEF_data.LOPHEKJBJKD = GCKNBNMLCEF_readData.EINIBCEFPPL;
			GCKNBNMLCEF_data.PLALNIIBLOF = GCKNBNMLCEF_readData.CFLMCGOJJJD;
			GCKNBNMLCEF_list.Add(GCKNBNMLCEF_data);
		}
		res_data.GCKNBNMLCEF = GCKNBNMLCEF_list.ToArray();

		List<ABNJFHAAANG> DEJCELHJKHN_list = new List<ABNJFHAAANG>();
		for(int DEJCELHJKHN_idx = 0; DEJCELHJKHN_idx < res_readData.FLKKDMDCNDNLength; DEJCELHJKHN_idx++)
		{
			FGEACEDNLAC DEJCELHJKHN_readData = res_readData.GetFLKKDMDCNDN(DEJCELHJKHN_idx);
			ABNJFHAAANG DEJCELHJKHN_data = new ABNJFHAAANG();

			DEJCELHJKHN_data.PLALNIIBLOF = DEJCELHJKHN_readData.CFLMCGOJJJD;
			DEJCELHJKHN_data.KBPENAAJPHN = DEJCELHJKHN_readData.CPICBLIGEPH;
			DEJCELHJKHN_data.AKKDBALDNAN = DEJCELHJKHN_readData.BKEMOEAJMHK;
			DEJCELHJKHN_data.OENPCNBFPDA = DEJCELHJKHN_readData.MOMCBJDJDIA;
			DEJCELHJKHN_list.Add(DEJCELHJKHN_data);
		}
		res_data.DEJCELHJKHN = DEJCELHJKHN_list.ToArray();

		List<JGKIKCIOAJJ> BHGDNGHDDAC_list = new List<JGKIKCIOAJJ>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			BOOHINDELKH BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			JGKIKCIOAJJ BHGDNGHDDAC_data = new JGKIKCIOAJJ();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<NNGGJFPJHOJ> MHGMDJNOLMI_list = new List<NNGGJFPJHOJ>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			EAJOKHIMIMD MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			NNGGJFPJHOJ MHGMDJNOLMI_data = new NNGGJFPJHOJ();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
