using FlatBuffers;
using System.Collections.Generic;

public class HNJNEMJIBKI
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint HANMDEBPBHG { get; set; } // 0xC IMDBPCNAOOE EFGGIMOPNMG PNGGKPFDKMA
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint FBFLDFMFFOH { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
}
public class IMLKIIBJABA
{
	public HNJNEMJIBKI[] BDDHMELPABN { get; set; } // 0x8 JJCJJPALGGI OCFACIBPFKK MNPFODINBCO
	public static IMLKIIBJABA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x9FB3A4
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		MLCJDNPCFHI res_readData = MLCJDNPCFHI.GetRootAsMLCJDNPCFHI(buffer);
		IMLKIIBJABA res_data = new IMLKIIBJABA();

		List<HNJNEMJIBKI> BDDHMELPABN_list = new List<HNJNEMJIBKI>();
		for(int BDDHMELPABN_idx = 0; BDDHMELPABN_idx < res_readData.NHJGDCCCDBJLength; BDDHMELPABN_idx++)
		{
			LHFKAKHPGBF BDDHMELPABN_readData = res_readData.GetNHJGDCCCDBJ(BDDHMELPABN_idx);
			HNJNEMJIBKI BDDHMELPABN_data = new HNJNEMJIBKI();

			BDDHMELPABN_data.PPFNGGCBJKC = BDDHMELPABN_readData.BBPHAPFBFHK;
			BDDHMELPABN_data.HANMDEBPBHG = BDDHMELPABN_readData.BLJLFEDLAME;
			BDDHMELPABN_data.PLALNIIBLOF = BDDHMELPABN_readData.CFLMCGOJJJD;
			BDDHMELPABN_data.FPOMEEJFBIG = BDDHMELPABN_readData.AEAKMMJLLDK;
			BDDHMELPABN_data.FBFLDFMFFOH = BDDHMELPABN_readData.ODBPKGJPLMD;
			BDDHMELPABN_list.Add(BDDHMELPABN_data);
		}
		res_data.BDDHMELPABN = BDDHMELPABN_list.ToArray();

		return res_data;
	}
}
