using FlatBuffers;
using System.Collections.Generic;

public class LFPCDGMAMJM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FBFLDFMFFOH_rar { get; set; } // 0xC LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint JPFMJHLCMJL_sa { get; set; } // 0x10 PIJIPMOBEIJ LLFFAPHPGFJ PMGNHNIKHLE
	public uint AOLLIMFKDAA_ma { get; set; } // 0x14 NFMGELLCAMN JOGECEHFINO PMCBBDHCEEN
	public uint FELIFAHDLON_ep { get; set; } // 0x18 KMOMMBIBCFB BIOMAAABABJ JAFMFIHLKIN
	public uint BCCOMAODPJI_hp { get; set; } // 0x1C ADINNEKFLLL KBJDPCLDJEB FPIIOJGBDEJ
	public uint LJELGFAFGAB_so { get; set; } // 0x20 CJCOPPAFPKE APHFJDOOLCK KBEAJHMCGPM
	public uint KNEDJFLCCLN_vo { get; set; } // 0x24 HJMKHFAHBIO DKJNGOIGJGH EOMMBJGKKJI
	public uint MBAMIOJNGBD_ch { get; set; } // 0x28 PJHOHPBOIDJ NJBKAFBFJML IGAFGHBHMIF
	public uint PIPCIMIALOO_sp { get; set; } // 0x2C INBCDPNEACE KJNBPECGBJJ DMAJEBCFHHK
	public uint AKOJJJLPCKA_c_s { get; set; } // 0x30 HAHLJMLFIKD NIKDJFBDBOO IDCBHPEIAFE
	public uint GBIIBCHECJC { get; set; } // 0x34 ELGGODKEDGD BDIKCFCEJAE GJPFMJCBIKM
	public uint ELBJIFCDJGO_a_s { get; set; } // 0x38 KAFBDDDADJI BEKOADLCBOB GDKMEJHCOGK
	public uint GPPCEKHBMCO { get; set; } // 0x3C EEEOKBBCEPK CIJCFDMOLNO PCMEJAMOLGG
	public uint LNKKMBCDPHH_l_s { get; set; } // 0x40 GPEMGLLCJIF PAPMCJONAGI MODJBBMBLCD
	public uint FPNNEEHLIJM { get; set; } // 0x44 GKEPMKJBKIB EOMGHPAMIHF GIBMKGLKOPB
	public uint PLALNIIBLOF_en { get; set; } // 0x48 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint OCAMDLMPBGA_dv { get; set; } // 0x4C JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
	public uint LHAFADCJBME_bd { get; set; } // 0x50 NCJHMADKINK CNJKJBOMBNG PNMMMKJCGOK
	public uint KOHNLDKIKPC_sb { get; set; } // 0x54 EAMJMDBMNKI KLCNELOBOGM ILNHCICNFHF
	public uint MOPBJIOCKML_hp1 { get; set; } // 0x58 EBKKGPFJALD HDGDPADNLOH EJHJBEJNCOP
	public uint KKPADIFPHOK_vo1 { get; set; } // 0x5C EECOAANIBDM JNJNCOOAOIA GBJBGJLDBPL
	public uint NDDDBPKPMDK_so1 { get; set; } // 0x60 OKPFFFHLKHL NJIJBEEFODO NKNDKPLDABD
	public uint JCAPANAALDF_ch1 { get; set; } // 0x64 OIGOJFEEAGN BAPJNJHNLHG KGEMNBACAED
	public uint FMGKFCHAOCF_sp1 { get; set; } // 0x68 KOHBCHJCKMA HNPAJPBFJIO LMKPMBJJOAE
	public uint ADLGKMBIPCA_fd { get; set; } // 0x6C KJBJJPDMEMK ECHDOIILAHP BNPHIHICNCJ
	public uint ILKEDIDGNLP_fd1 { get; set; } // 0x70 BGALOFCIHMB OELEOOFGFPN NCMNMEKHELE
	public uint AIFGNKMBFCD_note { get; set; } // 0x74 LHCBNKHLPNL FDHECHMMPPM HEEDDHLGOEF
	public uint PFJJFCPPNIN_nx { get; set; } // 0x78 JDMOEHEIMKJ DPIIPBMNHOI LAKMHLJFOAL
	public uint BCIDCCGECBG_nx1 { get; set; } // 0x7C HAJNNPEHKFO MMBLPNDIOFJ PJMDKDMBBON
	public uint JLHAHAMAIBG { get; set; } // 0x80 LEGHGNBEGEP PCKFMJBKFFC OHEPCHFLOOE
	public int IJEKNCDIIAE_mver { get; set; } // 0x84 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int FGJKNLLDHJI { get; set; } // 0x88 LFNBJDOJDFO DEOBFAMHBBJ INJJLHDGGMJ
	public uint OKEFHPHNFNK { get; set; } // 0x8C CJMLCACFNBL EOOOIMLEFAK FGANDDDEFLL
	public uint KALPJIJCHFO { get; set; } // 0x90 OJFCABLKAID BJDMIKLNJHN KDMNMHKPHND
	public int NPJOJEHFBKG { get; set; } // 0x94 KKECLFKOGOK OFPJOCMIBLC PPEFFHJHOFJ
	public uint DPHMNJNCHJG { get; set; } // 0x98 PCHMGEKBPAH JIAFMPMJACL NGJIPNJFGCL
	public uint FIKLIDJBPBB_va { get; set; } // 0x9C OJKLCHAGPPC KJJCFEGIHEL FDOLAKFLJJE
	public uint JIJOGLFOOMN_Aver { get; set; } // 0xA0 MCJCIKOEOHH AEOFOBJHHHN FDHKHDIKPKE
}
public class JNNFCGGHCAF
{
	public LFPCDGMAMJM[] OMODKDAOCJL { get; set; } // 0x8 LKOIJLCNCEF PEMNINDOHOD FAMPEBEJNJI
	public static JNNFCGGHCAF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1BA1D28
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		IGLOKFOAKDB res_readData = IGLOKFOAKDB.GetRootAsIGLOKFOAKDB(buffer);
		JNNFCGGHCAF res_data = new JNNFCGGHCAF();

		List<LFPCDGMAMJM> OMODKDAOCJL_list = new List<LFPCDGMAMJM>();
		for(int OMODKDAOCJL_idx = 0; OMODKDAOCJL_idx < res_readData.JEHCMIMHAKDLength; OMODKDAOCJL_idx++)
		{
			GLMHPNJHOIK OMODKDAOCJL_readData = res_readData.GetJEHCMIMHAKD(OMODKDAOCJL_idx);
			LFPCDGMAMJM OMODKDAOCJL_data = new LFPCDGMAMJM();

			OMODKDAOCJL_data.PPFNGGCBJKC_id = OMODKDAOCJL_readData.BBPHAPFBFHK;
			OMODKDAOCJL_data.FBFLDFMFFOH_rar = OMODKDAOCJL_readData.ODBPKGJPLMD;
			OMODKDAOCJL_data.JPFMJHLCMJL_sa = OMODKDAOCJL_readData.GJEJFAJHBME;
			OMODKDAOCJL_data.AOLLIMFKDAA_ma = OMODKDAOCJL_readData.OPEDKFOOFMO;
			OMODKDAOCJL_data.FELIFAHDLON_ep = OMODKDAOCJL_readData.DGPJIDBAOLO;
			OMODKDAOCJL_data.BCCOMAODPJI_hp = OMODKDAOCJL_readData.MHFDKEEEDEL;
			OMODKDAOCJL_data.LJELGFAFGAB_so = OMODKDAOCJL_readData.FHLKEIBOFNN;
			OMODKDAOCJL_data.KNEDJFLCCLN_vo = OMODKDAOCJL_readData.EGEFMJCLNDM;
			OMODKDAOCJL_data.MBAMIOJNGBD_ch = OMODKDAOCJL_readData.KDPKPOBKKMJ;
			OMODKDAOCJL_data.PIPCIMIALOO_sp = OMODKDAOCJL_readData.GKLHNNBMGKH;
			OMODKDAOCJL_data.AKOJJJLPCKA_c_s = OMODKDAOCJL_readData.NAGPKLGDNDA;
			OMODKDAOCJL_data.GBIIBCHECJC = OMODKDAOCJL_readData.DMOFFJMMAFH;
			OMODKDAOCJL_data.ELBJIFCDJGO_a_s = OMODKDAOCJL_readData.LDLOHEJKEKH;
			OMODKDAOCJL_data.GPPCEKHBMCO = OMODKDAOCJL_readData.BEDPEDGJEBE;
			OMODKDAOCJL_data.LNKKMBCDPHH_l_s = OMODKDAOCJL_readData.BNDEBMLCMNB;
			OMODKDAOCJL_data.FPNNEEHLIJM = OMODKDAOCJL_readData.IHACPFEKKHJ;
			OMODKDAOCJL_data.PLALNIIBLOF_en = OMODKDAOCJL_readData.CFLMCGOJJJD;
			OMODKDAOCJL_data.OCAMDLMPBGA_dv = OMODKDAOCJL_readData.DDMBKEJNPJK;
			OMODKDAOCJL_data.LHAFADCJBME_bd = OMODKDAOCJL_readData.BJNPAEKAFND;
			OMODKDAOCJL_data.KOHNLDKIKPC_sb = OMODKDAOCJL_readData.ONBMIJLCFBD;
			OMODKDAOCJL_data.MOPBJIOCKML_hp1 = OMODKDAOCJL_readData.BIKHPIFLIPL;
			OMODKDAOCJL_data.KKPADIFPHOK_vo1 = OMODKDAOCJL_readData.BIHCGDIPDHM;
			OMODKDAOCJL_data.NDDDBPKPMDK_so1 = OMODKDAOCJL_readData.DPLDPCPHPGK;
			OMODKDAOCJL_data.JCAPANAALDF_ch1 = OMODKDAOCJL_readData.PEFIAHNGPDI;
			OMODKDAOCJL_data.FMGKFCHAOCF_sp1 = OMODKDAOCJL_readData.PJLBCLAAJEA;
			OMODKDAOCJL_data.ADLGKMBIPCA_fd = OMODKDAOCJL_readData.IJMEOOJHNCG;
			OMODKDAOCJL_data.ILKEDIDGNLP_fd1 = OMODKDAOCJL_readData.NBECKADKFAL;
			OMODKDAOCJL_data.AIFGNKMBFCD_note = OMODKDAOCJL_readData.LDFCDBOALOL;
			OMODKDAOCJL_data.PFJJFCPPNIN_nx = OMODKDAOCJL_readData.KKJFKKJHCAI;
			OMODKDAOCJL_data.BCIDCCGECBG_nx1 = OMODKDAOCJL_readData.HIIOMBJHLJO;
			OMODKDAOCJL_data.JLHAHAMAIBG = OMODKDAOCJL_readData.MDECMDGBNEE;
			OMODKDAOCJL_data.IJEKNCDIIAE_mver = OMODKDAOCJL_readData.OFMGALJGDAO;
			OMODKDAOCJL_data.FGJKNLLDHJI = OMODKDAOCJL_readData.JMNNJABAGLE;
			OMODKDAOCJL_data.OKEFHPHNFNK = OMODKDAOCJL_readData.IPOAPJMECLN;
			OMODKDAOCJL_data.KALPJIJCHFO = OMODKDAOCJL_readData.NACDNMJHPOI;
			OMODKDAOCJL_data.NPJOJEHFBKG = OMODKDAOCJL_readData.KOLACJIMMPA;
			OMODKDAOCJL_data.DPHMNJNCHJG = OMODKDAOCJL_readData.KPIGACCFPFE;
			OMODKDAOCJL_data.FIKLIDJBPBB_va = OMODKDAOCJL_readData.DACNLPDCJGB;
			OMODKDAOCJL_data.JIJOGLFOOMN_Aver = OMODKDAOCJL_readData.NLAHBMFCPMP;
			OMODKDAOCJL_list.Add(OMODKDAOCJL_data);
		}
		res_data.OMODKDAOCJL = OMODKDAOCJL_list.ToArray();

		return res_data;
	}
}
