using FlatBuffers;
using System.Collections.Generic;

public class GDKBIMGFAEE
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint JBFLEDKDFCO { get; set; } // 0x18 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint ALAEHBKAEPB { get; set; } // 0x1C NILNPADBBHI NHILKCBAGHE ONHBPCBCFAE
	public uint FBFLDFMFFOH { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int NGILPOOLBCF { get; set; } // 0x24 JHEFBAFILNF EDGHLAHGBFN LFCKFNLGFCN
	public int JINEKNIBOFI { get; set; } // 0x28 KPHFGIFBIJA LKDHAPEGCPH PBPDONPMGNF
}
public class JABLGCMDAIK
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint LDLGLHBGOKE { get; set; } // 0x18 DPCAJGDKHGG EONNCAKAEFE BJAADDLLCHE
	public uint CPKMLLNADLJ { get; set; } // 0x1C COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint JBFLEDKDFCO { get; set; } // 0x20 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint DMEDKJPOLCH { get; set; } // 0x24 JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint FBFLDFMFFOH { get; set; } // 0x28 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int MLMCEBBDJOE { get; set; } // 0x2C LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x30 LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK { get; set; } // 0x34 JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
}
public class LNPGKJNNIFN
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class PJHPLPHEBJH
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class JONOKOHFAJO
{
	public GDKBIMGFAEE[] AKMICHNIBCI { get; set; } // 0x8 GODDHLICPCM KAFGANANOFF AGCAHNPHMPP
	public JABLGCMDAIK[] CKALDHBDFBN { get; set; } // 0xC ANAGMICLCNJ PBICKLABPAH LIJDJEFMBAL
	public LNPGKJNNIFN[] BHGDNGHDDAC { get; set; } // 0x10 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public PJHPLPHEBJH[] MHGMDJNOLMI { get; set; } // 0x14 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static JONOKOHFAJO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1BA42F8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		GLBBAECGHNN res_readData = GLBBAECGHNN.GetRootAsGLBBAECGHNN(buffer);
		JONOKOHFAJO res_data = new JONOKOHFAJO();

		List<GDKBIMGFAEE> AKMICHNIBCI_list = new List<GDKBIMGFAEE>();
		for(int AKMICHNIBCI_idx = 0; AKMICHNIBCI_idx < res_readData.EKEPMNOOFEFLength; AKMICHNIBCI_idx++)
		{
			IJHCOCLJICA AKMICHNIBCI_readData = res_readData.GetEKEPMNOOFEF(AKMICHNIBCI_idx);
			GDKBIMGFAEE AKMICHNIBCI_data = new GDKBIMGFAEE();

			AKMICHNIBCI_data.PPFNGGCBJKC = AKMICHNIBCI_readData.BBPHAPFBFHK;
			AKMICHNIBCI_data.IJEKNCDIIAE = AKMICHNIBCI_readData.OFMGALJGDAO;
			AKMICHNIBCI_data.PLALNIIBLOF = AKMICHNIBCI_readData.CFLMCGOJJJD;
			AKMICHNIBCI_data.GBJFNGCDKPM = AKMICHNIBCI_readData.LPJPOOHJKAE;
			AKMICHNIBCI_data.JBFLEDKDFCO = AKMICHNIBCI_readData.HOENDPOGFIO;
			AKMICHNIBCI_data.ALAEHBKAEPB = AKMICHNIBCI_readData.IINNLHJJLHD;
			AKMICHNIBCI_data.FBFLDFMFFOH = AKMICHNIBCI_readData.ODBPKGJPLMD;
			AKMICHNIBCI_data.NGILPOOLBCF = AKMICHNIBCI_readData.PJEDCALAIFP;
			AKMICHNIBCI_data.JINEKNIBOFI = AKMICHNIBCI_readData.KCEANJAMDBD;
			AKMICHNIBCI_list.Add(AKMICHNIBCI_data);
		}
		res_data.AKMICHNIBCI = AKMICHNIBCI_list.ToArray();

		List<JABLGCMDAIK> CKALDHBDFBN_list = new List<JABLGCMDAIK>();
		for(int CKALDHBDFBN_idx = 0; CKALDHBDFBN_idx < res_readData.DIOINIDFAMFLength; CKALDHBDFBN_idx++)
		{
			ABHNDHFIFLB CKALDHBDFBN_readData = res_readData.GetDIOINIDFAMF(CKALDHBDFBN_idx);
			JABLGCMDAIK CKALDHBDFBN_data = new JABLGCMDAIK();

			CKALDHBDFBN_data.PPFNGGCBJKC = CKALDHBDFBN_readData.BBPHAPFBFHK;
			CKALDHBDFBN_data.IJEKNCDIIAE = CKALDHBDFBN_readData.OFMGALJGDAO;
			CKALDHBDFBN_data.PLALNIIBLOF = CKALDHBDFBN_readData.CFLMCGOJJJD;
			CKALDHBDFBN_data.GBJFNGCDKPM = CKALDHBDFBN_readData.LPJPOOHJKAE;
			CKALDHBDFBN_data.LDLGLHBGOKE = CKALDHBDFBN_readData.OELANBBBMLK;
			CKALDHBDFBN_data.CPKMLLNADLJ = CKALDHBDFBN_readData.LMLNKHMPOIG;
			CKALDHBDFBN_data.JBFLEDKDFCO = CKALDHBDFBN_readData.HOENDPOGFIO;
			CKALDHBDFBN_data.DMEDKJPOLCH = CKALDHBDFBN_readData.ADCLAGBHDBC;
			CKALDHBDFBN_data.FBFLDFMFFOH = CKALDHBDFBN_readData.ODBPKGJPLMD;
			CKALDHBDFBN_data.MLMCEBBDJOE = CKALDHBDFBN_readData.JHAMBKOEJPL;
			CKALDHBDFBN_data.ODNILEDOAIP = CKALDHBDFBN_readData.MJHPFNPCLBD;
			CKALDHBDFBN_data.NPPGKNGIFGK = CKALDHBDFBN_readData.JDKBBEIBJBD;
			CKALDHBDFBN_list.Add(CKALDHBDFBN_data);
		}
		res_data.CKALDHBDFBN = CKALDHBDFBN_list.ToArray();

		List<LNPGKJNNIFN> BHGDNGHDDAC_list = new List<LNPGKJNNIFN>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			MJMHMHKFDNC BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			LNPGKJNNIFN BHGDNGHDDAC_data = new LNPGKJNNIFN();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<PJHPLPHEBJH> MHGMDJNOLMI_list = new List<PJHPLPHEBJH>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			OIJDGALEEAI MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			PJHPLPHEBJH MHGMDJNOLMI_data = new PJHPLPHEBJH();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
