using FlatBuffers;
using System.Collections.Generic;

public class DBFNFOEABBH
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0xC NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public uint HFNIHKOAMGC { get; set; } // 0x10 FHBGLLIFKHM ECGBAIBHGFP CGCGLFDKHPC
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO_SaveIdx { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x20 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x24 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint FCNKIKOOFKE { get; set; } // 0x28 HCCCABIHAGH HMIIBKHBKHE ALMBKAMFMDG
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x2C HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x30 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x34 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JMJDLDEIFKE { get; set; } // 0x38 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO_DayGroup { get; set; } // 0x3C IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x40 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public int MJBKGOJBPAD_item_type { get; set; } // 0x44 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public string FEMMDNIELFC_Desc { get; set; } // 0x48 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint HKKNEAGCIEB_RankingSupport { get; set; } // 0x4C DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public string OMCAOJJGOGG_Lb { get; set; } // 0x50 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM_StartAdventureId { get; set; } // 0x54 AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP_EndAdventureId { get; set; } // 0x58 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC_HelpIds { get; set; } // 0x5C IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int GMFNMNOIJHI { get; set; } // 0x60 JEMBIJCDGGI NLAJBPEIOPL AHFDBCPFLEJ
	public uint OHGDNJLFDFF_Start { get; set; } // 0x64 HNLGNDHJIED NHBPNMFMHOC NAIJIAGADLK
	public uint PHKLJGNMFBL_End { get; set; } // 0x68 EPNCDMLKDAD HIAAMENBKEA NKBJDKIHPPB
}
public class LICOJMAJDAF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint HLOBFDBFINJ_Link { get; set; } // 0x14 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint IHGDLBBPKFI_Next { get; set; } // 0x18 GDDAGPGNGHK ONOBDELIEFB MKNICENPJBP
	public string OPFGFINHFCE_name { get; set; } // 0x1C LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int GLCLFMGPMAN_ItemId { get; set; } // 0x20 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int NDNHKMJPBCM_Cost { get; set; } // 0x24 LPKMMHJOGLJ KGIMAEOIMBF LDEDKBEPHMI
	public uint PDBPFJJCADD_open_at { get; set; } // 0x28 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x2C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class FLMCFOFFDMM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint IMMDGJAOPCD_BoxId { get; set; } // 0x10 FKLCPJHMALL KADOBOBABJG BLLCKEDEKHH
	public int AEDMJLGNDHN_IsSp { get; set; } // 0x14 BEGHLJIFPJM GFPFIMDNOBK LKEHADMGMJF
	public int GLCLFMGPMAN_ItemId { get; set; } // 0x18 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int JBGEEPFKIGG_val { get; set; } // 0x1C AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint ADPPAIPFHML_num { get; set; } // 0x20 LONDDHLNFBL LJMLHOOPGEM PHNIOCPOBGO
}
public class AMMILNMBOPC
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint FPOMEEJFBIG_odr { get; set; } // 0x10 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public int GPJKJCBPBIP_Tim { get; set; } // 0x14 APKLCDDNJGD FIPDCOBPMEG DLKCEHBDNNJ
	public int OAFPGJLCNFM_cond { get; set; } // 0x18 NOAAJIPPHMP PMJFANGPJIE HEECOBEHHPJ
	public int GBJFNGCDKPM_typ { get; set; } // 0x1C GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint NKNAECHNACI_GroupId { get; set; } // 0x20 BPKPIMAPLAM HHFHLCKGNPK IPPHAJBFGEP
}
public class AIAIHJGIAOI
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class DKPFILODEHL
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class KBFIJHDHOGA
{
	public DBFNFOEABBH HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public LICOJMAJDAF[] GCMONMILNMH { get; set; } // 0xC AAMKEIBCNPP DKBAGPAHNGH BFFLFLKJGLL
	public FLMCFOFFDMM[] BNHMOENHDFB { get; set; } // 0x10 HGKKBJMAPNN NLKLLFOGFOM IPFIPKDJJIM
	public AMMILNMBOPC[] EBJIGPIKKNB { get; set; } // 0x14 OAMJELCFPFC HMFDNPFMCON PMNEPDJILFM
	public AIAIHJGIAOI[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public DKPFILODEHL[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static KBFIJHDHOGA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x101AF7C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LDCIDAKFJPH res_readData = LDCIDAKFJPH.GetRootAsLDCIDAKFJPH(buffer);
		KBFIJHDHOGA res_data = new KBFIJHDHOGA();

		GDOALKDMNGG HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		DBFNFOEABBH HMBHNLCFDIH_data = new DBFNFOEABBH();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.HFNIHKOAMGC = HMBHNLCFDIH_readData.HEMLBADKAOA;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO_SaveIdx = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.FCNKIKOOFKE = HMBHNLCFDIH_readData.KPJEPCJKIJJ;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO_DayGroup = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.MJBKGOJBPAD_item_type = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.FEMMDNIELFC_Desc = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKKNEAGCIEB_RankingSupport = HMBHNLCFDIH_readData.LENBJLOPKLE;
		HMBHNLCFDIH_data.OMCAOJJGOGG_Lb = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM_StartAdventureId = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP_EndAdventureId = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC_HelpIds = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.GMFNMNOIJHI = HMBHNLCFDIH_readData.MHPCFPIINFL;
		HMBHNLCFDIH_data.OHGDNJLFDFF_Start = HMBHNLCFDIH_readData.JFNKDHPAEGD;
		HMBHNLCFDIH_data.PHKLJGNMFBL_End = HMBHNLCFDIH_readData.KIPKMBIKLDO;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<LICOJMAJDAF> GCMONMILNMH_list = new List<LICOJMAJDAF>();
		for(int GCMONMILNMH_idx = 0; GCMONMILNMH_idx < res_readData.PDIOIJHGJHGLength; GCMONMILNMH_idx++)
		{
			PHJEGIBPDAG GCMONMILNMH_readData = res_readData.GetPDIOIJHGJHG(GCMONMILNMH_idx);
			LICOJMAJDAF GCMONMILNMH_data = new LICOJMAJDAF();

			GCMONMILNMH_data.PPFNGGCBJKC_id = GCMONMILNMH_readData.BBPHAPFBFHK;
			GCMONMILNMH_data.IJEKNCDIIAE_mver = GCMONMILNMH_readData.OFMGALJGDAO;
			GCMONMILNMH_data.PLALNIIBLOF_en = GCMONMILNMH_readData.CFLMCGOJJJD;
			GCMONMILNMH_data.HLOBFDBFINJ_Link = GCMONMILNMH_readData.OADMJNEOKLC;
			GCMONMILNMH_data.IHGDLBBPKFI_Next = GCMONMILNMH_readData.GDLJMMPFINH;
			GCMONMILNMH_data.OPFGFINHFCE_name = GCMONMILNMH_readData.IIDCFMHCPLJ;
			GCMONMILNMH_data.GLCLFMGPMAN_ItemId = GCMONMILNMH_readData.MBBJMJAAODG;
			GCMONMILNMH_data.NDNHKMJPBCM_Cost = GCMONMILNMH_readData.BCJCBHDMCDP;
			GCMONMILNMH_data.PDBPFJJCADD_open_at = GCMONMILNMH_readData.NJLJEKDBPCH;
			GCMONMILNMH_data.FDBNFFNFOND_close_at = GCMONMILNMH_readData.MAOAGDBDBIB;
			GCMONMILNMH_list.Add(GCMONMILNMH_data);
		}
		res_data.GCMONMILNMH = GCMONMILNMH_list.ToArray();

		List<FLMCFOFFDMM> BNHMOENHDFB_list = new List<FLMCFOFFDMM>();
		for(int BNHMOENHDFB_idx = 0; BNHMOENHDFB_idx < res_readData.HHBHEKNMBHFLength; BNHMOENHDFB_idx++)
		{
			OPEBPLACKMA BNHMOENHDFB_readData = res_readData.GetHHBHEKNMBHF(BNHMOENHDFB_idx);
			FLMCFOFFDMM BNHMOENHDFB_data = new FLMCFOFFDMM();

			BNHMOENHDFB_data.PPFNGGCBJKC_id = BNHMOENHDFB_readData.BBPHAPFBFHK;
			BNHMOENHDFB_data.PLALNIIBLOF_en = BNHMOENHDFB_readData.CFLMCGOJJJD;
			BNHMOENHDFB_data.IMMDGJAOPCD_BoxId = BNHMOENHDFB_readData.PJPIKBPCCMD;
			BNHMOENHDFB_data.AEDMJLGNDHN_IsSp = BNHMOENHDFB_readData.HKGPNPMBJCP;
			BNHMOENHDFB_data.GLCLFMGPMAN_ItemId = BNHMOENHDFB_readData.MBBJMJAAODG;
			BNHMOENHDFB_data.JBGEEPFKIGG_val = BNHMOENHDFB_readData.KJFEBMBHKOC;
			BNHMOENHDFB_data.ADPPAIPFHML_num = BNHMOENHDFB_readData.LFFMNLEJJMH;
			BNHMOENHDFB_list.Add(BNHMOENHDFB_data);
		}
		res_data.BNHMOENHDFB = BNHMOENHDFB_list.ToArray();

		List<AMMILNMBOPC> EBJIGPIKKNB_list = new List<AMMILNMBOPC>();
		for(int EBJIGPIKKNB_idx = 0; EBJIGPIKKNB_idx < res_readData.ABLEGKPGGIELength; EBJIGPIKKNB_idx++)
		{
			KLOLAGHEOOM EBJIGPIKKNB_readData = res_readData.GetABLEGKPGGIE(EBJIGPIKKNB_idx);
			AMMILNMBOPC EBJIGPIKKNB_data = new AMMILNMBOPC();

			EBJIGPIKKNB_data.PPFNGGCBJKC_id = EBJIGPIKKNB_readData.BBPHAPFBFHK;
			EBJIGPIKKNB_data.PLALNIIBLOF_en = EBJIGPIKKNB_readData.CFLMCGOJJJD;
			EBJIGPIKKNB_data.FPOMEEJFBIG_odr = EBJIGPIKKNB_readData.AEAKMMJLLDK;
			EBJIGPIKKNB_data.GPJKJCBPBIP_Tim = EBJIGPIKKNB_readData.EGPGKNLIBCG;
			EBJIGPIKKNB_data.OAFPGJLCNFM_cond = EBJIGPIKKNB_readData.KAOJJKIALDA;
			EBJIGPIKKNB_data.GBJFNGCDKPM_typ = EBJIGPIKKNB_readData.LPJPOOHJKAE;
			EBJIGPIKKNB_data.NKNAECHNACI_GroupId = EBJIGPIKKNB_readData.AJBJHLGIHIP;
			EBJIGPIKKNB_list.Add(EBJIGPIKKNB_data);
		}
		res_data.EBJIGPIKKNB = EBJIGPIKKNB_list.ToArray();

		List<AIAIHJGIAOI> BHGDNGHDDAC_list = new List<AIAIHJGIAOI>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			DJCKPLICDIP BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			AIAIHJGIAOI BHGDNGHDDAC_data = new AIAIHJGIAOI();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<DKPFILODEHL> MHGMDJNOLMI_list = new List<DKPFILODEHL>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			IFMBFGKPIBG MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			DKPFILODEHL MHGMDJNOLMI_data = new DKPFILODEHL();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
