using FlatBuffers;
using System.Collections.Generic;

public class ALNDGBMAILD
{
	public int PNDNJDMIKAN { get; set; } // 0x8 PECAMELOBCB PMOHAHMFELP_get_ CIMIIFHBEGB_set_
	public int ELHALBFPLJK { get; set; } // 0xC CHHGKBMJGDB MJCLNHJCMPL_get_ GFIEFLHIOPI_set_
}
public class DGILHAMKBKK
{
	public int AADJGKGCMCP { get; set; } // 0x8 CMDMAEGLNAO NDOOCOLGFEF_get_ FGAIBKOLMLO_set_
	public int FDAPNFDOHEJ { get; set; } // 0xC FJCBLAIPOLH CDEKDJJDAGP_get_ IEOHBLJGKCF_set_
	public int EDFJKODHCAN { get; set; } // 0x10 OHDOLICNMNM HAOKBLMBKND_get_ EEEPKLDGMAH_set_
}
public class IMMJLLOOKCF
{
	public int PNDNJDMIKAN { get; set; } // 0x8 PECAMELOBCB PMOHAHMFELP_get_ CIMIIFHBEGB_set_
	public int[] CBDOEDKIOJK_ev { get; set; } // 0xC CENBLPHOLKK COMDLMJJFFN_get_ev MJNJNAHIJCO_set_ev
}
public class CPNJPEHHNOO
{
	public int GNFJOONKCFH { get; set; } // 0x8 JGLANLMLCNL LOFPOONPOMC_get_ KEGADDBFANM_set_
	public int[] CBDOEDKIOJK_ev { get; set; } // 0xC CENBLPHOLKK COMDLMJJFFN_get_ev MJNJNAHIJCO_set_ev
}
public class AMEBNIIIHNG
{
	public int GNFJOONKCFH { get; set; } // 0x8 JGLANLMLCNL LOFPOONPOMC_get_ KEGADDBFANM_set_
	public int GLCLFMGPMAN_ItemId { get; set; } // 0xC KCELNMGLKHH LNJAENEGDEL_get_ItemId JHIDBGCHOKL_set_ItemId
	public int ADPPAIPFHML_num { get; set; } // 0x10 LONDDHLNFBL LJMLHOOPGEM_get_num PHNIOCPOBGO_set_num
	public int ACGLMKEBMDL_uc { get; set; } // 0x14 EPENFLDKGJE ALOLFIJOOHG_get_uc JDPCOMJIMHG_set_uc
	public int FBFLDFMFFOH_rar { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
}
public class GGKLHGBDPDD
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class KMPKAHGGCHK
{
	public ALNDGBMAILD[] PJFGGPOEBAH { get; set; } // 0x8 LKDEHKKHCOC FNIFPLHBGCH_get_ BINBHHADDAA_set_
	public DGILHAMKBKK[] KIEKMCKCMGD { get; set; } // 0xC AHOFIJDMDAO EEMBMMJIHPE_get_ CDHPBECJGGO_set_
	public IMMJLLOOKCF[] GOKCDMKKCMD { get; set; } // 0x10 MLELALGNENI EEFEAKJIAJD_get_ MJKJKEDHCGG_set_
	public CPNJPEHHNOO[] PFGDBAIFLGL { get; set; } // 0x14 PLIJMECLDCI CFPBPHBLKID_get_ JKJNNOFLDLF_set_
	public AMEBNIIIHNG[] PPMOLKLDNLB { get; set; } // 0x18 LOCEEBBABGD BLNAFPDHDLI_get_ HHAFJOBIANI_set_
	public GGKLHGBDPDD[] BHGDNGHDDAC { get; set; } // 0x1C JHDNDHBDFFI CEHHJMMMCID_get_ EDOEOHENKDG_set_
	public static KMPKAHGGCHK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1120554
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		GPDPAKFCMMO res_readData_ = GPDPAKFCMMO.GetRootAsGPDPAKFCMMO(buffer);
		KMPKAHGGCHK res_data_ = new KMPKAHGGCHK();

		List<ALNDGBMAILD> PJFGGPOEBAH_list_ = new List<ALNDGBMAILD>();
		for(int PJFGGPOEBAH_idx_ = 0; PJFGGPOEBAH_idx_ < res_readData_.FBFKOOCONJDLength; PJFGGPOEBAH_idx_++)
		{
			HHHCEGPGJII PJFGGPOEBAH_readData_ = res_readData_.GetFBFKOOCONJD(PJFGGPOEBAH_idx_);
			ALNDGBMAILD PJFGGPOEBAH_data_ = new ALNDGBMAILD();

			PJFGGPOEBAH_data_.PNDNJDMIKAN = PJFGGPOEBAH_readData_.NMOFFGFGFKA;
			PJFGGPOEBAH_data_.ELHALBFPLJK = PJFGGPOEBAH_readData_.NOEFOIOOICD;
			PJFGGPOEBAH_list_.Add(PJFGGPOEBAH_data_);
		}
		res_data_.PJFGGPOEBAH = PJFGGPOEBAH_list_.ToArray();

		List<DGILHAMKBKK> KIEKMCKCMGD_list_ = new List<DGILHAMKBKK>();
		for(int KIEKMCKCMGD_idx_ = 0; KIEKMCKCMGD_idx_ < res_readData_.FBAHAFKCMMHLength; KIEKMCKCMGD_idx_++)
		{
			DBDMELPOPMH KIEKMCKCMGD_readData_ = res_readData_.GetFBAHAFKCMMH(KIEKMCKCMGD_idx_);
			DGILHAMKBKK KIEKMCKCMGD_data_ = new DGILHAMKBKK();

			KIEKMCKCMGD_data_.AADJGKGCMCP = KIEKMCKCMGD_readData_.AINFENANAKL;
			KIEKMCKCMGD_data_.FDAPNFDOHEJ = KIEKMCKCMGD_readData_.IHODOLMEGIL;
			KIEKMCKCMGD_data_.EDFJKODHCAN = KIEKMCKCMGD_readData_.MDGINMBLOHO;
			KIEKMCKCMGD_list_.Add(KIEKMCKCMGD_data_);
		}
		res_data_.KIEKMCKCMGD = KIEKMCKCMGD_list_.ToArray();

		List<IMMJLLOOKCF> GOKCDMKKCMD_list_ = new List<IMMJLLOOKCF>();
		for(int GOKCDMKKCMD_idx_ = 0; GOKCDMKKCMD_idx_ < res_readData_.LDCIJBPBLPPLength; GOKCDMKKCMD_idx_++)
		{
			KBKAEPDDIME GOKCDMKKCMD_readData_ = res_readData_.GetLDCIJBPBLPP(GOKCDMKKCMD_idx_);
			IMMJLLOOKCF GOKCDMKKCMD_data_ = new IMMJLLOOKCF();

			GOKCDMKKCMD_data_.PNDNJDMIKAN = GOKCDMKKCMD_readData_.NMOFFGFGFKA;
			List<int> CBDOEDKIOJK_list_ = new List<int>();
			for(int CBDOEDKIOJK_idx_ = 0; CBDOEDKIOJK_idx_ < GOKCDMKKCMD_readData_.BMICKLAGCCDLength; CBDOEDKIOJK_idx_++)
			{
				CBDOEDKIOJK_list_.Add(GOKCDMKKCMD_readData_.GetBMICKLAGCCD(CBDOEDKIOJK_idx_));
			}
			GOKCDMKKCMD_data_.CBDOEDKIOJK_ev = CBDOEDKIOJK_list_.ToArray();

			GOKCDMKKCMD_list_.Add(GOKCDMKKCMD_data_);
		}
		res_data_.GOKCDMKKCMD = GOKCDMKKCMD_list_.ToArray();

		List<CPNJPEHHNOO> PFGDBAIFLGL_list_ = new List<CPNJPEHHNOO>();
		for(int PFGDBAIFLGL_idx_ = 0; PFGDBAIFLGL_idx_ < res_readData_.FHDMFCBDPHALength; PFGDBAIFLGL_idx_++)
		{
			KPCLMCOLBNC PFGDBAIFLGL_readData_ = res_readData_.GetFHDMFCBDPHA(PFGDBAIFLGL_idx_);
			CPNJPEHHNOO PFGDBAIFLGL_data_ = new CPNJPEHHNOO();

			PFGDBAIFLGL_data_.GNFJOONKCFH = PFGDBAIFLGL_readData_.PAAOHNKLBAC;
			List<int> CBDOEDKIOJK_list_ = new List<int>();
			for(int CBDOEDKIOJK_idx_ = 0; CBDOEDKIOJK_idx_ < PFGDBAIFLGL_readData_.BMICKLAGCCDLength; CBDOEDKIOJK_idx_++)
			{
				CBDOEDKIOJK_list_.Add(PFGDBAIFLGL_readData_.GetBMICKLAGCCD(CBDOEDKIOJK_idx_));
			}
			PFGDBAIFLGL_data_.CBDOEDKIOJK_ev = CBDOEDKIOJK_list_.ToArray();

			PFGDBAIFLGL_list_.Add(PFGDBAIFLGL_data_);
		}
		res_data_.PFGDBAIFLGL = PFGDBAIFLGL_list_.ToArray();

		List<AMEBNIIIHNG> PPMOLKLDNLB_list_ = new List<AMEBNIIIHNG>();
		for(int PPMOLKLDNLB_idx_ = 0; PPMOLKLDNLB_idx_ < res_readData_.LCCFMDJBNABLength; PPMOLKLDNLB_idx_++)
		{
			INOFLJPLFAN PPMOLKLDNLB_readData_ = res_readData_.GetLCCFMDJBNAB(PPMOLKLDNLB_idx_);
			AMEBNIIIHNG PPMOLKLDNLB_data_ = new AMEBNIIIHNG();

			PPMOLKLDNLB_data_.GNFJOONKCFH = PPMOLKLDNLB_readData_.PAAOHNKLBAC;
			PPMOLKLDNLB_data_.GLCLFMGPMAN_ItemId = PPMOLKLDNLB_readData_.MBBJMJAAODG/*_ItemId*/;
			PPMOLKLDNLB_data_.ADPPAIPFHML_num = PPMOLKLDNLB_readData_.LFFMNLEJJMH/*_num*/;
			PPMOLKLDNLB_data_.ACGLMKEBMDL_uc = PPMOLKLDNLB_readData_.PAEGHLMNPNO/*_uc*/;
			PPMOLKLDNLB_data_.FBFLDFMFFOH_rar = PPMOLKLDNLB_readData_.ODBPKGJPLMD/*_rar*/;
			PPMOLKLDNLB_list_.Add(PPMOLKLDNLB_data_);
		}
		res_data_.PPMOLKLDNLB = PPMOLKLDNLB_list_.ToArray();

		List<GGKLHGBDPDD> BHGDNGHDDAC_list_ = new List<GGKLHGBDPDD>();
		for(int BHGDNGHDDAC_idx_ = 0; BHGDNGHDDAC_idx_ < res_readData_.NJJINHMIOHNLength; BHGDNGHDDAC_idx_++)
		{
			OAIMGJACOFK BHGDNGHDDAC_readData_ = res_readData_.GetNJJINHMIOHN(BHGDNGHDDAC_idx_);
			GGKLHGBDPDD BHGDNGHDDAC_data_ = new GGKLHGBDPDD();

			BHGDNGHDDAC_data_.LJNAKDMILMC_key = BHGDNGHDDAC_readData_.AGOIMGHMGOH/*_key*/;
			BHGDNGHDDAC_data_.JBGEEPFKIGG_val = BHGDNGHDDAC_readData_.KJFEBMBHKOC/*_val*/;
			BHGDNGHDDAC_list_.Add(BHGDNGHDDAC_data_);
		}
		res_data_.BHGDNGHDDAC = BHGDNGHDDAC_list_.ToArray();

		return res_data_;
	}
}
