using FlatBuffers;
using System.Collections.Generic;

public class GMHAHLAIOKB
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint DMEDKJPOLCH { get; set; } // 0xC JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint DOOGFEGEKLG { get; set; } // 0x14 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public uint PLALNIIBLOF { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE { get; set; } // 0x1C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint FBFLDFMFFOH { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint FPOMEEJFBIG { get; set; } // 0x24 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint EMIJNAFJFJO { get; set; } // 0x28 GBHMMAHHJGG GBGPKONOFGD KCFHLAFJJPJ
	public uint KHCBANFDKBO { get; set; } // 0x2C HIGLBJDKMKJ MKDAJEEHBJC ELDLDDCADHA
}
public class KNJFLGCKEIF
{
	public GMHAHLAIOKB[] FNKIIFGDCDM { get; set; } // 0x8 LODMOGMIKOP HDMLBDMIIMD HCAANAAHKNJ
	public static KNJFLGCKEIF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1122BC8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		BHNBHGFFDII res_readData = BHNBHGFFDII.GetRootAsBHNBHGFFDII(buffer);
		KNJFLGCKEIF res_data = new KNJFLGCKEIF();

		List<GMHAHLAIOKB> FNKIIFGDCDM_list = new List<GMHAHLAIOKB>();
		for(int FNKIIFGDCDM_idx = 0; FNKIIFGDCDM_idx < res_readData.CGPJCLDIGDDLength; FNKIIFGDCDM_idx++)
		{
			FLFCIMHEKJE FNKIIFGDCDM_readData = res_readData.GetCGPJCLDIGDD(FNKIIFGDCDM_idx);
			GMHAHLAIOKB FNKIIFGDCDM_data = new GMHAHLAIOKB();

			FNKIIFGDCDM_data.PPFNGGCBJKC = FNKIIFGDCDM_readData.BBPHAPFBFHK;
			FNKIIFGDCDM_data.DMEDKJPOLCH = FNKIIFGDCDM_readData.ADCLAGBHDBC;
			FNKIIFGDCDM_data.JBGEEPFKIGG = FNKIIFGDCDM_readData.KJFEBMBHKOC;
			FNKIIFGDCDM_data.DOOGFEGEKLG = FNKIIFGDCDM_readData.GEJGMBBCFEE;
			FNKIIFGDCDM_data.PLALNIIBLOF = FNKIIFGDCDM_readData.CFLMCGOJJJD;
			FNKIIFGDCDM_data.IJEKNCDIIAE = FNKIIFGDCDM_readData.OFMGALJGDAO;
			FNKIIFGDCDM_data.FBFLDFMFFOH = FNKIIFGDCDM_readData.ODBPKGJPLMD;
			FNKIIFGDCDM_data.FPOMEEJFBIG = FNKIIFGDCDM_readData.AEAKMMJLLDK;
			FNKIIFGDCDM_data.EMIJNAFJFJO = FNKIIFGDCDM_readData.HHGNAFHNHEK;
			FNKIIFGDCDM_data.KHCBANFDKBO = FNKIIFGDCDM_readData.LFLGAOPCDLC;
			FNKIIFGDCDM_list.Add(FNKIIFGDCDM_data);
		}
		res_data.FNKIIFGDCDM = FNKIIFGDCDM_list.ToArray();

		return res_data;
	}
}
