using FlatBuffers;
using System.Collections.Generic;

public class GMHAHLAIOKB
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint DMEDKJPOLCH_cat { get; set; } // 0xC JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint JBGEEPFKIGG_val { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint DOOGFEGEKLG_max { get; set; } // 0x14 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public uint PLALNIIBLOF_en { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x1C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint FBFLDFMFFOH_rar { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint FPOMEEJFBIG_odr { get; set; } // 0x24 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint EMIJNAFJFJO_expir { get; set; } // 0x28 GBHMMAHHJGG GBGPKONOFGD KCFHLAFJJPJ
	public uint KHCBANFDKBO_Duration { get; set; } // 0x2C HIGLBJDKMKJ MKDAJEEHBJC ELDLDDCADHA
}
public class KNJFLGCKEIF
{
	public GMHAHLAIOKB[] FNKIIFGDCDM { get; set; } // 0x8 LODMOGMIKOP HDMLBDMIIMD HCAANAAHKNJ
	public static KNJFLGCKEIF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1122BC8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		BHNBHGFFDII res_readData = BHNBHGFFDII.GetRootAsBHNBHGFFDII(buffer);
		KNJFLGCKEIF res_data = new KNJFLGCKEIF();

		List<GMHAHLAIOKB> FNKIIFGDCDM_list = new List<GMHAHLAIOKB>();
		for(int FNKIIFGDCDM_idx = 0; FNKIIFGDCDM_idx < res_readData.CGPJCLDIGDDLength; FNKIIFGDCDM_idx++)
		{
			FLFCIMHEKJE FNKIIFGDCDM_readData = res_readData.GetCGPJCLDIGDD(FNKIIFGDCDM_idx);
			GMHAHLAIOKB FNKIIFGDCDM_data = new GMHAHLAIOKB();

			FNKIIFGDCDM_data.PPFNGGCBJKC_id = FNKIIFGDCDM_readData.BBPHAPFBFHK;
			FNKIIFGDCDM_data.DMEDKJPOLCH_cat = FNKIIFGDCDM_readData.ADCLAGBHDBC;
			FNKIIFGDCDM_data.JBGEEPFKIGG_val = FNKIIFGDCDM_readData.KJFEBMBHKOC;
			FNKIIFGDCDM_data.DOOGFEGEKLG_max = FNKIIFGDCDM_readData.GEJGMBBCFEE;
			FNKIIFGDCDM_data.PLALNIIBLOF_en = FNKIIFGDCDM_readData.CFLMCGOJJJD;
			FNKIIFGDCDM_data.IJEKNCDIIAE_mver = FNKIIFGDCDM_readData.OFMGALJGDAO;
			FNKIIFGDCDM_data.FBFLDFMFFOH_rar = FNKIIFGDCDM_readData.ODBPKGJPLMD;
			FNKIIFGDCDM_data.FPOMEEJFBIG_odr = FNKIIFGDCDM_readData.AEAKMMJLLDK;
			FNKIIFGDCDM_data.EMIJNAFJFJO_expir = FNKIIFGDCDM_readData.HHGNAFHNHEK;
			FNKIIFGDCDM_data.KHCBANFDKBO_Duration = FNKIIFGDCDM_readData.LFLGAOPCDLC;
			FNKIIFGDCDM_list.Add(FNKIIFGDCDM_data);
		}
		res_data.FNKIIFGDCDM = FNKIIFGDCDM_list.ToArray();

		return res_data;
	}
}
