using FlatBuffers;
using System.Collections.Generic;

public class BEHPCLGJNDE
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint GBJFNGCDKPM { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int OENPCNBFPDA { get; set; } // 0x10 CFHILALNGHJ BNLALNCFJPB KPJBLJCKBLF
	public int KFNDHKFLPPK { get; set; } // 0x14 IKDKPOLAAHF CCPAPHPPGOB ICBGFBNICOE
	public uint PDBPFJJCADD { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public uint PLALNIIBLOF { get; set; } // 0x20 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE { get; set; } // 0x24 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int LEJOJFHKHIJ { get; set; } // 0x28 FHBFPFOLLHA PGCOGCIHNGG PJDCNPKFOBE
	public string OPFGFINHFCE { get; set; } // 0x2C LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int JPFMJHLCMJL { get; set; } // 0x30 PIJIPMOBEIJ LLFFAPHPGFJ PMGNHNIKHLE
}
public class LEGLJNFOBGN
{
	public BEHPCLGJNDE[] AFNCMAJBLGO { get; set; } // 0x8 MCEMGKGEEEK JJCLCHLCEDN ENMBCFNMPBO
	public static LEGLJNFOBGN HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xD67EB0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		CHFNKBBHDGM res_readData = CHFNKBBHDGM.GetRootAsCHFNKBBHDGM(buffer);
		LEGLJNFOBGN res_data = new LEGLJNFOBGN();

		List<BEHPCLGJNDE> AFNCMAJBLGO_list = new List<BEHPCLGJNDE>();
		for(int AFNCMAJBLGO_idx = 0; AFNCMAJBLGO_idx < res_readData.EMGBLHGBJNDLength; AFNCMAJBLGO_idx++)
		{
			CJBICDDNGHH AFNCMAJBLGO_readData = res_readData.GetEMGBLHGBJND(AFNCMAJBLGO_idx);
			BEHPCLGJNDE AFNCMAJBLGO_data = new BEHPCLGJNDE();

			AFNCMAJBLGO_data.PPFNGGCBJKC = AFNCMAJBLGO_readData.BBPHAPFBFHK;
			AFNCMAJBLGO_data.GBJFNGCDKPM = AFNCMAJBLGO_readData.LPJPOOHJKAE;
			AFNCMAJBLGO_data.OENPCNBFPDA = AFNCMAJBLGO_readData.MOMCBJDJDIA;
			AFNCMAJBLGO_data.KFNDHKFLPPK = AFNCMAJBLGO_readData.IMCIIPLKCNO;
			AFNCMAJBLGO_data.PDBPFJJCADD = AFNCMAJBLGO_readData.NJLJEKDBPCH;
			AFNCMAJBLGO_data.FDBNFFNFOND = AFNCMAJBLGO_readData.MAOAGDBDBIB;
			AFNCMAJBLGO_data.PLALNIIBLOF = AFNCMAJBLGO_readData.CFLMCGOJJJD;
			AFNCMAJBLGO_data.IJEKNCDIIAE = AFNCMAJBLGO_readData.OFMGALJGDAO;
			AFNCMAJBLGO_data.LEJOJFHKHIJ = AFNCMAJBLGO_readData.EJPEFOELHFD;
			AFNCMAJBLGO_data.OPFGFINHFCE = AFNCMAJBLGO_readData.IIDCFMHCPLJ;
			AFNCMAJBLGO_data.JPFMJHLCMJL = AFNCMAJBLGO_readData.GJEJFAJHBME;
			AFNCMAJBLGO_list.Add(AFNCMAJBLGO_data);
		}
		res_data.AFNCMAJBLGO = AFNCMAJBLGO_list.ToArray();

		return res_data;
	}
}
