using FlatBuffers;
using System.Collections.Generic;

public class MKMPJMOODKL
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x14 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint FBFLDFMFFOH_rar { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
}
public class LGCNKCBKJBA
{
	public MKMPJMOODKL[] AAAKAPGGNGL { get; set; } // 0x8 HKFGLJEMJLN FBHLKPJCEIK BLHFBBOCHHL
	public static LGCNKCBKJBA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xD7076C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JPNGMOOGNIA res_readData = JPNGMOOGNIA.GetRootAsJPNGMOOGNIA(buffer);
		LGCNKCBKJBA res_data = new LGCNKCBKJBA();

		List<MKMPJMOODKL> AAAKAPGGNGL_list = new List<MKMPJMOODKL>();
		for(int AAAKAPGGNGL_idx = 0; AAAKAPGGNGL_idx < res_readData.GHBONFLCMKCLength; AAAKAPGGNGL_idx++)
		{
			JBAKGMLAGMJ AAAKAPGGNGL_readData = res_readData.GetGHBONFLCMKC(AAAKAPGGNGL_idx);
			MKMPJMOODKL AAAKAPGGNGL_data = new MKMPJMOODKL();

			AAAKAPGGNGL_data.PPFNGGCBJKC_id = AAAKAPGGNGL_readData.BBPHAPFBFHK;
			AAAKAPGGNGL_data.JBGEEPFKIGG_val = AAAKAPGGNGL_readData.KJFEBMBHKOC;
			AAAKAPGGNGL_data.PLALNIIBLOF_en = AAAKAPGGNGL_readData.CFLMCGOJJJD;
			AAAKAPGGNGL_data.IJEKNCDIIAE_mver = AAAKAPGGNGL_readData.OFMGALJGDAO;
			AAAKAPGGNGL_data.FBFLDFMFFOH_rar = AAAKAPGGNGL_readData.ODBPKGJPLMD;
			AAAKAPGGNGL_list.Add(AAAKAPGGNGL_data);
		}
		res_data.AAAKAPGGNGL = AAAKAPGGNGL_list.ToArray();

		return res_data;
	}
}
