using FlatBuffers;
using System.Collections.Generic;

public class LFDHMBMBANF
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int OGKBHHLMMID { get; set; } // 0x14 EGMFBEEFMOH CBAAJCGPEJC NHMOKHOBEHB
	public uint PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public string OCDMGOGMHGE_KeyPrefix { get; set; } // 0x20 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public int MNOKEJIPOBJ { get; set; } // 0x24 NKCJIAEEAAF ACNHGHKOCLM GJLIJNICBKM
}
public class PFCELKENNNE
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class ODDAHAKDLMP
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class AIIMCMMBIFN
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int FGKGELOJBJK_ul { get; set; } // 0x10 IEOEIIPHADP GGPCGPLCJOP ELGKDOFPKNE
	public int[] AEDMJLGNDHN_IsSp { get; set; } // 0x14 BEGHLJIFPJM GFPFIMDNOBK LKEHADMGMJF
	public int[] GLCLFMGPMAN_ItemId { get; set; } // 0x18 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int[] LJKMKCOAICL_ItemCount { get; set; } // 0x1C BAPDOHKGDGN KJPMAPBJBKE PPBMLEFDPOF
	public int[] JJHPDDPKBHF { get; set; } // 0x20 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
}
public class IHILMALOBMA
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int CPKMLLNADLJ_Serie { get; set; } // 0x10 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public int FDBOPFEOENF_diva { get; set; } // 0x14 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public int[] GLCLFMGPMAN_ItemId { get; set; } // 0x18 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
}
public class FCJFGEJHJGK
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PBEEPMLJGJC_Cid { get; set; } // 0xC KOAMCDEGIGO JGJMCAHJFFE FJPAJAAPBEN
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int NDFOAINJPIN_pos { get; set; } // 0x14 MJDPJMGBMAA CLKKCPLEKBC CLJOOFCICMO
	public int CPKMLLNADLJ_Serie { get; set; } // 0x18 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public int FDBOPFEOENF_diva { get; set; } // 0x1C DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public string FEMMDNIELFC_Desc { get; set; } // 0x20 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string JEPGJJJBFLN_ConditionText { get; set; } // 0x24 HOHNIBIOFEB AKHEBLBJGBP EEJDMJMLKMG
	public int GOKJLBDJOLA_df { get; set; } // 0x28 FBKPAMHNOFM CCEEILBGBOM MKNIFMGHJHC
	public int GPNPBHLLHDI_srnk { get; set; } // 0x2C HEJGNFAFADB HKNLEPBHECG NDOLKOBKNNE
	public int IMEPEOAFIIB_cbrnk { get; set; } // 0x30 MJKECFNADDB GBBFFLPKKFA PFPAJELFONN
	public int MAPNDFCJFLJ_ConditionType { get; set; } // 0x34 DLCEAFBCBGK IPFCNEIHNLJ CLNEANLIOFN
	public int JBFLEDKDFCO_cid { get; set; } // 0x38 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public int PMDLBHLNIDP_Target { get; set; } // 0x3C KBPFPPBNJCC HNDKMDOPGNC NLFFKMHAAKB
	public int GLCLFMGPMAN_ItemId { get; set; } // 0x40 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int LJKMKCOAICL_ItemCount { get; set; } // 0x44 BAPDOHKGDGN KJPMAPBJBKE PPBMLEFDPOF
	public int JJHPDDPKBHF { get; set; } // 0x48 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
}
public class GJJGDBPNBGP
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class IDPIHOHBGBH
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NFJHOMPBCPA
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public AIIMCMMBIFN[] CACDKPLABDE { get; set; } // 0xC PKBCLOGHPMG EPDHOBBIHJJ KLBMPAKFPKO
	public IHILMALOBMA[] APHNKNGKKFC { get; set; } // 0x10 NKNDJILLFLC IGMIBBHAANI LBGEJOLEKPL
	public FCJFGEJHJGK[] ABGNJMDKCEL { get; set; } // 0x14 LONKBOGPMAM MCPCDCLAOPM FGKJIMMAAKD
	public GJJGDBPNBGP[] AKIFKNAJBFG { get; set; } // 0x18 IAKBEDJFGBM ENLBPCBNDHI BOMDLPLMGAJ
	public IDPIHOHBGBH[] EKBIDLMHCBF { get; set; } // 0x1C HHEICLEJFJD PCDKGEEOEPP DCAMCMCJOHD
}
public class LGDFIOHBHIK
{
	public LFDHMBMBANF[] AJHKFCBHLKF { get; set; } // 0x8 GMFDANCDGIH FDNDPMEIJHL HABOJOAKION
	public PFCELKENNNE[] BHGDNGHDDAC { get; set; } // 0xC JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public ODDAHAKDLMP[] MHGMDJNOLMI { get; set; } // 0x10 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public NFJHOMPBCPA[] LMEMCJJJGKO { get; set; } // 0x14 NABHAOFEDJC MLNGIBACFPI BIIMDCIKKAF
	public static LGDFIOHBHIK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xD70AC0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JGABIAKLIJE res_readData = JGABIAKLIJE.GetRootAsJGABIAKLIJE(buffer);
		LGDFIOHBHIK res_data = new LGDFIOHBHIK();

		List<LFDHMBMBANF> AJHKFCBHLKF_list = new List<LFDHMBMBANF>();
		for(int AJHKFCBHLKF_idx = 0; AJHKFCBHLKF_idx < res_readData.GMMJCFGMCJHLength; AJHKFCBHLKF_idx++)
		{
			POKOMFMBPID AJHKFCBHLKF_readData = res_readData.GetGMMJCFGMCJH(AJHKFCBHLKF_idx);
			LFDHMBMBANF AJHKFCBHLKF_data = new LFDHMBMBANF();

			AJHKFCBHLKF_data.PPFNGGCBJKC_id = AJHKFCBHLKF_readData.BBPHAPFBFHK;
			AJHKFCBHLKF_data.IJEKNCDIIAE_mver = AJHKFCBHLKF_readData.OFMGALJGDAO;
			AJHKFCBHLKF_data.PLALNIIBLOF_en = AJHKFCBHLKF_readData.CFLMCGOJJJD;
			AJHKFCBHLKF_data.OGKBHHLMMID = AJHKFCBHLKF_readData.BJGOGMAOOOF;
			AJHKFCBHLKF_data.PDBPFJJCADD_open_at = AJHKFCBHLKF_readData.NJLJEKDBPCH;
			AJHKFCBHLKF_data.FDBNFFNFOND_close_at = AJHKFCBHLKF_readData.MAOAGDBDBIB;
			AJHKFCBHLKF_data.OCDMGOGMHGE_KeyPrefix = AJHKFCBHLKF_readData.HAEMDABJFJF;
			AJHKFCBHLKF_data.MNOKEJIPOBJ = AJHKFCBHLKF_readData.OAHOHJALFMC;
			AJHKFCBHLKF_list.Add(AJHKFCBHLKF_data);
		}
		res_data.AJHKFCBHLKF = AJHKFCBHLKF_list.ToArray();

		List<PFCELKENNNE> BHGDNGHDDAC_list = new List<PFCELKENNNE>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			KAAOOFNDCML BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			PFCELKENNNE BHGDNGHDDAC_data = new PFCELKENNNE();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<ODDAHAKDLMP> MHGMDJNOLMI_list = new List<ODDAHAKDLMP>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			LKAHFKFPLAH MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			ODDAHAKDLMP MHGMDJNOLMI_data = new ODDAHAKDLMP();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<NFJHOMPBCPA> LMEMCJJJGKO_list = new List<NFJHOMPBCPA>();
		for(int LMEMCJJJGKO_idx = 0; LMEMCJJJGKO_idx < res_readData.KDCENEMGIFLLength; LMEMCJJJGKO_idx++)
		{
			EDPJPHELMBH LMEMCJJJGKO_readData = res_readData.GetKDCENEMGIFL(LMEMCJJJGKO_idx);
			NFJHOMPBCPA LMEMCJJJGKO_data = new NFJHOMPBCPA();

			LMEMCJJJGKO_data.PPFNGGCBJKC_id = LMEMCJJJGKO_readData.BBPHAPFBFHK;
			List<AIIMCMMBIFN> CACDKPLABDE_list = new List<AIIMCMMBIFN>();
			for(int CACDKPLABDE_idx = 0; CACDKPLABDE_idx < LMEMCJJJGKO_readData.HEFLJHJEIJCLength; CACDKPLABDE_idx++)
			{
				DGKLGFOIGJB CACDKPLABDE_readData = LMEMCJJJGKO_readData.GetHEFLJHJEIJC(CACDKPLABDE_idx);
				AIIMCMMBIFN CACDKPLABDE_data = new AIIMCMMBIFN();

				CACDKPLABDE_data.PPFNGGCBJKC_id = CACDKPLABDE_readData.BBPHAPFBFHK;
				CACDKPLABDE_data.PLALNIIBLOF_en = CACDKPLABDE_readData.CFLMCGOJJJD;
				CACDKPLABDE_data.FGKGELOJBJK_ul = CACDKPLABDE_readData.LGACBNIDPFF;
				List<int> AEDMJLGNDHN_list = new List<int>();
				for(int AEDMJLGNDHN_idx = 0; AEDMJLGNDHN_idx < CACDKPLABDE_readData.PLHCBEBGMIELength; AEDMJLGNDHN_idx++)
				{
					AEDMJLGNDHN_list.Add(CACDKPLABDE_readData.GetPLHCBEBGMIE(AEDMJLGNDHN_idx));
				}
				CACDKPLABDE_data.AEDMJLGNDHN_IsSp = AEDMJLGNDHN_list.ToArray();

				List<int> GLCLFMGPMAN_list = new List<int>();
				for(int GLCLFMGPMAN_idx = 0; GLCLFMGPMAN_idx < CACDKPLABDE_readData.AGPECCAGHFLLength; GLCLFMGPMAN_idx++)
				{
					GLCLFMGPMAN_list.Add(CACDKPLABDE_readData.GetAGPECCAGHFL(GLCLFMGPMAN_idx));
				}
				CACDKPLABDE_data.GLCLFMGPMAN_ItemId = GLCLFMGPMAN_list.ToArray();

				List<int> LJKMKCOAICL_list = new List<int>();
				for(int LJKMKCOAICL_idx = 0; LJKMKCOAICL_idx < CACDKPLABDE_readData.DNGDCCIGJJELength; LJKMKCOAICL_idx++)
				{
					LJKMKCOAICL_list.Add(CACDKPLABDE_readData.GetDNGDCCIGJJE(LJKMKCOAICL_idx));
				}
				CACDKPLABDE_data.LJKMKCOAICL_ItemCount = LJKMKCOAICL_list.ToArray();

				List<int> JJHPDDPKBHF_list = new List<int>();
				for(int JJHPDDPKBHF_idx = 0; JJHPDDPKBHF_idx < CACDKPLABDE_readData.OOJBHHPJONJLength; JJHPDDPKBHF_idx++)
				{
					JJHPDDPKBHF_list.Add(CACDKPLABDE_readData.GetOOJBHHPJONJ(JJHPDDPKBHF_idx));
				}
				CACDKPLABDE_data.JJHPDDPKBHF = JJHPDDPKBHF_list.ToArray();

				CACDKPLABDE_list.Add(CACDKPLABDE_data);
			}
			LMEMCJJJGKO_data.CACDKPLABDE = CACDKPLABDE_list.ToArray();

			List<IHILMALOBMA> APHNKNGKKFC_list = new List<IHILMALOBMA>();
			for(int APHNKNGKKFC_idx = 0; APHNKNGKKFC_idx < LMEMCJJJGKO_readData.ILBKJACHOHMLength; APHNKNGKKFC_idx++)
			{
				DILKNNAKBII APHNKNGKKFC_readData = LMEMCJJJGKO_readData.GetILBKJACHOHM(APHNKNGKKFC_idx);
				IHILMALOBMA APHNKNGKKFC_data = new IHILMALOBMA();

				APHNKNGKKFC_data.PPFNGGCBJKC_id = APHNKNGKKFC_readData.BBPHAPFBFHK;
				APHNKNGKKFC_data.PLALNIIBLOF_en = APHNKNGKKFC_readData.CFLMCGOJJJD;
				APHNKNGKKFC_data.CPKMLLNADLJ_Serie = APHNKNGKKFC_readData.LMLNKHMPOIG;
				APHNKNGKKFC_data.FDBOPFEOENF_diva = APHNKNGKKFC_readData.PIFAMBCEMKL;
				List<int> GLCLFMGPMAN_list = new List<int>();
				for(int GLCLFMGPMAN_idx = 0; GLCLFMGPMAN_idx < APHNKNGKKFC_readData.AGPECCAGHFLLength; GLCLFMGPMAN_idx++)
				{
					GLCLFMGPMAN_list.Add(APHNKNGKKFC_readData.GetAGPECCAGHFL(GLCLFMGPMAN_idx));
				}
				APHNKNGKKFC_data.GLCLFMGPMAN_ItemId = GLCLFMGPMAN_list.ToArray();

				APHNKNGKKFC_list.Add(APHNKNGKKFC_data);
			}
			LMEMCJJJGKO_data.APHNKNGKKFC = APHNKNGKKFC_list.ToArray();

			List<FCJFGEJHJGK> ABGNJMDKCEL_list = new List<FCJFGEJHJGK>();
			for(int ABGNJMDKCEL_idx = 0; ABGNJMDKCEL_idx < LMEMCJJJGKO_readData.DELLLBAKAAALength; ABGNJMDKCEL_idx++)
			{
				DMMAPNIMIIK ABGNJMDKCEL_readData = LMEMCJJJGKO_readData.GetDELLLBAKAAA(ABGNJMDKCEL_idx);
				FCJFGEJHJGK ABGNJMDKCEL_data = new FCJFGEJHJGK();

				ABGNJMDKCEL_data.PPFNGGCBJKC_id = ABGNJMDKCEL_readData.BBPHAPFBFHK;
				ABGNJMDKCEL_data.PBEEPMLJGJC_Cid = ABGNJMDKCEL_readData.LDMLHPCNAPI;
				ABGNJMDKCEL_data.PLALNIIBLOF_en = ABGNJMDKCEL_readData.CFLMCGOJJJD;
				ABGNJMDKCEL_data.NDFOAINJPIN_pos = ABGNJMDKCEL_readData.LGEDAJAFHGG;
				ABGNJMDKCEL_data.CPKMLLNADLJ_Serie = ABGNJMDKCEL_readData.LMLNKHMPOIG;
				ABGNJMDKCEL_data.FDBOPFEOENF_diva = ABGNJMDKCEL_readData.PIFAMBCEMKL;
				ABGNJMDKCEL_data.FEMMDNIELFC_Desc = ABGNJMDKCEL_readData.NNKLANONDOM;
				ABGNJMDKCEL_data.JEPGJJJBFLN_ConditionText = ABGNJMDKCEL_readData.KPAGDPKMDOK;
				ABGNJMDKCEL_data.GOKJLBDJOLA_df = ABGNJMDKCEL_readData.FGONCIDNPDP;
				ABGNJMDKCEL_data.GPNPBHLLHDI_srnk = ABGNJMDKCEL_readData.GCJPCPFKIEL;
				ABGNJMDKCEL_data.IMEPEOAFIIB_cbrnk = ABGNJMDKCEL_readData.NEFKMGMJAOK;
				ABGNJMDKCEL_data.MAPNDFCJFLJ_ConditionType = ABGNJMDKCEL_readData.FIDHINJIOAD;
				ABGNJMDKCEL_data.JBFLEDKDFCO_cid = ABGNJMDKCEL_readData.HOENDPOGFIO;
				ABGNJMDKCEL_data.PMDLBHLNIDP_Target = ABGNJMDKCEL_readData.ECFLMBOLCAA;
				ABGNJMDKCEL_data.GLCLFMGPMAN_ItemId = ABGNJMDKCEL_readData.MBBJMJAAODG;
				ABGNJMDKCEL_data.LJKMKCOAICL_ItemCount = ABGNJMDKCEL_readData.COEFBEEOPHH;
				ABGNJMDKCEL_data.JJHPDDPKBHF = ABGNJMDKCEL_readData.EGCKDOIIACL;
				ABGNJMDKCEL_list.Add(ABGNJMDKCEL_data);
			}
			LMEMCJJJGKO_data.ABGNJMDKCEL = ABGNJMDKCEL_list.ToArray();

			List<GJJGDBPNBGP> AKIFKNAJBFG_list = new List<GJJGDBPNBGP>();
			for(int AKIFKNAJBFG_idx = 0; AKIFKNAJBFG_idx < LMEMCJJJGKO_readData.GFEGLNILLEELength; AKIFKNAJBFG_idx++)
			{
				CONJKLGMJJE AKIFKNAJBFG_readData = LMEMCJJJGKO_readData.GetGFEGLNILLEE(AKIFKNAJBFG_idx);
				GJJGDBPNBGP AKIFKNAJBFG_data = new GJJGDBPNBGP();

				AKIFKNAJBFG_data.LJNAKDMILMC_key = AKIFKNAJBFG_readData.AGOIMGHMGOH;
				AKIFKNAJBFG_data.JBGEEPFKIGG_val = AKIFKNAJBFG_readData.KJFEBMBHKOC;
				AKIFKNAJBFG_list.Add(AKIFKNAJBFG_data);
			}
			LMEMCJJJGKO_data.AKIFKNAJBFG = AKIFKNAJBFG_list.ToArray();

			List<IDPIHOHBGBH> EKBIDLMHCBF_list = new List<IDPIHOHBGBH>();
			for(int EKBIDLMHCBF_idx = 0; EKBIDLMHCBF_idx < LMEMCJJJGKO_readData.BFINILLMFOMLength; EKBIDLMHCBF_idx++)
			{
				BHJMBLJJLNM EKBIDLMHCBF_readData = LMEMCJJJGKO_readData.GetBFINILLMFOM(EKBIDLMHCBF_idx);
				IDPIHOHBGBH EKBIDLMHCBF_data = new IDPIHOHBGBH();

				EKBIDLMHCBF_data.LJNAKDMILMC_key = EKBIDLMHCBF_readData.AGOIMGHMGOH;
				EKBIDLMHCBF_data.JBGEEPFKIGG_val = EKBIDLMHCBF_readData.KJFEBMBHKOC;
				EKBIDLMHCBF_list.Add(EKBIDLMHCBF_data);
			}
			LMEMCJJJGKO_data.EKBIDLMHCBF = EKBIDLMHCBF_list.ToArray();

			LMEMCJJJGKO_list.Add(LMEMCJJJGKO_data);
		}
		res_data.LMEMCJJJGKO = LMEMCJJJGKO_list.ToArray();

		return res_data;
	}
}
