using FlatBuffers;
using System.Collections.Generic;

public class IBOBDDNBCKJ
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint DMEDKJPOLCH_cat { get; set; } // 0xC JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint JBGEEPFKIGG_val { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public uint DOOGFEGEKLG_max { get; set; } // 0x14 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public uint PLALNIIBLOF_en { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int IJEKNCDIIAE_mver { get; set; } // 0x1C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint FBFLDFMFFOH_rar { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint FPOMEEJFBIG_odr { get; set; } // 0x24 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
}
public class LLENNGEBHNC
{
	public IBOBDDNBCKJ[] AHGBBPMKAJK { get; set; } // 0x8 NGAOCNIGIFD BPBKKIAJABI GLFIMOKMIJI
	public static LLENNGEBHNC HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x180CF34
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		EAHMHMEDAOG res_readData = EAHMHMEDAOG.GetRootAsEAHMHMEDAOG(buffer);
		LLENNGEBHNC res_data = new LLENNGEBHNC();

		List<IBOBDDNBCKJ> AHGBBPMKAJK_list = new List<IBOBDDNBCKJ>();
		for(int AHGBBPMKAJK_idx = 0; AHGBBPMKAJK_idx < res_readData.GNEIHOGKEDGLength; AHGBBPMKAJK_idx++)
		{
			JPCMJGNLFFA AHGBBPMKAJK_readData = res_readData.GetGNEIHOGKEDG(AHGBBPMKAJK_idx);
			IBOBDDNBCKJ AHGBBPMKAJK_data = new IBOBDDNBCKJ();

			AHGBBPMKAJK_data.PPFNGGCBJKC_id = AHGBBPMKAJK_readData.BBPHAPFBFHK;
			AHGBBPMKAJK_data.DMEDKJPOLCH_cat = AHGBBPMKAJK_readData.ADCLAGBHDBC;
			AHGBBPMKAJK_data.JBGEEPFKIGG_val = AHGBBPMKAJK_readData.KJFEBMBHKOC;
			AHGBBPMKAJK_data.DOOGFEGEKLG_max = AHGBBPMKAJK_readData.GEJGMBBCFEE;
			AHGBBPMKAJK_data.PLALNIIBLOF_en = AHGBBPMKAJK_readData.CFLMCGOJJJD;
			AHGBBPMKAJK_data.IJEKNCDIIAE_mver = AHGBBPMKAJK_readData.OFMGALJGDAO;
			AHGBBPMKAJK_data.FBFLDFMFFOH_rar = AHGBBPMKAJK_readData.ODBPKGJPLMD;
			AHGBBPMKAJK_data.FPOMEEJFBIG_odr = AHGBBPMKAJK_readData.AEAKMMJLLDK;
			AHGBBPMKAJK_list.Add(AHGBBPMKAJK_data);
		}
		res_data.AHGBBPMKAJK = AHGBBPMKAJK_list.ToArray();

		return res_data;
	}
}
