using FlatBuffers;
using System.Collections.Generic;

public class BMPAGNNCFEC
{
	public int IKPIDCFOFEA_no { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM_get_no PCJEHLGEJDH_set_no
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public string FILGCAEHBAC { get; set; } // 0x10 AHCPHLKNCIH CLJEANKIMID_get_ NMBDMBBNFFI_set_
	public string DNJLJMKKDNA_EventId { get; set; } // 0x14 KCIFEAIAGDG DONEINFNFCP_get_EventId EPEBGHFNMKP_set_EventId
	public int DIPKCALNIII_diva_id { get; set; } // 0x18 HLEPHANBMGN EOGPBFIDAPF_get_diva_id JDNCGPBAFMB_set_diva_id
	public int BFGNMDGOEID_Pattern { get; set; } // 0x1C OINMOJBHLNE JKLBMKKNJCP_get_Pattern KCBMJJKGIEO_set_Pattern
	public int BEEAIAAJOHD_CostumeId { get; set; } // 0x20 JPEMECNHGLE DIIBIOEMHAI_get_CostumeId JIHEDMEFKAF_set_CostumeId
	public string FPLEBCKDCBE_pos_x { get; set; } // 0x24 BJHAJOOCEPM GMAGDACFGJF_get_pos_x BNOJHOABBFC_set_pos_x
	public string MDLMHEDHPHA_pos_y { get; set; } // 0x28 NIBANBEBJBP HBELOEOGKNM_get_pos_y APHNMFBNLBJ_set_pos_y
	public string CDKLKKKGAMB { get; set; } // 0x2C JJDILEPDIED PENAMACOCDB_get_ IDIJPHEIMNP_set_
	public string OAPEIEHMIJD { get; set; } // 0x30 HBDPNLCHOOF MGAKONGDNKC_get_ AGKNLFOALPN_set_
	public string IMGHEKMHHPC { get; set; } // 0x34 GIFFOGIIONL GODOEDOGOJL_get_ FNKEAHLECFK_set_
	public string GJEEMHGGDKD { get; set; } // 0x38 IOIIDKANOPA LAGPIOKNLKF_get_ FANGLHCAKIA_set_
	public string AELANGEHIPP { get; set; } // 0x3C IECEJFEGINH FCDHOPBCOOJ_get_ FIGGJPADNAP_set_
	public string EHDNFJOMMJJ { get; set; } // 0x40 JLOOCGHBFNN AFIDICHGOPM_get_ BHGEENOKOMF_set_
	public string LNKDMOBAHDA { get; set; } // 0x44 LKNFLPFPJMM OGLAJKLHCND_get_ LEBCFGLJJLO_set_
	public string LNMKDNMJLOE { get; set; } // 0x48 AJLANPDHALJ NLLNADCPCGF_get_ IEEJGALELAN_set_
	public string MPCKINJNGJH { get; set; } // 0x4C PEFHKIDOOGD IOGICLMACBK_get_ OEEOHBMHAEA_set_
	public string JIDKMIHGOHI { get; set; } // 0x50 MIPGBAHPADD BEBDAGCDNOL_get_ DLPIBIIBMIA_set_
	public int APGKOJKNNGP_EmblemId { get; set; } // 0x54 ONNNFKJBEEE KGLCIOHDBLL_get_EmblemId DJKADEGEAHE_set_EmblemId
	public int DCNFOHHNAEF { get; set; } // 0x58 JHBEFPKPJMK OJEIAPCKBOH_get_ HODLBNIOKLD_set_
	public int BEHGCAMHJIE { get; set; } // 0x5C PLEMPJIBDOG MGCMEGNIGMN_get_ IIMIIHDKMFG_set_
}
public class BBJJIIOLGCE
{
	public int IKPIDCFOFEA_no { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM_get_no PCJEHLGEJDH_set_no
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int HIEKBDMHKLP_MarkerNo { get; set; } // 0x10 MICLNMBOAJD FEDEEOKEBBH_get_MarkerNo AJEOEBDGIEJ_set_MarkerNo
	public string BLOIKEAGFED { get; set; } // 0x14 MFIPGNHFCPB DHMMPBOLDOI_get_ MDCPPKMMAAB_set_
	public int IOCAJMALMLJ { get; set; } // 0x18 JMEOGCMEKOH FEGPODJIFKL_get_ KFLGAHFCPAK_set_
	public int BEBCANGAMAK { get; set; } // 0x1C PMAMFFGIGOO EMBFDLNHDNF_get_ JPACANPPHOA_set_
}
public class LPKFACLGIMO
{
	public BMPAGNNCFEC[] BFKBNEAMHEB { get; set; } // 0x8 MLFHEGKMAEE GIDJPOFAKEN_get_ KDJJHDDAABF_set_
	public BBJJIIOLGCE[] PLIKHNFGBLO { get; set; } // 0xC GCBMJKCEGEL DOBNPKICLPI_get_ CICBGDKNIAL_set_
	public static LPKFACLGIMO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x10CE588
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LPLDAEJONGA res_readData_ = LPLDAEJONGA.GetRootAsLPLDAEJONGA(buffer);
		LPKFACLGIMO res_data_ = new LPKFACLGIMO();

		List<BMPAGNNCFEC> BFKBNEAMHEB_list_ = new List<BMPAGNNCFEC>();
		for(int BFKBNEAMHEB_idx_ = 0; BFKBNEAMHEB_idx_ < res_readData_.DGCEKGHCAKJLength; BFKBNEAMHEB_idx_++)
		{
			GCFDBLLEKED BFKBNEAMHEB_readData_ = res_readData_.GetDGCEKGHCAKJ(BFKBNEAMHEB_idx_);
			BMPAGNNCFEC BFKBNEAMHEB_data_ = new BMPAGNNCFEC();

			BFKBNEAMHEB_data_.IKPIDCFOFEA_no = BFKBNEAMHEB_readData_.CILHGCNPEFO/*_no*/;
			BFKBNEAMHEB_data_.PLALNIIBLOF_en = BFKBNEAMHEB_readData_.CFLMCGOJJJD/*_en*/;
			BFKBNEAMHEB_data_.FILGCAEHBAC = BFKBNEAMHEB_readData_.OAHLFBDGEMA;
			BFKBNEAMHEB_data_.DNJLJMKKDNA_EventId = BFKBNEAMHEB_readData_.IDHMHHMGAHM/*_EventId*/;
			BFKBNEAMHEB_data_.DIPKCALNIII_diva_id = BFKBNEAMHEB_readData_.DPKCMAHGHNI/*_diva_id*/;
			BFKBNEAMHEB_data_.BFGNMDGOEID_Pattern = BFKBNEAMHEB_readData_.JIDEBKHEBDK/*_Pattern*/;
			BFKBNEAMHEB_data_.BEEAIAAJOHD_CostumeId = BFKBNEAMHEB_readData_.EGLEPNNDBFM/*_CostumeId*/;
			BFKBNEAMHEB_data_.FPLEBCKDCBE_pos_x = BFKBNEAMHEB_readData_.CFCGMIMJKLE/*_pos_x*/;
			BFKBNEAMHEB_data_.MDLMHEDHPHA_pos_y = BFKBNEAMHEB_readData_.OFGPIPFIPKB/*_pos_y*/;
			BFKBNEAMHEB_data_.CDKLKKKGAMB = BFKBNEAMHEB_readData_.OJPMHDDPLNB;
			BFKBNEAMHEB_data_.OAPEIEHMIJD = BFKBNEAMHEB_readData_.HKAOHJLHFIB;
			BFKBNEAMHEB_data_.IMGHEKMHHPC = BFKBNEAMHEB_readData_.LGDGBMPGHFO;
			BFKBNEAMHEB_data_.GJEEMHGGDKD = BFKBNEAMHEB_readData_.PGHDIKKMIBA;
			BFKBNEAMHEB_data_.AELANGEHIPP = BFKBNEAMHEB_readData_.IEBDGJNJDNI;
			BFKBNEAMHEB_data_.EHDNFJOMMJJ = BFKBNEAMHEB_readData_.BBNNMGEMEGM;
			BFKBNEAMHEB_data_.LNKDMOBAHDA = BFKBNEAMHEB_readData_.FIGDHKGEOOF;
			BFKBNEAMHEB_data_.LNMKDNMJLOE = BFKBNEAMHEB_readData_.OHANDJDIPGG;
			BFKBNEAMHEB_data_.MPCKINJNGJH = BFKBNEAMHEB_readData_.PMIPDCPFJHH;
			BFKBNEAMHEB_data_.JIDKMIHGOHI = BFKBNEAMHEB_readData_.FFELJDJOGMI;
			BFKBNEAMHEB_data_.APGKOJKNNGP_EmblemId = BFKBNEAMHEB_readData_.MJGMLHPCJKL/*_EmblemId*/;
			BFKBNEAMHEB_data_.DCNFOHHNAEF = BFKBNEAMHEB_readData_.ILAPCKCGCJO;
			BFKBNEAMHEB_data_.BEHGCAMHJIE = BFKBNEAMHEB_readData_.HPLGKGLOAGC;
			BFKBNEAMHEB_list_.Add(BFKBNEAMHEB_data_);
		}
		res_data_.BFKBNEAMHEB = BFKBNEAMHEB_list_.ToArray();

		List<BBJJIIOLGCE> PLIKHNFGBLO_list_ = new List<BBJJIIOLGCE>();
		for(int PLIKHNFGBLO_idx_ = 0; PLIKHNFGBLO_idx_ < res_readData_.FJNMMFMGMKKLength; PLIKHNFGBLO_idx_++)
		{
			FOLCOOKNNKO PLIKHNFGBLO_readData_ = res_readData_.GetFJNMMFMGMKK(PLIKHNFGBLO_idx_);
			BBJJIIOLGCE PLIKHNFGBLO_data_ = new BBJJIIOLGCE();

			PLIKHNFGBLO_data_.IKPIDCFOFEA_no = PLIKHNFGBLO_readData_.CILHGCNPEFO/*_no*/;
			PLIKHNFGBLO_data_.PLALNIIBLOF_en = PLIKHNFGBLO_readData_.CFLMCGOJJJD/*_en*/;
			PLIKHNFGBLO_data_.HIEKBDMHKLP_MarkerNo = PLIKHNFGBLO_readData_.HNCIPPDJDPM/*_MarkerNo*/;
			PLIKHNFGBLO_data_.BLOIKEAGFED = PLIKHNFGBLO_readData_.IBCGFNCKHBJ;
			PLIKHNFGBLO_data_.IOCAJMALMLJ = PLIKHNFGBLO_readData_.JMLNODDMKCE;
			PLIKHNFGBLO_data_.BEBCANGAMAK = PLIKHNFGBLO_readData_.BJPLIBGKNON;
			PLIKHNFGBLO_list_.Add(PLIKHNFGBLO_data_);
		}
		res_data_.PLIKHNFGBLO = PLIKHNFGBLO_list_.ToArray();

		return res_data_;
	}
}
