using FlatBuffers;
using System.Collections.Generic;

public class BMPAGNNCFEC
{
	public int IKPIDCFOFEA { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM PCJEHLGEJDH
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string FILGCAEHBAC { get; set; } // 0x10 AHCPHLKNCIH CLJEANKIMID NMBDMBBNFFI
	public string DNJLJMKKDNA { get; set; } // 0x14 KCIFEAIAGDG DONEINFNFCP EPEBGHFNMKP
	public int DIPKCALNIII { get; set; } // 0x18 HLEPHANBMGN EOGPBFIDAPF JDNCGPBAFMB
	public int BFGNMDGOEID { get; set; } // 0x1C OINMOJBHLNE JKLBMKKNJCP KCBMJJKGIEO
	public int BEEAIAAJOHD { get; set; } // 0x20 JPEMECNHGLE DIIBIOEMHAI JIHEDMEFKAF
	public string FPLEBCKDCBE { get; set; } // 0x24 BJHAJOOCEPM GMAGDACFGJF BNOJHOABBFC
	public string MDLMHEDHPHA { get; set; } // 0x28 NIBANBEBJBP HBELOEOGKNM APHNMFBNLBJ
	public string CDKLKKKGAMB { get; set; } // 0x2C JJDILEPDIED PENAMACOCDB IDIJPHEIMNP
	public string OAPEIEHMIJD { get; set; } // 0x30 HBDPNLCHOOF MGAKONGDNKC AGKNLFOALPN
	public string IMGHEKMHHPC { get; set; } // 0x34 GIFFOGIIONL GODOEDOGOJL FNKEAHLECFK
	public string GJEEMHGGDKD { get; set; } // 0x38 IOIIDKANOPA LAGPIOKNLKF FANGLHCAKIA
	public string AELANGEHIPP { get; set; } // 0x3C IECEJFEGINH FCDHOPBCOOJ FIGGJPADNAP
	public string EHDNFJOMMJJ { get; set; } // 0x40 JLOOCGHBFNN AFIDICHGOPM BHGEENOKOMF
	public string LNKDMOBAHDA { get; set; } // 0x44 LKNFLPFPJMM OGLAJKLHCND LEBCFGLJJLO
	public string LNMKDNMJLOE { get; set; } // 0x48 AJLANPDHALJ NLLNADCPCGF IEEJGALELAN
	public string MPCKINJNGJH { get; set; } // 0x4C PEFHKIDOOGD IOGICLMACBK OEEOHBMHAEA
	public string JIDKMIHGOHI { get; set; } // 0x50 MIPGBAHPADD BEBDAGCDNOL DLPIBIIBMIA
	public int APGKOJKNNGP { get; set; } // 0x54 ONNNFKJBEEE KGLCIOHDBLL DJKADEGEAHE
	public int DCNFOHHNAEF { get; set; } // 0x58 JHBEFPKPJMK OJEIAPCKBOH HODLBNIOKLD
	public int BEHGCAMHJIE { get; set; } // 0x5C PLEMPJIBDOG MGCMEGNIGMN IIMIIHDKMFG
}
public class BBJJIIOLGCE
{
	public int IKPIDCFOFEA { get; set; } // 0x8 KLKLFOIDAPK CMEAKDLBLLM PCJEHLGEJDH
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int HIEKBDMHKLP { get; set; } // 0x10 MICLNMBOAJD FEDEEOKEBBH AJEOEBDGIEJ
	public string BLOIKEAGFED { get; set; } // 0x14 MFIPGNHFCPB DHMMPBOLDOI MDCPPKMMAAB
	public int IOCAJMALMLJ { get; set; } // 0x18 JMEOGCMEKOH FEGPODJIFKL KFLGAHFCPAK
	public int BEBCANGAMAK { get; set; } // 0x1C PMAMFFGIGOO EMBFDLNHDNF JPACANPPHOA
}
public class LPKFACLGIMO
{
	public BMPAGNNCFEC[] BFKBNEAMHEB { get; set; } // 0x8 MLFHEGKMAEE GIDJPOFAKEN KDJJHDDAABF
	public BBJJIIOLGCE[] PLIKHNFGBLO { get; set; } // 0xC GCBMJKCEGEL DOBNPKICLPI CICBGDKNIAL
	public static LPKFACLGIMO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x10CE588
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LPLDAEJONGA res_readData = LPLDAEJONGA.GetRootAsLPLDAEJONGA(buffer);
		LPKFACLGIMO res_data = new LPKFACLGIMO();

		List<BMPAGNNCFEC> BFKBNEAMHEB_list = new List<BMPAGNNCFEC>();
		for(int BFKBNEAMHEB_idx = 0; BFKBNEAMHEB_idx < res_readData.DGCEKGHCAKJLength; BFKBNEAMHEB_idx++)
		{
			GCFDBLLEKED BFKBNEAMHEB_readData = res_readData.GetDGCEKGHCAKJ(BFKBNEAMHEB_idx);
			BMPAGNNCFEC BFKBNEAMHEB_data = new BMPAGNNCFEC();

			BFKBNEAMHEB_data.IKPIDCFOFEA = BFKBNEAMHEB_readData.CILHGCNPEFO;
			BFKBNEAMHEB_data.PLALNIIBLOF = BFKBNEAMHEB_readData.CFLMCGOJJJD;
			BFKBNEAMHEB_data.FILGCAEHBAC = BFKBNEAMHEB_readData.OAHLFBDGEMA;
			BFKBNEAMHEB_data.DNJLJMKKDNA = BFKBNEAMHEB_readData.IDHMHHMGAHM;
			BFKBNEAMHEB_data.DIPKCALNIII = BFKBNEAMHEB_readData.DPKCMAHGHNI;
			BFKBNEAMHEB_data.BFGNMDGOEID = BFKBNEAMHEB_readData.JIDEBKHEBDK;
			BFKBNEAMHEB_data.BEEAIAAJOHD = BFKBNEAMHEB_readData.EGLEPNNDBFM;
			BFKBNEAMHEB_data.FPLEBCKDCBE = BFKBNEAMHEB_readData.CFCGMIMJKLE;
			BFKBNEAMHEB_data.MDLMHEDHPHA = BFKBNEAMHEB_readData.OFGPIPFIPKB;
			BFKBNEAMHEB_data.CDKLKKKGAMB = BFKBNEAMHEB_readData.OJPMHDDPLNB;
			BFKBNEAMHEB_data.OAPEIEHMIJD = BFKBNEAMHEB_readData.HKAOHJLHFIB;
			BFKBNEAMHEB_data.IMGHEKMHHPC = BFKBNEAMHEB_readData.LGDGBMPGHFO;
			BFKBNEAMHEB_data.GJEEMHGGDKD = BFKBNEAMHEB_readData.PGHDIKKMIBA;
			BFKBNEAMHEB_data.AELANGEHIPP = BFKBNEAMHEB_readData.IEBDGJNJDNI;
			BFKBNEAMHEB_data.EHDNFJOMMJJ = BFKBNEAMHEB_readData.BBNNMGEMEGM;
			BFKBNEAMHEB_data.LNKDMOBAHDA = BFKBNEAMHEB_readData.FIGDHKGEOOF;
			BFKBNEAMHEB_data.LNMKDNMJLOE = BFKBNEAMHEB_readData.OHANDJDIPGG;
			BFKBNEAMHEB_data.MPCKINJNGJH = BFKBNEAMHEB_readData.PMIPDCPFJHH;
			BFKBNEAMHEB_data.JIDKMIHGOHI = BFKBNEAMHEB_readData.FFELJDJOGMI;
			BFKBNEAMHEB_data.APGKOJKNNGP = BFKBNEAMHEB_readData.MJGMLHPCJKL;
			BFKBNEAMHEB_data.DCNFOHHNAEF = BFKBNEAMHEB_readData.ILAPCKCGCJO;
			BFKBNEAMHEB_data.BEHGCAMHJIE = BFKBNEAMHEB_readData.HPLGKGLOAGC;
			BFKBNEAMHEB_list.Add(BFKBNEAMHEB_data);
		}
		res_data.BFKBNEAMHEB = BFKBNEAMHEB_list.ToArray();

		List<BBJJIIOLGCE> PLIKHNFGBLO_list = new List<BBJJIIOLGCE>();
		for(int PLIKHNFGBLO_idx = 0; PLIKHNFGBLO_idx < res_readData.FJNMMFMGMKKLength; PLIKHNFGBLO_idx++)
		{
			FOLCOOKNNKO PLIKHNFGBLO_readData = res_readData.GetFJNMMFMGMKK(PLIKHNFGBLO_idx);
			BBJJIIOLGCE PLIKHNFGBLO_data = new BBJJIIOLGCE();

			PLIKHNFGBLO_data.IKPIDCFOFEA = PLIKHNFGBLO_readData.CILHGCNPEFO;
			PLIKHNFGBLO_data.PLALNIIBLOF = PLIKHNFGBLO_readData.CFLMCGOJJJD;
			PLIKHNFGBLO_data.HIEKBDMHKLP = PLIKHNFGBLO_readData.HNCIPPDJDPM;
			PLIKHNFGBLO_data.BLOIKEAGFED = PLIKHNFGBLO_readData.IBCGFNCKHBJ;
			PLIKHNFGBLO_data.IOCAJMALMLJ = PLIKHNFGBLO_readData.JMLNODDMKCE;
			PLIKHNFGBLO_data.BEBCANGAMAK = PLIKHNFGBLO_readData.BJPLIBGKNON;
			PLIKHNFGBLO_list.Add(PLIKHNFGBLO_data);
		}
		res_data.PLIKHNFGBLO = PLIKHNFGBLO_list.ToArray();

		return res_data;
	}
}
