using FlatBuffers;
using System.Collections.Generic;

public class FLNGBOANAGE
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FBFLDFMFFOH_rar { get; set; } // 0xC LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint JBGEEPFKIGG_val { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int FDBOPFEOENF_diva { get; set; } // 0x14 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public int GBJFNGCDKPM_typ { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
}
public class MADCJBCGGEE
{
	public FLNGBOANAGE[] GKNGIIHMBOD { get; set; } // 0x8 EMEIPPBCELJ PPDIJNPGCHB AHEPMHLJGHO
	public static MADCJBCGGEE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xA13E40
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OOKJGIANFNP res_readData = OOKJGIANFNP.GetRootAsOOKJGIANFNP(buffer);
		MADCJBCGGEE res_data = new MADCJBCGGEE();

		List<FLNGBOANAGE> GKNGIIHMBOD_list = new List<FLNGBOANAGE>();
		for(int GKNGIIHMBOD_idx = 0; GKNGIIHMBOD_idx < res_readData.LJOPIBIJHNALength; GKNGIIHMBOD_idx++)
		{
			LLGKOAFFEJF GKNGIIHMBOD_readData = res_readData.GetLJOPIBIJHNA(GKNGIIHMBOD_idx);
			FLNGBOANAGE GKNGIIHMBOD_data = new FLNGBOANAGE();

			GKNGIIHMBOD_data.PPFNGGCBJKC_id = GKNGIIHMBOD_readData.BBPHAPFBFHK;
			GKNGIIHMBOD_data.FBFLDFMFFOH_rar = GKNGIIHMBOD_readData.ODBPKGJPLMD;
			GKNGIIHMBOD_data.JBGEEPFKIGG_val = GKNGIIHMBOD_readData.KJFEBMBHKOC;
			GKNGIIHMBOD_data.FDBOPFEOENF_diva = GKNGIIHMBOD_readData.PIFAMBCEMKL;
			GKNGIIHMBOD_data.GBJFNGCDKPM_typ = GKNGIIHMBOD_readData.LPJPOOHJKAE;
			GKNGIIHMBOD_list.Add(GKNGIIHMBOD_data);
		}
		res_data.GKNGIIHMBOD = GKNGIIHMBOD_list.ToArray();

		return res_data;
	}
}
