using FlatBuffers;
using System.Collections.Generic;

public class FLNGBOANAGE
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FBFLDFMFFOH { get; set; } // 0xC LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int FDBOPFEOENF { get; set; } // 0x14 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public int GBJFNGCDKPM { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
}
public class MADCJBCGGEE
{
	public FLNGBOANAGE[] GKNGIIHMBOD { get; set; } // 0x8 EMEIPPBCELJ PPDIJNPGCHB AHEPMHLJGHO
	public static MADCJBCGGEE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xA13E40
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OOKJGIANFNP res_readData = OOKJGIANFNP.GetRootAsOOKJGIANFNP(buffer);
		MADCJBCGGEE res_data = new MADCJBCGGEE();

		List<FLNGBOANAGE> GKNGIIHMBOD_list = new List<FLNGBOANAGE>();
		for(int GKNGIIHMBOD_idx = 0; GKNGIIHMBOD_idx < res_readData.LJOPIBIJHNALength; GKNGIIHMBOD_idx++)
		{
			LLGKOAFFEJF GKNGIIHMBOD_readData = res_readData.GetLJOPIBIJHNA(GKNGIIHMBOD_idx);
			FLNGBOANAGE GKNGIIHMBOD_data = new FLNGBOANAGE();

			GKNGIIHMBOD_data.PPFNGGCBJKC = GKNGIIHMBOD_readData.BBPHAPFBFHK;
			GKNGIIHMBOD_data.FBFLDFMFFOH = GKNGIIHMBOD_readData.ODBPKGJPLMD;
			GKNGIIHMBOD_data.JBGEEPFKIGG = GKNGIIHMBOD_readData.KJFEBMBHKOC;
			GKNGIIHMBOD_data.FDBOPFEOENF = GKNGIIHMBOD_readData.PIFAMBCEMKL;
			GKNGIIHMBOD_data.GBJFNGCDKPM = GKNGIIHMBOD_readData.LPJPOOHJKAE;
			GKNGIIHMBOD_list.Add(GKNGIIHMBOD_data);
		}
		res_data.GKNGIIHMBOD = GKNGIIHMBOD_list.ToArray();

		return res_data;
	}
}
