using FlatBuffers;
using System.Collections.Generic;

public class IFKGBHNLKLK
{
	public string OPFGFINHFCE { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public uint OBGBAOLONDD { get; set; } // 0xC NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public uint MOEKELIIDEO { get; set; } // 0x10 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND { get; set; } // 0x14 JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint KNLGKBBIBOH { get; set; } // 0x18 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint NIMLIMFPNJP { get; set; } // 0x1C CFCDKDOEMHI KOAONIGFNCG FJIABKNMMCH
	public uint KCBGBFMGHPA { get; set; } // 0x20 EFPLKFAHIIB KKFGOCIGEKO LHGFDLDNFHN
	public int MJBKGOJBPAD { get; set; } // 0x24 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public int[] EJBGHLOOLBC { get; set; } // 0x28 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
}
public class BFOKFIJNCJJ
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD { get; set; } // 0x10 MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint[] OCDBMHBNLEF { get; set; } // 0x14 LPCHIABBGFA NGELBKLCNOH MDPMFHPNJIG
}
public class PALCPDPGOPC
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint GJNIPHMPMIC { get; set; } // 0xC DPPONBLCKFM KHBHBMGKHHM DBJGKNGMGOO
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FDBOPFEOENF { get; set; } // 0x14 DNDMMJJOAOE MJPHCAIKKJG GHECGDMEBFF
	public uint MJMPANIBFED { get; set; } // 0x18 GGAJJGLDIII LPHIIIAOHBE POHHJDNBLOD
	public string LICPCDCLOIO { get; set; } // 0x1C IHMDIJDCGJG HOLGODDMLPK EPOFNKOEIOL
}
public class COAOCGOFFHK
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class JBNGBDJIHLG
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class CKDNHLACCOP
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class MAGFOKIIPPD
{
	public IFKGBHNLKLK HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public BFOKFIJNCJJ[] KBFEMKJBHBL { get; set; } // 0xC JLAGPOJDACM DMIFMIKEHKE AHNGBJBPFLP
	public PALCPDPGOPC[] CEPBAOMAHNH { get; set; } // 0x10 EALHHHABHEI KJBLMCHIKFD OEBMOJPBAEF
	public COAOCGOFFHK[] MDDOGIAFDEI { get; set; } // 0x14 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public JBNGBDJIHLG[] BHGDNGHDDAC { get; set; } // 0x18 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public CKDNHLACCOP[] MHGMDJNOLMI { get; set; } // 0x1C JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static MAGFOKIIPPD HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xA141B4
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		FDGDGGHOJBP res_readData = FDGDGGHOJBP.GetRootAsFDGDGGHOJBP(buffer);
		MAGFOKIIPPD res_data = new MAGFOKIIPPD();

		HGBICHMJHMI HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		IFKGBHNLKLK HMBHNLCFDIH_data = new IFKGBHNLKLK();

		HMBHNLCFDIH_data.OPFGFINHFCE = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.OBGBAOLONDD = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.MOEKELIIDEO = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.KNLGKBBIBOH = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.NIMLIMFPNJP = HMBHNLCFDIH_readData.APJPCEEAANA;
		HMBHNLCFDIH_data.KCBGBFMGHPA = HMBHNLCFDIH_readData.KPMGJEELOEI;
		HMBHNLCFDIH_data.MJBKGOJBPAD = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC = EJBGHLOOLBC_list.ToArray();

		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<BFOKFIJNCJJ> KBFEMKJBHBL_list = new List<BFOKFIJNCJJ>();
		for(int KBFEMKJBHBL_idx = 0; KBFEMKJBHBL_idx < res_readData.BEINKIKDHCOLength; KBFEMKJBHBL_idx++)
		{
			PNLDFJMHBJH KBFEMKJBHBL_readData = res_readData.GetBEINKIKDHCO(KBFEMKJBHBL_idx);
			BFOKFIJNCJJ KBFEMKJBHBL_data = new BFOKFIJNCJJ();

			KBFEMKJBHBL_data.PPFNGGCBJKC = KBFEMKJBHBL_readData.BBPHAPFBFHK;
			KBFEMKJBHBL_data.OPFGFINHFCE = KBFEMKJBHBL_readData.IIDCFMHCPLJ;
			KBFEMKJBHBL_data.HEDAGCNPHGD = KBFEMKJBHBL_readData.HAEJDOGGKPC;
			List<uint> OCDBMHBNLEF_list = new List<uint>();
			for(int OCDBMHBNLEF_idx = 0; OCDBMHBNLEF_idx < KBFEMKJBHBL_readData.NHNLGCMFBNCLength; OCDBMHBNLEF_idx++)
			{
				OCDBMHBNLEF_list.Add(KBFEMKJBHBL_readData.GetNHNLGCMFBNC(OCDBMHBNLEF_idx));
			}
			KBFEMKJBHBL_data.OCDBMHBNLEF = OCDBMHBNLEF_list.ToArray();

			KBFEMKJBHBL_list.Add(KBFEMKJBHBL_data);
		}
		res_data.KBFEMKJBHBL = KBFEMKJBHBL_list.ToArray();

		List<PALCPDPGOPC> CEPBAOMAHNH_list = new List<PALCPDPGOPC>();
		for(int CEPBAOMAHNH_idx = 0; CEPBAOMAHNH_idx < res_readData.MMKDCMGIEKMLength; CEPBAOMAHNH_idx++)
		{
			IABACDAGDAP CEPBAOMAHNH_readData = res_readData.GetMMKDCMGIEKM(CEPBAOMAHNH_idx);
			PALCPDPGOPC CEPBAOMAHNH_data = new PALCPDPGOPC();

			CEPBAOMAHNH_data.PPFNGGCBJKC = CEPBAOMAHNH_readData.BBPHAPFBFHK;
			CEPBAOMAHNH_data.GJNIPHMPMIC = CEPBAOMAHNH_readData.GGJFACAIOBF;
			CEPBAOMAHNH_data.GBJFNGCDKPM = CEPBAOMAHNH_readData.LPJPOOHJKAE;
			CEPBAOMAHNH_data.FDBOPFEOENF = CEPBAOMAHNH_readData.PIFAMBCEMKL;
			CEPBAOMAHNH_data.MJMPANIBFED = CEPBAOMAHNH_readData.COPFAKAHEMN;
			CEPBAOMAHNH_data.LICPCDCLOIO = CEPBAOMAHNH_readData.IMOOHKAFLPP;
			CEPBAOMAHNH_list.Add(CEPBAOMAHNH_data);
		}
		res_data.CEPBAOMAHNH = CEPBAOMAHNH_list.ToArray();

		List<COAOCGOFFHK> MDDOGIAFDEI_list = new List<COAOCGOFFHK>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			IGPIHCHKGPE MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			COAOCGOFFHK MDDOGIAFDEI_data = new COAOCGOFFHK();

			MDDOGIAFDEI_data.PPFNGGCBJKC = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<JBNGBDJIHLG> BHGDNGHDDAC_list = new List<JBNGBDJIHLG>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			ALMNNMCFOHL BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			JBNGBDJIHLG BHGDNGHDDAC_data = new JBNGBDJIHLG();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<CKDNHLACCOP> MHGMDJNOLMI_list = new List<CKDNHLACCOP>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			GMBEOADAJAE MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			CKDNHLACCOP MHGMDJNOLMI_data = new CKDNHLACCOP();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
