using FlatBuffers;
using System.Collections.Generic;

public class IMDHBHHELPP
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public uint DOOGFEGEKLG_max { get; set; } // 0xC IKKMNBJGBJK AECMFIOFFJN_get_max NGOJJDOCIDG_set_max
	public uint HHGFOIMIGED { get; set; } // 0x10 ABDAOGLNIJK POJLCAFLBGA_get_ MNDPEODCBPL_set_
	public uint DODGLIDGBBC_ConditionValue { get; set; } // 0x14 AHLHEPGIFEI PAACNLDBGKP_get_ConditionValue AHIHPMDINHA_set_ConditionValue
}
public class BKJIHCIKGPA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int DMEDKJPOLCH_cat { get; set; } // 0x14 JAEJJPMKMFI IPKCKAAEEOE_get_cat JOGLLINFLJN_set_cat
	public int FPOMEEJFBIG_odr { get; set; } // 0x18 PJKJIFMIFDJ OEEBAHNAPEC_get_odr BEHAPLPPLNE_set_odr
	public int FBFLDFMFFOH_rar { get; set; } // 0x1C LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public int JBGEEPFKIGG_val { get; set; } // 0x20 AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
	public int EMIJNAFJFJO_expir { get; set; } // 0x24 GBHMMAHHJGG GBGPKONOFGD_get_expir KCFHLAFJJPJ_set_expir
	public uint PENIOLJHIPK { get; set; } // 0x28 BDEICLGKEHA AHIONKNDHHH_get_ NEOFLJKHAKC_set_
}
public class DGEFOEFDBNE
{
	public int KBDNDDMCCMC { get; set; } // 0x8 DPKDOPHMNPB OHBCJDEHNPO_get_ EFFNGHFLFKO_set_
	public int MALJIDIJEAO { get; set; } // 0xC DNNHJDCBDEG GINLPBMCLDP_get_ PMIGPAMCDDI_set_
	public int HBIFNGLIMPP { get; set; } // 0x10 DAPBJDFBIIL BOCBLAKOACE_get_ OIIACDMENIK_set_
	public int IBCJEHCCMFM { get; set; } // 0x14 BBIBEOOMICG BADMIIAGDMD_get_ ILNHHGLNKNK_set_
}
public class MAPLLKFHCLF
{
	public IMDHBHHELPP[] LIFDACJBDBA { get; set; } // 0x8 DHNOPCHCIOG OFJIEKEMPDA_get_ NDIKFOLDBJJ_set_
	public BKJIHCIKGPA[] CAHBHHIPMMO { get; set; } // 0xC BAPKFMJMIJP NMCNGABMFMG_get_ GKONNPFKLNC_set_
	public DGEFOEFDBNE JOELFNNPOPK { get; set; } // 0x10 EHDOPMGKKII NMNIPKLJBDP_get_ KFIJKPMDHGL_set_
	public static MAPLLKFHCLF HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xA2C984
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		IOOJDNCIHIC res_readData_ = IOOJDNCIHIC.GetRootAsIOOJDNCIHIC(buffer);
		MAPLLKFHCLF res_data_ = new MAPLLKFHCLF();

		List<IMDHBHHELPP> LIFDACJBDBA_list_ = new List<IMDHBHHELPP>();
		for(int LIFDACJBDBA_idx_ = 0; LIFDACJBDBA_idx_ < res_readData_.PKMCMIBBNDOLength; LIFDACJBDBA_idx_++)
		{
			ECNBODJFAFC LIFDACJBDBA_readData_ = res_readData_.GetPKMCMIBBNDO(LIFDACJBDBA_idx_);
			IMDHBHHELPP LIFDACJBDBA_data_ = new IMDHBHHELPP();

			LIFDACJBDBA_data_.PPFNGGCBJKC_id = LIFDACJBDBA_readData_.BBPHAPFBFHK/*_id*/;
			LIFDACJBDBA_data_.DOOGFEGEKLG_max = LIFDACJBDBA_readData_.GEJGMBBCFEE/*_max*/;
			LIFDACJBDBA_data_.HHGFOIMIGED = LIFDACJBDBA_readData_.MENLAOCDKFD;
			LIFDACJBDBA_data_.DODGLIDGBBC_ConditionValue = LIFDACJBDBA_readData_.LCDAMOBFFMK/*_ConditionValue*/;
			LIFDACJBDBA_list_.Add(LIFDACJBDBA_data_);
		}
		res_data_.LIFDACJBDBA = LIFDACJBDBA_list_.ToArray();

		List<BKJIHCIKGPA> CAHBHHIPMMO_list_ = new List<BKJIHCIKGPA>();
		for(int CAHBHHIPMMO_idx_ = 0; CAHBHHIPMMO_idx_ < res_readData_.IEFEAHKENMCLength; CAHBHHIPMMO_idx_++)
		{
			OBKDFBANMPH CAHBHHIPMMO_readData_ = res_readData_.GetIEFEAHKENMC(CAHBHHIPMMO_idx_);
			BKJIHCIKGPA CAHBHHIPMMO_data_ = new BKJIHCIKGPA();

			CAHBHHIPMMO_data_.PPFNGGCBJKC_id = CAHBHHIPMMO_readData_.BBPHAPFBFHK/*_id*/;
			CAHBHHIPMMO_data_.IJEKNCDIIAE_mver = CAHBHHIPMMO_readData_.OFMGALJGDAO/*_mver*/;
			CAHBHHIPMMO_data_.PLALNIIBLOF_en = CAHBHHIPMMO_readData_.CFLMCGOJJJD/*_en*/;
			CAHBHHIPMMO_data_.DMEDKJPOLCH_cat = CAHBHHIPMMO_readData_.ADCLAGBHDBC/*_cat*/;
			CAHBHHIPMMO_data_.FPOMEEJFBIG_odr = CAHBHHIPMMO_readData_.AEAKMMJLLDK/*_odr*/;
			CAHBHHIPMMO_data_.FBFLDFMFFOH_rar = CAHBHHIPMMO_readData_.ODBPKGJPLMD/*_rar*/;
			CAHBHHIPMMO_data_.JBGEEPFKIGG_val = CAHBHHIPMMO_readData_.KJFEBMBHKOC/*_val*/;
			CAHBHHIPMMO_data_.EMIJNAFJFJO_expir = CAHBHHIPMMO_readData_.HHGNAFHNHEK/*_expir*/;
			CAHBHHIPMMO_data_.PENIOLJHIPK = CAHBHHIPMMO_readData_.ODEMBFLHJGG;
			CAHBHHIPMMO_list_.Add(CAHBHHIPMMO_data_);
		}
		res_data_.CAHBHHIPMMO = CAHBHHIPMMO_list_.ToArray();

		HDMBLGJMPMA JOELFNNPOPK_readData_ = res_readData_.OFIBOIJKMPK;
		DGEFOEFDBNE JOELFNNPOPK_data_ = new DGEFOEFDBNE();

		JOELFNNPOPK_data_.KBDNDDMCCMC = JOELFNNPOPK_readData_.FANPJEPOAFK;
		JOELFNNPOPK_data_.MALJIDIJEAO = JOELFNNPOPK_readData_.PENNDFJDJMP;
		JOELFNNPOPK_data_.HBIFNGLIMPP = JOELFNNPOPK_readData_.CNOIMMHCCIH;
		JOELFNNPOPK_data_.IBCJEHCCMFM = JOELFNNPOPK_readData_.IDHMEJECPBO;
		res_data_.JOELFNNPOPK = JOELFNNPOPK_data_;
		return res_data_;
	}
}
