using FlatBuffers;
using System.Collections.Generic;

public class PLCJIGFCOIK
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int CPGFOBNKKBF { get; set; } // 0x10 CIAEKFDKLJB AMNKHCIJHJD INJMDACNFOL
	public string PFAOBLDNMGF { get; set; } // 0x14 DFHKMMADKJK EGIONHIJBIJ OBIJPLJHIIM
	public string PDHGIGPAEBG { get; set; } // 0x18 HCBCLJEGFKJ JEDAGPENDIG HPDKOCKJHPK
	public int BFINGCJHOHI { get; set; } // 0x1C PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public int GBJFNGCDKPM { get; set; } // 0x20 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int PDBPFJJCADD { get; set; } // 0x24 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int EGBOHDFBAPB { get; set; } // 0x28 DDNBDNJHAIB MGOEKKJNOLF NHPFDCAFAFF
	public int HPGNBPIBAOM { get; set; } // 0x2C BMEHEHGDBEL CNGGNJIILPC KINBLEJIELP
	public int AFHPLBPHEGA { get; set; } // 0x30 MEPFNKKKPHP INHKANPGKOO MJDENHCKCOE
	public int HEOLEHDFLJO { get; set; } // 0x34 EALEFNJMEPK OICOCHBFNAK HGLFJJHECGH
	public string KLMPFGOCBHC { get; set; } // 0x38 MODIAAEGMCJ BGJNIABLBDB HFBJLALGKOM
	public int DLCGAMHADEN { get; set; } // 0x3C ANDDAFHKOPK BNGHEBJEOPL PBMMAJFCPJL
	public int[] KGOFMDMDFCJ { get; set; } // 0x40 DODJFJLJPIE NPEIPAKLPPG CCMIKCFIDEM
	public int[] NNIIINKFDBG { get; set; } // 0x44 BGNHEGBJBFI JJCMDBOMGGE BEJCKOIHNPK
	public int IHCLFMKAJND { get; set; } // 0x48 HHENDIIFCBD MJKPAAFNENM LNMLLJLJFKN
	public int EILKGEADKGH { get; set; } // 0x4C PBIPJHCABED NPDDACIHBKD BJJMCKHBPNH
}
public class EGHGEIALECF
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string FEMMDNIELFC { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public int PDBPFJJCADD { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int EGBOHDFBAPB { get; set; } // 0x18 DDNBDNJHAIB MGOEKKJNOLF NHPFDCAFAFF
	public int KAPMOPMDHJE { get; set; } // 0x1C EJDCHACDMPH MONBNPKLFGC KGFFKEDNIID
}
public class MDFCHKPOMAJ
{
	public PLCJIGFCOIK[] GKBBBINCAGN { get; set; } // 0x8 FPAGOGOKEJK LNIEKMGPGDO FPJMNEDPCHG
	public EGHGEIALECF[] CMFJFBJHKPE { get; set; } // 0xC NBFPEPPMNGF KMCBNOABKEC JLJEGLHIHHK
	public static MDFCHKPOMAJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x130F5FC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LBAGNFKGHIB res_readData = LBAGNFKGHIB.GetRootAsLBAGNFKGHIB(buffer);
		MDFCHKPOMAJ res_data = new MDFCHKPOMAJ();

		List<PLCJIGFCOIK> GKBBBINCAGN_list = new List<PLCJIGFCOIK>();
		for(int GKBBBINCAGN_idx = 0; GKBBBINCAGN_idx < res_readData.CNOBKOPJGPLLength; GKBBBINCAGN_idx++)
		{
			AAHHDFJLDIO GKBBBINCAGN_readData = res_readData.GetCNOBKOPJGPL(GKBBBINCAGN_idx);
			PLCJIGFCOIK GKBBBINCAGN_data = new PLCJIGFCOIK();

			GKBBBINCAGN_data.PPFNGGCBJKC = GKBBBINCAGN_readData.BBPHAPFBFHK;
			GKBBBINCAGN_data.OPFGFINHFCE = GKBBBINCAGN_readData.IIDCFMHCPLJ;
			GKBBBINCAGN_data.CPGFOBNKKBF = GKBBBINCAGN_readData.DKMLEDJJFOI;
			GKBBBINCAGN_data.PFAOBLDNMGF = GKBBBINCAGN_readData.GHHPIICJHDB;
			GKBBBINCAGN_data.PDHGIGPAEBG = GKBBBINCAGN_readData.IJKHPPCHPGK;
			GKBBBINCAGN_data.BFINGCJHOHI = GKBBBINCAGN_readData.CLEEFGNMCEL;
			GKBBBINCAGN_data.GBJFNGCDKPM = GKBBBINCAGN_readData.LPJPOOHJKAE;
			GKBBBINCAGN_data.PDBPFJJCADD = GKBBBINCAGN_readData.NJLJEKDBPCH;
			GKBBBINCAGN_data.EGBOHDFBAPB = GKBBBINCAGN_readData.IPHMJNCEPIJ;
			GKBBBINCAGN_data.HPGNBPIBAOM = GKBBBINCAGN_readData.JBAHJKKJPEG;
			GKBBBINCAGN_data.AFHPLBPHEGA = GKBBBINCAGN_readData.OIMEOBNAAHH;
			GKBBBINCAGN_data.HEOLEHDFLJO = GKBBBINCAGN_readData.EOHDEKFEONI;
			GKBBBINCAGN_data.KLMPFGOCBHC = GKBBBINCAGN_readData.LCMOIMEFAHI;
			GKBBBINCAGN_data.DLCGAMHADEN = GKBBBINCAGN_readData.PELKLPGCMFN;
			List<int> KGOFMDMDFCJ_list = new List<int>();
			for(int KGOFMDMDFCJ_idx = 0; KGOFMDMDFCJ_idx < GKBBBINCAGN_readData.IDKJOALBKAALength; KGOFMDMDFCJ_idx++)
			{
				KGOFMDMDFCJ_list.Add(GKBBBINCAGN_readData.GetIDKJOALBKAA(KGOFMDMDFCJ_idx));
			}
			GKBBBINCAGN_data.KGOFMDMDFCJ = KGOFMDMDFCJ_list.ToArray();

			List<int> NNIIINKFDBG_list = new List<int>();
			for(int NNIIINKFDBG_idx = 0; NNIIINKFDBG_idx < GKBBBINCAGN_readData.AFDJJJOJBMOLength; NNIIINKFDBG_idx++)
			{
				NNIIINKFDBG_list.Add(GKBBBINCAGN_readData.GetAFDJJJOJBMO(NNIIINKFDBG_idx));
			}
			GKBBBINCAGN_data.NNIIINKFDBG = NNIIINKFDBG_list.ToArray();

			GKBBBINCAGN_data.IHCLFMKAJND = GKBBBINCAGN_readData.MCPMLMHKKOP;
			GKBBBINCAGN_data.EILKGEADKGH = GKBBBINCAGN_readData.BPMBFFDNMDD;
			GKBBBINCAGN_list.Add(GKBBBINCAGN_data);
		}
		res_data.GKBBBINCAGN = GKBBBINCAGN_list.ToArray();

		List<EGHGEIALECF> CMFJFBJHKPE_list = new List<EGHGEIALECF>();
		for(int CMFJFBJHKPE_idx = 0; CMFJFBJHKPE_idx < res_readData.MDOIDBIGFJILength; CMFJFBJHKPE_idx++)
		{
			LFDPEDHPEKC CMFJFBJHKPE_readData = res_readData.GetMDOIDBIGFJI(CMFJFBJHKPE_idx);
			EGHGEIALECF CMFJFBJHKPE_data = new EGHGEIALECF();

			CMFJFBJHKPE_data.PPFNGGCBJKC = CMFJFBJHKPE_readData.BBPHAPFBFHK;
			CMFJFBJHKPE_data.PLALNIIBLOF = CMFJFBJHKPE_readData.CFLMCGOJJJD;
			CMFJFBJHKPE_data.FEMMDNIELFC = CMFJFBJHKPE_readData.NNKLANONDOM;
			CMFJFBJHKPE_data.PDBPFJJCADD = CMFJFBJHKPE_readData.NJLJEKDBPCH;
			CMFJFBJHKPE_data.EGBOHDFBAPB = CMFJFBJHKPE_readData.IPHMJNCEPIJ;
			CMFJFBJHKPE_data.KAPMOPMDHJE = CMFJFBJHKPE_readData.BNFLNMGOJCM;
			CMFJFBJHKPE_list.Add(CMFJFBJHKPE_data);
		}
		res_data.CMFJFBJHKPE = CMFJFBJHKPE_list.ToArray();

		return res_data;
	}
}
