using FlatBuffers;
using System.Collections.Generic;

public class PLCJIGFCOIK
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE_name { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int CPGFOBNKKBF_CurrencyId { get; set; } // 0x10 CIAEKFDKLJB AMNKHCIJHJD INJMDACNFOL
	public string PFAOBLDNMGF { get; set; } // 0x14 DFHKMMADKJK EGIONHIJBIJ OBIJPLJHIIM
	public string PDHGIGPAEBG { get; set; } // 0x18 HCBCLJEGFKJ JEDAGPENDIG HPDKOCKJHPK
	public int BFINGCJHOHI_cnt { get; set; } // 0x1C PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public int GBJFNGCDKPM_typ { get; set; } // 0x20 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int PDBPFJJCADD_open_at { get; set; } // 0x24 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int EGBOHDFBAPB_closed_at { get; set; } // 0x28 DDNBDNJHAIB MGOEKKJNOLF NHPFDCAFAFF
	public int HPGNBPIBAOM_IsBeginner { get; set; } // 0x2C BMEHEHGDBEL CNGGNJIILPC KINBLEJIELP
	public int AFHPLBPHEGA { get; set; } // 0x30 MEPFNKKKPHP INHKANPGKOO MJDENHCKCOE
	public int HEOLEHDFLJO_ico { get; set; } // 0x34 EALEFNJMEPK OICOCHBFNAK HGLFJJHECGH
	public string KLMPFGOCBHC_description { get; set; } // 0x38 MODIAAEGMCJ BGJNIABLBDB HFBJLALGKOM
	public int DLCGAMHADEN_Label { get; set; } // 0x3C ANDDAFHKOPK BNGHEBJEOPL PBMMAJFCPJL
	public int[] KGOFMDMDFCJ_BonusId { get; set; } // 0x40 DODJFJLJPIE NPEIPAKLPPG CCMIKCFIDEM
	public int[] NNIIINKFDBG_BonusCount { get; set; } // 0x44 BGNHEGBJBFI JJCMDBOMGGE BEJCKOIHNPK
	public int IHCLFMKAJND { get; set; } // 0x48 HHENDIIFCBD MJKPAAFNENM LNMLLJLJFKN
	public int EILKGEADKGH_Order { get; set; } // 0x4C PBIPJHCABED NPDDACIHBKD BJJMCKHBPNH
}
public class EGHGEIALECF
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string FEMMDNIELFC_Desc { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public int PDBPFJJCADD_open_at { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int EGBOHDFBAPB_closed_at { get; set; } // 0x18 DDNBDNJHAIB MGOEKKJNOLF NHPFDCAFAFF
	public int KAPMOPMDHJE_label { get; set; } // 0x1C EJDCHACDMPH MONBNPKLFGC KGFFKEDNIID
}
public class MDFCHKPOMAJ
{
	public PLCJIGFCOIK[] GKBBBINCAGN { get; set; } // 0x8 FPAGOGOKEJK LNIEKMGPGDO FPJMNEDPCHG
	public EGHGEIALECF[] CMFJFBJHKPE { get; set; } // 0xC NBFPEPPMNGF KMCBNOABKEC JLJEGLHIHHK
	public static MDFCHKPOMAJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x130F5FC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LBAGNFKGHIB res_readData = LBAGNFKGHIB.GetRootAsLBAGNFKGHIB(buffer);
		MDFCHKPOMAJ res_data = new MDFCHKPOMAJ();

		List<PLCJIGFCOIK> GKBBBINCAGN_list = new List<PLCJIGFCOIK>();
		for(int GKBBBINCAGN_idx = 0; GKBBBINCAGN_idx < res_readData.CNOBKOPJGPLLength; GKBBBINCAGN_idx++)
		{
			AAHHDFJLDIO GKBBBINCAGN_readData = res_readData.GetCNOBKOPJGPL(GKBBBINCAGN_idx);
			PLCJIGFCOIK GKBBBINCAGN_data = new PLCJIGFCOIK();

			GKBBBINCAGN_data.PPFNGGCBJKC_id = GKBBBINCAGN_readData.BBPHAPFBFHK;
			GKBBBINCAGN_data.OPFGFINHFCE_name = GKBBBINCAGN_readData.IIDCFMHCPLJ;
			GKBBBINCAGN_data.CPGFOBNKKBF_CurrencyId = GKBBBINCAGN_readData.DKMLEDJJFOI;
			GKBBBINCAGN_data.PFAOBLDNMGF = GKBBBINCAGN_readData.GHHPIICJHDB;
			GKBBBINCAGN_data.PDHGIGPAEBG = GKBBBINCAGN_readData.IJKHPPCHPGK;
			GKBBBINCAGN_data.BFINGCJHOHI_cnt = GKBBBINCAGN_readData.CLEEFGNMCEL;
			GKBBBINCAGN_data.GBJFNGCDKPM_typ = GKBBBINCAGN_readData.LPJPOOHJKAE;
			GKBBBINCAGN_data.PDBPFJJCADD_open_at = GKBBBINCAGN_readData.NJLJEKDBPCH;
			GKBBBINCAGN_data.EGBOHDFBAPB_closed_at = GKBBBINCAGN_readData.IPHMJNCEPIJ;
			GKBBBINCAGN_data.HPGNBPIBAOM_IsBeginner = GKBBBINCAGN_readData.JBAHJKKJPEG;
			GKBBBINCAGN_data.AFHPLBPHEGA = GKBBBINCAGN_readData.OIMEOBNAAHH;
			GKBBBINCAGN_data.HEOLEHDFLJO_ico = GKBBBINCAGN_readData.EOHDEKFEONI;
			GKBBBINCAGN_data.KLMPFGOCBHC_description = GKBBBINCAGN_readData.LCMOIMEFAHI;
			GKBBBINCAGN_data.DLCGAMHADEN_Label = GKBBBINCAGN_readData.PELKLPGCMFN;
			List<int> KGOFMDMDFCJ_list = new List<int>();
			for(int KGOFMDMDFCJ_idx = 0; KGOFMDMDFCJ_idx < GKBBBINCAGN_readData.IDKJOALBKAALength; KGOFMDMDFCJ_idx++)
			{
				KGOFMDMDFCJ_list.Add(GKBBBINCAGN_readData.GetIDKJOALBKAA(KGOFMDMDFCJ_idx));
			}
			GKBBBINCAGN_data.KGOFMDMDFCJ_BonusId = KGOFMDMDFCJ_list.ToArray();

			List<int> NNIIINKFDBG_list = new List<int>();
			for(int NNIIINKFDBG_idx = 0; NNIIINKFDBG_idx < GKBBBINCAGN_readData.AFDJJJOJBMOLength; NNIIINKFDBG_idx++)
			{
				NNIIINKFDBG_list.Add(GKBBBINCAGN_readData.GetAFDJJJOJBMO(NNIIINKFDBG_idx));
			}
			GKBBBINCAGN_data.NNIIINKFDBG_BonusCount = NNIIINKFDBG_list.ToArray();

			GKBBBINCAGN_data.IHCLFMKAJND = GKBBBINCAGN_readData.MCPMLMHKKOP;
			GKBBBINCAGN_data.EILKGEADKGH_Order = GKBBBINCAGN_readData.BPMBFFDNMDD;
			GKBBBINCAGN_list.Add(GKBBBINCAGN_data);
		}
		res_data.GKBBBINCAGN = GKBBBINCAGN_list.ToArray();

		List<EGHGEIALECF> CMFJFBJHKPE_list = new List<EGHGEIALECF>();
		for(int CMFJFBJHKPE_idx = 0; CMFJFBJHKPE_idx < res_readData.MDOIDBIGFJILength; CMFJFBJHKPE_idx++)
		{
			LFDPEDHPEKC CMFJFBJHKPE_readData = res_readData.GetMDOIDBIGFJI(CMFJFBJHKPE_idx);
			EGHGEIALECF CMFJFBJHKPE_data = new EGHGEIALECF();

			CMFJFBJHKPE_data.PPFNGGCBJKC_id = CMFJFBJHKPE_readData.BBPHAPFBFHK;
			CMFJFBJHKPE_data.PLALNIIBLOF_en = CMFJFBJHKPE_readData.CFLMCGOJJJD;
			CMFJFBJHKPE_data.FEMMDNIELFC_Desc = CMFJFBJHKPE_readData.NNKLANONDOM;
			CMFJFBJHKPE_data.PDBPFJJCADD_open_at = CMFJFBJHKPE_readData.NJLJEKDBPCH;
			CMFJFBJHKPE_data.EGBOHDFBAPB_closed_at = CMFJFBJHKPE_readData.IPHMJNCEPIJ;
			CMFJFBJHKPE_data.KAPMOPMDHJE_label = CMFJFBJHKPE_readData.BNFLNMGOJCM;
			CMFJFBJHKPE_list.Add(CMFJFBJHKPE_data);
		}
		res_data.CMFJFBJHKPE = CMFJFBJHKPE_list.ToArray();

		return res_data;
	}
}
