using FlatBuffers;
using System.Collections.Generic;

public class DDHCKMFAKFA
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int FBFLDFMFFOH_rar { get; set; } // 0x14 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int MLMCEBBDJOE { get; set; } // 0x18 LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x1C LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK_price { get; set; } // 0x20 JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
	public int[] PIPDCAEIBPO { get; set; } // 0x24 MDOGGIFJDBA MIOJEAKDNKO OBPFGNALDKP
	public int KEJMJPHFFOJ_Max { get; set; } // 0x28 NNGEOJMHAEA FMNMLNIALNE GBEPCBPOGDB
	public int CPKMLLNADLJ_Serie { get; set; } // 0x2C COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
}
public class MDMEBHPAKIH
{
	public DDHCKMFAKFA[] NFBMFDPFHCL { get; set; } // 0x8 HDEEHBKLIOD DANCLHPKEMO OIPCINELDBO
	public static MDMEBHPAKIH HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x13100F0
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JBMPGMCNGNP res_readData = JBMPGMCNGNP.GetRootAsJBMPGMCNGNP(buffer);
		MDMEBHPAKIH res_data = new MDMEBHPAKIH();

		List<DDHCKMFAKFA> NFBMFDPFHCL_list = new List<DDHCKMFAKFA>();
		for(int NFBMFDPFHCL_idx = 0; NFBMFDPFHCL_idx < res_readData.OKEBOFCGHGDLength; NFBMFDPFHCL_idx++)
		{
			CKGLLPFMEDH NFBMFDPFHCL_readData = res_readData.GetOKEBOFCGHGD(NFBMFDPFHCL_idx);
			DDHCKMFAKFA NFBMFDPFHCL_data = new DDHCKMFAKFA();

			NFBMFDPFHCL_data.PPFNGGCBJKC_id = NFBMFDPFHCL_readData.BBPHAPFBFHK;
			NFBMFDPFHCL_data.IJEKNCDIIAE_mver = NFBMFDPFHCL_readData.OFMGALJGDAO;
			NFBMFDPFHCL_data.PLALNIIBLOF_en = NFBMFDPFHCL_readData.CFLMCGOJJJD;
			NFBMFDPFHCL_data.FBFLDFMFFOH_rar = NFBMFDPFHCL_readData.ODBPKGJPLMD;
			NFBMFDPFHCL_data.MLMCEBBDJOE = NFBMFDPFHCL_readData.JHAMBKOEJPL;
			NFBMFDPFHCL_data.ODNILEDOAIP = NFBMFDPFHCL_readData.MJHPFNPCLBD;
			NFBMFDPFHCL_data.NPPGKNGIFGK_price = NFBMFDPFHCL_readData.JDKBBEIBJBD;
			List<int> PIPDCAEIBPO_list = new List<int>();
			for(int PIPDCAEIBPO_idx = 0; PIPDCAEIBPO_idx < NFBMFDPFHCL_readData.CGHIJPPACBCLength; PIPDCAEIBPO_idx++)
			{
				PIPDCAEIBPO_list.Add(NFBMFDPFHCL_readData.GetCGHIJPPACBC(PIPDCAEIBPO_idx));
			}
			NFBMFDPFHCL_data.PIPDCAEIBPO = PIPDCAEIBPO_list.ToArray();

			NFBMFDPFHCL_data.KEJMJPHFFOJ_Max = NFBMFDPFHCL_readData.HMNFFFLCANH;
			NFBMFDPFHCL_data.CPKMLLNADLJ_Serie = NFBMFDPFHCL_readData.LMLNKHMPOIG;
			NFBMFDPFHCL_list.Add(NFBMFDPFHCL_data);
		}
		res_data.NFBMFDPFHCL = NFBMFDPFHCL_list.ToArray();

		return res_data;
	}
}
