using FlatBuffers;
using System.Collections.Generic;

public class ILCNBIAEIFB
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint BDJMFDKLHPM_s_id { get; set; } // 0x10 EOBCNECIOMH GFMBGPMJPLJ ENAMMCHJBDE
	public uint OCAMDLMPBGA_dv { get; set; } // 0x14 JKDMAFHPKDJ DHOGDENEIOI DBDFNFLGDFN
	public uint CEKKIGJHMDH { get; set; } // 0x18 HCNFHGLLDEG HLNCBLBDANO JFAGGENCMCI
	public uint AKEFCAFBFKJ_clv { get; set; } // 0x1C HMEFJMIBONM ILAGFIGNAIJ ACOFICGMCFO
	public uint EPBBNFDFLLD_or { get; set; } // 0x20 NPFHGPKKHIM BLGGFAKCGDK FMMOBHNGGCF
	public uint ILJEIMNCKME_cf_id { get; set; } // 0x24 NDGNFIAKHKN JNKBIGPEPNJ LAAEELACMFF
	public uint NPHJIIHDEDD_cdf { get; set; } // 0x28 NHKIHHLADHO ECKDCEECIBE BPMKGNFEHPC
	public uint LPADGFJPFDN { get; set; } // 0x2C LJGFJDABFGL IGKDGLPNIIP KFBOGIKKEGM
	public uint EHDDADDKMFI_f_id { get; set; } // 0x30 MCAKELLLNIO IFFJALDBDDI LMLHCMMIEJH
	public uint NHBLDIPBHNF_pg { get; set; } // 0x34 HEJBEEJPNPG HOMBHFADDNG FIEMLIDBMID
	public uint EOOCLKKJHLK { get; set; } // 0x38 MDFJCBNPFMF CDGGBBFFOND CEAKAJILBOG
	public int IJEKNCDIIAE_mver { get; set; } // 0x3C FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
public class MEPHNDCDFFJ
{
	public ILCNBIAEIFB[] PEJOABFFHHA { get; set; } // 0x8 BIKBPGHAIAB GLNDKIEHINH ICACJPGBGFI
	public static MEPHNDCDFFJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1311EFC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		PLONLLOGMEJ res_readData = PLONLLOGMEJ.GetRootAsPLONLLOGMEJ(buffer);
		MEPHNDCDFFJ res_data = new MEPHNDCDFFJ();

		List<ILCNBIAEIFB> PEJOABFFHHA_list = new List<ILCNBIAEIFB>();
		for(int PEJOABFFHHA_idx = 0; PEJOABFFHHA_idx < res_readData.JEEPKOLPINELength; PEJOABFFHHA_idx++)
		{
			GEGKPJCPNJE PEJOABFFHHA_readData = res_readData.GetJEEPKOLPINE(PEJOABFFHHA_idx);
			ILCNBIAEIFB PEJOABFFHHA_data = new ILCNBIAEIFB();

			PEJOABFFHHA_data.PPFNGGCBJKC_id = PEJOABFFHHA_readData.BBPHAPFBFHK;
			PEJOABFFHHA_data.PLALNIIBLOF_en = PEJOABFFHHA_readData.CFLMCGOJJJD;
			PEJOABFFHHA_data.BDJMFDKLHPM_s_id = PEJOABFFHHA_readData.MJOCIHPPKNO;
			PEJOABFFHHA_data.OCAMDLMPBGA_dv = PEJOABFFHHA_readData.DDMBKEJNPJK;
			PEJOABFFHHA_data.CEKKIGJHMDH = PEJOABFFHHA_readData.ACNNNALNEFM;
			PEJOABFFHHA_data.AKEFCAFBFKJ_clv = PEJOABFFHHA_readData.LOOGFGKLHGK;
			PEJOABFFHHA_data.EPBBNFDFLLD_or = PEJOABFFHHA_readData.HAMMBHGLKML;
			PEJOABFFHHA_data.ILJEIMNCKME_cf_id = PEJOABFFHHA_readData.KALCKCHDIDB;
			PEJOABFFHHA_data.NPHJIIHDEDD_cdf = PEJOABFFHHA_readData.KANIHFOMCKI;
			PEJOABFFHHA_data.LPADGFJPFDN = PEJOABFFHHA_readData.GBGHHKPDHOH;
			PEJOABFFHHA_data.EHDDADDKMFI_f_id = PEJOABFFHHA_readData.NAJHJIHCOON;
			PEJOABFFHHA_data.NHBLDIPBHNF_pg = PEJOABFFHHA_readData.LNCMMHCDOJE;
			PEJOABFFHHA_data.EOOCLKKJHLK = PEJOABFFHHA_readData.FOMMMCHNLPL;
			PEJOABFFHHA_data.IJEKNCDIIAE_mver = PEJOABFFHHA_readData.OFMGALJGDAO;
			PEJOABFFHHA_list.Add(PEJOABFFHHA_data);
		}
		res_data.PEJOABFFHHA = PEJOABFFHHA_list.ToArray();

		return res_data;
	}
}
