using FlatBuffers;
using System.Collections.Generic;

public class NNMHEHIOKGF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string FEMMDNIELFC_Desc { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint GMELAKNFKMG { get; set; } // 0x14 NBIGNIFKHLH GNIIGNBNAJF DNGBCJOKLND
	public string PIBLLGLCJEO_Param { get; set; } // 0x18 KGLJBJIIAEG CMKMAGNMPGC CICCOMMMNHK
	public uint OFMECFHNCHA_Popup { get; set; } // 0x1C DFMLABEHMKI OCBFEBBDDFI BMFCGGIPJDL
	public uint JOPPFEHKNFO_Pickup { get; set; } // 0x20 LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
	public uint PDBPFJJCADD_open_at { get; set; } // 0x24 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x28 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public uint DAPGDCPDCNA_Prio { get; set; } // 0x2C AIEPLCMPKAN GFAHOLGECII KJKCIHEDEBB
	public uint KNHOMNONOEB_AssetId { get; set; } // 0x30 EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
	public uint ODOAFNMJIMA { get; set; } // 0x34 FDPEIFCPCPD GGOLPHFOEAJ FKMPBPDOBIO
	public uint ADHCKHFANAL { get; set; } // 0x38 MODHJDMMONO LPICEPPJOMO EHJIKIJEILL
	public string AOBNHHIIJBO { get; set; } // 0x3C LHHNHCJDAEC JGFPKPOOAJH NOPEKIPBLDK
	public int IJEKNCDIIAE_mver { get; set; } // 0x40 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int KGICDMIJGDF_Group { get; set; } // 0x44 LHIOCOLMMNP ENACPBCEBLF KPCDPMGBPAG
	public int JPKPDCCGGLA { get; set; } // 0x48 OJCHAPPGEAI KMHGMKABEAE PCFICMIDNGC
	public int AMKJDECHIOF { get; set; } // 0x4C ICNHEJHCAKL CFKKLJPHGJL BNAMIEALHOB
	public uint KLHGOPBIOCN { get; set; } // 0x50 KAOLNDOBBGG PGEKHCMFGAB INPFJDENBAC
}
public class EIGKPFPCGJK
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int KLCMKLPIDDJ_Month { get; set; } // 0x14 LBNFMGNGCDA FKGAMFACFKO MHLPBOBOFJA
	public int BAOFEFFADPD_day { get; set; } // 0x18 MNBJKHKHMCL KHNONKOPIPO LBJPPBMDOGE
	public int KNHOMNONOEB_AssetId { get; set; } // 0x1C EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
	public string AOBNHHIIJBO { get; set; } // 0x20 LHHNHCJDAEC JGFPKPOOAJH NOPEKIPBLDK
}
public class OAPCAAGKGPP
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int CCPECDBPFCJ { get; set; } // 0x14 KFKMFOOLGHL AALOFMLBJJG MJNKKKHHMGF
	public int GBJFNGCDKPM_typ { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int JOFAGCFNKIO_OpenTime { get; set; } // 0x1C JCDBGAIOGFK JDJIHKNFDLG JNKGBAPAGOB
	public int EBCHFBIINDP_End { get; set; } // 0x20 LAAJBPDLLCP LHAMEHALKDB DHAPDOLCLHO
	public int KNHOMNONOEB_AssetId { get; set; } // 0x24 EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
	public string AOBNHHIIJBO { get; set; } // 0x28 LHHNHCJDAEC JGFPKPOOAJH NOPEKIPBLDK
}
public class MFNEHMPBDKK
{
	public NNMHEHIOKGF[] AGMBMGJAKFJ { get; set; } // 0x8 LFLHLNJAMOK IKAJPPHFGLL BNEKFKKOBPN
	public EIGKPFPCGJK[] PCKGJKCOPEB { get; set; } // 0xC MELDJIIFEHG ADLKHPDKOMM HNOBGAPBEAE
	public OAPCAAGKGPP[] KMGFICHGDGE { get; set; } // 0x10 OBMEBONLEBC FOPAMJKPKBG EBGAHIMDBGH
	public static MFNEHMPBDKK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1315770
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		KIPJDHHEGND res_readData = KIPJDHHEGND.GetRootAsKIPJDHHEGND(buffer);
		MFNEHMPBDKK res_data = new MFNEHMPBDKK();

		List<NNMHEHIOKGF> AGMBMGJAKFJ_list = new List<NNMHEHIOKGF>();
		for(int AGMBMGJAKFJ_idx = 0; AGMBMGJAKFJ_idx < res_readData.NFAJGFHLKGILength; AGMBMGJAKFJ_idx++)
		{
			GGALCNFLIBP AGMBMGJAKFJ_readData = res_readData.GetNFAJGFHLKGI(AGMBMGJAKFJ_idx);
			NNMHEHIOKGF AGMBMGJAKFJ_data = new NNMHEHIOKGF();

			AGMBMGJAKFJ_data.PPFNGGCBJKC_id = AGMBMGJAKFJ_readData.BBPHAPFBFHK;
			AGMBMGJAKFJ_data.PLALNIIBLOF_en = AGMBMGJAKFJ_readData.CFLMCGOJJJD;
			AGMBMGJAKFJ_data.FEMMDNIELFC_Desc = AGMBMGJAKFJ_readData.NNKLANONDOM;
			AGMBMGJAKFJ_data.GMELAKNFKMG = AGMBMGJAKFJ_readData.NBMJDIEAMAB;
			AGMBMGJAKFJ_data.PIBLLGLCJEO_Param = AGMBMGJAKFJ_readData.GMMOOPMEKKG;
			AGMBMGJAKFJ_data.OFMECFHNCHA_Popup = AGMBMGJAKFJ_readData.KGOFDIKBIHE;
			AGMBMGJAKFJ_data.JOPPFEHKNFO_Pickup = AGMBMGJAKFJ_readData.ALPALMJMJJK;
			AGMBMGJAKFJ_data.PDBPFJJCADD_open_at = AGMBMGJAKFJ_readData.NJLJEKDBPCH;
			AGMBMGJAKFJ_data.FDBNFFNFOND_close_at = AGMBMGJAKFJ_readData.MAOAGDBDBIB;
			AGMBMGJAKFJ_data.DAPGDCPDCNA_Prio = AGMBMGJAKFJ_readData.AIIPAPCLGGO;
			AGMBMGJAKFJ_data.KNHOMNONOEB_AssetId = AGMBMGJAKFJ_readData.NCADHENBLDB;
			AGMBMGJAKFJ_data.ODOAFNMJIMA = AGMBMGJAKFJ_readData.NFAOINKHBIG;
			AGMBMGJAKFJ_data.ADHCKHFANAL = AGMBMGJAKFJ_readData.PMEGAJICHMB;
			AGMBMGJAKFJ_data.AOBNHHIIJBO = AGMBMGJAKFJ_readData.DKAFKOABCJA;
			AGMBMGJAKFJ_data.IJEKNCDIIAE_mver = AGMBMGJAKFJ_readData.OFMGALJGDAO;
			AGMBMGJAKFJ_data.KGICDMIJGDF_Group = AGMBMGJAKFJ_readData.PEGBGEGKCGA;
			AGMBMGJAKFJ_data.JPKPDCCGGLA = AGMBMGJAKFJ_readData.GOOHAMCBHAE;
			AGMBMGJAKFJ_data.AMKJDECHIOF = AGMBMGJAKFJ_readData.LECDAEGCIMH;
			AGMBMGJAKFJ_data.KLHGOPBIOCN = AGMBMGJAKFJ_readData.PMFELBFGCJG;
			AGMBMGJAKFJ_list.Add(AGMBMGJAKFJ_data);
		}
		res_data.AGMBMGJAKFJ = AGMBMGJAKFJ_list.ToArray();

		List<EIGKPFPCGJK> PCKGJKCOPEB_list = new List<EIGKPFPCGJK>();
		for(int PCKGJKCOPEB_idx = 0; PCKGJKCOPEB_idx < res_readData.ONGHLNCPCMILength; PCKGJKCOPEB_idx++)
		{
			JIHBJPCAEMH PCKGJKCOPEB_readData = res_readData.GetONGHLNCPCMI(PCKGJKCOPEB_idx);
			EIGKPFPCGJK PCKGJKCOPEB_data = new EIGKPFPCGJK();

			PCKGJKCOPEB_data.PPFNGGCBJKC_id = PCKGJKCOPEB_readData.BBPHAPFBFHK;
			PCKGJKCOPEB_data.IJEKNCDIIAE_mver = PCKGJKCOPEB_readData.OFMGALJGDAO;
			PCKGJKCOPEB_data.PLALNIIBLOF_en = PCKGJKCOPEB_readData.CFLMCGOJJJD;
			PCKGJKCOPEB_data.KLCMKLPIDDJ_Month = PCKGJKCOPEB_readData.IALIGIAJJGP;
			PCKGJKCOPEB_data.BAOFEFFADPD_day = PCKGJKCOPEB_readData.FKGLOPMFMCP;
			PCKGJKCOPEB_data.KNHOMNONOEB_AssetId = PCKGJKCOPEB_readData.NCADHENBLDB;
			PCKGJKCOPEB_data.AOBNHHIIJBO = PCKGJKCOPEB_readData.DKAFKOABCJA;
			PCKGJKCOPEB_list.Add(PCKGJKCOPEB_data);
		}
		res_data.PCKGJKCOPEB = PCKGJKCOPEB_list.ToArray();

		List<OAPCAAGKGPP> KMGFICHGDGE_list = new List<OAPCAAGKGPP>();
		for(int KMGFICHGDGE_idx = 0; KMGFICHGDGE_idx < res_readData.OGCIHPPJHMGLength; KMGFICHGDGE_idx++)
		{
			JEFGONAHEGI KMGFICHGDGE_readData = res_readData.GetOGCIHPPJHMG(KMGFICHGDGE_idx);
			OAPCAAGKGPP KMGFICHGDGE_data = new OAPCAAGKGPP();

			KMGFICHGDGE_data.PPFNGGCBJKC_id = KMGFICHGDGE_readData.BBPHAPFBFHK;
			KMGFICHGDGE_data.IJEKNCDIIAE_mver = KMGFICHGDGE_readData.OFMGALJGDAO;
			KMGFICHGDGE_data.PLALNIIBLOF_en = KMGFICHGDGE_readData.CFLMCGOJJJD;
			KMGFICHGDGE_data.CCPECDBPFCJ = KMGFICHGDGE_readData.GONOGEBKNLE;
			KMGFICHGDGE_data.GBJFNGCDKPM_typ = KMGFICHGDGE_readData.LPJPOOHJKAE;
			KMGFICHGDGE_data.JOFAGCFNKIO_OpenTime = KMGFICHGDGE_readData.EBLEOMJJDMC;
			KMGFICHGDGE_data.EBCHFBIINDP_End = KMGFICHGDGE_readData.GKPLGGIHHBJ;
			KMGFICHGDGE_data.KNHOMNONOEB_AssetId = KMGFICHGDGE_readData.NCADHENBLDB;
			KMGFICHGDGE_data.AOBNHHIIJBO = KMGFICHGDGE_readData.DKAFKOABCJA;
			KMGFICHGDGE_list.Add(KMGFICHGDGE_data);
		}
		res_data.KMGFICHGDGE = KMGFICHGDGE_list.ToArray();

		return res_data;
	}
}
