using FlatBuffers;
using System.Collections.Generic;

public class NNMHEHIOKGF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public string FEMMDNIELFC_Desc { get; set; } // 0x10 GDKPKLJELJK JDHDMBHNKJD_get_Desc FNAJEJLLJOE_set_Desc
	public uint GMELAKNFKMG { get; set; } // 0x14 NBIGNIFKHLH GNIIGNBNAJF_get_ DNGBCJOKLND_set_
	public string PIBLLGLCJEO_Param { get; set; } // 0x18 KGLJBJIIAEG CMKMAGNMPGC_get_Param CICCOMMMNHK_set_Param
	public uint OFMECFHNCHA_Popup { get; set; } // 0x1C DFMLABEHMKI OCBFEBBDDFI_get_Popup BMFCGGIPJDL_set_Popup
	public uint JOPPFEHKNFO_Pickup { get; set; } // 0x20 LLNLOLIOPBO FNIOGOJFLMG_get_Pickup AJIOKKIJBED_set_Pickup
	public uint PDBPFJJCADD_open_at { get; set; } // 0x24 PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public uint FDBNFFNFOND_close_at { get; set; } // 0x28 INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
	public uint DAPGDCPDCNA_Prio { get; set; } // 0x2C AIEPLCMPKAN GFAHOLGECII_get_Prio KJKCIHEDEBB_set_Prio
	public uint KNHOMNONOEB_AssetId { get; set; } // 0x30 EJNCFCPHDML NECFMEFKKPH_get_AssetId MHNEFLJACHA_set_AssetId
	public uint ODOAFNMJIMA { get; set; } // 0x34 FDPEIFCPCPD GGOLPHFOEAJ_get_ FKMPBPDOBIO_set_
	public uint ADHCKHFANAL { get; set; } // 0x38 MODHJDMMONO LPICEPPJOMO_get_ EHJIKIJEILL_set_
	public string AOBNHHIIJBO { get; set; } // 0x3C LHHNHCJDAEC JGFPKPOOAJH_get_ NOPEKIPBLDK_set_
	public int IJEKNCDIIAE_mver { get; set; } // 0x40 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int KGICDMIJGDF_Group { get; set; } // 0x44 LHIOCOLMMNP ENACPBCEBLF_get_Group KPCDPMGBPAG_set_Group
	public int JPKPDCCGGLA { get; set; } // 0x48 OJCHAPPGEAI KMHGMKABEAE_get_ PCFICMIDNGC_set_
	public int AMKJDECHIOF { get; set; } // 0x4C ICNHEJHCAKL CFKKLJPHGJL_get_ BNAMIEALHOB_set_
	public uint KLHGOPBIOCN { get; set; } // 0x50 KAOLNDOBBGG PGEKHCMFGAB_get_ INPFJDENBAC_set_
}
public class EIGKPFPCGJK
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int KLCMKLPIDDJ_Month { get; set; } // 0x14 LBNFMGNGCDA FKGAMFACFKO_get_Month MHLPBOBOFJA_set_Month
	public int BAOFEFFADPD_day { get; set; } // 0x18 MNBJKHKHMCL KHNONKOPIPO_get_day LBJPPBMDOGE_set_day
	public int KNHOMNONOEB_AssetId { get; set; } // 0x1C EJNCFCPHDML NECFMEFKKPH_get_AssetId MHNEFLJACHA_set_AssetId
	public string AOBNHHIIJBO { get; set; } // 0x20 LHHNHCJDAEC JGFPKPOOAJH_get_ NOPEKIPBLDK_set_
}
public class OAPCAAGKGPP
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int CCPECDBPFCJ { get; set; } // 0x14 KFKMFOOLGHL AALOFMLBJJG_get_ MJNKKKHHMGF_set_
	public int GBJFNGCDKPM_typ { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public int JOFAGCFNKIO_OpenTime { get; set; } // 0x1C JCDBGAIOGFK JDJIHKNFDLG_get_OpenTime JNKGBAPAGOB_set_OpenTime
	public int EBCHFBIINDP_End { get; set; } // 0x20 LAAJBPDLLCP LHAMEHALKDB_get_End DHAPDOLCLHO_set_End
	public int KNHOMNONOEB_AssetId { get; set; } // 0x24 EJNCFCPHDML NECFMEFKKPH_get_AssetId MHNEFLJACHA_set_AssetId
	public string AOBNHHIIJBO { get; set; } // 0x28 LHHNHCJDAEC JGFPKPOOAJH_get_ NOPEKIPBLDK_set_
}
public class MFNEHMPBDKK
{
	public NNMHEHIOKGF[] AGMBMGJAKFJ { get; set; } // 0x8 LFLHLNJAMOK IKAJPPHFGLL_get_ BNEKFKKOBPN_set_
	public EIGKPFPCGJK[] PCKGJKCOPEB { get; set; } // 0xC MELDJIIFEHG ADLKHPDKOMM_get_ HNOBGAPBEAE_set_
	public OAPCAAGKGPP[] KMGFICHGDGE { get; set; } // 0x10 OBMEBONLEBC FOPAMJKPKBG_get_ EBGAHIMDBGH_set_
	public static MFNEHMPBDKK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1315770
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		KIPJDHHEGND res_readData_ = KIPJDHHEGND.GetRootAsKIPJDHHEGND(buffer);
		MFNEHMPBDKK res_data_ = new MFNEHMPBDKK();

		List<NNMHEHIOKGF> AGMBMGJAKFJ_list_ = new List<NNMHEHIOKGF>();
		for(int AGMBMGJAKFJ_idx_ = 0; AGMBMGJAKFJ_idx_ < res_readData_.NFAJGFHLKGILength; AGMBMGJAKFJ_idx_++)
		{
			GGALCNFLIBP AGMBMGJAKFJ_readData_ = res_readData_.GetNFAJGFHLKGI(AGMBMGJAKFJ_idx_);
			NNMHEHIOKGF AGMBMGJAKFJ_data_ = new NNMHEHIOKGF();

			AGMBMGJAKFJ_data_.PPFNGGCBJKC_id = AGMBMGJAKFJ_readData_.BBPHAPFBFHK/*_id*/;
			AGMBMGJAKFJ_data_.PLALNIIBLOF_en = AGMBMGJAKFJ_readData_.CFLMCGOJJJD/*_en*/;
			AGMBMGJAKFJ_data_.FEMMDNIELFC_Desc = AGMBMGJAKFJ_readData_.NNKLANONDOM/*_Desc*/;
			AGMBMGJAKFJ_data_.GMELAKNFKMG = AGMBMGJAKFJ_readData_.NBMJDIEAMAB;
			AGMBMGJAKFJ_data_.PIBLLGLCJEO_Param = AGMBMGJAKFJ_readData_.GMMOOPMEKKG/*_Param*/;
			AGMBMGJAKFJ_data_.OFMECFHNCHA_Popup = AGMBMGJAKFJ_readData_.KGOFDIKBIHE/*_Popup*/;
			AGMBMGJAKFJ_data_.JOPPFEHKNFO_Pickup = AGMBMGJAKFJ_readData_.ALPALMJMJJK/*_Pickup*/;
			AGMBMGJAKFJ_data_.PDBPFJJCADD_open_at = AGMBMGJAKFJ_readData_.NJLJEKDBPCH/*_open_at*/;
			AGMBMGJAKFJ_data_.FDBNFFNFOND_close_at = AGMBMGJAKFJ_readData_.MAOAGDBDBIB/*_close_at*/;
			AGMBMGJAKFJ_data_.DAPGDCPDCNA_Prio = AGMBMGJAKFJ_readData_.AIIPAPCLGGO/*_Prio*/;
			AGMBMGJAKFJ_data_.KNHOMNONOEB_AssetId = AGMBMGJAKFJ_readData_.NCADHENBLDB/*_AssetId*/;
			AGMBMGJAKFJ_data_.ODOAFNMJIMA = AGMBMGJAKFJ_readData_.NFAOINKHBIG;
			AGMBMGJAKFJ_data_.ADHCKHFANAL = AGMBMGJAKFJ_readData_.PMEGAJICHMB;
			AGMBMGJAKFJ_data_.AOBNHHIIJBO = AGMBMGJAKFJ_readData_.DKAFKOABCJA;
			AGMBMGJAKFJ_data_.IJEKNCDIIAE_mver = AGMBMGJAKFJ_readData_.OFMGALJGDAO/*_mver*/;
			AGMBMGJAKFJ_data_.KGICDMIJGDF_Group = AGMBMGJAKFJ_readData_.PEGBGEGKCGA/*_Group*/;
			AGMBMGJAKFJ_data_.JPKPDCCGGLA = AGMBMGJAKFJ_readData_.GOOHAMCBHAE;
			AGMBMGJAKFJ_data_.AMKJDECHIOF = AGMBMGJAKFJ_readData_.LECDAEGCIMH;
			AGMBMGJAKFJ_data_.KLHGOPBIOCN = AGMBMGJAKFJ_readData_.PMFELBFGCJG;
			AGMBMGJAKFJ_list_.Add(AGMBMGJAKFJ_data_);
		}
		res_data_.AGMBMGJAKFJ = AGMBMGJAKFJ_list_.ToArray();

		List<EIGKPFPCGJK> PCKGJKCOPEB_list_ = new List<EIGKPFPCGJK>();
		for(int PCKGJKCOPEB_idx_ = 0; PCKGJKCOPEB_idx_ < res_readData_.ONGHLNCPCMILength; PCKGJKCOPEB_idx_++)
		{
			JIHBJPCAEMH PCKGJKCOPEB_readData_ = res_readData_.GetONGHLNCPCMI(PCKGJKCOPEB_idx_);
			EIGKPFPCGJK PCKGJKCOPEB_data_ = new EIGKPFPCGJK();

			PCKGJKCOPEB_data_.PPFNGGCBJKC_id = PCKGJKCOPEB_readData_.BBPHAPFBFHK/*_id*/;
			PCKGJKCOPEB_data_.IJEKNCDIIAE_mver = PCKGJKCOPEB_readData_.OFMGALJGDAO/*_mver*/;
			PCKGJKCOPEB_data_.PLALNIIBLOF_en = PCKGJKCOPEB_readData_.CFLMCGOJJJD/*_en*/;
			PCKGJKCOPEB_data_.KLCMKLPIDDJ_Month = PCKGJKCOPEB_readData_.IALIGIAJJGP/*_Month*/;
			PCKGJKCOPEB_data_.BAOFEFFADPD_day = PCKGJKCOPEB_readData_.FKGLOPMFMCP/*_day*/;
			PCKGJKCOPEB_data_.KNHOMNONOEB_AssetId = PCKGJKCOPEB_readData_.NCADHENBLDB/*_AssetId*/;
			PCKGJKCOPEB_data_.AOBNHHIIJBO = PCKGJKCOPEB_readData_.DKAFKOABCJA;
			PCKGJKCOPEB_list_.Add(PCKGJKCOPEB_data_);
		}
		res_data_.PCKGJKCOPEB = PCKGJKCOPEB_list_.ToArray();

		List<OAPCAAGKGPP> KMGFICHGDGE_list_ = new List<OAPCAAGKGPP>();
		for(int KMGFICHGDGE_idx_ = 0; KMGFICHGDGE_idx_ < res_readData_.OGCIHPPJHMGLength; KMGFICHGDGE_idx_++)
		{
			JEFGONAHEGI KMGFICHGDGE_readData_ = res_readData_.GetOGCIHPPJHMG(KMGFICHGDGE_idx_);
			OAPCAAGKGPP KMGFICHGDGE_data_ = new OAPCAAGKGPP();

			KMGFICHGDGE_data_.PPFNGGCBJKC_id = KMGFICHGDGE_readData_.BBPHAPFBFHK/*_id*/;
			KMGFICHGDGE_data_.IJEKNCDIIAE_mver = KMGFICHGDGE_readData_.OFMGALJGDAO/*_mver*/;
			KMGFICHGDGE_data_.PLALNIIBLOF_en = KMGFICHGDGE_readData_.CFLMCGOJJJD/*_en*/;
			KMGFICHGDGE_data_.CCPECDBPFCJ = KMGFICHGDGE_readData_.GONOGEBKNLE;
			KMGFICHGDGE_data_.GBJFNGCDKPM_typ = KMGFICHGDGE_readData_.LPJPOOHJKAE/*_typ*/;
			KMGFICHGDGE_data_.JOFAGCFNKIO_OpenTime = KMGFICHGDGE_readData_.EBLEOMJJDMC/*_OpenTime*/;
			KMGFICHGDGE_data_.EBCHFBIINDP_End = KMGFICHGDGE_readData_.GKPLGGIHHBJ/*_End*/;
			KMGFICHGDGE_data_.KNHOMNONOEB_AssetId = KMGFICHGDGE_readData_.NCADHENBLDB/*_AssetId*/;
			KMGFICHGDGE_data_.AOBNHHIIJBO = KMGFICHGDGE_readData_.DKAFKOABCJA;
			KMGFICHGDGE_list_.Add(KMGFICHGDGE_data_);
		}
		res_data_.KMGFICHGDGE = KMGFICHGDGE_list_.ToArray();

		return res_data_;
	}
}
