using FlatBuffers;
using System.Collections.Generic;

public class DCHENGJKOKI
{
	public uint[] OEOIHIIIMCK { get; set; } // 0x8 CJPIOPLFGFA BLMLNFDOJHF IJLDMBPEGAK
	public uint MBAMIOJNGBD { get; set; } // 0xC PJHOHPBOIDJ NJBKAFBFJML IGAFGHBHMIF
	public uint BCCOMAODPJI { get; set; } // 0x10 ADINNEKFLLL KBJDPCLDJEB FPIIOJGBDEJ
	public uint LJELGFAFGAB { get; set; } // 0x14 CJCOPPAFPKE APHFJDOOLCK KBEAJHMCGPM
	public uint KNEDJFLCCLN { get; set; } // 0x18 HJMKHFAHBIO DKJNGOIGJGH EOMMBJGKKJI
	public uint ADLGKMBIPCA { get; set; } // 0x1C KJBJJPDMEMK ECHDOIILAHP BNPHIHICNCJ
	public uint PIPCIMIALOO { get; set; } // 0x20 INBCDPNEACE KJNBPECGBJJ DMAJEBCFHHK
}
public class MALFJMBMCLG
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JIBNPJCIALH { get; set; } // 0xC KOAOJEABIEG ODFPNCJNFPM LDFLKNMKMJG
	public string OPFGFINHFCE { get; set; } // 0x10 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public uint PLALNIIBLOF { get; set; } // 0x14 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint OJGBNNIJNEM { get; set; } // 0x18 GOCLPAADBNE LICAAFKDABO PNPLHIKAPAC
	public uint JPFMJHLCMJL { get; set; } // 0x1C PIJIPMOBEIJ LLFFAPHPGFJ PMGNHNIKHLE
	public uint OKADDOIJGNB { get; set; } // 0x20 AHENFOIADBF KJJLNOKJFKL HANJMIACJMH
	public uint KLCMKLPIDDJ { get; set; } // 0x24 LBNFMGNGCDA FKGAMFACFKO MHLPBOBOFJA
	public uint BAOFEFFADPD { get; set; } // 0x28 MNBJKHKHMCL KHNONKOPIPO LBJPPBMDOGE
	public DCHENGJKOKI DFEDIAPLFHN { get; set; } // 0x2C JDPHNDKLPIO BOFLPJOHHOM GDFOALHOPEG
	public int IJEKNCDIIAE { get; set; } // 0x30 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint LIOGKHIGJKN { get; set; } // 0x34 DGLBKOGGKHO JNBPCHKDNMD MLPEHHGEEIB
	public uint CMBCBNEODPD { get; set; } // 0x38 CLHDIBCIJBB EIMFDHBOECI OJMIHHIIBPI
}
public class MHKHMCAPDKK
{
	public MALFJMBMCLG[] INPCGKFIMIG { get; set; } // 0x8 HIGMNBMCFMA ALGNNBLEMFC DHAFGDNFCKI
	public static MHKHMCAPDKK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1952760
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OEMMCAHOCEL res_readData = OEMMCAHOCEL.GetRootAsOEMMCAHOCEL(buffer);
		MHKHMCAPDKK res_data = new MHKHMCAPDKK();

		List<MALFJMBMCLG> INPCGKFIMIG_list = new List<MALFJMBMCLG>();
		for(int INPCGKFIMIG_idx = 0; INPCGKFIMIG_idx < res_readData.NCMGOKNHGNLLength; INPCGKFIMIG_idx++)
		{
			LPDFHGHGHPA INPCGKFIMIG_readData = res_readData.GetNCMGOKNHGNL(INPCGKFIMIG_idx);
			MALFJMBMCLG INPCGKFIMIG_data = new MALFJMBMCLG();

			INPCGKFIMIG_data.PPFNGGCBJKC = INPCGKFIMIG_readData.BBPHAPFBFHK;
			INPCGKFIMIG_data.JIBNPJCIALH = INPCGKFIMIG_readData.PKKHBFGMNGA;
			INPCGKFIMIG_data.OPFGFINHFCE = INPCGKFIMIG_readData.IIDCFMHCPLJ;
			INPCGKFIMIG_data.PLALNIIBLOF = INPCGKFIMIG_readData.CFLMCGOJJJD;
			INPCGKFIMIG_data.OJGBNNIJNEM = INPCGKFIMIG_readData.NNNDHIHBMFL;
			INPCGKFIMIG_data.JPFMJHLCMJL = INPCGKFIMIG_readData.GJEJFAJHBME;
			INPCGKFIMIG_data.OKADDOIJGNB = INPCGKFIMIG_readData.OPDKCCDMPHA;
			INPCGKFIMIG_data.KLCMKLPIDDJ = INPCGKFIMIG_readData.IALIGIAJJGP;
			INPCGKFIMIG_data.BAOFEFFADPD = INPCGKFIMIG_readData.FKGLOPMFMCP;
			HJJBMKIDKFG DFEDIAPLFHN_readData = INPCGKFIMIG_readData.FFBCKIHFJJJ;
			DCHENGJKOKI DFEDIAPLFHN_data = new DCHENGJKOKI();

			List<uint> OEOIHIIIMCK_list = new List<uint>();
			for(int OEOIHIIIMCK_idx = 0; OEOIHIIIMCK_idx < DFEDIAPLFHN_readData.KIJLMKMIBFLLength; OEOIHIIIMCK_idx++)
			{
				OEOIHIIIMCK_list.Add(DFEDIAPLFHN_readData.GetKIJLMKMIBFL(OEOIHIIIMCK_idx));
			}
			DFEDIAPLFHN_data.OEOIHIIIMCK = OEOIHIIIMCK_list.ToArray();

			DFEDIAPLFHN_data.MBAMIOJNGBD = DFEDIAPLFHN_readData.KDPKPOBKKMJ;
			DFEDIAPLFHN_data.BCCOMAODPJI = DFEDIAPLFHN_readData.MHFDKEEEDEL;
			DFEDIAPLFHN_data.LJELGFAFGAB = DFEDIAPLFHN_readData.FHLKEIBOFNN;
			DFEDIAPLFHN_data.KNEDJFLCCLN = DFEDIAPLFHN_readData.EGEFMJCLNDM;
			DFEDIAPLFHN_data.ADLGKMBIPCA = DFEDIAPLFHN_readData.IJMEOOJHNCG;
			DFEDIAPLFHN_data.PIPCIMIALOO = DFEDIAPLFHN_readData.GKLHNNBMGKH;
			INPCGKFIMIG_data.DFEDIAPLFHN = DFEDIAPLFHN_data;
			INPCGKFIMIG_data.IJEKNCDIIAE = INPCGKFIMIG_readData.OFMGALJGDAO;
			INPCGKFIMIG_data.LIOGKHIGJKN = INPCGKFIMIG_readData.BEJCCAMIPNB;
			INPCGKFIMIG_data.CMBCBNEODPD = INPCGKFIMIG_readData.LAIOEDGDIFO;
			INPCGKFIMIG_list.Add(INPCGKFIMIG_data);
		}
		res_data.INPCGKFIMIG = INPCGKFIMIG_list.ToArray();

		return res_data;
	}
}
