using FlatBuffers;
using System.Collections.Generic;

public class APLNHNOKJFK
{
	public uint OKECOPNBAGP_ro { get; set; } // 0x8 GJMOEJLFGBN ACABAJEMECC_get_ro CELOOGFFIKN_set_ro
	public string OPFGFINHFCE_name { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE_get_name MJAMIGECMMF_set_name
	public int GBJFNGCDKPM_typ { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public int JMMEGKGCIIL { get; set; } // 0x14 ILCNHAFCAGN JDPKCAGDCLJ_get_ DNFIBINDNJO_set_
	public int HANMDEBPBHG_pic { get; set; } // 0x18 IMDBPCNAOOE EFGGIMOPNMG_get_pic PNGGKPFDKMA_set_pic
	public int PLALNIIBLOF_en { get; set; } // 0x1C DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int IJEKNCDIIAE_mver { get; set; } // 0x20 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PFJJFCPPNIN_nx { get; set; } // 0x24 JDMOEHEIMKJ DPIIPBMNHOI_get_nx LAKMHLJFOAL_set_nx
}
public class COJBCBGIGHJ
{
	public uint ODMJFHDIGLP_cnd { get; set; } // 0x8 DKHKAJOLLPE IEACLNIEABJ_get_cnd KEOPEEKGMDO_set_cnd
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public uint PPFNGGCBJKC_id { get; set; } // 0x10 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public uint OKECOPNBAGP_ro { get; set; } // 0x14 GJMOEJLFGBN ACABAJEMECC_get_ro CELOOGFFIKN_set_ro
	public uint EPKOHDLIKAN_tk { get; set; } // 0x18 HEFLNIKDCGO EPBFDHHAOMO_get_tk BJFENLPFMDK_set_tk
	public int KFCIJBLDHOK_v1 { get; set; } // 0x1C JPBPAFOAPIO EPEKNNHHPIF_get_v1 LFGKAMKBDGA_set_v1
	public int JLEIHOEGMOP_v2 { get; set; } // 0x20 JLNAMGLBPME JJGFFGDDFPA_get_v2 LIIFHDMHLHP_set_v2
	public int IJEKNCDIIAE_mver { get; set; } // 0x24 FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
}
public class EIDBDFGNCFB
{
	public int JBFLEDKDFCO_cid { get; set; } // 0x8 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public string OPFGFINHFCE_name { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE_get_name MJAMIGECMMF_set_name
	public string ONOPACPKFPK_ac { get; set; } // 0x10 OHJDEFNDKDA DJMMMALFDDG_get_ac PGMNJMHJHOG_set_ac
	public uint HANMDEBPBHG_pic { get; set; } // 0x14 IMDBPCNAOOE EFGGIMOPNMG_get_pic PNGGKPFDKMA_set_pic
	public uint PLALNIIBLOF_en { get; set; } // 0x18 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int DJJNOCDIIAE { get; set; } // 0x1C KIEEONFHJJB APHILLHCKDM_get_ MBPPAEHAOAM_set_
	public int CPKMLLNADLJ_Serie { get; set; } // 0x20 COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
}
public class CBGIPNJOPAH
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int DOKKMMFKLJI_Color { get; set; } // 0xC HHLLKENPACJ FGEACNKHOEB_get_Color KNMBKMIELEO_set_Color
}
public class MILDDOGCGLE
{
	public APLNHNOKJFK[] BHFAMKAPFNJ { get; set; } // 0x8 LAKHCMHJMAH IIMMELPMKAK_get_ JMAMGDOEKLP_set_
	public COJBCBGIGHJ[] IPCJPOGBHGP { get; set; } // 0xC IOFJJIHICGF BLCLBJJAPNM_get_ KELNPDBEIBA_set_
	public EIDBDFGNCFB[] CEPBAOMAHNH { get; set; } // 0x10 EALHHHABHEI KJBLMCHIKFD_get_ OEBMOJPBAEF_set_
	public CBGIPNJOPAH[] ABIKKECOBIJ { get; set; } // 0x14 GKCCAOHFLPA NOAODGOPFJC_get_ NGBFPOINDKG_set_
	public static MILDDOGCGLE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1956DE4
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		DEMFEEEPCCO res_readData_ = DEMFEEEPCCO.GetRootAsDEMFEEEPCCO(buffer);
		MILDDOGCGLE res_data_ = new MILDDOGCGLE();

		List<APLNHNOKJFK> BHFAMKAPFNJ_list_ = new List<APLNHNOKJFK>();
		for(int BHFAMKAPFNJ_idx_ = 0; BHFAMKAPFNJ_idx_ < res_readData_.ADNNNAFIBLDLength; BHFAMKAPFNJ_idx_++)
		{
			OCJCBHOBGJJ BHFAMKAPFNJ_readData_ = res_readData_.GetADNNNAFIBLD(BHFAMKAPFNJ_idx_);
			APLNHNOKJFK BHFAMKAPFNJ_data_ = new APLNHNOKJFK();

			BHFAMKAPFNJ_data_.OKECOPNBAGP_ro = BHFAMKAPFNJ_readData_.OCCGFNHHECN/*_ro*/;
			BHFAMKAPFNJ_data_.OPFGFINHFCE_name = BHFAMKAPFNJ_readData_.IIDCFMHCPLJ/*_name*/;
			BHFAMKAPFNJ_data_.GBJFNGCDKPM_typ = BHFAMKAPFNJ_readData_.LPJPOOHJKAE/*_typ*/;
			BHFAMKAPFNJ_data_.JMMEGKGCIIL = BHFAMKAPFNJ_readData_.FKLNFLAFBDH;
			BHFAMKAPFNJ_data_.HANMDEBPBHG_pic = BHFAMKAPFNJ_readData_.BLJLFEDLAME/*_pic*/;
			BHFAMKAPFNJ_data_.PLALNIIBLOF_en = BHFAMKAPFNJ_readData_.CFLMCGOJJJD/*_en*/;
			BHFAMKAPFNJ_data_.IJEKNCDIIAE_mver = BHFAMKAPFNJ_readData_.OFMGALJGDAO/*_mver*/;
			BHFAMKAPFNJ_data_.PFJJFCPPNIN_nx = BHFAMKAPFNJ_readData_.KKJFKKJHCAI/*_nx*/;
			BHFAMKAPFNJ_list_.Add(BHFAMKAPFNJ_data_);
		}
		res_data_.BHFAMKAPFNJ = BHFAMKAPFNJ_list_.ToArray();

		List<COJBCBGIGHJ> IPCJPOGBHGP_list_ = new List<COJBCBGIGHJ>();
		for(int IPCJPOGBHGP_idx_ = 0; IPCJPOGBHGP_idx_ < res_readData_.NEPBOHLLOGMLength; IPCJPOGBHGP_idx_++)
		{
			JCPFGFKDDJP IPCJPOGBHGP_readData_ = res_readData_.GetNEPBOHLLOGM(IPCJPOGBHGP_idx_);
			COJBCBGIGHJ IPCJPOGBHGP_data_ = new COJBCBGIGHJ();

			IPCJPOGBHGP_data_.ODMJFHDIGLP_cnd = IPCJPOGBHGP_readData_.NCIKNCJLFBI/*_cnd*/;
			IPCJPOGBHGP_data_.PLALNIIBLOF_en = IPCJPOGBHGP_readData_.CFLMCGOJJJD/*_en*/;
			IPCJPOGBHGP_data_.PPFNGGCBJKC_id = IPCJPOGBHGP_readData_.BBPHAPFBFHK/*_id*/;
			IPCJPOGBHGP_data_.OKECOPNBAGP_ro = IPCJPOGBHGP_readData_.OCCGFNHHECN/*_ro*/;
			IPCJPOGBHGP_data_.EPKOHDLIKAN_tk = IPCJPOGBHGP_readData_.JKAAFPNGHGN/*_tk*/;
			IPCJPOGBHGP_data_.KFCIJBLDHOK_v1 = IPCJPOGBHGP_readData_.MCJNHPMBPIJ/*_v1*/;
			IPCJPOGBHGP_data_.JLEIHOEGMOP_v2 = IPCJPOGBHGP_readData_.MGJKFKDICGC/*_v2*/;
			IPCJPOGBHGP_data_.IJEKNCDIIAE_mver = IPCJPOGBHGP_readData_.OFMGALJGDAO/*_mver*/;
			IPCJPOGBHGP_list_.Add(IPCJPOGBHGP_data_);
		}
		res_data_.IPCJPOGBHGP = IPCJPOGBHGP_list_.ToArray();

		List<EIDBDFGNCFB> CEPBAOMAHNH_list_ = new List<EIDBDFGNCFB>();
		for(int CEPBAOMAHNH_idx_ = 0; CEPBAOMAHNH_idx_ < res_readData_.MMKDCMGIEKMLength; CEPBAOMAHNH_idx_++)
		{
			AHKFABMCFNG CEPBAOMAHNH_readData_ = res_readData_.GetMMKDCMGIEKM(CEPBAOMAHNH_idx_);
			EIDBDFGNCFB CEPBAOMAHNH_data_ = new EIDBDFGNCFB();

			CEPBAOMAHNH_data_.JBFLEDKDFCO_cid = CEPBAOMAHNH_readData_.HOENDPOGFIO/*_cid*/;
			CEPBAOMAHNH_data_.OPFGFINHFCE_name = CEPBAOMAHNH_readData_.IIDCFMHCPLJ/*_name*/;
			CEPBAOMAHNH_data_.ONOPACPKFPK_ac = CEPBAOMAHNH_readData_.JFJLBDICHHJ/*_ac*/;
			CEPBAOMAHNH_data_.HANMDEBPBHG_pic = CEPBAOMAHNH_readData_.BLJLFEDLAME/*_pic*/;
			CEPBAOMAHNH_data_.PLALNIIBLOF_en = CEPBAOMAHNH_readData_.CFLMCGOJJJD/*_en*/;
			CEPBAOMAHNH_data_.DJJNOCDIIAE = CEPBAOMAHNH_readData_.BPOKEPDFBCO;
			CEPBAOMAHNH_data_.CPKMLLNADLJ_Serie = CEPBAOMAHNH_readData_.LMLNKHMPOIG/*_Serie*/;
			CEPBAOMAHNH_list_.Add(CEPBAOMAHNH_data_);
		}
		res_data_.CEPBAOMAHNH = CEPBAOMAHNH_list_.ToArray();

		List<CBGIPNJOPAH> ABIKKECOBIJ_list_ = new List<CBGIPNJOPAH>();
		for(int ABIKKECOBIJ_idx_ = 0; ABIKKECOBIJ_idx_ < res_readData_.OANLFAKIJOFLength; ABIKKECOBIJ_idx_++)
		{
			NCHJODAGBPK ABIKKECOBIJ_readData_ = res_readData_.GetOANLFAKIJOF(ABIKKECOBIJ_idx_);
			CBGIPNJOPAH ABIKKECOBIJ_data_ = new CBGIPNJOPAH();

			ABIKKECOBIJ_data_.PPFNGGCBJKC_id = ABIKKECOBIJ_readData_.BBPHAPFBFHK/*_id*/;
			ABIKKECOBIJ_data_.DOKKMMFKLJI_Color = ABIKKECOBIJ_readData_.DMJIIMKLBAL/*_Color*/;
			ABIKKECOBIJ_list_.Add(ABIKKECOBIJ_data_);
		}
		res_data_.ABIKKECOBIJ = ABIKKECOBIJ_list_.ToArray();

		return res_data_;
	}
}
