using FlatBuffers;
using System.Collections.Generic;

public class FHAPNNHNNCN
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int HJAFPEBIBOP { get; set; } // 0x14 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
	public int JBGEEPFKIGG { get; set; } // 0x18 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int DOOGFEGEKLG { get; set; } // 0x1C IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public int FPOMEEJFBIG { get; set; } // 0x20 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public uint FBFLDFMFFOH { get; set; } // 0x24 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
}
public class MKLLOAPBIGJ
{
	public FHAPNNHNNCN[] JNMKOOKNLIN { get; set; } // 0x8 OBFBJCIGOCE HKJHABAAOCC IEJEDMFIHLO
	public static MKLLOAPBIGJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x195A638
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		AMMFBOPDMFI res_readData = AMMFBOPDMFI.GetRootAsAMMFBOPDMFI(buffer);
		MKLLOAPBIGJ res_data = new MKLLOAPBIGJ();

		List<FHAPNNHNNCN> JNMKOOKNLIN_list = new List<FHAPNNHNNCN>();
		for(int JNMKOOKNLIN_idx = 0; JNMKOOKNLIN_idx < res_readData.JIHMDOCLAPKLength; JNMKOOKNLIN_idx++)
		{
			EFOIDPJOBDM JNMKOOKNLIN_readData = res_readData.GetJIHMDOCLAPK(JNMKOOKNLIN_idx);
			FHAPNNHNNCN JNMKOOKNLIN_data = new FHAPNNHNNCN();

			JNMKOOKNLIN_data.PPFNGGCBJKC = JNMKOOKNLIN_readData.BBPHAPFBFHK;
			JNMKOOKNLIN_data.IJEKNCDIIAE = JNMKOOKNLIN_readData.OFMGALJGDAO;
			JNMKOOKNLIN_data.PLALNIIBLOF = JNMKOOKNLIN_readData.CFLMCGOJJJD;
			JNMKOOKNLIN_data.HJAFPEBIBOP = JNMKOOKNLIN_readData.HBHEHJDPEBI;
			JNMKOOKNLIN_data.JBGEEPFKIGG = JNMKOOKNLIN_readData.KJFEBMBHKOC;
			JNMKOOKNLIN_data.DOOGFEGEKLG = JNMKOOKNLIN_readData.GEJGMBBCFEE;
			JNMKOOKNLIN_data.FPOMEEJFBIG = JNMKOOKNLIN_readData.AEAKMMJLLDK;
			JNMKOOKNLIN_data.FBFLDFMFFOH = JNMKOOKNLIN_readData.ODBPKGJPLMD;
			JNMKOOKNLIN_list.Add(JNMKOOKNLIN_data);
		}
		res_data.JNMKOOKNLIN = JNMKOOKNLIN_list.ToArray();

		return res_data;
	}
}
