using FlatBuffers;
using System.Collections.Generic;

public class CDHIKHMHMPC
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int PDBPFJJCADD { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public int FJOLNJLLJEJ { get; set; } // 0x1C BLIGJGPCOKP EAKAGHDPEMI GHECCGBGCBI
	public int KNHOMNONOEB { get; set; } // 0x20 EJNCFCPHDML NECFMEFKKPH MHNEFLJACHA
}
public class MLAEPADJOJH
{
	public CDHIKHMHMPC[] MJBONPHHNKG { get; set; } // 0x8 PDFMJOBHFJE LNGLAMGMLHL KLCILDKIJCF
	public static MLAEPADJOJH HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x195CBB8
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OGOJIHOJMHD res_readData = OGOJIHOJMHD.GetRootAsOGOJIHOJMHD(buffer);
		MLAEPADJOJH res_data = new MLAEPADJOJH();

		List<CDHIKHMHMPC> MJBONPHHNKG_list = new List<CDHIKHMHMPC>();
		for(int MJBONPHHNKG_idx = 0; MJBONPHHNKG_idx < res_readData.EIKBNOECLEALength; MJBONPHHNKG_idx++)
		{
			FJNOJOMGGKJ MJBONPHHNKG_readData = res_readData.GetEIKBNOECLEA(MJBONPHHNKG_idx);
			CDHIKHMHMPC MJBONPHHNKG_data = new CDHIKHMHMPC();

			MJBONPHHNKG_data.PPFNGGCBJKC = MJBONPHHNKG_readData.BBPHAPFBFHK;
			MJBONPHHNKG_data.IJEKNCDIIAE = MJBONPHHNKG_readData.OFMGALJGDAO;
			MJBONPHHNKG_data.PLALNIIBLOF = MJBONPHHNKG_readData.CFLMCGOJJJD;
			MJBONPHHNKG_data.PDBPFJJCADD = MJBONPHHNKG_readData.NJLJEKDBPCH;
			MJBONPHHNKG_data.FDBNFFNFOND = MJBONPHHNKG_readData.MAOAGDBDBIB;
			MJBONPHHNKG_data.FJOLNJLLJEJ = MJBONPHHNKG_readData.BDGDHOAJDFM;
			MJBONPHHNKG_data.KNHOMNONOEB = MJBONPHHNKG_readData.NCADHENBLDB;
			MJBONPHHNKG_list.Add(MJBONPHHNKG_data);
		}
		res_data.MJBONPHHNKG = MJBONPHHNKG_list.ToArray();

		return res_data;
	}
}
