using FlatBuffers;
using System.Collections.Generic;

public class FABKJOODBNN
{
	public int KAPMOPMDHJE { get; set; } // 0x8 EJDCHACDMPH MONBNPKLFGC KGFFKEDNIID
	public string[] PIBLLGLCJEO { get; set; } // 0xC KGLJBJIIAEG CMKMAGNMPGC CICCOMMMNHK
}
public class GPCOJNLJJLE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public FABKJOODBNN[] PBOHDAFOEIA { get; set; } // 0xC JGOGMDKIANB DOHAEHILHEJ PDACBNCMOJO
	public int PMJAGEJIOJE { get; set; } // 0x10 LLPEBCNLMAN BOEDFMEFNJH BBJCCCBILNL
	public string IPBHCLIHAPG { get; set; } // 0x14 PGDNLLBNAFF CBMCOGPJADM BAIGLALPKDE
}
public class NCFKBGFDBAG
{
	public GPCOJNLJJLE[] HEHPAMADHGC { get; set; } // 0x8 ELDDPACCPDB BGLEMGEDKIM HPKKCCEEGEK
	public static NCFKBGFDBAG HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x17CC234
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		JDKBJLPDAMB res_readData = JDKBJLPDAMB.GetRootAsJDKBJLPDAMB(buffer);
		NCFKBGFDBAG res_data = new NCFKBGFDBAG();

		List<GPCOJNLJJLE> HEHPAMADHGC_list = new List<GPCOJNLJJLE>();
		for(int HEHPAMADHGC_idx = 0; HEHPAMADHGC_idx < res_readData.PIIOHCJFHBDLength; HEHPAMADHGC_idx++)
		{
			LDOCPAKMACI HEHPAMADHGC_readData = res_readData.GetPIIOHCJFHBD(HEHPAMADHGC_idx);
			GPCOJNLJJLE HEHPAMADHGC_data = new GPCOJNLJJLE();

			HEHPAMADHGC_data.PPFNGGCBJKC = HEHPAMADHGC_readData.BBPHAPFBFHK;
			List<FABKJOODBNN> PBOHDAFOEIA_list = new List<FABKJOODBNN>();
			for(int PBOHDAFOEIA_idx = 0; PBOHDAFOEIA_idx < HEHPAMADHGC_readData.IIBAJDOLFBMLength; PBOHDAFOEIA_idx++)
			{
				LJONABMKIOM PBOHDAFOEIA_readData = HEHPAMADHGC_readData.GetIIBAJDOLFBM(PBOHDAFOEIA_idx);
				FABKJOODBNN PBOHDAFOEIA_data = new FABKJOODBNN();

				PBOHDAFOEIA_data.KAPMOPMDHJE = PBOHDAFOEIA_readData.BNFLNMGOJCM;
				List<string> PIBLLGLCJEO_list = new List<string>();
				for(int PIBLLGLCJEO_idx = 0; PIBLLGLCJEO_idx < PBOHDAFOEIA_readData.BPODDGNIDBGLength; PIBLLGLCJEO_idx++)
				{
					PIBLLGLCJEO_list.Add(PBOHDAFOEIA_readData.GetBPODDGNIDBG(PIBLLGLCJEO_idx));
				}
				PBOHDAFOEIA_data.PIBLLGLCJEO = PIBLLGLCJEO_list.ToArray();

				PBOHDAFOEIA_list.Add(PBOHDAFOEIA_data);
			}
			HEHPAMADHGC_data.PBOHDAFOEIA = PBOHDAFOEIA_list.ToArray();

			HEHPAMADHGC_data.PMJAGEJIOJE = HEHPAMADHGC_readData.GELNDPJNLJM;
			HEHPAMADHGC_data.IPBHCLIHAPG = HEHPAMADHGC_readData.IAHNDJDBCAJ;
			HEHPAMADHGC_list.Add(HEHPAMADHGC_data);
		}
		res_data.HEHPAMADHGC = HEHPAMADHGC_list.ToArray();

		return res_data;
	}
}
