using FlatBuffers;
using System.Collections.Generic;

public class JNHHIHOCMHN
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint HANMDEBPBHG_pic { get; set; } // 0xC IMDBPCNAOOE EFGGIMOPNMG PNGGKPFDKMA
	public uint HDEBAGHEIKD_plt { get; set; } // 0x10 LEOIDFOJDEB ILEIGMALLGJ EEAKPBHBMOL
	public uint DFOIEJOKDKJ_avo { get; set; } // 0x14 NELIGKOCNOK FKLAHJBFJCO APCNKLOJCNJ
	public uint AKOJJJLPCKA_c_s { get; set; } // 0x18 HAHLJMLFIKD NIKDJFBDBOO IDCBHPEIAFE
	public uint LNKKMBCDPHH_l_s { get; set; } // 0x1C GPEMGLLCJIF PAPMCJONAGI MODJBBMBLCD
}
public class NHADPDNKGIE
{
	public JNHHIHOCMHN[] EAHFNHMNPIB { get; set; } // 0x8 MEMBLECFIJD FCMCIMGKNLP CGGPLGMEJHC
	public static NHADPDNKGIE HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1890084
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		PCIEJLEICFK res_readData = PCIEJLEICFK.GetRootAsPCIEJLEICFK(buffer);
		NHADPDNKGIE res_data = new NHADPDNKGIE();

		List<JNHHIHOCMHN> EAHFNHMNPIB_list = new List<JNHHIHOCMHN>();
		for(int EAHFNHMNPIB_idx = 0; EAHFNHMNPIB_idx < res_readData.AHBLKAMALAMLength; EAHFNHMNPIB_idx++)
		{
			PJOFNFPMOLG EAHFNHMNPIB_readData = res_readData.GetAHBLKAMALAM(EAHFNHMNPIB_idx);
			JNHHIHOCMHN EAHFNHMNPIB_data = new JNHHIHOCMHN();

			EAHFNHMNPIB_data.PPFNGGCBJKC_id = EAHFNHMNPIB_readData.BBPHAPFBFHK;
			EAHFNHMNPIB_data.HANMDEBPBHG_pic = EAHFNHMNPIB_readData.BLJLFEDLAME;
			EAHFNHMNPIB_data.HDEBAGHEIKD_plt = EAHFNHMNPIB_readData.DALJDMJEJGE;
			EAHFNHMNPIB_data.DFOIEJOKDKJ_avo = EAHFNHMNPIB_readData.IDJCFCJMBCF;
			EAHFNHMNPIB_data.AKOJJJLPCKA_c_s = EAHFNHMNPIB_readData.NAGPKLGDNDA;
			EAHFNHMNPIB_data.LNKKMBCDPHH_l_s = EAHFNHMNPIB_readData.BNDEBMLCMNB;
			EAHFNHMNPIB_list.Add(EAHFNHMNPIB_data);
		}
		res_data.EAHFNHMNPIB = EAHFNHMNPIB_list.ToArray();

		return res_data;
	}
}
