using FlatBuffers;
using System.Collections.Generic;

public class KDNFKHOKMJL
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JPFMJHLCMJL_sa { get; set; } // 0xC PIJIPMOBEIJ LLFFAPHPGFJ PMGNHNIKHLE
	public uint FLNJLKKAFPB_mdl { get; set; } // 0x10 JLLDIELMHID IHDOHKGJGCM IGNBIGFGIFM
	public uint HDEBAGHEIKD_plt { get; set; } // 0x14 LEOIDFOJDEB ILEIGMALLGJ EEAKPBHBMOL
	public uint FCBJFKGDINH_atk { get; set; } // 0x18 EKHAHLAEBNM APJOLOOEKPM BEFLICOCMHH
	public uint NONBCCLGBAO_hit { get; set; } // 0x1C FGGPAEAFOJK AEJBEGKBPCO JPIBPFANBNG
	public uint PLALNIIBLOF_en { get; set; } // 0x20 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint[] GMELAKNFKMG { get; set; } // 0x24 NBIGNIFKHLH GNIIGNBNAJF DNGBCJOKLND
	public int IJEKNCDIIAE_mver { get; set; } // 0x28 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint BMIJDLBGFNP_skill { get; set; } // 0x2C NLNNLBICNHM NIHGHMNFOAO KOPGMKMNJJL
	public int BFCBGDOICCO { get; set; } // 0x30 JIJFLOEODFI BMIDBHCAMPH DLNNMGILLDO
}
public class NJOFJDHEGIK
{
	public KDNFKHOKMJL[] PIEGAMCFGGL { get; set; } // 0x8 LHBDLFBMMEE AFEINBHAFDG FPLDHNLOPKN
	public static NJOFJDHEGIK HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x18AC780
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		LDLCKBMOFJC res_readData = LDLCKBMOFJC.GetRootAsLDLCKBMOFJC(buffer);
		NJOFJDHEGIK res_data = new NJOFJDHEGIK();

		List<KDNFKHOKMJL> PIEGAMCFGGL_list = new List<KDNFKHOKMJL>();
		for(int PIEGAMCFGGL_idx = 0; PIEGAMCFGGL_idx < res_readData.HLBFAIIOKBILength; PIEGAMCFGGL_idx++)
		{
			ILOKJEKGMOB PIEGAMCFGGL_readData = res_readData.GetHLBFAIIOKBI(PIEGAMCFGGL_idx);
			KDNFKHOKMJL PIEGAMCFGGL_data = new KDNFKHOKMJL();

			PIEGAMCFGGL_data.PPFNGGCBJKC_id = PIEGAMCFGGL_readData.BBPHAPFBFHK;
			PIEGAMCFGGL_data.JPFMJHLCMJL_sa = PIEGAMCFGGL_readData.GJEJFAJHBME;
			PIEGAMCFGGL_data.FLNJLKKAFPB_mdl = PIEGAMCFGGL_readData.KAOBJENOMHF;
			PIEGAMCFGGL_data.HDEBAGHEIKD_plt = PIEGAMCFGGL_readData.DALJDMJEJGE;
			PIEGAMCFGGL_data.FCBJFKGDINH_atk = PIEGAMCFGGL_readData.JJPIKBCKLGF;
			PIEGAMCFGGL_data.NONBCCLGBAO_hit = PIEGAMCFGGL_readData.ENPKFDIPGPF;
			PIEGAMCFGGL_data.PLALNIIBLOF_en = PIEGAMCFGGL_readData.CFLMCGOJJJD;
			List<uint> GMELAKNFKMG_list = new List<uint>();
			for(int GMELAKNFKMG_idx = 0; GMELAKNFKMG_idx < PIEGAMCFGGL_readData.DLJEENDFNDBLength; GMELAKNFKMG_idx++)
			{
				GMELAKNFKMG_list.Add(PIEGAMCFGGL_readData.GetDLJEENDFNDB(GMELAKNFKMG_idx));
			}
			PIEGAMCFGGL_data.GMELAKNFKMG = GMELAKNFKMG_list.ToArray();

			PIEGAMCFGGL_data.IJEKNCDIIAE_mver = PIEGAMCFGGL_readData.OFMGALJGDAO;
			PIEGAMCFGGL_data.BMIJDLBGFNP_skill = PIEGAMCFGGL_readData.MPIHPCJAHGA;
			PIEGAMCFGGL_data.BFCBGDOICCO = PIEGAMCFGGL_readData.GBJKMHDILHH;
			PIEGAMCFGGL_list.Add(PIEGAMCFGGL_data);
		}
		res_data.PIEGAMCFGGL = PIEGAMCFGGL_list.ToArray();

		return res_data;
	}
}
