using FlatBuffers;
using System.Collections.Generic;

public class OANCBKFMLFB
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint FJFCNGNGIBN { get; set; } // 0x14 PKNMGMMCPPJ OCNDKILHCJK NMEEPJEFADN
	public uint CPKMLLNADLJ { get; set; } // 0x18 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint FBFLDFMFFOH { get; set; } // 0x1C LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int MLMCEBBDJOE { get; set; } // 0x20 LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x24 LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK { get; set; } // 0x28 JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
}
public class IJLIGDANLAG
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int FJFCNGNGIBN { get; set; } // 0x18 PKNMGMMCPPJ OCNDKILHCJK NMEEPJEFADN
	public uint CPKMLLNADLJ { get; set; } // 0x1C COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint FBFLDFMFFOH { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint FAKNMCIIAEM { get; set; } // 0x24 CLELCODBOBF CGDPJCABPDB JJFPNFCDNIC
	public uint KPECMLFDLOI { get; set; } // 0x28 CIGDCGJELBI ILFJIGDCGBK DOGEFDDMBDM
	public int NGILPOOLBCF { get; set; } // 0x2C JHEFBAFILNF EDGHLAHGBFN LFCKFNLGFCN
	public int JINEKNIBOFI { get; set; } // 0x30 KPHFGIFBIJA LKDHAPEGCPH PBPDONPMGNF
	public int IHLFAPCIBJB { get; set; } // 0x34 AOLAIPDAKCJ PJPNMBNCAKK OJMLOLMALOI
	public uint CMMNFCJNIOO { get; set; } // 0x38 OJPKPMGMBEH IPBHOIGBNEO EACBGCGAKLO
	public int FPOMEEJFBIG { get; set; } // 0x3C PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public int KEJMJPHFFOJ { get; set; } // 0x40 NNGEOJMHAEA FMNMLNIALNE GBEPCBPOGDB
	public int MLMCEBBDJOE { get; set; } // 0x44 LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x48 LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK { get; set; } // 0x4C JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
}
public class GJLHLFLOCGJ
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint CPKMLLNADLJ { get; set; } // 0x14 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint FBFLDFMFFOH { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int KEJMJPHFFOJ { get; set; } // 0x1C NNGEOJMHAEA FMNMLNIALNE GBEPCBPOGDB
	public int MLMCEBBDJOE { get; set; } // 0x20 LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x24 LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK { get; set; } // 0x28 JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
}
public class JLFONMFLBHF
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int GBJFNGCDKPM { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int FJFCNGNGIBN { get; set; } // 0x18 PKNMGMMCPPJ OCNDKILHCJK NMEEPJEFADN
	public uint DMEDKJPOLCH { get; set; } // 0x1C JAEJJPMKMFI IPKCKAAEEOE JOGLLINFLJN
	public uint CPKMLLNADLJ { get; set; } // 0x20 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint FBFLDFMFFOH { get; set; } // 0x24 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public uint FAKNMCIIAEM { get; set; } // 0x28 CLELCODBOBF CGDPJCABPDB JJFPNFCDNIC
	public uint KPECMLFDLOI { get; set; } // 0x2C CIGDCGJELBI ILFJIGDCGBK DOGEFDDMBDM
	public int NGILPOOLBCF { get; set; } // 0x30 JHEFBAFILNF EDGHLAHGBFN LFCKFNLGFCN
	public int JINEKNIBOFI { get; set; } // 0x34 KPHFGIFBIJA LKDHAPEGCPH PBPDONPMGNF
	public int IHLFAPCIBJB { get; set; } // 0x38 AOLAIPDAKCJ PJPNMBNCAKK OJMLOLMALOI
	public uint CMMNFCJNIOO { get; set; } // 0x3C OJPKPMGMBEH IPBHOIGBNEO EACBGCGAKLO
	public uint GLCLFMGPMAN { get; set; } // 0x40 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public int JJPDPNJFBHN { get; set; } // 0x44 BHLPKBCBIAE OFDIOBMHMHA PLFBKOJLLEG
}
public class JBFPJEDOMLM
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IGKCGELCEBD { get; set; } // 0xC AIMLABKMDPN LFEHAAKBIHB CGJGGKEKFLK
	public int[] KONAMNAICNJ { get; set; } // 0x10 MGIFEIKKFAM LJFCKOAHMLF MOPOAENNHDF
	public int[] JAHIGOPCJBG { get; set; } // 0x14 LAGBMDEGDCP CNMDIPDMDOC MGBJPOJMBON
}
public class IPFNMBJGFFB
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public uint PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int JBFLEDKDFCO { get; set; } // 0x14 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public int GBJFNGCDKPM { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint CPKMLLNADLJ { get; set; } // 0x1C COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public uint FBFLDFMFFOH { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI CHHJKABBIBL
	public int MLMCEBBDJOE { get; set; } // 0x24 LNGPPHKHGMH IGMHCODOFKG IIIGDLGGEGK
	public int ODNILEDOAIP { get; set; } // 0x28 LMNIPCGLCCM GNKPMBBAJHI PPMACIMALAC
	public int NPPGKNGIFGK { get; set; } // 0x2C JDJKLDMOMGO FLMDBAFHDNJ DIHIEJPOCOJ
	public int[] GNKMHCKFADN { get; set; } // 0x30 JCJPDGBHLCA MBODMLHJCML PGBABMMAOKI
}
public class JCNADBBMELP
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int IJEKNCDIIAE { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
	public int PLALNIIBLOF { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public int FLLNHNJFIFL { get; set; } // 0x14 PKFLEPBDGJH BONCEKFANMH HCCOHHKDDHI
	public int PDBPFJJCADD { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class HAJOGKOEFID
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class AGLIIECMMKO
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class NLFIKMMPOAL
{
	public OANCBKFMLFB[] DPMFAJPEFOL { get; set; } // 0x8 AEBFMDIMDLE JJHADCINGOE KFBMIPBJPJJ
	public IJLIGDANLAG[] NGJHCGBNCNL { get; set; } // 0xC MIJLONLBHHE POJACBMCHGP GBKAMCDCIBA
	public GJLHLFLOCGJ[] HLKGADDBKDB { get; set; } // 0x10 ABLDBGHEFAO DBKKMKFKMIC OIAJIDADJLG
	public JLFONMFLBHF[] NNCJEMHAIMC { get; set; } // 0x14 OPMDONDPIJL PGMMLNOOHHP LKFHCLBCGEL
	public JBFPJEDOMLM[] JMFICAHELIK { get; set; } // 0x18 MPNEFPBGAOI CGMKMGFEMPA KFMGOBOEHBC
	public IPFNMBJGFFB[] CEPBAOMAHNH { get; set; } // 0x1C EALHHHABHEI KJBLMCHIKFD OEBMOJPBAEF
	public JCNADBBMELP[] OOEMJCHLAKD { get; set; } // 0x20 FCEKMMDHAIC FINKADBKKPO BJFEEMEENDD
	public HAJOGKOEFID[] BHGDNGHDDAC { get; set; } // 0x24 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public AGLIIECMMKO[] MHGMDJNOLMI { get; set; } // 0x28 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public static NLFIKMMPOAL HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xC2E554
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		MOHBMMEAEON res_readData = MOHBMMEAEON.GetRootAsMOHBMMEAEON(buffer);
		NLFIKMMPOAL res_data = new NLFIKMMPOAL();

		List<OANCBKFMLFB> DPMFAJPEFOL_list = new List<OANCBKFMLFB>();
		for(int DPMFAJPEFOL_idx = 0; DPMFAJPEFOL_idx < res_readData.IJOFIDAFJGALength; DPMFAJPEFOL_idx++)
		{
			APKGJCPIHGB DPMFAJPEFOL_readData = res_readData.GetIJOFIDAFJGA(DPMFAJPEFOL_idx);
			OANCBKFMLFB DPMFAJPEFOL_data = new OANCBKFMLFB();

			DPMFAJPEFOL_data.PPFNGGCBJKC = DPMFAJPEFOL_readData.BBPHAPFBFHK;
			DPMFAJPEFOL_data.IJEKNCDIIAE = DPMFAJPEFOL_readData.OFMGALJGDAO;
			DPMFAJPEFOL_data.PLALNIIBLOF = DPMFAJPEFOL_readData.CFLMCGOJJJD;
			DPMFAJPEFOL_data.FJFCNGNGIBN = DPMFAJPEFOL_readData.DEIHLMHACCH;
			DPMFAJPEFOL_data.CPKMLLNADLJ = DPMFAJPEFOL_readData.LMLNKHMPOIG;
			DPMFAJPEFOL_data.FBFLDFMFFOH = DPMFAJPEFOL_readData.ODBPKGJPLMD;
			DPMFAJPEFOL_data.MLMCEBBDJOE = DPMFAJPEFOL_readData.JHAMBKOEJPL;
			DPMFAJPEFOL_data.ODNILEDOAIP = DPMFAJPEFOL_readData.MJHPFNPCLBD;
			DPMFAJPEFOL_data.NPPGKNGIFGK = DPMFAJPEFOL_readData.JDKBBEIBJBD;
			DPMFAJPEFOL_list.Add(DPMFAJPEFOL_data);
		}
		res_data.DPMFAJPEFOL = DPMFAJPEFOL_list.ToArray();

		List<IJLIGDANLAG> NGJHCGBNCNL_list = new List<IJLIGDANLAG>();
		for(int NGJHCGBNCNL_idx = 0; NGJHCGBNCNL_idx < res_readData.IEAIJABOLIDLength; NGJHCGBNCNL_idx++)
		{
			BEILOHDFALJ NGJHCGBNCNL_readData = res_readData.GetIEAIJABOLID(NGJHCGBNCNL_idx);
			IJLIGDANLAG NGJHCGBNCNL_data = new IJLIGDANLAG();

			NGJHCGBNCNL_data.PPFNGGCBJKC = NGJHCGBNCNL_readData.BBPHAPFBFHK;
			NGJHCGBNCNL_data.IJEKNCDIIAE = NGJHCGBNCNL_readData.OFMGALJGDAO;
			NGJHCGBNCNL_data.PLALNIIBLOF = NGJHCGBNCNL_readData.CFLMCGOJJJD;
			NGJHCGBNCNL_data.GBJFNGCDKPM = NGJHCGBNCNL_readData.LPJPOOHJKAE;
			NGJHCGBNCNL_data.FJFCNGNGIBN = NGJHCGBNCNL_readData.DEIHLMHACCH;
			NGJHCGBNCNL_data.CPKMLLNADLJ = NGJHCGBNCNL_readData.LMLNKHMPOIG;
			NGJHCGBNCNL_data.FBFLDFMFFOH = NGJHCGBNCNL_readData.ODBPKGJPLMD;
			NGJHCGBNCNL_data.FAKNMCIIAEM = NGJHCGBNCNL_readData.EMGBMDNPBIC;
			NGJHCGBNCNL_data.KPECMLFDLOI = NGJHCGBNCNL_readData.DMEMJNAEDHP;
			NGJHCGBNCNL_data.NGILPOOLBCF = NGJHCGBNCNL_readData.PJEDCALAIFP;
			NGJHCGBNCNL_data.JINEKNIBOFI = NGJHCGBNCNL_readData.KCEANJAMDBD;
			NGJHCGBNCNL_data.IHLFAPCIBJB = NGJHCGBNCNL_readData.DJCABBBPOPB;
			NGJHCGBNCNL_data.CMMNFCJNIOO = NGJHCGBNCNL_readData.OJFAPOIKHNG;
			NGJHCGBNCNL_data.FPOMEEJFBIG = NGJHCGBNCNL_readData.AEAKMMJLLDK;
			NGJHCGBNCNL_data.KEJMJPHFFOJ = NGJHCGBNCNL_readData.HMNFFFLCANH;
			NGJHCGBNCNL_data.MLMCEBBDJOE = NGJHCGBNCNL_readData.JHAMBKOEJPL;
			NGJHCGBNCNL_data.ODNILEDOAIP = NGJHCGBNCNL_readData.MJHPFNPCLBD;
			NGJHCGBNCNL_data.NPPGKNGIFGK = NGJHCGBNCNL_readData.JDKBBEIBJBD;
			NGJHCGBNCNL_list.Add(NGJHCGBNCNL_data);
		}
		res_data.NGJHCGBNCNL = NGJHCGBNCNL_list.ToArray();

		List<GJLHLFLOCGJ> HLKGADDBKDB_list = new List<GJLHLFLOCGJ>();
		for(int HLKGADDBKDB_idx = 0; HLKGADDBKDB_idx < res_readData.ICJLGDHMIEALength; HLKGADDBKDB_idx++)
		{
			NPBONKLNFED HLKGADDBKDB_readData = res_readData.GetICJLGDHMIEA(HLKGADDBKDB_idx);
			GJLHLFLOCGJ HLKGADDBKDB_data = new GJLHLFLOCGJ();

			HLKGADDBKDB_data.PPFNGGCBJKC = HLKGADDBKDB_readData.BBPHAPFBFHK;
			HLKGADDBKDB_data.IJEKNCDIIAE = HLKGADDBKDB_readData.OFMGALJGDAO;
			HLKGADDBKDB_data.PLALNIIBLOF = HLKGADDBKDB_readData.CFLMCGOJJJD;
			HLKGADDBKDB_data.CPKMLLNADLJ = HLKGADDBKDB_readData.LMLNKHMPOIG;
			HLKGADDBKDB_data.FBFLDFMFFOH = HLKGADDBKDB_readData.ODBPKGJPLMD;
			HLKGADDBKDB_data.KEJMJPHFFOJ = HLKGADDBKDB_readData.HMNFFFLCANH;
			HLKGADDBKDB_data.MLMCEBBDJOE = HLKGADDBKDB_readData.JHAMBKOEJPL;
			HLKGADDBKDB_data.ODNILEDOAIP = HLKGADDBKDB_readData.MJHPFNPCLBD;
			HLKGADDBKDB_data.NPPGKNGIFGK = HLKGADDBKDB_readData.JDKBBEIBJBD;
			HLKGADDBKDB_list.Add(HLKGADDBKDB_data);
		}
		res_data.HLKGADDBKDB = HLKGADDBKDB_list.ToArray();

		List<JLFONMFLBHF> NNCJEMHAIMC_list = new List<JLFONMFLBHF>();
		for(int NNCJEMHAIMC_idx = 0; NNCJEMHAIMC_idx < res_readData.IHLFHOBNKENLength; NNCJEMHAIMC_idx++)
		{
			BOPHBBPHOBP NNCJEMHAIMC_readData = res_readData.GetIHLFHOBNKEN(NNCJEMHAIMC_idx);
			JLFONMFLBHF NNCJEMHAIMC_data = new JLFONMFLBHF();

			NNCJEMHAIMC_data.PPFNGGCBJKC = NNCJEMHAIMC_readData.BBPHAPFBFHK;
			NNCJEMHAIMC_data.IJEKNCDIIAE = NNCJEMHAIMC_readData.OFMGALJGDAO;
			NNCJEMHAIMC_data.PLALNIIBLOF = NNCJEMHAIMC_readData.CFLMCGOJJJD;
			NNCJEMHAIMC_data.GBJFNGCDKPM = NNCJEMHAIMC_readData.LPJPOOHJKAE;
			NNCJEMHAIMC_data.FJFCNGNGIBN = NNCJEMHAIMC_readData.DEIHLMHACCH;
			NNCJEMHAIMC_data.DMEDKJPOLCH = NNCJEMHAIMC_readData.ADCLAGBHDBC;
			NNCJEMHAIMC_data.CPKMLLNADLJ = NNCJEMHAIMC_readData.LMLNKHMPOIG;
			NNCJEMHAIMC_data.FBFLDFMFFOH = NNCJEMHAIMC_readData.ODBPKGJPLMD;
			NNCJEMHAIMC_data.FAKNMCIIAEM = NNCJEMHAIMC_readData.EMGBMDNPBIC;
			NNCJEMHAIMC_data.KPECMLFDLOI = NNCJEMHAIMC_readData.DMEMJNAEDHP;
			NNCJEMHAIMC_data.NGILPOOLBCF = NNCJEMHAIMC_readData.PJEDCALAIFP;
			NNCJEMHAIMC_data.JINEKNIBOFI = NNCJEMHAIMC_readData.KCEANJAMDBD;
			NNCJEMHAIMC_data.IHLFAPCIBJB = NNCJEMHAIMC_readData.DJCABBBPOPB;
			NNCJEMHAIMC_data.CMMNFCJNIOO = NNCJEMHAIMC_readData.OJFAPOIKHNG;
			NNCJEMHAIMC_data.GLCLFMGPMAN = NNCJEMHAIMC_readData.MBBJMJAAODG;
			NNCJEMHAIMC_data.JJPDPNJFBHN = NNCJEMHAIMC_readData.GFAJCKHBDHL;
			NNCJEMHAIMC_list.Add(NNCJEMHAIMC_data);
		}
		res_data.NNCJEMHAIMC = NNCJEMHAIMC_list.ToArray();

		List<JBFPJEDOMLM> JMFICAHELIK_list = new List<JBFPJEDOMLM>();
		for(int JMFICAHELIK_idx = 0; JMFICAHELIK_idx < res_readData.HANOBLAKEKMLength; JMFICAHELIK_idx++)
		{
			CIGCHPCDJEH JMFICAHELIK_readData = res_readData.GetHANOBLAKEKM(JMFICAHELIK_idx);
			JBFPJEDOMLM JMFICAHELIK_data = new JBFPJEDOMLM();

			JMFICAHELIK_data.PPFNGGCBJKC = JMFICAHELIK_readData.BBPHAPFBFHK;
			JMFICAHELIK_data.IGKCGELCEBD = JMFICAHELIK_readData.OJDNBBILGJC;
			List<int> KONAMNAICNJ_list = new List<int>();
			for(int KONAMNAICNJ_idx = 0; KONAMNAICNJ_idx < JMFICAHELIK_readData.HDHGOLJEKBALength; KONAMNAICNJ_idx++)
			{
				KONAMNAICNJ_list.Add(JMFICAHELIK_readData.GetHDHGOLJEKBA(KONAMNAICNJ_idx));
			}
			JMFICAHELIK_data.KONAMNAICNJ = KONAMNAICNJ_list.ToArray();

			List<int> JAHIGOPCJBG_list = new List<int>();
			for(int JAHIGOPCJBG_idx = 0; JAHIGOPCJBG_idx < JMFICAHELIK_readData.MBAHAELMJLMLength; JAHIGOPCJBG_idx++)
			{
				JAHIGOPCJBG_list.Add(JMFICAHELIK_readData.GetMBAHAELMJLM(JAHIGOPCJBG_idx));
			}
			JMFICAHELIK_data.JAHIGOPCJBG = JAHIGOPCJBG_list.ToArray();

			JMFICAHELIK_list.Add(JMFICAHELIK_data);
		}
		res_data.JMFICAHELIK = JMFICAHELIK_list.ToArray();

		List<IPFNMBJGFFB> CEPBAOMAHNH_list = new List<IPFNMBJGFFB>();
		for(int CEPBAOMAHNH_idx = 0; CEPBAOMAHNH_idx < res_readData.MMKDCMGIEKMLength; CEPBAOMAHNH_idx++)
		{
			OLIHMDDCGNO CEPBAOMAHNH_readData = res_readData.GetMMKDCMGIEKM(CEPBAOMAHNH_idx);
			IPFNMBJGFFB CEPBAOMAHNH_data = new IPFNMBJGFFB();

			CEPBAOMAHNH_data.PPFNGGCBJKC = CEPBAOMAHNH_readData.BBPHAPFBFHK;
			CEPBAOMAHNH_data.IJEKNCDIIAE = CEPBAOMAHNH_readData.OFMGALJGDAO;
			CEPBAOMAHNH_data.PLALNIIBLOF = CEPBAOMAHNH_readData.CFLMCGOJJJD;
			CEPBAOMAHNH_data.JBFLEDKDFCO = CEPBAOMAHNH_readData.HOENDPOGFIO;
			CEPBAOMAHNH_data.GBJFNGCDKPM = CEPBAOMAHNH_readData.LPJPOOHJKAE;
			CEPBAOMAHNH_data.CPKMLLNADLJ = CEPBAOMAHNH_readData.LMLNKHMPOIG;
			CEPBAOMAHNH_data.FBFLDFMFFOH = CEPBAOMAHNH_readData.ODBPKGJPLMD;
			CEPBAOMAHNH_data.MLMCEBBDJOE = CEPBAOMAHNH_readData.JHAMBKOEJPL;
			CEPBAOMAHNH_data.ODNILEDOAIP = CEPBAOMAHNH_readData.MJHPFNPCLBD;
			CEPBAOMAHNH_data.NPPGKNGIFGK = CEPBAOMAHNH_readData.JDKBBEIBJBD;
			List<int> GNKMHCKFADN_list = new List<int>();
			for(int GNKMHCKFADN_idx = 0; GNKMHCKFADN_idx < CEPBAOMAHNH_readData.ONFIAKMPBCKLength; GNKMHCKFADN_idx++)
			{
				GNKMHCKFADN_list.Add(CEPBAOMAHNH_readData.GetONFIAKMPBCK(GNKMHCKFADN_idx));
			}
			CEPBAOMAHNH_data.GNKMHCKFADN = GNKMHCKFADN_list.ToArray();

			CEPBAOMAHNH_list.Add(CEPBAOMAHNH_data);
		}
		res_data.CEPBAOMAHNH = CEPBAOMAHNH_list.ToArray();

		List<JCNADBBMELP> OOEMJCHLAKD_list = new List<JCNADBBMELP>();
		for(int OOEMJCHLAKD_idx = 0; OOEMJCHLAKD_idx < res_readData.HOMGLAADLBLLength; OOEMJCHLAKD_idx++)
		{
			CMACEEIOAPP OOEMJCHLAKD_readData = res_readData.GetHOMGLAADLBL(OOEMJCHLAKD_idx);
			JCNADBBMELP OOEMJCHLAKD_data = new JCNADBBMELP();

			OOEMJCHLAKD_data.PPFNGGCBJKC = OOEMJCHLAKD_readData.BBPHAPFBFHK;
			OOEMJCHLAKD_data.IJEKNCDIIAE = OOEMJCHLAKD_readData.OFMGALJGDAO;
			OOEMJCHLAKD_data.PLALNIIBLOF = OOEMJCHLAKD_readData.CFLMCGOJJJD;
			OOEMJCHLAKD_data.FLLNHNJFIFL = OOEMJCHLAKD_readData.EBPIAGLECII;
			OOEMJCHLAKD_data.PDBPFJJCADD = OOEMJCHLAKD_readData.NJLJEKDBPCH;
			OOEMJCHLAKD_data.FDBNFFNFOND = OOEMJCHLAKD_readData.MAOAGDBDBIB;
			OOEMJCHLAKD_list.Add(OOEMJCHLAKD_data);
		}
		res_data.OOEMJCHLAKD = OOEMJCHLAKD_list.ToArray();

		List<HAJOGKOEFID> BHGDNGHDDAC_list = new List<HAJOGKOEFID>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			DKMEHGBGCPO BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			HAJOGKOEFID BHGDNGHDDAC_data = new HAJOGKOEFID();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<AGLIIECMMKO> MHGMDJNOLMI_list = new List<AGLIIECMMKO>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			KHFKCGEANFO MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			AGLIIECMMKO MHGMDJNOLMI_data = new AGLIIECMMKO();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		return res_data;
	}
}
