using FlatBuffers;
using System.Collections.Generic;

public class OANCBKFMLFB
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public uint FJFCNGNGIBN_Attribute { get; set; } // 0x14 PKNMGMMCPPJ OCNDKILHCJK_get_Attribute NMEEPJEFADN_set_Attribute
	public uint CPKMLLNADLJ_Serie { get; set; } // 0x18 COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
	public uint FBFLDFMFFOH_rar { get; set; } // 0x1C LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public int MLMCEBBDJOE { get; set; } // 0x20 LNGPPHKHGMH IGMHCODOFKG_get_ IIIGDLGGEGK_set_
	public int ODNILEDOAIP { get; set; } // 0x24 LMNIPCGLCCM GNKPMBBAJHI_get_ PPMACIMALAC_set_
	public int NPPGKNGIFGK_price { get; set; } // 0x28 JDJKLDMOMGO FLMDBAFHDNJ_get_price DIHIEJPOCOJ_set_price
}
public class IJLIGDANLAG
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public int FJFCNGNGIBN_Attribute { get; set; } // 0x18 PKNMGMMCPPJ OCNDKILHCJK_get_Attribute NMEEPJEFADN_set_Attribute
	public uint CPKMLLNADLJ_Serie { get; set; } // 0x1C COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
	public uint FBFLDFMFFOH_rar { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public uint FAKNMCIIAEM_IsAutoFlip { get; set; } // 0x24 CLELCODBOBF CGDPJCABPDB_get_IsAutoFlip JJFPNFCDNIC_set_IsAutoFlip
	public uint KPECMLFDLOI_pri { get; set; } // 0x28 CIGDCGJELBI ILFJIGDCGBK_get_pri DOGEFDDMBDM_set_pri
	public int NGILPOOLBCF_OffsetX { get; set; } // 0x2C JHEFBAFILNF EDGHLAHGBFN_get_OffsetX LFCKFNLGFCN_set_OffsetX
	public int JINEKNIBOFI_OffsetY { get; set; } // 0x30 KPHFGIFBIJA LKDHAPEGCPH_get_OffsetY PBPDONPMGNF_set_OffsetY
	public int IHLFAPCIBJB { get; set; } // 0x34 AOLAIPDAKCJ PJPNMBNCAKK_get_ OJMLOLMALOI_set_
	public uint CMMNFCJNIOO_IsOnShelf { get; set; } // 0x38 OJPKPMGMBEH IPBHOIGBNEO_get_IsOnShelf EACBGCGAKLO_set_IsOnShelf
	public int FPOMEEJFBIG_odr { get; set; } // 0x3C PJKJIFMIFDJ OEEBAHNAPEC_get_odr BEHAPLPPLNE_set_odr
	public int KEJMJPHFFOJ_Max { get; set; } // 0x40 NNGEOJMHAEA FMNMLNIALNE_get_Max GBEPCBPOGDB_set_Max
	public int MLMCEBBDJOE { get; set; } // 0x44 LNGPPHKHGMH IGMHCODOFKG_get_ IIIGDLGGEGK_set_
	public int ODNILEDOAIP { get; set; } // 0x48 LMNIPCGLCCM GNKPMBBAJHI_get_ PPMACIMALAC_set_
	public int NPPGKNGIFGK_price { get; set; } // 0x4C JDJKLDMOMGO FLMDBAFHDNJ_get_price DIHIEJPOCOJ_set_price
}
public class GJLHLFLOCGJ
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public uint CPKMLLNADLJ_Serie { get; set; } // 0x14 COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
	public uint FBFLDFMFFOH_rar { get; set; } // 0x18 LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public int KEJMJPHFFOJ_Max { get; set; } // 0x1C NNGEOJMHAEA FMNMLNIALNE_get_Max GBEPCBPOGDB_set_Max
	public int MLMCEBBDJOE { get; set; } // 0x20 LNGPPHKHGMH IGMHCODOFKG_get_ IIIGDLGGEGK_set_
	public int ODNILEDOAIP { get; set; } // 0x24 LMNIPCGLCCM GNKPMBBAJHI_get_ PPMACIMALAC_set_
	public int NPPGKNGIFGK_price { get; set; } // 0x28 JDJKLDMOMGO FLMDBAFHDNJ_get_price DIHIEJPOCOJ_set_price
}
public class JLFONMFLBHF
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int GBJFNGCDKPM_typ { get; set; } // 0x14 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public int FJFCNGNGIBN_Attribute { get; set; } // 0x18 PKNMGMMCPPJ OCNDKILHCJK_get_Attribute NMEEPJEFADN_set_Attribute
	public uint DMEDKJPOLCH_cat { get; set; } // 0x1C JAEJJPMKMFI IPKCKAAEEOE_get_cat JOGLLINFLJN_set_cat
	public uint CPKMLLNADLJ_Serie { get; set; } // 0x20 COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
	public uint FBFLDFMFFOH_rar { get; set; } // 0x24 LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public uint FAKNMCIIAEM_IsAutoFlip { get; set; } // 0x28 CLELCODBOBF CGDPJCABPDB_get_IsAutoFlip JJFPNFCDNIC_set_IsAutoFlip
	public uint KPECMLFDLOI_pri { get; set; } // 0x2C CIGDCGJELBI ILFJIGDCGBK_get_pri DOGEFDDMBDM_set_pri
	public int NGILPOOLBCF_OffsetX { get; set; } // 0x30 JHEFBAFILNF EDGHLAHGBFN_get_OffsetX LFCKFNLGFCN_set_OffsetX
	public int JINEKNIBOFI_OffsetY { get; set; } // 0x34 KPHFGIFBIJA LKDHAPEGCPH_get_OffsetY PBPDONPMGNF_set_OffsetY
	public int IHLFAPCIBJB { get; set; } // 0x38 AOLAIPDAKCJ PJPNMBNCAKK_get_ OJMLOLMALOI_set_
	public uint CMMNFCJNIOO_IsOnShelf { get; set; } // 0x3C OJPKPMGMBEH IPBHOIGBNEO_get_IsOnShelf EACBGCGAKLO_set_IsOnShelf
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x40 KCELNMGLKHH LNJAENEGDEL_get_ItemId JHIDBGCHOKL_set_ItemId
	public int JJPDPNJFBHN_TableId { get; set; } // 0x44 BHLPKBCBIAE OFDIOBMHMHA_get_TableId PLFBKOJLLEG_set_TableId
}
public class JBFPJEDOMLM
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IGKCGELCEBD { get; set; } // 0xC AIMLABKMDPN LFEHAAKBIHB_get_ CGJGGKEKFLK_set_
	public int[] KONAMNAICNJ { get; set; } // 0x10 MGIFEIKKFAM LJFCKOAHMLF_get_ MOPOAENNHDF_set_
	public int[] JAHIGOPCJBG { get; set; } // 0x14 LAGBMDEGDCP CNMDIPDMDOC_get_ MGBJPOJMBON_set_
}
public class IPFNMBJGFFB
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public uint PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int JBFLEDKDFCO_cid { get; set; } // 0x14 JOECCKJHICK LIJMKJLDHGP_get_cid NFNCLFPPADP_set_cid
	public int GBJFNGCDKPM_typ { get; set; } // 0x18 GHLFADHILNN CEJJMKODOGK_get_typ HOHCEBMMACI_set_typ
	public uint CPKMLLNADLJ_Serie { get; set; } // 0x1C COPJCMLLIMO BJPJMGHCDNO_get_Serie BPKIOJBKNBP_set_Serie
	public uint FBFLDFMFFOH_rar { get; set; } // 0x20 LMKEDCAPLEE HNLMNIOMOLI_get_rar CHHJKABBIBL_set_rar
	public int MLMCEBBDJOE { get; set; } // 0x24 LNGPPHKHGMH IGMHCODOFKG_get_ IIIGDLGGEGK_set_
	public int ODNILEDOAIP { get; set; } // 0x28 LMNIPCGLCCM GNKPMBBAJHI_get_ PPMACIMALAC_set_
	public int NPPGKNGIFGK_price { get; set; } // 0x2C JDJKLDMOMGO FLMDBAFHDNJ_get_price DIHIEJPOCOJ_set_price
	public int[] GNKMHCKFADN_stamp { get; set; } // 0x30 JCJPDGBHLCA MBODMLHJCML_get_stamp PGBABMMAOKI_set_stamp
}
public class JCNADBBMELP
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int IJEKNCDIIAE_mver { get; set; } // 0xC FAHNCMHNFCG KJIMMIBDCIL_get_mver DMEGNOKIKCD_set_mver
	public int PLALNIIBLOF_en { get; set; } // 0x10 DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int FLLNHNJFIFL { get; set; } // 0x14 PKFLEPBDGJH BONCEKFANMH_get_ HCCOHHKDDHI_set_
	public int PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC_get_open_at NBACOBCOJCA_set_open_at
	public int FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ_get_close_at NLJKMCHOCBK_set_close_at
}
public class HAJOGKOEFID
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class AGLIIECMMKO
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM_get_key OACJGKPBHIK_set_key
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON_get_val ABAFHIBFKCE_set_val
}
public class NLFIKMMPOAL
{
	public OANCBKFMLFB[] DPMFAJPEFOL { get; set; } // 0x8 AEBFMDIMDLE JJHADCINGOE_get_ KFBMIPBJPJJ_set_
	public IJLIGDANLAG[] NGJHCGBNCNL { get; set; } // 0xC MIJLONLBHHE POJACBMCHGP_get_ GBKAMCDCIBA_set_
	public GJLHLFLOCGJ[] HLKGADDBKDB { get; set; } // 0x10 ABLDBGHEFAO DBKKMKFKMIC_get_ OIAJIDADJLG_set_
	public JLFONMFLBHF[] NNCJEMHAIMC { get; set; } // 0x14 OPMDONDPIJL PGMMLNOOHHP_get_ LKFHCLBCGEL_set_
	public JBFPJEDOMLM[] JMFICAHELIK { get; set; } // 0x18 MPNEFPBGAOI CGMKMGFEMPA_get_ KFMGOBOEHBC_set_
	public IPFNMBJGFFB[] CEPBAOMAHNH { get; set; } // 0x1C EALHHHABHEI KJBLMCHIKFD_get_ OEBMOJPBAEF_set_
	public JCNADBBMELP[] OOEMJCHLAKD { get; set; } // 0x20 FCEKMMDHAIC FINKADBKKPO_get_ BJFEEMEENDD_set_
	public HAJOGKOEFID[] BHGDNGHDDAC { get; set; } // 0x24 JHDNDHBDFFI CEHHJMMMCID_get_ EDOEOHENKDG_set_
	public AGLIIECMMKO[] MHGMDJNOLMI { get; set; } // 0x28 JBFEKPIDNIC NFFJJGMEEOB_get_ BGEFBFOAMPK_set_
	public static NLFIKMMPOAL HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xC2E554
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		MOHBMMEAEON res_readData_ = MOHBMMEAEON.GetRootAsMOHBMMEAEON(buffer);
		NLFIKMMPOAL res_data_ = new NLFIKMMPOAL();

		List<OANCBKFMLFB> DPMFAJPEFOL_list_ = new List<OANCBKFMLFB>();
		for(int DPMFAJPEFOL_idx_ = 0; DPMFAJPEFOL_idx_ < res_readData_.IJOFIDAFJGALength; DPMFAJPEFOL_idx_++)
		{
			APKGJCPIHGB DPMFAJPEFOL_readData_ = res_readData_.GetIJOFIDAFJGA(DPMFAJPEFOL_idx_);
			OANCBKFMLFB DPMFAJPEFOL_data_ = new OANCBKFMLFB();

			DPMFAJPEFOL_data_.PPFNGGCBJKC_id = DPMFAJPEFOL_readData_.BBPHAPFBFHK/*_id*/;
			DPMFAJPEFOL_data_.IJEKNCDIIAE_mver = DPMFAJPEFOL_readData_.OFMGALJGDAO/*_mver*/;
			DPMFAJPEFOL_data_.PLALNIIBLOF_en = DPMFAJPEFOL_readData_.CFLMCGOJJJD/*_en*/;
			DPMFAJPEFOL_data_.FJFCNGNGIBN_Attribute = DPMFAJPEFOL_readData_.DEIHLMHACCH/*_Attribute*/;
			DPMFAJPEFOL_data_.CPKMLLNADLJ_Serie = DPMFAJPEFOL_readData_.LMLNKHMPOIG/*_Serie*/;
			DPMFAJPEFOL_data_.FBFLDFMFFOH_rar = DPMFAJPEFOL_readData_.ODBPKGJPLMD/*_rar*/;
			DPMFAJPEFOL_data_.MLMCEBBDJOE = DPMFAJPEFOL_readData_.JHAMBKOEJPL;
			DPMFAJPEFOL_data_.ODNILEDOAIP = DPMFAJPEFOL_readData_.MJHPFNPCLBD;
			DPMFAJPEFOL_data_.NPPGKNGIFGK_price = DPMFAJPEFOL_readData_.JDKBBEIBJBD/*_price*/;
			DPMFAJPEFOL_list_.Add(DPMFAJPEFOL_data_);
		}
		res_data_.DPMFAJPEFOL = DPMFAJPEFOL_list_.ToArray();

		List<IJLIGDANLAG> NGJHCGBNCNL_list_ = new List<IJLIGDANLAG>();
		for(int NGJHCGBNCNL_idx_ = 0; NGJHCGBNCNL_idx_ < res_readData_.IEAIJABOLIDLength; NGJHCGBNCNL_idx_++)
		{
			BEILOHDFALJ NGJHCGBNCNL_readData_ = res_readData_.GetIEAIJABOLID(NGJHCGBNCNL_idx_);
			IJLIGDANLAG NGJHCGBNCNL_data_ = new IJLIGDANLAG();

			NGJHCGBNCNL_data_.PPFNGGCBJKC_id = NGJHCGBNCNL_readData_.BBPHAPFBFHK/*_id*/;
			NGJHCGBNCNL_data_.IJEKNCDIIAE_mver = NGJHCGBNCNL_readData_.OFMGALJGDAO/*_mver*/;
			NGJHCGBNCNL_data_.PLALNIIBLOF_en = NGJHCGBNCNL_readData_.CFLMCGOJJJD/*_en*/;
			NGJHCGBNCNL_data_.GBJFNGCDKPM_typ = NGJHCGBNCNL_readData_.LPJPOOHJKAE/*_typ*/;
			NGJHCGBNCNL_data_.FJFCNGNGIBN_Attribute = NGJHCGBNCNL_readData_.DEIHLMHACCH/*_Attribute*/;
			NGJHCGBNCNL_data_.CPKMLLNADLJ_Serie = NGJHCGBNCNL_readData_.LMLNKHMPOIG/*_Serie*/;
			NGJHCGBNCNL_data_.FBFLDFMFFOH_rar = NGJHCGBNCNL_readData_.ODBPKGJPLMD/*_rar*/;
			NGJHCGBNCNL_data_.FAKNMCIIAEM_IsAutoFlip = NGJHCGBNCNL_readData_.EMGBMDNPBIC/*_IsAutoFlip*/;
			NGJHCGBNCNL_data_.KPECMLFDLOI_pri = NGJHCGBNCNL_readData_.DMEMJNAEDHP/*_pri*/;
			NGJHCGBNCNL_data_.NGILPOOLBCF_OffsetX = NGJHCGBNCNL_readData_.PJEDCALAIFP/*_OffsetX*/;
			NGJHCGBNCNL_data_.JINEKNIBOFI_OffsetY = NGJHCGBNCNL_readData_.KCEANJAMDBD/*_OffsetY*/;
			NGJHCGBNCNL_data_.IHLFAPCIBJB = NGJHCGBNCNL_readData_.DJCABBBPOPB;
			NGJHCGBNCNL_data_.CMMNFCJNIOO_IsOnShelf = NGJHCGBNCNL_readData_.OJFAPOIKHNG/*_IsOnShelf*/;
			NGJHCGBNCNL_data_.FPOMEEJFBIG_odr = NGJHCGBNCNL_readData_.AEAKMMJLLDK/*_odr*/;
			NGJHCGBNCNL_data_.KEJMJPHFFOJ_Max = NGJHCGBNCNL_readData_.HMNFFFLCANH/*_Max*/;
			NGJHCGBNCNL_data_.MLMCEBBDJOE = NGJHCGBNCNL_readData_.JHAMBKOEJPL;
			NGJHCGBNCNL_data_.ODNILEDOAIP = NGJHCGBNCNL_readData_.MJHPFNPCLBD;
			NGJHCGBNCNL_data_.NPPGKNGIFGK_price = NGJHCGBNCNL_readData_.JDKBBEIBJBD/*_price*/;
			NGJHCGBNCNL_list_.Add(NGJHCGBNCNL_data_);
		}
		res_data_.NGJHCGBNCNL = NGJHCGBNCNL_list_.ToArray();

		List<GJLHLFLOCGJ> HLKGADDBKDB_list_ = new List<GJLHLFLOCGJ>();
		for(int HLKGADDBKDB_idx_ = 0; HLKGADDBKDB_idx_ < res_readData_.ICJLGDHMIEALength; HLKGADDBKDB_idx_++)
		{
			NPBONKLNFED HLKGADDBKDB_readData_ = res_readData_.GetICJLGDHMIEA(HLKGADDBKDB_idx_);
			GJLHLFLOCGJ HLKGADDBKDB_data_ = new GJLHLFLOCGJ();

			HLKGADDBKDB_data_.PPFNGGCBJKC_id = HLKGADDBKDB_readData_.BBPHAPFBFHK/*_id*/;
			HLKGADDBKDB_data_.IJEKNCDIIAE_mver = HLKGADDBKDB_readData_.OFMGALJGDAO/*_mver*/;
			HLKGADDBKDB_data_.PLALNIIBLOF_en = HLKGADDBKDB_readData_.CFLMCGOJJJD/*_en*/;
			HLKGADDBKDB_data_.CPKMLLNADLJ_Serie = HLKGADDBKDB_readData_.LMLNKHMPOIG/*_Serie*/;
			HLKGADDBKDB_data_.FBFLDFMFFOH_rar = HLKGADDBKDB_readData_.ODBPKGJPLMD/*_rar*/;
			HLKGADDBKDB_data_.KEJMJPHFFOJ_Max = HLKGADDBKDB_readData_.HMNFFFLCANH/*_Max*/;
			HLKGADDBKDB_data_.MLMCEBBDJOE = HLKGADDBKDB_readData_.JHAMBKOEJPL;
			HLKGADDBKDB_data_.ODNILEDOAIP = HLKGADDBKDB_readData_.MJHPFNPCLBD;
			HLKGADDBKDB_data_.NPPGKNGIFGK_price = HLKGADDBKDB_readData_.JDKBBEIBJBD/*_price*/;
			HLKGADDBKDB_list_.Add(HLKGADDBKDB_data_);
		}
		res_data_.HLKGADDBKDB = HLKGADDBKDB_list_.ToArray();

		List<JLFONMFLBHF> NNCJEMHAIMC_list_ = new List<JLFONMFLBHF>();
		for(int NNCJEMHAIMC_idx_ = 0; NNCJEMHAIMC_idx_ < res_readData_.IHLFHOBNKENLength; NNCJEMHAIMC_idx_++)
		{
			BOPHBBPHOBP NNCJEMHAIMC_readData_ = res_readData_.GetIHLFHOBNKEN(NNCJEMHAIMC_idx_);
			JLFONMFLBHF NNCJEMHAIMC_data_ = new JLFONMFLBHF();

			NNCJEMHAIMC_data_.PPFNGGCBJKC_id = NNCJEMHAIMC_readData_.BBPHAPFBFHK/*_id*/;
			NNCJEMHAIMC_data_.IJEKNCDIIAE_mver = NNCJEMHAIMC_readData_.OFMGALJGDAO/*_mver*/;
			NNCJEMHAIMC_data_.PLALNIIBLOF_en = NNCJEMHAIMC_readData_.CFLMCGOJJJD/*_en*/;
			NNCJEMHAIMC_data_.GBJFNGCDKPM_typ = NNCJEMHAIMC_readData_.LPJPOOHJKAE/*_typ*/;
			NNCJEMHAIMC_data_.FJFCNGNGIBN_Attribute = NNCJEMHAIMC_readData_.DEIHLMHACCH/*_Attribute*/;
			NNCJEMHAIMC_data_.DMEDKJPOLCH_cat = NNCJEMHAIMC_readData_.ADCLAGBHDBC/*_cat*/;
			NNCJEMHAIMC_data_.CPKMLLNADLJ_Serie = NNCJEMHAIMC_readData_.LMLNKHMPOIG/*_Serie*/;
			NNCJEMHAIMC_data_.FBFLDFMFFOH_rar = NNCJEMHAIMC_readData_.ODBPKGJPLMD/*_rar*/;
			NNCJEMHAIMC_data_.FAKNMCIIAEM_IsAutoFlip = NNCJEMHAIMC_readData_.EMGBMDNPBIC/*_IsAutoFlip*/;
			NNCJEMHAIMC_data_.KPECMLFDLOI_pri = NNCJEMHAIMC_readData_.DMEMJNAEDHP/*_pri*/;
			NNCJEMHAIMC_data_.NGILPOOLBCF_OffsetX = NNCJEMHAIMC_readData_.PJEDCALAIFP/*_OffsetX*/;
			NNCJEMHAIMC_data_.JINEKNIBOFI_OffsetY = NNCJEMHAIMC_readData_.KCEANJAMDBD/*_OffsetY*/;
			NNCJEMHAIMC_data_.IHLFAPCIBJB = NNCJEMHAIMC_readData_.DJCABBBPOPB;
			NNCJEMHAIMC_data_.CMMNFCJNIOO_IsOnShelf = NNCJEMHAIMC_readData_.OJFAPOIKHNG/*_IsOnShelf*/;
			NNCJEMHAIMC_data_.GLCLFMGPMAN_ItemId = NNCJEMHAIMC_readData_.MBBJMJAAODG/*_ItemId*/;
			NNCJEMHAIMC_data_.JJPDPNJFBHN_TableId = NNCJEMHAIMC_readData_.GFAJCKHBDHL/*_TableId*/;
			NNCJEMHAIMC_list_.Add(NNCJEMHAIMC_data_);
		}
		res_data_.NNCJEMHAIMC = NNCJEMHAIMC_list_.ToArray();

		List<JBFPJEDOMLM> JMFICAHELIK_list_ = new List<JBFPJEDOMLM>();
		for(int JMFICAHELIK_idx_ = 0; JMFICAHELIK_idx_ < res_readData_.HANOBLAKEKMLength; JMFICAHELIK_idx_++)
		{
			CIGCHPCDJEH JMFICAHELIK_readData_ = res_readData_.GetHANOBLAKEKM(JMFICAHELIK_idx_);
			JBFPJEDOMLM JMFICAHELIK_data_ = new JBFPJEDOMLM();

			JMFICAHELIK_data_.PPFNGGCBJKC_id = JMFICAHELIK_readData_.BBPHAPFBFHK/*_id*/;
			JMFICAHELIK_data_.IGKCGELCEBD = JMFICAHELIK_readData_.OJDNBBILGJC;
			List<int> KONAMNAICNJ_list_ = new List<int>();
			for(int KONAMNAICNJ_idx_ = 0; KONAMNAICNJ_idx_ < JMFICAHELIK_readData_.HDHGOLJEKBALength; KONAMNAICNJ_idx_++)
			{
				KONAMNAICNJ_list_.Add(JMFICAHELIK_readData_.GetHDHGOLJEKBA(KONAMNAICNJ_idx_));
			}
			JMFICAHELIK_data_.KONAMNAICNJ = KONAMNAICNJ_list_.ToArray();

			List<int> JAHIGOPCJBG_list_ = new List<int>();
			for(int JAHIGOPCJBG_idx_ = 0; JAHIGOPCJBG_idx_ < JMFICAHELIK_readData_.MBAHAELMJLMLength; JAHIGOPCJBG_idx_++)
			{
				JAHIGOPCJBG_list_.Add(JMFICAHELIK_readData_.GetMBAHAELMJLM(JAHIGOPCJBG_idx_));
			}
			JMFICAHELIK_data_.JAHIGOPCJBG = JAHIGOPCJBG_list_.ToArray();

			JMFICAHELIK_list_.Add(JMFICAHELIK_data_);
		}
		res_data_.JMFICAHELIK = JMFICAHELIK_list_.ToArray();

		List<IPFNMBJGFFB> CEPBAOMAHNH_list_ = new List<IPFNMBJGFFB>();
		for(int CEPBAOMAHNH_idx_ = 0; CEPBAOMAHNH_idx_ < res_readData_.MMKDCMGIEKMLength; CEPBAOMAHNH_idx_++)
		{
			OLIHMDDCGNO CEPBAOMAHNH_readData_ = res_readData_.GetMMKDCMGIEKM(CEPBAOMAHNH_idx_);
			IPFNMBJGFFB CEPBAOMAHNH_data_ = new IPFNMBJGFFB();

			CEPBAOMAHNH_data_.PPFNGGCBJKC_id = CEPBAOMAHNH_readData_.BBPHAPFBFHK/*_id*/;
			CEPBAOMAHNH_data_.IJEKNCDIIAE_mver = CEPBAOMAHNH_readData_.OFMGALJGDAO/*_mver*/;
			CEPBAOMAHNH_data_.PLALNIIBLOF_en = CEPBAOMAHNH_readData_.CFLMCGOJJJD/*_en*/;
			CEPBAOMAHNH_data_.JBFLEDKDFCO_cid = CEPBAOMAHNH_readData_.HOENDPOGFIO/*_cid*/;
			CEPBAOMAHNH_data_.GBJFNGCDKPM_typ = CEPBAOMAHNH_readData_.LPJPOOHJKAE/*_typ*/;
			CEPBAOMAHNH_data_.CPKMLLNADLJ_Serie = CEPBAOMAHNH_readData_.LMLNKHMPOIG/*_Serie*/;
			CEPBAOMAHNH_data_.FBFLDFMFFOH_rar = CEPBAOMAHNH_readData_.ODBPKGJPLMD/*_rar*/;
			CEPBAOMAHNH_data_.MLMCEBBDJOE = CEPBAOMAHNH_readData_.JHAMBKOEJPL;
			CEPBAOMAHNH_data_.ODNILEDOAIP = CEPBAOMAHNH_readData_.MJHPFNPCLBD;
			CEPBAOMAHNH_data_.NPPGKNGIFGK_price = CEPBAOMAHNH_readData_.JDKBBEIBJBD/*_price*/;
			List<int> GNKMHCKFADN_list_ = new List<int>();
			for(int GNKMHCKFADN_idx_ = 0; GNKMHCKFADN_idx_ < CEPBAOMAHNH_readData_.ONFIAKMPBCKLength; GNKMHCKFADN_idx_++)
			{
				GNKMHCKFADN_list_.Add(CEPBAOMAHNH_readData_.GetONFIAKMPBCK(GNKMHCKFADN_idx_));
			}
			CEPBAOMAHNH_data_.GNKMHCKFADN_stamp = GNKMHCKFADN_list_.ToArray();

			CEPBAOMAHNH_list_.Add(CEPBAOMAHNH_data_);
		}
		res_data_.CEPBAOMAHNH = CEPBAOMAHNH_list_.ToArray();

		List<JCNADBBMELP> OOEMJCHLAKD_list_ = new List<JCNADBBMELP>();
		for(int OOEMJCHLAKD_idx_ = 0; OOEMJCHLAKD_idx_ < res_readData_.HOMGLAADLBLLength; OOEMJCHLAKD_idx_++)
		{
			CMACEEIOAPP OOEMJCHLAKD_readData_ = res_readData_.GetHOMGLAADLBL(OOEMJCHLAKD_idx_);
			JCNADBBMELP OOEMJCHLAKD_data_ = new JCNADBBMELP();

			OOEMJCHLAKD_data_.PPFNGGCBJKC_id = OOEMJCHLAKD_readData_.BBPHAPFBFHK/*_id*/;
			OOEMJCHLAKD_data_.IJEKNCDIIAE_mver = OOEMJCHLAKD_readData_.OFMGALJGDAO/*_mver*/;
			OOEMJCHLAKD_data_.PLALNIIBLOF_en = OOEMJCHLAKD_readData_.CFLMCGOJJJD/*_en*/;
			OOEMJCHLAKD_data_.FLLNHNJFIFL = OOEMJCHLAKD_readData_.EBPIAGLECII;
			OOEMJCHLAKD_data_.PDBPFJJCADD_open_at = OOEMJCHLAKD_readData_.NJLJEKDBPCH/*_open_at*/;
			OOEMJCHLAKD_data_.FDBNFFNFOND_close_at = OOEMJCHLAKD_readData_.MAOAGDBDBIB/*_close_at*/;
			OOEMJCHLAKD_list_.Add(OOEMJCHLAKD_data_);
		}
		res_data_.OOEMJCHLAKD = OOEMJCHLAKD_list_.ToArray();

		List<HAJOGKOEFID> BHGDNGHDDAC_list_ = new List<HAJOGKOEFID>();
		for(int BHGDNGHDDAC_idx_ = 0; BHGDNGHDDAC_idx_ < res_readData_.NJJINHMIOHNLength; BHGDNGHDDAC_idx_++)
		{
			DKMEHGBGCPO BHGDNGHDDAC_readData_ = res_readData_.GetNJJINHMIOHN(BHGDNGHDDAC_idx_);
			HAJOGKOEFID BHGDNGHDDAC_data_ = new HAJOGKOEFID();

			BHGDNGHDDAC_data_.LJNAKDMILMC_key = BHGDNGHDDAC_readData_.AGOIMGHMGOH/*_key*/;
			BHGDNGHDDAC_data_.JBGEEPFKIGG_val = BHGDNGHDDAC_readData_.KJFEBMBHKOC/*_val*/;
			BHGDNGHDDAC_list_.Add(BHGDNGHDDAC_data_);
		}
		res_data_.BHGDNGHDDAC = BHGDNGHDDAC_list_.ToArray();

		List<AGLIIECMMKO> MHGMDJNOLMI_list_ = new List<AGLIIECMMKO>();
		for(int MHGMDJNOLMI_idx_ = 0; MHGMDJNOLMI_idx_ < res_readData_.NPFBHGKLIOMLength; MHGMDJNOLMI_idx_++)
		{
			KHFKCGEANFO MHGMDJNOLMI_readData_ = res_readData_.GetNPFBHGKLIOM(MHGMDJNOLMI_idx_);
			AGLIIECMMKO MHGMDJNOLMI_data_ = new AGLIIECMMKO();

			MHGMDJNOLMI_data_.LJNAKDMILMC_key = MHGMDJNOLMI_readData_.AGOIMGHMGOH/*_key*/;
			MHGMDJNOLMI_data_.JBGEEPFKIGG_val = MHGMDJNOLMI_readData_.KJFEBMBHKOC/*_val*/;
			MHGMDJNOLMI_list_.Add(MHGMDJNOLMI_data_);
		}
		res_data_.MHGMDJNOLMI = MHGMDJNOLMI_list_.ToArray();

		return res_data_;
	}
}
