using FlatBuffers;
using System.Collections.Generic;

public class DGALLBPNAMN
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD_RankingName { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO_SaveIdx { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint EHHFFKAFOMC { get; set; } // 0x20 MDCEFKJDJIJ EMIPFAAPLIB JHGMJLNGOGD
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x24 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x28 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x2C HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x30 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x34 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JMJDLDEIFKE { get; set; } // 0x38 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO_DayGroup { get; set; } // 0x3C IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x40 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x44 HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public int MJBKGOJBPAD_item_type { get; set; } // 0x48 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public string FEMMDNIELFC_Desc { get; set; } // 0x4C GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint HKKNEAGCIEB_RankingSupport { get; set; } // 0x50 DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI_RankingThreshold { get; set; } // 0x54 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public string OMCAOJJGOGG_Lb { get; set; } // 0x58 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM_StartAdventureId { get; set; } // 0x5C AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP_EndAdventureId { get; set; } // 0x60 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC_HelpIds { get; set; } // 0x64 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int AHKPNPNOAMO_ExtreamOpen { get; set; } // 0x68 AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
}
public class CJHLABKGKAA
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MPLGPBNJDJB_FreeMusicId { get; set; } // 0x10 GNKPHDHIMAC KADAEAOKJNE MBKFNLHPNPP
	public uint HMHHNHEPAPP_BossId { get; set; } // 0x14 HPDAIIGOBPB KFGPMMLMMMD GBHCLENDGGF
	public int PDBPFJJCADD_open_at { get; set; } // 0x18 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND_close_at { get; set; } // 0x1C INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class MJDMKEIPOLH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM_typ { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG_odr { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC_Desc { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE_DescBalloon { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC_item_count { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ_Link { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO_st { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
}
public class MMFFEFPBLCJ
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class FKPLJBFLKAG
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class EPICOEPILEJ
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PDBPFJJCADD_open_at { get; set; } // 0xC PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND_close_at { get; set; } // 0x10 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public string FEMMDNIELFC_Desc { get; set; } // 0x14 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
}
public class KCFGJMAMFCH
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string OPFGFINHFCE_name { get; set; } // 0xC LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int CPKMLLNADLJ_Serie { get; set; } // 0x10 COPJCMLLIMO BJPJMGHCDNO BPKIOJBKNBP
	public int PIPCIMIALOO_sp { get; set; } // 0x14 INBCDPNEACE KJNBPECGBJJ DMAJEBCFHHK
	public int NNLAMKCDMEL { get; set; } // 0x18 JAMOJIECDOM ABKKKEOKALH HAPHPNMCGNM
	public int FCDNMBBPBKI { get; set; } // 0x1C FIPLJBFEFAB PMGBAPBMJNL CPCFBDPJEFB
	public int EPMCPGDIBHI { get; set; } // 0x20 BCCNGAFFIPD EJALPODFNDP IMAFFIMKNLB
	public int AKBHPFBDDOL_Val { get; set; } // 0x24 PHKLEFAKCPE ANBHKALCHDJ GDANPNDMDCC
}
public class LJIJADDCDBE
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int LLNDMKBBNIJ_ver { get; set; } // 0xC BGOALFDCFBL OHMCGADLNCA KJNHDFEGEGE
	public int OMIEMNDOPKA { get; set; } // 0x10 OOOPBMGFJMO BMAKCMKDHDG GMGFODNKLMJ
	public uint ICLFADEFBIH { get; set; } // 0x14 BCCHMFIHAKM PMCKFAGCIIJ OLLGCDNKPJA
	public uint FJOLNJLLJEJ_rank { get; set; } // 0x18 BLIGJGPCOKP EAKAGHDPEMI GHECCGBGCBI
	public uint OJLDNEGBFFG { get; set; } // 0x1C OLADBGMJOKP PAMMJMJOEJF DLAFEFDKAAO
	public uint DIDNBKKKEDK { get; set; } // 0x20 OJKHOCAFJNK JHGAFFFDGGA FBCELIIGMDN
	public uint CAFDIAFJDKP { get; set; } // 0x24 LLGJGNFHDCP DEKDOFLHFFA DGOFIHHOJLH
	public uint EHOBDMHPMHB { get; set; } // 0x28 CHNNFGJGKIK JLNLDGDJHHC DMAJICIEIEF
	public uint DIGJFGFKEJC { get; set; } // 0x2C BIEMJHGOAGI NNNBNBILPEJ HMMFFIMCJBD
	public uint JJELLPDAAEI { get; set; } // 0x30 GFAICJNMGJE ALGANNAIEKC BMFEKMPEONN
}
public class KLBFLPLFPNF
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint JIMJHIDEHNM_ApCounter { get; set; } // 0xC CPFMBIINNNL HMLIMKEFHHD OPHOIBNLNLN
	public uint KMHIOCCFPEM { get; set; } // 0x10 IPFOLAEEPPM LKPCAKHALNB JKOPPHOFGAO
	public uint PIABNPEFLEJ { get; set; } // 0x14 AJMJEOFELAF PLJJFPNFEKO IGGAEINKDPB
	public uint BMAHHKLNOGA { get; set; } // 0x18 FLNDJPEDDNF DJFJNNABHPG FMKAOFFDJIK
	public uint DHGAILOFNIP { get; set; } // 0x1C OMNLCDIPDDK PDPIPLFFJOI IAPIFAEJCKI
}
public class JHBMNFIHGBI
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint GBJFNGCDKPM_typ { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x10 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
}
public class KGNNHHFGLBG
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint[] AIHOJKFNEEN_itm { get; set; } // 0xC GGBFCEFNCFM BGFIPHMMOGA DHAIHODDOGM
	public uint[] BFINGCJHOHI_cnt { get; set; } // 0x10 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public uint[] EHKJFNAABMC_rat { get; set; } // 0x14 FAOHBEIIENC LGFHJLOCEDP BBBACEEAPNI
	public uint[] DOOGFEGEKLG_max { get; set; } // 0x18 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public uint[] DCFAPPHINAO { get; set; } // 0x1C BCAIMBGBHHF KMOAKOFGIPB EFLABJDKOHJ
}
public class DFPOGOFGFBN
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public string FEMMDNIELFC_Desc { get; set; } // 0xC GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint MDNKAFNHNDJ { get; set; } // 0x10 MNAKCGGNNBG GBIIEKLOEJM NPEJICJILAP
	public uint MAAGBAOIFFA { get; set; } // 0x14 HCBNBHLOHOB FBMOJCGJIOA FOEKKDBIIDE
	public uint AIMACNHIPMG { get; set; } // 0x18 ILLJHGNEBLE MBDGDLKOMEO IJLAGFLMIIF
	public uint DJJGNDCMNHF_BonusValue { get; set; } // 0x1C FACIBMKEMCC GEPCOAPEAJM MIFJBBAJAJP
	public uint MCNEIJAOLNO_Select { get; set; } // 0x20 JOMEFAFDJKF BCNJAKOOENE HJGLDPJIANJ
	public uint PENMGPNPHHG_BonusSp { get; set; } // 0x24 BBOMKPKCJOB ANDBDDOKLEC DCEFILHGKEG
	public uint PDJJELPFMJB_RateSp { get; set; } // 0x28 JMKINBBDECP EMCMLADMJEG HPKELCOIHHA
}
public class ALFLHDKBNIB
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int CNKFPJCGNFE_SceneId { get; set; } // 0xC OGPCJNOKMAM GJBOGOFHGNP GJDGIDCMJMH
	public int GNFBMCGMCFO_BonusBefore { get; set; } // 0x10 LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG_BonusAfter { get; set; } // 0x14 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class CNDLLOPINDF
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GNFBMCGMCFO_BonusBefore { get; set; } // 0xC LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG_BonusAfter { get; set; } // 0x10 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class MDDFBKANJDJ
{
	public int KHPHAAMGMJP { get; set; } // 0x8 FHLAGLBMFHE ABFDDKBBPCH MHDOIIEMDEH
	public int OFIAENKCJME { get; set; } // 0xC NHHGGLNCELI KADLAKFANGA AIDAPNCEPOB
	public int[] JMLCLHHLJHM { get; set; } // 0x10 HCOPKKMMEAL KCJKEEAILGB EGEABIGCJJK
}
public class NPAJGBIFLHB
{
	public DGALLBPNAMN HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public CJHLABKGKAA[] GHIHAGAOPNC { get; set; } // 0xC CNAPBHHKEPH OHCBAEGAKOH OIDPGMCLNBF
	public MJDMKEIPOLH[] MDDOGIAFDEI { get; set; } // 0x10 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public MMFFEFPBLCJ[] BHGDNGHDDAC { get; set; } // 0x14 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public FKPLJBFLKAG[] MHGMDJNOLMI { get; set; } // 0x18 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public EPICOEPILEJ[] IHNBOEPLJKE { get; set; } // 0x1C MMGGONDGLOL EMLHCNDOCCP GKPFNDEHLJD
	public KCFGJMAMFCH[] EENBPAPDNBP { get; set; } // 0x20 OENLNBHIPDD OFIFECKLFCF EJDNMOAFHDM
	public LJIJADDCDBE[] JLKPDLCFEIM { get; set; } // 0x24 IFECHAFLBDC JPMPNPBPEDD KKOJJELODLP
	public KLBFLPLFPNF[] JFLFHONDDNM { get; set; } // 0x28 LEDLBPOACAN MOMJNLCHIFB IFHGGPMHIBN
	public JHBMNFIHGBI[] PNMLJIPOOPO { get; set; } // 0x2C DAGODBMEKDN MMPAEDINCIL KDNMGOKMHGO
	public KGNNHHFGLBG[] DOKBJLFIGDM { get; set; } // 0x30 CJMEOILJPNG HEJCOKDEMOF GOJHFDKOEOK
	public DFPOGOFGFBN[] HBMGNHBFPHC { get; set; } // 0x34 IADPBPBIFMF HPHGOKHFOMI CEIDBCLBKOB
	public ALFLHDKBNIB[] OLACFKILCFD { get; set; } // 0x38 ODAEGEAACIA KCGGGPCDEPK ANKJOEMLFCI
	public CNDLLOPINDF[] MIOCOKLMLBD { get; set; } // 0x3C COILMDCEJLD MNIALHMNHFM OGLAMDPDFCD
	public MDDFBKANJDJ[] IEJLJIHIDJC { get; set; } // 0x40 CDHGOELCBFB DGNNDIPELAP BFHEABPGGHO
	public static NPAJGBIFLHB HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x1CB171C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		NBIKKFDBOFF res_readData = NBIKKFDBOFF.GetRootAsNBIKKFDBOFF(buffer);
		NPAJGBIFLHB res_data = new NPAJGBIFLHB();

		GMNMPFMGIBP HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		DGALLBPNAMN HMBHNLCFDIH_data = new DGALLBPNAMN();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD_RankingName = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO_SaveIdx = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.EHHFFKAFOMC = HMBHNLCFDIH_readData.DEPHCHOBAJG;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO_DayGroup = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.MJBKGOJBPAD_item_type = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.FEMMDNIELFC_Desc = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKKNEAGCIEB_RankingSupport = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI_RankingThreshold = JHPCPNJJHLI_list.ToArray();

		HMBHNLCFDIH_data.OMCAOJJGOGG_Lb = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM_StartAdventureId = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP_EndAdventureId = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC_HelpIds = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.AHKPNPNOAMO_ExtreamOpen = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<CJHLABKGKAA> GHIHAGAOPNC_list = new List<CJHLABKGKAA>();
		for(int GHIHAGAOPNC_idx = 0; GHIHAGAOPNC_idx < res_readData.AJMKEFMPKHBLength; GHIHAGAOPNC_idx++)
		{
			PPANHLHGDLD GHIHAGAOPNC_readData = res_readData.GetAJMKEFMPKHB(GHIHAGAOPNC_idx);
			CJHLABKGKAA GHIHAGAOPNC_data = new CJHLABKGKAA();

			GHIHAGAOPNC_data.PPFNGGCBJKC_id = GHIHAGAOPNC_readData.BBPHAPFBFHK;
			GHIHAGAOPNC_data.PLALNIIBLOF_en = GHIHAGAOPNC_readData.CFLMCGOJJJD;
			GHIHAGAOPNC_data.MPLGPBNJDJB_FreeMusicId = GHIHAGAOPNC_readData.IAPFGOHKAGE;
			GHIHAGAOPNC_data.HMHHNHEPAPP_BossId = GHIHAGAOPNC_readData.KAIMDDPJEON;
			GHIHAGAOPNC_data.PDBPFJJCADD_open_at = GHIHAGAOPNC_readData.NJLJEKDBPCH;
			GHIHAGAOPNC_data.FDBNFFNFOND_close_at = GHIHAGAOPNC_readData.MAOAGDBDBIB;
			GHIHAGAOPNC_list.Add(GHIHAGAOPNC_data);
		}
		res_data.GHIHAGAOPNC = GHIHAGAOPNC_list.ToArray();

		List<MJDMKEIPOLH> MDDOGIAFDEI_list = new List<MJDMKEIPOLH>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			ODMKHCAIAAI MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			MJDMKEIPOLH MDDOGIAFDEI_data = new MJDMKEIPOLH();

			MDDOGIAFDEI_data.PPFNGGCBJKC_id = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF_en = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM_typ = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG_odr = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC_Desc = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE_DescBalloon = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN_ItemId = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC_item_count = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ_Link = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO_st = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<MMFFEFPBLCJ> BHGDNGHDDAC_list = new List<MMFFEFPBLCJ>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			AMCNEEPKDOP BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			MMFFEFPBLCJ BHGDNGHDDAC_data = new MMFFEFPBLCJ();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<FKPLJBFLKAG> MHGMDJNOLMI_list = new List<FKPLJBFLKAG>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			MLHMMHEPMJC MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			FKPLJBFLKAG MHGMDJNOLMI_data = new FKPLJBFLKAG();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<EPICOEPILEJ> IHNBOEPLJKE_list = new List<EPICOEPILEJ>();
		for(int IHNBOEPLJKE_idx = 0; IHNBOEPLJKE_idx < res_readData.JHDOILHEBOGLength; IHNBOEPLJKE_idx++)
		{
			FIPKKAHPFHG IHNBOEPLJKE_readData = res_readData.GetJHDOILHEBOG(IHNBOEPLJKE_idx);
			EPICOEPILEJ IHNBOEPLJKE_data = new EPICOEPILEJ();

			IHNBOEPLJKE_data.PPFNGGCBJKC_id = IHNBOEPLJKE_readData.BBPHAPFBFHK;
			IHNBOEPLJKE_data.PDBPFJJCADD_open_at = IHNBOEPLJKE_readData.NJLJEKDBPCH;
			IHNBOEPLJKE_data.FDBNFFNFOND_close_at = IHNBOEPLJKE_readData.MAOAGDBDBIB;
			IHNBOEPLJKE_data.FEMMDNIELFC_Desc = IHNBOEPLJKE_readData.NNKLANONDOM;
			IHNBOEPLJKE_list.Add(IHNBOEPLJKE_data);
		}
		res_data.IHNBOEPLJKE = IHNBOEPLJKE_list.ToArray();

		List<KCFGJMAMFCH> EENBPAPDNBP_list = new List<KCFGJMAMFCH>();
		for(int EENBPAPDNBP_idx = 0; EENBPAPDNBP_idx < res_readData.NDFKGEGBOCELength; EENBPAPDNBP_idx++)
		{
			HKOLBHENPFE EENBPAPDNBP_readData = res_readData.GetNDFKGEGBOCE(EENBPAPDNBP_idx);
			KCFGJMAMFCH EENBPAPDNBP_data = new KCFGJMAMFCH();

			EENBPAPDNBP_data.PPFNGGCBJKC_id = EENBPAPDNBP_readData.BBPHAPFBFHK;
			EENBPAPDNBP_data.OPFGFINHFCE_name = EENBPAPDNBP_readData.IIDCFMHCPLJ;
			EENBPAPDNBP_data.CPKMLLNADLJ_Serie = EENBPAPDNBP_readData.LMLNKHMPOIG;
			EENBPAPDNBP_data.PIPCIMIALOO_sp = EENBPAPDNBP_readData.GKLHNNBMGKH;
			EENBPAPDNBP_data.NNLAMKCDMEL = EENBPAPDNBP_readData.OJPOLKBHIKP;
			EENBPAPDNBP_data.FCDNMBBPBKI = EENBPAPDNBP_readData.PGIKNMMIPKG;
			EENBPAPDNBP_data.EPMCPGDIBHI = EENBPAPDNBP_readData.JGLECHJPIGM;
			EENBPAPDNBP_data.AKBHPFBDDOL_Val = EENBPAPDNBP_readData.OFELDHPINMB;
			EENBPAPDNBP_list.Add(EENBPAPDNBP_data);
		}
		res_data.EENBPAPDNBP = EENBPAPDNBP_list.ToArray();

		List<LJIJADDCDBE> JLKPDLCFEIM_list = new List<LJIJADDCDBE>();
		for(int JLKPDLCFEIM_idx = 0; JLKPDLCFEIM_idx < res_readData.NNACKFOABOKLength; JLKPDLCFEIM_idx++)
		{
			JEOHKMOBFEM JLKPDLCFEIM_readData = res_readData.GetNNACKFOABOK(JLKPDLCFEIM_idx);
			LJIJADDCDBE JLKPDLCFEIM_data = new LJIJADDCDBE();

			JLKPDLCFEIM_data.PPFNGGCBJKC_id = JLKPDLCFEIM_readData.BBPHAPFBFHK;
			JLKPDLCFEIM_data.LLNDMKBBNIJ_ver = JLKPDLCFEIM_readData.CNNEAFFOPAO;
			JLKPDLCFEIM_data.OMIEMNDOPKA = JLKPDLCFEIM_readData.KMFBIBCCHJL;
			JLKPDLCFEIM_data.ICLFADEFBIH = JLKPDLCFEIM_readData.NCLDIBJIDLJ;
			JLKPDLCFEIM_data.FJOLNJLLJEJ_rank = JLKPDLCFEIM_readData.BDGDHOAJDFM;
			JLKPDLCFEIM_data.OJLDNEGBFFG = JLKPDLCFEIM_readData.ECNCFBDPGCL;
			JLKPDLCFEIM_data.DIDNBKKKEDK = JLKPDLCFEIM_readData.KNIIBDJOCJI;
			JLKPDLCFEIM_data.CAFDIAFJDKP = JLKPDLCFEIM_readData.NHNKCJFGAKN;
			JLKPDLCFEIM_data.EHOBDMHPMHB = JLKPDLCFEIM_readData.JAFADBHMNJL;
			JLKPDLCFEIM_data.DIGJFGFKEJC = JLKPDLCFEIM_readData.EPPCOIEJIJA;
			JLKPDLCFEIM_data.JJELLPDAAEI = JLKPDLCFEIM_readData.KGPEKKEIMCH;
			JLKPDLCFEIM_list.Add(JLKPDLCFEIM_data);
		}
		res_data.JLKPDLCFEIM = JLKPDLCFEIM_list.ToArray();

		List<KLBFLPLFPNF> JFLFHONDDNM_list = new List<KLBFLPLFPNF>();
		for(int JFLFHONDDNM_idx = 0; JFLFHONDDNM_idx < res_readData.PBGAHBOELGLLength; JFLFHONDDNM_idx++)
		{
			PEGCLNAOLBG JFLFHONDDNM_readData = res_readData.GetPBGAHBOELGL(JFLFHONDDNM_idx);
			KLBFLPLFPNF JFLFHONDDNM_data = new KLBFLPLFPNF();

			JFLFHONDDNM_data.PPFNGGCBJKC_id = JFLFHONDDNM_readData.BBPHAPFBFHK;
			JFLFHONDDNM_data.JIMJHIDEHNM_ApCounter = JFLFHONDDNM_readData.MKLGLNCCAJF;
			JFLFHONDDNM_data.KMHIOCCFPEM = JFLFHONDDNM_readData.NPCAIBOAGGO;
			JFLFHONDDNM_data.PIABNPEFLEJ = JFLFHONDDNM_readData.KLMIFFAAGOD;
			JFLFHONDDNM_data.BMAHHKLNOGA = JFLFHONDDNM_readData.JINBBAJGKGI;
			JFLFHONDDNM_data.DHGAILOFNIP = JFLFHONDDNM_readData.MDAGNDELGJC;
			JFLFHONDDNM_list.Add(JFLFHONDDNM_data);
		}
		res_data.JFLFHONDDNM = JFLFHONDDNM_list.ToArray();

		List<JHBMNFIHGBI> PNMLJIPOOPO_list = new List<JHBMNFIHGBI>();
		for(int PNMLJIPOOPO_idx = 0; PNMLJIPOOPO_idx < res_readData.LLDECIJKIGFLength; PNMLJIPOOPO_idx++)
		{
			NLMDFJFJBFA PNMLJIPOOPO_readData = res_readData.GetLLDECIJKIGF(PNMLJIPOOPO_idx);
			JHBMNFIHGBI PNMLJIPOOPO_data = new JHBMNFIHGBI();

			PNMLJIPOOPO_data.PPFNGGCBJKC_id = PNMLJIPOOPO_readData.BBPHAPFBFHK;
			PNMLJIPOOPO_data.GBJFNGCDKPM_typ = PNMLJIPOOPO_readData.LPJPOOHJKAE;
			PNMLJIPOOPO_data.GLCLFMGPMAN_ItemId = PNMLJIPOOPO_readData.MBBJMJAAODG;
			PNMLJIPOOPO_list.Add(PNMLJIPOOPO_data);
		}
		res_data.PNMLJIPOOPO = PNMLJIPOOPO_list.ToArray();

		List<KGNNHHFGLBG> DOKBJLFIGDM_list = new List<KGNNHHFGLBG>();
		for(int DOKBJLFIGDM_idx = 0; DOKBJLFIGDM_idx < res_readData.DFEAJAJHEBPLength; DOKBJLFIGDM_idx++)
		{
			AHDFDKOLGIN DOKBJLFIGDM_readData = res_readData.GetDFEAJAJHEBP(DOKBJLFIGDM_idx);
			KGNNHHFGLBG DOKBJLFIGDM_data = new KGNNHHFGLBG();

			DOKBJLFIGDM_data.PPFNGGCBJKC_id = DOKBJLFIGDM_readData.BBPHAPFBFHK;
			List<uint> AIHOJKFNEEN_list = new List<uint>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < DOKBJLFIGDM_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(DOKBJLFIGDM_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			DOKBJLFIGDM_data.AIHOJKFNEEN_itm = AIHOJKFNEEN_list.ToArray();

			List<uint> BFINGCJHOHI_list = new List<uint>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < DOKBJLFIGDM_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(DOKBJLFIGDM_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			DOKBJLFIGDM_data.BFINGCJHOHI_cnt = BFINGCJHOHI_list.ToArray();

			List<uint> EHKJFNAABMC_list = new List<uint>();
			for(int EHKJFNAABMC_idx = 0; EHKJFNAABMC_idx < DOKBJLFIGDM_readData.NGGAJCBPGFILength; EHKJFNAABMC_idx++)
			{
				EHKJFNAABMC_list.Add(DOKBJLFIGDM_readData.GetNGGAJCBPGFI(EHKJFNAABMC_idx));
			}
			DOKBJLFIGDM_data.EHKJFNAABMC_rat = EHKJFNAABMC_list.ToArray();

			List<uint> DOOGFEGEKLG_list = new List<uint>();
			for(int DOOGFEGEKLG_idx = 0; DOOGFEGEKLG_idx < DOKBJLFIGDM_readData.NMEEJNHKPCNLength; DOOGFEGEKLG_idx++)
			{
				DOOGFEGEKLG_list.Add(DOKBJLFIGDM_readData.GetNMEEJNHKPCN(DOOGFEGEKLG_idx));
			}
			DOKBJLFIGDM_data.DOOGFEGEKLG_max = DOOGFEGEKLG_list.ToArray();

			List<uint> DCFAPPHINAO_list = new List<uint>();
			for(int DCFAPPHINAO_idx = 0; DCFAPPHINAO_idx < DOKBJLFIGDM_readData.DOLNFDOMJBCLength; DCFAPPHINAO_idx++)
			{
				DCFAPPHINAO_list.Add(DOKBJLFIGDM_readData.GetDOLNFDOMJBC(DCFAPPHINAO_idx));
			}
			DOKBJLFIGDM_data.DCFAPPHINAO = DCFAPPHINAO_list.ToArray();

			DOKBJLFIGDM_list.Add(DOKBJLFIGDM_data);
		}
		res_data.DOKBJLFIGDM = DOKBJLFIGDM_list.ToArray();

		List<DFPOGOFGFBN> HBMGNHBFPHC_list = new List<DFPOGOFGFBN>();
		for(int HBMGNHBFPHC_idx = 0; HBMGNHBFPHC_idx < res_readData.FIKNJBFFMGGLength; HBMGNHBFPHC_idx++)
		{
			CHCOHLNPLMJ HBMGNHBFPHC_readData = res_readData.GetFIKNJBFFMGG(HBMGNHBFPHC_idx);
			DFPOGOFGFBN HBMGNHBFPHC_data = new DFPOGOFGFBN();

			HBMGNHBFPHC_data.PPFNGGCBJKC_id = HBMGNHBFPHC_readData.BBPHAPFBFHK;
			HBMGNHBFPHC_data.FEMMDNIELFC_Desc = HBMGNHBFPHC_readData.NNKLANONDOM;
			HBMGNHBFPHC_data.MDNKAFNHNDJ = HBMGNHBFPHC_readData.KGJOEPEIDMO;
			HBMGNHBFPHC_data.MAAGBAOIFFA = HBMGNHBFPHC_readData.JMFEAOOLOEG;
			HBMGNHBFPHC_data.AIMACNHIPMG = HBMGNHBFPHC_readData.FOOEBKAHMCM;
			HBMGNHBFPHC_data.DJJGNDCMNHF_BonusValue = HBMGNHBFPHC_readData.DMNNOAFOPFI;
			HBMGNHBFPHC_data.MCNEIJAOLNO_Select = HBMGNHBFPHC_readData.ACIJELOAHHD;
			HBMGNHBFPHC_data.PENMGPNPHHG_BonusSp = HBMGNHBFPHC_readData.EFOBFEHCBHJ;
			HBMGNHBFPHC_data.PDJJELPFMJB_RateSp = HBMGNHBFPHC_readData.LOJKHFENCOJ;
			HBMGNHBFPHC_list.Add(HBMGNHBFPHC_data);
		}
		res_data.HBMGNHBFPHC = HBMGNHBFPHC_list.ToArray();

		List<ALFLHDKBNIB> OLACFKILCFD_list = new List<ALFLHDKBNIB>();
		for(int OLACFKILCFD_idx = 0; OLACFKILCFD_idx < res_readData.HDNMEPFHLNFLength; OLACFKILCFD_idx++)
		{
			CKMBIDDOCEP OLACFKILCFD_readData = res_readData.GetHDNMEPFHLNF(OLACFKILCFD_idx);
			ALFLHDKBNIB OLACFKILCFD_data = new ALFLHDKBNIB();

			OLACFKILCFD_data.PPFNGGCBJKC_id = OLACFKILCFD_readData.BBPHAPFBFHK;
			OLACFKILCFD_data.CNKFPJCGNFE_SceneId = OLACFKILCFD_readData.DPFDOIIOICA;
			OLACFKILCFD_data.GNFBMCGMCFO_BonusBefore = OLACFKILCFD_readData.GEAIPAEKLNF;
			OLACFKILCFD_data.BFFGFAMJAIG_BonusAfter = OLACFKILCFD_readData.JGILGOILJNK;
			OLACFKILCFD_list.Add(OLACFKILCFD_data);
		}
		res_data.OLACFKILCFD = OLACFKILCFD_list.ToArray();

		List<CNDLLOPINDF> MIOCOKLMLBD_list = new List<CNDLLOPINDF>();
		for(int MIOCOKLMLBD_idx = 0; MIOCOKLMLBD_idx < res_readData.OLLJCDPOAAILength; MIOCOKLMLBD_idx++)
		{
			GPLJGOGMCNP MIOCOKLMLBD_readData = res_readData.GetOLLJCDPOAAI(MIOCOKLMLBD_idx);
			CNDLLOPINDF MIOCOKLMLBD_data = new CNDLLOPINDF();

			MIOCOKLMLBD_data.PPFNGGCBJKC_id = MIOCOKLMLBD_readData.BBPHAPFBFHK;
			MIOCOKLMLBD_data.GNFBMCGMCFO_BonusBefore = MIOCOKLMLBD_readData.GEAIPAEKLNF;
			MIOCOKLMLBD_data.BFFGFAMJAIG_BonusAfter = MIOCOKLMLBD_readData.JGILGOILJNK;
			MIOCOKLMLBD_list.Add(MIOCOKLMLBD_data);
		}
		res_data.MIOCOKLMLBD = MIOCOKLMLBD_list.ToArray();

		List<MDDFBKANJDJ> IEJLJIHIDJC_list = new List<MDDFBKANJDJ>();
		for(int IEJLJIHIDJC_idx = 0; IEJLJIHIDJC_idx < res_readData.BHNBMLKMLGNLength; IEJLJIHIDJC_idx++)
		{
			BDLNCCBHPAD IEJLJIHIDJC_readData = res_readData.GetBHNBMLKMLGN(IEJLJIHIDJC_idx);
			MDDFBKANJDJ IEJLJIHIDJC_data = new MDDFBKANJDJ();

			IEJLJIHIDJC_data.KHPHAAMGMJP = IEJLJIHIDJC_readData.OEBLGFLPMNE;
			IEJLJIHIDJC_data.OFIAENKCJME = IEJLJIHIDJC_readData.BJELMJJFMBI;
			List<int> JMLCLHHLJHM_list = new List<int>();
			for(int JMLCLHHLJHM_idx = 0; JMLCLHHLJHM_idx < IEJLJIHIDJC_readData.IHNCJBFCAAILength; JMLCLHHLJHM_idx++)
			{
				JMLCLHHLJHM_list.Add(IEJLJIHIDJC_readData.GetIHNCJBFCAAI(JMLCLHHLJHM_idx));
			}
			IEJLJIHIDJC_data.JMLCLHHLJHM = JMLCLHHLJHM_list.ToArray();

			IEJLJIHIDJC_list.Add(IEJLJIHIDJC_data);
		}
		res_data.IEJLJIHIDJC = IEJLJIHIDJC_list.ToArray();

		return res_data;
	}
}
