using FlatBuffers;
using System.Collections.Generic;

public class EGMHDLMLEFP
{
	public string OPFGFINHFCE_name { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD_RankingName { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public uint OBGBAOLONDD_UniqueId { get; set; } // 0x10 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF_name_for_api { get; set; } // 0x14 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public uint MOEKELIIDEO_SaveIdx { get; set; } // 0x18 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND_RankingStart { get; set; } // 0x1C JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint HPNOGLIFJOP_RankingEnd { get; set; } // 0x20 LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE_RankingEnd2 { get; set; } // 0x24 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF_RewardStart { get; set; } // 0x28 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI_RewardEnd { get; set; } // 0x2C BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH_RewardEnd2 { get; set; } // 0x30 HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint KHIKEGLBGAF_RankingRewardScene { get; set; } // 0x34 OAPPFIGOMHO FAHFDEFDLMH OJJMIBDFGBG
	public uint JMJDLDEIFKE { get; set; } // 0x38 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO_DayGroup { get; set; } // 0x3C IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x40 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x44 HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public string KOHMHBGOFFI_free_music { get; set; } // 0x48 JLLIIMINNHM GLMMBMGFOMJ MPHABIGJJJH
	public uint AHKPNPNOAMO_ExtreamOpen { get; set; } // 0x4C AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
	public uint HKKNEAGCIEB_RankingSupport { get; set; } // 0x50 DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI_RankingThreshold { get; set; } // 0x54 ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public int OILIKPOBBGD { get; set; } // 0x58 LHJMOHILJCF PNGAHHKCFNL HHAEIDBNCFO
	public int AMCPINEGNPG { get; set; } // 0x5C ACNKHNDFKID POIMFJHGJCB LDBONECIMLK
	public int AGGLDFOKCLJ { get; set; } // 0x60 OPCEBHACKCK DJLOPEINIGO CBIBNKDLFGH
	public int EODIMCFIMMP { get; set; } // 0x64 LIAFAMKFNNO ABLJNFODIJF BCNFBBDOCED
	public int GLFPABNKHHA { get; set; } // 0x68 MDEALIMIIHD CLPCKCFBEID DAPNMNFABNC
}
public class PCHHAILGOCM
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MPLGPBNJDJB_FreeMusicId { get; set; } // 0x10 GNKPHDHIMAC KADAEAOKJNE MBKFNLHPNPP
	public uint LGADCGFMLLD_step { get; set; } // 0x14 NPLLPPDCHOJ MAFBDLKFHGJ EPEFBOIALDI
	public uint MLKFDMFDFCE_enemy_c_skill { get; set; } // 0x18 OOHFBCCHNLG CLBKMDMNLJB OIGPBCCALHF
	public uint DKOPDNHDLIA_enemy_l_skill { get; set; } // 0x1C JEEBCJHFIHM NNKFJHHJFPA CBNANJFEJGC
	public int PDBPFJJCADD_open_at { get; set; } // 0x20 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public int FDBNFFNFOND_close_at { get; set; } // 0x24 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class GCBBGMDMIKI
{
	public uint PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM_typ { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG_odr { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC_Desc { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE_DescBalloon { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN_ItemId { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC_item_count { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ_Link { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO_st { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
	public uint CMPNCNFICGG { get; set; } // 0x68 KCDKLDNJPCG JMDKCLNPICK LBDBOKHBBHE
}
public class IHAHAELJEOG
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class OEJFMPCFIGG
{
	public string LJNAKDMILMC_key { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG_val { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class KLJIHHAEIOD
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KFCIJBLDHOK_v1 { get; set; } // 0xC JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int JLEIHOEGMOP { get; set; } // 0x10 JLNAMGLBPME JJGFFGDDFPA LIIFHDMHLHP
}
public class OLLJFONKEKO
{
	public EGMHDLMLEFP HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public PCHHAILGOCM[] GHIHAGAOPNC { get; set; } // 0xC CNAPBHHKEPH OHCBAEGAKOH OIDPGMCLNBF
	public GCBBGMDMIKI[] MDDOGIAFDEI { get; set; } // 0x10 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public IHAHAELJEOG[] BHGDNGHDDAC { get; set; } // 0x14 JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public OEJFMPCFIGG[] MHGMDJNOLMI { get; set; } // 0x18 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public KLJIHHAEIOD[] KIEKMCKCMGD { get; set; } // 0x1C AHOFIJDMDAO EEMBMMJIHPE CDHPBECJGGO
	public static OLLJFONKEKO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xCAB11C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OGABIHKHGGD res_readData = OGABIHKHGGD.GetRootAsOGABIHKHGGD(buffer);
		OLLJFONKEKO res_data = new OLLJFONKEKO();

		HLGKEMBLPMP HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		EGMHDLMLEFP HMBHNLCFDIH_data = new EGMHDLMLEFP();

		HMBHNLCFDIH_data.OPFGFINHFCE_name = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD_RankingName = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.OBGBAOLONDD_UniqueId = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF_name_for_api = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.MOEKELIIDEO_SaveIdx = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND_RankingStart = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.HPNOGLIFJOP_RankingEnd = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE_RankingEnd2 = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF_RewardStart = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI_RewardEnd = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH_RewardEnd2 = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.KHIKEGLBGAF_RankingRewardScene = HMBHNLCFDIH_readData.HKPPDACCCOH;
		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO_DayGroup = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.KOHMHBGOFFI_free_music = HMBHNLCFDIH_readData.GPCEIBGOEGB;
		HMBHNLCFDIH_data.AHKPNPNOAMO_ExtreamOpen = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		HMBHNLCFDIH_data.HKKNEAGCIEB_RankingSupport = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI_RankingThreshold = JHPCPNJJHLI_list.ToArray();

		HMBHNLCFDIH_data.OILIKPOBBGD = HMBHNLCFDIH_readData.DIMNACDMDNA;
		HMBHNLCFDIH_data.AMCPINEGNPG = HMBHNLCFDIH_readData.OBKOHEAAOHE;
		HMBHNLCFDIH_data.AGGLDFOKCLJ = HMBHNLCFDIH_readData.ABHMDHFOEFM;
		HMBHNLCFDIH_data.EODIMCFIMMP = HMBHNLCFDIH_readData.NDNILABOKNJ;
		HMBHNLCFDIH_data.GLFPABNKHHA = HMBHNLCFDIH_readData.HKONHGMBLBO;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<PCHHAILGOCM> GHIHAGAOPNC_list = new List<PCHHAILGOCM>();
		for(int GHIHAGAOPNC_idx = 0; GHIHAGAOPNC_idx < res_readData.AJMKEFMPKHBLength; GHIHAGAOPNC_idx++)
		{
			CLBPBGIPFPP GHIHAGAOPNC_readData = res_readData.GetAJMKEFMPKHB(GHIHAGAOPNC_idx);
			PCHHAILGOCM GHIHAGAOPNC_data = new PCHHAILGOCM();

			GHIHAGAOPNC_data.PPFNGGCBJKC_id = GHIHAGAOPNC_readData.BBPHAPFBFHK;
			GHIHAGAOPNC_data.PLALNIIBLOF_en = GHIHAGAOPNC_readData.CFLMCGOJJJD;
			GHIHAGAOPNC_data.MPLGPBNJDJB_FreeMusicId = GHIHAGAOPNC_readData.IAPFGOHKAGE;
			GHIHAGAOPNC_data.LGADCGFMLLD_step = GHIHAGAOPNC_readData.HICGGFMNEMI;
			GHIHAGAOPNC_data.MLKFDMFDFCE_enemy_c_skill = GHIHAGAOPNC_readData.EFFICDBHCCH;
			GHIHAGAOPNC_data.DKOPDNHDLIA_enemy_l_skill = GHIHAGAOPNC_readData.FOHAACCBBOP;
			GHIHAGAOPNC_data.PDBPFJJCADD_open_at = GHIHAGAOPNC_readData.NJLJEKDBPCH;
			GHIHAGAOPNC_data.FDBNFFNFOND_close_at = GHIHAGAOPNC_readData.MAOAGDBDBIB;
			GHIHAGAOPNC_list.Add(GHIHAGAOPNC_data);
		}
		res_data.GHIHAGAOPNC = GHIHAGAOPNC_list.ToArray();

		List<GCBBGMDMIKI> MDDOGIAFDEI_list = new List<GCBBGMDMIKI>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			LKEFGGDDBJK MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			GCBBGMDMIKI MDDOGIAFDEI_data = new GCBBGMDMIKI();

			MDDOGIAFDEI_data.PPFNGGCBJKC_id = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF_en = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM_typ = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG_odr = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC_Desc = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE_DescBalloon = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN_ItemId = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC_item_count = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ_Link = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO_st = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_data.CMPNCNFICGG = MDDOGIAFDEI_readData.CFMIBDJFAMO;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<IHAHAELJEOG> BHGDNGHDDAC_list = new List<IHAHAELJEOG>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			JACLMHBOGIE BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			IHAHAELJEOG BHGDNGHDDAC_data = new IHAHAELJEOG();

			BHGDNGHDDAC_data.LJNAKDMILMC_key = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG_val = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<OEJFMPCFIGG> MHGMDJNOLMI_list = new List<OEJFMPCFIGG>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			OJFDBJJIMMA MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			OEJFMPCFIGG MHGMDJNOLMI_data = new OEJFMPCFIGG();

			MHGMDJNOLMI_data.LJNAKDMILMC_key = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG_val = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<KLJIHHAEIOD> KIEKMCKCMGD_list = new List<KLJIHHAEIOD>();
		for(int KIEKMCKCMGD_idx = 0; KIEKMCKCMGD_idx < res_readData.FBAHAFKCMMHLength; KIEKMCKCMGD_idx++)
		{
			OHMMAIEEGMO KIEKMCKCMGD_readData = res_readData.GetFBAHAFKCMMH(KIEKMCKCMGD_idx);
			KLJIHHAEIOD KIEKMCKCMGD_data = new KLJIHHAEIOD();

			KIEKMCKCMGD_data.PPFNGGCBJKC = KIEKMCKCMGD_readData.BBPHAPFBFHK;
			KIEKMCKCMGD_data.KFCIJBLDHOK_v1 = KIEKMCKCMGD_readData.MCJNHPMBPIJ;
			KIEKMCKCMGD_data.JLEIHOEGMOP = KIEKMCKCMGD_readData.MGJKFKDICGC;
			KIEKMCKCMGD_list.Add(KIEKMCKCMGD_data);
		}
		res_data.KIEKMCKCMGD = KIEKMCKCMGD_list.ToArray();

		return res_data;
	}
}
