using FlatBuffers;
using System.Collections.Generic;

public class NKCJNCELIJN
{
	public string OPFGFINHFCE { get; set; } // 0x8 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public string HEDAGCNPHGD { get; set; } // 0xC MDDOAHHHPOP FJAAEFFFFNF GFPDDOPFCOG
	public string IDGAEEJLGIK { get; set; } // 0x10 MJHNCPIAJCK HDLHFAFLMLD PICAFNJCKOI
	public uint OBGBAOLONDD { get; set; } // 0x14 NCOKDCMHMJF OLHPPFCEIIK EIHCOIFCELN
	public string OCGFKMHNEOF { get; set; } // 0x18 FPPPOCOGLEB KOGCMPJKHEN NCLILAGAPCJ
	public string OGMGLOFKKPA { get; set; } // 0x1C IAAEFKNBJMJ IDPAEJFBCMD JEIDAEPANEH
	public uint MOEKELIIDEO { get; set; } // 0x20 MJBDEKDJLJL BGIBLNEJJNA BAMKBOHIDFG
	public uint BONDDBOFBND { get; set; } // 0x24 JLKMCNLLGOB NNHBILFHONA DKJIPIOFHNJ
	public uint EHHFFKAFOMC { get; set; } // 0x28 MDCEFKJDJIJ EMIPFAAPLIB JHGMJLNGOGD
	public uint HPNOGLIFJOP { get; set; } // 0x2C LKCBAFJAGDN CMOKHLBLIGO BGEFMCCGGAO
	public uint LNFKGHNHJKE { get; set; } // 0x30 DBAHKIMGPAI BMNKAHOBNCL OLDALGAEKNB
	public uint JGMDAOACOJF { get; set; } // 0x34 HLNLAENEKOD IHLILJPCPMB NFAIHFEHHEK
	public uint IDDBFFBPNGI { get; set; } // 0x38 BNFKFIHBOFD DFOFEPAMOAF DBJHPJBOILO
	public uint KNLGKBBIBOH { get; set; } // 0x3C HLFNONCONAP IOMNJKGAOOD CDGMGKOIMBP
	public uint JBFDHOIKAIK { get; set; } // 0x40 HKLAIJDEMID GBNKCHLEGPH AAKNFOAHCCI
	public uint KHIKEGLBGAF { get; set; } // 0x44 OAPPFIGOMHO FAHFDEFDLMH OJJMIBDFGBG
	public uint DPJCFLKFEPN { get; set; } // 0x48 IPODKLGLHPC MEAAAGCCAPI GNMJKJHPIOG
	public uint[] EEOGPJJCKHH { get; set; } // 0x4C CPNKKFMLHFL BBBPKCMKJEF CDMJOOGMGNP
	public uint JMJDLDEIFKE { get; set; } // 0x50 OAGMMIOODOF OIHKCLCPBJI PKPGPELDIBH
	public uint AHKNMANFILO { get; set; } // 0x54 IFFLMDALMBO PEGLCODNPHG PAGEFLIKEIE
	public string OCDMGOGMHGE { get; set; } // 0x58 AEEOIOIDHEE HBAAAKFHDBB NHJLJOIPOFK
	public string PJBILOFOCIC { get; set; } // 0x5C HAJIFCIAOBI NOEFEAIFHCL GJIJFGNONEL
	public int MJBKGOJBPAD { get; set; } // 0x60 DINOHEJLBOA COFMKKJBELJ KHOHIGFNIIF
	public string FEMMDNIELFC { get; set; } // 0x64 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public uint HKKNEAGCIEB { get; set; } // 0x68 DLECBCICIJB KCBPJPCEPHH KBACNJPKDOD
	public int[] JHPCPNJJHLI { get; set; } // 0x6C ABFFLNFIKGK BJHMPIECMGE DDMAPMOHPBM
	public uint[] HIAMHLLHAON { get; set; } // 0x70 OFPOHJIDECK DJDNABNLAPN EFAGPEJEIAA
	public int[] JKFPADIAKCK { get; set; } // 0x74 DJMAJJIHFPL CENPFGJOAPN FKKHCFFICFH
	public string OMCAOJJGOGG { get; set; } // 0x78 PLIJEFCMPPK PBEMPHPDDDB MCADMIEOCCF
	public int HIOOGLEJBKM { get; set; } // 0x7C AGFPHPAEDHA KCELJCIHBBI FNJPPJBPMAK
	public int FJCADCDNPMP { get; set; } // 0x80 OONAGAPPPIN ENAPOBLKPOP KLFDODOFHGA
	public int[] EJBGHLOOLBC { get; set; } // 0x84 IPIFFFAPMBI EPDMCNHPMMH DNLNMDIBEML
	public int AHKPNPNOAMO { get; set; } // 0x88 AFNKJBHLGEM GFGFHFAENCE BLDNJLKJEDC
	public int[] LJENLHCBLEL { get; set; } // 0x8C EAJKGDALAJG CAJLHCNDJIE AGDAOGBFHCK
	public int[] PLGNGKNPNCN { get; set; } // 0x90 CAFDHHMOBAP NLBAMFNGFJK JECPBNJIOGA
	public int EKJFNHHKBPL { get; set; } // 0x94 BPPNFOAFCPE BONLIFKCIFO HBFFBCJHJAC
}
public class FPJPKBBOICF
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint FOILNHKHHDF { get; set; } // 0xC LNNCNOIGMGM FOFBHPJDHFO LHPMDDKPJDP
	public int[] AIHOJKFNEEN { get; set; } // 0x10 GGBFCEFNCFM BGFIPHMMOGA DHAIHODDOGM
	public uint[] BFINGCJHOHI { get; set; } // 0x14 PIAHJAJPLKA LFMCLIDAPHB EDAEPDGGFJJ
	public uint[] JJHPDDPKBHF { get; set; } // 0x18 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public int JOPPFEHKNFO { get; set; } // 0x1C LLNLOLIOPBO FNIOGOJFLMG AJIOKKIJBED
	public uint[] HJAFPEBIBOP { get; set; } // 0x20 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class JGHDNNFHEHC
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint FPOMEEJFBIG { get; set; } // 0x14 PJKJIFMIFDJ OEEBAHNAPEC BEHAPLPPLNE
	public string FEMMDNIELFC { get; set; } // 0x18 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
	public string BGBJPGEIEDE { get; set; } // 0x1C PHIDBDJIBJG BCDOBODACON FHPAMAENALF
	public uint BDKFOMGCOOE { get; set; } // 0x20 AFHNGGCLCJA IEGJEPOCNKP KJJMLKOJKOF
	public uint PJGIAKGGHPF { get; set; } // 0x24 HCGGEPPOOKF LFJIBGGMKIJ MOPGHAMLFFD
	public uint MMCBOJHFDEF { get; set; } // 0x28 NCCCHDGKEBH ALOMOIIOEHD PPPBLMBLIFP
	public uint JBECECBFFBF { get; set; } // 0x2C CHJFOJHLJLJ HKICLFMGAOJ PBIOJAFGGGO
	public uint LDOMFAMFGLM { get; set; } // 0x30 MINKGKDHIMP JCDFJHEFGPB FNAJOBBCFOK
	public uint BMDGADMKOIH { get; set; } // 0x34 NAIPJEPIDCF ADOECNJGACD LINMGNPGDPG
	public uint AIIEBILNLGO { get; set; } // 0x38 OBJLHEJOAOF DOPPGNPHLCJ CCKBOCCHMDO
	public uint JOGDEMBADLO { get; set; } // 0x3C PBDLNJGJEMA EGIEIKOGMKI FHONLGBJLIF
	public uint GMJBANCDOJK { get; set; } // 0x40 FJOCNPLPJPM ODIJLDJAGEG HMPOFLDBKDG
	public uint AIEOAMKDHJC { get; set; } // 0x44 KCAOHAODDJO GLKENFCGECK IEGGEOHKMGA
	public uint GLCLFMGPMAN { get; set; } // 0x48 KCELNMGLKHH LNJAENEGDEL JHIDBGCHOKL
	public uint MBJIFDBEDAC { get; set; } // 0x4C HMBMCDEPOKO CLBHLMCKJOE ICAIGMILGGD
	public uint HLOBFDBFINJ { get; set; } // 0x50 NKHEKDNPDMD MDJOOEGJOGM FNGNAPLAOLA
	public uint JJHPDDPKBHF { get; set; } // 0x54 PIGEHKAPNNF HFILAJCCGJG ACCDONHEHCG
	public uint KOACGMPOIGN { get; set; } // 0x58 LNAMBEPKCJN PKEGNNOBBPL JBIPACHDNOK
	public uint ADCKKAFCIAC { get; set; } // 0x5C FBHJFPJNLKF JNODDBHABIC PCMHDPFOKCN
	public uint FNEIADJMHHO { get; set; } // 0x60 PJFAGECNJCF FAPDANAMOKF JIHDPPHAAOJ
	public uint EICJBAEDMNM { get; set; } // 0x64 GIEKKGKEHGK KINEOEMJLIF MFGDGANNOMO
	public uint HJAFPEBIBOP { get; set; } // 0x68 AELPJDJAIEA GNDLHNBPMHN HPFNBOKBEDD
}
public class EBDMGCHHCFD
{
	public int EEAPIKNJNDB { get; set; } // 0x8 CMFPHGJOINM KNLJPLHJMHI IMHAJFDFGJL
	public int NNDBJGDFEEM { get; set; } // 0xC CNDGBLDLDCC EHNOFMPHLFC GCANPOPEKEE
	public int DOOGFEGEKLG { get; set; } // 0x10 IKKMNBJGBJK AECMFIOFFJN NGOJJDOCIDG
	public int HNDOLKNBOIJ { get; set; } // 0x14 LGNECNNHFHG LMNEPLGBBGP AJMFFPNCNJO
	public int HHGFOIMIGED { get; set; } // 0x18 ABDAOGLNIJK POJLCAFLBGA MNDPEODCBPL
	public int IBCMDICBGHH { get; set; } // 0x1C AJGJOJDPAHF PEKFIENADFH GCOIKKBNJKP
	public int HKAILALAFDG { get; set; } // 0x20 NANNAKIHDGO LOODBOFCLAI MNPJGLAMKMI
	public int DJJGNDCMNHF { get; set; } // 0x24 FACIBMKEMCC GEPCOAPEAJM MIFJBBAJAJP
}
public class BAJEBICKGPF
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public string OPFGFINHFCE { get; set; } // 0x10 LGIIAPHCLPN DKJOHDGOIJE MJAMIGECMMF
	public int GOIKCKHMBDL { get; set; } // 0x14 HJKMFKFANAD BPGCGEDHBEH ICPMFBIDFFO
	public int AKNELONELJK { get; set; } // 0x18 MDCMMICBKFN BPPILHGDABB PMMIIHKEGCI
	public int KNIFCANOHOC { get; set; } // 0x1C DKDLLFCBBCE EOJEPLIPOMJ AEEMBPAEAAI
	public int EDJMDDAGCEJ { get; set; } // 0x20 DGADFLBHBLO BCMKDNCFOJO DDIAEKOKDIE
	public int HEFPAIOLBAG { get; set; } // 0x24 GFNMBBFAEPJ EAGPNJEBOCP LLIGHINHLOL
	public int DIPKCALNIII { get; set; } // 0x28 HLEPHANBMGN EOGPBFIDAPF JDNCGPBAFMB
	public int JFFOEAANFPG { get; set; } // 0x2C CIDDCGGDCLC MPCLPMPLFLH NILPBCIFCPA
	public int HEBKEJBDCBH { get; set; } // 0x30 GHHNOPMHDJE OMOHEDILHMF FCGDHINFKHC
	public int GLILAGLJLEP { get; set; } // 0x34 ALMNJFCAMKL HGPGPALMELF ECHLNFNJFFO
	public int ECOLMPLOPFM { get; set; } // 0x38 MEDPINHHMOM BFLCGLBAFOE NJGKCLHFDIB
	public int CFCIMKOHLIG { get; set; } // 0x3C LANMHDLJEHJ AJNACFGNOAA LCGAFCPHDKA
	public int IPPNCOHEEOD { get; set; } // 0x40 CEEMFIIOHNJ BNFNPCNAGAF GEMDEGDPJPK
	public int[] MJNMPAKBNKB { get; set; } // 0x44 PDODCGPFKHL MHFDKAPPNNH BBODBCKPBMA
	public int BDLNMOIOMHK { get; set; } // 0x48 EFBBEAKKPLD MKMAKAEDMBG GIJPLHEDIKD
	public int NLKEBAOBJCM { get; set; } // 0x4C ABLBDMPGEHA AECNKGBNKHH ECHLKFHOJFP
	public int ENNCJKLIGKE { get; set; } // 0x50 BIMOOCCCHCA CIGNNFNAAAN DOLNOHODMEI
	public int PALEGNNHIKH { get; set; } // 0x54 MONDIMNJDHC MALPONGOPKO BHAFNMAEHOH
	public int JCDEDIOAGKE { get; set; } // 0x58 ODLJLINFAIG FGFOFHBNLDH KJGHOKODAKB
}
public class OBMEFONPANB
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public int JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class CNMODGDHGHA
{
	public string LJNAKDMILMC { get; set; } // 0x8 KNJIHALCKLN LIIHHICIBKM OACJGKPBHIK
	public string JBGEEPFKIGG { get; set; } // 0xC AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
}
public class PDEFFJNHFOE
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int KFCIJBLDHOK { get; set; } // 0xC JPBPAFOAPIO EPEKNNHHPIF LFGKAMKBDGA
	public int JLEIHOEGMOP { get; set; } // 0x10 JLNAMGLBPME JJGFFGDDFPA LIIFHDMHLHP
}
public class EGFGKMKLEFG
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GBJFNGCDKPM { get; set; } // 0xC GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public int JBGEEPFKIGG { get; set; } // 0x10 AHPLCJAKAOP OLOCMINKGON ABAFHIBFKCE
	public int MAFAIIHJAFG { get; set; } // 0x14 FIINMMHBBJF LLNFMLKMFKB PCICDCAILIF
}
public class IJFIMCBAJDJ
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint MPLGPBNJDJB { get; set; } // 0x10 GNKPHDHIMAC KADAEAOKJNE MBKFNLHPNPP
	public uint CPBFAMJEODF { get; set; } // 0x14 HELFKONOIDE GEPFGJBNHNL MHBECPNIHLA
	public uint MGHPJNNDCIG { get; set; } // 0x18 BDHIGGLMBBI GFADFBMKBMD JECIKFDJMOB
	public uint PDBPFJJCADD { get; set; } // 0x1C PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x20 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class HJEKNHMEPBP
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint KOJMEPJBOJM { get; set; } // 0x10 PKDDGIPLJLB JFLEJAJJMPF DLOCAEEEJAE
	public uint PDBPFJJCADD { get; set; } // 0x14 PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x18 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
}
public class HIGMGCAKFAN
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint APGKOJKNNGP { get; set; } // 0x10 ONNNFKJBEEE KGLCIOHDBLL DJKADEGEAHE
	public uint AFKHNFBOMKI { get; set; } // 0x14 DJNLJJOGNOJ NMHOKCJEIDP MPFMEIDKANE
	public int[] HHOFENIINIJ { get; set; } // 0x18 IGLCGPLNILJ GONLLGNPBNN JDPMJLCNJID
	public uint LNNOCPJLNFD { get; set; } // 0x1C MLMKHHCOACO MHBPCBAONAC LCPLLCJMENN
	public uint GCPKJPNENJJ { get; set; } // 0x20 AKGOPOJGNJB DEFEJOEMOBM POILGINHMFI
	public uint FLOAHHHAOLE { get; set; } // 0x24 BHBKIMMGEDN LFPPNCDDIIL AANNOOHGHHI
	public uint COJMPBFFJFI { get; set; } // 0x28 CKHDNNCJNDI JPPCEEKHOFC HIOGIOLAEOI
	public uint KPFDEBIEAME { get; set; } // 0x2C LMGINMPHOEO IIMKGJJGKLL MDFOJINDCCM
	public uint MCBDCDLKACL { get; set; } // 0x30 KGPLNFHOKCJ GCJBJKEJMPN GNLEHPCNIFN
	public uint JLDNDNNDEEH { get; set; } // 0x34 CBHABEDJDFE IONADHGPJOM EIBPMJPKBMG
	public uint LIIIGJFLAAB { get; set; } // 0x38 ALAOJLOAPCC JPIBNDOCFKB AGFPHGNJJIH
	public uint NGNKKFNDEPD { get; set; } // 0x3C DPDCEJOOOPG DDOMBIIGHJH OHENGMHAJHL
	public uint MKOKEGGPFBC { get; set; } // 0x40 PEBHFLIEAMP LGAMCIJDOOL CJGNIOCOPEO
}
public class FMPMFOBJNCM
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PDBPFJJCADD { get; set; } // 0xC PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x10 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public string FEMMDNIELFC { get; set; } // 0x14 GDKPKLJELJK JDHDMBHNKJD FNAJEJLLJOE
}
public class NFEINLOIPEP
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int CNKFPJCGNFE { get; set; } // 0xC OGPCJNOKMAM GJBOGOFHGNP GJDGIDCMJMH
	public int GNFBMCGMCFO { get; set; } // 0x10 LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x14 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class PHNMAKOGBKJ
{
	public int PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public int GNFBMCGMCFO { get; set; } // 0xC LAMLKPEDMHF NCIMMDJLPLJ HNAJAFBHOLM
	public int BFFGFAMJAIG { get; set; } // 0x10 KAFLAFEBBLM PKMNOMELPMN IABBJBAHKCE
}
public class FJOLJGPGDGD
{
	public int KHPHAAMGMJP { get; set; } // 0x8 FHLAGLBMFHE ABFDDKBBPCH MHDOIIEMDEH
	public int OFIAENKCJME { get; set; } // 0xC NHHGGLNCELI KADLAKFANGA AIDAPNCEPOB
	public int[] JMLCLHHLJHM { get; set; } // 0x10 HCOPKKMMEAL KCJKEEAILGB EGEABIGCJJK
}
public class OPHFFGFJIBJ
{
	public NKCJNCELIJN HMBHNLCFDIH { get; set; } // 0x8 GHOEBMKFFAF HPDMBLBOMBI BMLFCMKAALF
	public FPJPKBBOICF[] MCHFABAKPMH { get; set; } // 0xC BFBKDKPKLMM IPDEGCCJALP HHNBEKGDAPD
	public JGHDNNFHEHC[] MDDOGIAFDEI { get; set; } // 0x10 HAAHCMPJBIP CBFJCGPNJOM OPAONKKDHFO
	public EBDMGCHHCFD[] DDIGKGINBKL { get; set; } // 0x14 PDKPOGFFOLI KAPIMONBHFP AIMLNIKAAND
	public BAJEBICKGPF[] MDMKOGDHCIC { get; set; } // 0x18 APCNHOKAIHA PAPOEPEOLCN FLJDOGDFONB
	public OBMEFONPANB[] BHGDNGHDDAC { get; set; } // 0x1C JHDNDHBDFFI CEHHJMMMCID EDOEOHENKDG
	public CNMODGDHGHA[] MHGMDJNOLMI { get; set; } // 0x20 JBFEKPIDNIC NFFJJGMEEOB BGEFBFOAMPK
	public PDEFFJNHFOE[] KIEKMCKCMGD { get; set; } // 0x24 AHOFIJDMDAO EEMBMMJIHPE CDHPBECJGGO
	public EGFGKMKLEFG[] MHKNGJMEGFI { get; set; } // 0x28 DGMLFJKGMLO DJAALDIHICI ILMEEBDMNBJ
	public IJFIMCBAJDJ[] GHIHAGAOPNC { get; set; } // 0x2C CNAPBHHKEPH OHCBAEGAKOH OIDPGMCLNBF
	public HJEKNHMEPBP[] PLHPEOKOMHH { get; set; } // 0x30 IDLJFKPEBJH LGMBCPGJICE CEFDNIOEIBP
	public HIGMGCAKFAN[] NIPMOFJPFJG { get; set; } // 0x34 JHLFCOABLEL EOABNDPPCEK EFJHPJCJBIP
	public FMPMFOBJNCM[] IHNBOEPLJKE { get; set; } // 0x38 MMGGONDGLOL EMLHCNDOCCP GKPFNDEHLJD
	public NFEINLOIPEP[] OLACFKILCFD { get; set; } // 0x3C ODAEGEAACIA KCGGGPCDEPK ANKJOEMLFCI
	public PHNMAKOGBKJ[] MIOCOKLMLBD { get; set; } // 0x40 COILMDCEJLD MNIALHMNHFM OGLAMDPDFCD
	public FJOLJGPGDGD[] IEJLJIHIDJC { get; set; } // 0x44 CDHGOELCBFB DGNNDIPELAP BFHEABPGGHO
	public static OPHFFGFJIBJ HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xCB2A30
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		OIMNNAPBCGG res_readData = OIMNNAPBCGG.GetRootAsOIMNNAPBCGG(buffer);
		OPHFFGFJIBJ res_data = new OPHFFGFJIBJ();

		LJKBFOAOAJG HMBHNLCFDIH_readData = res_readData.OPBPOOKODJK;
		NKCJNCELIJN HMBHNLCFDIH_data = new NKCJNCELIJN();

		HMBHNLCFDIH_data.OPFGFINHFCE = HMBHNLCFDIH_readData.IIDCFMHCPLJ;
		HMBHNLCFDIH_data.HEDAGCNPHGD = HMBHNLCFDIH_readData.HAEJDOGGKPC;
		HMBHNLCFDIH_data.IDGAEEJLGIK = HMBHNLCFDIH_readData.NNCGCDNLJEE;
		HMBHNLCFDIH_data.OBGBAOLONDD = HMBHNLCFDIH_readData.MAIJBDCJPNJ;
		HMBHNLCFDIH_data.OCGFKMHNEOF = HMBHNLCFDIH_readData.MKDFHLALNAF;
		HMBHNLCFDIH_data.OGMGLOFKKPA = HMBHNLCFDIH_readData.LIBHMBEONKC;
		HMBHNLCFDIH_data.MOEKELIIDEO = HMBHNLCFDIH_readData.MCHOEAGDGJP;
		HMBHNLCFDIH_data.BONDDBOFBND = HMBHNLCFDIH_readData.LLJNABNBDMN;
		HMBHNLCFDIH_data.EHHFFKAFOMC = HMBHNLCFDIH_readData.DEPHCHOBAJG;
		HMBHNLCFDIH_data.HPNOGLIFJOP = HMBHNLCFDIH_readData.DJHKCHMBGHC;
		HMBHNLCFDIH_data.LNFKGHNHJKE = HMBHNLCFDIH_readData.BCKOLCDDIAG;
		HMBHNLCFDIH_data.JGMDAOACOJF = HMBHNLCFDIH_readData.LKIBIHGHEMA;
		HMBHNLCFDIH_data.IDDBFFBPNGI = HMBHNLCFDIH_readData.ANELKJCGJJL;
		HMBHNLCFDIH_data.KNLGKBBIBOH = HMBHNLCFDIH_readData.AEOKLKJAKHB;
		HMBHNLCFDIH_data.JBFDHOIKAIK = HMBHNLCFDIH_readData.IDMMPIIIPLL;
		HMBHNLCFDIH_data.KHIKEGLBGAF = HMBHNLCFDIH_readData.HKPPDACCCOH;
		HMBHNLCFDIH_data.DPJCFLKFEPN = HMBHNLCFDIH_readData.NAMFJMCKFIF;
		List<uint> EEOGPJJCKHH_list = new List<uint>();
		for(int EEOGPJJCKHH_idx = 0; EEOGPJJCKHH_idx < HMBHNLCFDIH_readData.EBFEIMNOLHPLength; EEOGPJJCKHH_idx++)
		{
			EEOGPJJCKHH_list.Add(HMBHNLCFDIH_readData.GetEBFEIMNOLHP(EEOGPJJCKHH_idx));
		}
		HMBHNLCFDIH_data.EEOGPJJCKHH = EEOGPJJCKHH_list.ToArray();

		HMBHNLCFDIH_data.JMJDLDEIFKE = HMBHNLCFDIH_readData.OGBOPHDAMCI;
		HMBHNLCFDIH_data.AHKNMANFILO = HMBHNLCFDIH_readData.HGFJBAJCFNF;
		HMBHNLCFDIH_data.OCDMGOGMHGE = HMBHNLCFDIH_readData.HAEMDABJFJF;
		HMBHNLCFDIH_data.PJBILOFOCIC = HMBHNLCFDIH_readData.PPCOEAIPHKA;
		HMBHNLCFDIH_data.MJBKGOJBPAD = HMBHNLCFDIH_readData.BNOHOIBDHLP;
		HMBHNLCFDIH_data.FEMMDNIELFC = HMBHNLCFDIH_readData.NNKLANONDOM;
		HMBHNLCFDIH_data.HKKNEAGCIEB = HMBHNLCFDIH_readData.LENBJLOPKLE;
		List<int> JHPCPNJJHLI_list = new List<int>();
		for(int JHPCPNJJHLI_idx = 0; JHPCPNJJHLI_idx < HMBHNLCFDIH_readData.KNDBMPNNCGGLength; JHPCPNJJHLI_idx++)
		{
			JHPCPNJJHLI_list.Add(HMBHNLCFDIH_readData.GetKNDBMPNNCGG(JHPCPNJJHLI_idx));
		}
		HMBHNLCFDIH_data.JHPCPNJJHLI = JHPCPNJJHLI_list.ToArray();

		List<uint> HIAMHLLHAON_list = new List<uint>();
		for(int HIAMHLLHAON_idx = 0; HIAMHLLHAON_idx < HMBHNLCFDIH_readData.JFKBEBPJGBHLength; HIAMHLLHAON_idx++)
		{
			HIAMHLLHAON_list.Add(HMBHNLCFDIH_readData.GetJFKBEBPJGBH(HIAMHLLHAON_idx));
		}
		HMBHNLCFDIH_data.HIAMHLLHAON = HIAMHLLHAON_list.ToArray();

		List<int> JKFPADIAKCK_list = new List<int>();
		for(int JKFPADIAKCK_idx = 0; JKFPADIAKCK_idx < HMBHNLCFDIH_readData.OJBCAEPBACPLength; JKFPADIAKCK_idx++)
		{
			JKFPADIAKCK_list.Add(HMBHNLCFDIH_readData.GetOJBCAEPBACP(JKFPADIAKCK_idx));
		}
		HMBHNLCFDIH_data.JKFPADIAKCK = JKFPADIAKCK_list.ToArray();

		HMBHNLCFDIH_data.OMCAOJJGOGG = HMBHNLCFDIH_readData.EMNAOOMCCGD;
		HMBHNLCFDIH_data.HIOOGLEJBKM = HMBHNLCFDIH_readData.ODMLFHELAJK;
		HMBHNLCFDIH_data.FJCADCDNPMP = HMBHNLCFDIH_readData.JOIACOFCFAA;
		List<int> EJBGHLOOLBC_list = new List<int>();
		for(int EJBGHLOOLBC_idx = 0; EJBGHLOOLBC_idx < HMBHNLCFDIH_readData.CLEFGBLBDGJLength; EJBGHLOOLBC_idx++)
		{
			EJBGHLOOLBC_list.Add(HMBHNLCFDIH_readData.GetCLEFGBLBDGJ(EJBGHLOOLBC_idx));
		}
		HMBHNLCFDIH_data.EJBGHLOOLBC = EJBGHLOOLBC_list.ToArray();

		HMBHNLCFDIH_data.AHKPNPNOAMO = HMBHNLCFDIH_readData.KPCNGKDBMHA;
		List<int> LJENLHCBLEL_list = new List<int>();
		for(int LJENLHCBLEL_idx = 0; LJENLHCBLEL_idx < HMBHNLCFDIH_readData.NIPICAKPCOJLength; LJENLHCBLEL_idx++)
		{
			LJENLHCBLEL_list.Add(HMBHNLCFDIH_readData.GetNIPICAKPCOJ(LJENLHCBLEL_idx));
		}
		HMBHNLCFDIH_data.LJENLHCBLEL = LJENLHCBLEL_list.ToArray();

		List<int> PLGNGKNPNCN_list = new List<int>();
		for(int PLGNGKNPNCN_idx = 0; PLGNGKNPNCN_idx < HMBHNLCFDIH_readData.HDHNOMIENLOLength; PLGNGKNPNCN_idx++)
		{
			PLGNGKNPNCN_list.Add(HMBHNLCFDIH_readData.GetHDHNOMIENLO(PLGNGKNPNCN_idx));
		}
		HMBHNLCFDIH_data.PLGNGKNPNCN = PLGNGKNPNCN_list.ToArray();

		HMBHNLCFDIH_data.EKJFNHHKBPL = HMBHNLCFDIH_readData.HFKHLKGAJEL;
		res_data.HMBHNLCFDIH = HMBHNLCFDIH_data;
		List<FPJPKBBOICF> MCHFABAKPMH_list = new List<FPJPKBBOICF>();
		for(int MCHFABAKPMH_idx = 0; MCHFABAKPMH_idx < res_readData.KJFDCEGGPPHLength; MCHFABAKPMH_idx++)
		{
			DPJIIOJHIDD MCHFABAKPMH_readData = res_readData.GetKJFDCEGGPPH(MCHFABAKPMH_idx);
			FPJPKBBOICF MCHFABAKPMH_data = new FPJPKBBOICF();

			MCHFABAKPMH_data.PPFNGGCBJKC = MCHFABAKPMH_readData.BBPHAPFBFHK;
			MCHFABAKPMH_data.FOILNHKHHDF = MCHFABAKPMH_readData.HJNPKHJJDBB;
			List<int> AIHOJKFNEEN_list = new List<int>();
			for(int AIHOJKFNEEN_idx = 0; AIHOJKFNEEN_idx < MCHFABAKPMH_readData.LEFPIGNDJNCLength; AIHOJKFNEEN_idx++)
			{
				AIHOJKFNEEN_list.Add(MCHFABAKPMH_readData.GetLEFPIGNDJNC(AIHOJKFNEEN_idx));
			}
			MCHFABAKPMH_data.AIHOJKFNEEN = AIHOJKFNEEN_list.ToArray();

			List<uint> BFINGCJHOHI_list = new List<uint>();
			for(int BFINGCJHOHI_idx = 0; BFINGCJHOHI_idx < MCHFABAKPMH_readData.BNCIPLKECMCLength; BFINGCJHOHI_idx++)
			{
				BFINGCJHOHI_list.Add(MCHFABAKPMH_readData.GetBNCIPLKECMC(BFINGCJHOHI_idx));
			}
			MCHFABAKPMH_data.BFINGCJHOHI = BFINGCJHOHI_list.ToArray();

			List<uint> JJHPDDPKBHF_list = new List<uint>();
			for(int JJHPDDPKBHF_idx = 0; JJHPDDPKBHF_idx < MCHFABAKPMH_readData.OOJBHHPJONJLength; JJHPDDPKBHF_idx++)
			{
				JJHPDDPKBHF_list.Add(MCHFABAKPMH_readData.GetOOJBHHPJONJ(JJHPDDPKBHF_idx));
			}
			MCHFABAKPMH_data.JJHPDDPKBHF = JJHPDDPKBHF_list.ToArray();

			MCHFABAKPMH_data.JOPPFEHKNFO = MCHFABAKPMH_readData.ALPALMJMJJK;
			List<uint> HJAFPEBIBOP_list = new List<uint>();
			for(int HJAFPEBIBOP_idx = 0; HJAFPEBIBOP_idx < MCHFABAKPMH_readData.PODPGCKCBEOLength; HJAFPEBIBOP_idx++)
			{
				HJAFPEBIBOP_list.Add(MCHFABAKPMH_readData.GetPODPGCKCBEO(HJAFPEBIBOP_idx));
			}
			MCHFABAKPMH_data.HJAFPEBIBOP = HJAFPEBIBOP_list.ToArray();

			MCHFABAKPMH_list.Add(MCHFABAKPMH_data);
		}
		res_data.MCHFABAKPMH = MCHFABAKPMH_list.ToArray();

		List<JGHDNNFHEHC> MDDOGIAFDEI_list = new List<JGHDNNFHEHC>();
		for(int MDDOGIAFDEI_idx = 0; MDDOGIAFDEI_idx < res_readData.OIJINAJFMCBLength; MDDOGIAFDEI_idx++)
		{
			FEGHFAKKEGO MDDOGIAFDEI_readData = res_readData.GetOIJINAJFMCB(MDDOGIAFDEI_idx);
			JGHDNNFHEHC MDDOGIAFDEI_data = new JGHDNNFHEHC();

			MDDOGIAFDEI_data.PPFNGGCBJKC = MDDOGIAFDEI_readData.BBPHAPFBFHK;
			MDDOGIAFDEI_data.PLALNIIBLOF = MDDOGIAFDEI_readData.CFLMCGOJJJD;
			MDDOGIAFDEI_data.GBJFNGCDKPM = MDDOGIAFDEI_readData.LPJPOOHJKAE;
			MDDOGIAFDEI_data.FPOMEEJFBIG = MDDOGIAFDEI_readData.AEAKMMJLLDK;
			MDDOGIAFDEI_data.FEMMDNIELFC = MDDOGIAFDEI_readData.NNKLANONDOM;
			MDDOGIAFDEI_data.BGBJPGEIEDE = MDDOGIAFDEI_readData.JGAGKFPAAIB;
			MDDOGIAFDEI_data.BDKFOMGCOOE = MDDOGIAFDEI_readData.NMGIFIOPMIJ;
			MDDOGIAFDEI_data.PJGIAKGGHPF = MDDOGIAFDEI_readData.NFPKGHADCCP;
			MDDOGIAFDEI_data.MMCBOJHFDEF = MDDOGIAFDEI_readData.PJCPCILBICH;
			MDDOGIAFDEI_data.JBECECBFFBF = MDDOGIAFDEI_readData.GAHFANCNFIH;
			MDDOGIAFDEI_data.LDOMFAMFGLM = MDDOGIAFDEI_readData.ANOHJLDOAAK;
			MDDOGIAFDEI_data.BMDGADMKOIH = MDDOGIAFDEI_readData.GJJPLLHMMAF;
			MDDOGIAFDEI_data.AIIEBILNLGO = MDDOGIAFDEI_readData.AJHANMOKKDF;
			MDDOGIAFDEI_data.JOGDEMBADLO = MDDOGIAFDEI_readData.PBAJJGLCCDO;
			MDDOGIAFDEI_data.GMJBANCDOJK = MDDOGIAFDEI_readData.MPMOLHBIKKG;
			MDDOGIAFDEI_data.AIEOAMKDHJC = MDDOGIAFDEI_readData.ENECIEOGIJC;
			MDDOGIAFDEI_data.GLCLFMGPMAN = MDDOGIAFDEI_readData.MBBJMJAAODG;
			MDDOGIAFDEI_data.MBJIFDBEDAC = MDDOGIAFDEI_readData.IMCFOKIBEMC;
			MDDOGIAFDEI_data.HLOBFDBFINJ = MDDOGIAFDEI_readData.OADMJNEOKLC;
			MDDOGIAFDEI_data.JJHPDDPKBHF = MDDOGIAFDEI_readData.EGCKDOIIACL;
			MDDOGIAFDEI_data.KOACGMPOIGN = MDDOGIAFDEI_readData.GPBKFHCJEPD;
			MDDOGIAFDEI_data.ADCKKAFCIAC = MDDOGIAFDEI_readData.EBBBDFADIPN;
			MDDOGIAFDEI_data.FNEIADJMHHO = MDDOGIAFDEI_readData.GLIIHLOLPEF;
			MDDOGIAFDEI_data.EICJBAEDMNM = MDDOGIAFDEI_readData.KMEODDMBHHE;
			MDDOGIAFDEI_data.HJAFPEBIBOP = MDDOGIAFDEI_readData.HBHEHJDPEBI;
			MDDOGIAFDEI_list.Add(MDDOGIAFDEI_data);
		}
		res_data.MDDOGIAFDEI = MDDOGIAFDEI_list.ToArray();

		List<EBDMGCHHCFD> DDIGKGINBKL_list = new List<EBDMGCHHCFD>();
		for(int DDIGKGINBKL_idx = 0; DDIGKGINBKL_idx < res_readData.AOANPDIPJJILength; DDIGKGINBKL_idx++)
		{
			IICAOBEAJHF DDIGKGINBKL_readData = res_readData.GetAOANPDIPJJI(DDIGKGINBKL_idx);
			EBDMGCHHCFD DDIGKGINBKL_data = new EBDMGCHHCFD();

			DDIGKGINBKL_data.EEAPIKNJNDB = DDIGKGINBKL_readData.CHIFDEGOIBH;
			DDIGKGINBKL_data.NNDBJGDFEEM = DDIGKGINBKL_readData.CCIHMCAPHCB;
			DDIGKGINBKL_data.DOOGFEGEKLG = DDIGKGINBKL_readData.GEJGMBBCFEE;
			DDIGKGINBKL_data.HNDOLKNBOIJ = DDIGKGINBKL_readData.LKLFOCIFLIE;
			DDIGKGINBKL_data.HHGFOIMIGED = DDIGKGINBKL_readData.MENLAOCDKFD;
			DDIGKGINBKL_data.IBCMDICBGHH = DDIGKGINBKL_readData.PBANPANLNFF;
			DDIGKGINBKL_data.HKAILALAFDG = DDIGKGINBKL_readData.JGIPHJMJPEI;
			DDIGKGINBKL_data.DJJGNDCMNHF = DDIGKGINBKL_readData.DMNNOAFOPFI;
			DDIGKGINBKL_list.Add(DDIGKGINBKL_data);
		}
		res_data.DDIGKGINBKL = DDIGKGINBKL_list.ToArray();

		List<BAJEBICKGPF> MDMKOGDHCIC_list = new List<BAJEBICKGPF>();
		for(int MDMKOGDHCIC_idx = 0; MDMKOGDHCIC_idx < res_readData.OFDNIJAEIIFLength; MDMKOGDHCIC_idx++)
		{
			MGJAIDMKMCE MDMKOGDHCIC_readData = res_readData.GetOFDNIJAEIIF(MDMKOGDHCIC_idx);
			BAJEBICKGPF MDMKOGDHCIC_data = new BAJEBICKGPF();

			MDMKOGDHCIC_data.PPFNGGCBJKC = MDMKOGDHCIC_readData.BBPHAPFBFHK;
			MDMKOGDHCIC_data.PLALNIIBLOF = MDMKOGDHCIC_readData.CFLMCGOJJJD;
			MDMKOGDHCIC_data.OPFGFINHFCE = MDMKOGDHCIC_readData.IIDCFMHCPLJ;
			MDMKOGDHCIC_data.GOIKCKHMBDL = MDMKOGDHCIC_readData.IKILGDOHAFC;
			MDMKOGDHCIC_data.AKNELONELJK = MDMKOGDHCIC_readData.CLPPHJAOKPA;
			MDMKOGDHCIC_data.KNIFCANOHOC = MDMKOGDHCIC_readData.IHBIEFNEPMC;
			MDMKOGDHCIC_data.EDJMDDAGCEJ = MDMKOGDHCIC_readData.NMBMENKFDCE;
			MDMKOGDHCIC_data.HEFPAIOLBAG = MDMKOGDHCIC_readData.PDIBMFKEJMM;
			MDMKOGDHCIC_data.DIPKCALNIII = MDMKOGDHCIC_readData.DPKCMAHGHNI;
			MDMKOGDHCIC_data.JFFOEAANFPG = MDMKOGDHCIC_readData.BMONGFPOEOB;
			MDMKOGDHCIC_data.HEBKEJBDCBH = MDMKOGDHCIC_readData.FMJMJIKOLFL;
			MDMKOGDHCIC_data.GLILAGLJLEP = MDMKOGDHCIC_readData.AACHELNDICD;
			MDMKOGDHCIC_data.ECOLMPLOPFM = MDMKOGDHCIC_readData.FKLPAEODOCH;
			MDMKOGDHCIC_data.CFCIMKOHLIG = MDMKOGDHCIC_readData.FPHHEKLGANL;
			MDMKOGDHCIC_data.IPPNCOHEEOD = MDMKOGDHCIC_readData.KELLGKFABLD;
			List<int> MJNMPAKBNKB_list = new List<int>();
			for(int MJNMPAKBNKB_idx = 0; MJNMPAKBNKB_idx < MDMKOGDHCIC_readData.CENBENCHADMLength; MJNMPAKBNKB_idx++)
			{
				MJNMPAKBNKB_list.Add(MDMKOGDHCIC_readData.GetCENBENCHADM(MJNMPAKBNKB_idx));
			}
			MDMKOGDHCIC_data.MJNMPAKBNKB = MJNMPAKBNKB_list.ToArray();

			MDMKOGDHCIC_data.BDLNMOIOMHK = MDMKOGDHCIC_readData.LBMKEILIGBG;
			MDMKOGDHCIC_data.NLKEBAOBJCM = MDMKOGDHCIC_readData.NBDEBEPOLOB;
			MDMKOGDHCIC_data.ENNCJKLIGKE = MDMKOGDHCIC_readData.NPIBNFGMMEK;
			MDMKOGDHCIC_data.PALEGNNHIKH = MDMKOGDHCIC_readData.HAMEBHALAEN;
			MDMKOGDHCIC_data.JCDEDIOAGKE = MDMKOGDHCIC_readData.OEGNNNEFAAK;
			MDMKOGDHCIC_list.Add(MDMKOGDHCIC_data);
		}
		res_data.MDMKOGDHCIC = MDMKOGDHCIC_list.ToArray();

		List<OBMEFONPANB> BHGDNGHDDAC_list = new List<OBMEFONPANB>();
		for(int BHGDNGHDDAC_idx = 0; BHGDNGHDDAC_idx < res_readData.NJJINHMIOHNLength; BHGDNGHDDAC_idx++)
		{
			FKOAKLHPCHP BHGDNGHDDAC_readData = res_readData.GetNJJINHMIOHN(BHGDNGHDDAC_idx);
			OBMEFONPANB BHGDNGHDDAC_data = new OBMEFONPANB();

			BHGDNGHDDAC_data.LJNAKDMILMC = BHGDNGHDDAC_readData.AGOIMGHMGOH;
			BHGDNGHDDAC_data.JBGEEPFKIGG = BHGDNGHDDAC_readData.KJFEBMBHKOC;
			BHGDNGHDDAC_list.Add(BHGDNGHDDAC_data);
		}
		res_data.BHGDNGHDDAC = BHGDNGHDDAC_list.ToArray();

		List<CNMODGDHGHA> MHGMDJNOLMI_list = new List<CNMODGDHGHA>();
		for(int MHGMDJNOLMI_idx = 0; MHGMDJNOLMI_idx < res_readData.NPFBHGKLIOMLength; MHGMDJNOLMI_idx++)
		{
			KKJAMCMMILC MHGMDJNOLMI_readData = res_readData.GetNPFBHGKLIOM(MHGMDJNOLMI_idx);
			CNMODGDHGHA MHGMDJNOLMI_data = new CNMODGDHGHA();

			MHGMDJNOLMI_data.LJNAKDMILMC = MHGMDJNOLMI_readData.AGOIMGHMGOH;
			MHGMDJNOLMI_data.JBGEEPFKIGG = MHGMDJNOLMI_readData.KJFEBMBHKOC;
			MHGMDJNOLMI_list.Add(MHGMDJNOLMI_data);
		}
		res_data.MHGMDJNOLMI = MHGMDJNOLMI_list.ToArray();

		List<PDEFFJNHFOE> KIEKMCKCMGD_list = new List<PDEFFJNHFOE>();
		for(int KIEKMCKCMGD_idx = 0; KIEKMCKCMGD_idx < res_readData.FBAHAFKCMMHLength; KIEKMCKCMGD_idx++)
		{
			CFPOOLLFNPL KIEKMCKCMGD_readData = res_readData.GetFBAHAFKCMMH(KIEKMCKCMGD_idx);
			PDEFFJNHFOE KIEKMCKCMGD_data = new PDEFFJNHFOE();

			KIEKMCKCMGD_data.PPFNGGCBJKC = KIEKMCKCMGD_readData.BBPHAPFBFHK;
			KIEKMCKCMGD_data.KFCIJBLDHOK = KIEKMCKCMGD_readData.MCJNHPMBPIJ;
			KIEKMCKCMGD_data.JLEIHOEGMOP = KIEKMCKCMGD_readData.MGJKFKDICGC;
			KIEKMCKCMGD_list.Add(KIEKMCKCMGD_data);
		}
		res_data.KIEKMCKCMGD = KIEKMCKCMGD_list.ToArray();

		List<EGFGKMKLEFG> MHKNGJMEGFI_list = new List<EGFGKMKLEFG>();
		for(int MHKNGJMEGFI_idx = 0; MHKNGJMEGFI_idx < res_readData.GGKDJGGAFKALength; MHKNGJMEGFI_idx++)
		{
			BPAAICMLPOI MHKNGJMEGFI_readData = res_readData.GetGGKDJGGAFKA(MHKNGJMEGFI_idx);
			EGFGKMKLEFG MHKNGJMEGFI_data = new EGFGKMKLEFG();

			MHKNGJMEGFI_data.PPFNGGCBJKC = MHKNGJMEGFI_readData.BBPHAPFBFHK;
			MHKNGJMEGFI_data.GBJFNGCDKPM = MHKNGJMEGFI_readData.LPJPOOHJKAE;
			MHKNGJMEGFI_data.JBGEEPFKIGG = MHKNGJMEGFI_readData.KJFEBMBHKOC;
			MHKNGJMEGFI_data.MAFAIIHJAFG = MHKNGJMEGFI_readData.LAIEPFCPDLK;
			MHKNGJMEGFI_list.Add(MHKNGJMEGFI_data);
		}
		res_data.MHKNGJMEGFI = MHKNGJMEGFI_list.ToArray();

		List<IJFIMCBAJDJ> GHIHAGAOPNC_list = new List<IJFIMCBAJDJ>();
		for(int GHIHAGAOPNC_idx = 0; GHIHAGAOPNC_idx < res_readData.AJMKEFMPKHBLength; GHIHAGAOPNC_idx++)
		{
			KBACMNEFKPH GHIHAGAOPNC_readData = res_readData.GetAJMKEFMPKHB(GHIHAGAOPNC_idx);
			IJFIMCBAJDJ GHIHAGAOPNC_data = new IJFIMCBAJDJ();

			GHIHAGAOPNC_data.PPFNGGCBJKC = GHIHAGAOPNC_readData.BBPHAPFBFHK;
			GHIHAGAOPNC_data.PLALNIIBLOF = GHIHAGAOPNC_readData.CFLMCGOJJJD;
			GHIHAGAOPNC_data.MPLGPBNJDJB = GHIHAGAOPNC_readData.IAPFGOHKAGE;
			GHIHAGAOPNC_data.CPBFAMJEODF = GHIHAGAOPNC_readData.HBMAMCJNDIH;
			GHIHAGAOPNC_data.MGHPJNNDCIG = GHIHAGAOPNC_readData.PMPNFFNPDPJ;
			GHIHAGAOPNC_data.PDBPFJJCADD = GHIHAGAOPNC_readData.NJLJEKDBPCH;
			GHIHAGAOPNC_data.FDBNFFNFOND = GHIHAGAOPNC_readData.MAOAGDBDBIB;
			GHIHAGAOPNC_list.Add(GHIHAGAOPNC_data);
		}
		res_data.GHIHAGAOPNC = GHIHAGAOPNC_list.ToArray();

		List<HJEKNHMEPBP> PLHPEOKOMHH_list = new List<HJEKNHMEPBP>();
		for(int PLHPEOKOMHH_idx = 0; PLHPEOKOMHH_idx < res_readData.MBCMHJLOICPLength; PLHPEOKOMHH_idx++)
		{
			NGMAEKGBJCM PLHPEOKOMHH_readData = res_readData.GetMBCMHJLOICP(PLHPEOKOMHH_idx);
			HJEKNHMEPBP PLHPEOKOMHH_data = new HJEKNHMEPBP();

			PLHPEOKOMHH_data.PPFNGGCBJKC = PLHPEOKOMHH_readData.BBPHAPFBFHK;
			PLHPEOKOMHH_data.PLALNIIBLOF = PLHPEOKOMHH_readData.CFLMCGOJJJD;
			PLHPEOKOMHH_data.KOJMEPJBOJM = PLHPEOKOMHH_readData.NMDCNDPDNMM;
			PLHPEOKOMHH_data.PDBPFJJCADD = PLHPEOKOMHH_readData.NJLJEKDBPCH;
			PLHPEOKOMHH_data.FDBNFFNFOND = PLHPEOKOMHH_readData.MAOAGDBDBIB;
			PLHPEOKOMHH_list.Add(PLHPEOKOMHH_data);
		}
		res_data.PLHPEOKOMHH = PLHPEOKOMHH_list.ToArray();

		List<HIGMGCAKFAN> NIPMOFJPFJG_list = new List<HIGMGCAKFAN>();
		for(int NIPMOFJPFJG_idx = 0; NIPMOFJPFJG_idx < res_readData.PONHONIGHOOLength; NIPMOFJPFJG_idx++)
		{
			DFOHOJKKKDJ NIPMOFJPFJG_readData = res_readData.GetPONHONIGHOO(NIPMOFJPFJG_idx);
			HIGMGCAKFAN NIPMOFJPFJG_data = new HIGMGCAKFAN();

			NIPMOFJPFJG_data.PPFNGGCBJKC = NIPMOFJPFJG_readData.BBPHAPFBFHK;
			NIPMOFJPFJG_data.PLALNIIBLOF = NIPMOFJPFJG_readData.CFLMCGOJJJD;
			NIPMOFJPFJG_data.APGKOJKNNGP = NIPMOFJPFJG_readData.MJGMLHPCJKL;
			NIPMOFJPFJG_data.AFKHNFBOMKI = NIPMOFJPFJG_readData.KEJFLGLANOM;
			List<int> HHOFENIINIJ_list = new List<int>();
			for(int HHOFENIINIJ_idx = 0; HHOFENIINIJ_idx < NIPMOFJPFJG_readData.KKIOBDILLGCLength; HHOFENIINIJ_idx++)
			{
				HHOFENIINIJ_list.Add(NIPMOFJPFJG_readData.GetKKIOBDILLGC(HHOFENIINIJ_idx));
			}
			NIPMOFJPFJG_data.HHOFENIINIJ = HHOFENIINIJ_list.ToArray();

			NIPMOFJPFJG_data.LNNOCPJLNFD = NIPMOFJPFJG_readData.GCPGKNHOELA;
			NIPMOFJPFJG_data.GCPKJPNENJJ = NIPMOFJPFJG_readData.OINHNODKGMO;
			NIPMOFJPFJG_data.FLOAHHHAOLE = NIPMOFJPFJG_readData.PDMFOEDKBPM;
			NIPMOFJPFJG_data.COJMPBFFJFI = NIPMOFJPFJG_readData.DKLGCNIKBNO;
			NIPMOFJPFJG_data.KPFDEBIEAME = NIPMOFJPFJG_readData.CAOMFEHHCJO;
			NIPMOFJPFJG_data.MCBDCDLKACL = NIPMOFJPFJG_readData.NGHNHBKONEK;
			NIPMOFJPFJG_data.JLDNDNNDEEH = NIPMOFJPFJG_readData.AAEFDGPJPDH;
			NIPMOFJPFJG_data.LIIIGJFLAAB = NIPMOFJPFJG_readData.BPOBCDFADPN;
			NIPMOFJPFJG_data.NGNKKFNDEPD = NIPMOFJPFJG_readData.BDPKAIDKLBB;
			NIPMOFJPFJG_data.MKOKEGGPFBC = NIPMOFJPFJG_readData.PKAOKEACOEE;
			NIPMOFJPFJG_list.Add(NIPMOFJPFJG_data);
		}
		res_data.NIPMOFJPFJG = NIPMOFJPFJG_list.ToArray();

		List<FMPMFOBJNCM> IHNBOEPLJKE_list = new List<FMPMFOBJNCM>();
		for(int IHNBOEPLJKE_idx = 0; IHNBOEPLJKE_idx < res_readData.JHDOILHEBOGLength; IHNBOEPLJKE_idx++)
		{
			ONKCPJNPOHI IHNBOEPLJKE_readData = res_readData.GetJHDOILHEBOG(IHNBOEPLJKE_idx);
			FMPMFOBJNCM IHNBOEPLJKE_data = new FMPMFOBJNCM();

			IHNBOEPLJKE_data.PPFNGGCBJKC = IHNBOEPLJKE_readData.BBPHAPFBFHK;
			IHNBOEPLJKE_data.PDBPFJJCADD = IHNBOEPLJKE_readData.NJLJEKDBPCH;
			IHNBOEPLJKE_data.FDBNFFNFOND = IHNBOEPLJKE_readData.MAOAGDBDBIB;
			IHNBOEPLJKE_data.FEMMDNIELFC = IHNBOEPLJKE_readData.NNKLANONDOM;
			IHNBOEPLJKE_list.Add(IHNBOEPLJKE_data);
		}
		res_data.IHNBOEPLJKE = IHNBOEPLJKE_list.ToArray();

		List<NFEINLOIPEP> OLACFKILCFD_list = new List<NFEINLOIPEP>();
		for(int OLACFKILCFD_idx = 0; OLACFKILCFD_idx < res_readData.HDNMEPFHLNFLength; OLACFKILCFD_idx++)
		{
			BDHHMNFDCJO OLACFKILCFD_readData = res_readData.GetHDNMEPFHLNF(OLACFKILCFD_idx);
			NFEINLOIPEP OLACFKILCFD_data = new NFEINLOIPEP();

			OLACFKILCFD_data.PPFNGGCBJKC = OLACFKILCFD_readData.BBPHAPFBFHK;
			OLACFKILCFD_data.CNKFPJCGNFE = OLACFKILCFD_readData.DPFDOIIOICA;
			OLACFKILCFD_data.GNFBMCGMCFO = OLACFKILCFD_readData.GEAIPAEKLNF;
			OLACFKILCFD_data.BFFGFAMJAIG = OLACFKILCFD_readData.JGILGOILJNK;
			OLACFKILCFD_list.Add(OLACFKILCFD_data);
		}
		res_data.OLACFKILCFD = OLACFKILCFD_list.ToArray();

		List<PHNMAKOGBKJ> MIOCOKLMLBD_list = new List<PHNMAKOGBKJ>();
		for(int MIOCOKLMLBD_idx = 0; MIOCOKLMLBD_idx < res_readData.OLLJCDPOAAILength; MIOCOKLMLBD_idx++)
		{
			CGCBGGNEJKJ MIOCOKLMLBD_readData = res_readData.GetOLLJCDPOAAI(MIOCOKLMLBD_idx);
			PHNMAKOGBKJ MIOCOKLMLBD_data = new PHNMAKOGBKJ();

			MIOCOKLMLBD_data.PPFNGGCBJKC = MIOCOKLMLBD_readData.BBPHAPFBFHK;
			MIOCOKLMLBD_data.GNFBMCGMCFO = MIOCOKLMLBD_readData.GEAIPAEKLNF;
			MIOCOKLMLBD_data.BFFGFAMJAIG = MIOCOKLMLBD_readData.JGILGOILJNK;
			MIOCOKLMLBD_list.Add(MIOCOKLMLBD_data);
		}
		res_data.MIOCOKLMLBD = MIOCOKLMLBD_list.ToArray();

		List<FJOLJGPGDGD> IEJLJIHIDJC_list = new List<FJOLJGPGDGD>();
		for(int IEJLJIHIDJC_idx = 0; IEJLJIHIDJC_idx < res_readData.BHNBMLKMLGNLength; IEJLJIHIDJC_idx++)
		{
			CKLOMKMJBLL IEJLJIHIDJC_readData = res_readData.GetBHNBMLKMLGN(IEJLJIHIDJC_idx);
			FJOLJGPGDGD IEJLJIHIDJC_data = new FJOLJGPGDGD();

			IEJLJIHIDJC_data.KHPHAAMGMJP = IEJLJIHIDJC_readData.OEBLGFLPMNE;
			IEJLJIHIDJC_data.OFIAENKCJME = IEJLJIHIDJC_readData.BJELMJJFMBI;
			List<int> JMLCLHHLJHM_list = new List<int>();
			for(int JMLCLHHLJHM_idx = 0; JMLCLHHLJHM_idx < IEJLJIHIDJC_readData.IHNCJBFCAAILength; JMLCLHHLJHM_idx++)
			{
				JMLCLHHLJHM_list.Add(IEJLJIHIDJC_readData.GetIHNCJBFCAAI(JMLCLHHLJHM_idx));
			}
			IEJLJIHIDJC_data.JMLCLHHLJHM = JMLCLHHLJHM_list.ToArray();

			IEJLJIHIDJC_list.Add(IEJLJIHIDJC_data);
		}
		res_data.IEJLJIHIDJC = IEJLJIHIDJC_list.ToArray();

		return res_data;
	}
}
