using FlatBuffers;
using System.Collections.Generic;

public class OCANCOENHML
{
	public uint PPFNGGCBJKC { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO HIGKAIDMOKN
	public uint PLALNIIBLOF { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE JJFJNEJLBDG
	public uint GBJFNGCDKPM { get; set; } // 0x10 GHLFADHILNN CEJJMKODOGK HOHCEBMMACI
	public uint JBFLEDKDFCO { get; set; } // 0x14 JOECCKJHICK LIJMKJLDHGP NFNCLFPPADP
	public uint CHOIMHCMAHG { get; set; } // 0x18 ALCEBFJAGJB APOIMEHLPBD HJFDHIEGGBH
	public uint PDBPFJJCADD { get; set; } // 0x1C PMJMBGBCIGO FOACOMBHPAC NBACOBCOJCA
	public uint FDBNFFNFOND { get; set; } // 0x20 INOJHLHGKMI BPJOGHJCLDJ NLJKMCHOCBK
	public int IJEKNCDIIAE { get; set; } // 0x24 FAHNCMHNFCG KJIMMIBDCIL DMEGNOKIKCD
}
public class PCKMEHLNOFO
{
	public OCANCOENHML[] EKDAACJJAPP { get; set; } // 0x8 NCLFBMBAOIK JGEKGHCEAIC IMEOEGMGECM
	public static PCKMEHLNOFO HEGEKFMJNCC(byte[] NIODCJLINJN)// 0xCC19EC
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		BNMAJCFEFOK res_readData = BNMAJCFEFOK.GetRootAsBNMAJCFEFOK(buffer);
		PCKMEHLNOFO res_data = new PCKMEHLNOFO();

		List<OCANCOENHML> EKDAACJJAPP_list = new List<OCANCOENHML>();
		for(int EKDAACJJAPP_idx = 0; EKDAACJJAPP_idx < res_readData.LHHOBGIGIEILength; EKDAACJJAPP_idx++)
		{
			PEDMFAEMCPG EKDAACJJAPP_readData = res_readData.GetLHHOBGIGIEI(EKDAACJJAPP_idx);
			OCANCOENHML EKDAACJJAPP_data = new OCANCOENHML();

			EKDAACJJAPP_data.PPFNGGCBJKC = EKDAACJJAPP_readData.BBPHAPFBFHK;
			EKDAACJJAPP_data.PLALNIIBLOF = EKDAACJJAPP_readData.CFLMCGOJJJD;
			EKDAACJJAPP_data.GBJFNGCDKPM = EKDAACJJAPP_readData.LPJPOOHJKAE;
			EKDAACJJAPP_data.JBFLEDKDFCO = EKDAACJJAPP_readData.HOENDPOGFIO;
			EKDAACJJAPP_data.CHOIMHCMAHG = EKDAACJJAPP_readData.DNIDLBOLLGH;
			EKDAACJJAPP_data.PDBPFJJCADD = EKDAACJJAPP_readData.NJLJEKDBPCH;
			EKDAACJJAPP_data.FDBNFFNFOND = EKDAACJJAPP_readData.MAOAGDBDBIB;
			EKDAACJJAPP_data.IJEKNCDIIAE = EKDAACJJAPP_readData.OFMGALJGDAO;
			EKDAACJJAPP_list.Add(EKDAACJJAPP_data);
		}
		res_data.EKDAACJJAPP = EKDAACJJAPP_list.ToArray();

		return res_data;
	}
}
