using FlatBuffers;
using System.Collections.Generic;

public class AFICKGBLCKO
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int FNEIADJMHHO_st { get; set; } // 0x10 PJFAGECNJCF FAPDANAMOKF_get_st JIHDPPHAAOJ_set_st
	public int KOMKKBDABJP_end { get; set; } // 0x14 JPPMFGFLNGH MOMCBDJIGKO_get_end NECMHGINPDE_set_end
	public string LLNDMKBBNIJ_ver { get; set; } // 0x18 BGOALFDCFBL OHMCGADLNCA_get_ver KJNHDFEGEGE_set_ver
	public string KOHNLDKIKPC_sb { get; set; } // 0x1C EAMJMDBMNKI KLCNELOBOGM_get_sb ILNHCICNFHF_set_sb
	public string BPFBAHCDJFJ { get; set; } // 0x20 BCJILIKDOAD CBFEAHBKODM_get_ KJLAKHNLPCG_set_
}
public class CNPDMOGIBEN
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int FNEIADJMHHO_st { get; set; } // 0x10 PJFAGECNJCF FAPDANAMOKF_get_st JIHDPPHAAOJ_set_st
	public int KOMKKBDABJP_end { get; set; } // 0x14 JPPMFGFLNGH MOMCBDJIGKO_get_end NECMHGINPDE_set_end
	public string KOHNLDKIKPC_sb { get; set; } // 0x18 EAMJMDBMNKI KLCNELOBOGM_get_sb ILNHCICNFHF_set_sb
	public string BPFBAHCDJFJ { get; set; } // 0x1C BCJILIKDOAD CBFEAHBKODM_get_ KJLAKHNLPCG_set_
}
public class CHOGPKAJDJN
{
	public int PPFNGGCBJKC_id { get; set; } // 0x8 FDGEMCPHJCB DEMEPMAEJOO_get_id HIGKAIDMOKN_set_id
	public int PLALNIIBLOF_en { get; set; } // 0xC DFMNDOMAPAB JPCJNLHHIPE_get_en JJFJNEJLBDG_set_en
	public int FNEIADJMHHO_st { get; set; } // 0x10 PJFAGECNJCF FAPDANAMOKF_get_st JIHDPPHAAOJ_set_st
	public int KOMKKBDABJP_end { get; set; } // 0x14 JPPMFGFLNGH MOMCBDJIGKO_get_end NECMHGINPDE_set_end
	public string LLNDMKBBNIJ_ver { get; set; } // 0x18 BGOALFDCFBL OHMCGADLNCA_get_ver KJNHDFEGEGE_set_ver
	public string CJEKGLGBIHF_path { get; set; } // 0x1C MLKJHEBAJFA JBNEOHCKDPL_get_path OPKIKIDFDKK_set_path
	public string KOHNLDKIKPC_sb { get; set; } // 0x20 EAMJMDBMNKI KLCNELOBOGM_get_sb ILNHCICNFHF_set_sb
	public string BPFBAHCDJFJ { get; set; } // 0x24 BCJILIKDOAD CBFEAHBKODM_get_ KJLAKHNLPCG_set_
}
public class NKJOBGGCCNA
{
	public int NHJBJIGNLHI { get; set; } // 0x8 GPBBDENNDAJ CALOGMNCDCM_get_ IPPJIMDIGPK_set_
	public string ADBOHBLBNDL { get; set; } // 0xC NPMGAJJELEL OPAPKEJLHCF_get_ GMJEJBHAAAL_set_
	public string IOIMHJAOKOO_Hash { get; set; } // 0x10 GMLEDKKPBFJ HJMJGBCJBIN_get_Hash OLGHLLNJPKD_set_Hash
}
public class PJADOKMABLA
{
	public AFICKGBLCKO[] KKFLAKPPPHL { get; set; } // 0x8 MOEKECBIILD DMEGLNCFKKH_get_ IDLCACEMKPK_set_
	public CNPDMOGIBEN[] HONMNBAJPGL { get; set; } // 0xC KBAKPGIOKAA LDNJEPPPPGA_get_ NELOBFINFJH_set_
	public CHOGPKAJDJN[] JDODPPDNNFK { get; set; } // 0x10 CGDOLHJEOBI NHIBBNMFLHJ_get_ LFKMDFGOCAB_set_
	public NKJOBGGCCNA[] MLMGFOGCDMD { get; set; } // 0x14 DCCINJNILEL FDHOOMNIEAE_get_ OFEAAAAKFCC_set_
	public static PJADOKMABLA HEGEKFMJNCC(byte[] NIODCJLINJN)// 0x92F49C
	{
		ByteBuffer buffer = new ByteBuffer(NIODCJLINJN);
		NBKNKAIJOGL res_readData_ = NBKNKAIJOGL.GetRootAsNBKNKAIJOGL(buffer);
		PJADOKMABLA res_data_ = new PJADOKMABLA();

		List<AFICKGBLCKO> KKFLAKPPPHL_list_ = new List<AFICKGBLCKO>();
		for(int KKFLAKPPPHL_idx_ = 0; KKFLAKPPPHL_idx_ < res_readData_.DDODJOIHKKGLength; KKFLAKPPPHL_idx_++)
		{
			POBCGIFNDJF KKFLAKPPPHL_readData_ = res_readData_.GetDDODJOIHKKG(KKFLAKPPPHL_idx_);
			AFICKGBLCKO KKFLAKPPPHL_data_ = new AFICKGBLCKO();

			KKFLAKPPPHL_data_.PPFNGGCBJKC_id = KKFLAKPPPHL_readData_.BBPHAPFBFHK/*_id*/;
			KKFLAKPPPHL_data_.PLALNIIBLOF_en = KKFLAKPPPHL_readData_.CFLMCGOJJJD/*_en*/;
			KKFLAKPPPHL_data_.FNEIADJMHHO_st = KKFLAKPPPHL_readData_.GLIIHLOLPEF/*_st*/;
			KKFLAKPPPHL_data_.KOMKKBDABJP_end = KKFLAKPPPHL_readData_.BNDAHALMIPE/*_end*/;
			KKFLAKPPPHL_data_.LLNDMKBBNIJ_ver = KKFLAKPPPHL_readData_.CNNEAFFOPAO/*_ver*/;
			KKFLAKPPPHL_data_.KOHNLDKIKPC_sb = KKFLAKPPPHL_readData_.ONBMIJLCFBD/*_sb*/;
			KKFLAKPPPHL_data_.BPFBAHCDJFJ = KKFLAKPPPHL_readData_.NNNCOKLKPIH;
			KKFLAKPPPHL_list_.Add(KKFLAKPPPHL_data_);
		}
		res_data_.KKFLAKPPPHL = KKFLAKPPPHL_list_.ToArray();

		List<CNPDMOGIBEN> HONMNBAJPGL_list_ = new List<CNPDMOGIBEN>();
		for(int HONMNBAJPGL_idx_ = 0; HONMNBAJPGL_idx_ < res_readData_.DLNKALNBAPBLength; HONMNBAJPGL_idx_++)
		{
			FMINENNNIEO HONMNBAJPGL_readData_ = res_readData_.GetDLNKALNBAPB(HONMNBAJPGL_idx_);
			CNPDMOGIBEN HONMNBAJPGL_data_ = new CNPDMOGIBEN();

			HONMNBAJPGL_data_.PPFNGGCBJKC_id = HONMNBAJPGL_readData_.BBPHAPFBFHK/*_id*/;
			HONMNBAJPGL_data_.PLALNIIBLOF_en = HONMNBAJPGL_readData_.CFLMCGOJJJD/*_en*/;
			HONMNBAJPGL_data_.FNEIADJMHHO_st = HONMNBAJPGL_readData_.GLIIHLOLPEF/*_st*/;
			HONMNBAJPGL_data_.KOMKKBDABJP_end = HONMNBAJPGL_readData_.BNDAHALMIPE/*_end*/;
			HONMNBAJPGL_data_.KOHNLDKIKPC_sb = HONMNBAJPGL_readData_.ONBMIJLCFBD/*_sb*/;
			HONMNBAJPGL_data_.BPFBAHCDJFJ = HONMNBAJPGL_readData_.NNNCOKLKPIH;
			HONMNBAJPGL_list_.Add(HONMNBAJPGL_data_);
		}
		res_data_.HONMNBAJPGL = HONMNBAJPGL_list_.ToArray();

		List<CHOGPKAJDJN> JDODPPDNNFK_list_ = new List<CHOGPKAJDJN>();
		for(int JDODPPDNNFK_idx_ = 0; JDODPPDNNFK_idx_ < res_readData_.NBNMLJNKNACLength; JDODPPDNNFK_idx_++)
		{
			FNHCIJOFLAE JDODPPDNNFK_readData_ = res_readData_.GetNBNMLJNKNAC(JDODPPDNNFK_idx_);
			CHOGPKAJDJN JDODPPDNNFK_data_ = new CHOGPKAJDJN();

			JDODPPDNNFK_data_.PPFNGGCBJKC_id = JDODPPDNNFK_readData_.BBPHAPFBFHK/*_id*/;
			JDODPPDNNFK_data_.PLALNIIBLOF_en = JDODPPDNNFK_readData_.CFLMCGOJJJD/*_en*/;
			JDODPPDNNFK_data_.FNEIADJMHHO_st = JDODPPDNNFK_readData_.GLIIHLOLPEF/*_st*/;
			JDODPPDNNFK_data_.KOMKKBDABJP_end = JDODPPDNNFK_readData_.BNDAHALMIPE/*_end*/;
			JDODPPDNNFK_data_.LLNDMKBBNIJ_ver = JDODPPDNNFK_readData_.CNNEAFFOPAO/*_ver*/;
			JDODPPDNNFK_data_.CJEKGLGBIHF_path = JDODPPDNNFK_readData_.GOIOMMIEMJF/*_path*/;
			JDODPPDNNFK_data_.KOHNLDKIKPC_sb = JDODPPDNNFK_readData_.ONBMIJLCFBD/*_sb*/;
			JDODPPDNNFK_data_.BPFBAHCDJFJ = JDODPPDNNFK_readData_.NNNCOKLKPIH;
			JDODPPDNNFK_list_.Add(JDODPPDNNFK_data_);
		}
		res_data_.JDODPPDNNFK = JDODPPDNNFK_list_.ToArray();

		List<NKJOBGGCCNA> MLMGFOGCDMD_list_ = new List<NKJOBGGCCNA>();
		for(int MLMGFOGCDMD_idx_ = 0; MLMGFOGCDMD_idx_ < res_readData_.PAAHAEGCMLFLength; MLMGFOGCDMD_idx_++)
		{
			MNOGIDIBJHJ MLMGFOGCDMD_readData_ = res_readData_.GetPAAHAEGCMLF(MLMGFOGCDMD_idx_);
			NKJOBGGCCNA MLMGFOGCDMD_data_ = new NKJOBGGCCNA();

			MLMGFOGCDMD_data_.NHJBJIGNLHI = MLMGFOGCDMD_readData_.LNPFMOAGCJJ;
			MLMGFOGCDMD_data_.ADBOHBLBNDL = MLMGFOGCDMD_readData_.FFONHAEBCEG;
			MLMGFOGCDMD_data_.IOIMHJAOKOO_Hash = MLMGFOGCDMD_readData_.PAPMBEBHHIG/*_Hash*/;
			MLMGFOGCDMD_list_.Add(MLMGFOGCDMD_data_);
		}
		res_data_.MLMGFOGCDMD = MLMGFOGCDMD_list_.ToArray();

		return res_data_;
	}
}
